<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Bretton Woods and Related Agreements Act</a><ul class="TocIndent"><li><a href="#h-31269"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-32045"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="#h-32405"><span class="scheduleLabel">SCHEDULE III</span> <span class="scheduleTitleText"> - (<em>Original</em>)</span></a>
</li>
<li><a href="#h-32681"><span class="scheduleLabel">SCHEDULE IV</span> </a>
</li>
<li><a href="#h-32920"><span class="scheduleLabel">SCHEDULE V</span> <span class="scheduleTitleText"> - Convention Establishing the Multilateral Investment Guarantee Agency</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
