<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les explosifs</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-196913"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-196918"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-196953"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-196958"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-196963"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-197003"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-197042"><span class="HTitleText1">Licences et permis</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-197087"><span class="HTitleText1">Inspecteurs et chimistes</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-197161"><span class="HTitleText1">Enquêtes sur les accidents</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-197172"><span class="HTitleText1">Infractions, peines et procédure</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-197274"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

