<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Student Financial Assistance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Appropriate Authorities</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Agreements with Lenders</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="#h-5"><span class="HTitleText1">Government Financing of Student Loans</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Interest-free and Deferral Periods</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Death or Disability of Borrower</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText1">Certificates of Eligibility</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText1">Maximum Amount of Outstanding Student Loans</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText1">Alternative Payments</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-11"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-12"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>21 to 27 - </span><a href="#h-13"><span class="HTitleText1">Amendments to Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-14"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
