<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Manitoba Supplementary Provisions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-348510"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-348515"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-348526"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>5 to 18 - </span><a href="page-1.html#h-348535"><span class="HLabel1">PART II</span> - <span class="HTitleText1">[Repealed, 1992, c. 1, s. 146 (Sch. IX, item 35)]</span></a>
</li>
<li><span class='sectionRange'>19 to 34 - </span><a href="page-1.html#h-348537"><span class="HLabel1">PART III</span> - <span class="HTitleText1">[Repealed, 1992, c. 1, s. 146 (Sch. IX, item 35)]</span></a>
</li></ul>
</li></ul>

</nav>

