<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Financial Administration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-227967"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-227972"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-228015"><span class="HTitleText1">Alteration of Schedules</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-228078"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Organization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-228079"><span class="HTitleText2">Treasury Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-228080"><span class="HTitleText3">Establishment</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-228092"><span class="HTitleText3">Public Officers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-228122"><span class="HTitleText3">Responsibilities and Powers</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-228219"><span class="HTitleText3">Human Resources Management</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-228322"><span class="HTitleText2">Department of Finance</span></a>
</li></ul>
</li><li><span class='sectionRange'>16.1 - </span><a href="#h-228342"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Internal Audit and Accounting Officers</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-228394"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Public Money</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-228550"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Public Disbursements</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-228742"><span class="HLabel1">PART III.1</span> - <span class="HTitleText1">Contracts</span></a>
</li>
<li><span class='sectionRange'>42.2 - </span><a href="#h-228796"><span class="HLabel1">PART III.2</span> - <span class="HTitleText1">Financial Transactions Related to Asset Management</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-228850"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Public Debt</span></a>
</li>
<li><span class='sectionRange'>60.2 - </span><a href="#h-229029"><span class="HLabel1">PART IV.1</span> - <span class="HTitleText1">Stability and Efficiency of the Financial System</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-229064"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Public Property</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-229076"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Public Accounts</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-229121"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Assignment of Crown Debts</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-229182"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Assignment of Debts Due to the Crown Under Payment Bonds</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-229213"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Civil Liability and Offences</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-229273"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Crown Corporations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="#h-229274"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-229336"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-229370"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Corporate Affairs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-229371"><span class="HTitleText3">Accountability to Parliament</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-229376"><span class="HTitleText3">Directives</span></a>
</li>
<li><span class='sectionRange'>89.2 - </span><a href="#h-229406"><span class="HTitleText3">Implementation of World Trade Organization Agreement</span></a>
</li>
<li><span class='sectionRange'>89.3 - </span><a href="#h-229416"><span class="HTitleText3">Implementation of Canadian Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>89.4 - </span><a href="#h-229421"><span class="HTitleText3">Implementation of Canada-Chile Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>89.41 - </span><a href="#h-229431"><span class="HTitleText3">Implementation of Canada–Colombia Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>89.5 - </span><a href="#h-229441"><span class="HTitleText3">Implementation of Canada — Costa Rica Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>89.6 - </span><a href="#h-229451"><span class="HTitleText3">Implementation of Canada–Peru Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>89.7 - </span><a href="#h-229461"><span class="HTitleText3">Implementation of Other Free Trade Agreements</span></a>
</li>
<li><span class='sectionRange'>89.8 - </span><a href="#h-229469"><span class="HTitleText3">Orders — Terms and Conditions of Employment</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-229499"><span class="HTitleText3">Restricted Transactions</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-229597"><span class="HTitleText3">Crown Agency Status</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-229648"><span class="HTitleText3">Third Parties</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-229670"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>104.1 - </span><a href="#h-229679"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Directors and Officers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104.1 - </span><a href="#h-229680"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-229685"><span class="HTitleText3">Appointment</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-229714"><span class="HTitleText3">Resignation</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-229722"><span class="HTitleText3">Remuneration</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-229736"><span class="HTitleText3">Management</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-229779"><span class="HTitleText3">By-laws</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-229799"><span class="HTitleText3">Duties</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-229861"><span class="HTitleText3">Indemnification</span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="#h-229883"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Financial Management and Control</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-229884"><span class="HTitleText3">Definitions</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-229893"><span class="HTitleText3">Financial Year</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-229901"><span class="HTitleText3">Corporate Plans and Budgets</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-229981"><span class="HTitleText3">Borrowing</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-230000"><span class="HTitleText3">Bank Accounts</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-230015"><span class="HTitleText3">Surpluses</span></a>
</li>
<li><span class='sectionRange'>130.1 - </span><a href="#h-230020"><span class="HTitleText3">Dividends</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-230029"><span class="HTitleText3">Financial Management</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-230065"><span class="HTitleText3">Auditor’s Reports</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-230101"><span class="HTitleText3">Auditors</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-230140"><span class="HTitleText3">Special Examination</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-230189"><span class="HTitleText3">Consultation with Auditor General</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-230194"><span class="HTitleText3">Right to Information</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-230209"><span class="HTitleText3">Policy</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-230217"><span class="HTitleText3">Qualified Privilege</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-230222"><span class="HTitleText3">Costs</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-230230"><span class="HTitleText3">Audit Committee</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-230253"><span class="HTitleText3">Reports</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-230294"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-230295"><span class="HTitleText3">Commercially Detrimental Information</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-230307"><span class="HTitleText3">Sanction</span></a>
</li>
<li><span class='sectionRange'>154.01 - </span><a href="#h-230312"><span class="HTitleText3">Offence</span></a>
</li></ul>
</li><li><span class='sectionRange'>154.1 - </span><a href="#h-230322"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">Implementation of the North American Free Trade Agreement</span></a>
</li></ul>
</li><li><span class='sectionRange'>155 - </span><a href="#h-230332"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Miscellaneous</span></a>
</li>
<li><a href="#h-230472"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-230498"><span class="scheduleLabel">SCHEDULE I.1</span> </a>
</li>
<li><a href="#h-230507"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="#h-230530"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li>
<li><a href="#h-230578"><span class="scheduleLabel">SCHEDULE IV</span> <span class="scheduleTitleText"> - Portions of the Core Public Administration</span></a>
</li>
<li><a href="#h-230641"><span class="scheduleLabel">SCHEDULE V</span> <span class="scheduleTitleText"> - Separate Agencies</span></a>
</li>
<li><a href="#h-230672"><span class="scheduleLabel">SCHEDULE VI</span> </a>
</li>
<li><a href="#h-82"><span class="scheduleLabel">SCHEDULE VII</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
