<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Commercial Arbitration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-87531"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-87534"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-87552"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-87569"><span class="HTitleText1">Courts</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-87574"><span class="HTitleText1">Publication</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-87577"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-87584"><span class="HTitleText1">Her Majesty is Bound</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-87587"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-87591"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Commercial Arbitration Code</span></a>
</li>
<li><a href="#h-87807"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

