<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2002 sur l’accord fiscal Canada — Koweït</a><ul class="TocIndent"><li><a href="#h-144747"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Accord entre le gouvernement du Canada et le gouvernement de l’État du Koweït en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
