<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le système correctionnel et la mise en liberté sous condition</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-102929"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-102932"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Système correctionnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-102933"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-102982"><span class="HTitleText2">Objet et principes</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-103002"><span class="HTitleText2">Service correctionnel du Canada</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-103036"><span class="HTitleText2">Écrou</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-103063"><span class="HTitleText2">Plan correctionnel</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-103082"><span class="HTitleText2">Accord d’échange de services</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-103094"><span class="HTitleText2">Permission de sortir avec escorte</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-103135"><span class="HTitleText2">Placement à l’extérieur</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-103155"><span class="HTitleText2">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-103169"><span class="HTitleText2">Indemnité de décès et d’invalidité</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-103172"><span class="HTitleText2">Renseignements</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-103272"><span class="HTitleText2">Incarcération et transfèrement des détenus</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-103284"><span class="HTitleText2">Cote de sécurité</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-103296"><span class="HTitleText2">Isolement préventif</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-103334"><span class="HTitleText2">Régime disciplinaire</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-103394"><span class="HTitleText2">Infractions punissables par procédure sommaire</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-103402"><span class="HTitleText2">Fouilles et saisies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-103403"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-103414"><span class="HTitleText3">Fouille des détenus</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-103479"><span class="HTitleText3">Fouille de cellules</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-103482"><span class="HTitleText3">Fouille des visiteurs</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-103498"><span class="HTitleText3">Fouille de véhicules</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-103512"><span class="HTitleText3">Avertissements</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-103515"><span class="HTitleText3">Fouille des agents</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-103525"><span class="HTitleText3">Saisie</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-103533"><span class="HTitleText3">Fouilles dans les établissements résidentiels communautaires</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-103543"><span class="HTitleText3">Rapports de fouilles et de saisies</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-103548"><span class="HTitleText2">Conditions de détention</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-103576"><span class="HTitleText2">Programmes pour les délinquants</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-103590"><span class="HTitleText2">Autochtones</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-103625"><span class="HTitleText2">Services de santé</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-103655"><span class="HTitleText2">Griefs ou plaintes</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-103673"><span class="HTitleText2">Mise en liberté des détenus</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-103689"><span class="HTitleText2">Hébergement temporaire</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-103699"><span class="HTitleText2">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-103702"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-103757"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-103763"><span class="HTitleText2">Directives du commissaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-103769"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Mise en liberté sous condition, maintien en incarcération et surveillance de longue durée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-103770"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-103817"><span class="HTitleText2">Objet et principes</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-103837"><span class="HTitleText2">Commission des libérations conditionnelles du Canada</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-103900"><span class="HTitleText2">Commissions provinciales des libérations conditionnelles</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-103926"><span class="HTitleText2">Permission de sortir sans escorte</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-103986"><span class="HTitleText2">Admissibilité à la libération conditionnelle</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-104069"><span class="HTitleText2">Examen des dossiers de libération conditionnelle</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-104146"><span class="HTitleText2">Libération d’office</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-104178"><span class="HTitleText2">Conséquences de la libération conditionnelle ou d’office et permission de sortir sans escorte</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-104196"><span class="HTitleText2">Maintien en incarcération au cours de la période prévue pour la libération d’office</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-104362"><span class="HTitleText2">Conditions de la mise en liberté</span></a>
</li>
<li><span class='sectionRange'>134.1 - </span><a href="#h-104403"><span class="HTitleText2">Conditions de la surveillance de longue durée</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-104429"><span class="HTitleText2">Suspension, cessation, révocation et ineffectivité de la libération conditionnelle ou d’office ou de la surveillance de longue durée</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-104560"><span class="HTitleText2">Fusion de peines</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-104568"><span class="HTitleText2">Audiences</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-104634"><span class="HTitleText2">Communication de l’information</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-104684"><span class="HTitleText2">Dossiers</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-104713"><span class="HTitleText2">Révision judiciaire</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-104716"><span class="HTitleText2">Organisation de la Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="#h-104717"><span class="HTitleText3">Section d’appel</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-104727"><span class="HTitleText3">Appel auprès de la Section d’appel</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-104754"><span class="HTitleText3">Siège et bureaux régionaux</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-104772"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="#h-104862"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="#h-104879"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Enquêteur correctionnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-104880"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-104898"><span class="HTitleText2">Enquêteur correctionnel</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-104923"><span class="HTitleText2">Gestion</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-104926"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-104932"><span class="HTitleText2">Serment professionnel</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-104935"><span class="HTitleText2">Attributions</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-104950"><span class="HTitleText2">Programme d’information</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-104953"><span class="HTitleText2">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-104989"><span class="HTitleText2">Conclusions, rapports et recommandations</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-105034"><span class="HTitleText2">Confidentialité</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-105058"><span class="HTitleText2">Délégation</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-105068"><span class="HTitleText2">Cadre législatif</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-105076"><span class="HTitleText2">Procédures</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-105087"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-105093"><span class="HTitleText2">Rapports au Parlement</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-105102"><span class="HTitleText2">Documents confidentiels du Conseil privé</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-105119"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-105122"><span class="HTitleText2">Sa Majesté</span></a>
</li></ul>
</li><li><span class='sectionRange'>199 à 203 - </span><a href="#h-105125"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Modifications connexes et corrélatives, abrogations, dispositions transitoires et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 à 203 - </span><a href="#h-105126"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>205 à 207 - </span><a href="#h-105129"><span class="HTitleText2">Loi sur les prisons et les maisons de correction</span></a>
</li>
<li><span class='sectionRange'>208 à 211 - </span><a href="#h-105131"><span class="HTitleText2">Loi sur le transfèrement des délinquants</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-105133"><span class="HTitleText2">Loi sur le ministère du Solliciteur général</span></a>
</li>
<li><span class='sectionRange'>213 et 214 - </span><a href="#h-105135"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>215 et 216 - </span><a href="#h-105137"><span class="HTitleText2">Mentions</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-105139"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-105207"><span class="HTitleText2">Examen des dispositions sur le maintien de l’incarcération</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-105213"><span class="HTitleText2">Examen détaillé de la loi</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-105219"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-96"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-105352"><span class="scheduleLabel">ANNEXE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
