<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Corps féminin de la Marine royale et le South African Military Nursing Service (Service sud-africain d’infirmières militaires) [Prestations]</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-454150"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-454155"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-454163"><span class="HTitleText1">Prestations de service de guerre</span></a>
</li></ul>
</li></ul>

</nav>

