<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi maritime du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Droits des autochtones</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Politique maritime nationale</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Administrations portuaires canadiennes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Mandataire de Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Prorogation des commissions portuaires</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Administrations portuaires initiales</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText2">Administrateurs</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Régime juridique applicable aux administrations portuaires</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-14"><span class="HTitleText2">Capacité et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-15"><span class="HTitleText2">Réunion annuelle</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-16"><span class="HTitleText2">Gestion financière</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText2">Examens spéciaux</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-18"><span class="HTitleText2">Biens</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-19"><span class="HTitleText2">Droits</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-20"><span class="HTitleText2">Langues officielles</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-21"><span class="HTitleText2">Liquidation et dissolution</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-22"><span class="HTitleText2">Service de circulation portuaire</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-23"><span class="HTitleText2">Maintien de l’ordre et de la sécurité des personnes et des biens</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-24"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-25"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Ports publics</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-26"><span class="HTitleText2">Désignation par le gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-27"><span class="HTitleText2">Droits</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-28"><span class="HTitleText2">Directeurs de port et gardiens de quai</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-29"><span class="HTitleText2">Ententes</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-30"><span class="HTitleText2">Immeubles fédéraux et biens réels fédéraux</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-31"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-32"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-33"><span class="HTitleText2">Contrôle de la circulation</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-34"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Voie maritime</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-35"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-36"><span class="HTitleText2">Objectifs</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-37"><span class="HTitleText2">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-38"><span class="HTitleText2">Assemblée annuelle publique</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-39"><span class="HTitleText2">Gestion financière</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-40"><span class="HTitleText2">Examens spéciaux</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-41"><span class="HTitleText2">Biens</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-42"><span class="HTitleText2">Droits</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-43"><span class="HTitleText2">Loi sur les langues officielles</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-44"><span class="HTitleText2">Dissolution</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-45"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-46"><span class="HTitleText2">Contrôle de la circulation</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-47"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-48"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Règlements et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="#h-49"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-50"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-51"><span class="HTitleText2">Contrôle de la circulation</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-52"><span class="HTitleText2">Paiement des droits</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-53"><span class="HTitleText2">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-54"><span class="HTitleText3">Désignation</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-55"><span class="HTitleText3">Inspection</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-56"><span class="HTitleText3">Perquisitions et saisies</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-57"><span class="HTitleText3">Rétention de navires</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="#h-58"><span class="HTitleText2">Autres pouvoirs</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-59"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-60"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Ressources humaines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-61"><span class="HTitleText2">Voie maritime</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-62"><span class="HTitleText2">Sociétés de port locales</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-63"><span class="HTitleText2">Commissions portuaires</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-64"><span class="HTitleText2">Ports non autonomes de la Société canadienne des ports</span></a>
</li>
<li><span class='sectionRange'>138.1 - </span><a href="#h-65"><span class="HTitleText2">Régimes de prestations comparables</span></a>
</li></ul>
</li><li><span class='sectionRange'>139 - </span><a href="#h-66"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>145 à 158 - </span><a href="#h-67"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Modifications de la Loi sur le pilotage</span></a>
</li>
<li><span class='sectionRange'>159 à 196 - </span><a href="#h-68"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Modifications corrélatives, abrogations et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 à 196 - </span><a href="#h-69"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>197 à 204.1 - </span><a href="#h-70"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-71"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-72"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
