<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le Service canadien du renseignement de sécurité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-74307"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-74312"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-74339"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Service canadien du renseignement de sécurité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-74340"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-74350"><span class="HTitleText2">Directeur</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-74371"><span class="HTitleText2">Gestion</span></a>
</li>
<li><span class='sectionRange'>11.01 - </span><a href="page-2.html#h-74434"><span class="HTitleText2">Fonctions du Service</span></a>
</li>
<li><span class='sectionRange'>20.2 - </span><a href="page-6.html#h-1180214"><span class="HTitleText2">Rapport au Parlement</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="page-6.html#h-74580"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-7.html#h-74719"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">[Abrogée, 2019, ch. 13, art. 22]</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-7.html#h-74905"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">[Abrogée, 2019, ch. 13, art. 22]</span></a>
</li>
<li><a href="page-8.html#h-74914"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

