<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-37122"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-37125"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments Related to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-37126"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-37155"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-37163"><span class="HTitleText2">Canada Education Savings Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-37165"><span class="HTitleText2">Canada Education Savings Regulations</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-37167"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-37172"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the Excise Tax Act (Other than with Respect to the Goods and Services Tax/Harmonized Sales Tax)</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-37175"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments in Respect of the Goods and Services Tax/Harmonized Sales Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-37176"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-37185"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-37187"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Other Measures Relating to Taxation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-37188"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-37190"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-37195"><span class="HTitleText2">Payments to Ontario</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-37200"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Tax-back Guarantee Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-37203"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Federal-Provincial Fiscal Arrangements Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="#h-37204"><span class="HTitleText2">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-37219"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-37223"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-37224"><span class="HTitleText3">Canada-Newfoundland Atlantic Accord Implementation Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-37228"><span class="HTitleText3">Nova Scotia and Newfoundland and Labrador Additional Fiscal Equalization Offset Payments Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-37232"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-37242"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Amendments to the Financial Administration Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="#h-37243"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-37248"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-37251"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Amendments to the Canada Mortgage and Housing Corporation Act</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-37253"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Amendments Relating to Eligible Financial Contracts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-37254"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-37267"><span class="HTitleText2">Canada Deposit Insurance Corporation Act</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-37269"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-37276"><span class="HTitleText2">Payment Clearing and Settlement Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-37280"><span class="HTitleText2">Winding-up and Restructuring Act</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-37285"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-37291"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-37293"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-37296"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Payments to Provinces and Territories</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-37297"><span class="HTitleText2">Payment to British Columbia</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-37300"><span class="HTitleText2">Clean Air and Climate Change Trust Fund</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-37308"><span class="HTitleText2">Transitional Payments</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-37319"><span class="HTitleText2">Human Papillomavirus Immunization</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-37327"><span class="HTitleText2">Patient Wait Times Guarantee</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-37335"><span class="HTitleText2">Child Care Spaces</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-37346"><span class="HTitleText2">Payment to Yukon</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-37349"><span class="HTitleText2">Payment to Northwest Territories</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-37352"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Payments to Certain Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-37353"><span class="HTitleText2">Nature Conservancy of Canada</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-37356"><span class="HTitleText2">Canada Health Infoway Inc.</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-37359"><span class="HTitleText2">CANARIE Inc.</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-37362"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-37365"><span class="HTitleText2">Aid to Afghanistan</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-37380"><span class="HTitleText2">Rick Hansen Man in Motion Foundation</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-37383"><span class="HTitleText2">The Perimeter Institute for Theoretical Physics</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-37386"><span class="HTitleText2">Canada Foundation for Sustainable Development Technology</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-37395"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Amendments Relating to Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="#h-37396"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-37399"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-37401"><span class="HTitleText2">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-37404"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-37406"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-37408"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Amendments to the Department of Public Works and Government Services Act</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-37412"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Amendment to the Financial Consumer Agency of Canada Act</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
