<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Defence Production Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-171746"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-171751"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-171781"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Procurement of Defence Supplies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-171782"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-171824"><span class="HTitleText2">Powers and Duties of the Minister</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-171840"><span class="HTitleText2">Organization of Industry for Defence</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-171862"><span class="HTitleText2">Defence Procurement</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-171957"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-2.html#h-171983"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Regulation of Access to Controlled Goods</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-2.html#h-171984"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-2.html#h-171989"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-171996"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-172008"><span class="HTitleText2">Registration</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-172020"><span class="HTitleText2">Exemption</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-172036"><span class="HTitleText2">Report</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-172041"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-3.html#h-172062"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-3.html#h-172078"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><a href="page-4.html#h-172110"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Controlled Goods List</span></a>
</li></ul>
</li></ul>

</nav>

