<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Hazardous Materials Information Review Act</a><ul class="TocIndent"><li><span class='sectionRange'>9 - </span><a href="#h-252440"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-252445"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-252480"><span class="HTitleText1">Review of Confidential Business Information</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-252607"><span class="HTitleText1">Exemption</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-252617"><span class="HTitleText1">Appeals</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-252699"><span class="HTitleText1">Council</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-252726"><span class="HTitleText1">Appeal Boards</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-252761"><span class="HTitleText1">Superannuation</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-252766"><span class="HTitleText1">Confidentiality of Information</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-252790"><span class="HTitleText1">Powers of the Minister</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-252800"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-252816"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-252828"><span class="HTitleText1">Liability</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
