<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Perfluorooctane Sulfonate Virtual Elimination Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-416858"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-416861"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-416864"><span class="HTitleText1">Addition to the List</span></a>
</li></ul>
</li></ul>

</nav>

