<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-393376"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-393379"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-393413"><span class="HTitleText1">Modification des annexes</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-393421"><span class="HTitleText1">Sensibilisation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-393426"><span class="HTitleText1">Code de conduite</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-393448"><span class="HTitleText1">Actes répréhensibles</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-393462"><span class="HTitleText1">Divulgation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-393522"><span class="HTitleText1">Plaintes en matière de représailles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-393523"><span class="HTitleText2">Interdiction — représailles</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="#h-393528"><span class="HTitleText2">Plaintes</span></a>
</li>
<li><span class='sectionRange'>19.5 - </span><a href="#h-393581"><span class="HTitleText2">Sanctions disciplinaires</span></a>
</li>
<li><span class='sectionRange'>19.7 - </span><a href="#h-393619"><span class="HTitleText2">Enquêtes relatives aux plaintes</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-393641"><span class="HTitleText2">Conciliation</span></a>
</li>
<li><span class='sectionRange'>20.3 - </span><a href="#h-393671"><span class="HTitleText2">Décision suivant l’enquête</span></a>
</li>
<li><span class='sectionRange'>20.7 - </span><a href="#h-393705"><span class="HTitleText2">Tribunal de la protection des fonctionnaires divulgateurs d’actes répréhensibles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20.7 - </span><a href="#h-393706"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>20.8 - </span><a href="#h-393730"><span class="HTitleText3">Administration</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-393736"><span class="HTitleText3">Procédures</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-393756"><span class="HTitleText3">Demandes du commissaire</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-393867"><span class="HTitleText1">Attributions du commissaire</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-393956"><span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-394012"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-394070"><span class="HTitleText1">Commissariat à l’intégrité du secteur public</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-394071"><span class="HTitleText2">Commissaire à l’intégrité du secteur public</span></a>
</li>
<li><span class='sectionRange'>39.3 - </span><a href="#h-394097"><span class="HTitleText2">Personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-394109"><span class="HTitleText1">Interdictions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-394110"><span class="HTitleText2">Interdictions générales</span></a>
</li>
<li><span class='sectionRange'>42.1 - </span><a href="#h-394123"><span class="HTitleText2">Employeurs</span></a>
</li>
<li><span class='sectionRange'>42.2 - </span><a href="#h-394138"><span class="HTitleText2">Contrats</span></a>
</li></ul>
</li><li><span class='sectionRange'>42.3 - </span><a href="#h-394148"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-394155"><span class="HTitleText1">Caractère confidentiel</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-394162"><span class="HTitleText1">Immunité</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-394178"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-394245"><span class="HTitleText1">Organismes exclus</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-394250"><span class="HTitleText1">Examen quinquennal</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="#h-394255"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-394260"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-394261"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-394264"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>56.1 - </span><a href="#h-394266"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>56.2 - </span><a href="#h-394268"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>56.5 - </span><a href="#h-394272"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-394274"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels et les documents électroniques</cite></span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-394276"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-394279"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-394283"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-47"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-394303"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-49"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
