<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
International Boundary Waters Treaty Act</a><ul class="TocIndent"><li><span class='sectionRange'>10 - </span><a href="#h-1"><span class="HTitleText1">Licences and Prohibitions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-2"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HTitleText2">Prohibition</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-8"><span class="HTitleText2">Aboriginal and Treaty Rights</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText2">Injunctions</span></a>
</li></ul>
</li><li><a href="#h-11"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
