<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Antarctic Environmental Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-3591"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-3594"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3628"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3631"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3637"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-3712"><span class="HTitleText1">Permits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-3713"><span class="HTitleText2">Issuance</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-3734"><span class="HTitleText2">Environmental Impact Assessments</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-3744"><span class="HTitleText2">Waste Management Plans and Emergency Plans</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-3747"><span class="HTitleText2">Security</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-2.html#h-3753"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-3793"><span class="HTitleText1">Enforcement in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-2.html#h-3794"><span class="HTitleText2">Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-3808"><span class="HTitleText2">Inspections in Canada</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-3869"><span class="HTitleText2">Search and Seizure in Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-3917"><span class="HTitleText2">Detention in Canada</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-3958"><span class="HTitleText2">Detention of Vessels</span></a>
</li>
<li><span class='sectionRange'>37.01 - </span><a href="page-3.html#h-3983"><span class="HTitleText2">Direction of Vessels</span></a>
</li>
<li><span class='sectionRange'>37.02 - </span><a href="page-3.html#h-3990"><span class="HTitleText2">Environmental Protection Compliance Orders</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-4119"><span class="HTitleText2">Assistance to Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-4126"><span class="HTitleText2">Forfeiture in Canada</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="page-5.html#h-4166"><span class="HTitleText2">Liability for Costs</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-5.html#h-4171"><span class="HTitleText1">Inspections in the Antarctic</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-4213"><span class="HTitleText1">Obstruction and False Information</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-7.html#h-4553"><span class="HTitleText1">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-4575"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

