<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Health Events of National Concern Payments Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1241142"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1241145"><span class="HTitleText1">Public Health Event of National Concern</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
