<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Department of Canadian Heritage Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-69701"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-69704"><span class="HTitleText1">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-69712"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-69739"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-69742"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-69773"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>16 to 42 - </span><a href="page-1.html#h-69800"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>43 to 45 - </span><a href="page-1.html#h-69802"><span class="HTitleText1">References</span></a>
</li>
<li><span class='sectionRange'>48 and 49 - </span><a href="page-1.html#h-69808"><span class="HTitleText1">Repeals</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-1.html#h-69810"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

