<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Genetic Non-Discrimination Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-247308"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-247311"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-247317"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-247337"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-247342"><span class="HTitleText1">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-247344"><span class="HTitleText1">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-247347"><span class="HTitleText1">Coordinating Amendments</span></a>
</li></ul>
</li></ul>

</nav>

