<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Agence de développement économique du Canada pour les régions du Québec</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-172091"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-172094"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-172100"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-172103"><span class="HTitleText1">Ministre</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-172133"><span class="HTitleText1">Agence de développement économique du Canada pour les régions du Québec</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-172145"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-172185"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-172195"><span class="HTitleText1">Pouvoir réglementaire</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-172211"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-172221"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-172248"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-172249"><span class="HTitleText2">Loi sur le vérificateur général</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-172251"><span class="HTitleText2">Loi sur le ministère de l’Industrie</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-172256"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-172258"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-172260"><span class="HTitleText2">Loi sur les traitements</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-172262"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-172264"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

