<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Code canadien du travail</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-331098"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-331103"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>Préambule - </span><a href="#h-331120"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Relations du travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-331130"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-331177"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-331199"><span class="HTitleText2">Grands travaux</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-331204"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Libertés fondamentales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-331212"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Conseil canadien des relations industrielles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-331213"><span class="HTitleText3">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-331403"><span class="HTitleText3">Pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-331528"><span class="HTitleText3">Révision et exécution des ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-331555"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Acquisition et extinction des droits de négociation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-331556"><span class="HTitleText3">Demande d’accréditation</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-331591"><span class="HTitleText3">Détermination des unités de négociation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-331609"><span class="HTitleText3">Accréditation des agents négociateurs et questions connexes</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-331732"><span class="HTitleText3">Révocation de l’accréditation et questions connexes</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-331788"><span class="HTitleText3">Droits et obligations du successeur</span></a>
</li>
<li><span class='sectionRange'>47.3 - </span><a href="#h-331867"><span class="HTitleText3">Contrats successifs de fourniture de services</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-331877"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Négociations collectives et conventions collectives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-331878"><span class="HTitleText3">Obligation de négocier collectivement</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-331898"><span class="HTitleText3">Changement technologique</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-331969"><span class="HTitleText3">Contenu et interprétation des conventions collectives</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-332096"><span class="HTitleText3">Précompte obligatoire des cotisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>70.1 - </span><a href="#h-332113"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Conciliation et première convention</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70.1 - </span><a href="#h-332114"><span class="HTitleText3">Service fédéral de médiation et de conciliation</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-332122"><span class="HTitleText3">Procédures de conciliation</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-332195"><span class="HTitleText3">Première convention collective</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-332210"><span class="HTitleText3">Constitution des commissions de conciliation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-332233"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>87.1 - </span><a href="#h-332263"><span class="HLabel2">SECTION V.1</span> - <span class="HTitleText2">Obligations en matière de grèves et de lock-out</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-332340"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Interdictions et recours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-332341"><span class="HTitleText3">Grèves et lock-out</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-332384"><span class="HTitleText3">Déclarations relatives aux grèves et lock-out</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-332414"><span class="HTitleText3">Pratiques déloyales</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-332530"><span class="HTitleText3">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>104.1 - </span><a href="#h-332570"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104.1 - </span><a href="#h-332571"><span class="HTitleText3">Règlement pacifique des conflits de travail</span></a>
</li>
<li><span class='sectionRange'>108.1 - </span><a href="#h-332612"><span class="HTitleText3">Scrutin sur les offres de l’employeur</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-332626"><span class="HTitleText3">Accès aux employés</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-332651"><span class="HTitleText3">Communication des états financiers</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-332663"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-332683"><span class="HTitleText3">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-332728"><span class="HTitleText3">Accords avec les provinces</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-332742"><span class="HTitleText3">Rapports annuels</span></a>
</li>
<li><span class='sectionRange'>121.1 - </span><a href="#h-332749"><span class="HTitleText3">Application de lois provinciales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="#h-332798"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Santé et sécurité au travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-332799"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>122.1 - </span><a href="#h-332829"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>122.3 - </span><a href="#h-332838"><span class="HTitleText2">Modes de communication</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-332846"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-332860"><span class="HTitleText2">Obligations des employeurs</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-332962"><span class="HTitleText2">Obligations des employés</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-332982"><span class="HTitleText2">Sécurité au travail</span></a>
</li>
<li><span class='sectionRange'>127.1 - </span><a href="#h-332995"><span class="HTitleText2">Processus de règlement interne des plaintes</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-333137"><span class="HTitleText2">Employées enceintes ou allaitantes</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-333151"><span class="HTitleText2">Plaintes découlant de mesures disciplinaires</span></a>
</li>
<li><span class='sectionRange'>134.1 - </span><a href="#h-333175"><span class="HTitleText2">Comités d’orientation en matière de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-333203"><span class="HTitleText2">Comités locaux de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-333249"><span class="HTitleText2">Règles communes aux comités d’orientation et aux comités locaux</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-333304"><span class="HTitleText2">Représentants en matière de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>137.1 - </span><a href="#h-333355"><span class="HTitleText2">Commission de la sécurité dans les mines de charbon</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-333396"><span class="HTitleText2">Exécution</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-333421"><span class="HTitleText2">Exercice des pouvoirs du ministre en matière de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-333473"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-333517"><span class="HTitleText2">Mesures spéciales de sécurité</span></a>
</li>
<li><span class='sectionRange'>145.1 - </span><a href="#h-333551"><span class="HTitleText2">Appel des décisions et instructions</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-333607"><span class="HTitleText2">Mesures disciplinaires</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-333622"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-333676"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-333686"><span class="HTitleText2">Ordonnances, décisions et instructions du Conseil</span></a>
</li>
<li><span class='sectionRange'>156.1 - </span><a href="#h-333696"><span class="HTitleText2">Facturation</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-333704"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-333744"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Durée normale du travail, salaire, congés et jours fériés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-333745"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-333766"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-333792"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Durée du travail</span></a>
</li>
<li><span class='sectionRange'>177.1 - </span><a href="#h-1187276"><span class="HLabel2">SECTION I.1</span> - <span class="HTitleText2">Assouplissement des conditions d’emploi</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-333913"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Salaire minimum</span></a>
</li>
<li><span class='sectionRange'>181.1 - </span><a href="#h-1187512"><span class="HLabel2">SECTION II.1</span> - <span class="HTitleText2">Pauses pour raisons médicales ou allaitement</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-333949"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Égalité des salaires</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-333957"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Congés annuels</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-334009"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Jours fériés</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-334093"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Employeurs multiples</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-334105"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Réaffectation et congé liés à la maternité et congés divers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="#h-334106"><span class="HTitleText3">Réaffectation et congé liés à la maternité</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-334137"><span class="HTitleText3">Congé de maternité</span></a>
</li>
<li><span class='sectionRange'>206.1 - </span><a href="#h-334149"><span class="HTitleText3">Congé parental</span></a>
</li>
<li><span class='sectionRange'>206.3 - </span><a href="#h-334181"><span class="HTitleText3">Congé de soignant</span></a>
</li>
<li><span class='sectionRange'>206.4 - </span><a href="#h-334218"><span class="HTitleText3">Congé en cas de maladie grave</span></a>
</li>
<li><span class='sectionRange'>206.5 - </span><a href="#h-334250"><span class="HTitleText3">Congé en cas de décès ou de disparition</span></a>
</li>
<li><span class='sectionRange'>206.6 - </span><a href="#h-1187364"><span class="HTitleText3">Congé personnel</span></a>
</li>
<li><span class='sectionRange'>206.7 - </span><a href="#h-1187388"><span class="HTitleText3">Congé pour les victimes de violence familiale</span></a>
</li>
<li><span class='sectionRange'>206.8 - </span><a href="#h-1187413"><span class="HTitleText3">Congé pour pratiques autochtones traditionnelles</span></a>
</li>
<li><span class='sectionRange'>206.9 - </span><a href="#h-1187626"><span class="HTitleText3">Congé pour fonctions judiciaires</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-334279"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>210 - </span><a href="#h-334423"><span class="HLabel2">SECTION VIII</span> - <span class="HTitleText2">Congés de décès</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-334438"><span class="HLabel2">SECTION IX</span> - <span class="HTitleText2">Licenciements collectifs</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-334618"><span class="HLabel2">SECTION X</span> - <span class="HTitleText2">Licenciements individuels</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-334653"><span class="HLabel2">SECTION XI</span> - <span class="HTitleText2">Indemnité de départ</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-334677"><span class="HLabel2">SECTION XII</span> - <span class="HTitleText2">Saisie-arrêt</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-334682"><span class="HLabel2">SECTION XIII</span> - <span class="HTitleText2">Congé pour raisons médicales</span></a>
</li>
<li><span class='sectionRange'>239.01 - </span><a href="#h-1249869"><span class="HLabel2">SECTION XIII.01</span> - <span class="HTitleText2">Congé lié à la COVID-19</span></a>
</li>
<li><span class='sectionRange'>239.1 - </span><a href="#h-334708"><span class="HLabel2">SECTION XIII.1</span> - <span class="HTitleText2">Accidents et maladies professionnels</span></a>
</li>
<li><span class='sectionRange'>239.2 - </span><a href="#h-334737"><span class="HLabel2">SECTION XIII.2</span> - <span class="HTitleText2">Régimes d’invalidité de longue durée</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-334751"><span class="HLabel2">SECTION XIV</span> - <span class="HTitleText2">Congédiement injuste</span></a>
</li>
<li><span class='sectionRange'>246.1 - </span><a href="#h-1178698"><span class="HLabel2">SECTION XIV.1</span> - <span class="HTitleText2">Plainte pour représailles</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-334822"><span class="HLabel2">SECTION XV</span> - <span class="HTitleText2">Paiement du salaire</span></a>
</li>
<li><span class='sectionRange'>247.1 - </span><a href="#h-334829"><span class="HLabel2">SECTION XV.1</span> - <span class="HTitleText2">Harcèlement sexuel</span></a>
</li>
<li><span class='sectionRange'>247.5 - </span><a href="#h-334860"><span class="HLabel2">SECTION XV.2</span> - <span class="HTitleText2">Congé pour les membres de la force de réserve</span></a>
</li>
<li><span class='sectionRange'>247.98 - </span><a href="#h-334969"><span class="HLabel2">SECTION XV.3</span> - <span class="HTitleText2">Tests génétiques</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-335020"><span class="HLabel2">SECTION XVI</span> - <span class="HTitleText2">Application et dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>248 - </span><a href="#h-335021"><span class="HTitleText3">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-335031"><span class="HTitleText3">Inspections</span></a>
</li>
<li><span class='sectionRange'>251.001 - </span><a href="#h-1108027"><span class="HTitleText3">Vérification interne</span></a>
</li>
<li><span class='sectionRange'>251.01 - </span><a href="#h-335074"><span class="HTitleText3">Plaintes</span></a>
</li>
<li><span class='sectionRange'>251.1 - </span><a href="#h-335145"><span class="HTitleText3">Recouvrement du salaire</span></a>
</li>
<li><span class='sectionRange'>251.101 - </span><a href="#h-1108071"><span class="HTitleText3">Ordres de l’inspecteur — Révision et appel</span></a>
</li>
<li><span class='sectionRange'>251.13 - </span><a href="#h-1108094"><span class="HTitleText3">Ordres — Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-335259"><span class="HTitleText3">Renseignements et déclarations</span></a>
</li>
<li><span class='sectionRange'>254.1 - </span><a href="#h-335296"><span class="HTitleText3">Retenues</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-335315"><span class="HTitleText3">Fusion d’entreprises fédérales</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-335323"><span class="HTitleText3">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-335391"><span class="HTitleText3">Arrêtés ministériels</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-335396"><span class="HTitleText3">Projets pilotes</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-335405"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-335428"><span class="HTitleText3">Application de lois provinciales</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
