<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Grain Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Canadian Grain Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Constitution of the Commission and Commissioners</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-6"><span class="HTitleText2">Head Office, Meetings and Hearings</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText2">By-laws</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">Objects of the Commission</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText2">Functions of the Commission</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Grain Grades, Grading and Inspection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-12"><span class="HTitleText2">Grain Grades</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Grain Standards Committees</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText2">Primary Standard Samples and Export Standard Samples</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText2">Inspection of Grain</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText2">Grain Appeal Tribunals</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText2">Appeals of Grain Grades</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Licences and Licensees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-19"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-20"><span class="HTitleText2">Charges by Licensees</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="#h-21"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Elevators and Grain Dealers and the Handling of Grain by Licensees and Other Persons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-22"><span class="HTitleText2">Declaration</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-23"><span class="HTitleText2">Elevators Generally</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-24"><span class="HTitleText2">Primary Elevators</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-25"><span class="HTitleText2">Terminal Elevators and Transfer Elevators</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-26"><span class="HTitleText2">Process Elevators</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-27"><span class="HTitleText2">Weigh-overs at Elevators</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-28"><span class="HTitleText2">Grain Dealers</span></a>
</li>
<li><span class='sectionRange'>82.1 - </span><a href="#h-29"><span class="HTitleText2">Grain Receipts</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-30"><span class="HTitleText2">Grain Handling Generally</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-31"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Carriage of Grain</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-32"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-33"><span class="HTitleText2">Producer Railway Cars</span></a>
</li></ul>
</li><li><span class='sectionRange'>87.1 - </span><a href="#h-34"><span class="HLabel1">PART V.1</span> - <span class="HTitleText1">Importation of Grain</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-35"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Enforcement and Enforcement Procedures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-36"><span class="HTitleText2">Inspection and Seizure</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-37"><span class="HTitleText2">Investigations and Arbitration</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-38"><span class="HTitleText2">Orders Respecting Operations or Suspending Licences</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-39"><span class="HTitleText2">Revocation of Licences</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-40"><span class="HTitleText2">Review by Minister</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-41"><span class="HTitleText2">Orders for Payment</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-42"><span class="HTitleText2">Public Hearings</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-43"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-44"><span class="HTitleText2">Enforcement of Orders for Payment</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-45"><span class="HTitleText2">Appeals to Court</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-46"><span class="HTitleText2">Prohibitions, Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-47"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-48"><span class="HTitleText2">Cash Purchase Tickets and Elevator Receipts</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-49"><span class="HTitleText2">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-50"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-51"><span class="HTitleText2">Changes in Grades</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="#h-52"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-243881"><span class="scheduleLabel">SCHEDULES I AND II</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
