<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le mariage civil</a><ul class="TocIndent"><li><span class='sectionRange'>2 - </span><a href="#h-1"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mariage</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-2"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Dissolution du mariage des époux non-résidents</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
