<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Cultural Property Export and Import Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-138693"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-138698"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-138713"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-138718"><span class="HTitleText1">Canadian Cultural Property Export Control List</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-138738"><span class="HTitleText1">Permit Officers</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-138743"><span class="HTitleText1">Expert Examiners</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-138753"><span class="HTitleText1">Export Permits</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-138812"><span class="HTitleText1">General Permits</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-138820"><span class="HTitleText1">Review Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-138821"><span class="HTitleText2">Review Board Established</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-138842"><span class="HTitleText2">Duties</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-138850"><span class="HTitleText2">Head Office and Sittings</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-138858"><span class="HTitleText2">Advisers</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-138867"><span class="HTitleText2">Rules and Procedure</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-138888"><span class="HTitleText2">Review of Applications for Export Permits</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-138928"><span class="HTitleText2">Determination Relating to Income Tax Matters</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-138952"><span class="HTitleText2">Income Tax Certificate</span></a>
</li>
<li><span class='sectionRange'>33.1 - </span><a href="#h-138964"><span class="HTitleText2">Appeals Before the Tax Court of Canada</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-138993"><span class="HTitleText2">Report to Minister</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-138998"><span class="HTitleText1">Financial</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-139015"><span class="HTitleText1">Convention for the Protection of Cultural Property in the Event of Armed Conflict and Its Protocols</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-139048"><span class="HTitleText1">Foreign Cultural Property</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-139076"><span class="HTitleText1">Designation of Cultural Property</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-139081"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-139090"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-139144"><span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-139164"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Article 1 of the Convention for the Protection of Cultural Property in the Event of Armed Conflict Done at the Hague on May 14, 1954</span></a>
</li></ul>
</li></ul>

</nav>

