<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’enregistrement de renseignements sur les délinquants sexuels</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-435419"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-435422"><span class="HTitleText1">Objet et principes</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-435435"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-435461"><span class="HTitleText1">Obligations imposées aux délinquants sexuels</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-435563"><span class="HTitleText1">Devoirs des préposés</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-435689"><span class="HTitleText1">Gestion de renseignements</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-435715"><span class="HTitleText1">Pouvoir de recueillir et de communiquer des renseignements</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-435744"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-435797"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-435802"><span class="HTitleText1">Autorisations, désignations et règlements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-435828"><span class="HTitleText1">Modifications connexes : Code criminel</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-435831"><span class="HTitleText1">Examen et rapport</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-435837"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-435838"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-435840"><span class="HTitleText2">Loi sur le casier judiciaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-435842"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-435844"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

