<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–Namibia Tax Convention Act, 2013</a><ul class="TocIndent"><li><a href="page-2.html#h-151683"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention Between Canada and the Republic of Namibia for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-3.html#h-151958"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>

