<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Government Annuities Improvement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-247907"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-247910"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-247916"><span class="HTitleText1">Increased Rate of Return</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-247934"><span class="HTitleText1">Increased Flexibility</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-247943"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-247950"><span class="HTitleText1">Discontinuance of Sales of Annuities</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-247955"><span class="HTitleText1">Government Annuities Account</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-247963"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-247966"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-247973"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><a href="page-2.html#h-247980"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

