<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Financial Consumer Agency of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Establishment of Agency</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Commissioner of Agency</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Powers, Duties and Functions of the Commissioner</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">Deputy Commissioners</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText1">Exercise of Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-9"><span class="HTitleText1">Staff of Agency</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText1">Conflict of Interest</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText1">Confidentiality</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText1">Assessments</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-15"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-17"><span class="HTitleText2">Determination of Responsibility and Penalty</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-18"><span class="HTitleText2">Appeal to Federal Court</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-19"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-20"><span class="HTitleText2">Rules about Violations</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-21"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-22"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-23"><span class="HTitleText1">No Liability</span></a>
</li>
<li><span class='sectionRange'>33.1 - </span><a href="#h-24"><span class="HTitleText1">Immunities</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-25"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>35 to 140 - </span><a href="#h-26"><span class="HTitleText1">Amendments to Acts in Relation to Financial Institutions</span></a>
</li>
<li><span class='sectionRange'>572 to 583 - </span><a href="#h-27"><span class="HTitleText1">Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>584 to 592 - </span><a href="#h-28"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>593 - </span><a href="#h-29"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-222838"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-222849"><span class="scheduleLabel">SCHEDULES 2 AND 3</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
