<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 1984 sur la Convention Canada-États-Unis en matière d’impôts</a><ul class="TocIndent"><li><a href="page-2.html#h-57738"><span class="scheduleLabel">ANNEXE I</span> - <span class="scheduleTitleText"> - Convention entre le Canada et les États-Unis d’Amérique en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="page-3.html#h-58241"><span class="scheduleLabel">ANNEXE II</span> - <span class="scheduleTitleText"> - Modifiant la Convention entre le Canada et les États-Unis d’Amérique en matière d’impôts sur le revenu et sur la fortune signée à Washington le 26 septembre 1980</span></a>
</li>
<li><a href="page-4.html#h-58314"><span class="scheduleLabel">ANNEXE III</span> - <span class="scheduleTitleText"> - Deuxième protocole</span> - <span class="scheduleTitleText"> - Modifiant la Convention entre le Canada et les États-Unis d’Amérique en matière d’impôts sur le revenu et sur la fortune signée à Washington le 26 septembre 1980 telle que modifiée par le Protocole signé à Ottawa le 14 juin 1983</span></a>
</li>
<li><a href="page-5.html#h-58338"><span class="scheduleLabel">ANNEXE IV</span> <span class="scheduleTitleText"> - Protocole modifiant la Convention entre le Canada et les États-Unis d’Amérique en matière d’impôts sur le revenu et sur la fortune signée à Washington le 26 septembre 1980 et modifiée par les Protocoles signés le 14 juin 1983 et le 28 mars 1984</span></a>
</li>
<li><a href="page-6.html#h-58438"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Protocole modifiant la Convention entre le Canada et les États-Unis d’Amérique en matière d’impôts sur le revenu et sur la fortune signée à Washington le 26 septembre 1980 telle que modifiée par les Protocoles signés le 14 juin 1983, le 28 mars 1984 et le 17 mars 1995</span></a>
</li>
<li><a href="page-7.html#h-58476"><span class="scheduleLabel">ANNEXE VI</span> <span class="scheduleTitleText"> - Protocole modifiant la Convention entre le Canada et les États-Unis d’Amérique en matière d’impôts sur le revenu et sur la fortune, faite à Washington le 26 septembre 1980 et modifiée par les Protocoles faits le 14 juin 1983, le 28 mars 1984, le 17 mars 1995 et le 29 juillet 1997</span></a>
</li></ul>
</li></ul>

</nav>

