<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le réexamen de l’admissibilité aux prestations d’assurance-chômage (pension)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-451081"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-451084"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-451099"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-451122"><span class="HTitleText1">Loi de 1971 sur l’assurance-chômage</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-451125"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

