<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Petroleum Resources Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-166255"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-166258"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-166300"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-166301"><span class="HTitleText2">Manner of Giving Notices</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-166306"><span class="HTitleText2">Application of Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-166309"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-166312"><span class="HTitleText2">Designations and Appointments</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-166331"><span class="HTitleText2">General Rules Respecting Interests</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-166357"><span class="HLabel1">PART II</span> - <span class="HTitleText1">General Rules Relating to Issuance of Interests</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-166358"><span class="HTitleText2">Authority to Issue Interests</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-166368"><span class="HTitleText2">Issuance of Interests in Relation to Crown Reserve Lands</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-166416"><span class="HTitleText2">Benefits Plan</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-166421"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Exploration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-166422"><span class="HTitleText2">Exploration Licences</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-166462"><span class="HTitleText2">Significant Discoveries</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-166486"><span class="HTitleText2">Significant Discovery Licences</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-166513"><span class="HTitleText2">Drilling Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-166532"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-166533"><span class="HTitleText2">Commercial Discoveries</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-166547"><span class="HTitleText2">Development Orders</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-166563"><span class="HTitleText2">Issuance of Production Licences</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-166609"><span class="HTitleText2">Subsurface Storage Licences</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-166615"><span class="HTitleText2">Qualification for Production Licence</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-166620"><span class="HLabel1">PART V</span> - <span class="HTitleText1">[Repealed, 1993, c. 47, s. 3]</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-166621"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Royalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-166622"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-166625"><span class="HTitleText2">Payment of Royalties</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-166637"><span class="HTitleText2">Returns and Retention of Records</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-166652"><span class="HTitleText2">Assessments, Objections and Appeals</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-166695"><span class="HTitleText2">Refunds</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-166698"><span class="HTitleText2">Special Remedies</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-166735"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-166750"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Environmental Studies Research Fund</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-166867"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Transfers, Assignments and Registration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-166868"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-166901"><span class="HTitleText2">Transfer and Assignment</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-166905"><span class="HTitleText2">Registration</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-167020"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-167021"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-167122"><span class="HTitleText2">Arbitration</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-167145"><span class="HTitleText2">Cancellation of Rights</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-167153"><span class="HTitleText2">Hearings and Judicial Review</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-167179"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-167207"><span class="HTitleText2">Report to Parliament</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-167210"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Transitional, Consequential and Commencement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-167211"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>118 to 130 - </span><a href="#h-167294"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-167296"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

