<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Law Commission of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-344657"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-344660"><span class="HTitleText1">Establishment of Commission</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-344663"><span class="HTitleText1">Purpose, Powers and Duties of Commission</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-344692"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-344725"><span class="HTitleText1">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-344733"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-344739"><span class="HTitleText1">Staff</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-344751"><span class="HTitleText1">Advisory Bodies</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-344772"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>26 to 30 - </span><a href="#h-344790"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-344792"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

