<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Pilotage Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Pilotage Authorities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText2">Organization</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-6"><span class="HTitleText1">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HTitleText1">Licences and Certificates</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-8"><span class="HTitleText1">Tariffs</span></a>
</li>
<li><span class='sectionRange'>36.01 - </span><a href="#h-9"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-10"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-11"><span class="HTitleText1">St. Lambert Lock</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-12"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-13"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-14"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><a href="#h-15"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
