<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la monnaie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-138847"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-138852"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-138859"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Monnaie et pièces</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-138860"><span class="HTitleText2">Unité monétaire</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-138869"><span class="HTitleText2">Pièces et billets ayant cours légal</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-138883"><span class="HTitleText2">Pouvoir libératoire</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-138923"><span class="HTitleText2">Fausse monnaie</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-138928"><span class="HTitleText2">Fonte des pièces</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-138936"><span class="HTitleText2">Comptes et contrats</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-138966"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Compte du fonds des changes</span></a>
</li>
<li><a href="#h-139038"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
