<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’accord en matière d’éducation conclu avec la Nation des Anishinabes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-3380"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3383"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3398"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-3430"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-3440"><span class="HTitleText1">Règlements et décrets</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-3443"><span class="HTitleText1">Modification de l’annexe</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-3449"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-3450"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-3452"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-3454"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-3456"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-3460"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Premières nations participantes</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
