<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection de la navigation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-355826"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-355831"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-355849"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-355854"><span class="HTitleText1">Ouvrages</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-356000"><span class="HTitleText1">Obstacles</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-356057"><span class="HTitleText1">Dépôts et assèchement</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-356082"><span class="HTitleText1">Accords et arrangements</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-356100"><span class="HTitleText1">Règlements, arrêtés, incorporation par renvoi et arrêtés d’urgence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-356101"><span class="HTitleText2">Règlements et arrêtés</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-356149"><span class="HTitleText2">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-356162"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-356184"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-356185"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-356190"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-356228"><span class="HTitleText2">Interdiction</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-356236"><span class="HTitleText2">Injonction</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-356246"><span class="HTitleText2">Immunité</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-356254"><span class="HTitleText2">Pénalités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39.1 - </span><a href="#h-356255"><span class="HTitleText3">Violations</span></a>
</li>
<li><span class='sectionRange'>39.11 - </span><a href="#h-356265"><span class="HTitleText3">Ouverture de la procédure</span></a>
</li>
<li><span class='sectionRange'>39.12 - </span><a href="#h-356282"><span class="HTitleText3">Pénalités</span></a>
</li>
<li><span class='sectionRange'>39.13 - </span><a href="#h-356292"><span class="HTitleText3">Contestation devant le Tribunal</span></a>
</li>
<li><span class='sectionRange'>39.14 - </span><a href="#h-356304"><span class="HTitleText3">Recouvrement de créances</span></a>
</li>
<li><span class='sectionRange'>39.16 - </span><a href="#h-356324"><span class="HTitleText3">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>39.22 - </span><a href="#h-356352"><span class="HTitleText3">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-356373"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><a href="#h-356402"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Eaux navigables</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
