<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi confirmant une convention entre le gouvernement du Canada et le gouvernement de la province du Nouveau-Brunswick à l’égard de réserves indiennes</a><ul class="TocIndent"><li><a href="page-2.html#h-355773"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - (Traduction)</span></a>
</li></ul>
</li></ul>

</nav>

