<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Accountability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-238122"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-238125"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Conflicts of Interest, Election Financing, Lobbying and Ministers’ Staff</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-238126"><span class="HTitleText2"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-238127"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-238129"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-238154"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-238155"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-238157"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-238160"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-238162"><span class="HTitleText4"><cite class="XRefExternalAct">First Nations Fiscal and Statistical Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-238164"><span class="HTitleText4"><cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-238174"><span class="HTitleText4"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-238176"><span class="HTitleText4"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-238178"><span class="HTitleText4"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-238185"><span class="HTitleText4"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-238189"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-238194"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-238196"><span class="HTitleText4"><cite class="XRefExternalAct">Radiocommunication Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-238198"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-238203"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Elections Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-238204"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-238226"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-238230"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-238231"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-238234"><span class="HTitleText2"><cite class="XRefExternalAct">Lobbyists Registration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-238235"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-238253"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-238255"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-238265"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-238266"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-238270"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-238275"><span class="HTitleText4"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-238277"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-238280"><span class="HTitleText2"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-238282"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>100 - </span><a href="#h-238283"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-238291"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-238293"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-238309"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Supporting Parliament</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="#h-238310"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-238312"><span class="HTitleText2"><cite class="XRefExternalAct">Auditor General Act</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-238314"><span class="HTitleText2"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-238316"><span class="HTitleText2">Parliament of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-238317"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-238323"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-238327"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-238329"><span class="HTitleText2"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-238331"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="#h-238333"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Office of the Director of Public Prosecutions, Administrative Transparency and Disclosure of Wrongdoing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-238334"><span class="HTitleText2"><cite class="XRefExternalAct">Director of Public Prosecutions Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-238335"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-238337"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-238345"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="#h-238346"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-238348"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Elections Act</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-238356"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-238358"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-238361"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="#h-238363"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-238364"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>172.1 - </span><a href="#h-238398"><span class="HTitleText3">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172.1 - </span><a href="#h-238399"><span class="HTitleText4">Canadian Wheat Board Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-238401"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Elections Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-238402"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-238408"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-238410"><span class="HTitleText2"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>179.1 - </span><a href="#h-238412"><span class="HTitleText2"><cite class="XRefExternalAct">Library and Archives of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-238415"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-238429"><span class="HTitleText2"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="#h-238430"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-238463"><span class="HTitleText3">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-238465"><span class="HTitleText2"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-238467"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>229 - </span><a href="#h-238473"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Administrative Oversight and Accountability</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="#h-238474"><span class="HTitleText2"><cite class="XRefExternalAct">Business Development Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-238476"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Council for the Arts Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-238478"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Mortgage And Housing Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-238482"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-238486"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Revenue Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-238488"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Commercial Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-238490"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Dairy Commission Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-238491"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-238495"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="#h-238497"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Race Relations Foundation Act</cite></span></a>
</li>
<li><span class='sectionRange'>244.1 - </span><a href="#h-238500"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Tourism Commission Act</cite></span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-238503"><span class="HTitleText2"><cite class="XRefExternalAct">Cape Breton Development Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="#h-238505"><span class="HTitleText2"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-238507"><span class="HTitleText2"><cite class="XRefExternalAct">Enterprise Cape Breton Corporation Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="#h-238508"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-238515"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="#h-238517"><span class="HTitleText2"><cite class="XRefExternalAct">Export Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-238519"><span class="HTitleText2"><cite class="XRefExternalAct">Farm Credit Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-238522"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>257 - </span><a href="#h-238523"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-238538"><span class="HTitleText3">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>276 - </span><a href="#h-238544"><span class="HTitleText2"><cite class="XRefExternalAct">Freshwater Fish Marketing Act</cite></span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-238548"><span class="HTitleText2"><cite class="XRefExternalAct">Museums Act</cite></span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="#h-238550"><span class="HTitleText2"><cite class="XRefExternalAct">National Arts Centre Act</cite></span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="#h-238554"><span class="HTitleText2"><cite class="XRefExternalAct">National Capital Act</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-238562"><span class="HTitleText2"><cite class="XRefExternalAct">Pilotage Act</cite></span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="#h-238568"><span class="HTitleText2"><cite class="XRefExternalAct">Public Sector Pension Investment Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-238572"><span class="HTitleText2"><cite class="XRefExternalAct">Royal Canadian Mint Act</cite></span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="#h-238574"><span class="HTitleText2"><cite class="XRefExternalAct">Standards Council of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-238576"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>301 - </span><a href="#h-238582"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Procurement and Contracting</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>301 - </span><a href="#h-238583"><span class="HTitleText2"><cite class="XRefExternalAct">Auditor General Act</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-238589"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Public Works and Government Services Act</cite></span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-238592"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="#h-238593"><span class="HTitleText3">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-238599"><span class="HTitleText3">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>314 - </span><a href="#h-238601"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-238608"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
