<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Paiements de péréquation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Paiements de péréquation aux provinces</span></a>
</li>
<li><span class='sectionRange'>3.6 - </span><a href="#h-5"><span class="HTitleText2">Nouvelle-Écosse et Terre-Neuve-et-Labrador</span></a>
</li>
<li><span class='sectionRange'>3.91 - </span><a href="#h-6"><span class="HTitleText2">Généralités</span></a>
</li></ul>
</li><li><span class='sectionRange'>3.98 - </span><a href="#h-7"><span class="HLabel1">PARTIE I.01</span> - <span class="HTitleText1">Autres Paiements</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-8"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Paiements aux territoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-9"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-10"><span class="HTitleText2">Paiements de transfert aux territoires</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="#h-11"><span class="HTitleText2">Généralités</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-12"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Paiements de stabilisation aux provinces</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-13"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Accords d’application</span></a>
</li>
<li><span class='sectionRange'>8.2 - </span><a href="#h-14"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Accords d’harmonisation de la taxe de vente</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-15"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Paiements de transfert relatifs à l’élimination des impôts provinciaux sur le capital</span> </a>
</li>
<li><span class='sectionRange'>12.02 - </span><a href="#h-16"><span class="HLabel1">PARTIE IV.01</span> - <span class="HTitleText1">Paiements de transfert — impôt relatif au report des avantages liés aux options d’achat d’actions prévu à la partie I.01 de la Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>12.1 - </span><a href="#h-17"><span class="HLabel1">PARTIE IV.1</span> - <span class="HTitleText1">Paiements de transfert relatifs aux impôts sur les dividendes d’actions privilégiées prévus aux parties IV.1 et VI.1 de la Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>12.4 - </span><a href="#h-18"><span class="HLabel1">PARTIE IV.2</span> - <span class="HTitleText1">Paiements de transfert — impôt sur les paiements dans le cadre de régimes enregistrés d’épargne-études prévu à la partie X.5 de la Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-19"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">[Abrogée, 2012, ch. 19, art. 391]</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-20"><span class="HLabel1">PARTIE V.1</span> - <span class="HTitleText1">Transfert canadien en matière de santé, Transfert canadien en matière de programmes sociaux et Transfert visant la réduction des temps d’attente</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-21"><span class="HTitleText2">Transfert canadien en matière de santé</span></a>
</li>
<li><span class='sectionRange'>24.3 - </span><a href="#h-22"><span class="HTitleText2">Transfert canadien en matière de programmes sociaux</span></a>
</li>
<li><span class='sectionRange'>24.61 - </span><a href="#h-23"><span class="HTitleText2">Transfert visant la réduction des temps d’attente</span></a>
</li>
<li><span class='sectionRange'>24.7 - </span><a href="#h-24"><span class="HTitleText2">Totalité des transferts fiscaux et de la péréquation</span></a>
</li>
<li><span class='sectionRange'>24.701 - </span><a href="#h-25"><span class="HTitleText2">Protection temporaire</span></a>
</li>
<li><span class='sectionRange'>24.8 - </span><a href="#h-26"><span class="HTitleText2">Paiements</span></a>
</li>
<li><span class='sectionRange'>24.9 - </span><a href="#h-27"><span class="HTitleText2">Réduction et retenue</span></a>
</li>
<li><span class='sectionRange'>25.6 - </span><a href="#h-28"><span class="HTitleText2">Retenue et déduction supplémentaires</span></a>
</li>
<li><span class='sectionRange'>25.7 - </span><a href="#h-29"><span class="HTitleText2">Mentions dans les autres lois</span></a>
</li>
<li><span class='sectionRange'>25.8 - </span><a href="#h-30"><span class="HTitleText2">Rapport</span></a>
</li>
<li><span class='sectionRange'>25.9 - </span><a href="#h-31"><span class="HTitleText2">Examen parlementaire</span></a>
</li>
<li><span class='sectionRange'>25.91 - </span><a href="#h-32"><span class="HTitleText2">Communiqués</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-33"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Paiements de remplacement pour les programmes permanents</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-34"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Taxes et droits provinciaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-35"><span class="HTitleText2">Définitions et modification des annexes</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-36"><span class="HTitleText2">Accords de réciprocité fiscale</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-37"><span class="HTitleText2">Paiements à l’égard des taxes et droits provinciaux par les sociétés d’État</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-38"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-39"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-40"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-41"><span class="HTitleText2">Loi de 2006 sur les droits d’exportation de produits de bois d’oeuvre</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-42"><span class="HTitleText2">Paiement sur le Trésor</span></a>
</li></ul>
</li><li><a href="#h-43"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-236269"><span class="scheduleLabel">ANNEXE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
