<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le partage des prestations de retraite</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-404468"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-404471"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-404499"><span class="HTitleText1">Demande de partage</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-404546"><span class="HTitleText1">Partage</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-404591"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-404616"><span class="HTitleText1">Infraction</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-404619"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>

