<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Oil and Gas Operations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-5"><span class="HTitleText1">Chief Safety Officer and Chief Conservation Officer</span></a>
</li>
<li><span class='sectionRange'>3.2 - </span><a href="#h-6"><span class="HTitleText1">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-7"><span class="HTitleText1">Prohibition</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-8"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-9"><span class="HTitleText1">Licences and Authorizations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5.02 - </span><a href="#h-10"><span class="HTitleText2">Safety of Works and Activities</span></a>
</li>
<li><span class='sectionRange'>5.03 - </span><a href="#h-11"><span class="HTitleText2">Financial Responsibility</span></a>
</li>
<li><span class='sectionRange'>5.11 - </span><a href="#h-12"><span class="HTitleText2">Declarations</span></a>
</li>
<li><span class='sectionRange'>5.12 - </span><a href="#h-13"><span class="HTitleText2">Certificates</span></a>
</li></ul>
</li><li><span class='sectionRange'>5.4 - </span><a href="#h-14"><span class="HTitleText1">Oil and Gas Administration Advisory Council</span></a>
</li>
<li><span class='sectionRange'>5.5 - </span><a href="#h-15"><span class="HTitleText1">Offshore Oil and Gas Training Standards Advisory Board</span></a>
</li>
<li><span class='sectionRange'>5.6 - </span><a href="#h-16"><span class="HTitleText1">Extended Formation Flow Tests</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-17"><span class="HTitleText1">Oil and Gas Committee</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-18"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-19"><span class="HTitleText2">Jurisdiction and Powers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-20"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-21"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Regulation of Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-22"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-23"><span class="HTitleText2">Production Orders</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-24"><span class="HTitleText2">Waste</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-25"><span class="HTitleText2">Spills and Debris</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-26"><span class="HTitleText2">Inquiries</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-27"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Production Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-28"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-29"><span class="HTitleText2">Pooling</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-30"><span class="HTitleText2">Unitization</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-31"><span class="HTitleText2">Compulsory Unitization</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-32"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-33"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Appeals and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-34"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-35"><span class="HTitleText2">Safety and Conservation Officers</span></a>
</li>
<li><span class='sectionRange'>58.2 - </span><a href="#h-36"><span class="HTitleText2">Installation Manager</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-37"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-38"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-39"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
