<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Excise Tax Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Insurance Premiums Other than Marine</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Air Transportation Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Tax Imposed</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HTitleText2">Collection of Tax</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-10"><span class="HTitleText2">Penalty on Failure to File Return</span></a>
</li>
<li><span class='sectionRange'>20.2 - </span><a href="#h-11"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>21.1 - </span><a href="#h-12"><span class="HLabel1">PART II.1</span> - <span class="HTitleText1">Telecommunication Programming Services Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21.1 - </span><a href="#h-13"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>21.11 - </span><a href="#h-14"><span class="HTitleText2">Application to Crown</span></a>
</li>
<li><span class='sectionRange'>21.12 - </span><a href="#h-15"><span class="HTitleText2">Imposition and Payment of Tax</span></a>
</li>
<li><span class='sectionRange'>21.14 - </span><a href="#h-16"><span class="HTitleText2">Determination of Amount Charged in Certain Circumstances</span></a>
</li>
<li><span class='sectionRange'>21.15 - </span><a href="#h-17"><span class="HTitleText2">Security</span></a>
</li>
<li><span class='sectionRange'>21.16 - </span><a href="#h-18"><span class="HTitleText2">Diversions</span></a>
</li>
<li><span class='sectionRange'>21.17 - </span><a href="#h-19"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="#h-20"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>21.21 - </span><a href="#h-21"><span class="HTitleText2">Increase of Amount Charged by Licensee</span></a>
</li></ul>
</li><li><span class='sectionRange'>21.22 - </span><a href="#h-22"><span class="HLabel1">PART II.2</span> - <span class="HTitleText1">Telecommunication Services Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21.22 - </span><a href="#h-23"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>21.23 - </span><a href="#h-24"><span class="HTitleText2">Application to Crown</span></a>
</li>
<li><span class='sectionRange'>21.24 - </span><a href="#h-25"><span class="HTitleText2">Imposition of Tax</span></a>
</li>
<li><span class='sectionRange'>21.25 - </span><a href="#h-26"><span class="HTitleText2">Determination of Amount Charged in Certain Circumstances</span></a>
</li>
<li><span class='sectionRange'>21.26 - </span><a href="#h-27"><span class="HTitleText2">Relief from Tax</span></a>
</li>
<li><span class='sectionRange'>21.29 - </span><a href="#h-28"><span class="HTitleText2">Diversions</span></a>
</li>
<li><span class='sectionRange'>21.3 - </span><a href="#h-29"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>21.31 - </span><a href="#h-30"><span class="HTitleText2">Collection of Tax</span></a>
</li>
<li><span class='sectionRange'>21.32 - </span><a href="#h-31"><span class="HTitleText2">Returns and Remittance of Tax</span></a>
</li>
<li><span class='sectionRange'>21.34 - </span><a href="#h-32"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-33"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Excise Taxes on Cosmetics, Jewellery, Radios, Etc.</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-34"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">[Repealed, 2002, c. 22, s. 370]</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-35"><span class="HLabel1">PART V</span> - <span class="HTitleText1">[Repealed, 2002, c. 22, s. 370]</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-36"><span class="HLabel1">PART V.1</span> - <span class="HTitleText1">[Repealed, 2000, c. 30, s. 10]</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-37"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Consumption or Sales Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-38"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-39"><span class="HTitleText2">Tax Imposed</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-40"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-41"><span class="HTitleText2">Evasion</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="#h-42"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58.1 - </span><a href="#h-43"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-44"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-45"><span class="HTitleText2">Stamps</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-46"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-47"><span class="HTitleText2">Exported Goods</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-48"><span class="HTitleText2">Liability of the Crown</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-49"><span class="HTitleText2">Deductions, Refunds and Drawbacks</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-50"><span class="HTitleText2">Returns and Payment of Tax</span></a>
</li>
<li><span class='sectionRange'>80.1 - </span><a href="#h-51"><span class="HTitleText2">Security</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-52"><span class="HTitleText2">Obligation of Trustees</span></a>
</li>
<li><span class='sectionRange'>81.1 - </span><a href="#h-53"><span class="HTitleText2">Assessments</span></a>
</li>
<li><span class='sectionRange'>81.15 - </span><a href="#h-54"><span class="HTitleText2">Objections</span></a>
</li>
<li><span class='sectionRange'>81.19 - </span><a href="#h-55"><span class="HTitleText2">Rights of Appeal</span></a>
</li>
<li><span class='sectionRange'>81.25 - </span><a href="#h-56"><span class="HTitleText2">Appeals to Tribunal</span></a>
</li>
<li><span class='sectionRange'>81.28 - </span><a href="#h-57"><span class="HTitleText2">Appeals to Court</span></a>
</li>
<li><span class='sectionRange'>81.32 - </span><a href="#h-58"><span class="HTitleText2">Extension of Time for Objection or Appeal</span></a>
</li>
<li><span class='sectionRange'>81.33 - </span><a href="#h-59"><span class="HTitleText2">Purchaser Objections and Appeals</span></a>
</li>
<li><span class='sectionRange'>81.34 - </span><a href="#h-60"><span class="HTitleText2">Interventions</span></a>
</li>
<li><span class='sectionRange'>81.36 - </span><a href="#h-61"><span class="HTitleText2">References</span></a>
</li>
<li><span class='sectionRange'>81.38 - </span><a href="#h-62"><span class="HTitleText2">Payments by Minister on Appeals</span></a>
</li>
<li><span class='sectionRange'>81.39 - </span><a href="#h-63"><span class="HTitleText2">Overpayments by Minister</span></a>
</li>
<li><span class='sectionRange'>81.4 - </span><a href="#h-64"><span class="HTitleText2">Administrative Charge under the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-65"><span class="HTitleText2">Collection</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-66"><span class="HTitleText2">Service</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-67"><span class="HTitleText2">Evidence</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-68"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Transitional</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-69"><span class="HTitleText2">Sales Tax Inventory Rebate</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-70"><span class="HTitleText2">New Housing Rebate</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="#h-71"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Goods and Services Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-72"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Interpretation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-73"><span class="HTitleText3">Relationships, Associations, Separate Persons and Residence</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-74"><span class="HTitleText3">Supplies and Commercial Activities</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-75"><span class="HTitleText3">Small Suppliers</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-76"><span class="HTitleText3">Financial Institutions</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-77"><span class="HTitleText3">Consideration</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-78"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Goods and Services Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-79"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Imposition of Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-80"><span class="HTitleText4">When Tax Payable</span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="#h-81"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Input Tax Credits</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-82"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Special Cases</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>171 - </span><a href="#h-83"><span class="HTitleText4">Becoming and Ceasing to be Registrant</span></a>
</li>
<li><span class='sectionRange'>171.1 - </span><a href="#h-84"><span class="HTitleText4">Taxi Businesses</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-85"><span class="HTitleText4">Appropriation of Property</span></a>
</li>
<li><span class='sectionRange'>172.1 - </span><a href="#h-86"><span class="HTitleText4">Pension Plans</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-87"><span class="HTitleText4">Taxable Benefits</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-88"><span class="HTitleText4">Allowances and Reimbursements</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-89"><span class="HTitleText4">Used Returnable Containers</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-90"><span class="HTitleText4">Agents</span></a>
</li>
<li><span class='sectionRange'>177.1 - </span><a href="#h-91"><span class="HTitleText4">Collecting Body and Collective Societies</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-92"><span class="HTitleText4">Network Sellers</span></a>
</li>
<li><span class='sectionRange'>178.1 - </span><a href="#h-93"><span class="HTitleText4">Direct Sellers</span></a>
</li>
<li><span class='sectionRange'>178.6 - </span><a href="#h-94"><span class="HTitleText4">Buying Groups</span></a>
</li>
<li><span class='sectionRange'>178.7 - </span><a href="#h-95"><span class="HTitleText4">Designated Charities</span></a>
</li>
<li><span class='sectionRange'>178.8 - </span><a href="#h-96"><span class="HTitleText4">Import Arrangements</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-97"><span class="HTitleText4">Non-resident</span></a>
</li>
<li><span class='sectionRange'>180.1 - </span><a href="#h-98"><span class="HTitleText4">International Travel</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-99"><span class="HTitleText4">Coupons and Rebates</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-100"><span class="HTitleText4">Property Acquired by Insurers on Settlement of Claim</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-101"><span class="HTitleText4">Property and Services for Financial Services</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-102"><span class="HTitleText4">Bets and Games of Chance</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-103"><span class="HTitleText4">Prizes</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-104"><span class="HTitleText4">Dues</span></a>
</li>
<li><span class='sectionRange'>189.1 - </span><a href="#h-105"><span class="HTitleText4">Fees</span></a>
</li>
<li><span class='sectionRange'>189.2 - </span><a href="#h-106"><span class="HTitleText4">Foreign Conventions</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-107"><span class="HTitleText4">Real Property</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-108"><span class="HTitleText4">Real Property Credits</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-109"><span class="HTitleText4">Statement as to Use of Real Property</span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="#h-110"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Capital Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 - </span><a href="#h-111"><span class="HTitleText4">Capital Personal Property</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-112"><span class="HTitleText4">Capital Real Property</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>212 - </span><a href="#h-113"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Tax on Importation of Goods</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-114"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Tax on Imported Taxable Supplies</span></a>
</li>
<li><span class='sectionRange'>220.01 - </span><a href="#h-115"><span class="HLabel2">DIVISION IV.1</span> - <span class="HTitleText2">Tax on Property and Services Brought Into a Participating Province</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220.05 - </span><a href="#h-116"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Tax on Tangible Personal Property</span></a>
</li>
<li><span class='sectionRange'>220.08 - </span><a href="#h-117"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Tax on Intangible Property and Services</span></a>
</li>
<li><span class='sectionRange'>220.09 - </span><a href="#h-118"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Returns and Payment of Tax</span></a>
</li></ul>
</li><li><span class='sectionRange'>221 - </span><a href="#h-119"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">Collection and Remittance of Division II Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>221 - </span><a href="#h-120"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Collection</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-121"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Remittance of Tax</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-122"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Returns</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-123"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Registration</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="#h-124"><span class="HLabel3">SUBDIVISION E</span> - <span class="HTitleText3">Fiscal Periods and Reporting Periods</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>243 - </span><a href="#h-125"><span class="HTitleText4">Fiscal Periods</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-126"><span class="HTitleText4">Reporting Periods</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="#h-127"><span class="HLabel2">DIVISION VI</span> - <span class="HTitleText2">Rebates</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-128"><span class="HLabel2">DIVISION VII</span> - <span class="HTitleText2">Miscellaneous</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="#h-129"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Trustees, Receivers and Personal Representatives</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-130"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Amalgamation and Winding-up</span></a>
</li>
<li><span class='sectionRange'>272.1 - </span><a href="#h-131"><span class="HLabel3">SUBDIVISION B.1</span> - <span class="HTitleText3">Partnerships and Joint Ventures</span></a>
</li>
<li><span class='sectionRange'>273.1 - </span><a href="#h-132"><span class="HLabel3">SUBDIVISION B.2</span> - <span class="HTitleText3">Export Distribution Centres</span></a>
</li>
<li><span class='sectionRange'>273.2 - </span><a href="#h-133"><span class="HLabel3">SUBDIVISION B.3</span> - <span class="HTitleText3">Information Returns</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-134"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Anti-avoidance</span></a>
</li></ul>
</li><li><span class='sectionRange'>275 - </span><a href="#h-135"><span class="HLabel2">DIVISION VIII</span> - <span class="HTitleText2">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>275 - </span><a href="#h-136"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Administration</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-137"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Returns, Penalties and Interest</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-138"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-139"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Assessments, Objections and Appeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>296 - </span><a href="#h-140"><span class="HTitleText4">Assessments</span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="#h-141"><span class="HTitleText4">Objections and Appeals</span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="#h-142"><span class="HLabel3">SUBDIVISION E</span> - <span class="HTitleText3">Collection</span></a>
</li>
<li><span class='sectionRange'>326 - </span><a href="#h-143"><span class="HLabel3">SUBDIVISION F</span> - <span class="HTitleText3">Offences</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="#h-144"><span class="HLabel3">SUBDIVISION G</span> - <span class="HTitleText3">Evidence and Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>336 - </span><a href="#h-145"><span class="HLabel2">DIVISION IX</span> - <span class="HTitleText2">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="#h-146"><span class="HTitleText3">Real Property</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-147"><span class="HTitleText3">Property and Services</span></a>
</li></ul>
</li><li><span class='sectionRange'>348 - </span><a href="#h-148"><span class="HLabel2">DIVISION X</span> - <span class="HTitleText2">Transitional Provisions for Participating Provinces</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>348 - </span><a href="#h-149"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>349 - </span><a href="#h-150"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="#h-151"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Transition</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>352 - </span><a href="#h-152"><span class="HTitleText4">Property and Services</span></a>
</li></ul>
</li><li><span class='sectionRange'>362 - </span><a href="#h-153"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Special Cases</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-200399"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-200452"><span class="scheduleLabel">SCHEDULE II</span></a>
</li>
<li><a href="#h-200457"><span class="scheduleLabel">SCHEDULE II.1</span> <span class="scheduleTitleText"> - Specific Tax Rates on Petroleum Products</span></a>
</li>
<li><a href="#h-200466"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li>
<li><a href="#h-200794"><span class="scheduleLabel">SCHEDULE III.1</span> - <span class="scheduleTitleText"> - Goods Sold by Deemed Manufacturers or Producers</span></a>
</li>
<li><a href="#h-200807"><span class="scheduleLabel">SCHEDULE IV</span> </a>
</li>
<li><a href="#h-200861"><span class="scheduleLabel">SCHEDULE V</span> <span class="scheduleTitleText"> - Exempt Supplies</span></a>
</li>
<li><a href="#h-201391"><span class="scheduleLabel">SCHEDULE VI</span> <span class="scheduleTitleText"> - Zero-Rated Supplies</span></a>
</li>
<li><a href="#h-201796"><span class="scheduleLabel">SCHEDULE VII</span> <span class="scheduleTitleText"> - Non-Taxable Importations</span></a>
</li>
<li><a href="#h-201840"><span class="scheduleLabel">SCHEDULE VIII</span> </a>
</li>
<li><a href="#h-201850"><span class="scheduleLabel">SCHEDULE IX</span> <span class="scheduleTitleText"> - Supply in a Province</span></a>
</li>
<li><a href="#h-201977"><span class="scheduleLabel">SCHEDULE X</span> - <span class="scheduleTitleText"> - Non-Taxable Property and Services for Purposes of Division IV.1 of Part IX</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
