<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Farm Income Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-236315"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-236318"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-236337"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-236340"><span class="HTitleText1">Protection of Producers’ Income</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-236341"><span class="HTitleText2">Agreements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-236432"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-236448"><span class="HTitleText2">Special Measures</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="page-2.html#h-236466"><span class="HTitleText1">Accounts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-2.html#h-236467"><span class="HTitleText2">Crop Reinsurance Fund</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-236491"><span class="HTitleText2">Net Income Stabilization Account in the Accounts of Canada</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="page-2.html#h-236511"><span class="HTitleText2">Net Income Stabilization Accounts in Financial Institutions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-236541"><span class="HTitleText2">Revenue Insurance Fund</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-236563"><span class="HTitleText2">Advances</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-3.html#h-236576"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-236584"><span class="HTitleText1">Payments Out of Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-236587"><span class="HTitleText1">Reports to Parliament</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-236597"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-236622"><span class="HTitleText1">Consequential Amendment</span></a>
</li>
<li><span class='sectionRange'>27 to 29 - </span><a href="page-3.html#h-236624"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-236626"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

