<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’arpentage des terres du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-336362"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-336367"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-336392"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>5 à 16 - </span><a href="#h-336409"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Pouvoirs et fonction des arpenteurs des terres du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-336411"><span class="HTitleText2">Pouvoirs et fonctions des arpenteurs</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-336428"><span class="HTitleText2">Étalon de mesure</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-336438"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Arpentage des terres du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-336439"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-336468"><span class="HTitleText2">Arpentages</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-336484"><span class="HTitleText2">Plans</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-336510"><span class="HTitleText2">Bornes</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-336518"><span class="HTitleText2">Réarpentages</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-336528"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Arpentages spéciaux de terres territoriales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-336529"><span class="HTitleText2">Portée et application</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-336536"><span class="HTitleText2">Arpentages spéciaux</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-336557"><span class="HTitleText2">Procédure relative aux arpentages spéciaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-336635"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-336636"><span class="HTitleText2">Pouvoir général d’exécuter des arpentages</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-336644"><span class="HTitleText2">Preuve</span></a>
</li>
<li><span class='sectionRange'>51 et 52 - </span><a href="#h-336660"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

