<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Agricultural Marketing Programs Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Advance Payments Program</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Advance Guarantee Agreements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText2">Eligibility and Repayment</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HTitleText2">Amount of Advances</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Default</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-8"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Price Pooling Program</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-9"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Government Purchases Program</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-11"><span class="HTitleText2">Contractual and Financial Matters</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-12"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-13"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-14"><span class="HTitleText2">Reports to Parliament</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 to 45 - </span><a href="#h-15"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Repeals, Transitional Provisions, Consequential Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 to 45 - </span><a href="#h-16"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-17"><span class="HTitleText2">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-18"><span class="HTitleText3">Agricultural Products Board Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-19"><span class="HTitleText3">Agricultural Products Cooperative Marketing Act</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-20"><span class="HTitleText3">Advance Payments for Crops Act</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-21"><span class="HTitleText3">Prairie Grain Advance Payments Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 to 55 - </span><a href="#h-22"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-23"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-24"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Programs</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
