<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la pension de la fonction publique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Égalité de statut</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Pension de retraite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Pension de retraite</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Personnes tenues de contribuer</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Service ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Service ouvrant droit à pension et accompagné d’option : montant dont le paiement est requis</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Options</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Prestations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText3">Définitions, etc.</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-12"><span class="HTitleText3">Pensions : mode de calcul</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-13"><span class="HTitleText2">Contributeurs qui comptent moins de deux années de service ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-14"><span class="HTitleText2">Contributeurs qui comptent au moins deux années de service ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-15"><span class="HTitleText2">Contrôleurs de la circulation aérienne</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-16"><span class="HTitleText2">Service correctionnel du Canada</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-17"><span class="HTitleText2">Paiements aux survivants, aux enfants et à d’autres bénéficiaires</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-18"><span class="HTitleText2">Prestations minimales</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText2">Paiements au titre de l’invalidité</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-20"><span class="HTitleText2">Personnes employées de nouveau</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-21"><span class="HTitleText2">Examens médicaux</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-22"><span class="HTitleText2">Changement de destinataire en certains cas</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-23"><span class="HTitleText2">Présomption de décès</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-24"><span class="HTitleText2">Cas particuliers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-25"><span class="HTitleText3">Employés transférés de Terre-Neuve ayant droit à pension</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-26"><span class="HTitleText3">Représentants diplomatiques et consulaires</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-27"><span class="HTitleText3">Organismes de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-28"><span class="HTitleText3">Personnes morales déclarées faire partie ou avoir fait partie de la fonction publique, à des fins restreintes seulement</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-29"><span class="HTitleText2">Loi sur la pension de retraite des Forces canadiennes et Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-30"><span class="HTitleText2">Accords réciproques de transfert</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-31"><span class="HTitleText2">Cession de service</span></a>
</li>
<li><span class='sectionRange'>40.2 - </span><a href="#h-32"><span class="HTitleText2">Accords de transfert</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-33"><span class="HTitleText2">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-34"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-35"><span class="HTitleText2">Paiements sur le compte de pension de retraite</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-36"><span class="HTitleText2">Montants</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="#h-37"><span class="HTitleText2">Fonds de placement du compte de pension de retraite de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>44.2 - </span><a href="#h-38"><span class="HTitleText2">Caisse de retraite de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-39"><span class="HTitleText2">Rapport actuariel</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-40"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>46.1 - </span><a href="#h-41"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Dispositions applicables à la société canadienne des postes</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-42"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Prestations supplémentaires de décès</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-43"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-44"><span class="HTitleText2">Choix</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-45"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-46"><span class="HTitleText2">Prestations</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-47"><span class="HTitleText2">Compte de prestations de décès de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-48"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-49"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Prestations supplémentaires</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-50"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-51"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-400447"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Prime unique</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
