<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les traitements</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-433469"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-433476"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Traitements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-433477"><span class="HTitleText2">Traitements payables sur le trésor</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-433482"><span class="HTitleText2">Traitement des lieutenants-gouverneurs</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-433506"><span class="HTitleText2">Traitements des ministres : avant le 1er avril 2004</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-433546"><span class="HTitleText2">Traitements des ministres : à compter du 1er avril 2004</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-433602"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Soutien aux ministres visés aux alinéas 4.1(3)z.4) à z.9)</span></a>
</li></ul>
</li></ul>

</nav>

