<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Government Employees Compensation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-251655"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-251660"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-251680"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-251688"><span class="HTitleText1">Compensation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-251748"><span class="HTitleText1">Claims Against Third Parties and Compensation</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-251786"><span class="HTitleText1">No Other Claims Against Crown</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-251795"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

