<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les compétences linguistiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-336081"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-336084"><span class="HTitleText1">Compétences linguistiques</span></a>
</li></ul>
</li></ul>

</nav>

