<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Customs Tariff</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-142680"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-142683"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Interpretation and General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-142684"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-142807"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-142823"><span class="HTitleText2">Amendment of Schedule</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-142869"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Customs Duties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-142870"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Origin of Goods</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-142871"><span class="HTitleText3">Rules of Origin</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-142893"><span class="HTitleText3">Direct Shipment and Transhipment</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-142910"><span class="HTitleText3">Marking of Goods</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-142924"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Imposition of Customs Duties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-142925"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-142974"><span class="HTitleText3">Special Classification</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-142977"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Tariff Treatments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-142978"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-143042"><span class="HTitleText3">General Tariff</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-143053"><span class="HTitleText3">Most-Favoured-Nation Tariff</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-143117"><span class="HTitleText3">General Preferential Tariff</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-143154"><span class="HTitleText3">Least Developed Country Tariff</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-143185"><span class="HTitleText3">Commonwealth Caribbean Countries Tariff</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-143211"><span class="HTitleText3">Australia Tariff and New Zealand Tariff</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-143244"><span class="HTitleText3">United States Tariff and Mexico Tariff</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-143285"><span class="HTitleText3">Chile Tariff</span></a>
</li>
<li><span class='sectionRange'>49.01 - </span><a href="#h-143332"><span class="HTitleText3">Colombia Tariff</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="#h-143382"><span class="HTitleText3">Costa Rica Tariff</span></a>
</li>
<li><span class='sectionRange'>49.41 - </span><a href="#h-143436"><span class="HTitleText3">Panama Tariff</span></a>
</li>
<li><span class='sectionRange'>49.5 - </span><a href="#h-143475"><span class="HTitleText3">Peru Tariff</span></a>
</li>
<li><span class='sectionRange'>49.6 - </span><a href="#h-143509"><span class="HTitleText3">Honduras Tariff</span></a>
</li>
<li><span class='sectionRange'>49.7 - </span><a href="#h-143543"><span class="HTitleText3">Korea Tariff</span></a>
</li>
<li><span class='sectionRange'>49.8 - </span><a href="#h-143594"><span class="HTitleText3">Canada–European Union Tariff</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-143656"><span class="HTitleText3">Canada–Israel Agreement Tariff</span></a>
</li>
<li><span class='sectionRange'>52.1 - </span><a href="#h-143673"><span class="HTitleText3">Iceland Tariff</span></a>
</li>
<li><span class='sectionRange'>52.2 - </span><a href="#h-143714"><span class="HTitleText3">Norway Tariff</span></a>
</li>
<li><span class='sectionRange'>52.3 - </span><a href="#h-143755"><span class="HTitleText3">Switzerland–Liechtenstein Tariff</span></a>
</li>
<li><span class='sectionRange'>52.4 - </span><a href="#h-143796"><span class="HTitleText3">Jordan Tariff</span></a>
</li>
<li><span class='sectionRange'>52.5 - </span><a href="#h-143812"><span class="HTitleText3">Ukraine Tariff</span></a>
</li>
<li><span class='sectionRange'>52.6 - </span><a href="#h-143822"><span class="HTitleText3">Comprehensive and Progressive Trans-Pacific Partnership Tariff</span></a>
</li>
<li><span class='sectionRange'>52.62 - </span><a href="#h-143900"><span class="HTitleText3">Comprehensive and Progressive Australia Tariff</span></a>
</li>
<li><span class='sectionRange'>52.64 - </span><a href="#h-143978"><span class="HTitleText3">Comprehensive and Progressive Brunei Tariff</span></a>
</li>
<li><span class='sectionRange'>52.66 - </span><a href="#h-144056"><span class="HTitleText3">Comprehensive and Progressive Chile Tariff</span></a>
</li>
<li><span class='sectionRange'>52.68 - </span><a href="#h-144134"><span class="HTitleText3">Comprehensive and Progressive Japan Tariff</span></a>
</li>
<li><span class='sectionRange'>52.7 - </span><a href="#h-144212"><span class="HTitleText3">Comprehensive and Progressive Malaysia Tariff</span></a>
</li>
<li><span class='sectionRange'>52.72 - </span><a href="#h-144290"><span class="HTitleText3">Comprehensive and Progressive Mexico Tariff</span></a>
</li>
<li><span class='sectionRange'>52.74 - </span><a href="#h-144368"><span class="HTitleText3">Comprehensive and Progressive New Zealand Tariff</span></a>
</li>
<li><span class='sectionRange'>52.76 - </span><a href="#h-144446"><span class="HTitleText3">Comprehensive and Progressive Peru Tariff</span></a>
</li>
<li><span class='sectionRange'>52.78 - </span><a href="#h-144524"><span class="HTitleText3">Comprehensive and Progressive Singapore Tariff</span></a>
</li>
<li><span class='sectionRange'>52.8 - </span><a href="#h-144602"><span class="HTitleText3">Comprehensive and Progressive Vietnam Tariff</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-144680"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Special Measures, Emergency Measures and Safeguards</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-144681"><span class="HTitleText3">Special Measures</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-144702"><span class="HTitleText3">Global Emergency Measures</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-144829"><span class="HTitleText3">Safeguard Measures for Agricultural Goods</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-144909"><span class="HTitleText3">Bilateral Emergency Measures — Chile</span></a>
</li>
<li><span class='sectionRange'>71.01 - </span><a href="#h-144940"><span class="HTitleText3">Bilateral Emergency Measures — Colombia</span></a>
</li>
<li><span class='sectionRange'>71.1 - </span><a href="#h-144961"><span class="HTitleText3">Bilateral Emergency Measures — Costa Rica</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="#h-144997"><span class="HTitleText3">Bilateral Emergency Measures — Iceland</span></a>
</li>
<li><span class='sectionRange'>71.3 - </span><a href="#h-145030"><span class="HTitleText3">Bilateral Emergency Measures — Norway</span></a>
</li>
<li><span class='sectionRange'>71.4 - </span><a href="#h-145065"><span class="HTitleText3">Bilateral Emergency Measures — Switzerland–Liechtenstein</span></a>
</li>
<li><span class='sectionRange'>71.41 - </span><a href="#h-145098"><span class="HTitleText3">Bilateral Emergency Measures — Panama</span></a>
</li>
<li><span class='sectionRange'>71.5 - </span><a href="#h-145120"><span class="HTitleText3">Bilateral Emergency Measures — Peru</span></a>
</li>
<li><span class='sectionRange'>71.6 - </span><a href="#h-145140"><span class="HTitleText3">Bilateral Emergency Measures — Jordan</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-145165"><span class="HTitleText3">Bilateral Emergency Measures  —  Honduras</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-145197"><span class="HTitleText3">Bilateral Emergency Measures for Textile and Apparel Goods Imported from Honduras</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-145223"><span class="HTitleText3">Bilateral Emergency Measures — Korea</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-145265"><span class="HTitleText3">Bilateral Emergency Measures — Ukraine</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-145287"><span class="HTitleText3">Emergency Measures — CPTPP Countries</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-145315"><span class="HTitleText3">Emergency Measures for Textile and Apparel Goods Imported from CPTPP Countries</span></a>
</li>
<li><span class='sectionRange'>77.1 - </span><a href="#h-145333"><span class="HTitleText3">Safeguard Measures in Respect of China</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-145419"><span class="HTitleText3">Surtaxes</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-145429"><span class="HTitleText3">Goods in Transit</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-145450"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Duties Relief</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="#h-145451"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-145463"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Reduction of Rates of Customs Duty</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-145477"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Importation without Full Payment of Duties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="#h-145478"><span class="HTitleText3">Reduced Value for Duty</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-145511"><span class="HTitleText3">Ethno-cultural Groups</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-145516"><span class="HTitleText3">Duty Deferral</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-145706"><span class="HTitleText3">Canadian Goods Abroad</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-145764"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-145789"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Obsolete or Surplus Goods</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-145818"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Additional Relief</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-145864"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="#h-145959"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-146096"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Prohibited Goods</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-146102"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>147 to 191 - </span><a href="#h-146124"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>192 to 212 - </span><a href="#h-146126"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-146128"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>213 - </span><a href="#h-146129"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-146131"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-146135"><span class="scheduleLabel"><span class="wb-invisible">Footnote </span><sup>*</sup>SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
