<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">Fixation des limites et règlement des litiges</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Approbation préalable des règlements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Cogestion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Constitution de l’Office</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText2">Attributions de l’Office</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText2">Fonctionnement</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-10"><span class="HTitleText2">Décisions portant sur la gestion extracôtière</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-11"><span class="HTitleText2">Sécurité des approvisionnements régionaux</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-12"><span class="HTitleText2">Instructions ministérielles</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-13"><span class="HTitleText2">Exposés relatifs aux titres</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-14"><span class="HTitleText2">Enquêtes publiques</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-15"><span class="HTitleText2">Plan de retombées économiques</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-16"><span class="HTitleText2">Coordination administrative</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-17"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Hydrocarbures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-18"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-19"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-20"><span class="HTitleText3">Modalités des avis</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-21"><span class="HTitleText3">Obligation</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-22"><span class="HTitleText3">Nominations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-23"><span class="HTitleText3">Dispositions générales sur les titres</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="#h-24"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Dispositions générales sur l’octroi des titres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="#h-25"><span class="HTitleText3">Pouvoir général</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-26"><span class="HTitleText3">Titres sur des réserves de l’État</span></a>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-27"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Prospection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-28"><span class="HTitleText3">Permis de prospection</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-29"><span class="HTitleText3">Découvertes importantes</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-30"><span class="HTitleText3">Attestation de découverte importante</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-31"><span class="HTitleText3">Arrêtés de forage</span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-32"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-33"><span class="HTitleText3">Découvertes exploitables</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-34"><span class="HTitleText3">Arrêtés de mise en valeur</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-35"><span class="HTitleText3">Licences de production</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-36"><span class="HTitleText3">Licences de stockage souterrain</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-37"><span class="HTitleText3">Critère d’obtention</span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="#h-38"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">[Abrogée, 1993, ch. 47, art. 8]</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-39"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Redevances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97 - </span><a href="#h-40"><span class="HTitleText3">Levée des redevances</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-41"><span class="HTitleText3">Assujettissement et recouvrement</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-42"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Fonds renouvelables pour l’étude de l’environnement</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-43"><span class="HLabel2">SECTION VIII</span> - <span class="HTitleText2">Transferts, cessions et enregistrement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-44"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-45"><span class="HTitleText3">Transferts et cessions</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-46"><span class="HTitleText3">Enregistrement</span></a>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="#h-47"><span class="HLabel2">SECTION IX</span> - <span class="HTitleText2">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="#h-48"><span class="HTitleText3">Renseignements</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-49"><span class="HTitleText3">Arbitrage</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-50"><span class="HTitleText3">Annulation des titres</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-51"><span class="HTitleText3">Audiences et révision</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-52"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-53"><span class="HLabel2">SECTION X</span> - <span class="HTitleText2">Dispositions transitoires, corrélatives et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-54"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="#h-55"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Opérations pétrolières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-56"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-57"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-58"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>136.1 - </span><a href="#h-59"><span class="HTitleText2">Conseil d’harmonisation</span></a>
</li>
<li><span class='sectionRange'>136.2 - </span><a href="#h-60"><span class="HTitleText2">Conseil des normes extracôtières de formation</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-61"><span class="HTitleText2">Interdiction</span></a>
</li>
<li><span class='sectionRange'>137.1 - </span><a href="#h-62"><span class="HTitleText2">Délégation</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-63"><span class="HTitleText2">Permis et autorisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-64"><span class="HTitleText3">Permis et autorisations de travaux</span></a>
</li>
<li><span class='sectionRange'>138.2 - </span><a href="#h-65"><span class="HTitleText3">Sécurité des activités</span></a>
</li>
<li><span class='sectionRange'>138.3 - </span><a href="#h-66"><span class="HTitleText3">Responsabilité financière</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-67"><span class="HTitleText3">Autorisation de plans de mise en valeur</span></a>
</li>
<li><span class='sectionRange'>139.1 - </span><a href="#h-68"><span class="HTitleText3">Déclarations</span></a>
</li>
<li><span class='sectionRange'>139.2 - </span><a href="#h-69"><span class="HTitleText3">Certificats</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-70"><span class="HTitleText2">Délégué à la sécurité et délégué à l’exploitation</span></a>
</li>
<li><span class='sectionRange'>140.1 - </span><a href="#h-71"><span class="HTitleText2">Dérogation à la loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>140.2 - </span><a href="#h-72"><span class="HTitleText2">Essais d’écoulement prolongés</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-73"><span class="HTitleText2">Comité des hydrocarbures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-74"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-75"><span class="HTitleText3">Compétence et attributions</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-76"><span class="HTitleText3">Exécution</span></a>
</li></ul>
</li><li><span class='sectionRange'>149 - </span><a href="#h-77"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Réglementation de l’exploitation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="#h-78"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-79"><span class="HTitleText3">Arrêtés de production</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-80"><span class="HTitleText3">Gaspillage</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-81"><span class="HTitleText3">Rejets et débris</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-82"><span class="HTitleText3">Enquêtes</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-83"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Accords de production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-84"><span class="HTitleText3">Mise en commun</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-85"><span class="HTitleText3">Union</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-86"><span class="HTitleText3">Union obligatoire</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-87"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>184 - </span><a href="#h-88"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Appels et mesures de contrainte</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>184 - </span><a href="#h-89"><span class="HTitleText3">Appels</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-90"><span class="HTitleText3">Agents de la sécurité et du contrôle de l’exploitation</span></a>
</li>
<li><span class='sectionRange'>193.2 - </span><a href="#h-91"><span class="HTitleText3">Chargé de projet</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-92"><span class="HTitleText3">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-93"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-94"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-95"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-96"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Partage des recettes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-97"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-98"><span class="HTitleText2">Impôts indirects</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-99"><span class="HTitleText2">Taxe sur les primes d’assurance</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-100"><span class="HTitleText2">Accord fiscal</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-101"><span class="HTitleText2">Imposition des personnes morales</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-102"><span class="HTitleText2">Assujettissement et recouvrement</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-103"><span class="HTitleText2">Fonds de recettes</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-104"><span class="HTitleText2">Compétence des tribunaux</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-105"><span class="HTitleText2">Règlement</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-106"><span class="HTitleText2">Affectation</span></a>
</li></ul>
</li><li><span class='sectionRange'>218 - </span><a href="#h-107"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Paiements de péréquation compensatoires et détermination du potentiel fiscal par habitant</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>218 - </span><a href="#h-108"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-109"><span class="HTitleText2">Péréquation compensatoire</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-110"><span class="HTitleText2">Détermination du potentiel</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-111"><span class="HTitleText2">Détermination</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-112"><span class="HTitleText2">Versements anticipés</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-113"><span class="HTitleText2">Affectation</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-114"><span class="HTitleText2">Rapports</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-115"><span class="HTitleText2">Règlement</span></a>
</li></ul>
</li><li><span class='sectionRange'>228 - </span><a href="#h-116"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Fonds de développement extracôtier</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="#h-117"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-118"><span class="HTitleText2">Fonds de développement</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-119"><span class="HTitleText2">Accord avec le gouvernement provincial</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-120"><span class="HTitleText2">Paiements</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-121"><span class="HTitleText2">Comité du Fonds de développement</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-122"><span class="HTitleText2">Affectation</span></a>
</li></ul>
</li><li><span class='sectionRange'>234 et 235 - </span><a href="#h-123"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Impôt des personnes morales</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-124"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Dispositions transitoires et corrélatives et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>236 - </span><a href="#h-125"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>237 et 238 - </span><a href="#h-126"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-127"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
