<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Indigenous Languages Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1151116"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1151119"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1151134"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1151151"><span class="HTitleText1">Rights Related to Indigenous Languages</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-1151154"><span class="HTitleText1">Powers, Duties and Functions of Minister</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-1151165"><span class="HTitleText1">Federal Institutions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-1151177"><span class="HTitleText1">Office of Commissioner of Indigenous Languages</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-1151178"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-1151212"><span class="HTitleText2">Mandate and Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-1151267"><span class="HTitleText2">Financial Management</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-1151344"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-1151364"><span class="HTitleText1">Regulations and Rules</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-1151396"><span class="HTitleText1">Independent Review</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="#h-1151410"><span class="HTitleText1">Parliamentary Review</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-1151413"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
