<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Industry Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Establishment of Department</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Regional Economic Development in Ontario and Quebec</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Powers, Duties and Functions of the Registrar General of Canada</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-7"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Transitional and Related Amendments, Repeals and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>26 to 30 - </span><a href="#h-9"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 to 30 - </span><a href="#h-10"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText3">Broadcasting Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-12"><span class="HTitleText3">Canada Corporations Act</span></a>
</li>
<li><span class='sectionRange'>33 and 34 - </span><a href="#h-13"><span class="HTitleText3">Department of Communications Act</span></a>
</li>
<li><span class='sectionRange'>35 to 38 - </span><a href="#h-14"><span class="HTitleText3">Department of Consumer and Corporate Affairs Act</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText3">Employment Support Act</span></a>
</li>
<li><span class='sectionRange'>40 to 43 - </span><a href="#h-16"><span class="HTitleText3">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-17"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>45 to 51 - </span><a href="#h-18"><span class="HTitleText3">Investment Canada Act</span></a>
</li>
<li><span class='sectionRange'>52 and 53 - </span><a href="#h-19"><span class="HTitleText3">Plant Breeders’ Rights Act</span></a>
</li>
<li><span class='sectionRange'>54 to 56 - </span><a href="#h-20"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>57 to 59 - </span><a href="#h-21"><span class="HTitleText3">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-22"><span class="HTitleText3">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-23"><span class="HTitleText3">Salaries Act</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-24"><span class="HTitleText3">References</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 to 66 - </span><a href="#h-25"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-26"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
