<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Witness Protection Program Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-464726"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-464731"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-464753"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-464758"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-464768"><span class="HTitleText1">Witness Protection Program</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="page-1.html#h-464832"><span class="HTitleText1">Designated Programs</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-464853"><span class="HTitleText1">Protection of Information</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-464971"><span class="HTitleText1">Agreements and Arrangements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-464999"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-465041"><span class="HTitleText1">Offence</span></a>
</li>
<li><span class='sectionRange'>22 and 23 - </span><a href="page-3.html#h-465046"><span class="HTitleText1">Related and Consequential Amendments</span></a>
</li>
<li><a href="page-4.html#h-465049"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Designated Programs</span></a>
</li></ul>
</li></ul>

</nav>

