<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1996 pour la mise en oeuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-314346"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-314349"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Accord Canada — Russie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-314365"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Convention Canada — Afrique du sud en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-314381"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Accord Canada — Tanzanie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-314397"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Accord Canada — Inde en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-314413"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Convention Canada — Ukraine en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="#h-314430"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Accord entre le gouvernement du Canada et le gouvernement de la Fédération de la Russie en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-314679"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement de la République sud-africaine en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="#h-314949"><span class="scheduleLabel">ANNEXE III</span> <span class="scheduleTitleText"> - Accord entre le Canada et la République-Unie de Tanzanie en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-315279"><span class="scheduleLabel">ANNEXE IV</span> <span class="scheduleTitleText"> - Accord entre le gouvernement du Canada et le gouvernement de la République de l’Inde en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-315599"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Convention entre le Canada et l’Ukraine en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li></ul>
</li></ul>

</nav>

