<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les ports de pêche et de plaisance</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-227566"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-227571"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-227595"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-227634"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-227654"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-227695"><span class="HTitleText1">Recouvrement des droits</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-227703"><span class="HTitleText1">Enlèvement, saisie, rétention et vente</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-227759"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-227776"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-227786"><span class="HTitleText1">Paiement des amendes</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-227798"><span class="HTitleText1">Enquêtes sur les accidents</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-227807"><span class="HTitleText1">Personnel</span></a>
</li></ul>
</li></ul>

</nav>

