<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Forces Members and Veterans Re-establishment and Compensation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Career Transition Services</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Rehabilitation Services, Vocational Assistance and Financial Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Rehabilitation Services and Vocational Assistance</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText2">Earnings Loss Benefit</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText2">Supplementary Retirement Benefit</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-10"><span class="HTitleText2">Canadian Forces Income Support Benefit</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-11"><span class="HTitleText2">Career Impact Allowance</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-12"><span class="HTitleText2">Retirement Income Security Benefit</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-13"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-14"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Critical Injury, Disability, Death and Detention</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-15"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="#h-16"><span class="HTitleText2">Critical Injury Benefit</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-17"><span class="HTitleText2">Disability Awards</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-18"><span class="HTitleText2">Death Benefit</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-19"><span class="HTitleText2">Clothing Allowance</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-20"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-21"><span class="HTitleText2">Detention Benefit</span></a>
</li></ul>
</li><li><span class='sectionRange'>65.1 - </span><a href="#h-22"><span class="HLabel1">PART 3.1</span> - <span class="HTitleText1">Family Caregiver Relief Benefit</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-23"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="#h-24"><span class="HTitleText2">Health Benefits</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-25"><span class="HTitleText2">Designations</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-26"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>75.1 - </span><a href="#h-27"><span class="HTitleText2">Transition to Civilian Life</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-28"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-29"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-30"><span class="HTitleText2">Sharing of Information</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-31"><span class="HTitleText2">Review</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-32"><span class="HTitleText2">Overpayments</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-33"><span class="HTitleText2">Miscellaneous</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-34"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-35"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Transitional Provisions, Related and Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-36"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-37"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-38"><span class="HTitleText3">Children of Deceased Veterans Education Assistance Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-39"><span class="HTitleText3">Department of Veterans Affairs Act</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-40"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-41"><span class="HTitleText3">Injured Military Members Compensation Act</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-42"><span class="HTitleText3">Pension Act</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-43"><span class="HTitleText3">Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-44"><span class="HTitleText3">Veterans Review and Appeal Board Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-45"><span class="HTitleText3">Public Service Employment Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="#h-46"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-47"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-69360"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-49"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-69380"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
