<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
High Risk Child Sex Offender Database Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-254115"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-254118"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-254134"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-254137"><span class="HTitleText1">Database</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-254170"><span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

