<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des services aériens</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-390904"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-390907"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-390915"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Employés du groupe exploitation technique, entretien et soutien opérationnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-390916"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-390923"><span class="HTitleText2">Services aériens</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-390941"><span class="HTitleText2">Prorogation de la convention collective</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-390952"><span class="HTitleText2">Choix de l’offre finale</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-390986"><span class="HTitleText2">Nouvelle convention collective</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-390994"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Pilotes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-390995"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-391002"><span class="HTitleText2">Services aériens</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-391020"><span class="HTitleText2">Prorogation de la convention collective</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-391031"><span class="HTitleText2">Choix de l’offre finale</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-391065"><span class="HTitleText2">Nouvelle convention collective</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-391073"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-391074"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-391077"><span class="HTitleText2">Contrôle d’application</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-391091"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

