<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Cannabis Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-76878"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-76881"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-76961"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-76966"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-76969"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-76979"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Prohibitions, Obligations and Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-1.html#h-76980"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Criminal Activities</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-77140"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Other Prohibitions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-3.html#h-77141"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Promotion</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-77220"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Packaging and Labelling</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-77239"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Display</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-77244"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Selling and Distributing</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-77265"><span class="HLabel3">SUBDIVISION E</span> - <span class="HTitleText3">Other Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="page-4.html#h-77275"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-77291"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-4.html#h-77311"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Ticketable Offences</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-5.html#h-77411"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Licences and Permits</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-5.html#h-77505"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">General Authorizations</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-6.html#h-77536"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Ministerial Orders</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-6.html#h-77600"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Cannabis Tracking System</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-6.html#h-77630"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Inspections</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-7.html#h-77694"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Search Warrant</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-7.html#h-77724"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Disposition of Seized Things</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="page-7.html#h-77725"><span class="HTitleText2">Report to Minister</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-7.html#h-77738"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-7.html#h-77750"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Non-chemical Offence-related Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-7.html#h-77751"><span class="HTitleText3">Restraint Orders</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-7.html#h-77783"><span class="HTitleText3">Management Orders</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-7.html#h-77817"><span class="HTitleText3">Forfeiture</span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="page-8.html#h-77910"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Cannabis and Chemical Property</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-9.html#h-77961"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-9.html#h-77962"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-9.html#h-77965"><span class="HTitleText2">Violation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-9.html#h-77971"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-9.html#h-77988"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-9.html#h-78001"><span class="HTitleText2">Compliance Agreements</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="page-9.html#h-78033"><span class="HTitleText2">Review by Minister</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-9.html#h-78049"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-10.html#h-78066"><span class="HTitleText2">Rules About Violations</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-10.html#h-78082"><span class="HTitleText2">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>128 - </span><a href="page-10.html#h-78091"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-10.html#h-78092"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-10.html#h-78103"><span class="HTitleText2">Analysis</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-10.html#h-78111"><span class="HTitleText2">Trademarks</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-10.html#h-78117"><span class="HTitleText2">Evidence and Procedure</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-10.html#h-78149"><span class="HTitleText2">Regulations and Exemptions</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-11.html#h-78234"><span class="HTitleText2">Fees</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-11.html#h-78265"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-11.html#h-78278"><span class="HTitleText2">Technical Assistance</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-11.html#h-78281"><span class="HTitleText2">Amendments to Schedules</span></a>
</li>
<li><span class='sectionRange'>151.1 - </span><a href="page-11.html#h-78291"><span class="HTitleText2">Review and Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="page-11.html#h-78297"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Transitional Provisions and Related, Consequential and Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="page-11.html#h-78298"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-12.html#h-78423"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>162 - </span><a href="page-12.html#h-78424"><span class="HTitleText3"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-12.html#h-78429"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="page-12.html#h-78430"><span class="HTitleText3"><cite class="XRefExternalAct">Criminal Records Act</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-12.html#h-78432"><span class="HTitleText3"><cite class="XRefExternalAct">Identification of Criminals Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-12.html#h-78435"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-12.html#h-78437"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-12.html#h-78440"><span class="HTitleText3"><cite class="XRefExternalAct">Mutual Legal Assistance in Criminal Matters Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-12.html#h-78442"><span class="HTitleText3"><cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-12.html#h-78444"><span class="HTitleText3"><cite class="XRefExternalAct">Seized Property Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-12.html#h-78454"><span class="HTitleText3"><cite class="XRefExternalAct">Firearms Act</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="page-12.html#h-78456"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-12.html#h-78458"><span class="HTitleText3"><cite class="XRefExternalAct">Youth Criminal Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-12.html#h-78460"><span class="HTitleText3">International Interests in Mobile Equipment (aircraft equipment) Act</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-12.html#h-78462"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Consumer Product Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-13.html#h-78464"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Victims Bill of Rights</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="page-13.html#h-78466"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>193.1 - </span><a href="page-13.html#h-78473"><span class="HLabel1">PART 12.1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Cannabis Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-13.html#h-78475"><span class="HLabel1">PART 13</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Controlled Drugs and Substances Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="page-13.html#h-78476"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-13.html#h-78490"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>207 - </span><a href="page-13.html#h-78492"><span class="HLabel1">PART 14</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>207 - </span><a href="page-13.html#h-78493"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="page-13.html#h-78512"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>226 - </span><a href="page-13.html#h-78514"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-14.html#h-78520"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-15.html#h-78526"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-16.html#h-78533"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-17.html#h-78541"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-18.html#h-78549"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-19.html#h-78557"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>

</nav>

