<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Public Service Week: Serving Canadians Better Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-363376"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-363379"><span class="HTitleText1">National Public Service Week</span></a>
</li></ul>
</li></ul>

</nav>

