<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1992 sur le transport des marchandises dangereuses</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Accords avec les provinces</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Indications de danger, règles et normes de sécurité</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Plan d’intervention d’urgence</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">Contenants</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText1">Inspecteurs et autres personnes désignées</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText1">Solvabilité</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText1">Obligation d’agir</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText1">Mesures d’intervention</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText1">Responsabilité personnelle</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HTitleText1">Recouvrement des frais et dépens</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-16"><span class="HTitleText1">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-17"><span class="HTitleText1">Recherches</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-18"><span class="HTitleText1">Règlements et arrêtés</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-19"><span class="HTitleText1">Permis et ordres</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-20"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-21"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>43 à 45 - </span><a href="#h-22"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-23"><span class="HTitleText1">Projet de loi c-13</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-24"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><a href="#h-442157"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
