<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Security of Information Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Miscellaneous Offences</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Special Operational Information and Persons Permanently Bound to Secrecy</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText2">Communications with Foreign Entities or Terrorist Groups</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText2">Economic Espionage</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-8"><span class="HTitleText2">Foreign-influenced or Terrorist-influenced Threats or Violence</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText2">Harbouring or Concealing</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText2">Preparatory Acts</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-11"><span class="HTitleText2">Conspiracy, Attempts, Etc.</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-12"><span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-13"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
