<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur les paiements</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-72292"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-72297"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-72349"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-72357"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Association canadienne des paiements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-72358"><span class="HTitleText2">Constitution et adhésion</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-72412"><span class="HTitleText2">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-72434"><span class="HTitleText2">Siège social</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-72439"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-72495"><span class="HTitleText2">Président du conseil</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-72507"><span class="HTitleText2">Président de l’Association</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-72517"><span class="HTitleText2">Diligence</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-72524"><span class="HTitleText2">Fonctions et pouvoirs du conseil</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-72564"><span class="HTitleText2">Règles, déclarations de principe et normes</span></a>
</li>
<li><span class='sectionRange'>19.2 - </span><a href="#h-72585"><span class="HTitleText2">Annulation</span></a>
</li>
<li><span class='sectionRange'>19.3 - </span><a href="#h-72595"><span class="HTitleText2">Instructions</span></a>
</li>
<li><span class='sectionRange'>19.4 - </span><a href="#h-72611"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-72620"><span class="HTitleText2">Comités du conseil</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="#h-72638"><span class="HTitleText2">Comité consultatif des intervenants</span></a>
</li>
<li><span class='sectionRange'>21.4 - </span><a href="#h-72660"><span class="HTitleText2">Comité consultatif des membres</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-72670"><span class="HTitleText2">Budgets</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-72678"><span class="HTitleText2">Plan d’entreprise et rapport annuel d’activités</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-72703"><span class="HTitleText2">Assemblée annuelle</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-72711"><span class="HTitleText2">Vérificateur</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-72720"><span class="HTitleText2">Exercice</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-72725"><span class="HTitleText2">Participation par moyen électronique</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-72734"><span class="HTitleText2">Droits et obligations des membres</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-72740"><span class="HTitleText2">Insolvabilité</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-72767"><span class="HTitleText2">Application des autres lois</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-72775"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-72788"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Systèmes de paiement désignés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-72789"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-72798"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-72803"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-72822"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-72838"><span class="HTitleText2">Lignes directrices et instructions</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-72868"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-72878"><span class="HTitleText2">Participants</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-72888"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

