<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Fertilizers Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-222127"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-222132"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-222161"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-222189"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="#h-222240"><span class="HTitleText1">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>5.2 - </span><a href="#h-222252"><span class="HTitleText1">Registrations and Licences</span></a>
</li>
<li><span class='sectionRange'>5.5 - </span><a href="#h-222285"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-222298"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="#h-222374"><span class="HTitleText1">Analysis</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="#h-222381"><span class="HTitleText1">Limitation on Liability</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-222392"><span class="HTitleText1">Offences and Punishment</span></a>
</li></ul>
</li></ul>

</nav>

