<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Office national de l’énergie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-370769"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-370774"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-370829"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-370834"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Office national de l’énergie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-370835"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-370868"><span class="HTitleText2">Dirigeants</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-370897"><span class="HTitleText2">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-370911"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-370920"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-370939"><span class="HTitleText2">Pouvoirs de l’Office</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-371032"><span class="HTitleText2">Ordonnances et décisions</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-371112"><span class="HTitleText2">Droits, redevances et frais</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-371124"><span class="HTitleText2">Preuve des documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-371131"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Fonctions consultatives</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="#h-371160"><span class="HLabel1">PARTIE II.1</span> - <span class="HTitleText1">Droits, production et usage rationnel du pétrole et du gaz</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28.1 - </span><a href="#h-371161"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>28.2 - </span><a href="#h-371166"><span class="HTitleText2">Déclarations de découverte importante et de découverte exploitable</span></a>
</li>
<li><span class='sectionRange'>28.3 - </span><a href="#h-371184"><span class="HTitleText2">Permis de travaux et autorisations</span></a>
</li>
<li><span class='sectionRange'>28.4 - </span><a href="#h-371189"><span class="HTitleText2">Délégué à l’exploitation et délégué à la sécurité</span></a>
</li>
<li><span class='sectionRange'>28.7 - </span><a href="#h-371223"><span class="HTitleText2">Ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-371237"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Construction, exploitation et cessation d’exploitation des pipelines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-371238"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-371266"><span class="HTitleText2">Tracé des pipelines</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-371282"><span class="HTitleText2">Plan, profil et livre de renvoi</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-371294"><span class="HTitleText2">Détermination et acceptation du tracé détaillé</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-371346"><span class="HTitleText2">Erreurs</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-371360"><span class="HTitleText2">Obligations des directeurs de l’Enregistrement</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-371374"><span class="HTitleText2">Autres plans</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-371379"><span class="HTitleText2">Déviations</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-371389"><span class="HTitleText2">Détournement ou changement de tracé d’un pipeline</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-371405"><span class="HTitleText2">Autorisation de mise en service</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-371413"><span class="HTitleText2">Réglementation de la construction, de l’exploitation et de la cessation d’exploitation</span></a>
</li>
<li><span class='sectionRange'>48.11 - </span><a href="#h-371457"><span class="HTitleText2">Principe du pollueur-payeur</span></a>
</li>
<li><span class='sectionRange'>48.12 - </span><a href="#h-371462"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>48.13 - </span><a href="#h-371500"><span class="HTitleText2">Obligations financières</span></a>
</li>
<li><span class='sectionRange'>48.15 - </span><a href="#h-371533"><span class="HTitleText2">Remboursement par les compagnies</span></a>
</li>
<li><span class='sectionRange'>48.16 - </span><a href="#h-371538"><span class="HTitleText2">Compagnie désignée</span></a>
</li>
<li><span class='sectionRange'>48.18 - </span><a href="#h-371569"><span class="HTitleText2">Tribunal d’indemnisation en matière de pipelines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48.18 - </span><a href="#h-371570"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>48.24 - </span><a href="#h-371610"><span class="HTitleText3">Président et personnel</span></a>
</li>
<li><span class='sectionRange'>48.29 - </span><a href="#h-371634"><span class="HTitleText3">Attributions du Tribunal</span></a>
</li>
<li><span class='sectionRange'>48.35 - </span><a href="#h-371667"><span class="HTitleText3">Demandes d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>48.39 - </span><a href="#h-371707"><span class="HTitleText3">Paiement par l’Office</span></a>
</li>
<li><span class='sectionRange'>48.43 - </span><a href="#h-371735"><span class="HTitleText3">Réexamen</span></a>
</li>
<li><span class='sectionRange'>48.45 - </span><a href="#h-371757"><span class="HTitleText3">Révision judiciaire</span></a>
</li>
<li><span class='sectionRange'>48.46 - </span><a href="#h-371762"><span class="HTitleText3">Affectation et remboursement</span></a>
</li>
<li><span class='sectionRange'>48.47 - </span><a href="#h-371783"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>48.49 - </span><a href="#h-371815"><span class="HTitleText2">Mesures liées à la cessation d’exploitation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-371825"><span class="HTitleText2">Inspecteurs</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-371886"><span class="HTitleText2">Certificats</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-371983"><span class="HTitleText2">Annulation et suspension</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-371993"><span class="HTitleText2">Conditions du certificat</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-371998"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="#h-372027"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Construction et exploitation de lignes de transport d’électricité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58.1 - </span><a href="#h-372028"><span class="HTitleText2">Lignes internationales</span></a>
</li>
<li><span class='sectionRange'>58.11 - </span><a href="#h-372033"><span class="HTitleText2">Permis</span></a>
</li>
<li><span class='sectionRange'>58.15 - </span><a href="#h-372062"><span class="HTitleText2">Certificats</span></a>
</li>
<li><span class='sectionRange'>58.17 - </span><a href="#h-372107"><span class="HTitleText2">Emplacement et construction régis par loi provinciale</span></a>
</li>
<li><span class='sectionRange'>58.23 - </span><a href="#h-372137"><span class="HTitleText2">Emplacement et construction régis par loi fédérale</span></a>
</li>
<li><span class='sectionRange'>58.28 - </span><a href="#h-372176"><span class="HTitleText2">Détournements, changements de tracé, franchissements et cessation d’exploitation</span></a>
</li>
<li><span class='sectionRange'>58.35 - </span><a href="#h-372307"><span class="HTitleText2">Permis et certificats</span></a>
</li>
<li><span class='sectionRange'>58.38 - </span><a href="#h-372326"><span class="HTitleText2">Divers</span></a>
</li>
<li><span class='sectionRange'>58.4 - </span><a href="#h-372342"><span class="HTitleText2">Lignes interprovinciales</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.5 - </span><a href="#h-372352"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Transport, droits et tarifs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58.5 - </span><a href="#h-372353"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-372358"><span class="HTitleText2">Pouvoirs de l’Office</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-372363"><span class="HTitleText2">Production du tarif</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-372377"><span class="HTitleText2">Droits justes et raisonnables</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-372392"><span class="HTitleText2">Rejet ou suspension du tarif</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-372401"><span class="HTitleText2">Distinction injuste</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-372419"><span class="HTitleText2">Stipulations de non-responsabilité</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-372429"><span class="HTitleText2">Transport du pétrole ou du gaz</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-372442"><span class="HTitleText2">Transport et vente du gaz</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-372452"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Pouvoirs des compagnies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-372453"><span class="HTitleText2">Pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-372490"><span class="HTitleText2">Prise de possession et utilisation de terrains</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-372546"><span class="HTitleText2">Mines et minéraux</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-372574"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-372585"><span class="HTitleText2">Acquisition des terrains</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-372617"><span class="HTitleText2">Procédure de négociation</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-372633"><span class="HTitleText2">Procédure d’arbitrage</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-372779"><span class="HTitleText2">Droit d’accès</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-372810"><span class="HTitleText2">Construction malgré la présence d’installations de service public</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-372929"><span class="HTitleText2">Exécutions</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-372942"><span class="HTitleText2">Interprétation de lois spéciales</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="#h-372949"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Exportations et importations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-372950"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Pétrole et gaz</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-372951"><span class="HTitleText3">Interdiction</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-372956"><span class="HTitleText3">Délivrance de licences</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-372990"><span class="HTitleText3">Annulation et suspension</span></a>
</li>
<li><span class='sectionRange'>119.01 - </span><a href="#h-373002"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>119.02 - </span><a href="#h-373023"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Électricité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119.02 - </span><a href="#h-373024"><span class="HTitleText3">Interdiction</span></a>
</li>
<li><span class='sectionRange'>119.03 - </span><a href="#h-373029"><span class="HTitleText3">Permis</span></a>
</li>
<li><span class='sectionRange'>119.07 - </span><a href="#h-373061"><span class="HTitleText3">Décrets</span></a>
</li>
<li><span class='sectionRange'>119.08 - </span><a href="#h-373073"><span class="HTitleText3">Licences</span></a>
</li>
<li><span class='sectionRange'>119.09 - </span><a href="#h-373088"><span class="HTitleText3">Conditions — permis et licences</span></a>
</li>
<li><span class='sectionRange'>119.094 - </span><a href="#h-373111"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>119.1 à 119.7 - </span><a href="#h-373120"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Mise en oeuvre d’accords de libre-échange</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-373162"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>123 - </span><a href="#h-373182"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Marché interprovincial du pétrole et du gaz</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-373183"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-373192"><span class="HTitleText2">Contrôle de l’Office</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-373200"><span class="HTitleText2">Délivrance des licences</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-373217"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-373226"><span class="HTitleText2">Infractions et application</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="#h-373236"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="#h-373237"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-373273"><span class="HTitleText2">Détermination de la peine</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-373343"><span class="HTitleText2">Rapport au Parlement</span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-373348"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="#h-373349"><span class="HTitleText2">Attributions de l’Office</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-373373"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-373402"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-373425"><span class="HTitleText2">Révision</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-373460"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-373469"><span class="HTitleText2">Recouvrement des pénalités</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-373484"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
