<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Convention Canada-Belgique en matière d’impôt sur le revenu (1976)</a><ul class="TocIndent"><li><span class='sectionRange'>4 - </span><a href="#h-41481"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Convention Canada-Belgique en matière d’impôt sur le revenu</span></a>
</li>
<li><a href="#h-41494"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement du Royaume de Belgique en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li></ul>
</li></ul>

</nav>

