<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Public Health Agency of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-401108"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-401111"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-401120"><span class="HTitleText1">Public Health Agency of Canada</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="page-1.html#h-401130"><span class="HTitleText1">President</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-401143"><span class="HTitleText1">Chief Public Health Officer</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-401187"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-401204"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-401235"><span class="HTitleText1">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-401236"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-401238"><span class="HTitleText2"><cite class="XRefExternalAct">Quarantine Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-1.html#h-401240"><span class="HTitleText1">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-401242"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

