<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le Service administratif des tribunaux judiciaires</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-109368"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-109371"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-109377"><span class="HTitleText1">Service administratif des tribunaux judiciaires</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-109387"><span class="HTitleText1">Administrateur en chef</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-109408"><span class="HTitleText1">Pouvoirs et attributions de l’administrateur en chef</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-109418"><span class="HTitleText1">Juges en chef</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-109439"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-109442"><span class="HTitleText1">Spécialistes à contrat</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-109445"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>13 à 58 - </span><a href="page-1.html#h-109451"><span class="HTitleText1">Modification de la Loi sur la Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>59 à 81 - </span><a href="page-1.html#h-109453"><span class="HTitleText1">Modification de la Loi sur la Cour canadienne de l’impôt</span></a>
</li>
<li><span class='sectionRange'>82 à 111 - </span><a href="page-1.html#h-109455"><span class="HTitleText1">Modification de la Loi sur les juges</span></a>
</li>
<li><span class='sectionRange'>112 et 113 - </span><a href="page-1.html#h-109457"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 et 113 - </span><a href="page-1.html#h-109458"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="page-1.html#h-109460"><span class="HTitleText2">Loi de mise en oeuvre de la Convention sur les mines antipersonnel</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-1.html#h-109462"><span class="HTitleText2">Loi sur le Fonds de bienfaisance de l’armée</span></a>
</li>
<li><span class='sectionRange'>116 et 117 - </span><a href="page-1.html#h-109464"><span class="HTitleText2">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-1.html#h-109466"><span class="HTitleText2">Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-1.html#h-109469"><span class="HTitleText2">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="page-1.html#h-109471"><span class="HTitleText2">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-1.html#h-109473"><span class="HTitleText2">Loi sur les transports au Canada</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-1.html#h-109475"><span class="HTitleText2">Loi sur la détermination de la participation et du contrôle canadiens</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-1.html#h-109477"><span class="HTitleText2">Loi de mise en oeuvre de l’Accord sur la Station spatiale internationale civile</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-1.html#h-109479"><span class="HTitleText2">Loi sur l’arbitrage commercial</span></a>
</li>
<li><span class='sectionRange'>126 à 129 - </span><a href="page-1.html#h-109481"><span class="HTitleText2">Loi sur la concurrence</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-1.html#h-109483"><span class="HTitleText2">Loi sur le Tribunal de la concurrence</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-1.html#h-109485"><span class="HTitleText2">Loi sur le droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-1.html#h-109487"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-1.html#h-109489"><span class="HTitleText2">Loi sur les Cris et les Naskapis du Québec</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-1.html#h-109491"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-1.html#h-109493"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-1.html#h-109495"><span class="HTitleText2">Loi d’urgence sur les approvisionnements d’énergie</span></a>
</li>
<li><span class='sectionRange'>137 à 140 - </span><a href="page-1.html#h-109497"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-1.html#h-109499"><span class="HTitleText2">Loi sur l’extradition</span></a>
</li>
<li><span class='sectionRange'>142 et 143 - </span><a href="page-1.html#h-109501"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>144 à 147 - </span><a href="page-1.html#h-109503"><span class="HTitleText2">Loi sur l’immigration</span></a>
</li>
<li><span class='sectionRange'>148 et 149 - </span><a href="page-1.html#h-109505"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-1.html#h-109507"><span class="HTitleText2">Loi sur la Convention relative aux contrats de vente internationale de marchandises</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-1.html#h-109509"><span class="HTitleText2">Loi d’interprétation</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-1.html#h-109511"><span class="HTitleText2">Loi sur Investissement Canada</span></a>
</li>
<li><span class='sectionRange'>153 et 154 - </span><a href="page-1.html#h-109513"><span class="HTitleText2">Loi sur la défense nationale</span></a>
</li>
<li><span class='sectionRange'>155 à 157 - </span><a href="page-1.html#h-109515"><span class="HTitleText2">Loi sur les langues officielles</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-1.html#h-109517"><span class="HTitleText2">Loi sur la protection des obtentions végétales</span></a>
</li>
<li><span class='sectionRange'>159 et 160 - </span><a href="page-1.html#h-109519"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-1.html#h-109521"><span class="HTitleText2">Loi sur le recyclage des produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>162 et 163 - </span><a href="page-1.html#h-109523"><span class="HTitleText2">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-1.html#h-109525"><span class="HTitleText2">Loi sur l’emploi dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>165 à 167 - </span><a href="page-1.html#h-109527"><span class="HTitleText2">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-1.html#h-109529"><span class="HTitleText2">Loi sur la sécurité ferroviaire</span></a>
</li>
<li><span class='sectionRange'>169 à 173 - </span><a href="page-1.html#h-109531"><span class="HTitleText2">Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-1.html#h-109533"><span class="HTitleText2">Loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>175 et 176 - </span><a href="page-1.html#h-109535"><span class="HTitleText2">Loi sur la Cour suprême</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-1.html#h-109537"><span class="HTitleText2">Loi sur les marques de commerce</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-1.html#h-109539"><span class="HTitleText2">Loi sur la Convention des Nations Unies concernant les sentences arbitrales étrangères</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="page-1.html#h-109541"><span class="HTitleText2">Loi sur le Tribunal des anciens combattants (révision et appel)</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-1.html#h-109543"><span class="HTitleText2">Loi sur l’autonomie gouvernementale des premières nations du Yukon</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-1.html#h-109545"><span class="HTitleText2">Loi sur l’Office des droits de surface du Yukon</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-1.html#h-109547"><span class="HTitleText2">Nouvelle terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="page-1.html#h-109565"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>193 à 198 - </span><a href="page-2.html#h-109612"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-2.html#h-109614"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-3.html#h-109618"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>

