<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Old Age Security Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-387581"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-387586"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-387660"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Monthly Pension</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-387661"><span class="HTitleText2">Pension Payable</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-387729"><span class="HTitleText2">Information from Statistics Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-387734"><span class="HTitleText2">Amount of Pension</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-387768"><span class="HTitleText2">Payment of Pension</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-387820"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Monthly Guaranteed Income Supplement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-387821"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-387829"><span class="HTitleText2">Supplement Payable</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-387866"><span class="HTitleText2">Amount of Supplement</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-387961"><span class="HTitleText2">Calculation of Income</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-387979"><span class="HTitleText2">Statement or Estimate of Income</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-388033"><span class="HTitleText2">Spouses and Common-law Partners</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-388090"><span class="HTitleText2">Payment of Supplement</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-388102"><span class="HTitleText2">Adjustment of Payments</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-388109"><span class="HTitleText2">Cessation of Payment</span></a>
</li>
<li><span class='sectionRange'>18.2 - </span><a href="#h-388114"><span class="HTitleText2">Cancellation of Payment</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-388124"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Monthly Allowances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-388125"><span class="HTitleText2">Allowance Payable</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-388263"><span class="HTitleText2">Amount of Allowance</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-388421"><span class="HTitleText2">Commencement of Allowance</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-388438"><span class="HTitleText2">Payment of Allowance</span></a>
</li></ul>
</li><li><span class='sectionRange'>26.1 - </span><a href="#h-388459"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26.1 - </span><a href="#h-388460"><span class="HTitleText2">Effect of Waiver</span></a>
</li>
<li><span class='sectionRange'>26.2 - </span><a href="#h-388465"><span class="HTitleText2">Inviting Applications</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-388470"><span class="HTitleText2">Adjustment in Consumer Price Index</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-388475"><span class="HTitleText2">Reconsiderations and Appeals</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="#h-388496"><span class="HTitleText2">Incapacity</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-388514"><span class="HTitleText2">Death</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-388543"><span class="HTitleText2">Erroneous Advice or Administrative Error</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-388548"><span class="HTitleText2">Availability of Information</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-388578"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-388611"><span class="HTitleText2">Form of Documents</span></a>
</li>
<li><span class='sectionRange'>35.1 - </span><a href="#h-388616"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-388677"><span class="HTitleText2">Oaths and Affidavits</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-388685"><span class="HTitleText2">Agreements</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-388739"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="#h-388755"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>44.2 - </span><a href="#h-388781"><span class="HTitleText2">Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-388825"><span class="HTitleText2">Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-388830"><span class="HTitleText2">Administration and Annual Report</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

