<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada-Germany Tax Agreement Act, 1982</a><ul class="TocIndent"><li><a href="#h-136750"><span class="scheduleLabel">PART 1</span> - <span class="scheduleTitleText"> - Agreement Between Canada and the Federal Republic of Germany for the Avoidance of Double Taxation with Respect to Taxes on Income and Certain Other Taxes, the Prevention of Fiscal Evasion and the Assistance in Tax Matters</span></a>
</li>
<li><a href="#h-137073"><span class="scheduleLabel">PART 2</span> - <span class="scheduleTitleText"> - Protocol to the Agreement Between Canada and the Federal Republic of Germany for the Avoidance of Double Taxation with Respect to Taxes on Income and Certain Other Taxes, the Prevention of Fiscal Evasion and the Assistance in Tax Matters</span></a>
</li></ul>
</li></ul>

</nav>

