<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les subventions au développement régional</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-416441"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-416446"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-416471"><span class="HTitleText1">Désignation de régions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-416481"><span class="HTitleText1">Subventions au développement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-416482"><span class="HTitleText2">Autorisation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-416490"><span class="HTitleText2">Maximum</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-416517"><span class="HTitleText2">Détermination du montant</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-416528"><span class="HTitleText2">Établissements exclus</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-416538"><span class="HTitleText2">Restrictions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-416568"><span class="HTitleText2">Paiement des subventions au développement</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-416586"><span class="HTitleText1">Fiscalité</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-416591"><span class="HTitleText1">Services de main-d’oeuvre</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-416601"><span class="HTitleText1">Garanties de prêts</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-416630"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-416639"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-416659"><span class="HTitleText1">Conseil des subventions au développement régional</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
