<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Natural Resources Transfer (School Lands) Amendment Act, 1961</a><ul class="TocIndent"><li><a href="#h-364206"><span class="scheduleLabel">SCHEDULE A</span> - <span class="scheduleTitleText"> - <em>Memorandum of Agreement</em></span> - <span class="scheduleTitleText"> - Made this thirteenth day of July, 1961</span></a>
</li>
<li><a href="#h-364226"><span class="scheduleLabel">SCHEDULE B</span> - <span class="scheduleTitleText"> - <em>Memorandum of Agreement</em></span> - <span class="scheduleTitleText"> - Made this thirteenth day of July, 1961</span></a>
</li>
<li><a href="#h-364246"><span class="scheduleLabel">SCHEDULE C</span> - <span class="scheduleTitleText"> - <em>Memorandum of Agreement</em></span> - <span class="scheduleTitleText"> - Made this fourteenth day of July, 1961</span></a>
</li></ul>
</li></ul>

</nav>

