<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
British Columbia Grain Handling Operations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-33594"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-33597"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-33600"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Vancouver Grain Handling Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-33601"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-33610"><span class="HTitleText2">Grain Handling Operations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-33635"><span class="HTitleText2">Mediator-Arbitrator</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-33652"><span class="HTitleText2">Amendment of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-33655"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-33667"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Prince Rupert Grain Handling Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-33668"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-33676"><span class="HTitleText2">Grain Handling Operations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-33701"><span class="HTitleText2">Mediator-Arbitrator</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-33718"><span class="HTitleText2">Amendment of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-33721"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-33733"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-33740"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
