<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi relative aux cessions d’aéroports</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1412"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1415"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1430"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1433"><span class="HTitleText1">Langues officielles</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1443"><span class="HTitleText1">Pensions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-1462"><span class="HTitleText1">Impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-1478"><span class="HTitleText1">Saisie et rétention d’aéronefs</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-1499"><span class="HTitleText1">Placements autorisés</span></a>
</li></ul>
</li></ul>

</nav>

