<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1995 sur les opérations portuaires de la côte ouest</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Supervision du débardage</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Obligations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Prolongation de la convention collective</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">Médiateur-arbitre</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Frais</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">Modification de la convention collective</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-11"><span class="scheduleLabel"><span class="otherLang" lang="en">SCHEDULE</span> / ANNEXE</span>  / paragraphe 2(1))</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
