<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Depository Bills and Notes Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-171632"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-171635"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-171655"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-171658"><span class="HTitleText1">Depository Bills and Notes</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-171700"><span class="HTitleText1">Liabilities and Actions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-171735"><span class="HTitleText1">Amendment to Financial Administration Act</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
