<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des Forces canadiennes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Services de réorientation professionnelle</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Services de réadaptation, assistance professionnelle et avantages financiers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Services de réadaptation et assistance professionnelle</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText2">Allocation pour perte de revenus</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText2">Prestation de retraite supplémentaire</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-10"><span class="HTitleText2">Allocation de soutien du revenu</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-11"><span class="HTitleText2">Allocation pour déficience permanente</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-12"><span class="HTitleText2">Allocation de sécurité du revenu de retraite</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-13"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-14"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Blessure grave, invalidité, décès et captivité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-15"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="#h-16"><span class="HTitleText2">Indemnité pour blessure grave</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-17"><span class="HTitleText2">Indemnité d’invalidité</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-18"><span class="HTitleText2">Indemnité de décès</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-19"><span class="HTitleText2">Allocation vestimentaire</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-20"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-21"><span class="HTitleText2">Indemnité de captivité</span></a>
</li></ul>
</li><li><span class='sectionRange'>65.1 - </span><a href="#h-22"><span class="HLabel1">PARTIE 3.1</span> - <span class="HTitleText1">Allocation pour relève d’un aidant familial</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-23"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Généralités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="#h-24"><span class="HTitleText2">Soins de santé</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-25"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-26"><span class="HTitleText2">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>75.1 - </span><a href="#h-27"><span class="HTitleText2">Transition à la vie civile</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-28"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-29"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-30"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-31"><span class="HTitleText2">Révision</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-32"><span class="HTitleText2">Trop-perçu</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-33"><span class="HTitleText2">Divers</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-34"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-35"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions transitoires, modifications connexes, disposition de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-36"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-37"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-38"><span class="HTitleText3">Loi sur l’aide en matière d’éducation aux enfants des anciens combattants décédés</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-39"><span class="HTitleText3">Loi sur le ministère des Anciens Combattants</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-40"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-41"><span class="HTitleText3">Loi d’indemnisation des militaires ayant subi des blessures</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-42"><span class="HTitleText3">Loi sur les pensions</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-43"><span class="HTitleText3">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-44"><span class="HTitleText3">Loi sur le Tribunal des anciens combattants (révision et appel)</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-45"><span class="HTitleText3">Loi sur l’emploi dans la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="#h-46"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-47"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-48"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-49"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-50"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
