<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2001 sur l’accise</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-174268"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-174271"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-174498"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Application et administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-2.html#h-174499"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-174502"><span class="HTitleText2">Personnel assurant l’exécution</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-174527"><span class="HTitleText2">Enquêtes</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-2.html#h-174541"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Licences, agréments et autorisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-2.html#h-174542"><span class="HTitleText2">Licences et agréments</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-174565"><span class="HTitleText2">Autorisations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-174583"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-174594"><span class="HTitleText2">Entrepôts d’accise spéciaux</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-174613"><span class="HTitleText2">Boutiques hors taxes</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-174616"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-3.html#h-174642"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Tabac</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-3.html#h-174643"><span class="HTitleText2">Réglementation du tabac</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-174878"><span class="HTitleText2">Droit sur le tabac</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-174940"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-5.html#h-175000"><span class="HTitleText2">Droits spéciaux sur les produits du tabac</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="page-6.html#h-175050"><span class="HLabel1">PARTIE 3.1</span> - <span class="HTitleText1">Taxe sur les stocks de cigarettes</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-6.html#h-175124"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Alcool</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="page-6.html#h-175125"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-7.html#h-175194"><span class="HTitleText2">Alcool en vrac</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-7.html#h-175249"><span class="HTitleText2">Contenants spéciaux de spiritueux</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-7.html#h-175265"><span class="HTitleText2">Contenants spéciaux de vin</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-7.html#h-175281"><span class="HTitleText2">Alcool emballé</span></a>
</li>
<li><span class='sectionRange'>93.1 - </span><a href="page-8.html#h-175360"><span class="HTitleText2">Préparations assujetties à des restrictions</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-8.html#h-175369"><span class="HTitleText2">Alcool dénaturé et alcool spécialement dénaturé</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-8.html#h-175425"><span class="HTitleText2">Responsabilité en matière de spiritueux en vrac</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-8.html#h-175465"><span class="HTitleText2">Responsabilité en matière de vin en vrac</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-9.html#h-175508"><span class="HTitleText2">Imposition et paiement du droit sur l’alcool</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-10.html#h-175698"><span class="HTitleText2">Assujettissement des exploitants agréés d’entrepôt d’accise et des utilisateurs agréés</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-10.html#h-175716"><span class="HTitleText2">Utilisations et sorties d’alcool non assujetties au droit</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-10.html#h-175765"><span class="HTitleText2">Détermination du volume d’alcool</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-11.html#h-175777"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>158.01 - </span><a href="page-11.html#h-175843"><span class="HLabel1">PARTIE 4.1</span> - <span class="HTitleText1">Cannabis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>158.01 - </span><a href="page-11.html#h-175844"><span class="HTitleText2">Exclusions</span></a>
</li>
<li><span class='sectionRange'>158.02 - </span><a href="page-11.html#h-175852"><span class="HTitleText2">Production et estampillage du cannabis</span></a>
</li>
<li><span class='sectionRange'>158.17 - </span><a href="page-12.html#h-176020"><span class="HTitleText2">Responsabilité en matière de cannabis</span></a>
</li>
<li><span class='sectionRange'>158.19 - </span><a href="page-12.html#h-176043"><span class="HTitleText2">Imposition et acquittement des droits sur le cannabis</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="page-13.html#h-176184"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions générales concernant les droits et autres sommes exigibles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="page-13.html#h-176185"><span class="HTitleText2">Périodes d’exercice</span></a>
</li>
<li><span class='sectionRange'>159.1 - </span><a href="page-13.html#h-176202"><span class="HTitleText2">Périodes de déclaration</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-14.html#h-176248"><span class="HTitleText2">Déclarations et paiement des droits et autres sommes</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-14.html#h-176316"><span class="HTitleText2">Intérêts</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-14.html#h-176339"><span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-15.html#h-176451"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-16.html#h-176604"><span class="HTitleText2">Opposition aux cotisations</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-17.html#h-176653"><span class="HTitleText2">Appel</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-17.html#h-176756"><span class="HTitleText2">Registres et renseignements</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="page-19.html#h-177004"><span class="HTitleText2">Faillites et réorganisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="page-19.html#h-177058"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="page-19.html#h-177059"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-21.html#h-177240"><span class="HTitleText2">Produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-21.html#h-177274"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="page-22.html#h-177436"><span class="HTitleText2">Imposition des pénalités</span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="page-22.html#h-177454"><span class="HTitleText2">Mandats de perquisition</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="page-23.html#h-177486"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-23.html#h-177530"><span class="HTitleText2">Sort des choses saisies</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="page-23.html#h-177557"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="page-23.html#h-177564"><span class="HTitleText2">Révision de la pénalité imposée ou de la saisie</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-24.html#h-177650"><span class="HTitleText2">Revendication des tiers</span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="page-24.html#h-177712"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-26.html#h-177986"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="page-27.html#h-178056"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="page-27.html#h-178133"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Dispositions transitoires, modifications corrélatives et connexes et dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>305 - </span><a href="page-27.html#h-178134"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>321 à 325 - </span><a href="page-29.html#h-178280"><span class="HTitleText2">Modifications corrélatives et connexes</span></a>
</li>
<li><span class='sectionRange'>408 à 411 - </span><a href="page-29.html#h-178286"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>412 à 421 - </span><a href="page-29.html#h-178288"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Modifications concernant la taxe d’accise sur les produits du tabac</span></a>
</li>
<li><span class='sectionRange'>422 à 432 - </span><a href="page-29.html#h-178290"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Modifications concernant les provisions de bord</span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="page-29.html#h-178292"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-30.html#h-178296"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Taux du droit sur les produits du tabac</span></a>
</li>
<li><a href="page-31.html#h-178313"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Droit additionnel sur les cigares</span></a>
</li>
<li><a href="page-32.html#h-178322"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Taux des droits spéciaux sur certains produits de tabac fabriqué</span></a>
</li>
<li><a href="page-33.html#h-178354"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - Taux du droit sur les spiritueux</span></a>
</li>
<li><a href="page-34.html#h-178364"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - Taux du droit spécial sur les spiritueux</span></a>
</li>
<li><a href="page-35.html#h-178367"><span class="scheduleLabel">ANNEXE 6</span> <span class="scheduleTitleText"> - Taux du droit sur le vin</span></a>
</li>
<li><a href="page-36.html#h-178381"><span class="scheduleLabel">ANNEXE 7</span> <span class="scheduleTitleText"> - Droit sur les produits du cannabis</span></a>
</li></ul>
</li></ul>

</nav>

