<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’aménagement du territoire et l’évaluation des projets au Nunavut</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText1">Consultations</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Commissions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Commission d’aménagement du Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText3">Mise en place</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText3">Attributions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText3">Réunions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText3">Règlements administratifs et règles</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText2">Commission du Nunavut chargée de l’examen des répercussions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText3">Mise en place</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText3">Attributions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText3">Réunions</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText3">Règlements administratifs et règles</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText3">Comités</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText2">Dispositions générales concernant les commissions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText3">Membres</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-20"><span class="HTitleText3">Personnel</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-21"><span class="HTitleText3">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-22"><span class="HTitleText3">Statut et pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-23"><span class="HTitleText3">Siège</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-24"><span class="HTitleText3">Langues</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-25"><span class="HTitleText3">Règlements administratifs et règles</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-26"><span class="HTitleText3">Dispositions financières</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-27"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Aménagement du territoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-28"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-29"><span class="HTitleText2">Politiques, priorités et objectifs</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-30"><span class="HTitleText2">Plans d’aménagement du territoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-31"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-32"><span class="HTitleText3">Élaboration</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-33"><span class="HTitleText3">Modification</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-34"><span class="HTitleText3">Révision périodique</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-35"><span class="HTitleText3">Mise en oeuvre</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-36"><span class="HTitleText2">Parcs et aires de préservation</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-37"><span class="HTitleText2">Municipalités</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-38"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Évaluation des projets à réaliser dans la région désignée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-39"><span class="HTitleText2">Définitions et disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-40"><span class="HTitleText2">Caractère obligatoire</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-41"><span class="HTitleText2">Examen par la Commission d’aménagement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-42"><span class="HTitleText3">Proposition relative au projet</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-43"><span class="HTitleText3">Plan d’aménagement en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-44"><span class="HTitleText4">Décision</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-45"><span class="HTitleText4">Projet conforme au plan d’aménagement</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-46"><span class="HTitleText4">Projet non conforme au plan d’aménagement</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-47"><span class="HTitleText4">Délai</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-48"><span class="HTitleText3">Absence de plan d’aménagement</span></a>
</li></ul>
</li><li><span class='sectionRange'>86 - </span><a href="#h-49"><span class="HTitleText2">Examen préalable par la Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-50"><span class="HTitleText2">Examen approfondi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-51"><span class="HTitleText3">Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-52"><span class="HTitleText3">Commission fédérale d’évaluation environnementale</span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-53"><span class="HTitleText2">Conditions visant la réalisation des projets</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="#h-54"><span class="HTitleText3">Compatibilité</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-55"><span class="HTitleText3">Programmes de suivi</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-56"><span class="HTitleText3">Mise en oeuvre</span></a>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="#h-57"><span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-58"><span class="HTitleText3">Modification du projet en cours d’évaluation</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-59"><span class="HTitleText3">Demandes en cours d’évaluation</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-60"><span class="HTitleText3">Modification du projet après l’évaluation</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-61"><span class="HTitleText3">Projets non réalisés</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-62"><span class="HTitleText3">Consultations</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-63"><span class="HTitleText3">Pluralité de ministres compétents</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-64"><span class="HTitleText3">Décisions motivées</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-65"><span class="HTitleText2">Cas particuliers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-66"><span class="HTitleText3">Sécurité nationale</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-67"><span class="HTitleText3">Situations d’urgence</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-68"><span class="HTitleText3">Réapprovisionnement et mouvements de navire</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-69"><span class="HTitleText3">Activités d’exploration, de préparation ou de mise en valeur</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-70"><span class="HTitleText3">Projets transfrontaliers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-71"><span class="HTitleText4">Examen par la Commission d’aménagement</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-72"><span class="HTitleText4">Examen préalable par la Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-73"><span class="HTitleText4">Examen approfondi</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="#h-74"><span class="HTitleText5">Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-75"><span class="HTitleText5">Commission fédérale d’évaluation environnementale ou formation conjointe</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-76"><span class="HTitleText3">Parcs et aires de préservation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-77"><span class="HTitleText4">Projets</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-78"><span class="HTitleText4">Création, abolition et modification de la superficie</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-79"><span class="HTitleText5">Disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-80"><span class="HTitleText5">Proposition</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-81"><span class="HTitleText5">Plan d’aménagement en vigueur</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-82"><span class="HTitleText5">Absence de plan d’aménagement</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-83"><span class="HTitleText5">Régime juridique applicable</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-84"><span class="HTitleText5">Travaux antérieurs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>184 - </span><a href="#h-85"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Examen des projets à réaliser à l’extérieur de la région désignée</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-86"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>189 - </span><a href="#h-87"><span class="HTitleText2">Définitions et disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-88"><span class="HTitleText2">Qualité pour agir en cours d’évaluation</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-89"><span class="HTitleText2">Coordination des activités</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-90"><span class="HTitleText2">Renseignements et documents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-91"><span class="HTitleText3">Obtention des renseignements</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-92"><span class="HTitleText3">Utilisation des renseignements</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-93"><span class="HTitleText3">Communication des renseignements et des documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>207 - </span><a href="#h-94"><span class="HTitleText2">Maintien des droits</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-95"><span class="HTitleText2">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>209 - </span><a href="#h-96"><span class="HTitleText3">Désignation</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-97"><span class="HTitleText3">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-98"><span class="HTitleText3">Ordres</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-99"><span class="HTitleText3">Coordination</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-100"><span class="HTitleText3">Injonction</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-101"><span class="HTitleText3">Interdictions, infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>220 - </span><a href="#h-102"><span class="HTitleText2">Questions judiciaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-103"><span class="HTitleText3">Compétence judiciaire</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-104"><span class="HTitleText3">Immunité</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-105"><span class="HTitleText3">Délais</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-106"><span class="HTitleText2">Surveillance générale</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-107"><span class="HTitleText2">Règlements et arrêtés</span></a>
</li></ul>
</li><li><span class='sectionRange'>231 - </span><a href="#h-108"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><a href="#h-109"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-110"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Organismes administratifs désignés</span></a>
</li>
<li><a href="#h-111"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Catégories d’ouvrages ou d’activités exemptés de l’examen préalable</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
