<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Customs Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-139182"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-139185"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-139327"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-139328"><span class="HTitleText2">Application to Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-139338"><span class="HTitleText2">Penalty and Interest</span></a>
</li>
<li><span class='sectionRange'>3.4 - </span><a href="#h-139356"><span class="HTitleText2">Security</span></a>
</li>
<li><span class='sectionRange'>3.5 - </span><a href="#h-139368"><span class="HTitleText2">Payment of Large Amounts</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-139377"><span class="HTitleText2">Performance of Obligations</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-139384"><span class="HTitleText2">Customs Offices and Facilities</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-139416"><span class="HTitleText2">Application of Act</span></a>
</li>
<li><span class='sectionRange'>7.1 - </span><a href="#h-139419"><span class="HTitleText2">Provision of Information</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-139424"><span class="HTitleText2">Forms</span></a>
</li>
<li><span class='sectionRange'>8.1 - </span><a href="#h-139429"><span class="HTitleText2">Electronic Filing</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-139456"><span class="HTitleText2">Brokers and Agents</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-139485"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Importation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-139486"><span class="HTitleText2">Persons</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-139580"><span class="HTitleText2">Report of Goods</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-139674"><span class="HTitleText2">Duties</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-139684"><span class="HTitleText2">Liability for Duties on Goods Reported</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-139702"><span class="HTitleText2">Movement and Storage of Goods</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-139734"><span class="HTitleText2">Transportation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-139769"><span class="HTitleText2">Warehouses and Duty Free Shops</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-139830"><span class="HTitleText2">Release</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-139835"><span class="HTitleText2">Accounting and Payment of Duties</span></a>
</li>
<li><span class='sectionRange'>35.01 - </span><a href="#h-139955"><span class="HTitleText2">Marking of Goods</span></a>
</li>
<li><span class='sectionRange'>35.1 - </span><a href="#h-139975"><span class="HTitleText2">Origin of Goods</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-139995"><span class="HTitleText2">Abandoned Goods</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-140001"><span class="HTitleText2">Unclaimed Goods</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-140027"><span class="HTitleText2">Goods of a Prescribed Class</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-140035"><span class="HTitleText2">Records</span></a>
</li>
<li><span class='sectionRange'>42.01 - </span><a href="#h-140081"><span class="HTitleText2">Verifications</span></a>
</li>
<li><span class='sectionRange'>42.1 - </span><a href="#h-140086"><span class="HTitleText2">Verifications under a Free Trade Agreement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42.1 - </span><a href="#h-140087"><span class="HTitleText3">Conduct of Verification</span></a>
</li>
<li><span class='sectionRange'>42.2 - </span><a href="#h-140113"><span class="HTitleText3">Statement of Origin</span></a>
</li>
<li><span class='sectionRange'>42.3 - </span><a href="#h-140121"><span class="HTitleText3">Effective Date of Re-determination of Origin</span></a>
</li>
<li><span class='sectionRange'>42.4 - </span><a href="#h-140139"><span class="HTitleText3">Denial or Withdrawal of Benefit of Preferential Tariff Treatment Under Certain Free Trade Agreements</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-140148"><span class="HTitleText3">Production of Documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>43.1 - </span><a href="#h-140158"><span class="HTitleText2">Advance Rulings</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-140173"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Calculation of Duty</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-140174"><span class="HTitleText2">Duties Based on Percentage Rates</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-140175"><span class="HTitleText3">Valuation for Duty</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-140180"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-140223"><span class="HTitleText3">Determination of Value for Duty</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-140226"><span class="HTitleText3">Order of Consideration of Methods of Valuation</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-140240"><span class="HTitleText3">Transaction Value of the Goods</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-140287"><span class="HTitleText3">Transaction Value of Identical Goods</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-140308"><span class="HTitleText3">Transaction Value of Similar Goods</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-140318"><span class="HTitleText3">Deductive Value</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-140350"><span class="HTitleText3">Computed Value</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-140368"><span class="HTitleText3">Residual Method</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-140373"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="#h-140382"><span class="HTitleText2">Duties Based on Specific Quantities or Specific Values</span></a>
</li>
<li><span class='sectionRange'>57.01 - </span><a href="#h-140385"><span class="HTitleText2">Marking Determination</span></a>
</li>
<li><span class='sectionRange'>57.1 - </span><a href="#h-140393"><span class="HTitleText2">Determination, Re-determination and Further Re-determination of Origin, Tariff Classification and Value for Duty of Imported Goods</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-140432"><span class="HTitleText2">Re-determination and Further Re-determination by President</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-140540"><span class="HTitleText3">Appeals and References</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-140594"><span class="HTitleText3">Special Provisions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-140624"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Abatements and Refunds</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-140718"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Exportation</span></a>
</li>
<li><span class='sectionRange'>97.21 - </span><a href="#h-140789"><span class="HLabel1">PART V.1</span> - <span class="HTitleText1">Collections</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97.21 - </span><a href="#h-140790"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>97.211 - </span><a href="#h-140806"><span class="HTitleText2">Ancillary Powers</span></a>
</li>
<li><span class='sectionRange'>97.22 - </span><a href="#h-140816"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>97.24 - </span><a href="#h-140838"><span class="HTitleText2">Certificates, Liens and Set-off</span></a>
</li>
<li><span class='sectionRange'>97.28 - </span><a href="#h-140915"><span class="HTitleText2">Garnishment and Non-arm’s Length Transfers</span></a>
</li>
<li><span class='sectionRange'>97.3 - </span><a href="#h-140978"><span class="HTitleText2">Acquisition of Property and Seizures</span></a>
</li>
<li><span class='sectionRange'>97.34 - </span><a href="#h-141010"><span class="HTitleText2">Collection Restrictions</span></a>
</li>
<li><span class='sectionRange'>97.36 - </span><a href="#h-141062"><span class="HTitleText2">Trustees, Receivers and Personal Representatives</span></a>
</li>
<li><span class='sectionRange'>97.4 - </span><a href="#h-141134"><span class="HTitleText2">Amalgamations and Windings-up</span></a>
</li>
<li><span class='sectionRange'>97.42 - </span><a href="#h-141146"><span class="HTitleText2">Partnerships</span></a>
</li>
<li><span class='sectionRange'>97.43 - </span><a href="#h-141158"><span class="HTitleText2">Unincorporated Bodies</span></a>
</li>
<li><span class='sectionRange'>97.44 - </span><a href="#h-141167"><span class="HTitleText2">Assessments, Objections and Appeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97.44 - </span><a href="#h-141168"><span class="HTitleText3">Assessments</span></a>
</li>
<li><span class='sectionRange'>97.48 - </span><a href="#h-141214"><span class="HTitleText3">Objections and Appeals</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-141353"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-141354"><span class="HTitleText2">Powers of Officers</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-141455"><span class="HTitleText2">Limitation of Actions or Proceedings</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-141465"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-141574"><span class="HTitleText2">Inquiries</span></a>
</li>
<li><span class='sectionRange'>109.1 - </span><a href="#h-141582"><span class="HTitleText2">Penalties and Interest</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-141627"><span class="HTitleText2">Seizures</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-141688"><span class="HTitleText2">Return of Goods Seized</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-141744"><span class="HTitleText2">Forfeitures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-141745"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-141755"><span class="HTitleText3">Ascertained Forfeiture</span></a>
</li>
<li><span class='sectionRange'>126.1 - </span><a href="#h-141785"><span class="HTitleText3">Review of Seizure, Ascertained Forfeiture or Penalty Assessment</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-141937"><span class="HTitleText3">Third Party Claims</span></a>
</li></ul>
</li><li><span class='sectionRange'>142 - </span><a href="#h-142009"><span class="HTitleText2">Disposal of Things Abandoned or Forfeit</span></a>
</li>
<li><span class='sectionRange'>147.1 - </span><a href="#h-142034"><span class="HTitleText2">Collection of Duties on Mail</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-142076"><span class="HTitleText2">Evidence</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-142135"><span class="HTitleText2">Prohibitions, Offences and Punishment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-142136"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-142194"><span class="HTitleText3">Procedure</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>163.4 - </span><a href="#h-142200"><span class="HLabel1">PART VI.1</span> - <span class="HTitleText1">Enforcement of Criminal Offences Other than Offences Under This Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163.4 - </span><a href="#h-142201"><span class="HTitleText2">Powers of Designated Officers</span></a>
</li></ul>
</li><li><span class='sectionRange'>164 - </span><a href="#h-142220"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-142273"><span class="HTitleText1">Parliamentary Review</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-142279"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>170 to 182 - </span><a href="#h-142289"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-142295"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-101"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
