<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Employment Insurance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-215680"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-215683"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-215730"><span class="HTitleText1">Report</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-215744"><span class="HTitleText1">Maximum Yearly Insurable Earnings</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-215761"><span class="HTitleText1">Insurable Employment</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-215806"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Unemployment Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-215807"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-215831"><span class="HTitleText2">Qualifying for Benefits</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-215911"><span class="HTitleText2">Benefit Period</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-216010"><span class="HTitleText2">Payment of Benefits</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-216070"><span class="HTitleText2">Rate of Benefits</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-216111"><span class="HTitleText2">Disentitlement to Benefits</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-216122"><span class="HTitleText2">Deductions from Benefits</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-216150"><span class="HTitleText2">Special Benefits</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-216361"><span class="HTitleText2">Work-Sharing</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-216380"><span class="HTitleText2">Courses, Programs and Employment Benefits</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-216396"><span class="HTitleText2">Disqualification and Disentitlement</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-216527"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-216579"><span class="HTitleText2">Non-assignment of Benefits and Liability to Return Benefits and Pay Penalties</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-216637"><span class="HTitleText2">Claim Procedure</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-216700"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-216770"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Employment Benefits and National Employment Service</span></a>
</li>
<li><span class='sectionRange'>65.21 - </span><a href="#h-216884"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Premiums and Other Financial Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65.21 - </span><a href="#h-216885"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>65.3 - </span><a href="#h-216890"><span class="HTitleText2">Premiums</span></a>
</li>
<li><span class='sectionRange'>70.2 - </span><a href="#h-217011"><span class="HTitleText2">Employment Insurance Operating Account</span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="#h-217096"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Insurable Earnings and Collection of Premiums</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="#h-217097"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-217103"><span class="HTitleText2">Payment of Premiums</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-217261"><span class="HTitleText2">Rulings and Appeals</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-217305"><span class="HTitleText2">Overpayments and Refunds</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-217430"><span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-217531"><span class="HTitleText2">Objection and Review</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-217558"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-217585"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-217620"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Pilot Projects</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-217634"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Administrative Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-217635"><span class="HTitleText2">Administrative Review</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-217680"><span class="HTitleText2">Investigations</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-217690"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-217866"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-217893"><span class="HTitleText2">Social Insurance Number</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-217911"><span class="HTitleText2">Reports</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-217915"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Benefit Repayment</span></a>
</li>
<li><span class='sectionRange'>152.01 - </span><a href="#h-217977"><span class="HLabel1">PART VII.1</span> - <span class="HTitleText1">Benefits For Self-Employed Persons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152.01 - </span><a href="#h-217978"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>152.02 - </span><a href="#h-218013"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>152.03 - </span><a href="#h-218033"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>152.07 - </span><a href="#h-218232"><span class="HTitleText2">Qualifying for Benefits</span></a>
</li>
<li><span class='sectionRange'>152.1 - </span><a href="#h-218290"><span class="HTitleText2">Benefit Period</span></a>
</li>
<li><span class='sectionRange'>152.13 - </span><a href="#h-218372"><span class="HTitleText2">Payment of Benefits</span></a>
</li>
<li><span class='sectionRange'>152.21 - </span><a href="#h-218482"><span class="HTitleText2">Premium</span></a>
</li>
<li><span class='sectionRange'>152.22 - </span><a href="#h-218497"><span class="HTitleText2">Self-employed Earnings and Collection of Premiums</span></a>
</li>
<li><span class='sectionRange'>152.31 - </span><a href="#h-218588"><span class="HTitleText2">Application of other Provisions</span></a>
</li>
<li><span class='sectionRange'>152.311 - </span><a href="#h-218607"><span class="HTitleText2">Delegation</span></a>
</li>
<li><span class='sectionRange'>152.32 - </span><a href="#h-218612"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>152.33 - </span><a href="#h-218617"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>152.34 - </span><a href="#h-218628"><span class="HTitleText2">Review of this Part</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-218633"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Self-employed Persons Engaged in Fishing</span></a>
</li>
<li><span class='sectionRange'>153.1 - </span><a href="#h-218655"><span class="HLabel1">PART VIII.1</span> - <span class="HTitleText1">Alternate Access to Special Benefits</span></a>
</li>
<li><span class='sectionRange'>153.2 - </span><a href="#h-218667"><span class="HLabel1">PART VIII.2</span> - <span class="HTitleText1">Regulations — Provincial Plans</span></a>
</li>
<li><span class='sectionRange'>154 and 155 - </span><a href="#h-218683"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Repeals, Transitional Provisions, Related and Conditional Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>154 and 155 - </span><a href="#h-218684"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-218686"><span class="HTitleText2">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-218687"><span class="HTitleText3">National Training Act</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-218693"><span class="HTitleText3">Unemployment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-218741"><span class="HTitleText3">Transitional Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 to 186 - </span><a href="#h-218746"><span class="HTitleText2">Consequential and Related Amendments</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-218748"><span class="HTitleText2">Changes in Terminology</span></a>
</li>
<li><span class='sectionRange'>188 and 189 - </span><a href="#h-218750"><span class="HTitleText2">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-218752"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-218785"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-218795"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Interim Provisions</span></a>
</li>
<li><a href="#h-218837"><span class="scheduleLabel">SCHEDULE III</span></a>
</li>
<li><a href="#h-218840"><span class="scheduleLabel">SCHEDULE IV</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
