<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant la modification de la Loi sur les produits dangereux et du Code canadien du travail, l’édiction de la Loi sur le contrôle des renseignements relatifs aux matières dangereuses et la modification d’autres lois en conséquence</a><ul class="TocIndent"><li><span class='sectionRange'>1 et 2 - </span><a href="#h-246794"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Loi sur les produits dangereux</span></a>
</li>
<li><span class='sectionRange'>3 à 8 - </span><a href="#h-246796"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>9 à 51 - </span><a href="#h-246798"><span class="HTitleText1">Partie III</span></a>
</li>
<li><span class='sectionRange'>52 et 53 - </span><a href="#h-246800"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Modifications corrélatives, dispositions transitoires et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 et 53 - </span><a href="#h-246801"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-246803"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-246822"><span class="HTitleText2">Examen par le Parlement</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-246825"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-246829"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
