<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les eaux du Nunavut et le Tribunal des droits de surface du Nunavut</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-363435"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-363438"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-363459"><span class="HTitleText1">Préséance</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-363465"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Eaux du Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-363466"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-363489"><span class="HTitleText2">Portée et effet</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-363494"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-363502"><span class="HTitleText2">Délégation et accords</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-363507"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-363529"><span class="HTitleText2">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-363535"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Office des eaux du Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-363536"><span class="HTitleText3">Mise en place</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-363584"><span class="HTitleText3">Langues</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-363594"><span class="HTitleText3">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-363602"><span class="HTitleText3">Statut et pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-363619"><span class="HTitleText3">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-363631"><span class="HTitleText3">Règles et règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-363657"><span class="HTitleText3">Mission et rapports avec d’autres organismes</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-363693"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Attribution de permis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-363694"><span class="HTitleText3">Règles générales</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-363740"><span class="HTitleText3">Demandes relatives aux permis</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-363759"><span class="HTitleText3">Procédure</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-363797"><span class="HTitleText3">Délais</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55.1 - </span><a href="#h-363798"><span class="HTitleText4">Pouvoir d’agir</span></a>
</li>
<li><span class='sectionRange'>55.2 - </span><a href="#h-363803"><span class="HTitleText4">Décision de l’Office et approbation</span></a>
</li>
<li><span class='sectionRange'>55.31 - </span><a href="#h-363812"><span class="HTitleText4">Calcul du délai</span></a>
</li>
<li><span class='sectionRange'>55.6 - </span><a href="#h-363830"><span class="HTitleText4">Prolongation</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-363838"><span class="HTitleText3">Conditions de délivrance</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-363899"><span class="HTitleText3">Terres inuit</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-363935"><span class="HTitleText3">Vallée du Mackenzie</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-363938"><span class="HTitleText3">Conditions des permis</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-363967"><span class="HTitleText3">Sûreté</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-363992"><span class="HTitleText3">Expropriation</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-364033"><span class="HTitleText3">Registre public</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-364041"><span class="HTitleText3">Décisions</span></a>
</li>
<li><span class='sectionRange'>81.1 - </span><a href="#h-364057"><span class="HTitleText3">Recouvrement des coûts</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-364068"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-364069"><span class="HTitleText3">Règlements et décrets</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-364118"><span class="HTitleText3">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-364166"><span class="HTitleText3">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>94.01 - </span><a href="#h-364233"><span class="HTitleText3">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94.01 - </span><a href="#h-364234"><span class="HTitleText4">Règlements</span></a>
</li>
<li><span class='sectionRange'>94.02 - </span><a href="#h-364250"><span class="HTitleText4">Violations</span></a>
</li>
<li><span class='sectionRange'>94.07 - </span><a href="#h-364283"><span class="HTitleText4">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>94.11 - </span><a href="#h-364306"><span class="HTitleText4">Révision</span></a>
</li>
<li><span class='sectionRange'>94.16 - </span><a href="#h-364336"><span class="HTitleText4">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>94.18 - </span><a href="#h-364345"><span class="HTitleText4">Recouvrement des pénalités</span></a>
</li>
<li><span class='sectionRange'>94.2 - </span><a href="#h-364360"><span class="HTitleText4">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-364369"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Tribunal des droits de surface du Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-364370"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-364377"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-364385"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-364388"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Mise en place du Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-364389"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-364416"><span class="HTitleText3">Langues</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-364430"><span class="HTitleText3">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-364438"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-364441"><span class="HTitleText3">Pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-364451"><span class="HTitleText3">Statut</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-364454"><span class="HTitleText3">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-364466"><span class="HTitleText3">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-364475"><span class="HTitleText3">Saisine du Tribunal</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-364483"><span class="HTitleText3">Procédure</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-364525"><span class="HTitleText3">Dossiers</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-364534"><span class="HTitleText3">Règles</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="#h-364562"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Ordonnances relatives à l’entrée sur les terres inuit</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="#h-364563"><span class="HTitleText3">Exercice des droits miniers</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-364578"><span class="HTitleText3">Activités commerciales</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-364591"><span class="HTitleText3">Matériaux de construction</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-364601"><span class="HTitleText3">Règles générales concernant les ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="#h-364640"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Ordonnances relatives à l’entrée sur les terres non inuit</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="#h-364641"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-364646"><span class="HTitleText3">Exercice des droits miniers</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-364649"><span class="HTitleText3">Règles générales concernant l’ordonnance</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-364684"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Droit minier et pierre à sculpter</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-364685"><span class="HTitleText3">Matières spécifiées des terres inuit</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-364691"><span class="HTitleText3">Pierre à sculpter des terres domaniales</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-364697"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Indemnités relatives aux ressources fauniques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="#h-364698"><span class="HTitleText3">Définitions et terminologie</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-364716"><span class="HTitleText3">Responsabilité de l’entrepreneur</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-364743"><span class="HTitleText3">Demande au Tribunal</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-364761"><span class="HTitleText3">Autres recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-364767"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-364768"><span class="HTitleText3">Décisions du Tribunal</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-364786"><span class="HTitleText3">Révision des ordonnances</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-364804"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>171 - </span><a href="#h-364813"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions transitoires, modifications corrélatives, dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>171 - </span><a href="#h-364814"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>176 à 199 - </span><a href="#h-364848"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>200 à 202 - </span><a href="#h-364850"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-364852"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-364856"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-364892"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
