<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les douanes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-135710"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-135713"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-135855"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-135856"><span class="HTitleText2">Application à Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-135866"><span class="HTitleText2">Pénalités et intérêts</span></a>
</li>
<li><span class='sectionRange'>3.4 - </span><a href="#h-135884"><span class="HTitleText2">Garantie</span></a>
</li>
<li><span class='sectionRange'>3.5 - </span><a href="#h-135892"><span class="HTitleText2">Paiement de sommes importantes</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-135901"><span class="HTitleText2">Solidarité</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-135908"><span class="HTitleText2">Bureaux de douane et installations douanières</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-135939"><span class="HTitleText2">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>7.1 - </span><a href="#h-135942"><span class="HTitleText2">Fourniture de renseignements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-135947"><span class="HTitleText2">Formulaires</span></a>
</li>
<li><span class='sectionRange'>8.1 - </span><a href="#h-135952"><span class="HTitleText2">Transmission électronique</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-135979"><span class="HTitleText2">Courtiers et mandataires</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-136008"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Importation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-136009"><span class="HTitleText2">Présentation au bureau</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-136103"><span class="HTitleText2">Déclaration</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-136196"><span class="HTitleText2">Droits</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-136206"><span class="HTitleText2">Responsabilité du paiement des droits sur les marchandises déclarées</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-136224"><span class="HTitleText2">Mouvement et entreposage des marchandises</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-136256"><span class="HTitleText2">Transit</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-136291"><span class="HTitleText2">Entrepôts et boutiques hors taxes</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-136352"><span class="HTitleText2">Dédouanement</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-136357"><span class="HTitleText2">Déclaration en détail et paiement des droits</span></a>
</li>
<li><span class='sectionRange'>35.01 - </span><a href="#h-136475"><span class="HTitleText2">Marquage des marchandises</span></a>
</li>
<li><span class='sectionRange'>35.1 - </span><a href="#h-136495"><span class="HTitleText2">Origine des marchandises</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-136515"><span class="HTitleText2">Abandon</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-136521"><span class="HTitleText2">Dépôt de douane</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-136547"><span class="HTitleText2">Marchandises d’une catégorie réglementaire</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-136555"><span class="HTitleText2">Documents</span></a>
</li>
<li><span class='sectionRange'>42.01 - </span><a href="#h-136601"><span class="HTitleText2">Vérifications</span></a>
</li>
<li><span class='sectionRange'>42.1 - </span><a href="#h-136606"><span class="HTitleText2">Vérifications dans le cadre d’un accord de libre-échange</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42.1 - </span><a href="#h-136607"><span class="HTitleText3">Origine des marchandises, exonération de droits et drawback de droits</span></a>
</li>
<li><span class='sectionRange'>42.2 - </span><a href="#h-136633"><span class="HTitleText3">Déclaration de l’origine</span></a>
</li>
<li><span class='sectionRange'>42.3 - </span><a href="#h-136641"><span class="HTitleText3">Prise d’effet de la révision de la détermination de l’origine</span></a>
</li>
<li><span class='sectionRange'>42.4 - </span><a href="#h-136657"><span class="HTitleText3">Refus ou retrait du traitement tarifaire préférentiel — certains accords de libre-échange</span></a>
</li>
<li><span class='sectionRange'>42.5 - </span><a href="#h-1241302"><span class="HTitleText3">Évasion douanière</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-136668"><span class="HTitleText3">Production de documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>43.1 - </span><a href="#h-136678"><span class="HTitleText2">Décisions anticipées</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-136693"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Calcul des droits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-136694"><span class="HTitleText2">Droits basés sur un pourcentage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-136695"><span class="HTitleText3">Valeur en douane</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-136700"><span class="HTitleText3">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-136743"><span class="HTitleText3">Détermination de la valeur en douane</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-136746"><span class="HTitleText3">Ordre d’application des méthodes d’appréciation</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-136760"><span class="HTitleText3">Valeur transactionnelle des marchandises</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-136807"><span class="HTitleText3">Valeur transactionnelle des marchandises identiques</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-136828"><span class="HTitleText3">Valeur transactionnelle des marchandises semblables</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-136838"><span class="HTitleText3">Valeur de référence</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-136869"><span class="HTitleText3">Valeur reconstituée</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-136886"><span class="HTitleText3">Dernière méthode d’appréciation</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-136891"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="#h-136900"><span class="HTitleText2">Droits basés sur les quantités ou les valeurs déterminées</span></a>
</li>
<li><span class='sectionRange'>57.01 - </span><a href="#h-136903"><span class="HTitleText2">Détermination de la conformité des marques</span></a>
</li>
<li><span class='sectionRange'>57.1 - </span><a href="#h-136911"><span class="HTitleText2">Détermination de l’origine, du classement tarifaire et de la valeur en douane des marchandises importées, révision et réexamen</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-136950"><span class="HTitleText2">Révision ou réexamen par le président</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-137058"><span class="HTitleText3">Appels et recours</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-137111"><span class="HTitleText3">Dispositions spéciales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-137141"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Abattements et remboursements</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-1172766"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Collecte de renseignements sur les personnes et les marchandises</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="#h-1172776"><span class="HTitleText2">Personnes quittant le Canada</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-1172824"><span class="HTitleText2">Exportation de marchandises</span></a>
</li></ul>
</li><li><span class='sectionRange'>97.21 - </span><a href="#h-137304"><span class="HLabel1">PARTIE V.1</span> - <span class="HTitleText1">Perception</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97.21 - </span><a href="#h-137305"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>97.211 - </span><a href="#h-137321"><span class="HTitleText2">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>97.22 - </span><a href="#h-137331"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>97.24 - </span><a href="#h-137353"><span class="HTitleText2">Certificat de non-paiement, gage et déduction ou compensation</span></a>
</li>
<li><span class='sectionRange'>97.28 - </span><a href="#h-137430"><span class="HTitleText2">Saisie-arrêt et transferts à des personnes liées</span></a>
</li>
<li><span class='sectionRange'>97.3 - </span><a href="#h-137493"><span class="HTitleText2">Acquisition de biens et saisie</span></a>
</li>
<li><span class='sectionRange'>97.34 - </span><a href="#h-137525"><span class="HTitleText2">Restrictions au recouvrement</span></a>
</li>
<li><span class='sectionRange'>97.36 - </span><a href="#h-137577"><span class="HTitleText2">Syndics de faillite, séquestres et représentants personnels</span></a>
</li>
<li><span class='sectionRange'>97.4 - </span><a href="#h-137649"><span class="HTitleText2">Fusion et liquidation</span></a>
</li>
<li><span class='sectionRange'>97.42 - </span><a href="#h-137661"><span class="HTitleText2">Sociétés de personnes</span></a>
</li>
<li><span class='sectionRange'>97.43 - </span><a href="#h-137673"><span class="HTitleText2">Entités non constituées en personne morale</span></a>
</li>
<li><span class='sectionRange'>97.44 - </span><a href="#h-137682"><span class="HTitleText2">Cotisations, oppositions et appels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97.44 - </span><a href="#h-137683"><span class="HTitleText3">Cotisations</span></a>
</li>
<li><span class='sectionRange'>97.48 - </span><a href="#h-137729"><span class="HTitleText3">Opposition et appel</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-137868"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-137869"><span class="HTitleText2">Pouvoirs des agents</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-137969"><span class="HTitleText2">Prescriptions</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-137979"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-138088"><span class="HTitleText2">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>109.1 - </span><a href="#h-138096"><span class="HTitleText2">Pénalités et intérêts</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-138141"><span class="HTitleText2">Saisies</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-138201"><span class="HTitleText2">Restitution des marchandises saisies</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-138257"><span class="HTitleText2">Confiscation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-138258"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-138268"><span class="HTitleText3">Confiscation compensatoire</span></a>
</li>
<li><span class='sectionRange'>126.1 - </span><a href="#h-138298"><span class="HTitleText3">Procédures en cas de saisie, de confiscation compensatoire ou de pénalités</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-138450"><span class="HTitleText3">Revendication des tiers</span></a>
</li></ul>
</li><li><span class='sectionRange'>142 - </span><a href="#h-138522"><span class="HTitleText2">Destination des objets abandonnés ou confisqués</span></a>
</li>
<li><span class='sectionRange'>147.1 - </span><a href="#h-138547"><span class="HTitleText2">Perception des droits sur le courrier</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-138587"><span class="HTitleText2">Preuve</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-138643"><span class="HTitleText2">Interdictions, infractions et peines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-138644"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-138700"><span class="HTitleText3">Procédure</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>163.4 - </span><a href="#h-138706"><span class="HLabel1">PARTIE VI.1</span> - <span class="HTitleText1">Contrôle d’application en matière d’infractions criminelles à d’autres lois</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163.4 - </span><a href="#h-138707"><span class="HTitleText2">Pouvoirs des agents des douanes désignés</span></a>
</li></ul>
</li><li><span class='sectionRange'>164 - </span><a href="#h-138726"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-138779"><span class="HTitleText1">Suivi parlementaire</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-138785"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>170 à 182 - </span><a href="#h-138795"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-138801"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-138805"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

