<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Roosevelt Campobello International Park Commission Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-428146"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-428149"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-428162"><span class="HTitleText1">Powers and Exemptions of the Commission</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="#h-428173"><span class="HTitleText1">Appointment of Alternate Members</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-428178"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-428181"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-428185"><span class="scheduleLabel">SCHEDULE</span> - <span class="scheduleTitleText"> - </span> - <span class="scheduleTitleText"> - Agreement Between the Government of Canada and the Government of the United States of America Relating to the Establishment of the Roosevelt Campobello International Park</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
