<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget 1995</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-34186"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 à 6 - </span><a href="page-1.html#h-34189"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Rémunération</span></a>
</li>
<li><span class='sectionRange'>7 à 10 - </span><a href="page-1.html#h-34191"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Gestion du personnel</span></a>
</li>
<li><span class='sectionRange'>11 à 22 - </span><a href="page-1.html#h-34193"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Transports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 à 22 - </span><a href="page-1.html#h-34194"><span class="HTitleText2">Loi de 1987 sur les transports nationaux</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-34196"><span class="HTitleText2">Entrée en vigueur</span></a>
</li>
<li><span class='sectionRange'>24 à 26 - </span><a href="page-1.html#h-34199"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-1.html#h-34201"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-1.html#h-34211"><span class="HTitleText2">Édiction</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-1.html#h-34214"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Arrangements fiscaux et autres matières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 et 32 - </span><a href="page-1.html#h-34216"><span class="HTitleText2">Régime d’assistance publique du Canada</span></a>
</li>
<li><span class='sectionRange'>33 à 41 - </span><a href="page-1.html#h-34218"><span class="HTitleText2">Loi canadienne sur la santé</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-1.html#h-34220"><span class="HTitleText2">Loi sur l’aide en matière d’éducation aux enfants des anciens combattants décédés</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-1.html#h-34222"><span class="HTitleText2">Loi sur le ministère des Affaires étrangères et du Commerce international</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-1.html#h-34224"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces et sur les contributions fédérales en matière d’enseignement postsecondaire et de santé</span></a>
</li>
<li><span class='sectionRange'>57 à 60 - </span><a href="page-1.html#h-34230"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-1.html#h-34232"><span class="HTitleText2">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>62 à 64 - </span><a href="page-1.html#h-34234"><span class="HTitleText2">Loi sur le transfert de l’impôt sur le revenu des entreprises d’utilité publique</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-1.html#h-34238"><span class="HTitleText2">Loi sur la cession du droit au remboursement en matière d’impôt</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-1.html#h-34240"><span class="HTitleText2">Loi sur la réadaptation professionnelle des personnes handicapées</span></a>
</li>
<li><span class='sectionRange'>68 à 72 - </span><a href="page-1.html#h-34242"><span class="HTitleText2">Loi sur les allocations aux anciens combattants</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="page-1.html#h-34244"><span class="HTitleText1">Modifications conditionnelles</span></a>
</li>
<li><a href="page-2.html#h-34247"><span class="scheduleLabel">ANNEXE I</span></a>
</li>
<li><a href="page-3.html#h-34250"><span class="scheduleLabel">ANNEXE II</span> </a>
</li></ul>
</li></ul>

</nav>

