<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le commerce des spiritueux</a><ul class="TocIndent"><li><a href="#h-426919"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Utilisation des noms de spiritueux</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
