<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Lands Surveys Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-344804"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-344809"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-344832"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>5 to 16 - </span><a href="page-1.html#h-344849"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Powers and Duties of Canada Lands Surveyors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-1.html#h-344851"><span class="HTitleText2">Duties and Powers of Surveyors</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-344868"><span class="HTitleText2">Standard of Measure</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-1.html#h-344878"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Surveys of Canada Lands</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="page-1.html#h-344879"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-1.html#h-344908"><span class="HTitleText2">Surveys</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-1.html#h-344924"><span class="HTitleText2">Plans</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-344950"><span class="HTitleText2">Boundaries</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-344958"><span class="HTitleText2">Resurveys</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-2.html#h-344968"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Special Surveys of Territorial Lands</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-2.html#h-344969"><span class="HTitleText2">Scope and Administration</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-2.html#h-344976"><span class="HTitleText2">Special Surveys</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-344997"><span class="HTitleText2">Procedure of Special Surveys</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-2.html#h-345076"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-2.html#h-345077"><span class="HTitleText2">General Power to Survey</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-3.html#h-345085"><span class="HTitleText2">Evidence</span></a>
</li>
<li><span class='sectionRange'>51 and 52 - </span><a href="page-3.html#h-345101"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

