<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Modification des annexes</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Sensibilisation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Code de conduite</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">Actes répréhensibles</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Divulgation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-8"><span class="HTitleText1">Protection des divulgateurs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText1">Attributions du commissaire</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-11"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-12"><span class="HTitleText1">Commissariat à l’intégrité du secteur public</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-13"><span class="HTitleText2">Commissaire à l’intégrité du secteur public</span></a>
</li>
<li><span class='sectionRange'>39.3 - </span><a href="#h-14"><span class="HTitleText2">Personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-15"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-16"><span class="HTitleText1">Caractère confidentiel</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-17"><span class="HTitleText1">Immunité</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-18"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-19"><span class="HTitleText1">Organismes exclus</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-20"><span class="HTitleText1">Examen quinquennal</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="#h-21"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-22"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-23"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-24"><span class="HTitleText2">Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-25"><span class="HTitleText2">Loi sur la protection des renseignements personnels et les documents électroniques</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-26"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-27"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-28"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-29"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-30"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-31"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
