<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Administration canadienne de la sûreté du transport aérien</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Rôle du ministre</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Création et mission de l’Administration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText1">Capacité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">Structure organisationnelle de l’Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText2">Président du conseil</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText2">Premier dirigeant</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">Compétence générale du conseil</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-12"><span class="HTitleText1">Contrats, ententes et accords</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-14"><span class="HTitleText1">Renseignements de sécurité</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText1">Examen</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-16"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-17"><span class="HTitleText1">Dispositions transitoires</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
