<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Gwich’in Land Claim Settlement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-247212"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-247215"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-247218"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-247221"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-247241"><span class="HTitleText1">Other Laws</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-247245"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-247248"><span class="HTitleText1">Consequential Amendment</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-247250"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

