<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le parc de Kingsmere</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-330000"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><a href="#h-330025"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Extrait du testament de M. King :</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
