<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Food and Drugs Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Foods, Drugs, Cosmetics and Devices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Food</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Drugs</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText2">Cosmetics</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-8"><span class="HTitleText2">Devices</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText2">Inspection, Seizure and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-11"><span class="HTitleText2">Analysis</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-12"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-13"><span class="HTitleText2">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-14"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-15"><span class="HTitleText2">Exports</span></a>
</li></ul>
</li><li><a href="#h-16"><span class="HLabel1">PARTS III AND IV</span> - <span class="HTitleText1">[Repealed, 1996, c. 19, s. 81]</span></a>
</li>
<li><a href="#h-234755"><span class="scheduleLabel">SCHEDULE A</span> </a>
</li>
<li><a href="#h-234789"><span class="scheduleLabel">SCHEDULE B</span> </a>
</li>
<li><a href="#h-234799"><span class="scheduleLabel">SCHEDULE C</span> </a>
</li>
<li><a href="#h-20"><span class="scheduleLabel">SCHEDULE D</span> </a>
</li>
<li><a href="#h-234827"><span class="scheduleLabel">SCHEDULE E</span> </a>
</li>
<li><a href="#h-234832"><span class="scheduleLabel">SCHEDULE F</span> </a>
</li>
<li><a href="#h-234837"><span class="scheduleLabel">SCHEDULES G AND H</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
