<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Journée lavande</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-400735"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-400738"><span class="HTitleText1">Journée lavande</span></a>
</li></ul>
</li></ul>

</nav>

