<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la capitale nationale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-365275"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-365280"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-365303"><span class="HTitleText1">Maintien de la commission</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-365351"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-365363"><span class="HTitleText1">Comités</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-365375"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-365393"><span class="HTitleText1">Aménagement</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-365443"><span class="HTitleText1">Expropriation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-365451"><span class="HTitleText1">Biens</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-365472"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-365481"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-365506"><span class="HTitleText1">Généralités</span></a>
</li>
<li><a href="#h-365520"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Délimitation de la région de la capitale nationale</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
