<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des obtentions végétales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Obtentions végétales</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Demande de certificat d’obtention</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">Dénomination des obtentions végétales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">Traitement de la demande</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">Certificat temporaire</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText1">Examen et règlement de la demande</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-11"><span class="HTitleText1">Délivrance du certificat d’obtention</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-12"><span class="HTitleText1">Maintien du matériel de multiplication</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HTitleText1">Cession du certificat</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-14"><span class="HTitleText1">Licence obligatoire</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-15"><span class="HTitleText1">Annulations et révocations</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HTitleText1">Renonciation au certificat</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText1">Mandataires</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-18"><span class="HTitleText1">Moyens de réparation</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-19"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-20"><span class="HTitleText1">Bureau de la protection des obtentions végétales</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-21"><span class="HTitleText1">Archives</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-22"><span class="HTitleText1">Publication</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-23"><span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-24"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-25"><span class="HTitleText1">Loi sur les semences</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-26"><span class="HTitleText1">Examen de la loi</span></a>
</li>
<li><span class='sectionRange'>79. à 81 - </span><a href="#h-27"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-28"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
