<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Economic Action Plan 2014 Act, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-175307"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-175310"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the Income Tax Act and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-175311"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-1.html#h-175341"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-1.html#h-175343"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-1.html#h-175350"><span class="HTitleText2"><cite class="XRefExternalRegulation">Canada Pension Plan Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-1.html#h-175352"><span class="HTitleText2"><cite class="XRefExternalRegulation">Insurable Earnings and Collection of Premiums Regulations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="page-1.html#h-175354"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the Excise Tax Act (GST/HST Measures)</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-1.html#h-175377"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the Excise Act, 2001, the Excise Tax Act (Other Than GST/HST Measures) and the Air Travellers Security Charge Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-1.html#h-175378"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-1.html#h-175379"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-1.html#h-175404"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="page-1.html#h-175406"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-1.html#h-175414"><span class="HTitleText2"><cite class="XRefExternalAct">Air Travellers Security Charge Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-1.html#h-175416"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Customs Tariff</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-1.html#h-175417"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-1.html#h-175425"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="page-1.html#h-175431"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Canada–United States Enhanced Tax Information Exchange Agreement Implementation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="page-1.html#h-175432"><span class="HTitleText2">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-1.html#h-175435"><span class="HTitleText2">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="page-1.html#h-175438"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="page-1.html#h-175439"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Payments — Veterans Affairs</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-2.html#h-175506"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Canada Deposit Insurance Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="page-2.html#h-175507"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-2.html#h-175509"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-2.html#h-175511"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Regulatory Cooperation Council Initiative on Workplace Chemicals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-2.html#h-175512"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Hazardous Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-2.html#h-175532"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-2.html#h-175543"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-2.html#h-175548"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-2.html#h-175552"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="page-2.html#h-175566"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-2.html#h-175568"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-2.html#h-175571"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>163 - </span><a href="page-2.html#h-175574"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-2.html#h-175576"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-2.html#h-175579"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Members of Parliament Retiring Allowances Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="page-2.html#h-175580"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-2.html#h-175582"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="page-2.html#h-175584"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="page-2.html#h-175585"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-2.html#h-175589"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="page-2.html#h-175595"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-2.html#h-175599"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Atlantic Canada Opportunities Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>175 - </span><a href="page-2.html#h-175600"><span class="HTitleText3"><cite class="XRefExternalAct">Atlantic Canada Opportunities Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-2.html#h-175604"><span class="HTitleText3">Dissolution of Board</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="page-2.html#h-175606"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">Enterprise Cape Breton Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="page-2.html#h-175607"><span class="HTitleText3">Dissolution</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-3.html#h-175648"><span class="HTitleText3"><cite class="XRefExternalAct">Atlantic Canada Opportunities Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-3.html#h-175650"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="page-3.html#h-175651"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-3.html#h-175654"><span class="HTitleText4"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-3.html#h-175656"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="page-3.html#h-175658"><span class="HTitleText3">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>193 - </span><a href="page-3.html#h-175660"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Museums Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="page-3.html#h-175661"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-3.html#h-175663"><span class="HTitleText3">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="page-3.html#h-175664"><span class="HTitleText4">Definitions</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="page-3.html#h-175666"><span class="HTitleText4">Online Works of Reference</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-3.html#h-175672"><span class="HTitleText4">Virtual Museum of Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="page-3.html#h-175678"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="page-3.html#h-175681"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Nordion and Theratronics Divestiture Authorization Act</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="page-3.html#h-175686"><span class="HLabel2">DIVISION 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-3.html#h-175688"><span class="HLabel2">DIVISION 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="page-3.html#h-175690"><span class="HLabel2">DIVISION 15</span> - <span class="HTitleText2">Regulatory Cooperation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>212 - </span><a href="page-3.html#h-175691"><span class="HTitleText3"><cite class="XRefExternalAct">Motor Vehicle Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-3.html#h-175711"><span class="HTitleText3"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-3.html#h-175713"><span class="HTitleText3"><cite class="XRefExternalAct">Transportation of Dangerous Goods Act, 1992</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-3.html#h-175715"><span class="HTitleText3"><cite class="XRefExternalAct">Ensuring Safe Vehicles Imported from Mexico for Canadians Act</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-3.html#h-175717"><span class="HTitleText3"><cite class="XRefExternalAct">Safe Food for Canadians Act</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="page-3.html#h-175721"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-3.html#h-175723"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="page-3.html#h-175726"><span class="HLabel2">DIVISION 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="page-3.html#h-175727"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="page-3.html#h-175730"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>242 - </span><a href="page-3.html#h-175733"><span class="HLabel2">DIVISION 17</span> - <span class="HTitleText2">Sickness Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>242 - </span><a href="page-3.html#h-175734"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="page-3.html#h-175740"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-3.html#h-175744"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="page-3.html#h-175746"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="page-3.html#h-175749"><span class="HLabel2">DIVISION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Food Inspection Agency Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>252 - </span><a href="page-3.html#h-175750"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-3.html#h-175752"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="page-3.html#h-175756"><span class="HLabel2">DIVISION 19</span> - <span class="HTitleText2">Money Laundering and Terrorist Financing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>254 - </span><a href="page-3.html#h-175757"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-3.html#h-175801"><span class="HTitleText3"><cite class="XRefExternalAct">Jobs and Economic Growth Act</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="page-3.html#h-175803"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="page-3.html#h-175811"><span class="HLabel2">DIVISION 20</span> - <span class="HTitleText2">Immigration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="page-3.html#h-175812"><span class="HTitleText3"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="page-4.html#h-175820"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="page-4.html#h-175822"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>308 - </span><a href="page-4.html#h-175825"><span class="HLabel2">DIVISION 21</span> - <span class="HTitleText2">Public Service Labour Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="page-4.html#h-175826"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Labour Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="page-4.html#h-175828"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="page-4.html#h-175830"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>311 - </span><a href="page-4.html#h-175837"><span class="HLabel2">DIVISION 22</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Softwood Lumber Products Export Charge Act, 2006</cite></span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="page-4.html#h-175840"><span class="HLabel2">DIVISION 23</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2009</cite></span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="page-4.html#h-175842"><span class="HLabel2">DIVISION 24</span> - <span class="HTitleText2">Securitization of Insured Mortgage or Hypothecary Loans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>314 - </span><a href="page-4.html#h-175843"><span class="HTitleText3"><cite class="XRefExternalAct">Protection of Residential Mortgage or Hypothecary Insurance Act</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-4.html#h-175846"><span class="HTitleText3"><cite class="XRefExternalAct">National Housing Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="page-4.html#h-175848"><span class="HLabel2">DIVISION 25</span> - <span class="HTitleText2">Amendments Relating to International Treaties on Trademarks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>317 - </span><a href="page-4.html#h-175849"><span class="HTitleText3">Amendments to the <cite class="XRefExternalAct">Trade-marks Act</cite></span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="page-4.html#h-175898"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>364 - </span><a href="page-4.html#h-175899"><span class="HTitleText4"><cite class="XRefExternalAct">Olympic and Paralympic Marks Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>366 - </span><a href="page-4.html#h-175902"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="page-4.html#h-175904"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-4.html#h-175906"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>369 - </span><a href="page-4.html#h-175914"><span class="HLabel2">DIVISION 26</span> - <span class="HTitleText2">Reduction of Governor in Council Appointments</span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="page-4.html#h-175917"><span class="HLabel2">DIVISION 27</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Old Age Security Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>371 - </span><a href="page-4.html#h-175918"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>374 - </span><a href="page-4.html#h-175922"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>375 - </span><a href="page-4.html#h-175925"><span class="HLabel2">DIVISION 28</span> - <span class="HTitleText2"><cite class="XRefExternalAct">New Bridge for the St. Lawrence Act</cite></span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="page-4.html#h-175928"><span class="HLabel2">DIVISION 29</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Administrative Tribunals Support Service of Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="page-4.html#h-175929"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="page-4.html#h-175932"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="page-4.html#h-175938"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="page-4.html#h-175939"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>389 - </span><a href="page-4.html#h-175947"><span class="HTitleText4"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="page-4.html#h-175949"><span class="HTitleText4"><cite class="XRefExternalAct">Cultural Property Export and Import Act</cite></span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="page-4.html#h-175953"><span class="HTitleText4"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="page-4.html#h-175955"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="page-4.html#h-175976"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="page-4.html#h-175979"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>421 - </span><a href="page-4.html#h-175985"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>428 - </span><a href="page-4.html#h-175993"><span class="HTitleText4"><cite class="XRefExternalAct">Special Import Measures Act</cite></span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="page-4.html#h-176011"><span class="HTitleText4"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>447 - </span><a href="page-5.html#h-176014"><span class="HTitleText4"><cite class="XRefExternalAct">Competition Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="page-5.html#h-176017"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Agricultural Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="page-5.html#h-176021"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>458 - </span><a href="page-5.html#h-176028"><span class="HTitleText4"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>459 - </span><a href="page-5.html#h-176030"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="page-5.html#h-176032"><span class="HTitleText4"><cite class="XRefExternalAct">Status of the Artist Act</cite></span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="page-5.html#h-176036"><span class="HTitleText4"><cite class="XRefExternalAct">Employment Equity Act</cite></span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="page-5.html#h-176038"><span class="HTitleText4"><cite class="XRefExternalAct">Transportation Appeal Tribunal of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="page-5.html#h-176041"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="page-5.html#h-176044"><span class="HTitleText4"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>469 - </span><a href="page-5.html#h-176046"><span class="HTitleText4"><cite class="XRefExternalAct">Specific Claims Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="page-5.html#h-176049"><span class="HTitleText4"><cite class="XRefExternalAct">Economic Action Plan 2013 Act, No. 2</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>480 - </span><a href="page-5.html#h-176059"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>482 - </span><a href="page-5.html#h-176062"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>483 - </span><a href="page-5.html#h-176065"><span class="HLabel2">DIVISION 30</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Apprentice Loans Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>483 - </span><a href="page-5.html#h-176066"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>484 - </span><a href="page-5.html#h-176069"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>484 - </span><a href="page-5.html#h-176070"><span class="HTitleText4"><cite class="XRefExternalAct">Bankruptcy and Insolvency Act</cite></span></a>
</li>
<li><span class='sectionRange'>485 - </span><a href="page-5.html#h-176072"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>486 - </span><a href="page-5.html#h-176074"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-6.html#h-176078"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-7.html#h-176081"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-8.html#h-176084"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-9.html#h-176086"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-10.html#h-176089"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="page-11.html#h-176092"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>

</nav>

