<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’indemnisation des marins marchands</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-348262"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-348267"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-348298"><span class="HTitleText1">Domaine d’application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-348318"><span class="HTitleText1">Indemnité</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-348422"><span class="HTitleText1">Avis de l’accident</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-348442"><span class="HTitleText1">Examen médical</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-348465"><span class="HTitleText1">Révision de l’indemnité</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-348470"><span class="HTitleText1">Assurance</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-348482"><span class="HTitleText1">Montant de l’indemnité</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-348612"><span class="HTitleText1">Assistance médicale</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-348634"><span class="HTitleText1">Règles et ordonnances</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-348639"><span class="HTitleText1">Délégation et frais d’application</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
