<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Regional Development Incentives Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-426565"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-426570"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-426595"><span class="HTitleText1">Designation of Regions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-426605"><span class="HTitleText1">Development Incentives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-426606"><span class="HTitleText2">Authorization of Incentives</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-426614"><span class="HTitleText2">Maximum Amounts</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-426642"><span class="HTitleText2">Determination of Amount of Incentive</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-426653"><span class="HTitleText2">Ineligible Facilities</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-426663"><span class="HTitleText2">Limiting Provisions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-426694"><span class="HTitleText2">Payment of Incentives</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-426713"><span class="HTitleText1">Tax Provisions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-426718"><span class="HTitleText1">Manpower Services</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-426728"><span class="HTitleText1">Loan Guarantees</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-426757"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-426766"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-426786"><span class="HTitleText1">Regional Development Incentives Board</span></a>
</li></ul>
</li></ul>

</nav>

