<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
British Columbia Treaty Commission Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-33847"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-33850"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-33860"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-33863"><span class="HTitleText1">Establishment of Commission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-33871"><span class="HTitleText1">Purpose and Powers of Commission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-33885"><span class="HTitleText1">Commissioners</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-33911"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-33932"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-33940"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-33943"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-33946"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-33949"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-33957"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>23 and 24 - </span><a href="#h-33963"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-33965"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
