<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Trademarks Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-450119"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-450124"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-450214"><span class="HTitleText1">Unfair Competition and Prohibited Signs</span></a>
</li>
<li><span class='sectionRange'>11.11 - </span><a href="#h-450284"><span class="HTitleText1">Geographical Indications</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-450601"><span class="HTitleText1">Registrable Trademarks</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-450650"><span class="HTitleText1">Persons Entitled to Registration of Trademarks</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-450673"><span class="HTitleText1">Validity and Effect of Registration</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-450732"><span class="HTitleText1">Certification Marks</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-450752"><span class="HTitleText1">Register of Trademarks</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-450811"><span class="HTitleText1">Applications for Registration of Trademarks</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-450916"><span class="HTitleText1">Registration of Trademarks</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-450935"><span class="HTitleText1">Amendment of the Register</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-450981"><span class="HTitleText1">Renewal of Registrations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-450993"><span class="HTitleText1">Extensions of Time</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-451001"><span class="HTitleText1">Transfer</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-451011"><span class="HTitleText1">Change of Purpose in Use of Trademark</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-451016"><span class="HTitleText1">Licences</span></a>
</li>
<li><span class='sectionRange'>51.01 - </span><a href="#h-451043"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>51.02 - </span><a href="#h-451085"><span class="HTitleText1">Importation and Exportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51.02 - </span><a href="#h-451086"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>51.03 - </span><a href="#h-451099"><span class="HTitleText2">Prohibition</span></a>
</li>
<li><span class='sectionRange'>51.04 - </span><a href="#h-451126"><span class="HTitleText2">Request for Assistance</span></a>
</li>
<li><span class='sectionRange'>51.05 - </span><a href="#h-451143"><span class="HTitleText2">Measures Relating to Detained Goods</span></a>
</li>
<li><span class='sectionRange'>51.1 - </span><a href="#h-451200"><span class="HTitleText2">No Liability</span></a>
</li>
<li><span class='sectionRange'>51.11 - </span><a href="#h-451208"><span class="HTitleText2">Powers of Court Relating to Detained Goods</span></a>
</li></ul>
</li><li><span class='sectionRange'>51.13 - </span><a href="#h-451230"><span class="HTitleText1">Trademark Agents</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-451249"><span class="HTitleText1">Legal Proceedings</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-451370"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-451416"><span class="HTitleText1">Newfoundland</span></a>
</li>
<li><span class='sectionRange'>68.1 - </span><a href="#h-451428"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><a href="#h-451445"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

