<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Société canadienne des postes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-58615"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-58620"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-58652"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-58657"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Société canadienne des postes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-58658"><span class="HTitleText2">Constitution de la Société</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-58663"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-58679"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-58695"><span class="HTitleText2">Président du conseil</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-58705"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-58717"><span class="HTitleText2">Siège social</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-58722"><span class="HTitleText2">Gestion de la Société</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-58738"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-58755"><span class="HTitleText2">Privilège exclusif de la Société</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-58781"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-58797"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="#h-58852"><span class="HTitleText2">Rapports</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-58862"><span class="HTitleText2">Instructions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-58879"><span class="HTitleText2">Statut de la Société</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-58903"><span class="HTitleText2">Dispositions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-58980"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-58981"><span class="HTitleText2">Pouvoirs publics</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-59007"><span class="HTitleText2">Conventions</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-59012"><span class="HTitleText2">Transmission des envois</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-59020"><span class="HTitleText2">Services financiers</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-59022"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-59034"><span class="HTitleText2">Ouverture des envois</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-59045"><span class="HTitleText2">Douanes</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-59061"><span class="HTitleText2">Arrêté d’interdiction</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-59118"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-59199"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

