<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting the Hudson Bay Mining and Smelting Co., Limited</a><ul class="TocIndent"><li><a href="#h-254937"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Manitoba Safety and Health Laws</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
