<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Port of Montreal Operations Act, 2021</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1292138"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1292141"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1292156"><span class="HTitleText1">Port of Montreal Operations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1292170"><span class="HTitleText1">Extension of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-1292181"><span class="HTitleText1">Mediator-Arbitrator</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-1292209"><span class="HTitleText1">New Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-1292225"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1292237"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
