<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur les sociétés par actions</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Définitions et application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Objet</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Constitution</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Capacité et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-8"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Siège social et livres</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Financement</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-10"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Vente d’actions faisant l’objet de restrictions</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-11"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Certificats de valeurs mobilières, registres et transferts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-12"><span class="HTitleText2">Définitions et dispositions générales</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-13"><span class="HTitleText2">Émission — Émetteur</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-14"><span class="HTitleText2">Acquisition</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-15"><span class="HTitleText2">Inscription</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-16"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Acte de fiducie</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-17"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Séquestres et séquestres-gérants</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-18"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-19"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Transactions d’initiés</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-20"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Actionnaires</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-21"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Procurations</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-22"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Présentation de renseignements d’ordre financier</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-23"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Modifications de structure</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-24"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Opérations de fermeture et d’éviction</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-25"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Acquisitions forcées</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-26"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Liquidation et dissolution</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-27"><span class="HLabel1">PARTIE XIX</span> - <span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>237.1 - </span><a href="#h-28"><span class="HLabel1">PARTIE XIX.1</span> - <span class="HTitleText1">Répartition de l’indemnité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>237.1 - </span><a href="#h-29"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>237.3 - </span><a href="#h-30"><span class="HTitleText2">Répartition de l’indemnité</span></a>
</li>
<li><span class='sectionRange'>237.5 - </span><a href="#h-31"><span class="HTitleText2">Responsabilité solidaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>238 - </span><a href="#h-32"><span class="HLabel1">PARTIE XX</span> - <span class="HTitleText1">Recours, infractions et peines</span></a>
</li>
<li><span class='sectionRange'>252.1 - </span><a href="#h-33"><span class="HLabel1">PARTIE XX.1</span> - <span class="HTitleText1">Documents sous forme électronique ou autre</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-34"><span class="HLabel1">PARTIE XXI</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
