<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Officers Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-403864"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-403870"><span class="HTitleText1">Commissions</span></a>
</li>
<li><a href="#h-403881"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
