<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord sur le commerce intérieur <span class='Repealed'>[Abrogée, 2017, ch. 33, art. 228]</span></a></li></ul>
</nav>
</div></section>
