<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Student Loans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText1">Guaranteed Student Loans</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText1">Periods Free of Interest or Repayment</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Liability of the Minister</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText1">Special Interest-free Periods</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText1">Death or Disability of Borrower</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText1">Certificates of Eligibility</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText1">Alternative Payments</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>17.1 - </span><a href="#h-12"><span class="HTitleText1">Forms</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
