<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Wild Animal and Plant Protection and Regulation of International and Interprovincial Trade Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Binding on Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Federal Permits</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">Ticketable Offences</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-12"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-13"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
