<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les langues autochtones</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1137578"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1137581"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-1137594"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-1137611"><span class="HTitleText1">Droits relatifs aux langues autochtones</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-1137614"><span class="HTitleText1">Attributions ministérielles</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="page-1.html#h-1137625"><span class="HTitleText1">Institutions fédérales</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-1137637"><span class="HTitleText1">Bureau du commissaire aux langues autochtones</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-1.html#h-1137638"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-1137672"><span class="HTitleText2">Mission et attributions</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-1137727"><span class="HTitleText2">Gestion financière</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-2.html#h-1137804"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-2.html#h-1137824"><span class="HTitleText1">Règlements et règles</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-1137856"><span class="HTitleText1">Examen indépendant</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="page-3.html#h-1137870"><span class="HTitleText1">Examen parlementaire</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-3.html#h-1137873"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

