<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi fédérale sur les hydrocarbures</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-162087"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-162090"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-162127"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-162128"><span class="HTitleText2">Modalités des avis</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-162133"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-162136"><span class="HTitleText2">Obligation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-162139"><span class="HTitleText2">Nominations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-162158"><span class="HTitleText2">Dispositions générales sur les titres</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-162183"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Dispositions générales sur l’octroi des titres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-162184"><span class="HTitleText2">Pouvoir général</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-162192"><span class="HTitleText2">Titres sur des réserves de l’État</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-162236"><span class="HTitleText2">Plans de retombées économiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-162241"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Prospection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-162242"><span class="HTitleText2">Permis de prospection</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-162279"><span class="HTitleText2">Découvertes importantes</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-162299"><span class="HTitleText2">Attestation de découverte importante</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-162323"><span class="HTitleText2">Arrêtés de forage</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-162342"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-162343"><span class="HTitleText2">Découvertes exploitables</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-162357"><span class="HTitleText2">Arrêtés de mise en valeur</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-162373"><span class="HTitleText2">Licences de production</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-162413"><span class="HTitleText2">Licence de stockage souterrain</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-162419"><span class="HTitleText2">Critère d’obtention</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-162424"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">[Abrogée, 1993, ch. 47, art. 3]</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-162425"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Redevances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-162426"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-162429"><span class="HTitleText2">Paiement des redevances</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-162441"><span class="HTitleText2">Rapports et déclarations</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-162454"><span class="HTitleText2">Cotisation, oppositions et appels</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-162497"><span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-162500"><span class="HTitleText2">Recours spéciaux</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-162534"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-162549"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Fonds pour l’étude de l’environnement</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-162659"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Transferts, cessions et enregistrement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-162660"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-162683"><span class="HTitleText2">Transferts et cessions</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-162687"><span class="HTitleText2">Enregistrement</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-162793"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-162794"><span class="HTitleText2">Renseignements</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-162891"><span class="HTitleText2">Arbitrage</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-162912"><span class="HTitleText2">Annulation des titres</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-162920"><span class="HTitleText2">Audiences et révision</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-162946"><span class="HTitleText2">Dispositions réglementaires</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-162974"><span class="HTitleText2">Rapport</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-162977"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Dispositions transitoires, corrélatives et d’entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-162978"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>118 à 130 - </span><a href="#h-163061"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-163063"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

