<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les délais et autres périodes (COVID-19)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1245440"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1245443"><span class="HTitleText1">Définition, interprétation et champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-1245453"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-1245461"><span class="HTitleText1">Délais concernant les instances</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-1245474"><span class="HTitleText1">Autres délais et périodes</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-1245502"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-1245507"><span class="HTitleText1">Transparence et contrôle parlementaire</span></a>
</li>
<li><a href="page-2.html#h-1245519"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

