<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en œuvre de la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles et du Protocole portant sur les questions spécifiques aux matériels d’équipement aéronautiques à la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Force de loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Incompatibilité</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">Tribunaux</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText1">Demandes de déclaration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText1">Modifications à certaines lois</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-12"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-13"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-14"><span class="HTitleText2">Loi sur les liquidations et les restructurations</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-15"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles</span></a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole portant sur les questions spécifiques aux matériels d’équipement aéronautiques à la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles</span></a>
</li>
<li><a href="#h-18"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Texte refondu de la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles et de son Protocole portant sur les questions spécifiques aux matériels d’équipement aéronautiques</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
