<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Animal Pedigree Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-2837"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2840"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-2863"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-2869"><span class="HTitleText1">Purpose of Associations</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-2872"><span class="HTitleText1">Scope of Associations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-2880"><span class="HTitleText1">Incorporating an Association</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-2921"><span class="HTitleText1">Body Corporate</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-2924"><span class="HTitleText1">Powers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-2934"><span class="HTitleText1">Use of Funds</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-2942"><span class="HTitleText1">Liability</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-2948"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-2999"><span class="HTitleText1">Amendment of Articles of Incorporation</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-3058"><span class="HTitleText1">Amalgamations</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-3101"><span class="HTitleText1">Registration</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-3122"><span class="HTitleText1">Purebred Status</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-3128"><span class="HTitleText1">Identification</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-3143"><span class="HTitleText1">Semen and Embryos</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-3153"><span class="HTitleText1">Recognition of New Breeds</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-3165"><span class="HTitleText1">Canadian Livestock Records Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-3166"><span class="HTitleText2">Corporation Established</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-3176"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-3181"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-3194"><span class="HTitleText2">Use of Funds</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-3202"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-3224"><span class="HTitleText2">By-laws</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-3238"><span class="HTitleText2">General Manager</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-3244"><span class="HTitleText2">Members</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-3250"><span class="HTitleText2">Voting</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-3263"><span class="HTitleText2">Termination of Membership</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-3271"><span class="HTitleText2">Annual Meeting</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-3274"><span class="HTitleText2">Liability</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-3277"><span class="HTitleText2">General Stud and Herd Book</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-3286"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-3318"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-3323"><span class="HTitleText1">Dissolution</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-3336"><span class="HTitleText1">Miscellaneous</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-3365"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-3394"><span class="HTitleText1">Existing Associations</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-3421"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-3429"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-3431"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

