<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Code criminel</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-111940"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-111945"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-112165"><span class="HTitleText1">Partie I</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3.1 - </span><a href="#h-112166"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-112481"><span class="HTitleText2">Participants aux infractions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-112531"><span class="HTitleText2">Protection des personnes chargées de l’application et de l’exécution de la loi</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-112701"><span class="HTitleText2">Répression des émeutes</span></a>
</li>
<li><span class='sectionRange'>33.1 - </span><a href="#h-112730"><span class="HTitleText2">Intoxication volontaire</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-112740"><span class="HTitleText2">Défense de la personne</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-112762"><span class="HTitleText2">Défense des biens</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-112788"><span class="HTitleText2">Protection des personnes exerçant l’autorité</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-112800"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Infractions contre l’ordre public</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-112801"><span class="HTitleText2">Trahison et autres infractions contre l’autorité et la personne de la reine</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-112846"><span class="HTitleText2">Actes prohibés</span></a>
</li>
<li><span class='sectionRange'>56.1 - </span><a href="#h-112903"><span class="HTitleText2">Documents officiels</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-112957"><span class="HTitleText2">Sédition</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-113002"><span class="HTitleText2">Attroupements illégaux et émeutes</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-113049"><span class="HTitleText2">Exercices illégaux</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-113064"><span class="HTitleText2">Duels</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-113066"><span class="HTitleText2">Prise de possession et détention par la force</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-113084"><span class="HTitleText2">Piraterie</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-113101"><span class="HTitleText2">Infractions portant atteinte à la sécurité aérienne ou maritime</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-113149"><span class="HTitleText2">Matières et engins dangereux</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-113216"><span class="HTitleText2">Combats concertés</span></a>
</li></ul>
</li><li><span class='sectionRange'>83.01 - </span><a href="#h-113231"><span class="HLabel1">PARTIE II.1</span> - <span class="HTitleText1">Terrorisme</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83.01 - </span><a href="#h-113232"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>83.02 - </span><a href="#h-113274"><span class="HTitleText2">Financement du terrorisme</span></a>
</li>
<li><span class='sectionRange'>83.05 - </span><a href="#h-113293"><span class="HTitleText2">Inscription des entités</span></a>
</li>
<li><span class='sectionRange'>83.08 - </span><a href="#h-113350"><span class="HTitleText2">Blocage des biens</span></a>
</li>
<li><span class='sectionRange'>83.13 - </span><a href="#h-113413"><span class="HTitleText2">Saisie et blocage de biens</span></a>
</li>
<li><span class='sectionRange'>83.14 - </span><a href="#h-113459"><span class="HTitleText2">Confiscation des biens</span></a>
</li>
<li><span class='sectionRange'>83.18 - </span><a href="#h-113511"><span class="HTitleText2">Participer, faciliter, donner des instructions et héberger</span></a>
</li>
<li><span class='sectionRange'>83.231 - </span><a href="#h-113664"><span class="HTitleText2">Incitation à craindre des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>83.24 - </span><a href="#h-113682"><span class="HTitleText2">Procédure et aggravation de peine</span></a>
</li>
<li><span class='sectionRange'>83.28 - </span><a href="#h-113707"><span class="HTitleText2">Investigation</span></a>
</li>
<li><span class='sectionRange'>83.3 - </span><a href="#h-113762"><span class="HTitleText2">Engagement assorti de conditions</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-113881"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Armes à feu et autres armes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-113882"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-113962"><span class="HTitleText2">Infractions relatives à l’usage</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-114005"><span class="HTitleText2">Infractions relatives à la possession</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-114154"><span class="HTitleText2">Infractions relatives au trafic</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-114186"><span class="HTitleText2">Infraction relative à l’assemblage</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-114196"><span class="HTitleText2">Infractions relatives à l’importation ou l’exportation</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-114225"><span class="HTitleText2">Infractions relatives aux armes perdues, volées, trouvées, détruites ou maquillées</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-114272"><span class="HTitleText2">Ordonnance d’interdiction</span></a>
</li>
<li><span class='sectionRange'>117.011 - </span><a href="#h-114412"><span class="HTitleText2">Ordonnance de restriction</span></a>
</li>
<li><span class='sectionRange'>117.02 - </span><a href="#h-114438"><span class="HTitleText2">Perquisition et saisie</span></a>
</li>
<li><span class='sectionRange'>117.07 - </span><a href="#h-114498"><span class="HTitleText2">Dispenses</span></a>
</li>
<li><span class='sectionRange'>117.11 - </span><a href="#h-114557"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-114603"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Infractions contre l’application de la loi et l’administration de la justice</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="#h-114604"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-114629"><span class="HTitleText2">Corruption et désobéissance</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-114778"><span class="HTitleText2">Personnes qui trompent la justice</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-114874"><span class="HTitleText2">Évasion et délivrance de prisonniers</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-114950"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Infractions d’ordre sexuel, actes contraires aux bonnes moeurs, inconduite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-114951"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>150.1 - </span><a href="#h-114959"><span class="HTitleText2">Infractions d’ordre sexuel</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-115166"><span class="HTitleText2">Infractions tendant à corrompre les moeurs</span></a>
</li>
<li><span class='sectionRange'>172.2 - </span><a href="#h-115408"><span class="HTitleText2">Inconduite</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-115492"><span class="HTitleText2">Nuisances</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="#h-115514"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Atteintes à la vie privée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-115515"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-115724"><span class="HTitleText2">Interception des communications</span></a>
</li></ul>
</li><li><span class='sectionRange'>197 - </span><a href="#h-116147"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Maisons de désordre, jeux et paris</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-116148"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-116192"><span class="HTitleText2">Présomptions</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-116194"><span class="HTitleText2">Perquisition</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-116214"><span class="HTitleText2">Entrave à l’exécution d’un mandat</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-116216"><span class="HTitleText2">Jeux et paris</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-116427"><span class="HTitleText2">Maisons de débauche</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-116447"><span class="HTitleText2">Infractions se rattachant à l’offre, à la prestation ou à l’obtention de services sexuels moyennant rétribution</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-116460"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Infractions contre la personne et la réputation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-116461"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-116477"><span class="HTitleText2">Devoirs tendant à la conservation de la vie</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-116522"><span class="HTitleText2">Négligence criminelle</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-116543"><span class="HTitleText2">Homicide</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-116605"><span class="HTitleText2">Meurtre, homicide involontaire coupable et infanticide</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="#h-116728"><span class="HTitleText2">Suicide</span></a>
</li>
<li><span class='sectionRange'>241.1 - </span><a href="#h-116750"><span class="HTitleText2">Aide médicale à mourir</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-116859"><span class="HTitleText2">Négligence à la naissance d’un enfant et suppression de part</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-116868"><span class="HTitleText2">Lésions corporelles et actes et omissions qui mettent les personnes en danger</span></a>
</li>
<li><span class='sectionRange'>264.1 - </span><a href="#h-117018"><span class="HTitleText2">Voies de fait</span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-117487"><span class="HTitleText2">Enlèvement, traite des personnes, prise d’otage et rapt</span></a>
</li>
<li><span class='sectionRange'>286.1 - </span><a href="#h-117627"><span class="HTitleText2">Marchandisation des activités sexuelles</span></a>
</li>
<li><span class='sectionRange'>287 - </span><a href="#h-117705"><span class="HTitleText2">Avortement</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="#h-117745"><span class="HTitleText2">Maladies vénériennes</span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-117747"><span class="HTitleText2">Infractions aux droits conjugaux</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-117804"><span class="HTitleText2">Célébration illicite du mariage</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-117816"><span class="HTitleText2">Libelle diffamatoire</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="#h-117957"><span class="HTitleText2">Verdicts</span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="#h-117962"><span class="HTitleText2">Propagande haineuse</span></a>
</li></ul>
</li><li><span class='sectionRange'>320.11 - </span><a href="#h-118063"><span class="HLabel1">PARTIE VIII.1</span> - <span class="HTitleText1">Infractions relatives aux moyens de transport</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>320.11 - </span><a href="#h-118064"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>320.12 - </span><a href="#h-118085"><span class="HTitleText2">Reconnaissance et déclaration</span></a>
</li>
<li><span class='sectionRange'>320.13 - </span><a href="#h-118094"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>320.27 - </span><a href="#h-118273"><span class="HTitleText2">Questions relatives aux enquêtes</span></a>
</li>
<li><span class='sectionRange'>320.31 - </span><a href="#h-118346"><span class="HTitleText2">Questions relatives à la preuve</span></a>
</li>
<li><span class='sectionRange'>320.36 - </span><a href="#h-118421"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>321 - </span><a href="#h-118467"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Infractions contre les droits de propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>321 - </span><a href="#h-118468"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="#h-118489"><span class="HTitleText2">Vol</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-118597"><span class="HTitleText2">Infractions ressemblant au vol</span></a>
</li>
<li><span class='sectionRange'>343 - </span><a href="#h-118735"><span class="HTitleText2">Vol qualifié et extorsion</span></a>
</li>
<li><span class='sectionRange'>347 - </span><a href="#h-118788"><span class="HTitleText2">Taux d’intérêt criminel</span></a>
</li>
<li><span class='sectionRange'>348 - </span><a href="#h-118833"><span class="HTitleText2">Introduction par effraction</span></a>
</li>
<li><span class='sectionRange'>354 - </span><a href="#h-118929"><span class="HTitleText2">Possession et trafic</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-119012"><span class="HTitleText2">Escroquerie</span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="#h-119073"><span class="HTitleText2">Faux et infractions similaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>379 - </span><a href="#h-119196"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Opérations frauduleuses en matière de contrats et de commerce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>379 - </span><a href="#h-119197"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="#h-119202"><span class="HTitleText2">Fraude</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="#h-119427"><span class="HTitleText2">Falsification de livres et documents</span></a>
</li>
<li><span class='sectionRange'>402.1 - </span><a href="#h-119468"><span class="HTitleText2">Vol d’identité et fraude à l’identité</span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="#h-119518"><span class="HTitleText2">Contrefaçon de marques de commerce et de désignations de fabrique</span></a>
</li>
<li><span class='sectionRange'>415 - </span><a href="#h-119570"><span class="HTitleText2">Épaves</span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-119583"><span class="HTitleText2">Approvisionnements publics</span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="#h-119634"><span class="HTitleText2">Violation de contrat, intimidation et distinction injuste envers les syndiqués</span></a>
</li>
<li><span class='sectionRange'>426 - </span><a href="#h-119706"><span class="HTitleText2">Commissions secrètes</span></a>
</li></ul>
</li><li><span class='sectionRange'>428 - </span><a href="#h-119724"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Actes volontaires et prohibés concernant certains biens</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>428 - </span><a href="#h-119725"><span class="HTitleText2">Définition et interprétation</span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="#h-119741"><span class="HTitleText2">Méfaits</span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="#h-119845"><span class="HTitleText2">Crime d’incendie et autres incendies</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="#h-119878"><span class="HTitleText2">Autres interventions concernant des biens</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="#h-119925"><span class="HTitleText2">Animaux</span></a>
</li>
<li><span class='sectionRange'>445.1 - </span><a href="#h-119955"><span class="HTitleText2">Cruauté envers les animaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>448 - </span><a href="#h-120009"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Infractions relatives à la monnaie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>448 - </span><a href="#h-120010"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-120025"><span class="HTitleText2">Fabrication</span></a>
</li>
<li><span class='sectionRange'>450 - </span><a href="#h-120030"><span class="HTitleText2">Possession</span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-120045"><span class="HTitleText2">Mise en circulation</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="#h-120062"><span class="HTitleText2">Dégradation ou affaiblissement de la monnaie</span></a>
</li>
<li><span class='sectionRange'>458 - </span><a href="#h-120091"><span class="HTitleText2">Instruments ou matières</span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="#h-120103"><span class="HTitleText2">Annonce et trafic de la monnaie contrefaite ou des symboles de valeur contrefaits</span></a>
</li>
<li><span class='sectionRange'>461 - </span><a href="#h-120113"><span class="HTitleText2">Dispositions spéciales relatives à la preuve</span></a>
</li>
<li><span class='sectionRange'>462 - </span><a href="#h-120125"><span class="HTitleText2">Confiscation</span></a>
</li></ul>
</li><li><span class='sectionRange'>462.1 - </span><a href="#h-120137"><span class="HLabel1">PARTIE XII.1</span> - <span class="HTitleText1">[Abrogée, 2018, ch. 16, art. 211]</span></a>
</li>
<li><span class='sectionRange'>462.3 - </span><a href="#h-120140"><span class="HLabel1">PARTIE XII.2</span> - <span class="HTitleText1">Produits de la criminalité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>462.3 - </span><a href="#h-120141"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>462.31 - </span><a href="#h-120166"><span class="HTitleText2">Infraction</span></a>
</li>
<li><span class='sectionRange'>462.32 - </span><a href="#h-120180"><span class="HTitleText2">Perquisitions, fouilles, saisies et détention</span></a>
</li>
<li><span class='sectionRange'>462.37 - </span><a href="#h-120342"><span class="HTitleText2">Confiscation des produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>462.47 - </span><a href="#h-120507"><span class="HTitleText2">Restriction du droit d’action</span></a>
</li>
<li><span class='sectionRange'>462.49 - </span><a href="#h-120569"><span class="HTitleText2">Autres dispositions en matière de confiscation</span></a>
</li>
<li><span class='sectionRange'>462.5 - </span><a href="#h-120577"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>463 - </span><a href="#h-120582"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Tentatives — complots — complices</span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-120709"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Juridiction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>468 - </span><a href="#h-120710"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>476 - </span><a href="#h-120782"><span class="HTitleText2">Juridiction spéciale</span></a>
</li>
<li><span class='sectionRange'>482 - </span><a href="#h-120894"><span class="HTitleText2">Règles de cour</span></a>
</li></ul>
</li><li><span class='sectionRange'>483 - </span><a href="#h-120950"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Procédure et pouvoirs spéciaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>483 - </span><a href="#h-120951"><span class="HTitleText2">Pouvoirs généraux de certains fonctionnaires</span></a>
</li>
<li><span class='sectionRange'>487.04 - </span><a href="#h-121473"><span class="HTitleText2">Analyse génétique effectuée à des fins médicolégales</span></a>
</li>
<li><span class='sectionRange'>487.1 - </span><a href="#h-121896"><span class="HTitleText2">Autres dispositions : mandats de perquisition et ordonnances de préservation ou de communication</span></a>
</li>
<li><span class='sectionRange'>490.011 - </span><a href="#h-122191"><span class="HTitleText2">Renseignements sur les délinquants sexuels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>490.011 - </span><a href="#h-122192"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>490.012 - </span><a href="#h-122286"><span class="HTitleText3">Ordonnance de se conformer à la <cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite></span></a>
</li>
<li><span class='sectionRange'>490.019 - </span><a href="#h-122385"><span class="HTitleText3">Avis et obligation de se conformer à la <cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite> — condamnations antérieures au 15 décembre 2004</span></a>
</li>
<li><span class='sectionRange'>490.02901 - </span><a href="#h-122497"><span class="HTitleText3">Avis et obligation de se conformer à la <cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite> — condamnations à l’étranger</span></a>
</li>
<li><span class='sectionRange'>490.02912 - </span><a href="#h-122600"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le transfèrement international des délinquants</cite></span></a>
</li>
<li><span class='sectionRange'>490.03 - </span><a href="#h-122640"><span class="HTitleText3">Communications de renseignements</span></a>
</li>
<li><span class='sectionRange'>490.031 - </span><a href="#h-122653"><span class="HTitleText3">Infractions</span></a>
</li>
<li><span class='sectionRange'>490.032 - </span><a href="#h-122679"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>490.1 - </span><a href="#h-122686"><span class="HTitleText2">Confiscation de biens infractionnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>493 - </span><a href="#h-122975"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Mesures concernant la comparution d’un prévenu devant un juge de paix et la mise en liberté provisoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>493 - </span><a href="#h-122976"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>494 - </span><a href="#h-122998"><span class="HTitleText2">Arrestation sans mandat et mise en liberté</span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-123138"><span class="HTitleText2">Comparution du prévenu devant un juge de paix</span></a>
</li>
<li><span class='sectionRange'>504 - </span><a href="#h-123186"><span class="HTitleText2">Dénonciation, sommation et mandat</span></a>
</li>
<li><span class='sectionRange'>515 - </span><a href="#h-123345"><span class="HTitleText2">Mise en liberté provisoire par voie judiciaire</span></a>
</li>
<li><span class='sectionRange'>524 - </span><a href="#h-123586"><span class="HTitleText2">Arrestation d’un prévenu en liberté</span></a>
</li>
<li><span class='sectionRange'>525 - </span><a href="#h-123630"><span class="HTitleText2">Examen de la détention quand le procès est retardé</span></a>
</li>
<li><span class='sectionRange'>527 - </span><a href="#h-123673"><span class="HTitleText2">Procédure en vue d’obtenir la comparution d’un prisonnier</span></a>
</li>
<li><span class='sectionRange'>528 - </span><a href="#h-123699"><span class="HTitleText2">Visa du mandat</span></a>
</li>
<li><span class='sectionRange'>529 - </span><a href="#h-123709"><span class="HTitleText2">Entrée dans une maison d’habitation pour arrestation</span></a>
</li></ul>
</li><li><span class='sectionRange'>530 - </span><a href="#h-123754"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Langue de l’accusé</span></a>
</li>
<li><span class='sectionRange'>535 - </span><a href="#h-123826"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Procédure à l’enquête préliminaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>535 - </span><a href="#h-123827"><span class="HTitleText2">Juridiction</span></a>
</li>
<li><span class='sectionRange'>536.3 - </span><a href="#h-123884"><span class="HTitleText2">Procédures précédant l’enquête préliminaire</span></a>
</li>
<li><span class='sectionRange'>537 - </span><a href="#h-123905"><span class="HTitleText2">Pouvoirs du juge de paix</span></a>
</li>
<li><span class='sectionRange'>539 - </span><a href="#h-123934"><span class="HTitleText2">Manière de recueillir les témoignages</span></a>
</li>
<li><span class='sectionRange'>543 - </span><a href="#h-123998"><span class="HTitleText2">Renvoi lorsque l’infraction a été commise dans une autre juridiction</span></a>
</li>
<li><span class='sectionRange'>544 - </span><a href="#h-124011"><span class="HTitleText2">Prévenu qui s’esquive</span></a>
</li>
<li><span class='sectionRange'>545 - </span><a href="#h-124030"><span class="HTitleText2">Procédure lorsque le témoin refuse de déposer</span></a>
</li>
<li><span class='sectionRange'>546 - </span><a href="#h-124045"><span class="HTitleText2">Dispositions rectificatives</span></a>
</li>
<li><span class='sectionRange'>548 - </span><a href="#h-124063"><span class="HTitleText2">Décision et engagements</span></a>
</li>
<li><span class='sectionRange'>551 - </span><a href="#h-124101"><span class="HTitleText2">Transmission du dossier</span></a>
</li></ul>
</li><li><span class='sectionRange'>551.1 - </span><a href="#h-124106"><span class="HLabel1">PARTIE XVIII.1</span> - <span class="HTitleText1">Juge responsable de la gestion de l’instance</span></a>
</li>
<li><span class='sectionRange'>552 - </span><a href="#h-124200"><span class="HLabel1">PARTIE XIX</span> - <span class="HTitleText1">Actes criminels — procès sans jury</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>552 - </span><a href="#h-124201"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>553 - </span><a href="#h-124219"><span class="HTitleText2">Juridiction des juges de la cour provinciale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>553 - </span><a href="#h-124220"><span class="HTitleText3">Juridiction absolue</span></a>
</li>
<li><span class='sectionRange'>554 - </span><a href="#h-124250"><span class="HTitleText3">Juridiction du juge de la cour provinciale avec consentement</span></a>
</li></ul>
</li><li><span class='sectionRange'>558 - </span><a href="#h-124299"><span class="HTitleText2">Juridiction des juges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>558 - </span><a href="#h-124300"><span class="HTitleText3">Juridiction du juge avec consentement</span></a>
</li>
<li><span class='sectionRange'>560 - </span><a href="#h-124312"><span class="HTitleText3">Choix</span></a>
</li>
<li><span class='sectionRange'>566 - </span><a href="#h-124428"><span class="HTitleText3">Procès</span></a>
</li></ul>
</li><li><span class='sectionRange'>567 - </span><a href="#h-124449"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>573 - </span><a href="#h-124495"><span class="HLabel1">PARTIE XIX.1</span> - <span class="HTitleText1">Cour de justice du Nunavut</span></a>
</li>
<li><span class='sectionRange'>574 - </span><a href="#h-124566"><span class="HLabel1">PARTIE XX</span> - <span class="HTitleText1">Procédure lors d’un procès devant jury et dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>574 - </span><a href="#h-124567"><span class="HTitleText2">Présentation de l’acte d’accusation</span></a>
</li>
<li><span class='sectionRange'>581 - </span><a href="#h-124636"><span class="HTitleText2">Dispositions générales quant aux chefs d’accusation</span></a>
</li>
<li><span class='sectionRange'>584 - </span><a href="#h-124671"><span class="HTitleText2">Dispositions spéciales quant aux chefs d’accusation</span></a>
</li>
<li><span class='sectionRange'>587 - </span><a href="#h-124694"><span class="HTitleText2">Détails</span></a>
</li>
<li><span class='sectionRange'>588 - </span><a href="#h-124714"><span class="HTitleText2">Propriété de biens</span></a>
</li>
<li><span class='sectionRange'>589 - </span><a href="#h-124719"><span class="HTitleText2">Réunion ou séparation de chefs d’accusation</span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-124763"><span class="HTitleText2">Réunion des accusés dans certains cas</span></a>
</li>
<li><span class='sectionRange'>597 - </span><a href="#h-124780"><span class="HTitleText2">Procédure lorsque l’accusé est en liberté</span></a>
</li>
<li><span class='sectionRange'>599 - </span><a href="#h-124809"><span class="HTitleText2">Renvoi de l’affaire devant le tribunal d’une autre circonscription territoriale</span></a>
</li>
<li><span class='sectionRange'>601 - </span><a href="#h-124828"><span class="HTitleText2">Modification</span></a>
</li>
<li><span class='sectionRange'>603 - </span><a href="#h-124875"><span class="HTitleText2">Inspection et copies des documents</span></a>
</li>
<li><span class='sectionRange'>606 - </span><a href="#h-124894"><span class="HTitleText2">Plaidoyers</span></a>
</li>
<li><span class='sectionRange'>620 - </span><a href="#h-125000"><span class="HTitleText2">Organisations</span></a>
</li>
<li><span class='sectionRange'>624 - </span><a href="#h-125020"><span class="HTitleText2">Dossier des procédures</span></a>
</li>
<li><span class='sectionRange'>625.1 - </span><a href="#h-125032"><span class="HTitleText2">Conférence préparatoire</span></a>
</li>
<li><span class='sectionRange'>626 - </span><a href="#h-125040"><span class="HTitleText2">Jurys</span></a>
</li>
<li><span class='sectionRange'>628 - </span><a href="#h-125056"><span class="HTitleText2">Récusation du tableau des jurés</span></a>
</li>
<li><span class='sectionRange'>631 - </span><a href="#h-125071"><span class="HTitleText2">Formation de la liste du jury</span></a>
</li>
<li><span class='sectionRange'>645 - </span><a href="#h-125218"><span class="HTitleText2">Procès</span></a>
</li>
<li><span class='sectionRange'>655 - </span><a href="#h-125348"><span class="HTitleText2">Preuve au procès</span></a>
</li>
<li><span class='sectionRange'>658 - </span><a href="#h-125417"><span class="HTitleText2">Enfants et jeunes personnes</span></a>
</li>
<li><span class='sectionRange'>659 - </span><a href="#h-125431"><span class="HTitleText2">Corroboration</span></a>
</li>
<li><span class='sectionRange'>660 - </span><a href="#h-125436"><span class="HTitleText2">Verdicts</span></a>
</li>
<li><span class='sectionRange'>664 - </span><a href="#h-125472"><span class="HTitleText2">Condamnations antérieures</span></a>
</li>
<li><span class='sectionRange'>669.1 - </span><a href="#h-125505"><span class="HTitleText2">Juridiction</span></a>
</li>
<li><span class='sectionRange'>670 - </span><a href="#h-125534"><span class="HTitleText2">Vices de forme dans la convocation des jurés</span></a>
</li></ul>
</li><li><span class='sectionRange'>672.1 - </span><a href="#h-125549"><span class="HLabel1">PARTIE XX.1</span> - <span class="HTitleText1">Troubles mentaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>672.1 - </span><a href="#h-125550"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>672.11 - </span><a href="#h-125576"><span class="HTitleText2">Ordonnance d’évaluation de l’état mental</span></a>
</li>
<li><span class='sectionRange'>672.2 - </span><a href="#h-125667"><span class="HTitleText2">Rapports d’évaluation</span></a>
</li>
<li><span class='sectionRange'>672.21 - </span><a href="#h-125679"><span class="HTitleText2">Déclarations protégées</span></a>
</li>
<li><span class='sectionRange'>672.22 - </span><a href="#h-125696"><span class="HTitleText2">Aptitude à subir son procès</span></a>
</li>
<li><span class='sectionRange'>672.34 - </span><a href="#h-125776"><span class="HTitleText2">Verdict de non-responsabilité criminelle pour cause de troubles mentaux</span></a>
</li>
<li><span class='sectionRange'>672.38 - </span><a href="#h-125805"><span class="HTitleText2">Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>672.45 - </span><a href="#h-125850"><span class="HTitleText2">Audiences</span></a>
</li>
<li><span class='sectionRange'>672.54 - </span><a href="#h-126046"><span class="HTitleText2">Décisions rendues par le tribunal ou la commission d’examen</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>672.54 - </span><a href="#h-126047"><span class="HTitleText3">Modalités des décisions</span></a>
</li>
<li><span class='sectionRange'>672.64 - </span><a href="#h-126133"><span class="HTitleText3">Accusé à haut risque</span></a>
</li>
<li><span class='sectionRange'>672.67 - </span><a href="#h-126157"><span class="HTitleText3">Contrevenants à double statut</span></a>
</li></ul>
</li><li><span class='sectionRange'>672.72 - </span><a href="#h-126208"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>672.81 - </span><a href="#h-126283"><span class="HTitleText2">Révision des décisions</span></a>
</li>
<li><span class='sectionRange'>672.85 - </span><a href="#h-126346"><span class="HTitleText2">Pouvoirs relatifs à la comparution</span></a>
</li>
<li><span class='sectionRange'>672.851 - </span><a href="#h-126353"><span class="HTitleText2">Suspension d’instance</span></a>
</li>
<li><span class='sectionRange'>672.86 - </span><a href="#h-126395"><span class="HTitleText2">Transfèrements interprovinciaux</span></a>
</li>
<li><span class='sectionRange'>672.9 - </span><a href="#h-126429"><span class="HTitleText2">Exécution des ordonnances et des règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>673 - </span><a href="#h-126479"><span class="HLabel1">PARTIE XXI</span> - <span class="HTitleText1">Appels — actes criminels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>673 - </span><a href="#h-126480"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>674 - </span><a href="#h-126495"><span class="HTitleText2">Droit d’appel</span></a>
</li>
<li><span class='sectionRange'>678 - </span><a href="#h-126559"><span class="HTitleText2">Procédures en appel</span></a>
</li>
<li><span class='sectionRange'>686 - </span><a href="#h-126702"><span class="HTitleText2">Pouvoirs de la cour d’appel</span></a>
</li>
<li><span class='sectionRange'>691 - </span><a href="#h-126794"><span class="HTitleText2">Appels à la Cour suprême du Canada</span></a>
</li>
<li><span class='sectionRange'>696 - </span><a href="#h-126863"><span class="HTitleText2">Appels par le procureur général du Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>696.1 - </span><a href="#h-126868"><span class="HLabel1">PARTIE XXI.1</span> - <span class="HTitleText1">Demandes de révision auprès du ministre — erreurs judiciaires</span></a>
</li>
<li><span class='sectionRange'>697 - </span><a href="#h-126918"><span class="HLabel1">PARTIE XXII</span> - <span class="HTitleText1">Assignation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>697 - </span><a href="#h-126919"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>698 - </span><a href="#h-126924"><span class="HTitleText2">Assignation ou mandat</span></a>
</li>
<li><span class='sectionRange'>701 - </span><a href="#h-126972"><span class="HTitleText2">Exécution ou signification</span></a>
</li>
<li><span class='sectionRange'>704 - </span><a href="#h-127009"><span class="HTitleText2">Témoin qui fait défaut ou s’esquive</span></a>
</li>
<li><span class='sectionRange'>708.1 - </span><a href="#h-127056"><span class="HTitleText2">Copies transmises par voie électronique</span></a>
</li>
<li><span class='sectionRange'>709 - </span><a href="#h-127061"><span class="HTitleText2">Témoignage par commission</span></a>
</li>
<li><span class='sectionRange'>714.1 - </span><a href="#h-127118"><span class="HTitleText2">Déposition à distance</span></a>
</li>
<li><span class='sectionRange'>715 - </span><a href="#h-127154"><span class="HTitleText2">Témoignages antérieurement recueillis</span></a>
</li>
<li><span class='sectionRange'>715.1 - </span><a href="#h-127173"><span class="HTitleText2">Enregistrement vidéo</span></a>
</li></ul>
</li><li><span class='sectionRange'>715.3 - </span><a href="#h-127188"><span class="HLabel1">PARTIE XXII.1</span> - <span class="HTitleText1">Accords de réparation</span></a>
</li>
<li><span class='sectionRange'>716 - </span><a href="#h-127389"><span class="HLabel1">PARTIE XXIII</span> - <span class="HTitleText1">Détermination de la peine</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>716 - </span><a href="#h-127390"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>717 - </span><a href="#h-127404"><span class="HTitleText2">Mesures de rechange</span></a>
</li>
<li><span class='sectionRange'>718 - </span><a href="#h-127475"><span class="HTitleText2">Objectif et principes</span></a>
</li>
<li><span class='sectionRange'>718.21 - </span><a href="#h-127519"><span class="HTitleText2">Organisations</span></a>
</li>
<li><span class='sectionRange'>718.3 - </span><a href="#h-127534"><span class="HTitleText2">Peines en général</span></a>
</li>
<li><span class='sectionRange'>720 - </span><a href="#h-127585"><span class="HTitleText2">Procédure et règles de preuve</span></a>
</li>
<li><span class='sectionRange'>730 - </span><a href="#h-127763"><span class="HTitleText2">Absolutions inconditionnelles et sous conditions</span></a>
</li>
<li><span class='sectionRange'>731 - </span><a href="#h-127778"><span class="HTitleText2">Probation</span></a>
</li>
<li><span class='sectionRange'>734 - </span><a href="#h-127949"><span class="HTitleText2">Amendes et confiscations</span></a>
</li>
<li><span class='sectionRange'>737.1 - </span><a href="#h-128116"><span class="HTitleText2">Dédommagement</span></a>
</li>
<li><span class='sectionRange'>742 - </span><a href="#h-128186"><span class="HTitleText2">Condamnations à l’emprisonnement avec sursis</span></a>
</li>
<li><span class='sectionRange'>743 - </span><a href="#h-128400"><span class="HTitleText2">Emprisonnement</span></a>
</li>
<li><span class='sectionRange'>743.6 - </span><a href="#h-128454"><span class="HTitleText2">Admissibilité à la libération conditionnelle</span></a>
</li>
<li><span class='sectionRange'>744 - </span><a href="#h-128466"><span class="HTitleText2">Remise du délinquant au gardien de prison</span></a>
</li>
<li><span class='sectionRange'>745 - </span><a href="#h-128471"><span class="HTitleText2">Emprisonnement à perpétuité</span></a>
</li>
<li><span class='sectionRange'>748 - </span><a href="#h-128649"><span class="HTitleText2">Pardon et remises</span></a>
</li>
<li><span class='sectionRange'>750 - </span><a href="#h-128672"><span class="HTitleText2">Incapacité</span></a>
</li>
<li><span class='sectionRange'>751 - </span><a href="#h-128691"><span class="HTitleText2">Dispositions diverses</span></a>
</li></ul>
</li><li><span class='sectionRange'>752 - </span><a href="#h-128700"><span class="HLabel1">PARTIE XXIV</span> - <span class="HTitleText1">Délinquants dangereux et délinquants à contrôler</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>752 - </span><a href="#h-128701"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>752.01 - </span><a href="#h-128793"><span class="HTitleText2">Délinquants dangereux et délinquants à contrôler</span></a>
</li></ul>
</li><li><span class='sectionRange'>762 - </span><a href="#h-128980"><span class="HLabel1">PARTIE XXV</span> - <span class="HTitleText1">Effet et mise à exécution des engagements</span></a>
</li>
<li><span class='sectionRange'>774 - </span><a href="#h-129091"><span class="HLabel1">PARTIE XXVI</span> - <span class="HTitleText1">Recours extraordinaires</span></a>
</li>
<li><span class='sectionRange'>785 - </span><a href="#h-129183"><span class="HLabel1">PARTIE XXVII</span> - <span class="HTitleText1">Déclarations de culpabilité par procédure sommaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>785 - </span><a href="#h-129184"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>787 - </span><a href="#h-129217"><span class="HTitleText2">Peine</span></a>
</li>
<li><span class='sectionRange'>788 - </span><a href="#h-129226"><span class="HTitleText2">Dénonciation</span></a>
</li>
<li><span class='sectionRange'>793 - </span><a href="#h-129256"><span class="HTitleText2">Irrégularités et objections</span></a>
</li>
<li><span class='sectionRange'>795 - </span><a href="#h-129264"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>798 - </span><a href="#h-129270"><span class="HTitleText2">Procès</span></a>
</li>
<li><span class='sectionRange'>804 - </span><a href="#h-129329"><span class="HTitleText2">Décision</span></a>
</li>
<li><span class='sectionRange'>810 - </span><a href="#h-129370"><span class="HTitleText2">Engagement de ne pas troubler l’ordre public</span></a>
</li>
<li><span class='sectionRange'>812 - </span><a href="#h-129646"><span class="HTitleText2">Appel</span></a>
</li>
<li><span class='sectionRange'>816 - </span><a href="#h-129694"><span class="HTitleText2">Mise en liberté provisoire de l’appelant</span></a>
</li>
<li><span class='sectionRange'>821 - </span><a href="#h-129744"><span class="HTitleText2">Procédure sur appel</span></a>
</li>
<li><span class='sectionRange'>829 - </span><a href="#h-129821"><span class="HTitleText2">Appels sommaires basés sur une transcription ou un exposé conjoint des faits sur lequel les parties se sont entendues</span></a>
</li>
<li><span class='sectionRange'>839 - </span><a href="#h-129887"><span class="HTitleText2">Pourvois devant la cour d’appel</span></a>
</li>
<li><span class='sectionRange'>840 - </span><a href="#h-129905"><span class="HTitleText2">Honoraires et allocations</span></a>
</li></ul>
</li><li><span class='sectionRange'>841 - </span><a href="#h-129913"><span class="HLabel1">PARTIE XXVIII</span> - <span class="HTitleText1">Dispositions diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>841 - </span><a href="#h-129914"><span class="HTitleText2">Documents électroniques</span></a>
</li>
<li><span class='sectionRange'>848 - </span><a href="#h-129951"><span class="HTitleText2">Comparution à distance de l’accusé</span></a>
</li>
<li><span class='sectionRange'>849 - </span><a href="#h-129956"><span class="HTitleText2">Formules</span></a>
</li></ul>
</li><li><a href="#h-129967"><span class="scheduleLabel">ANNEXE DE LA PARTIE XX.1</span></a>
</li>
<li><a href="#h-129970"><span class="scheduleLabel">ANNEXE DE LA PARTIE XXII.1</span> <span class="scheduleTitleText"> - Infractions pouvant faire l’objet d’un accord de réparation</span></a>
</li>
<li><a href="#h-130010"><span class="scheduleLabel">ANNEXE [de la partie XXV]</span> </a>
</li>
<li><a href="#h-130019"><span class="scheduleLabel">ANNEXE [de la partie XXVII]</span> </a>
</li>
<li><a href="#h-130066"><span class="scheduleLabel">FORMULE 1</span> <span class="scheduleTitleText"> - Dénonciation en vue d’obtenir un mandat de perquisition</span></a>
</li>
<li><a href="#h-130082"><span class="scheduleLabel">FORMULE 2</span> <span class="scheduleTitleText"> - Dénonciation</span></a>
</li>
<li><a href="#h-130098"><span class="scheduleLabel">FORMULE 3</span></a>
</li>
<li><a href="#h-130102"><span class="scheduleLabel">FORMULE 4</span> <span class="scheduleTitleText"> - En-tête d’un acte d’accusation</span></a>
</li>
<li><a href="#h-130120"><span class="scheduleLabel">FORMULE 5</span> <span class="scheduleTitleText"> - Mandat de perquisition</span></a>
</li>
<li><a href="#h-130133"><span class="scheduleLabel">FORMULE 5.001</span> <span class="scheduleTitleText"> - Ordre de préservation</span></a>
</li>
<li><a href="#h-130151"><span class="scheduleLabel">FORMULE 5.002</span> <span class="scheduleTitleText"> - Dénonciation en vue d’obtenir une ordonnance de préservation</span></a>
</li>
<li><a href="#h-130167"><span class="scheduleLabel">FORMULE 5.003</span> <span class="scheduleTitleText"> - Ordonnance de préservation</span></a>
</li>
<li><a href="#h-130185"><span class="scheduleLabel">FORMULE 5.004</span> <span class="scheduleTitleText"> - Dénonciation en vue d’obtenir une ordonnance de communication</span></a>
</li>
<li><a href="#h-130219"><span class="scheduleLabel">FORMULE 5.005</span> <span class="scheduleTitleText"> - Ordonnance de communication : documents</span></a>
</li>
<li><a href="#h-130239"><span class="scheduleLabel">FORMULE 5.006</span> <span class="scheduleTitleText"> - Ordonnance de communication en vue de retracer une communication</span></a>
</li>
<li><a href="#h-130258"><span class="scheduleLabel">FORMULE 5.007</span> <span class="scheduleTitleText"> - Ordonnance de communication : données de transmission ou données de localisation</span></a>
</li>
<li><a href="#h-130275"><span class="scheduleLabel">FORMULE 5.008</span> <span class="scheduleTitleText"> - Ordonnance de communication : données financières</span></a>
</li>
<li><a href="#h-130292"><span class="scheduleLabel">FORMULE 5.0081</span> <span class="scheduleTitleText"> - Dénonciation en vue d’obtenir la révocation ou la modification d’une ordonnance rendue en vertu de l’un des articles 487.013 à 487.018 du Code criminel</span></a>
</li>
<li><a href="#h-130307"><span class="scheduleLabel">FORMULE 5.009</span> <span class="scheduleTitleText"> - Dénonciation en vue d’obtenir une ordonnance de non-divulgation</span></a>
</li>
<li><a href="#h-130323"><span class="scheduleLabel">FORMULE 5.0091</span> <span class="scheduleTitleText"> - Ordonnance de non-divulgation</span></a>
</li>
<li><a href="#h-130339"><span class="scheduleLabel">FORMULE 5.01</span> <span class="scheduleTitleText"> - Dénonciation justifiant la délivrance d’un mandat autorisant le prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130362"><span class="scheduleLabel">FORMULE 5.02</span> <span class="scheduleTitleText"> - Mandat autorisant le prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130385"><span class="scheduleLabel">FORMULE 5.03</span> <span class="scheduleTitleText"> - Ordonnance de prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130399"><span class="scheduleLabel">FORMULE 5.04</span> <span class="scheduleTitleText"> - Ordonnance de prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130424"><span class="scheduleLabel">FORMULE 5.041</span> <span class="scheduleTitleText"> - Ordonnance à l’égard de la personne assujettie au prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130444"><span class="scheduleLabel">FORMULE 5.05</span> <span class="scheduleTitleText"> - Demande d’autorisation de prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130463"><span class="scheduleLabel">FORMULE 5.06</span> <span class="scheduleTitleText"> - Autorisation de prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130485"><span class="scheduleLabel">FORMULE 5.061</span> <span class="scheduleTitleText"> - Sommation à l’égard de la personne assujettie au prélèvement de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130505"><span class="scheduleLabel">FORMULE 5.062</span> <span class="scheduleTitleText"> - Mandat d’arrestation</span></a>
</li>
<li><a href="#h-130519"><span class="scheduleLabel">FORMULE 5.07</span> <span class="scheduleTitleText"> - Rapport à un juge de la cour provinciale ou au tribunal</span></a>
</li>
<li><a href="#h-130539"><span class="scheduleLabel">FORMULE 5.08</span> <span class="scheduleTitleText"> - Demande d’autorisation de prélèvement d’échantillons supplémentaires de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130555"><span class="scheduleLabel">FORMULE 5.09</span> <span class="scheduleTitleText"> - Autorisation de prélèvement d’échantillons supplémentaires de substances corporelles pour analyse génétique</span></a>
</li>
<li><a href="#h-130573"><span class="scheduleLabel">FORMULE 5.1</span> <span class="scheduleTitleText"> - Mandat de perquisition</span></a>
</li>
<li><a href="#h-130592"><span class="scheduleLabel">FORMULE 5.2</span> <span class="scheduleTitleText"> - Rapport à un juge de paix</span></a>
</li>
<li><a href="#h-130611"><span class="scheduleLabel">FORMULE 5.3</span> <span class="scheduleTitleText"> - Rapport au juge</span></a>
</li>
<li><a href="#h-130630"><span class="scheduleLabel">FORMULE 6</span> <span class="scheduleTitleText"> - Sommation à une personne inculpée d’infraction</span></a>
</li>
<li><a href="#h-130652"><span class="scheduleLabel">FORMULE 7</span> <span class="scheduleTitleText"> - Mandat d’arrestation</span></a>
</li>
<li><a href="#h-130679"><span class="scheduleLabel">FORMULE 7.1</span> <span class="scheduleTitleText"> - Mandat d’entrée dans une maison d’habitation</span></a>
</li>
<li><a href="#h-130697"><span class="scheduleLabel">FORMULE 8</span> <span class="scheduleTitleText"> - Mandat de dépôt</span></a>
</li>
<li><a href="#h-130721"><span class="scheduleLabel">FORMULE 9</span> <span class="scheduleTitleText"> - Citation à comparaître délivrée par un agent de la paix à une personne qui n’est pas encore inculpée d’infraction</span></a>
</li>
<li><a href="#h-130742"><span class="scheduleLabel">FORMULE 10</span> <span class="scheduleTitleText"> - Promesse de comparaître</span></a>
</li>
<li><a href="#h-130762"><span class="scheduleLabel">FORMULE 11</span> <span class="scheduleTitleText"> - Engagement contracté devant un fonctionnaire responsable ou un autre agent de la paix</span></a>
</li>
<li><a href="#h-130784"><span class="scheduleLabel">FORMULE 11.1</span> <span class="scheduleTitleText"> - Promesse remise à un agent de la paix ou à un fonctionnaire responsable</span></a>
</li>
<li><a href="#h-130814"><span class="scheduleLabel">FORMULE 12</span> <span class="scheduleTitleText"> - Promesse remise à un juge de paix ou à un juge</span></a>
</li>
<li><a href="#h-130842"><span class="scheduleLabel">FORMULE 13</span> <span class="scheduleTitleText"> - Promesse remise par un appelant (défendeur)</span></a>
</li>
<li><a href="#h-130861"><span class="scheduleLabel">FORMULE 14</span> <span class="scheduleTitleText"> - Promesse remise par l’appelant (poursuivant)</span></a>
</li>
<li><a href="#h-130870"><span class="scheduleLabel">FORMULE 15</span> <span class="scheduleTitleText"> - Mandat de conduire un prévenu devant un juge de paix d’une autre circonscription territoriale</span></a>
</li>
<li><a href="#h-130883"><span class="scheduleLabel">FORMULE 16</span> <span class="scheduleTitleText"> - Assignation à un témoin</span></a>
</li>
<li><a href="#h-130898"><span class="scheduleLabel">FORMULE 16.1</span> <span class="scheduleTitleText"> - Assignation à un témoin dans les cas des poursuites pour une infraction visée au paragraphe 278.2(1) du Code criminel</span></a>
</li>
<li><a href="#h-130918"><span class="scheduleLabel">FORMULE 17</span> <span class="scheduleTitleText"> - Mandat d’amener un témoin</span></a>
</li>
<li><a href="#h-130937"><span class="scheduleLabel">FORMULE 18</span> <span class="scheduleTitleText"> - Mandat d’arrestation contre un témoin qui s’esquive</span></a>
</li>
<li><a href="#h-130951"><span class="scheduleLabel">FORMULE 19</span> <span class="scheduleTitleText"> - Mandat de renvoi d’un prisonnier</span></a>
</li>
<li><a href="#h-130965"><span class="scheduleLabel">FORMULE 20</span> <span class="scheduleTitleText"> - Mandat de dépôt contre un témoin qui refuse de prêter serment ou de témoigner</span></a>
</li>
<li><a href="#h-130980"><span class="scheduleLabel">FORMULE 21</span> <span class="scheduleTitleText"> - Mandat de dépôt sur déclaration de culpabilité</span></a>
</li>
<li><a href="#h-130998"><span class="scheduleLabel">FORMULE 22</span> <span class="scheduleTitleText"> - Mandat de dépôt sur une ordonnance de payer une somme d’argent</span></a>
</li>
<li><a href="#h-131012"><span class="scheduleLabel">FORMULE 23</span> <span class="scheduleTitleText"> - Mandat de dépôt pour omission de fournir un engagement de ne pas troubler l’ordre public</span></a>
</li>
<li><a href="#h-131027"><span class="scheduleLabel">FORMULE 24</span> <span class="scheduleTitleText"> - Mandat de dépôt d’un témoin pour omission de contracter un engagement</span></a>
</li>
<li><a href="#h-131042"><span class="scheduleLabel">FORMULE 25</span> <span class="scheduleTitleText"> - Mandat de dépôt pour outrage au tribunal</span></a>
</li>
<li><a href="#h-131062"><span class="scheduleLabel">FORMULE 26</span> <span class="scheduleTitleText"> - Mandat de dépôt en l’absence du paiement des frais d’appel</span></a>
</li>
<li><a href="#h-131075"><span class="scheduleLabel">FORMULE 27</span> <span class="scheduleTitleText"> - Mandat de dépôt pour déchéance d’un engagement</span></a>
</li>
<li><a href="#h-131089"><span class="scheduleLabel">FORMULE 28</span> <span class="scheduleTitleText"> - Visa du mandat</span></a>
</li>
<li><a href="#h-131100"><span class="scheduleLabel">FORMULE 28.1</span></a>
</li>
<li><a href="#h-131104"><span class="scheduleLabel">FORMULE 29</span> <span class="scheduleTitleText"> - Visa du mandat</span></a>
</li>
<li><a href="#h-131115"><span class="scheduleLabel">FORMULE 30</span> <span class="scheduleTitleText"> - Ordre d’amener un prévenu devant un juge de paix avant l’expiration de la période de renvoi</span></a>
</li>
<li><a href="#h-131126"><span class="scheduleLabel">FORMULE 31</span> <span class="scheduleTitleText"> - Déposition d’un témoin</span></a>
</li>
<li><a href="#h-131137"><span class="scheduleLabel">FORMULE 32</span> <span class="scheduleTitleText"> - Engagement</span></a>
</li>
<li><a href="#h-131186"><span class="scheduleLabel">FORMULE 33</span> <span class="scheduleTitleText"> - Certificat de défaut à inscrire sur l’engagement</span></a>
</li>
<li><a href="#h-131197"><span class="scheduleLabel">FORMULE 34</span> <span class="scheduleTitleText"> - Bref de saisie-exécution</span></a>
</li>
<li><a href="#h-131208"><span class="scheduleLabel">FORMULE 34.1</span> <span class="scheduleTitleText"> - Déclaration relative au dédommagement</span></a>
</li>
<li><a href="#h-131230"><span class="scheduleLabel">FORMULE 34.2</span> <span class="scheduleTitleText"> - Déclaration de la victime</span></a>
</li>
<li><a href="#h-131297"><span class="scheduleLabel">FORMULE 34.3</span> <span class="scheduleTitleText"> - Déclaration au nom d’une collectivité</span></a>
</li>
<li><a href="#h-131360"><span class="scheduleLabel">FORMULE 35</span> <span class="scheduleTitleText"> - Condamnation</span></a>
</li>
<li><a href="#h-131375"><span class="scheduleLabel">FORMULE 36</span> <span class="scheduleTitleText"> - Ordonnance contre un contrevenant</span></a>
</li>
<li><a href="#h-131386"><span class="scheduleLabel">FORMULE 37</span> <span class="scheduleTitleText"> - Ordonnance d’acquittement d’un prévenu</span></a>
</li>
<li><a href="#h-131398"><span class="scheduleLabel">FORMULE 38</span> <span class="scheduleTitleText"> - Condamnation pour outrage au tribunal</span></a>
</li>
<li><a href="#h-131409"><span class="scheduleLabel">FORMULE 39</span> <span class="scheduleTitleText"> - Ordonnance de libération d’une personne sous garde</span></a>
</li>
<li><a href="#h-131419"><span class="scheduleLabel">FORMULE 40</span> <span class="scheduleTitleText"> - Récusation du tableau des jurés</span></a>
</li>
<li><a href="#h-131431"><span class="scheduleLabel">FORMULE 41</span> <span class="scheduleTitleText"> - Récusation motivée</span></a>
</li>
<li><a href="#h-131442"><span class="scheduleLabel">FORMULE 42</span> <span class="scheduleTitleText"> - Certificat de non-paiement des frais d’appel</span></a>
</li>
<li><a href="#h-131451"><span class="scheduleLabel">FORMULE 43</span> <span class="scheduleTitleText"> - Reçu du geôlier, donné à un agent de la paix et constatant la réception d’un prisonnier</span></a>
</li>
<li><a href="#h-131459"><span class="scheduleLabel">FORMULE 44</span> </a>
</li>
<li><a href="#h-131468"><span class="scheduleLabel">FORMULE 45</span> </a>
</li>
<li><a href="#h-131476"><span class="scheduleLabel">FORMULE 46</span> <span class="scheduleTitleText"> - Ordonnance de probation</span></a>
</li>
<li><a href="#h-131497"><span class="scheduleLabel">FORMULE 47</span> <span class="scheduleTitleText"> - Ordonnance de communication de renseignements fiscaux</span></a>
</li>
<li><a href="#h-131511"><span class="scheduleLabel">FORMULE 48</span> <span class="scheduleTitleText"> - Ordonnance d’évaluation du tribunal</span></a>
</li>
<li><a href="#h-131532"><span class="scheduleLabel">FORMULE 48.1</span> <span class="scheduleTitleText"> - Ordonnance d’évaluation de la commission d’examen</span></a>
</li>
<li><a href="#h-131550"><span class="scheduleLabel">FORMULE 48.2</span> <span class="scheduleTitleText"> - Déclaration de la victime  —  non-responsabilité criminelle</span></a>
</li>
<li><a href="#h-131613"><span class="scheduleLabel">FORMULE 49</span> <span class="scheduleTitleText"> - Mandat de dépôt</span></a>
</li>
<li><a href="#h-131634"><span class="scheduleLabel">FORMULE 50</span> <span class="scheduleTitleText"> - Mandat de dépôt</span></a>
</li>
<li><a href="#h-131657"><span class="scheduleLabel">FORMULE 51</span> <span class="scheduleTitleText"> - Avis de l’obligation de fournir des échantillons de substance corporelle</span></a>
</li>
<li><a href="#h-131672"><span class="scheduleLabel">FORMULE 52</span> <span class="scheduleTitleText"> - Ordonnance enjoignant de se conformer à la Loi sur l’enregistrement de renseignements sur les délinquants sexuels</span></a>
</li>
<li><a href="#h-131693"><span class="scheduleLabel">FORMULE 53</span> <span class="scheduleTitleText"> - Ordonnance enjoignant de se conformer à la Loi sur l’enregistrement de renseignements sur les délinquants sexuels</span></a>
</li>
<li><a href="#h-131713"><span class="scheduleLabel">FORMULE 54</span> <span class="scheduleTitleText"> - Obligation de se conformer à la Loi sur l’enregistrement de renseignements sur les délinquants sexuels</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
