<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Conventions de Genève, Loi sur les</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Approbation des conventions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Infractions graves</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Procédures judiciaires à l’égard de personnes protégées</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Disposition générale</span></a>
</li>
<li><a href="#h-242036"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-242375"><span class="scheduleLabel">ANNEXE II</span> </a>
</li>
<li><a href="#h-242692"><span class="scheduleLabel">ANNEXE III</span> </a>
</li>
<li><a href="#h-243505"><span class="scheduleLabel">ANNEXE IV</span> </a>
</li>
<li><a href="#h-244318"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Protocole I</span> - <span class="scheduleTitleText"> - Protocole additionnel aux Conventions de Genève du 12 août 1949 relatif à la protection des victimes des conflits armés internationaux (Protocole I)</span></a>
</li>
<li><a href="#h-245252"><span class="scheduleLabel">ANNEXE VI</span> <span class="scheduleTitleText"> - Protocole II</span> - <span class="scheduleTitleText"> - Protocole additionnel aux Conventions de Genève du 12 août 1949 relatif à la protection des victimes des conflits armés non internationaux (Protocole II)</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
