<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Agence spatiale canadienne</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-73287"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-73290"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-73298"><span class="HTitleText1">Mise sur pied de l’agence</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-73301"><span class="HTitleText1">Mission et attributions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-73330"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-73362"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-73403"><span class="HTitleText1">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>24 à 27 - </span><a href="#h-73406"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-73408"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-73414"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

