<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les Cris et les Naskapis du Québec</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Incompatibilité avec des lois fédérales ou provinciales</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Application de la Loi sur les indiens</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Règlements administratifs et résolutions d’une bande</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="#h-6"><span class="HTitleText1">Règlements administratifs et résolutions de l’administration régionale crie</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">Application de lois provinciales par règlement</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Administrations locales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Constitution des bandes en personnes morales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText2">Appartenance aux bandes</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-12"><span class="HTitleText2">Mission de la bande</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-13"><span class="HTitleText2">Siège de la bande</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Conseil de la bande</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Assemblées du conseil</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-16"><span class="HTitleText2">Comités du conseil</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText2">Organismes, personnel et mandataires de la bande</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">Règlements administratifs Administration locale</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-19"><span class="HTitleText2">Règles régissant la prise des règlements administratifs et des résolutions</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-20"><span class="HTitleText2">Contestation des règlements administratifs et résolutions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-21"><span class="HTitleText2">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-22"><span class="HTitleText3">Dispositions transitoires pour les Cris</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-23"><span class="HTitleText3">Dispositions transitoires pour les Naskapis</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>62.01 - </span><a href="#h-24"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Administration régionale crie</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-25"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Élections de la bande</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-26"><span class="HTitleText2">Règlements administratifs électoraux</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-27"><span class="HTitleText2">Éligibilité des membres du conseil</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-28"><span class="HTitleText2">Personnel électoral</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-29"><span class="HTitleText2">Convocation des élections</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-30"><span class="HTitleText2">Contentieux électoral</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-31"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Assemblées et référendums de la bande</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-32"><span class="HTitleText2">Assemblées ordinaires</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-33"><span class="HTitleText2">Assemblées extraordinaires et référendums</span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-34"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Administration financière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>93 - </span><a href="#h-35"><span class="HTitleText2">Vérification</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-36"><span class="HTitleText2">Pouvoirs d’emprunt</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-37"><span class="HTitleText2">Marchés</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-38"><span class="HTitleText2">Mise en tutelle</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-39"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Terres des catégories IA et IA-N : droits de résidence et d’accès</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="#h-40"><span class="HTitleText2">Droits de résidence</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-41"><span class="HTitleText2">Droits d’accès</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-42"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-43"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Droits des bandes, du Québec et des tiers concernant les terres des catégories IA et IA-N</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-44"><span class="HTitleText2">Dépôts de stéatite</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-45"><span class="HTitleText2">Ressources forestières</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-46"><span class="HTitleText2">Gravier</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-47"><span class="HTitleText2">Droits relatifs aux minéraux et droits tréfonciers</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-48"><span class="HTitleText2">Droits et intérêts acquis sur les terres des catégories IA et IA-N</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-49"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Expropriation des terres de catégorie IA ou IA-N par le Québec</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-50"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Octroi de droits et d’intérêts sur les terres des catégories IA et IA-N et les bâtiments qui s’y trouvent</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-51"><span class="HTitleText2">Droit de superficie</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-52"><span class="HTitleText2">Transferts ultérieurs</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-53"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="#h-54"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Abandons</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-55"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Service de l’enregistrement</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-56"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Expropriation par la bande</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-57"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Commission Crie-Naskapie</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-58"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Successions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>181 - </span><a href="#h-59"><span class="HTitleText2">Disposition des biens traditionnels lors d’une succession ab intestat</span></a>
</li></ul>
</li><li><span class='sectionRange'>187 - </span><a href="#h-60"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Exemptions fiscales</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-61"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Insaisissabilité</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-62"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Police</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-63"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-64"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Administration de la justice</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-65"><span class="HLabel1">PARTIE XIX</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>204 à 217 - </span><a href="#h-66"><span class="HLabel1">PARTIE XX</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="#h-67"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
