<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le moratoire relatif aux pétroliers</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1137255"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1137258"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-1137272"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="page-1.html#h-1137278"><span class="HTitleText1">Droits des peuples autochtones du Canada</span></a>
</li>
<li><span class='sectionRange'>3.2 - </span><a href="page-1.html#h-1137281"><span class="HTitleText1">Obligation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-1137284"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-1137304"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-1137312"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-1.html#h-1137313"><span class="HTitleText2">Obligation de faire rapport</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-1137335"><span class="HTitleText2">Personnes désignées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-1137343"><span class="HTitleText3">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-1137380"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="page-2.html#h-1137400"><span class="HTitleText2">Détention des bâtiments</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-1137434"><span class="HTitleText2">Vente des bâtiments</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-2.html#h-1137475"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-1137478"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-1137510"><span class="HTitleText1">Poursuites par procédure sommaire</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-1137518"><span class="HTitleText1">Examen et rapport</span></a>
</li>
<li><a href="page-3.html#h-1137525"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

