<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la Loi de l’impôt sur le revenu, édictant la Loi sur les allocations spéciales pour enfants, apportant des modifications corrélatives à d’autres lois et abrogeant la Loi sur les allocations familiales</a><ul class="TocIndent"><li><span class='sectionRange'>1 à 22 - </span><a href="#h-78732"><span class="HTitleText1">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-78734"><span class="HTitleText1">Loi sur les allocations spéciales pour enfants</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-78739"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>28 à 30 - </span><a href="#h-78747"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-78749"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><a href="#h-78757"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - [Voir Allocations spéciales pour enfants, Loi sur les]</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
