<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les paiements versés en remplacement d’impôts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-346347"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-346352"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-346432"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-346437"><span class="HTitleText1">Pouvoir de verser des paiements</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-346461"><span class="HTitleText1">Calcul des paiements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-346513"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-346540"><span class="HTitleText1">Sociétés d’État</span></a>
</li>
<li><span class='sectionRange'>11.1 - </span><a href="page-2.html#h-346550"><span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-346566"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="page-3.html#h-346591"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="page-4.html#h-346603"><span class="scheduleLabel">ANNEXE II</span> </a>
</li>
<li><a href="page-5.html#h-346622"><span class="scheduleLabel">ANNEXE III</span> </a>
</li>
<li><a href="page-6.html#h-346695"><span class="scheduleLabel">ANNEXE IV</span> </a>
</li></ul>
</li></ul>

</nav>

