<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Marine Transportation Security Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-352594"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-352597"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-352629"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-352644"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-352666"><span class="HTitleText1">Security Measures</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-352685"><span class="HTitleText1">Security Rules</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-352719"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-352722"><span class="HTitleText1">Confidentiality of Security Measures and Security Rules</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-352745"><span class="HTitleText1">Directions to Vessels</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-352766"><span class="HTitleText1">Notices to Operators</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-352769"><span class="HTitleText1">Screening</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-352875"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-352922"><span class="HTitleText1">General Provisions Relating to Offences</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-352947"><span class="HTitleText1">Administrative Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-352948"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-352953"><span class="HTitleText2">Assurances of Compliance and Notices of Violation</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-353044"><span class="HTitleText2">Choice of Proceedings</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-353049"><span class="HTitleText2">Recovery of Debts</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-353065"><span class="HTitleText2">Rules of Law about Violations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-353085"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-353119"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
