<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’hymne national</a><ul class="TocIndent"><li><a href="#h-355344"><span class="scheduleLabel"><span class="otherLang" lang="en">SCHEDULE</span> / ANNEXE</span>  / article 2)</span> - <span class="scheduleTitleText"> - <span class="otherLang" lang="en">National Anthem</span> — Hymne national</span> - <span class="scheduleTitleText"> - O Canada</span></a>
</li></ul>
</li></ul>

</nav>

