<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Garnishment, Attachment and Pension Diversion Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-247358"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-247363"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Garnishment and Attachment Proceedings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-247364"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-247374"><span class="HTitleText2">Garnishment of Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-247379"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Departments and Certain Crown Corporations</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-247459"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Crown Corporations not Covered by Division I</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-247469"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Canadian Forces</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-247474"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Senate, House of Commons, Library of Parliament, Office of the Senate Ethics Officer, Office of the Conflict of Interest and Ethics Commissioner, Parliamentary Protective Service and Office of the Parliamentary Budget Officer</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-247555"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-247574"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Diversion of Pension Benefits to Satisfy Financial Support Orders</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-247575"><span class="HTitleText2">Application of Part</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-247580"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-247611"><span class="HTitleText2">Conditions for Diversion of Pension Benefits</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-247667"><span class="HTitleText2">Amount of Diversion</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-247729"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><a href="#h-247773"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
