<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Monnaie royale canadienne</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-418759"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-418764"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-418780"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-418785"><span class="HTitleText1">Constitution, mission et siège</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-418796"><span class="HTitleText1">Composition du capital</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-418815"><span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-418846"><span class="HTitleText1">Monnaie hors circulation</span></a>
</li>
<li><span class='sectionRange'>6.4 - </span><a href="#h-418867"><span class="HTitleText1">Monnaie de circulation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-418883"><span class="HTitleText1">Pièces canadiennes</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-418895"><span class="HTitleText1">Président et conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-418948"><span class="HTitleText1">Personnel de la monnaie</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-418965"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-418974"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><a href="#h-418993"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
