<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la communication d’information ayant trait à la sécurité du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Objet et principes</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Communication d’information</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText1">Immunité en matière civile</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">Pouvoirs du gouverneur en conseil</span></a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Institutions exclues</span></a>
</li>
<li><a href="#h-8"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Institutions supplémentaires</span></a>
</li>
<li><a href="#h-9"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
