<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Customs and Excise Offshore Application Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-142544"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-142549"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-142580"><span class="HTitleText1">Customs Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-142590"><span class="HTitleText1">Information and Documentation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-142598"><span class="HTitleText1">Acquired Rights</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-142599"><span class="HTitleText2">Goods For Use on Site</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-142617"><span class="HTitleText2">Goods Under Prior Order</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-142635"><span class="HTitleText2">Special Rules</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-142650"><span class="HTitleText2">Ships</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
