<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l'emploi dans la fonction publique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Commission de la fonction publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Attributions générales de la Commission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Délégation de pouvoirs</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Dossiers et enquêtes</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Nomination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Pouvoir de nomination</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Nominations</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Normes et critères</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText2">Concours</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="#h-14"><span class="HTitleText2">Emploi temporaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Durée des fonctions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Stage</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-18"><span class="HTitleText2">Disponibilité</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-19"><span class="HTitleText2">Congé</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-20"><span class="HTitleText2">Activités politiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>34.1 - </span><a href="#h-21"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Mutations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34.1 - </span><a href="#h-22"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>34.2 - </span><a href="#h-23"><span class="HTitleText2">Conditions</span></a>
</li>
<li><span class='sectionRange'>34.3 - </span><a href="#h-24"><span class="HTitleText2">Recours en matière de mutations</span></a>
</li>
<li><span class='sectionRange'>34.6 - </span><a href="#h-25"><span class="HTitleText2">Dispositions non applicables</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-26"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-27"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>37.3 - </span><a href="#h-28"><span class="HTitleText2">Transferts en bloc</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-29"><span class="HTitleText2">Traitement à la nomination</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-30"><span class="HTitleText2">Personnel des cabinets de ministres</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-31"><span class="HTitleText2">Autres hauts responsables</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-32"><span class="HTitleText2">Exemptions</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-33"><span class="HTitleText2">Irrégularités et pratiques frauduleuses</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-34"><span class="HTitleText2">Serments</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-35"><span class="HTitleText2">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-36"><span class="HTitleText2">Champ d’application</span></a>
</li></ul>
</li><li><a href="#h-37"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Serment professionnel d’un commissaire</span></a>
</li>
<li><a href="#h-38"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Définitions</span></a>
</li>
<li><a href="#h-39"><span class="scheduleLabel">ANNEXE III</span> <span class="scheduleTitleText"> - Serment professionnel et engagement au secret professionnel</span></a>
</li>
<li><a href="#h-40"><span class="scheduleLabel">ANNEXE IV</span> <span class="scheduleTitleText"> - Convocation à une enquête</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
