<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Commission du parc international Roosevelt de Campobello</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-418017"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-418020"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-418033"><span class="HTitleText1">Pouvoirs et privilèges de la Commission</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="page-1.html#h-418044"><span class="HTitleText1">Nomination de membres suppléants</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-418049"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-418052"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-2.html#h-418056"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - (Traduction)</span> - <span class="scheduleTitleText"> - Accord entre le gouvernement des Etats-Unis d’Amérique et le gouvernement du Canada relatif à la création du parc international Roosevelt de Campobello</span></a>
</li></ul>
</li></ul>

</nav>

