<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Transportation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">National Transportation Policy</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Canadian Transportation Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText3">Continuation and Organization</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText3">Remuneration</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText3">Chairperson</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText3">Quorum</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText3">Rules</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText3">Head Office</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText3">Staff</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-15"><span class="HTitleText3">Records</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-16"><span class="HTitleText3">Powers of Agency</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-17"><span class="HTitleText3">Mediation</span></a>
</li>
<li><span class='sectionRange'>36.2 - </span><a href="#h-18"><span class="HTitleText3">Mediation or Arbitration</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-19"><span class="HTitleText3">Inquiries</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-20"><span class="HTitleText3">Review and Appeal</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-21"><span class="HTitleText3">Report of Agency</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-22"><span class="HTitleText2">Governor in Council</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-23"><span class="HTitleText3">Directions to Agency</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-24"><span class="HTitleText3">Extraordinary Disruptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-25"><span class="HTitleText2">Minister</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-26"><span class="HTitleText3">Support Agreements</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-27"><span class="HTitleText3">Inquiries</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-28"><span class="HTitleText3">Transportation Information</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-29"><span class="HTitleText3">Industry Review</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-30"><span class="HTitleText3">Review of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>53.1 - </span><a href="#h-31"><span class="HTitleText2">Review of Mergers and Acquisitions</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-32"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="#h-33"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Air Transportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-34"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-35"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-36"><span class="HTitleText2">Licence for Domestic Service</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-37"><span class="HTitleText2">Licence for Scheduled International Service</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-38"><span class="HTitleText2">Licence for Non-scheduled International Service</span></a>
</li>
<li><span class='sectionRange'>75.1 - </span><a href="#h-39"><span class="HTitleText2">Issuance of International Charter Permits</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-40"><span class="HTitleText2">Ministerial Directions for International Service</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-41"><span class="HTitleText2">Duties and Powers of Agency</span></a>
</li>
<li><span class='sectionRange'>85.1 - </span><a href="#h-42"><span class="HTitleText2">Air Travel Complaints</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-43"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-44"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Railway Transportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-45"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-46"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Construction and Operation of Railways</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>90 - </span><a href="#h-47"><span class="HTitleText3">Certificate of Fitness</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-48"><span class="HTitleText3">General Powers of Railway Companies</span></a>
</li>
<li><span class='sectionRange'>95.1 - </span><a href="#h-49"><span class="HTitleText3">Noise and Vibration</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-50"><span class="HTitleText3">Land Transfer</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-51"><span class="HTitleText3">Railway Lines</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-52"><span class="HTitleText3">Road and Utility Crossings</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-53"><span class="HTitleText3">Private Crossings</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-54"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Financial Transactions of Railway Companies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-55"><span class="HTitleText3">Security</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-56"><span class="HTitleText3">Documents Dealing with Rolling Stock</span></a>
</li>
<li><span class='sectionRange'>105.1 - </span><a href="#h-57"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-58"><span class="HTitleText3">Insolvent Railway Companies</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-59"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Rates, Tariffs and Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-60"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-61"><span class="HTitleText3">Rates and Conditions of Service</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-62"><span class="HTitleText3">Level of Services</span></a>
</li>
<li><span class='sectionRange'>116.1 - </span><a href="#h-63"><span class="HTitleText3">Traffic of Grain</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-64"><span class="HTitleText3">Tariffs — General</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-65"><span class="HTitleText3">Tariffs — Freight</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-66"><span class="HTitleText3">Joint Rates</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-67"><span class="HTitleText3">Confidential Contracts</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-68"><span class="HTitleText3">Interswitching</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-69"><span class="HTitleText3">Competitive Line Rates</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-70"><span class="HTitleText3">Limiting Carriers’ Liability</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-71"><span class="HTitleText3">Running Rights and Joint Track Usage</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-72"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">Transferring and Discontinuing the Operation of Railway Lines</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-73"><span class="HLabel2">DIVISION VI</span> - <span class="HTitleText2">Transportation of Western Grain</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="#h-74"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-75"><span class="HTitleText3">Application of Division IV</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-76"><span class="HTitleText3">Tariffs</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-77"><span class="HTitleText3">Maximum Grain Revenue Entitlement</span></a>
</li>
<li><span class='sectionRange'>151.1 - </span><a href="#h-78"><span class="HTitleText3">List of Available Sidings</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-79"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>152.1 - </span><a href="#h-80"><span class="HLabel2">DIVISION VI.1</span> - <span class="HTitleText2">Public Passenger Service Providers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152.1 - </span><a href="#h-81"><span class="HTitleText3">Dispute Resolution</span></a>
</li>
<li><span class='sectionRange'>152.4 - </span><a href="#h-82"><span class="HTitleText3">Agreements</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="#h-83"><span class="HLabel2">DIVISION VII</span> - <span class="HTitleText2">Other Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-84"><span class="HTitleText3">Accounting</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-85"><span class="HTitleText3">Determination of Costs</span></a>
</li>
<li><span class='sectionRange'>157.1 - </span><a href="#h-86"><span class="HTitleText3">Agreements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-87"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Arbitrations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-88"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Final Offer Arbitration</span></a>
</li>
<li><span class='sectionRange'>169.31 - </span><a href="#h-89"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Arbitration on Level of Services</span></a>
</li></ul>
</li><li><span class='sectionRange'>170 - </span><a href="#h-90"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Transportation of Persons with Disabilities</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-91"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-92"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>176.1 - </span><a href="#h-93"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 to 184 - </span><a href="#h-94"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Repeals, Transitional Provisions, Consequential and Conditional Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 to 184 - </span><a href="#h-95"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-96"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>202 to 274 - </span><a href="#h-97"><span class="HTitleText2">Consequential and Related Amendments</span></a>
</li>
<li><span class='sectionRange'>275 to 277 - </span><a href="#h-98"><span class="HTitleText2">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-99"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-57337"><span class="scheduleLabel">SCHEDULE I / <span class="otherLang" lang="fr">ANNEXE I</span></span> </span></a>
</li>
<li><a href="#h-101"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Grain, Crop or Product</span></a>
</li>
<li><a href="#h-102"><span class="scheduleLabel">SCHEDULES III AND IV</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
