<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Companies' Creditors Arrangement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Compromises and Arrangements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>18.6 - </span><a href="#h-5"><span class="HTitleText1">International Insolvencies</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
