<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Interest Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-270659"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-270664"><span class="HTitleText1">Rate of Interest</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-270681"><span class="HTitleText1">Interest on Moneys Secured by Mortgage on Real Property or Hypothec on Immovables</span></a>
</li></ul>
</li></ul>

</nav>

