<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Auditor General Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-7053"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-7058"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-7088"><span class="HTitleText1">Auditor General of Canada</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7108"><span class="HTitleText1">Powers and Duties</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7176"><span class="HTitleText1">Access to Information</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7197"><span class="HTitleText1">Staff of the Auditor General</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-7241"><span class="HTitleText1">Immunities</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7255"><span class="HTitleText1">Estimates</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7267"><span class="HTitleText1">Audit of the Office of the Auditor General</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-7275"><span class="HTitleText1">Sustainable Development</span></a>
</li>
<li><a href="#h-11"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
