<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Administrative Tribunals Support Service of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-89"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-92"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-99"><span class="HTitleText1">Administrative Tribunals Support Service of Canada</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-107"><span class="HTitleText1">Chief Administrator</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-138"><span class="HTitleText1">Administrative Tribunal Chairpersons</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-141"><span class="HTitleText1">Employees of the Service</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-144"><span class="HTitleText1">General</span></a>
</li>
<li><a href="page-2.html#h-152"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Administrative Tribunals</span></a>
</li></ul>
</li></ul>

</nav>

