<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Northwest Territories Waters Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2.1 - </span><a href="#h-4"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Delegation to Northwest Territories Minister</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Agreements</span></a>
</li>
<li><span class='sectionRange'>7.2 - </span><a href="#h-8"><span class="HTitleText2">Consultation</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText1">Use of Waters</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-10"><span class="HTitleText1">Deposit of Waste</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="#h-11"><span class="HTitleText1">Tlicho Communities</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-12"><span class="HTitleText1">Inuvialuit Water Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-13"><span class="HTitleText2">Board Established</span></a>
</li>
<li><span class='sectionRange'>10.5 - </span><a href="#h-14"><span class="HTitleText2">Term of Office</span></a>
</li>
<li><span class='sectionRange'>10.7 - </span><a href="#h-15"><span class="HTitleText2">Remuneration</span></a>
</li>
<li><span class='sectionRange'>11.2 - </span><a href="#h-16"><span class="HTitleText2">Conflict of Interest</span></a>
</li>
<li><span class='sectionRange'>11.3 - </span><a href="#h-17"><span class="HTitleText2">Immunity</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-18"><span class="HTitleText1">Objects and Powers of Board</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-19"><span class="HTitleText1">Public Hearings and Procedure</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-20"><span class="HTitleText1">Time Limits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24.1 - </span><a href="#h-21"><span class="HTitleText2">Authority to Act</span></a>
</li>
<li><span class='sectionRange'>24.2 - </span><a href="#h-22"><span class="HTitleText2">Decisions by Board and Approvals</span></a>
</li>
<li><span class='sectionRange'>24.5 - </span><a href="#h-23"><span class="HTitleText2">Excluded Periods</span></a>
</li>
<li><span class='sectionRange'>24.7 - </span><a href="#h-24"><span class="HTitleText2">Extensions</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-25"><span class="HTitleText1">Public Register</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-26"><span class="HTitleText1">Decisions and Orders</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="#h-27"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>28.2 - </span><a href="#h-28"><span class="HTitleText1">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-29"><span class="HTitleText1">Rights and Duties of Licensees and Others</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-30"><span class="HTitleText1">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-31"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-32"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>44.01 - </span><a href="#h-33"><span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44.01 - </span><a href="#h-34"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>44.02 - </span><a href="#h-35"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>44.07 - </span><a href="#h-36"><span class="HTitleText2">Rules About Violations</span></a>
</li>
<li><span class='sectionRange'>44.11 - </span><a href="#h-37"><span class="HTitleText2">Reviews</span></a>
</li>
<li><span class='sectionRange'>44.16 - </span><a href="#h-38"><span class="HTitleText2">Responsibility</span></a>
</li>
<li><span class='sectionRange'>44.18 - </span><a href="#h-39"><span class="HTitleText2">Recovery of Penalties</span></a>
</li>
<li><span class='sectionRange'>44.2 - </span><a href="#h-40"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-41"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-42"><span class="HTitleText1">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-43"><span class="HTitleText2">Northern Canada Power Commission (share issuance and sale authorization) Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-44"><span class="HTitleText2">Other references to Northern Inland Waters Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-45"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
