<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le système de justice pénale pour les adolescents</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-458990"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-458993"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-459037"><span class="HTitleText1">Déclaration de principes</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-459065"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mesures extrajudiciaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-459066"><span class="HTitleText2">Principes et objectifs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-459080"><span class="HTitleText2">Avertissements, mises en garde et renvois</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-459092"><span class="HTitleText2">Sanctions extrajudiciaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-459117"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Organisation du système de justice pénale pour les adolescents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-459118"><span class="HTitleText2">Tribunal pour adolescents</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-459171"><span class="HTitleText2">Comités de justice pour la jeunesse</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-459187"><span class="HTitleText2">Groupes consultatifs</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-459197"><span class="HTitleText2">Juges de paix</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-459203"><span class="HTitleText2">Greffier du tribunal pour adolescents</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-459208"><span class="HTitleText2">Directeurs provinciaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-459211"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Procédures judiciaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-459212"><span class="HTitleText2">Consentement préalable du procureur général</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-459220"><span class="HTitleText2">Droit aux services d’un avocat</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-459262"><span class="HTitleText2">Avis aux père et mère</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-459311"><span class="HTitleText2">Détention avant le prononcé de la peine</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-459381"><span class="HTitleText2">Comparution</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-459402"><span class="HTitleText2">Mise en liberté ou détention sous garde</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-459422"><span class="HTitleText2">Rapports médicaux et psychologiques</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-459473"><span class="HTitleText2">Renvoi à un organisme de protection de la jeunesse</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-459476"><span class="HTitleText2">Jugement</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-459482"><span class="HTitleText2">Appels</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-459508"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Détermination de la peine</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-459509"><span class="HTitleText2">Objectif et principes</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-459564"><span class="HTitleText2">Rapport prédécisionnel</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-459613"><span class="HTitleText2">Peines spécifiques</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-459876"><span class="HTitleText2">Peine applicable aux adultes et choix de la procédure</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-460040"><span class="HTitleText2">Conséquences de la cessation d’effet des peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-460062"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Garde et surveillance</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-460436"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Dossiers et confidentialité des renseignements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-460437"><span class="HTitleText2">Protection de la vie privée des adolescents</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-460467"><span class="HTitleText2">Empreintes digitales et photographies</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-460473"><span class="HTitleText2">Dossiers</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-460499"><span class="HTitleText2">Accès aux dossiers</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-460633"><span class="HTitleText2">Communication des renseignements contenus dans les dossiers</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-460677"><span class="HTitleText2">Destruction des dossiers et interdiction d’utilisation ou d’accès</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-460699"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-460700"><span class="HTitleText2">Dessaisissement du juge</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-460708"><span class="HTitleText2">Remplacement de juges</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-460716"><span class="HTitleText2">Pouvoir d’exclusion</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-460740"><span class="HTitleText2">Transfert de compétence</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-460745"><span class="HTitleText2">Confiscation du montant des engagements</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-460765"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-460792"><span class="HTitleText2">Application du Code criminel</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-460841"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-460851"><span class="HTitleText2">Preuve</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-460929"><span class="HTitleText2">Formules, règlements et règles de fonctionnement</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-460940"><span class="HTitleText2">Accord avec les provinces</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-460943"><span class="HTitleText2">Programmes</span></a>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="#h-460949"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>166 à 198 - </span><a href="#h-460992"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Modifications corrélatives, abrogation et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 à 198 - </span><a href="#h-460993"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-460995"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-460997"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-58"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
