<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le tabac et les produits de vapotage</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-438595"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-438600"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-438636"><span class="HTitleText1">Pouvoirs du gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-438647"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-438650"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-438669"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Produits du tabac</span></a>
</li>
<li><span class='sectionRange'>7.2 - </span><a href="page-2.html#h-438731"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Produits de vapotage</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-438797"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Accès</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-438863"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Étiquetage</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-438909"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Promotion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="page-3.html#h-438925"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Produits du tabac</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="page-4.html#h-439040"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Produits de vapotage</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-4.html#h-439173"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Dispositions diverses</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-5.html#h-439211"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-5.html#h-439212"><span class="HTitleText2">Inspection et analyse</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-439274"><span class="HTitleText2">Saisie et restitution</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-6.html#h-439326"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>42.1 - </span><a href="page-6.html#h-439336"><span class="HLabel1">PARTIE V.1</span> - <span class="HTitleText1">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-6.html#h-439362"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-439455"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>60.1 - </span><a href="page-7.html#h-439467"><span class="HLabel1">PARTIE VII.1</span> - <span class="HTitleText1">Examen de la loi</span></a>
</li>
<li><span class='sectionRange'>61 à 63 - </span><a href="page-7.html#h-439475"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Modifications connexes, abrogations et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 à 63 - </span><a href="page-7.html#h-439476"><span class="HTitleText2">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>64 et 65 - </span><a href="page-7.html#h-439478"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-7.html#h-439480"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-8.html#h-439493"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-9.html#h-439505"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-10.html#h-439516"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>

