<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le ministère de la Citoyenneté et de l’Immigration</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-78880"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-78883"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-78891"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-78916"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>9 à 22 - </span><a href="page-1.html#h-78929"><span class="HTitleText1">Modifications corrélatives</span></a>
</li></ul>
</li></ul>

</nav>

