<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la gouvernance de la nation dakota de Sioux Valley</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-421108"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-421111"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-421117"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-421128"><span class="HTitleText1">Nation dakota de Sioux Valley</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-421146"><span class="HTitleText1">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-421158"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-421191"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-421199"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-421200"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-421202"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-421204"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-421206"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
