<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les engrais</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-216519"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-216524"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-216552"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-216580"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="#h-216627"><span class="HTitleText1">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>5.2 - </span><a href="#h-216639"><span class="HTitleText1">Enregistrements, licences et agréments</span></a>
</li>
<li><span class='sectionRange'>5.5 - </span><a href="#h-216672"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-216685"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="#h-216760"><span class="HTitleText1">Analyse</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="#h-216767"><span class="HTitleText1">Restriction de responsabilité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-216776"><span class="HTitleText1">Infractions et peines</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
