<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1991 sur la Convention Canada-Mexique sur l’échange de renseignements fiscaux</a><ul class="TocIndent"><li><span class='sectionRange'>19 - </span><a href="#h-147098"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Convention Canada-Mexique sur l’échange de renseignements fiscaux</span></a>
</li>
<li><a href="#h-147112"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement des États-Unis Mexicains sur l’échange de renseignements en matière fiscale</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
