<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Revised Statutes of Canada, 1985 Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-427906"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-427909"><span class="HTitleText1">Confirmation, Commencement and Repeal</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-427921"><span class="HTitleText1">Effects of Revision and Repeal</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-427930"><span class="HTitleText1">Publication, Citation and Appendices</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-427950"><span class="HTitleText1">Supplements</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-427971"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

