<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Supreme Court Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">The Court</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">The Judges</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-5"><span class="HTitleText1">The Registrar and Other Officers</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-6"><span class="HTitleText1">Barristers, Advocates, Attorneys and Solicitors</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-7"><span class="HTitleText1">Sessions and Quorum</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-8"><span class="HTitleText1">Appellate Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-9"><span class="HTitleText1">Judgments</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-10"><span class="HTitleText1">Costs</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-11"><span class="HTitleText1">Amendments</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-12"><span class="HTitleText1">Interest</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-13"><span class="HTitleText1">Certificate of Judgment</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-14"><span class="HTitleText1">Judgment Final and Conclusive</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-15"><span class="HTitleText1">Special Jurisdiction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-16"><span class="HTitleText2">References by Governor in Council</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-17"><span class="HTitleText2">References by Senate or House of Commons</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-18"><span class="HTitleText2">Certiorari</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-19"><span class="HTitleText1">Procedure in Appeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-20"><span class="HTitleText2">The Appeal</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-21"><span class="HTitleText2">Stay of Execution</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-22"><span class="HTitleText2">Discontinuance of Proceedings</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-23"><span class="HTitleText2">Consent to Reversal of Judgment</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-24"><span class="HTitleText2">Dismissal for Delay</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-25"><span class="HTitleText2">Death of Parties</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-26"><span class="HTitleText1">Entry of Causes</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-27"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-28"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
