<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Fisheries and Oceans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-232256"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-232261"><span class="HTitleText1">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-232273"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-232289"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-232294"><span class="HTitleText1">Annual Report</span></a>
</li></ul>
</li></ul>

</nav>

