<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Lobbying Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-339030"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-339035"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-339070"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-339094"><span class="HTitleText1">Office of the Commissioner of Lobbying</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4.1 - </span><a href="#h-339095"><span class="HTitleText2">Commissioner of Lobbying</span></a>
</li>
<li><span class='sectionRange'>4.3 - </span><a href="#h-339120"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>4.4 - </span><a href="#h-339128"><span class="HTitleText2">Delegation</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-339135"><span class="HTitleText1">Registration of Lobbyists</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-339136"><span class="HTitleText2">Consultant Lobbyists</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-339192"><span class="HTitleText2">In-house Lobbyists (Corporations and Organizations)</span></a>
</li>
<li><span class='sectionRange'>7.1 - </span><a href="#h-339254"><span class="HTitleText2">Certification</span></a>
</li>
<li><span class='sectionRange'>7.2 - </span><a href="#h-339259"><span class="HTitleText2">Documents in Electronic or Other Form</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-339274"><span class="HTitleText1">Registry</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-339303"><span class="HTitleText1">Lobbyists’ Remuneration</span></a>
</li>
<li><span class='sectionRange'>10.11 - </span><a href="#h-339311"><span class="HTitleText1">Restriction on Lobbying Activity</span></a>
</li>
<li><span class='sectionRange'>10.2 - </span><a href="#h-339346"><span class="HTitleText1">Lobbyists’ Code of Conduct</span></a>
</li>
<li><span class='sectionRange'>10.4 - </span><a href="#h-339367"><span class="HTitleText1">Investigations</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-339411"><span class="HTitleText1">Reports to Parliament</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-339423"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-339434"><span class="HTitleText1">Recovery of Fees</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-339439"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>14.1 - </span><a href="#h-339459"><span class="HTitleText1">Review by Parliament</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-339467"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

