<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les transports au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-52932"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-52935"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-52938"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-52950"><span class="HTitleText1">Politique nationale des transports</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-52960"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="#h-52993"><span class="HTitleText1">Pouvoir du gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>6.2 - </span><a href="#h-1159873"><span class="HTitleText1">Exécution et contrôle d’application par voie électronique</span></a>
</li>
<li><span class='sectionRange'>6.6 - </span><a href="#h-1238680"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-52998"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-52999"><span class="HTitleText2">Office des transports du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-53000"><span class="HTitleText3">Maintien et composition</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-53041"><span class="HTitleText3">Rémunération</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-53056"><span class="HTitleText3">Président</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-53063"><span class="HTitleText3">Quorum</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-53074"><span class="HTitleText3">Règles</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-53080"><span class="HTitleText3">Siège de l’Office</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-53088"><span class="HTitleText3">Personnel</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-53093"><span class="HTitleText3">Registre</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-53108"><span class="HTitleText3">Attributions de l’Office</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-53172"><span class="HTitleText3">Médiation</span></a>
</li>
<li><span class='sectionRange'>36.11 - </span><a href="#h-53192"><span class="HTitleText3">Services d’information et de règlement informel de différends</span></a>
</li>
<li><span class='sectionRange'>36.2 - </span><a href="#h-53204"><span class="HTitleText3">Médiation ou arbitrage</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-53216"><span class="HTitleText3">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-53228"><span class="HTitleText3">Révision et appel</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-53240"><span class="HTitleText3">Rapport de l’Office</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-53256"><span class="HTitleText2">Gouverneur en conseil</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-53257"><span class="HTitleText3">Directives à l’Office</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-53269"><span class="HTitleText3">Perturbations extraordinaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-53292"><span class="HTitleText2">Ministre</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-53294"><span class="HTitleText3">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-53304"><span class="HTitleText3">Renseignements relatifs aux transports</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-53410"><span class="HTitleText3">Examen de la situation de l’industrie</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-53423"><span class="HTitleText3">Examen de la loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>53.1 - </span><a href="#h-53441"><span class="HTitleText2">Examen des fusions et acquisitions</span></a>
</li>
<li><span class='sectionRange'>53.7 - </span><a href="#h-1108192"><span class="HTitleText2">Examen des ententes entre au moins deux entreprises de transport offrant des services aériens</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-53523"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="#h-53529"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Transport aérien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-53530"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-53596"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-53612"><span class="HTitleText2">Service intérieur</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-53738"><span class="HTitleText2">Service international régulier</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-53772"><span class="HTitleText2">Service international à la demande</span></a>
</li>
<li><span class='sectionRange'>75.1 - </span><a href="#h-53800"><span class="HTitleText2">Délivrance de permis d’affrètement international</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-53805"><span class="HTitleText2">Directives ministérielles en matière de service international</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-53823"><span class="HTitleText2">Attributions de l’Office</span></a>
</li>
<li><span class='sectionRange'>85.1 - </span><a href="#h-53863"><span class="HTitleText2">Plaintes relatives au transport aérien</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-53879"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-53942"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Transport ferroviaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-53943"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-53989"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Construction et exploitation des chemins de fer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>90 - </span><a href="#h-53990"><span class="HTitleText3">Certificat d’aptitude</span></a>
</li>
<li><span class='sectionRange'>93.1 - </span><a href="#h-54045"><span class="HTitleText3">Assurance responsabilité</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-54071"><span class="HTitleText3">Pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>95.1 - </span><a href="#h-54086"><span class="HTitleText3">Bruit et vibrations</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-54116"><span class="HTitleText3">Opérations foncières</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-54133"><span class="HTitleText3">Lignes de chemin de fer</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-54148"><span class="HTitleText3">Franchissement routier et par desserte</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-54165"><span class="HTitleText3">Passages</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-54175"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Opérations financières des compagnies de chemin de fer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-54176"><span class="HTitleText3">Sûretés</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-54188"><span class="HTitleText3">Documents concernant le matériel roulant</span></a>
</li>
<li><span class='sectionRange'>105.1 - </span><a href="#h-54200"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-54213"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Prix, tarif et services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-54214"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-54225"><span class="HTitleText3">Prix et conditions de service</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-54228"><span class="HTitleText3">Niveau de services</span></a>
</li>
<li><span class='sectionRange'>116.1 - </span><a href="#h-54306"><span class="HTitleText3">Transport du grain</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-54310"><span class="HTitleText3">Tarifs — généralités</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-54323"><span class="HTitleText3">Tarifs — marchandise</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-54359"><span class="HTitleText3">Prix communs</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-54387"><span class="HTitleText3">Contrats confidentiels</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-54418"><span class="HTitleText3">Interconnexion</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-54465"><span class="HTitleText3">Interconnexion de longue distance</span></a>
</li>
<li><span class='sectionRange'>136.9 - </span><a href="#h-54614"><span class="HTitleText3">Lieux de correspondance</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-54626"><span class="HTitleText3">Traitement de la question de la responsabilité des transporteurs</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-54642"><span class="HTitleText3">Droits de circulation et usage commun des voies</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-54660"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Transferts et cessation de l’exploitation de lignes</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-54862"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Transport du grain de l’Ouest</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="#h-54863"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-54880"><span class="HTitleText3">Application de la section IV</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-54883"><span class="HTitleText3">Tarifs</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-54891"><span class="HTitleText3">Revenu admissible maximal</span></a>
</li>
<li><span class='sectionRange'>151.1 - </span><a href="#h-54956"><span class="HTitleText3">Liste des voies d’évitement</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-54966"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>152.1 - </span><a href="#h-54978"><span class="HLabel2">SECTION VI.1</span> - <span class="HTitleText2">Sociétés de transport publiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152.1 - </span><a href="#h-54979"><span class="HTitleText3">Règlement de différends</span></a>
</li>
<li><span class='sectionRange'>152.4 - </span><a href="#h-55003"><span class="HTitleText3">Accords</span></a>
</li></ul>
</li><li><span class='sectionRange'>152.5 - </span><a href="#h-55013"><span class="HLabel2">SECTION VI.2</span> - <span class="HTitleText2">Responsabilité et indemnisation en cas d’accidents ferroviaires impliquant des marchandises désignées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152.5 - </span><a href="#h-55014"><span class="HTitleText3">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>152.7 - </span><a href="#h-55030"><span class="HTitleText3">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>153.4 - </span><a href="#h-55086"><span class="HTitleText3">Caisse d’indemnisation pour les accidents ferroviaires impliquant des marchandises désignées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153.4 - </span><a href="#h-55087"><span class="HTitleText4">Établissement de la Caisse</span></a>
</li>
<li><span class='sectionRange'>153.7 - </span><a href="#h-55113"><span class="HTitleText4">Administrateur et administrateur adjoint</span></a>
</li>
<li><span class='sectionRange'>154.4 - </span><a href="#h-55167"><span class="HTitleText4">Demandes d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>155.2 - </span><a href="#h-55233"><span class="HTitleText4">Action contre une compagnie de chemin de fer</span></a>
</li>
<li><span class='sectionRange'>155.3 - </span><a href="#h-55241"><span class="HTitleText4">Contributions</span></a>
</li>
<li><span class='sectionRange'>155.92 - </span><a href="#h-55377"><span class="HTitleText4">Administration de la Caisse</span></a>
</li></ul>
</li><li><span class='sectionRange'>155.97 - </span><a href="#h-55437"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>155.98 - </span><a href="#h-55449"><span class="HTitleText3">Disposition générale</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="#h-55454"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Autres dispositions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-55455"><span class="HTitleText3">Comptabilité</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-55467"><span class="HTitleText3">Calcul des frais</span></a>
</li>
<li><span class='sectionRange'>157.1 - </span><a href="#h-55483"><span class="HTitleText3">Accords</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-55499"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Arbitrages</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-55500"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Arbitrage sur l’offre finale</span></a>
</li>
<li><span class='sectionRange'>169.31 - </span><a href="#h-55696"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Arbitrage sur le niveau de services</span></a>
</li></ul>
</li><li><span class='sectionRange'>169.5 - </span><a href="#h-55864"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Transport des personnes handicapées</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-55885"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-55886"><span class="HTitleText2">Mesures de contrainte</span></a>
</li>
<li><span class='sectionRange'>176.1 - </span><a href="#h-55900"><span class="HTitleText2">Sanctions administratives pécuniaires</span></a>
</li>
<li><span class='sectionRange'>181.2 - </span><a href="#h-1179199"><span class="HTitleText2">Arrêtés de communication</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 à 184 - </span><a href="#h-56014"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Abrogations, dispositions transitoires, modifications connexes, modifications conditionnelles et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 à 184 - </span><a href="#h-56015"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-56028"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>202 à 274 - </span><a href="#h-56077"><span class="HTitleText2">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>275 à 277 - </span><a href="#h-56079"><span class="HTitleText2">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-56081"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-56085"><span class="scheduleLabel"><span class="otherLang" lang="en">SCHEDULE I</span> / ANNEXE I</span>  / (articles 116, 141, 142, 146.1)</span></a>
</li>
<li><a href="#h-56103"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Grains, plantes ou produits</span></a>
</li>
<li><a href="#h-56169"><span class="scheduleLabel"><span class="otherLang" lang="en">SCHEDULE III</span> / ANNEXE III</span>  / définition de « matière toxique par inhalation »)</span> - <span class="scheduleTitleText"> - <span class="otherLang" lang="en">UN Numbers for Dangerous Goods</span> / Numéros ONU de marchandises dangereuses</span></a>
</li>
<li><a href="#h-56174"><span class="scheduleLabel">ANNEXE IV</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
