<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant le nouveau pont pour le Saint-Laurent</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-355697"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-355700"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-355714"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-355717"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-355729"><span class="HTitleText1">Ententes</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-355739"><span class="HTitleText1">Droits</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-355744"><span class="HTitleText1">Décret</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-355752"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
