<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère des Affaires indiennes et du Nord canadien</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-324745"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-324750"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-324762"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-324784"><span class="HTitleText1">Rapport annuel</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
