<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Hibernia Development Project Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-253969"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-253972"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-254000"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-254038"><span class="HTitleText1">Validation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-254046"><span class="HTitleText1">Application of Federal and Provincial Laws</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-254047"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-254077"><span class="HTitleText2">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-254087"><span class="HTitleText2">Saving</span></a>
</li>
<li><span class='sectionRange'>11.1 - </span><a href="#h-254090"><span class="HTitleText2">Inconsistent Laws</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 to 21 - </span><a href="#h-254095"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-254097"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-254099"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
