<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Déline Final Self-Government Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-171499"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-171502"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-171514"><span class="HTitleText1">Déline Agreement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-171533"><span class="HTitleText1">Déline Got’Ine Government</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-171538"><span class="HTitleText1">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-171546"><span class="HTitleText1">Taxation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-171551"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-171589"><span class="HTitleText1">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-171590"><span class="HTitleText2"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-171592"><span class="HTitleText2"><cite class="XRefExternalAct">Mackenzie Valley Resource Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-1.html#h-171612"><span class="HTitleText2"><cite class="XRefExternalAct">First Nations Goods and Services Tax Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-1.html#h-171614"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-1.html#h-171616"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

