<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
International Boundary Commission Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-270724"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-270729"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-270740"><span class="HTitleText1">Powers of the Commission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-270757"><span class="HTitleText1">Prohibition</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-270774"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-270779"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

