<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Motor Vehicle Transport Act, 1987</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Safety</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Bus Transport</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Operating Licence</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Tariffs and Tolls</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Trucking</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Operating Licence</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HLabel1">PART III</span> - <span class="HTitleText1"></span>[Repealed, 1996, c. 17, s. 19] </a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Exceptions and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Exemption</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText2">Foreign Carriers</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText2">Offence and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Consequential Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-15"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-16"><span class="HTitleText2">Energy Supplies Emergency Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-17"><span class="HTitleText2">Canada Grain Act</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-18"><span class="HTitleText2">National Transportation Act, 1987</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-19"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-20"><span class="HTitleText2">Coming Into Force</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-21"><span class="HTitleText2">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-22"><span class="HTitleText1">Annual Report</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
