<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la dissolution ou la cession de sociétés d’État</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-132112"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-132115"><span class="HTitleText1">Corporation Place du Havre Canada inc.</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-132129"><span class="HTitleText1">Société de construction des musées du Canada, inc.</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-132137"><span class="HTitleText1">Office canadien des provendes</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-132151"><span class="HTitleText1">Société canadienne des brevets et d’exploitation limitée</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-132164"><span class="HTitleText1">Harbourfront corporation</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-132188"><span class="HTitleText1">Les associés Mingan, ltée</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-132195"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

