<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’Agence de la santé publique du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-391597"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-391600"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-391609"><span class="HTitleText1">Agence de la santé publique du Canada</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="page-1.html#h-391619"><span class="HTitleText1">Président</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-391632"><span class="HTitleText1">Administrateur en chef de la santé publique</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-391676"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-391693"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-391724"><span class="HTitleText1">Modifications connexe et corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-391725"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de la Santé</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-391727"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la quarantaine</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-1.html#h-391729"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-391731"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

