<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi d’urgence sur les approvisionnements d’énergie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-214807"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-214812"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-214832"><span class="HTitleText1">Office de répartition des approvisionnements d’énergie</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-214919"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Répartition obligatoire des approvisionnements</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-215024"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Rationnement des produits contrôlés</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-215048"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions générales et gestion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-215049"><span class="HTitleText2">Obligations contractuelles</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-215062"><span class="HTitleText2">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>32.2 - </span><a href="#h-215085"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-215135"><span class="HTitleText2">Pratiques commerciales restrictives</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-215149"><span class="HTitleText2">Considérations afférentes à l’environnement</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-215172"><span class="HTitleText2">Transport</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-215229"><span class="HTitleText2">Protection des renseignements</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-215239"><span class="HTitleText2">Exécution</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-215265"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Autres dispositions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
