<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2005</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-36503"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-36506"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments in Respect of Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-36507"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-36525"><span class="HTitleText2">Income Tax Application Rules</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-36527"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments in Respect of the Air Travellers Security Charge</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-36528"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-36530"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-36532"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments in Respect of the Goods and Services Tax and Harmonized Sales Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-36533"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-36537"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Amendments in Respect of Excise Tax on Jewellery, Etc.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-36538"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-36543"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Amendments to the Federal-Provincial Fiscal Arrangements Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-36544"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-36547"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-36549"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Northern Strategy</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-36557"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Auditor General of Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-36558"><span class="HTitleText2">Amendments to the Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-36563"><span class="HTitleText2">Amendments to the Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-36570"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-36571"><span class="HTitleText3"><cite class="XRefExternalAct">Broadcasting Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-36575"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-36577"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Race Relations Foundation Act</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-36580"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Pension Investment Board Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>50 - </span><a href="#h-36584"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-36587"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Payments to Certain Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-36588"><span class="HTitleText2">Aboriginal Healing Foundation</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-36591"><span class="HTitleText2">Asia-Pacific Foundation of Canada</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-36594"><span class="HTitleText2">Canadian Academies of Science</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-36597"><span class="HTitleText2">Canadian Cattlemen’s Association</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-36600"><span class="HTitleText2">Canadian Youth Business Foundation</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-36603"><span class="HTitleText2">Federation of Canadian Municipalities</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-36609"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-36612"><span class="HTitleText2">Precarn Incorporated</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-36615"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Asia-Pacific Foundation of Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-36616"><span class="HTitleText2">Asia-Pacific Foundation of Canada Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-36638"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-36640"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Amendment to the Budget Implementation Act, 1998</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-36642"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Payments for Infrastructure</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-36650"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Nova Scotia and Newfoundland and Labrador Additional Fiscal Equalization Offset Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="#h-36651"><span class="HTitleText2">Nova Scotia and Newfoundland and Labrador Additional Fiscal Equalization Offset Payments Act</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-36653"><span class="HTitleText2">Related Amendment to the Budget Implementation Act, 2004</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-36655"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Canada Emission Reduction Incentives Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-36656"><span class="HTitleText2">Canada Emission Reduction Incentives Agency Act</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-36658"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-36659"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-36661"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-36663"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-36666"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="#h-36668"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-36671"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="#h-36674"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Greenhouse Gas Technology Investment Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="#h-36675"><span class="HTitleText2">Greenhouse Gas Technology Investment Fund Act</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-36677"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-36680"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Amendments to the Canada Deposit Insurance Corporation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-36681"><span class="HTitleText2">Canada Deposit Insurance Corporation Act</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-36693"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-36699"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">Amendments to the Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-36703"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">Amendments to the Currency Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>113 - </span><a href="#h-36704"><span class="HTitleText2">Exchange Fund Account</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-36709"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-36712"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="#h-36715"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">Amendments to the Department of Public Works and Government Services Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-36716"><span class="HTitleText2">Department of Public Works and Government Services Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-36722"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-36725"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">Amendments Related to the Premium Rate Provided For Under the Employment Insurance Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-36726"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-36728"><span class="HTitleText2">Department of Human Resources Development Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-36731"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-36733"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">Amendments to the Employment Insurance Act (Provincial Plans)</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-36736"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">Amendments to the Financial Administration Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>132 - </span><a href="#h-36737"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-36740"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-36743"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">Amendments to the Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-36746"><span class="HLabel1">PART 23</span> - <span class="HTitleText1">Payments to Certain Provinces and Territories</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-36747"><span class="HTitleText2">Payment to Quebec</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-36753"><span class="HTitleText2">Payment to British Columbia</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-36759"><span class="HTitleText2">Payment to Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-36765"><span class="HTitleText2">Payment to Yukon</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-36771"><span class="HTitleText2">Payment to the Northwest Territories</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-36777"><span class="HTitleText2">Payment to Nunavut</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

