<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Service Superannuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-408032"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-408037"><span class="HTitleText1">Equality of Status</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-408042"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Superannuation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-408043"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-408090"><span class="HTitleText2">Superannuation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-408098"><span class="HTitleText2">Persons Required to Contribute</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-408171"><span class="HTitleText2">Pensionable Service</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-408215"><span class="HTitleText2">Elective Pensionable Service: Amount Required to be Paid</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-408252"><span class="HTitleText2">Elections</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-408296"><span class="HTitleText2">Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-408297"><span class="HTitleText3">Definitions, etc.</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-408347"><span class="HTitleText3">Annuities: How Computed</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-408419"><span class="HTitleText2">Group 1 Contributors with Less than Two Years of Pensionable Service</span></a>
</li>
<li><span class='sectionRange'>12.1 - </span><a href="#h-408469"><span class="HTitleText2">Group 2 Contributors with Less than Two Years of Pensionable Service</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-408506"><span class="HTitleText2">Group 1 Contributors with Two or More Years of Pensionable Service</span></a>
</li>
<li><span class='sectionRange'>13.001 - </span><a href="#h-408554"><span class="HTitleText2">Group 2 Contributors with Two or More Years of Pensionable Service</span></a>
</li>
<li><span class='sectionRange'>13.01 - </span><a href="#h-408600"><span class="HTitleText2">Group 1 and Group 2 Contributors with Two or More Years of Pensionable Service</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-408637"><span class="HTitleText2">Air Traffic Controllers</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-408718"><span class="HTitleText2">Correctional Service of Canada</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-408749"><span class="HTitleText2">Payments to Survivors, Children and Other Beneficiaries</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-408814"><span class="HTitleText2">Minimum Benefits</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-408834"><span class="HTitleText2">Disability Payments</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-408842"><span class="HTitleText2">Persons Re-employed</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-408851"><span class="HTitleText2">Medical Examinations</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-408868"><span class="HTitleText2">Diversion of Amounts Payable in Certain Cases</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-408879"><span class="HTitleText2">Presumption of Death</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-408887"><span class="HTitleText2">Special Cases</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-408889"><span class="HTitleText3">Transferred Pensionable Newfoundland Employees</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-408919"><span class="HTitleText3">Diplomatic and Consular Representatives</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-408924"><span class="HTitleText3">Public Service Corporations</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-408941"><span class="HTitleText3">Corporations declared to form or to have formed part of the Public Service for limited purposes only</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-408951"><span class="HTitleText2">Canadian Forces Superannuation Act and Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-409001"><span class="HTitleText2">Reciprocal Transfer Agreements</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-409052"><span class="HTitleText2">Divestiture of Service</span></a>
</li>
<li><span class='sectionRange'>40.2 - </span><a href="#h-409064"><span class="HTitleText2">Transfer Agreements</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-409107"><span class="HTitleText2">Advisory Committee</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-409126"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-409256"><span class="HTitleText2">Payments out of the Account</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-409266"><span class="HTitleText2">Amounts</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="#h-409294"><span class="HTitleText2">Public Service Superannuation Investment Fund</span></a>
</li>
<li><span class='sectionRange'>44.2 - </span><a href="#h-409308"><span class="HTitleText2">Public Service Pension Fund</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-409367"><span class="HTitleText2">Actuarial Report</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-409372"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>46.1 - </span><a href="#h-409377"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Provisions That Apply to Canada Post Corporation</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-409446"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Supplementary Death Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-409447"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-409508"><span class="HTitleText2">Elections</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-409535"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-409540"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-409566"><span class="HTitleText2">Public Service Death Benefit Account</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-409582"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-409649"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Supplementary Benefits</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-409708"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-409754"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-410014"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Single Premium</span></a>
</li></ul>
</li></ul>

</nav>

