<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Energy Supplies Emergency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-220401"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-220406"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-220429"><span class="HTitleText1">Energy Supplies Allocation Board</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-220516"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Mandatory Allocation of Supplies</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-220621"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Rationing of Controlled Products</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-220645"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General and Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-2.html#h-220646"><span class="HTitleText2">Contractual Obligations</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-220659"><span class="HTitleText2">Compensation</span></a>
</li>
<li><span class='sectionRange'>32.2 - </span><a href="page-3.html#h-220682"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-220732"><span class="HTitleText2">Restrictive Trade Practices</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-220746"><span class="HTitleText2">Environmental Considerations</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-220769"><span class="HTitleText2">Transportation</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="page-4.html#h-220826"><span class="HTitleText2">Confidentiality of Information</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-220836"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="page-4.html#h-220862"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Other Provisions</span></a>
</li></ul>
</li></ul>

</nav>

