<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Winding-up and Restructuring Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-465327"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-465332"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-465397"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-465412"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-465413"><span class="HTitleText2">Limitation of Part</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-465422"><span class="HTitleText2">Winding-up Order</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-465442"><span class="HTitleText2">Application for Order</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-465476"><span class="HTitleText2">Staying Proceedings</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-465485"><span class="HTitleText2">Effect of Winding-up Order</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-465528"><span class="HTitleText2">Appointment of Liquidators</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-465576"><span class="HTitleText2">Powers and Duties of Liquidators</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-465631"><span class="HTitleText2">Appointment of Inspectors</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-465636"><span class="HTitleText2">Remuneration of Liquidators and Inspectors</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-465649"><span class="HTitleText2">Court Discharging Functions of Liquidator</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-465661"><span class="HTitleText2">Contributories</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-465726"><span class="HTitleText2">Meetings of Creditors</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-465755"><span class="HTitleText2">Creditors’ Claims</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-465798"><span class="HTitleText2">Secured Claims</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-465844"><span class="HTitleText2">Dividend Sheet</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-465849"><span class="HTitleText2">Liens</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-465860"><span class="HTitleText2">Contestation of Claims</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-465888"><span class="HTitleText2">Distribution of Assets</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-465904"><span class="HTitleText2">Fraudulent Preferences</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-465974"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-465999"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-466123"><span class="HTitleText2">Rules, Regulations and Forms</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-466137"><span class="HTitleText2">Unclaimed Deposits</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-466154"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-466179"><span class="HTitleText2">Evidence</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-466198"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Authorized Foreign Banks</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-466265"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Restructuring of Insurance Companies</span></a>
</li></ul>
</li></ul>

</nav>

