<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de soutien de l’emploi</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-213276"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-213279"><span class="HTitleText1">Interprétation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-213294"><span class="HTitleText2">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-213297"><span class="HTitleText2">Prestation de fonds</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-213305"><span class="HTitleText2">Commission de soutien de l’emploi</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-213332"><span class="HTitleText2">Subvention de soutien de l’emploi</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-213355"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

