<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Centre on Substance Abuse Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-61494"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-61497"><span class="HTitleText1">Centre Established</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-61500"><span class="HTitleText1">Purpose of the Centre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-61508"><span class="HTitleText1">Capacity and Powers</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-61522"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-61548"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-61571"><span class="HTitleText1">Officers and Staff</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-61580"><span class="HTitleText1">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-61592"><span class="HTitleText1">Committees</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-61595"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-61603"><span class="HTitleText1">Status of Centre</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-61614"><span class="HTitleText1">Financial Year and Audit</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-61619"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-61631"><span class="HTitleText1">Evaluation</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-61636"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
