<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–Azerbaijan Tax Convention Act, 2004</a><ul class="TocIndent"><li><a href="page-2.html#h-42226"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Republic of Azerbaijan for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-3.html#h-42482"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

