<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la reprise économique (mesures incitatives)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-172280"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-172283"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modifications relatives à l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-172284"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-172299"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-1.html#h-172302"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Divers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-1.html#h-172303"><span class="HTitleText2">Paiements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-1.html#h-172304"><span class="HTitleText3">Allègement — dette multilatérale</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-172310"><span class="HTitleText3">Paiement à la Nouvelle-Écosse — hydrocarbures extracôtiers</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="page-1.html#h-172313"><span class="HTitleText2">Loi sur les accords de Bretton Woods et des accords connexes</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-172317"><span class="HTitleText2">Loi sur la radiodiffusion</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-172319"><span class="HTitleText2">Loi d’exécution du budget de 2009</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-172321"><span class="HTitleText2">Régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-1.html#h-172322"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-1.html#h-172341"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-1.html#h-172347"><span class="HTitleText2">Loi sur l’Office d’investissement du régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-1.html#h-172348"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-1.html#h-172351"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-1.html#h-172354"><span class="HTitleText2">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-1.html#h-172359"><span class="HTitleText2">Tarif des douanes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-1.html#h-172360"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-1.html#h-172367"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="page-1.html#h-172369"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="page-1.html#h-172370"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-1.html#h-172374"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-1.html#h-172377"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-1.html#h-172379"><span class="HTitleText2">Modifications relatives à la Loi sur la faillite et l’insolvabilité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="page-1.html#h-172380"><span class="HTitleText3">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-1.html#h-172385"><span class="HTitleText3">Chapitre 36 des Lois du Canada (2007)</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-2.html#h-172388"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>

