<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la réorganisation et l’aliénation de Téléglobe Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-450174"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-450177"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-450202"><span class="HTitleText1">Réorganisation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-450227"><span class="HTitleText1">Affaires internes et statut</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-450236"><span class="HTitleText1">Réglementation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-450241"><span class="HTitleText1">Aliénation et dissolution</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-450264"><span class="HTitleText1">Annexe</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-450266"><span class="HTitleText1">Dispositions transitoires et corrélatives</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-450323"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-450327"><span class="scheduleLabel">ANNEXES I ET II</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
