<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Revenue Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-49640"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-49645"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-49657"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-49660"><span class="HTitleText1">Continuation and Mandate of the Agency</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-49681"><span class="HTitleText1">Minister</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-49725"><span class="HTitleText1">Structure of the Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-49726"><span class="HTitleText2">Board of Management</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-49763"><span class="HTitleText2">Chair</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-49770"><span class="HTitleText2">Commissioner and Deputy Commissioner</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-49799"><span class="HTitleText1">General Authority of the Agency</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-49812"><span class="HTitleText1">Management and Direction of the Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-49813"><span class="HTitleText2">Responsibilities of the Board</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-49840"><span class="HTitleText2">Responsibilities of the Commissioner</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-49874"><span class="HTitleText2">Duties and Indemnification of Directors</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-49921"><span class="HTitleText1">Corporate Business Plan</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-49945"><span class="HTitleText1">Human Resources</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-50005"><span class="HTitleText1">Expenditures</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-50022"><span class="HTitleText1">Contracts, Agreements, Arrangements and Legal Proceedings</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-50064"><span class="HTitleText1">Intellectual Property</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-50069"><span class="HTitleText1">Real Property and Immovables</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-50170"><span class="HTitleText1">Reports to Parliament</span></a>
</li>
<li><span class='sectionRange'>89.1 - </span><a href="#h-50194"><span class="HTitleText1">Application of the Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-50197"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>106 to 185.1 - </span><a href="#h-50284"><span class="HTitleText1">Consequential and Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-50287"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-50289"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
