<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’assurance du service civil</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-83568"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-83573"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-83594"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-83599"><span class="HTitleText1">Contrats d’assurance</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-83704"><span class="HTitleText1">Sommes d’argent</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-83710"><span class="HTitleText1">Rapport</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
