<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la non-discrimination génétique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-241269"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-241272"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-241278"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-241298"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-241303"><span class="HTitleText1">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-241305"><span class="HTitleText1">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-241308"><span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>

</nav>

