<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Fisheries Improvement Loans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-233255"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-233260"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-233284"><span class="HTitleText1">Guaranteed Loans</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-233335"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-233360"><span class="HTitleText1">Special Powers of a Bank</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-233375"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-233389"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
