<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Fort Nelson Indian Reserve Minerals Revenue Sharing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-237121"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-237124"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-237129"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-237136"><span class="HTitleText1">Amendments</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-237141"><span class="HTitleText1">Commencement</span></a>
</li>
<li><a href="#h-237147"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
