<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les parcs nationaux du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Parcs nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Gestion</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">Terrains</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText1">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HTitleText1">Atténuation des dommages à l’environnement</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-11"><span class="HTitleText1">Collectivités</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-12"><span class="HTitleText1">Dispositions applicables à certains parcs</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-13"><span class="HTitleText1">Réserves</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-14"><span class="HTitleText1">Lieux historiques nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>43 à 46 - </span><a href="#h-15"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>47 à 56 - </span><a href="#h-16"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>68 à 70.1 - </span><a href="#h-17"><span class="HTitleText1">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-18"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-19"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Parcs nationaux du Canada</span></a>
</li>
<li><a href="#h-20"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Réserves à vocation de parc national du Canada</span></a>
</li>
<li><a href="#h-354493"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Espèces protégées</span></a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - Collectivités</span></a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - Stations commerciales de ski</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
