<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Carriage by Air Act</a><ul class="TocIndent"><li><a href="page-2.html#h-78968"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="page-3.html#h-79201"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Provisions as to Liability of Carrier in the Event of the Death of a Passenger</span></a>
</li>
<li><a href="page-4.html#h-79216"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li>
<li><a href="page-5.html#h-79346"><span class="scheduleLabel">SCHEDULE IV</span> <span class="scheduleTitleText"> - Montreal Protocol No. 4 To Amend the Convention for the Unification of Certain Rules Relating to International Carriage by Air, Signed at Warsaw on 12 October 1929, as Amended by the Protocol Done at the Hague on 28 September 1955</span></a>
</li>
<li><a href="page-6.html#h-79453"><span class="scheduleLabel">SCHEDULE V</span> <span class="scheduleTitleText"> - Convention, Supplementary to the Warsaw Convention, for the Unification of Certain Rules Relating to International Carriage by Air Performed by a Person Other than the Contracting Carrier</span></a>
</li>
<li><a href="page-7.html#h-79536"><span class="scheduleLabel">SCHEDULE VI</span> <span class="scheduleTitleText"> - Convention for the Unification of Certain Rules for International Carriage by Air</span></a>
</li></ul>
</li></ul>

</nav>

