<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Indian (Soldier Settlement) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1045430"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-1045436"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Soldier Settlement</span></a>
</li></ul>
</li></ul>

</nav>

