<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi autorisant la Société de développement du Cap-Breton à aliéner ses biens et prévoyant la dissolution de celle-ci</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-76858"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-76861"><span class="HTitleText1">Aliénation des biens et dissolution</span></a>
</li>
<li><span class='sectionRange'>6 à 17 - </span><a href="#h-76876"><span class="HTitleText1">Modification de la Loi sur la Société de développement du Cap-Breton</span></a>
</li>
<li><span class='sectionRange'>18 à 22 - </span><a href="#h-76878"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-76880"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
