<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi portant exécution de certaines dispositions du budget déposé au Parlement le 23 mars 2004</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Paiements de péréquation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText2">Transfert canadien en matière de programmes sociaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Généralités : paiements à certaines entités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Paiements à une fiducie</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText2">Paiements à la Nouvelle-Écosse</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Paiement à la Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Subventions accordées à certains organismes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText3">Fondation du Canada pour l’appui technologique au développement durable</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-12"><span class="HTitleText3">Inforoute Santé du Canada Inc.</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-13"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur la Fondation du Canada pour l’appui technologique au développement durable</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-14"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Modification du Régime de pensions du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-15"><span class="HTitleText2"><cite class="XRefExternalAct">Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-16"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-17"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-18"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Modification de la Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-19"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Modification de la Loi sur financement agricole Canada</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-20"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Remboursement aux municipalités de la taxe sur les produits et services et de la taxe de vente harmonisée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-22"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Délai de prescription pour le recouvrement de dettes fiscales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit pour la sécurité des passagers du transport aérien</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-24"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-25"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-26"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-27"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
