<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Crown Corporations Dissolution or Transfer Authorization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-135560"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-135563"><span class="HTitleText1">Canada Harbour Place Corporation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-135578"><span class="HTitleText1">Canada Museums Construction Corporation Inc.</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-135586"><span class="HTitleText1">Canadian Livestock Feed Board</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-135600"><span class="HTitleText1">Canadian Patents and Development Limited</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-135613"><span class="HTitleText1">Harbourfront Corporation</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-135637"><span class="HTitleText1">Mingan Associates, Ltd.</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-135644"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
