<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la compétence des premières nations en matière d’éducation en Colombie-Britannique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-221024"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-221027"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-221046"><span class="HTitleText1">Objet et effet</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-221056"><span class="HTitleText1">Effet de l’accord spécifique</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-221070"><span class="HTitleText1">Autorité scolaire des premières nations</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-221101"><span class="HTitleText1">Mission et attributions de l’autorité scolaire</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-221129"><span class="HTitleText1">Administration scolaire communautaire</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-221135"><span class="HTitleText1">Cadre législatif</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-221138"><span class="HTitleText1">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-221148"><span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-221154"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-221177"><span class="HTitleText1">Décrets et règlements</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-221183"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="page-2.html#h-221184"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-221186"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-2.html#h-221189"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-3.html#h-221193"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Premières nations participantes</span></a>
</li></ul>
</li></ul>

</nav>

