<nav role="navigation" id="wb-sm" data-ajax-replace="/ajax/sitemenu-en.html" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">
<div class="container nvbar">
<h2>Topics menu</h2>
<div class="row">
<ul class="list-inline menu">
<li><a href="#project">Family Law</a></li>
<li><a href="#implement">Criminal Justice</a></li>
<li><a href="#funding">Funding</a></li>
<li><a href="#systemofjustice">Canada's System of Justice</a></li>
<li><a href="#laws">Laws</a></li>
</ul>
</div>
</div>
</nav>