<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi de 1995 sur les opérations portuaires de la côte ouest <span class='Repealed'>[Abrogée, 2017, ch. 26, art. 68]</span></a></li></ul>
</nav>
</div></section>
