<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–Korea Income Tax Convention Act, 1980</a><ul class="TocIndent"><li><a href="page-2.html#h-148009"><span class="scheduleLabel">SCHEDULE IV</span> - <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Republic of Korea for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income</span></a>
</li></ul>
</li></ul>

</nav>

