<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le cadre fédéral relatif à l’état de stress post-traumatique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-232823"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-232826"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-232832"><span class="HTitleText1">Cadre fédéral relatif à l’état de stress post-traumatique</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-232845"><span class="HTitleText1">Examen et rapport</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
