<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Pesticide Residue Compensation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-391423"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-391428"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-391437"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Pesticide Residue Compensation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-391438"><span class="HTitleText2">Compensation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-391485"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-391519"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-391538"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Compensation Appeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-391539"><span class="HTitleText2">Assessor</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

