<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Supplementary Fiscal Equalization Payments 1982-87 Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-442429"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-442432"><span class="HTitleText1">Supplementary Payments</span></a>
</li></ul>
</li></ul>

</nav>

