<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Visiting Forces Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-464020"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-464025"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-464040"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Application of Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-464053"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Disciplinary Jurisdiction of Visiting Forces</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-464131"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Claims for Personal Injuries and Property Damage</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-464166"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Security Provisions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-464183"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Taxation</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-464214"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Attachments to and from Canadian Forces</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-464234"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

