<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1994 sur la convention concernant les oiseaux migrateurs</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-348661"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-348664"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-348704"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-348709"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-348712"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-348717"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>5.4 - </span><a href="#h-348756"><span class="HTitleText1">Obligations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-348765"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-349026"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-349055"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>18.3 - </span><a href="#h-349398"><span class="HTitleText1">Application du droit criminel</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-349419"><span class="HTitleText1">Contraventions</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="#h-349445"><span class="HTitleText1">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-349460"><span class="HTitleText1">Modification corrélative</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-349462"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><a href="#h-349465"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - (Traduction)</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
