<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Agricultural Loans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-232948"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-232953"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-232970"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-232975"><span class="HTitleText1">Guaranteed Farm Loans</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-233025"><span class="HTitleText1">Guaranteed Farm Products Marketing Loans</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-233055"><span class="HTitleText1">Limitation of Minister’s Liability</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-233090"><span class="HTitleText1">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-233114"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-233126"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>23 to 25 - </span><a href="#h-233153"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>26 to 32 - </span><a href="#h-233155"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-233157"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

