<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi limitant les dépenses publiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-426744"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-426747"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-426772"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

