<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Criminal Code</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-3"><span class="HTitleText1">Part I</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3.1 - </span><a href="#h-4"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-5"><span class="HTitleText2">Parties to Offences</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-6"><span class="HTitleText2">Protection of Persons Administering and Enforcing the Law</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-7"><span class="HTitleText2">Suppression of Riots</span></a>
</li>
<li><span class='sectionRange'>33.1 - </span><a href="#h-8"><span class="HTitleText2">Self-induced Intoxication</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-9"><span class="HTitleText2">Defence of Person</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-10"><span class="HTitleText2">Defence of Property</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-11"><span class="HTitleText2">Protection of Persons in Authority</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-12"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Offences Against Public Order</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-13"><span class="HTitleText2">Treason and other Offences against the Queen’s Authority and Person</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-14"><span class="HTitleText2">Prohibited Acts</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-15"><span class="HTitleText2">Passports</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-16"><span class="HTitleText2">Sedition</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-17"><span class="HTitleText2">Unlawful Assemblies and Riots</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-18"><span class="HTitleText2">Unlawful Drilling</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-19"><span class="HTitleText2">Duels</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-20"><span class="HTitleText2">Forcible Entry and Detainer</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-21"><span class="HTitleText2">Piracy</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-22"><span class="HTitleText2">Offences against Air or Maritime Safety</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-23"><span class="HTitleText2">Dangerous Substances</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-24"><span class="HTitleText2">Prize Fights</span></a>
</li></ul>
</li><li><span class='sectionRange'>83.01 - </span><a href="#h-25"><span class="HLabel1">PART II.1</span> - <span class="HTitleText1">Terrorism</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83.01 - </span><a href="#h-26"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>83.02 - </span><a href="#h-27"><span class="HTitleText2">Financing of Terrorism</span></a>
</li>
<li><span class='sectionRange'>83.05 - </span><a href="#h-28"><span class="HTitleText2">List of Entities</span></a>
</li>
<li><span class='sectionRange'>83.08 - </span><a href="#h-29"><span class="HTitleText2">Freezing of Property</span></a>
</li>
<li><span class='sectionRange'>83.13 - </span><a href="#h-30"><span class="HTitleText2">Seizure and Restraint of Property</span></a>
</li>
<li><span class='sectionRange'>83.14 - </span><a href="#h-31"><span class="HTitleText2">Forfeiture of Property</span></a>
</li>
<li><span class='sectionRange'>83.18 - </span><a href="#h-32"><span class="HTitleText2">Participating, Facilitating, Instructing and Harbouring</span></a>
</li>
<li><span class='sectionRange'>83.231 - </span><a href="#h-33"><span class="HTitleText2">Hoax Regarding Terrorist Activity</span></a>
</li>
<li><span class='sectionRange'>83.24 - </span><a href="#h-34"><span class="HTitleText2">Proceedings and Aggravated Punishment</span></a>
</li>
<li><span class='sectionRange'>83.28 - </span><a href="#h-35"><span class="HTitleText2">Investigative Hearing</span></a>
</li>
<li><span class='sectionRange'>83.3 - </span><a href="#h-36"><span class="HTitleText2">Recognizance with Conditions</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-37"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Firearms and Other Weapons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-38"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-39"><span class="HTitleText2">Use Offences</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-40"><span class="HTitleText2">Possession Offences</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-41"><span class="HTitleText2">Trafficking Offences</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-42"><span class="HTitleText2">Assembling Offence</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-43"><span class="HTitleText2">Export and Import Offences</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-44"><span class="HTitleText2">Offences relating to Lost, Destroyed or Defaced Weapons, etc.</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-45"><span class="HTitleText2">Prohibition Orders</span></a>
</li>
<li><span class='sectionRange'>117.011 - </span><a href="#h-46"><span class="HTitleText2">Limitations on Access</span></a>
</li>
<li><span class='sectionRange'>117.02 - </span><a href="#h-47"><span class="HTitleText2">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>117.07 - </span><a href="#h-48"><span class="HTitleText2">Exempted Persons</span></a>
</li>
<li><span class='sectionRange'>117.11 - </span><a href="#h-49"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-50"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Offences Against the Administration of Law and Justice</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="#h-51"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-52"><span class="HTitleText2">Corruption and Disobedience</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-53"><span class="HTitleText2">Misleading Justice</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-54"><span class="HTitleText2">Escapes and Rescues</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-55"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Sexual Offences, Public Morals and Disorderly Conduct</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-56"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>150.1 - </span><a href="#h-57"><span class="HTitleText2">Sexual Offences</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-58"><span class="HTitleText2">Offences Tending to Corrupt Morals</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-59"><span class="HTitleText2">Disorderly Conduct</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-60"><span class="HTitleText2">Nuisances</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="#h-61"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Invasion of Privacy</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-62"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-63"><span class="HTitleText2">Interception of Communications</span></a>
</li></ul>
</li><li><span class='sectionRange'>197 - </span><a href="#h-64"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Disorderly Houses, Gaming and Betting</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-65"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-66"><span class="HTitleText2">Presumptions</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-67"><span class="HTitleText2">Search</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-68"><span class="HTitleText2">Obstruction</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-69"><span class="HTitleText2">Gaming and Betting</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-70"><span class="HTitleText2">Bawdy-houses</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-71"><span class="HTitleText2">Procuring</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-72"><span class="HTitleText2">Offence in Relation to Prostitution</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-73"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Offences Against the Person and Reputation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-74"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-75"><span class="HTitleText2">Duties Tending to Preservation of Life</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-76"><span class="HTitleText2">Criminal Negligence</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-77"><span class="HTitleText2">Homicide</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-78"><span class="HTitleText2">Murder, Manslaughter and Infanticide</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="#h-79"><span class="HTitleText2">Suicide</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-80"><span class="HTitleText2">Neglect in Child-birth and Concealing Dead Body</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-81"><span class="HTitleText2">Bodily Harm and Acts and Omissions Causing Danger to the Person</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-82"><span class="HTitleText2">Motor Vehicles, Vessels and Aircraft</span></a>
</li>
<li><span class='sectionRange'>264.1 - </span><a href="#h-83"><span class="HTitleText2">Assaults</span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-84"><span class="HTitleText2">Kidnapping, Trafficking in Persons, Hostage Taking and Abduction</span></a>
</li>
<li><span class='sectionRange'>287 - </span><a href="#h-85"><span class="HTitleText2">Abortion</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="#h-86"><span class="HTitleText2">Venereal Diseases</span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-87"><span class="HTitleText2">Offences Against Conjugal Rights</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-88"><span class="HTitleText2">Unlawful Solemnization of Marriage</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-89"><span class="HTitleText2">Blasphemous Libel</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-90"><span class="HTitleText2">Defamatory Libel</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="#h-91"><span class="HTitleText2">Verdicts</span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="#h-92"><span class="HTitleText2">Hate Propaganda</span></a>
</li></ul>
</li><li><span class='sectionRange'>321 - </span><a href="#h-93"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Offences Against Rights of Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>321 - </span><a href="#h-94"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="#h-95"><span class="HTitleText2">Theft</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-96"><span class="HTitleText2">Offences Resembling Theft</span></a>
</li>
<li><span class='sectionRange'>343 - </span><a href="#h-97"><span class="HTitleText2">Robbery and Extortion</span></a>
</li>
<li><span class='sectionRange'>347 - </span><a href="#h-98"><span class="HTitleText2">Criminal Interest Rate</span></a>
</li>
<li><span class='sectionRange'>348 - </span><a href="#h-99"><span class="HTitleText2">Breaking and Entering</span></a>
</li>
<li><span class='sectionRange'>354 - </span><a href="#h-100"><span class="HTitleText2">Having in Possession</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-101"><span class="HTitleText2">False Pretences</span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="#h-102"><span class="HTitleText2">Forgery and Offences Resembling Forgery</span></a>
</li></ul>
</li><li><span class='sectionRange'>379 - </span><a href="#h-103"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Fraudulent Transactions Relating to Contracts and Trade</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>379 - </span><a href="#h-104"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="#h-105"><span class="HTitleText2">Fraud</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="#h-106"><span class="HTitleText2">Falsification of Books and Documents</span></a>
</li>
<li><span class='sectionRange'>403 - </span><a href="#h-107"><span class="HTitleText2">Personation</span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="#h-108"><span class="HTitleText2">Forgery of Trade-marks and Trade Descriptions</span></a>
</li>
<li><span class='sectionRange'>415 - </span><a href="#h-109"><span class="HTitleText2">Wreck</span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-110"><span class="HTitleText2">Public Stores</span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="#h-111"><span class="HTitleText2">Breach of Contract, Intimidation and Discrimination Against Trade Unionists</span></a>
</li>
<li><span class='sectionRange'>426 - </span><a href="#h-112"><span class="HTitleText2">Secret Commissions</span></a>
</li>
<li><span class='sectionRange'>427 - </span><a href="#h-113"><span class="HTitleText2">Trading Stamps</span></a>
</li></ul>
</li><li><span class='sectionRange'>428 - </span><a href="#h-114"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Wilful and Forbidden Acts in Respect of Certain Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>428 - </span><a href="#h-115"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="#h-116"><span class="HTitleText2">Mischief</span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="#h-117"><span class="HTitleText2">Arson and Other Fires</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="#h-118"><span class="HTitleText2">Other Interference with Property</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="#h-119"><span class="HTitleText2">Cattle and Other Animals</span></a>
</li>
<li><span class='sectionRange'>446 - </span><a href="#h-120"><span class="HTitleText2">Cruelty to Animals</span></a>
</li></ul>
</li><li><span class='sectionRange'>448 - </span><a href="#h-121"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Offences Relating to Currency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>448 - </span><a href="#h-122"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-123"><span class="HTitleText2">Making</span></a>
</li>
<li><span class='sectionRange'>450 - </span><a href="#h-124"><span class="HTitleText2">Possession</span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-125"><span class="HTitleText2">Uttering</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="#h-126"><span class="HTitleText2">Defacing or Impairing</span></a>
</li>
<li><span class='sectionRange'>458 - </span><a href="#h-127"><span class="HTitleText2">Instruments or Materials</span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="#h-128"><span class="HTitleText2">Advertising and Trafficking in Counterfeit Money or Counterfeit Tokens of Value</span></a>
</li>
<li><span class='sectionRange'>461 - </span><a href="#h-129"><span class="HTitleText2">Special Provisions as to Proof</span></a>
</li>
<li><span class='sectionRange'>462 - </span><a href="#h-130"><span class="HTitleText2">Forfeiture</span></a>
</li></ul>
</li><li><span class='sectionRange'>462.1 - </span><a href="#h-131"><span class="HLabel1">PART XII.1</span> - <span class="HTitleText1">Instruments and Literature for Illicit Drug Use</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>462.1 - </span><a href="#h-132"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>462.2 - </span><a href="#h-133"><span class="HTitleText2">Offence and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>462.3 - </span><a href="#h-134"><span class="HLabel1">PART XII.2</span> - <span class="HTitleText1">Proceeds of Crime</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>462.3 - </span><a href="#h-135"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>462.31 - </span><a href="#h-136"><span class="HTitleText2">Offence</span></a>
</li>
<li><span class='sectionRange'>462.32 - </span><a href="#h-137"><span class="HTitleText2">Search, Seizure and Detention of Proceeds of Crime</span></a>
</li>
<li><span class='sectionRange'>462.37 - </span><a href="#h-138"><span class="HTitleText2">Forfeiture of Proceeds of Crime</span></a>
</li>
<li><span class='sectionRange'>462.47 - </span><a href="#h-139"><span class="HTitleText2">Disclosure Provisions</span></a>
</li>
<li><span class='sectionRange'>462.49 - </span><a href="#h-140"><span class="HTitleText2">Specific Rules of Forfeiture</span></a>
</li>
<li><span class='sectionRange'>462.5 - </span><a href="#h-141"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>463 - </span><a href="#h-142"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Attempts — Conspiracies — Accessories</span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-143"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Jurisdiction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>468 - </span><a href="#h-144"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>476 - </span><a href="#h-145"><span class="HTitleText2">Special Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>482 - </span><a href="#h-146"><span class="HTitleText2">Rules of Court</span></a>
</li></ul>
</li><li><span class='sectionRange'>483 - </span><a href="#h-147"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">Special Procedure and Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>483 - </span><a href="#h-148"><span class="HTitleText2">General Powers of Certain Officials</span></a>
</li>
<li><span class='sectionRange'>487.04 - </span><a href="#h-149"><span class="HTitleText2">Forensic DNA Analysis</span></a>
</li>
<li><span class='sectionRange'>487.1 - </span><a href="#h-150"><span class="HTitleText2">Other Provisions respecting Search Warrants</span></a>
</li>
<li><span class='sectionRange'>490.011 - </span><a href="#h-151"><span class="HTitleText2">Sex Offender Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>490.011 - </span><a href="#h-152"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>490.012 - </span><a href="#h-153"><span class="HTitleText3">Order to Comply with Registration Requirements</span></a>
</li>
<li><span class='sectionRange'>490.019 - </span><a href="#h-154"><span class="HTitleText3">Obligation to Comply with Registration Requirements</span></a>
</li>
<li><span class='sectionRange'>490.03 - </span><a href="#h-155"><span class="HTitleText3">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>490.031 - </span><a href="#h-156"><span class="HTitleText3">Offences</span></a>
</li>
<li><span class='sectionRange'>490.032 - </span><a href="#h-157"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>490.1 - </span><a href="#h-158"><span class="HTitleText2">Forfeiture of Offence-related Property</span></a>
</li></ul>
</li><li><span class='sectionRange'>493 - </span><a href="#h-159"><span class="HLabel1">PART XVI</span> - <span class="HTitleText1">Compelling Appearance of Accused Before a Justice and Interim Release</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>493 - </span><a href="#h-160"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>494 - </span><a href="#h-161"><span class="HTitleText2">Arrest without Warrant and Release from Custody</span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-162"><span class="HTitleText2">Appearance of Accused before Justice</span></a>
</li>
<li><span class='sectionRange'>504 - </span><a href="#h-163"><span class="HTitleText2">Information, Summons and Warrant</span></a>
</li>
<li><span class='sectionRange'>515 - </span><a href="#h-164"><span class="HTitleText2">Judicial Interim Release</span></a>
</li>
<li><span class='sectionRange'>524 - </span><a href="#h-165"><span class="HTitleText2">Arrest of Accused on Interim Release</span></a>
</li>
<li><span class='sectionRange'>525 - </span><a href="#h-166"><span class="HTitleText2">Review of Detention where Trial Delayed</span></a>
</li>
<li><span class='sectionRange'>527 - </span><a href="#h-167"><span class="HTitleText2">Procedure to Procure Attendance of a Prisoner</span></a>
</li>
<li><span class='sectionRange'>528 - </span><a href="#h-168"><span class="HTitleText2">Endorsement of Warrant</span></a>
</li>
<li><span class='sectionRange'>529 - </span><a href="#h-169"><span class="HTitleText2">Powers to Enter Dwelling-houses to Carry out Arrests</span></a>
</li></ul>
</li><li><span class='sectionRange'>530 - </span><a href="#h-170"><span class="HLabel1">PART XVII</span> - <span class="HTitleText1">Language of Accused</span></a>
</li>
<li><span class='sectionRange'>535 - </span><a href="#h-171"><span class="HLabel1">PART XVIII</span> - <span class="HTitleText1">Procedure on Preliminary Inquiry</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>535 - </span><a href="#h-172"><span class="HTitleText2">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>536.3 - </span><a href="#h-173"><span class="HTitleText2">Procedures before Preliminary Inquiry</span></a>
</li>
<li><span class='sectionRange'>537 - </span><a href="#h-174"><span class="HTitleText2">Powers of Justice</span></a>
</li>
<li><span class='sectionRange'>539 - </span><a href="#h-175"><span class="HTitleText2">Taking Evidence of Witnesses</span></a>
</li>
<li><span class='sectionRange'>543 - </span><a href="#h-176"><span class="HTitleText2">Remand Where Offence Committed in Another Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>544 - </span><a href="#h-177"><span class="HTitleText2">Absconding Accused</span></a>
</li>
<li><span class='sectionRange'>545 - </span><a href="#h-178"><span class="HTitleText2">Procedure where Witness Refuses to Testify</span></a>
</li>
<li><span class='sectionRange'>546 - </span><a href="#h-179"><span class="HTitleText2">Remedial Provisions</span></a>
</li>
<li><span class='sectionRange'>548 - </span><a href="#h-180"><span class="HTitleText2">Adjudication and Recognizances</span></a>
</li>
<li><span class='sectionRange'>551 - </span><a href="#h-181"><span class="HTitleText2">Transmission of Record</span></a>
</li></ul>
</li><li><span class='sectionRange'>552 - </span><a href="#h-182"><span class="HLabel1">PART XIX</span> - <span class="HTitleText1">Indictable Offences — Trial Without Jury</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>552 - </span><a href="#h-183"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>553 - </span><a href="#h-184"><span class="HTitleText2">Jurisdiction of Provincial Court Judges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>553 - </span><a href="#h-185"><span class="HTitleText3">Absolute Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>554 - </span><a href="#h-186"><span class="HTitleText3">Provincial Court Judge’s Jurisdiction with Consent</span></a>
</li></ul>
</li><li><span class='sectionRange'>558 - </span><a href="#h-187"><span class="HTitleText2">Jurisdiction of Judges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>558 - </span><a href="#h-188"><span class="HTitleText3">Judge’s Jurisdiction with Consent</span></a>
</li>
<li><span class='sectionRange'>560 - </span><a href="#h-189"><span class="HTitleText3">Election</span></a>
</li>
<li><span class='sectionRange'>566 - </span><a href="#h-190"><span class="HTitleText3">Trial</span></a>
</li></ul>
</li><li><span class='sectionRange'>567 - </span><a href="#h-191"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>573 - </span><a href="#h-192"><span class="HLabel1">PART XIX.1</span> - <span class="HTitleText1">Nunavut Court of Justice</span></a>
</li>
<li><span class='sectionRange'>574 - </span><a href="#h-193"><span class="HLabel1">PART XX</span> - <span class="HTitleText1">Procedure in Jury Trials and General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>574 - </span><a href="#h-194"><span class="HTitleText2">Preferring Indictment</span></a>
</li>
<li><span class='sectionRange'>581 - </span><a href="#h-195"><span class="HTitleText2">General Provisions respecting Counts</span></a>
</li>
<li><span class='sectionRange'>584 - </span><a href="#h-196"><span class="HTitleText2">Special Provisions respecting Counts</span></a>
</li>
<li><span class='sectionRange'>587 - </span><a href="#h-197"><span class="HTitleText2">Particulars</span></a>
</li>
<li><span class='sectionRange'>588 - </span><a href="#h-198"><span class="HTitleText2">Ownership of Property</span></a>
</li>
<li><span class='sectionRange'>589 - </span><a href="#h-199"><span class="HTitleText2">Joinder or Severance of Counts</span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-200"><span class="HTitleText2">Joinder of Accused in Certain Cases</span></a>
</li>
<li><span class='sectionRange'>597 - </span><a href="#h-201"><span class="HTitleText2">Proceedings when Person Indicted is at Large</span></a>
</li>
<li><span class='sectionRange'>599 - </span><a href="#h-202"><span class="HTitleText2">Change of Venue</span></a>
</li>
<li><span class='sectionRange'>601 - </span><a href="#h-203"><span class="HTitleText2">Amendment</span></a>
</li>
<li><span class='sectionRange'>603 - </span><a href="#h-204"><span class="HTitleText2">Inspection and Copies of Documents</span></a>
</li>
<li><span class='sectionRange'>606 - </span><a href="#h-205"><span class="HTitleText2">Pleas</span></a>
</li>
<li><span class='sectionRange'>620 - </span><a href="#h-206"><span class="HTitleText2">Organizations</span></a>
</li>
<li><span class='sectionRange'>624 - </span><a href="#h-207"><span class="HTitleText2">Record of Proceedings</span></a>
</li>
<li><span class='sectionRange'>625.1 - </span><a href="#h-208"><span class="HTitleText2">Pre-hearing Conference</span></a>
</li>
<li><span class='sectionRange'>626 - </span><a href="#h-209"><span class="HTitleText2">Juries</span></a>
</li>
<li><span class='sectionRange'>628 - </span><a href="#h-210"><span class="HTitleText2">Challenging the Array</span></a>
</li>
<li><span class='sectionRange'>631 - </span><a href="#h-211"><span class="HTitleText2">Empanelling Jury</span></a>
</li>
<li><span class='sectionRange'>645 - </span><a href="#h-212"><span class="HTitleText2">Trial</span></a>
</li>
<li><span class='sectionRange'>655 - </span><a href="#h-213"><span class="HTitleText2">Evidence on Trial</span></a>
</li>
<li><span class='sectionRange'>658 - </span><a href="#h-214"><span class="HTitleText2">Children and Young Persons</span></a>
</li>
<li><span class='sectionRange'>659 - </span><a href="#h-215"><span class="HTitleText2">Corroboration</span></a>
</li>
<li><span class='sectionRange'>660 - </span><a href="#h-216"><span class="HTitleText2">Verdicts</span></a>
</li>
<li><span class='sectionRange'>664 - </span><a href="#h-217"><span class="HTitleText2">Previous Convictions</span></a>
</li>
<li><span class='sectionRange'>669.1 - </span><a href="#h-218"><span class="HTitleText2">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>670 - </span><a href="#h-219"><span class="HTitleText2">Formal Defects in Jury Process</span></a>
</li></ul>
</li><li><span class='sectionRange'>672.1 - </span><a href="#h-220"><span class="HLabel1">PART XX.1</span> - <span class="HTitleText1">Mental Disorder</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>672.1 - </span><a href="#h-221"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>672.11 - </span><a href="#h-222"><span class="HTitleText2">Assessment Orders</span></a>
</li>
<li><span class='sectionRange'>672.2 - </span><a href="#h-223"><span class="HTitleText2">Assessment Reports</span></a>
</li>
<li><span class='sectionRange'>672.21 - </span><a href="#h-224"><span class="HTitleText2">Protected Statements</span></a>
</li>
<li><span class='sectionRange'>672.22 - </span><a href="#h-225"><span class="HTitleText2">Fitness to Stand Trial</span></a>
</li>
<li><span class='sectionRange'>672.34 - </span><a href="#h-226"><span class="HTitleText2">Verdict of Not Criminally Responsible on Account of Mental Disorder</span></a>
</li>
<li><span class='sectionRange'>672.38 - </span><a href="#h-227"><span class="HTitleText2">Review Boards</span></a>
</li>
<li><span class='sectionRange'>672.45 - </span><a href="#h-228"><span class="HTitleText2">Disposition Hearings</span></a>
</li>
<li><span class='sectionRange'>672.54 - </span><a href="#h-229"><span class="HTitleText2">Dispositions by a Court or Review Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>672.54 - </span><a href="#h-230"><span class="HTitleText3">Terms of Dispositions</span></a>
</li>
<li><span class='sectionRange'>672.67 - </span><a href="#h-231"><span class="HTitleText3">Dual Status Offenders</span></a>
</li></ul>
</li><li><span class='sectionRange'>672.72 - </span><a href="#h-232"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>672.81 - </span><a href="#h-233"><span class="HTitleText2">Review of Dispositions</span></a>
</li>
<li><span class='sectionRange'>672.85 - </span><a href="#h-234"><span class="HTitleText2">Power to Compel Appearance</span></a>
</li>
<li><span class='sectionRange'>672.851 - </span><a href="#h-235"><span class="HTitleText2">Stay of Proceedings</span></a>
</li>
<li><span class='sectionRange'>672.86 - </span><a href="#h-236"><span class="HTitleText2">Interprovincial Transfers</span></a>
</li>
<li><span class='sectionRange'>672.9 - </span><a href="#h-237"><span class="HTitleText2">Enforcement of Orders and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>673 - </span><a href="#h-238"><span class="HLabel1">PART XXI</span> - <span class="HTitleText1">Appeals — Indictable Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>673 - </span><a href="#h-239"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>674 - </span><a href="#h-240"><span class="HTitleText2">Right of Appeal</span></a>
</li>
<li><span class='sectionRange'>678 - </span><a href="#h-241"><span class="HTitleText2">Procedure on Appeals</span></a>
</li>
<li><span class='sectionRange'>686 - </span><a href="#h-242"><span class="HTitleText2">Powers of the Court of Appeal</span></a>
</li>
<li><span class='sectionRange'>691 - </span><a href="#h-243"><span class="HTitleText2">Appeals to the Supreme Court of Canada</span></a>
</li>
<li><span class='sectionRange'>696 - </span><a href="#h-244"><span class="HTitleText2">Appeals by Attorney General of Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>696.1 - </span><a href="#h-245"><span class="HLabel1">PART XXI.1</span> - <span class="HTitleText1">Applications for Ministerial Review — Miscarriages of Justice</span></a>
</li>
<li><span class='sectionRange'>697 - </span><a href="#h-246"><span class="HLabel1">PART XXII</span> - <span class="HTitleText1">Procuring Attendance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>697 - </span><a href="#h-247"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>698 - </span><a href="#h-248"><span class="HTitleText2">Process</span></a>
</li>
<li><span class='sectionRange'>701 - </span><a href="#h-249"><span class="HTitleText2">Execution or Service of Process</span></a>
</li>
<li><span class='sectionRange'>704 - </span><a href="#h-250"><span class="HTitleText2">Defaulting or Absconding Witness</span></a>
</li>
<li><span class='sectionRange'>708.1 - </span><a href="#h-251"><span class="HTitleText2">Electronically Transmitted Copies</span></a>
</li>
<li><span class='sectionRange'>709 - </span><a href="#h-252"><span class="HTitleText2">Evidence on Commission</span></a>
</li>
<li><span class='sectionRange'>714.1 - </span><a href="#h-253"><span class="HTitleText2">Video and Audio Evidence</span></a>
</li>
<li><span class='sectionRange'>715 - </span><a href="#h-254"><span class="HTitleText2">Evidence Previously Taken</span></a>
</li>
<li><span class='sectionRange'>715.1 - </span><a href="#h-255"><span class="HTitleText2">Video-recorded Evidence</span></a>
</li></ul>
</li><li><span class='sectionRange'>716 - </span><a href="#h-256"><span class="HLabel1">PART XXIII</span> - <span class="HTitleText1">Sentencing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>716 - </span><a href="#h-257"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>717 - </span><a href="#h-258"><span class="HTitleText2">Alternative Measures</span></a>
</li>
<li><span class='sectionRange'>718 - </span><a href="#h-259"><span class="HTitleText2">Purpose and Principles of Sentencing</span></a>
</li>
<li><span class='sectionRange'>718.21 - </span><a href="#h-260"><span class="HTitleText2">Organizations</span></a>
</li>
<li><span class='sectionRange'>718.3 - </span><a href="#h-261"><span class="HTitleText2">Punishment Generally</span></a>
</li>
<li><span class='sectionRange'>720 - </span><a href="#h-262"><span class="HTitleText2">Procedure and Evidence</span></a>
</li>
<li><span class='sectionRange'>730 - </span><a href="#h-263"><span class="HTitleText2">Absolute and Conditional Discharges</span></a>
</li>
<li><span class='sectionRange'>731 - </span><a href="#h-264"><span class="HTitleText2">Probation</span></a>
</li>
<li><span class='sectionRange'>734 - </span><a href="#h-265"><span class="HTitleText2">Fines and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>738 - </span><a href="#h-266"><span class="HTitleText2">Restitution</span></a>
</li>
<li><span class='sectionRange'>742 - </span><a href="#h-267"><span class="HTitleText2">Conditional Sentence of Imprisonment</span></a>
</li>
<li><span class='sectionRange'>743 - </span><a href="#h-268"><span class="HTitleText2">Imprisonment</span></a>
</li>
<li><span class='sectionRange'>743.6 - </span><a href="#h-269"><span class="HTitleText2">Eligibility for Parole</span></a>
</li>
<li><span class='sectionRange'>744 - </span><a href="#h-270"><span class="HTitleText2">Delivery of Offender to Keeper of Prison</span></a>
</li>
<li><span class='sectionRange'>745 - </span><a href="#h-271"><span class="HTitleText2">Imprisonment for Life</span></a>
</li>
<li><span class='sectionRange'>748 - </span><a href="#h-272"><span class="HTitleText2">Pardons and Remissions</span></a>
</li>
<li><span class='sectionRange'>750 - </span><a href="#h-273"><span class="HTitleText2">Disabilities</span></a>
</li>
<li><span class='sectionRange'>751 - </span><a href="#h-274"><span class="HTitleText2">Miscellaneous Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>752 - </span><a href="#h-275"><span class="HLabel1">PART XXIV</span> - <span class="HTitleText1">Dangerous Offenders and Long-term Offenders</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>752 - </span><a href="#h-276"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>752.1 - </span><a href="#h-277"><span class="HTitleText2">Dangerous Offenders and Long-Term Offenders</span></a>
</li></ul>
</li><li><span class='sectionRange'>762 - </span><a href="#h-278"><span class="HLabel1">PART XXV</span> - <span class="HTitleText1">Effect and Enforcement of Recognizances</span></a>
</li>
<li><span class='sectionRange'>774 - </span><a href="#h-279"><span class="HLabel1">PART XXVI</span> - <span class="HTitleText1">Extraordinary Remedies</span></a>
</li>
<li><span class='sectionRange'>785 - </span><a href="#h-280"><span class="HLabel1">PART XXVII</span> - <span class="HTitleText1">Summary Convictions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>785 - </span><a href="#h-281"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>787 - </span><a href="#h-282"><span class="HTitleText2">Punishment</span></a>
</li>
<li><span class='sectionRange'>788 - </span><a href="#h-283"><span class="HTitleText2">Information</span></a>
</li>
<li><span class='sectionRange'>793 - </span><a href="#h-284"><span class="HTitleText2">Defects and Objections</span></a>
</li>
<li><span class='sectionRange'>795 - </span><a href="#h-285"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>798 - </span><a href="#h-286"><span class="HTitleText2">Trial</span></a>
</li>
<li><span class='sectionRange'>804 - </span><a href="#h-287"><span class="HTitleText2">Adjudication</span></a>
</li>
<li><span class='sectionRange'>810 - </span><a href="#h-288"><span class="HTitleText2">Sureties to Keep the Peace</span></a>
</li>
<li><span class='sectionRange'>812 - </span><a href="#h-289"><span class="HTitleText2">Appeal</span></a>
</li>
<li><span class='sectionRange'>816 - </span><a href="#h-290"><span class="HTitleText2">Interim Release of Appellant</span></a>
</li>
<li><span class='sectionRange'>821 - </span><a href="#h-291"><span class="HTitleText2">Procedure on Appeal</span></a>
</li>
<li><span class='sectionRange'>829 - </span><a href="#h-292"><span class="HTitleText2">Summary Appeal on Transcript or Agreed Statement of Facts</span></a>
</li>
<li><span class='sectionRange'>839 - </span><a href="#h-293"><span class="HTitleText2">Appeals to Court of Appeal</span></a>
</li>
<li><span class='sectionRange'>840 - </span><a href="#h-294"><span class="HTitleText2">Fees and Allowances</span></a>
</li></ul>
</li><li><span class='sectionRange'>841 - </span><a href="#h-295"><span class="HLabel1">PART XXVIII</span> - <span class="HTitleText1">Miscellaneous</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>841 - </span><a href="#h-296"><span class="HTitleText2">Electronic Documents</span></a>
</li>
<li><span class='sectionRange'>848 - </span><a href="#h-297"><span class="HTitleText2">Remote Appearance by Incarcerated Accused</span></a>
</li>
<li><span class='sectionRange'>849 - </span><a href="#h-298"><span class="HTitleText2">Forms</span></a>
</li></ul>
</li><li><a href="#h-133415"><span class="scheduleLabel">SCHEDULE TO PART XX.1</span></a>
</li>
<li><a href="#h-300"><span class="scheduleLabel">SCHEDULE [to Part XXV]</span> </a>
</li>
<li><a href="#h-133467"><span class="scheduleLabel">SCHEDULE [to Part XXVII]</span> </a>
</li>
<li><a href="#h-302"><span class="scheduleLabel">[Forms]</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
