<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Youth Criminal Justice Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-470115"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-470118"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-470162"><span class="HTitleText1">Declaration of Principle</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-470190"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Extrajudicial Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-470191"><span class="HTitleText2">Principles and Objectives</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-470207"><span class="HTitleText2">Warnings, Cautions and Referrals</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-470219"><span class="HTitleText2">Extrajudicial Sanctions</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-470248"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Organization of Youth Criminal Justice System</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-470249"><span class="HTitleText2">Youth Justice Court</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-470302"><span class="HTitleText2">Youth Justice Committees</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-470318"><span class="HTitleText2">Conferences</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-470328"><span class="HTitleText2">Justices of the Peace</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-470334"><span class="HTitleText2">Clerks of the Court</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-470339"><span class="HTitleText2">Provincial Directors</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-470342"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Judicial Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-470343"><span class="HTitleText2">Consent to Prosecute</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-1214556"><span class="HTitleText2">Certain Offences — Review of Charges by Attorney General</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-470351"><span class="HTitleText2">Right to Counsel</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-470394"><span class="HTitleText2">Notices to Parents</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-470443"><span class="HTitleText2">Detention and Release</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-470513"><span class="HTitleText2">Appearance</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-470534"><span class="HTitleText2">Application for Release from or Detention in Custody</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-470554"><span class="HTitleText2">Medical and Psychological Reports</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-470608"><span class="HTitleText2">Referral to Child Welfare Agency</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-470611"><span class="HTitleText2">Adjudication</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-470617"><span class="HTitleText2">Appeals</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-470643"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Sentencing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-470644"><span class="HTitleText2">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-470699"><span class="HTitleText2">Pre-sentence Report</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-470749"><span class="HTitleText2">Youth Sentences</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-471029"><span class="HTitleText2">Adult Sentence and Election</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-471195"><span class="HTitleText2">Effect of Termination of Youth Sentence</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-471217"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Custody and Supervision</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-471611"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Publication, Records and Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-471612"><span class="HTitleText2">Protection of Privacy of Young Persons</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-471644"><span class="HTitleText2">Fingerprints and Photographs</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-471650"><span class="HTitleText2">Records That May Be Kept</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-471676"><span class="HTitleText2">Access to Records</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-471814"><span class="HTitleText2">Disclosure of Information in a Record</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-471858"><span class="HTitleText2">Disposition or Destruction of Records and Prohibition on Use and Disclosure</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-471880"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-471881"><span class="HTitleText2">Disqualification of Judge</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-471887"><span class="HTitleText2">Substitution of Judge</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-471895"><span class="HTitleText2">Exclusion from Hearing</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-471918"><span class="HTitleText2">Transfer of Charges</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-471923"><span class="HTitleText2">Forfeiture of Recognizances</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-471943"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-471973"><span class="HTitleText2">Application of Criminal Code</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-472022"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-472032"><span class="HTitleText2">Evidence</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-472112"><span class="HTitleText2">Forms, Regulations and Rules of Court</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-472123"><span class="HTitleText2">Agreements with Provinces</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-472126"><span class="HTitleText2">Programs</span></a>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="#h-472132"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>166 to 198 - </span><a href="#h-472178"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Consequential Amendments, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 to 198 - </span><a href="#h-472179"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-472181"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-472183"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-472187"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

