<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la saisie-arrêt et la distraction de pensions</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-241319"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-241324"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Procédure en matière de saisie-arrêt</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-241325"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-241334"><span class="HTitleText2">Saisie-arrêt</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-241339"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Ministères et certaines sociétés d’État</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-241417"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Sociétés d’État non visées par la section I</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-241427"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-241432"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Entités parlementaires</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-241512"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="page-3.html#h-241531"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Distraction de prestations de pension pour l’exécution d’ordonnances de soutien financier</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-3.html#h-241532"><span class="HTitleText2">Application de la présente partie</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-241537"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-241567"><span class="HTitleText2">Conditions de la distraction de prestations de pension</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-241621"><span class="HTitleText2">Montant des versements</span></a>
</li>
<li><span class='sectionRange'>40.2 - </span><a href="page-4.html#h-241683"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-4.html#h-1160579"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="page-5.html#h-241727"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

