<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’accord définitif concernant la Première Nation de Tsawwassen</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-448795"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-448798"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-448808"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-448821"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-448824"><span class="HTitleText1">Terres</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-448827"><span class="HTitleText1">Fiscalité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-448832"><span class="HTitleText1">Pêches</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-448837"><span class="HTitleText1">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-448847"><span class="HTitleText1">Application de lois de la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-448850"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-448876"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-448895"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-448896"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-448898"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des terres des premières nations</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-448900"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pêches</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-448902"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-448904"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-448906"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-448909"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
