<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les paiements de péréquation compensatoires supplémentaires à la Nouvelle-Écosse et à Terre-Neuve-et-Labrador</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-358867"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-358870"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-358876"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-358879"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Paiements de péréquation compensatoires supplémentaires à la Nouvelle-Écosse</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-358940"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Paiements de péréquation compensatoires supplémentaires à Terre-Neuve-et-Labrador</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-359008"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
