<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le tabac</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Produits du tabac</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Accès</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Étiquetage</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Promotion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-9"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-10"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-11"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-12"><span class="HTitleText2">Saisie et restitution</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-13"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>42.1 - </span><a href="#h-14"><span class="HLabel1">PARTIE V.1</span> - <span class="HTitleText1">Dépôt des projets de règlement</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-15"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-16"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>61 à 63 - </span><a href="#h-17"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Modifications connexes, abrogations et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 à 63 - </span><a href="#h-18"><span class="HTitleText2">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>64 et 65 - </span><a href="#h-19"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-20"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
