<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Health Care, Early Childhood Development and Other Social Services Funding Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-146155"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-146158"><span class="HTitleText1">Medical Equipment Trust</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-146164"><span class="HTitleText1">Funding for Health Information and Communications Technologies</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-146167"><span class="HTitleText1">Payment Out of Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>5 and 6 - </span><a href="#h-146170"><span class="HTitleText1">Amendments to the Federal-Provincial Fiscal Arrangements Act</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
