<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Cape Breton Development Corporation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-78783"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-78788"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-78802"><span class="HTitleText1">Corporation Established</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-78834"><span class="HTitleText1">Organization and Staff</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-78843"><span class="HTitleText1">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-78860"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-1.html#h-78868"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-1.html#h-78902"><span class="HTitleText1">Repeal</span></a>
</li></ul>
</li></ul>

</nav>

