<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le règlement des revendications relatives aux terres retranchées des réserves des Indiens de la Colombie-Britannique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-32845"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-32848"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-32858"><span class="HTitleText1">Conventions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-32872"><span class="HTitleText1">Disposition générale</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
