<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Judges Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-336688"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-336693"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-336712"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Judges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-336713"><span class="HTitleText2">Eligibility</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-336724"><span class="HTitleText2">Age of Retirement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-336734"><span class="HTitleText2">Salaries</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-336884"><span class="HTitleText2">Periodic Adjustment and Revision of Salaries</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-336989"><span class="HTitleText2">Allowances for Incidental, Non-accountable and Representational Expenses</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-337020"><span class="HTitleText2">Supernumerary Judges</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-337056"><span class="HTitleText2">Chief Justice Continuing as Judge</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-337097"><span class="HTitleText2">Early Notice</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-337105"><span class="HTitleText2">Travel and Other Allowances</span></a>
</li>
<li><span class='sectionRange'>41.1 - </span><a href="#h-337180"><span class="HTitleText2">Special Retirement Provision — Supreme Court of Canada Judges</span></a>
</li>
<li><span class='sectionRange'>41.2 - </span><a href="#h-337193"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-337251"><span class="HTitleText2">Annuities for Judges</span></a>
</li>
<li><span class='sectionRange'>43.1 - </span><a href="#h-337286"><span class="HTitleText2">Prorated Annuities — Early Retirement</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-337310"><span class="HTitleText2">Annuities for Survivors</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="#h-337380"><span class="HTitleText2">Lump Sum Payment</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-337385"><span class="HTitleText2">Annuities for Surviving Children</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-337413"><span class="HTitleText2">Regulations concerning Inheritance Taxes</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-337418"><span class="HTitleText2">Judges’ Contributions toward Annuities</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-337464"><span class="HTitleText2">Diversion Under Financial Support Order</span></a>
</li>
<li><span class='sectionRange'>52.1 - </span><a href="#h-337472"><span class="HTitleText2">Division of Judge’s Annuity Benefits on Conjugal Breakdown</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-337640"><span class="HTitleText2">Payment of Salaries, Allowances, Annuities and Other Amounts</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-337654"><span class="HTitleText2">Absence from Judicial Duties</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-337671"><span class="HTitleText2">Extra-judicial Employment</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-337698"><span class="HTitleText2">Extra Remuneration</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="#h-337708"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Canadian Judicial Council</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-337709"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-337712"><span class="HTitleText2">Constitution of the Council</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-337753"><span class="HTitleText2">Inquiries concerning Judges</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-337775"><span class="HTitleText2">Report and Recommendations</span></a>
</li>
<li><span class='sectionRange'>65.1 - </span><a href="#h-1310063"><span class="HTitleText2">Annuity Calculations</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-337788"><span class="HTitleText2">Effect of Inquiry</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-337799"><span class="HTitleText2">Inquiries concerning Other Persons</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-337812"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-337817"><span class="HTitleText2">Removal by Parliament or Governor in Council</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="#h-337822"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Administration of Federal Judicial Affairs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-337823"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-337828"><span class="HTitleText2">Commissioner for Federal Judicial Affairs</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-337844"><span class="HTitleText2">Registrar of the Supreme Court of Canada</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-337853"><span class="HTitleText2">Commissioner’s Staff</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

