<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Health Agency of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Public Health Agency of Canada</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">Chief Public Health Officer</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText1">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2"><cite class="XRefExternalAct">Quarantine Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
