<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend the Bills of Exchange Act, the Interpretation Act and the Canada Labour Code (National Day for Truth and Reconciliation)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1294198"><span class="HTitleText1">Purpose of this Act</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1294201"><span class="HTitleText1">Bills of Exchange Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1294206"><span class="HTitleText1">Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1294211"><span class="HTitleText1">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1294218"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

