<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Hazardous Products Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">[Repealed, 2010, c. 21, s. 73]</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-4"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Hazardous Products</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-5"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>14.3 - </span><a href="#h-7"><span class="HTitleText2">Preparing and Maintaining Documents</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-9"><span class="HTitleText2">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText2">Amendments to Schedules 1 and 2</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Consultation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Tests, Studies and Compilation of Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText2">Inspectors and Analysts</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HTitleText2">Inspection and Analysis</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-16"><span class="HTitleText2">Dealing with Seized Things</span></a>
</li>
<li><span class='sectionRange'>26.1 - </span><a href="#h-17"><span class="HTitleText2">Orders for Taking Measures</span></a>
</li>
<li><span class='sectionRange'>26.2 - </span><a href="#h-18"><span class="HTitleText2">Review of Orders for Taking Measures</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-19"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-20"><span class="HTitleText2">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-21"><span class="HTitleText2">Offence, Punishment and Procedure</span></a>
</li></ul>
</li><li><a href="#h-254717"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Non-Application of Part II</span></a>
</li>
<li><a href="#h-254727"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Hazard Classes</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
