<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Firearms Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-223059"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-223062"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-223111"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-223117"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-223131"><span class="HTitleText1">Authorized Possession</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-223132"><span class="HTitleText2">Eligibility to Hold Licences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-223133"><span class="HTitleText3">General Rules</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-223188"><span class="HTitleText3">Special Cases — Persons</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-223226"><span class="HTitleText3">Special Cases — Prohibited Firearms, Weapons, Devices and Ammunition</span></a>
</li></ul>
</li><li><span class='sectionRange'>12.1 - </span><a href="#h-223283"><span class="HTitleText2">Registration Certificates</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-223301"><span class="HTitleText1">Authorized Transportation of Firearms</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-223346"><span class="HTitleText1">Authorized Transfers and Lending</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-223347"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-223354"><span class="HTitleText2">Authorized Transfers</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-223464"><span class="HTitleText2">Authorized Lending</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-223479"><span class="HTitleText1">Authorized Exportation and Importation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-223480"><span class="HTitleText2">Individuals</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-223517"><span class="HTitleText2">Businesses</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-223529"><span class="HTitleText1">Licences, Registration Certificates and Authorizations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-223530"><span class="HTitleText2">Applications</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-223551"><span class="HTitleText2">Issuance</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-223601"><span class="HTitleText2">Term</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-223680"><span class="HTitleText2">Refusal to Issue and Revocation</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-223726"><span class="HTitleText2">References to Provincial Court Judge</span></a>
</li>
<li><span class='sectionRange'>76.1 - </span><a href="#h-223752"><span class="HTitleText2">Appeals to Superior Court and Court of Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>81.1 - </span><a href="#h-223792"><span class="HTitleText1">Commissioner of Firearms</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-223813"><span class="HTitleText1">Canadian Firearms Registration System</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-223814"><span class="HTitleText2">Registrar of Firearms</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-223823"><span class="HTitleText2">Records of the Registrar</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-223858"><span class="HTitleText2">Records of Chief Firearms Officers</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-223872"><span class="HTitleText2">Reporting of Prohibition Orders</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-223875"><span class="HTitleText2">Access to Records</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-223882"><span class="HTitleText2">Electronic Filing</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-223897"><span class="HTitleText2">Reports</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-223909"><span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-223910"><span class="HTitleText2">Agreements with Provinces</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-223915"><span class="HTitleText2">Other Matters</span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-223931"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-223940"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-223986"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-224023"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-224112"><span class="HTitleText1">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-224113"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-224190"><span class="HTitleText2">Registration Certificates</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-224204"><span class="HTitleText2">Authorized Transportation of Firearms</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 and 137 - </span><a href="#h-224252"><span class="HTitleText1">Conditional Amendments to this Act</span></a>
</li>
<li><span class='sectionRange'>138 and 139 - </span><a href="#h-224254"><span class="HTitleText1">Amendments to the Criminal Code</span></a>
</li>
<li><span class='sectionRange'>140 to 157 - </span><a href="#h-224256"><span class="HTitleText1">Related and Consequential Amendments to the Criminal Code</span></a>
</li>
<li><span class='sectionRange'>158 to 168 - </span><a href="#h-224258"><span class="HTitleText1">Related and Consequential Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>188 to 192 - </span><a href="#h-224262"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-224264"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
