<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Arts Centre Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-374033"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-374038"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-374050"><span class="HTitleText1">Corporation Established</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-374055"><span class="HTitleText1">Members of the Board</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-374074"><span class="HTitleText1">President</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-374091"><span class="HTitleText1">Officers and Employees</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-374096"><span class="HTitleText1">Objects and Powers of the Corporation</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-374127"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-374147"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-374152"><span class="HTitleText1">Report to Parliament</span></a>
</li></ul>
</li></ul>

</nav>

