<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’accord concernant la Banque asiatique d’investissement dans les infrastructures</a><ul class="TocIndent"><li><a href="page-2.html#h-5097"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Statuts de la Banque Asiatique d’Investissement dans les Infrastructures</span> - <span class="scheduleTitleText"> -  </span></a>
</li></ul>
</li></ul>

</nav>

