<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon Placer Mining Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Disposition of Crown Placer Mining Rights</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-5"><span class="HTitleText2">Right to Acquire Claims</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HTitleText2">Size, Form, etc., of Claims</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-7"><span class="HTitleText2">Locating and Recording</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-8"><span class="HTitleText2">Surveys</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-9"><span class="HTitleText2">Title</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-10"><span class="HTitleText2">Grouping</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-11"><span class="HTitleText2">Water Rights</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-12"><span class="HTitleText2">Drainage</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-13"><span class="HTitleText2">Disputes</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-14"><span class="HTitleText2">Administration of Estates</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-15"><span class="HTitleText2">Taxation and Fees</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-16"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-17"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Land Use and Reclamation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-18"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-19"><span class="HTitleText2">Purpose of Part</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-20"><span class="HTitleText2">Placer Land Use Operations</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-21"><span class="HTitleText2">Applications</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-22"><span class="HTitleText2">Security</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-23"><span class="HTitleText2">Inspector’s Power to Amend Class II Land Use Operations</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-24"><span class="HTitleText2">Amendment and Renewal of Operating Plans</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-25"><span class="HTitleText2">Assignment</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-26"><span class="HTitleText2">Inspection and Enforcement</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-27"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-28"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><a href="#h-29"><span class="scheduleLabel">SCHEDULE I</span></a>
</li>
<li><a href="#h-30"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Fees</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
