<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le poinçonnage des métaux précieux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-387371"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-387376"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-387401"><span class="HTitleText1">Poinçonnage</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-387424"><span class="HTitleText1">Marques nationales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-387432"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-387463"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-387477"><span class="HTitleText1">Infractions et peines</span></a>
</li></ul>
</li></ul>

</nav>

