<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget de 2000</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-34885"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 à 6 - </span><a href="page-1.html#h-34888"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Assurance-emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 à 6 - </span><a href="page-1.html#h-34889"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 à 6 - </span><a href="page-1.html#h-34890"><span class="HTitleText3">Modifications générales</span></a>
</li>
<li><span class='sectionRange'>7 à 9 - </span><a href="page-1.html#h-34892"><span class="HTitleText3">Dispositions provisoires</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-34895"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>12 à 15 - </span><a href="page-1.html#h-34898"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Transfert canadien en matière de santé et de programmes sociaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 à 15 - </span><a href="page-1.html#h-34899"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 à 21 - </span><a href="page-1.html#h-34903"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Aide financière aux étudiants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 à 21 - </span><a href="page-1.html#h-34904"><span class="HTitleText2">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-1.html#h-34908"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Taxe de vente des premières nations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-1.html#h-34909"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>30 à 33 - </span><a href="page-1.html#h-34983"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-1.html#h-34985"><span class="HTitleText2">Modification conditionnelle</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 et 36 - </span><a href="page-1.html#h-34987"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>37 à 41 - </span><a href="page-1.html#h-34989"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-1.html#h-34991"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Modifications apportées à d’autres lois</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-1.html#h-34992"><span class="HTitleText2">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-1.html#h-34997"><span class="HTitleText2">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-1.html#h-35004"><span class="HTitleText2">Loi sur les mesures spéciales d’importation</span></a>
</li></ul>
</li><li><a href="page-2.html#h-35007"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Taxe sur certaines fournitures</span></a>
</li></ul>
</li></ul>

</nav>

