<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nelson House First Nation Flooded Land Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-364412"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-364415"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-364430"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-364440"><span class="HTitleText1">Claims</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-364451"><span class="HTitleText1">Arbitration</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
