<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Remote Sensing Space Systems Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-426985"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-426988"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-427013"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-427016"><span class="HTitleText1">Application of Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-427027"><span class="HTitleText1">Operation of Remote Sensing Space Systems</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-427028"><span class="HTitleText2">Requirement for Licence</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-427037"><span class="HTitleText2">Applications, Licences and Related Matters</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-427095"><span class="HTitleText2">Amendment, Suspension and Cancellation of Licences</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-427123"><span class="HTitleText2">Interruptions of Service</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-427135"><span class="HTitleText2">Priority Access</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-427156"><span class="HTitleText2">Transfer of Remote Sensing Satellites</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-427164"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-427194"><span class="HTitleText1">Requests for Information</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-427204"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-427238"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-427256"><span class="HTitleText1">No Liability</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-427262"><span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-427263"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-427266"><span class="HTitleText2">Enforcement Officers</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-427274"><span class="HTitleText2">Notices of Violation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-427292"><span class="HTitleText2">Determination of Responsibility and Penalty</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-427293"><span class="HTitleText3">Payment of Penalty</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-427296"><span class="HTitleText3">Making Representations</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-427311"><span class="HTitleText3">Responsibility</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-427314"><span class="HTitleText2">Appeal to Minister</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-427320"><span class="HTitleText2">Rules about Violations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-427336"><span class="HTitleText2">Recovery of Penalties and Amounts</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-427349"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="#h-427381"><span class="HTitleText1">Review and Report</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-427387"><span class="HTitleText1">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-427389"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

