<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to amend certain Acts in relation to pensions and to enact the Special Retirement Arrangements Act and the Pension Benefits Division Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 to 31 - </span><a href="#h-402858"><span class="HTitleText1">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>32 to 59 - </span><a href="#h-402860"><span class="HTitleText1">Canadian Forces Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>60 to 80 - </span><a href="#h-402862"><span class="HTitleText1">Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-402864"><span class="HTitleText1">Members of Parliament Retiring Allowances Act</span></a>
</li>
<li><span class='sectionRange'>82 to 105 - </span><a href="#h-402866"><span class="HTitleText1">Amendments to Other Acts, Enactment of Schedules, Transitional and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 to 105 - </span><a href="#h-402867"><span class="HTitleText2">Amendments to other Acts</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-402869"><span class="HTitleText2">Enactment of Schedules</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-402874"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-402877"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-402886"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-402888"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
