<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur l’évaluation environnementale (2012)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-60931"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-60934"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-60989"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-60992"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-61007"><span class="HTitleText1">Effets environnementaux</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-61036"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-61047"><span class="HTitleText1">Examen préalable</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-61070"><span class="HTitleText1">Évaluation environnementale obligatoire</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-61094"><span class="HTitleText1">Évaluation environnementale des projets désignés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-61095"><span class="HTitleText2">Autorité responsable</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-61104"><span class="HTitleText2">Début de l’évaluation environnementale</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-61107"><span class="HTitleText2">Consultation et coopération avec certaines instances</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-61110"><span class="HTitleText2">Éléments à examiner</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-61130"><span class="HTitleText2">Obligation des autorités fédérales</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-61137"><span class="HTitleText2">Évaluation environnementale effectuée par l’autorité responsable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-61138"><span class="HTitleText3">Règles générales</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-61179"><span class="HTitleText3">Article 54 de la Loi sur l’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-61226"><span class="HTitleText3">Substitution</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-61257"><span class="HTitleText3">Évaluations équivalentes</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-61268"><span class="HTitleText2">Évaluation environnementale renvoyée pour examen par une commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-61269"><span class="HTitleText3">Règles générales</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-61367"><span class="HTitleText3">Règles en cas d’arrêt de l’examen</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-61382"><span class="HTitleText2">Prise de décisions</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-61409"><span class="HTitleText2">Déclaration</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-61437"><span class="HTitleText2">Programmes d’aide financière</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-61447"><span class="HTitleText2">Recouvrement des coûts</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-61461"><span class="HTitleText2">Arrêt de l’évaluation environnementale</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-61472"><span class="HTitleText2">Renseignements confidentiels</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="#h-61475"><span class="HTitleText1">Fonctions de certaines autorités relativement aux projets</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-61516"><span class="HTitleText1">Études régionales</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-61535"><span class="HTitleText1">Registre canadien d’évaluation environnementale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-61536"><span class="HTitleText2">Établissement du registre</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-61544"><span class="HTitleText2">Site Internet</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-61571"><span class="HTitleText2">Dossiers de projet</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-61585"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-61599"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-61661"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-61662"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-61668"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-61702"><span class="HTitleText2">Ordres</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-61714"><span class="HTitleText2">Injonction</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-61722"><span class="HTitleText2">Interdictions et infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-61751"><span class="HTitleText1">Agence canadienne d’évaluation environnementale</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-61811"><span class="HTitleText1">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-61817"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><a href="#h-46"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Autorités fédérales</span></a>
</li>
<li><a href="#h-61919"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Composantes de l’environnement</span></a>
</li>
<li><a href="#h-61921"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Organismes</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
