<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’enregistrement des organismes de bienfaisance (renseignements de sécurité)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-78049"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-78052"><span class="HTitleText1">Objet et principes</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-78060"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-78070"><span class="HTitleText1">Certificat</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-78081"><span class="HTitleText1">Examen judiciaire du certificat</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-78130"><span class="HTitleText1">Révision du certificat</span></a>
</li></ul>
</li></ul>

</nav>

