<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Time Limits and Other Periods Act (COVID-19)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1257367"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1257370"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1257380"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1257388"><span class="HTitleText1">Time Limits Related to Proceedings</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-1257401"><span class="HTitleText1">Other Time Limits and Periods</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-1257429"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-1257434"><span class="HTitleText1">Transparency and Parliamentary Oversight</span></a>
</li>
<li><a href="#h-1257446"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

