<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Wages Liability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-464650"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-464655"><span class="HTitleText1">Public Works</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-464664"><span class="HTitleText1">Subsidized Works</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-464672"><span class="HTitleText1">Works by Chartered Companies</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-464688"><span class="HTitleText1">Offences and Punishment</span></a>
</li></ul>
</li></ul>

</nav>

