<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Kanesatake Interim Land Base Governance Act</a><ul class="TocIndent"><li><span class='sectionRange'>24 - </span><a href="#h-338302"><span class="HTitleText1">Amendment to Canada Lands Surveys Act</span></a>
</li>
<li><a href="#h-338305"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Kanesatake Mohawk Interim Land Base</span></a>
</li></ul>
</li></ul>

</nav>

