<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–United Kingdom Trade Continuity Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1288229"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1288232"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-1288248"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-1288251"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-1288263"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-1288271"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-1288272"><span class="HTitleText2">Approval and Representation on the Canada–U.K. Joint Committee</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-1288277"><span class="HTitleText2">Tribunals, Arbitration Panels and Panels of Experts</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-1288291"><span class="HTitleText2">Expenses</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-1288297"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-1288307"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments and Transitional Provision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-1288308"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-1288309"><span class="HTitleText3"><cite class="XRefExternalAct">Export and Import Permits Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-1288321"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-1288326"><span class="HTitleText3"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-1288332"><span class="HTitleText3"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-1288340"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-1.html#h-1288355"><span class="HTitleText3"><cite class="XRefExternalAct">Commercial Arbitration Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-1.html#h-1288359"><span class="HTitleText3"><cite class="XRefExternalAct">Coasting Trade Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-1.html#h-1288383"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>50 - </span><a href="page-1.html#h-1288427"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-1.html#h-1288432"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coordinating Amendment and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-1.html#h-1288433"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-1.html#h-1288437"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-2.html#h-1288444"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-3.html#h-1288450"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-4.html#h-1288457"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

