<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve-et-Labrador</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-148918"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-148923"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-148955"><span class="HTitleText1">Fixation des limites et règlement des litiges</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-148980"><span class="HTitleText1">Approbation préalable des règlements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-148988"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-148996"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Cogestion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-148997"><span class="HTitleText2">Constitution de l’Office</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-149095"><span class="HTitleText2">Attributions de l’Office</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-149106"><span class="HTitleText2">Fonctionnement</span></a>
</li>
<li><span class='sectionRange'>29.1 - </span><a href="#h-149192"><span class="HTitleText2">Recouvrement des coûts</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-149215"><span class="HTitleText2">Décisions portant sur la gestion extracôtière</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-149275"><span class="HTitleText2">Sécurité des approvisionnements régionaux</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-149299"><span class="HTitleText2">Instructions ministérielles</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-149320"><span class="HTitleText2">Exposés relatifs aux titres</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-149330"><span class="HTitleText2">Enquêtes publiques</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="#h-149346"><span class="HTitleText2">Audiences publiques</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-149367"><span class="HTitleText2">Plan de retombées économiques</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-149387"><span class="HTitleText2">Coordination administrative</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-149402"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Hydrocarbures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-149403"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-149424"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-149425"><span class="HTitleText3">Modalités des avis</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-149430"><span class="HTitleText3">Obligation</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-149433"><span class="HTitleText3">Nominations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-149450"><span class="HTitleText3">Dispositions générales sur les titres</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="#h-149474"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Dispositions générales sur l’octroi des titres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="#h-149475"><span class="HTitleText3">Pouvoir général</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-149485"><span class="HTitleText3">Titres sur des réserves de l’État</span></a>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-149533"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Prospection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-149534"><span class="HTitleText3">Permis de prospection</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-149567"><span class="HTitleText3">Découvertes importantes</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-149583"><span class="HTitleText3">Attestation de découverte importante</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-149609"><span class="HTitleText3">Arrêtés de forage</span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-149628"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-149629"><span class="HTitleText3">Découvertes exploitables</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-149639"><span class="HTitleText3">Arrêtés de mise en valeur</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-149653"><span class="HTitleText3">Licences de production</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-149695"><span class="HTitleText3">Licences de stockage souterrain</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-149701"><span class="HTitleText3">Critère d’obtention</span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="#h-149706"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">[Abrogée, 1993, ch. 47, art. 8]</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-149707"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Redevances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97 - </span><a href="#h-149708"><span class="HTitleText3">Levée des redevances</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-149750"><span class="HTitleText3">Assujettissement et recouvrement</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-149753"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Fonds renouvelables pour l’étude de l’environnement</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-149763"><span class="HLabel2">SECTION VIII</span> - <span class="HTitleText2">Transferts, cessions et enregistrement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-149764"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-149787"><span class="HTitleText3">Transferts et cessions</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-149791"><span class="HTitleText3">Enregistrement</span></a>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="#h-149899"><span class="HLabel2">SECTION IX</span> - <span class="HTitleText2">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="#h-149900"><span class="HTitleText3">Renseignements</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-149991"><span class="HTitleText3">Arbitrage</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-150010"><span class="HTitleText3">Annulation des titres</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-150018"><span class="HTitleText3">Audiences et révision</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-150044"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-150063"><span class="HLabel2">SECTION X</span> - <span class="HTitleText2">Dispositions transitoires, corrélatives et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-150064"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="#h-150117"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Opérations pétrolières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-150118"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-150131"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-150141"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>136.1 - </span><a href="#h-150146"><span class="HTitleText2">Conseil d’harmonisation</span></a>
</li>
<li><span class='sectionRange'>136.2 - </span><a href="#h-150151"><span class="HTitleText2">Conseil des normes extracôtières de formation</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-150156"><span class="HTitleText2">Interdiction</span></a>
</li>
<li><span class='sectionRange'>137.1 - </span><a href="#h-150164"><span class="HTitleText2">Délégation</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-150169"><span class="HTitleText2">Permis et autorisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-150170"><span class="HTitleText3">Permis et autorisations de travaux</span></a>
</li>
<li><span class='sectionRange'>138.2 - </span><a href="#h-150228"><span class="HTitleText3">Sécurité des activités</span></a>
</li>
<li><span class='sectionRange'>138.21 - </span><a href="#h-150233"><span class="HTitleText3">Agents de traitement</span></a>
</li>
<li><span class='sectionRange'>138.3 - </span><a href="#h-150238"><span class="HTitleText3">Exigences financières</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-150243"><span class="HTitleText3">Autorisation de plans de mise en valeur</span></a>
</li>
<li><span class='sectionRange'>139.1 - </span><a href="#h-150259"><span class="HTitleText3">Déclarations</span></a>
</li>
<li><span class='sectionRange'>139.2 - </span><a href="#h-150272"><span class="HTitleText3">Certificats</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-150294"><span class="HTitleText2">Délégué à la sécurité et délégué à l’exploitation</span></a>
</li>
<li><span class='sectionRange'>140.1 - </span><a href="#h-150299"><span class="HTitleText2">Dérogation à la loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>140.2 - </span><a href="#h-150304"><span class="HTitleText2">Essais d’écoulement prolongés</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-150314"><span class="HTitleText2">Comité des hydrocarbures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-150315"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-150347"><span class="HTitleText3">Compétence et attributions</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-150362"><span class="HTitleText3">Exécution</span></a>
</li></ul>
</li><li><span class='sectionRange'>149 - </span><a href="#h-150372"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Réglementation de l’exploitation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="#h-150373"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-150434"><span class="HTitleText3">Arrêtés de production</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-150446"><span class="HTitleText3">Gaspillage</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-150499"><span class="HTitleText3">Rejets et débris</span></a>
</li>
<li><span class='sectionRange'>164.1 - </span><a href="#h-1115179"><span class="HTitleText3">Tarification des émissions de gaz à effet de serre</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-150666"><span class="HTitleText3">Enquêtes</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-150682"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Accords de production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-150706"><span class="HTitleText3">Mise en commun</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-150749"><span class="HTitleText3">Union</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-150770"><span class="HTitleText3">Union obligatoire</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-150835"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>184 - </span><a href="#h-150846"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Appels et mesures de contrainte</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>184 - </span><a href="#h-150847"><span class="HTitleText3">Appels</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-150873"><span class="HTitleText3">Agents de la sécurité et du contrôle de l’exploitation</span></a>
</li>
<li><span class='sectionRange'>193.2 - </span><a href="#h-151025"><span class="HTitleText3">Chargé de projet</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-151038"><span class="HTitleText3">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>202.01 - </span><a href="#h-151164"><span class="HTitleText3">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>202.01 - </span><a href="#h-151165"><span class="HTitleText4">Attributions</span></a>
</li>
<li><span class='sectionRange'>202.03 - </span><a href="#h-151189"><span class="HTitleText4">Violations</span></a>
</li>
<li><span class='sectionRange'>202.07 - </span><a href="#h-151218"><span class="HTitleText4">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>202.2 - </span><a href="#h-151241"><span class="HTitleText4">Révision</span></a>
</li>
<li><span class='sectionRange'>202.7 - </span><a href="#h-151274"><span class="HTitleText4">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>202.9 - </span><a href="#h-151283"><span class="HTitleText4">Recouvrement des pénalités</span></a>
</li>
<li><span class='sectionRange'>202.92 - </span><a href="#h-151298"><span class="HTitleText4">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-151307"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-151310"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-151315"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>205.001 - </span><a href="#h-151321"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Santé et sécurité au travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>205.001 - </span><a href="#h-151322"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>205.002 - </span><a href="#h-151377"><span class="HTitleText2">Obligation</span></a>
</li>
<li><span class='sectionRange'>205.003 - </span><a href="#h-151382"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>205.009 - </span><a href="#h-151419"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>205.01 - </span><a href="#h-151429"><span class="HTitleText2">Répartition de la responsabilité</span></a>
</li>
<li><span class='sectionRange'>205.011 - </span><a href="#h-151439"><span class="HTitleText2">Obligations de l’exploitant</span></a>
</li>
<li><span class='sectionRange'>205.018 - </span><a href="#h-151539"><span class="HTitleText2">Obligations de l’employeur</span></a>
</li>
<li><span class='sectionRange'>205.024 - </span><a href="#h-151624"><span class="HTitleText2">Obligations du superviseur</span></a>
</li>
<li><span class='sectionRange'>205.026 - </span><a href="#h-151637"><span class="HTitleText2">Obligations de l’employé</span></a>
</li>
<li><span class='sectionRange'>205.03 - </span><a href="#h-151663"><span class="HTitleText2">Obligations du fournisseur</span></a>
</li>
<li><span class='sectionRange'>205.034 - </span><a href="#h-151685"><span class="HTitleText2">Obligations du propriétaire, de l’indivisaire et des dirigeants</span></a>
</li>
<li><span class='sectionRange'>205.037 - </span><a href="#h-151709"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>205.043 - </span><a href="#h-151779"><span class="HTitleText2">Comités et coordonnateur</span></a>
</li>
<li><span class='sectionRange'>205.048 - </span><a href="#h-151878"><span class="HTitleText2">Activités de surveillance</span></a>
</li>
<li><span class='sectionRange'>205.049 - </span><a href="#h-151900"><span class="HTitleText2">Rapport sur des préoccupations de santé et de sécurité au travail</span></a>
</li>
<li><span class='sectionRange'>205.05 - </span><a href="#h-151912"><span class="HTitleText2">Droit de refus</span></a>
</li>
<li><span class='sectionRange'>205.056 - </span><a href="#h-152001"><span class="HTitleText2">Employées enceintes ou qui allaitent</span></a>
</li>
<li><span class='sectionRange'>205.059 - </span><a href="#h-152041"><span class="HTitleText2">Représailles et plaintes</span></a>
</li>
<li><span class='sectionRange'>205.066 - </span><a href="#h-152137"><span class="HTitleText2">Activités de l’Office</span></a>
</li>
<li><span class='sectionRange'>205.068 - </span><a href="#h-152160"><span class="HTitleText2">Autorisation</span></a>
</li>
<li><span class='sectionRange'>205.069 - </span><a href="#h-152170"><span class="HTitleText2">Substitutions</span></a>
</li>
<li><span class='sectionRange'>205.071 - </span><a href="#h-152212"><span class="HTitleText2">Exécution et contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>205.082 - </span><a href="#h-152386"><span class="HTitleText2">Protection du lieu</span></a>
</li>
<li><span class='sectionRange'>205.083 - </span><a href="#h-152397"><span class="HTitleText2">Communication des renseignements</span></a>
</li>
<li><span class='sectionRange'>205.09 - </span><a href="#h-152441"><span class="HTitleText2">Procédures</span></a>
</li>
<li><span class='sectionRange'>205.092 - </span><a href="#h-152455"><span class="HTitleText2">Ordres et décisions</span></a>
</li>
<li><span class='sectionRange'>205.097 - </span><a href="#h-152497"><span class="HTitleText2">Affichage et transmission de certains documents</span></a>
</li>
<li><span class='sectionRange'>205.098 - </span><a href="#h-152515"><span class="HTitleText2">Révision et appels</span></a>
</li>
<li><span class='sectionRange'>205.103 - </span><a href="#h-152574"><span class="HTitleText2">Exécution des ordonnances</span></a>
</li>
<li><span class='sectionRange'>205.104 - </span><a href="#h-152584"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>205.118 - </span><a href="#h-152683"><span class="HTitleText2">Conseil consultatif</span></a>
</li>
<li><span class='sectionRange'>205.119 - </span><a href="#h-152708"><span class="HTitleText2">Vérification et enquête</span></a>
</li>
<li><span class='sectionRange'>205.121 - </span><a href="#h-152741"><span class="HTitleText2">Documents sous forme électronique ou autre</span></a>
</li>
<li><span class='sectionRange'>205.124 - </span><a href="#h-152773"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-152824"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Partage des recettes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-152825"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-152834"><span class="HTitleText2">Taxe à la consommation</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-152852"><span class="HTitleText2">Taxe sur les primes d’assurance</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-152864"><span class="HTitleText2">Accord fiscal</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-152889"><span class="HTitleText2">Imposition des personnes morales</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-152914"><span class="HTitleText2">Assujettissement et recouvrement</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-152917"><span class="HTitleText2">Fonds de recettes</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-152937"><span class="HTitleText2">Compétence des tribunaux</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-152947"><span class="HTitleText2">Règlement</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-152954"><span class="HTitleText2">Affectation</span></a>
</li></ul>
</li><li><span class='sectionRange'>218 - </span><a href="#h-152957"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">[Abrogée, 2015, ch. 4, art. 69]</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-152969"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">[Abrogée, 2015, ch. 4, art. 69]</span></a>
</li>
<li><span class='sectionRange'>234 et 235 - </span><a href="#h-152976"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Impôt des personnes morales</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-152978"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Dispositions transitoires et corrélatives et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>236 - </span><a href="#h-152979"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>237 et 238 - </span><a href="#h-152984"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-152986"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-152995"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-153005"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Dispositions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
