<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Income Tax Conventions Implementation Act, 1999</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-326725"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-326728"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada — Kyrgyzstan Income Tax Agreement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-326744"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Canada — Lebanon Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-326760"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Canada — Algeria Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-326776"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Canada — Bulgaria Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-326792"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Canada — Portugal Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-326808"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Canada — Uzbekistan Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-326824"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Canada — Jordan Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-326840"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Canada — Japan Income Tax Convention</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-326841"><span class="HTitleText2">Canada-Japan Income Tax Convention Act, 1986</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-326843"><span class="HTitleText2">An Act to implement conventions between Canada and the Kingdom of the Netherlands and Canada and Japan and agreements between Canada and the People’s Republic of China and Canada and the Republic of Malta for the avoidance of double taxation with respect to income tax</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-326849"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Canada — Luxembourg Income Tax Convention</span></a>
</li>
<li><a href="#h-326868"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-327178"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-327480"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-327779"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-328081"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="#h-328395"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li>
<li><a href="#h-328677"><span class="scheduleLabel">SCHEDULE 7</span> </a>
</li>
<li><a href="#h-328950"><span class="scheduleLabel">SCHEDULE 8</span> </a>
</li>
<li><a href="#h-328953"><span class="scheduleLabel">SCHEDULE 9</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
