<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Physical Activity and Sport Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-392630"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-392633"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-392636"><span class="HTitleText1">Policies</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-392649"><span class="HTitleText1">Objects and Mandate</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-392670"><span class="HTitleText1">Agreements and Arrangements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-392678"><span class="HTitleText1">Sport Dispute Resolution Centre of Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-392679"><span class="HTitleText2">Establishment of Centre</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-392695"><span class="HTitleText2">Mission and Powers</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-392716"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-392760"><span class="HTitleText2">Chairperson</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-392767"><span class="HTitleText2">Executive Director</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-392776"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-392783"><span class="HTitleText2">Audit</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-392802"><span class="HTitleText2">Arbitrators and Mediators</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-392808"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-392849"><span class="HTitleText2">Corporate Plan and Annual Report</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-392883"><span class="HTitleText2">Dissolution</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-392895"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-392901"><span class="HTitleText1">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-392902"><span class="HTitleText2">Department of Canadian Heritage Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-392904"><span class="HTitleText1">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-392906"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-392908"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

