<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’accord définitif concernant les Tlaamins</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-438264"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-438267"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-438277"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-438290"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-438293"><span class="HTitleText1">Terres</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-438296"><span class="HTitleText1">Fiscalité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-438301"><span class="HTitleText1">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-438315"><span class="HTitleText1">Application de lois de la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-438318"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-438344"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-438345"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-438347"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pêches</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-438349"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-438351"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-438353"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des terres des premières nations</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-438355"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal des revendications particulières</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-438357"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

