<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection de l’assurance hypothécaire résidentielle</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Assureurs hypothécaires agréés</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText1">Protection d’assurance hypothécaire</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-6"><span class="HTitleText1">Plafond des prêts protégés</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-7"><span class="HTitleText1">Examen et rapport</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-8"><span class="HTitleText1">Peines</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-9"><span class="HTitleText1">Procédures judiciaires</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-10"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-11"><span class="HTitleText1">Résiliation des accords</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
