<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Public Sector Equitable Compensation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-402034"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-402037"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-402070"><span class="HTitleText1">Obligation to Provide Equitable Compensation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-402076"><span class="HTitleText1">Equitable Compensation Assessment</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-402098"><span class="HTitleText1">Employers with Non-unionized Employees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-402099"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-402142"><span class="HTitleText2">Complaints</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-2.html#h-402160"><span class="HTitleText1">Employers with Unionized Employees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-2.html#h-402161"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-402180"><span class="HTitleText2">Arbitration</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-402200"><span class="HTitleText2">Conciliation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-402211"><span class="HTitleText2">Ratification</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-402216"><span class="HTitleText2">Complaints</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-2.html#h-402230"><span class="HTitleText1">Federal Public Sector Labour Relations and Employment Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-2.html#h-402231"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-402247"><span class="HTitleText2">Complaints Filed by Non-unionized Employees</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-402271"><span class="HTitleText2">Complaints Filed by Unionized Employees</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-402305"><span class="HTitleText2">Costs</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-3.html#h-402308"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-402315"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-402339"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-402349"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-3.html#h-402365"><span class="HTitleText1">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-3.html#h-402366"><span class="HTitleText2">Complaints by Non-unionized Employees</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-3.html#h-402369"><span class="HTitleText2">Taking Effect of Provisions in Respect of Unionized Employees</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-3.html#h-402374"><span class="HTitleText2">First Collective Agreement After Taking Effect</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

