<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada-United States Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-58875"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-58878"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-58892"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-58911"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Implementation of Agreement Generally</span></a>
</li>
<li><span class='sectionRange'>23 to 45 - </span><a href="page-1.html#h-58942"><span class="HLabel1">PART II</span> - <span class="HTitleText1">[Repealed, 1995, c. 29, s. 18]</span></a>
</li>
<li><span class='sectionRange'>23 to 45 - </span><a href="page-1.html#h-58943"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Amendments to the Special Import Measures Act</span></a>
</li>
<li><span class='sectionRange'>46 to 148 - </span><a href="page-1.html#h-58945"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Related and Consequential Amendments to Implement the Agreement</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-1.html#h-58947"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Transitional and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="page-1.html#h-58948"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-1.html#h-58951"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-2.html#h-58958"><span class="scheduleLabel"><span class="wb-invisible">Footnote </span><sup>*</sup>SCHEDULE — PART A</span></a>
</li>
<li><a href="page-3.html#h-58960"><span class="scheduleLabel">SCHEDULE — PARTS B AND C</span></a>
</li></ul>
</li></ul>

</nav>

