<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Pope John Paul II Day Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-395520"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-395523"><span class="HTitleText1">Pope John Paul II Day</span></a>
</li></ul>
</li></ul>

</nav>

