<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Student Financial Assistance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-441655"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-441658"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-441679"><span class="HTitleText1">Appropriate Authorities</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-441694"><span class="HTitleText1">Agreements with Lenders</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="#h-441723"><span class="HTitleText1">Government Financing of Student Loans</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-441759"><span class="HTitleText1">Interest-free and Deferral Periods</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="#h-441787"><span class="HTitleText1">Family Physicians, Nurses and Nurse Practitioners in Under-Served Rural or Remote Communities</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="#h-1242089"><span class="HTitleText1">Period — March 30, 2020 to September 30, 2020</span></a>
</li>
<li><span class='sectionRange'>9.4 - </span><a href="#h-1292752"><span class="HTitleText1">Period — April 1, 2021 to March 31, 2022</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-441797"><span class="HTitleText1">Death or Disability of Borrower</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-441820"><span class="HTitleText1">Certificates of Eligibility</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-441850"><span class="HTitleText1">Maximum Amount of Outstanding Student Loans</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-441855"><span class="HTitleText1">Alternative Payments</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-441931"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-441968"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-1204840"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>21 to 27 - </span><a href="#h-442107"><span class="HTitleText1">Amendments to Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-442109"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-442111"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
