<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Farm Products Agencies Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-237660"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-237665"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-237702"><span class="HLabel1">PART I</span> - <span class="HTitleText1">National Farm Products Council</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-237703"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-237730"><span class="HTitleText2">Duties and Powers</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-237771"><span class="HTitleText2">Public Hearings</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-237796"><span class="HTitleText2">Organization</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-237817"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-237822"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Farm Products Marketing Agencies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-237823"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-237857"><span class="HTitleText2">Membership of Agencies</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-237880"><span class="HTitleText2">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-237922"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-237943"><span class="HTitleText2">Financial</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-237959"><span class="HTitleText2">Annual Report</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-237964"><span class="HTitleText2">Agreements</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-237973"><span class="HTitleText2">Inspectors</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-237994"><span class="HTitleText2">Recovery of Debts Due an Agency</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-237999"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-238017"><span class="HTitleText2">Winding-up of Agencies</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-238022"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Farm Products Promotion and Research Agencies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-238023"><span class="HTitleText2">Establishment</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
