<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Centre national des Arts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-365085"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-365090"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-365101"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-365106"><span class="HTitleText1">Membres du conseil</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-365125"><span class="HTitleText1">Président</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-365142"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-365147"><span class="HTitleText1">Mission et pouvoirs de la société</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-365178"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-365198"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-365203"><span class="HTitleText1">Rapport au Parlement</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
