<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la surveillance du secteur énergétique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-214568"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-214573"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-214595"><span class="HTitleText1">Surveillance du secteur énergétique</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-214649"><span class="HTitleText1">Surveillance des négociants en pétrole et en gaz</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-214673"><span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-214674"><span class="HTitleText2">Rapports sur les produits énergétiques et les entreprises énergétiques</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-214682"><span class="HTitleText2">Documents, dossiers et livres de comptabilité</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-214697"><span class="HTitleText2">Divulgation de statistiques et de renseignements</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-214719"><span class="HTitleText2">Exécution</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-214748"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
