<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le statut de l’artiste</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-429864"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-429867"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-429868"><span class="HTitleText2">Déclaration et politique sur le statut de l’artiste</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-1.html#h-429884"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Relations professionnelles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-429885"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-429903"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-429914"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-429917"><span class="HTitleText2">Liberté d’association</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-429920"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-429934"><span class="HTitleText2">Conseil canadien des relations industrielles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-429941"><span class="HTitleText3">Attributions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-429986"><span class="HTitleText3">Critères d’application</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-429993"><span class="HTitleText3">Procédure</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-430018"><span class="HTitleText3">Révision et exécution des décisions et ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-2.html#h-430035"><span class="HTitleText2">Accréditation des associations d’artistes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-2.html#h-430036"><span class="HTitleText3">Conditions préalables à l’accréditation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-430045"><span class="HTitleText3">Associations de producteurs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-430055"><span class="HTitleText3">Procédure d’accréditation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-430070"><span class="HTitleText3">Définition du secteur et détermination de la représentativité</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-430087"><span class="HTitleText3">Accréditation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-430104"><span class="HTitleText3">Annulation de l’accréditation</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-430118"><span class="HTitleText3">Droits et obligations du successeur</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="page-2.html#h-430126"><span class="HTitleText2">Négociations et accords-cadres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-2.html#h-430127"><span class="HTitleText3">Avis de négociation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-430143"><span class="HTitleText3">Durée et effet des accords-cadres</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-430163"><span class="HTitleText3">Contenu et interprétation des accords-cadres</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-3.html#h-430223"><span class="HTitleText3">Précompte obligatoire des cotisations</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-3.html#h-430226"><span class="HTitleText3">Règlement des conflits de travail</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="page-3.html#h-430229"><span class="HTitleText2">Interdictions et recours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="page-3.html#h-430230"><span class="HTitleText3">Moyens de pression</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-3.html#h-430233"><span class="HTitleText3">Déclarations relatives aux moyens de pression</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-3.html#h-430252"><span class="HTitleText3">Pratiques déloyales</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-4.html#h-430319"><span class="HTitleText3">Accords de coproduction</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-4.html#h-430325"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-4.html#h-430330"><span class="HTitleText3">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-4.html#h-430358"><span class="HTitleText3">Preuve</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-4.html#h-430367"><span class="HTitleText3">Dispositions diverses</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>68 à 70 - </span><a href="page-4.html#h-430387"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-4.html#h-430389"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

