<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Société d’assurance-dépôts du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-81276"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-81281"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-81322"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>2.2 - </span><a href="page-1.html#h-81327"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-81332"><span class="HTitleText1">Constitution et fonctionnement de la société</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-81388"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-3.html#h-81561"><span class="HTitleText1">Assurance-dépôts</span></a>
</li>
<li><span class='sectionRange'>26.01 - </span><a href="page-5.html#h-81805"><span class="HTitleText1">Institutions fédérales sans assurance-dépôts</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-5.html#h-81860"><span class="HTitleText1">Inspection des institutions membres</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-6.html#h-81913"><span class="HTitleText1">Résiliation et annulation de l’assurance</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-6.html#h-82002"><span class="HTitleText1">Arrangements avec les provinces</span></a>
</li>
<li><span class='sectionRange'>39.01 - </span><a href="page-7.html#h-82034"><span class="HTitleText1">Restructuration des institutions fédérales membres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39.01 - </span><a href="page-7.html#h-1117662"><span class="HTitleText2">Plans de règlement</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="page-7.html#h-82035"><span class="HTitleText2">Dévolution à la Société et nomination de la Société comme séquestre</span></a>
</li>
<li><span class='sectionRange'>39.181 - </span><a href="page-9.html#h-82371"><span class="HTitleText2">Non-application de certaines dispositions législatives</span></a>
</li>
<li><span class='sectionRange'>39.2 - </span><a href="page-10.html#h-82430"><span class="HTitleText2">Opérations de restructuration</span></a>
</li>
<li><span class='sectionRange'>39.23 - </span><a href="page-10.html#h-82533"><span class="HTitleText2">Indemnité</span></a>
</li>
<li><span class='sectionRange'>39.371 - </span><a href="page-11.html#h-82599"><span class="HTitleText2">Constitution et fonctionnement des institutions-relais</span></a>
</li></ul>
</li><li><span class='sectionRange'>39.38 - </span><a href="page-11.html#h-82695"><span class="HTitleText1">Restructuration des institutions provinciales membres</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-12.html#h-82703"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-12.html#h-82723"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="page-12.html#h-82742"><span class="HTitleText1">Immunité</span></a>
</li>
<li><span class='sectionRange'>45.2 - </span><a href="page-12.html#h-82769"><span class="HTitleText1">Confidentialité</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-12.html#h-82809"><span class="HTitleText1">Liquidation</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-12.html#h-82814"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><a href="page-14.html#h-82859"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

