<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant à décourager les actes de terrorisme contre le Canada et les Canadiens</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-329702"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-329705"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-329711"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-329714"><span class="HTitleText1">Cause d’action</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
