<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant la déclaration obligatoire de la pornographie juvénile sur Internet par les personnes qui fournissent des services Internet</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-270785"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-270800"><span class="HTitleText1">Obligations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-270820"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-270833"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-270842"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
