<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le contrôle des renseignements relatifs aux matières dangereuses</a><ul class="TocIndent"><li><span class='sectionRange'>9 - </span><a href="#h-1"><span class="HLabel1"></span> - <span class="HTitleText1">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-2"><span class="HTitleText2">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-4"><span class="HTitleText2">Contrôle des renseignements confidentiels</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-5"><span class="HTitleText2">Dérogation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-6"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-7"><span class="HTitleText2">Constitution du Conseil</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-8"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-9"><span class="HTitleText2">Mission du bureau de direction</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HTitleText2">Pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-11"><span class="HTitleText2">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-12"><span class="HTitleText2">Directeur général</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-13"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-14"><span class="HTitleText2">Pensions</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-15"><span class="HTitleText2">Structure</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-16"><span class="HTitleText2">Commissions d’appel</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-17"><span class="HTitleText2">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-18"><span class="HTitleText2">Renseignements confidentiels</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-19"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-20"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-21"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HTitleText2">Responsabilité</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
