<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Health Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Deputy Head</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-6"><span class="HTitleText1">Regulations and Punishment</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText1">Provincial Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>16 to 31 - </span><a href="#h-9"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HTitleText1">References</span></a>
</li>
<li><span class='sectionRange'>35 and 36 - </span><a href="#h-11"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-13"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
