<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le règlement de la revendication territoriale des Dénés et Métis du Sahtu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-420330"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-420333"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-420336"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-420339"><span class="HTitleText1">Entente</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-420357"><span class="HTitleText1">Cadre législatif</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-420361"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>11 et 12 - </span><a href="#h-420364"><span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-420366"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

