<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de la Zone du chemin de fer et du Bloc de la rivière La Paix</a><ul class="TocIndent"><li><a href="#h-437712"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - Convention</span></a>
</li>
<li><a href="#h-437796"><span class="scheduleLabel">PREMIÈRE ANNEXE</span> - <span class="scheduleTitleText"> - Emplacements de quais</span></a>
</li>
<li><a href="#h-437802"><span class="scheduleLabel">DEUXIÈME ANNEXE</span> - <span class="scheduleTitleText"> - Parcs nationaux</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
