<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le transfèrement international des délinquants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Objet et principes</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">Ministre</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Consentement</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">Application continue et adaptation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">Probation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">Adolescents</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText1">Calcul des peines</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-10"><span class="HTitleText1">Mesures d’ordre humanitaire</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText1">Ententes administratives</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HTitleText1">Disposition générale</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-13"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-14"><span class="HTitleText1">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-16"><span class="HTitleText1">Nouvelle terminologie</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
