<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le droit d’auteur</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-100028"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-100033"><span class="HTitleText1">Définitions et dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-100188"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Droit d’auteur et droits moraux sur les oeuvres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-100189"><span class="HTitleText2">Droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-100210"><span class="HTitleText2">Oeuvres susceptibles de faire l’objet d’un droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-100237"><span class="HTitleText2">Durée du droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-100293"><span class="HTitleText2">Possession du droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>14.1 - </span><a href="#h-100320"><span class="HTitleText2">Droits moraux</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-100341"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Droit d’auteur sur les prestations, enregistrements sonores et signaux de communication et droits moraux sur les prestations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-100342"><span class="HTitleText2">Droits de l’artiste-interprète</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-100343"><span class="HTitleText3">Droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>17.1 - </span><a href="#h-100404"><span class="HTitleText3">Droits moraux</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-100425"><span class="HTitleText2">Droits du producteur d’enregistrement sonore</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-100456"><span class="HTitleText2">Dispositions communes aux artistes-interprètes et aux producteurs d’enregistrements sonores</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-100507"><span class="HTitleText2">Droits des radiodiffuseurs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-100522"><span class="HTitleText2">Réciprocité</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-100540"><span class="HTitleText2">Durée des droits</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-100560"><span class="HTitleText2">Titularité</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-100572"><span class="HTitleText2">Droits des artistes-interprètes — pays OMC</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-100595"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Violation du droit d’auteur et des droits moraux, et cas d’exception</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-100596"><span class="HTitleText2">Violation du droit d’auteur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-100597"><span class="HTitleText3">Règle générale</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-100640"><span class="HTitleText3">Importations parallèles de livres</span></a>
</li></ul>
</li><li><span class='sectionRange'>28.1 - </span><a href="#h-100664"><span class="HTitleText2">Violation des droits moraux</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-100678"><span class="HTitleText2">Exceptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-100679"><span class="HTitleText3">Utilisation équitable</span></a>
</li>
<li><span class='sectionRange'>29.21 - </span><a href="#h-100704"><span class="HTitleText3">Contenu non commercial généré par l’utilisateur</span></a>
</li>
<li><span class='sectionRange'>29.22 - </span><a href="#h-100718"><span class="HTitleText3">Reproduction à des fins privées</span></a>
</li>
<li><span class='sectionRange'>29.23 - </span><a href="#h-100735"><span class="HTitleText3">Fixation d’un signal et enregistrement d’une émission pour écoute ou visionnement en différé</span></a>
</li>
<li><span class='sectionRange'>29.24 - </span><a href="#h-100753"><span class="HTitleText3">Copies de sauvegarde</span></a>
</li>
<li><span class='sectionRange'>29.3 - </span><a href="#h-100767"><span class="HTitleText3">Actes à but non lucratif</span></a>
</li>
<li><span class='sectionRange'>29.4 - </span><a href="#h-100775"><span class="HTitleText3">Établissements d’enseignement</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-100928"><span class="HTitleText3">Bibliothèques, musées ou services d’archives</span></a>
</li>
<li><span class='sectionRange'>30.3 - </span><a href="#h-100993"><span class="HTitleText3">Disposition commune aux établissements d’enseignement, bibliothèques, musées ou services d’archives</span></a>
</li>
<li><span class='sectionRange'>30.4 - </span><a href="#h-101014"><span class="HTitleText3">Bibliothèques, musées ou services d’archives faisant partie d’un établissement d’enseignement</span></a>
</li>
<li><span class='sectionRange'>30.5 - </span><a href="#h-101019"><span class="HTitleText3">Bibliothèque et Archives du Canada</span></a>
</li>
<li><span class='sectionRange'>30.6 - </span><a href="#h-101028"><span class="HTitleText3">Programmes d’ordinateur</span></a>
</li>
<li><span class='sectionRange'>30.62 - </span><a href="#h-101044"><span class="HTitleText3">Recherche sur le chiffrement</span></a>
</li>
<li><span class='sectionRange'>30.63 - </span><a href="#h-101057"><span class="HTitleText3">Sécurité</span></a>
</li>
<li><span class='sectionRange'>30.7 - </span><a href="#h-101067"><span class="HTitleText3">Incorporation incidente</span></a>
</li>
<li><span class='sectionRange'>30.71 - </span><a href="#h-101074"><span class="HTitleText3">Reproductions temporaires pour processus technologiques</span></a>
</li>
<li><span class='sectionRange'>30.8 - </span><a href="#h-101082"><span class="HTitleText3">Enregistrements éphémères</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-101137"><span class="HTitleText3">Retransmission</span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="#h-101158"><span class="HTitleText3">Services réseau</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-101177"><span class="HTitleText3">Personnes ayant des déficiences perceptuelles</span></a>
</li>
<li><span class='sectionRange'>32.1 - </span><a href="#h-101241"><span class="HTitleText3">Obligations découlant de la loi</span></a>
</li>
<li><span class='sectionRange'>32.2 - </span><a href="#h-101255"><span class="HTitleText3">Autres cas de non-violation</span></a>
</li></ul>
</li><li><span class='sectionRange'>32.3 - </span><a href="#h-101283"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>32.4 - </span><a href="#h-101288"><span class="HTitleText2">Indemnisation pour acte antérieur à la reconnaissance du droit d’auteur des artistes-interprètes et des radiodiffuseurs</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-101311"><span class="HTitleText2">Indemnisation pour acte antérieur à la reconnaissance du droit d’auteur ou des droits moraux</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-101333"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Recours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-101334"><span class="HTitleText2">Recours civils</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-101335"><span class="HTitleText3">Violation du droit d’auteur et des droits moraux</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-101460"><span class="HTitleText3">Mesures techniques de protection et information sur le régime des droits</span></a>
</li>
<li><span class='sectionRange'>41.23 - </span><a href="#h-101613"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>41.25 - </span><a href="#h-101632"><span class="HTitleText2">Dispositions concernant les fournisseurs de services réseau et d’outils de repérage</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-101697"><span class="HTitleText2">Recours criminels</span></a>
</li>
<li><span class='sectionRange'>43.1 - </span><a href="#h-101737"><span class="HTitleText2">Prescription</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-101747"><span class="HTitleText2">Importation et exportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-101748"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>44.01 - </span><a href="#h-101759"><span class="HTitleText3">Interdiction et rétention par les agents des douanes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44.01 - </span><a href="#h-101760"><span class="HTitleText4">Interdiction</span></a>
</li>
<li><span class='sectionRange'>44.02 - </span><a href="#h-101772"><span class="HTitleText4">Demande d’aide</span></a>
</li>
<li><span class='sectionRange'>44.03 - </span><a href="#h-101788"><span class="HTitleText4">Mesures relatives aux exemplaires retenus</span></a>
</li>
<li><span class='sectionRange'>44.08 - </span><a href="#h-101845"><span class="HTitleText4">Immunité</span></a>
</li>
<li><span class='sectionRange'>44.09 - </span><a href="#h-101853"><span class="HTitleText4">Pouvoirs du tribunal relativement aux exemplaires retenus</span></a>
</li></ul>
</li><li><span class='sectionRange'>44.11 - </span><a href="#h-101876"><span class="HTitleText3">Interdiction d’importation sur notification</span></a>
</li>
<li><span class='sectionRange'>44.12 - </span><a href="#h-101881"><span class="HTitleText3">Ordonnance judiciaire de rétention</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-101954"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-101955"><span class="HTitleText2">Bureau du droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-101994"><span class="HTitleText2">Enregistrement</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-102070"><span class="HTitleText2">Taxes</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-102077"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Divers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-102078"><span class="HTitleText2">Droits substitués</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-102093"><span class="HTitleText2">Erreurs matérielles</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-102098"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-102111"><span class="HTitleText2">Dessins industriels et topographies</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="#h-102158"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Commission du droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-102268"><span class="HLabel1">PARTIE VII.1</span> - <span class="HTitleText1">Gestion collective du droit d’auteur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-1109134"><span class="HTitleText2">Sociétés de gestion</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-1109162"><span class="HTitleText2">Tarifs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-1109163"><span class="HTitleText3">Projets de tarif</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-102330"><span class="HTitleText3">Retrait ou modification du projet de tarif</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-1109217"><span class="HTitleText3">Homologation du tarif</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="#h-102441"><span class="HTitleText2">Fixation des redevances dans des cas particuliers</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-1109289"><span class="HTitleText2">Règles particulières relatives aux redevances</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-1109313"><span class="HTitleText2">Conséquences liées aux tarifs et à la fixation de redevances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-1109314"><span class="HTitleText3">Actes autorisés et recours</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-1109346"><span class="HTitleText3">Portée de l’entente</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-1109350"><span class="HTitleText2">Réclamation du titulaire du droit d’auteur : redevances particulières</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-1109366"><span class="HTitleText2">Examen des ententes</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-1109386"><span class="HLabel1">PARTIE VII.2</span> - <span class="HTitleText1">Demandes particulières à la Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-102501"><span class="HTitleText2">Titulaires introuvables</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-102513"><span class="HTitleText2">Indemnisation pour acte antérieur à la reconnaissance du droit d’auteur ou des droits moraux</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-102523"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Copie pour usage privé</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="#h-102524"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-102539"><span class="HTitleText2">Copie pour usage privé</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-102551"><span class="HTitleText2">Droit à rémunération</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-102559"><span class="HTitleText2">Redevances</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-102609"><span class="HTitleText2">Répartition des redevances</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-102631"><span class="HTitleText2">Exemption</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-102641"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-102652"><span class="HTitleText2">Recours civils</span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-102667"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-102687"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Droits existants</span></a>
</li>
<li><a href="#h-102699"><span class="scheduleLabel">ANNEXE II</span></a>
</li>
<li><a href="#h-102702"><span class="scheduleLabel">ANNEXE III</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
