<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Income Tax Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-279727"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-279732"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-279733"><span class="HLabel2">DIVISION A</span> - <span class="HTitleText2">Liability for Tax</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-279747"><span class="HLabel2">DIVISION B</span> - <span class="HTitleText2">Computation of Income</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-279748"><span class="HTitleText3">Basic Rules</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-279779"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Income or Loss from an Office or Employment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-279780"><span class="HTitleText4">Basic Rules</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-279788"><span class="HTitleText4">Inclusions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-3.html#h-280185"><span class="HTitleText4">Deductions</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="page-4.html#h-280413"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Income or Loss from a Business or Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-4.html#h-280414"><span class="HTitleText4">Basic Rules</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-5.html#h-280535"><span class="HTitleText4">Inclusions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-12.html#h-281928"><span class="HTitleText4">Deductions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-17.html#h-283393"><span class="HTitleText4">Ceasing to carry on business</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-18.html#h-283436"><span class="HTitleText4">Special Cases</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-22.html#h-284188"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Taxable Capital Gains and Allowable Capital Losses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47.1 - </span><a href="page-26.html#h-285132"><span class="HTitleText4">Indexed Security Investment Plans</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="page-31.html#h-286072"><span class="HLabel3">SUBDIVISION D</span> - <span class="HTitleText3">Other Sources of Income</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56.4 - </span><a href="page-32.html#h-286355"><span class="HTitleText4">Restrictive Covenants</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="page-34.html#h-286571"><span class="HLabel3">SUBDIVISION E</span> - <span class="HTitleText3">Deductions in Computing Income</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-45.html#h-288838"><span class="HLabel3">SUBDIVISION F</span> - <span class="HTitleText3">Rules Relating to Computation of Income</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-56.html#h-290592"><span class="HLabel3">SUBDIVISION G</span> - <span class="HTitleText3">Amounts Not Included in Computing Income</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-57.html#h-290685"><span class="HLabel3">SUBDIVISION H</span> - <span class="HTitleText3">Corporations Resident in Canada and their Shareholders</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>86.1 - </span><a href="page-61.html#h-291279"><span class="HTitleText4">Foreign Spin-offs</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="page-64.html#h-292582"><span class="HLabel3">SUBDIVISION I</span> - <span class="HTitleText3">Shareholders of Corporations Not Resident in Canada</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-70.html#h-294865"><span class="HLabel3">SUBDIVISION J</span> - <span class="HTitleText3">Partnerships and their Members</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-73.html#h-295288"><span class="HLabel3">SUBDIVISION K</span> - <span class="HTitleText3">Trusts and their Beneficiaries</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="page-77.html#h-296174"><span class="HLabel2">DIVISION C</span> - <span class="HTitleText2">Computation of Taxable Income</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110.2 - </span><a href="page-79.html#h-296427"><span class="HTitleText3">Lump-sum Payments</span></a>
</li></ul>
</li><li><span class='sectionRange'>115 - </span><a href="page-82.html#h-297488"><span class="HLabel2">DIVISION D</span> - <span class="HTitleText2">Taxable Income Earned in Canada by Non-Residents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>115.2 - </span><a href="page-83.html#h-297585"><span class="HTitleText3">Non-Residents with Canadian Investment Service Providers</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="page-84.html#h-297734"><span class="HLabel2">DIVISION E</span> - <span class="HTitleText2">Computation of Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="page-84.html#h-297735"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Rules Applicable to Individuals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117.1 - </span><a href="page-84.html#h-297759"><span class="HTitleText4">Annual Adjustment of Deductions and Other Amounts</span></a>
</li>
<li><span class='sectionRange'>120.31 - </span><a href="page-92.html#h-298979"><span class="HTitleText4">Lump-sum Payments</span></a>
</li>
<li><span class='sectionRange'>120.4 - </span><a href="page-92.html#h-298999"><span class="HTitleText4">Tax on Split Income</span></a>
</li></ul>
</li><li><span class='sectionRange'>122.6 - </span><a href="page-95.html#h-299563"><span class="HLabel3">SUBDIVISION A.1</span> - <span class="HTitleText3">Canada Child Benefit</span></a>
</li>
<li><span class='sectionRange'>122.7 - </span><a href="page-96.html#h-299725"><span class="HLabel3">SUBDIVISION A.2</span> - <span class="HTitleText3">Canada Workers Benefit</span></a>
</li>
<li><span class='sectionRange'>122.8 - </span><a href="page-97.html#h-299820"><span class="HLabel3">SUBDIVISION A.3</span> - <span class="HTitleText3">Climate Action Incentive</span></a>
</li>
<li><span class='sectionRange'>122.9 - </span><a href="page-97.html#h-299875"><span class="HLabel3">SUBDIVISION A.4</span> - <span class="HTitleText3">School Supplies Tax Credit</span></a>
</li>
<li><span class='sectionRange'>122.91 - </span><a href="page-97.html#h-1171696"><span class="HLabel3">SUBDIVISION A.5</span> - <span class="HTitleText3">Canada Training Credit</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="page-98.html#h-299918"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Rules Applicable to Corporations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123.4 - </span><a href="page-98.html#h-299947"><span class="HTitleText4">Corporation Tax Reductions</span></a>
</li>
<li><span class='sectionRange'>125.4 - </span><a href="page-100.html#h-300339"><span class="HTitleText4">Canadian Film or Video Production Tax Credit</span></a>
</li>
<li><span class='sectionRange'>125.5 - </span><a href="page-100.html#h-300428"><span class="HTitleText4">Film or Video Production Services Tax Credit</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="page-102.html#h-300489"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Rules Applicable to all Taxpayers</span></a>
</li></ul>
</li><li><span class='sectionRange'>127.5 - </span><a href="page-106.html#h-301844"><span class="HLabel2">DIVISION E.1</span> - <span class="HTitleText2">Minimum Tax</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-107.html#h-302020"><span class="HLabel2">DIVISION F</span> - <span class="HTitleText2">Special Rules Applicable in Certain Circumstances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-107.html#h-302021"><span class="HTitleText3">Bankruptcies</span></a>
</li>
<li><span class='sectionRange'>128.1 - </span><a href="page-108.html#h-302099"><span class="HTitleText3">Changes in Residence</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-109.html#h-302354"><span class="HTitleText3">Private Corporations</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-110.html#h-302511"><span class="HTitleText3">Investment Corporations</span></a>
</li>
<li><span class='sectionRange'>130.1 - </span><a href="page-110.html#h-302560"><span class="HTitleText3">Mortgage Investment Corporations</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-111.html#h-302635"><span class="HTitleText3">Mutual Fund Corporations</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-112.html#h-302799"><span class="HTitleText3">Mutual Fund Trusts</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-114.html#h-303072"><span class="HTitleText3">Non-Resident-Owned Investment Corporations</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-115.html#h-303233"><span class="HTitleText3">Patronage Dividends</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="page-115.html#h-303294"><span class="HTitleText3">Agricultural Cooperatives — Tax-deferred Patronage Dividends</span></a>
</li>
<li><span class='sectionRange'>135.2 - </span><a href="page-116.html#h-303370"><span class="HTitleText3">Continuance of the Canadian Wheat Board</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-117.html#h-303545"><span class="HTitleText3">Cooperative Corporations</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-117.html#h-303557"><span class="HTitleText3">Credit Unions, Savings and Credit Unions and Deposit Insurance Corporations</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-119.html#h-303768"><span class="HTitleText3">Insurance Corporations</span></a>
</li>
<li><span class='sectionRange'>139.1 - </span><a href="page-121.html#h-304333"><span class="HTitleText3">Demutualization of Insurance Corporations</span></a>
</li>
<li><span class='sectionRange'>142.2 - </span><a href="page-122.html#h-304588"><span class="HTitleText3">Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>142.2 - </span><a href="page-122.html#h-304589"><span class="HTitleText4">Interpretation</span></a>
</li>
<li><span class='sectionRange'>142.3 - </span><a href="page-123.html#h-304660"><span class="HTitleText4">Income from Specified Debt Obligations</span></a>
</li>
<li><span class='sectionRange'>142.4 - </span><a href="page-123.html#h-304680"><span class="HTitleText4">Disposition of Specified Debt Obligations</span></a>
</li>
<li><span class='sectionRange'>142.5 - </span><a href="page-123.html#h-304770"><span class="HTitleText4">Mark-to-Market Properties</span></a>
</li>
<li><span class='sectionRange'>142.6 - </span><a href="page-124.html#h-304905"><span class="HTitleText4">Additional Rules</span></a>
</li>
<li><span class='sectionRange'>142.7 - </span><a href="page-125.html#h-305007"><span class="HTitleText4">Conversion of Foreign Bank Affiliate to Branch</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-126.html#h-305128"><span class="HTitleText4">Communal Organizations</span></a>
</li></ul>
</li><li><span class='sectionRange'>143.2 - </span><a href="page-127.html#h-305263"><span class="HTitleText3">Cost of Tax Shelter Investments and Limited-recourse Debt in Respect of Gifting Arrangements</span></a>
</li>
<li><span class='sectionRange'>143.3 - </span><a href="page-127.html#h-305349"><span class="HTitleText3">Expenditure — Limitations</span></a>
</li>
<li><span class='sectionRange'>143.4 - </span><a href="page-128.html#h-305380"><span class="HTitleText3">Expenditure — Limit for Contingent Amount</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="page-128.html#h-305417"><span class="HLabel2">DIVISION G</span> - <span class="HTitleText2">Deferred and Other Special Income Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="page-128.html#h-305418"><span class="HTitleText3">Employees Profit Sharing Plans</span></a>
</li>
<li><span class='sectionRange'>144.1 - </span><a href="page-129.html#h-305531"><span class="HTitleText3">Employee Life and Health Trust</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="page-130.html#h-305616"><span class="HTitleText3">Registered Supplementary Unemployment Benefit Plans</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="page-130.html#h-305632"><span class="HTitleText3">Registered Retirement Savings Plans</span></a>
</li>
<li><span class='sectionRange'>146.01 - </span><a href="page-131.html#h-306024"><span class="HTitleText3">Home Buyers’ Plan</span></a>
</li>
<li><span class='sectionRange'>146.02 - </span><a href="page-132.html#h-306187"><span class="HTitleText3">Lifelong Learning Plan</span></a>
</li>
<li><span class='sectionRange'>146.1 - </span><a href="page-133.html#h-306304"><span class="HTitleText3">Registered Education Savings Plans</span></a>
</li>
<li><span class='sectionRange'>146.2 - </span><a href="page-134.html#h-306517"><span class="HTitleText3">Tax-free Savings Accounts</span></a>
</li>
<li><span class='sectionRange'>146.3 - </span><a href="page-134.html#h-306609"><span class="HTitleText3">Registered Retirement Income Funds</span></a>
</li>
<li><span class='sectionRange'>146.4 - </span><a href="page-135.html#h-306842"><span class="HTitleText3">Registered Disability Savings Plan</span></a>
</li>
<li><span class='sectionRange'>146.5 - </span><a href="page-136.html#h-1310557"><span class="HTitleText3">Advanced Life Deferred Annuity</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-136.html#h-307105"><span class="HTitleText3">Deferred Profit Sharing Plans</span></a>
</li>
<li><span class='sectionRange'>147.1 - </span><a href="page-137.html#h-307331"><span class="HTitleText3">Registered Pension Plans</span></a>
</li>
<li><span class='sectionRange'>147.5 - </span><a href="page-139.html#h-307745"><span class="HTitleText3">Pooled Registered Pension Plans</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-140.html#h-307970"><span class="HTitleText3">Life Insurance Policies</span></a>
</li>
<li><span class='sectionRange'>148.1 - </span><a href="page-141.html#h-308212"><span class="HTitleText3">Eligible Funeral Arrangements</span></a>
</li></ul>
</li><li><span class='sectionRange'>149 - </span><a href="page-141.html#h-308265"><span class="HLabel2">DIVISION H</span> - <span class="HTitleText2">Exemptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="page-141.html#h-308266"><span class="HTitleText3">Miscellaneous Exemptions</span></a>
</li>
<li><span class='sectionRange'>149.1 - </span><a href="page-142.html#h-308534"><span class="HTitleText3">Qualified Donees</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="page-143.html#h-308901"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Returns, Assessments, Payment and Appeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="page-143.html#h-308902"><span class="HTitleText3">Returns</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="page-144.html#h-308987"><span class="HTitleText3">Estimate of Tax</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-144.html#h-308992"><span class="HTitleText3">Assessment</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-145.html#h-309170"><span class="HTitleText3">Payment of Tax</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-149.html#h-309636"><span class="HTitleText3">Interest</span></a>
</li>
<li><span class='sectionRange'>161.1 - </span><a href="page-150.html#h-309747"><span class="HTitleText3">Offset of Refund Interest and Arrears Interest</span></a>
</li>
<li><span class='sectionRange'>161.3 - </span><a href="page-150.html#h-309795"><span class="HTitleText3">Small Amounts Owing</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-150.html#h-309807"><span class="HTitleText3">Penalties</span></a>
</li>
<li><span class='sectionRange'>163.2 - </span><a href="page-152.html#h-310111"><span class="HTitleText3">Misrepresentation of a Tax Matter by a Third Party</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="page-153.html#h-310228"><span class="HTitleText3">Refunds</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="page-154.html#h-310376"><span class="HTitleText3">Objections to Assessments</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-154.html#h-310430"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-155.html#h-310503"><span class="HTitleText3">Revocation of Registration of Certain Organizations and Associations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168.1 - </span><a href="page-155.html#h-1310680"><span class="HTitleText4">Designation of Qualified Canadian Journalism Organizations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="page-155.html#h-310527"><span class="HLabel2">DIVISION J</span> - <span class="HTitleText2">Appeals to the Tax Court of Canada and the Federal Court of Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>180.01 - </span><a href="page-156.html#h-310710"><span class="HLabel1">PART I.01</span> - <span class="HTitleText1">Tax in Respect of Stock Option Benefit Deferral</span></a>
</li>
<li><span class='sectionRange'>180.1 - </span><a href="page-156.html#h-310738"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Individual Surtax</span></a>
</li>
<li><span class='sectionRange'>180.2 - </span><a href="page-156.html#h-310742"><span class="HLabel1">PART I.2</span> - <span class="HTitleText1">Tax on Old Age Security Benefits</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-157.html#h-310794"><span class="HLabel1">PART I.3</span> - <span class="HTitleText1">Tax on Large Corporations</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-159.html#h-311107"><span class="HLabel1">PART II</span> - <span class="HTitleText1">[Repealed, 2017, c. 20, s. 27]</span></a>
</li>
<li><span class='sectionRange'>183.1 - </span><a href="page-159.html#h-311114"><span class="HLabel1">PART II.1</span> - <span class="HTitleText1">Tax on Corporate Distributions</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="page-159.html#h-311150"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Additional Tax on Excessive Elections</span></a>
</li>
<li><span class='sectionRange'>185.1 - </span><a href="page-160.html#h-311207"><span class="HLabel1">PART III.1</span> - <span class="HTitleText1">Additional Tax on Excessive Eligible Dividend Designations</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-160.html#h-311263"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Tax on Taxable Dividends Received by Private Corporations</span></a>
</li>
<li><span class='sectionRange'>187.1 - </span><a href="page-161.html#h-311330"><span class="HLabel1">PART IV.1</span> - <span class="HTitleText1">Taxes on Dividends on Certain Preferred Shares Received by Corporations</span></a>
</li>
<li><span class='sectionRange'>187.7 - </span><a href="page-161.html#h-311385"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Tax and Penalties in Respect of Qualified Donees</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-163.html#h-311628"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Tax on Capital of Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>190.1 - </span><a href="page-163.html#h-311649"><span class="HTitleText2">Calculation of Capital Tax</span></a>
</li>
<li><span class='sectionRange'>190.2 - </span><a href="page-164.html#h-311795"><span class="HTitleText2">Administrative Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="page-165.html#h-311820"><span class="HLabel1">PART VI.1</span> - <span class="HTitleText1">Tax on Corporations Paying Dividends on Taxable Preferred Shares</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-166.html#h-311992"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Refundable Tax on Corporations Issuing Qualifying Shares</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-167.html#h-312074"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Refundable Tax on Corporations in Respect of Scientific Research and Experimental Development Tax Credit</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-168.html#h-312171"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Tax on Deduction Under Section 66.5</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-168.html#h-312185"><span class="HLabel1">PART IX.1</span> - <span class="HTitleText1">Tax on Sift Partnerships</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-168.html#h-312229"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Taxes on Deferred Profit Sharing Plans and Revoked Plans</span></a>
</li>
<li><span class='sectionRange'>204.1 - </span><a href="page-170.html#h-312399"><span class="HLabel1">PART X.1</span> - <span class="HTitleText1">Tax in Respect of Over-contributions to Deferred Income Plans</span></a>
</li>
<li><span class='sectionRange'>204.4 - </span><a href="page-171.html#h-312531"><span class="HLabel1">PART X.2</span> - <span class="HTitleText1">Tax in Respect of Registered Investments</span></a>
</li>
<li><span class='sectionRange'>204.8 - </span><a href="page-171.html#h-312629"><span class="HLabel1">PART X.3</span> - <span class="HTitleText1">Labour-sponsored Venture Capital Corporations</span></a>
</li>
<li><span class='sectionRange'>204.9 - </span><a href="page-174.html#h-312964"><span class="HLabel1">PART X.4</span> - <span class="HTitleText1">Tax in Respect of Overpayments to Registered Education Savings Plans</span></a>
</li>
<li><span class='sectionRange'>204.94 - </span><a href="page-174.html#h-313043"><span class="HLabel1">PART X.5</span> - <span class="HTitleText1">Payments Under Registered Education Savings Plans</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="page-175.html#h-313074"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Tax in Respect of Advanced Life Deferred Annuity</span></a>
</li>
<li><span class='sectionRange'>207.01 - </span><a href="page-175.html#h-313096"><span class="HLabel1">PART XI.01</span> - <span class="HTitleText1">Taxes in Respect of Registered Plans</span></a>
</li>
<li><span class='sectionRange'>207.1 - </span><a href="page-176.html#h-313431"><span class="HLabel1">PART XI.1</span> - <span class="HTitleText1">Tax in Respect of Deferred Income Plans and Other Tax Exempt Persons</span></a>
</li>
<li><span class='sectionRange'>207.3 - </span><a href="page-177.html#h-313456"><span class="HLabel1">PART XI.2</span> - <span class="HTitleText1">Tax in Respect of Dispositions of Certain Properties</span></a>
</li>
<li><span class='sectionRange'>207.5 - </span><a href="page-177.html#h-313483"><span class="HLabel1">PART XI.3</span> - <span class="HTitleText1">Tax in Respect of Retirement Compensation Arrangements</span></a>
</li>
<li><span class='sectionRange'>207.8 - </span><a href="page-178.html#h-313643"><span class="HLabel1">PART XI.4</span> - <span class="HTitleText1">Tax on Excess EPSP Amounts</span></a>
</li>
<li><span class='sectionRange'>207.9 - </span><a href="page-178.html#h-1310930"><span class="HLabel1">PART XI.5</span> - <span class="HTitleText1">Tax in Respect of Employee Life and Health Trust</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="page-178.html#h-313671"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Tax in Respect of Certain Royalties, Taxes, Lease Rentals, Etc., Paid to a Government by a Tax Exempt Person</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="page-178.html#h-313675"><span class="HLabel1">PART XII.1</span> - <span class="HTitleText1">Tax on Carved-out Income</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="page-179.html#h-313730"><span class="HLabel1">PART XII.2</span> - <span class="HTitleText1">Tax on Designated Income of Certain Trusts</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-179.html#h-313843"><span class="HLabel1">PART XII.3</span> - <span class="HTitleText1">Tax on Investment Income of Life Insurers</span></a>
</li>
<li><span class='sectionRange'>211.6 - </span><a href="page-180.html#h-313990"><span class="HLabel1">PART XII.4</span> - <span class="HTitleText1">Tax on Qualifying Environmental Trusts</span></a>
</li>
<li><span class='sectionRange'>211.7 - </span><a href="page-181.html#h-314052"><span class="HLabel1">PART XII.5</span> - <span class="HTitleText1">Recovery of Labour-sponsored Funds Tax Credit</span></a>
</li>
<li><span class='sectionRange'>211.91 - </span><a href="page-181.html#h-314117"><span class="HLabel1">PART XII.6</span> - <span class="HTitleText1">Tax on Flow-through Shares</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="page-181.html#h-314143"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Tax on Income from Canada of Non-resident Persons</span></a>
</li>
<li><span class='sectionRange'>218.2 - </span><a href="page-186.html#h-315259"><span class="HLabel1">PART XIII.1</span> - <span class="HTitleText1">Additional Tax on Authorized Foreign Banks</span></a>
</li>
<li><span class='sectionRange'>218.3 - </span><a href="page-186.html#h-315281"><span class="HLabel1">PART XIII.2</span> - <span class="HTitleText1">Non-resident Investors in Canadian Mutual Funds</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="page-186.html#h-315332"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Additional Tax on Non-resident Corporations</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-187.html#h-315483"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="page-187.html#h-315484"><span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="page-188.html#h-315687"><span class="HTitleText2">Collection</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-191.html#h-316115"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="page-198.html#h-316851"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="page-199.html#h-317177"><span class="HTitleText2">Procedure and Evidence</span></a>
</li></ul>
</li><li><span class='sectionRange'>244.1 - </span><a href="page-199.html#h-317234"><span class="HLabel1">PART XV.1</span> - <span class="HTitleText1">Reporting of Electronic Funds Transfer</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="page-200.html#h-317321"><span class="HLabel1">PART XVI</span> - <span class="HTitleText1">Tax Avoidance</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="page-200.html#h-317370"><span class="HLabel1">PART XVI.1</span> - <span class="HTitleText1">Transfer Pricing</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="page-201.html#h-317484"><span class="HLabel1">PART XVII</span> - <span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="page-209.html#h-319968"><span class="HLabel1">PART XVIII</span> - <span class="HTitleText1">Enhanced International Information Reporting</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="page-210.html#h-320102"><span class="HLabel1">PART XIX</span> - <span class="HTitleText1">Common Reporting Standard</span></a>
</li>
<li><a href="page-214.html#h-320658"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Listed Corporations</span></a>
</li></ul>
</li></ul>

</nav>

