<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la responsabilité en matière de carboneutralité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1294944"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1294947"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1294957"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1294960"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1294963"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1294966"><span class="HTitleText1">Cibles et plans</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-1295030"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1295065"><span class="HTitleText1">Dépôt et publication</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-1295082"><span class="HTitleText1">Organisme consultatif</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-1295119"><span class="HTitleText1">Ministre des Finances</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-1295122"><span class="HTitleText1">Commissaire à l’environnement et au développement durable</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-1295132"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-1295146"><span class="HTitleText1">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-1295147"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le vérificateur général</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-1295152"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

