<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la compensation et le règlement des paiements</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Encadrement des systèmes de compensation et de règlement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Systèmes visés</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Renseignements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Directives</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Pouvoirs de la banque</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText2">Dispositions concernant le règlement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Avis de changements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Vérification et inspection</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-12"><span class="HTitleText2">Pouvoirs de la banque</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-13"><span class="HTitleText2">Accords de compensation</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-14"><span class="HTitleText2">Chambre spécialisée</span></a>
</li>
<li><span class='sectionRange'>13.2 - </span><a href="#h-15"><span class="HTitleText2">Accords</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-16"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-17"><span class="HTitleText2">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-18"><span class="HTitleText2">Lignes directrices</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-19"><span class="HTitleText2">Confidentialité des renseignements</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-20"><span class="HTitleText2">Désignations et directives</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-21"><span class="HTitleText2">Absence de responsabilité</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-22"><span class="HTitleText2">Contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-23"><span class="HTitleText2">Établissements participants</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-24"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
