<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Translation Bureau Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-451755"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-451760"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-451765"><span class="HTitleText1">Establishment of Translation Bureau</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-451770"><span class="HTitleText1">Duties and Functions of Bureau</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-451778"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-451784"><span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

