<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le ministère des Ressources naturelles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-355362"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-355365"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-355372"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-355380"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-355397"><span class="HTitleText1">Rapport</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-355403"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>11 à 36 - </span><a href="page-1.html#h-355413"><span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-1.html#h-355415"><span class="HTitleText1">Nouvelle terminologie</span></a>
</li>
<li><span class='sectionRange'>39 à 41 - </span><a href="page-1.html#h-355424"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-1.html#h-355426"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

