<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur les organisations à but non lucratif</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-153376"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-153379"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Définitions et application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-153380"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-153443"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-153455"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-153458"><span class="HTitleText2">Désignation du ministre</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-153461"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Constitution</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-153537"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Capacité et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-153565"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-153662"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Financement</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-153699"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Titres de créance, certificats, registres et transfert</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-153700"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-153729"><span class="HTitleText2">Certificats de titres de créance</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-153762"><span class="HTitleText2">Registres</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-153813"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-153820"><span class="HTitleText2">Livraison des titres de créance</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-153829"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-154082"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Actes de fiducie</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-154148"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Séquestres et séquestres-gérants</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-154179"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-154483"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Règlements administratifs et membres</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-154701"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Présentation des renseignements d’ordre financier</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-154744"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">Expert-comptable</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-154878"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">Modification de structure</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-155165"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">Liquidation et dissolution</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-155486"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">Enquête</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-155545"><span class="HLabel1">PARTIE 16</span> - <span class="HTitleText1">Recours, infractions et peines</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-155674"><span class="HLabel1">PARTIE 17</span> - <span class="HTitleText1">Documents sous forme électronique ou autre</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-155726"><span class="HLabel1">PARTIE 18</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>272 - </span><a href="#h-155727"><span class="HTitleText2">Avis, certificats et autres documents</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="#h-155792"><span class="HTitleText2">Directeur</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="#h-155880"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>294 - </span><a href="#h-155901"><span class="HLabel1">PARTIE 19</span> - <span class="HTitleText1">Personnes morales sans capital-actions constituées par une Loi spéciale</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-155930"><span class="HLabel1">PARTIE 20</span> - <span class="HTitleText1">Dispositions transitoires, modifications corrélatives, dispositions de coordination, abrogations et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="#h-155931"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-155954"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>300 - </span><a href="#h-155955"><span class="HTitleText3">Loi constituant en corporation « St. Mary’s River Bridge Company »</span></a>
</li>
<li><span class='sectionRange'>303 - </span><a href="#h-155959"><span class="HTitleText3">Loi sur la Fondation Jules et Paul-Émile Léger</span></a>
</li>
<li><span class='sectionRange'>304 - </span><a href="#h-155961"><span class="HTitleText3">Acte pour incorporer la Compagnie du Havre de Pickering, (à responsabilité limitée) et pour l’autoriser à percevoir des péages</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-155963"><span class="HTitleText3">Loi permettant la création par fusion de L’Église Wesleyenne du Canada</span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-155965"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-155967"><span class="HTitleText3">Loi d’exécution du budget de 1997</span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="#h-155970"><span class="HTitleText3">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="#h-155974"><span class="HTitleText3">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-155976"><span class="HTitleText3">Loi sur les corporations canadiennes</span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-155978"><span class="HTitleText3">Loi sur l’Office de financement de l’assurance-emploi du Canada</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="#h-155980"><span class="HTitleText3">Loi sur la Fondation du Canada pour l’appui technologique au développement durable</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="#h-155983"><span class="HTitleText3">Loi sur l’Office d’investissement du régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="#h-155985"><span class="HTitleText3">Loi sur l’Agence canadienne d’inspection des aliments</span></a>
</li>
<li><span class='sectionRange'>319 - </span><a href="#h-155987"><span class="HTitleText3">Loi sur les Instituts de recherche en santé du Canada</span></a>
</li>
<li><span class='sectionRange'>320 - </span><a href="#h-155989"><span class="HTitleText3">Loi canadienne sur les paiements</span></a>
</li>
<li><span class='sectionRange'>321 - </span><a href="#h-155991"><span class="HTitleText3">Loi sur les coopératives de l’énergie</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="#h-155993"><span class="HTitleText3">Loi sur les Cris et les Naskapis du Québec</span></a>
</li>
<li><span class='sectionRange'>323 - </span><a href="#h-155995"><span class="HTitleText3">Loi sur l’Église évangélique luthérienne au Canada</span></a>
</li>
<li><span class='sectionRange'>324 - </span><a href="#h-155997"><span class="HTitleText3">Loi sur l’Église missionnaire évangélique, section de l’Ouest canadien</span></a>
</li>
<li><span class='sectionRange'>327 - </span><a href="#h-156001"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="#h-156003"><span class="HTitleText3">Loi sur la gestion financière et statistique des premières nations</span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="#h-156005"><span class="HTitleText3">Loi sur l’association personnalisée le Bouclier vert du Canada</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="#h-156007"><span class="HTitleText3">Loi sur le règlement de la revendication territoriale des Gwich’in</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="#h-156009"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="#h-156011"><span class="HTitleText3">Loi relative aux répercussions du projet gazier Mackenzie</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="#h-156013"><span class="HTitleText3">Loi sur l’éducation des Mi’kmaq</span></a>
</li>
<li><span class='sectionRange'>334 - </span><a href="#h-156015"><span class="HTitleText3">Loi sur l’activité physique et le sport</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-156017"><span class="HTitleText3">Loi sur le pilotage</span></a>
</li>
<li><span class='sectionRange'>336 - </span><a href="#h-156019"><span class="HTitleText3">Loi sur l’Office d’investissement des régimes de pensions du secteur public</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-156021"><span class="HTitleText3">Loi sur le règlement de la revendication territoriale des Dénés et Métis du Sahtu</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="#h-156023"><span class="HTitleText3">Loi sur l’Union des producteurs de grain</span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="#h-156025"><span class="HTitleText3">Loi sur le règlement des revendications territoriales des premières nations du Yukon</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-156027"><span class="HTitleText3">Autres lois</span></a>
</li></ul>
</li><li><span class='sectionRange'>341 - </span><a href="#h-156030"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-156051"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="#h-156063"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
