<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les jeunes contrevenants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Déclaration de principes</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Mesures de rechange</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Compétence</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Détention avant décision</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText1">Avis aux père et mère</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">Droit aux services d’un avocat</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText1">Comparution</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText1">Rapports médicaux et psychologiques</span></a>
</li>
<li><span class='sectionRange'>13.2 - </span><a href="#h-11"><span class="HTitleText1">Application de la partie XX.1 du Code criminel (troubles mentaux)</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText1">Rapport prédécisionnel</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-13"><span class="HTitleText1">Dessaisissement du juge</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-14"><span class="HTitleText1">Renvoi</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-15"><span class="HTitleText1">Transfert de compétence</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-16"><span class="HTitleText1">Jugement</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-17"><span class="HTitleText1">Décisions</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-18"><span class="HTitleText1">Appels</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText1">Examen des décisions</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-20"><span class="HTitleText1">Mise en liberté provisoire</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-21"><span class="HTitleText1">Conséquences de la cessation d’effet des décisions</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-22"><span class="HTitleText1">Délégués à la jeunesse</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-23"><span class="HTitleText1">Protection de la vie privée des adolescents</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-24"><span class="HTitleText1">Tenue et utilisation des dossiers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-25"><span class="HTitleText2">Dossiers dont la tenue est autorisée</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-26"><span class="HTitleText2">Empreintes digitales et photographies</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="#h-27"><span class="HTitleText2">Communication des dossiers</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-28"><span class="HTitleText2">Non-communication et destruction des dossiers</span></a>
</li>
<li><span class='sectionRange'>45.01 - </span><a href="#h-29"><span class="HTitleText2">Conservation des dossiers</span></a>
</li>
<li><span class='sectionRange'>45.02 - </span><a href="#h-30"><span class="HTitleText2">Répertoire spécial</span></a>
</li>
<li><span class='sectionRange'>45.03 - </span><a href="#h-31"><span class="HTitleText2">Répertoire spécial des empreintes digitales</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="#h-32"><span class="HTitleText2">Communication des dossiers dans certains cas</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-33"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-34"><span class="HTitleText1">Outrage au tribunal</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-35"><span class="HTitleText1">Confiscation du montant des engagements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-36"><span class="HTitleText1">Entrave à l’exécution d’une décision</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-37"><span class="HTitleText1">Applicabilité du Code criminel</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-38"><span class="HTitleText1">Procédure</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-39"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-40"><span class="HTitleText1">Remplacement de juges</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-41"><span class="HTitleText1">Fonctions des greffiers du tribunal</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-42"><span class="HTitleText1">Formules, règlements et règles de cour</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-43"><span class="HTitleText1">Comités de justice pour la jeunesse</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-44"><span class="HTitleText1">Accord avec les provinces</span></a>
</li>
<li><a href="#h-45"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
