<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Pilotage Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-394338"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="page-1.html#h-394343"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-394353"><span class="HTitleText1">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-394365"><span class="HTitleText1">Pilotage Authorities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-394366"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-394397"><span class="HTitleText2">Organization</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-394480"><span class="HTitleText2">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-394638"><span class="HTitleText2">Charges</span></a>
</li>
<li><span class='sectionRange'>36.01 - </span><a href="page-3.html#h-394683"><span class="HTitleText2">Financial Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>38.01 - </span><a href="page-3.html#h-1242575"><span class="HTitleText1">Conduct of Ship Subject to Compulsory Pilotage</span></a>
</li>
<li><span class='sectionRange'>38.1 - </span><a href="page-3.html#h-1297785"><span class="HTitleText1">Licences and Pilotage Certificates</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-4.html#h-394700"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-394734"><span class="HTitleText1">St. Lambert Lock</span></a>
</li>
<li><span class='sectionRange'>46.01 - </span><a href="page-4.html#h-1297901"><span class="HTitleText1">Electronic Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="page-4.html#h-1242613"><span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46.1 - </span><a href="page-4.html#h-1242614"><span class="HTitleText2">Designation of Authorized Persons</span></a>
</li>
<li><span class='sectionRange'>46.12 - </span><a href="page-4.html#h-1242623"><span class="HTitleText2">Compliance Measures</span></a>
</li>
<li><span class='sectionRange'>46.23 - </span><a href="page-5.html#h-1242757"><span class="HTitleText2">Provisions Related to Entry</span></a>
</li>
<li><span class='sectionRange'>46.25 - </span><a href="page-5.html#h-1242769"><span class="HTitleText2">Obstruction</span></a>
</li>
<li><span class='sectionRange'>46.26 - </span><a href="page-5.html#h-1242774"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>46.35 - </span><a href="page-6.html#h-1242892"><span class="HTitleText2">Recovery of Debts</span></a>
</li>
<li><span class='sectionRange'>46.37 - </span><a href="page-6.html#h-1242913"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>46.44 - </span><a href="page-7.html#h-1242968"><span class="HTitleText2">Public Record</span></a>
</li>
<li><span class='sectionRange'>46.46 - </span><a href="page-7.html#h-1242996"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-7.html#h-394745"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-8.html#h-394777"><span class="HTitleText1">Regulations, Exemption Orders, Interim Orders and Directions</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-8.html#h-394788"><span class="HTitleText1">Review of Act</span></a>
</li>
<li><a href="page-10.html#h-394874"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

