<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la protection de l’environnement en Antarctique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-3525"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-3528"><span class="HTitleText1">Dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-3562"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-3565"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-3571"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-3646"><span class="HTitleText1">Permis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-3647"><span class="HTitleText2">Délivrance des permis</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-3668"><span class="HTitleText2">Évaluations environnementales</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-3678"><span class="HTitleText2">Plan de gestion des déchets et plan d’urgence</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-3681"><span class="HTitleText2">Garanties</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-2.html#h-3687"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-3724"><span class="HTitleText1">Contrôle d’application au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="page-2.html#h-3725"><span class="HTitleText2">Agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-3739"><span class="HTitleText2">Inspections au Canada</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-3799"><span class="HTitleText2">Perquisition et saisie au Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-3838"><span class="HTitleText2">Rétention au Canada</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-3870"><span class="HTitleText2">Arrêt de bâtiments</span></a>
</li>
<li><span class='sectionRange'>37.01 - </span><a href="page-3.html#h-3895"><span class="HTitleText2">Ordre aux bâtiments</span></a>
</li>
<li><span class='sectionRange'>37.02 - </span><a href="page-3.html#h-3902"><span class="HTitleText2">Ordres d’exécution en matière de protection de l’environnement</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-4027"><span class="HTitleText2">Aide à donner aux agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-4034"><span class="HTitleText2">Confiscation au Canada</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="page-5.html#h-4071"><span class="HTitleText2">Responsabilité pour frais</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-5.html#h-4076"><span class="HTitleText1">Inspections en antarctique</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-4116"><span class="HTitleText1">Entrave et renseignements faux ou trompeurs</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-7.html#h-4456"><span class="HTitleText1">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-4478"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

