<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 1999 pour la mise en oeuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-318436"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-318439"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Accord Canada – Kirghizistan en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-318455"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Convention Canada – Liban en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-318471"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Convention Canada – Algérie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-318487"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Convention Canada – Bulgarie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-318503"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Convention Canada – Portugal en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-1.html#h-318519"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Convention Canada – Ouzbékistan en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-1.html#h-318535"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Convention Canada – Jordanie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-1.html#h-318551"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Convention Canada – Japon en matière d’impôts sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-1.html#h-318552"><span class="HTitleText2">Loi de 1986 sur la Convention Canada-Japon en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-2.html#h-318554"><span class="HTitleText2">Loi de mise en oeuvre d’une convention conclue entre le Canada et le Royaume des Pays-Bas, d’une convention conclue entre le Canada et le Japon, d’un accord conclu entre le Canada et la République populaire de Chine et d’un accord conclu entre le Canada et la République de Malte, en vue d’éviter les doubles impositions en matière d’impôts sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="page-2.html#h-318560"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Convention Canada – Luxembourg en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="page-3.html#h-318579"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-4.html#h-318889"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-5.html#h-319191"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-6.html#h-319490"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="page-7.html#h-319792"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="page-8.html#h-320106"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li>
<li><a href="page-9.html#h-320388"><span class="scheduleLabel">ANNEXE 7</span> </a>
</li>
<li><a href="page-10.html#h-320661"><span class="scheduleLabel">ANNEXE 8</span> </a>
</li>
<li><a href="page-11.html#h-320664"><span class="scheduleLabel">ANNEXE 9</span> </a>
</li></ul>
</li></ul>

</nav>

