<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Representation Act, 1985</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-427447"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-427450"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Constitution Act, 1867</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-427454"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Electoral Boundaries Readjustment for 1981 Census</span></a>
</li>
<li><span class='sectionRange'>5 to 11 - </span><a href="#h-427460"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Electoral Boundaries Readjustment Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-427464"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

