<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Service Fees Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-445342"><span class="HTitleText1">Short title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-445345"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-445363"><span class="HTitleText1">Performance Standards</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-445386"><span class="HTitleText1">Consultation and Parliamentary Review</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-445445"><span class="HTitleText1">Annual Adjustment</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-445460"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-445478"><span class="HTitleText1">Low-materiality Fees</span></a>
</li></ul>
</li></ul>

</nav>

