<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Bridges Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-33977"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-33982"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-33990"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-33995"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-34086"><span class="HTitleText1">Punishment</span></a>
</li></ul>
</li></ul>

</nav>

