<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’Accord définitif nisga’a</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-356442"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-356445"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-356456"><span class="HTitleText1">Accord définitif nisga’a</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-356477"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-356512"><span class="HTitleText1">Lois de la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-356515"><span class="HTitleText1">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-356526"><span class="HTitleText1">Procédures judiciaires ou administratives</span></a>
</li>
<li><span class='sectionRange'>21 à 26 - </span><a href="page-1.html#h-356536"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-1.html#h-356538"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

