<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada National Parks Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-360227"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-360230"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-360255"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-360258"><span class="HTitleText1">National Parks of Canada</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-360301"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-360335"><span class="HTitleText1">Park Lands</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-360375"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-360446"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-360508"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-360810"><span class="HTitleText1">Mitigation of Environmental Damage</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-5.html#h-360818"><span class="HTitleText1">Park Communities</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-5.html#h-360852"><span class="HTitleText1">Provisions for Particular Parks</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-360883"><span class="HTitleText1">Park Reserves</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-6.html#h-360965"><span class="HTitleText1">National Historic Sites of Canada</span></a>
</li>
<li><span class='sectionRange'>43 to 46 - </span><a href="page-6.html#h-360975"><span class="HTitleText1">Repeals</span></a>
</li>
<li><span class='sectionRange'>47 to 56 - </span><a href="page-6.html#h-360977"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>68 to 70.1 - </span><a href="page-6.html#h-360981"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-6.html#h-360983"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-7.html#h-360994"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - National Parks of Canada</span></a>
</li>
<li><a href="page-8.html#h-362395"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - National Park Reserves of Canada</span></a>
</li>
<li><a href="page-9.html#h-363258"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Protected Species</span></a>
</li>
<li><a href="page-10.html#h-363277"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-11.html#h-363287"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - Commercial Ski Areas</span></a>
</li></ul>
</li></ul>

</nav>

