<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les offices des produits agricoles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-231725"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-231730"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-231767"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Conseil national des produits agricoles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-231768"><span class="HTitleText2">Création</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-231795"><span class="HTitleText2">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-231835"><span class="HTitleText2">Audiences publiques</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-231860"><span class="HTitleText2">Organisation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-231881"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-231886"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Offices de commercialisation des produits de ferme</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-231887"><span class="HTitleText2">Création</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-231921"><span class="HTitleText2">Composition des offices</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-231944"><span class="HTitleText2">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-231985"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-232006"><span class="HTitleText2">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-232022"><span class="HTitleText2">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-232027"><span class="HTitleText2">Accords</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-232036"><span class="HTitleText2">Inspecteurs</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-232057"><span class="HTitleText2">Recouvrement des dettes dues à un office</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-232062"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-232079"><span class="HTitleText2">Dissolution des offices</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-232084"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Offices de promotion et de recherche</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-232085"><span class="HTitleText2">Création</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

