<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Extradition Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-212737"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-212740"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-212768"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Extradition from Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-212769"><span class="HTitleText2">Extraditable Conduct</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-212793"><span class="HTitleText2">Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-212796"><span class="HTitleText2">Publication of Extradition Agreements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-212804"><span class="HTitleText2">Designated States and Entities</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-212810"><span class="HTitleText2">Specific Agreements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-212818"><span class="HTitleText2">Minister’s Power to Receive Requests</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-212824"><span class="HTitleText2">Warrant for Provisional Arrest</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-212860"><span class="HTitleText2">Authority to Proceed</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-212873"><span class="HTitleText2">Arrest or Summons Following Authority to Proceed</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-212889"><span class="HTitleText2">Appearance</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-212938"><span class="HTitleText2">Substitution and Amendment of Authority to Proceed</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-212948"><span class="HTitleText2">Extradition Hearing</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-212984"><span class="HTitleText2">Rules of Evidence</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-213024"><span class="HTitleText2">Judge’s Report</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-213033"><span class="HTitleText2">Property</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-213041"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-213069"><span class="HTitleText2">Submissions</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-213075"><span class="HTitleText2">Reasons for Refusal</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-213122"><span class="HTitleText2">Appeal</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-213173"><span class="HTitleText2">Judicial Review of Minister’s Order</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-213201"><span class="HTitleText2">Order of Surrender</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-213241"><span class="HTitleText2">Temporary Surrender</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-213279"><span class="HTitleText2">Remedy</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-213289"><span class="HTitleText2">Consent</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-213313"><span class="HTitleText2">Waiver of Extradition</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-213334"><span class="HTitleText2">Transit</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-213357"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Extradition to Canada</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-213429"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Transitional Provisions, Consequential and Related Amendments and Repeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-213430"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>86 to 88 - </span><a href="#h-213435"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>89 to 128 - </span><a href="#h-213437"><span class="HTitleText2">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>129 and 130 - </span><a href="#h-213439"><span class="HTitleText2">Repeals</span></a>
</li></ul>
</li><li><a href="#h-213442"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

