<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Indian Act Amendment and Replacement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-331684"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-331687"><span class="HTitleText1">Report</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-331690"><span class="HTitleText1">Indian Act</span></a>
</li></ul>
</li></ul>

</nav>

