<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord de libre-échange Canada — Chili</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-42523"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-42526"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-42541"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-42549"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-42552"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-42565"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Mise en oeuvre de l’accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-42566"><span class="HTitleText2">Approbation de l’Accord</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-42569"><span class="HTitleText2">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-42572"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-42579"><span class="HTitleText2">Groupes spéciaux, comités et conseils d’examen scientifique</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-42596"><span class="HTitleText2">Décrets et règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 à 93 - </span><a href="#h-42617"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-42619"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions transitoires et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94 - </span><a href="#h-42620"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-42626"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-42633"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
