<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le directeur des poursuites pénales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-168127"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-168130"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-168135"><span class="HTitleText1">Directeur des poursuites pénales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-168191"><span class="HTitleText1">Adjoints, procureurs et autres personnels</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-168215"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-168223"><span class="HTitleText1">Directives</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-168236"><span class="HTitleText1">Questions d’intérêt général ou public</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-168241"><span class="HTitleText1">Prise en charge</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-168249"><span class="HTitleText1">Rapport annuel</span></a>
</li></ul>
</li></ul>

</nav>

