<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la santé des animaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-246992"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-246995"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-247039"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-247044"><span class="HTitleText1">Lutte contre les maladies et les substances toxiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-247045"><span class="HTitleText2">Déclarations, prélèvements et échantillons</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-247059"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-247086"><span class="HTitleText2">Importation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-247132"><span class="HTitleText2">Exportation d’animaux</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-247157"><span class="HTitleText2">Assistance internationale</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-247160"><span class="HTitleText1">Lieux contaminés et zones de contrôle</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-247246"><span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-247247"><span class="HTitleText2">Installations</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-247279"><span class="HTitleText2">Inspecteurs et agents d’exécution</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-247312"><span class="HTitleText2">Sceaux</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-247320"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-247352"><span class="HTitleText2">Perquisitions</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-247364"><span class="HTitleText2">Mesures consécutives à la saisie</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-247406"><span class="HTitleText1">Disposition et traitement</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-247419"><span class="HTitleText1">Prélèvements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-247422"><span class="HTitleText1">Restriction de responsabilité</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-247431"><span class="HTitleText1">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-247494"><span class="HTitleText1">Redevances et autres frais</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-247513"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>64.1 - </span><a href="#h-247581"><span class="HTitleText1">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>64.2 - </span><a href="#h-247593"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-247602"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-247643"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-247655"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-247660"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-247663"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
