<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yale First Nation Final Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-469945"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-469948"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-469958"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-469971"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-469974"><span class="HTitleText1">Lands</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-469977"><span class="HTitleText1">Taxation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-469982"><span class="HTitleText1">Fisheries</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-469987"><span class="HTitleText1">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-469992"><span class="HTitleText1">Application of Laws of British Columbia</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-469995"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-470026"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-470027"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-470029"><span class="HTitleText2">Fisheries Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-470031"><span class="HTitleText2">Payments in Lieu of Taxes Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-470033"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-470035"><span class="HTitleText2">Specific Claims Tribunal Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-470037"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

