<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Queen Elizabeth II Canadian Research Fund Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-419930"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="page-1.html#h-419935"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-419940"><span class="HTitleText1">The Fund</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-419954"><span class="HTitleText1">Powers and Duties of the Council</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-419979"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

