<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Parliament of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-389913"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-389916"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Senate and House of Commons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-389917"><span class="HTitleText2">Parliament Continued</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-389926"><span class="HTitleText2">Privileges, Immunities and Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-389927"><span class="HTitleText3">Definition</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-389942"><span class="HTitleText3">Publication of Proceedings</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-389966"><span class="HTitleText3">Examination of Witnesses</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-389997"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Senate</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-389998"><span class="HTitleText2">Conflict of Interest</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-390012"><span class="HTitleText2">Deputy Speaker</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="#h-390025"><span class="HTitleText2">Internal Administration</span></a>
</li>
<li><span class='sectionRange'>19.5 - </span><a href="#h-390060"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>19.6 - </span><a href="#h-390079"><span class="HTitleText2">Opinions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-390121"><span class="HTitleText2">Financial Administration</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-390131"><span class="HTitleText2">Senate Ethics Officer</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-390202"><span class="HLabel1">PART III</span> - <span class="HTitleText1">House of Commons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-390203"><span class="HLabel2">DIVISION A</span> - <span class="HTitleText2">Eligibility, Resignation and Vacancies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-390204"><span class="HTitleText3">Simultaneous Candidacies</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-390209"><span class="HTitleText3">Members of Provincial Legislature</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-390231"><span class="HTitleText3">Resignation of Members</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-390255"><span class="HTitleText3">Vacancies</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-390291"><span class="HLabel2">DIVISION B</span> - <span class="HTitleText2">Conflict of Interest</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-390395"><span class="HLabel2">DIVISION C</span> - <span class="HTitleText2">Speaker, Parliamentary Secretaries, Clerk and Other Personnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-390396"><span class="HTitleText3">Deputy Speaker</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-390416"><span class="HTitleText3">Parliamentary Secretaries</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-390430"><span class="HTitleText3">Clerk and Other Personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>49.1 - </span><a href="#h-390439"><span class="HLabel2">DIVISION C.1</span> - <span class="HTitleText2">Caucuses</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-390507"><span class="HLabel2">DIVISION D</span> - <span class="HTitleText2">Board of Internal Economy</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="#h-390508"><span class="HTitleText3">Establishment and Organization</span></a>
</li>
<li><span class='sectionRange'>52.2 - </span><a href="#h-390552"><span class="HTitleText3">Functions of Board</span></a>
</li>
<li><span class='sectionRange'>52.5 - </span><a href="#h-390575"><span class="HTitleText3">By-laws</span></a>
</li>
<li><span class='sectionRange'>52.6 - </span><a href="#h-390594"><span class="HTitleText3">Opinions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>54.1 - </span><a href="#h-390645"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Remuneration of Members of Parliament</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54.1 - </span><a href="#h-390646"><span class="HTitleText2">Remuneration Reference Amount</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-390654"><span class="HTitleText2">Sessional Allowances Before April 1, 2004</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-390704"><span class="HTitleText2">Sessional Allowances From April 1, 2004</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-390720"><span class="HTitleText2">General Provisions Regarding Sessional Allowances</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-390753"><span class="HTitleText2">Salaries and Additional Allowances of Members Before April 1, 2004</span></a>
</li>
<li><span class='sectionRange'>62.1 - </span><a href="#h-390786"><span class="HTitleText2">Salaries and Additional Allowances of Members From April 1, 2004</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-390844"><span class="HTitleText2">Expenses</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-390871"><span class="HTitleText2">Adjustment of Salaries and Allowances</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-390881"><span class="HTitleText2">Allowances after Dissolution</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-390886"><span class="HTitleText2">Severance Allowance</span></a>
</li>
<li><span class='sectionRange'>71.1 - </span><a href="#h-390930"><span class="HTitleText2">Disability Allowance</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="#h-390951"><span class="HTitleText2">Group Insurance Plans</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-390964"><span class="HTitleText2">Financial Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>72.01 - </span><a href="#h-390974"><span class="HLabel1">PART V</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-390990"><span class="HTitleText2">Library of Parliament</span></a>
</li>
<li><span class='sectionRange'>79.01 - </span><a href="#h-391047"><span class="HTitleText2">Parliamentary Budget Officer</span></a>
</li>
<li><span class='sectionRange'>79.51 - </span><a href="#h-391214"><span class="HTitleText2">Parliamentary Protective Service</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79.51 - </span><a href="#h-391215"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>79.52 - </span><a href="#h-391228"><span class="HTitleText3">Establishment and Mandate</span></a>
</li>
<li><span class='sectionRange'>79.54 - </span><a href="#h-391245"><span class="HTitleText3">Director of Service</span></a>
</li>
<li><span class='sectionRange'>79.55 - </span><a href="#h-391255"><span class="HTitleText3">Arrangement for Physical Security Services</span></a>
</li>
<li><span class='sectionRange'>79.57 - </span><a href="#h-391270"><span class="HTitleText3">Estimates</span></a>
</li>
<li><span class='sectionRange'>79.58 - </span><a href="#h-391275"><span class="HTitleText3">Powers, Privileges, Rights and Immunities</span></a>
</li>
<li><span class='sectionRange'>79.59 - </span><a href="#h-391280"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-391285"><span class="HTitleText2">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-391298"><span class="HTitleText2">Conflict of Interest and Ethics Commissioner</span></a>
</li></ul>
</li><li><a href="#h-391401"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

