<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le transfèrement des délinquants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Transfèrement des délinquants canadiens au Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Transfèrement des délinquants canadiens en détention</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">Transfèrement des délinquants canadiens en libération conditionnelle</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText1">Transfèrement des délinquants canadiens soumis à une ordonnance de probation ou à des conditions équivalentes</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText1">Jeunes contrevenants</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText1">Pardon</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">Transfèrement des délinquants étrangers du Canada</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-10"><span class="HTitleText1">Règlements</span></a>
</li>
<li><a href="#h-11"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
