<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2016 sur l’arrangement fiscal relatif aux territoires du Canada et de Taiwan</a><ul class="TocIndent"><li><a href="#h-40263"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Arrangement entre le Bureau commercial du Canada à Taipei et le Bureau économique et culturel de Taipei au Canada en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="#h-40530"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole d’entente</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
