<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les biens de surplus de la Couronne</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-433361"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-433366"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-433382"><span class="HTitleText1">Biens de surplus</span></a>
</li>
<li><span class='sectionRange'>7. à 12 - </span><a href="#h-433422"><span class="HTitleText1">Corporation de disposition des biens de la Couronne</span></a>
</li>
<li><a href="#h-433458"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
