<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Competition Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-87824"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-87829"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Purpose and Interpretation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1.1 - </span><a href="#h-87830"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-87835"><span class="HTitleText2">Interpretation</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="#h-87926"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-88256"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Mutual Legal Assistance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-88257"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>30.01 - </span><a href="#h-88273"><span class="HTitleText2">Functions of the Minister of Justice</span></a>
</li>
<li><span class='sectionRange'>30.02 - </span><a href="#h-88291"><span class="HTitleText2">Publication of Agreements</span></a>
</li>
<li><span class='sectionRange'>30.03 - </span><a href="#h-88301"><span class="HTitleText2">Requests Made to Canada from Abroad</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30.03 - </span><a href="#h-88302"><span class="HTitleText3">Requests</span></a>
</li>
<li><span class='sectionRange'>30.04 - </span><a href="#h-88307"><span class="HTitleText3">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-88365"><span class="HTitleText3">Evidence for Use Abroad</span></a>
</li>
<li><span class='sectionRange'>30.19 - </span><a href="#h-88493"><span class="HTitleText3">Lending Exhibits</span></a>
</li>
<li><span class='sectionRange'>30.24 - </span><a href="#h-88537"><span class="HTitleText3">Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>30.25 - </span><a href="#h-88545"><span class="HTitleText2">Evidence Obtained by Canada from Abroad</span></a>
</li>
<li><span class='sectionRange'>30.29 - </span><a href="#h-88565"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-88588"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Special Remedies</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-88717"><span class="HLabel1">PART V</span> - <span class="HTitleText1">[Repealed, R.S., 1985, c. 19 (2nd Supp.), s. 29]</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-88718"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Offences in Relation to Competition</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-89016"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Other Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-89017"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-89089"><span class="HTitleText2">Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>74.01 - </span><a href="#h-89169"><span class="HLabel1">PART VII.1</span> - <span class="HTitleText1">Deceptive Marketing Practices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>74.01 - </span><a href="#h-89170"><span class="HTitleText2">Reviewable Matters</span></a>
</li>
<li><span class='sectionRange'>74.09 - </span><a href="#h-89299"><span class="HTitleText2">Administrative Remedies</span></a>
</li>
<li><span class='sectionRange'>74.17 - </span><a href="#h-89439"><span class="HTitleText2">Rules of Procedure</span></a>
</li>
<li><span class='sectionRange'>74.18 - </span><a href="#h-89444"><span class="HTitleText2">Appeals</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-89458"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Matters Reviewable by Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-89459"><span class="HTitleText2">Restrictive Trade Practices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-89460"><span class="HTitleText3">Refusal to Deal</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-89478"><span class="HTitleText3">Price Maintenance</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-89522"><span class="HTitleText3">Exclusive Dealing, Tied Selling and Market Restriction</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-89563"><span class="HTitleText3">Abuse of Dominant Position</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-89619"><span class="HTitleText3">Delivered Pricing</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-89636"><span class="HTitleText3">Foreign Judgments and Laws</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-89668"><span class="HTitleText3">Foreign Suppliers</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-89675"><span class="HTitleText2">Specialization Agreements</span></a>
</li>
<li><span class='sectionRange'>90.1 - </span><a href="#h-89729"><span class="HTitleText2">Agreements or Arrangements that Prevent or Lessen Competition Substantially</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-89782"><span class="HTitleText2">Mergers</span></a>
</li>
<li><span class='sectionRange'>103.1 - </span><a href="#h-89925"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-90061"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Notifiable Transactions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-90062"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-90077"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-90138"><span class="HTitleText2">Exemptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-90139"><span class="HTitleText3">Acquisition of Voting Shares, Assets or Interests</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-90150"><span class="HTitleText3">Combinations</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-90158"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-90168"><span class="HTitleText2">Notice and Information</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-90234"><span class="HTitleText2">Completion of Proposed Transactions</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-90266"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>124.1 - </span><a href="#h-90276"><span class="HLabel1">PART X</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124.1 - </span><a href="#h-90277"><span class="HTitleText2">Commissioner’s Opinions</span></a>
</li>
<li><span class='sectionRange'>124.2 - </span><a href="#h-90285"><span class="HTitleText2">References to Tribunal</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-90297"><span class="HTitleText2">Representations to Boards, Commissions or Other Tribunals</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-90312"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-90317"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

