<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
North American Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-365704"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-365707"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-365722"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-365731"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-365734"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-365749"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Implementation of Agreement Generally</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-365750"><span class="HTitleText2">Approval of Agreement</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-365753"><span class="HTitleText2">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-365756"><span class="HTitleText2">Free Trade Commission</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-365761"><span class="HTitleText2">Canadian Section of Secretariat</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-365780"><span class="HTitleText2">Panels, Committees and Scientific Review Boards</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-365790"><span class="HTitleText2">Orders and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 to 241 - </span><a href="#h-365811"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Related and Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-365813"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-365820"><span class="scheduleLabel"><span class="wb-invisible">Footnote </span><sup>*</sup>SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

