<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le ministère des Femmes et de l’Égalité des genres</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-454095"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-454098"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-454106"><span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-454121"><span class="HTitleText1">Comités</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-454129"><span class="HTitleText1">Dispositions transitoires</span></a>
</li></ul>
</li></ul>

</nav>

