<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la restructuration du secteur des pêches de l’Atlantique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-6758"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-6763"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-6776"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-6781"><span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6794"><span class="HTitleText1">Contributions, prêts et garanties</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6810"><span class="HTitleText1">Rapport</span></a>
</li></ul>
</li></ul>

</nav>

