<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la protection de l’information</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-375581"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-375586"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-375655"><span class="HTitleText1">Infractions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-375656"><span class="HTitleText2">Infractions diverses</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-375694"><span class="HTitleText2">Renseignements opérationnels spéciaux et personnes astreintes au secret à perpétuité</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-375804"><span class="HTitleText2">Communication à des entités étrangères ou groupes terroristes</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-375832"><span class="HTitleText2">Espionnage économique</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-375852"><span class="HTitleText2">Menaces, accusations ou violence pour le compte d’une entité étrangère ou d’un groupe terroriste</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-375864"><span class="HTitleText2">Hébergement ou dissimulation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-375874"><span class="HTitleText2">Actes préparatoires</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-375887"><span class="HTitleText2">Tentative, complicité, etc.</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-3.html#h-375892"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="page-4.html#h-375924"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

