<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Transportation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-54105"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-54108"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-54111"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-54123"><span class="HTitleText1">National Transportation Policy</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-54133"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="#h-54166"><span class="HTitleText1">Power of the Governor in Council</span></a>
</li>
<li><span class='sectionRange'>6.2 - </span><a href="#h-1171098"><span class="HTitleText1">Electronic Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-54171"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-54172"><span class="HTitleText2">Canadian Transportation Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-54173"><span class="HTitleText3">Continuation and Organization</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-54214"><span class="HTitleText3">Remuneration</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-54229"><span class="HTitleText3">Chairperson</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-54236"><span class="HTitleText3">Quorum</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-54247"><span class="HTitleText3">Rules</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-54253"><span class="HTitleText3">Head Office</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-54261"><span class="HTitleText3">Staff</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-54266"><span class="HTitleText3">Records</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-54281"><span class="HTitleText3">Powers of Agency</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-54349"><span class="HTitleText3">Mediation</span></a>
</li>
<li><span class='sectionRange'>36.11 - </span><a href="#h-54369"><span class="HTitleText3">Information and Informal Dispute Resolution Services</span></a>
</li>
<li><span class='sectionRange'>36.2 - </span><a href="#h-54381"><span class="HTitleText3">Mediation or Arbitration</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-54393"><span class="HTitleText3">Inquiries</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-54405"><span class="HTitleText3">Review and Appeal</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-54417"><span class="HTitleText3">Report of Agency</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-54433"><span class="HTitleText2">Governor in Council</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-54434"><span class="HTitleText3">Directions to Agency</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-54446"><span class="HTitleText3">Extraordinary Disruptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-54471"><span class="HTitleText2">Minister</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-54473"><span class="HTitleText3">Inquiries</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-54483"><span class="HTitleText3">Transportation Information</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-54589"><span class="HTitleText3">Industry Review</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-54602"><span class="HTitleText3">Review of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>53.1 - </span><a href="#h-54620"><span class="HTitleText2">Review of Mergers and Acquisitions</span></a>
</li>
<li><span class='sectionRange'>53.7 - </span><a href="#h-1122281"><span class="HTitleText2">Review of Arrangements Involving Two or More Transportation Undertakings Providing Air Services</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-54702"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="#h-54708"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Air Transportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-54709"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-54782"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-54801"><span class="HTitleText2">Licence for Domestic Service</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-54929"><span class="HTitleText2">Licence for Scheduled International Service</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-54965"><span class="HTitleText2">Licence for Non-scheduled International Service</span></a>
</li>
<li><span class='sectionRange'>75.1 - </span><a href="#h-54995"><span class="HTitleText2">Issuance of International Charter Permits</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-55000"><span class="HTitleText2">Ministerial Directions for International Service</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-55018"><span class="HTitleText2">Duties and Powers of Agency</span></a>
</li>
<li><span class='sectionRange'>85.1 - </span><a href="#h-55064"><span class="HTitleText2">Air Travel Complaints</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-55080"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-55143"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Railway Transportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-55144"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-55190"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Construction and Operation of Railways</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>90 - </span><a href="#h-55191"><span class="HTitleText3">Certificate of Fitness</span></a>
</li>
<li><span class='sectionRange'>93.1 - </span><a href="#h-55246"><span class="HTitleText3">Liability Insurance</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-55272"><span class="HTitleText3">General Powers of Railway Companies</span></a>
</li>
<li><span class='sectionRange'>95.1 - </span><a href="#h-55287"><span class="HTitleText3">Noise and Vibration</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-55317"><span class="HTitleText3">Land Transfer</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-55334"><span class="HTitleText3">Railway Lines</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-55351"><span class="HTitleText3">Road and Utility Crossings</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-55368"><span class="HTitleText3">Private Crossings</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-55378"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Financial Transactions of Railway Companies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-55379"><span class="HTitleText3">Security</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-55391"><span class="HTitleText3">Documents Dealing with Rolling Stock</span></a>
</li>
<li><span class='sectionRange'>105.1 - </span><a href="#h-55403"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-55416"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Rates, Tariffs and Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-55417"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-55431"><span class="HTitleText3">Rates and Conditions of Service</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-55434"><span class="HTitleText3">Level of Services</span></a>
</li>
<li><span class='sectionRange'>116.1 - </span><a href="#h-55518"><span class="HTitleText3">Traffic of Grain</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-55522"><span class="HTitleText3">Tariffs — General</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-55535"><span class="HTitleText3">Tariffs — Freight</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-55571"><span class="HTitleText3">Joint Rates</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-55601"><span class="HTitleText3">Confidential Contracts</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-55632"><span class="HTitleText3">Interswitching</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-55679"><span class="HTitleText3">Long-haul Interswitching</span></a>
</li>
<li><span class='sectionRange'>136.9 - </span><a href="#h-55828"><span class="HTitleText3">Interchanges</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-55840"><span class="HTitleText3">Means to Deal with Carriers’ Liability</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-55856"><span class="HTitleText3">Running Rights and Joint Track Usage</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-55877"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">Transferring and Discontinuing the Operation of Railway Lines</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-56086"><span class="HLabel2">DIVISION VI</span> - <span class="HTitleText2">Transportation of Western Grain</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="#h-56087"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-56108"><span class="HTitleText3">Application of Division IV</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-56111"><span class="HTitleText3">Tariffs</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-56119"><span class="HTitleText3">Maximum Grain Revenue Entitlement</span></a>
</li>
<li><span class='sectionRange'>151.1 - </span><a href="#h-56184"><span class="HTitleText3">List of Available Sidings</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-56194"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>152.1 - </span><a href="#h-56206"><span class="HLabel2">DIVISION VI.1</span> - <span class="HTitleText2">Public Passenger Service Providers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152.1 - </span><a href="#h-56207"><span class="HTitleText3">Dispute Resolution</span></a>
</li>
<li><span class='sectionRange'>152.4 - </span><a href="#h-56231"><span class="HTitleText3">Agreements</span></a>
</li></ul>
</li><li><span class='sectionRange'>152.5 - </span><a href="#h-56241"><span class="HLabel2">DIVISION VI.2</span> - <span class="HTitleText2">Liability and Compensation in Case of Railway Accidents Involving Designated Goods</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152.5 - </span><a href="#h-56242"><span class="HTitleText3">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>152.7 - </span><a href="#h-56258"><span class="HTitleText3">Liability</span></a>
</li>
<li><span class='sectionRange'>153.4 - </span><a href="#h-56314"><span class="HTitleText3">Fund for Railway Accidents Involving Designated Goods</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153.4 - </span><a href="#h-56315"><span class="HTitleText4">Establishment of Fund</span></a>
</li>
<li><span class='sectionRange'>153.7 - </span><a href="#h-56341"><span class="HTitleText4">Administrator and Deputy Administrator</span></a>
</li>
<li><span class='sectionRange'>154.4 - </span><a href="#h-56395"><span class="HTitleText4">Claims</span></a>
</li>
<li><span class='sectionRange'>155.2 - </span><a href="#h-56461"><span class="HTitleText4">Proceedings Against Railway Company</span></a>
</li>
<li><span class='sectionRange'>155.3 - </span><a href="#h-56469"><span class="HTitleText4">Levies</span></a>
</li>
<li><span class='sectionRange'>155.92 - </span><a href="#h-56607"><span class="HTitleText4">Administration of Fund</span></a>
</li></ul>
</li><li><span class='sectionRange'>155.97 - </span><a href="#h-56669"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>155.98 - </span><a href="#h-56681"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="#h-56686"><span class="HLabel2">DIVISION VII</span> - <span class="HTitleText2">Other Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-56687"><span class="HTitleText3">Accounting</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-56699"><span class="HTitleText3">Determination of Costs</span></a>
</li>
<li><span class='sectionRange'>157.1 - </span><a href="#h-56717"><span class="HTitleText3">Agreements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-56733"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Arbitrations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-56734"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Final Offer Arbitration</span></a>
</li>
<li><span class='sectionRange'>169.31 - </span><a href="#h-56934"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Arbitration on Level of Services</span></a>
</li></ul>
</li><li><span class='sectionRange'>169.5 - </span><a href="#h-57102"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Transportation of Persons with Disabilities</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-57123"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-57124"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>176.1 - </span><a href="#h-57138"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>181.2 - </span><a href="#h-1191823"><span class="HTitleText2">Production Order</span></a>
</li></ul>
</li><li><span class='sectionRange'>182 to 184 - </span><a href="#h-57261"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Repeals, Transitional Provisions, Consequential and Conditional Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>182 to 184 - </span><a href="#h-57262"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-57275"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>202 to 274 - </span><a href="#h-57329"><span class="HTitleText2">Consequential and Related Amendments</span></a>
</li>
<li><span class='sectionRange'>275 to 277 - </span><a href="#h-57331"><span class="HTitleText2">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-57333"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-57337"><span class="scheduleLabel">SCHEDULE I / <span class="otherLang" lang="fr">ANNEXE I</span></span> </span></a>
</li>
<li><a href="#h-57355"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Grain, Crop or Product</span></a>
</li>
<li><a href="#h-57421"><span class="scheduleLabel">SCHEDULE III / <span class="otherLang" lang="fr">ANNEXE III</span></span> )</span> - <span class="scheduleTitleText"> - UN Numbers for Dangerous Goods / <span class="otherLang" lang="fr">Numéros ONU de marchandises dangereuses</span></span></a>
</li>
<li><a href="#h-57426"><span class="scheduleLabel">SCHEDULE IV</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
