<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le financement des petites entreprises du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-52692"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-52695"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-52712"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-52724"><span class="HTitleText1">Admissibilité</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-52742"><span class="HTitleText1">Responsabilité du ministre</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-52782"><span class="HTitleText1">Droits et frais</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-52792"><span class="HTitleText1">Projets pilotes</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-52804"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-52835"><span class="HTitleText1">Vérification et examen</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-52847"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-52860"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-52869"><span class="HTitleText1">Modification corrélative</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-52871"><span class="HTitleText1">Abrogation</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
