<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Parliamentary Employment and Staff Relations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-389201"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-389204"><span class="HTitleText1">Application of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-389212"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Staff Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-389213"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-389267"><span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-389268"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-389288"><span class="HTitleText3">Rights</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-389296"><span class="HTitleText3">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-389316"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Federal Public Sector Labour Relations and Employment Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-389317"><span class="HTitleText3">Application of Certain Acts</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-389324"><span class="HTitleText3">Powers, Duties and Functions</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-389376"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Collective Bargaining and Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-389377"><span class="HTitleText3">Certification of Bargaining Agents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-389378"><span class="HTitleText4">Application for Certification</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-389390"><span class="HTitleText4">When Application for Certification may be Made</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-389405"><span class="HTitleText4">Determination of Appropriate Bargaining Units</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-389415"><span class="HTitleText4">Certification</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-389439"><span class="HTitleText4">Where Certification Prohibited</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-389451"><span class="HTitleText4">Effect of Certification</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-389465"><span class="HTitleText3">Revocations of Certification</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-389466"><span class="HTitleText4">On Application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-389483"><span class="HTitleText4">For Abandonment or Other Cause</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-389489"><span class="HTitleText4">For Fraud</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-389495"><span class="HTitleText4">Revocation of Certification of Council</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-389501"><span class="HTitleText4">Effect of Revocation: Rights of Employee Organizations and Employees</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-389508"><span class="HTitleText4">Successor Rights</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-389511"><span class="HTitleText3">Negotiation of Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-389512"><span class="HTitleText4">Notice to Bargain Collectively</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-389520"><span class="HTitleText4">Where Notice Given</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-389527"><span class="HTitleText4">Conciliation</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-389536"><span class="HTitleText3">Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-389537"><span class="HTitleText4">Authority to Enter into Agreement</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-389540"><span class="HTitleText4">Provisions of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-389550"><span class="HTitleText4">Duration and Effect</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-389562"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Provisions Applicable to Resolution of Disputes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-389565"><span class="HTitleText3">Arbitration</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-389594"><span class="HTitleText3">Request for Arbitration</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-389615"><span class="HTitleText3">Consideration of Dispute and Award</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-389633"><span class="HTitleText3">Arbitral Award Matters</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-389641"><span class="HTitleText3">Making of Arbitral Award</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-389653"><span class="HTitleText3">Duration and Operation of Arbitral Awards</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-389670"><span class="HTitleText3">Implementation of Arbitral Awards</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-389673"><span class="HTitleText3">Completion and Variation of Arbitral Awards</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-389678"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-389679"><span class="HTitleText3">Right to Present Grievances</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-389694"><span class="HTitleText3">Adjudication of Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-389695"><span class="HTitleText4">Reference to Adjudication</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-389710"><span class="HTitleText4">Appointment of Adjudicators</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-389713"><span class="HTitleText4">Establishment of a Board of Adjudication</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-389723"><span class="HTitleText4">Duty of the Board</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-389746"><span class="HTitleText4">Jurisdiction of Adjudicator</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-389754"><span class="HTitleText4">Decision of Adjudicator</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-389772"><span class="HTitleText4">Expenses of Adjudication</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-389786"><span class="HTitleText4">Enforcement of Obligations of Employer and Employee Organizations</span></a>
</li></ul>
</li><li><span class='sectionRange'>71 - </span><a href="#h-389794"><span class="HTitleText3">Regulations respecting Grievances</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="#h-389813"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-389814"><span class="HTitleText3">Review of Decisions</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-389822"><span class="HTitleText3">Offences relating to Strikes</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-389836"><span class="HTitleText3">Consent to Prosecution</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-389839"><span class="HTitleText3">Protection</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-389844"><span class="HTitleText3">Witness Fees</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-389847"><span class="HTitleText3">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-389850"><span class="HTitleText3">Provision of Facilities and Staff</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-389855"><span class="HTitleText3">Superannuation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-389861"><span class="HTitleText3">Report to Parliament</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-389864"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Standard Hours, Wages, Leave, Etc.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="#h-389865"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-389878"><span class="HTitleText2">Canada Labour Code (Part III)</span></a>
</li></ul>
</li><li><span class='sectionRange'>86.1 - </span><a href="#h-1316559"><span class="HLabel1">PART II.1</span> - <span class="HTitleText1">Pay Equity</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-389883"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Occupational Health and Safety</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-389884"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-389887"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Labour Code</cite> (Part II)</span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-389896"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-389900"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
