<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi modifiant la législation sur les institutions financières et édictant une loi nouvelle</a><ul class="TocIndent"><li><span class='sectionRange'>1 à 20 - </span><a href="#h-217243"><span class="HTitleText1">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>21 à 47 - </span><a href="#h-217245"><span class="HTitleText1">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-217247"><span class="HTitleText1">Loi modifiant la Loi sur la Société d’assurance-dépôts du Canada et d’autres lois en conséquence</span></a>
</li>
<li><span class='sectionRange'>49 à 65 - </span><a href="#h-217249"><span class="HTitleText1">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>66 à 103 - </span><a href="#h-217251"><span class="HTitleText1">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>104 à 111 - </span><a href="#h-217253"><span class="HTitleText1">Loi sur le bureau du surintendant des institutions financières</span></a>
</li>
<li><span class='sectionRange'>112 à 132 - </span><a href="#h-217255"><span class="HTitleText1">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>133 à 161 - </span><a href="#h-217257"><span class="HTitleText1">Loi sur les liquidations</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-217259"><span class="HTitleText1">Loi sur la compensation et le règlement des paiements</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-217262"><span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-217263"><span class="HTitleText2">Loi sur l’Association canadienne des paiements</span></a>
</li>
<li><span class='sectionRange'>164 et 165 - </span><a href="#h-217265"><span class="HTitleText2">Loi sur l’association personnalisée le Bouclier vert du Canada</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-217267"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-217269"><span class="HTitleText2">Renvois à la Loi sur les liquidations</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-217273"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-217277"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
