<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Nordion and Theratronics Divestiture Authorization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-365533"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-365536"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-365551"><span class="HTitleText1">Authorization of Divestiture</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-365559"><span class="HTitleText1">Nordion</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-365630"><span class="HTitleText1">Theratronics</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-365637"><span class="HTitleText1">Transitional and Consequential</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-365664"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

