<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Jewish Heritage Month Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-73087"><span class="HTitleText1">Short title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-73090"><span class="HTitleText1">Canadian Jewish Heritage Month</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
