<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Parks Canada Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-388873"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-388876"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-388901"><span class="HTitleText1">Establishment of Agency</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-388976"><span class="HTitleText1">Organization of Agency</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-388993"><span class="HTitleText1">Human Resources</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-389019"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-389034"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-389086"><span class="HTitleText1">Fees</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-389111"><span class="HTitleText1">Reports and Plans</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="page-2.html#h-389131"><span class="HTitleText1">Application of the Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-389134"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>46 to 61.01 - </span><a href="page-3.html#h-389164"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>61.1 - </span><a href="page-3.html#h-389166"><span class="HTitleText1">Conditional Amendment</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-3.html#h-389168"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-4.html#h-389172"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

