<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi d’harmonisation n<Sup>o</Sup> 1 du droit fédéral avec le droit civil</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Droit fédéral et droit civil de la province de Québec</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Titre</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Code civil du Bas Canada</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Mariage</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la Loi d’interprétation</span></a>
</li>
<li><span class='sectionRange'>9 à 24 - </span><a href="#h-7"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modification de la Loi sur les immeubles fédéraux</span></a>
</li>
<li><span class='sectionRange'>25 à 33 - </span><a href="#h-8"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Modification de la Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>34 à 52 - </span><a href="#h-9"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Modification de la Loi sur la responsabilité civile de l’État et le contentieux administratif</span></a>
</li>
<li><span class='sectionRange'>53 à 128 - </span><a href="#h-10"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Modifications diverses à d’autres lois</span></a>
</li>
<li><span class='sectionRange'>129 à 173 - </span><a href="#h-11"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>174. à 176 - </span><a href="#h-12"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-13"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Disposition transitoire et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="#h-14"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-15"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
