<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Supporting Vulnerable Seniors and Strengthening Canada’s Economy Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-443066"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-443069"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the Income Tax Act, a Related Act and a Related Regulation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-443070"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-443073"><span class="HTitleText2">Canada Disability Savings Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-443077"><span class="HTitleText2">Canada Disability Savings Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-443080"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Measures Relating to Excise Duties and Sales and Excise Taxes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-443081"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-443083"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-443087"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-443090"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-443091"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-443094"><span class="HTitleText2">Canadian Youth Business Foundation</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-443097"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Auditor General Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-443099"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Canada Student Financial Assistance Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-443100"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-443102"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-443105"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Mortgage or Hypothecary Insurance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-443106"><span class="HTitleText2">Enactment of Protection of Residential Mortgage or Hypothecary Insurance Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-443109"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-443110"><span class="HTitleText3">Budget Implementation Act, 2006</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-443112"><span class="HTitleText3">National Housing Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-443116"><span class="HTitleText3">Office of the Superintendent of Financial Institutions Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-443118"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-443121"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-443125"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-443128"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Assessment of Financial Institutions Regulations, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-443129"><span class="HTitleText2">Amendment to the Regulations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-443131"><span class="HTitleText2">Validation</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-443133"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Financial Administration Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-443134"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-443137"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-443140"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Canada Shipping Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="#h-443141"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-443150"><span class="HTitleText2">Consequential Amendment to the Coasting Trade Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

