<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Interpretation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-279141"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-279146"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-279162"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-279172"><span class="HTitleText1">Enacting Clause of Acts</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-279181"><span class="HTitleText1">Operation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-279182"><span class="HTitleText2">Royal Assent</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-279194"><span class="HTitleText2">Day Fixed for Commencement or Repeal</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-279206"><span class="HTitleText2">Regulation Prior to Commencement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-279211"><span class="HTitleText2">Territorial Operation</span></a>
</li></ul>
</li><li><span class='sectionRange'>8.1 - </span><a href="page-1.html#h-279228"><span class="HTitleText1">Rules of Construction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8.1 - </span><a href="page-1.html#h-279229"><span class="HTitleText2">Property and Civil Rights</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-279238"><span class="HTitleText2">Private Acts</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-279243"><span class="HTitleText2">Law Always Speaking</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-279248"><span class="HTitleText2">Imperative and Permissive Construction</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-279253"><span class="HTitleText2">Enactments Remedial</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-279258"><span class="HTitleText2">Preambles and Marginal Notes</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-279267"><span class="HTitleText2">Application of Interpretation Provisions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-279281"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-279286"><span class="HTitleText2">Proclamations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-279297"><span class="HTitleText2">Oaths</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-279307"><span class="HTitleText2">Reports to Parliament</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-279312"><span class="HTitleText2">Corporations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-279326"><span class="HTitleText2">Majority and Quorum</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-279340"><span class="HTitleText2">Appointment, Retirement and Powers of Officers</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-279374"><span class="HTitleText2">Evidence</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-279382"><span class="HTitleText2">Computation of Time</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-279415"><span class="HTitleText2">Miscellaneous Rules</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-279440"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>34.1 - </span><a href="page-2.html#h-279455"><span class="HTitleText2">Powers to Enter Dwelling-houses to Carry out Arrests</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-2.html#h-279462"><span class="HTitleText1">Definitions</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-279584"><span class="HTitleText1">References and Citations</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-279607"><span class="HTitleText1">Repeal and Amendment</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-3.html#h-279653"><span class="HTitleText1">Demise of Crown</span></a>
</li>
<li><a href="page-4.html#h-279664"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

