<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Energy Board Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-379817"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-379822"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-379885"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-379890"><span class="HLabel1">PART I</span> - <span class="HTitleText1">National Energy Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-379891"><span class="HTitleText2">Establishment of the Board</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-379924"><span class="HTitleText2">Executive Officers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-379953"><span class="HTitleText2">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-379967"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-379976"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-379995"><span class="HTitleText2">Powers of the Board</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-380093"><span class="HTitleText2">Orders and Decisions</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-380177"><span class="HTitleText2">Fees, Levies and Charges</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-380193"><span class="HTitleText2">Proof of Documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-380200"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Advisory Functions</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="#h-380231"><span class="HLabel1">PART II.1</span> - <span class="HTitleText1">Oil and Gas Interests, Production and Conservation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28.1 - </span><a href="#h-380232"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>28.2 - </span><a href="#h-380237"><span class="HTitleText2">Declarations of Significant Discovery and Commercial Discovery</span></a>
</li>
<li><span class='sectionRange'>28.3 - </span><a href="#h-380255"><span class="HTitleText2">Operating Licences and Authorizations</span></a>
</li>
<li><span class='sectionRange'>28.4 - </span><a href="#h-380260"><span class="HTitleText2">Chief Conservation Officer and Chief Safety Officer</span></a>
</li>
<li><span class='sectionRange'>28.7 - </span><a href="#h-380297"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-380311"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Construction, Operation and Abandonment of Pipelines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-380312"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-380341"><span class="HTitleText2">Location of Pipelines</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-380357"><span class="HTitleText2">Plan, Profile and Book of Reference</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-380369"><span class="HTitleText2">Determination of Detailed Route and Approval</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-380421"><span class="HTitleText2">Errors</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-380435"><span class="HTitleText2">Duties of Registrars of Deeds</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-380449"><span class="HTitleText2">Further Plans</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-380454"><span class="HTitleText2">Deviations</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-380464"><span class="HTitleText2">Diversion or Relocation</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-380480"><span class="HTitleText2">Leave to Open Pipelines</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-380488"><span class="HTitleText2">Regulation of Construction, Operation and Abandonment</span></a>
</li>
<li><span class='sectionRange'>48.11 - </span><a href="#h-380532"><span class="HTitleText2">Polluter Pays Principle</span></a>
</li>
<li><span class='sectionRange'>48.12 - </span><a href="#h-380537"><span class="HTitleText2">Liability</span></a>
</li>
<li><span class='sectionRange'>48.13 - </span><a href="#h-380575"><span class="HTitleText2">Financial Requirements</span></a>
</li>
<li><span class='sectionRange'>48.15 - </span><a href="#h-380608"><span class="HTitleText2">Reimbursement by Company</span></a>
</li>
<li><span class='sectionRange'>48.16 - </span><a href="#h-380613"><span class="HTitleText2">Designated Company</span></a>
</li>
<li><span class='sectionRange'>48.18 - </span><a href="#h-380644"><span class="HTitleText2">Pipeline Claims Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48.18 - </span><a href="#h-380645"><span class="HTitleText3">Establishment</span></a>
</li>
<li><span class='sectionRange'>48.24 - </span><a href="#h-380685"><span class="HTitleText3">Chairperson and Staff</span></a>
</li>
<li><span class='sectionRange'>48.29 - </span><a href="#h-380709"><span class="HTitleText3">Tribunal’s Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>48.35 - </span><a href="#h-380742"><span class="HTitleText3">Claims for Compensation</span></a>
</li>
<li><span class='sectionRange'>48.39 - </span><a href="#h-380780"><span class="HTitleText3">Payment by the Board</span></a>
</li>
<li><span class='sectionRange'>48.43 - </span><a href="#h-380808"><span class="HTitleText3">Reconsideration</span></a>
</li>
<li><span class='sectionRange'>48.45 - </span><a href="#h-380828"><span class="HTitleText3">Judicial Review</span></a>
</li>
<li><span class='sectionRange'>48.46 - </span><a href="#h-380833"><span class="HTitleText3">Appropriation and Repayment</span></a>
</li>
<li><span class='sectionRange'>48.47 - </span><a href="#h-380854"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>48.49 - </span><a href="#h-380886"><span class="HTitleText2">Measures Related to Abandonment</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-380896"><span class="HTitleText2">Inspection Officers</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-380972"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-381069"><span class="HTitleText2">Revocation and Suspension</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-381079"><span class="HTitleText2">Conditions to Certificate</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-381084"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="#h-381114"><span class="HLabel1">PART III.1</span> - <span class="HTitleText1">Construction and Operation of Power Lines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58.1 - </span><a href="#h-381115"><span class="HTitleText2">International Power Lines</span></a>
</li>
<li><span class='sectionRange'>58.11 - </span><a href="#h-381120"><span class="HTitleText2">Permits</span></a>
</li>
<li><span class='sectionRange'>58.15 - </span><a href="#h-381149"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>58.17 - </span><a href="#h-381200"><span class="HTitleText2">Location and Construction under Provincial Law</span></a>
</li>
<li><span class='sectionRange'>58.23 - </span><a href="#h-381230"><span class="HTitleText2">Location and Construction under Federal Law</span></a>
</li>
<li><span class='sectionRange'>58.28 - </span><a href="#h-381283"><span class="HTitleText2">Diversions, Relocations, Crossings and Abandonments</span></a>
</li>
<li><span class='sectionRange'>58.35 - </span><a href="#h-381424"><span class="HTitleText2">Permits and Certificates</span></a>
</li>
<li><span class='sectionRange'>58.38 - </span><a href="#h-381447"><span class="HTitleText2">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>58.4 - </span><a href="#h-381465"><span class="HTitleText2">Interprovincial Power Lines</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.5 - </span><a href="#h-381475"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Traffic, Tolls and Tariffs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58.5 - </span><a href="#h-381476"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-381481"><span class="HTitleText2">Powers of Board</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-381486"><span class="HTitleText2">Filing of Tariff</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-381500"><span class="HTitleText2">Just and Reasonable Tolls</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-381515"><span class="HTitleText2">Disallowance of Tariff</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-381524"><span class="HTitleText2">Discrimination</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-381543"><span class="HTitleText2">Contracts Limiting Liabilities</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-381553"><span class="HTitleText2">Transmission, etc., of Oil or Gas</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-381569"><span class="HTitleText2">Transmission and Sale of Gas</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-381579"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Powers of Pipeline Companies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-381580"><span class="HTitleText2">General Powers</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-381617"><span class="HTitleText2">Taking and Using Lands</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-381673"><span class="HTitleText2">Mines and Minerals</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-381701"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-381712"><span class="HTitleText2">Acquisition of Lands</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-381746"><span class="HTitleText2">Negotiation Proceedings</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-381762"><span class="HTitleText2">Arbitration Proceedings</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-381909"><span class="HTitleText2">Right of Entry</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-381940"><span class="HTitleText2">Construction over other Utility Lines, etc.</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-382062"><span class="HTitleText2">Executions, etc.</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-382075"><span class="HTitleText2">Construing Special Acts</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="#h-382082"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Exports and Imports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-382083"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Oil and Gas</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-382084"><span class="HTitleText3">Prohibition</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-382089"><span class="HTitleText3">Issuance of Licences</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-382123"><span class="HTitleText3">Revocation and Suspension</span></a>
</li>
<li><span class='sectionRange'>119.01 - </span><a href="#h-382135"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>119.02 - </span><a href="#h-382158"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Electricity</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119.02 - </span><a href="#h-382159"><span class="HTitleText3">Prohibition</span></a>
</li>
<li><span class='sectionRange'>119.03 - </span><a href="#h-382164"><span class="HTitleText3">Issuance of Permits</span></a>
</li>
<li><span class='sectionRange'>119.07 - </span><a href="#h-382196"><span class="HTitleText3">Orders</span></a>
</li>
<li><span class='sectionRange'>119.08 - </span><a href="#h-382210"><span class="HTitleText3">Issuance of Licences</span></a>
</li>
<li><span class='sectionRange'>119.09 - </span><a href="#h-382225"><span class="HTitleText3">Conditions of Permits and Licences</span></a>
</li>
<li><span class='sectionRange'>119.094 - </span><a href="#h-382252"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>119.1 to 119.7 - </span><a href="#h-382264"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Implementation of Free Trade Agreements</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-382309"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Offences, Punishment and Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>123 - </span><a href="#h-382329"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Interprovincial Oil and Gas Trade</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-382330"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-382339"><span class="HTitleText2">Control by Board</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-382347"><span class="HTitleText2">Issue of Licences</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-382364"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-382373"><span class="HTitleText2">Offences, Punishment and Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="#h-382383"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="#h-382384"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-382421"><span class="HTitleText2">Sentencing</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-382491"><span class="HTitleText2">Report to Parliament</span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-382496"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="#h-382497"><span class="HTitleText2">Board’s Powers</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-382521"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-382550"><span class="HTitleText2">Rules about Violations</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-382575"><span class="HTitleText2">Reviews</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-382610"><span class="HTitleText2">Responsibility</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-382619"><span class="HTitleText2">Recovery of Penalties</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-382634"><span class="HTitleText2">General</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
