<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi donnant effet à l’exigence de clarté formulée par la Cour suprême du Canada dans son avis sur le Renvoi sur la sécession du Québec</a></li></ul>

</nav>
</div></section>
