<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Centre international des droits de la personne et du développement démocratique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Constitution du centre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Mission, capacité et pouvoirs du centre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-6"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-7"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-8"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-9"><span class="HTitleText1">Modification corrélative</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
