<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Surplus Crown Assets Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-443841"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-443846"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-443863"><span class="HTitleText1">Surplus Property</span></a>
</li>
<li><span class='sectionRange'>7. to 12 - </span><a href="#h-443903"><span class="HTitleText1">Crown Assets Disposal Corporation</span></a>
</li>
<li><a href="#h-443939"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

