<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Framework on Palliative Care in Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-237430"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-237433"><span class="HTitleText1">Framework on Palliative Care in Canada</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-237451"><span class="HTitleText1">State of Palliative Care in Canada</span></a>
</li></ul>
</li></ul>

</nav>

