<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Disability Tax Credit Promoters Restrictions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-172649"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-172652"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-172666"><span class="HTitleText1">Promoter’s Fee</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-172681"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-172686"><span class="HTitleText1">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-172689"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-172695"><span class="HTitleText1">Application of Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-172698"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-1.html#h-172699"><span class="HTitleText2">Tax Court of Canada Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-1.html#h-172701"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

