<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Coastal Fisheries Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-87204"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-87209"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-87250"><span class="HTitleText1">Foreign Fishing Vessels</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-87304"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-87337"><span class="HTitleText1">Inspection, Arrest, Seizure and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-87428"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-87478"><span class="HTitleText1">Application of Criminal Law</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-87517"><span class="HTitleText1">Jurisdiction of Courts</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
