<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Electoral Boundaries Readjustment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-213517"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-213522"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-213536"><span class="HTitleText1">Electoral Boundaries Commissions</span></a>
</li>
<li><span class='sectionRange'>12.1 - </span><a href="#h-213599"><span class="HTitleText1">Commencement and Preparation of Report</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-213671"><span class="HTitleText1">Completion of Report</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-213714"><span class="HTitleText1">Representation Order</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="#h-213761"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

