<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les coopératives de l’énergie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-99713"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-99716"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-99740"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Société coopérative de l’énergie</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-99774"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Société coopérative de développement énergétique</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-99854"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-99868"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Statuts constitutifs de la société</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
