<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1994 sur les opérations portuaires de la côte ouest</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Reprise des opérations de débardage</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Obligations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Choix de l’offre finale</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">Modifications ultérieures de la convention collective</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText1">Sanction</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-8"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-9"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Membres de l’association patronale</span></a>
</li>
<li><a href="#h-10"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Sections du syndicat</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
