<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la salubrité de l’eau potable des Premières Nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-419125"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-419128"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-419148"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-419210"><span class="HTitleText1">Autres lois</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-419220"><span class="HTitleText1">Limites de responsabilité, moyens de défense et immunités</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-419238"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

