<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Charte canadienne des droits des victimes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-74180"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-74183"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-74204"><span class="HTitleText1">Droits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-74205"><span class="HTitleText2">Droit à l’information</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-74219"><span class="HTitleText2">Droit à la protection</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-74230"><span class="HTitleText2">Droit de participation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-74235"><span class="HTitleText2">Droit au dédommagement</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-74240"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-74279"><span class="HTitleText1">Recours</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
