<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Privacy Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-397172"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-397177"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-397182"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-397227"><span class="HTitleText1">Designation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-397235"><span class="HTitleText1">Collection, Retention and Disposal of Personal Information</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-397260"><span class="HTitleText1">Protection of Personal Information</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-397331"><span class="HTitleText1">Personal Information Banks</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-397341"><span class="HTitleText1">Personal Information Index</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-397361"><span class="HTitleText1">Access to Personal Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-397362"><span class="HTitleText2">Right of Access</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-397379"><span class="HTitleText2">Requests for Access</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-397414"><span class="HTitleText2">Access</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-397430"><span class="HTitleText1">Exemptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-397431"><span class="HTitleText2">Exempt Banks</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-397443"><span class="HTitleText2">Responsibilities of Government</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-397525"><span class="HTitleText2">Personal Information</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-397530"><span class="HTitleText2">Privilege and Professional Secrecy</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-397539"><span class="HTitleText2">Medical Records</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-397544"><span class="HTitleText1">Complaints</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-397570"><span class="HTitleText1">Investigations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-397620"><span class="HTitleText1">Review of Exempt Banks</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-397636"><span class="HTitleText1">Review of Compliance with Sections 4 to 8</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-397648"><span class="HTitleText1">Reports to Parliament</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-397667"><span class="HTitleText1">Review by the Federal Court</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-397737"><span class="HTitleText1">Office of the Privacy Commissioner</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-397738"><span class="HTitleText2">Privacy Commissioner</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-397768"><span class="HTitleText2">Assistant Privacy Commissioner</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-397789"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-397797"><span class="HTitleText2">Delegation</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-397812"><span class="HTitleText2">Special Studies</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-397824"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-397867"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-397875"><span class="HTitleText1">Exclusions</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-397922"><span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-397994"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Government Institutions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
