<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi prévoyant l’indemnisation des militaires ayant subi des blessures pendant leur service</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-325334"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-325337"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-325345"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-325351"><span class="HTitleText1">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-325418"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-325454"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><a href="#h-325460"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

