<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Bridge To Strengthen Trade Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-33423"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-33426"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-33441"><span class="HTitleText1">Construction of the Bridge, Parkway and Related Works</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-33502"><span class="HTitleText1">Operation of the Bridge and Related Works</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-33510"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-33541"><span class="HTitleText1">Information Gathering</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-33547"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-33558"><span class="HTitleText1">Regulatory Powers</span></a>
</li>
<li><a href="#h-33567"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

