<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Civil Air Navigation Services Commercialization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-80847"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-80850"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-80922"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-80925"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-80932"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Commercialization of Civil Air Navigation Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-80933"><span class="HTitleText2">Authority to Transfer</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-80936"><span class="HTitleText2">Not Agent of Her Majesty</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-80939"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Provision of Civil Air Navigation Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-80940"><span class="HTitleText2">Provision of Services</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-80965"><span class="HTitleText2">Designation as Authority for Chicago Convention</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-80970"><span class="HTitleText2">Aeronautical Radio Navigation Services</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-80982"><span class="HTitleText2">Planning and Management of Airspace</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-80985"><span class="HTitleText2">Changing Services and Closing Facilities</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-81007"><span class="HTitleText2">Designated Northern or Remote Services</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-81053"><span class="HTitleText2">Level of Service Policies</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-81069"><span class="HTitleText2">Directions</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-81096"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Charges for Air Navigation Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-81097"><span class="HTitleText2">Right to Impose Charges</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-81113"><span class="HTitleText2">Initial Charges</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-81119"><span class="HTitleText2">New and Revised Charges</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-81125"><span class="HTitleText2">Charging Principles</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-81168"><span class="HTitleText2">Changing Charges</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-81209"><span class="HTitleText2">Special Approval of Charges</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-81243"><span class="HTitleText2">Appeal of Charges</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-81298"><span class="HTitleText2">Liability for Payment</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-81308"><span class="HTitleText2">Seizure and Detention of Aircraft</span></a>
</li></ul>
</li><li><span class='sectionRange'>58 - </span><a href="#h-81324"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Human Resources and Labour Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-81325"><span class="HTitleText2">Designated Employees</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-81348"><span class="HTitleText2">Collective Agreements and Arbitral Awards</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-81427"><span class="HTitleText2">Bargaining Agents</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-81440"><span class="HTitleText2">Severance Pay</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-81450"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Services to Humanitarian or Emergency Flights</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-81511"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Control and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>85 - </span><a href="#h-81512"><span class="HTitleText2">Sending Notices</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-81518"><span class="HTitleText2">Amendment of Letters Patent and By-laws</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-81524"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="#h-81570"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="#h-81571"><span class="HTitleText2">Official Languages</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-81574"><span class="HTitleText2">Authority to Provide Services</span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-81579"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Financial Arrangements</span></a>
</li>
<li><span class='sectionRange'>99 to 106 - </span><a href="#h-81587"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Related, Consequential and Conditional Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 to 106 - </span><a href="#h-81588"><span class="HTitleText2">Related and Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>107 and 108 - </span><a href="#h-81590"><span class="HTitleText2">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-81592"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

