<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord économique et commercial global entre le Canada et l’Union européenne</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-94016"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-94019"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-94032"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-94035"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-94047"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-94055"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’Accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-94056"><span class="HTitleText2">Approbation et représentation au sein du Comité mixte de l’AÉCG</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-94061"><span class="HTitleText2">Tribunaux, groupes spéciaux d’arbitrage et groupes d’experts</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-94075"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-94081"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-94091"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-94092"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-94103"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-94105"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les aliments et drogues</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-94108"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-94113"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-94142"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-94163"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Investissement Canada</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-94166"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-94177"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’arbitrage commercial</cite></span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-94179"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le cabotage</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-94184"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-94199"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les produits antiparasitaires</cite></span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-94205"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-94210"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="#h-94211"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les corporations canadiennes</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-94215"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’énergie nucléaire</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-94217"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-94219"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-94223"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la production de défense</cite></span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-94226"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-94228"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les inventions des fonctionnaires</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-94230"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les marques olympiques et paralympiques</cite></span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-94232"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la croissance économique et la prospérité — Canada-Corée</cite></span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-94234"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="#h-94236"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="#h-94237"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-94245"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-94258"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-94261"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-94264"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-94267"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-94270"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="#h-94273"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>

</nav>

