<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le Jour de la bataille de Vimy</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-452854"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-452857"><span class="HTitleText1">Jour de la bataille de Vimy</span></a>
</li></ul>
</li></ul>

</nav>

