<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Business Development Bank of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-40234"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-40237"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-40261"><span class="HTitleText1">Establishment and Organization of the Bank</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-40262"><span class="HTitleText2">Status of the Bank</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-40272"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-40278"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-40319"><span class="HTitleText2">Officers and Employees</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-40341"><span class="HTitleText2">Remuneration and Benefits</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-40360"><span class="HTitleText1">Specific Powers of the Bank</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-40361"><span class="HTitleText2">Financial Services</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-40432"><span class="HTitleText2">Management Services</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-40445"><span class="HTitleText2">Treasury Activities</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-40465"><span class="HTitleText2">Agreements and Programs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-40472"><span class="HTitleText2">Ancillary Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-40483"><span class="HTitleText1">Capital of the Bank</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-40540"><span class="HTitleText1">Debt-to-equity Ratio</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-40555"><span class="HTitleText1">Conflict of Interest</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-40582"><span class="HTitleText1">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-40617"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-40619"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>44 to 55 - </span><a href="#h-40638"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><a href="#h-40641"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
