<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi canadienne sur les droits de la personne</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-250625"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-250630"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-250635"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Motifs de distinction illicite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-250636"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-250654"><span class="HTitleText2">Actes discriminatoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-2.html#h-250846"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Commission canadienne des droits de la personne</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-2.html#h-250860"><span class="HTitleText2">Pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-250891"><span class="HTitleText2">Rétribution</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-250901"><span class="HTitleText2">Dirigeants et personnel</span></a>
</li>
<li><span class='sectionRange'>38.1 - </span><a href="page-3.html#h-1179272"><span class="HTitleText2">Commissaire à l’accessibilité</span></a>
</li>
<li><span class='sectionRange'>38.3 - </span><a href="page-3.html#h-1306025"><span class="HTitleText2">Commissaire à l’équité salariale</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="page-3.html#h-250974"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Actes discriminatoires et dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="page-4.html#h-251035"><span class="HTitleText2">Enquête</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-4.html#h-251107"><span class="HTitleText2">Conciliation</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-251120"><span class="HTitleText2">Règlement</span></a>
</li>
<li><span class='sectionRange'>48.1 - </span><a href="page-5.html#h-251130"><span class="HTitleText2">Tribunal canadien des droits de la personne</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-251248"><span class="HTitleText2">Instruction des plaintes</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-6.html#h-251353"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-6.html#h-251370"><span class="HTitleText2">Rapports</span></a>
</li>
<li><span class='sectionRange'>61.1 - </span><a href="page-6.html#h-251382"><span class="HTitleText2">Ministre responsable</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-6.html#h-251387"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="page-6.html#h-251410"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Application</span></a>
</li></ul>
</li></ul>

</nav>

