<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2001 sur l’accise</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-3"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Application et administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Personnel assurant l’exécution</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText2">Enquêtes</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Licences, agréments et autorisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Licences et agréments</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Autorisations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText2">Entrepôts d’accise spéciaux</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Boutiques hors taxes</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Tabac</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Réglementation du tabac</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-16"><span class="HTitleText2">Droit sur le tabac</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-17"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-18"><span class="HTitleText2">Droits spéciaux sur les produits du tabac</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="#h-19"><span class="HLabel1">PARTIE 3.1</span> - <span class="HTitleText1">Taxe sur les stocks de cigarettes</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-20"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Alcool</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-21"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-22"><span class="HTitleText2">Alcool en vrac</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-23"><span class="HTitleText2">Contenants spéciaux de spiritueux</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-24"><span class="HTitleText2">Contenants spéciaux de vin</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-25"><span class="HTitleText2">Alcool emballé</span></a>
</li>
<li><span class='sectionRange'>93.1 - </span><a href="#h-26"><span class="HTitleText2">Préparations assujetties à des restrictions</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-27"><span class="HTitleText2">Alcool dénaturé et alcool spécialement dénaturé</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-28"><span class="HTitleText2">Responsabilité en matière de spiritueux en vrac</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-29"><span class="HTitleText2">Responsabilité en matière de vin en vrac</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-30"><span class="HTitleText2">Imposition et paiement du droit sur l’alcool</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-31"><span class="HTitleText2">Assujettissement des exploitants agréés d’entrepôt d’accise et des utilisateurs agréés</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-32"><span class="HTitleText2">Utilisations et sorties d’alcool non assujetties au droit</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-33"><span class="HTitleText2">Détermination du volume d’alcool</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-34"><span class="HTitleText2">Entrepôts d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>158.01 - </span><a href="#h-35"><span class="HLabel1">PARTIE 4.1</span> - <span class="HTitleText1">Cannabis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>158.01 - </span><a href="#h-36"><span class="HTitleText2">Exclusions</span></a>
</li>
<li><span class='sectionRange'>158.02 - </span><a href="#h-37"><span class="HTitleText2">Production et estampillage du cannabis</span></a>
</li>
<li><span class='sectionRange'>158.17 - </span><a href="#h-38"><span class="HTitleText2">Responsabilité en matière de cannabis</span></a>
</li>
<li><span class='sectionRange'>158.19 - </span><a href="#h-39"><span class="HTitleText2">Imposition et acquittement des droits sur le cannabis</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-40"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions générales concernant les droits et autres sommes exigibles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-41"><span class="HTitleText2">Périodes d’exercice</span></a>
</li>
<li><span class='sectionRange'>159.1 - </span><a href="#h-42"><span class="HTitleText2">Périodes de déclaration</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-43"><span class="HTitleText2">Déclarations et paiement des droits et autres sommes</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-44"><span class="HTitleText2">Intérêts</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-45"><span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-46"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-47"><span class="HTitleText2">Opposition aux cotisations</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-48"><span class="HTitleText2">Appel</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-49"><span class="HTitleText2">Registres et renseignements</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-50"><span class="HTitleText2">Faillites et réorganisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-51"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-52"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-53"><span class="HTitleText2">Produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-54"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-55"><span class="HTitleText2">Imposition des pénalités</span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="#h-56"><span class="HTitleText2">Mandats de perquisition</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-57"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-58"><span class="HTitleText2">Sort des choses saisies</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="#h-59"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-60"><span class="HTitleText2">Révision de la pénalité imposée ou de la saisie</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-61"><span class="HTitleText2">Revendication des tiers</span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="#h-62"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-63"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="#h-64"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-65"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Dispositions transitoires, modifications corrélatives et connexes et dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>305 - </span><a href="#h-66"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>321 à 325 - </span><a href="#h-67"><span class="HTitleText2">Modifications corrélatives et connexes</span></a>
</li>
<li><span class='sectionRange'>408 à 411 - </span><a href="#h-68"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>412 à 421 - </span><a href="#h-69"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Modifications concernant la taxe d’accise sur les produits du tabac</span></a>
</li>
<li><span class='sectionRange'>422 à 432 - </span><a href="#h-70"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Modifications concernant les provisions de bord</span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="#h-71"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-178296"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Taux du droit sur les produits du tabac</span></a>
</li>
<li><a href="#h-178313"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Droit additionnel sur les cigares</span></a>
</li>
<li><a href="#h-178322"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Taux des droits spéciaux sur certains produits de tabac fabriqué</span></a>
</li>
<li><a href="#h-178354"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - Taux du droit sur les spiritueux</span></a>
</li>
<li><a href="#h-178364"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - Taux du droit spécial sur les spiritueux</span></a>
</li>
<li><a href="#h-178367"><span class="scheduleLabel">ANNEXE 6</span> <span class="scheduleTitleText"> - Taux du droit sur le vin</span></a>
</li>
<li><a href="#h-178381"><span class="scheduleLabel">ANNEXE 7</span> <span class="scheduleTitleText"> - Droit sur les produits du cannabis</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
