<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Winding-up and Restructuring Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Limitation of Part</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText2">Winding-up Order</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2">Application for Order</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText2">Staying Proceedings</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText2">Effect of Winding-up Order</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText2">Appointment of Liquidators</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-11"><span class="HTitleText2">Powers and Duties of Liquidators</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-12"><span class="HTitleText2">Appointment of Inspectors</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-13"><span class="HTitleText2">Remuneration of Liquidators and Inspectors</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-14"><span class="HTitleText2">Court Discharging Functions of Liquidator</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-15"><span class="HTitleText2">Contributories</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-16"><span class="HTitleText2">Meetings of Creditors</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-17"><span class="HTitleText2">Creditors’ Claims</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-18"><span class="HTitleText2">Secured Claims</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-19"><span class="HTitleText2">Dividend Sheet</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-20"><span class="HTitleText2">Liens</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-21"><span class="HTitleText2">Contestation of Claims</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-22"><span class="HTitleText2">Distribution of Assets</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-23"><span class="HTitleText2">Fraudulent Preferences</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-24"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-25"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-26"><span class="HTitleText2">Rules, Regulations and Forms</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-27"><span class="HTitleText2">Unclaimed Deposits</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-28"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-29"><span class="HTitleText2">Evidence</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-30"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Authorized Foreign Banks</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-31"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Restructuring of Insurance Companies</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
