<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant à promouvoir l’efficacité et la capacité d’adaptation de l’économie canadienne par la réglementation de certaines pratiques qui découragent l’exercice des activités commerciales par voie électronique et modifiant la Loi sur le Conseil de la radiodiffusion et des télécommunications canadiennes, la Loi sur la concurrence, la Loi sur la protection des renseignements personnels et les documents électroniques et la Loi sur les télécommunications</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Incompatibilité</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Obligations et interdictions</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Demande de préservation de données</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Avis de communication</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Mandats</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Engagement</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Procès-verbaux</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText2">Appel à la Cour d’appel fédérale</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Recouvrement des sanctions et autres sommes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-18"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-19"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-20"><span class="HTitleText1">Injonction</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-21"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-22"><span class="HTitleText1">Droit privé d’action</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-23"><span class="HTitleText2">Demande</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-24"><span class="HTitleText2">Audience</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-25"><span class="HTitleText2">Règles propres aux contraventions et aux comportements susceptibles d’examen</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-26"><span class="HTitleText1">Consultation et communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-27"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-28"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-29"><span class="HTitleText1">Modification de la présente loi</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-30"><span class="HTitleText1">Modification De La Loi Sur Le Conseil De La Radiodiffusion Et Des Télécommunications Canadiennes</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-31"><span class="HTitleText1">Modification De La Loi Sur La Concurrence</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-32"><span class="HTitleText1">Modification De La Loi Sur La Protection Des Renseignements Personnels Et Les Documents Électroniques</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-33"><span class="HTitleText1">Modification De La Loi Sur Les Télécommunications</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-34"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
