<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l'Office d'investissement du régime de pensions du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Constitution de l’office</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Gestion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Administrateurs</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText2">Dirigeants</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Diligence</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-12"><span class="HTitleText2">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-13"><span class="HTitleText2">Réunions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Conflit d’intérêts</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-15"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-17"><span class="HTitleText1">Comités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-18"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-19"><span class="HTitleText2">Comité de vérification</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-20"><span class="HTitleText2">Comité de placement</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-21"><span class="HTitleText1">Placements</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-22"><span class="HTitleText1">Gestion financière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-23"><span class="HTitleText2">Exercice</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-24"><span class="HTitleText2">États financiers</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-25"><span class="HTitleText2">Rapport du vérificateur</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-26"><span class="HTitleText2">Vérificateur</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-27"><span class="HTitleText2">Accès aux renseignements</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-28"><span class="HTitleText2">Immunité du vérificateur</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-29"><span class="HTitleText2">Vérification spéciale</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-30"><span class="HTitleText2">Examens spéciaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>50 - </span><a href="#h-31"><span class="HTitleText1">Rapports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="#h-32"><span class="HTitleText2">États financiers trimestriels</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-33"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-34"><span class="HTitleText1">Assemblées publiques</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-35"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-36"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-37"><span class="HTitleText1">Liquidation</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-38"><span class="HTitleText1">Compte du Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>58 à 99 - </span><a href="#h-39"><span class="HTitleText1">Modifications du Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>100 à 107 - </span><a href="#h-40"><span class="HTitleText1">Modifications de la Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>108 et 109 - </span><a href="#h-41"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-42"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-161914"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
