<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’équité dans la rémunération du secteur public</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Obligation d’offrir une rémunération équitable</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Évaluation en matière de rémunération équitable</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Employeurs ayant des employés non syndiqués</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Plaintes</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText1">Employeurs ayant des employés syndiqués</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Arbitrage</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText2">Conciliation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Ratification</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Plaintes</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText1">Commission des relations de travail dans la fonction publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-16"><span class="HTitleText2">Plaintes déposées par les employés non syndiqués</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText2">Plaintes déposées par les employés syndiqués</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-18"><span class="HTitleText2">Dépenses</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-19"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-20"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-21"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-22"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-23"><span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-24"><span class="HTitleText2">Plaintes déposées par des employés non syndiqués</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-25"><span class="HTitleText2">Prise d’effet de dispositions à l’égard des employés syndiqués</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-26"><span class="HTitleText2">Première convention collective après la prise d’effet</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
