<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Statute Revision Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Statute Revision Commission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Public General Statutes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Revision</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Consolidation</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText2">Consolidation of Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Other Duties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-10"><span class="HTitleText2">Annual Statutes</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText2">Other Statutory Material</span></a>
</li></ul>
</li><li><a href="#h-441472"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Model Bill</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
