<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Centre canadien de gestion</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Constitution du centre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Mission et attributions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">Directeur et personnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText2">Directeur</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText2">Personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText1">Services en matière de formation et de recherche</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText1">Redevances</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText1">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>21 à 25 - </span><a href="#h-14"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-15"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
