<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Trade Unions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-451463"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-451468"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-451473"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-451503"><span class="HTitleText1">Constitution and Registration</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-451546"><span class="HTitleText1">Annual Statement</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-451558"><span class="HTitleText1">Respecting Property</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-451577"><span class="HTitleText1">Procedure</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-451591"><span class="HTitleText1">Accounting</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-451616"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-451660"><span class="HTitleText1">Procedure</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-451671"><span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-451681"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Maximum Fees</span></a>
</li>
<li><a href="#h-451688"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Matters To Be Provided for by the Rules of Trade Unions Registered Under This Act</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
