<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian International Trade Tribunal Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-71563"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-71566"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-71642"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-71652"><span class="HTitleText1">Canadian International Trade Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-71653"><span class="HTitleText2">Establishment of Tribunal</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-71719"><span class="HTitleText2">Head Office, Sittings and Quorum</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-71730"><span class="HTitleText2">Powers, Duties and Functions</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-71746"><span class="HTitleText1">Inquiries and Reviews</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-71747"><span class="HTitleText2">References and Mid-Term Reviews</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-72107"><span class="HTitleText2">Complaints by Domestic Producers</span></a>
</li></ul>
</li><li><span class='sectionRange'>30.02 - </span><a href="#h-72408"><span class="HTitleText1">Extension Inquiries</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-72495"><span class="HTitleText1">Complaints by Potential Suppliers</span></a>
</li>
<li><span class='sectionRange'>30.2 - </span><a href="#h-72601"><span class="HTitleText1">Safeguard Measures in Respect of China</span></a>
</li>
<li><span class='sectionRange'>30.27 - </span><a href="#h-72759"><span class="HTitleText1">Safeguard Measures in Respect of Korea</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-72818"><span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-72819"><span class="HTitleText2">Procedural Matters</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-72841"><span class="HTitleText2">By-laws, Rules and Regulations</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-72884"><span class="HTitleText2">Annual Report</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-72889"><span class="HTitleText2">Disclosure of Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>50 and 51 - </span><a href="#h-72980"><span class="HTitleText1">Repeals, Consequential Amendments and Transitional</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 and 51 - </span><a href="#h-72981"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-72983"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-72985"><span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-73058"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-73065"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
