<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les réserves indiennes de la Nouvelle-Écosse</a><ul class="TocIndent"><li><a href="#h-324850"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - (Traduction)</span> - <span class="scheduleTitleText"> - Mémorandum de la convention conclue ce 14e jour d’avril 1959</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
