<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les allocations spéciales pour enfants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-78614"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-78617"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-78626"><span class="HTitleText1">Allocations spéciales</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-78660"><span class="HTitleText1">Protection de l’allocation spéciale</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-78663"><span class="HTitleText1">Montant de l’allocation spéciale</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-78674"><span class="HTitleText1">Recouvrement de l’allocation spéciale</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-78682"><span class="HTitleText1">Renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-78704"><span class="HTitleText1">Commissaire aux serments</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-78712"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>

