<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Olympic and Paralympic Marks Act</a><ul class="TocIndent"><li><span class='sectionRange'>13 - </span><a href="#h-387480"><span class="HTitleText1">Amendment to this Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-387482"><span class="HTitleText1">Related Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-387483"><span class="HTitleText2">Trade-marks Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-387485"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-387492"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Marks</span></a>
</li>
<li><a href="#h-387534"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-387544"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Expressions</span></a>
</li></ul>
</li></ul>

</nav>

