<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal-Provincial Fiscal Arrangements Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-240711"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-240716"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-240744"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Fiscal Equalization Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-240745"><span class="HTitleText2">Fiscal Equalization Payments to Provinces</span></a>
</li>
<li><span class='sectionRange'>3.71 - </span><a href="#h-240937"><span class="HTitleText2">Nova Scotia</span></a>
</li>
<li><span class='sectionRange'>3.91 - </span><a href="#h-241086"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>3.98 - </span><a href="#h-241123"><span class="HLabel1">PART I.01</span> - <span class="HTitleText1">Other Payments</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-241133"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Territorial Financing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-241134"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-241187"><span class="HTitleText2">Territorial Formula Financing Payments</span></a>
</li>
<li><span class='sectionRange'>4.12 - </span><a href="#h-241235"><span class="HTitleText2">Other Payments</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="#h-241242"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-241287"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Fiscal Stabilization Payments to Provinces</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-241351"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Administration Agreements</span></a>
</li>
<li><span class='sectionRange'>8.2 - </span><a href="#h-241412"><span class="HLabel1">PART III.1</span> - <span class="HTitleText1">Sales Tax Harmonization Agreements</span></a>
</li>
<li><span class='sectionRange'>8.8 - </span><a href="#h-241462"><span class="HLabel1">PART III.2</span> - <span class="HTitleText1">Coordinated Cannabis Taxation Agreements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-241490"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Transfer Payments with Respect to the Elimination of Provincial Capital Taxes</span></a>
</li>
<li><span class='sectionRange'>12.02 - </span><a href="#h-241549"><span class="HLabel1">PART IV.01</span> - <span class="HTitleText1">Transfer Payments — Tax in Respect of Stock Option Benefit Deferral Under Part I.01 of the Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>12.1 - </span><a href="#h-241558"><span class="HLabel1">PART IV.1</span> - <span class="HTitleText1">Transfer Payments with Respect to Preferred Share Dividend Taxes Under Parts IV.1 and VI.1 of the Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>12.31 - </span><a href="#h-241582"><span class="HLabel1">PART IV.11</span> - <span class="HTitleText1">Transfer Payments — Tax in Respect of Sift Trusts or Sift Partnerships</span></a>
</li>
<li><span class='sectionRange'>12.4 - </span><a href="#h-241636"><span class="HLabel1">PART IV.2</span> - <span class="HTitleText1">Transfer Payments — Tax on Payments Under Registered Education Savings Plans Under Part X.5 of the Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>12.6 - </span><a href="#h-241645"><span class="HLabel1">PART IV.3</span> - <span class="HTitleText1">Transfer Payments — Tax on Excess Epsp Amounts Under Part Xi.4 of the Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>12.8 - </span><a href="#h-241658"><span class="HLabel1">PART IV.4</span> - <span class="HTitleText1">Transfer Payments with Respect to Federal Taxes — Necessary Information</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-241663"><span class="HLabel1">PART V</span> - <span class="HTitleText1">[Repealed, 2012, c. 19, s. 391]</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-241681"><span class="HLabel1">PART V.1</span> - <span class="HTitleText1">Canada Health Transfer, Canada Social Transfer and Wait Times Reduction Transfer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-241682"><span class="HTitleText2">Canada Health Transfer</span></a>
</li>
<li><span class='sectionRange'>24.3 - </span><a href="#h-241741"><span class="HTitleText2">Canada Social Transfer</span></a>
</li>
<li><span class='sectionRange'>24.61 - </span><a href="#h-241788"><span class="HTitleText2">Wait Times Reduction Transfer</span></a>
</li>
<li><span class='sectionRange'>24.7 - </span><a href="#h-241818"><span class="HTitleText2">Total Equalized Tax Transfer</span></a>
</li>
<li><span class='sectionRange'>24.701 - </span><a href="#h-241887"><span class="HTitleText2">Transition Protection</span></a>
</li>
<li><span class='sectionRange'>24.71 - </span><a href="#h-1241789"><span class="HTitleText2">Additional Payments for Fiscal Year 2019–2020</span></a>
</li>
<li><span class='sectionRange'>24.72 - </span><a href="#h-1310013"><span class="HTitleText2">Additional Payments</span></a>
</li>
<li><span class='sectionRange'>24.8 - </span><a href="#h-241923"><span class="HTitleText2">Payments</span></a>
</li>
<li><span class='sectionRange'>24.9 - </span><a href="#h-241928"><span class="HTitleText2">Reduction or Withholding</span></a>
</li>
<li><span class='sectionRange'>25.6 - </span><a href="#h-242002"><span class="HTitleText2">Additional Withholding and Deduction</span></a>
</li>
<li><span class='sectionRange'>25.7 - </span><a href="#h-242012"><span class="HTitleText2">References in Other Acts</span></a>
</li>
<li><span class='sectionRange'>25.8 - </span><a href="#h-242017"><span class="HTitleText2">Report</span></a>
</li>
<li><span class='sectionRange'>25.9 - </span><a href="#h-242022"><span class="HTitleText2">Parliamentary Review</span></a>
</li>
<li><span class='sectionRange'>25.91 - </span><a href="#h-242030"><span class="HTitleText2">Communiqués</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-242035"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Alternative Payments for Standing Programs</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-242075"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Provincial Taxes and Fees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-242076"><span class="HTitleText2">Interpretation and Amendments to Schedules</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-242102"><span class="HTitleText2">Reciprocal Taxation Agreements</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-242116"><span class="HTitleText2">Payment in Respect of Provincial Taxes and Fees by Crown Corporations</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-242138"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-242147"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-242148"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-242166"><span class="HTitleText2">Softwood Lumber Products Export Charge Act, 2006</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-242174"><span class="HTitleText2">Payment out of Consolidated Revenue Fund</span></a>
</li></ul>
</li><li><a href="#h-242180"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-242241"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
