<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Payments Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Act Binding on Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canadian Payments Association</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText2">Establishment and Membership</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Head Office</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Chairperson</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText2">President</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText2">Duties and Powers of Board</span></a>
</li>
<li><span class='sectionRange'>19.2 - </span><a href="#h-12"><span class="HTitleText2">Disallowance</span></a>
</li>
<li><span class='sectionRange'>19.3 - </span><a href="#h-13"><span class="HTitleText2">Directives</span></a>
</li>
<li><span class='sectionRange'>19.4 - </span><a href="#h-14"><span class="HTitleText2">Information Requirements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText2">Committees</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Budgets</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-17"><span class="HTitleText2">Annual Meeting</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-18"><span class="HTitleText2">Auditor</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-19"><span class="HTitleText2">Fiscal Year</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-20"><span class="HTitleText2">Electronic Meetings</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-21"><span class="HTitleText2">Rights and Duties of Members</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-22"><span class="HTitleText2">Insolvency</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-23"><span class="HTitleText2">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-24"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-25"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Designated Payment Systems</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-26"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-27"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-28"><span class="HTitleText2">Designation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-29"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-30"><span class="HTitleText2">Guidelines and Directives</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-31"><span class="HTitleText2">Information Requirements</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-32"><span class="HTitleText2">Participants</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-33"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
