<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le multiculturalisme canadien</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-71406"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-71409"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-71419"><span class="HTitleText1">Politique canadienne du multiculturalisme</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-71441"><span class="HTitleText1">Mise en oeuvre de la politique canadienne du multiculturalisme</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-71472"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
