<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada-Chile Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-43553"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-43556"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-43571"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-43579"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-43582"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-43595"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Implementation of Agreement Generally</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-43596"><span class="HTitleText2">Approval of Agreement</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-43599"><span class="HTitleText2">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-43602"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-43609"><span class="HTitleText2">Panels, Committees and Scientific Review Boards</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-43626"><span class="HTitleText2">Orders and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 to 93 - </span><a href="page-1.html#h-43647"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Related and Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-1.html#h-43649"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Transitional and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94 - </span><a href="page-1.html#h-43650"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-1.html#h-43656"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-2.html#h-43663"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

