<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act respecting the mandatory reporting of Internet child pornography by persons who provide an Internet service</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-277506"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-277521"><span class="HTitleText1">Duties</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-277541"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-277554"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-277563"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

