<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Disability Savings Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-82625"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-82628"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-82654"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-82657"><span class="HTitleText1">Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-82662"><span class="HTitleText1">Payments</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-82756"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

