<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Elections Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Electoral Rights</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Chief Electoral Officer and Staff</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Chief Electoral Officer</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HTitleText2">Assistant Chief Electoral Officer and Staff</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Election Officers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText2">Returning Officers and Assistant Returning Officers</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HTitleText2">Election Officers Appointed by Returning Officer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-11"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-12"><span class="HTitleText3">Revising Agents</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-13"><span class="HTitleText3">Deputy Returning Officers and Poll Clerks</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-14"><span class="HTitleText3">Registration Officers</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-15"><span class="HTitleText2">Equality of Votes</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-16"><span class="HTitleText2">New Electoral Districts</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-17"><span class="HTitleText2">Merger of Registered Parties</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-18"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-19"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Register of Electors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-20"><span class="HTitleText2">Maintenance and Communication of Register</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-21"><span class="HTitleText2">Updating the Register</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-22"><span class="HTitleText2">Agreements on Giving Information</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-23"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="#h-24"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Conduct of an Election</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="#h-25"><span class="HTitleText2">Writs of Election</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-26"><span class="HTitleText2">Notice of Election by Returning Officer</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-27"><span class="HTitleText2">Return by Acclamation</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-28"><span class="HTitleText2">Holding of an Election</span></a>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-29"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Candidates</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-30"><span class="HTitleText2">Qualifications</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-31"><span class="HTitleText2">Nomination of Candidates</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-32"><span class="HTitleText2">Rights of Candidates</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-33"><span class="HTitleText2">Obligations of Candidates</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-34"><span class="HTitleText2">Prohibition</span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="#h-35"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Revision of Lists of Electors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>93 - </span><a href="#h-36"><span class="HTitleText2">Preliminary Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-37"><span class="HTitleText2">Notice of Confirmation of Registration</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-38"><span class="HTitleText2">Revision Process</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-39"><span class="HTitleText2">Objection Procedure</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-40"><span class="HTitleText2">Revised Lists of Electors and Official Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-41"><span class="HTitleText2">Merger of Polling Divisions</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-42"><span class="HTitleText2">Final Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-43"><span class="HTitleText2">Use of Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-44"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-45"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Preparation for the Vote</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-46"><span class="HTitleText2">List of Deputy Returning Officers</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-47"><span class="HTitleText2">Election Materials</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-48"><span class="HTitleText2">Supply of Election Materials to Deputy Returning Officer</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-49"><span class="HTitleText2">Polling Stations and Central Polling Places</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-50"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-51"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Voting</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-52"><span class="HTitleText2">Voting Opportunities</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-53"><span class="HTitleText2">Polling Day</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="#h-54"><span class="HTitleText3">Hours</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-55"><span class="HTitleText3">Time to Employees for Voting</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-56"><span class="HTitleText3">Proceedings at the Poll</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-57"><span class="HTitleText3">Admitting Voters</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-58"><span class="HTitleText3">Voting Procedure</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-59"><span class="HTitleText3">Special Voting Procedures</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-60"><span class="HTitleText3">Transfer Certificates</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-61"><span class="HTitleText3">Polling Day Registration</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-62"><span class="HTitleText3">Duties of Poll Clerk</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-63"><span class="HTitleText3">Secrecy</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-64"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-65"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Advance Polling</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-66"><span class="HTitleText2">Establishment of Advance Polling Stations</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-67"><span class="HTitleText2">Registration</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-68"><span class="HTitleText2">Voting Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="#h-69"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Special Voting Rules</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="#h-70"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-71"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">ADMINISTRATION AND GENERAL PROCEDURES</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-72"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">CANADIAN FORCES ELECTORS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>190 - </span><a href="#h-73"><span class="HTitleText3">Definitions</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-74"><span class="HTitleText3">Voting Entitlement and Electoral Districts</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-75"><span class="HTitleText3">Statement of Ordinary Residence</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-76"><span class="HTitleText3">Coordinating Officer</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-77"><span class="HTitleText3">Steps to Prepare for Vote</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-78"><span class="HTitleText3">Duties of Commanding Officers</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-79"><span class="HTitleText3">Voting</span></a>
</li></ul>
</li><li><span class='sectionRange'>220 - </span><a href="#h-80"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">ELECTORS TEMPORARILY RESIDENT OUTSIDE CANADA</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-81"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">ELECTORS RESIDING IN CANADA</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-82"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">INCARCERATED ELECTORS</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-83"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">COUNTING OF VOTES AT THE OFFICE OF THE CHIEF ELECTORAL OFFICER</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-84"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">COUNTING OF VOTES IN THE OFFICE OF THE RETURNING OFFICER</span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="#h-85"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">COMMUNICATION OF THE RESULTS OF THE VOTE</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="#h-86"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">PROHIBITIONS</span></a>
</li></ul>
</li><li><span class='sectionRange'>283 - </span><a href="#h-87"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Counting Votes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>283 - </span><a href="#h-88"><span class="HTitleText2">Polling Stations</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="#h-89"><span class="HTitleText2">Advance Polls</span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-90"><span class="HTitleText2">Delivery of Ballot Boxes to Returning Officer</span></a>
</li></ul>
</li><li><span class='sectionRange'>293 - </span><a href="#h-91"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Validation of Results by the Returning Officer</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="#h-92"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Judicial Recount</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="#h-93"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-94"><span class="HTitleText2">Recount Procedure</span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="#h-95"><span class="HTitleText2">Failure of Judge to Conduct Recount</span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="#h-96"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Return of the Writ</span></a>
</li>
<li><span class='sectionRange'>319 - </span><a href="#h-97"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">Communications</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>319 - </span><a href="#h-98"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>320 - </span><a href="#h-99"><span class="HTitleText2">Election Advertising</span></a>
</li>
<li><span class='sectionRange'>326 - </span><a href="#h-100"><span class="HTitleText2">Election Opinion Surveys</span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="#h-101"><span class="HTitleText2">Premature Transmission</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="#h-102"><span class="HTitleText2">Broadcasting outside Canada</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="#h-103"><span class="HTitleText2">Non-interference by Foreigners</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="#h-104"><span class="HTitleText2">Political Broadcasts</span></a>
</li></ul>
</li><li><span class='sectionRange'>349 - </span><a href="#h-105"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">Third Party Election Advertising</span></a>
</li>
<li><span class='sectionRange'>363 - </span><a href="#h-106"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">Financial Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>363 - </span><a href="#h-107"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="#h-108"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">REGISTRATION OF POLITICAL PARTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>366 - </span><a href="#h-109"><span class="HTitleText3">Application for Registration</span></a>
</li>
<li><span class='sectionRange'>375 - </span><a href="#h-110"><span class="HTitleText3">Registered Agents and Auditors</span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="#h-111"><span class="HTitleText3">Change of Information in Registry of Parties</span></a>
</li>
<li><span class='sectionRange'>385 - </span><a href="#h-112"><span class="HTitleText3">Deregistration of Registered Parties</span></a>
</li>
<li><span class='sectionRange'>400 - </span><a href="#h-113"><span class="HTitleText3">Merger of Registered Parties</span></a>
</li></ul>
</li><li><span class='sectionRange'>403.01 - </span><a href="#h-114"><span class="HLabel2">DIVISION 1.1</span> - <span class="HTitleText2">Registration of Electoral District Associations and Financial Administration of Registered Associations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403.01 - </span><a href="#h-115"><span class="HTitleText3">Registration of Electoral District Associations</span></a>
</li>
<li><span class='sectionRange'>403.18 - </span><a href="#h-116"><span class="HTitleText3">Deregistration of Registered Associations</span></a>
</li>
<li><span class='sectionRange'>403.27 - </span><a href="#h-117"><span class="HTitleText3">Financial Administration of Registered Associations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403.27 - </span><a href="#h-118"><span class="HTitleText4">General</span></a>
</li>
<li><span class='sectionRange'>403.29 - </span><a href="#h-119"><span class="HTitleText4">Processing of Expense Claims</span></a>
</li>
<li><span class='sectionRange'>403.35 - </span><a href="#h-120"><span class="HTitleText4">Financial Reporting</span></a>
</li>
<li><span class='sectionRange'>403.39 - </span><a href="#h-121"><span class="HTitleText4">Payment of Audit Expenses</span></a>
</li>
<li><span class='sectionRange'>403.4 - </span><a href="#h-122"><span class="HTitleText4">Corrections and Extended Reporting Periods</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>404 - </span><a href="#h-123"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">GENERAL FINANCIAL PROVISIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>404 - </span><a href="#h-124"><span class="HTitleText3">Contributions</span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="#h-125"><span class="HTitleText3">Expenses</span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="#h-126"><span class="HTitleText3">Inflation Adjustment Factor</span></a>
</li></ul>
</li><li><span class='sectionRange'>415 - </span><a href="#h-127"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">FINANCIAL ADMINISTRATION OF REGISTERED PARTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>415 - </span><a href="#h-128"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>417 - </span><a href="#h-129"><span class="HTitleText3">Processing of Expense Claims</span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="#h-130"><span class="HTitleText3">Maximum Election Expenses</span></a>
</li>
<li><span class='sectionRange'>423.1 - </span><a href="#h-131"><span class="HTitleText3">Deemed Contributions</span></a>
</li>
<li><span class='sectionRange'>424 - </span><a href="#h-132"><span class="HTitleText3">Financial Reporting</span></a>
</li>
<li><span class='sectionRange'>429 - </span><a href="#h-133"><span class="HTitleText3">Election Expenses Reporting</span></a>
</li>
<li><span class='sectionRange'>432 - </span><a href="#h-134"><span class="HTitleText3">Corrections and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>435 - </span><a href="#h-135"><span class="HTitleText3">Reimbursement of Election Expenses</span></a>
</li>
<li><span class='sectionRange'>435.01 - </span><a href="#h-136"><span class="HTitleText3">Quarterly Allowances</span></a>
</li></ul>
</li><li><span class='sectionRange'>435.03 - </span><a href="#h-137"><span class="HLabel2">DIVISION 3.1</span> - <span class="HTitleText2">Registration and Financial Administration of Leadership Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>435.03 - </span><a href="#h-138"><span class="HTitleText3">Registration</span></a>
</li>
<li><span class='sectionRange'>435.2 - </span><a href="#h-139"><span class="HTitleText3">Financial Administration of Leadership Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>435.2 - </span><a href="#h-140"><span class="HTitleText4">Powers, Duties and Functions of Financial Agent</span></a>
</li>
<li><span class='sectionRange'>435.23 - </span><a href="#h-141"><span class="HTitleText4">Recovery of Claims</span></a>
</li>
<li><span class='sectionRange'>435.3 - </span><a href="#h-142"><span class="HTitleText4">Return on Financing and Expenses in a Leadership Campaign</span></a>
</li>
<li><span class='sectionRange'>435.37 - </span><a href="#h-143"><span class="HTitleText4">Corrections and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>435.44 - </span><a href="#h-144"><span class="HTitleText4">Surplus of Leadership Campaign Funds</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>436 - </span><a href="#h-145"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">FINANCIAL ADMINISTRATION OF CANDIDATES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>436 - </span><a href="#h-146"><span class="HTitleText3">Powers, Duties and Functions of Official Agent</span></a>
</li>
<li><span class='sectionRange'>439 - </span><a href="#h-147"><span class="HTitleText3">Notice of Nomination Meeting</span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="#h-148"><span class="HTitleText3">Election Expenses Limit</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="#h-149"><span class="HTitleText3">Recovery of Claims</span></a>
</li>
<li><span class='sectionRange'>451 - </span><a href="#h-150"><span class="HTitleText3">Return on Financing and Expenses in an Electoral Campaign</span></a>
</li>
<li><span class='sectionRange'>457 - </span><a href="#h-151"><span class="HTitleText3">Corrections and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="#h-152"><span class="HTitleText3">Reimbursement of Election Expenses and Personal Expenses</span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="#h-153"><span class="HTitleText3">Surplus of Electoral Funds</span></a>
</li>
<li><span class='sectionRange'>477 - </span><a href="#h-154"><span class="HTitleText3">Supply and Use of Forms</span></a>
</li></ul>
</li><li><span class='sectionRange'>478.01 - </span><a href="#h-155"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Nomination Contest Report and Financial Administration of Nomination Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>478.01 - </span><a href="#h-156"><span class="HTitleText3">Nomination Contest Report</span></a>
</li>
<li><span class='sectionRange'>478.11 - </span><a href="#h-157"><span class="HTitleText3">Financial Administration of Nomination Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>478.11 - </span><a href="#h-158"><span class="HTitleText4">Powers, Duties and Functions of Financial Agent</span></a>
</li>
<li><span class='sectionRange'>478.16 - </span><a href="#h-159"><span class="HTitleText4">Recovery of Claims</span></a>
</li>
<li><span class='sectionRange'>478.23 - </span><a href="#h-160"><span class="HTitleText4">Return on Financing and Expenses in a Nomination Campaign</span></a>
</li>
<li><span class='sectionRange'>478.32 - </span><a href="#h-161"><span class="HTitleText4">Corrections and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>478.39 - </span><a href="#h-162"><span class="HTitleText4">Surplus of Nomination Campaign Funds</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>479 - </span><a href="#h-163"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>479 - </span><a href="#h-164"><span class="HTitleText2">Peace and Good Order at Elections</span></a>
</li>
<li><span class='sectionRange'>480 - </span><a href="#h-165"><span class="HTitleText2">Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>480 - </span><a href="#h-166"><span class="HTitleText3">General Provisions</span></a>
</li>
<li><span class='sectionRange'>483 - </span><a href="#h-167"><span class="HTitleText3">Offences under Part 1 (Electoral Rights)</span></a>
</li>
<li><span class='sectionRange'>484 - </span><a href="#h-168"><span class="HTitleText3">Offences under Part 3 (Election Officers)</span></a>
</li>
<li><span class='sectionRange'>485 - </span><a href="#h-169"><span class="HTitleText3">Offences under Part 4 (Register of Electors)</span></a>
</li>
<li><span class='sectionRange'>486 - </span><a href="#h-170"><span class="HTitleText3">Offences under Part 6 (Candidates)</span></a>
</li>
<li><span class='sectionRange'>487 - </span><a href="#h-171"><span class="HTitleText3">Offences under Part 7 (Revision of List of Electors)</span></a>
</li>
<li><span class='sectionRange'>488 - </span><a href="#h-172"><span class="HTitleText3">Offences under Part 8 (Preparation for the Vote)</span></a>
</li>
<li><span class='sectionRange'>489 - </span><a href="#h-173"><span class="HTitleText3">Offences under Part 9 (Voting)</span></a>
</li>
<li><span class='sectionRange'>490 - </span><a href="#h-174"><span class="HTitleText3">Offences under Part 10 (Advance Polling)</span></a>
</li>
<li><span class='sectionRange'>491 - </span><a href="#h-175"><span class="HTitleText3">Offences under Part 11 (Special Voting Rules)</span></a>
</li>
<li><span class='sectionRange'>492 - </span><a href="#h-176"><span class="HTitleText3">Offences under Part 12 (Counting Votes)</span></a>
</li>
<li><span class='sectionRange'>493 - </span><a href="#h-177"><span class="HTitleText3">Offence under Part 13 (Validation of Results by the Returning Officer)</span></a>
</li>
<li><span class='sectionRange'>494 - </span><a href="#h-178"><span class="HTitleText3">Offences under Part 15 (Return of the Writ)</span></a>
</li>
<li><span class='sectionRange'>495 - </span><a href="#h-179"><span class="HTitleText3">Offences under Part 16 (Communications)</span></a>
</li>
<li><span class='sectionRange'>496 - </span><a href="#h-180"><span class="HTitleText3">Offences under Part 17 (Third Party Election Advertising)</span></a>
</li>
<li><span class='sectionRange'>497 - </span><a href="#h-181"><span class="HTitleText3">Offences under Part 18 (Finance)</span></a>
</li>
<li><span class='sectionRange'>498 - </span><a href="#h-182"><span class="HTitleText3">Offences under this Part (Enforcement)</span></a>
</li>
<li><span class='sectionRange'>499 - </span><a href="#h-183"><span class="HTitleText3">Offences under Part 21 (General)</span></a>
</li></ul>
</li><li><span class='sectionRange'>500 - </span><a href="#h-184"><span class="HTitleText2">Punishment</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-185"><span class="HTitleText2">Illegal Practices and Corrupt Practices</span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-186"><span class="HTitleText2">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>509 - </span><a href="#h-187"><span class="HTitleText2">Commissioner of Canada Elections</span></a>
</li>
<li><span class='sectionRange'>516 - </span><a href="#h-188"><span class="HTitleText2">Injunctions</span></a>
</li>
<li><span class='sectionRange'>517 - </span><a href="#h-189"><span class="HTitleText2">Compliance Agreements</span></a>
</li></ul>
</li><li><span class='sectionRange'>522 - </span><a href="#h-190"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">Contested Elections</span></a>
</li>
<li><span class='sectionRange'>533 - </span><a href="#h-191"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>533 - </span><a href="#h-192"><span class="HTitleText2">Reports of Chief Electoral Officer</span></a>
</li>
<li><span class='sectionRange'>538 - </span><a href="#h-193"><span class="HTitleText2">Polling Divisions</span></a>
</li>
<li><span class='sectionRange'>539 - </span><a href="#h-194"><span class="HTitleText2">Amendments to Schedule 3</span></a>
</li>
<li><span class='sectionRange'>540 - </span><a href="#h-195"><span class="HTitleText2">Custody of Election Documents and Documents Relating to the Register of Electors</span></a>
</li>
<li><span class='sectionRange'>542 - </span><a href="#h-196"><span class="HTitleText2">Fees and Expenses of Election Officers</span></a>
</li>
<li><span class='sectionRange'>547 - </span><a href="#h-197"><span class="HTitleText2">Notice</span></a>
</li>
<li><span class='sectionRange'>549 - </span><a href="#h-198"><span class="HTitleText2">Oaths and Affidavits</span></a>
</li>
<li><span class='sectionRange'>550 - </span><a href="#h-199"><span class="HTitleText2">Signed Pledges by Candidates Prohibited</span></a>
</li>
<li><span class='sectionRange'>551 - </span><a href="#h-200"><span class="HTitleText2">By-Elections</span></a>
</li>
<li><span class='sectionRange'>552 - </span><a href="#h-201"><span class="HTitleText2">Forms</span></a>
</li>
<li><span class='sectionRange'>553 - </span><a href="#h-202"><span class="HTitleText2">Payments out of Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>554 - </span><a href="#h-203"><span class="HTitleText2">Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>555 - </span><a href="#h-204"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">Transitional Provisions, Consequential Amendments, Repeals and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>555 - </span><a href="#h-205"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>559 to 572 - </span><a href="#h-206"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>573 to 576 - </span><a href="#h-207"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>577 - </span><a href="#h-208"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-211164"><span class="scheduleLabel">SCHEDULE 1</span></a>
</li>
<li><a href="#h-210"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Provincial Acts</span></a>
</li>
<li><a href="#h-211"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - List of Electoral Districts</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
