<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Wages Liability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-464650"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-464655"><span class="HTitleText1">Public Works</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-464664"><span class="HTitleText1">Subsidized Works</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-464672"><span class="HTitleText1">Works by Chartered Companies</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-464688"><span class="HTitleText1">Offences and Punishment</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
