<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Aeronautics Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-7489"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-7494"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-7499"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-7549"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Aeronautics</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-7550"><span class="HTitleText2">Application of Part</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="page-1.html#h-7564"><span class="HTitleText2">Responsibilities of Minister</span></a>
</li>
<li><span class='sectionRange'>4.4 - </span><a href="page-2.html#h-7609"><span class="HTitleText2">Charges</span></a>
</li>
<li><span class='sectionRange'>4.7 - </span><a href="page-2.html#h-7673"><span class="HTitleText2">Aviation Security</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4.7 - </span><a href="page-2.html#h-7674"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4.71 - </span><a href="page-2.html#h-7681"><span class="HTitleText3">Aviation Security Regulations</span></a>
</li>
<li><span class='sectionRange'>4.72 - </span><a href="page-2.html#h-7707"><span class="HTitleText3">Security Measures</span></a>
</li>
<li><span class='sectionRange'>4.75 - </span><a href="page-3.html#h-7751"><span class="HTitleText3">Foreign Aircraft Requirements</span></a>
</li>
<li><span class='sectionRange'>4.76 - </span><a href="page-3.html#h-7756"><span class="HTitleText3">Emergency Directions</span></a>
</li>
<li><span class='sectionRange'>4.79 - </span><a href="page-3.html#h-7779"><span class="HTitleText3">Unauthorized Disclosure</span></a>
</li>
<li><span class='sectionRange'>4.8 - </span><a href="page-3.html#h-7789"><span class="HTitleText3">Security Clearances</span></a>
</li>
<li><span class='sectionRange'>4.81 - </span><a href="page-3.html#h-7794"><span class="HTitleText3">Provision of Information</span></a>
</li>
<li><span class='sectionRange'>4.84 - </span><a href="page-4.html#h-7903"><span class="HTitleText3">Screenings</span></a>
</li>
<li><span class='sectionRange'>4.86 - </span><a href="page-4.html#h-7921"><span class="HTitleText3">Air Carrier and Aerodrome Assessments</span></a>
</li>
<li><span class='sectionRange'>4.87 - </span><a href="page-4.html#h-7926"><span class="HTitleText3">Verifying Compliance and Testing Effectiveness</span></a>
</li></ul>
</li><li><span class='sectionRange'>4.9 - </span><a href="page-4.html#h-7931"><span class="HTitleText2">General Regulatory Powers</span></a>
</li>
<li><span class='sectionRange'>5.4 - </span><a href="page-4.html#h-7997"><span class="HTitleText2">Airport Zoning</span></a>
</li>
<li><span class='sectionRange'>5.9 - </span><a href="page-5.html#h-8089"><span class="HTitleText2">General Provisions Respecting Regulations, Orders, etc.</span></a>
</li>
<li><span class='sectionRange'>6.41 - </span><a href="page-5.html#h-8132"><span class="HTitleText2">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>6.5 - </span><a href="page-6.html#h-8157"><span class="HTitleText2">Medical and Optometric Information</span></a>
</li>
<li><span class='sectionRange'>6.6 - </span><a href="page-6.html#h-8173"><span class="HTitleText2">Measures Relating to Canadian Aviation Documents</span></a>
</li>
<li><span class='sectionRange'>7.3 - </span><a href="page-7.html#h-8320"><span class="HTitleText2">Prohibitions, Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>7.6 - </span><a href="page-8.html#h-8411"><span class="HTitleText2">Procedure Pertaining to Certain Contraventions</span></a>
</li>
<li><span class='sectionRange'>8.4 - </span><a href="page-8.html#h-8498"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-9.html#h-8556"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-9.html#h-8564"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Military Investigations Involving Civilians</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-9.html#h-8565"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-9.html#h-8591"><span class="HTitleText2">Authorization by Minister</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-9.html#h-8596"><span class="HTitleText2">Airworthiness Investigative Authority</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-9.html#h-8612"><span class="HTitleText2">Investigations of Military-Civilian Occurrences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-9.html#h-8613"><span class="HTitleText3">Investigations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-10.html#h-8688"><span class="HTitleText3">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-10.html#h-8770"><span class="HTitleText3">Privilege</span></a>
</li>
<li><span class='sectionRange'>24.3 - </span><a href="page-11.html#h-8876"><span class="HTitleText3">Evidence of Authority and of Investigators</span></a>
</li>
<li><span class='sectionRange'>24.5 - </span><a href="page-11.html#h-8885"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>24.6 - </span><a href="page-11.html#h-8905"><span class="HTitleText3">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>24.8 - </span><a href="page-11.html#h-8928"><span class="HTitleText2">Military Investigations under Part I</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-11.html#h-8933"><span class="HLabel1">PART III</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-11.html#h-8934"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-11.html#h-8939"><span class="HTitleText2">Prosecution</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-11.html#h-8960"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">[Repealed, 2001, c. 29, s. 44]</span></a>
</li>
<li><a href="page-13.html#h-8971"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

