<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Food and Drugs Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-233997"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-234002"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-234053"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Foods, Drugs, Cosmetics and Devices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-234054"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-234067"><span class="HTitleText2">Food</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-234115"><span class="HTitleText2">Drugs</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-234163"><span class="HTitleText2">Cosmetics</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-234181"><span class="HTitleText2">Devices</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-234197"><span class="HTitleText2">Therapeutic Products</span></a>
</li>
<li><span class='sectionRange'>21.9 - </span><a href="#h-1174034"><span class="HTitleText2">Advanced Therapeutic Products</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-234281"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-234282"><span class="HTitleText2">Inspection, Seizure and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-234355"><span class="HTitleText2">Removal, Forfeiture or Destruction of Unlawful Imports</span></a>
</li>
<li><span class='sectionRange'>27.3 - </span><a href="#h-1174159"><span class="HTitleText2">Preventive and Remedial Measures</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-234398"><span class="HTitleText2">Analysis</span></a>
</li>
<li><span class='sectionRange'>29.1 - </span><a href="#h-234414"><span class="HTitleText2">Power of the Minister</span></a>
</li>
<li><span class='sectionRange'>29.2 - </span><a href="#h-234422"><span class="HTitleText2">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-234432"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-234517"><span class="HTitleText2">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>30.2 - </span><a href="#h-234541"><span class="HTitleText2">Marketing Authorizations</span></a>
</li>
<li><span class='sectionRange'>30.5 - </span><a href="#h-234566"><span class="HTitleText2">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>30.61 - </span><a href="#h-234582"><span class="HTitleText2">Fees</span></a>
</li>
<li><span class='sectionRange'>30.7 - </span><a href="#h-234623"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-234638"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-234726"><span class="HTitleText2">Exports</span></a>
</li></ul>
</li><li><a href="#h-234753"><span class="HLabel1">PARTS III AND IV</span> - <span class="HTitleText1">[Repealed, 1996, c. 19, s. 81]</span></a>
</li>
<li><a href="#h-1174230"><span class="scheduleLabel">SCHEDULE A</span> </a>
</li>
<li><a href="#h-234755"><span class="scheduleLabel">SCHEDULE A.1</span> </a>
</li>
<li><a href="#h-234789"><span class="scheduleLabel">SCHEDULE B</span> </a>
</li>
<li><a href="#h-234799"><span class="scheduleLabel">SCHEDULE C</span> </a>
</li>
<li><a href="#h-234806"><span class="scheduleLabel">SCHEDULE D</span> </a>
</li>
<li><a href="#h-234827"><span class="scheduleLabel">SCHEDULE E</span> </a>
</li>
<li><a href="#h-234832"><span class="scheduleLabel">SCHEDULE F</span> </a>
</li>
<li><a href="#h-1174263"><span class="scheduleLabel">SCHEDULE G</span> </a>
</li>
<li><a href="#h-1174273"><span class="scheduleLabel">SCHEDULE H</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
