<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi relative à la stratégie nationale sur l’élimination sûre et écologique des lampes contenant du mercure</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-355251"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-355254"><span class="HTitleText1">Stratégie nationale</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-355265"><span class="HTitleText1">Rapport d’examen</span></a>
</li></ul>
</li></ul>

</nav>

