<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le cabotage</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-84222"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-84225"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-84271"><span class="HTitleText1">Réglementation de l’utilisation des navires étrangers et des navires non dédouanés</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-84372"><span class="HTitleText1">Mission de l’office</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-84382"><span class="HTitleText1">Pratiques injustes</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-84390"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-84396"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-84407"><span class="HTitleText1">Perquisitions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-84417"><span class="HTitleText1">Rétention du navire</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-84492"><span class="HTitleText1">Autres infractions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-84502"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>22 à 28 - </span><a href="#h-84510"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-84512"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-84515"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
