<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canadian Transportation Accident Investigation and Safety Board Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-75348"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-75351"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-75397"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-75426"><span class="HTitleText1">Canadian Transportation Accident Investigation and Safety Board</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-75561"><span class="HTitleText1">Investigations and Public Inquiries</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-75708"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-4.html#h-75791"><span class="HTitleText1">Privilege</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-75881"><span class="HTitleText1">Evidence of Investigators</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-4.html#h-75890"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-5.html#h-75913"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>37 to 57 - </span><a href="page-5.html#h-75936"><span class="HTitleText1">Consequential Amendments and Repeal</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-5.html#h-75938"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-5.html#h-75995"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-6.html#h-75999"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

