<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la sécurité ferroviaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-414553"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-414556"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-414568"><span class="HTitleText1">Objectifs</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-414586"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-414644"><span class="HTitleText1">Cadre législatif</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-414649"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-414672"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Construction et modification d’installations ferroviaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-414673"><span class="HTitleText2">Normes</span></a>
</li>
<li><span class='sectionRange'>7.1 - </span><a href="#h-414685"><span class="HTitleText2">Construction et modification de franchissements routiers</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-414690"><span class="HTitleText2">Avis des travaux projetés</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-414707"><span class="HTitleText2">Commencement des travaux projetés</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-414742"><span class="HTitleText2">Subventions pour les travaux concernant la sécurité des franchissements routiers ou d’autres réalisations contribuant à la sécurité ferroviaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>17.1 - </span><a href="#h-414820"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Exploitation et entretien des installations et du matériel ferroviaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17.1 - </span><a href="#h-414821"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>17.4 - </span><a href="#h-414841"><span class="HTitleText2">Certificat d’exploitation de chemin de fer</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-414914"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-414932"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-414996"><span class="HTitleText2">Dispositions diverses concernant les règles et les règlements</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-415043"><span class="HTitleText2">Pouvoirs de l’Office — incendie</span></a>
</li>
<li><span class='sectionRange'>23.1 - </span><a href="#h-415059"><span class="HTitleText2">Avertissement audible</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-415071"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Activités autres que ferroviaires pouvant compromettre la sécurité ferroviaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-415072"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-415091"><span class="HTitleText2">Pouvoirs des compagnies de chemin de fer</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-415107"><span class="HTitleText2">Pouvoirs de l’Office</span></a>
</li>
<li><span class='sectionRange'>26.1 - </span><a href="#h-415123"><span class="HTitleText2">Interdiction d’accès aux lignes de chemin de fer</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-415132"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Application et contrôle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-415133"><span class="HTitleText2">Inspecteurs de la sécurité ferroviaire et agents de contrôle</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-415249"><span class="HTitleText2">Avis des inspecteurs de la sécurité ferroviaire en matière de sécurité ou de sûreté ferroviaires</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-415304"><span class="HTitleText2">Ordres ministériels</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-415360"><span class="HTitleText2">Injonctions ministérielles</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-415378"><span class="HTitleText2">Assimilation à des ordonnances judiciaires</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-415392"><span class="HTitleText2">Renseignements médicaux</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-415408"><span class="HTitleText2">Exigences relatives aux renseignements</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-415428"><span class="HTitleText2">Sûreté du transport ferroviaire</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-415462"><span class="HTitleText2">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="#h-415478"><span class="HTitleText2">Sanctions administratives pécuniaires</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-415579"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-415618"><span class="HLabel1">PARTIE IV.1</span> - <span class="HTitleText1">Agents de police</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-415644"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Dispositions diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-415645"><span class="HTitleText2">Délégation de pouvoirs</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-415648"><span class="HTitleText2">Loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-415661"><span class="HTitleText2">Règlements — général</span></a>
</li>
<li><span class='sectionRange'>47.4 - </span><a href="#h-415709"><span class="HTitleText2">Accords</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-415723"><span class="HTitleText2">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-415726"><span class="HTitleText2">Incompatibilité</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-415732"><span class="HTitleText2">Examen de la loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-415740"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Modifications corrélatives et dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-415741"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>53 et 54 - </span><a href="#h-415743"><span class="HTitleText2">Loi sur les Chemins de fer nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>55 à 62 - </span><a href="#h-415745"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>63 à 65 - </span><a href="#h-415747"><span class="HTitleText2">Loi de 1987 sur les transports nationaux</span></a>
</li>
<li><span class='sectionRange'>66 à 114 - </span><a href="#h-415749"><span class="HTitleText2">Loi sur les chemins de fer</span></a>
</li>
<li><span class='sectionRange'>115 à 118 - </span><a href="#h-415751"><span class="HTitleText2">Loi sur le déplacement des lignes de chemin de fer et les croisements de chemin de fer</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-415753"><span class="HTitleText2">Dispositions transitoires concernant les modifications à la Loi sur les chemins de fer</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-415799"><span class="HTitleText2">Dispositions transitoires corrélatives à l’abrogation des parties II et III de la Loi sur le déplacement des lignes de chemin de fer et les croisements de chemin de fer</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-415808"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

