<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Northumberland Strait Crossing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-366105"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-366108"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-366119"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-366122"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-366144"><span class="HTitleText1">Annual Subsidy</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-366155"><span class="HTitleText1">Tolls</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-366158"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

