<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nunavut Waters and Nunavut Surface Rights Tribunal Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-372321"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-372324"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-372347"><span class="HTitleText1">Precedence</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-372353"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Nunavut Waters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-372354"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-372385"><span class="HTitleText2">Scope and Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-372390"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-372398"><span class="HTitleText2">Delegation and Agreements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-372403"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-372427"><span class="HTitleText2">Compensation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-372433"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Nunavut Water Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-372434"><span class="HTitleText3">Establishment and Organization of Board</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-372484"><span class="HTitleText3">Languages</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-372494"><span class="HTitleText3">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-372502"><span class="HTitleText3">Status and General Powers</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-372521"><span class="HTitleText3">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-372533"><span class="HTitleText3">Rules and By-laws</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-372559"><span class="HTitleText3">Objects of Board and Its Relationship with Other Bodies</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-372595"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Licences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-372596"><span class="HTitleText3">General Rules</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-372642"><span class="HTitleText3">Applications in Relation to Licences</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-372661"><span class="HTitleText3">Procedure</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-372699"><span class="HTitleText3">Time Limits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55.1 - </span><a href="#h-372700"><span class="HTitleText4">Authority to Act</span></a>
</li>
<li><span class='sectionRange'>55.2 - </span><a href="#h-372705"><span class="HTitleText4">Decisions by Board and Approvals</span></a>
</li>
<li><span class='sectionRange'>55.31 - </span><a href="#h-372714"><span class="HTitleText4">Calculation of Time Limit</span></a>
</li>
<li><span class='sectionRange'>55.6 - </span><a href="#h-372732"><span class="HTitleText4">Extensions</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-372740"><span class="HTitleText3">Conditions of Issuance</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-372799"><span class="HTitleText3">Inuit-owned Land</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-372835"><span class="HTitleText3">Mackenzie Valley</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-372838"><span class="HTitleText3">Conditions of Licences</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-372867"><span class="HTitleText3">Security</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-372892"><span class="HTitleText3">Expropriation</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-372935"><span class="HTitleText3">Public Register</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-372943"><span class="HTitleText3">Decisions</span></a>
</li>
<li><span class='sectionRange'>81.1 - </span><a href="#h-372959"><span class="HTitleText3">Cost Recovery</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-372970"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-372971"><span class="HTitleText3">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-373022"><span class="HTitleText3">Enforcement</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-373079"><span class="HTitleText3">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>94.01 - </span><a href="#h-373148"><span class="HTitleText3">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94.01 - </span><a href="#h-373149"><span class="HTitleText4">Regulations</span></a>
</li>
<li><span class='sectionRange'>94.02 - </span><a href="#h-373165"><span class="HTitleText4">Violations</span></a>
</li>
<li><span class='sectionRange'>94.07 - </span><a href="#h-373198"><span class="HTitleText4">Rules about Violations</span></a>
</li>
<li><span class='sectionRange'>94.11 - </span><a href="#h-373223"><span class="HTitleText4">Reviews</span></a>
</li>
<li><span class='sectionRange'>94.16 - </span><a href="#h-373253"><span class="HTitleText4">Responsibility</span></a>
</li>
<li><span class='sectionRange'>94.18 - </span><a href="#h-373262"><span class="HTitleText4">Recovery of Penalties</span></a>
</li>
<li><span class='sectionRange'>94.2 - </span><a href="#h-373277"><span class="HTitleText4">General</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-373286"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Nunavut Surface Rights Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-373287"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-373296"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-373304"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-373307"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Establishment and Organization of Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-373308"><span class="HTitleText3">Tribunal Established</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-373335"><span class="HTitleText3">Languages</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-373349"><span class="HTitleText3">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-373357"><span class="HTitleText3">By-laws</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-373360"><span class="HTitleText3">General Powers</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-373372"><span class="HTitleText3">Status</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-373375"><span class="HTitleText3">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-373387"><span class="HTitleText3">Annual Report</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-373396"><span class="HTitleText3">Jurisdiction of Tribunal</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-373404"><span class="HTitleText3">Applications and Hearings</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-373448"><span class="HTitleText3">Records</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-373457"><span class="HTitleText3">Rules</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="#h-373485"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Entry Orders for Inuit-owned Lands</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="#h-373486"><span class="HTitleText3">Exercise of Mineral Rights</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-373507"><span class="HTitleText3">Other Commercial Purposes</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-373523"><span class="HTitleText3">Construction Materials</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-373533"><span class="HTitleText3">General Rules for Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="#h-373572"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Entry Orders for Non-Inuit-owned Land</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="#h-373573"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-373578"><span class="HTitleText3">Exercise of Mineral Rights</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-373585"><span class="HTitleText3">General Rules for Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-373620"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Mineral Rights and Carving Stone</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-373621"><span class="HTitleText3">Specified Substances on Inuit-owned Land</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-373627"><span class="HTitleText3">Carving Stone on Crown Lands</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-373633"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Wildlife Compensation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="#h-373634"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-373652"><span class="HTitleText3">Liability of Developers</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-373679"><span class="HTitleText3">Applications to Tribunal</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-373701"><span class="HTitleText3">Other Remedies</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-373707"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-373708"><span class="HTitleText3">Decisions of the Tribunal</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-373726"><span class="HTitleText3">Review of Orders</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-373753"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>171 - </span><a href="#h-373762"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Transitional Provisions, Consequential and Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>171 - </span><a href="#h-373763"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>176 to 199 - </span><a href="#h-373797"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>200 to 202 - </span><a href="#h-373799"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-373801"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-373805"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-373841"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

