<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Prisons and Reformatories Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-397012"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-397017"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-397034"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-397039"><span class="HTitleText1">Committal, Reception and Transfer of Prisoners</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-397058"><span class="HTitleText1">Earned Remission</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-397094"><span class="HTitleText1">Temporary Absence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-397095"><span class="HTitleText2">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>7.2 - </span><a href="#h-397108"><span class="HTitleText2">Designated Authority</span></a>
</li>
<li><span class='sectionRange'>7.3 - </span><a href="#h-397116"><span class="HTitleText2">Authorization of Absence</span></a>
</li>
<li><span class='sectionRange'>7.5 - </span><a href="#h-397134"><span class="HTitleText2">Suspension, Cancellation and Revocation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-397153"><span class="HTitleText2">Effect on Release Date</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-397158"><span class="HTitleText1">Young Offenders</span></a>
</li></ul>
</li></ul>

</nav>

