<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Pension Plan</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-167616"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-167621"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-167699"><span class="HTitleText1">Application and Operation of Act</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-167733"><span class="HTitleText1">Electronic Alternatives</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-167738"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Contributions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-167746"><span class="HLabel2">DIVISION A</span> - <span class="HTitleText2">Contributions Payable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-167747"><span class="HTitleText3">Pensionable Employment</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-167794"><span class="HTitleText3">Contributions by Employees and Employers in respect of Pensionable Employment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-167896"><span class="HTitleText3">Contributions by Persons in respect of Self-Employed Earnings</span></a>
</li></ul>
</li><li><span class='sectionRange'>11.1 - </span><a href="#h-167950"><span class="HLabel2">DIVISION B</span> - <span class="HTitleText2">Calculation of Contributions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11.1 - </span><a href="#h-167951"><span class="HTitleText3">Contribution Rate</span></a>
</li>
<li><span class='sectionRange'>11.2 - </span><a href="#h-167962"><span class="HTitleText3">First Additional Contribution Rate and Second Additional Contribution Rate</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-167967"><span class="HTitleText3">Contributory Salary and Wages</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-167996"><span class="HTitleText3">Contributory Self-Employed Earnings</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-168085"><span class="HTitleText3">Salary and Wages on which Contribution made</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-168134"><span class="HTitleText3">Maximum Contributory Earnings</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-168139"><span class="HTitleText3">Maximum Pensionable Earnings</span></a>
</li>
<li><span class='sectionRange'>17.1 - </span><a href="#h-168155"><span class="HTitleText3">Additional Maximum Pensionable Earnings</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-168171"><span class="HTitleText3">Year’s Maximum Pensionable Earnings</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-168204"><span class="HTitleText3">Year’s Additional Maximum Pensionable Earnings</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-168214"><span class="HTitleText3">Basic Exemption</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-168241"><span class="HTitleText3">Year’s Basic Exemption</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-168249"><span class="HLabel2">DIVISION C</span> - <span class="HTitleText2">Collection of Contributions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-168250"><span class="HTitleText3">Employees and Employers</span></a>
</li>
<li><span class='sectionRange'>26.1 - </span><a href="#h-168398"><span class="HTitleText3">Rulings and Appeals</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-168463"><span class="HLabel2">DIVISION D</span> - <span class="HTitleText2">Collection of Contributions in Respect of Self-Employed Earnings</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-168542"><span class="HLabel2">DIVISION E</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-168543"><span class="HTitleText3">Refunds of Overpayments</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-168580"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-168603"><span class="HTitleText3">Offences</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-168629"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Pensions and Supplementary Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-168630"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-168667"><span class="HTitleText2">Pension Index</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-168677"><span class="HLabel2">DIVISION A</span> - <span class="HTitleText2">Benefits Payable</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-168765"><span class="HLabel2">DIVISION B</span> - <span class="HTitleText2">Calculation of Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-168766"><span class="HTitleText3">Basic Amount and Annual Adjustment</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-168777"><span class="HTitleText3">Retirement Pension</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-169243"><span class="HTitleText3">Division of Unadjusted Pensionable Earnings for Divorces and Annulments before the Coming into Force of section 55.1</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-169272"><span class="HTitleText3">Division of Unadjusted Pensionable Earnings</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-169378"><span class="HTitleText3">Disability Pension</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-169443"><span class="HTitleText3">Death Benefit</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-169475"><span class="HTitleText3">Survivor’s Pension</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-169685"><span class="HTitleText3">Disabled Contributor’s Child’s Benefit and Orphan’s Benefit</span></a>
</li>
<li><span class='sectionRange'>59.1 - </span><a href="#h-169698"><span class="HTitleText3">Post-retirement Benefit</span></a>
</li>
<li><span class='sectionRange'>59.2 - </span><a href="#h-169764"><span class="HTitleText3">Post-retirement Disability Benefit</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-169777"><span class="HLabel2">DIVISION C</span> - <span class="HTitleText2">Payment of Benefits: General Provisions</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-170030"><span class="HLabel2">DIVISION D</span> - <span class="HTitleText2">Payment of Benefits: Special Rules Applicable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-170031"><span class="HTitleText3">Retirement Pension</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-170072"><span class="HTitleText3">Disability Pension and Post-retirement Disability Benefit</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-170131"><span class="HTitleText3">Death Benefit</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-170144"><span class="HTitleText3">Survivor’s Pension</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-170165"><span class="HTitleText3">Disabled Contributor’s Child’s Benefit and Orphan’s Benefit</span></a>
</li>
<li><span class='sectionRange'>76.1 - </span><a href="#h-170206"><span class="HTitleText3">Post-retirement Benefit</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-170220"><span class="HLabel2">DIVISION E</span> - <span class="HTitleText2">Payment of Benefits: Amount Payable Under Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-170303"><span class="HLabel2">DIVISION F</span> - <span class="HTitleText2">Reconsiderations and Appeals</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-170336"><span class="HLabel2">DIVISION G</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-170354"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-170383"><span class="HTitleText3">Offences</span></a>
</li>
<li><span class='sectionRange'>90.1 - </span><a href="#h-170397"><span class="HTitleText3">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>90.2 - </span><a href="#h-170422"><span class="HTitleText3">Administration and Enforcement</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-170466"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-170467"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-170476"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-170495"><span class="HTitleText2">Records and Information</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-170589"><span class="HTitleText2">Availability of Information</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-170620"><span class="HTitleText2">Agreements with Provinces</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-170627"><span class="HTitleText2">Oaths, Affidavits, Declarations and Affirmations</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-170641"><span class="HTitleText2">Reciprocal Agreements with Other Countries</span></a>
</li>
<li><span class='sectionRange'>107.1 - </span><a href="#h-170656"><span class="HTitleText2">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>113.1 - </span><a href="#h-170786"><span class="HTitleText2">Financial Review of the Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-170930"><span class="HTitleText2">Amendments to Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-170953"><span class="HTitleText2">Report of Chief Actuary</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-170992"><span class="HTitleText2">Annual Report to Parliament and the Provinces</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-171007"><span class="HTitleText2">Government Employees</span></a>
</li></ul>
</li><li><a href="#h-171025"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-171035"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - First and Second Additional Contribution Rates</span></a>
</li></ul>
</li></ul>

</nav>

