<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Mackenzie Valley Resource Management Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-345757"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-345760"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-345860"><span class="HTitleText1">Application and Consultation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-345882"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">General Provisions Respecting Boards</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-345883"><span class="HTitleText2">Establishment and Organization</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-345954"><span class="HTitleText2">General Powers</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-345982"><span class="HTitleText2">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-345998"><span class="HTitleText2">Reports</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-346004"><span class="HTitleText2">By-laws, Rules and Other Instruments</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-346025"><span class="HTitleText2">Jurisdiction of Courts</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-346030"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Land Use Planning</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-346031"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-346043"><span class="HTitleText2">Gwich’in Land Use Planning Board</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-346053"><span class="HTitleText2">Sahtu Land Use Planning Board</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-346063"><span class="HTitleText2">Land Use Planning</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-346109"><span class="HTitleText2">Compliance with Plans</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-346141"><span class="HTitleText2">Comprehensive Review</span></a>
</li>
<li><span class='sectionRange'>50.1 - </span><a href="#h-346144"><span class="HTitleText2">Policy Directions</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-346154"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Land and Water Regulation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-346155"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-346218"><span class="HTitleText2">Gwich’in Land and Water Board</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-346228"><span class="HTitleText2">Sahtu Land and Water Board</span></a>
</li>
<li><span class='sectionRange'>57.1 - </span><a href="#h-346238"><span class="HTitleText2">Wekeezhii Land and Water Board</span></a>
</li>
<li><span class='sectionRange'>57.3 - </span><a href="#h-346254"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-346346"><span class="HTitleText2">Special Rules for Land Use</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-346367"><span class="HTitleText2">Special Rules for the Use of Waters and the Deposit of Waste</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-346368"><span class="HTitleText3">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>72.03 - </span><a href="#h-346398"><span class="HTitleText3">Licences</span></a>
</li>
<li><span class='sectionRange'>72.15 - </span><a href="#h-346582"><span class="HTitleText3">Public Hearings and Procedure</span></a>
</li>
<li><span class='sectionRange'>72.26 - </span><a href="#h-346675"><span class="HTitleText3">Rights and Duties of Licensees and Others With Authorizations to Use Waters</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-346696"><span class="HTitleText2">Aboriginal Water Rights</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-346717"><span class="HTitleText2">Compensation — Gwich’in and Sahtu First Nations</span></a>
</li>
<li><span class='sectionRange'>79.1 - </span><a href="#h-346751"><span class="HTitleText2">Compensation — Tlicho First Nation</span></a>
</li>
<li><span class='sectionRange'>79.4 - </span><a href="#h-1173350"><span class="HTitleText2">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-346787"><span class="HTitleText2">Access to Construction Materials</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-346818"><span class="HTitleText2">Powers and Duties of Federal Minister</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-346824"><span class="HTitleText2">Policy Directions</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-346844"><span class="HTitleText2">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-346845"><span class="HTitleText3">Designation</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-346853"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-346906"><span class="HTitleText3">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-346963"><span class="HTitleText2">Regulations and Rules</span></a>
</li>
<li><span class='sectionRange'>91.1 - </span><a href="#h-347073"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-347087"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-347179"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="#h-347186"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Mackenzie Valley Land and Water Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="#h-347187"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-347220"><span class="HTitleText2">Establishment of Board</span></a>
</li>
<li><span class='sectionRange'>101.1 - </span><a href="#h-347241"><span class="HTitleText2">Mandate of Board</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-347294"><span class="HTitleText2">Cooperation with Other Authorities</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-347297"><span class="HTitleText2">Powers of Governor in Council and Federal Minister</span></a>
</li>
<li><span class='sectionRange'>109.1 - </span><a href="#h-347319"><span class="HTitleText2">Powers of Tlicho Government</span></a>
</li>
<li><span class='sectionRange'>109.11 - </span><a href="#h-347324"><span class="HTitleText2">Powers of Déline Got’ine Government</span></a>
</li>
<li><span class='sectionRange'>109.2 - </span><a href="#h-347329"><span class="HTitleText2">Precedence Relating to Policy Directions</span></a>
</li>
<li><span class='sectionRange'>109.3 - </span><a href="#h-1173397"><span class="HTitleText2">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>109.4 - </span><a href="#h-1173406"><span class="HTitleText2">Consultations</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-347341"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-347346"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Mackenzie Valley Environmental Impact Review Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-347347"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-347372"><span class="HTitleText2">Establishment of Review Board</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-347386"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-347475"><span class="HTitleText2">Preliminary Screening</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-347500"><span class="HTitleText2">Environmental Assessment</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-347642"><span class="HTitleText2">Environmental Impact Review</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-347774"><span class="HTitleText2">Cooperation and Joint Reviews</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-347845"><span class="HTitleText2">Transregional and External Developments</span></a>
</li>
<li><span class='sectionRange'>142.01 - </span><a href="#h-1173451"><span class="HTitleText2">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>142.1 - </span><a href="#h-347891"><span class="HTitleText2">Public Register</span></a>
</li>
<li><span class='sectionRange'>142.2 - </span><a href="#h-347916"><span class="HTitleText2">Policy Directions</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-347926"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>144.1 - </span><a href="#h-1173500"><span class="HLabel1">PART 5.1</span> - <span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144.1 - </span><a href="#h-1173502"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>144.11 - </span><a href="#h-1173519"><span class="HTitleText2">Federal Minister’s Powers</span></a>
</li>
<li><span class='sectionRange'>144.12 - </span><a href="#h-1173541"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>144.17 - </span><a href="#h-1173582"><span class="HTitleText2">Rules About Violations</span></a>
</li>
<li><span class='sectionRange'>144.21 - </span><a href="#h-1173611"><span class="HTitleText2">Reviews</span></a>
</li>
<li><span class='sectionRange'>144.26 - </span><a href="#h-1173657"><span class="HTitleText2">Responsibility</span></a>
</li>
<li><span class='sectionRange'>144.28 - </span><a href="#h-1173666"><span class="HTitleText2">Recovery of Penalties</span></a>
</li>
<li><span class='sectionRange'>144.3 - </span><a href="#h-1173681"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>144.32 - </span><a href="#h-1173696"><span class="HLabel1">PART 5.2</span> - <span class="HTitleText1">Regional Studies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144.32 - </span><a href="#h-1173697"><span class="HTitleText2">Committee Studying Impact of Works and Activities</span></a>
</li>
<li><span class='sectionRange'>144.37 - </span><a href="#h-1173742"><span class="HTitleText2">Joint Committee</span></a>
</li>
<li><span class='sectionRange'>144.38 - </span><a href="#h-1173747"><span class="HTitleText2">Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>145 - </span><a href="#h-347952"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Environmental Monitoring and Audit</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-347992"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Transitional Provisions, Consequential Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-347993"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>160 to 167 - </span><a href="#h-348016"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-348018"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-348025"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Designated Regulatory Agencies</span></a>
</li></ul>
</li></ul>

</nav>

