<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi des ressources naturelles du Manitoba</a><ul class="TocIndent"><li><a href="#h-437558"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - Convention</span></a>
</li>
<li><a href="#h-437646"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - Convention entre le Canada, l’Ontario et le Manitoba</span></a>
</li></ul>
</li></ul>

</nav>

