<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Statutory Instruments Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-442123"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-442128"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-442154"><span class="HTitleText1">Examination of Proposed Regulations</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-442174"><span class="HTitleText1">Transmission and Registration</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-442198"><span class="HTitleText1">Power to Revoke Regulations</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-442206"><span class="HTitleText1">Coming into Force of Regulations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-442217"><span class="HTitleText1">Publication in Canada Gazette</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-442239"><span class="HTitleText1">Indexes</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-442247"><span class="HTitleText1">Revisions and Consolidations of Regulations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-442255"><span class="HTitleText1">Judicial Notice of Statutory Instruments</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-442267"><span class="HTitleText1">Right of Access to Statutory Instruments</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="page-2.html#h-442280"><span class="HTitleText1">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-442333"><span class="HTitleText1">Scrutiny by Parliament of Statutory Instruments</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-442364"><span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

