<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi d’exécution du budget et de l’énoncé économique de 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-33888"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-33891"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modifications concernant la taxe sur les produits et services et la taxe de vente harmonisée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-33892"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-33899"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification concernant la taxe d’accise sur les carburants renouvelables</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-33900"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-33902"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modifications relatives à l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-33903"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-33964"><span class="HTitleText2">Règles concernant l’application de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-33966"><span class="HTitleText2">Loi sur l’interprétation des conventions en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-33968"><span class="HTitleText2">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-33988"><span class="HTitleText2">Règlement sur le Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-33990"><span class="HTitleText2">Règlement sur la rémunération assurable et la perception des cotisations</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-33992"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-34002"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Épargne-invalidité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-34003"><span class="HTitleText2">Modifications relatives à l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-34004"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-34029"><span class="HTitleText3">Règlement de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-34033"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="#h-34034"><span class="HTitleText4">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-34036"><span class="HTitleText4">Loi sur la sécurité de la vieillesse</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-34038"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-34044"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-34046"><span class="HTitleText2">Loi canadienne sur l’épargne-invalidité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-34047"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-34050"><span class="HTitleText3">Modification corrélative à la <cite class="XRefExternalAct">Loi sur les allocations spéciales pour enfants</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-34052"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>139 - </span><a href="#h-34055"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Incitatif pour l’élimination des impôts provinciaux sur le capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>139 - </span><a href="#h-34056"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-34058"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Loi sur l’immunité de la banque des règlements internationaux</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-34061"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Retraite progressive — modifications autres que celles concernant l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-34062"><span class="HTitleText2">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-34065"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-34068"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Garantie de marché</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-34078"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Opérations pétrolières au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="#h-34079"><span class="HTitleText2">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-34086"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-34087"><span class="HTitleText3">Loi fédérale sur les hydrocarbures</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-34089"><span class="HTitleText3">Loi sur l’Office national de l’énergie</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>154 - </span><a href="#h-34092"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Modifications à la Loi sur la protection du revenu agricole</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-34100"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="#h-34101"><span class="HTitleText2">Modifications à la Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-34110"><span class="HTitleText2">Modifications à la Loi d’exécution du budget de 2007</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-34114"><span class="HTitleText2">Modification corrélative à la <cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-34116"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-34120"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="#h-34126"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">Modifications à la loi canadienne sur l’épargne-études</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-34129"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">Partenariats public-privé</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-34132"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1">Modifications d’ordre fiscal visant à mettre en oeuvre l’énoncé économique de 2007</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-34133"><span class="HTitleText2">Modifications relatives à l’impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-34134"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="#h-34139"><span class="HTitleText2">Modifications visant à mettre en oeuvre la réduction du taux de la TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-34140"><span class="HTitleText3">Loi sur la taxe d’accise</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="#h-34154"><span class="HTitleText2">Modifications connexes découlant de la réduction du taux de la TPS/TVH</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="#h-34155"><span class="HTitleText3">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-34157"><span class="HTitleText3">Loi de 2001 sur l’accise</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-34158"><span class="HTitleText4">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-34171"><span class="HTitleText4">Application</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
