<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les serments d’allégeance</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-373759"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-373764"><span class="HTitleText1">Serment d’allégeance</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-373772"><span class="HTitleText1">Affirmation solennelle</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-373777"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-373784"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
