<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi concernant la « Buffalo and Fort Erie Public Bridge Company »</a><ul class="TocIndent"><li><a href="page-2.html#h-39185"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - Lois de l’État de New-York — Par autorisation</span> - <span class="scheduleTitleText"> - Chapitre 824</span></a>
</li></ul>
</li></ul>

</nav>

