<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Race Relations Foundation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-73810"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-73813"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-73822"><span class="HTitleText1">Establishment of Foundation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-73825"><span class="HTitleText1">Purpose of Foundation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-73835"><span class="HTitleText1">Powers and Capacity of Foundation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-73850"><span class="HTitleText1">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-73874"><span class="HTitleText1">Executive Director</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-73888"><span class="HTitleText1">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-73896"><span class="HTitleText1">Committees</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-73899"><span class="HTitleText1">Principal Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-73911"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-73920"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-73957"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-73979"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-73992"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

