<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le rétablissement de la livraison du courrier aux Canadiens</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-417350"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-417353"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-417365"><span class="HTitleText1">Services postaux</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-417379"><span class="HTitleText1">Prorogation de la convention collective</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-417390"><span class="HTitleText1">Choix de l’offre finale</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-417429"><span class="HTitleText1">Nouvelle convention collective</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-417443"><span class="HTitleText1">Frais</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-417446"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-417460"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
