<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Navigable Waters Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Approval of Works</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2">Ministerial Orders</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-10"><span class="HTitleText2">Interim Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Obstacles and Obstructions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>14.1 - </span><a href="#h-13"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-14"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Regulation of Ferry Cables and Swing or Draw Bridges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-16"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-17"><span class="HTitleText2">Interim Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-18"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-19"><span class="HTitleText2">Designation</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-20"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-21"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-22"><span class="HTitleText2">Injunction</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-23"><span class="HTitleText2">Immunity</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-24"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-25"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Review</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
