<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Law—Civil Law Harmonization Act, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-238811"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-238814"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Federal Law and Civil Law of the Province of Quebec</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-238815"><span class="HTitleText2">Title</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-238818"><span class="HTitleText2">Civil Code of Lower Canada</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-238824"><span class="HTitleText2">Marriage</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-238835"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>9 to 24 - </span><a href="#h-238837"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the Federal Real Property Act</span></a>
</li>
<li><span class='sectionRange'>25 to 33 - </span><a href="#h-238839"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Amendments to the Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>34 to 52 - </span><a href="#h-238841"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Amendments to the Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>53 to 128 - </span><a href="#h-238843"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Miscellaneous Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>129 to 173 - </span><a href="#h-238845"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-238847"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-238850"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Transitional Provision and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="#h-238851"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-238859"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
