<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la radiation de condamnations constituant des injustices historiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-206427"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-206430"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-206435"><span class="HTitleText1">Attributions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-206440"><span class="HTitleText1">Radiation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-206441"><span class="HTitleText2">Effets</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-206449"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-206486"><span class="HTitleText2">Ordonnance</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-206493"><span class="HTitleText2">Destruction et suppression</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-206506"><span class="HTitleText2">Communication de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-1.html#h-206509"><span class="HTitleText1">Modifications à l’annexe</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-206515"><span class="HTitleText1">Critères</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-206518"><span class="HTitleText1">Infractions d’ordre sexuel entre des personnes du même sexe</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-1.html#h-206526"><span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-1.html#h-206527"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-1.html#h-206531"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite></span></a>
</li></ul>
</li><li><a href="page-2.html#h-206534"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

