<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les paiements anticipés pour le grain des Prairies</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Avances pour du grain battu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Pouvoir de verser des avances</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Demande</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Engagement</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Coproducteurs</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Montant de l’avance</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Avances de secours pour le séchage du grain</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Avances de secours pour du grain non battu</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Mention dans le carnet de livraison</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-12"><span class="HTitleText2">Pouvoirs de la Commission</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-13"><span class="HTitleText2">Privilège relatif aux avances</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-14"><span class="HTitleText1">Livraisons de grain</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-15"><span class="HTitleText1">Défaut à l’égard d’un engagement</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
