<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Impact Assessment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1160079"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1160082"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1160164"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1160167"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1160170"><span class="HTitleText1">Purposes</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-1160193"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-1160225"><span class="HTitleText1">Designation of Physical Activity</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-1160245"><span class="HTitleText1">Planning Phase</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-1160246"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-1160273"><span class="HTitleText2">Decisions Regarding Impact Assessments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-1160274"><span class="HTitleText3">Agency’s Decision</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1160289"><span class="HTitleText3">Minister’s Notice</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-1160295"><span class="HTitleText2">Information Gathering</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-1160329"><span class="HTitleText1">Impact Assessments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-1160330"><span class="HTitleText2">Consultation and Cooperation with Certain Jurisdictions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-1160335"><span class="HTitleText2">Factors To Be Considered</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-1160364"><span class="HTitleText2">Federal Authority’s Obligation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-1160370"><span class="HTitleText2">Impact Assessment by Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-1160371"><span class="HTitleText3">General Rules</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-1160421"><span class="HTitleText3">Substitution</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-1160459"><span class="HTitleText2">Impact Assessment by a Review Panel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-1160460"><span class="HTitleText3">General Rules</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-1160644"><span class="HTitleText3">Confidential Information</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-1160647"><span class="HTitleText3">Rules in Case of Termination</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-1160669"><span class="HTitleText2">Decision-Making</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-1160708"><span class="HTitleText2">Decision Statement</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-1160777"><span class="HTitleText2">Termination of Impact Assessment</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-1160780"><span class="HTitleText2">Confidential Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-1160783"><span class="HTitleText1">Participant Funding Programs</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-1160792"><span class="HTitleText1">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-1160814"><span class="HTitleText1">Duties of Certain Authorities in Relation to Projects</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-1160875"><span class="HTitleText1">Regional Assessments and Strategic Assessments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="#h-1160876"><span class="HTitleText2">Regional Assessments</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-1160894"><span class="HTitleText2">Strategic Assessments</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-1160902"><span class="HTitleText2">General Rules</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-1160928"><span class="HTitleText1">Canadian Impact Assessment Registry</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-1160929"><span class="HTitleText2">Establishment of Registry</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-1160937"><span class="HTitleText2">Internet Site</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-1160969"><span class="HTitleText2">Project Files</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-1160986"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-1161000"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-1161092"><span class="HTitleText1">Minister’s Advisory Council</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-1161114"><span class="HTitleText1">Indigenous Knowledge</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-1161129"><span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-1161130"><span class="HTitleText2">Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-1161138"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-1161183"><span class="HTitleText2">Notice of Non-compliance</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-1161193"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-1161225"><span class="HTitleText2">Review of Orders</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-1161264"><span class="HTitleText2">Federal Court</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-1161269"><span class="HTitleText2">Injunctions</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-1161277"><span class="HTitleText2">Voluntary Reports</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-1161292"><span class="HTitleText2">Prohibitions and Offences</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-1161339"><span class="HTitleText2">Publication</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-1161347"><span class="HTitleText1">Impact Assessment Agency of Canada</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-1161430"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-1161436"><span class="HTitleText1">Review of Act</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-1161439"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><a href="#h-1161540"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Federal Authorities</span></a>
</li>
<li><a href="#h-1161545"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Lands that are Subject to a Land Claim Agreement</span></a>
</li>
<li><a href="#h-1161547"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Components of the Environment and Health, Social or Economic Matters</span></a>
</li>
<li><a href="#h-1161554"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - Bodies</span></a>
</li></ul>
</li></ul>

</nav>

