<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Customs and Revenue Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Establishment and Mandate of the Agency</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Minister</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">Structure of the Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText2">Board of Management</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText2">Chair</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText2">Commissioner and Deputy Commissioner</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-10"><span class="HTitleText1">General Authority of the Agency</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText1">Management and Direction of the Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText2">Responsibilities of the Board</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-13"><span class="HTitleText2">Responsibilities of the Commissioner</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-14"><span class="HTitleText2">Duties and Indemnification of Directors</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-15"><span class="HTitleText1">Corporate Business Plan</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-16"><span class="HTitleText1">Human Resources</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-17"><span class="HTitleText1">Expenditures</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-18"><span class="HTitleText1">Contracts, Agreements, Arrangements and Legal Proceedings</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-19"><span class="HTitleText1">Intellectual Property</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-20"><span class="HTitleText1">Real Property and Immovables</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-21"><span class="HTitleText1">Reports to Parliament</span></a>
</li>
<li><span class='sectionRange'>89.1 - </span><a href="#h-22"><span class="HTitleText1">Application of the Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-23"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>106 to 185.1 - </span><a href="#h-24"><span class="HTitleText1">Consequential and Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-25"><span class="HTitleText1">Other Referential Amendments</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-26"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-27"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
