<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Service Staff Relations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Public Service</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Additions to and Transfers within Schedule I</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="#h-6"><span class="HTitleText2">Managerial or Confidential Positions</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText1">Basic Rights and Prohibitions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText2">Rights</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-10"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Public Service Staff Relations Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-11"><span class="HTitleText2">Constitution of Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-12"><span class="HTitleText3">Chairperson and Members</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText3">Remuneration</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-14"><span class="HTitleText3">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText3">Staff and Experts</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-16"><span class="HTitleText2">Powers and Duties of the Board</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Collective Bargaining and Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText2">Certification of Bargaining Agents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText3">Application for Certification</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-20"><span class="HTitleText3">When Application for Certification may be made</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-21"><span class="HTitleText3">Determination of Appropriate Bargaining Units</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-22"><span class="HTitleText3">Certification</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-23"><span class="HTitleText3">Where Certification Prohibited</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-24"><span class="HTitleText3">Effect of Certification</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-25"><span class="HTitleText2">Revocations of Certification</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-26"><span class="HTitleText3">On Application</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-27"><span class="HTitleText3">For Abandonment or Other Cause</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-28"><span class="HTitleText3">For Fraud</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-29"><span class="HTitleText3">Revocation of Certification of Council</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-30"><span class="HTitleText3">Effect of Revocation: Rights of Employee Organizations and Employees</span></a>
</li>
<li><span class='sectionRange'>48.1 - </span><a href="#h-31"><span class="HTitleText3">Successor Rights</span></a>
</li></ul>
</li><li><span class='sectionRange'>49.1 - </span><a href="#h-32"><span class="HTitleText2">Negotiation of Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49.1 - </span><a href="#h-33"><span class="HTitleText3">Master Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-34"><span class="HTitleText3">Notice to Bargain Collectively</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-35"><span class="HTitleText3">Where Notice Given</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-36"><span class="HTitleText3">Conciliation</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="#h-37"><span class="HTitleText3">Fact Finding</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="#h-38"><span class="HTitleText2">Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-39"><span class="HTitleText3">Authority to enter into Agreement</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-40"><span class="HTitleText3">Provisions of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-41"><span class="HTitleText3">Duration and Effect</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-42"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Provisions Applicable to Resolution of Disputes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="#h-43"><span class="HTitleText2">Alternate Dispute Resolution Process</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-44"><span class="HTitleText2">Suspension</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-45"><span class="HTitleText2">Arbitration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-46"><span class="HTitleText3">Request for Arbitration</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-47"><span class="HTitleText3">Establishment of Arbitration Board</span></a>
</li>
<li><span class='sectionRange'>65.1 - </span><a href="#h-48"><span class="HTitleText3">Appointment of Arbitrator</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-49"><span class="HTitleText3">Subject-Matter of Arbitral Award</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-50"><span class="HTitleText3">Making of Arbitral Award</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-51"><span class="HTitleText3">Duration and Operation of Arbitral Awards</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-52"><span class="HTitleText3">Implementation of Arbitral Awards</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-53"><span class="HTitleText3">Completion and Variation of Arbitral Awards</span></a>
</li></ul>
</li><li><span class='sectionRange'>76 - </span><a href="#h-54"><span class="HTitleText2">Conciliation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-55"><span class="HTitleText3">Request for Conciliation</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-56"><span class="HTitleText3">Establishment of Conciliation Board</span></a>
</li>
<li><span class='sectionRange'>77.1 - </span><a href="#h-57"><span class="HTitleText3">Appointment of Conciliation Commissioner</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-58"><span class="HTitleText3">Designated Positions</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-59"><span class="HTitleText3">Terms of Reference</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-60"><span class="HTitleText3">Procedure</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-61"><span class="HTitleText3">Report</span></a>
</li>
<li><span class='sectionRange'>90.1 - </span><a href="#h-62"><span class="HTitleText3">Vote on Employer’s Offer</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-63"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-64"><span class="HTitleText2">Right to Present Grievances</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-65"><span class="HTitleText2">Adjudication of Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="#h-66"><span class="HTitleText3">Reference to Adjudication</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-67"><span class="HTitleText3">Appointment of Adjudicators</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-68"><span class="HTitleText3">Establishment of a Board of Adjudication</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-69"><span class="HTitleText3">Duty of the Board</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-70"><span class="HTitleText3">Jurisdiction of Adjudicator</span></a>
</li>
<li><span class='sectionRange'>96.1 - </span><a href="#h-71"><span class="HTitleText3">Powers of Adjudicator</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-72"><span class="HTitleText3">Decision of Adjudicator</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-73"><span class="HTitleText3">Expenses of Adjudication</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-74"><span class="HTitleText3">Enforcement of Obligations of Employer and Employee Organizations</span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="#h-75"><span class="HTitleText2">Regulations respecting Grievances</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-76"><span class="HLabel1">PART V</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-77"><span class="HTitleText2">Rights and Prohibitions relating to Strikes</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-78"><span class="HTitleText2">Consent to Prosecution</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-79"><span class="HTitleText2">Protection of Members and Staff</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-80"><span class="HTitleText2">Witness Fees</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-81"><span class="HTitleText2">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-82"><span class="HTitleText2">Provision of Facilities and Staff</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-83"><span class="HTitleText2">Superannuation</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-84"><span class="HTitleText2">Saving Provision</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-85"><span class="HTitleText2">Report to Parliament</span></a>
</li></ul>
</li><li><a href="#h-86"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-87"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="#h-88"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
