<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting the Buffalo and Fort Erie Public Bridge Company</a><ul class="TocIndent"><li><a href="#h-40151"><span class="scheduleLabel">SCHEDULE</span> - <span class="scheduleTitleText"> - Laws of New York. — By Authority</span> - <span class="scheduleTitleText"> - Chapter 824</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
