<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la représentation (1974)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-417275"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-417278"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Acte de l’Amérique du Nord britannique</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-417283"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Revision des limites des circonscriptions électorales</span></a>
</li></ul>
</li></ul>

</nav>

