<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Competition Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-2"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Purpose and Interpretation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1.1 - </span><a href="#h-3"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText2">Interpretation</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-6"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Mutual Legal Assistance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-7"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>30.01 - </span><a href="#h-8"><span class="HTitleText2">Functions of the Minister of Justice</span></a>
</li>
<li><span class='sectionRange'>30.02 - </span><a href="#h-9"><span class="HTitleText2">Publication of Agreements</span></a>
</li>
<li><span class='sectionRange'>30.03 - </span><a href="#h-10"><span class="HTitleText2">Requests Made to Canada from Abroad</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30.03 - </span><a href="#h-11"><span class="HTitleText3">Requests</span></a>
</li>
<li><span class='sectionRange'>30.04 - </span><a href="#h-12"><span class="HTitleText3">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-13"><span class="HTitleText3">Evidence for Use Abroad</span></a>
</li>
<li><span class='sectionRange'>30.19 - </span><a href="#h-14"><span class="HTitleText3">Lending Exhibits</span></a>
</li>
<li><span class='sectionRange'>30.24 - </span><a href="#h-15"><span class="HTitleText3">Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>30.25 - </span><a href="#h-16"><span class="HTitleText2">Evidence Obtained by Canada from Abroad</span></a>
</li>
<li><span class='sectionRange'>30.29 - </span><a href="#h-17"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-18"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Special Remedies</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-19"><span class="HLabel1">PART V</span> - <span class="HTitleText1">[Repealed, R.S., 1985, c. 19 (2nd Supp.), s. 29]</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-20"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Offences in Relation to Competition</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-21"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Other Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-22"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-23"><span class="HTitleText2">Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>74.01 - </span><a href="#h-24"><span class="HLabel1">PART VII.1</span> - <span class="HTitleText1">Deceptive Marketing Practices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>74.01 - </span><a href="#h-25"><span class="HTitleText2">Reviewable Matters</span></a>
</li>
<li><span class='sectionRange'>74.09 - </span><a href="#h-26"><span class="HTitleText2">Administrative Remedies</span></a>
</li>
<li><span class='sectionRange'>74.17 - </span><a href="#h-27"><span class="HTitleText2">Rules of Procedure</span></a>
</li>
<li><span class='sectionRange'>74.18 - </span><a href="#h-28"><span class="HTitleText2">Appeals</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-29"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Matters Reviewable by Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-30"><span class="HTitleText2">Restrictive Trade Practices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-31"><span class="HTitleText3">Refusal to Deal</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-32"><span class="HTitleText3">Price Maintenance</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-33"><span class="HTitleText3">Exclusive Dealing, Tied Selling and Market Restriction</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-34"><span class="HTitleText3">Abuse of Dominant Position</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-35"><span class="HTitleText3">Delivered Pricing</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-36"><span class="HTitleText3">Foreign Judgments and Laws</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-37"><span class="HTitleText3">Foreign Suppliers</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-38"><span class="HTitleText2">Specialization Agreements</span></a>
</li>
<li><span class='sectionRange'>90.1 - </span><a href="#h-39"><span class="HTitleText2">Agreements or Arrangements that Prevent or Lessen Competition Substantially</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-40"><span class="HTitleText2">Mergers</span></a>
</li>
<li><span class='sectionRange'>103.1 - </span><a href="#h-41"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-42"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Notifiable Transactions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-43"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-44"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-45"><span class="HTitleText2">Exemptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-46"><span class="HTitleText3">Acquisition of Voting Shares, Assets or Interests</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-47"><span class="HTitleText3">Combinations</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-48"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-49"><span class="HTitleText2">Notice and Information</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-50"><span class="HTitleText2">Completion of Proposed Transactions</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-51"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>124.1 - </span><a href="#h-52"><span class="HLabel1">PART X</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124.1 - </span><a href="#h-53"><span class="HTitleText2">Commissioner’s Opinions</span></a>
</li>
<li><span class='sectionRange'>124.2 - </span><a href="#h-54"><span class="HTitleText2">References to Tribunal</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-55"><span class="HTitleText2">Representations to Boards, Commissions or Other Tribunals</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-56"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-57"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
