<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Foreign Missions and International Organizations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-234972"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-234975"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-234995"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Foreign Diplomatic Missions and Consular Posts</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-235020"><span class="HLabel1">PART II</span> - <span class="HTitleText1">International Organizations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-235049"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Political Subdivisions of Foreign States</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-235075"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-235076"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-235096"><span class="HTitleText2">Security of Intergovernmental Conferences</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-235108"><span class="HTitleText2">Certificate</span></a>
</li>
<li><span class='sectionRange'>11.1 - </span><a href="#h-235118"><span class="HTitleText2">Importation of Alcohol</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-235125"><span class="HTitleText2">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>14 and 15 - </span><a href="#h-235142"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-235144"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-235147"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-235151"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Vienna Convention on Diplomatic Relations</span></a>
</li>
<li><a href="#h-235415"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Vienna Convention on Consular Relations</span></a>
</li>
<li><a href="#h-235841"><span class="scheduleLabel">SCHEDULE III</span> <span class="scheduleTitleText"> - Convention on the Privileges and Immunities of the United Nations</span></a>
</li>
<li><a href="#h-18"><span class="scheduleLabel">SCHEDULE IV</span> <span class="scheduleTitleText"> - Designated Treaties, Conventions and Agreements</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
