<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’exportation et l’importation des diamants bruts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-197303"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-197306"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-197319"><span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-197335"><span class="HTitleText1">Exportation de diamants bruts</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-197366"><span class="HTitleText1">Diamants bruts importés</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-197389"><span class="HTitleText1">Diamants bruts en transit</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-197399"><span class="HTitleText1">Inspections</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-197421"><span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-197426"><span class="HTitleText1">Mesures consécutives à la saisie</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-197444"><span class="HTitleText1">Confiscation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-197458"><span class="HTitleText1">Responsabilité pour frais</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-197464"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-197481"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-197532"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-15"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
