<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi fédérale sur le développement durable</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-234652"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-234655"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-234664"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-234667"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-234670"><span class="HTitleText1">Principe fondamental</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-234673"><span class="HTitleText1">Comité</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-234676"><span class="HTitleText1">Bureau</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-234684"><span class="HTitleText1">Conseil consultatif sur le développement durable</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-234696"><span class="HTitleText1">Stratégie fédérale de développement durable</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-1263488"><span class="HTitleText1">Stratégies de développement durable des entités désignées</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-234730"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="page-2.html#h-1263532"><span class="HTitleText1">Examen permanent</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-234733"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-234736"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-2.html#h-234737"><span class="HTitleText2">Loi sur le vérificateur général</span></a>
</li></ul>
</li><li><a href="page-3.html#h-1263551"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

