<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la statistique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-430401"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-430406"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-430416"><span class="HTitleText1">Statistique Canada</span></a>
</li>
<li><span class='sectionRange'>8.1 - </span><a href="page-1.html#h-430503"><span class="HTitleText1">Conseil consultatif canadien de la statistique</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-430521"><span class="HTitleText1">Statistique</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-430586"><span class="HTitleText1">Secret</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-430635"><span class="HTitleText1">Recensement de la population et recensement agricole</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-430658"><span class="HTitleText1">Statistique générale</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-430709"><span class="HTitleText1">Statistique criminelle</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-430726"><span class="HTitleText1">Infractions et peines</span></a>
</li></ul>
</li></ul>

</nav>

