<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Accord sur les revendications territoriales des Inuit du Labrador</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-335468"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-335471"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-335481"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-335487"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-335502"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-335505"><span class="HTitleText1">Fiscalité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-335510"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-335538"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-335539"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-335541"><span class="HTitleText2">Loi sur les parcs nationaux du Canada</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-335543"><span class="HTitleText2">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-335546"><span class="HTitleText2">Loi sur les paiements versés en remplacement d’impôts</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-335548"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-335550"><span class="HTitleText1">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-335551"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-335553"><span class="HTitleText2">Loi sur l’enregistrement des lobbyistes</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-335555"><span class="HTitleText2">Loi sur les paiements versés en remplacement d’impôts</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-335557"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-335559"><span class="HTitleText2">Autres modifications</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-335561"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
