<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le ministère des Anciens Combattants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-452873"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="page-1.html#h-452878"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-452883"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-452895"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-452908"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>5.2 - </span><a href="page-1.html#h-452953"><span class="HTitleText1">Trop-perçu</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-452969"><span class="HTitleText1">Serments et affidavits</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="page-1.html#h-452977"><span class="HTitleText1">Bureau de services juridiques des pensions</span></a>
</li>
<li><span class='sectionRange'>6.3 - </span><a href="page-2.html#h-452996"><span class="HTitleText1">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-453034"><span class="HTitleText1">Rapport annuel</span></a>
</li></ul>
</li></ul>

</nav>

