<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la croissance économique et la prospérité — Canada-Corée</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-144263"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-144266"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-144279"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-144282"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-144293"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-144299"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’accord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-144300"><span class="HTitleText2">Approbation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-144303"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-144308"><span class="HTitleText2">Groupes spéciaux, groupes d’experts, comités, sous-comités, groupes de travail et autres organes</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-144330"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-144347"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-144348"><span class="HTitleText2">Loi sur la responsabilité civile de l’État et le contentieux administratif</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-144351"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-144353"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-144360"><span class="HTitleText2">Loi sur l’arbitrage commercial</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-144362"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-144373"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-144388"><span class="HTitleText2">Loi sur le ministère de l’Emploi et du Développement social</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-144391"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-144392"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-144395"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-144399"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-144402"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
