<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant les enfants, les jeunes et les familles des Premières Nations, des Inuits et des Métis</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1137031"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-1137053"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-1137056"><span class="HTitleText1">Objet et principes</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-1137079"><span class="HTitleText1">Intérêt de l’enfant autochtone</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-1137097"><span class="HTitleText1">Fourniture des services à l’enfance et à la famille</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-1137122"><span class="HTitleText1">Placement de l’enfant autochtone</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-1137141"><span class="HTitleText1">Compétence en matière de services à l’enfance et à la famille</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-1137149"><span class="HTitleText1">Texte législatif d’un groupe, d’une collectivité ou d’un peuple autochtones</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-1137150"><span class="HTitleText2">Coordination et application</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-1137193"><span class="HTitleText2">Publication et accessibilité</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-1137201"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-1137222"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-1137228"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-1137236"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

