<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en œuvre de la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles et du Protocole portant sur les questions spécifiques aux matériels d’équipement aéronautiques à la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-265517"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-265520"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-265534"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-265537"><span class="HTitleText1">Force de loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-265545"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-265548"><span class="HTitleText1">Incompatibilité</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-265556"><span class="HTitleText1">Tribunaux</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-265559"><span class="HTitleText1">Demandes de déclaration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-265565"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="page-1.html#h-265568"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-265573"><span class="HTitleText1">Modifications à certaines lois</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-265574"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-265576"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-265581"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-265584"><span class="HTitleText2">Loi sur les liquidations et les restructurations</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-1.html#h-265587"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-2.html#h-265591"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles</span></a>
</li>
<li><a href="page-3.html#h-266086"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole portant sur les questions spécifiques aux matériels d’équipement aéronautiques à la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles</span></a>
</li>
<li><a href="page-4.html#h-266397"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Texte refondu de la Convention relative aux garanties internationales portant sur des matériels d’équipement mobiles et de son Protocole portant sur les questions spécifiques aux matériels d’équipement aéronautiques</span></a>
</li></ul>
</li></ul>

</nav>

