<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Department of Public Safety and Emergency Preparedness Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-401507"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-401510"><span class="HTitleText1">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-401518"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-401543"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-401558"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-401559"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-401562"><span class="HTitleText2">Canadian Centre on Substance Abuse Act</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-401564"><span class="HTitleText2">Canadian Peacekeeping Service Medal Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-401566"><span class="HTitleText2">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-401568"><span class="HTitleText2">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-401570"><span class="HTitleText2">Controlled Drugs and Substances Act</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-401573"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-401575"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-401584"><span class="HTitleText2">DNA Identification Act</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-1.html#h-401586"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-1.html#h-401589"><span class="HTitleText2">Firearms Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-1.html#h-401591"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-1.html#h-401594"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-1.html#h-401597"><span class="HTitleText2">Terminology Changes</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-1.html#h-401599"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-1.html#h-401602"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-1.html#h-401604"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

