<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Marine Atlantic Inc. Acquisition Authorization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-348738"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-348741"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-348746"><span class="HTitleText1">Change of Name</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-348752"><span class="HTitleText1">Transfer of Shares</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-348770"><span class="HTitleText1">Transfer of Property</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-348781"><span class="HTitleText1">Amendment of Articles</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-348784"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-348787"><span class="HTitleText1">Commencement</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
