<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des eaux navigables</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Ouvrages nécessitant une approbation préalable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Obstacles ou obstructions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-11"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-12"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Règlements sur les câbles de traille et ponts tournants ou ponts-bascule</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-13"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
