<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Soldier Settlement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-432949"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-432954"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-433013"><span class="HLabel1">PART I</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-433014"><span class="HTitleText2">Constitutions of the Board</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-433027"><span class="HTitleText2">Corporate Powers of the Board</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-433051"><span class="HTitleText2">Reservation and Acquirement of Lands and Other Property</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-433108"><span class="HTitleText2">Agricultural Training</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-433118"><span class="HTitleText2">Soldier Grants</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-433131"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Sales and Advances to Settlers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-433132"><span class="HTitleText2">Sales of Land</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-433148"><span class="HTitleText2">Sales of Stock and Equipment</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-433161"><span class="HTitleText2">Advances for Improvements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-433171"><span class="HTitleText2">Terms of Disposition of Property</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-433187"><span class="HTitleText2">Resale upon Default</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-433209"><span class="HTitleText2">Leasing of Lands</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-433214"><span class="HTitleText2">Advances for the Discharge of Encumbrances</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-433232"><span class="HTitleText2">Charges on Dominion Lands</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-433244"><span class="HTitleText2">Limitations upon Sales and Advances</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-433252"><span class="HTitleText2">Sales for Special Purposes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-433260"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-433306"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Compulsory Purchase of Lands</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-433307"><span class="HTitleText2">Settlement Areas</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-433343"><span class="HTitleText2">Duties of Owners of Lands Within a Settlement Area</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-433355"><span class="HTitleText2">Procedure for Compulsory Purchase</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-433401"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-433406"><span class="HTitleText2">Payment of Compensation or Costs</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-433411"><span class="HTitleText2">Interest</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-433419"><span class="HTitleText2">Resistance to Peaceful Possession</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-433427"><span class="HTitleText2">Inspection and Survey of and Entry upon Lands</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-433448"><span class="HTitleText2">Directions Respecting Compulsory Purchases</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-433456"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Miscellaneous Provisions</span></a>
</li>
<li><a href="#h-433703"><span class="scheduleLabel">SCHEDULE OF FORMS</span></a>
</li></ul>
</li></ul>

</nav>

