<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
An Act to amend the Hazardous Products Act and the Canada Labour Code, to enact the Hazardous Materials Information Review Act and to amend other Acts in relation thereto</a><ul class="TocIndent"><li><span class='sectionRange'>1 and 2 - </span><a href="page-1.html#h-252843"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Hazardous Products Act</span></a>
</li>
<li><span class='sectionRange'>3 to 8 - </span><a href="page-1.html#h-252845"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>9 to 51 - </span><a href="page-1.html#h-252847"><span class="HTitleText1">Part III</span></a>
</li>
<li><span class='sectionRange'>52 and 53 - </span><a href="page-1.html#h-252849"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Related Amendments, Transitional and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 and 53 - </span><a href="page-1.html#h-252850"><span class="HTitleText2">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-1.html#h-252852"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-1.html#h-252871"><span class="HTitleText2">Review by Parliament</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-1.html#h-252874"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-2.html#h-252878"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

