<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’administration de l’énergie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-213753"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-213758"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-213774"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-213779"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Redevances d’exportation sur le pétrole</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-213895"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Redevance de recouvrement en matière de carburant de soute</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-213928"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Pétrole canadien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-213929"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-213941"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-213948"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-213957"><span class="HTitleText2">Contrôle des prix</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-214006"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-214035"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-214044"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Gaz domestique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-214045"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-214074"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-214081"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-214090"><span class="HTitleText2">Contrôle des prix</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-214145"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-214174"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-214184"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-214210"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Redevances d’indemnisation pétrolière</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-214304"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Dispositions visant la canadianisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-214305"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Redevance spéciale et taxation</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-214326"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Compte d’accroissement du taux de propriété canadienne</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-214397"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Indemnité compensatrice du coût</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="#h-214402"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Indemnité pétrolière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="#h-214403"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-214410"><span class="HTitleText3">Versement de l’indemnité</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-214442"><span class="HTitleText3">Comptabilité</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-214464"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Indemnités de transfert des ressources en pétrole</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-214465"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-214474"><span class="HTitleText3">Ordre du gouverneur en conseil à l’Office</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-214479"><span class="HTitleText3">Indemnités</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-214500"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-214515"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
