<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Assisted Human Reproduction Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Principles</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Prohibited Activities</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">Controlled Activities</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">Privacy and Access to Information</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-7"><span class="HTitleText1">Responsibility of Minister</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText1">Assisted Human Reproduction Agency of Canada</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-9"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-10"><span class="HTitleText1">Inspection and Enforcement</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-11"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-12"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-13"><span class="HTitleText1">Equivalency Agreements</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-14"><span class="HTitleText1">Parliamentary Review</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-15"><span class="HTitleText1">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-16"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-17"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-18"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-19"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-20"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-21"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-22"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
