<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les déclarations des personnes morales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-102713"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-102718"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-102743"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Personnes morales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-102744"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-102770"><span class="HTitleText2">Déclarations</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-102836"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-102850"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">[Abrogée, 1998, ch. 26, art. 65]</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-102851"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
