<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les institutions financières et modifiant le système d’assurance-dépôts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-217288"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 à 46 - </span><a href="#h-217291"><span class="HLabel1">PARTIE I</span></a>
</li>
<li><span class='sectionRange'>47 à 73 - </span><a href="#h-217293"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Loi sur la Société d’assurance-dépôts du Canada</span></a>
</li>
<li><span class='sectionRange'>74 à 84 - </span><a href="#h-217295"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-217297"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>86 à 101 - </span><a href="#h-217299"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>102 à 123 - </span><a href="#h-217301"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Loi sur les compagnies d’assurance canadiennes et britanniques</span></a>
</li>
<li><span class='sectionRange'>124 à 136 - </span><a href="#h-217303"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Loi sur les compagnies d’assurance étrangères</span></a>
</li>
<li><span class='sectionRange'>137 à 142 - </span><a href="#h-217305"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Loi sur les sociétés d’investissement</span></a>
</li>
<li><span class='sectionRange'>143 à 158 - </span><a href="#h-217307"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Loi sur les sociétés de prêt</span></a>
</li>
<li><span class='sectionRange'>159 à 173 - </span><a href="#h-217309"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Loi sur les sociétés de fiducie</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-217311"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

