<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’équité en matière d’emploi</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-209718"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-209721"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-209726"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-209749"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-209776"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Équité en matière d’emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-209777"><span class="HTitleText2">Obligations de l’employeur</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-209865"><span class="HTitleText2">Dossiers et rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-209944"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-209945"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-209972"><span class="HTitleText2">Engagement de l’employeur et ordres</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-210003"><span class="HTitleText2">Demande de révision ou d’ordonnance</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-210013"><span class="HTitleText2">Tribunal de l’équité en matière d’emploi</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-210070"><span class="HTitleText2">Restriction</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-210086"><span class="HTitleText2">Renseignements protégés</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-210098"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Sanctions pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-210099"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-210124"><span class="HTitleText2">Options</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-210157"><span class="HTitleText2">Exécution des sanctions pécuniaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-210163"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-210214"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>46 à 53 - </span><a href="#h-210217"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-210219"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-210221"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

