<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Intelligence Commissioner Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1170182"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1170185"><span class="HTitleText1">Definition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1170188"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1170191"><span class="HTitleText1">Commissioner</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-1170243"><span class="HTitleText1">Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-1170280"><span class="HTitleText1">Public Report</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-1170288"><span class="HTitleText1">Information</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
