<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1995 pour la mise en oeuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-313409"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-313412"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Convention Canada — Lettonie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-313428"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Convention Canada — Estonie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-313444"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Convention Canada — Trinité et Tobago en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>20 à 22 - </span><a href="#h-313460"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Protocole à la convention Canada — Hongrie en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="#h-313463"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Convention entre le Canada et la République de la Lettonie en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-313759"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Convention entre le Canada et la République d’Estonie en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-314054"><span class="scheduleLabel">ANNEXE III</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement de la République de la Trinité et Tobago en vue d’éviter les doubles impositions, de prévenir l’évasion fiscale en matière d’impôts sur le revenu et d’encourager le commerce et les investissements internationaux</span></a>
</li>
<li><a href="#h-314330"><span class="scheduleLabel">ANNEXE IV</span></a>
</li></ul>
</li></ul>

</nav>

