<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Asia-Pacific Foundation of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Foundation Established</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Purpose of Foundation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Powers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText1">President and Staff</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText1">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText1">Committees</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-11"><span class="HTitleText1">Status of Foundation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-12"><span class="HTitleText1">Registered Charity</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HTitleText1">Financial</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-14"><span class="HTitleText1">Dissolution</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-15"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-16"><span class="HTitleText1">Report</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-17"><span class="HTitleText1">Review</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
