<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la preuve au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-133989"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-133994"><span class="HTitleText1">Partie I</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-133995"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-134000"><span class="HTitleText2">Témoins</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-134074"><span class="HTitleText2">Serments et affirmations solennelles</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-134129"><span class="HTitleText2">Admission d’office</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-134138"><span class="HTitleText2">Preuve documentaire</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="page-4.html#h-134376"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-134381"><span class="HTitleText2">Renseignements d’intérêt public</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-134437"><span class="HTitleText2">Relations internationales et défense et sécurité nationales</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-6.html#h-134685"><span class="HTitleText2">Renseignements confidentiels du Conseil privé de la Reine pour le Canada</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="page-6.html#h-134705"><span class="HTitleText2">Sources journalistiques</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-6.html#h-134745"><span class="HTitleText2">Lois provinciales concernant la preuve</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-6.html#h-134750"><span class="HTitleText2">Déclarations solennelles</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-7.html#h-134757"><span class="HTitleText2">Preuves des assurances</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="page-7.html#h-134762"><span class="HTitleText1">Partie II</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="page-7.html#h-134763"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-7.html#h-134768"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-7.html#h-134781"><span class="HTitleText2">Procédure</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="page-7.html#h-134819"><span class="HTitleText1">Partie III</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-7.html#h-134820"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-7.html#h-134831"><span class="HTitleText2">Serments et affirmations solennelles</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-134836"><span class="HTitleText2">Preuve documentaire</span></a>
</li></ul>
</li><li><a href="page-8.html#h-134845"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Entités désignées</span></a>
</li></ul>
</li></ul>

</nav>

