<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la défense nationale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Ministère de la Défense nationale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Sous-ministre</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Juge-avocat général</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText2">Matériel</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Forces canadiennes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText2">Unités et autres éléments</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText2">Chef d’état-major de la défense</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText2">Pouvoirs de commandement</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText2">Enrôlement</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText2">Affectation et détachement</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Avancement</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-18"><span class="HTitleText2">Griefs</span></a>
</li>
<li><span class='sectionRange'>29.16 - </span><a href="#h-19"><span class="HTitleText2">Comité externe d’examen des griefs militaires</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-20"><span class="HTitleText2">Libération</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-21"><span class="HTitleText2">Service actif</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-22"><span class="HTitleText2">Service</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-23"><span class="HTitleText2">Restriction applicable au déploiement</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-24"><span class="HTitleText2">Solde et indemnités</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-25"><span class="HTitleText2">Fourniture et distribution de matériel</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-26"><span class="HTitleText2">Biens publics</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-27"><span class="HTitleText2">Biens non publics</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-28"><span class="HTitleText2">Successions militaires</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-29"><span class="HTitleText2">Présomption de décès</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-30"><span class="HTitleText2">Effets personnels des absents</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-31"><span class="HTitleText2">Commissions d’enquête</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-32"><span class="HTitleText2">Organisations de cadets</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-33"><span class="HTitleText2">Établissements d’enseignement</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-34"><span class="HTitleText2">Associations militaires</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-35"><span class="HTitleText2">Exercice de l’autorité</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-36"><span class="HTitleText2">Notification des ordres</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-37"><span class="HTitleText2">Validité des documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 à 59 - </span><a href="#h-38"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Code de discipline militaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 à 59 - </span><a href="#h-39"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Compétence des forces canadiennes en matière disciplinaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 à 59 - </span><a href="#h-40"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-41"><span class="HTitleText3">Fin de non-recevoir</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-42"><span class="HTitleText3">Lieu de la perpétration de l’infraction</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-43"><span class="HTitleText3">Lieu du procès</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-44"><span class="HTitleText3">Période d’assujettissement</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-45"><span class="HTitleText3">Restrictions relatives à certaines infractions</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-46"><span class="HTitleText3">Compétence des tribunaux civils</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="#h-47"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Infractions d’ordre militaire et peines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-48"><span class="HTitleText3">Responsabilité des infractions</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-49"><span class="HTitleText3">Manquement au devoir face à l’ennemi — Commandants</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-50"><span class="HTitleText3">Manquement au devoir en général face à l’ennemi</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-51"><span class="HTitleText3">Sécurité</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-52"><span class="HTitleText3">Prisonniers de guerre</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-53"><span class="HTitleText3">Diverses infractions relatives aux opérations</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-54"><span class="HTitleText3">Espions au service de l’ennemi</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-55"><span class="HTitleText3">Mutinerie</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-56"><span class="HTitleText3">Infractions séditieuses</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-57"><span class="HTitleText3">Insubordination</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-58"><span class="HTitleText3">Désertion</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-59"><span class="HTitleText3">Absence sans permission</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-60"><span class="HTitleText3">Conduite déshonorante</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-61"><span class="HTitleText3">Infractions relatives aux arrêts et à la détention militaires</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-62"><span class="HTitleText3">Infractions relatives aux navires</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-63"><span class="HTitleText3">Infractions relatives aux aéronefs</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-64"><span class="HTitleText3">Infractions relatives aux véhicules</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-65"><span class="HTitleText3">Infractions relatives aux biens</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-66"><span class="HTitleText3">Infractions relatives aux tribunaux</span></a>
</li>
<li><span class='sectionRange'>119.1 - </span><a href="#h-67"><span class="HTitleText3">Infraction relative à la <cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite></span></a>
</li>
<li><span class='sectionRange'>119.2 - </span><a href="#h-68"><span class="HTitleText3">Infraction relative à l’identification par les empreintes génétiques</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-69"><span class="HTitleText3">Infractions relatives aux cantonnements</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-70"><span class="HTitleText3">Infractions relatives à l’enrôlement</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-71"><span class="HTitleText3">Infractions diverses</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-72"><span class="HTitleText3">Conduite préjudiciable au bon ordre et à la discipline</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-73"><span class="HTitleText3">Infractions de droit commun</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-74"><span class="HTitleText3">Condamnation pour infractions de même nature</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-75"><span class="HTitleText3">Peines</span></a>
</li>
<li><span class='sectionRange'>147.1 - </span><a href="#h-76"><span class="HTitleText3">Ordonnance d’interdiction</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-77"><span class="HTitleText3">Jugements</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-78"><span class="HTitleText3">Incarcération en vertu de plusieurs sentences</span></a>
</li>
<li><span class='sectionRange'>149.2 - </span><a href="#h-79"><span class="HTitleText3">Relèvement de peine</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-80"><span class="HTitleText3">Ignorance de la loi</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-81"><span class="HTitleText3">Moyens de défense civils</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-82"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Arrestation et détention avant procès</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-83"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-84"><span class="HTitleText3">Pouvoir d’arrestation</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-85"><span class="HTitleText3">Mesures suivant l’arrestation</span></a>
</li>
<li><span class='sectionRange'>158.2 - </span><a href="#h-86"><span class="HTitleText3">Révision de la détention</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-87"><span class="HTitleText3">Révision par le juge militaire</span></a>
</li>
<li><span class='sectionRange'>159.8 - </span><a href="#h-88"><span class="HTitleText3">Obligation du directeur des poursuites militaires</span></a>
</li>
<li><span class='sectionRange'>159.9 - </span><a href="#h-89"><span class="HTitleText3">Révision par la Cour d’appel de la cour martiale</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="#h-90"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Début des poursuites</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>160 - </span><a href="#h-91"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-92"><span class="HTitleText3">Accusations</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-93"><span class="HTitleText3">Obligation d’agir avec célérité</span></a>
</li>
<li><span class='sectionRange'>162.1 - </span><a href="#h-94"><span class="HTitleText3">Droit à un procès devant une cour martiale</span></a>
</li></ul>
</li><li><span class='sectionRange'>162.3 - </span><a href="#h-95"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Procès sommaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>162.3 - </span><a href="#h-96"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-97"><span class="HTitleText3">Procès sommaire devant commandant</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-98"><span class="HTitleText3">Procès sommaire devant des commandants supérieurs</span></a>
</li>
<li><span class='sectionRange'>164.2 - </span><a href="#h-99"><span class="HTitleText3">Saisine du directeur des poursuites militaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-100"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Procès devant une cour martiale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-101"><span class="HTitleText3">Mise en accusation nécessaire</span></a>
</li>
<li><span class='sectionRange'>165.1 - </span><a href="#h-102"><span class="HTitleText3">Directeur des poursuites militaires</span></a>
</li>
<li><span class='sectionRange'>165.18 - </span><a href="#h-103"><span class="HTitleText3">Administrateur de la cour martiale</span></a>
</li>
<li><span class='sectionRange'>165.21 - </span><a href="#h-104"><span class="HTitleText3">Juges militaires</span></a>
</li>
<li><span class='sectionRange'>165.22 - </span><a href="#h-105"><span class="HTitleText3">Juges militaires de la force de réserve</span></a>
</li>
<li><span class='sectionRange'>165.23 - </span><a href="#h-106"><span class="HTitleText3">Attributions et immunité des juges militaires</span></a>
</li>
<li><span class='sectionRange'>165.24 - </span><a href="#h-107"><span class="HTitleText3">Juge militaire en chef</span></a>
</li>
<li><span class='sectionRange'>165.31 - </span><a href="#h-108"><span class="HTitleText3">Comité d’enquête sur les juges militaires</span></a>
</li>
<li><span class='sectionRange'>165.33 - </span><a href="#h-109"><span class="HTitleText3">Comité d’examen de la rémunération des juges militaires</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-110"><span class="HTitleText3">Cour martiale générale</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-111"><span class="HTitleText3">Cour martiale permanente</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-112"><span class="HTitleText3">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-113"><span class="HTitleText3">Admission en cour martiale</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-114"><span class="HTitleText3">Règles de la preuve</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-115"><span class="HTitleText3">Témoins devant la cour martiale</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-116"><span class="HTitleText3">Témoignage par commission rogatoire</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-117"><span class="HTitleText3">Récusation</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-118"><span class="HTitleText3">Procédures préliminaires</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-119"><span class="HTitleText3">Modification des accusations</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-120"><span class="HTitleText3">Ajournements</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-121"><span class="HTitleText3">Examen</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-122"><span class="HTitleText3">Décisions de la cour martiale générale</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-123"><span class="HTitleText3">Infractions semblables</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-124"><span class="HTitleText3">Prononcé du jugement</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-125"><span class="HTitleText3">Décès ou incapacité en cours d’instance</span></a>
</li></ul>
</li><li><span class='sectionRange'>196.11 - </span><a href="#h-126"><span class="HLabel2">SECTION 6.1</span> - <span class="HTitleText2">Analyse génétique à des fins médicolégales</span></a>
</li>
<li><span class='sectionRange'>196.26 - </span><a href="#h-127"><span class="HLabel2">SECTION 6.2</span> - <span class="HTitleText2">Identification des accusés et des contrevenants</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-128"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Troubles mentaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-129"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-130"><span class="HTitleText3">Aptitude à subir son procès</span></a>
</li>
<li><span class='sectionRange'>202.13 - </span><a href="#h-131"><span class="HTitleText3">Troubles mentaux au moment de la perpétration</span></a>
</li>
<li><span class='sectionRange'>202.17 - </span><a href="#h-132"><span class="HTitleText3">Dispositions générales en matière d’ordonnances d’évaluation, de décisions et de rapports d’évaluation</span></a>
</li>
<li><span class='sectionRange'>202.24 - </span><a href="#h-133"><span class="HTitleText3">Déclarations protégées</span></a>
</li>
<li><span class='sectionRange'>202.25 - </span><a href="#h-134"><span class="HTitleText3">Application de certaines dispositions du Code criminel</span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-135"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Dispositions applicables à l’emprisonnement et à la détention</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="#h-136"><span class="HTitleText3">Calcul de la peine</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-137"><span class="HTitleText3">Prisons militaires et casernes disciplinaires</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-138"><span class="HTitleText3">Suspension de l’emprisonnement ou de la détention</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-139"><span class="HTitleText3">Envoi en prison ou détention</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-140"><span class="HTitleText3">Déplacement temporaire hors du lieu d’incarcération</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-141"><span class="HTitleText3">Règles applicables aux condamnés et aux prisonniers militaires</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-142"><span class="HTitleText3">Validité des documents</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-143"><span class="HTitleText3">Troubles mentaux pendant l’emprisonnement ou la détention</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-144"><span class="HTitleText3">Transfèrement des contrevenants</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-145"><span class="HLabel2">SECTION 8.1</span> - <span class="HTitleText2">Renseignements sur les délinquants sexuels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>227 - </span><a href="#h-146"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>227.01 - </span><a href="#h-147"><span class="HTitleText3">Ordonnance de se conformer à la <cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite></span></a>
</li>
<li><span class='sectionRange'>227.06 - </span><a href="#h-148"><span class="HTitleText3">Avis et obligation de se conformer à la <cite class="XRefExternalAct">Loi sur l’enregistrement de renseignements sur les délinquants sexuels</cite> — condamnations antérieures au 12 septembre 2008</span></a>
</li>
<li><span class='sectionRange'>227.15 - </span><a href="#h-149"><span class="HTitleText3">Suspension de délais, d’instances et d’obligations</span></a>
</li>
<li><span class='sectionRange'>227.18 - </span><a href="#h-150"><span class="HTitleText3">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>227.2 - </span><a href="#h-151"><span class="HTitleText3">Autorisations, désignations et règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>228 - </span><a href="#h-152"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Appels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="#h-153"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-154"><span class="HTitleText3">Droit d’appel</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-155"><span class="HTitleText3">Mode d’interjection</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-156"><span class="HTitleText3">Appels de décisions</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-157"><span class="HTitleText3">Cour d’appel de la cour martiale</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-158"><span class="HTitleText3">Décisions par la Cour d’appel de la cour martiale</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-159"><span class="HTitleText3">Règles de procédure en appel</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-160"><span class="HTitleText3">Appel à la Cour suprême du Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>248.1 - </span><a href="#h-161"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Mise en liberté pendant l’appel</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-162"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2">Révision du verdict et de la peine</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>249 - </span><a href="#h-163"><span class="HTitleText3">Autorités compétentes</span></a>
</li>
<li><span class='sectionRange'>249.11 - </span><a href="#h-164"><span class="HTitleText3">Annulation de verdicts</span></a>
</li>
<li><span class='sectionRange'>249.12 - </span><a href="#h-165"><span class="HTitleText3">Substitution de verdicts</span></a>
</li>
<li><span class='sectionRange'>249.13 - </span><a href="#h-166"><span class="HTitleText3">Substitution de peines</span></a>
</li>
<li><span class='sectionRange'>249.14 - </span><a href="#h-167"><span class="HTitleText3">Mitigation, commutation et remise de peines</span></a>
</li>
<li><span class='sectionRange'>249.15 - </span><a href="#h-168"><span class="HTitleText3">Conditions applicables à la nouvelle peine</span></a>
</li>
<li><span class='sectionRange'>249.16 - </span><a href="#h-169"><span class="HTitleText3">Nouveau procès</span></a>
</li></ul>
</li><li><span class='sectionRange'>249.17 - </span><a href="#h-170"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2">Dispositions diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>249.17 - </span><a href="#h-171"><span class="HTitleText3">Représentation de l’accusé</span></a>
</li>
<li><span class='sectionRange'>249.18 - </span><a href="#h-172"><span class="HTitleText3">Service d’avocats de la défense</span></a>
</li>
<li><span class='sectionRange'>249.22 - </span><a href="#h-173"><span class="HTitleText3">Témoins devant la cour martiale ou le commissaire</span></a>
</li>
<li><span class='sectionRange'>249.23 - </span><a href="#h-174"><span class="HTitleText3">Mandat d’arrestation pour défaut de comparaître</span></a>
</li>
<li><span class='sectionRange'>249.24 - </span><a href="#h-175"><span class="HTitleText3">Effet des nouvelles peines</span></a>
</li>
<li><span class='sectionRange'>249.25 - </span><a href="#h-176"><span class="HTitleText3">Restitution de biens</span></a>
</li>
<li><span class='sectionRange'>249.26 - </span><a href="#h-177"><span class="HTitleText3">Mention d’un grade</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>250 - </span><a href="#h-178"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Plaintes concernant la police militaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250 - </span><a href="#h-179"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>250.1 - </span><a href="#h-180"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Commission d’examen des plaintes concernant la police militaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.1 - </span><a href="#h-181"><span class="HTitleText3">Constitution et organisation de la Commission</span></a>
</li>
<li><span class='sectionRange'>250.11 - </span><a href="#h-182"><span class="HTitleText3">Président</span></a>
</li>
<li><span class='sectionRange'>250.12 - </span><a href="#h-183"><span class="HTitleText3">Siège</span></a>
</li>
<li><span class='sectionRange'>250.13 - </span><a href="#h-184"><span class="HTitleText3">Personnel</span></a>
</li>
<li><span class='sectionRange'>250.14 - </span><a href="#h-185"><span class="HTitleText3">Obligation d’agir avec célérité</span></a>
</li>
<li><span class='sectionRange'>250.15 - </span><a href="#h-186"><span class="HTitleText3">Règles</span></a>
</li>
<li><span class='sectionRange'>250.16 - </span><a href="#h-187"><span class="HTitleText3">Immunité</span></a>
</li>
<li><span class='sectionRange'>250.17 - </span><a href="#h-188"><span class="HTitleText3">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.18 - </span><a href="#h-189"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Plaintes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.18 - </span><a href="#h-190"><span class="HLabel3">SOUS-SECTION 1</span> - <span class="HTitleText3">Droit de déposer une plainte</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.18 - </span><a href="#h-191"><span class="HTitleText4">Plainte pour inconduite</span></a>
</li>
<li><span class='sectionRange'>250.19 - </span><a href="#h-192"><span class="HTitleText4">Plainte pour ingérence</span></a>
</li>
<li><span class='sectionRange'>250.2 - </span><a href="#h-193"><span class="HTitleText4">Prescription</span></a>
</li>
<li><span class='sectionRange'>250.21 - </span><a href="#h-194"><span class="HTitleText4">Réception des plaintes</span></a>
</li>
<li><span class='sectionRange'>250.24 - </span><a href="#h-195"><span class="HTitleText4">Retrait</span></a>
</li>
<li><span class='sectionRange'>250.25 - </span><a href="#h-196"><span class="HTitleText4">Dossiers</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.26 - </span><a href="#h-197"><span class="HTitleText3">Sous-section 2</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.26 - </span><a href="#h-198"><span class="HTitleText4">Plaintes pour inconduite</span></a>
</li>
<li><span class='sectionRange'>250.31 - </span><a href="#h-199"><span class="HTitleText4">Renvoi devant la Commission</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.34 - </span><a href="#h-200"><span class="HLabel3">SOUS-SECTION 3</span> - <span class="HTitleText3">Plaintes pour ingérence</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.38 - </span><a href="#h-201"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Enquête et audience publique de la Commission</span></a>
</li>
<li><span class='sectionRange'>250.49 - </span><a href="#h-202"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Révision et rapport final</span></a>
</li></ul>
</li><li><span class='sectionRange'>251 - </span><a href="#h-203"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Dispositions diverses d’application générale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>251 - </span><a href="#h-204"><span class="HTitleText2">Serments</span></a>
</li>
<li><span class='sectionRange'>251.2 - </span><a href="#h-205"><span class="HTitleText2">Frais et indemnités des témoins</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-206"><span class="HTitleText2">Mesures à prendre par les autorités civiles concernant les déserteurs et les absents sans permission</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-207"><span class="HTitleText2">Certificats des tribunaux civils</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-208"><span class="HTitleText2">Obligations liées à l’incarcération</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-209"><span class="HTitleText2">Manoeuvres</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-210"><span class="HTitleText2">Exemption des péages ou autres droits</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-211"><span class="HTitleText2">Convois</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-212"><span class="HTitleText2">Sauvetage</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="#h-213"><span class="HTitleText2">Limitation des responsabilités civiles</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-214"><span class="HTitleText2">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-215"><span class="HTitleText2">Personnes à charge</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-216"><span class="HTitleText2">Compétence des tribunaux civils</span></a>
</li>
<li><span class='sectionRange'>273.1 - </span><a href="#h-217"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>273.2 - </span><a href="#h-218"><span class="HTitleText2">Perquisitions</span></a>
</li>
<li><span class='sectionRange'>273.6 - </span><a href="#h-219"><span class="HTitleText2">Service public</span></a>
</li></ul>
</li><li><span class='sectionRange'>273.61 - </span><a href="#h-220"><span class="HLabel1">PARTIE V.1</span> - <span class="HTitleText1">Centre de la sécurité des télécommunications</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-221"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Aide au pouvoir civil</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-222"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Infractions du ressort des tribunaux civils et peines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>286 - </span><a href="#h-223"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-224"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><a href="#h-225"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
