<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 2 d’exécution du budget de 2017</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-38145"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-38148"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite> et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-38149"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-38230"><span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-38232"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-38255"><span class="HTitleText2">Règlement modifiant le <cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite> (modifications diverses, n<sup>o</sup> 3)</span></a>
</li></ul>
</li><li><span class='sectionRange'>106 - </span><a href="#h-38257"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la <cite class="XRefExternalAct">Loi sur la taxe d’accise</cite> et de textes connexes (mesures relatives à la TPS/TVH)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>106 - </span><a href="#h-38258"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-38316"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les remboursements aux organismes de services publics (TPS/TVH)</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-38318"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur les mandataires désignés (TPS/TVH)</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-38320"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur l’accise</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-38325"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-38329"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Mesures diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172 - </span><a href="#h-38330"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les accords de Bretton Woods et des accords connexes</cite></span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-38335"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accord concernant la Banque asiatique d’investissement dans les infrastructures</cite></span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-38338"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Accords de financement en matière de développement international</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-38351"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>180 - </span><a href="#h-38352"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-38355"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-38359"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>185 - </span><a href="#h-38360"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-38362"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-38364"><span class="HTitleText3">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="#h-38366"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la compensation et le règlement des paiements</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-38373"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le pipe-line du Nord</cite></span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-38375"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>195 - </span><a href="#h-38376"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-38396"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-38398"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-38402"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>217 - </span><a href="#h-38408"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi n<sup>o</sup> 1 sur le plan d’action économique de 2015</cite></span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-38411"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Commerce au Canada et harmonisation d’exigences en matière d’efficacité énergétique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>219 - </span><a href="#h-38412"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de mise en oeuvre de l’Accord de libre-échange canadien</cite></span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-38415"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-38417"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi sur l’efficacité énergétique</cite></span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-38420"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>223 - </span><a href="#h-38421"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-38423"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère des Travaux publics et des Services gouvernementaux</cite></span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-38426"><span class="HTitleText4"><cite class="XRefExternalRegulation">Règlement concernant l’ombudsman de l’approvisionnement</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-38428"><span class="HTitleText3">Abrogations</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-38433"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>230 - </span><a href="#h-38436"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>230 - </span><a href="#h-38437"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-38462"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-38464"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>255 - </span><a href="#h-38465"><span class="HTitleText4"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-38467"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Nunavut</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-38469"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Yukon</cite></span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="#h-38471"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les Territoires du Nord-Ouest</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="#h-38473"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="#h-38479"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque de développement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-38481"><span class="HLabel2">SECTION 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li></ul>
</li><li><a href="#h-38484"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

