<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Prevention of Terrorist Travel Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-396720"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-396723"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-396726"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-396729"><span class="HTitleText1">Appeals</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-396749"><span class="HTitleText1">Judicial Review</span></a>
</li></ul>
</li></ul>

</nav>

