<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des végétaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-384335"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-384338"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-384341"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-384360"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-384363"><span class="HTitleText1">Lutte antiparasitaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-384364"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-384380"><span class="HTitleText2">Importation et exportation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-384418"><span class="HTitleText2">Assistance internationale</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-384421"><span class="HTitleText1">Lieux infestés</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-384452"><span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-384453"><span class="HTitleText2">Installations</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-384483"><span class="HTitleText2">Inspecteurs</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-384514"><span class="HTitleText2">Sceaux</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-384522"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-384553"><span class="HTitleText2">Perquisitions</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-384565"><span class="HTitleText2">Mesures consécutives à la saisie</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-384607"><span class="HTitleText2">Confiscation automatique</span></a>
</li></ul>
</li><li><span class='sectionRange'>36.1 - </span><a href="#h-384622"><span class="HTitleText1">Interdictions relatives aux documents</span></a>
</li>
<li><span class='sectionRange'>36.3 - </span><a href="#h-384637"><span class="HTitleText1">Interdictions relatives au marquage et à l’identification</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-384653"><span class="HTitleText1">Prélèvements</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-384659"><span class="HTitleText1">Restriction de la responsabilité</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-384668"><span class="HTitleText1">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-384707"><span class="HTitleText1">Redevances et autres frais</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-384719"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>47.1 - </span><a href="#h-384759"><span class="HTitleText1">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>47.2 - </span><a href="#h-384771"><span class="HTitleText1">Autorisations</span></a>
</li>
<li><span class='sectionRange'>47.3 - </span><a href="#h-384781"><span class="HTitleText1">Disposition générale</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-384786"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-384834"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-384846"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-384849"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-384851"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

