<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Maanulth First Nations Final Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-348560"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-348563"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-348573"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-348586"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-348589"><span class="HTitleText1">Lands</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-348592"><span class="HTitleText1">Taxation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-348597"><span class="HTitleText1">Fisheries</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-348602"><span class="HTitleText1">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-348607"><span class="HTitleText1">Application of Laws of British Columbia</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-348610"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-348641"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-348642"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-348644"><span class="HTitleText2"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-348646"><span class="HTitleText2"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-348648"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-348650"><span class="HTitleText2"><cite class="XRefExternalAct">Specific Claims Tribunal Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-348652"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

