<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Garnishment, Attachment and Pension Diversion Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Garnishment and Attachment Proceedings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Garnishment of Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">DEPARTMENTS AND CERTAIN CROWN CORPORATIONS</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">CROWN CORPORATIONS NOT COVERED BY DIVISION I</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">CANADIAN FORCES</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">SENATE, HOUSE OF COMMONS AND LIBRARY OF PARLIAMENT</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-9"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">GENERAL</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-10"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Diversion of Pension Benefits to Satisfy Financial Support Orders</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText2">Application of Part</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-12"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-13"><span class="HTitleText2">Conditions for Diversion of Pension Benefits</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-14"><span class="HTitleText2">Amount of Diversion</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-15"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><a href="#h-247773"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
