<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Hong Kong Tax Agreement Act, 2013</a><ul class="TocIndent"><li><a href="#h-146357"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Agreement Between the Government of Canada and the Government of the Hong Kong Special Administrative Region of the People’s Republic of China for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income</span></a>
</li>
<li><a href="#h-146630"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>

