<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Energy Administration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-219343"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-219348"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-219363"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-219368"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Oil Export Charges</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-219484"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Transportation Fuel Compensation Recovery Charge</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-219517"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Domestic Oil</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-2.html#h-219518"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-219531"><span class="HTitleText2">Application of Part</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-219538"><span class="HTitleText2">Purpose of Part</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-219547"><span class="HTitleText2">Price Restraint</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-219596"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-219625"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="page-3.html#h-219634"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Domestic Gas</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="page-3.html#h-219635"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-219664"><span class="HTitleText2">Application of Part</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-219671"><span class="HTitleText2">Purpose of Part</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-219680"><span class="HTitleText2">Price Restraint</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-3.html#h-219735"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-4.html#h-219764"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-4.html#h-219774"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="page-4.html#h-219800"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Petroleum Compensation Charge</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-5.html#h-219896"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Canadian Ownership Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="page-5.html#h-219897"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Special Charge and Taxation</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-5.html#h-219918"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Canadian Ownership Account</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="page-5.html#h-219989"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Cost Compensation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="page-5.html#h-219994"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Petroleum Compensation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="page-5.html#h-219995"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-5.html#h-220002"><span class="HTitleText3">Payment of Compensation</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="page-6.html#h-220034"><span class="HTitleText3">Petroleum Compensation Accounting</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-6.html#h-220056"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Petroleum Supplies Transfer Compensation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="page-6.html#h-220057"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-6.html#h-220066"><span class="HTitleText3">Direction of Governor in Council to Board</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-6.html#h-220071"><span class="HTitleText3">Compensation</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-6.html#h-220092"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="page-6.html#h-220107"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

