<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Health Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-151436"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-151441"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-151484"><span class="HTitleText1">Canadian Health Care Policy</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-151489"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-151494"><span class="HTitleText1">Cash Contribution</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-151500"><span class="HTitleText1">Program Criteria</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-151558"><span class="HTitleText1">Conditions for Cash Contribution</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-151565"><span class="HTitleText1">Defaults</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-151602"><span class="HTitleText1">Extra-billing and User Charges</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-151633"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-151649"><span class="HTitleText1">Report to Parliament</span></a>
</li></ul>
</li></ul>

</nav>

