<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Office des droits de surface des Territoires du Nord-Ouest</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Préséance</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText1">Mise en place de l’Office des droits de surface des Territoires du Nord-Ouest</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText2">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText2">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText2">Statut et pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-11"><span class="HTitleText2">Langues</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText2">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-14"><span class="HTitleText1">Examen des demandes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText2">Saisine de l’Office</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-16"><span class="HTitleText2">Instruction des demandes d’ordonnance et des révisions</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-17"><span class="HTitleText2">Formations chargées d’instruire les demandes d’ordonnance et les révisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-18"><span class="HTitleText1">Ordonnances relatives aux terres désignées et aux terres tlichos</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-19"><span class="HTitleText2">Ordonnances d’accès</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-20"><span class="HTitleText3">Documents exigés</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-21"><span class="HTitleText3">Obligations incombant à l’Office : délivrance d’ordonnances d’accès</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-22"><span class="HTitleText3">Conditions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-23"><span class="HTitleText3">Indemnités</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-24"><span class="HTitleText3">Paiement préalable à l’exercice du droit d’accès</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-25"><span class="HTitleText3">Ordonnances d’accès provisoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-26"><span class="HTitleText2">Autres ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-27"><span class="HTitleText1">Ordonnances relatives aux terres non désignées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-28"><span class="HTitleText2">Ordonnances d’accès</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-29"><span class="HTitleText3">Documents exigés</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-30"><span class="HTitleText3">Obligations incombant à l’Office : délivrance d’ordonnances d’accès</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-31"><span class="HTitleText3">Conditions</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-32"><span class="HTitleText3">Indemnités</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-33"><span class="HTitleText3">Paiement préalable à l’exercice du droit d’accès</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-34"><span class="HTitleText3">Ordonnances d’accès provisoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-35"><span class="HTitleText2">Autres ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-36"><span class="HTitleText1">Généralités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-37"><span class="HTitleText2">Ordonnances et décisions de l’Office</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-38"><span class="HTitleText2">Révision des ordonnances d’accès</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-39"><span class="HTitleText2">Révocation des ordonnances d’accès</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-40"><span class="HTitleText2">Compétence de la Cour suprême des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-41"><span class="HTitleText2">Règles de l’Office</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-42"><span class="HTitleText2">Registre public</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-43"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>100 - </span><a href="#h-44"><span class="HTitleText1">Dispositions transitoires</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
