<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Farm Credit Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-232462"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-232467"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-232480"><span class="HTitleText1">Corporation Continued</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-232490"><span class="HTitleText1">Purpose, Capacity and Powers</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-232522"><span class="HTitleText1">Corporate Organization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-232523"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-232544"><span class="HTitleText2">Officers, Committees and Staff</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-232574"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-232618"><span class="HTitleText1">Repeals and Transitional</span></a>
</li></ul>
</li></ul>

</nav>

