<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian High Arctic Research Station Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-69887"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-69890"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-69903"><span class="HTitleText1">Designation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-69906"><span class="HTitleText1">CHARS Established</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-69912"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-69919"><span class="HTitleText1">Powers and Functions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-69963"><span class="HTitleText1">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-69980"><span class="HTitleText1">Chairperson</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-69985"><span class="HTitleText1">President of CHARS</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-70007"><span class="HTitleText1">Human Resources</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-70033"><span class="HTitleText1">Offices and Meetings</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-70043"><span class="HTitleText1">Bylaws</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-70049"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

