<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Saguenay-St. Lawrence Marine Park Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-429920"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-429923"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-429935"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-429938"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-429941"><span class="HTitleText1">Establishment of the Park</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-429951"><span class="HTitleText1">Change of Park Boundaries</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-429968"><span class="HTitleText1">Administration of Park</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-429988"><span class="HTitleText1">Superintendent, Park Wardens and Enforcement Officers</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-430019"><span class="HTitleText1">Harmonization Committee</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-430027"><span class="HTitleText1">Coordinating Committee</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-430035"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-430058"><span class="HTitleText1">Arrest, Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-430094"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-430311"><span class="HTitleText1">Ticketable Offences</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-430333"><span class="HTitleText1">Other Remedies</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-430339"><span class="HTitleText1">Consequential Amendment</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-430341"><span class="HTitleText1">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-430344"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-430348"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Saguenay-St. Lawrence Marine Park</span></a>
</li></ul>
</li></ul>

</nav>

