<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la santé des non-fumeurs</a><ul class="TocIndent"><li><span class='sectionRange'>15 - </span><a href="#h-356728"><span class="HTitleText1">Loi sur les produits dangereux</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-356730"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

