<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les restructurations et les transferts d’attributions dans l’administration publique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-398216"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-398221"><span class="HTitleText1">Remaniements et restructurations</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-398228"><span class="HTitleText1">Continuité des pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-398233"><span class="HTitleText1">Cessation de fonctions</span></a>
</li></ul>
</li></ul>

</nav>

