<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les produits agricoles au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-39852"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-39855"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-39887"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-39890"><span class="HTitleText1">Conseil d’arbitrage et commission de révision</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-39980"><span class="HTitleText1">Plainte au conseil d’arbitrage</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-39986"><span class="HTitleText1">Recours en révision</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-39996"><span class="HTitleText1">Exécution des décisions et ordonnances</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-40029"><span class="HTitleText1">Agrément des établissements et des laboratoires</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-40034"><span class="HTitleText1">Marques de commerce nationales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-40039"><span class="HTitleText1">Commerce des produits agricoles</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-40046"><span class="HTitleText1">Agents d’application</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-40063"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-40091"><span class="HTitleText1">Perquisition</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-40101"><span class="HTitleText1">Mesures consécutives à la saisie</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-40136"><span class="HTitleText1">Importations irrégulières</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-40144"><span class="HTitleText1">Preuve de solvabilité</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-40149"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-40175"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-40210"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-40224"><span class="HTitleText1">Abrogation</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
