<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
First Nations Jurisdiction over Education in British Columbia Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Purpose and Effect of the Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Effect of Individual Agreement</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText1">First Nations Education Authority</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-6"><span class="HTitleText1">Purpose and Powers of the Authority</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HTitleText1">Community Education Authority</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">Other Acts</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText1">Liability</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText1">Minister’s Duties and Powers</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText1">Orders and Regulations</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-14"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText2">Privacy Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Participating First Nations</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
