<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Olympic and Paralympic Marks Act</a><ul class="TocIndent"><li><span class='sectionRange'>13 - </span><a href="#h-1"><span class="HTitleText1">Amendment to this Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-2"><span class="HTitleText1">Related Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-3"><span class="HTitleText2">Trade-marks Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-4"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-5"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Marks</span></a>
</li>
<li><a href="#h-6"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-7"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Expressions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
