<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Fondation Asie-Pacifique du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-6433"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-6438"><span class="HTitleText1">Constitution de la fondation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-6443"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-6455"><span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-6481"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-6521"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-6575"><span class="HTitleText1">Président et personnel</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-6601"><span class="HTitleText1">Indemnités et frais</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-6614"><span class="HTitleText1">Comités</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-6626"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-6638"><span class="HTitleText1">Statut de la fondation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-6647"><span class="HTitleText1">Organisme de charité enregistré</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-6660"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-6683"><span class="HTitleText1">Liquidation</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-2.html#h-6699"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-2.html#h-6717"><span class="HTitleText1">Rapport</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-6732"><span class="HTitleText1">Examen</span></a>
</li></ul>
</li></ul>

</nav>

