<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Family Orders and Agreements Enforcement Assistance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-221517"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-221520"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Release of Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-221521"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-221539"><span class="HTitleText2">Federal-Provincial Agreements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-221554"><span class="HTitleText2">Applications to Court</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-221584"><span class="HTitleText2">Applications for the Release of Information</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-221641"><span class="HTitleText2">Processing of Applications</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-221660"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-2.html#h-221672"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Garnishment of Federal Moneys to Satisfy Orders</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-2.html#h-221673"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-221690"><span class="HTitleText2">Garnishment of Her Majesty</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-221701"><span class="HTitleText2">Garnishee Summons</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-221714"><span class="HTitleText2">Garnishee Summons of Continuing Effect</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-221721"><span class="HTitleText2">Service of Documents</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-2.html#h-221730"><span class="HTitleText2">Administrative Procedures</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-2.html#h-221743"><span class="HTitleText2">Response to Garnishee Summons</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-2.html#h-221750"><span class="HTitleText2">Discharge of Liability</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-3.html#h-221756"><span class="HTitleText2">Notice to Judgment Debtor</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-221762"><span class="HTitleText2">Recovery of Excess Payments</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-221769"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-3.html#h-221781"><span class="HTitleText2">Garnishment, Attachment and Pension Diversion Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-3.html#h-221784"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-3.html#h-221789"><span class="HTitleText2">Fee</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-3.html#h-221796"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-3.html#h-221813"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Licence Denial</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-3.html#h-221814"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-3.html#h-221836"><span class="HTitleText2">Purpose of Part</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-3.html#h-221841"><span class="HTitleText2">Application of Part</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-3.html#h-221850"><span class="HTitleText2">Licence Denial Application</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-4.html#h-221881"><span class="HTitleText2">Obligations of Appropriate Ministers</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-4.html#h-221895"><span class="HTitleText2">No Appeal</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-4.html#h-221900"><span class="HTitleText2">Request to Terminate Application of Part</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-4.html#h-221928"><span class="HTitleText2">Offence</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-4.html#h-221938"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>78.1 - </span><a href="page-4.html#h-221943"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78.1 - </span><a href="page-4.html#h-1174696"><span class="HTitleText2">No Liability</span></a>
</li>
<li><span class='sectionRange'>78.2 - </span><a href="page-4.html#h-1174705"><span class="HTitleText2">Research</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-4.html#h-221944"><span class="HTitleText2">Release Authorization</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-4.html#h-221952"><span class="HTitleText2">Prohibition, Offence and Punishment</span></a>
</li></ul>
</li><li><a href="page-5.html#h-221966"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Licences</span></a>
</li></ul>
</li></ul>

</nav>

