<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
James Bay and Northern Quebec Native Claims Settlement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-334139"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-334142"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-334147"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-334161"><span class="HTitleText1">Supplementary and Other Agreements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-334194"><span class="HTitleText1">Consequential Amendment</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-334196"><span class="HTitleText1">Inconsistent Laws</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-334199"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-334202"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-334205"><span class="HTitleText1">Commencement</span></a>
</li></ul>
</li></ul>

</nav>

