<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Thunder Bay Grain Handling Operations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-448497"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-448500"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-448503"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-448511"><span class="HTitleText1">Grain Handling Operations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-448536"><span class="HTitleText1">Mediator-Arbitrator</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-448553"><span class="HTitleText1">Amendment of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-448556"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-448568"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-448572"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

