<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Multilateral Instrument in Respect of Tax Conventions Act</a><ul class="TocIndent"><li><a href="#h-1148503"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Multilateral Convention to Implement Tax Treaty Related Measures to Prevent Base Erosion and Profit Shifting</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
