<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Income Tax Conventions Implementation Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-329332"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-329335"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada — Slovenia Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-329351"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Canada — Ecuador Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-329367"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Canada — Venezuela Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-329383"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Canada — Peru Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-329399"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Canada — Senegal Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-1.html#h-329415"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Canada — Czech Republic Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-1.html#h-329431"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Canada — Slovak Republic Income Tax Agreement</span></a>
</li>
<li><span class='sectionRange'>44 and 45 - </span><a href="page-2.html#h-329447"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Canada — Germany Income Tax Agreement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 and 45 - </span><a href="page-2.html#h-329448"><span class="HTitleText2">Canada — Germany Tax Agreement Act, 1982</span></a>
</li></ul>
</li><li><a href="page-3.html#h-329456"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Republic of Slovenia for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-4.html#h-329724"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-5.html#h-330020"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-6.html#h-330307"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-7.html#h-330613"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Republic of Senegal for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income</span></a>
</li>
<li><a href="page-8.html#h-330891"><span class="scheduleLabel">SCHEDULE 6</span> <span class="scheduleTitleText"> - Convention Between Canada and the Czech Republic for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income</span></a>
</li>
<li><a href="page-9.html#h-331153"><span class="scheduleLabel">SCHEDULE 7</span> <span class="scheduleTitleText"> - Agreement Between the Government of Canada and the Government of the Slovak Republic for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-10.html#h-331429"><span class="scheduleLabel">SCHEDULE 8</span></a>
</li></ul>
</li></ul>

</nav>

