<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Safe Drinking Water for First Nations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-429254"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-429257"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-429277"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-429341"><span class="HTitleText1">Other Acts</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-429351"><span class="HTitleText1">Limits on Liability, Defences and Immunities</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-429369"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

