<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère de l’Agriculture et de l’Agroalimentaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-9737"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-9742"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-9754"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li></ul>
</li></ul>

</nav>

