<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi sur la réadaptation professionnelle des personnes handicapées <span class='Repealed'>[Abrogée,  2005, ch. 35, art. 69]</span></a></li></ul>
</nav>
</div></section>
