<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les mesures de transparence dans le secteur extractif</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et dispositions générales</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText1">Obligations des entités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText2">Rapport sur les paiements</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2">Conservation de documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Renseignements et vérification indépendante</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-13"><span class="HTitleText2">Pouvoirs de la personne désignée</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText2">Arrêté — mesures correctives</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-16"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-17"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-18"><span class="HTitleText1">Dispositions transitoires</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
