<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Investment Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Definitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Organization and Mandate</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Director of Investments</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Notification</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Rules and Presumptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText2">Canadian Status Rules</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-12"><span class="HTitleText2">Acquisition of Control Rules</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText2">Timing Rules</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-14"><span class="HTitleText2">Sending Notices, Receipts or Demands</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-15"><span class="HTitleText2">Operation of Other Acts</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-17"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-18"><span class="HTitleText2">Privileged Information</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-19"><span class="HTitleText2">Written Opinions</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-20"><span class="HTitleText2">Guidelines and Interpretation Notes</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-21"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Remedies, Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-22"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">[Repealed, 1995, c. 1, s. 49]</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-23"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Transitional, Consequential Amendments and Commencement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-24"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-25"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-26"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-27"><span class="HTitleText2">Canadian Ownership and Control Determination Act</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-28"><span class="HTitleText2">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-29"><span class="HTitleText2">Northern Pipeline Act</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-30"><span class="HTitleText2">Commencement</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
