<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Commission canadienne du blé (activités en période intérimaire)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Commission canadienne du blé</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Prorogation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Statut, mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">Président directeur général</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">Administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText2">Fonds de réserve</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Fixation des prix, bénéfices et pertes</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Placements</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Comptabilité et rapports</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Caisse de retraite et assurance collective</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Instructions du gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Plans, emprunts et garantie</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Organisation du marché interprovincial et de l’exportation du grain</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-18"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText2">Achat de grains et acompte à la livraison</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-20"><span class="HTitleText2">Distribution du solde créditeur et versements intérimaires</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-21"><span class="HTitleText2">Distinctions à l’intérieur d’un même grade</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-22"><span class="HTitleText2">Comptabilité distincte</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-23"><span class="HTitleText2">Règlements et autorisations concernant les certificats et les comptes</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-24"><span class="HTitleText2">Autres méthodes d’achat de grains</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-25"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-26"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-27"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-28"><span class="HTitleText2">Mise en oeuvre de l’Accord de libre-échange nord-américain</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-29"><span class="HTitleText2">Emprunts des mandataires</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-30"><span class="HTitleText2">Déclaration</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-31"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
