<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le cannabis</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-75029"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-75032"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-75096"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-75101"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-75104"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-75114"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Interdictions, obligations et infractions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-75115"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Activités criminelles</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-75275"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Autres interdictions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-75276"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Promotion</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-75355"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Emballage et étiquetage</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-75374"><span class="HLabel3">SOUS-SECTION C</span> - <span class="HTitleText3">Exposition</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-75379"><span class="HLabel3">SOUS-SECTION D</span> - <span class="HTitleText3">Vente et distribution</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-75400"><span class="HLabel3">SOUS-SECTION E</span> - <span class="HTitleText3">Autres interdictions</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-75410"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-75426"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-75446"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Contraventions</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-75546"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Licences et permis</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-75640"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Autorisations générales</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-75671"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Arrêtés du ministre</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-75733"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Système de suivi du cannabis</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-75763"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Inspections</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-75827"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Mandat de perquisition</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-75855"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Disposition des choses saisies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-75856"><span class="HTitleText2">Rapport au ministre</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-75869"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-75881"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Biens infractionnels non chimiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-75882"><span class="HTitleText3">Ordonnances de blocage</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-75914"><span class="HTitleText3">Ordonnances de prise en charge</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-75948"><span class="HTitleText3">Confiscation</span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="#h-76039"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Cannabis et biens chimiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-76088"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-76089"><span class="HTitleText2">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-76092"><span class="HTitleText2">Violation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-76098"><span class="HTitleText2">Ouverture de la procédure</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-76115"><span class="HTitleText2">Sanctions</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-76125"><span class="HTitleText2">Transactions</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-76148"><span class="HTitleText2">Contestation devant le ministre</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-76164"><span class="HTitleText2">Exécution des sanctions</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-76181"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-76195"><span class="HTitleText2">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>128 - </span><a href="#h-76204"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="#h-76205"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-76216"><span class="HTitleText2">Analyse</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-76224"><span class="HTitleText2">Marques de commerce</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-76230"><span class="HTitleText2">Preuve et procédure</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-76262"><span class="HTitleText2">Règlements et exemptions</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-76345"><span class="HTitleText2">Prix</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-76376"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-76389"><span class="HTitleText2">Assistance technique</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-76392"><span class="HTitleText2">Modification des annexes</span></a>
</li>
<li><span class='sectionRange'>151.1 - </span><a href="#h-76402"><span class="HTitleText2">Examen et rapport</span></a>
</li></ul>
</li><li><span class='sectionRange'>152 - </span><a href="#h-76408"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">Dispositions transitoires, modifications connexes et corrélatives et dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>152 - </span><a href="#h-76409"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-76534"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>162 - </span><a href="#h-76535"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-76540"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-76541"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le casier judiciaire</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-76543"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’identification des criminels</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-76546"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-76548"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-76551"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’entraide juridique en matière criminelle</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-76553"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le système correctionnel et la mise en liberté sous condition</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-76555"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’administration des biens saisis</cite></span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-76565"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les armes à feu</cite></span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-76567"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-76569"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le système de justice pénale pour les adolescents</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-76571"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les garanties internationales portant sur des matériels d’équipement mobiles (matériels d’équipement aéronautiques)</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-76573"><span class="HTitleText3"><cite class="XRefExternalAct">Loi canadienne sur la sécurité des produits de consommation</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-76575"><span class="HTitleText3"><cite class="XRefExternalAct">Charte canadienne des droits des victimes</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>188 - </span><a href="#h-76577"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>193.1 - </span><a href="#h-76584"><span class="HLabel1">PARTIE 12.1</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi sur le cannabis</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-76586"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Loi réglementant certaines drogues et autres substances</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="#h-76587"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-76601"><span class="HTitleText2">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>207 - </span><a href="#h-76603"><span class="HLabel1">PARTIE 14</span> - <span class="HTitleText1"><cite class="XRefExternalAct">Code criminel</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>207 - </span><a href="#h-76604"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-76623"><span class="HTitleText2">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>226 - </span><a href="#h-76625"><span class="HLabel1">PARTIE 15</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-79"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-80"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-81"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-82"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-83"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="#h-84"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
