<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Corrections and Conditional Release Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Institutional and Community Corrections</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Correctional Service of Canada</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-6"><span class="HTitleText2">Reception of Inmates</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-7"><span class="HTitleText2">Correctional Plans</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText2">Exchange of Service Agreements</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText2">Escorted Temporary Absences</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText2">Work Releases</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Investigations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Compensation for Death or Disability</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText2">Information</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-14"><span class="HTitleText2">Placement and Transfer of Inmates</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Security Classification</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-16"><span class="HTitleText2">Administrative Segregation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-17"><span class="HTitleText2">Discipline</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">Summary Conviction Offences</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-19"><span class="HTitleText2">Search and Seizure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-20"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-21"><span class="HTitleText3">Searches of Inmates</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-22"><span class="HTitleText3">Searches of Cells</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-23"><span class="HTitleText3">Searches of Visitors</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-24"><span class="HTitleText3">Searches of Vehicles</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-25"><span class="HTitleText3">Warnings to be Posted</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-26"><span class="HTitleText3">Searches of Staff Members</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-27"><span class="HTitleText3">Power to Seize</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-28"><span class="HTitleText3">Searches in Community-based Residential Facilities</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-29"><span class="HTitleText3">Reports Relating to Searches and Seizures</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-30"><span class="HTitleText2">General — Living Conditions</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-31"><span class="HTitleText2">Programs for Offenders</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-32"><span class="HTitleText2">Aboriginal Offenders</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-33"><span class="HTitleText2">Health Care</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-34"><span class="HTitleText2">Grievance or Complaint Procedure</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-35"><span class="HTitleText2">Release of Inmates</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-36"><span class="HTitleText2">Temporary Accommodation in Penitentiary</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-37"><span class="HTitleText2">Annual Report</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-38"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-39"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-40"><span class="HTitleText2">Commissioner’s Directives</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-41"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Conditional Release, Detention and Long-term Supervision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-42"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-43"><span class="HTitleText2">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-44"><span class="HTitleText2">Constitution and Jurisdiction of Board</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-45"><span class="HTitleText2">Constitution and Jurisdiction of Provincial Boards</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-46"><span class="HTitleText2">Unescorted Temporary Absence</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-47"><span class="HTitleText2">Eligibility for Parole</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-48"><span class="HTitleText2">Parole Reviews</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-49"><span class="HTitleText2">Statutory Release</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-50"><span class="HTitleText2">Effect of Parole, Statutory Release or Unescorted Temporary Absence</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-51"><span class="HTitleText2">Detention during Period of Statutory Release</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-52"><span class="HTitleText2">Conditions of Release</span></a>
</li>
<li><span class='sectionRange'>134.1 - </span><a href="#h-53"><span class="HTitleText2">Conditions for Long-Term Supervision</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-54"><span class="HTitleText2">Suspension, Termination, Revocation and Inoperativeness of Parole, Statutory Release or Long-Term Supervision</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-55"><span class="HTitleText2">Merged Sentences</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-56"><span class="HTitleText2">Review Hearings</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-57"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-58"><span class="HTitleText2">Records of Reviews and Decisions</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-59"><span class="HTitleText2">Review and Evidence</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-60"><span class="HTitleText2">Organization of the Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>146 - </span><a href="#h-61"><span class="HTitleText3">Appeal Division</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-62"><span class="HTitleText3">Appeal to Appeal Division</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-63"><span class="HTitleText3">Head Office and Regions</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-64"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>156 - </span><a href="#h-65"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="#h-66"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Correctional Investigator</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-67"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-68"><span class="HTitleText2">Correctional Investigator</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-69"><span class="HTitleText2">Management</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-70"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-71"><span class="HTitleText2">Oath of Office</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-72"><span class="HTitleText2">Function</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-73"><span class="HTitleText2">Information Program</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-74"><span class="HTitleText2">Investigations</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-75"><span class="HTitleText2">Findings, Reports and Recommendations</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-76"><span class="HTitleText2">Confidentiality</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-77"><span class="HTitleText2">Delegation</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-78"><span class="HTitleText2">Relationship With Other Acts</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-79"><span class="HTitleText2">Legal Proceedings</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-80"><span class="HTitleText2">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-81"><span class="HTitleText2">Annual and Special Reports</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-82"><span class="HTitleText2">Confidences of the Queen’s Privy Council</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-83"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-84"><span class="HTitleText2">Her Majesty</span></a>
</li></ul>
</li><li><span class='sectionRange'>199 to 203 - </span><a href="#h-85"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Consequential and Related Amendments, Repeal and Transitional Provisions and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 to 203 - </span><a href="#h-86"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>205 to 207 - </span><a href="#h-87"><span class="HTitleText2">Prisons and Reformatories Act</span></a>
</li>
<li><span class='sectionRange'>208 to 211 - </span><a href="#h-88"><span class="HTitleText2">Transfer of Offenders Act</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-89"><span class="HTitleText2">Department of the Solicitor General Act</span></a>
</li>
<li><span class='sectionRange'>213 and 214 - </span><a href="#h-90"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>215 and 216 - </span><a href="#h-91"><span class="HTitleText2">References</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-92"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-93"><span class="HTitleText2">Review of Detention Provisions</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-94"><span class="HTitleText2">Review of Whole Act</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-95"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-96"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-97"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
