<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Station canadienne de recherche dans l’Extrême-Arctique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-68261"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-68264"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-68277"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-68280"><span class="HTitleText1">Constitution</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-68286"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-68293"><span class="HTitleText1">Pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-68337"><span class="HTitleText1">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-68354"><span class="HTitleText1">Président du Conseil</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-68359"><span class="HTitleText1">Président de la SCREA</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-68379"><span class="HTitleText1">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-68405"><span class="HTitleText1">Bureaux et réunions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-68415"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-68421"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

