<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’augmentation du rendement des rentes sur l’État</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-241861"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-241864"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-241870"><span class="HTitleText1">Augmentation du rendement</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-241888"><span class="HTitleText1">Aménagements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-241897"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-241904"><span class="HTitleText1">Cessation du régime des rentes sur l’État</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-241909"><span class="HTitleText1">Compte des rentes sur l’État</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-241917"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-241920"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-241927"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><a href="page-2.html#h-241934"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>

