<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Société canadienne d’hypothèques et de logement</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-161007"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-161012"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-161026"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Constitution et fonctionnement de la société</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-161027"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-161100"><span class="HTitleText2">Fonctionnement de la Société</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-161144"><span class="HTitleText2">Capital</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-161149"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Mission et pouvoirs de la société</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-161150"><span class="HTitleText2">Activités</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-161219"><span class="HTitleText2">Pouvoirs connexes</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="#h-161255"><span class="HTitleText2">Collaboration et ententes</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-161263"><span class="HTitleText2">Réserve</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-161273"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Vérification et dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-161274"><span class="HTitleText2">Vérification</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-161285"><span class="HTitleText2">Exercice de la Société</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-161290"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><a href="#h-161311"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
