<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les forces hydrauliques du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-456391"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-456396"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-456414"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-456425"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-456516"><span class="HTitleText1">Décrets et règlements</span></a>
</li></ul>
</li></ul>

</nav>

