<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tobacco and Vaping Products Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Governor in Council’s Powers</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Tobacco Products</span></a>
</li>
<li><span class='sectionRange'>7.2 - </span><a href="#h-7"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Vaping Products</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Access</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Labelling</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Promotion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-11"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Tobacco Products</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-12"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Vaping Products</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Miscellaneous Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-14"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-15"><span class="HTitleText2">Inspection and Analysis</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-16"><span class="HTitleText2">Seizure and Restoration</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-17"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>42.1 - </span><a href="#h-18"><span class="HLabel1">PART V.1</span> - <span class="HTitleText1">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-20"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>60.1 - </span><a href="#h-21"><span class="HLabel1">PART VII.1</span> - <span class="HTitleText1">Review of the Act</span></a>
</li>
<li><span class='sectionRange'>61 to 63 - </span><a href="#h-22"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Consequential Amendments, Repeals and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 to 63 - </span><a href="#h-23"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>64 and 65 - </span><a href="#h-24"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-25"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-26"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
