<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi sur le compte de service et de réduction de la dette <span class='Repealed'>[Abrogée, 2003, ch. 15, art. 43]</span></a></li></ul>
</nav>
</div></section>
