<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Dominion Water Power Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-467464"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-467469"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-467487"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-467498"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-467589"><span class="HTitleText1">Orders and Regulations</span></a>
</li></ul>
</li></ul>

</nav>

