<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le blocage des biens de dirigeants étrangers corrompus</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-231536"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-231539"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-231566"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-231569"><span class="HTitleText1">Décrets et règlements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-231596"><span class="HTitleText1">Obligation de vérification</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-231610"><span class="HTitleText1">Communication</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-231618"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-231639"><span class="HTitleText1">Droits des personnes visées par tout décret ou règlement</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-231647"><span class="HTitleText1">Demande d’attestation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-231658"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-231667"><span class="HTitleText1">Examen et rapport</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
