<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le Parlement du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-380546"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-380549"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Sénat et Chambre des communes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-380550"><span class="HTitleText2">Continuité du Parlement</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-380559"><span class="HTitleText2">Privilèges, immunités et pouvoirs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-380560"><span class="HTitleText3">Nature</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-380575"><span class="HTitleText3">Publication de documents</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-380598"><span class="HTitleText3">Interrogatoire des témoins</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-380629"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Sénat</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-380630"><span class="HTitleText2">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-380644"><span class="HTitleText2">Suppléance du président</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="page-1.html#h-380657"><span class="HTitleText2">Régie interne</span></a>
</li>
<li><span class='sectionRange'>19.5 - </span><a href="page-1.html#h-380692"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>19.6 - </span><a href="page-2.html#h-380711"><span class="HTitleText2">Avis</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-380752"><span class="HTitleText2">Administration financière</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="page-2.html#h-380762"><span class="HTitleText2">Conseiller sénatorial en éthique</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="page-2.html#h-380833"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Chambre des communes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-2.html#h-380834"><span class="HLabel2">SECTION A</span> - <span class="HTitleText2">Éligibilité, démission et vacance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-2.html#h-380835"><span class="HTitleText3">Candidatures multiples</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-380840"><span class="HTitleText3">Membres d’une législature provinciale</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-380862"><span class="HTitleText3">Démission d’un député</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-380886"><span class="HTitleText3">Vacance</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-3.html#h-380920"><span class="HLabel2">SECTION B</span> - <span class="HTitleText2">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-381022"><span class="HLabel2">SECTION C</span> - <span class="HTitleText2">Président, secrétaires parlementaires, greffier et autres membres du personnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-4.html#h-381023"><span class="HTitleText3">Suppléance du président</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-381043"><span class="HTitleText3">Secrétaires parlementaires</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-381057"><span class="HTitleText3">Greffier et autres membres du personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>49.1 - </span><a href="page-4.html#h-381066"><span class="HLabel2">SECTION C.1</span> - <span class="HTitleText2">Groupes parlementaires</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-381134"><span class="HLabel2">SECTION D</span> - <span class="HTitleText2">Bureau de régie interne</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="page-4.html#h-381135"><span class="HTitleText3">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>52.2 - </span><a href="page-5.html#h-381177"><span class="HTitleText3">Mission</span></a>
</li>
<li><span class='sectionRange'>52.5 - </span><a href="page-5.html#h-381200"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>52.6 - </span><a href="page-5.html#h-381219"><span class="HTitleText3">Avis</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>54.1 - </span><a href="page-5.html#h-381269"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Rémunération des parlementaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54.1 - </span><a href="page-5.html#h-381270"><span class="HTitleText2">Montant de base de la rémunération</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-5.html#h-381278"><span class="HTitleText2">Indemnités de session : avant le 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="page-6.html#h-381325"><span class="HTitleText2">Indemnités de session : à compter du 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-6.html#h-381341"><span class="HTitleText2">Dispositions générales relatives aux indemnités de session</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-6.html#h-381372"><span class="HTitleText2">Traitements et autres indemnités de certains membres : avant le 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>62.1 - </span><a href="page-6.html#h-381405"><span class="HTitleText2">Traitements et autres indemnités de certains membres : à compter du 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-7.html#h-381463"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-7.html#h-381490"><span class="HTitleText2">Rajustement des traitements et indemnités</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-7.html#h-381500"><span class="HTitleText2">Indemnités en cas de dissolution de la Chambre des communes</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-7.html#h-381505"><span class="HTitleText2">Indemnité de départ</span></a>
</li>
<li><span class='sectionRange'>71.1 - </span><a href="page-7.html#h-381547"><span class="HTitleText2">Allocation d’invalidité</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="page-7.html#h-381568"><span class="HTitleText2">Régimes collectifs d’assurance</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-7.html#h-381578"><span class="HTitleText2">Dispositions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>72.01 - </span><a href="page-8.html#h-381588"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="page-8.html#h-381604"><span class="HTitleText2">Bibliothèque du Parlement</span></a>
</li>
<li><span class='sectionRange'>79.01 - </span><a href="page-8.html#h-381661"><span class="HTitleText2">Directeur parlementaire du budget</span></a>
</li>
<li><span class='sectionRange'>79.51 - </span><a href="page-9.html#h-381828"><span class="HTitleText2">Service de protection parlementaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79.51 - </span><a href="page-9.html#h-381829"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>79.52 - </span><a href="page-9.html#h-381842"><span class="HTitleText3">Constitution et mission</span></a>
</li>
<li><span class='sectionRange'>79.54 - </span><a href="page-9.html#h-381859"><span class="HTitleText3">Directeur du Service</span></a>
</li>
<li><span class='sectionRange'>79.55 - </span><a href="page-9.html#h-381869"><span class="HTitleText3">Arrangement pour la prestation de services de sécurité physique</span></a>
</li>
<li><span class='sectionRange'>79.57 - </span><a href="page-10.html#h-381884"><span class="HTitleText3">État estimatif</span></a>
</li>
<li><span class='sectionRange'>79.58 - </span><a href="page-10.html#h-381889"><span class="HTitleText3">Pouvoirs, droits, privilèges et immunités</span></a>
</li>
<li><span class='sectionRange'>79.59 - </span><a href="page-10.html#h-381894"><span class="HTitleText3">Disposition générale</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="page-10.html#h-381899"><span class="HTitleText2">Infraction et peine</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="page-10.html#h-381912"><span class="HTitleText2">Commissaire aux conflits d’intérêts et à l’éthique</span></a>
</li></ul>
</li><li><a href="page-11.html#h-382015"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

