<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada-Israel Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-147264"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-147267"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-147279"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-147282"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-147285"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-147296"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Implementation of Agreement Generally</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-147297"><span class="HTitleText2">Approval of Agreement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-147300"><span class="HTitleText2">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-147303"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-147316"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 to 61 - </span><a href="#h-147321"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-147323"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-147330"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
