<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Sickle Cell Awareness Day Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-363908"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-363911"><span class="HTitleText1">National Sickle Cell Awareness Day</span></a>
</li></ul>
</li></ul>

</nav>

