<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la commercialisation des services de contrôle de sûreté</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1154987"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1154990"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-1155009"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-1155012"><span class="HTitleText1">Administration de contrôle désignée</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-1155040"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-1155054"><span class="HTitleText1">Services de contrôle de sûreté</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-1155093"><span class="HTitleText1">Redevances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="page-1.html#h-1155094"><span class="HTitleText2">Imposition et établissement</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-1155195"><span class="HTitleText2">Avis d’opposition</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-1155222"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-1155231"><span class="HTitleText2">Perception et versement</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-3.html#h-1155243"><span class="HTitleText1">Saisie et détention d’aéronefs</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-3.html#h-1155256"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-3.html#h-1155276"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-3.html#h-1155284"><span class="HTitleText1">Examen quinquennal</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-1155290"><span class="HTitleText1">Dispositions transitoires</span></a>
</li></ul>
</li></ul>

</nav>

