<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget and Economic Statement Implementation Act, 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments in Respect of the Goods and Services Tax/Harmonized Sales Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendment Relating to Excise Tax on Renewable Fuels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-8"><span class="HTitleText2">Income Tax Application Rules</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-9"><span class="HTitleText2">Income Tax Conventions Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-10"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-11"><span class="HTitleText2">Canada Pension Plan Regulations</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-12"><span class="HTitleText2">Insurable Earnings and Collection of Premiums Regulations</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-13"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-14"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Disability Savings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-15"><span class="HTitleText2">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-16"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-17"><span class="HTitleText3">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-18"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="#h-19"><span class="HTitleText4">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-20"><span class="HTitleText4">Old Age Security Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-21"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-22"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-23"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Disability Savings Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-24"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-25"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Children’s Special Allowances Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-26"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>139 - </span><a href="#h-27"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Incentive for Provinces to Eliminate Taxes on Capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>139 - </span><a href="#h-28"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-29"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Bank for International Settlements (Immunity) Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-30"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Phased Retirement — Amendments Other than Those Concerning Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-31"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-32"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-33"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Advance Market Commitment</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-34"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Oil and Gas Operations in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="#h-35"><span class="HTitleText2">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-36"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-37"><span class="HTitleText3">Canada Petroleum Resources Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-38"><span class="HTitleText3">National Energy Board Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>154 - </span><a href="#h-39"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Amendments to the Farm Income Protection Act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-40"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Federal-Provincial Fiscal Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="#h-41"><span class="HTitleText2">Amendments to the Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-42"><span class="HTitleText2">Amendments to the Budget Implementation Act, 2007</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-43"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Canada-Newfoundland Atlantic Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-44"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-45"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="#h-46"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Amendments to the Canada Education Savings Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-47"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Private-Public Partnerships</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-48"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Tax Amendments to Implement the 2007 Economic Statement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-49"><span class="HTitleText2">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-50"><span class="HTitleText3">Income Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="#h-51"><span class="HTitleText2">Amendments to Implement the GST/HST Rate Reduction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-52"><span class="HTitleText3">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="#h-53"><span class="HTitleText2">Related Amendments as a Result of the GST/HST Rate Reduction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="#h-54"><span class="HTitleText3">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-55"><span class="HTitleText3">Excise Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-56"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-57"><span class="HTitleText4">Application</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
