<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Injured Military Members Compensation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-333647"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-333650"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-333658"><span class="HTitleText1">Designation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-333664"><span class="HTitleText1">Compensation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-333733"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-333769"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><a href="page-2.html#h-333775"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

