<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi des dispositions supplémentaires du Manitoba</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-339955"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-339960"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-339971"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>5 à 18 - </span><a href="#h-339980"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">[Abrogée, 1992, ch. 1, art. 146 (ann. IX, no 35)]</span></a>
</li>
<li><span class='sectionRange'>19 à 34 - </span><a href="#h-339982"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">[Abrogée, 1992, ch. 1, art. 146, ann. IX, no 35)]</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
