<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la semaine nationale des dons d’organes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-351460"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-351463"><span class="HTitleText1">Semaine nationale des dons d’organes</span></a>
</li></ul>
</li></ul>

</nav>

