<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la mise en quarantaine</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-409370"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-409373"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-409392"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-409395"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-409398"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-409430"><span class="HTitleText1">Voyageurs</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-409573"><span class="HTitleText1">Véhicules</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-409650"><span class="HTitleText1">Cadavres, organes et restes humains</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-409662"><span class="HTitleText1">Pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-409699"><span class="HTitleText1">Renseignements</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-409727"><span class="HTitleText1">Urgences</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-409759"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-409801"><span class="HTitleText1">Loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-409804"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-409833"><span class="HTitleText1">Dispositions connexes</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-409880"><span class="HTitleText1">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="#h-409881"><span class="HTitleText2">Loi sur l’immigration et la protection des réfugiés</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-409883"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-409885"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-409887"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-409891"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
