<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Real Property and Federal Immovables Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-240351"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-240356"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-240384"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-240389"><span class="HTitleText1">Dispositions, Leases and Licences</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-240394"><span class="HTitleText1">Grants and Concessions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-240456"><span class="HTitleText1">Application of Other Laws</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-240465"><span class="HTitleText1">Minister of Justice</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-240478"><span class="HTitleText1">Authority for Dispositions, Acquisitions and Administrative Transfers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-240551"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>23 to 49 - </span><a href="#h-240580"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-240582"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-240584"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
