<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le cinéma</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-373532"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-373537"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-373548"><span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-373553"><span class="HTitleText1">Office national du film</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-373587"><span class="HTitleText1">Mission de l’office</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-373597"><span class="HTitleText1">Pouvoirs de l’office</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-373639"><span class="HTitleText1">Commissaire du gouvernement à la cinématographie</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-373658"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-373670"><span class="HTitleText1">Rapports</span></a>
</li>
<li><a href="page-2.html#h-373683"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Serment professionnel et engagement au secret professionnel</span></a>
</li></ul>
</li></ul>

</nav>

