<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-9551"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-9554"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-9567"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-9570"><span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-9602"><span class="HTitleText1">Ouverture de la poursuite</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9612"><span class="HTitleText1">Avertissements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9618"><span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-9629"><span class="HTitleText1">Transactions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9652"><span class="HTitleText1">Contestation devant le ministre</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9663"><span class="HTitleText1">Révision par la Commission</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9669"><span class="HTitleText1">Exécution des sanctions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9690"><span class="HTitleText1">Règles spécifiques aux violations</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-9709"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>27 à 89 - </span><a href="#h-9723"><span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-9725"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
