<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Sports Pool and Loto Canada Winding-Up Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-437239"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-437242"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-437250"><span class="HTitleText1">Canadian Sports Pool Corporation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-437260"><span class="HTitleText1">Loto Canada Inc.</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-437266"><span class="HTitleText1">Legal Proceedings</span></a>
</li></ul>
</li></ul>

</nav>

