<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Social Sciences and Humanities Research Council Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-433824"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-433829"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-433838"><span class="HTitleText1">Constitution of the Council</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-433843"><span class="HTitleText1">Functions and Powers</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-433855"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-433944"><span class="HTitleText1">Financial</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-433954"><span class="HTitleText1">Report to Parliament</span></a>
</li></ul>
</li></ul>

</nav>

