<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la continuation des paiements de Pioneer Trust</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-383532"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-383535"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-383545"><span class="HTitleText1">Affectation</span></a>
</li></ul>
</li></ul>

</nav>

