<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur Services partagés Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-435865"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-435868"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-435874"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-435877"><span class="HTitleText1">Constitution</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-435882"><span class="HTitleText1">Attributions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-435928"><span class="HTitleText1">Organisation et siège</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-435943"><span class="HTitleText1">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-435946"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-435951"><span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-1.html#h-435952"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-435957"><span class="HTitleText2">ancien ministère</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

