<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Excise Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-2"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText1">Interpretation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText2">Distilleries</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText2">Breweries</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText2">Bonded Manufacturers</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText2">Tobacco and Cigars and Manufacturers thereof</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-10"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-11"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-12"><span class="HTitleText2">Obligations of Licensees</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HTitleText2">Books, Accounts and Papers</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-14"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-15"><span class="HTitleText2">Duties, how Ascertained and when Payable</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-16"><span class="HTitleText2">Bonding and Warehousing</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-17"><span class="HTitleText2">Powers and Duties of Officers</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-18"><span class="HTitleText2">Protection of Officers</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-19"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>110.1 - </span><a href="#h-20"><span class="HTitleText2">Recovery of Duties and Penalties</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-21"><span class="HTitleText2">Appropriation of Penalties and Forfeitures</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-22"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="#h-23"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Distilleries</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="#h-24"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-25"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-26"><span class="HTitleText2">Duties of Excise</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-27"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-28"><span class="HTitleText2">Bonding and Warehousing</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-29"><span class="HTitleText2">Permits</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-30"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>167 - </span><a href="#h-31"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Breweries</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-32"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-33"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-34"><span class="HTitleText2">Duties of Excise</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-35"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-36"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>180 - </span><a href="#h-37"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Bonded Manufacturers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>180 - </span><a href="#h-38"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-39"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-40"><span class="HTitleText2">Duties of Excise</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-41"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-42"><span class="HTitleText2">Drawback and Remission of Duties</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-43"><span class="HTitleText2">Supervision</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-44"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-45"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="#h-46"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Tobacco and Cigars and Manufacturers Thereof</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>195 - </span><a href="#h-47"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-48"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-49"><span class="HTitleText2">Duties</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-50"><span class="HTitleText2">Tobacco Packaging, Stamping and Marking</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-51"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-52"><span class="HTitleText2">Quantities of Tobacco and Cigars</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-53"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-54"><span class="HTitleText2">Bonding and Warehousing</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-55"><span class="HTitleText2">Canadian Leaf Tobacco</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-56"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="#h-57"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Denatured Alcohol, Specially Denatured Alcohol and Wood Alcohol</span></a>
</li>
<li><a href="#h-58"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
