<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l'Office d'investissement des régimes de pensions du secteur public</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Constitution de l’office</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Gestion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Administrateurs</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Dirigeants</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText2">Diligence</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Décisions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Conflit d’intérêts</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-14"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-15"><span class="HTitleText1">Comités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-16"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Comité de vérification</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-18"><span class="HTitleText2">Comité de placement</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-19"><span class="HTitleText1">Placements</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-20"><span class="HTitleText1">Gestion financière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-21"><span class="HTitleText2">Exercice</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-22"><span class="HTitleText2">États financiers</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-23"><span class="HTitleText2">Rapport du vérificateur</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-24"><span class="HTitleText2">Vérificateur</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-25"><span class="HTitleText2">Accès aux renseignements</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-26"><span class="HTitleText2">Immunité du vérificateur</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-27"><span class="HTitleText2">Vérification spéciale</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-28"><span class="HTitleText2">Examens spéciaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-29"><span class="HTitleText1">Rapports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-30"><span class="HTitleText2">États financiers trimestriels</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-31"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-32"><span class="HTitleText1">Réunions</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-33"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-34"><span class="HTitleText1">Infraction</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-35"><span class="HTitleText1">Liquidation</span></a>
</li>
<li><span class='sectionRange'>53 à 114 - </span><a href="#h-36"><span class="HTitleText1">Modification de la Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>115 à 168 - </span><a href="#h-37"><span class="HTitleText1">Modification de la Loi sur la pension de retraite des forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>169 à 206 - </span><a href="#h-38"><span class="HTitleText1">Modification de la Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>207 à 227 - </span><a href="#h-39"><span class="HTitleText1">Modification d’autres lois</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-40"><span class="HTitleText1">Modification corrélative</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-41"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-42"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
