<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Commission des relations de travail et de l’emploi dans le secteur public fédéral</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-397251"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-397256"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-397264"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-397267"><span class="HTitleText1">Commission des relations de travail et de l’emploi dans le secteur public fédéral </span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-397268"><span class="HTitleText2">Maintien et composition</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-397280"><span class="HTitleText2">Nomination des commissaires</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-397324"><span class="HTitleText2">Rémunération</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-397329"><span class="HTitleText2">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-397334"><span class="HTitleText2">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-397352"><span class="HTitleText2">Attributions de la Commission</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-397375"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-397392"><span class="HTitleText2">Experts</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-397397"><span class="HTitleText2">Immunité</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-397414"><span class="HTitleText2">Révision et exécution</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-397431"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-397442"><span class="HTitleText2">Formations</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-397462"><span class="HTitleText2">Indemnités des témoins</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-397465"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
