<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Fondation canadienne des relations raciales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-72100"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-72103"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-72112"><span class="HTitleText1">Constitution de la fondation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-72115"><span class="HTitleText1">Mission de la fondation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-72125"><span class="HTitleText1">Pouvoirs et capacité de la fondation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-72140"><span class="HTitleText1">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-72164"><span class="HTitleText1">Directeur général</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-72178"><span class="HTitleText1">Rémunération et indemnités</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-72186"><span class="HTitleText1">Comités</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-72189"><span class="HTitleText1">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-72201"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-72210"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-72246"><span class="HTitleText1">Financement</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-72267"><span class="HTitleText1">Rapport</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-72280"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

