<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée nationale de la philanthropie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-354591"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-354594"><span class="HTitleText1">Journée nationale de la philanthropie</span></a>
</li></ul>
</li></ul>

</nav>

