<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi canadienne sur la santé</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-147826"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-147831"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-147874"><span class="HTitleText1">Politique canadienne de la santé</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-147879"><span class="HTitleText1">Raison d’être</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-147884"><span class="HTitleText1">Contribution pécuniaire</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-147890"><span class="HTitleText1">Conditions d’octroi</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-147948"><span class="HTitleText1">Contribution pécuniaire assujettie à des conditions</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-147955"><span class="HTitleText1">Manquements</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-147992"><span class="HTitleText1">Surfacturation et frais modérateurs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-148023"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-148039"><span class="HTitleText1">Rapport au Parlement</span></a>
</li></ul>
</li></ul>

</nav>

