<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’équité salariale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-400758"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-400761"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-400764"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-400830"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-400833"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-400874"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Plan d’équité salariale</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-400995"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Processus d’établissement du plan d’équité salariale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-400996"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-400999"><span class="HTitleText2">Identification des catégories d’emploi</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-401009"><span class="HTitleText2">Décision relative à la prédominance féminine ou masculine des catégories d’emploi</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-401031"><span class="HTitleText2">Établissement de la valeur du travail</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-401045"><span class="HTitleText2">Calcul de la rémunération</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-401065"><span class="HTitleText2">Comparaison de la rémunération</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-401114"><span class="HTitleText2">Contenu et affichage</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-401171"><span class="HTitleText2">Augmentations de la rémunération</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-401244"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Révision du maintien de l’équité salariale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-401245"><span class="HTitleText2">Mise à jour du plan d’équité salariale</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-401336"><span class="HTitleText2">Processus pour la mise à jour du plan d’équité salariale</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-401347"><span class="HTitleText2">Affichage</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-401380"><span class="HTitleText2">Augmentations de la rémunération</span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-401398"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Dispositions générales relatives aux plans d’équité salariale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-401399"><span class="HTitleText2">Déclarations annuelles</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-401439"><span class="HTitleText2">Conservation de documents</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-401454"><span class="HTitleText2">Transfert ou location</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-401472"><span class="HTitleText2">Conventions collectives</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-401475"><span class="HTitleText2">Mise en oeuvre</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-401478"><span class="HTitleText2">Intérêts</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-401484"><span class="HTitleText2">Interdictions</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-401509"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Commissaire à l’équité salariale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-401510"><span class="HTitleText2">Rôle du Commissaire à l’équité salariale</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-401530"><span class="HTitleText2">Autorisations du Commissaire à l’équité salariale</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-401560"><span class="HTitleText2">Renseignements et rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-401575"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Enquêtes et évaluations</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-401641"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>125 - </span><a href="#h-401642"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-401645"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-401648"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-401674"><span class="HTitleText2">Attributions du Commissaire à l’équité salariale</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-401677"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-401699"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-401714"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-401722"><span class="HTitleText2">Révision</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-401749"><span class="HTitleText2">Recouvrement des pénalités</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-401764"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>147 - </span><a href="#h-401773"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Règlement des différends</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="#h-401774"><span class="HTitleText2">Différends, objections et plaintes</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-401805"><span class="HTitleText2">Règlement par le Commissaire à l’équité salariale</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-401887"><span class="HTitleText2">Révisions</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-401907"><span class="HTitleText2">Renvoi au Tribunal</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-401955"><span class="HTitleText2">Appel</span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="#h-401979"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Personnel des cabinets de ministres</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-401987"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Dispositions diverses</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
