<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Agreement on Internal Trade Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Implementation of the Agreement Generally</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Approval of Agreement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText2">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Committee on Internal Trade</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Panels and Committees</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText2">Appointments</span></a>
</li></ul>
</li><li><span class='sectionRange'>15. to 19 - </span><a href="#h-13"><span class="HTitleText1">Related and Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
