<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi de mise en oeuvre de la convention sur les armes biologiques ou à toxines <span class='Repealed'>[Abrogée avant d'entrer en vigueur, 2008, ch. 20, art. 3]</span></a></li></ul>
</nav>
</div></section>
