<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les mesures économiques spéciales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-423844"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-423847"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-423860"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-423863"><span class="HTitleText1">Décrets et règlements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-423903"><span class="HTitleText1">Application</span></a>
</li></ul>
</li></ul>

</nav>

