<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Foreign Publishers Advertising Services Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-235955"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-235958"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-235991"><span class="HTitleText1">Prohibition</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-236013"><span class="HTitleText1">Investigations</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-236029"><span class="HTitleText1">Ministerial Demands and Judicial Proceedings</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-236063"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-236093"><span class="HTitleText1">Recovery of Fines by Civil Judgment</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-236096"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-236104"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-236112"><span class="HTitleText1">Non-application of Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-236127"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

