<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de mise en oeuvre de l’Accord de libre-échange Canada–AELÉ</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-81017"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-81020"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-81041"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-81049"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-81052"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-81062"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’accord et des accords bilatéraux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-81063"><span class="HTitleText2">Approbation de l’Accord et des accords bilatéraux</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-81066"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-81073"><span class="HTitleText2">Sous-comités et groupes de travail</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-81080"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-81090"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-81091"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-81099"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-1.html#h-81107"><span class="HTitleText2">Tarif des douanes</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-1.html#h-81116"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-2.html#h-81120"><span class="scheduleLabel">ANNEXES 1 À 7</span></a>
</li></ul>
</li></ul>

</nav>

