<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Small Business Investment Grants Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-431404"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-431407"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-431413"><span class="HTitleText1">Small Business Investment Grants</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-431423"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

