<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
International River Improvements Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Licences</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText2">Assistance to Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-11"><span class="HTitleText2">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Compliance Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HTitleText1">Obstruction and False Information</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-14"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-15"><span class="HTitleText1">Reports</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
