<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Legislation Revision and Consolidation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-441267"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-441272"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-441286"><span class="HTitleText1">Statute Revision Commission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-441298"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Public General Statutes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-441299"><span class="HTitleText2">Revision</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-1.html#h-441326"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-441327"><span class="HTitleText2">Revision</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-2.html#h-441419"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Consolidated Statutes and Regulations of Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-2.html#h-441420"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-441427"><span class="HTitleText2">Consolidation of the Statutes and Regulations</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-441440"><span class="HTitleText2">Publication and Distribution</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-441452"><span class="HTitleText2">Effect of Consolidation</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-441466"><span class="HTitleText2">Co-publishing Agreements</span></a>
</li></ul>
</li><li><a href="page-3.html#h-441472"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Model Bill</span></a>
</li></ul>
</li></ul>

</nav>

