<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’indemnisation du dommage causé par des pesticides</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-382037"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-382042"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-382051"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Indemnisation du dommage causé par des pesticides</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-382052"><span class="HTitleText2">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-382099"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-382132"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="page-1.html#h-382151"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Appels des décisions ministérielles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-382152"><span class="HTitleText2">Évaluateur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

