<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord Canada–États-Unis pour un meilleur échange de renseignements fiscaux</a><ul class="TocIndent"><li><a href="#h-57093"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Accord entre le gouvernement du Canada et le gouvernement des États-Unis d’Amérique en vue d’améliorer l’observation fiscale à l’échelle internationale au moyen d’un meilleur échange de renseignements en vertu de la Convention entre le Canada et les États-Unis d’Amérique en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-57295"><span class="scheduleLabel"><strong>ANNEXE I</strong></span> - <span class="scheduleTitleText"> - Obligations de diligence raisonnable en matière d’identification et de déclaration de comptes déclarables américains et de paiements effectués à certaines institutions financières non participantes</span></a>
</li>
<li><a href="#h-57496"><span class="scheduleLabel"><strong>ANNEXE II</strong></span> - <span class="scheduleTitleText"> - Institutions financières canadiennes non déclarantes et produits dispensés de déclaration</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
