<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Service canadien du renseignement de sécurité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-74307"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-74312"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-74339"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Service canadien du renseignement de sécurité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-74340"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-74350"><span class="HTitleText2">Directeur</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-74371"><span class="HTitleText2">Gestion</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-74434"><span class="HTitleText2">Fonctions du Service</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-74580"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-74719"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-74720"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-74734"><span class="HTitleText2">Comité de surveillance des activités de renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-74809"><span class="HTitleText2">Plaintes</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-74848"><span class="HTitleText2">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-74884"><span class="HTitleText2">Rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-74905"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Examen parlementaire</span></a>
</li>
<li><a href="#h-74914"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
