<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la prévention de la pollution des eaux arctiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-5565"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-5570"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-5587"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="page-1.html#h-5599"><span class="HTitleText1">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-5607"><span class="HTitleText1">Dépôt de déchets</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-5677"><span class="HTitleText1">Plans et devis des ouvrages</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-5689"><span class="HTitleText1">Zones de contrôle de la sécurité de la navigation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-5728"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-5770"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-5824"><span class="HTitleText1">Saisie et confiscation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-5868"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-5876"><span class="HTitleText1">Disposition des amendes</span></a>
</li></ul>
</li></ul>

</nav>

