<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Hazardous Materials Information Review Act</a><ul class="TocIndent"><li><span class='sectionRange'>9 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText1">Review of Confidential Business Information</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-4"><span class="HTitleText1">Exemption</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-5"><span class="HTitleText1">Appeals</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-6"><span class="HTitleText1">Commission Established</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-7"><span class="HTitleText1">Chairman</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-8"><span class="HTitleText1">Objects of Council</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-9"><span class="HTitleText1">Powers and Functions</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-10"><span class="HTitleText1">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-11"><span class="HTitleText1">President</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-12"><span class="HTitleText1">Staff</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-13"><span class="HTitleText1">Superannuation</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-14"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-15"><span class="HTitleText1">Appeal Boards</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-16"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-17"><span class="HTitleText1">Confidentiality of Information</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-18"><span class="HTitleText1">Rules</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-19"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-20"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-21"><span class="HTitleText1">Liability</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
