<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la sécurité automobile</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-344668"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-344671"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-344690"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>2.2 - </span><a href="page-1.html#h-344695"><span class="HTitleText1">Ententes administratives</span></a>
</li>
<li><span class='sectionRange'>2.3 - </span><a href="page-1.html#h-344700"><span class="HTitleText1">Personne-ressource</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-344705"><span class="HTitleText1">Marques nationales de sécurité</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-344721"><span class="HTitleText1">Exigences relatives aux matériels</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-344784"><span class="HTitleText1">Dispense pour les véhicules</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-344799"><span class="HTitleText1">Avis de défaut et de non-conformité et arrêtés</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-344919"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-3.html#h-344959"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>16.01 - </span><a href="page-3.html#h-345008"><span class="HTitleText1">Consentements</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-345024"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="page-4.html#h-345054"><span class="HTitleText1">Confiscation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-4.html#h-345066"><span class="HTitleText1">Recherches, examens, tests et droits</span></a>
</li>
<li><span class='sectionRange'>22 et 23 - </span><a href="page-4.html#h-345087"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-4.html#h-345089"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-5.html#h-345093"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Équipement</span></a>
</li>
<li><a href="page-6.html#h-1212280"><span class="scheduleLabel">ANNEXE II</span></a>
</li></ul>
</li></ul>

</nav>

