<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Industrial and Regional Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-333261"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-333266"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-333279"><span class="HTitleText1">Tier Groups</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-333293"><span class="HTitleText1">Grants, Contributions, Loans and Guarantees</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-333361"><span class="HTitleText1">Board</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-333371"><span class="HTitleText1">Report</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-333379"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-333393"><span class="HTitleText1">Expiration</span></a>
</li></ul>
</li></ul>

</nav>

