<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Department of Justice Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-338088"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-338093"><span class="HTitleText1">Establishment of the Department; Attorney General</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-338110"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-338126"><span class="HTitleText1">Powers, Duties and Functions of the Attorney General</span></a>
</li></ul>
</li></ul>

</nav>

