<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Preclearance Act, 2016</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-396237"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-396240"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-396255"><span class="HTitleText1">Designation of Ministers</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-396263"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Preclearance by the United States in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-396264"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-396277"><span class="HTitleText2">Designation of Preclearance Areas and Preclearance Perimeters</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-396292"><span class="HTitleText2">Powers, Duties and Functions in Preclearance Area and Preclearance Perimeter</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-396293"><span class="HTitleText3">Preclearance</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-396311"><span class="HTitleText3">Other Powers and Justification</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-396334"><span class="HTitleText2">Preclearance Area</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-396335"><span class="HTitleText3">Access</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-396343"><span class="HTitleText3">Obligations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-396357"><span class="HTitleText3">Powers, Duties and Functions</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-396431"><span class="HTitleText2">Preclearance Perimeter</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-396449"><span class="HTitleText2">Withdrawal</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-396493"><span class="HTitleText2">Seizure and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-396503"><span class="HTitleText2">Police Officers and Border Services Officers</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-396521"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-396531"><span class="HTitleText2">Civil Liability and Immunity</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-396543"><span class="HTitleText2">Limitation on Requests for Extradition or Provisional Arrest</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-396546"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-396561"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Preclearance by Canada in the United States</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-396562"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-396581"><span class="HTitleText2">Preclearance</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-396625"><span class="HTitleText2">Detention and Delivery under Laws of the United States</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-396631"><span class="HTitleText2">Exemption from Compliance on Entry into Canada</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-396639"><span class="HTitleText2">Withdrawal</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-396651"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-396661"><span class="HTitleText2">Offences — Acts or Omissions in Preclearance Area or Preclearance Perimeter</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-396677"><span class="HTitleText2">Jurisdiction — Offence by Canadian Officer</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-396690"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Related Amendments to the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>62.1 - </span><a href="#h-396693"><span class="HLabel1">PART 3.1</span> - <span class="HTitleText1">Independent Review</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-396696"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Consequential Amendment, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-396697"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-396699"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-396702"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-396706"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Locations in Canada in which Preclearance Areas and Preclearance Perimeters May Be Designated</span></a>
</li></ul>
</li></ul>

</nav>

