<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Official Residences Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-384747"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-384752"><span class="HTitleText1">Properties</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-384778"><span class="HTitleText1">Staff</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-384792"><span class="HTitleText1">Moneys Authorized and Appropriated</span></a>
</li>
<li><a href="#h-384806"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-384814"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="#h-384820"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
