<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la procréation assistée</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-5894"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-5897"><span class="HTitleText1">Principes</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-5907"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-5947"><span class="HTitleText1">Actes interdits</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-6019"><span class="HTitleText1">Responsabilités du ministre</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-2.html#h-6045"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-3.html#h-6170"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-3.html#h-6193"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-3.html#h-6260"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="page-3.html#h-6261"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-3.html#h-6264"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-3.html#h-6266"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-3.html#h-6269"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="page-3.html#h-6271"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

