<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Civil Marriage Act</a><ul class="TocIndent"><li><span class='sectionRange'>2 - </span><a href="#h-85522"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Marriage</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-85552"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Dissolution of Marriage For Non-Resident Spouses</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
