<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1982 sur l’Accord Canada-Allemagne en matière d’impôts</a><ul class="TocIndent"><li><a href="#h-133293"><span class="scheduleLabel">PARTIE 1</span> - <span class="scheduleTitleText"> - Accord entre le Canada et la République fédérale d’Allemagne en vue d’éviter les doubles impositions en matière d’impôts sur le revenu et de certains autres impôts, de prévenir l’évasion fiscale et de fournir assistance en matière d’impôts</span></a>
</li>
<li><a href="#h-133616"><span class="scheduleLabel">PARTIE 2</span> - <span class="scheduleTitleText"> - Protocole à l’Accord entre le Canada et la République fédérale d’Allemagne en vue d’éviter les doubles impositions en matière d’impôts sur le revenu et de certains autres impôts, de prévenir l’évasion fiscale et de fournir assistance en matière d’impôts</span></a>
</li></ul>
</li></ul>

</nav>

