<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Centre canadien d’hygiène et de sécurité au travail</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Mission, pouvoirs et fonctions du centre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Membres du conseil</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Président</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText1">Bureau</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText1">Comités et personnel</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText1">Rémunération et indemnités</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-12"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-13"><span class="HTitleText1">Rapports</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
