<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Trade-marks Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-3"><span class="HTitleText1">Unfair Competition and Prohibited Marks</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText1">Registrable Trade-marks</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText1">Persons Entitled to Registration of Trade-marks</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText1">Validity and Effect of Registration</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-7"><span class="HTitleText1">Certification Marks</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-8"><span class="HTitleText1">Register of Trade-marks</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-9"><span class="HTitleText1">Applications for Registration of Trade-marks</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-10"><span class="HTitleText1">Registration of Trade-marks</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-11"><span class="HTitleText1">Amendment of the Register</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-12"><span class="HTitleText1">Renewal of Registrations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-13"><span class="HTitleText1">Extensions of Time</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-14"><span class="HTitleText1">Transfer</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-15"><span class="HTitleText1">Change of Purpose in Use of Mark</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-16"><span class="HTitleText1">Licences</span></a>
</li>
<li><span class='sectionRange'>51.01 - </span><a href="#h-17"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>51.02 - </span><a href="#h-18"><span class="HTitleText1">Importation and Exportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51.02 - </span><a href="#h-19"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>51.03 - </span><a href="#h-20"><span class="HTitleText2">Prohibition</span></a>
</li>
<li><span class='sectionRange'>51.04 - </span><a href="#h-21"><span class="HTitleText2">Request for Assistance</span></a>
</li>
<li><span class='sectionRange'>51.05 - </span><a href="#h-22"><span class="HTitleText2">Measures Relating to Detained Goods</span></a>
</li>
<li><span class='sectionRange'>51.1 - </span><a href="#h-23"><span class="HTitleText2">No Liability</span></a>
</li>
<li><span class='sectionRange'>51.11 - </span><a href="#h-24"><span class="HTitleText2">Powers of Court Relating to Detained Goods</span></a>
</li></ul>
</li><li><span class='sectionRange'>51.13 - </span><a href="#h-25"><span class="HTitleText1">Trade-mark Agents</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-26"><span class="HTitleText1">Legal Proceedings</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-27"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-28"><span class="HTitleText1">Newfoundland</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-29"><span class="HTitleText1">Transitional Provision</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
