<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Pensions Reporting Act</a><ul class="TocIndent"><li><span class='sectionRange'>10 to 13 - </span><a href="#h-401320"><span class="HTitleText1">Related and Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-401322"><span class="HTitleText1">Commencement</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
