<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Motor Vehicle Safety Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-353310"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-353313"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-353332"><span class="HTitleText1">Exercise of Powers</span></a>
</li>
<li><span class='sectionRange'>2.2 - </span><a href="page-1.html#h-353337"><span class="HTitleText1">Administrative Agreements</span></a>
</li>
<li><span class='sectionRange'>2.3 - </span><a href="page-1.html#h-353342"><span class="HTitleText1">Contact Person</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-353347"><span class="HTitleText1">National Safety Marks</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-353363"><span class="HTitleText1">Vehicle and Equipment Requirements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-353430"><span class="HTitleText1">Vehicle Exemptions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-353445"><span class="HTitleText1">Notices of Defect and of Non-Compliance and Orders</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-353579"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-3.html#h-353619"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>16.01 - </span><a href="page-3.html#h-353670"><span class="HTitleText1">Consent Agreement</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-353686"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="page-4.html#h-353716"><span class="HTitleText1">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-4.html#h-353728"><span class="HTitleText1">Research, Analysis, Testing and Fees</span></a>
</li>
<li><span class='sectionRange'>22 and 23 - </span><a href="page-4.html#h-353749"><span class="HTitleText1">Repeals</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-4.html#h-353751"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-5.html#h-353755"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Motor Vehicle Equipment</span></a>
</li>
<li><a href="page-6.html#h-1226049"><span class="scheduleLabel">SCHEDULE II</span></a>
</li></ul>
</li></ul>

</nav>

