<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Governor General’s Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-252196"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-252201"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Office of Governor General</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="#h-252237"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Governor General’s Retiring Annuity</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
