<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’aménagement du territoire et l’évaluation des projets au Nunavut</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-361608"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-361611"><span class="HTitleText1">Définitions et dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-361671"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-361681"><span class="HTitleText1">Consultations</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-361684"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-361690"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Commissions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-361691"><span class="HTitleText2">Commission d’aménagement du Nunavut</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-361692"><span class="HTitleText3">Mise en place</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-361718"><span class="HTitleText3">Attributions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-361728"><span class="HTitleText3">Réunions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-361731"><span class="HTitleText3">Règlements administratifs et règles</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-361745"><span class="HTitleText2">Commission du Nunavut chargée de l’examen des répercussions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-361746"><span class="HTitleText3">Mise en place</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-361769"><span class="HTitleText3">Attributions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-361783"><span class="HTitleText3">Réunions</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-361795"><span class="HTitleText3">Règlements administratifs et règles</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-361814"><span class="HTitleText3">Comités</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-361822"><span class="HTitleText2">Dispositions générales concernant les commissions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-361823"><span class="HTitleText3">Membres</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-361842"><span class="HTitleText3">Personnel</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-361848"><span class="HTitleText3">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-361858"><span class="HTitleText3">Statut et pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-361866"><span class="HTitleText3">Siège</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-361869"><span class="HTitleText3">Langues</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-361879"><span class="HTitleText3">Règlements administratifs et règles</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-361894"><span class="HTitleText3">Dispositions financières</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-361906"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Aménagement du territoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-361907"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-361910"><span class="HTitleText2">Politiques, priorités et objectifs</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-361924"><span class="HTitleText2">Plans d’aménagement du territoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-361925"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-361954"><span class="HTitleText3">Élaboration</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-361997"><span class="HTitleText3">Modification</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-362031"><span class="HTitleText3">Révision périodique</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-362036"><span class="HTitleText3">Mise en oeuvre</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-362057"><span class="HTitleText2">Parcs et aires de préservation</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-362065"><span class="HTitleText2">Municipalités</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-362073"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Évaluation des projets à réaliser dans la région désignée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-362074"><span class="HTitleText2">Définitions et disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-362084"><span class="HTitleText2">Caractère obligatoire</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-362106"><span class="HTitleText2">Examen par la Commission d’aménagement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-362107"><span class="HTitleText3">Proposition relative au projet</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-362117"><span class="HTitleText3">Plan d’aménagement en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-362118"><span class="HTitleText4">Décision</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-362124"><span class="HTitleText4">Projet conforme au plan d’aménagement</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-362141"><span class="HTitleText4">Projet non conforme au plan d’aménagement</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-362175"><span class="HTitleText4">Délai</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-362185"><span class="HTitleText3">Absence de plan d’aménagement</span></a>
</li></ul>
</li><li><span class='sectionRange'>86 - </span><a href="#h-362193"><span class="HTitleText2">Examen préalable par la Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-362299"><span class="HTitleText2">Examen approfondi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-362300"><span class="HTitleText3">Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-362471"><span class="HTitleText3">Commission fédérale d’évaluation environnementale</span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-362643"><span class="HTitleText2">Conditions visant la réalisation des projets</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="#h-362644"><span class="HTitleText3">Compatibilité</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-362647"><span class="HTitleText3">Programmes de suivi</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-362668"><span class="HTitleText3">Mise en oeuvre</span></a>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="#h-362704"><span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-362705"><span class="HTitleText3">Modification du projet en cours d’évaluation</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-362722"><span class="HTitleText3">Demandes en cours d’évaluation</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-362751"><span class="HTitleText3">Modification du projet après l’évaluation</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-362759"><span class="HTitleText3">Projets non réalisés</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-362767"><span class="HTitleText3">Consultations</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-362770"><span class="HTitleText3">Pluralité de ministres compétents</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-362780"><span class="HTitleText3">Décisions motivées</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-362787"><span class="HTitleText2">Cas particuliers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-362788"><span class="HTitleText3">Sécurité nationale</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-362791"><span class="HTitleText3">Situations d’urgence</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-362812"><span class="HTitleText3">Réapprovisionnement et mouvements de navire</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-362818"><span class="HTitleText3">Activités d’exploration, de préparation ou de mise en valeur</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-362835"><span class="HTitleText3">Projets transfrontaliers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-362836"><span class="HTitleText4">Examen par la Commission d’aménagement</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-362842"><span class="HTitleText4">Examen préalable par la Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-362848"><span class="HTitleText4">Examen approfondi</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="#h-362849"><span class="HTitleText5">Commission d’examen</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-362868"><span class="HTitleText5">Commission fédérale d’évaluation environnementale ou formation conjointe</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-362898"><span class="HTitleText3">Parcs et aires de préservation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-362899"><span class="HTitleText4">Projets</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-362970"><span class="HTitleText4">Création, abolition et modification de la superficie</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-362971"><span class="HTitleText5">Disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-362974"><span class="HTitleText5">Proposition</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-362982"><span class="HTitleText5">Plan d’aménagement en vigueur</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-363030"><span class="HTitleText5">Absence de plan d’aménagement</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-363033"><span class="HTitleText5">Régime juridique applicable</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-363063"><span class="HTitleText5">Travaux antérieurs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>184 - </span><a href="#h-363066"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Examen des projets à réaliser à l’extérieur de la région désignée</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-363080"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>189 - </span><a href="#h-363081"><span class="HTitleText2">Définitions et disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-363089"><span class="HTitleText2">Qualité pour agir en cours d’évaluation</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-363094"><span class="HTitleText2">Coordination des activités</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-363108"><span class="HTitleText2">Renseignements et documents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-363109"><span class="HTitleText3">Obtention des renseignements</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-363119"><span class="HTitleText3">Utilisation des renseignements</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-363122"><span class="HTitleText3">Communication des renseignements et des documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>207 - </span><a href="#h-363227"><span class="HTitleText2">Maintien des droits</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-363252"><span class="HTitleText2">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>209 - </span><a href="#h-363253"><span class="HTitleText3">Désignation</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-363256"><span class="HTitleText3">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-363292"><span class="HTitleText3">Ordres</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-363302"><span class="HTitleText3">Coordination</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-363305"><span class="HTitleText3">Injonction</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-363313"><span class="HTitleText3">Interdictions, infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>220 - </span><a href="#h-363327"><span class="HTitleText2">Questions judiciaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-363328"><span class="HTitleText3">Compétence judiciaire</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-363346"><span class="HTitleText3">Immunité</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-363351"><span class="HTitleText3">Délais</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-363354"><span class="HTitleText2">Surveillance générale</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-363360"><span class="HTitleText2">Règlements et arrêtés</span></a>
</li></ul>
</li><li><span class='sectionRange'>231 - </span><a href="#h-363381"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><a href="#h-363406"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-363409"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Organismes administratifs désignés</span></a>
</li>
<li><a href="#h-363415"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Catégories d’ouvrages ou d’activités exemptés de l’examen préalable</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
