<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la pension de retraite des Forces canadiennes </a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Égalité de statut</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-4"><span class="HTitleText1">Application à certains membres de la force de réserve</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Pension de retraite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText2">Admissibilité aux prestations</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText2">Service ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText2">Service ouvrant droit à pension et accompagné d’option : montant exigible</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-10"><span class="HTitleText2">Options</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText2">Prestations : définitions et autres dispositions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText2">Mode de calcul des annuités</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-13"><span class="HTitleText2">Prestations à payer aux contributeurs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Prestations à payer aux survivants, aux enfants et à d’autres bénéficiaires</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-15"><span class="HTitleText2">Prestations minimales</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-16"><span class="HTitleText2">Cas spéciaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText3">Anciens membres de la force régulière</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText3">Membres de la force régulière enrôlés pour une période de service déterminée</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HTitleText3">Anciens employés de la fonction publique et membres de la Gendarmerie royale du Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-20"><span class="HTitleText2">Conseil des pensions militaires</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="#h-21"><span class="HTitleText2">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-23"><span class="HTitleText2">Paiements sur le compte de pension de retraite</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-24"><span class="HTitleText2">Montants</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-25"><span class="HTitleText2">Fonds de placement du compte de pension de retraite des Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>55.2 - </span><a href="#h-26"><span class="HTitleText2">Caisse de retraite des Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-27"><span class="HTitleText2">Rapport actuariel</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-28"><span class="HTitleText2">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-29"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-30"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>59.1 - </span><a href="#h-31"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Régime de pension de la force de réserve</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-32"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Prestations de décès supplémentaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-33"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-34"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-35"><span class="HTitleText2">Prestations</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-36"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-37"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Prestations supplémentaires</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-38"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-69604"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
