<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le commissaire au renseignement</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1156469"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1156472"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1156475"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1156478"><span class="HTitleText1">Commissaire</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-1156530"><span class="HTitleText1">Attributions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-1156567"><span class="HTitleText1">Rapport public</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-1156575"><span class="HTitleText1">Renseignements</span></a>
</li></ul>
</li></ul>

</nav>

