<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les Territoires du Nord-Ouest</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Pouvoir exécutif</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-4"><span class="HTitleText1">Pouvoir législatif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText2">Assemblée législative des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText2">Législature des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-7"><span class="HTitleText2">Compétence législative</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-8"><span class="HTitleText1">Trésor des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-9"><span class="HTitleText1">Comptes publics des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-10"><span class="HTitleText1">Administration de la justice</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-11"><span class="HTitleText2">Organisation judiciaire</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-12"><span class="HTitleText2">Cour suprême des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-13"><span class="HTitleText2">Cour d’appel des Territoires du Nord-Ouest</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-14"><span class="HTitleText1">Terres domaniales et eaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-15"><span class="HTitleText2">Gestion et maîtrise</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-16"><span class="HTitleText2">Restrictions</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-17"><span class="HTitleText2">Indemnisation</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-18"><span class="HTitleText2">Accords</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-19"><span class="HTitleText1">Modification de la présente loi</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-20"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-21"><span class="HTitleText1">Modification apportée à la présente Loi</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
