<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Bureau canadien d’enquête sur les accidents de transport et de la sécurité des transports</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-73618"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-73621"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-73649"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-73669"><span class="HTitleText1">Bureau canadien d’enquête sur les accidents de transport et de la sécurité des transports</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-73790"><span class="HTitleText1">Enquêtes — enquêtes publiques</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-73903"><span class="HTitleText1">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-73968"><span class="HTitleText1">Renseignements protégés</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-74039"><span class="HTitleText1">Témoignage des enquêteurs</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-74048"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-74069"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>37 à 57 - </span><a href="#h-74090"><span class="HTitleText1">Modifications corrélatives et abrogation</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-74092"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-74145"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-74149"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

