<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les associations coopératives de crédit</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Définitions et application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-4"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-7"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Constitution, prorogation et cessation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText2">Formalités constitutives</span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="#h-9"><span class="HTitleText2">Prorogation</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HTitleText2">Cessation</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-11"><span class="HTitleText2">Dénomination sociale</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-12"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Associés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-13"><span class="HTitleText2">Adhésion</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-14"><span class="HTitleText2">Retrait et expulsion</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-15"><span class="HTitleText2">Registre des associés</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-16"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-17"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Organisation et fonctionnement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-18"><span class="HTitleText2">Réunions</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-19"><span class="HTitleText2">Fonctionnement initial</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="#h-20"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Structure du capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="#h-21"><span class="HTitleText2">Capital social</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-22"><span class="HTitleText2">Titres secondaires</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-23"><span class="HTitleText2">Certificats de valeurs mobilières et transferts</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="#h-24"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Administration de l’association</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="#h-25"><span class="HTitleText2">Associés et actionnaires</span></a>
</li>
<li><span class='sectionRange'>166.01 - </span><a href="#h-26"><span class="HTitleText2">Procurations</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-27"><span class="HTitleText2">Administrateurs et dirigeants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-28"><span class="HTitleText3">Obligations</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-29"><span class="HTitleText3">Administrateurs — Nombre et qualités requises</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-30"><span class="HTitleText3">Administrateurs — Élections et fonctions</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-31"><span class="HTitleText3">Vacances d’administrateurs</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-32"><span class="HTitleText3">Réunions du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-33"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-34"><span class="HTitleText3">Comités du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-35"><span class="HTitleText3">Mandat des administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-36"><span class="HTitleText3">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-37"><span class="HTitleText3">Responsabilité, exonération et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>219 - </span><a href="#h-38"><span class="HTitleText2">Modifications de structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>219 - </span><a href="#h-39"><span class="HTitleText3">Modifications</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-40"><span class="HTitleText3">Fusion</span></a>
</li>
<li><span class='sectionRange'>233.1 - </span><a href="#h-41"><span class="HTitleText3">Ventes d’éléments d’actif</span></a>
</li></ul>
</li><li><span class='sectionRange'>234 - </span><a href="#h-42"><span class="HTitleText2">Livres et registres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>234 - </span><a href="#h-43"><span class="HTitleText3">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-44"><span class="HTitleText3">Registres des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-45"><span class="HTitleText3">Dénomination sociale et sceau</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="#h-46"><span class="HTitleText2">Initiés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>260 - </span><a href="#h-47"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-48"><span class="HTitleText3">Rapport d’initié</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-49"><span class="HTitleText3">Opérations d’initiés</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="#h-50"><span class="HTitleText3">Recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>268 - </span><a href="#h-51"><span class="HTitleText2">Prospectus</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-52"><span class="HTitleText2"><cite class="XRefExternalAct">Actes de fiducie</cite></span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="#h-53"><span class="HTitleText2">États financiers et vérificateurs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>291 - </span><a href="#h-54"><span class="HTitleText3">Rapport financier annuel</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-55"><span class="HTitleText3">Vérificateur</span></a>
</li></ul>
</li><li><span class='sectionRange'>318 - </span><a href="#h-56"><span class="HTitleText2">Recours judiciaires</span></a>
</li>
<li><span class='sectionRange'>323 - </span><a href="#h-57"><span class="HTitleText2">Liquidation et dissolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>323 - </span><a href="#h-58"><span class="HTitleText3">Définition et application</span></a>
</li>
<li><span class='sectionRange'>326 - </span><a href="#h-59"><span class="HTitleText3">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="#h-60"><span class="HTitleText3">Surveillance judiciaire</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="#h-61"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>354 - </span><a href="#h-62"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>354 - </span><a href="#h-63"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Restrictions à la propriété</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="#h-64"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">[Abrogée, 1994, ch. 47, art. 54]</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="#h-65"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Arrêtés et ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>375 - </span><a href="#h-66"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Activité et pouvoirs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>375 - </span><a href="#h-67"><span class="HTitleText2">Activités commerciales générales</span></a>
</li>
<li><span class='sectionRange'>385.01 - </span><a href="#h-68"><span class="HTitleText2">Dépôts</span></a>
</li>
<li><span class='sectionRange'>385.03 - </span><a href="#h-69"><span class="HTitleText2">Soldes non réclamés</span></a>
</li>
<li><span class='sectionRange'>385.05 - </span><a href="#h-70"><span class="HTitleText2">Comptes</span></a>
</li>
<li><span class='sectionRange'>385.14 - </span><a href="#h-71"><span class="HTitleText2">Coût d’emprunt</span></a>
</li>
<li><span class='sectionRange'>385.22 - </span><a href="#h-72"><span class="HTitleText2">Réclamations</span></a>
</li>
<li><span class='sectionRange'>385.25 - </span><a href="#h-73"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>386 - </span><a href="#h-74"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>386 - </span><a href="#h-75"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>387 - </span><a href="#h-76"><span class="HTitleText2">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="#h-77"><span class="HTitleText2">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-78"><span class="HTitleText2">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="#h-79"><span class="HTitleText2">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>398 - </span><a href="#h-80"><span class="HTitleText2">Prêts commerciaux</span></a>
</li>
<li><span class='sectionRange'>401 - </span><a href="#h-81"><span class="HTitleText2">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="#h-82"><span class="HTitleText2">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>403 - </span><a href="#h-83"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>409 - </span><a href="#h-84"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Capital et liquidités</span></a>
</li>
<li><span class='sectionRange'>409.1 - </span><a href="#h-85"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Opérations avec apparentés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>409.1 - </span><a href="#h-86"><span class="HTitleText2">Interprétation et application</span></a>
</li>
<li><span class='sectionRange'>413 - </span><a href="#h-87"><span class="HTitleText2">Opérations interdites</span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="#h-88"><span class="HTitleText2">Opérations permises</span></a>
</li>
<li><span class='sectionRange'>425 - </span><a href="#h-89"><span class="HTitleText2">Restrictions applicables aux opérations permises</span></a>
</li>
<li><span class='sectionRange'>428 - </span><a href="#h-90"><span class="HTitleText2">Obligation d’information</span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="#h-91"><span class="HTitleText2">Recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>431 - </span><a href="#h-92"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Réglementation des associations : surintendant</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>431 - </span><a href="#h-93"><span class="HTitleText2">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>431 - </span><a href="#h-94"><span class="HTitleText3">Relevés</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="#h-95"><span class="HTitleText3">Enquête sur les associations</span></a>
</li></ul>
</li><li><span class='sectionRange'>438.1 - </span><a href="#h-96"><span class="HTitleText2">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>438.1 - </span><a href="#h-97"><span class="HTitleText3">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>439 - </span><a href="#h-98"><span class="HTitleText3">Décisions</span></a>
</li>
<li><span class='sectionRange'>441.01 - </span><a href="#h-99"><span class="HTitleText3">Rejet des candidatures et destitution</span></a>
</li>
<li><span class='sectionRange'>442 - </span><a href="#h-100"><span class="HTitleText3">Surveillance et intervention</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>452.1 - </span><a href="#h-101"><span class="HLabel1">PARTIE XIII.1</span> - <span class="HTitleText1">Réglementation des associations de détail : commissaire</span></a>
</li>
<li><span class='sectionRange'>452.6 - </span><a href="#h-102"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>452.6 - </span><a href="#h-103"><span class="HTitleText2">Avis et autres documents</span></a>
</li>
<li><span class='sectionRange'>459.2 - </span><a href="#h-104"><span class="HTitleText2">Agréments</span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="#h-105"><span class="HTitleText2">Arrêts, ordonnances et décisions</span></a>
</li>
<li><span class='sectionRange'>461.1 - </span><a href="#h-106"><span class="HTitleText2">Demandes au surintendant</span></a>
</li>
<li><span class='sectionRange'>461.2 - </span><a href="#h-107"><span class="HTitleText2">Demandes relatives à certains agréments</span></a>
</li>
<li><span class='sectionRange'>462 - </span><a href="#h-108"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="#h-109"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="#h-110"><span class="HTitleText2">Délégation</span></a>
</li></ul>
</li><li><span class='sectionRange'>465 - </span><a href="#h-111"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Peines</span></a>
</li>
<li><span class='sectionRange'>472 - </span><a href="#h-112"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Coopératives de crédit centrales</span></a>
</li>
<li><span class='sectionRange'>481 - </span><a href="#h-113"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Prêts consentis à des associations et à des agences d’assurance-dépôts</span></a>
</li>
<li><span class='sectionRange'>488 à 499 - </span><a href="#h-114"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>500 - </span><a href="#h-115"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
