<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2017, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-38414"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-38417"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Income Tax Act</cite> and to Related Legislation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-38418"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-38453"><span class="HTitleText2"><cite class="XRefExternalAct">Budget Implementation Act, 2016, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-38455"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-38459"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-38461"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Tax Act</cite> (GST/HST Measures)</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-38469"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the <cite class="XRefExternalAct">Excise Act</cite>, the <cite class="XRefExternalAct">Excise Act, 2001</cite> and the <cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-38470"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act</cite></span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-38474"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-38500"><span class="HTitleText2"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-38502"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-38504"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-38505"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Special Import Measures Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-38506"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-38538"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-38542"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-38545"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Public Debt</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="#h-38546"><span class="HTitleText3">Enactment of <cite class="XRefExternalAct">Borrowing Authority Act</cite></span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-38549"><span class="HTitleText3">Amendment to the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-38551"><span class="HTitleText3">Amendment to the <cite class="XRefExternalAct">Hibernia Development Project Act</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-38553"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Budget Implementation Act, 2016, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-38555"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-38560"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Financial Sector Stability</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-38561"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-38565"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-38567"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>113 - </span><a href="#h-38575"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Shared Services Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-38578"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Payment to the Canadian Institute for Advanced Research</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-38581"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Financial Assistance for Students</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-38582"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Student Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-38584"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Education Savings Act</cite></span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-38589"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="#h-38595"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Parliamentary Budget Officer and Board of Internal Economy</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-38596"><span class="HTitleText3"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-38597"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-38607"><span class="HTitleText4">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>157 - </span><a href="#h-38634"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-38635"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-38637"><span class="HTitleText4"><cite class="XRefExternalAct">Canada Post Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-38639"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-38641"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-38643"><span class="HTitleText4"><cite class="XRefExternalAct">Garnishment, Attachment and Pension Diversion Act</cite></span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-38654"><span class="HTitleText4"><cite class="XRefExternalAct">Government Employees Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-38656"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-38658"><span class="HTitleText4"><cite class="XRefExternalAct">Radiocommunication Act</cite></span></a>
</li>
<li><span class='sectionRange'>173.1 - </span><a href="#h-38660"><span class="HTitleText4"><cite class="XRefExternalAct">Royal Canadian Mounted Police Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-38662"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-38667"><span class="HTitleText4"><cite class="XRefExternalAct">Non-smokers’ Health Act</cite></span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-38669"><span class="HTitleText4"><cite class="XRefExternalAct">Official Languages Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-38676"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-38678"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-38680"><span class="HTitleText4"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-38683"><span class="HTitleText4"><cite class="XRefExternalAct">Expenditure Restraint Act</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-38685"><span class="HTitleText4"><cite class="XRefExternalAct">Language Skills Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="#h-38687"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="#h-38690"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>192 - </span><a href="#h-38691"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-38694"><span class="HTitleText3">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="#h-38696"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Funding for Home Care Services and Mental Health Services</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-38716"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Judges Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="#h-38717"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-38749"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-38751"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>229 - </span><a href="#h-38757"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2">Support for Families: Benefits and Leaves</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="#h-38758"><span class="HTitleText3"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="#h-38759"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-38785"><span class="HTitleText4">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-38789"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>259 - </span><a href="#h-38792"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>259 - </span><a href="#h-38793"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-38803"><span class="HTitleText4">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>269 - </span><a href="#h-38805"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="#h-38808"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Canadian Forces Members and Veterans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>270 - </span><a href="#h-38809"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Forces Members and Veterans Re-establishment and Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-38828"><span class="HTitleText3"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="#h-38832"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Veterans Affairs Act</cite></span></a>
</li>
<li><span class='sectionRange'>292 - </span><a href="#h-38834"><span class="HTitleText3">Terminology Changes</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="#h-38839"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-38844"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>297 - </span><a href="#h-38845"><span class="HTitleText4"><cite class="XRefExternalAct">Jobs, Growth and Long-term Prosperity Act</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-38847"><span class="HTitleText4"><cite class="XRefExternalAct">Budget Implementation Act, 2016, No. 1</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="#h-38849"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>300 - </span><a href="#h-38852"><span class="HLabel2">DIVISION 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-38859"><span class="HLabel2">DIVISION 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Employment Insurance Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>306 - </span><a href="#h-38860"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="#h-38866"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>312 - </span><a href="#h-38869"><span class="HLabel2">DIVISION 15</span> - <span class="HTitleText2">Agreements — Minister of Transport</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>312 - </span><a href="#h-38870"><span class="HTitleText3"><cite class="XRefExternalAct">Aeronautics Act</cite></span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-38873"><span class="HTitleText3"><cite class="XRefExternalAct">Navigation Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="#h-38875"><span class="HTitleText3"><cite class="XRefExternalAct">Railway Safety Act</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-38877"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Shipping Act, 2001</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="#h-38879"><span class="HLabel2">DIVISION 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Food and Drugs Act</cite></span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="#h-38881"><span class="HLabel2">DIVISION 17</span> - <span class="HTitleText2">Labour and Employment Laws</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>318 - </span><a href="#h-38882"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Labour Code</cite></span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="#h-38943"><span class="HTitleText3"><cite class="XRefExternalAct">Wage Earner Protection Program Act</cite></span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="#h-38948"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="#h-38961"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>394 - </span><a href="#h-38962"><span class="HTitleText4"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="#h-38964"><span class="HTitleText4"><cite class="XRefExternalAct">Hazardous Materials Information Review Act</cite></span></a>
</li>
<li><span class='sectionRange'>396 - </span><a href="#h-38966"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Labour Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="#h-38968"><span class="HTitleText4"><cite class="XRefExternalAct">Public Servants Disclosure Protection Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>398 - </span><a href="#h-38970"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="#h-38975"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>403 - </span><a href="#h-38991"><span class="HLabel2">DIVISION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Infrastructure Bank Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>403 - </span><a href="#h-38992"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>404 - </span><a href="#h-38995"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>404 - </span><a href="#h-38996"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>405 - </span><a href="#h-38998"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="#h-39000"><span class="HTitleText4"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>407 - </span><a href="#h-39002"><span class="HLabel2">DIVISION 19</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>407 - </span><a href="#h-39003"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>436 - </span><a href="#h-39033"><span class="HTitleText3"><cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>436 - </span><a href="#h-39034"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="#h-39037"><span class="HTitleText4">Related Amendment to the <cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>439 - </span><a href="#h-39039"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>441 - </span><a href="#h-39042"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>442 - </span><a href="#h-39050"><span class="HLabel2">DIVISION 20</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Invest in Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>442 - </span><a href="#h-39051"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="#h-39054"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="#h-39056"><span class="HTitleText3">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>444 - </span><a href="#h-39057"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="#h-39059"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>448 - </span><a href="#h-39063"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-39065"><span class="HTitleText4"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>450 - </span><a href="#h-39067"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>451 - </span><a href="#h-39070"><span class="HLabel2">DIVISION 21</span> - <span class="HTitleText2">Modernization of Service Fees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>451 - </span><a href="#h-39071"><span class="HTitleText3">Enactment of <cite class="XRefExternalAct">Service Fees Act</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-39074"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>453 - </span><a href="#h-39076"><span class="HTitleText3">Related Amendment to the <cite class="XRefExternalAct">Economic Action Plan 2014 Act, No. 1</cite></span></a>
</li>
<li><span class='sectionRange'>454 - </span><a href="#h-39078"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="#h-39083"><span class="HTitleText3">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>456 - </span><a href="#h-39085"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>457 - </span><a href="#h-39087"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-39094"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-39096"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
