<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Post Corporation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-59874"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-59879"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-59913"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-59918"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Canada Post Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-59919"><span class="HTitleText2">Incorporation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-59924"><span class="HTitleText2">Objects</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-59940"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-59956"><span class="HTitleText2">Chairperson of the Board</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-59966"><span class="HTitleText2">President of the Corporation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-59978"><span class="HTitleText2">Head Office</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-59983"><span class="HTitleText2">Administration of Corporation</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-59999"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-60016"><span class="HTitleText2">Exclusive Privilege of Corporation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-60042"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-60058"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="page-2.html#h-60113"><span class="HTitleText2">Reports</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-60125"><span class="HTitleText2">Directives</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-60142"><span class="HTitleText2">Status of Corporation</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="page-3.html#h-60166"><span class="HTitleText2">Financial</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-3.html#h-60243"><span class="HLabel1">PART II</span> - <span class="HTitleText1">General Postal Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-3.html#h-60244"><span class="HTitleText2">Government Mail</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-60271"><span class="HTitleText2">Agreements</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-60276"><span class="HTitleText2">Transmission of Mail</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-60284"><span class="HTitleText2">Funds Left with Corporation</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-60286"><span class="HTitleText2">Liability</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-60298"><span class="HTitleText2">Inspection of Mail</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-60309"><span class="HTitleText2">Customs</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-60325"><span class="HTitleText2">Prohibitory Orders</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-4.html#h-60384"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-4.html#h-60465"><span class="HTitleText1">Commencement</span></a>
</li></ul>
</li></ul>

</nav>

