<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les régimes de pension agréés collectifs</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-385414"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-385417"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-385443"><span class="HTitleText1">Objet de la présente loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-385446"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-385451"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-385490"><span class="HTitleText1">Attributions du surintendant</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-385506"><span class="HTitleText1">Agrément</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-385529"><span class="HTitleText1">Gestion des régimes de pension agréés collectifs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-385530"><span class="HTitleText2">Administrateur</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-385582"><span class="HTitleText2">Employeur</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-2.html#h-385603"><span class="HTitleText1">Directives</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-385619"><span class="HTitleText1">Oppositions et appels</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-2.html#h-385642"><span class="HTitleText1">Obligations générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-2.html#h-385643"><span class="HTitleText2">Conditions de participation</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-3.html#h-385688"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-3.html#h-385696"><span class="HTitleText2">Immobilisation des cotisations</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-3.html#h-385708"><span class="HTitleText2">Paiements variables</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-385730"><span class="HTitleText2">Décès du participant</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-3.html#h-385738"><span class="HTitleText2">Divorce, annulation du mariage, séparation ou échec de l’union de fait</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-3.html#h-385760"><span class="HTitleText2">Transfert des fonds et achat de prestations viagères</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-3.html#h-385777"><span class="HTitleText2">Interdiction de la discrimination sexuelle</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-3.html#h-385780"><span class="HTitleText2">Droits à l’information</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-4.html#h-385795"><span class="HTitleText2">Obligations en matière de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-4.html#h-385811"><span class="HTitleText1">Cessation et liquidation</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-4.html#h-385841"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-4.html#h-385908"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-5.html#h-385937"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-5.html#h-385984"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-5.html#h-385987"><span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="page-5.html#h-385988"><span class="HTitleText2">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-5.html#h-385992"><span class="HTitleText2">Loi sur les arrangements avec les créanciers des compagnies</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-5.html#h-385994"><span class="HTitleText2">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-5.html#h-385996"><span class="HTitleText2">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-5.html#h-386003"><span class="HTitleText2">Loi sur le Bureau du surintendant des institutions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="page-5.html#h-386008"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-5.html#h-386010"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

