<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2003</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-36067"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-36070"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Diagnostic and Medical Equipment</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-36078"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-36086"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Student Loans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-36087"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Student Financial Assistance Act</cite></span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-36092"><span class="HTitleText2">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-36094"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-1.html#h-36100"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Employment Insurance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-1.html#h-36101"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-36110"><span class="HTitleText2">Employment Insurance (Fishing) Regulations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-36113"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-36115"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="page-1.html#h-36116"><span class="HTitleText3">Canada Labour Code</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-1.html#h-36121"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="page-1.html#h-36127"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">General — Non-tax Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-1.html#h-36128"><span class="HTitleText2">Foundations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-1.html#h-36129"><span class="HTitleText3">Budget Implementation Act, 1997</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-1.html#h-36131"><span class="HTitleText3">Budget Implementation Act, 1998</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-1.html#h-36133"><span class="HTitleText3">Canada Foundation for Sustainable Development Technology Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-1.html#h-36135"><span class="HTitleText2">Appropriations for Grants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-1.html#h-36136"><span class="HTitleText3">Canada Foundation for Sustainable Development Technology</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-1.html#h-36139"><span class="HTitleText3">Canadian Foundation for Climate and Atmospheric Sciences</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-1.html#h-36142"><span class="HTitleText3">Canada Health Infoway Inc.</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-1.html#h-36145"><span class="HTitleText3">Canadian Health Services Research Foundation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-1.html#h-36148"><span class="HTitleText3">Canadian Institute for Health Information</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-1.html#h-36151"><span class="HTitleText3">Canada Foundation for Innovation</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-1.html#h-36154"><span class="HTitleText3">Genome Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-1.html#h-36157"><span class="HTitleText2">Amendments to the Farm Credit Canada Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-1.html#h-36160"><span class="HTitleText2">Repeal of Debt Servicing and Reduction Account Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-1.html#h-36164"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Amendments to the Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-1.html#h-36166"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Amendments Related to the Taxation of Tobacco Products</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-1.html#h-36167"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-1.html#h-36169"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-1.html#h-36179"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-1.html#h-36184"><span class="HTitleText2">Coming into Force and Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-1.html#h-36190"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Amendments Related to Excise Tax on Fuel and to the Goods and Services Tax/Harmonized Sales Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="page-1.html#h-36191"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-1.html#h-36197"><span class="HTitleText2">Consequential Amendment to Excise Act, 2001</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-1.html#h-36199"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">First Nations Goods and Services Taxes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="page-1.html#h-36200"><span class="HTitleText2">First Nations Goods and Services Tax Act</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-1.html#h-36202"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="page-1.html#h-36203"><span class="HTitleText3">Excise Tax Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>69 - </span><a href="page-1.html#h-36205"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Amendments to the Income Tax Act and Another Act As a Consequence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="page-1.html#h-36206"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-1.html#h-36228"><span class="HTitleText2">Children’s Special Allowances Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-1.html#h-36230"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Amendments Related to Standardized Accounting</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-1.html#h-36231"><span class="HTitleText2">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-1.html#h-36235"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-1.html#h-36253"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-2.html#h-36273"><span class="HTitleText2">Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="page-2.html#h-36274"><span class="HTitleText3">Excise Act, 2001</span></a>
</li></ul>
</li></ul>
</li><li><a href="page-3.html#h-36277"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

