<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Ukrainian Famine and Genocide (“Holodomor”) Memorial Day Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-461836"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-461839"><span class="HTitleText1">Ukrainian Famine and Genocide (“holodomor”) Memorial Day</span></a>
</li></ul>
</li></ul>

</nav>

