<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les restrictions applicables aux promoteurs du crédit d’impôt pour personnes handicapées</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-168272"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-168275"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-168288"><span class="HTitleText1">Frais du promoteur</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-168303"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-168308"><span class="HTitleText1">Communication des renseignements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-168311"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-168317"><span class="HTitleText1">Application de la Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-168320"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-1.html#h-168321"><span class="HTitleText2">Loi sur la Cour canadienne de l’impôt</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-1.html#h-168323"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

