<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Weights and Measures Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Approval of Devices by the Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Units of Measurement</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Use of Units of Measurement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">Use of Devices</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText1">Marking of Commodities</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText1">Reference and Local Standards</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText1">Inspection of Devices</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText1">Inspection Fees and Charges</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-12"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-13"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-14"><span class="HTitleText1">Seizure and Detention</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-15"><span class="HTitleText1">Forfeiture</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Units Based on the International System of Units</span></a>
</li>
<li><a href="#h-468721"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Canadian Units of Measurement</span></a>
</li>
<li><a href="#h-468761"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li>
<li><a href="#h-19"><span class="scheduleLabel">SCHEDULE IV</span> <span class="scheduleTitleText"> - Reference Standards</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
