<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant la taxe sur les produits et services des premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-220678"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-220681"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-220704"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Taxe sur les produits et services des premières nations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-220705"><span class="HTitleText2">Application d’autres lois fédérales</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-220717"><span class="HTitleText2">Texte législatif concernant la taxe sur les produits et services d’une première nation</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-220871"><span class="HTitleText2">Texte législatif autochtone édicté en vertu d’un pouvoir distinct</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-220887"><span class="HTitleText2">Accord d’application et partie IX de la Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-220890"><span class="HTitleText2">Infractions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-220896"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-220908"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Taxe de vente des premières nations — provinces visées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-220909"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-220922"><span class="HTitleText2">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-220942"><span class="HTitleText2">Accord d’application</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-220947"><span class="HTitleText2">Délégation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-220986"><span class="HTitleText2">Disposition générale</span></a>
</li></ul>
</li><li><a href="#h-16"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-221002"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
