<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’étiquetage des textiles</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-438059"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-438064"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-438081"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-438104"><span class="HTitleText1">Étiquetage</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-438115"><span class="HTitleText1">Analystes</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-438120"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-438161"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-438187"><span class="HTitleText1">Infractions et peines</span></a>
</li></ul>
</li></ul>

</nav>

