<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Anti-terrorism Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-4950"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 to 23 - </span><a href="#h-4953"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Criminal Code</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23.1 - </span><a href="#h-4955"><span class="HTitleText2">Consequential Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 to 30 - </span><a href="#h-4957"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Official Secrets Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 to 42 - </span><a href="#h-4959"><span class="HTitleText2">Consequential Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 and 44 - </span><a href="#h-4961"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Canada Evidence Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 and 46 - </span><a href="#h-4963"><span class="HTitleText2">Consequential Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 to 75 - </span><a href="#h-4965"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Proceeds of Crime (Money Laundering) Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 to 86 - </span><a href="#h-4967"><span class="HTitleText2">Consequential Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 to 112 - </span><a href="#h-4969"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-4971"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Registration of Charities — Security Information</span></a>
</li>
<li><span class='sectionRange'>114 to 118 - </span><a href="#h-4973"><span class="HTitleText1">Amendments to the Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>119 to 144 - </span><a href="#h-4975"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Coordinating, Review and Commencement Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 to 144 - </span><a href="#h-4976"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-4978"><span class="HTitleText2">Review and Report</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-4984"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
