<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Agence des services frontaliers du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-41835"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-41838"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-41851"><span class="HTitleText1">Constitution et mission de l’agence</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-41869"><span class="HTitleText1">Ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-41879"><span class="HTitleText1">Président et premier vice-président</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-41910"><span class="HTitleText1">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-41913"><span class="HTitleText1">Pouvoirs de l’agence</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-41939"><span class="HTitleText1">Utilisation des crédits</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-41942"><span class="HTitleText1">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-41948"><span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-41949"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-41957"><span class="HTitleText2">Ancienne agence</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-41995"><span class="HTitleText2">Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-42042"><span class="HTitleText2">Monnaie royale canadienne</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-42045"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-42046"><span class="HTitleText2">Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-42048"><span class="HTitleText2">Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-42051"><span class="HTitleText2">Loi sur les produits agricoles au Canada</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-42053"><span class="HTitleText2">Loi sur l’Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-42073"><span class="HTitleText2">Loi sur l’Agence canadienne d’inspection des aliments</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-42075"><span class="HTitleText2">Loi sur le Tribunal canadien du commerce extérieur</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-42079"><span class="HTitleText2">Loi sur le ministère de la Citoyenneté et de l’Immigration</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-42081"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-42083"><span class="HTitleText2">Loi sur l’exportation et l’importation de biens culturels</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-42085"><span class="HTitleText2">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-42112"><span class="HTitleText2">Loi sur la compétence extracôtière du Canada pour les douanes et l’accise</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-42114"><span class="HTitleText2">Tarif des douanes</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-42118"><span class="HTitleText2">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-42120"><span class="HTitleText2">Loi sur l’accise</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-42122"><span class="HTitleText2">Loi de 2001 sur l’accise</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-42130"><span class="HTitleText2">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-42143"><span class="HTitleText2">Loi d’aide à l’exécution des ordonnances et des ententes familiales</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-42145"><span class="HTitleText2">Loi relative aux aliments du bétail</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-42147"><span class="HTitleText2">Loi sur les engrais</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-42149"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-42152"><span class="HTitleText2">Loi sur l’inspection du poisson</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-42154"><span class="HTitleText2">Loi sur la santé des animaux</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-42156"><span class="HTitleText2">Loi sur l’immigration et la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-42159"><span class="HTitleText2">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-42161"><span class="HTitleText2">Loi sur l’inspection des viandes</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-42164"><span class="HTitleText2">Loi sur la protection des végétaux</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-42166"><span class="HTitleText2">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-42171"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-42173"><span class="HTitleText2">Loi sur la Monnaie royale canadienne</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-42176"><span class="HTitleText2">Loi sur les semences</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-42178"><span class="HTitleText2">Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-42185"><span class="HTitleText2">Modifications terminologiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-42192"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-42196"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
