<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’ouvrage de franchissement du détroit de Northumberland</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-357316"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-357319"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-357330"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-357333"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-357355"><span class="HTitleText1">Subvention annuelle</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-357365"><span class="HTitleText1">Droits</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-357368"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

