<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la responsabilité en matière d’aide au développement officielle</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-374857"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-374860"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-374866"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-374882"><span class="HTitleText1">Aide au développement officielle</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-374897"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-374916"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

