<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la modernisation de certains régimes d'avantages et d'obligations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-2"><span class="HTitleText1">Règle d’interprétation</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText1">Loi sur les programmes de commercialisation agricole</span></a>
</li>
<li><span class='sectionRange'>3 à 7 - </span><a href="#h-4"><span class="HTitleText1">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>8 à 21 - </span><a href="#h-5"><span class="HTitleText1">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>22 à 24 - </span><a href="#h-6"><span class="HTitleText1">Loi sur les lettres de change</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-7"><span class="HTitleText1">Loi sur les ponts</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-8"><span class="HTitleText1">Loi sur la Banque de développement du Canada</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-9"><span class="HTitleText1">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-10"><span class="HTitleText1">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-11"><span class="HTitleText1">Loi sur les corporations canadiennes</span></a>
</li>
<li><span class='sectionRange'>30 à 40 - </span><a href="#h-12"><span class="HTitleText1">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-13"><span class="HTitleText1">Loi sur la Société canadienne d’hypothèques et de logement</span></a>
</li>
<li><span class='sectionRange'>42 à 65 - </span><a href="#h-14"><span class="HTitleText1">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>66. à 68 - </span><a href="#h-15"><span class="HTitleText1">Loi sur la pension de retraite des forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-16"><span class="HTitleText1">Loi sur la médaille canadienne du maintien de la paix</span></a>
</li>
<li><span class='sectionRange'>70 à 72 - </span><a href="#h-17"><span class="HTitleText1">Loi sur la Commission canadienne du blé</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-18"><span class="HTitleText1">Loi sur le transport aérien</span></a>
</li>
<li><span class='sectionRange'>74 à 77 - </span><a href="#h-19"><span class="HTitleText1">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>78 et 79 - </span><a href="#h-20"><span class="HTitleText1">Loi sur l’assurance du service civil</span></a>
</li>
<li><span class='sectionRange'>80 à 83 - </span><a href="#h-21"><span class="HTitleText1">Loi sur les prestations de guerre pour les civils</span></a>
</li>
<li><span class='sectionRange'>84 à 86 - </span><a href="#h-22"><span class="HTitleText1">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-23"><span class="HTitleText1">Loi sur les déclarations des personnes morales</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-24"><span class="HTitleText1">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>89 et 90 - </span><a href="#h-25"><span class="HTitleText1">Loi sur les Cris et les Naskapis du Québec</span></a>
</li>
<li><span class='sectionRange'>91 à 95 - </span><a href="#h-26"><span class="HTitleText1">Code criminel</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-27"><span class="HTitleText1">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>97 et 98 - </span><a href="#h-28"><span class="HTitleText1">Loi sur la continuation de la pension des services de défense</span></a>
</li>
<li><span class='sectionRange'>99 à 105 - </span><a href="#h-29"><span class="HTitleText1">Loi sur la pension spéciale du service diplomatique</span></a>
</li>
<li><span class='sectionRange'>106 à 109 - </span><a href="#h-30"><span class="HTitleText1">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-31"><span class="HTitleText1">Loi sur les biens en déshérence</span></a>
</li>
<li><span class='sectionRange'>111 à 114 - </span><a href="#h-32"><span class="HTitleText1">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-33"><span class="HTitleText1">Loi d’aide à l’exécution des ordonnances et des ententes familiales</span></a>
</li>
<li><span class='sectionRange'>116 à 118 - </span><a href="#h-34"><span class="HTitleText1">Loi sur les armes à feu</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-35"><span class="HTitleText1">Loi sur les missions étrangères et les organisations internationales</span></a>
</li>
<li><span class='sectionRange'>120 et 121 - </span><a href="#h-36"><span class="HTitleText1">Loi sur la saisie-arrêt et la distraction de pensions</span></a>
</li>
<li><span class='sectionRange'>122 et 123 - </span><a href="#h-37"><span class="HTitleText1">Loi relative aux rentes sur l’État</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-38"><span class="HTitleText1">Loi sur le fonctionnement des sociétés du secteur public</span></a>
</li>
<li><span class='sectionRange'>125 et 126 - </span><a href="#h-39"><span class="HTitleText1">Loi sur l’indemnisation des agents de l’État</span></a>
</li>
<li><span class='sectionRange'>127 à 129 - </span><a href="#h-40"><span class="HTitleText1">Loi sur le gouverneur général</span></a>
</li>
<li><span class='sectionRange'>130 à 146 - </span><a href="#h-41"><span class="HTitleText1">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-42"><span class="HTitleText1">Règles concernant l’application de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>148 à 152 - </span><a href="#h-43"><span class="HTitleText1">Loi sur les indiens</span></a>
</li>
<li><span class='sectionRange'>153 à 158 - </span><a href="#h-44"><span class="HTitleText1">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>159 à 169 - </span><a href="#h-45"><span class="HTitleText1">Loi sur les juges</span></a>
</li>
<li><span class='sectionRange'>170 à 175 - </span><a href="#h-46"><span class="HTitleText1">Loi sur la pension de retraite des lieutenants-gouverneurs</span></a>
</li>
<li><span class='sectionRange'>176 à 186 - </span><a href="#h-47"><span class="HTitleText1">Loi sur les allocations de retraite des parlementaires</span></a>
</li>
<li><span class='sectionRange'>187 à 191 - </span><a href="#h-48"><span class="HTitleText1">Loi sur l’indemnisation des marins marchands</span></a>
</li>
<li><span class='sectionRange'>192 à 209 - </span><a href="#h-49"><span class="HTitleText1">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-50"><span class="HTitleText1">Loi sur le Parlement du Canada</span></a>
</li>
<li><span class='sectionRange'>211 à 221 - </span><a href="#h-51"><span class="HTitleText1">Loi sur les pensions</span></a>
</li>
<li><span class='sectionRange'>243 à 253 - </span><a href="#h-52"><span class="HTitleText1">Loi sur le partage des prestations de retraite</span></a>
</li>
<li><span class='sectionRange'>254 à 264 - </span><a href="#h-53"><span class="HTitleText1">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>265 à 270 - </span><a href="#h-54"><span class="HTitleText1">Loi sur les sociétés de caisse de retraite</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-55"><span class="HTitleText1">Loi sur les rapports relatifs aux pensions publiques</span></a>
</li>
<li><span class='sectionRange'>272 à 274 - </span><a href="#h-56"><span class="HTitleText1">Loi sur l’emploi dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>275 à 277 - </span><a href="#h-57"><span class="HTitleText1">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>278 à 284 - </span><a href="#h-58"><span class="HTitleText1">Loi de l’assurance des soldats de retour</span></a>
</li>
<li><span class='sectionRange'>285 à 287 - </span><a href="#h-59"><span class="HTitleText1">Loi sur la continuation des pensions de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>288 à 290 - </span><a href="#h-60"><span class="HTitleText1">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="#h-61"><span class="HTitleText1">Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>292 à 294 - </span><a href="#h-62"><span class="HTitleText1">Loi sur les régimes de retraite particuliers</span></a>
</li>
<li><span class='sectionRange'>295 et 296 - </span><a href="#h-63"><span class="HTitleText1">Loi sur les prestations de retraite supplémentaires</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-64"><span class="HTitleText1">Loi sur les syndicats ouvriers</span></a>
</li>
<li><span class='sectionRange'>298 à 302 - </span><a href="#h-65"><span class="HTitleText1">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>303 à 310 - </span><a href="#h-66"><span class="HTitleText1">Loi sur l’assurance des anciens combattants</span></a>
</li>
<li><span class='sectionRange'>311 à 314 - </span><a href="#h-67"><span class="HTitleText1">Loi sur les terres destinées aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="#h-68"><span class="HTitleText1">Loi sur le tribunal des anciens combattants (révision et appel)</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-69"><span class="HTitleText1">Loi sur les forces étrangères présentes au Canada</span></a>
</li>
<li><span class='sectionRange'>317 à 339 - </span><a href="#h-70"><span class="HTitleText1">Loi sur les allocations aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-71"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-349820"><span class="scheduleLabel">ANNEXES 1 ET 2</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
