<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Heritage Lighthouse Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-253791"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-253794"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-253804"><span class="HTitleText1">Purpose and Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-253815"><span class="HTitleText1">Designation of Heritage Lighthouses</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-253841"><span class="HTitleText1">Protection of Heritage Lighthouses</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-253863"><span class="HTitleText1">Maintenance of Heritage Lighthouses</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-253866"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-253872"><span class="HTitleText1">Related Amendments to the Parks Canada Agency Act</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-253875"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
