<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Housing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Rights and Obligations of the Corporation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Approved Lenders</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Housing Loan Insurance, Guarantee and Protection</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Housing for Rental Purposes</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-8"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Land Assembly</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-9"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Land Acquisition and Leasing</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-10"><span class="HTitleText1">Part V</span> - <span class="HTitleText1">[Repealed, R.S., 1985, c. 25 (4th Supp.), s. 23]</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-11"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Repair, Rehabilitation, Improvement and Conversion of Buildings</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-12"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Facilitation of Home Ownership and Occupancy</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-13"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Housing Research, Community Planning and International Support</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-14"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Public Housing</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-15"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">New Communities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-16"><span class="HTitleText2">Federal-Provincial Agreements</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-17"><span class="HTitleText2">Loans</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-18"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Loans for Student Housing Projects</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-19"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Community Services</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-20"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Housing Development</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-21"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-22"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
