<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2013 sur l’accord fiscal Canada-Hong Kong</a><ul class="TocIndent"><li><a href="page-2.html#h-142767"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Accord entre le gouvernement du Canada et le gouvernement de la Région administrative spéciale de Hong Kong de la République populaire de Chine en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="page-3.html#h-143040"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole</span></a>
</li></ul>
</li></ul>

</nav>

