<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Public Health Events of National Concern Payments Act <span class='Repealed'>[Repealed, 2020, c. 12, s. 11]</span></a></li></ul>
</nav>
</div></section>
