<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Conflict of Interest Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Conflict of Interest Rules</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-5"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Compliance Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-6"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Recusal</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText2">Confidential Disclosure</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText2">Public Declaration</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-10"><span class="HTitleText2">Divestment</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-11"><span class="HTitleText2">Functions of the Commissioner</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-12"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Post-employment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-13"><span class="HTitleText2">Rules for All Former Public Office Holders</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-14"><span class="HTitleText2">Rules for Former Reporting Public Office Holders</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText2">Functions of the Commissioner</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-16"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-17"><span class="HTitleText2">Mandate and Powers of the Commissioner</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-18"><span class="HTitleText2">Public Registry</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-19"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-20"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
