<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les renseignements en matière de modification du temps</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-456554"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-456559"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-456566"><span class="HTitleText1">Renseignements</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-456579"><span class="HTitleText1">Registres et rapports</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-456596"><span class="HTitleText1">Divulgation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-456601"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-456606"><span class="HTitleText1">Infraction et peine</span></a>
</li></ul>
</li></ul>

</nav>

