<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Programme de protection des témoins</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-453746"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-453751"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-453773"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-453778"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-453788"><span class="HTitleText1">Programme de protection des témoins</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-453850"><span class="HTitleText1">Programmes désignés</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-453871"><span class="HTitleText1">Protection des renseignements</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-453989"><span class="HTitleText1">Accords et arrangements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-454017"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-454059"><span class="HTitleText1">Infraction et peine</span></a>
</li>
<li><span class='sectionRange'>22 et 23 - </span><a href="#h-454064"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><a href="#h-454067"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Programmes désignés</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
