<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Agence Parcs Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Constitution de l’agence</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-4"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">Fixation des prix</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-9"><span class="HTitleText1">Rapports et plans</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-10"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-11"><span class="HTitleText1">Application de la Loi sur les langues officielles</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>46 à 61.01 - </span><a href="#h-13"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>61.1 - </span><a href="#h-14"><span class="HTitleText1">Modification conditionnelle</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-15"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
