<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Arctic Waters Pollution Prevention Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-5662"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-5667"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-5684"><span class="HTitleText1">Application of Act</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="page-1.html#h-5696"><span class="HTitleText1">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-5704"><span class="HTitleText1">Deposit of Waste</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-5779"><span class="HTitleText1">Plans and Specifications of Works</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-5791"><span class="HTitleText1">Shipping Safety Control Zones</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-5830"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-5872"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-5928"><span class="HTitleText1">Seizure and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-5973"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-5981"><span class="HTitleText1">Disposition of Fines</span></a>
</li></ul>
</li></ul>

</nav>

