<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Blue Water Bridge Authority Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Joint Operation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Organization</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText2">Powers and Duties of Authority</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText2">Revenues</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText2">Borrowing Powers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-8"><span class="HTitleText2">Accounting</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-10"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Canadian Operation</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
