<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les subventions aux provinces</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-391465"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-391470"><span class="HTitleText1">Subventions déterminées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-391471"><span class="HTitleText2">Nouveau-Brunswick</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-391476"><span class="HTitleText2">Île-du-Prince-Édouard</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-391486"><span class="HTitleText2">Manitoba</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-391494"><span class="HTitleText1">Intérêts et allocations pour dettes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-391529"><span class="HTitleText2">Manitoba</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-391541"><span class="HTitleText1">Avances</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
