<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Centre de la sécurité des télécommunications</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1156609"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1156612"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1156628"><span class="HTitleText1">Principe</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1156631"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1156634"><span class="HTitleText1">Centre de la sécurité des télécommunications</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-1156635"><span class="HTitleText2">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-1156645"><span class="HTitleText2">Chef du Centre de la sécurité des télécommunications</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-1156671"><span class="HTitleText2">Ressources humaines</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-1156693"><span class="HTitleText1">Mandat</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-1156720"><span class="HTitleText1">Activités</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-1156760"><span class="HTitleText1">Autorisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-1156761"><span class="HTitleText2">Autorisations de renseignement étranger et de cybersécurité</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-1156782"><span class="HTitleText2">Autorisations de cyberopérations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-1156808"><span class="HTitleText2">Processus</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-1156858"><span class="HTitleText2">Abrogation et modification</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-1156882"><span class="HTitleText2">Autorisations en cas d’urgence</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-1156896"><span class="HTitleText2">Communication d’informations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-1156918"><span class="HTitleText2">Règles générales applicables aux autorisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-1156943"><span class="HTitleText1">Ententes</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-1156949"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-1156990"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>

