<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Wheat Board Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HLabel1">PART I</span> - <span class="HTitleText1">The Canadian Wheat Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText2">Continuation of the Corporation</span></a>
</li>
<li><span class='sectionRange'>3.01 - </span><a href="#h-6"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>3.06 - </span><a href="#h-7"><span class="HTitleText2">Election of Directors</span></a>
</li>
<li><span class='sectionRange'>3.09 - </span><a href="#h-8"><span class="HTitleText2">President</span></a>
</li>
<li><span class='sectionRange'>3.12 - </span><a href="#h-9"><span class="HTitleText2">Directors and Officers</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-10"><span class="HTitleText2">Object and Powers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-11"><span class="HTitleText2">Pricing, Profits and Losses</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-12"><span class="HTitleText2">Investment of Moneys</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-13"><span class="HTitleText2">Accounts and Reports</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-14"><span class="HTitleText2">Pension Fund and Group Insurance</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-15"><span class="HTitleText2">Directions by Governor in Council</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-16"><span class="HTitleText2">Plans, Borrowings and Guarantees</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-17"><span class="HTitleText2">Operation of Elevators</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-18"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Control of Elevators and Railways</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-19"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-20"><span class="HTitleText2">Delivery of Grain</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-21"><span class="HTitleText2">Permit Books</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-22"><span class="HTitleText2">Administration</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-23"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Interprovincial and Export Marketing of Wheat by the Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-24"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-25"><span class="HTitleText2">Purchase of Wheat and Initial Payment</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-26"><span class="HTitleText2">Payment of Balance and Interim Payments</span></a>
</li>
<li><span class='sectionRange'>33.1 - </span><a href="#h-27"><span class="HTitleText2">Deductions for Research</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-28"><span class="HTitleText2">Quality Characteristics within Grades</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-29"><span class="HTitleText2">Separate Accounts</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-30"><span class="HTitleText2">Regulations and Authorizations respecting Certificates and Accounts</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-31"><span class="HTitleText2">Cash Purchases of Wheat</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-32"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-33"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Regulation of Interprovincial and Export Trade in Wheat</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-34"><span class="HTitleText2">Prohibited Activities</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-35"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-36"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Other Grains</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-37"><span class="HTitleText2">Application of Parts III and IV</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-38"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Marketing Plans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-39"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-40"><span class="HTitleText2">Establishment of Marketing Plans</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-41"><span class="HTitleText2">Initial Payment Guarantee</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-42"><span class="HTitleText2">Review and Audit</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-43"><span class="HTitleText2">Endorsement of Permit Books</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-44"><span class="HTitleText2">Inspectors</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-45"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-46"><span class="HTitleText2">Prohibited Activities</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-47"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="#h-48"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>61.1 - </span><a href="#h-49"><span class="HTitleText2">Implementation of the North American Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-50"><span class="HTitleText2">Borrowing by Agents</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-51"><span class="HTitleText2">Permit Books</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-52"><span class="HTitleText2">Delivery in Contravention of Act</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-53"><span class="HTitleText2">Social Insurance Number</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-54"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-55"><span class="HTitleText2">Evidence</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-56"><span class="HTitleText2">Summary Procedures</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-57"><span class="HTitleText2">Declaration</span></a>
</li>
<li><span class='sectionRange'>76.1 - </span><a href="#h-58"><span class="HTitleText2">Review by Minister</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-59"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-60"><span class="scheduleLabel">SCHEDULE / <span class="otherLang" lang="fr">ANNEXE</span></span> )</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
