<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les eaux des Territoires du Nord-Ouest</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2.1 - </span><a href="#h-4"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Délégation au ministre des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Accords</span></a>
</li>
<li><span class='sectionRange'>7.2 - </span><a href="#h-8"><span class="HTitleText2">Consultations</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText1">Utilisation des eaux</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-10"><span class="HTitleText1">Dépôt de déchets</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="#h-11"><span class="HTitleText1">Collectivités tlichos</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-12"><span class="HTitleText1">Office inuvialuit des eaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-13"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>10.5 - </span><a href="#h-14"><span class="HTitleText2">Mandat</span></a>
</li>
<li><span class='sectionRange'>10.7 - </span><a href="#h-15"><span class="HTitleText2">Rémunération</span></a>
</li>
<li><span class='sectionRange'>11.2 - </span><a href="#h-16"><span class="HTitleText2">Conflit d’intérêts</span></a>
</li>
<li><span class='sectionRange'>11.3 - </span><a href="#h-17"><span class="HTitleText2">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-18"><span class="HTitleText1">Mission et pouvoirs de l’office</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-19"><span class="HTitleText1">Audiences publiques et procédure</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-20"><span class="HTitleText1">Délais</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24.1 - </span><a href="#h-21"><span class="HTitleText2">Pouvoir d’agir</span></a>
</li>
<li><span class='sectionRange'>24.2 - </span><a href="#h-22"><span class="HTitleText2">Décision de l’Office et approbation</span></a>
</li>
<li><span class='sectionRange'>24.5 - </span><a href="#h-23"><span class="HTitleText2">Délais non compris</span></a>
</li>
<li><span class='sectionRange'>24.7 - </span><a href="#h-24"><span class="HTitleText2">Prolongation</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-25"><span class="HTitleText1">Registre public</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-26"><span class="HTitleText1">Décisions et ordonnances</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="#h-27"><span class="HTitleText1">Rapports</span></a>
</li>
<li><span class='sectionRange'>28.2 - </span><a href="#h-28"><span class="HTitleText1">Recouvrement des coûts</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-29"><span class="HTitleText1">Droits et obligations des titulaires de permis et autres</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-30"><span class="HTitleText1">Règlements et décrets</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-31"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-32"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>44.01 - </span><a href="#h-33"><span class="HTitleText1">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44.01 - </span><a href="#h-34"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>44.02 - </span><a href="#h-35"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>44.07 - </span><a href="#h-36"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>44.11 - </span><a href="#h-37"><span class="HTitleText2">Révision</span></a>
</li>
<li><span class='sectionRange'>44.16 - </span><a href="#h-38"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>44.18 - </span><a href="#h-39"><span class="HTitleText2">Recouvrement des pénalités</span></a>
</li>
<li><span class='sectionRange'>44.2 - </span><a href="#h-40"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-41"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-42"><span class="HTitleText1">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-43"><span class="HTitleText2">Loi autorisant l’émission et la vente des actions de la Commission d’énergie du Nord canadien</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-44"><span class="HTitleText2">Mentions de la Loi sur les eaux internes du Nord</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-45"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
