<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Public Sector Labour Relations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-404907"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-404912"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-404978"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Labour Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-404979"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-404998"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Employee Freedoms</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-405001"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Management Rights</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-405010"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Consultation Committees and Co-Development</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-405026"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Federal Public Sector Labour Relations and Employment Board</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-405113"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Bargaining Rights</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-405114"><span class="HTitleText3">Certification of Bargaining Agents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-405115"><span class="HTitleText4">Application for Certification</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-405138"><span class="HTitleText4">Determination of Appropriate Bargaining Units</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-405150"><span class="HTitleText4">Managerial or Confidential Positions</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-405179"><span class="HTitleText4">Certification</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-405202"><span class="HTitleText4">Where Certification Prohibited</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-405208"><span class="HTitleText4">Effect of Certification</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-405222"><span class="HTitleText3">Changes to Certification</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="#h-405223"><span class="HTitleText4">Review of Bargaining Units</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-405233"><span class="HTitleText4">Managerial or Confidential Positions</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-405269"><span class="HTitleText3">Successor Rights and Obligations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-405333"><span class="HTitleText3">Revocation of Certification</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-405376"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Choice of Process for Dispute Resolution</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-405395"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Collective Bargaining and Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>105 - </span><a href="#h-405396"><span class="HTitleText3">Negotiation of Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>105 - </span><a href="#h-405397"><span class="HTitleText4">Notice to Bargain Collectively</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-405410"><span class="HTitleText4">Effect of Notice</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-405421"><span class="HTitleText4">Mediation</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-405427"><span class="HTitleText4">Collective Bargaining for Two or More Units</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-405433"><span class="HTitleText4">Two-tier Bargaining</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-405443"><span class="HTitleText3">Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-405444"><span class="HTitleText4">Authority to Enter into Agreement</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-405449"><span class="HTitleText4">Restriction on Content of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-405456"><span class="HTitleText4">Duration and Effect</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-405471"><span class="HTitleText4">Amendments</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="#h-405474"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Essential Services</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-405592"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Arbitration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-405593"><span class="HTitleText3">Application of Division</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-405600"><span class="HTitleText3">Request for Arbitration</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-405618"><span class="HTitleText3">Establishment of Arbitration Board</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-405649"><span class="HTitleText3">Referral to Arbitration</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-405657"><span class="HTitleText3">Duty and Powers</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-405672"><span class="HTitleText3">Making of Arbitral Award</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-405713"><span class="HTitleText3">Duration and Operation of Arbitral Award</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-405736"><span class="HTitleText3">Implementation</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-405739"><span class="HTitleText3">Matters Not Dealt With</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-405743"><span class="HTitleText3">Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="#h-405746"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">Conciliation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>160 - </span><a href="#h-405747"><span class="HTitleText3">Application of Division</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-405754"><span class="HTitleText3">Request for Conciliation</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-405768"><span class="HTitleText3">Establishment of Public Interest Commission</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-405833"><span class="HTitleText3">Powers and Functions</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-405857"><span class="HTitleText3">Report</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-405888"><span class="HTitleText3">Alternate Dispute Resolution Process</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-405906"><span class="HTitleText3">Vote on Employer’s Offer</span></a>
</li></ul>
</li><li><span class='sectionRange'>184 - </span><a href="#h-405920"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2">Strike Votes</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-405930"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Unfair Labour Practices</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-405987"><span class="HLabel2">DIVISION 13</span> - <span class="HTitleText2">Complaints</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-406040"><span class="HLabel2">DIVISION 14</span> - <span class="HTitleText2">Prohibitions and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-406041"><span class="HTitleText3">Acts of Officers and Representatives of Employee Organizations</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-406044"><span class="HTitleText3">Prohibitions Relating to Strikes</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-406120"><span class="HTitleText3">Declarations and Orders Relating to Strikes</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-406139"><span class="HTitleText3">Prohibition Relating to Essential Services</span></a>
</li>
<li><span class='sectionRange'>199.1 - </span><a href="#h-406144"><span class="HTitleText3">Prohibition Relating to Counselling</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-406149"><span class="HTitleText3">Offences and Punishment</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-406173"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-406174"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-406196"><span class="HTitleText2">Conflict Management</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-406199"><span class="HTitleText2">Individual Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>208 - </span><a href="#h-406200"><span class="HTitleText3">Presentation</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-406220"><span class="HTitleText3">Reference to Adjudication</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-406245"><span class="HTitleText3">Representation</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-406250"><span class="HTitleText3">Binding Effect</span></a>
</li></ul>
</li><li><span class='sectionRange'>215 - </span><a href="#h-406255"><span class="HTitleText2">Group Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>215 - </span><a href="#h-406256"><span class="HTitleText3">Presentation</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-406274"><span class="HTitleText3">Reference to Adjudication</span></a>
</li>
<li><span class='sectionRange'>217.1 - </span><a href="#h-406282"><span class="HTitleText3">Withdrawal from Group Grievance</span></a>
</li></ul>
</li><li><span class='sectionRange'>220 - </span><a href="#h-406287"><span class="HTitleText2">Policy Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-406288"><span class="HTitleText3">Presentation</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-406300"><span class="HTitleText3">Reference to Adjudication</span></a>
</li></ul>
</li><li><span class='sectionRange'>222.1 - </span><a href="#h-406308"><span class="HTitleText2">Adjudication</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>222.1 - </span><a href="#h-406309"><span class="HTitleText3">Notice to Board</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-406324"><span class="HTitleText3">Board of Adjudication</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-406330"><span class="HTitleText3">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-406335"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-406347"><span class="HTitleText3">Decision</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-406395"><span class="HTitleText3">Expenses of Adjudication</span></a>
</li></ul>
</li><li><span class='sectionRange'>236 - </span><a href="#h-406405"><span class="HTitleText2">No Right of Action</span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-406413"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>238.01 - </span><a href="#h-406434"><span class="HLabel1">PART 2.1</span> - <span class="HTitleText1">Provisions Unique to the Royal Canadian Mounted Police</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>238.01 - </span><a href="#h-406435"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>238.05 - </span><a href="#h-406462"><span class="HTitleText2">Unique Role as Police Organization</span></a>
</li>
<li><span class='sectionRange'>238.06 - </span><a href="#h-406467"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Labour Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>238.06 - </span><a href="#h-406468"><span class="HTitleText3">Adjournment of Proceedings</span></a>
</li>
<li><span class='sectionRange'>238.07 - </span><a href="#h-406476"><span class="HTitleText3">Law Enforcement, Public Safety and National Security</span></a>
</li>
<li><span class='sectionRange'>238.13 - </span><a href="#h-406535"><span class="HTitleText3">Certification of Bargaining Agents</span></a>
</li>
<li><span class='sectionRange'>238.17 - </span><a href="#h-406562"><span class="HTitleText3">Revocation of Certification</span></a>
</li>
<li><span class='sectionRange'>238.18 - </span><a href="#h-406572"><span class="HTitleText3">Process for Dispute Resolution</span></a>
</li>
<li><span class='sectionRange'>238.19 - </span><a href="#h-406577"><span class="HTitleText3">Restriction on Content of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>238.2 - </span><a href="#h-406584"><span class="HTitleText3">Essential Services, Conciliation and Strike Votes</span></a>
</li>
<li><span class='sectionRange'>238.21 - </span><a href="#h-406589"><span class="HTitleText3">Arbitration</span></a>
</li>
<li><span class='sectionRange'>238.23 - </span><a href="#h-406606"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>238.24 - </span><a href="#h-406613"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>238.24 - </span><a href="#h-406614"><span class="HTitleText3">Individual Grievances</span></a>
</li>
<li><span class='sectionRange'>238.26 - </span><a href="#h-406626"><span class="HTitleText3">Adjournment of Proceedings</span></a>
</li>
<li><span class='sectionRange'>238.27 - </span><a href="#h-406634"><span class="HTitleText3">Law Enforcement, Public Safety and National Security</span></a>
</li>
<li><span class='sectionRange'>238.33 - </span><a href="#h-406693"><span class="HTitleText3">Unique Role as Police Organization</span></a>
</li>
<li><span class='sectionRange'>238.34 - </span><a href="#h-406698"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="#h-406705"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Occupational Health and Safety</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-406706"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-406709"><span class="HTitleText2">Part II of Canada Labour Code</span></a>
</li></ul>
</li><li><span class='sectionRange'>241 - </span><a href="#h-406722"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>241 - </span><a href="#h-406723"><span class="HTitleText2">Defects in Proceedings</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-406729"><span class="HTitleText2">Restriction on Admissibility of Evidence</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="#h-406734"><span class="HTitleText2">Protection</span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="#h-406750"><span class="HTitleText2">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-406753"><span class="HTitleText2">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-406763"><span class="HTitleText2">Witness Fees</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-406768"><span class="HTitleText2">Provision of Facilities and Human Resources</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-406773"><span class="HTitleText2">Application of Safety or Security Provisions</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-406780"><span class="HTitleText2">Five-year Review</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

