<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Eeyou Marine Region Land Claims Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-176829"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-176832"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-176840"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-176843"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-176861"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-176864"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-176904"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

