<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi concernant le drapeau national du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-373514"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-373517"><span class="HTitleText1">Déploiement du drapeau national</span></a>
</li></ul>
</li></ul>

</nav>

