<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Referendum Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-426030"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-426033"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-426068"><span class="HTitleText1">Proclamation of Referendum</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-426103"><span class="HTitleText1">Writs of Referendum</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-426119"><span class="HTitleText1">Conduct of Referendum</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-426164"><span class="HTitleText1">Registration of Referendum Committees</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-426201"><span class="HTitleText1">Referendum Expenses and Contributions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-426238"><span class="HTitleText1">Agents and Auditors</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-426277"><span class="HTitleText1">Referendum Broadcasts</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-426352"><span class="HTitleText1">Recounts</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-426376"><span class="HTitleText1">Information Programs</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-426382"><span class="HTitleText1">Participation by Public Servants and Referendum Officers</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-426396"><span class="HTitleText1">Chief Electoral Officer’s Costs</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-426399"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-4.html#h-426446"><span class="HTitleText1">Review of Act</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-426452"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-5.html#h-426461"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Writ of Referendum</span></a>
</li>
<li><a href="page-6.html#h-426478"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li></ul>
</li></ul>

</nav>

