<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2001 pour la mise en oeuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-321043"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-321046"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Convention Canada — Slovénie en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-321062"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Convention Canada — Équateur en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-321078"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Convention Canada — Venezuela en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-321094"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Convention Canada — Pérou en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-321110"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Convention Canada — Sénégal en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-321126"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Convention Canada — République tchèque en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-321142"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Accord Canada — République slovaque en matière d’impôts sur le revenu</span></a>
</li>
<li><span class='sectionRange'>44 et 45 - </span><a href="#h-321158"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Accord Canada — Allemagne en matière d’impôts sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 et 45 - </span><a href="#h-321159"><span class="HTitleText2">Loi de 1982 sur l’Accord Canada–Allemagne en matière d’impôts</span></a>
</li></ul>
</li><li><a href="#h-321167"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement de la République de Slovénie en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-321435"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-321731"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-322018"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-322324"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement de la République du Sénégal en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="#h-322601"><span class="scheduleLabel">ANNEXE 6</span> <span class="scheduleTitleText"> - Convention entre le Canada et la République Tchèque en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="#h-322863"><span class="scheduleLabel">ANNEXE 7</span> <span class="scheduleTitleText"> - Accord entre le gouvernement du Canada et le gouvernement de la République Slovaque en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-323139"><span class="scheduleLabel">ANNEXE 8</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
