<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-232933"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-232938"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-232948"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Paiements de péréquation, de stabilisation et de droits successoraux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-1.html#h-232973"><span class="HTitleText2">Paiements de péréquation du revenu provincial</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-233044"><span class="HTitleText2">Paiements de stabilisation du revenu provincial</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-1.html#h-233062"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Paiements de rajustement pour l’enseignement post-secondaire</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-233196"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-2.html#h-233197"><span class="HTitleText2">Accords relatifs à la perception fiscale</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-233215"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

