<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Labour Adjustment Benefits Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-338478"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-338483"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-338507"><span class="HTitleText1">Designation of Industries</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-338543"><span class="HTitleText1">Labour Adjustment Review Board</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-338586"><span class="HTitleText1">Entitlement to Labour Adjustment Benefits</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-338591"><span class="HTitleText1">Certification by Board</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-338615"><span class="HTitleText1">Application to Commission</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-338637"><span class="HTitleText1">Qualification for Benefits</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-338680"><span class="HTitleText1">Labour Adjustment Benefits</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-338764"><span class="HTitleText1">Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-338840"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
