<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Cour suprême</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">La Cour</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Les juges</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-5"><span class="HTitleText1">Greffe et personnel de la Cour</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-6"><span class="HTitleText1">Avocats et procureurs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-7"><span class="HTitleText1">Sessions et quorum</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-8"><span class="HTitleText1">Juridiction d’appel</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-9"><span class="HTitleText1">Jugements</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-10"><span class="HTitleText1">Frais</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-11"><span class="HTitleText1">Amendements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-12"><span class="HTitleText1">Intérêt</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-13"><span class="HTitleText1">Certificat de jugement</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-14"><span class="HTitleText1">Caractère souverain</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-15"><span class="HTitleText1">Juridiction spéciale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-16"><span class="HTitleText2">Renvois par le gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-17"><span class="HTitleText2">Questions déférées par le Sénat ou les Communes</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-18"><span class="HTitleText2">Certiorari</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-19"><span class="HTitleText1">Procédure d’appel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-20"><span class="HTitleText2">L’appel</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-21"><span class="HTitleText2">Sursis d’exécution</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-22"><span class="HTitleText2">Désistement</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-23"><span class="HTitleText2">Cassation du jugement</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-24"><span class="HTitleText2">Rejet de l’appel pour retard</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-25"><span class="HTitleText2">Décès des parties</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-26"><span class="HTitleText1">Mise au rôle</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-27"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-28"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
