<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les conventions de Genève</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-241949"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-241954"><span class="HTitleText1">Approbation des conventions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-241964"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Infractions graves</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-241980"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Procédures judiciaires à l’égard de personnes protégées</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-242030"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Disposition générale</span></a>
</li>
<li><a href="page-2.html#h-242036"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="page-3.html#h-242375"><span class="scheduleLabel">ANNEXE II</span> </a>
</li>
<li><a href="page-4.html#h-242692"><span class="scheduleLabel">ANNEXE III</span> </a>
</li>
<li><a href="page-5.html#h-243505"><span class="scheduleLabel">ANNEXE IV</span> </a>
</li>
<li><a href="page-6.html#h-244318"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Protocole I</span> - <span class="scheduleTitleText"> - Protocole additionnel aux Conventions de Genève du 12 août 1949 relatif à la protection des victimes des conflits armés internationaux (Protocole I)</span></a>
</li>
<li><a href="page-7.html#h-245252"><span class="scheduleLabel">ANNEXE VI</span> <span class="scheduleTitleText"> - Protocole II</span> - <span class="scheduleTitleText"> - Protocole additionnel aux Conventions de Genève du 12 août 1949 relatif à la protection des victimes des conflits armés non internationaux (Protocole II)</span></a>
</li>
<li><a href="page-8.html#h-245417"><span class="scheduleLabel">ANNEXE VII</span> <span class="scheduleTitleText"> - Protocole III</span> - <span class="scheduleTitleText"> - Protocole additionnel aux Conventions de Genève du 12 août 1949 relatif à l’adoption d’un signe distinctif additionnel (Protocole III)</span></a>
</li></ul>
</li></ul>

</nav>

