<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord de libre-échange Canada — États-Unis</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-57617"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-57620"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-57633"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-57652"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Mise en oeuvre de l’accord</span></a>
</li>
<li><span class='sectionRange'>23 à 45 - </span><a href="#h-57683"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">[Abrogée, 1995, ch. 29, art. 18]</span></a>
</li>
<li><span class='sectionRange'>23 à 45 - </span><a href="#h-57684"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Modifications à la Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>46 à 148 - </span><a href="#h-57686"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Modifications connexes visant la mise en oeuvre de l’accord</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-57688"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Dispositions transitoires et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="#h-57689"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-57692"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-57699"><span class="scheduleLabel"><span class="wb-invisible">Note de bas de page </span><sup>*</sup>ANNEXE — PARTIE A</span></a>
</li>
<li><a href="#h-57701"><span class="scheduleLabel">ANNEXE — PARTIES B ET C</span></a>
</li></ul>
</li></ul>

</nav>

