<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Financial Administration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Alteration of Schedules</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Organization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">Treasury Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText3">Public Officers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText3">Responsibilities and Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Department of Finance</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Public Money</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Public Disbursements</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-11"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Public Debt</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-12"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Public Property</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-13"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Public Accounts</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-14"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Assignment of Crown Debts</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-15"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Assignment of Debts Due to the Crown Under Payment Bonds</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-16"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Civil Liability and Offences</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-17"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Crown Corporations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="#h-18"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-19"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-20"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">CORPORATE AFFAIRS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-21"><span class="HTitleText3">Accountability to Parliament</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-22"><span class="HTitleText3">Directives</span></a>
</li>
<li><span class='sectionRange'>89.2 - </span><a href="#h-23"><span class="HTitleText3">Implementation of World Trade Organization Agreement</span></a>
</li>
<li><span class='sectionRange'>89.3 - </span><a href="#h-24"><span class="HTitleText3">Implementation of Agreement on Internal Trade</span></a>
</li>
<li><span class='sectionRange'>89.4 - </span><a href="#h-25"><span class="HTitleText3">Implementation of Canada-Chile Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>89.5 - </span><a href="#h-26"><span class="HTitleText3">Implementation of Canada — Costa Rica Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-27"><span class="HTitleText3">Restricted Transactions</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-28"><span class="HTitleText3">Crown Agency Status</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-29"><span class="HTitleText3">Third Parties</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-30"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>104.1 - </span><a href="#h-31"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">DIRECTORS AND OFFICERS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104.1 - </span><a href="#h-32"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-33"><span class="HTitleText3">Appointment</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-34"><span class="HTitleText3">Resignation</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-35"><span class="HTitleText3">Remuneration</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-36"><span class="HTitleText3">Management</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-37"><span class="HTitleText3">By-laws</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-38"><span class="HTitleText3">Duties</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-39"><span class="HTitleText3">Indemnification</span></a>
</li></ul>
</li><li><span class='sectionRange'>120 - </span><a href="#h-40"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">FINANCIAL MANAGEMENT AND CONTROL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-41"><span class="HTitleText3">Definitions</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-42"><span class="HTitleText3">Financial Year</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-43"><span class="HTitleText3">Corporate Plans and Budgets</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-44"><span class="HTitleText3">Borrowing</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-45"><span class="HTitleText3">Bank Accounts</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-46"><span class="HTitleText3">Surpluses</span></a>
</li>
<li><span class='sectionRange'>130.1 - </span><a href="#h-47"><span class="HTitleText3">Dividends</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-48"><span class="HTitleText3">Financial Management</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-49"><span class="HTitleText3">Auditor’s Reports</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-50"><span class="HTitleText3">Auditors</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-51"><span class="HTitleText3">Special Examination</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-52"><span class="HTitleText3">Consultation with Auditor General</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-53"><span class="HTitleText3">Right to Information</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-54"><span class="HTitleText3">Policy</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-55"><span class="HTitleText3">Qualified Privilege</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-56"><span class="HTitleText3">Costs</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-57"><span class="HTitleText3">Audit Committee</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-58"><span class="HTitleText3">Reports</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-59"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">GENERAL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-60"><span class="HTitleText3">Commercially Detrimental Information</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-61"><span class="HTitleText3">Sanction</span></a>
</li></ul>
</li><li><span class='sectionRange'>154.1 - </span><a href="#h-62"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">IMPLEMENTATION OF THE NORTH AMERICAN FREE TRADE AGREEMENT</span></a>
</li></ul>
</li><li><span class='sectionRange'>155 - </span><a href="#h-63"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Miscellaneous</span></a>
</li>
<li><a href="#h-64"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-65"><span class="scheduleLabel">SCHEDULE I.1</span> </a>
</li>
<li><a href="#h-66"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="#h-67"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
