<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Oil and Gas Operations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-385220"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-385225"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-385269"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-385281"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-385294"><span class="HTitleText1">Chief Safety Officer and Chief Conservation Officer</span></a>
</li>
<li><span class='sectionRange'>3.2 - </span><a href="#h-385299"><span class="HTitleText1">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-385304"><span class="HTitleText1">Prohibition</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-385329"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="#h-385337"><span class="HTitleText1">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-385352"><span class="HTitleText1">Licences and Authorizations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-385353"><span class="HTitleText2">Operating Licences and Authorization for Work</span></a>
</li>
<li><span class='sectionRange'>5.011 - </span><a href="#h-385411"><span class="HTitleText2">Navigable Waters</span></a>
</li>
<li><span class='sectionRange'>5.02 - </span><a href="#h-385435"><span class="HTitleText2">Safety of Works and Activities</span></a>
</li>
<li><span class='sectionRange'>5.021 - </span><a href="#h-385440"><span class="HTitleText2">Spill-treating Agent</span></a>
</li>
<li><span class='sectionRange'>5.03 - </span><a href="#h-385445"><span class="HTitleText2">Financial Requirements</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="#h-385450"><span class="HTitleText2">Development Plan Approval</span></a>
</li>
<li><span class='sectionRange'>5.11 - </span><a href="#h-385500"><span class="HTitleText2">Declarations</span></a>
</li>
<li><span class='sectionRange'>5.12 - </span><a href="#h-385516"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>5.2 - </span><a href="#h-385538"><span class="HTitleText2">Benefits Plan Approval</span></a>
</li>
<li><span class='sectionRange'>5.3 - </span><a href="#h-385554"><span class="HTitleText2">Guidelines and Interpretation Notes</span></a>
</li>
<li><span class='sectionRange'>5.31 - </span><a href="#h-385564"><span class="HTitleText2">Jurisdiction and Powers of the Commission of the Canadian Energy Regulator</span></a>
</li>
<li><span class='sectionRange'>5.37 - </span><a href="#h-385615"><span class="HTitleText2">Documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>5.4 - </span><a href="#h-385623"><span class="HTitleText1">Oil and Gas Administration Advisory Council</span></a>
</li>
<li><span class='sectionRange'>5.5 - </span><a href="#h-385631"><span class="HTitleText1">Offshore Oil and Gas Training Standards Advisory Board</span></a>
</li>
<li><span class='sectionRange'>5.6 - </span><a href="#h-385639"><span class="HTitleText1">Extended Formation Flow Tests</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-385649"><span class="HTitleText1">Oil and Gas Committee</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-385650"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-385688"><span class="HTitleText2">Jurisdiction and Powers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-385709"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>13.01 - </span><a href="#h-385719"><span class="HLabel1">PART 0.1</span> - <span class="HTitleText1">Traffic, Tolls and Tariffs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13.01 - </span><a href="#h-385720"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>13.02 - </span><a href="#h-385731"><span class="HTitleText2">Powers of Commission</span></a>
</li>
<li><span class='sectionRange'>13.03 - </span><a href="#h-385736"><span class="HTitleText2">Filing of Tariff</span></a>
</li>
<li><span class='sectionRange'>13.05 - </span><a href="#h-385750"><span class="HTitleText2">Just and Reasonable Tolls</span></a>
</li>
<li><span class='sectionRange'>13.08 - </span><a href="#h-385765"><span class="HTitleText2">Disallowance of Tariff</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-385774"><span class="HTitleText2">Discrimination</span></a>
</li>
<li><span class='sectionRange'>13.13 - </span><a href="#h-385792"><span class="HTitleText2">Contracts Limiting Liabilities</span></a>
</li>
<li><span class='sectionRange'>13.14 - </span><a href="#h-385802"><span class="HTitleText2">Transmission of Oil or Gas</span></a>
</li>
<li><span class='sectionRange'>13.15 - </span><a href="#h-385815"><span class="HTitleText2">Transmission and Sale of Gas</span></a>
</li>
<li><span class='sectionRange'>13.17 - </span><a href="#h-385827"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-385834"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Regulation of Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-385835"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-385916"><span class="HTitleText2">Production Orders</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-385928"><span class="HTitleText2">Waste</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-385970"><span class="HTitleText2">Spills and Debris</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-386126"><span class="HTitleText2">Inquiries</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-386144"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Production Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-386145"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-386175"><span class="HTitleText2">Pooling</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-386231"><span class="HTitleText2">Unitization</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-386254"><span class="HTitleText2">Compulsory Unitization</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-386346"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>48.01 - </span><a href="#h-386359"><span class="HTitleText2">Straddling Resources — Inuvialuit Settlement Region</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48.01 - </span><a href="#h-386360"><span class="HTitleText3">Definitions</span></a>
</li>
<li><span class='sectionRange'>48.02 - </span><a href="#h-386369"><span class="HTitleText3">Determination</span></a>
</li>
<li><span class='sectionRange'>48.04 - </span><a href="#h-386381"><span class="HTitleText3">Exploitation of Straddling Resources</span></a>
</li></ul>
</li><li><span class='sectionRange'>48.1 - </span><a href="#h-386480"><span class="HTitleText2">Transboundary Pools or Fields</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48.1 - </span><a href="#h-386481"><span class="HTitleText3">Delineation</span></a>
</li>
<li><span class='sectionRange'>48.15 - </span><a href="#h-386520"><span class="HTitleText3">Agreements Relating to Development</span></a>
</li>
<li><span class='sectionRange'>48.27 - </span><a href="#h-386627"><span class="HTitleText3">Referral to Expert</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-386647"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Appeals and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-386648"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-386679"><span class="HTitleText2">Safety and Conservation Officers</span></a>
</li>
<li><span class='sectionRange'>58.2 - </span><a href="#h-386731"><span class="HTitleText2">Installation Manager</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-386744"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>71.01 - </span><a href="#h-386860"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>71.01 - </span><a href="#h-386861"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>71.03 - </span><a href="#h-386885"><span class="HTitleText3">Violations</span></a>
</li>
<li><span class='sectionRange'>71.07 - </span><a href="#h-386914"><span class="HTitleText3">Rules About Violations</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="#h-386939"><span class="HTitleText3">Reviews</span></a>
</li>
<li><span class='sectionRange'>71.7 - </span><a href="#h-386974"><span class="HTitleText3">Responsibility</span></a>
</li>
<li><span class='sectionRange'>71.9 - </span><a href="#h-386983"><span class="HTitleText3">Recovery of Penalties</span></a>
</li>
<li><span class='sectionRange'>72.01 - </span><a href="#h-386998"><span class="HTitleText3">General</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>72.1 - </span><a href="#h-387007"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-387012"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-387017"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-387023"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-387033"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Provisions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
