<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les sociétés d’assurances</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-251487"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-251490"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Définitions et application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-251491"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-251643"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-251773"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-251783"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-251827"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Constitution, prorogation et cessation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-251828"><span class="HTitleText2">Formalités constitutives</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-251929"><span class="HTitleText2">Prorogation</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-252006"><span class="HTitleText2">Cessation</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-252034"><span class="HTitleText2">Dénomination sociale</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-252100"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Organisation et fonctionnement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-252101"><span class="HTitleText2">Réunions</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-252130"><span class="HTitleText2">Fonctionnement initial</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-252236"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Structure du capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-252237"><span class="HTitleText2">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>83.01 - </span><a href="#h-252467"><span class="HTitleText2">Restrictions particulières aux actions de sociétés mutuelles</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-252551"><span class="HTitleText2">Titres secondaires</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-252559"><span class="HTitleText2">Certificats de valeurs mobilières et transferts</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-252952"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Administration de la société</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-252953"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Actionnaires et souscripteurs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-252954"><span class="HTitleText3">Lieu des assemblées</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-252964"><span class="HTitleText3">Convocation des assemblées</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-252976"><span class="HTitleText3">Dates de référence</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-253012"><span class="HTitleText3">Avis des assemblées</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-253084"><span class="HTitleText3">Propositions des actionnaires et des souscripteurs</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-253145"><span class="HTitleText3">Listes des actionnaires et des souscripteurs</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-253172"><span class="HTitleText3">Quorum</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-253190"><span class="HTitleText3">Vote</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-253231"><span class="HTitleText3">Résolution tenant lieu d’assemblée</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-253243"><span class="HTitleText3">Demande de convocation</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-253264"><span class="HTitleText3">Pouvoirs du tribunal</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-253289"><span class="HTitleText3">Conventions de vote</span></a>
</li></ul>
</li><li><span class='sectionRange'>164 - </span><a href="#h-253292"><span class="HLabel2">SECTION I.1</span> - <span class="HTitleText2">Procurations</span></a>
</li>
<li><span class='sectionRange'>164.08 - </span><a href="#h-253416"><span class="HLabel2">SECTION I.2</span> - <span class="HTitleText2">Restriction du droit de vote</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-253444"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Administrateurs et dirigeants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-253445"><span class="HTitleText3">Obligations</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-253503"><span class="HTitleText3">Administrateurs — Nombre et qualités</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-253550"><span class="HTitleText3">Administrateurs — Élection et fonctions</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-253628"><span class="HTitleText3">Élections incomplètes et vacances d’administrateurs</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-253729"><span class="HTitleText3">Réunions du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-253817"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-253852"><span class="HTitleText3">Comités du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-253897"><span class="HTitleText3">Mandat des administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-253934"><span class="HTitleText3">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-253992"><span class="HTitleText3">Responsabilité, exonération et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>224 - </span><a href="#h-254080"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Modifications de structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>224 - </span><a href="#h-254081"><span class="HTitleText3">Modifications — Lettres patentes</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-254093"><span class="HTitleText3">Mutualisation</span></a>
</li>
<li><span class='sectionRange'>236.1 - </span><a href="#h-254184"><span class="HTitleText3">Transformation en société avec actions ordinaires</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-254257"><span class="HTitleText3">Modifications — Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-254328"><span class="HTitleText3">Fusion</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-254490"><span class="HTitleText3">Ventes d’éléments d’actif et réassurance</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="#h-254558"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-254667"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Registres des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-254714"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Dénomination sociale et sceau</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-254724"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">[Abrogée, 1997, ch. 15, art. 230]</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-254725"><span class="HLabel2">SECTION VIII</span> - <span class="HTitleText2">Initiés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>288 - </span><a href="#h-254726"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="#h-254747"><span class="HTitleText3">Rapport d’initié</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="#h-254765"><span class="HTitleText3">Opérations d’initiés</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-254783"><span class="HTitleText3">Recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>296 - </span><a href="#h-254843"><span class="HLabel2">SECTION IX</span> - <span class="HTitleText2">Prospectus</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-254861"><span class="HLabel2">SECTION IX.1</span> - <span class="HTitleText2">Transactions de fermeture et transactions d’éviction</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-254944"><span class="HLabel2">SECTION X</span> - <span class="HTitleText2">Offres publiques d’achat</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="#h-255068"><span class="HLabel2">SECTION XI</span> - <span class="HTitleText2">Acte de fiducie</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="#h-255148"><span class="HLabel2">SECTION XII</span> - <span class="HTitleText2">Rapports financiers</span></a>
</li>
<li><span class='sectionRange'>336 - </span><a href="#h-255220"><span class="HLabel2">SECTION XIII</span> - <span class="HTitleText2">Vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="#h-255221"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-255228"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="#h-255234"><span class="HTitleText3">Conditions</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-255267"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="#h-255318"><span class="HTitleText3">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>356 - </span><a href="#h-255405"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>357 - </span><a href="#h-255408"><span class="HLabel2">SECTION XIV</span> - <span class="HTitleText2">Actuaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>357 - </span><a href="#h-255409"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="#h-255431"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>365 - </span><a href="#h-255459"><span class="HTitleText3">Évaluations et rapports</span></a>
</li>
<li><span class='sectionRange'>370 - </span><a href="#h-255495"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>371 - </span><a href="#h-255501"><span class="HLabel2">SECTION XV</span> - <span class="HTitleText2">Recours judiciaires</span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="#h-255546"><span class="HLabel2">SECTION XVI</span> - <span class="HTitleText2">Liquidation et dissolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="#h-255547"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="#h-255550"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="#h-255564"><span class="HTitleText3">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>385 - </span><a href="#h-255602"><span class="HTitleText3">Surveillance judiciaire</span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="#h-255732"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>406.1 - </span><a href="#h-255772"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>406.1 - </span><a href="#h-255773"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>407 - </span><a href="#h-255803"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Restrictions à la propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>419 - </span><a href="#h-256064"><span class="HTitleText3">Procédure d’agrément</span></a>
</li></ul>
</li><li><span class='sectionRange'>432 - </span><a href="#h-256184"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Arrêtés et ordonnances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>434 - </span><a href="#h-256204"><span class="HTitleText3">Dispositions d’ordre général</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>440 - </span><a href="#h-256228"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Activité et pouvoirs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>440 - </span><a href="#h-256229"><span class="HTitleText2">Activités générales</span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="#h-256286"><span class="HTitleText2">Branches d’assurance</span></a>
</li>
<li><span class='sectionRange'>450 - </span><a href="#h-256323"><span class="HTitleText2">Caisses séparées</span></a>
</li>
<li><span class='sectionRange'>456 - </span><a href="#h-256346"><span class="HTitleText2">Polices à participation</span></a>
</li>
<li><span class='sectionRange'>464.1 - </span><a href="#h-256405"><span class="HTitleText2">Polices ajustables</span></a>
</li>
<li><span class='sectionRange'>465 - </span><a href="#h-256417"><span class="HTitleText2">Réassurance</span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="#h-256425"><span class="HTitleText2">Restrictions</span></a>
</li>
<li><span class='sectionRange'>473 - </span><a href="#h-256502"><span class="HTitleText2">Restrictions particulières aux sociétés d’assurance-vie</span></a>
</li>
<li><span class='sectionRange'>476 - </span><a href="#h-256522"><span class="HTitleText2">Restrictions particulières aux sociétés d’assurances multirisques et aux sociétés d’assurance maritime</span></a>
</li>
<li><span class='sectionRange'>479 - </span><a href="#h-256538"><span class="HTitleText2">Coût d’emprunt</span></a>
</li>
<li><span class='sectionRange'>486 - </span><a href="#h-256625"><span class="HTitleText2">Réclamations</span></a>
</li>
<li><span class='sectionRange'>488 - </span><a href="#h-256652"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>490 - </span><a href="#h-256712"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>490 - </span><a href="#h-256713"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>492 - </span><a href="#h-256791"><span class="HTitleText2">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>495 - </span><a href="#h-256854"><span class="HTitleText2">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>498 - </span><a href="#h-257025"><span class="HTitleText2">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-257087"><span class="HTitleText2">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-257101"><span class="HTitleText2">Prêts commerciaux : sociétés d’assurance-vie</span></a>
</li>
<li><span class='sectionRange'>505 - </span><a href="#h-257110"><span class="HTitleText2">Prêts commerciaux et à la consommation : sociétés d’assurances multirisques et sociétés d’assurance maritime</span></a>
</li>
<li><span class='sectionRange'>506 - </span><a href="#h-257115"><span class="HTitleText2">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>507 - </span><a href="#h-257120"><span class="HTitleText2">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>508 - </span><a href="#h-257127"><span class="HTitleText2">Limite globale</span></a>
</li>
<li><span class='sectionRange'>509 - </span><a href="#h-257137"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>515 - </span><a href="#h-257207"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Capital et liquidités</span></a>
</li>
<li><span class='sectionRange'>517.1 - </span><a href="#h-257222"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Opérations avec apparentés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>517.1 - </span><a href="#h-257223"><span class="HTitleText2">Interprétation et application</span></a>
</li>
<li><span class='sectionRange'>521 - </span><a href="#h-257310"><span class="HTitleText2">Opérations interdites</span></a>
</li>
<li><span class='sectionRange'>522 - </span><a href="#h-257320"><span class="HTitleText2">Opérations permises</span></a>
</li>
<li><span class='sectionRange'>534 - </span><a href="#h-257489"><span class="HTitleText2">Restrictions applicables aux opérations permises</span></a>
</li>
<li><span class='sectionRange'>537 - </span><a href="#h-257502"><span class="HTitleText2">Obligation d’information</span></a>
</li>
<li><span class='sectionRange'>539 - </span><a href="#h-257512"><span class="HTitleText2">Recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>540 - </span><a href="#h-257522"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Sociétés de secours mutuel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>540 - </span><a href="#h-257523"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>541 - </span><a href="#h-257540"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>543 - </span><a href="#h-257678"><span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>550 - </span><a href="#h-257741"><span class="HTitleText2">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>550 - </span><a href="#h-257742"><span class="HTitleText3">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>551 - </span><a href="#h-257750"><span class="HTitleText3">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>554 - </span><a href="#h-257808"><span class="HTitleText3">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>557 - </span><a href="#h-257885"><span class="HTitleText3">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>561 - </span><a href="#h-257940"><span class="HTitleText3">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>562 - </span><a href="#h-257950"><span class="HTitleText3">Prêts commerciaux et à la consommation</span></a>
</li>
<li><span class='sectionRange'>563 - </span><a href="#h-257957"><span class="HTitleText3">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>565 - </span><a href="#h-257969"><span class="HTitleText3">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>566 - </span><a href="#h-257976"><span class="HTitleText3">Limite globale</span></a>
</li>
<li><span class='sectionRange'>567 - </span><a href="#h-257986"><span class="HTitleText3">Divers</span></a>
</li>
<li><span class='sectionRange'>570 - </span><a href="#h-258027"><span class="HTitleText3">Non-interdiction</span></a>
</li></ul>
</li><li><span class='sectionRange'>570.01 - </span><a href="#h-258034"><span class="HTitleText2">Liquidation et dissolution d’une société de secours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>570.01 - </span><a href="#h-258035"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>570.02 - </span><a href="#h-258040"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>570.03 - </span><a href="#h-258048"><span class="HTitleText3">Obligation de fournir des renseignements</span></a>
</li>
<li><span class='sectionRange'>570.04 - </span><a href="#h-258053"><span class="HTitleText3">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>570.09 - </span><a href="#h-258098"><span class="HTitleText3">Surveillance judiciaire</span></a>
</li>
<li><span class='sectionRange'>570.23 - </span><a href="#h-258249"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>571 - </span><a href="#h-258305"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Sociétés d’assurances étrangères</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>571 - </span><a href="#h-258306"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>572 - </span><a href="#h-258321"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>573 - </span><a href="#h-258330"><span class="HTitleText2">Garantie de risques</span></a>
</li>
<li><span class='sectionRange'>588 - </span><a href="#h-258503"><span class="HTitleText2">Branches d’assurance</span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-258535"><span class="HTitleText2">Caisses séparées</span></a>
</li>
<li><span class='sectionRange'>596 - </span><a href="#h-258550"><span class="HTitleText2">Réassurance</span></a>
</li>
<li><span class='sectionRange'>598 - </span><a href="#h-258567"><span class="HTitleText2">Coût d’emprunt</span></a>
</li>
<li><span class='sectionRange'>604 - </span><a href="#h-258654"><span class="HTitleText2">Réclamations</span></a>
</li>
<li><span class='sectionRange'>606 - </span><a href="#h-258681"><span class="HTitleText2">Divers</span></a>
</li>
<li><span class='sectionRange'>608 - </span><a href="#h-258726"><span class="HTitleText2">Actif suffisant</span></a>
</li>
<li><span class='sectionRange'>613 - </span><a href="#h-258795"><span class="HTitleText2">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>613 - </span><a href="#h-258796"><span class="HTitleText3">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>615 - </span><a href="#h-258806"><span class="HTitleText3">Restrictions générales</span></a>
</li>
<li><span class='sectionRange'>616 - </span><a href="#h-258812"><span class="HTitleText3">Prêts commerciaux par les sociétés d’assurance-vie étrangères</span></a>
</li>
<li><span class='sectionRange'>617 - </span><a href="#h-258820"><span class="HTitleText3">Prêts commerciaux et à la consommation par les sociétés d’assurances multirisques étrangères et les sociétés d’assurance maritime étrangères</span></a>
</li>
<li><span class='sectionRange'>618 - </span><a href="#h-258825"><span class="HTitleText3">Biens immeubles</span></a>
</li>
<li><span class='sectionRange'>619 - </span><a href="#h-258835"><span class="HTitleText3">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>620 - </span><a href="#h-258845"><span class="HTitleText3">Limite globale</span></a>
</li></ul>
</li><li><span class='sectionRange'>621 - </span><a href="#h-258851"><span class="HTitleText2">Opérations avec apparentés</span></a>
</li>
<li><span class='sectionRange'>623 - </span><a href="#h-258860"><span class="HTitleText2">Actuaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>623 - </span><a href="#h-258861"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>625 - </span><a href="#h-258877"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>628 - </span><a href="#h-258905"><span class="HTitleText3">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>632 - </span><a href="#h-258938"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>632.1 - </span><a href="#h-258944"><span class="HTitleText2">Vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>632.1 - </span><a href="#h-258945"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>633 - </span><a href="#h-258950"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>634 - </span><a href="#h-258956"><span class="HTitleText3">Conditions</span></a>
</li>
<li><span class='sectionRange'>636 - </span><a href="#h-258989"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>641 - </span><a href="#h-259023"><span class="HTitleText3">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>646 - </span><a href="#h-259070"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>647 - </span><a href="#h-259073"><span class="HTitleText2">Livres</span></a>
</li>
<li><span class='sectionRange'>650 - </span><a href="#h-259090"><span class="HTitleText2">Libération de l’actif</span></a>
</li></ul>
</li><li><span class='sectionRange'>656 - </span><a href="#h-259119"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Sociétés provinciales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>656 - </span><a href="#h-259120"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>657 - </span><a href="#h-259128"><span class="HTitleText2">Autorisation de fonctionnement</span></a>
</li>
<li><span class='sectionRange'>660 - </span><a href="#h-259149"><span class="HTitleText2">Obligations des administrateurs</span></a>
</li>
<li><span class='sectionRange'>661 - </span><a href="#h-259170"><span class="HTitleText2">Livres et registres</span></a>
</li></ul>
</li><li><span class='sectionRange'>663 - </span><a href="#h-259195"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Réglementation des sociétés, sociétés de secours, sociétés étrangères et sociétés provinciales : surintendant</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>663 - </span><a href="#h-259196"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>664 - </span><a href="#h-259199"><span class="HTitleText2">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>664 - </span><a href="#h-259200"><span class="HTitleText3">États</span></a>
</li>
<li><span class='sectionRange'>674 - </span><a href="#h-259340"><span class="HTitleText3">Enquête sur les sociétés</span></a>
</li></ul>
</li><li><span class='sectionRange'>675.1 - </span><a href="#h-259356"><span class="HTitleText2">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>675.1 - </span><a href="#h-259357"><span class="HTitleText3">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>676 - </span><a href="#h-259362"><span class="HTitleText3">Décisions</span></a>
</li>
<li><span class='sectionRange'>678.01 - </span><a href="#h-259382"><span class="HTitleText3">Rejet des candidatures et destitution</span></a>
</li>
<li><span class='sectionRange'>678.5 - </span><a href="#h-259491"><span class="HTitleText3">Surveillance et intervention</span></a>
</li>
<li><span class='sectionRange'>686 - </span><a href="#h-259567"><span class="HTitleText3">Cotisations particulières des sociétés</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>693 - </span><a href="#h-259622"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Réglementation des sociétés et sociétés étrangères : commissaire</span></a>
</li>
<li><span class='sectionRange'>699 - </span><a href="#h-259659"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Sociétés de portefeuille d’assurances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>699 - </span><a href="#h-259660"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>700 - </span><a href="#h-259666"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>701 - </span><a href="#h-259682"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>708 - </span><a href="#h-259733"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Constitution, prorogation et cessation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>708 - </span><a href="#h-259734"><span class="HTitleText3">Formalités constitutives</span></a>
</li>
<li><span class='sectionRange'>719 - </span><a href="#h-259822"><span class="HTitleText3">Prorogation</span></a>
</li>
<li><span class='sectionRange'>726 - </span><a href="#h-259889"><span class="HTitleText3">Cessation</span></a>
</li>
<li><span class='sectionRange'>730 - </span><a href="#h-259914"><span class="HTitleText3">Dénomination sociale</span></a>
</li>
<li><span class='sectionRange'>738 - </span><a href="#h-259977"><span class="HTitleText3">Publication de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>739 - </span><a href="#h-259984"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Organisation et fonctionnement</span></a>
</li>
<li><span class='sectionRange'>742 - </span><a href="#h-260013"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Structure du capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>742 - </span><a href="#h-260014"><span class="HTitleText3">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>762 - </span><a href="#h-260238"><span class="HTitleText3">Titres secondaires</span></a>
</li>
<li><span class='sectionRange'>763 - </span><a href="#h-260248"><span class="HTitleText3">Certificats de valeurs mobilières et transferts</span></a>
</li></ul>
</li><li><span class='sectionRange'>764 - </span><a href="#h-260260"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Administration de la société de portefeuille d’assurances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>764 - </span><a href="#h-260261"><span class="HLabel3">SOUS-SECTION 1</span> - <span class="HTitleText3">Actionnaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>764 - </span><a href="#h-260262"><span class="HTitleText4">Lieu des assemblées</span></a>
</li>
<li><span class='sectionRange'>765 - </span><a href="#h-260272"><span class="HTitleText4">Convocation des assemblées</span></a>
</li>
<li><span class='sectionRange'>766 - </span><a href="#h-260284"><span class="HTitleText4">Dates de référence</span></a>
</li>
<li><span class='sectionRange'>767 - </span><a href="#h-260304"><span class="HTitleText4">Avis des assemblées</span></a>
</li>
<li><span class='sectionRange'>770 - </span><a href="#h-260348"><span class="HTitleText4">Propositions des actionnaires</span></a>
</li>
<li><span class='sectionRange'>772 - </span><a href="#h-260399"><span class="HTitleText4">Liste des actionnaires</span></a>
</li>
<li><span class='sectionRange'>773 - </span><a href="#h-260417"><span class="HTitleText4">Quorum</span></a>
</li>
<li><span class='sectionRange'>775 - </span><a href="#h-260431"><span class="HTitleText4">Vote</span></a>
</li>
<li><span class='sectionRange'>779 - </span><a href="#h-260460"><span class="HTitleText4">Résolution tenant lieu d’assemblée</span></a>
</li>
<li><span class='sectionRange'>780 - </span><a href="#h-260472"><span class="HTitleText4">Demande de convocation</span></a>
</li>
<li><span class='sectionRange'>781 - </span><a href="#h-260491"><span class="HTitleText4">Pouvoirs du tribunal</span></a>
</li>
<li><span class='sectionRange'>784 - </span><a href="#h-260520"><span class="HTitleText4">Conventions de vote</span></a>
</li></ul>
</li><li><span class='sectionRange'>785 - </span><a href="#h-260525"><span class="HLabel3">SOUS-SECTION 2</span> - <span class="HTitleText3">Procurations et restriction du droit de vote</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>785 - </span><a href="#h-260526"><span class="HTitleText4">Procurations</span></a>
</li>
<li><span class='sectionRange'>793 - </span><a href="#h-260646"><span class="HTitleText4">Restriction du droit de vote</span></a>
</li></ul>
</li><li><span class='sectionRange'>794 - </span><a href="#h-260670"><span class="HLabel3">SOUS-SECTION 3</span> - <span class="HTitleText3">Administrateurs et dirigeants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>794 - </span><a href="#h-260671"><span class="HTitleText4">Obligations</span></a>
</li>
<li><span class='sectionRange'>796 - </span><a href="#h-260698"><span class="HTitleText4">Administrateurs — nombre et qualités</span></a>
</li>
<li><span class='sectionRange'>800 - </span><a href="#h-260728"><span class="HTitleText4">Administrateurs — élection et fonctions</span></a>
</li>
<li><span class='sectionRange'>805 - </span><a href="#h-260796"><span class="HTitleText4">Élections incomplètes et vacances d’administrateurs</span></a>
</li>
<li><span class='sectionRange'>816 - </span><a href="#h-260890"><span class="HTitleText4">Réunions du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>825 - </span><a href="#h-260977"><span class="HTitleText4">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>828 - </span><a href="#h-261000"><span class="HTitleText4">Comités du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>830 - </span><a href="#h-261025"><span class="HTitleText4">Mandat des administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>836 - </span><a href="#h-261070"><span class="HTitleText4">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>841 - </span><a href="#h-261128"><span class="HTitleText4">Responsabilité, exonération et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>849 - </span><a href="#h-261219"><span class="HLabel3">SOUS-SECTION 4</span> - <span class="HTitleText3">Modifications de structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>849 - </span><a href="#h-261220"><span class="HTitleText4">Modifications — lettres patentes</span></a>
</li>
<li><span class='sectionRange'>851 - </span><a href="#h-261232"><span class="HTitleText4">Modifications — règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>857 - </span><a href="#h-261292"><span class="HTitleText4">Fusion</span></a>
</li>
<li><span class='sectionRange'>867 - </span><a href="#h-261430"><span class="HTitleText4">Ventes d’éléments d’actif</span></a>
</li></ul>
</li><li><span class='sectionRange'>868 - </span><a href="#h-261448"><span class="HLabel3">SOUS-SECTION 5</span> - <span class="HTitleText3">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>879 - </span><a href="#h-261562"><span class="HLabel3">SOUS-SECTION 6</span> - <span class="HTitleText3">Registres des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>880 - </span><a href="#h-261570"><span class="HLabel3">SOUS-SECTION 7</span> - <span class="HTitleText3">Dénomination sociale et sceau</span></a>
</li>
<li><span class='sectionRange'>882 - </span><a href="#h-261582"><span class="HLabel3">SOUS-SECTION 8</span> - <span class="HTitleText3">Initiés</span></a>
</li>
<li><span class='sectionRange'>883 - </span><a href="#h-261590"><span class="HLabel3">SOUS-SECTION 9</span> - <span class="HTitleText3">Prospectus</span></a>
</li>
<li><span class='sectionRange'>883.1 - </span><a href="#h-261595"><span class="HLabel3">SOUS-SECTION 9.1</span> - <span class="HTitleText3">Transactions de fermeture et transactions d’éviction</span></a>
</li>
<li><span class='sectionRange'>884 - </span><a href="#h-261605"><span class="HLabel3">SOUS-SECTION 10</span> - <span class="HTitleText3">Offres publiques d’achat</span></a>
</li>
<li><span class='sectionRange'>885 - </span><a href="#h-261612"><span class="HLabel3">SOUS-SECTION 11</span> - <span class="HTitleText3">Acte de fiducie</span></a>
</li>
<li><span class='sectionRange'>886 - </span><a href="#h-261621"><span class="HLabel3">SOUS-SECTION 12</span> - <span class="HTitleText3">Rapports financiers</span></a>
</li>
<li><span class='sectionRange'>892 - </span><a href="#h-261692"><span class="HLabel3">SOUS-SECTION 13</span> - <span class="HTitleText3">Vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>892 - </span><a href="#h-261693"><span class="HTitleText4">Définitions</span></a>
</li>
<li><span class='sectionRange'>893 - </span><a href="#h-261702"><span class="HTitleText4">Nomination</span></a>
</li>
<li><span class='sectionRange'>894 - </span><a href="#h-261710"><span class="HTitleText4">Conditions</span></a>
</li>
<li><span class='sectionRange'>896 - </span><a href="#h-261744"><span class="HTitleText4">Vacances</span></a>
</li>
<li><span class='sectionRange'>902 - </span><a href="#h-261804"><span class="HTitleText4">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>911 - </span><a href="#h-261887"><span class="HTitleText4">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>912 - </span><a href="#h-261892"><span class="HLabel3">SOUS-SECTION 14</span> - <span class="HTitleText3">Recours judiciaires</span></a>
</li>
<li><span class='sectionRange'>917 - </span><a href="#h-261943"><span class="HLabel3">SOUS-SECTION 15</span> - <span class="HTitleText3">Liquidation et dissolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>917 - </span><a href="#h-261944"><span class="HTitleText4">Définition</span></a>
</li>
<li><span class='sectionRange'>918 - </span><a href="#h-261949"><span class="HTitleText4">Application</span></a>
</li>
<li><span class='sectionRange'>920 - </span><a href="#h-261963"><span class="HTitleText4">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>925 - </span><a href="#h-262008"><span class="HTitleText4">Surveillance judiciaire</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>926 - </span><a href="#h-262019"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Propriété</span></a>
</li>
<li><span class='sectionRange'>963 - </span><a href="#h-262369"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Activité commerciale et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>966 - </span><a href="#h-262398"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>966 - </span><a href="#h-262399"><span class="HTitleText3">Interprétation</span></a>
</li>
<li><span class='sectionRange'>967 - </span><a href="#h-262417"><span class="HTitleText3">Placements</span></a>
</li>
<li><span class='sectionRange'>968 - </span><a href="#h-262422"><span class="HTitleText3">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>971 - </span><a href="#h-262483"><span class="HTitleText3">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>974 - </span><a href="#h-262623"><span class="HTitleText3">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>978 - </span><a href="#h-262674"><span class="HTitleText3">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>979 - </span><a href="#h-262688"><span class="HTitleText3">Prêts commerciaux</span></a>
</li>
<li><span class='sectionRange'>981 - </span><a href="#h-262697"><span class="HTitleText3">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>982 - </span><a href="#h-262702"><span class="HTitleText3">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>983 - </span><a href="#h-262709"><span class="HTitleText3">Limite globale</span></a>
</li>
<li><span class='sectionRange'>984 - </span><a href="#h-262719"><span class="HTitleText3">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>992 - </span><a href="#h-262818"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Capital et liquidités</span></a>
</li>
<li><span class='sectionRange'>993 - </span><a href="#h-262830"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2">Réglementation des sociétés de portefeuille d’assurances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>993 - </span><a href="#h-262831"><span class="HTitleText3">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>993 - </span><a href="#h-262832"><span class="HTitleText4">États</span></a>
</li>
<li><span class='sectionRange'>1000 - </span><a href="#h-262920"><span class="HTitleText4">Enquête sur les sociétés de portefeuille d’assurances</span></a>
</li></ul>
</li><li><span class='sectionRange'>1002 - </span><a href="#h-262934"><span class="HTitleText3">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1002 - </span><a href="#h-262935"><span class="HTitleText4">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>1003 - </span><a href="#h-262940"><span class="HTitleText4">Décisions</span></a>
</li>
<li><span class='sectionRange'>1005 - </span><a href="#h-262963"><span class="HTitleText4">Rejet des candidatures et destitution</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1007.1 - </span><a href="#h-263024"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1007.1 - </span><a href="#h-263025"><span class="HTitleText2">Avis et autres documents</span></a>
</li>
<li><span class='sectionRange'>1016 - </span><a href="#h-263089"><span class="HTitleText2">Agréments</span></a>
</li>
<li><span class='sectionRange'>1016.61 - </span><a href="#h-263148"><span class="HTitleText2">Exception aux principes comptables généralement reconnus</span></a>
</li>
<li><span class='sectionRange'>1016.7 - </span><a href="#h-263158"><span class="HTitleText2">Exemption ou adaptation par décret</span></a>
</li>
<li><span class='sectionRange'>1017 - </span><a href="#h-263206"><span class="HTitleText2">Arrêts, ordonnances et décisions</span></a>
</li>
<li><span class='sectionRange'>1019 - </span><a href="#h-263215"><span class="HTitleText2">Demandes au surintendant</span></a>
</li>
<li><span class='sectionRange'>1019.1 - </span><a href="#h-263235"><span class="HTitleText2">Demandes relatives à certains agréments</span></a>
</li>
<li><span class='sectionRange'>1020 - </span><a href="#h-263258"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>1021 - </span><a href="#h-263271"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>1022 - </span><a href="#h-263294"><span class="HTitleText2">Délégation</span></a>
</li></ul>
</li><li><span class='sectionRange'>1023 - </span><a href="#h-263299"><span class="HLabel1">PARTIE XIX</span> - <span class="HTitleText1">Peines</span></a>
</li>
<li><span class='sectionRange'>1034 - </span><a href="#h-263373"><span class="HLabel1">PARTIE XX</span> - <span class="HTitleText1">Documents sous forme électronique ou autre</span></a>
</li>
<li><a href="#h-263463"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Branches d’assurance</span></a>
</li></ul>
</li></ul>

</nav>

