<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Service canadien d’appui aux tribunaux administratifs</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-89"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-92"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-99"><span class="HTitleText1">Service canadien d’appui aux tribunaux administratifs</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-107"><span class="HTitleText1">Administrateur en chef</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-138"><span class="HTitleText1">Présidents des tribunaux administratifs</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-141"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-144"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-152"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Tribunaux administratifs</span></a>
</li></ul>
</li></ul>

</nav>

