<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Standards Council of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-439829"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-439834"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-439841"><span class="HTitleText1">Council Established</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-439850"><span class="HTitleText1">Mandate and Powers</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-439901"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-439956"><span class="HTitleText1">Staff</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-439989"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-439998"><span class="HTitleText1">Provincial-territorial Advisory Committee</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-440008"><span class="HTitleText1">Standards Development Organizations Advisory Committee</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-440018"><span class="HTitleText1">Meetings</span></a>
</li></ul>
</li></ul>

</nav>

