<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la pension de retraite des Forces canadiennes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-68435"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-68440"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-68479"><span class="HTitleText1">Égalité de statut</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="page-1.html#h-68484"><span class="HTitleText1">Application à certains membres de la force de réserve</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-68494"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Pension de retraite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-68495"><span class="HTitleText2">Admissibilité aux prestations</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-68503"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-68523"><span class="HTitleText2">Service ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-68563"><span class="HTitleText2">Service ouvrant droit à pension et accompagné d’option : montant exigible</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-68604"><span class="HTitleText2">Options</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-68640"><span class="HTitleText2">Prestations : définitions et autres dispositions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-3.html#h-68673"><span class="HTitleText2">Mode de calcul des annuités</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-68716"><span class="HTitleText2">Prestations à payer aux contributeurs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-4.html#h-68794"><span class="HTitleText2">Prestations à payer aux survivants, aux enfants et à d’autres bénéficiaires</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-68896"><span class="HTitleText2">Prestations minimales</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-68927"><span class="HTitleText2">Cas spéciaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-5.html#h-68928"><span class="HTitleText3">Anciens membres de la force régulière</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-5.html#h-68944"><span class="HTitleText3">Membres de la force régulière enrôlés pour une période de service déterminée</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-6.html#h-68996"><span class="HTitleText3">Anciens employés de la fonction publique et membres de la Gendarmerie royale du Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="page-6.html#h-69045"><span class="HTitleText2">Conseil des pensions militaires</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="page-6.html#h-69059"><span class="HTitleText2">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-6.html#h-69081"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-7.html#h-69121"><span class="HTitleText2">Paiements sur le compte de pension de retraite</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-69131"><span class="HTitleText2">Montants</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="page-7.html#h-69158"><span class="HTitleText2">Fonds de placement du compte de pension de retraite des Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>55.2 - </span><a href="page-7.html#h-69172"><span class="HTitleText2">Caisse de retraite des Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-8.html#h-69231"><span class="HTitleText2">Rapport actuariel</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-8.html#h-69236"><span class="HTitleText2">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-8.html#h-69241"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-8.html#h-69246"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>59.1 - </span><a href="page-8.html#h-69254"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Régime de pension de la force de réserve</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-8.html#h-69289"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Prestations de décès supplémentaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="page-8.html#h-69290"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-9.html#h-69353"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-9.html#h-69358"><span class="HTitleText2">Prestations</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-9.html#h-69396"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="page-9.html#h-69436"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Prestations supplémentaires</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-10.html#h-69494"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="page-11.html#h-69604"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

