<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les conflits d’intérêts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-89876"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-89879"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-89933"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-89941"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Règles régissant les conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-90020"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Mesures d’observation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-2.html#h-90021"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-90048"><span class="HTitleText2">Récusation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-90051"><span class="HTitleText2">Communication confidentielle</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-90084"><span class="HTitleText2">Déclaration publique</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-90106"><span class="HTitleText2">Dessaisissement</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-90144"><span class="HTitleText2">Fonctions du commissaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="page-3.html#h-90169"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">L’après-mandat</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="page-3.html#h-90170"><span class="HTitleText2">Règles régissant tous les ex-titulaires de charge publique</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-90178"><span class="HTitleText2">Règles régissant les ex-titulaires de charge publique principaux</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-90213"><span class="HTitleText2">Fonctions du commissaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="page-3.html#h-90243"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Administration et application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="page-3.html#h-90244"><span class="HTitleText2">Mission et pouvoirs du commissaire</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-4.html#h-90308"><span class="HTitleText2">Registre public</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-4.html#h-90331"><span class="HTitleText2">Pénalités</span></a>
</li></ul>
</li><li><span class='sectionRange'>62.1 - </span><a href="page-4.html#h-90382"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Généralités</span></a>
</li></ul>
</li></ul>

</nav>

