<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Environmental Assessment Act, 2012</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Purposes</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Environmental Effects</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">Screening</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText1">Environmental Assessment Required</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText1">Environmental Assessment of Designated Projects</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Responsible Authority</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText2">Commencement of Environmental Assessment</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText2">Consultation and Cooperation with Certain Jurisdictions</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-13"><span class="HTitleText2">Factors To Be Considered</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText2">Federal Authority’s Obligation</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-15"><span class="HTitleText2">Environmental Assessment by Responsible Authority</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-16"><span class="HTitleText3">General Rules</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText3">Section 54 of the <cite class="XRefExternalAct">National Energy Board Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText3">Substitution</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-19"><span class="HTitleText3">Equivalent Assessment</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-20"><span class="HTitleText2">Environmental Assessment by a Review Panel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-21"><span class="HTitleText3">General Rules</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-22"><span class="HTitleText3">Rules in Case of Termination</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-23"><span class="HTitleText2">Decision Making</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-24"><span class="HTitleText2">Decision Statement</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-25"><span class="HTitleText2">Participant Funding Programs</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-26"><span class="HTitleText2">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-27"><span class="HTitleText2">Termination of Environmental Assessment</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-28"><span class="HTitleText2">Confidential Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="#h-29"><span class="HTitleText1">Duties of Certain Authorities in Relation to Projects</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-30"><span class="HTitleText1">Regional Studies</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-31"><span class="HTitleText1">Canadian Environmental Assessment Registry</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-32"><span class="HTitleText2">Establishment of Registry</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-33"><span class="HTitleText2">Internet Site</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-34"><span class="HTitleText2">Project Files</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-35"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-36"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-37"><span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-38"><span class="HTitleText2">Designation</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-39"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-40"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-41"><span class="HTitleText2">Injunctions</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-42"><span class="HTitleText2">Prohibitions and Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-43"><span class="HTitleText1">Canadian Environmental Assessment Agency</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-44"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-45"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><a href="#h-46"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Federal Authorities</span></a>
</li>
<li><a href="#h-47"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Components of the Environment</span></a>
</li>
<li><a href="#h-48"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Bodies</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
