<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les ressources en eau du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-59789"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-59794"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-59821"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-59826"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Gestion intégrale des ressources en eau</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-59827"><span class="HTitleText2">Arrangements fédéro-provinciaux</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-59835"><span class="HTitleText2">Programmes de gestion intégrale des ressources en eau</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-59884"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Gestion qualitative des eaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-59885"><span class="HTitleText2">Pollution des eaux</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-59894"><span class="HTitleText2">Accords fédéro-provinciaux pour la gestion qualitative des eaux</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-59927"><span class="HTitleText2">Gestion qualitative des eaux par le gouvernement fédéral</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-59952"><span class="HTitleText2">Organismes de gestion qualitative des eaux</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-60011"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-60042"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">[Abrogée, L.R. (1985), ch. 16 (4e suppl.), art. 141]</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-60043"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-60044"><span class="HTitleText2">Inspecteurs et analystes</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-60084"><span class="HTitleText2">Comités consultatifs</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-60092"><span class="HTitleText2">Programme d’information du public</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-60097"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-60132"><span class="HTitleText2">Preuve</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-60142"><span class="HTitleText2">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-60147"><span class="HTitleText2">Disposition financière</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
