<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’évaluation d’impact</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1146422"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1146425"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1146499"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1146502"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1146505"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-1146528"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-1146560"><span class="HTitleText1">Désignation des activités concrètes</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-1146580"><span class="HTitleText1">Étape préparatoire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-1146581"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-1146608"><span class="HTitleText2">Décisions à l’égard des évaluations d’impact</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-1146609"><span class="HTitleText3">Décision de l’Agence</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1146624"><span class="HTitleText3">Décision du ministre</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-1146630"><span class="HTitleText2">Collecte de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-1146664"><span class="HTitleText1">Évaluations d’impact</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-1146665"><span class="HTitleText2">Consultation et coopération avec certaines instances</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-1146670"><span class="HTitleText2">Éléments à examiner</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-1146699"><span class="HTitleText2">Obligation des autorités fédérales</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-1146705"><span class="HTitleText2">Évaluation d’impact effectuée par l’Agence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-1146706"><span class="HTitleText3">Règles générales</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-1146756"><span class="HTitleText3">Substitution</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-1146794"><span class="HTitleText2">Évaluation d’impact renvoyée pour examen par une commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-1146795"><span class="HTitleText3">Règles générales</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-1146979"><span class="HTitleText3">Renseignements confidentiels</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-1146982"><span class="HTitleText3">Règles en cas d’arrêt de l’examen</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-1147004"><span class="HTitleText2">Prise de décisions</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-1147043"><span class="HTitleText2">Déclaration</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-1147112"><span class="HTitleText2">Arrêt de l’évaluation d’impact</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-1147115"><span class="HTitleText2">Renseignements confidentiels</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-1147118"><span class="HTitleText1">Programmes d’aide financière</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-1147127"><span class="HTitleText1">Recouvrement des coûts</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-1147147"><span class="HTitleText1">Fonctions de certaines autorités relativement aux projets</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-1147208"><span class="HTitleText1">Évaluations régionales et évaluations stratégiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="#h-1147209"><span class="HTitleText2">Évaluations régionales</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-1147227"><span class="HTitleText2">Évaluations stratégiques</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-1147235"><span class="HTitleText2">Règles générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-1147261"><span class="HTitleText1">Registre canadien d’évaluation d’impact</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-1147262"><span class="HTitleText2">Établissement du registre</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-1147270"><span class="HTitleText2">Site Internet</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-1147302"><span class="HTitleText2">Dossiers de projet</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-1147319"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-1147333"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-1147425"><span class="HTitleText1">Conseil consultatif du ministre</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-1147447"><span class="HTitleText1">Connaissances autochtones</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-1147462"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-1147463"><span class="HTitleText2">Agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-1147471"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-1147516"><span class="HTitleText2">Avis de non-conformité</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-1147526"><span class="HTitleText2">Ordres</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-1147558"><span class="HTitleText2">Révision des ordres</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-1147597"><span class="HTitleText2">Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-1147602"><span class="HTitleText2">Injonction</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-1147610"><span class="HTitleText2">Rapports volontaires</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-1147625"><span class="HTitleText2">Interdictions et infractions</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-1147672"><span class="HTitleText2">Publication</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-1147680"><span class="HTitleText1">Agence canadienne d’évaluation d’impact</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-1147763"><span class="HTitleText1">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-1147769"><span class="HTitleText1">Examen de la loi</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-1147772"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><a href="#h-1147876"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Autorités fédérales</span></a>
</li>
<li><a href="#h-1147881"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Terres faisant l’objet d’un accord sur des revendications territoriales</span></a>
</li>
<li><a href="#h-1147883"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Composantes de l’environnement et matières sanitaires, sociales ou économiques</span></a>
</li>
<li><a href="#h-1147890"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - Organismes</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
