<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la gestion des ressources de la vallée du Mackenzie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et autres dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-3"><span class="HTitleText1">Champ d’application et consultation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Dispositions générales concernant les offices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-6"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-7"><span class="HTitleText2">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-8"><span class="HTitleText2">Rapports</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-9"><span class="HTitleText2">Textes d’application</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-10"><span class="HTitleText2">Compétence</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-11"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Aménagement territorial</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-12"><span class="HTitleText2">Principes d’application</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-13"><span class="HTitleText2">Office gwich’in d’aménagement territorial</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-14"><span class="HTitleText2">Office d’aménagement territorial du Sahtu</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-15"><span class="HTitleText2">Plan d’aménagement</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-16"><span class="HTitleText2">Caractère obligatoire</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-17"><span class="HTitleText2">Révision</span></a>
</li>
<li><span class='sectionRange'>50.1 - </span><a href="#h-18"><span class="HTitleText2">Instructions générales obligatoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-19"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Réglementation des terres et des eaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-20"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-21"><span class="HTitleText2">Office gwich’in des terres et des eaux</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-22"><span class="HTitleText2">Office des terres et des eaux du Sahtu</span></a>
</li>
<li><span class='sectionRange'>57.1 - </span><a href="#h-23"><span class="HTitleText2">Office des terres et des eaux du Wekeezhii</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-24"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-25"><span class="HTitleText2">Règles propres à l’utilisation des terres</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-26"><span class="HTitleText2">Droits des autochtones sur les eaux</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-27"><span class="HTitleText2">Indemnisation des premières nations des Gwich’in et du Sahtu</span></a>
</li>
<li><span class='sectionRange'>79.1 - </span><a href="#h-28"><span class="HTitleText2">Indemnisation de la première nation tlicho</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-29"><span class="HTitleText2">Fourniture de matériaux de construction</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-30"><span class="HTitleText2">Attributions ministérielles</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-31"><span class="HTitleText2">Instructions générales obligatoires</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-32"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-33"><span class="HTitleText2">Règlements et règles</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-34"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-35"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="#h-36"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Office des terres et des eaux de la vallée du Mackenzie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="#h-37"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-38"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>101.1 - </span><a href="#h-39"><span class="HTitleText2">Mission et compétence de l’Office</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-40"><span class="HTitleText2">Coopération avec d’autres organes</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-41"><span class="HTitleText2">Pouvoirs du gouverneur en conseil et du ministre fédéral</span></a>
</li>
<li><span class='sectionRange'>109.1 - </span><a href="#h-42"><span class="HTitleText2">Pouvoirs du gouvernement tlicho</span></a>
</li>
<li><span class='sectionRange'>109.2 - </span><a href="#h-43"><span class="HTitleText2">Règles applicables en cas d’incompatibilité</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-44"><span class="HTitleText2">Contrôle d’application</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-45"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Office d’examen des répercussions environnementales de la vallée du Mackenzie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-46"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-47"><span class="HTitleText2">Mise en place de l’Office</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-48"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-49"><span class="HTitleText2">Examen préalable</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-50"><span class="HTitleText2">Évaluation environnementale</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-51"><span class="HTitleText2">Étude d’impact</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-52"><span class="HTitleText2">Coopération et examens conjoints</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-53"><span class="HTitleText2">Projets de développement transfrontaliers et extérieurs</span></a>
</li>
<li><span class='sectionRange'>142.1 - </span><a href="#h-54"><span class="HTitleText2">Registre public</span></a>
</li>
<li><span class='sectionRange'>142.2 - </span><a href="#h-55"><span class="HTitleText2">Instructions générales obligatoires</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-56"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>145 - </span><a href="#h-57"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Contrôle et vérification en matière d’environnement</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-58"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Dispositions transitoires, modifications connexes et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-59"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>160 à 167 - </span><a href="#h-60"><span class="HTitleText2">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-61"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-339498"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Organismes administratifs désignés</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
