<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la continuation des pensions de la Gendarmerie royale du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-410407"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-410412"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-410434"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Généralités</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-410471"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Pensions des officiers</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-410651"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Pensions des gendarmes</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-3.html#h-410760"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Pensions aux veuves et orphelins</span></a>
</li>
<li><a href="page-5.html#h-410901"><span class="scheduleLabel">ANNEXE DE LA PARTIE IV</span> - <span class="scheduleTitleText"> - Contributions requises pour acheter les prestations décrites à l’article 48</span></a>
</li></ul>
</li></ul>

</nav>

