<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 1985 sur les normes de prestation de pension</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-405716"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-405719"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-405803"><span class="HTitleText1">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-405838"><span class="HTitleText1">Attributions du surintendant</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-405852"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-405897"><span class="HTitleText1">Gestion des régimes de pension</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-3.html#h-406013"><span class="HTitleText1">Capitalisation et excédent</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-3.html#h-406014"><span class="HTitleText2">Capitalisation requise</span></a>
</li>
<li><span class='sectionRange'>9.11 - </span><a href="page-4.html#h-406062"><span class="HTitleText2">Lettres de crédit</span></a>
</li>
<li><span class='sectionRange'>9.16 - </span><a href="page-4.html#h-406102"><span class="HTitleText2">Sociétés d’État</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="page-4.html#h-406107"><span class="HTitleText2">Excédent</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-4.html#h-406151"><span class="HTitleText1">Agrément</span></a>
</li>
<li><span class='sectionRange'>10.2 - </span><a href="page-4.html#h-406185"><span class="HTitleText1">Transfert de fonds</span></a>
</li>
<li><span class='sectionRange'>10.4 - </span><a href="page-4.html#h-406206"><span class="HTitleText1">Régime distinct</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-5.html#h-406216"><span class="HTitleText1">Directives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-5.html#h-406234"><span class="HTitleText1">Obligations générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-5.html#h-406235"><span class="HTitleText2">Obligation en matière de renseignements</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-5.html#h-406255"><span class="HTitleText2">Conditions de participation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-5.html#h-406278"><span class="HTitleText2">Droit à une prestation de pension immédiate</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="page-5.html#h-406300"><span class="HTitleText2">Prestation de retraite progressive</span></a>
</li>
<li><span class='sectionRange'>16.2 - </span><a href="page-6.html#h-406336"><span class="HTitleText2">Prestation variable</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-6.html#h-406374"><span class="HTitleText2">Acquisition du droit aux prestations</span></a>
</li>
<li><span class='sectionRange'>17.1 - </span><a href="page-6.html#h-1160626"><span class="HTitleText2">Préservation des prestations</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-6.html#h-406381"><span class="HTitleText2">Immobilisation des cotisations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-6.html#h-406395"><span class="HTitleText2">Intérêt</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-6.html#h-406407"><span class="HTitleText2">Cotisations patronales minimales — Régime à prestations déterminées</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-6.html#h-406423"><span class="HTitleText2">L’après-retraite</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-6.html#h-406440"><span class="HTitleText2">Prestation de décès préretraite</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-7.html#h-406457"><span class="HTitleText2">Mariage ou union de fait</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-7.html#h-406462"><span class="HTitleText2">Divorce, annulation du mariage, séparation ou échec de l’union de fait</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-7.html#h-406494"><span class="HTitleText2">Transferts des droits à pension et achats de prestations viagères</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-7.html#h-406525"><span class="HTitleText2">Interdiction de la discrimination sexuelle</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-7.html#h-406540"><span class="HTitleText2">Droits à l’information</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-8.html#h-406570"><span class="HTitleText1">Cessation et liquidation</span></a>
</li>
<li><span class='sectionRange'>29.01 - </span><a href="page-8.html#h-406625"><span class="HTitleText1">Mécanisme d’accommodement pour les régimes de pension en difficulté</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-9.html#h-406752"><span class="HTitleText1">Effet de la vente de l’entreprise ou de l’exploitation</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-9.html#h-406767"><span class="HTitleText1">Paiement des prestations et désignation des bénéficiaires</span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="page-9.html#h-406770"><span class="HTitleText1">Communications électroniques</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-9.html#h-406795"><span class="HTitleText1">Oppositions et appels</span></a>
</li>
<li><span class='sectionRange'>33.1 - </span><a href="page-9.html#h-406822"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-10.html#h-406882"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-10.html#h-406911"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-11.html#h-406996"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-11.html#h-407003"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-11.html#h-407005"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-11.html#h-407017"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-12.html#h-407021"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>

