<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi réglementant certaines drogues et autres substances</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-92138"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-92141"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-92190"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Infractions et peines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-92191"><span class="HTitleText2">Infractions particulières</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-92332"><span class="HTitleText2">Avis</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-92337"><span class="HTitleText2">Rapport au parlement</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-92345"><span class="HTitleText2">Détermination de la peine</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-92368"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Exécution et mesures de contrainte</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-92412"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Disposition</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-3.html#h-92425"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Biens infractionnels non-chimiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-3.html#h-92426"><span class="HTitleText3">Ordonnances de blocage</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="page-3.html#h-92463"><span class="HTitleText3">Ordonnances de prise en charge</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-92499"><span class="HTitleText3">Confiscation</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-4.html#h-92596"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Substances désignées, précurseurs et biens infractionnels chimiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-5.html#h-92657"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="page-5.html#h-92658"><span class="HTitleText2">Inspecteurs</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="page-5.html#h-92727"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Ordonnances administratives pour violation de règlements spéciaux</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-6.html#h-92787"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-6.html#h-92788"><span class="HTitleText2">Analyse</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="page-6.html#h-92798"><span class="HTitleText2">Arrêtés du ministre</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-6.html#h-92844"><span class="HTitleText2">Infraction et peine</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="page-6.html#h-92851"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-92883"><span class="HTitleText2">Preuve et procédure</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="page-7.html#h-92932"><span class="HTitleText2">Assistance technique</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-92937"><span class="HTitleText2">Règlements et exemptions</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-8.html#h-93034"><span class="HTitleText2">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-8.html#h-93042"><span class="HTitleText2">Modification des annexes</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-8.html#h-93056"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Dispositions transitoires, modifications corrélatives et conditionnelles, abrogation et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="page-8.html#h-93057"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>64 à 93.1 - </span><a href="page-8.html#h-93069"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>93.2 et 93.3 - </span><a href="page-8.html#h-93071"><span class="HTitleText2">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-8.html#h-93073"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-8.html#h-93075"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-9.html#h-93079"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="page-10.html#h-93305"><span class="scheduleLabel">ANNEXE II</span> </a>
</li>
<li><a href="page-11.html#h-93367"><span class="scheduleLabel">ANNEXE III</span> </a>
</li>
<li><a href="page-12.html#h-93425"><span class="scheduleLabel">ANNEXE IV</span> </a>
</li>
<li><a href="page-13.html#h-93584"><span class="scheduleLabel">ANNEXE V</span> </a>
</li>
<li><a href="page-14.html#h-93588"><span class="scheduleLabel">ANNEXE VI</span> </a>
</li>
<li><a href="page-15.html#h-93645"><span class="scheduleLabel">ANNEXE VII</span></a>
</li>
<li><a href="page-16.html#h-93648"><span class="scheduleLabel">ANNEXE VIII</span></a>
</li>
<li><a href="page-17.html#h-93651"><span class="scheduleLabel">ANNEXE IX</span> </a>
</li></ul>
</li></ul>

</nav>

