<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act for the settlement of certain questions between the Governments of Canada and Ontario respecting Indian Reserve Lands</a><ul class="TocIndent"><li><a href="#h-333113"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
