<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Budget Implementation Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-36008"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-36011"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Air Transport Security</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-36012"><span class="HTitleText2">Canadian Air Transport Security Authority Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-36014"><span class="HTitleText2">Consequential Amendment</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-36016"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-1.html#h-36019"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Air Security Charges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-36020"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>6 to 9 - </span><a href="page-1.html#h-36022"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-36024"><span class="HTitleText2">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-36026"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 to 14 - </span><a href="page-1.html#h-36029"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Employment Insurance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 to 14 - </span><a href="page-1.html#h-36030"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-36032"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-36034"><span class="HTitleText2">Employment Insurance (Fishing) Regulations</span></a>
</li>
<li><span class='sectionRange'>17 and 18 - </span><a href="page-1.html#h-36036"><span class="HTitleText2">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-36038"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 to 44 - </span><a href="page-1.html#h-36044"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-1.html#h-36046"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Canada Fund for Africa</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-1.html#h-36047"><span class="HTitleText2">Canada Fund for Africa Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-1.html#h-36049"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-1.html#h-36052"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Canada Strategic Infrastructure Fund</span></a>
</li></ul>
</li></ul>

</nav>

