<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Evidence Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Part I</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Witnesses</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText2">Judicial Notice</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText2">Documentary Evidence</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-8"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-9"><span class="HTitleText2">Specified Public Interest</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-10"><span class="HTitleText2">International Relations and National Defence and National Security</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-11"><span class="HTitleText2">Confidences of the Queen’s Privy Council for Canada</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-12"><span class="HTitleText2">Provincial Laws of Evidence</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-13"><span class="HTitleText2">Statutory Declarations</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-14"><span class="HTitleText2">Insurance Proofs</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-15"><span class="HTitleText1">Part II</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-16"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-17"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-18"><span class="HTitleText2">Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-19"><span class="HTitleText1">Part III</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-20"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-21"><span class="HTitleText2">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-22"><span class="HTitleText2">Documentary Evidence</span></a>
</li></ul>
</li><li><a href="#h-23"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Designated Entities</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
