<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la gestion des terres des premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-221214"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-221217"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-221246"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-221249"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-221266"><span class="HTitleText1">Mise en place du régime de gestion des terres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-1.html#h-221267"><span class="HTitleText2">Code foncier et accord spécifique</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-221343"><span class="HTitleText2">Vérification</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-221365"><span class="HTitleText2">Consultation populaire et certification</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-221421"><span class="HTitleText2">Entrée en vigueur du code foncier</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-2.html#h-221445"><span class="HTitleText1">Régime de gestion des terres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-2.html#h-221446"><span class="HTitleText2">Pouvoirs généraux de la première nation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-221474"><span class="HTitleText2">Textes législatifs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-221555"><span class="HTitleText2">Registre des terres des premières nations</span></a>
</li>
<li><span class='sectionRange'>25.1 - </span><a href="page-3.html#h-221569"><span class="HTitleText2">Ajout aux terres de la première nation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-221598"><span class="HTitleText2">Restrictions en matière d’aliénation</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-4.html#h-221691"><span class="HTitleText1">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-221703"><span class="HTitleText1">Immunité et contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-221717"><span class="HTitleText1">Cadre législatif</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-4.html#h-221765"><span class="HTitleText1">Modification des annexes</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-221777"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-221791"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-6.html#h-221795"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-7.html#h-221805"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

