<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Servants Inventions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-403892"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-403897"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-403906"><span class="HTitleText1">Inventions Vested in Her Majesty</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-403963"><span class="HTitleText1">Awards</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-403968"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-403973"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-403984"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
