<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant l’Accord sur les revendications territoriales du Nunavut</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-361537"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-361540"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-361545"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-361548"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-361573"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-361576"><span class="HTitleText1">Conseil de gestion des ressources fauniques du Nunavut</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-361586"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

