<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi d’exécution du budget de 1999</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-34836"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 à 10 - </span><a href="#h-34839"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Transfert canadien en matière de santé et de programmes sociaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 à 10 - </span><a href="#h-34840"><span class="HTitleText2">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-34842"><span class="HTitleText2">Loi canadienne sur la santé</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-34844"><span class="HTitleText2">Loi sur le Nunavut</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-34846"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 à 16 - </span><a href="#h-34850"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Pension du secteur public</span></a>
</li>
<li><span class='sectionRange'>17 à 19 - </span><a href="#h-34852"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Gestion des ressources humaines</span></a>
</li>
<li><span class='sectionRange'>20 à 24 - </span><a href="#h-34854"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Gestion des fonds publics</span></a>
</li>
<li><span class='sectionRange'>31 à 34 - </span><a href="#h-34858"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Taxes de vente de certaines premières nations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 à 34 - </span><a href="#h-34859"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">[Abrogée, 2000, ch. 14, art. 32]</span></a>
</li>
<li><span class='sectionRange'>31 à 34 - </span><a href="#h-34860"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Loi d’exécution du budget de 1997</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-34862"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Loi sur l’autonomie gouvernementale des premières nations du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-34864"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Prestation fiscale canadienne pour enfants</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-34866"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Crédit de taxe sur les produits et services</span></a>
</li>
<li><span class='sectionRange'>38 à 41 - </span><a href="#h-34868"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Communication de renseignements confidentiels</span></a>
</li>
<li><span class='sectionRange'>42 à 50 - </span><a href="#h-34870"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Modifications apportées à d’autres lois</span></a>
</li></ul>
</li></ul>

</nav>

