<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Civil International Space Station Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-85176"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-85179"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-85184"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-85193"><span class="HTitleText1">Information</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-85216"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-85219"><span class="HTitleText1">Amendments to the Agreement</span></a>
</li>
<li><span class='sectionRange'>11 and 12 - </span><a href="#h-85222"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-85224"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-85228"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Agreement Among the Government of Canada, Governments of Member States of the European Space Agency, the Government of Japan, the Government of the Russian Federation, and the Government of the United States of America Concerning Cooperation on the Civil International Space Station</span></a>
</li>
<li><a href="#h-85470"><span class="scheduleLabel">ANNEX</span> - <span class="scheduleTitleText"> - Space Station Elements To Be Provided by the Partners</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
