<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les lettres de change</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-28128"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-28133"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-28150"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-28219"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Lettres de change</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-28220"><span class="HTitleText2">Forme de la lettre et interprétation</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-28355"><span class="HTitleText2">Acceptation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-28396"><span class="HTitleText2">Livraison</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-28414"><span class="HTitleText2">Échéance des lettres</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-28445"><span class="HTitleText2">Capacité et habilité des parties</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-28488"><span class="HTitleText2">Cause</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-28512"><span class="HTitleText2">Détenteur régulier</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-28537"><span class="HTitleText2">Négociation</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-28635"><span class="HTitleText2">Droits et pouvoirs du détenteur</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-28644"><span class="HTitleText2">Présentation à l’acceptation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-28722"><span class="HTitleText2">Présentation au paiement</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-28815"><span class="HTitleText2">Avis de refus</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-28915"><span class="HTitleText2">Protêt</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-29019"><span class="HTitleText2">Obligations des parties</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-29088"><span class="HTitleText2">Libération</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-29148"><span class="HTitleText2">Acceptation et paiement par intervention</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-29202"><span class="HTitleText2">Effets perdus</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-29214"><span class="HTitleText2">Pluralité d’exemplaires</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-29235"><span class="HTitleText2">Conflit de lois</span></a>
</li>
<li><span class='sectionRange'>163.1 - </span><a href="#h-29261"><span class="HTitleText2">Image officielle et présentation électronique</span></a>
</li></ul>
</li><li><span class='sectionRange'>164 - </span><a href="#h-29303"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Chèques sur une banque</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-29332"><span class="HTitleText2">Chèques barrés</span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="#h-29389"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Billets</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-29473"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Lettres et billets de consommation</span></a>
</li>
<li><a href="#h-29527"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

