<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Conseil canadien des normes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-429440"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-429445"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-429452"><span class="HTitleText1">Constitution du conseil</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-429461"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-429511"><span class="HTitleText1">Fonctionnement</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-429566"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-429599"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-429608"><span class="HTitleText1">Comité consultatif des provinces et territoires</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-429618"><span class="HTitleText1">Comité consultatif des organismes d’élaboration de normes</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-429628"><span class="HTitleText1">Réunions</span></a>
</li></ul>
</li></ul>

</nav>

