<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les forces étrangères présentes au Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-453048"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-453053"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-453068"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Champ d’application de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-453081"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Juridiction disciplinaire des forces étrangères présentes au Canada</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-453158"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Réclamations pour blessures et pour dommages causés aux biens</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-453193"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions relatives à la sécurité</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-453210"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Impôt</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-453241"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Assignations auprès des forces canadiennes et d’autres forces</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-453261"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>

