<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les produits antiparasitaires</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">Homologation des produits antiparasitaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Demande d’homologation ou de modification d’homologation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Limites maximales de résidus</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Renseignements supplémentaires et obligation de communiquer</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Réévaluation et examen spécial</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Autres motifs de révocation ou de modification</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText2">Consultation publique</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText1">Contrôle de l’exportation</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">Examen des décisions</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText1">Autorisation d’utilisation d’un produit antiparasitaire non homologué</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText1">Accès à l’information</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-19"><span class="HTitleText1">Application de la loi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-20"><span class="HTitleText2">Inspecteurs et analystes</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-21"><span class="HTitleText2">Rapport volontaire</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-22"><span class="HTitleText2">Visite</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-23"><span class="HTitleText2">Perquisitions</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-24"><span class="HTitleText2">Saisies</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-25"><span class="HTitleText2">Mesures consécutives à la saisie</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-26"><span class="HTitleText2">Mesures pour faire observer la loi</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-27"><span class="HTitleText2">Mesures d’élimination et de contrôle des risques</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-28"><span class="HTitleText2">Révision des ordres des inspecteurs</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-29"><span class="HTitleText2">Ordre du tribunal</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-30"><span class="HTitleText1">Livraison de documents</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-31"><span class="HTitleText1">Droits et autres frais</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-32"><span class="HTitleText1">Limitation de responsabilité</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-33"><span class="HTitleText1">Droits à payer pour l’utilisation de renseignements</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-34"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>67.1 - </span><a href="#h-35"><span class="HTitleText1">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-36"><span class="HTitleText1">Infractions et peines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-37"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-38"><span class="HTitleText2">Dispositions connexes</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-39"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-40"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>82 à 88 - </span><a href="#h-41"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-42"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-43"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
