<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Honduras Economic Growth and Prosperity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-146185"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-146188"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-146204"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-146207"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-146218"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-146224"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement and the Related Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-146225"><span class="HTitleText2">Approval</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-146228"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-146233"><span class="HTitleText2">Panels, Committees, Subcommittees, Working Groups and Expert Groups</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-146256"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-146266"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-146267"><span class="HTitleText2"><cite class="XRefExternalAct">Crown Liability and Proceedings Act</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-146269"><span class="HTitleText2"><cite class="XRefExternalAct">Export and Import Permits Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-146273"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-146275"><span class="HTitleText2"><cite class="XRefExternalAct">Importation of Intoxicating Liquors Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-146278"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-146286"><span class="HTitleText2"><cite class="XRefExternalAct">Commercial Arbitration Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-146288"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian International Trade Tribunal Act</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-146297"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-146308"><span class="HTitleText2"><cite class="XRefExternalAct">Department of Employment and Social Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-146311"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-146312"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-146315"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-24"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-25"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
