<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Manganese-based Fuel Additives Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-348255"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-348258"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-348264"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-348267"><span class="HTitleText1">Interprovincial Trade and Importation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-348291"><span class="HTitleText1">Records</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-348307"><span class="HTitleText1">Powers of the Minister</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-348317"><span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-348318"><span class="HTitleText2">Inspectors and Analysts</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-348324"><span class="HTitleText2">Provisions of the Canadian Environmental Protection Act, 1999</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-348329"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-348370"><span class="HTitleText1">Amendments to the Schedule</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-348373"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-348377"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Controlled Substances</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
