<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Secure Air Travel Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-444682"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-444685"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-444688"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-444699"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-444707"><span class="HTitleText1">Air Carriers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-444713"><span class="HTitleText1">Minister</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-444729"><span class="HTitleText1">Directions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-444737"><span class="HTitleText1">Collection and Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-444760"><span class="HTitleText1">Administrative Recourse</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-444774"><span class="HTitleText1">Appeals</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-444802"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-444807"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-444830"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-444850"><span class="HTitleText1">Prosecution</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-444860"><span class="HTitleText1">Inspection Powers</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-444886"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-444893"><span class="HTitleText1">Transitional Provision</span></a>
</li></ul>
</li></ul>

</nav>

