<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Institutes of Health Research Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-71284"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-71287"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-71290"><span class="HTitleText1">Establishment</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-71298"><span class="HTitleText1">Objective</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-71317"><span class="HTitleText1">Powers and Functions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-71327"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-71367"><span class="HTitleText1">Compensation and Benefits</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-71382"><span class="HTitleText1">Responsibilities of Governing Council</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-71422"><span class="HTitleText1">Health Research Institutes</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-71448"><span class="HTitleText1">President and Employees</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-71464"><span class="HTitleText1">Powers</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-71492"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-71501"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>41 to 50 - </span><a href="#h-71546"><span class="HTitleText1">Consequential Amendments, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 to 50 - </span><a href="#h-71547"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-71549"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-71551"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
