<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les allocations aux anciens combattants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-455762"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.01 - </span><a href="#h-455767"><span class="HTitleText1">Déclaration</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-455772"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-455864"><span class="HTitleText1">Égalité de statut</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-455869"><span class="HTitleText1">Allocations aux anciens combattants, aux survivants et aux orphelins</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-455909"><span class="HTitleText1">Attribution de montants spéciaux</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-455932"><span class="HTitleText1">Versement d’allocations</span></a>
</li>
<li><span class='sectionRange'>6.2 - </span><a href="#h-455938"><span class="HTitleText1">Résidence au Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-455954"><span class="HTitleText1">Définition de « revenu »</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-455976"><span class="HTitleText1">Limitations</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-456025"><span class="HTitleText1">Suspension de l’allocation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-456039"><span class="HTitleText1">Paiement pour le compte du bénéficiaire</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-456055"><span class="HTitleText1">Protection de l’allocation</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-456063"><span class="HTitleText1">Recouvrements et paiements insuffisants</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-456084"><span class="HTitleText1">Ajustement trimestriel des allocations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-456114"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-456122"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-456147"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-456169"><span class="HTitleText1">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-456192"><span class="HTitleText1">Appels</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-456202"><span class="HTitleText1">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-456220"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-456236"><span class="HTitleText1">Description des anciens combattants</span></a>
</li>
<li><a href="#h-456373"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

