<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget de 1998</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-34712"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-34715"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">[Abrogée, 2008, ch. 28, art. 95]</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-1.html#h-34761"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Autorisation de cession</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-1.html#h-34793"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Retraite anticipée — suspension de l’indemnité de cessation d’emploi</span></a>
</li>
<li><span class='sectionRange'>72 à 75 - </span><a href="page-1.html#h-34799"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">[Abrogée, 2000, ch. 14, art. 31]</span></a>
</li>
<li><span class='sectionRange'>72 à 75 - </span><a href="page-1.html#h-34800"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Subvention canadienne pour l’épargne-études</span></a>
</li>
<li><span class='sectionRange'>76 à 79 - </span><a href="page-1.html#h-34802"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Accords d’application avec des gouvernements autochtones</span></a>
</li>
<li><span class='sectionRange'>80 à 83 - </span><a href="page-1.html#h-34804"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Produits du tabac</span></a>
</li>
<li><span class='sectionRange'>84 à 90 - </span><a href="page-1.html#h-34806"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Taxe de transport aérien</span></a>
</li>
<li><span class='sectionRange'>91 à 98 - </span><a href="page-1.html#h-34808"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Régime national de prestations pour enfants</span></a>
</li>
<li><span class='sectionRange'>99 à 103 - </span><a href="page-1.html#h-34810"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-1.html#h-34812"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Remboursement de la cotisation patronale</span></a>
</li>
<li><span class='sectionRange'>105 à 124 - </span><a href="page-1.html#h-34814"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">Supplément et allocations</span></a>
</li>
<li><span class='sectionRange'>125 à 132 - </span><a href="page-1.html#h-34816"><span class="HLabel1">PARTIE 13</span> - <span class="HTitleText1">Aide financière aux institutions financières et aux États étrangers</span></a>
</li>
<li><a href="page-2.html#h-34821"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>

