<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Seeds Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-446516"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-446521"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-446550"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-446572"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-446615"><span class="HTitleText1">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>4.11 - </span><a href="#h-446627"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="#h-446640"><span class="HTitleText1">Licence</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-446652"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>8.2 - </span><a href="#h-446729"><span class="HTitleText1">Analysis</span></a>
</li>
<li><span class='sectionRange'>8.3 - </span><a href="#h-446736"><span class="HTitleText1">Limitation on Liability</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-446747"><span class="HTitleText1">Offences and Punishment</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
