<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les prestations d’adaptation pour les travailleurs</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-330128"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-330133"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-330157"><span class="HTitleText1">Désignation de secteurs d’activités</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-330193"><span class="HTitleText1">Office d’aide à l’adaptation des travailleurs</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-330236"><span class="HTitleText1">Droit aux prestations d’adaptation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-330241"><span class="HTitleText1">Certification par l’office</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-330265"><span class="HTitleText1">Demande à la commission</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-330287"><span class="HTitleText1">Admissibilité</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-330329"><span class="HTitleText1">Prestations d’adaptation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-330411"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-330486"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

