<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée des anciens combattants de la guerre de Corée</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-330059"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-330062"><span class="HTitleText1">Journée des anciens combattants de la guerre de Corée</span></a>
</li></ul>
</li></ul>

</nav>

