<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Fondation Asie-Pacifique du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Constitution de la fondation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText1">Président et personnel</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText1">Indemnités et frais</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-9"><span class="HTitleText1">Comités</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-11"><span class="HTitleText1">Statut de la fondation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-12"><span class="HTitleText1">Organisme de charité enregistré</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-14"><span class="HTitleText1">Dissolution</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-15"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-16"><span class="HTitleText1">Rapport</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-17"><span class="HTitleText1">Examen</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
