<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Official Development Assistance Accountability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-384049"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-384052"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-384058"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-384074"><span class="HTitleText1">Official Development Assistance</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-384089"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-384108"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
