<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
International Financial Assistance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-272119"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-272122"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-272125"><span class="HTitleText1">International Financial Assistance</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-272157"><span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

