<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Prohibiting Cluster Munitions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-399860"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-399863"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-399900"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-399903"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-399906"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-399949"><span class="HTitleText1">Detention in a Safe Place</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-399954"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-399957"><span class="HTitleText1">Amendments to the Convention</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-399960"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-399985"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-399991"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-3.html#h-399995"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Convention on Cluster Munitions</span></a>
</li></ul>
</li></ul>

</nav>

