<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’expropriation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-206572"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-206577"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-206613"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Expropriation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-206614"><span class="HTitleText2">Acquisition et délaissement de biens-fonds</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-206861"><span class="HTitleText2">Indemnité</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-206965"><span class="HTitleText2">Paiement de l’indemnité</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-207032"><span class="HTitleText2">Intérêt</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-5.html#h-207054"><span class="HTitleText2">Entrée et possession</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-5.html#h-207069"><span class="HTitleText2">Frais</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="page-5.html#h-207077"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Usage des biens-fonds</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-207105"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="page-6.html#h-207116"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

