<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Prompt Payment for Construction Work Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1169462"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1169465"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1169491"><span class="HTitleText1">Designation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1169494"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1169497"><span class="HTitleText1">Application of Act</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-1169521"><span class="HTitleText1">Payments Between Parties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-1169522"><span class="HTitleText2">Her Majesty or Service Provider to Contractor</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-1169534"><span class="HTitleText2">Contractor to Subcontractor</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-1169544"><span class="HTitleText2">Subcontractor to Subcontractor</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-1169558"><span class="HTitleText2">Holdback</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-1169566"><span class="HTitleText2">Non-payment</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-1169581"><span class="HTitleText2">Dispute Resolution</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-1169634"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-1169652"><span class="HTitleText1">Transitional Provision</span></a>
</li></ul>
</li></ul>

</nav>

