<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Diplomatic Service (Special) Superannuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-172713"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-172718"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-172729"><span class="HTitleText1">Equality of Status</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-172734"><span class="HTitleText1">Retirement and Superannuation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-172742"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Superannuation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-172743"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-172816"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-172843"><span class="HTitleText2">Alternate Benefits</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-172899"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-2.html#h-172944"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Supplementary Retirement Benefit Contributions</span></a>
</li></ul>
</li></ul>

</nav>

