<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Currency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-142341"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-142346"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-142353"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Currency and Coinage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-142354"><span class="HTitleText2">Monetary Unit</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-142363"><span class="HTitleText2">Current Coins and Notes</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-142377"><span class="HTitleText2">Legal Tender</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-142417"><span class="HTitleText2">Counterfeit Coins</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-142422"><span class="HTitleText2">Melting Coins</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-142430"><span class="HTitleText2">Accounts, Contracts and other Matters Relating to Money</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="page-1.html#h-142461"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Exchange Fund Account</span></a>
</li>
<li><a href="page-3.html#h-142533"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

