<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la responsabilité en matière maritime</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-340899"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-340902"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-340907"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-340910"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Blessures corporelles et accidents mortels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-340911"><span class="HTitleText2">Définition et champ d’application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-340921"><span class="HTitleText2">Responsabilité : personnes à charge</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="page-1.html#h-340961"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Partage de la responsabilité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="page-1.html#h-340962"><span class="HTitleText2">Définition et champ d’application</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-340974"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-341000"><span class="HTitleText2">Prescription</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-1.html#h-341010"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Limitation de responsabilité en matière de créances maritimes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="page-1.html#h-341011"><span class="HTitleText2">Définitions et dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-341033"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-341077"><span class="HTitleText2">Propriétaires de docks, canaux ou ports</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-341095"><span class="HTitleText2">Modification des limites de responsabilité</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-341103"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>34.1 - </span><a href="page-2.html#h-341130"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-2.html#h-341137"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Responsabilité en matière de transport de passagers par eau</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-2.html#h-341138"><span class="HTitleText2">Définitions et dispositions interprétatives</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-341154"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-3.html#h-341182"><span class="HTitleText2">Règlements et décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-3.html#h-341196"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Responsabilité en matière de transport de marchandises par eau</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-3.html#h-341197"><span class="HTitleText2">Définitions et disposition interprétative</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-3.html#h-341206"><span class="HTitleText2">Règles de La Haye-Visby</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-3.html#h-341216"><span class="HTitleText2">Règles de Hambourg</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-3.html#h-341230"><span class="HTitleText2">Procédure intentée au Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-3.html#h-341239"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Responsabilité et indemnisation en matière de pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-3.html#h-341240"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Conventions internationales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-3.html#h-341241"><span class="HTitleText3">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-3.html#h-341266"><span class="HTitleText3">Convention sur la responsabilité civile</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-4.html#h-341345"><span class="HTitleText3">Convention sur le Fonds international</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-4.html#h-341375"><span class="HTitleText3">Protocole portant création d’un Fonds complémentaire</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-4.html#h-341405"><span class="HTitleText3">Convention sur les hydrocarbures de soute</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="page-5.html#h-341490"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Responsabilité non visée par la section 1</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="page-5.html#h-341491"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-5.html#h-341505"><span class="HTitleText3">Champ d’application</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="page-5.html#h-341543"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="page-5.html#h-341544"><span class="HTitleText3">Cour d’amirauté</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-5.html#h-341557"><span class="HTitleText3">Enregistrement des jugements étrangers</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-6.html#h-341637"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="page-6.html#h-341650"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Caisse d’indemnisation des dommages dus à la pollution par les hydrocarbures causée par les navires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-6.html#h-341651"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-6.html#h-341671"><span class="HTitleText2">Caisse d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-6.html#h-341703"><span class="HTitleText2">Administrateur et administrateur adjoint</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="page-7.html#h-341753"><span class="HTitleText2">Responsabilités de la Caisse d’indemnisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="page-7.html#h-341754"><span class="HTitleText3">Processus d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>106.1 - </span><a href="page-7.html#h-341844"><span class="HTitleText3">Processus d’indemnisation accéléré</span></a>
</li></ul>
</li><li><span class='sectionRange'>107 - </span><a href="page-8.html#h-341945"><span class="HTitleText2">Demandes d’indemnisation des pertes de revenus</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-8.html#h-341998"><span class="HTitleText2">Action en responsabilité contre le propriétaire d’un navire</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-9.html#h-342008"><span class="HTitleText2">Fonds en cas d’urgence</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-9.html#h-342055"><span class="HTitleText2">Contributions à la Caisse d’indemnisation, au Fonds international et au Fonds complémentaire</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-10.html#h-342232"><span class="HTitleText2">Gestion de la Caisse d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-11.html#h-342290"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="page-11.html#h-342301"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="page-11.html#h-342302"><span class="HTitleText2">Exécution et contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>130.01 - </span><a href="page-11.html#h-342360"><span class="HTitleText2">Sanctions administratives pécuniaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130.01 - </span><a href="page-11.html#h-342361"><span class="HTitleText3">Transaction et Procès-verbal</span></a>
</li>
<li><span class='sectionRange'>130.11 - </span><a href="page-12.html#h-342488"><span class="HTitleText3">Recouvrement des créances</span></a>
</li>
<li><span class='sectionRange'>130.13 - </span><a href="page-12.html#h-342509"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>130.17 - </span><a href="page-12.html#h-342526"><span class="HTitleText3">Registre public</span></a>
</li>
<li><span class='sectionRange'>130.19 - </span><a href="page-13.html#h-342554"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>131 - </span><a href="page-13.html#h-342562"><span class="HTitleText2">Infractions</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-13.html#h-342611"><span class="HTitleText2">Vente de navires</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="page-13.html#h-342655"><span class="HTitleText2">Privilège maritime</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="page-13.html#h-342673"><span class="HTitleText2">Prescription</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-13.html#h-342678"><span class="HTitleText2">Incompatibilité</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-14.html#h-342683"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-15.html#h-342689"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-16.html#h-342869"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-17.html#h-343022"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Règles de la Haye-Visby</span></a>
</li>
<li><a href="page-18.html#h-343130"><span class="scheduleLabel">ANNEXE 4</span> <span class="scheduleTitleText"> - Règles de Hambourg</span></a>
</li>
<li><a href="page-19.html#h-343407"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - Texte des articles I à XI, XII bis et 15 de la Convention internationale de 1992 sur la responsabilité civile pour les dommages dus à la pollution par les hydrocarbures modifiée par la résolution de 2000</span></a>
</li>
<li><a href="page-20.html#h-343563"><span class="scheduleLabel">ANNEXE 6</span> <span class="scheduleTitleText"> - Texte des articles 1 à 4, 6 à 10, 12 à 15, 36 ter, 29, 33 et 37 de la Convention internationale de 1992 portant création d’un Fonds international d’indemnisation pour les dommages dus à la pollution par les hydrocarbures modifiée par la résolution de 2000</span></a>
</li>
<li><a href="page-21.html#h-343714"><span class="scheduleLabel">ANNEXE 7</span> <span class="scheduleTitleText"> - Texte des articles 1 à 15, 18, 20, 24, 25 et 29 du Protocole de 2003 à la Convention internationale de 1992 portant création d’un Fonds international d’indemnisation pour les dommages dus à la pollution par les hydrocarbures</span></a>
</li>
<li><a href="page-22.html#h-343855"><span class="scheduleLabel">ANNEXE 8</span> <span class="scheduleTitleText"> - Texte des articles 1 à 10 de la Convention internationale de 2001 sur la responsabilité civile pour les dommages dus à la pollution par les hydrocarbures de soute</span></a>
</li></ul>
</li></ul>

</nav>

