<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 1 sur le plan d’action économique de 2014</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-170892"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-170895"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la Loi de l’impôt sur le revenu et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-170896"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-170926"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-170928"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-170935"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur le Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-170937"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur la rémunération assurable et la perception des cotisations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-170939"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modification de la Loi sur la taxe d’accise (mesures relatives à la TPS/TVH)</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-170962"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modification de la Loi de 2001 sur l’accise, de la Loi sur la taxe d’accise (sauf les dispositions concernant la TPS/TVH) et de la Loi sur le droit pour la sécurité des passagers du transport aérien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-170963"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2001 sur l’accise</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-170964"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-170989"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>83 - </span><a href="#h-170991"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-170999"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit pour la sécurité des passagers du transport aérien</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-171001"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Tarif des douanes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-171002"><span class="HTitleText2">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-171010"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-171016"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Loi de mise en oeuvre de l’Accord Canada–États-Unis pour un meilleur échange de renseignements fiscaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-171017"><span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-171020"><span class="HTitleText2">Modification de la <cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>102 - </span><a href="#h-171023"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Diverses mesures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-171024"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Paiements — anciens combattants</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-171091"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Société d’assurance-dépôts du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-171092"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Banque du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-171094"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la Société d’assurance-dépôts du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-171096"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Initiative du Conseil de coopération en matière de réglementation concernant les produits chimiques dans les lieux de travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-171097"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur les produits dangereux</cite></span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-171117"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-171128"><span class="HTitleText3">Modification du <cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-171133"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-171137"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-171151"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-171153"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-171156"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>163 - </span><a href="#h-171159"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-171161"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les juges</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-171164"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les allocations de retraite des parlementaires</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-171165"><span class="HTitleText3">Modifications de la loi</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-171167"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="#h-171169"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la défense nationale</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-171170"><span class="HTitleText3">Modifications de la loi</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-171174"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>172 - </span><a href="#h-171180"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-171184"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Agence de promotion économique du Canada atlantique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>175 - </span><a href="#h-171185"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence de promotion économique du Canada atlantique</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-171189"><span class="HTitleText3">Dissolution du conseil</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-171191"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Société d’expansion du Cap-Breton</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-171192"><span class="HTitleText3">Dissolution</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-171233"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’Agence de promotion économique du Canada atlantique</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-171235"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>188 - </span><a href="#h-171236"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-171239"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-171241"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>192 - </span><a href="#h-171243"><span class="HTitleText3">Abrogation</span></a>
</li></ul>
</li><li><span class='sectionRange'>193 - </span><a href="#h-171245"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les musées</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-171246"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-171248"><span class="HTitleText3">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="#h-171249"><span class="HTitleText4">Définitions</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-171251"><span class="HTitleText4">Ouvrages de référence en ligne</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-171257"><span class="HTitleText4">Musée virtuel du Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="#h-171263"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-171266"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi autorisant l’aliénation de Nordion et de Theratronics</cite></span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-171271"><span class="HLabel2">SECTION 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-171273"><span class="HLabel2">SECTION 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-171275"><span class="HLabel2">SECTION 15</span> - <span class="HTitleText2">Coopération en matière de réglementation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>212 - </span><a href="#h-171276"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la sécurité automobile</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-171296"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la sécurité ferroviaire</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-171298"><span class="HTitleText3"><cite class="XRefExternalAct">Loi de 1992 sur le transport des marchandises dangereuses</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-171300"><span class="HTitleText3"><cite class="XRefExternalAct">Loi assurant aux Canadiens la sécurité des véhicules importés du Mexique</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-171302"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la salubrité des aliments au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-171306"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-171308"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="#h-171311"><span class="HLabel2">SECTION 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les télécommunications</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-171312"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="#h-171315"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>242 - </span><a href="#h-171318"><span class="HLabel2">SECTION 17</span> - <span class="HTitleText2">Prestations de maladie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>242 - </span><a href="#h-171319"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-171325"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-171329"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-171331"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="#h-171334"><span class="HLabel2">SECTION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence canadienne d’inspection des aliments</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>252 - </span><a href="#h-171335"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-171337"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="#h-171341"><span class="HLabel2">SECTION 19</span> - <span class="HTitleText2">Recyclage des produits de la criminalité et financement des activités terroristes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>254 - </span><a href="#h-171342"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-171386"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’emploi et la croissance économique</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-171388"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>299 - </span><a href="#h-171396"><span class="HLabel2">SECTION 20</span> - <span class="HTitleText2">Immigration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="#h-171397"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-171405"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-171407"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>308 - </span><a href="#h-171410"><span class="HLabel2">SECTION 21</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Relations de travail dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="#h-171411"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les relations de travail dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>309 - </span><a href="#h-171413"><span class="HTitleText3"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="#h-171415"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>311 - </span><a href="#h-171422"><span class="HLabel2">SECTION 22</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi de 2006 sur les droits d’exportation de produits de bois d’oeuvre</cite></span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-171425"><span class="HLabel2">SECTION 23</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi d’exécution du budget de 2009</cite></span></a>
</li>
<li><span class='sectionRange'>314 - </span><a href="#h-171427"><span class="HLabel2">SECTION 24</span> - <span class="HTitleText2">Titrisation de prêts hypothécaires assurés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>314 - </span><a href="#h-171428"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur la protection de l’assurance hypothécaire résidentielle</cite></span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-171431"><span class="HTitleText3"><cite class="XRefExternalAct">Loi nationale sur l’habitation</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>317 - </span><a href="#h-171433"><span class="HLabel2">SECTION 25</span> - <span class="HTitleText2">Modifications liées aux traités internationaux sur les marques de commerce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>317 - </span><a href="#h-171434"><span class="HTitleText3">Modification de la <cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>364 - </span><a href="#h-171483"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>364 - </span><a href="#h-171484"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les marques olympiques et paralympiques</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>366 - </span><a href="#h-171487"><span class="HTitleText3">Modifications terminologiques</span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="#h-171489"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="#h-171491"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>369 - </span><a href="#h-171499"><span class="HLabel2">SECTION 26</span> - <span class="HTitleText2">Mesure de réduction des postes pourvus par le gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="#h-171502"><span class="HLabel2">SECTION 27</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la sécurité de la vieillesse</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>371 - </span><a href="#h-171503"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>374 - </span><a href="#h-171507"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>375 - </span><a href="#h-171510"><span class="HLabel2">SECTION 28</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi visant le nouveau pont pour le Saint-Laurent</cite></span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="#h-171513"><span class="HLabel2">SECTION 29</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Service canadien d’appui aux tribunaux administratifs</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="#h-171514"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="#h-171517"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>382 - </span><a href="#h-171523"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>382 - </span><a href="#h-171524"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>389 - </span><a href="#h-171532"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="#h-171534"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’exportation et l’importation de biens culturels</cite></span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="#h-171538"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la taxe d’accise</cite></span></a>
</li>
<li><span class='sectionRange'>394 - </span><a href="#h-171540"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="#h-171561"><span class="HTitleText4"><cite class="XRefExternalAct">Loi canadienne sur les droits de la personne</cite></span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-171564"><span class="HTitleText4"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>421 - </span><a href="#h-171570"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>428 - </span><a href="#h-171578"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les mesures spéciales d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="#h-171596"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>447 - </span><a href="#h-171599"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal de la concurrence</cite></span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-171602"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les produits agricoles au Canada</cite></span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-171606"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal canadien du commerce extérieur</cite></span></a>
</li>
<li><span class='sectionRange'>458 - </span><a href="#h-171613"><span class="HTitleText4"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>459 - </span><a href="#h-171615"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="#h-171617"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le statut de l’artiste</cite></span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="#h-171621"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’équité en matière d’emploi</cite></span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="#h-171623"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="#h-171626"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-171629"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li>
<li><span class='sectionRange'>469 - </span><a href="#h-171631"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Tribunal des revendications particulières</cite></span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="#h-171634"><span class="HTitleText4"><cite class="XRefExternalAct">Loi n<sup>o</sup> 2 sur le plan d’action économique de 2013</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>480 - </span><a href="#h-171644"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>482 - </span><a href="#h-171647"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>483 - </span><a href="#h-171650"><span class="HLabel2">SECTION 30</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les prêts aux apprentis</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>483 - </span><a href="#h-171651"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>484 - </span><a href="#h-171654"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>484 - </span><a href="#h-171655"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la faillite et l’insolvabilité</cite></span></a>
</li>
<li><span class='sectionRange'>485 - </span><a href="#h-171657"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>486 - </span><a href="#h-171659"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-171663"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-171666"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-171669"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-171671"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-171674"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="#h-171677"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
