<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Flag of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-382663"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-382666"><span class="HTitleText1">Displaying the National Flag</span></a>
</li></ul>
</li></ul>

</nav>

