<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’assurance des anciens combattants</a><ul class="TocIndent"><li><a href="#h-451758"><span class="scheduleLabel"><span class="otherLang" lang="en">SCHEDULE A</span> — ANNEXE A</span> - <span class="scheduleTitleText"> - <span class="otherLang" lang="en">Monthly Premiums for $1,000 Insurance Payable at Death</span></span> - <span class="scheduleTitleText"> - Primes mensuelles par $1,000 d’assurance payable au décès</span></a>
</li>
<li><a href="#h-451769"><span class="scheduleLabel">ANNEXE B</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
