<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le règlement des revendications des Inuvialuit de la région ouest de l’Arctique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-456827"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-456830"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-456842"><span class="HTitleText1">Convention</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-456854"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-456859"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-456862"><span class="HTitleText1">Modification corrélative</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-456864"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

