<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection d’espèces animales ou végétales sauvages et la réglementation de leur commerce international et interprovincial</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-457794"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-457797"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-457808"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-457811"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-457814"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-457817"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-457837"><span class="HTitleText1">Licence fédérale</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-457851"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-457978"><span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-458154"><span class="HTitleText1">Contravention</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-458178"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-458210"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-458212"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

