<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Department of Human Resources Development Act <span class='Repealed'>[Repealed,  2005, c. 34, s. 84]</span></a></li></ul>
</nav>
</div></section>
