<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Elections Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-203471"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-203474"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-2.html#h-203583"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Electoral Rights</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-203635"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Chief Electoral Officer and Staff</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-2.html#h-203636"><span class="HTitleText2">Chief Electoral Officer</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-3.html#h-203779"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="page-3.html#h-203796"><span class="HTitleText2">Advisory Committee of Political Parties</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="page-3.html#h-203808"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Election Officers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="page-3.html#h-203809"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>23.2 - </span><a href="page-4.html#h-203863"><span class="HTitleText2">Field Liaison Officers</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-4.html#h-203893"><span class="HTitleText2">Returning Officers and Assistant Returning Officers</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-5.html#h-203989"><span class="HTitleText2">Election Officers Appointed by Returning Officer</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-5.html#h-204063"><span class="HTitleText2">Equality of Votes</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-204066"><span class="HTitleText2">New Electoral Districts</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-5.html#h-204078"><span class="HTitleText2">Merger of Registered Parties</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-204081"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-5.html#h-204094"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Register of Electors and Register of Future Electors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-5.html#h-204095"><span class="HTitleText2">Maintenance and Communication</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-204118"><span class="HTitleText2">Updates</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-6.html#h-204188"><span class="HTitleText2">Agreements on Giving Information</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-6.html#h-204199"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>56.1 - </span><a href="page-6.html#h-204213"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Conduct of an Election</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56.1 - </span><a href="page-6.html#h-204214"><span class="HTitleText2">Date of General Election</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-7.html#h-204235"><span class="HTitleText2">Writs of Election</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="page-7.html#h-204283"><span class="HTitleText2">Notice of Election by Returning Officer</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-7.html#h-204290"><span class="HTitleText2">Return by Acclamation</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-7.html#h-204298"><span class="HTitleText2">Holding of an Election</span></a>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="page-7.html#h-204313"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Candidates</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="page-7.html#h-204314"><span class="HTitleText2">Qualifications</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-7.html#h-204328"><span class="HTitleText2">Nomination of Candidates</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-8.html#h-204432"><span class="HTitleText2">Rights of Candidates</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-9.html#h-204459"><span class="HTitleText2">Prohibition</span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="page-9.html#h-204475"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Revision of Lists of Electors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>93 - </span><a href="page-9.html#h-204476"><span class="HTitleText2">Preliminary Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-9.html#h-204493"><span class="HTitleText2">Notice of Confirmation of Registration</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-9.html#h-204516"><span class="HTitleText2">Revision Process</span></a>
</li>
<li><span class='sectionRange'>104.1 - </span><a href="page-10.html#h-204603"><span class="HTitleText2">Updated Preliminary Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-10.html#h-204608"><span class="HTitleText2">Revised Lists of Electors and Official Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="page-10.html#h-204629"><span class="HTitleText2">Merger of Polling Divisions</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="page-10.html#h-204635"><span class="HTitleText2">Final Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-10.html#h-204645"><span class="HTitleText2">Use of Lists of Electors</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-10.html#h-204659"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="page-10.html#h-204673"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Preparation for the Vote</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="page-10.html#h-204674"><span class="HTitleText2">List of Election Officers</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-10.html#h-204680"><span class="HTitleText2">Election Materials</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-11.html#h-204724"><span class="HTitleText2">Provision of Election Materials to Election Officers</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-11.html#h-204741"><span class="HTitleText2">Polling Stations</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="page-11.html#h-204801"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="page-11.html#h-204809"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Voting</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="page-11.html#h-204810"><span class="HTitleText2">Voting Opportunities</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="page-11.html#h-204816"><span class="HTitleText2">Polling Day</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="page-11.html#h-204817"><span class="HTitleText3">Hours</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-11.html#h-204835"><span class="HTitleText3">Time to Employees for Voting</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-11.html#h-204850"><span class="HTitleText3">Proceedings at the Poll</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="page-12.html#h-204907"><span class="HTitleText3">Admitting Voters</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-13.html#h-204993"><span class="HTitleText3">Voting Procedure</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-13.html#h-205021"><span class="HTitleText3">Special Voting Procedures</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-13.html#h-205051"><span class="HTitleText3">Transfer Certificates</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-13.html#h-205081"><span class="HTitleText3">Polling Day Registration</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-14.html#h-205125"><span class="HTitleText3">Duties of Election Officers Assigned to Polling Station</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-14.html#h-205142"><span class="HTitleText3">Secrecy</span></a>
</li>
<li><span class='sectionRange'>164.1 - </span><a href="page-14.html#h-205155"><span class="HTitleText3">Audit</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="page-14.html#h-205160"><span class="HTitleText2">Prohibitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>168 - </span><a href="page-14.html#h-205192"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Advance Polling</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="page-14.html#h-205193"><span class="HTitleText2">Establishment of Advance Polling Stations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168.1 - </span><a href="page-14.html#h-1131670"><span class="HTitleText3">Transfer Certificates</span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="page-14.html#h-205211"><span class="HTitleText2">Registration</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-15.html#h-205253"><span class="HTitleText2">Voting Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="page-15.html#h-205333"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Special Voting Rules</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="page-15.html#h-205334"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-16.html#h-205360"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Administration and General Procedures</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-16.html#h-205403"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Canadian Forces Electors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>190 - </span><a href="page-16.html#h-205404"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="page-16.html#h-205409"><span class="HTitleText3">Voting Entitlement</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-16.html#h-1131856"><span class="HTitleText3">Registration</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="page-16.html#h-205490"><span class="HTitleText3">Coordinating Officer</span></a>
</li>
<li><span class='sectionRange'>199.2 - </span><a href="page-16.html#h-1121011"><span class="HTitleText3">Liaison Officers</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-16.html#h-205500"><span class="HTitleText3">Steps to Prepare for Vote</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="page-17.html#h-205514"><span class="HTitleText3">Duties of Commanding Officers</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="page-17.html#h-205555"><span class="HTitleText3">Voting</span></a>
</li></ul>
</li><li><span class='sectionRange'>220 - </span><a href="page-18.html#h-205615"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Electors Resident Outside Canada</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-18.html#h-205684"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Electors Residing in Canada</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="page-19.html#h-205779"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Incarcerated Electors</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="page-20.html#h-205883"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Counting of Votes at the Office of the Chief Electoral Officer</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="page-21.html#h-205946"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Counting of Votes in the Office of the Returning Officer</span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-21.html#h-206002"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Communication of the Results of the Vote</span></a>
</li></ul>
</li><li><span class='sectionRange'>281 - </span><a href="page-21.html#h-206008"><span class="HLabel1">PART 11.1</span> - <span class="HTitleText1">Prohibitions in Relation to Voting</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-22.html#h-206023"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Counting Votes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>283 - </span><a href="page-22.html#h-206024"><span class="HTitleText2">Polling Stations</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="page-23.html#h-206087"><span class="HTitleText2">Advance Polls</span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="page-23.html#h-206099"><span class="HTitleText2">Delivery of Ballot Boxes to Returning Officer</span></a>
</li></ul>
</li><li><span class='sectionRange'>293 - </span><a href="page-23.html#h-206121"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Validation of Results by the Returning Officer</span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="page-23.html#h-206156"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Judicial Recount</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>299 - </span><a href="page-23.html#h-206157"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="page-23.html#h-206163"><span class="HTitleText2">Recount Procedure</span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="page-24.html#h-206241"><span class="HTitleText2">Failure of Judge to Conduct Recount</span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="page-24.html#h-206270"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Return of the Writ</span></a>
</li>
<li><span class='sectionRange'>319 - </span><a href="page-24.html#h-206310"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">Communications</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>319 - </span><a href="page-24.html#h-206311"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>320 - </span><a href="page-25.html#h-206326"><span class="HTitleText2">Election Advertising</span></a>
</li>
<li><span class='sectionRange'>325.1 - </span><a href="page-25.html#h-1132538"><span class="HTitleText2">Online Platforms</span></a>
</li>
<li><span class='sectionRange'>326 - </span><a href="page-25.html#h-206359"><span class="HTitleText2">Election Surveys</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="page-25.html#h-206399"><span class="HTitleText2">Broadcasting outside Canada</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="page-25.html#h-206412"><span class="HTitleText2">Political Broadcasts</span></a>
</li></ul>
</li><li><span class='sectionRange'>348.01 - </span><a href="page-27.html#h-206569"><span class="HLabel1">PART 16.1</span> - <span class="HTitleText1">Voter Contact Calling Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>348.01 - </span><a href="page-27.html#h-206570"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>348.02 - </span><a href="page-27.html#h-206602"><span class="HLabel2">DIVISION 1.1</span> - <span class="HTitleText2">Provision of Voter Contact Calling Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>348.02 - </span><a href="page-27.html#h-206603"><span class="HTitleText3">Agreements Relating to Voter Contact Calling Services</span></a>
</li>
<li><span class='sectionRange'>348.06 - </span><a href="page-27.html#h-206633"><span class="HTitleText3">Filing Obligations — Registration Notices</span></a>
</li>
<li><span class='sectionRange'>348.1 - </span><a href="page-28.html#h-206686"><span class="HTitleText3">Role of the Canadian Radio-television and Telecommunications Commission</span></a>
</li></ul>
</li><li><span class='sectionRange'>348.16 - </span><a href="page-28.html#h-206717"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Scripts, Recordings and Lists of Telephone Numbers</span></a>
</li></ul>
</li><li><span class='sectionRange'>349 - </span><a href="page-28.html#h-206738"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">Third Party Advertising, Partisan Activities and Election Surveys</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>349 - </span><a href="page-28.html#h-1132622"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>349.01 - </span><a href="page-28.html#h-1132650"><span class="HLabel2">DIVISION 0.1</span> - <span class="HTitleText2">Prohibition on Use of Foreign Funds by Third Parties</span></a>
</li>
<li><span class='sectionRange'>349.1 - </span><a href="page-29.html#h-1132690"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Partisan Activities, Partisan Advertising and Election Surveys During Pre-election Period</span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="page-30.html#h-1132894"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Partisan Activities, Election Advertising and Election Surveys During Election Period</span></a>
</li>
<li><span class='sectionRange'>358.1 - </span><a href="page-32.html#h-1133077"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Third Parties’ Bank Accounts, Registry of Third Parties and Third-Party Expenses Returns</span></a>
</li></ul>
</li><li><span class='sectionRange'>363 - </span><a href="page-33.html#h-206929"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">Financial Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>363 - </span><a href="page-33.html#h-206930"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">General Financial Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>363 - </span><a href="page-33.html#h-206931"><span class="HTitleText3">Contributions</span></a>
</li>
<li><span class='sectionRange'>373 - </span><a href="page-34.html#h-207065"><span class="HTitleText3">Loans, Guarantees and Suretyships</span></a>
</li>
<li><span class='sectionRange'>374.1 - </span><a href="page-34.html#h-1133237"><span class="HTitleText3">Expenses</span></a>
</li>
<li><span class='sectionRange'>384 - </span><a href="page-36.html#h-207202"><span class="HTitleText3">Inflation Adjustment Factor</span></a>
</li></ul>
</li><li><span class='sectionRange'>384.1 - </span><a href="page-36.html#h-207209"><span class="HLabel2">DIVISION 1.1</span> - <span class="HTitleText2">Regulated Fundraising Events</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>384.1 - </span><a href="page-36.html#h-207210"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>384.2 - </span><a href="page-36.html#h-207232"><span class="HTitleText3">Publication and Report</span></a>
</li>
<li><span class='sectionRange'>384.4 - </span><a href="page-37.html#h-207311"><span class="HTitleText3">Contributions</span></a>
</li>
<li><span class='sectionRange'>384.5 - </span><a href="page-37.html#h-207316"><span class="HTitleText3">Corrections, Revisions and Extended Reporting Periods</span></a>
</li></ul>
</li><li><span class='sectionRange'>385 - </span><a href="page-37.html#h-207362"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Political Parties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>385 - </span><a href="page-37.html#h-207363"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Registration of Political Parties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>385 - </span><a href="page-37.html#h-207364"><span class="HTitleText4">Application for Registration</span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="page-38.html#h-207455"><span class="HTitleText4">Officers, Registered Agents, Auditors and Members</span></a>
</li>
<li><span class='sectionRange'>405 - </span><a href="page-39.html#h-207591"><span class="HTitleText4">Changes in Information Concerning Parties</span></a>
</li>
<li><span class='sectionRange'>409 - </span><a href="page-39.html#h-207648"><span class="HTitleText4">Deregistration of Registered Parties</span></a>
</li>
<li><span class='sectionRange'>421 - </span><a href="page-40.html#h-207739"><span class="HTitleText4">Merger of Registered Parties</span></a>
</li></ul>
</li><li><span class='sectionRange'>425 - </span><a href="page-40.html#h-207792"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Financial Administration of Registered Parties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>425 - </span><a href="page-40.html#h-207793"><span class="HTitleText4">General</span></a>
</li>
<li><span class='sectionRange'>427 - </span><a href="page-40.html#h-207811"><span class="HTitleText4">Recovery of Claims for Debts</span></a>
</li>
<li><span class='sectionRange'>429.1 - </span><a href="page-40.html#h-1133406"><span class="HTitleText4">Maximum Partisan Advertising Expenses</span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="page-41.html#h-207826"><span class="HTitleText4">Maximum Election Expenses</span></a>
</li>
<li><span class='sectionRange'>432 - </span><a href="page-41.html#h-207849"><span class="HTitleText4">Financial Reporting</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="page-42.html#h-207970"><span class="HTitleText4">Reporting on Expenses</span></a>
</li>
<li><span class='sectionRange'>440 - </span><a href="page-42.html#h-208004"><span class="HTitleText4">Corrections, Revisions and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="page-42.html#h-208059"><span class="HTitleText4">Reimbursement of Election Expenses and Accessibility Expenses</span></a>
</li>
<li><span class='sectionRange'>445 - </span><a href="page-43.html#h-208078"><span class="HTitleText4">Quarterly Allowances</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>447 - </span><a href="page-43.html#h-208114"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Electoral District Associations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>447 - </span><a href="page-43.html#h-208115"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Registration of Electoral District Associations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>447 - </span><a href="page-43.html#h-208116"><span class="HTitleText4">Registration</span></a>
</li>
<li><span class='sectionRange'>456 - </span><a href="page-43.html#h-208178"><span class="HTitleText4">Electoral District Agents and Auditors</span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="page-44.html#h-208237"><span class="HTitleText4">Changes in Information Concerning Registered Associations</span></a>
</li>
<li><span class='sectionRange'>465 - </span><a href="page-44.html#h-208253"><span class="HTitleText4">Deregistration of Registered Associations</span></a>
</li></ul>
</li><li><span class='sectionRange'>474 - </span><a href="page-44.html#h-208331"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Financial Administration of Registered Associations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>474 - </span><a href="page-44.html#h-208332"><span class="HTitleText4">General</span></a>
</li>
<li><span class='sectionRange'>475.1 - </span><a href="page-45.html#h-208350"><span class="HTitleText4">Recovery of Claims for Debts</span></a>
</li>
<li><span class='sectionRange'>475.4 - </span><a href="page-45.html#h-208365"><span class="HTitleText4">Financial Reporting</span></a>
</li>
<li><span class='sectionRange'>475.8 - </span><a href="page-45.html#h-208427"><span class="HTitleText4">Payment of Audit Expenses</span></a>
</li>
<li><span class='sectionRange'>475.9 - </span><a href="page-45.html#h-208435"><span class="HTitleText4">Corrections, Revisions and Extended Reporting Periods</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>476 - </span><a href="page-46.html#h-208490"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Nomination Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>476 - </span><a href="page-46.html#h-208491"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>476.1 - </span><a href="page-46.html#h-208504"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Nomination Contest Report</span></a>
</li>
<li><span class='sectionRange'>476.64 - </span><a href="page-46.html#h-208562"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Financial Administration of Nomination Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>476.64 - </span><a href="page-46.html#h-208563"><span class="HTitleText4">Powers, Duties and Functions of Financial Agent</span></a>
</li>
<li><span class='sectionRange'>476.69 - </span><a href="page-46.html#h-208613"><span class="HTitleText4">Recovery of Claims for Debts</span></a>
</li>
<li><span class='sectionRange'>476.75 - </span><a href="page-47.html#h-208650"><span class="HTitleText4">Nomination Campaign Return</span></a>
</li>
<li><span class='sectionRange'>476.83 - </span><a href="page-48.html#h-208774"><span class="HTitleText4">Corrections, Revisions and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>476.901 - </span><a href="page-48.html#h-1133553"><span class="HTitleText4">Payment of Audit Expenses</span></a>
</li>
<li><span class='sectionRange'>476.91 - </span><a href="page-48.html#h-208860"><span class="HTitleText4">Surplus of Nomination Campaign Funds</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>477 - </span><a href="page-48.html#h-208887"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Candidates</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>477 - </span><a href="page-48.html#h-208888"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Official Agent and Auditor</span></a>
</li>
<li><span class='sectionRange'>477.45 - </span><a href="page-49.html#h-208953"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Financial Administration of Candidates</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>477.45 - </span><a href="page-49.html#h-208954"><span class="HTitleText4">Powers, Duties and Functions of Official Agent</span></a>
</li>
<li><span class='sectionRange'>477.49 - </span><a href="page-49.html#h-209001"><span class="HTitleText4">Election Expenses Limit</span></a>
</li>
<li><span class='sectionRange'>477.53 - </span><a href="page-50.html#h-209062"><span class="HTitleText4">Recovery of Claims for Debts</span></a>
</li>
<li><span class='sectionRange'>477.59 - </span><a href="page-50.html#h-209102"><span class="HTitleText4">Electoral Campaign Return</span></a>
</li>
<li><span class='sectionRange'>477.65 - </span><a href="page-51.html#h-209207"><span class="HTitleText4">Corrections, Revisions and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>477.73 - </span><a href="page-52.html#h-209304"><span class="HTitleText4">Reimbursement of Certain Expenses</span></a>
</li>
<li><span class='sectionRange'>477.8 - </span><a href="page-52.html#h-209377"><span class="HTitleText4">Surplus of Electoral Funds</span></a>
</li>
<li><span class='sectionRange'>477.86 - </span><a href="page-53.html#h-209434"><span class="HTitleText4">Supply and Use of Forms</span></a>
</li></ul>
</li><li><span class='sectionRange'>477.89 - </span><a href="page-53.html#h-209452"><span class="HLabel3">SUBDIVISION C</span> - <span class="HTitleText3">Gifts and Other Advantages</span></a>
</li></ul>
</li><li><span class='sectionRange'>478 - </span><a href="page-53.html#h-209546"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Leadership Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>478.1 - </span><a href="page-53.html#h-209565"><span class="HLabel3">SUBDIVISION A</span> - <span class="HTitleText3">Registration of Leadership Contestants</span></a>
</li>
<li><span class='sectionRange'>478.71 - </span><a href="page-54.html#h-209711"><span class="HLabel3">SUBDIVISION B</span> - <span class="HTitleText3">Financial Administration of Leadership Contestants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>478.71 - </span><a href="page-54.html#h-209712"><span class="HTitleText4">Powers, Duties and Functions of Financial Agent</span></a>
</li>
<li><span class='sectionRange'>478.74 - </span><a href="page-55.html#h-209747"><span class="HTitleText4">Recovery of Claims for Debts</span></a>
</li>
<li><span class='sectionRange'>478.8 - </span><a href="page-55.html#h-209784"><span class="HTitleText4">Leadership Campaign Return</span></a>
</li>
<li><span class='sectionRange'>478.86 - </span><a href="page-56.html#h-209885"><span class="HTitleText4">Corrections, Revisions and Extended Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>478.931 - </span><a href="page-56.html#h-1133794"><span class="HTitleText4">Payment of Audit Expenses</span></a>
</li>
<li><span class='sectionRange'>478.94 - </span><a href="page-57.html#h-209971"><span class="HTitleText4">Surplus of Leadership Campaign Funds</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>479 - </span><a href="page-57.html#h-209996"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>479 - </span><a href="page-57.html#h-209997"><span class="HTitleText2">Peace and Good Order at Elections</span></a>
</li>
<li><span class='sectionRange'>480 - </span><a href="page-57.html#h-210017"><span class="HTitleText2">Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>480 - </span><a href="page-57.html#h-210018"><span class="HTitleText3">General Provisions</span></a>
</li>
<li><span class='sectionRange'>484 - </span><a href="page-57.html#h-210051"><span class="HTitleText3">Offences under Part 3 (Election Officers)</span></a>
</li>
<li><span class='sectionRange'>485 - </span><a href="page-57.html#h-210070"><span class="HTitleText3">Offences under Part 4 (Register of Electors and Register of Future Electors)</span></a>
</li>
<li><span class='sectionRange'>486 - </span><a href="page-57.html#h-210076"><span class="HTitleText3">Offences under Part 6 (Candidates)</span></a>
</li>
<li><span class='sectionRange'>487 - </span><a href="page-58.html#h-210090"><span class="HTitleText3">Offences under Part 7 (Revision of List of Electors)</span></a>
</li>
<li><span class='sectionRange'>488 - </span><a href="page-58.html#h-210100"><span class="HTitleText3">Offences under Part 8 (Preparation for the Vote)</span></a>
</li>
<li><span class='sectionRange'>489 - </span><a href="page-58.html#h-210108"><span class="HTitleText3">Offences under Part 9 (Voting)</span></a>
</li>
<li><span class='sectionRange'>490 - </span><a href="page-58.html#h-210138"><span class="HTitleText3">Offences under Part 10 (Advance Polling)</span></a>
</li>
<li><span class='sectionRange'>491 - </span><a href="page-58.html#h-210147"><span class="HTitleText3">Offences under Part 11 (Special Voting Rules)</span></a>
</li>
<li><span class='sectionRange'>491.1 - </span><a href="page-58.html#h-1133927"><span class="HTitleText3">Offences under Part 11.1 (Prohibitions in relation to Voting)</span></a>
</li>
<li><span class='sectionRange'>492 - </span><a href="page-58.html#h-210165"><span class="HTitleText3">Offences under Part 12 (Counting Votes)</span></a>
</li>
<li><span class='sectionRange'>493 - </span><a href="page-58.html#h-210173"><span class="HTitleText3">Offence under Part 13 (Validation of Results by the Returning Officer)</span></a>
</li>
<li><span class='sectionRange'>494 - </span><a href="page-58.html#h-210176"><span class="HTitleText3">Offences under Part 15 (Return of the Writ)</span></a>
</li>
<li><span class='sectionRange'>495 - </span><a href="page-58.html#h-210181"><span class="HTitleText3">Offences under Part 16 (Communications)</span></a>
</li>
<li><span class='sectionRange'>495.1 - </span><a href="page-59.html#h-210212"><span class="HTitleText3">Offences under Division 2 of Part 16.1 (Scripts and Recordings)</span></a>
</li>
<li><span class='sectionRange'>495.21 - </span><a href="page-59.html#h-210231"><span class="HTitleText3">Offences under Part 17 (Third Party Advertising, Partisan Activities and Election Surveys)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>495.21 - </span><a href="page-59.html#h-1133997"><span class="HTitleText4">Offences under Division 0.1 of Part 17 (Prohibition on Use of Foreign Funds by Third Parties)</span></a>
</li>
<li><span class='sectionRange'>495.3 - </span><a href="page-59.html#h-1134007"><span class="HTitleText4">Offences under Division 1 of Part 17 (Partisan Activities, Partisan Advertising and Election Surveys During Pre-election Period)</span></a>
</li>
<li><span class='sectionRange'>496 - </span><a href="page-59.html#h-1134032"><span class="HTitleText4">Offences under Division 2 of Part 17 (Partisan Activities, Election Advertising and Election Surveys During Election Period)</span></a>
</li>
<li><span class='sectionRange'>496.1 - </span><a href="page-59.html#h-1134052"><span class="HTitleText4">Offences under Division 3 of Part 17 (Third Parties’ Bank Accounts, Registry of Third Parties and Third-Party Expenses Returns)</span></a>
</li></ul>
</li><li><span class='sectionRange'>497 - </span><a href="page-59.html#h-210250"><span class="HTitleText3">Offences under Part 18 (Finance)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>497 - </span><a href="page-59.html#h-210251"><span class="HTitleText4">Offences under Division 1 of Part 18 (General Financial Provisions)</span></a>
</li>
<li><span class='sectionRange'>497.01 - </span><a href="page-59.html#h-210286"><span class="HTitleText4">Offences under Division 1.1 of Part 18 (Regulated Fundraising Events)</span></a>
</li>
<li><span class='sectionRange'>497.1 - </span><a href="page-60.html#h-210304"><span class="HTitleText4">Offences under Division 2 of Part 18 (Political Parties)</span></a>
</li>
<li><span class='sectionRange'>497.2 - </span><a href="page-60.html#h-210352"><span class="HTitleText4">Offences under Division 3 of Part 18 (Electoral District Associations)</span></a>
</li>
<li><span class='sectionRange'>497.3 - </span><a href="page-60.html#h-210392"><span class="HTitleText4">Offences under Division 4 of Part 18 (Nomination Contestants)</span></a>
</li>
<li><span class='sectionRange'>497.4 - </span><a href="page-61.html#h-210440"><span class="HTitleText4">Offences under Division 5 of Part 18 (Candidates)</span></a>
</li>
<li><span class='sectionRange'>497.5 - </span><a href="page-61.html#h-210495"><span class="HTitleText4">Offences under Division 6 of Part 18 (Leadership Contestants)</span></a>
</li></ul>
</li><li><span class='sectionRange'>498 - </span><a href="page-61.html#h-210545"><span class="HTitleText3">Offences under this Part (Enforcement)</span></a>
</li>
<li><span class='sectionRange'>499 - </span><a href="page-62.html#h-210548"><span class="HTitleText3">Offences under Part 21 (General)</span></a>
</li></ul>
</li><li><span class='sectionRange'>500 - </span><a href="page-62.html#h-210556"><span class="HTitleText2">Punishment</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="page-62.html#h-210614"><span class="HTitleText2">Illegal Practices and Corrupt Practices</span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="page-62.html#h-210645"><span class="HTitleText2">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>508.1 - </span><a href="page-63.html#h-1134173"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>508.4 - </span><a href="page-63.html#h-1134186"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>509 - </span><a href="page-63.html#h-210709"><span class="HTitleText2">Commissioner of Canada Elections</span></a>
</li>
<li><span class='sectionRange'>509.3 - </span><a href="page-64.html#h-210738"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>509.6 - </span><a href="page-64.html#h-210754"><span class="HTitleText2">Payments out of Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>510 - </span><a href="page-64.html#h-210761"><span class="HTitleText2">Investigations</span></a>
</li>
<li><span class='sectionRange'>511 - </span><a href="page-64.html#h-1121155"><span class="HTitleText2">Prosecutions</span></a>
</li>
<li><span class='sectionRange'>516 - </span><a href="page-65.html#h-210828"><span class="HTitleText2">Injunctions</span></a>
</li>
<li><span class='sectionRange'>517 - </span><a href="page-65.html#h-210838"><span class="HTitleText2">Compliance Agreements</span></a>
</li>
<li><span class='sectionRange'>521.1 - </span><a href="page-65.html#h-210881"><span class="HTitleText2">Deregistration</span></a>
</li>
<li><span class='sectionRange'>521.11 - </span><a href="page-65.html#h-1134236"><span class="HTitleText2">Proceedings in Respect of a Violation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>521.11 - </span><a href="page-65.html#h-1134237"><span class="HTitleText3">Notice of Violation</span></a>
</li>
<li><span class='sectionRange'>521.13 - </span><a href="page-66.html#h-1134262"><span class="HTitleText3">Undertakings</span></a>
</li>
<li><span class='sectionRange'>521.14 - </span><a href="page-66.html#h-1134280"><span class="HTitleText3">Review</span></a>
</li>
<li><span class='sectionRange'>521.16 - </span><a href="page-66.html#h-1134309"><span class="HTitleText3">Consequences</span></a>
</li>
<li><span class='sectionRange'>521.21 - </span><a href="page-66.html#h-1134347"><span class="HTitleText3">Miscellaneous</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>522 - </span><a href="page-67.html#h-210907"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">Contested Elections</span></a>
</li>
<li><span class='sectionRange'>533 - </span><a href="page-67.html#h-210974"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>533 - </span><a href="page-67.html#h-210975"><span class="HTitleText2">Reports of Chief Electoral Officer</span></a>
</li>
<li><span class='sectionRange'>537.1 - </span><a href="page-68.html#h-1121230"><span class="HTitleText2">Report of Commissioner</span></a>
</li>
<li><span class='sectionRange'>538 - </span><a href="page-68.html#h-211021"><span class="HTitleText2">Polling Divisions</span></a>
</li>
<li><span class='sectionRange'>539 - </span><a href="page-68.html#h-211033"><span class="HTitleText2">Amendments to Schedule 3</span></a>
</li>
<li><span class='sectionRange'>539.1 - </span><a href="page-68.html#h-211043"><span class="HTitleText2">Custody of Election Documents and Documents Relating to the Register of Electors</span></a>
</li>
<li><span class='sectionRange'>542 - </span><a href="page-68.html#h-211076"><span class="HTitleText2">Fees and Expenses of Election Officers</span></a>
</li>
<li><span class='sectionRange'>547 - </span><a href="page-69.html#h-211105"><span class="HTitleText2">Notice</span></a>
</li>
<li><span class='sectionRange'>549 - </span><a href="page-69.html#h-211116"><span class="HTitleText2">Solemn Declarations and Affidavits</span></a>
</li>
<li><span class='sectionRange'>550 - </span><a href="page-69.html#h-211126"><span class="HTitleText2">Signed Pledges by Candidates Prohibited</span></a>
</li>
<li><span class='sectionRange'>551 - </span><a href="page-69.html#h-211129"><span class="HTitleText2">By-Elections</span></a>
</li>
<li><span class='sectionRange'>552 - </span><a href="page-69.html#h-211132"><span class="HTitleText2">Forms</span></a>
</li>
<li><span class='sectionRange'>553 - </span><a href="page-69.html#h-211137"><span class="HTitleText2">Payments out of Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>554 - </span><a href="page-69.html#h-211148"><span class="HTitleText2">Amendments</span></a>
</li>
<li><span class='sectionRange'>555 - </span><a href="page-69.html#h-1134461"><span class="HTitleText2">Judicial Review</span></a>
</li></ul>
</li><li><a href="page-70.html#h-1134471"><span class="scheduleLabel">SCHEDULE 1</span></a>
</li>
<li><a href="page-71.html#h-211200"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-72.html#h-211268"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - List of Electoral Districts</span></a>
</li>
<li><a href="page-73.html#h-211319"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li></ul>
</li></ul>

</nav>

