<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le pilotage</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-384863"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-384868"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-384878"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Pilotage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-384879"><span class="HTitleText2">Définitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>3 - </span><a href="#h-384890"><span class="HTitleText1">Administrations de pilotage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-384891"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-384922"><span class="HTitleText2">Fonctionnement</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-385005"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-385058"><span class="HTitleText1">Brevets et certificats</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-385161"><span class="HTitleText1">Tarifs</span></a>
</li>
<li><span class='sectionRange'>36.01 - </span><a href="#h-385206"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-385223"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-385257"><span class="HTitleText1">Écluse de Saint-Lambert</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-385268"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-385298"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-385309"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-385317"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Régime de pension des pilotes du Bas Saint-Laurent</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-385318"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-385343"><span class="HTitleText2">Application de la Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-385348"><span class="HTitleText2">Application de la Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-385388"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><a href="#h-385394"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
