<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Transportation of Dangerous Goods Act, 1992</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-452136"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-452139"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-452178"><span class="HTitleText1">Application of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-452193"><span class="HTitleText1">Agreement with Provinces</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-452201"><span class="HTitleText1">Safety and Security</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-452202"><span class="HTitleText2">Safety Requirements, Security Requirements, Safety Standards and Safety Marks</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-452215"><span class="HTitleText2">Compliance Marks and Dangerous Goods Marks</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="page-1.html#h-452224"><span class="HTitleText1">Emergency Response Assistance Plans and Security Plans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-1.html#h-452225"><span class="HTitleText2">Emergency Response Assistance Plans</span></a>
</li>
<li><span class='sectionRange'>7.3 - </span><a href="page-2.html#h-452260"><span class="HTitleText2">Security Plans</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-2.html#h-452268"><span class="HTitleText1">Means of Containment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-452284"><span class="HTitleText1">Inspectors</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-452310"><span class="HTitleText1">Financial Responsibility</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-452320"><span class="HTitleText1">Monitoring Compliance</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-452373"><span class="HTitleText1">Duty to Respond</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-452383"><span class="HTitleText1">Intervention</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-452398"><span class="HTitleText1">Personal Liability</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-452406"><span class="HTitleText1">Inquiries</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-452422"><span class="HTitleText1">Recovery of Costs and Expenses</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-452442"><span class="HTitleText1">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-452469"><span class="HTitleText1">Research and Advice</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-3.html#h-452486"><span class="HTitleText1">Regulations, Measures and Orders</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-4.html#h-452635"><span class="HTitleText1">Certificates and Directions</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-452664"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-452716"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>43 to 45 - </span><a href="page-5.html#h-452728"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-452730"><span class="HTitleText1">Bill C-13</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-452732"><span class="HTitleText1">Repeal</span></a>
</li>
<li><a href="page-6.html#h-452735"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

