<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Lieutenant Governors Superannuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-345479"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-345484"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-345503"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Superannuation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-345504"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-345527"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-345537"><span class="HTitleText2">Election not to Contribute</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-345549"><span class="HTitleText2">Diversion of Payments</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-345557"><span class="HTitleText2">Surviving Spouse</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-345580"><span class="HTitleText2">Death Benefit</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-345585"><span class="HTitleText2">Payments</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-345596"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-1.html#h-345612"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Supplementary Retirement Benefits Contributions</span></a>
</li></ul>
</li></ul>

</nav>

