<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée mondiale de sensibilisation à l’autisme</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-454229"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-454232"><span class="HTitleText1">Journée mondiale de sensibilisation à l’autisme</span></a>
</li></ul>
</li></ul>

</nav>

