<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Freshwater Fish Marketing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Freshwater Fish Marketing Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Constitution of the Corporation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText2">Purpose and Powers</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText2">Organization and Staff</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText2">Financial</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Advisory Committee</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Regulation of Interprovincial and Export Trade</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Interprovincial and Export Trade</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Duties and Powers of the Corporation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2">Agreements Respecting Participation</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-16"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-17"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Annual Report</span></a>
</li>
<li><a href="#h-231155"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
