<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Mutual Legal Assistance in Criminal Matters Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Schedule</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Publication of Agreements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Administrative Arrangements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Foreign Investigations or Other Proceedings in Respect of Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText2">Implementation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Fines</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="#h-10"><span class="HTitleText2">International Criminal Court</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="#h-11"><span class="HTitleText2">Foreign Orders for Restraint, Seizure and Forfeiture of Property in Canada</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-12"><span class="HTitleText2">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText2">Evidence for Use Abroad</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-14"><span class="HTitleText2">Transfer of Detained Persons</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Lending Exhibits</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText2">Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-17"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Admissibility in Canada of Evidence Obtained Abroad Pursuant to an Agreement</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-18"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Implementation of Agreements in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-19"><span class="HTitleText2">Special Authorization to Come Into Canada</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-20"><span class="HTitleText2">Detention in Canada</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-21"><span class="HTitleText2">Determination of the Validity of Refusals</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-22"><span class="HTitleText2">Privilege for Foreign Records</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-23"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Consequential Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-24"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-25"><span class="HTitleText2">Crown Liability Act</span></a>
</li>
<li><span class='sectionRange'>47 and 48 - </span><a href="#h-26"><span class="HTitleText2">Immigration Act</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-27"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-28"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Designated States or Entities</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
