<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Service Employment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Public Service Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Commission Established</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText2">General Powers and Duties of Commission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Delegation of Authority</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Records and Inquiries</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Appointment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Authority to Appoint</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Appointments</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Standards and Criteria</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText2">Competitions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="#h-14"><span class="HTitleText2">Casual Employment</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Employment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Tenure</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-17"><span class="HTitleText2">Probation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-18"><span class="HTitleText2">Lay-Offs</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-19"><span class="HTitleText2">Leave of Absence</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-20"><span class="HTitleText2">Political Partisanship</span></a>
</li></ul>
</li><li><span class='sectionRange'>34.1 - </span><a href="#h-21"><span class="HLabel1">PART III.1</span> - <span class="HTitleText1">Deployment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34.1 - </span><a href="#h-22"><span class="HTitleText2">Right to Deploy</span></a>
</li>
<li><span class='sectionRange'>34.2 - </span><a href="#h-23"><span class="HTitleText2">Conditions</span></a>
</li>
<li><span class='sectionRange'>34.3 - </span><a href="#h-24"><span class="HTitleText2">Recourse on Deployment</span></a>
</li>
<li><span class='sectionRange'>34.6 - </span><a href="#h-25"><span class="HTitleText2">Provisions not Applicable</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-26"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-27"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>37.3 - </span><a href="#h-28"><span class="HTitleText2">Block Transfers</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-29"><span class="HTitleText2">Rate of Pay on Appointment</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-30"><span class="HTitleText2">Ministers’ Staffs</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-31"><span class="HTitleText2">Other Public Officials</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-32"><span class="HTitleText2">Exclusions</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-33"><span class="HTitleText2">Irregularities and Fraudulent Practices</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-34"><span class="HTitleText2">Oaths</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-35"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-36"><span class="HTitleText2">Application of Act</span></a>
</li></ul>
</li><li><a href="#h-37"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Oath or Solemn Affirmation of Office of Commissioner</span></a>
</li>
<li><a href="#h-38"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Definitions</span></a>
</li>
<li><a href="#h-39"><span class="scheduleLabel">SCHEDULE III</span> <span class="scheduleTitleText"> - Oath or Solemn Affirmation of Office and Secrecy</span></a>
</li>
<li><a href="#h-40"><span class="scheduleLabel">SCHEDULE IV</span> <span class="scheduleTitleText"> - Summons to an Inquiry</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
