<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des obtentions végétales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-383566"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-383569"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-383608"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-383611"><span class="HTitleText1">Conditions de protection</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-383635"><span class="HTitleText1">Droits protégés</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-383694"><span class="HTitleText1">Demande de certificat d’obtention</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-383747"><span class="HTitleText1">Dénomination</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-383773"><span class="HTitleText1">Traitement de la demande</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-383785"><span class="HTitleText1">Protection provisoire</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-383804"><span class="HTitleText1">Examen et règlement de la demande</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-383848"><span class="HTitleText1">Délivrance du certificat d’obtention</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-383869"><span class="HTitleText1">Maintien du matériel de multiplication</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-383879"><span class="HTitleText1">Cession du certificat</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-383889"><span class="HTitleText1">Licence obligatoire</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-383910"><span class="HTitleText1">Annulations et révocations</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-383939"><span class="HTitleText1">Renonciation au certificat</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-383947"><span class="HTitleText1">Mandataires</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-383963"><span class="HTitleText1">Moyens de réparation</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-384057"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-384097"><span class="HTitleText1">Bureau de la protection des obtentions végétales</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-384137"><span class="HTitleText1">Archives</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-384198"><span class="HTitleText1">Publication</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-384232"><span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-384249"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-384281"><span class="HTitleText1">Loi sur les semences</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-384289"><span class="HTitleText1">Examen de la loi</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-384306"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-384319"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

