<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Consumer Product Safety Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-44273"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-44276"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-44309"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-44312"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-44328"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-44351"><span class="HTitleText1">Tests, Studies and Compilation of Information</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-44357"><span class="HTitleText1">Preparing and Maintaining Documents</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-44373"><span class="HTitleText1">Duties in the Event of an Incident</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-44390"><span class="HTitleText1">Disclosure of Information by the Minister</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-44407"><span class="HTitleText1">Inspectors</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-44419"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-44454"><span class="HTitleText1">Procedures Following Seizure</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="page-2.html#h-44481"><span class="HTitleText1">Removal or Forfeiture of Unlawful Imports</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-44497"><span class="HTitleText1">Analysis</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-44505"><span class="HTitleText1">Orders for Recalls and Taking Measures</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-44530"><span class="HTitleText1">Review of Orders for Recalls and Taking Measures</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-3.html#h-44558"><span class="HTitleText1">Injunction</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="page-3.html#h-44566"><span class="HTitleText1">Costs</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-3.html#h-44583"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-3.html#h-44651"><span class="HTitleText1">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-44669"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-4.html#h-44707"><span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="page-4.html#h-44708"><span class="HTitleText2">Violation</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-4.html#h-44711"><span class="HTitleText2">Powers of the Governor in Council and Minister</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-4.html#h-44725"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-4.html#h-44736"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-4.html#h-44749"><span class="HTitleText2">Compliance Agreements</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-4.html#h-44783"><span class="HTitleText2">Review by the Minister</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-4.html#h-44797"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-4.html#h-44815"><span class="HTitleText2">Rules of Law About Violations</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-5.html#h-44835"><span class="HTitleText2">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-5.html#h-44840"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-5.html#h-44856"><span class="HTitleText1">Consequential Amendments to the Hazardous Products Act</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-5.html#h-44861"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-6.html#h-44865"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-7.html#h-44890"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

