<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Association of Former Parliamentarians Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-60944"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-60947"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-60954"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-60959"><span class="HTitleText1">Objects</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-60969"><span class="HTitleText1">Powers</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-60987"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-61001"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-61019"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-61033"><span class="HTitleText1">Transition</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-61039"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

