<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de l’impôt sur le revenu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-272941"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-272946"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-272947"><span class="HLabel2">SECTION A</span> - <span class="HTitleText2">Assujettissement à l’impôt</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-272960"><span class="HLabel2">SECTION B</span> - <span class="HTitleText2">Calcul du revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-272961"><span class="HTitleText3">Règles fondamentales</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-272991"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Revenu ou perte provenant d’une charge ou d’un emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-272992"><span class="HTitleText4">Règles fondamentales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-273000"><span class="HTitleText4">Éléments à inclure</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-273335"><span class="HTitleText4">Déductions</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-273545"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Revenu ou perte provenant d’une entreprise ou d’un bien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-273546"><span class="HTitleText4">Règles fondamentales</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-273667"><span class="HTitleText4">Éléments à inclure</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-274979"><span class="HTitleText4">Déductions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-276385"><span class="HTitleText4">Cessation de l’exploitation d’une entreprise</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-276428"><span class="HTitleText4">Cas spéciaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-277155"><span class="HLabel3">SOUS-SECTION C</span> - <span class="HTitleText3">Gains en capital imposables et pertes en capital déductibles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47.1 - </span><a href="#h-278100"><span class="HTitleText4">Régimes de placements en titres indexés</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-278998"><span class="HLabel3">SOUS-SECTION D</span> - <span class="HTitleText3">Autres sources de revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56.4 - </span><a href="#h-279265"><span class="HTitleText4">Clauses restrictives</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-279469"><span class="HLabel3">SOUS-SECTION E</span> - <span class="HTitleText3">Déductions dans le calcul du revenu</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-281634"><span class="HLabel3">SOUS-SECTION F</span> - <span class="HTitleText3">Règles relatives au calcul du revenu</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-283329"><span class="HLabel3">SOUS-SECTION G</span> - <span class="HTitleText3">Sommes exclues du calcul du revenu</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-283422"><span class="HLabel3">SOUS-SECTION H</span> - <span class="HTitleText3">Les sociétés résidant au Canada et leurs actionnaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>86.1 - </span><a href="#h-283981"><span class="HTitleText4">Distributions d’actions de l’étranger</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-285260"><span class="HLabel3">SOUS-SECTION I</span> - <span class="HTitleText3">Actionnaires de sociétés ne résidant pas au Canada</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-287510"><span class="HLabel3">SOUS-SECTION J</span> - <span class="HTitleText3">Les sociétés de personnes et leurs associés</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-287918"><span class="HLabel3">SOUS-SECTION K</span> - <span class="HTitleText3">Les fiducies et leurs bénéficiaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-288759"><span class="HLabel2">SECTION C</span> - <span class="HTitleText2">Calcul du revenu imposable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110.2 - </span><a href="#h-289007"><span class="HTitleText3">Paiements forfaitaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>115 - </span><a href="#h-290034"><span class="HLabel2">SECTION D</span> - <span class="HTitleText2">Revenu imposable gagné au Canada par des non-résidents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>115.2 - </span><a href="#h-290131"><span class="HTitleText3">Non-résidents et fournisseurs de services de placement canadiens</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-290277"><span class="HLabel2">SECTION E</span> - <span class="HTitleText2">Calcul de l’impôt</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-290278"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Règles applicables aux particuliers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117.1 - </span><a href="#h-290302"><span class="HTitleText4">Rajustement annuel des déductions et autres sommes</span></a>
</li>
<li><span class='sectionRange'>120.31 - </span><a href="#h-291474"><span class="HTitleText4">Paiements forfaitaires</span></a>
</li>
<li><span class='sectionRange'>120.4 - </span><a href="#h-291492"><span class="HTitleText4">Impôt sur le revenu fractionné</span></a>
</li></ul>
</li><li><span class='sectionRange'>122.6 - </span><a href="#h-292047"><span class="HLabel3">SOUS-SECTION A.1</span> - <span class="HTitleText3">Allocation canadienne pour enfants</span></a>
</li>
<li><span class='sectionRange'>122.7 - </span><a href="#h-292208"><span class="HLabel3">SOUS-SECTION A.2</span> - <span class="HTitleText3">Allocation canadienne pour les travailleurs</span></a>
</li>
<li><span class='sectionRange'>122.8 - </span><a href="#h-292303"><span class="HLabel3">SOUS-SECTION A.3</span> - <span class="HTitleText3">Incitatif à agir pour le climat</span></a>
</li>
<li><span class='sectionRange'>122.9 - </span><a href="#h-292358"><span class="HLabel3">SOUS-SECTION A.4</span> - <span class="HTitleText3">Crédit d’impôt pour fournitures scolaires</span></a>
</li>
<li><span class='sectionRange'>122.91 - </span><a href="#h-1161785"><span class="HLabel3">SOUS-SECTION A.5</span> - <span class="HTitleText3">Crédit canadien pour la formation</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-292401"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Règles applicable aux sociétés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123.4 - </span><a href="#h-292428"><span class="HTitleText4">Réductions de l’impôt des sociétés</span></a>
</li>
<li><span class='sectionRange'>125.4 - </span><a href="#h-292813"><span class="HTitleText4">Crédit d’impôt pour production cinématographique ou magnétoscopique canadienne</span></a>
</li>
<li><span class='sectionRange'>125.5 - </span><a href="#h-292898"><span class="HTitleText4">Crédit d’impôt pour services de production cinématographique ou magnétoscopique</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-292958"><span class="HLabel3">SOUS-SECTION C</span> - <span class="HTitleText3">Règles applicables à tous les contribuables</span></a>
</li></ul>
</li><li><span class='sectionRange'>127.5 - </span><a href="#h-294257"><span class="HLabel2">SECTION E.1</span> - <span class="HTitleText2">Impôt minimum</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-294419"><span class="HLabel2">SECTION F</span> - <span class="HTitleText2">Règles spéciale applicables en certains cas</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="#h-294420"><span class="HTitleText3">Faillites</span></a>
</li>
<li><span class='sectionRange'>128.1 - </span><a href="#h-294494"><span class="HTitleText3">Changement de résidence</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-294741"><span class="HTitleText3">Sociétés privées</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-294898"><span class="HTitleText3">Sociétés de placement</span></a>
</li>
<li><span class='sectionRange'>130.1 - </span><a href="#h-294945"><span class="HTitleText3">Sociétés de placement hypothécaire</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-295017"><span class="HTitleText3">Sociétés de placement à capital variable</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-295178"><span class="HTitleText3">Fiducies de fonds commun de placement</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-295444"><span class="HTitleText3">Sociétés de placement appartenant à des non-résidents</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-295601"><span class="HTitleText3">Ristournes</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-295660"><span class="HTitleText3">Coopératives agricoles — ristournes à imposition différée</span></a>
</li>
<li><span class='sectionRange'>135.2 - </span><a href="#h-295734"><span class="HTitleText3">Prorogation de la Commission canadienne du blé</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-295909"><span class="HTitleText3">Sociétés coopératives</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-295921"><span class="HTitleText3">Caisses de crédit, caisses d’épargne et de crédit et compagnies d’assurance-dépôts</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-296124"><span class="HTitleText3">Compagnies d’assurance</span></a>
</li>
<li><span class='sectionRange'>139.1 - </span><a href="#h-296658"><span class="HTitleText3">Démutualisation des compagnies d’assurance</span></a>
</li>
<li><span class='sectionRange'>142.2 - </span><a href="#h-296899"><span class="HTitleText3">Institutions Financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>142.2 - </span><a href="#h-296900"><span class="HTitleText4">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>142.3 - </span><a href="#h-296959"><span class="HTitleText4">Revenu provenant de titres de créance déterminés</span></a>
</li>
<li><span class='sectionRange'>142.4 - </span><a href="#h-296976"><span class="HTitleText4">Disposition de titres de créance déterminés</span></a>
</li>
<li><span class='sectionRange'>142.5 - </span><a href="#h-297062"><span class="HTitleText4">Biens évalués à la valeur du marché</span></a>
</li>
<li><span class='sectionRange'>142.6 - </span><a href="#h-297192"><span class="HTitleText4">Autres règles</span></a>
</li>
<li><span class='sectionRange'>142.7 - </span><a href="#h-297291"><span class="HTitleText4">Transformation d’une filiale de banque étrangère en succursale</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-297411"><span class="HTitleText4">Organismes communautaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>143.2 - </span><a href="#h-297547"><span class="HTitleText3">Coûts des abris fiscaux déterminés et dettes à recours limité relatives aux arrangements de don</span></a>
</li>
<li><span class='sectionRange'>143.3 - </span><a href="#h-297627"><span class="HTitleText3">Dépenses — restrictions</span></a>
</li>
<li><span class='sectionRange'>143.4 - </span><a href="#h-297658"><span class="HTitleText3">Dépenses — limite relative à un montant éventuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-297693"><span class="HLabel2">SECTION G</span> - <span class="HTitleText2">Régimes de participation différée et autres arrangements spéciaux relatifs aux revenus</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="#h-297694"><span class="HTitleText3">Régimes de participation des employés aux bénéfices</span></a>
</li>
<li><span class='sectionRange'>144.1 - </span><a href="#h-297798"><span class="HTitleText3">Fiducie de soins de santé au bénéfice d’employés</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-297883"><span class="HTitleText3">Régimes enregistrés de prestations supplémentaires de chômage</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-297899"><span class="HTitleText3">Régimes enregistrés d’épargne-retraite</span></a>
</li>
<li><span class='sectionRange'>146.01 - </span><a href="#h-298262"><span class="HTitleText3">Régime d’accession à la propriété</span></a>
</li>
<li><span class='sectionRange'>146.02 - </span><a href="#h-298418"><span class="HTitleText3">Régime d’éducation permanente</span></a>
</li>
<li><span class='sectionRange'>146.1 - </span><a href="#h-298524"><span class="HTitleText3">Régimes enregistrés d’épargne-études</span></a>
</li>
<li><span class='sectionRange'>146.2 - </span><a href="#h-298726"><span class="HTitleText3">Comptes d’épargne libre d’impôt</span></a>
</li>
<li><span class='sectionRange'>146.3 - </span><a href="#h-298818"><span class="HTitleText3">Fonds enregistrés de revenu de retraite</span></a>
</li>
<li><span class='sectionRange'>146.4 - </span><a href="#h-299040"><span class="HTitleText3">Régime enregistré d’épargne-invalidité</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-299300"><span class="HTitleText3">Régimes de participation différée aux bénéfices</span></a>
</li>
<li><span class='sectionRange'>147.1 - </span><a href="#h-299505"><span class="HTitleText3">Régimes de pension agréés</span></a>
</li>
<li><span class='sectionRange'>147.5 - </span><a href="#h-299901"><span class="HTitleText3">Régimes de pension agréés collectifs</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-300126"><span class="HTitleText3">Polices d’assurance-vie</span></a>
</li>
<li><span class='sectionRange'>148.1 - </span><a href="#h-300367"><span class="HTitleText3">Arrangements de services funéraires</span></a>
</li></ul>
</li><li><span class='sectionRange'>149 - </span><a href="#h-300420"><span class="HLabel2">SECTION H</span> - <span class="HTitleText2">Exemptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="#h-300421"><span class="HTitleText3">Exemptions diverses</span></a>
</li>
<li><span class='sectionRange'>149.1 - </span><a href="#h-300686"><span class="HTitleText3">Donataires reconnus</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-301050"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Déclarations, cotisations, paiement et appels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-301051"><span class="HTitleText3">Déclarations</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-301136"><span class="HTitleText3">Estimation de l’impôt</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-301141"><span class="HTitleText3">Cotisation</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-301315"><span class="HTitleText3">Paiement de l’impôt</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-301775"><span class="HTitleText3">Intérêts</span></a>
</li>
<li><span class='sectionRange'>161.1 - </span><a href="#h-301877"><span class="HTitleText3">Compensation des intérêts créditeurs et des intérêts débiteurs</span></a>
</li>
<li><span class='sectionRange'>161.3 - </span><a href="#h-301924"><span class="HTitleText3">Sommes minimes</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-301936"><span class="HTitleText3">Pénalités</span></a>
</li>
<li><span class='sectionRange'>163.2 - </span><a href="#h-302200"><span class="HTitleText3">Information trompeuse en matière fiscale fournie par des tiers</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-302317"><span class="HTitleText3">Remboursements</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-302462"><span class="HTitleText3">Opposition à la cotisation</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-302516"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-302583"><span class="HTitleText3">Révocation de l’enregistrement de certaines oeuvres et associations</span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="#h-302606"><span class="HLabel2">SECTION J</span> - <span class="HTitleText2">Appels auprès de la Cour canadienne de l’impôt et de la Cour d’appel fédérale</span></a>
</li></ul>
</li><li><span class='sectionRange'>180.01 - </span><a href="#h-302783"><span class="HLabel1">PARTIE I.01</span> - <span class="HTitleText1">Impôt relatif au report des avantages liés aux options d’achat d’actions</span></a>
</li>
<li><span class='sectionRange'>180.1 - </span><a href="#h-302812"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Impôt supplémentaire (revenus des particuliers)</span></a>
</li>
<li><span class='sectionRange'>180.2 - </span><a href="#h-302816"><span class="HLabel1">PARTIE I.2</span> - <span class="HTitleText1">Impôt sur les prestations de sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-302867"><span class="HLabel1">PARTIE I.3</span> - <span class="HTitleText1">Impôt des grandes sociétés</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-303159"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">[Abrogée, 2017, ch. 20, art. 27]</span></a>
</li>
<li><span class='sectionRange'>183.1 - </span><a href="#h-303166"><span class="HLabel1">PARTIE II.1</span> - <span class="HTitleText1">Impôt sur certaines distributions de surplus</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-303202"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Impôt supplémentaire sur les excédents résultant d’un choix</span></a>
</li>
<li><span class='sectionRange'>185.1 - </span><a href="#h-303254"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Impôt supplémentaire sur les désignations excessives de dividendes déterminés</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-303309"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Impôt sur les dividendes imposables reçus par les sociétés privées</span></a>
</li>
<li><span class='sectionRange'>187.1 - </span><a href="#h-303375"><span class="HLabel1">PARTIE IV.1</span> - <span class="HTitleText1">Imposition des dividendes reçus par des sociétés sur certaines actions privilégiées</span></a>
</li>
<li><span class='sectionRange'>187.7 - </span><a href="#h-303421"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Impôt et pénalités relatifs aux donataires reconnus</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-303662"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Impôt des institutions financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>190.1 - </span><a href="#h-303683"><span class="HTitleText2">Calcul de l’impôt</span></a>
</li>
<li><span class='sectionRange'>190.2 - </span><a href="#h-303820"><span class="HTitleText2">Dispositions d’ordre administratif</span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="#h-303845"><span class="HLabel1">PARTIE VI.1</span> - <span class="HTitleText1">Imposition des sociétés versant des dividendes sur des actions privilégiées imposables</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-304003"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Impôt remboursable aux sociétés émettant des actions admissibles</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-304081"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Impôt sur les sociétés remboursable au titre du crédit d’impôt pour des activités de recherche scientifique et de développement expérimental</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-304173"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Impôt sur la déduction visée à l’article 66.5</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-304187"><span class="HLabel1">PARTIE IX.1</span> - <span class="HTitleText1">Impôt des sociétés de personnes intermédiaires de placement déterminées</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-304228"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Impôts sur les régimes de participation différée aux bénéfices et sur les régimes dont l’agrément est retiré</span></a>
</li>
<li><span class='sectionRange'>204.1 - </span><a href="#h-304395"><span class="HLabel1">PARTIE X.1</span> - <span class="HTitleText1">Impôt frappant les excédents de contribution aux régimes de revenu différé</span></a>
</li>
<li><span class='sectionRange'>204.4 - </span><a href="#h-304518"><span class="HLabel1">PARTIE X.2</span> - <span class="HTitleText1">Impôt sur les placements enregistrés</span></a>
</li>
<li><span class='sectionRange'>204.8 - </span><a href="#h-304612"><span class="HLabel1">PARTIE X.3</span> - <span class="HTitleText1">Sociétés à capital de risque de travailleurs</span></a>
</li>
<li><span class='sectionRange'>204.9 - </span><a href="#h-304932"><span class="HLabel1">PARTIE X.4</span> - <span class="HTitleText1">Impôt sur les versements excédentaires aux régimes enregistrés d’épargne-études</span></a>
</li>
<li><span class='sectionRange'>204.94 - </span><a href="#h-305009"><span class="HLabel1">PARTIE X.5</span> - <span class="HTitleText1">Paiements dans le cadre de régimes enregistrés d’épargne-études</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-305038"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">[Abrogée, 2017, ch. 33, art. 66]</span></a>
</li>
<li><span class='sectionRange'>207.01 - </span><a href="#h-305060"><span class="HLabel1">PARTIE XI.01</span> - <span class="HTitleText1">Impôts relatifs aux régimes enregistrés</span></a>
</li>
<li><span class='sectionRange'>207.1 - </span><a href="#h-305392"><span class="HLabel1">PARTIE XI.1</span> - <span class="HTitleText1">Impôt relatif aux régimes de revenu différé et à d’autres personnes exonérées d’impôt</span></a>
</li>
<li><span class='sectionRange'>207.3 - </span><a href="#h-305417"><span class="HLabel1">PARTIE XI.2</span> - <span class="HTitleText1">Impôt sur la disposition de certains biens</span></a>
</li>
<li><span class='sectionRange'>207.5 - </span><a href="#h-305444"><span class="HLabel1">PARTIE XI.3</span> - <span class="HTitleText1">Impôt sur les conventions de retraite</span></a>
</li>
<li><span class='sectionRange'>207.8 - </span><a href="#h-305600"><span class="HLabel1">PARTIE XI.4</span> - <span class="HTitleText1">Impôt sur les excédents RPEB</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-305628"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Impôt relatif à certains impôts, loyers, à certaines redevances, etc. versés à un gouvernement par une personne exonérée d’impôt</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-305632"><span class="HLabel1">PARTIE XII.1</span> - <span class="HTitleText1">Impôt sur les revenus miniers et pétroliers tirés de biens restreints</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-305680"><span class="HLabel1">PARTIE XII.2</span> - <span class="HTitleText1">Impôt sur le revenu distribué de certaines fiducies</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-305788"><span class="HLabel1">PARTIE XII.3</span> - <span class="HTitleText1">Impôt sur le revenu de placement des assureurs sur la vie</span></a>
</li>
<li><span class='sectionRange'>211.6 - </span><a href="#h-305928"><span class="HLabel1">PARTIE XII.4</span> - <span class="HTitleText1">Impôt des fiducies pour l’environnement admissible</span></a>
</li>
<li><span class='sectionRange'>211.7 - </span><a href="#h-305989"><span class="HLabel1">PARTIE XII.5</span> - <span class="HTitleText1">Recouvrement du crédit d’impôt relatif à un fonds de travailleurs</span></a>
</li>
<li><span class='sectionRange'>211.91 - </span><a href="#h-306054"><span class="HLabel1">PARTIE XII.6</span> - <span class="HTitleText1">Impôt sur les actions accréditives</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-306080"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Impôt sur le revenu de personnes non-résidentes provenant du Canada</span></a>
</li>
<li><span class='sectionRange'>218.2 - </span><a href="#h-307185"><span class="HLabel1">PARTIE XIII.1</span> - <span class="HTitleText1">Impôt supplémentaire des banques étrangères autorisées</span></a>
</li>
<li><span class='sectionRange'>218.3 - </span><a href="#h-307206"><span class="HLabel1">PARTIE XIII.2</span> - <span class="HTitleText1">Placements de non-résidents dans les fonds communs de placement canadiens</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-307255"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Impôt supplémentaire des sociétés non-résidentes</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-307396"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Application et exécution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-307397"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-307593"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-308008"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-308732"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-309055"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>244.1 - </span><a href="#h-309112"><span class="HLabel1">PARTIE XV.1</span> - <span class="HTitleText1">Déclaration des télévirements</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-309199"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Évitement fiscal</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-309244"><span class="HLabel1">PARTIE XVI.1</span> - <span class="HTitleText1">Prix de transfert</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-309354"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-311700"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Processus élargi de déclaration de renseignements</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-311834"><span class="HLabel1">PARTIE XIX</span> - <span class="HTitleText1">Norme commune de déclaration</span></a>
</li>
<li><a href="#h-312390"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Sociétés visées</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
