<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nunavut Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Establishment and Government</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Establishment of Nunavut</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Seat of Government</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Executive Power</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText3">Commissioner of Nunavut</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText3">Executive Council of Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Legislative Power</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText3">Legislature for Nunavut</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-11"><span class="HTitleText3">Legislative Assembly of Nunavut</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-12"><span class="HTitleText3">Legislative Powers</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-13"><span class="HTitleText3">Laws Applicable in Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-14"><span class="HTitleText2">Judicial Power</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-15"><span class="HTitleText3">Judicature</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText3">Nunavut Court of Justice</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-17"><span class="HTitleText3">Court of Appeal of Nunavut</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-18"><span class="HTitleText3">Repeal</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-19"><span class="HLabel1">PART II</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-20"><span class="HTitleText2">Official Languages</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-21"><span class="HTitleText2">Nunavut Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-22"><span class="HTitleText2">Territorial Accounts</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-23"><span class="HTitleText2">Lands</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-24"><span class="HTitleText2">Cultural Sites and Property</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-25"><span class="HLabel1">*PART III</span> - <span class="HTitleText1">*[Note: Part III Repealed July 1, 1999.]</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-26"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="#h-27"><span class="HTitleText2">Expenditures</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-28"><span class="HTitleText2">Interim Commissioner of Nunavut</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-29"><span class="HTitleText2">Council of the Northwest Territories</span></a>
</li>
<li><span class='sectionRange'>76.01 - </span><a href="#h-30"><span class="HTitleText2">First Elections</span></a>
</li>
<li><span class='sectionRange'>76.05 - </span><a href="#h-31"><span class="HTitleText2">Initial Laws of Nunavut</span></a>
</li>
<li><span class='sectionRange'>76.06 - </span><a href="#h-32"><span class="HTitleText2">Public Offices and Bodies</span></a>
</li>
<li><span class='sectionRange'>76.09 - </span><a href="#h-33"><span class="HTitleText2">Pending Matters</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 to 77.3 - </span><a href="#h-34"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Consequential Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 to 77.3 - </span><a href="#h-35"><span class="HTitleText2">Northwest Territories Act</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-36"><span class="HTitleText2">Other Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-37"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-370251"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Western Boundary of Nunavut</span></a>
</li>
<li><a href="#h-370272"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Communities</span></a>
</li>
<li><a href="#h-370315"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
