<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’identification des criminels</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-251430"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-251435"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-251440"><span class="HTitleText1">Identification des criminels</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-251465"><span class="HTitleText1">Destruction des empreintes digitales et des photographies</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
