<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Split Lake Cree First Nation Flooded Land Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-437186"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-437189"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-437204"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-437214"><span class="HTitleText1">Claims</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-437223"><span class="HTitleText1">Arbitration</span></a>
</li></ul>
</li></ul>

</nav>

