<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les ponts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-33062"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-33067"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-33075"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-33080"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-33171"><span class="HTitleText1">Peines</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
