<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les produits dangereux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">[Abrogée, 2010, ch. 21, art. 73]</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-4"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Produits contrôlés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-9"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Liste de divulgation des ingrédients</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Modification de l’annexe II</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Consultation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Divulgation</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-14"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-15"><span class="HTitleText2">Inspecteurs et analystes</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Fouille, saisie et confiscation</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-18"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText2">Infractions, peines et procédure</span></a>
</li></ul>
</li><li><a href="#h-20"><span class="scheduleLabel">ANNEXE I</span></a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">ANNEXE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
