<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Protection of Residential Mortgage or Hypothecary Insurance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Purposes</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Approved Mortgage Insurers</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText1">Mortgage or Hypothecary Insurance Protection</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-6"><span class="HTitleText1">Protected Loan Limit</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-7"><span class="HTitleText1">Examination and Reporting</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-8"><span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-9"><span class="HTitleText1">Legal Proceedings</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-10"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-11"><span class="HTitleText1">Termination of Agreements</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
