<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 2004, No. 2</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-36410"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-36412"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-36414"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments to the First Nations Goods and Services Tax Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-36425"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the Income Tax Act and Certain Other Acts As a Consequence and a Coordinating Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-36426"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-36470"><span class="HTitleText2">Budget Implementation Act, 2003</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-36472"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-36475"><span class="HTitleText2">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-36477"><span class="HTitleText2">Income Tax Conventions Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-36479"><span class="HTitleText2">Tax Court of Canada Act</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-36483"><span class="HTitleText2">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-36485"><span class="HTitleText2">Co-ordinating Amendment</span></a>
</li></ul>
</li><li><a href="#h-36488"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

