<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Northern Canada Power Commission (Share Issuance and Sale Authorization) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-365851"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-365854"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-365861"><span class="HTitleText1">Capital Structure</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-365874"><span class="HTitleText1">Crown Property and Liabilities</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-365882"><span class="HTitleText1">Sale to Territorial Government</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-365887"><span class="HTitleText1">Accounts of Canada</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-365895"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-365904"><span class="HTitleText1">Repealed and Consequential</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-1.html#h-365905"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-365907"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-365909"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements and Federal Post-Secondary Education and Health Contributions Act, 1977</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-365912"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-365914"><span class="HTitleText2">Municipal Grants Act, 1980</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-365916"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-365918"><span class="HTitleText2">Public Sector Compensation Restraint Act</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-365920"><span class="HTitleText2">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-365922"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-1.html#h-365924"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

