<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Forestry Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-236781"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-236786"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-236791"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Development and Research</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-236809"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Forest Experimental Areas</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
