<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Government Services Act, 1999</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-251881"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-251884"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Operational Groups</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-251885"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-251897"><span class="HTitleText2">Government Services</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-251902"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-251914"><span class="HTitleText2">Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-251938"><span class="HTitleText2">Amendment of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-251941"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-251960"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-251963"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Correctional Groups</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-251964"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-251976"><span class="HTitleText2">Government Services</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-251981"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-251993"><span class="HTitleText2">Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-252017"><span class="HTitleText2">Amendment of Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-252020"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-252039"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-252043"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-252061"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
