<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Health Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-252893"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-252896"><span class="HTitleText1">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-252902"><span class="HTitleText1">Deputy Head</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-252905"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-252938"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-252960"><span class="HTitleText1">Regulations and Punishment</span></a>
</li>
<li><span class='sectionRange'>11.1 - </span><a href="#h-252966"><span class="HTitleText1">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-252990"><span class="HTitleText1">Provincial Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-252993"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>16 to 31 - </span><a href="#h-253013"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-253015"><span class="HTitleText1">References</span></a>
</li>
<li><span class='sectionRange'>35 and 36 - </span><a href="#h-253024"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-253026"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-253028"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
