<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les mesures d’aide liées au coût de l’énergie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-213383"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-213386"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Prestation liée au coût de l’énergie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-213403"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-213404"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-213407"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-213409"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Réduction de la consommation énergétique des habitations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-213419"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Transport en commun</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-213429"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Dispositions de coordination</span></a>
</li></ul>
</li></ul>

</nav>

