<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi visant à changer le nom de certaines circonscriptions électorales ainsi qu’à modifier la Loi sur la révision des limites des circonscriptions électorales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-417933"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-417936"><span class="HTitleText1">Circonscriptions électorales du Québec, de l’Ontario, de la Saskatchewan, de l’Alberta et de la Colombie-Britannique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-417937"><span class="HTitleText2">Québec</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-417964"><span class="HTitleText2">Ontario</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-417985"><span class="HTitleText2">Saskatchewan</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-417988"><span class="HTitleText2">Alberta</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-417997"><span class="HTitleText2">Colombie-Britannique</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-418002"><span class="HTitleText1">Modification à la Loi sur la révision des limites des circonscriptions électorales</span></a>
</li></ul>
</li></ul>

</nav>

