<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 1994 sur la Convention Canada-Argentine en matière d’impôts sur le revenu</a><ul class="TocIndent"><li><span class='sectionRange'>19 - </span><a href="page-1.html#h-40551"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Convention Canada-Argentine en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="page-2.html#h-40568"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Convention entre le Canada et la République Argentine en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="page-3.html#h-40848"><span class="scheduleLabel">ANNEXE VI</span> <span class="scheduleTitleText"> - Protocole</span></a>
</li></ul>
</li></ul>

</nav>

