<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la réorganisation et l’aliénation de Télésat Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-450342"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-450345"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-450363"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-450366"><span class="HTitleText1">Transfert d’actions au ministre</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-450378"><span class="HTitleText1">Vente d’actions par le ministre</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-450388"><span class="HTitleText1">Prorogation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-450409"><span class="HTitleText1">Affaires internes et statut</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-450423"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-450431"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-450451"><span class="HTitleText1">Modification</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-450453"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
