<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2002 sur la convention fiscale Canada — Émirats Arabes Unis</a><ul class="TocIndent"><li><a href="#h-56738"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement des Émirats Arabes Unis en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-57033"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole</span></a>
</li></ul>
</li></ul>

</nav>

