<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la production de défense</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-167371"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-167376"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-167404"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Fourniture de matériel de défense</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-167405"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-167447"><span class="HTitleText2">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-167463"><span class="HTitleText2">Organisation de l’industrie pour la défense</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-167485"><span class="HTitleText2">Approvisionnement pour la défense</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-167580"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-167606"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Réglementation de l’accès aux marchandises contrôlées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-167607"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-167612"><span class="HTitleText2">Exclusion de certaines personnes</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-167619"><span class="HTitleText2">Infractions</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-167631"><span class="HTitleText2">Inscription</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-167643"><span class="HTitleText2">Exemption</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-167659"><span class="HTitleText2">Renseignements</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-167664"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-167685"><span class="HTitleText2">Pouvoirs réglementaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-167701"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><a href="#h-19"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Liste des marchandises contrôlées</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
