<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Tribunal de la concurrence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-88195"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Tribunal de la concurrence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1 - </span><a href="#h-88196"><span class="HTitleText2">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-88199"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-88208"><span class="HTitleText2">Constitution du Tribunal</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-88254"><span class="HTitleText2">Compétence et pouvoirs du Tribunal</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-88290"><span class="HTitleText2">Organisation du Tribunal</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-88305"><span class="HTitleText2">Procédures devant le Tribunal</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-88317"><span class="HTitleText2">Appel</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-88325"><span class="HTitleText2">Administration du Tribunal</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-88329"><span class="HTitleText2">Règles</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 à 45 - </span><a href="#h-88347"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Loi relative aux enquêtes sur les coalitions</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-88349"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-88350"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>47 et 48 - </span><a href="#h-88352"><span class="HTitleText2">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-88354"><span class="HTitleText2">Loi d’urgence sur les approvisionnements d’énergie</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-88356"><span class="HTitleText2">Loi sur les offices de commercialisation des produits de ferme</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-88358"><span class="HTitleText2">Loi sur les transports nationaux</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-88360"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-88362"><span class="HTitleText2">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-88364"><span class="HTitleText2">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>55 à 58 - </span><a href="#h-88366"><span class="HTitleText2">Loi dérogatoire sur les conférences maritimes</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-88368"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-88378"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions transitoires et entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
