<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la radiocommunication</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-413838"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-413843"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-413876"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-413891"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-413905"><span class="HTitleText1">Pouvoirs ministériels</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-413960"><span class="HTitleText1">Pouvoirs du gouverneur en conseil et autres</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-414072"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-414182"><span class="HTitleText1">Sanctions administratives pécuniaires</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-414319"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-414336"><span class="HTitleText1">Recours civil</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
