<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Unemployment Insurance Benefit Entitlement Adjustments (Pension Payments) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-462020"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-462023"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-462038"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-462061"><span class="HTitleText1">Unemployment Insurance Act, 1971</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-462064"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

