<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Financial Institutions Depositors Compensation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-222948"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-222951"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-222964"><span class="HTitleText1">Payments</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-222999"><span class="HTitleText1">Discharge of Liability</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-223002"><span class="HTitleText1">Rights of Her Majesty</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-223012"><span class="HTitleText1">Income Tax</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-223015"><span class="HTitleText1">Powers and Agreements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-223028"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-223040"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-223043"><span class="HTitleText1">Commencement</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
