<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Restoring Rail Service Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-427606"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-427609"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-427621"><span class="HTitleText1">Rail Service Operations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-427635"><span class="HTitleText1">Extension of Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-427646"><span class="HTitleText1">Arbitration</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-427667"><span class="HTitleText1">New Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-427675"><span class="HTitleText1">Costs</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-427678"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-427692"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
