<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Development Corporation Reorganization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-82479"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-82482"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-82492"><span class="HTitleText1">Disposal of Crown Securities</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-82498"><span class="HTitleText1">Continuation of Corporation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-82575"><span class="HTitleText1">Transitional and Repeal Provisions</span></a>
</li></ul>
</li></ul>

</nav>

