<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Salaries Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-443950"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-443957"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Salaries</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-443958"><span class="HTitleText2">Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-443963"><span class="HTitleText2">Salary of Lieutenant Governors</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-443987"><span class="HTitleText2">Salaries of Ministers Before April 1, 2004</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="page-1.html#h-444027"><span class="HTitleText2">Salaries of Ministers from April 1, 2004</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-1.html#h-444083"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Support for Ministers Referred to in Paragraphs 4.1(3)(z.4) to (z.9)</span></a>
</li></ul>
</li></ul>

</nav>

