<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada — United Arab Emirates Tax Convention Act, 2002</a><ul class="TocIndent"><li><a href="#h-57994"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the United Arab Emirates for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="#h-58289"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>

