<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Freshwater Fish Marketing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-230889"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-230894"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-230907"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Freshwater Fish Marketing Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-230908"><span class="HTitleText2">Constitution of the Corporation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-230946"><span class="HTitleText2">Purpose and Powers</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-230964"><span class="HTitleText2">Organization and Staff</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-230985"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-231010"><span class="HTitleText2">Financial</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-231020"><span class="HLabel1">PART II</span> - <span class="HTitleText1">[Repealed, 2010, c. 12, s. 1738]</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-231023"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Regulation of Interprovincial and Export Trade</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-231024"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-231031"><span class="HTitleText2">Interprovincial and Export Trade</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-231043"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-231050"><span class="HTitleText2">Duties and Powers of the Corporation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-231069"><span class="HTitleText2">Agreements Respecting Participation</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-231081"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-231129"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-231149"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Annual Report</span></a>
</li>
<li><a href="#h-231155"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
