<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Colombia Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-43792"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-43795"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-43811"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-43814"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-43825"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-43831"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement and the Related Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-43832"><span class="HTitleText2">Approval</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-43835"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-43840"><span class="HTitleText2">Panels, Committees, Subcommittees and Working Groups</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-43852"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-43862"><span class="HTitleText2">Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-43865"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-43866"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-43874"><span class="HTitleText2">Commercial Arbitration Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-43876"><span class="HTitleText2">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-43878"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-43884"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-43898"><span class="HTitleText2">Department of Human Resources and Skills Development Act</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-43900"><span class="HTitleText2">Export and Import Permits Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-43904"><span class="HTitleText2">Financial Administration Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-43906"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-43913"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-43916"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

