<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Convention Canada-Royaume-Uni relative aux jugements en matière civile et commerciale</a><ul class="TocIndent"><li><a href="#h-82956"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Convention entre le Canada et le Royaume-Uni de Grande-Bretagne et d’Irlande du Nord pour assurer la reconnaissance et l’exécution réciproques des jugements en matière civile et commerciale</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
