<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’aéronautique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-7381"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-7386"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-7391"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-7444"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Aéronautique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-7445"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="#h-7459"><span class="HTitleText2">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>4.4 - </span><a href="#h-7504"><span class="HTitleText2">Redevances</span></a>
</li>
<li><span class='sectionRange'>4.7 - </span><a href="#h-7566"><span class="HTitleText2">Sûreté aérienne</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4.7 - </span><a href="#h-7567"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>4.71 - </span><a href="#h-7574"><span class="HTitleText3">Règlements sur la sûreté aérienne</span></a>
</li>
<li><span class='sectionRange'>4.72 - </span><a href="#h-7600"><span class="HTitleText3">Mesures de sûreté</span></a>
</li>
<li><span class='sectionRange'>4.75 - </span><a href="#h-7642"><span class="HTitleText3">Exigences relatives aux aéronefs étrangers</span></a>
</li>
<li><span class='sectionRange'>4.76 - </span><a href="#h-7647"><span class="HTitleText3">Directives d’urgence</span></a>
</li>
<li><span class='sectionRange'>4.79 - </span><a href="#h-7670"><span class="HTitleText3">Communications illicites</span></a>
</li>
<li><span class='sectionRange'>4.8 - </span><a href="#h-7680"><span class="HTitleText3">Habilitations de sécurité</span></a>
</li>
<li><span class='sectionRange'>4.81 - </span><a href="#h-7685"><span class="HTitleText3">Fourniture de renseignements</span></a>
</li>
<li><span class='sectionRange'>4.84 - </span><a href="#h-7794"><span class="HTitleText3">Contrôles</span></a>
</li>
<li><span class='sectionRange'>4.86 - </span><a href="#h-7812"><span class="HTitleText3">Contrôle des transporteurs aériens et aérodromes</span></a>
</li>
<li><span class='sectionRange'>4.87 - </span><a href="#h-7817"><span class="HTitleText3">Contrôle d’observation et d’efficacité</span></a>
</li></ul>
</li><li><span class='sectionRange'>4.9 - </span><a href="#h-7822"><span class="HTitleText2">Dispositions réglementaires générales</span></a>
</li>
<li><span class='sectionRange'>5.4 - </span><a href="#h-7888"><span class="HTitleText2">Zonage des aéroports</span></a>
</li>
<li><span class='sectionRange'>5.9 - </span><a href="#h-7971"><span class="HTitleText2">Dispositions générales concernant les règlements, arrêtés, etc.</span></a>
</li>
<li><span class='sectionRange'>6.41 - </span><a href="#h-8014"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>6.5 - </span><a href="#h-8037"><span class="HTitleText2">Renseignements médicaux et optométriques</span></a>
</li>
<li><span class='sectionRange'>6.6 - </span><a href="#h-8053"><span class="HTitleText2">Mesures relatives aux documents d’aviation canadiens</span></a>
</li>
<li><span class='sectionRange'>7.3 - </span><a href="#h-8194"><span class="HTitleText2">Interdictions, infractions et peines</span></a>
</li>
<li><span class='sectionRange'>7.6 - </span><a href="#h-8282"><span class="HTitleText2">Procédure relative à certaines contraventions</span></a>
</li>
<li><span class='sectionRange'>8.4 - </span><a href="#h-8365"><span class="HTitleText2">Mesures de contrainte</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8422"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-8430"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Enquêtes militaires mettant en cause des civils</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-8431"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8454"><span class="HTitleText2">Autorisation ministérielle</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8459"><span class="HTitleText2">Directeur des enquêtes sur la navigabilité</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8475"><span class="HTitleText2">Enquêtes sur les accidents militaro-civils</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-8476"><span class="HTitleText3">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8541"><span class="HTitleText3">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-8609"><span class="HTitleText3">Renseignements protégés</span></a>
</li>
<li><span class='sectionRange'>24.3 - </span><a href="#h-8707"><span class="HTitleText3">Témoignage du directeur et des enquêteurs</span></a>
</li>
<li><span class='sectionRange'>24.5 - </span><a href="#h-8716"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>24.6 - </span><a href="#h-8734"><span class="HTitleText3">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>24.8 - </span><a href="#h-8757"><span class="HTitleText2">Enquêtes militaires régies par la partie I</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-8762"><span class="HLabel1">PARTIE III</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-8763"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-8768"><span class="HTitleText2">Poursuites</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-8789"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">[Abrogée, 2001, ch. 29, art. 44]</span></a>
</li>
<li><a href="#h-8800"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

