<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canadian Net-Zero Emissions Accountability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1305625"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1305628"><span class="HTitleText1">Definitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-1305638"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-1305641"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-1305644"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-1305647"><span class="HTitleText1">Targets and Plans</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-1305711"><span class="HTitleText1">Reports</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-1305746"><span class="HTitleText1">Tabling and Publication</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-1305763"><span class="HTitleText1">Advisory Body</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-1305800"><span class="HTitleText1">Minister of Finance</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-1305803"><span class="HTitleText1">Commissioner of the Environment and Sustainable Development</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-1305813"><span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-1305827"><span class="HTitleText1">Consequential Amendment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="page-2.html#h-1305828"><span class="HTitleText2"><cite class="XRefExternalAct">Auditor General Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="page-2.html#h-1305833"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

