<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le casier judiciaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-131742"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-131747"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-131768"><span class="HTitleText1">Commission des libérations conditionnelles du Canada</span></a>
</li>
<li><span class='sectionRange'>2.3 - </span><a href="page-1.html#h-131780"><span class="HTitleText1">Effet de la suspension du casier</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-131789"><span class="HTitleText1">Demande de suspension du casier</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-131797"><span class="HTitleText1">Procédure</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-131860"><span class="HTitleText1">Garde des dossiers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-131916"><span class="HTitleText1">Révocation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-131939"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-3.html#h-131966"><span class="HTitleText1">Infraction</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-3.html#h-131971"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><a href="page-4.html#h-131984"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-5.html#h-132060"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-6.html#h-1182914"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Infractions liées au cannabis</span></a>
</li></ul>
</li></ul>

</nav>

