<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi relative aux aliments du bétail</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-236281"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-236286"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-236318"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-236360"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>5.1 - </span><a href="page-1.html#h-236404"><span class="HTitleText1">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>5.2 - </span><a href="page-2.html#h-236416"><span class="HTitleText1">Enregistrements, licences et agréments</span></a>
</li>
<li><span class='sectionRange'>5.5 - </span><a href="page-2.html#h-236449"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-236466"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="page-2.html#h-236542"><span class="HTitleText1">Analyse</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="page-2.html#h-236549"><span class="HTitleText1">Restriction de responsabilité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-236558"><span class="HTitleText1">Infractions et peines</span></a>
</li></ul>
</li></ul>

</nav>

