<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de la convention sur les armes biologiques ou à toxines</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Mise en oeuvre de la Convention</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-3"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-4"><span class="HTitleText1">Renseignements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-5"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
