<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère de l'Industrie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Développement économique régional en Ontario et au Québec</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Pouvoirs et fonctions du registraire général du Canada</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-7"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Dispositions transitoires, modifications connexes, abrogations et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>26 à 30 - </span><a href="#h-9"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 à 30 - </span><a href="#h-10"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText3">Loi sur la radiodiffusion</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-12"><span class="HTitleText3">Loi sur les corporations canadiennes</span></a>
</li>
<li><span class='sectionRange'>33 et 34 - </span><a href="#h-13"><span class="HTitleText3">Loi sur le ministère des Communications</span></a>
</li>
<li><span class='sectionRange'>35 à 38 - </span><a href="#h-14"><span class="HTitleText3">Loi sur le ministère de la Consommation et des Affaires commerciales</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText3">Loi de soutien de l’emploi</span></a>
</li>
<li><span class='sectionRange'>40 à 43 - </span><a href="#h-16"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-17"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>45 à 51 - </span><a href="#h-18"><span class="HTitleText3">Loi sur Investissement Canada</span></a>
</li>
<li><span class='sectionRange'>52 et 53 - </span><a href="#h-19"><span class="HTitleText3">Loi sur la protection des obtentions végétales</span></a>
</li>
<li><span class='sectionRange'>54 à 56 - </span><a href="#h-20"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>57 à 59 - </span><a href="#h-21"><span class="HTitleText3">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-22"><span class="HTitleText3">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-23"><span class="HTitleText3">Loi sur les traitements</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-24"><span class="HTitleText3">Nouvelle terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 à 66 - </span><a href="#h-25"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-26"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
