<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les opérations transfrontalières intégrées de contrôle d’application de la loi</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-263915"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-263918"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-263924"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-263927"><span class="HTitleText1">Principes</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-263936"><span class="HTitleText1">Autorité centrale du Canada</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-263968"><span class="HTitleText1">Pouvoirs des agents désignés</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-263973"><span class="HTitleText1">Personnes détenues</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-263979"><span class="HTitleText1">Saisies</span></a>
</li></ul>
</li></ul>

</nav>

