<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les lettres de change</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-4"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Lettres de change</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText2">Forme de la lettre et interprétation</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-6"><span class="HTitleText2">Acceptation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-7"><span class="HTitleText2">Livraison</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-8"><span class="HTitleText2">Échéance des lettres</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-9"><span class="HTitleText2">Capacité et habilité des parties</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-10"><span class="HTitleText2">Cause</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-11"><span class="HTitleText2">Détenteur régulier</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-12"><span class="HTitleText2">Négociation</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-13"><span class="HTitleText2">Droits et pouvoirs du détenteur</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-14"><span class="HTitleText2">Présentation à l’acceptation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-15"><span class="HTitleText2">Présentation au paiement</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-16"><span class="HTitleText2">Avis de refus</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-17"><span class="HTitleText2">Protêt</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-18"><span class="HTitleText2">Obligations des parties</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-19"><span class="HTitleText2">Libération</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-20"><span class="HTitleText2">Acceptation et paiement par intervention</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-21"><span class="HTitleText2">Effets perdus</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-22"><span class="HTitleText2">Pluralité d’exemplaires</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-23"><span class="HTitleText2">Conflit de lois</span></a>
</li></ul>
</li><li><span class='sectionRange'>164 - </span><a href="#h-24"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Chèques sur une banque</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-25"><span class="HTitleText2">Chèques barrés</span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="#h-26"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Billets</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-27"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Lettres et billets de consommation</span></a>
</li>
<li><a href="#h-29527"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
