<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Railway Safety Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-424514"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-424517"><span class="HTitleText1">Application of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-424529"><span class="HTitleText1">Objectives</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-424547"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-424622"><span class="HTitleText1">Relationship to Canadian Navigable Waters Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-424627"><span class="HTitleText1">Coordination Agreements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-2.html#h-424651"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Construction or Alteration of Railway Works</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-2.html#h-424652"><span class="HTitleText2">Standards</span></a>
</li>
<li><span class='sectionRange'>7.1 - </span><a href="page-2.html#h-424666"><span class="HTitleText2">Construction and Alteration of Road Crossings</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-424671"><span class="HTitleText2">Notice of Certain Proposed Railway Works</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-424688"><span class="HTitleText2">Undertaking of Proposed Railway Works</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-424737"><span class="HTitleText2">Grants for Proposed Railway Works and Other Undertakings Contributing to Safe Railway Operations and to Public Safety at Road Crossings</span></a>
</li></ul>
</li><li><span class='sectionRange'>17.1 - </span><a href="page-3.html#h-424833"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Operation and Maintenance of Railway Works and Equipment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17.1 - </span><a href="page-3.html#h-424834"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>17.4 - </span><a href="page-3.html#h-424854"><span class="HTitleText2">Railway Operating Certificate</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-4.html#h-424927"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-4.html#h-424951"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-4.html#h-425025"><span class="HTitleText2">Miscellaneous Provisions Relating to Regulations and Rules</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-5.html#h-425076"><span class="HTitleText2">Powers of Agency — Fire</span></a>
</li>
<li><span class='sectionRange'>23.1 - </span><a href="page-5.html#h-425094"><span class="HTitleText2">Audible Warnings</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-5.html#h-425112"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Non-railway Operations Affecting Railway Safety</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="page-5.html#h-425113"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-5.html#h-425141"><span class="HTitleText2">Power of Railway Companies on Adjoining Lands</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-5.html#h-425157"><span class="HTitleText2">Powers of Agency</span></a>
</li>
<li><span class='sectionRange'>26.1 - </span><a href="page-5.html#h-425175"><span class="HTitleText2">Access to Line Works Prohibited</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-5.html#h-425184"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-5.html#h-425185"><span class="HTitleText2">Railway Safety Inspectors and Screening Officers</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-6.html#h-425314"><span class="HTitleText2">Notices of Railway Safety Inspectors Concerning the Safety or Security of Railway Operations</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-7.html#h-425369"><span class="HTitleText2">Ministerial Orders</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-7.html#h-425437"><span class="HTitleText2">Emergency Directives</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-7.html#h-425459"><span class="HTitleText2">Enforcement through Court</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-8.html#h-425473"><span class="HTitleText2">Medical Information</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-8.html#h-425496"><span class="HTitleText2">Other Information Requirements</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-8.html#h-425516"><span class="HTitleText2">Security</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-8.html#h-425565"><span class="HTitleText2">Inquiries</span></a>
</li>
<li><span class='sectionRange'>40.1 - </span><a href="page-8.html#h-425582"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-9.html#h-425684"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-9.html#h-425729"><span class="HLabel1">PART IV.1</span> - <span class="HTitleText1">Police Constables</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-9.html#h-425755"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Miscellaneous Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-9.html#h-425756"><span class="HTitleText2">Exercise of Powers</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-10.html#h-425759"><span class="HTitleText2">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-10.html#h-425772"><span class="HTitleText2">Regulations — General</span></a>
</li>
<li><span class='sectionRange'>47.4 - </span><a href="page-10.html#h-425820"><span class="HTitleText2">Agreements</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-10.html#h-425834"><span class="HTitleText2">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-10.html#h-425837"><span class="HTitleText2">Inconsistent Provisions</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-10.html#h-425843"><span class="HTitleText2">Review of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="page-10.html#h-425851"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Consequential Amendments and Transitional Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="page-10.html#h-425852"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>53 and 54 - </span><a href="page-10.html#h-425854"><span class="HTitleText2">Canadian National Railways Act</span></a>
</li>
<li><span class='sectionRange'>55 to 62 - </span><a href="page-10.html#h-425856"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>63 to 65 - </span><a href="page-10.html#h-425858"><span class="HTitleText2">National Transportation Act, 1987</span></a>
</li>
<li><span class='sectionRange'>66 to 114 - </span><a href="page-10.html#h-425860"><span class="HTitleText2">Railway Act</span></a>
</li>
<li><span class='sectionRange'>115 to 118 - </span><a href="page-10.html#h-425862"><span class="HTitleText2">Railway Relocation and Crossing Act</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-10.html#h-425864"><span class="HTitleText2">Transitional Provisions Relating to Railway Act Amendments</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="page-11.html#h-425916"><span class="HTitleText2">Transitional Provisions Relating to Repeal of Parts II and III of the Railway Relocation and Crossing Act</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-11.html#h-425925"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

