<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Criminal Records Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-135188"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-135193"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-135214"><span class="HTitleText1">Parole Board of Canada</span></a>
</li>
<li><span class='sectionRange'>2.3 - </span><a href="#h-135226"><span class="HTitleText1">Effect of Record Suspension</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-135235"><span class="HTitleText1">Application for Record Suspension</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-135243"><span class="HTitleText1">Procedure</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-135308"><span class="HTitleText1">Custody of Records</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-135364"><span class="HTitleText1">Revocation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-135387"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-135414"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-135419"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><a href="#h-135432"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-135508"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
