<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’immigration et la protection des réfugiés</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-267391"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-267394"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-267408"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-267443"><span class="HTitleText1">Mise en application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-267489"><span class="HTitleText1">Concertation intergouvernementale</span></a>
</li>
<li><span class='sectionRange'>10.01 - </span><a href="#h-267515"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Immigration au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10.01 - </span><a href="#h-267516"><span class="HLabel2">SECTION 0.01</span> - <span class="HTitleText2">Renseignements biométriques</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-267531"><span class="HLabel2">SECTION 0.1</span> - <span class="HTitleText2">Invitation à présenter une demande</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-267600"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Formalités et sélection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-267601"><span class="HTitleText3">Formalités</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-267637"><span class="HTitleText3">Sélection des résidents permanents</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-267645"><span class="HTitleText3">Régime de parrainage</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-267654"><span class="HTitleText3">Engagements</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-267666"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>14.1 - </span><a href="#h-267684"><span class="HTitleText3">Instructions du ministre</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-267712"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Contrôle</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-267739"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Entrée et séjour au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-267740"><span class="HTitleText3">Entrée et séjour</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-267794"><span class="HTitleText3">Statut et autorisation d’entrer</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-267919"><span class="HTitleText3">Droits et obligations des résidents permanents et des résidents temporaires</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-267979"><span class="HTitleText3">Attestation de statut</span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="#h-267990"><span class="HTitleText3">Titre de voyage de réfugié</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-267995"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-268011"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Interdictions de territoire</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-268132"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Perte de statut et renvoi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-268133"><span class="HTitleText3">Constat de l’interdiction de territoire</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-268152"><span class="HTitleText3">Enquête par la Section de l’immigration</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-268159"><span class="HTitleText3">Perte du statut</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-268183"><span class="HTitleText3">Exécution des mesures de renvoi</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-268217"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-268230"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Détention et mise en liberté</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-268331"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Droit d’appel</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-268396"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-268426"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Certificats et protection de renseignements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-268427"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-268434"><span class="HTitleText3">Certificat</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-268475"><span class="HTitleText3">Détention et mise en liberté</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-268539"><span class="HTitleText3">Protection des renseignements</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-268571"><span class="HTitleText3">Avocat spécial</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-268631"><span class="HTitleText3">Autres instances</span></a>
</li>
<li><span class='sectionRange'>87.2 - </span><a href="#h-268658"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>87.3 - </span><a href="#h-268670"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87.3 - </span><a href="#h-268671"><span class="HTitleText3">Instructions sur le traitement des demandes</span></a>
</li>
<li><span class='sectionRange'>87.31 - </span><a href="#h-1160996"><span class="HTitleText3">Demandes de visa de résident temporaire et de permis de travail ou d’études</span></a>
</li>
<li><span class='sectionRange'>87.4 - </span><a href="#h-268698"><span class="HTitleText3">Travailleurs qualifiés (fédéral)</span></a>
</li>
<li><span class='sectionRange'>87.5 - </span><a href="#h-268712"><span class="HTitleText3">Catégories fédérales des investisseurs et des entrepreneurs</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-268732"><span class="HTitleText3">Prêts</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-268738"><span class="HTitleText3">Frais</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-268785"><span class="HTitleText3">Numéros d’assurance sociale</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-268790"><span class="HTitleText3">Représentation ou conseil</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-268827"><span class="HTitleText3">Incorporation par renvoi</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-268847"><span class="HTitleText3">Rapports au Parlement</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-268863"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Protection des réfugiés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-268864"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Notions d’asile, de réfugié et de personne à protéger</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-268903"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Réfugiés et personnes à protéger</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-268904"><span class="HTitleText3">Demande d’asile</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-268918"><span class="HTitleText3">Examen de la recevabilité par l’agent</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-268967"><span class="HTitleText3">Interruption de l’étude de la demande d’asile</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-268988"><span class="HTitleText3">Procédure d’extradition</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-269000"><span class="HTitleText3">Étrangers sans papier</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-269003"><span class="HTitleText3">Décision sur la demande d’asile</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-269013"><span class="HTitleText3">Perte de l’asile</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-269028"><span class="HTitleText3">Annulation par la Section de la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>109.1 - </span><a href="#h-269036"><span class="HTitleText3">Désignation de pays d’origine</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-269055"><span class="HTitleText3">Appel devant la Section d’appel des réfugiés</span></a>
</li>
<li><span class='sectionRange'>111.1 - </span><a href="#h-269099"><span class="HTitleText3">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-269112"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Examen des risques avant renvoi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-269113"><span class="HTitleText3">Protection</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-269163"><span class="HTitleText3">Principe du non-refoulement</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-269175"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Exécution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-269176"><span class="HTitleText2">Organisation d’entrée illégale au Canada</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-269232"><span class="HTitleText2">Infractions relatives aux documents</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-269252"><span class="HTitleText2">Infractions générales</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-269297"><span class="HTitleText2">Règles visant les poursuites</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-269316"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-269322"><span class="HTitleText2">Agents d’application de la loi</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-269344"><span class="HTitleText2">Agents de la paix</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-269351"><span class="HTitleText2">Contraventions</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-269373"><span class="HTitleText2">Créances de Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-269389"><span class="HTitleText2">Exécution des créances</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-269410"><span class="HTitleText2">Propriétaires et exploitants de véhicules et d’installations de transport</span></a>
</li>
<li><span class='sectionRange'>150.1 - </span><a href="#h-269438"><span class="HTitleText2">Communication de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-269451"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Commission de l’immigration et du statut de réfugié</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-269452"><span class="HTitleText2">Composition de la Commission</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-269487"><span class="HTitleText2">Siège et personnel</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-269497"><span class="HTitleText2">Présidence de la Commission</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-269520"><span class="HTitleText2">Fonctionnement</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-269536"><span class="HTitleText2">Attributions communes</span></a>
</li>
<li><span class='sectionRange'>169.1 - </span><a href="#h-269584"><span class="HTitleText2">Section de la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-269610"><span class="HTitleText2">Section d’appel des réfugiés</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-269627"><span class="HTitleText2">Section de l’immigration</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-269641"><span class="HTitleText2">Section d’appel de l’immigration</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-269655"><span class="HTitleText2">Mesures correctives et disciplinaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>186.1 - </span><a href="#h-269701"><span class="HLabel1">PARTIE 4.1</span> - <span class="HTitleText1">Application par voie électronique</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-269743"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions transitoires, modifications corrélatives, disposition de coordination, abrogations et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="#h-269744"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-269788"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>202 - </span><a href="#h-269789"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-269791"><span class="HTitleText3">Loi sur les programmes de commercialisation agricole</span></a>
</li>
<li><span class='sectionRange'>204 et 205 - </span><a href="#h-269793"><span class="HTitleText3">Loi sur la généalogie des animaux</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-269795"><span class="HTitleText3">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-269797"><span class="HTitleText3">Loi d’exécution du budget de 1998</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-269799"><span class="HTitleText3">Loi sur la Banque de développement du Canada</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-269801"><span class="HTitleText3">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-269803"><span class="HTitleText3">Loi sur l’Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>211 à 214 - </span><a href="#h-269805"><span class="HTitleText3">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-269807"><span class="HTitleText3">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>216 à 218 - </span><a href="#h-269809"><span class="HTitleText3">Loi sur la marine marchande du Canada</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-269811"><span class="HTitleText3">Loi fédérale sur l’aide financière aux étudiants</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-269813"><span class="HTitleText3">Loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>221 et 222 - </span><a href="#h-269815"><span class="HTitleText3">Loi sur les transports au Canada</span></a>
</li>
<li><span class='sectionRange'>223 à 226 - </span><a href="#h-269817"><span class="HTitleText3">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-269819"><span class="HTitleText3">Loi de mise en oeuvre de la Convention sur les armes chimiques</span></a>
</li>
<li><span class='sectionRange'>227.1 à 232 - </span><a href="#h-269821"><span class="HTitleText3">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-269823"><span class="HTitleText3">Loi de mise en oeuvre du Traité d’interdiction complète des essais nucléaires</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-269825"><span class="HTitleText3">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>235 à 241 - </span><a href="#h-269827"><span class="HTitleText3">Loi sur le droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>242 et 243 - </span><a href="#h-269829"><span class="HTitleText3">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-269831"><span class="HTitleText3">Code criminel</span></a>
</li>
<li><span class='sectionRange'>248 et 249 - </span><a href="#h-269835"><span class="HTitleText3">Loi sur les mesures d’urgence</span></a>
</li>
<li><span class='sectionRange'>250 à 252 - </span><a href="#h-269837"><span class="HTitleText3">Loi sur l’extradition</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-269839"><span class="HTitleText3">Loi sur les services publicitaires fournis par des éditeurs étrangers</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-269841"><span class="HTitleText3">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-269843"><span class="HTitleText3">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>256 à 258 - </span><a href="#h-269845"><span class="HTitleText3">Loi sur le Centre international des droits de la personne et du développement démocratique</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-269847"><span class="HTitleText3">Loi sur Investissement Canada</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-269849"><span class="HTitleText3">Loi sur les prestations d’adaptation pour les travailleurs</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-269851"><span class="HTitleText3">Loi sur l’entraide juridique en matière criminelle</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-269853"><span class="HTitleText3">Loi sur l’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>263 à 267 - </span><a href="#h-269855"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-269857"><span class="HTitleText3">Loi sur le pilotage</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-269859"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-269861"><span class="HTitleText3">Loi sur le recyclage des produits de la criminalité</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-269863"><span class="HTitleText3">Loi sur les marques de commerce</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-269865"><span class="HTitleText3">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-269867"><span class="HTitleText3">Terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>273.1 - </span><a href="#h-269872"><span class="HTitleText2">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-269874"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-269876"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-269882"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

