<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les terres destinées aux anciens combattants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-451804"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-451809"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-451828"><span class="HTitleText1">Directeur et employés</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-451843"><span class="HTitleText1">Pouvoirs corporatifs du directeur</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-451863"><span class="HTitleText1">Caisse de la Loi sur les terres destinées aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-451880"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Aide à l’établissement sur des terres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-1.html#h-451881"><span class="HTitleText2">Formation agricole</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-451891"><span class="HTitleText2">Acquisition de terres et d’autres biens</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-451899"><span class="HTitleText2">Bâtiments et améliorations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-451910"><span class="HTitleText2">Ventes de terres et d’autres biens aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-452044"><span class="HTitleText2">Avances sur garantie de la terre possédée par un ancien combattant</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-452073"><span class="HTitleText2">Assurances et taxes</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-452097"><span class="HTitleText2">Comité d’agrément</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-452128"><span class="HTitleText2">Résiliation et revente en cas de défaut</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-452174"><span class="HTitleText2">Location ou autre aliénation de biens</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-452179"><span class="HTitleText2">Prix de vente modifié</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-452191"><span class="HTitleText2">Vente pour fins spéciales</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-4.html#h-452198"><span class="HTitleText2">Terres prises pour des objets publics</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-4.html#h-452208"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-5.html#h-452342"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>48.1 - </span><a href="page-5.html#h-452360"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="page-5.html#h-452380"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">[Abrogée, 1980-81-82-83, ch. 78, art. 11]</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-5.html#h-452381"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Assistance au titre des améliorations agricoles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="page-5.html#h-452382"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-5.html#h-452391"><span class="HTitleText2">Prêts aux cultivateurs à plein temps</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-5.html#h-452422"><span class="HTitleText2">Prêts aux cultivateurs à temps partiel</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-5.html#h-452433"><span class="HTitleText2">Forme de la convention</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-5.html#h-452441"><span class="HTitleText2">Conditions du prêt</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-5.html#h-452465"><span class="HTitleText2">Garantie</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-6.html#h-452489"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-6.html#h-452498"><span class="HTitleText2">Généralités</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

