<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Radiation Emitting Devices Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-420039"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-420044"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-420065"><span class="HTitleText1">Restriction on Application of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-420072"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-420091"><span class="HTitleText1">Notification</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-420108"><span class="HTitleText1">Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-420157"><span class="HTitleText1">Disposition of Devices with Consent of Owner</span></a>
</li>
<li><span class='sectionRange'>12.1 - </span><a href="#h-420168"><span class="HTitleText1">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>12.2 - </span><a href="#h-420180"><span class="HTitleText1">Removal or Forfeiture of Unlawful Imports</span></a>
</li>
<li><span class='sectionRange'>12.3 - </span><a href="#h-420196"><span class="HTitleText1">Costs</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-420211"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-420236"><span class="HTitleText1">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-420260"><span class="HTitleText1">Offence and Punishment</span></a>
</li></ul>
</li></ul>

</nav>

