<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les forêts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-230846"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-230851"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-230856"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Développement et recherche</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-230874"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Régions d’expérimentation forestière</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
