<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Excise Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-182930"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="page-1.html#h-182935"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-182952"><span class="HTitleText1">Interpretation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-182953"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-183013"><span class="HTitleText2">Distilleries</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-183040"><span class="HTitleText2">Breweries</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-183060"><span class="HTitleText2">Bonded Manufacturers</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-183067"><span class="HTitleText2">Tobacco and Cigars and Manufacturers thereof</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="page-2.html#h-183099"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-183109"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-2.html#h-183110"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-3.html#h-183208"><span class="HTitleText2">Obligations of Licensees</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-183244"><span class="HTitleText2">Books, Accounts and Papers</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-183282"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-183343"><span class="HTitleText2">Duties, how Ascertained and when Payable</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-183414"><span class="HTitleText2">Bonding and Warehousing</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-6.html#h-183568"><span class="HTitleText2">Powers and Duties of Officers</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-6.html#h-183660"><span class="HTitleText2">Protection of Officers</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-7.html#h-183692"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>110.1 - </span><a href="page-8.html#h-183865"><span class="HTitleText2">Recovery of Duties and Penalties</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="page-9.html#h-184001"><span class="HTitleText2">Appropriation of Penalties and Forfeitures</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-9.html#h-184018"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="page-9.html#h-184033"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Distilleries</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="page-9.html#h-184034"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-9.html#h-184039"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-10.html#h-184077"><span class="HTitleText2">Duties of Excise</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-11.html#h-184206"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-11.html#h-184211"><span class="HTitleText2">Bonding and Warehousing</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-11.html#h-184239"><span class="HTitleText2">Permits</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-11.html#h-184253"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>167 - </span><a href="page-12.html#h-184330"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Breweries</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="page-12.html#h-184331"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-12.html#h-184336"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="page-12.html#h-184351"><span class="HTitleText2">Duties of Excise</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-12.html#h-184450"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-12.html#h-184455"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>180 - </span><a href="page-13.html#h-184493"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Bonded Manufacturers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>180 - </span><a href="page-13.html#h-184494"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="page-13.html#h-184499"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-13.html#h-184519"><span class="HTitleText2">Duties of Excise</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="page-13.html#h-184524"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-13.html#h-184529"><span class="HTitleText2">Drawback and Remission of Duties</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-13.html#h-184541"><span class="HTitleText2">Supervision</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-13.html#h-184560"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="page-13.html#h-184565"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="page-13.html#h-184574"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Tobacco and Cigars and Manufacturers Thereof</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>195 - </span><a href="page-13.html#h-184575"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="page-13.html#h-184580"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-13.html#h-184603"><span class="HTitleText2">Duties</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-13.html#h-184613"><span class="HTitleText2">Tobacco Packaging, Stamping and Marking</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="page-14.html#h-184693"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="page-14.html#h-184707"><span class="HTitleText2">Quantities of Tobacco and Cigars</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="page-14.html#h-184712"><span class="HTitleText2">Returns</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-14.html#h-184717"><span class="HTitleText2">Bonding and Warehousing</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-14.html#h-184734"><span class="HTitleText2">Canadian Leaf Tobacco</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-15.html#h-184775"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="page-16.html#h-184941"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Denatured Alcohol, Specially Denatured Alcohol and Wood Alcohol</span></a>
</li>
<li><a href="page-17.html#h-185063"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

