<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Philanthropy Day Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-363354"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-363357"><span class="HTitleText1">National Philanthropy Day</span></a>
</li></ul>
</li></ul>

</nav>

