<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’indemnité aux déposants de certaines institutions financières</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-217327"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-217330"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-217342"><span class="HTitleText1">Paiements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-217375"><span class="HTitleText1">Extinction de responsabilité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-217378"><span class="HTitleText1">Droits de Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-217388"><span class="HTitleText1">Impôt</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-217391"><span class="HTitleText1">Pouvoirs et accords</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-217404"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-217416"><span class="HTitleText1">Affectation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-217419"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

