<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les produits antiparasitaires</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-408178"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-408181"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-408236"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-408239"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-408253"><span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-408259"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-408291"><span class="HTitleText1">Homologation des produits antiparasitaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-408292"><span class="HTitleText2">Demande d’homologation ou de modification d’homologation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-408348"><span class="HTitleText2">Limites maximales de résidus</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-408368"><span class="HTitleText2">Renseignements supplémentaires et obligation de communiquer</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-408382"><span class="HTitleText2">Réévaluation et examen spécial</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-408470"><span class="HTitleText2">Autres motifs de révocation ou de modification</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-408496"><span class="HTitleText2">Consultation publique</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-408518"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-408540"><span class="HTitleText1">Contrôle de l’exportation</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-408576"><span class="HTitleText1">Examen des décisions</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-408621"><span class="HTitleText1">Autorisation d’utilisation d’un produit antiparasitaire non homologué</span></a>
</li>
<li><span class='sectionRange'>41.1 - </span><a href="#h-1176926"><span class="HTitleText1">Renseignements sur la sécurité des produits antiparasitaires non homologués</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-408637"><span class="HTitleText1">Accès à l’information</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-408744"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-408745"><span class="HTitleText2">Inspecteurs et analystes</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-408766"><span class="HTitleText2">Rapport volontaire</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-408783"><span class="HTitleText2">Visite</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-408844"><span class="HTitleText2">Saisies</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-408849"><span class="HTitleText2">Mesures relatives aux choses saisies</span></a>
</li>
<li><span class='sectionRange'>53.3 - </span><a href="#h-408882"><span class="HTitleText2">Retrait, confiscation ou destruction d’importations illégales</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="#h-408925"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-408964"><span class="HTitleText2">Mesures pour faire observer la loi</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-408984"><span class="HTitleText2">Mesures d’élimination et de contrôle des risques</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-409003"><span class="HTitleText2">Révision des ordres des inspecteurs</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-409036"><span class="HTitleText2">Ordre du tribunal</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-409041"><span class="HTitleText1">Livraison de documents</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-409057"><span class="HTitleText1">Droits et autres frais</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-409079"><span class="HTitleText1">Limitation de responsabilité</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-409082"><span class="HTitleText1">Droits à payer pour l’utilisation de renseignements</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-409096"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>67.1 - </span><a href="#h-409154"><span class="HTitleText1">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-409176"><span class="HTitleText1">Infractions et peines</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-409177"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-409205"><span class="HTitleText2">Dispositions connexes</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-409266"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-409279"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>82 à 88 - </span><a href="#h-409285"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-409287"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-409289"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

