<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Harbour Commissions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">National Ports Policy</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Establishment of Harbour Commissions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Members and Staff</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">General Powers</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText1">Borrowing Powers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">Finances</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText1">Expropriation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText1">Payment of Rates</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-12"><span class="HTitleText1">Seizure</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
