<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Telecommunications Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-459777"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-459780"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-459781"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-459815"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-459818"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-459827"><span class="HTitleText2">Canadian Telecommunications Policy</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-459839"><span class="HTitleText2">Powers of Governor in Council, Commission and Minister</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-459911"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Eligibility to Operate</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-459912"><span class="HTitleText2">Canadian Ownership and Control</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-459949"><span class="HTitleText2">International Telecommunications Services Licences</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-459985"><span class="HTitleText2">International Submarine Cable Licences</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-460008"><span class="HTitleText2">Documentary Evidence</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-460011"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-460042"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Rates, Facilities and Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-460043"><span class="HTitleText2">Provision of Services</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-460091"><span class="HTitleText2">Roaming</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-460133"><span class="HTitleText2">Forbearance</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-460145"><span class="HTitleText2">Order to Provide Services</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-460153"><span class="HTitleText2">Content of Messages</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-460156"><span class="HTitleText2">Provision of Information</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-460204"><span class="HTitleText2">Connection of Facilities</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-460210"><span class="HTitleText2">Unsolicited Telecommunications</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-460308"><span class="HTitleText2">Construction and Expropriation Powers</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="#h-460349"><span class="HTitleText2">Telecommunications Numbering and Other Matters</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-460395"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-460396"><span class="HTitleText2">Exercise of Powers</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-460437"><span class="HTitleText2">Guidelines and Advice</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-460445"><span class="HTitleText2">Decisions of Commission</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-460466"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-460482"><span class="HTitleText2">Evidence</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-460496"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>69.1 - </span><a href="#h-460522"><span class="HLabel1">PART IV.1</span> - <span class="HTitleText1">Telecommunications Apparatus</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69.1 - </span><a href="#h-460523"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>69.2 - </span><a href="#h-460530"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>69.3 - </span><a href="#h-460538"><span class="HTitleText2">Minister’s Powers</span></a>
</li>
<li><span class='sectionRange'>69.4 - </span><a href="#h-460567"><span class="HTitleText2">Powers of Governor in Council and Others</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-460586"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Investigation and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="#h-460587"><span class="HTitleText2">Inquiries</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-460601"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-460634"><span class="HTitleText2">Civil Liability</span></a>
</li>
<li><span class='sectionRange'>72.001 - </span><a href="#h-460644"><span class="HTitleText2">General Administrative Monetary Penalties Scheme</span></a>
</li>
<li><span class='sectionRange'>72.01 - </span><a href="#h-460755"><span class="HTitleText2">Administrative Monetary Penalties Scheme for Unsolicited Telecommunications</span></a>
</li>
<li><span class='sectionRange'>72.14 - </span><a href="#h-460825"><span class="HTitleText2">Provisions Applicable to Both Administrative Monetary Penalties Schemes</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-460857"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>74.1 - </span><a href="#h-460892"><span class="HTitleText2">Forfeiture</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-460912"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>77 to 129 - </span><a href="#h-460927"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Related Amendments, Repeals, Application of Certain Provisions and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 to 129 - </span><a href="#h-460928"><span class="HTitleText2">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>130 and 131 - </span><a href="#h-460930"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-460932"><span class="HTitleText2">Application of Certain Provisions</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-460937"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

