<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Special Retirement Arrangements Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-434273"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-434276"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-434289"><span class="HTitleText1">Special Pension Plans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-434290"><span class="HTitleText2">Establishment of Plans</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-434310"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-434313"><span class="HTitleText2">Registered Pension Plans Account</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-1.html#h-434329"><span class="HTitleText1">Retirement Compensation Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-434330"><span class="HTitleText2">Establishment of Arrangements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-434382"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-434392"><span class="HTitleText2">Retirement Compensation Arrangements Account</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="page-2.html#h-434416"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

