<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord sur la Station spatiale internationale civile</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-83110"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-83113"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-83118"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-83127"><span class="HTitleText1">Renseignements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-83148"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-83151"><span class="HTitleText1">Modification de l’accord</span></a>
</li>
<li><span class='sectionRange'>11 et 12 - </span><a href="#h-83154"><span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-83156"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-83160"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Accord entre le gouvernement du Canada, les gouvernements d’États membres de l’Agence spatiale européenne, le gouvernement du Japon, le gouvernement de la Fédération de Russie et le gouvernement des États-Unis d’Amérique sur la coopération relative à la Station spatiale internationale civile</span></a>
</li>
<li><a href="#h-83403"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - Éléments de la Station spatiale à fournir par les Partenaires</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
