<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’aide à l’exécution des ordonnances et des ententes familiales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-215917"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-215920"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Communication de renseignements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-215921"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-215939"><span class="HTitleText2">Accords fédéro-provinciaux</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-215954"><span class="HTitleText2">Requête au tribunal</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-215983"><span class="HTitleText2">Demande de communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-216039"><span class="HTitleText2">Instruction de la demande</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-216058"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-2.html#h-216070"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Saisie-arrêt de sommes fédérales pour l’exécution d’ordonnances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-2.html#h-216071"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-216087"><span class="HTitleText2">Saisie-arrêt entre les mains de Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-216098"><span class="HTitleText2">Bref de saisie-arrêt</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-216110"><span class="HTitleText2">Bref de saisie-arrêt à effet continu</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-216117"><span class="HTitleText2">Signification des documents</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-2.html#h-216126"><span class="HTitleText2">Procédures administratives</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-2.html#h-216139"><span class="HTitleText2">Donner suite à un bref de saisie-arrêt</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-2.html#h-216146"><span class="HTitleText2">Paiement libératoire</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-3.html#h-216152"><span class="HTitleText2">Avis au débiteur</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-216158"><span class="HTitleText2">Recouvrement du paiement excédentaire</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-216165"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-3.html#h-216174"><span class="HTitleText2">Loi sur la saisie-arrêt et la distraction de pensions</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-3.html#h-216177"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-3.html#h-216182"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-3.html#h-216189"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="page-3.html#h-216206"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Refus d’autorisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="page-3.html#h-216207"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-3.html#h-216228"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="page-3.html#h-216233"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-3.html#h-216242"><span class="HTitleText2">Demandes de refus d’autorisation</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-4.html#h-216273"><span class="HTitleText2">Devoirs du ministre compétent</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-4.html#h-216287"><span class="HTitleText2">Aucun appel</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="page-4.html#h-216292"><span class="HTitleText2">Cessation d’effet des mesures</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-4.html#h-216320"><span class="HTitleText2">Infraction</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-4.html#h-216330"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>78.1 - </span><a href="page-4.html#h-216335"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78.1 - </span><a href="page-4.html#h-1161685"><span class="HTitleText2">Absence de responsabilité</span></a>
</li>
<li><span class='sectionRange'>78.2 - </span><a href="page-4.html#h-1161694"><span class="HTitleText2">Travaux de recherche</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-4.html#h-216336"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-4.html#h-216344"><span class="HTitleText2">Interdiction, infraction et peine</span></a>
</li></ul>
</li><li><a href="page-5.html#h-216358"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Autorisations</span></a>
</li></ul>
</li></ul>

</nav>

