<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tax Court of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">The Court</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">The Judges</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-5"><span class="HTitleText1">Jurisdiction and Powers of the Court</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">Proceedings Before the Court</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText2">General Procedure</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText2">Informal Procedure</span></a>
</li>
<li><span class='sectionRange'>18.31 - </span><a href="#h-9"><span class="HTitleText2">References</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText1">Oaths and Affidavits</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HTitleText1">Rules</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-12"><span class="HTitleText1">Administration of Court</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-13"><span class="HTitleText1">Transitional</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
