<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting first nations goods and services tax</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-226395"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-226398"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-226421"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">First Nations Goods and Services Tax Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-226422"><span class="HTitleText2">Application of other Acts of Parliament</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-226434"><span class="HTitleText2">First Nation Goods and Services Tax Law</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-226589"><span class="HTitleText2">First Nation Law Enacted Under Separate Power</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-226605"><span class="HTitleText2">Administration Agreement and Part IX of Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-226608"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-226614"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-226626"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">First Nations Sales Tax — Specified Provinces</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-226627"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-226640"><span class="HTitleText2">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-226660"><span class="HTitleText2">Administration Agreement</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-226665"><span class="HTitleText2">Delegation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-226704"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><a href="#h-226710"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-226720"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>

