<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Bank Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-10042"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-10045"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Interpretation and Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-10046"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-10196"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10439"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-10489"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Status and Powers</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10541"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Incorporation and Continuance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-10542"><span class="HTitleText2">Formalities of Incorporation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-10636"><span class="HTitleText2">Continuance</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-10756"><span class="HTitleText2">Discontinuance</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-10796"><span class="HTitleText2">Corporate Name</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-10844"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Organization and Commencement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-10845"><span class="HTitleText2">Organization Meetings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-10846"><span class="HTitleText3">Banks Other Than Federal Credit Unions</span></a>
</li>
<li><span class='sectionRange'>47.01 - </span><a href="#h-10875"><span class="HTitleText3">Federal Credit Unions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47.01 - </span><a href="#h-10876"><span class="HTitleText4">Meeting of First Directors</span></a>
</li>
<li><span class='sectionRange'>47.02 - </span><a href="#h-10891"><span class="HTitleText4">First Meeting of Members</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>47.03 - </span><a href="#h-10904"><span class="HTitleText2">Membership in a Federal Credit Union</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47.03 - </span><a href="#h-10905"><span class="HTitleText3">Conditions of Membership</span></a>
</li>
<li><span class='sectionRange'>47.05 - </span><a href="#h-10924"><span class="HTitleText3">Withdrawal and Termination</span></a>
</li></ul>
</li><li><span class='sectionRange'>47.11 - </span><a href="#h-10967"><span class="HTitleText2">General Provisions — Federal Credit Unions</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-11012"><span class="HTitleText2">Commencement and Carrying on of Business</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-11116"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Capital Structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-11117"><span class="HTitleText2">Share Capital</span></a>
</li>
<li><span class='sectionRange'>79.1 - </span><a href="#h-11387"><span class="HTitleText2">Membership Capital</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-11433"><span class="HTitleText2">Subordinated Indebtedness</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-11443"><span class="HTitleText2">Security Certificates and Transfers</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-11846"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Corporate Governance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-11847"><span class="HTitleText2">Shareholders and Members</span></a>
</li>
<li><span class='sectionRange'>156.01 - </span><a href="#h-12163"><span class="HTitleText2">Proxies</span></a>
</li>
<li><span class='sectionRange'>156.09 - </span><a href="#h-12281"><span class="HTitleText2">Restrictions on Voting</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-12311"><span class="HTitleText2">Directors and Officers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-12312"><span class="HTitleText3">Duties</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-12340"><span class="HTitleText3">Qualification and Number — Directors</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-12394"><span class="HTitleText3">Election and Tenure — Directors</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-12469"><span class="HTitleText3">Incomplete Elections and Director Vacancies</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-12575"><span class="HTitleText3">Meetings of the Board</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-12669"><span class="HTitleText3">By-laws</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-12798"><span class="HTitleText3">Committees of the Board</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-12845"><span class="HTitleText3">Directors and Officers — Authority</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-12903"><span class="HTitleText3">Conflicts of Interest</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-12966"><span class="HTitleText3">Liability, Exculpation and Indemnification</span></a>
</li></ul>
</li><li><span class='sectionRange'>215 - </span><a href="#h-13056"><span class="HTitleText2">Fundamental Changes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>215 - </span><a href="#h-13057"><span class="HTitleText3">Amendments — Letters Patent</span></a>
</li>
<li><span class='sectionRange'>216.01 - </span><a href="#h-13069"><span class="HTitleText3">Conversion into Federal Credit Union</span></a>
</li>
<li><span class='sectionRange'>216.08 - </span><a href="#h-13131"><span class="HTitleText3">Conversion into Bank with Common Shares</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-13197"><span class="HTitleText3">Amendments — By-laws</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-13253"><span class="HTitleText3">Amalgamation</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-13416"><span class="HTitleText3">Transfer of Business</span></a>
</li></ul>
</li><li><span class='sectionRange'>237 - </span><a href="#h-13456"><span class="HTitleText2">Corporate Records</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>237 - </span><a href="#h-13457"><span class="HTitleText3">Head Office and Corporate Records</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-13579"><span class="HTitleText3">Securities Registers</span></a>
</li>
<li><span class='sectionRange'>254.1 - </span><a href="#h-13623"><span class="HTitleText3">Members Register</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-13672"><span class="HTitleText3">Corporate Name and Seal</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-13683"><span class="HTitleText3">Insiders</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="#h-13705"><span class="HTitleText3">Insider Reporting</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-13723"><span class="HTitleText3">Insider Trading</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-13741"><span class="HTitleText3">Civil remedies</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-13804"><span class="HTitleText3">Prospectus</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-13832"><span class="HTitleText3">Going-private Transactions and Squeeze-out Transactions</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="#h-13914"><span class="HTitleText3">Compulsory Acquisitions</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-14041"><span class="HTitleText3">Trust Indentures</span></a>
</li></ul>
</li><li><span class='sectionRange'>307 - </span><a href="#h-14123"><span class="HTitleText2">Financial Statements and Auditors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>307 - </span><a href="#h-14124"><span class="HTitleText3">Annual Financial Statement</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-14200"><span class="HTitleText3">Auditors</span></a>
</li>
<li><span class='sectionRange'>334 - </span><a href="#h-14400"><span class="HTitleText3">Remedial Actions</span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="#h-14453"><span class="HTitleText3">Liquidation and Dissolution</span></a>
</li>
<li><span class='sectionRange'>342 - </span><a href="#h-14465"><span class="HTitleText3">Simple Liquidation</span></a>
</li>
<li><span class='sectionRange'>347 - </span><a href="#h-14513"><span class="HTitleText3">Court-supervised Liquidation</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-14649"><span class="HTitleText3">General</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>370 - </span><a href="#h-14716"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Ownership</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>370 - </span><a href="#h-14717"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Definitions and Interpretation</span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="#h-14777"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Ownership of Banks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>372 - </span><a href="#h-14778"><span class="HTitleText3">Constraints on Ownership</span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="#h-15127"><span class="HTitleText3">Approval Process</span></a>
</li></ul>
</li><li><span class='sectionRange'>402 - </span><a href="#h-15252"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">Directions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>404 - </span><a href="#h-15279"><span class="HTitleText3">General Provisions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>409 - </span><a href="#h-15307"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Business and Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>409 - </span><a href="#h-15308"><span class="HTitleText2">General Business</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>425 - </span><a href="#h-15576"><span class="HTitleText3">Special Security</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="#h-15900"><span class="HTitleText3">Deposit Acceptance</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="#h-15917"><span class="HTitleText3">Unclaimed Balances</span></a>
</li>
<li><span class='sectionRange'>439.1 - </span><a href="#h-15971"><span class="HTitleText3">Accounts</span></a>
</li>
<li><span class='sectionRange'>448.3 - </span><a href="#h-16056"><span class="HTitleText3">Registered Products</span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-16070"><span class="HTitleText3">Borrowing Costs</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="#h-16152"><span class="HTitleText3">Complaints</span></a>
</li></ul>
</li><li><span class='sectionRange'>457 - </span><a href="#h-16213"><span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>464 - </span><a href="#h-16405"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Investments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>464 - </span><a href="#h-16406"><span class="HTitleText2">Definitions and Application</span></a>
</li>
<li><span class='sectionRange'>465 - </span><a href="#h-16452"><span class="HTitleText2">General Constraints on Investments</span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-16515"><span class="HTitleText2">Subsidiaries and Equity Investments</span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="#h-16660"><span class="HTitleText2">Exceptions and Exclusions</span></a>
</li>
<li><span class='sectionRange'>475 - </span><a href="#h-16723"><span class="HTitleText2">Portfolio Limits</span></a>
</li>
<li><span class='sectionRange'>476 - </span><a href="#h-16737"><span class="HTitleText2">Real Property</span></a>
</li>
<li><span class='sectionRange'>477 - </span><a href="#h-16742"><span class="HTitleText2">Equities</span></a>
</li>
<li><span class='sectionRange'>478 - </span><a href="#h-16753"><span class="HTitleText2">Aggregate Limit</span></a>
</li>
<li><span class='sectionRange'>479 - </span><a href="#h-16767"><span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>484.1 - </span><a href="#h-16857"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Capital, Liquidity and Capacity to Absorb Losses</span></a>
</li>
<li><span class='sectionRange'>485.1 - </span><a href="#h-16915"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Self-dealing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>485.1 - </span><a href="#h-16916"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>489 - </span><a href="#h-16997"><span class="HTitleText2">Prohibited Related Party Transactions</span></a>
</li>
<li><span class='sectionRange'>490 - </span><a href="#h-17007"><span class="HTitleText2">Permitted Related Party Transactions</span></a>
</li>
<li><span class='sectionRange'>501 - </span><a href="#h-17171"><span class="HTitleText2">Restrictions on Permitted Transactions</span></a>
</li>
<li><span class='sectionRange'>504 - </span><a href="#h-17184"><span class="HTitleText2">Disclosure</span></a>
</li>
<li><span class='sectionRange'>506 - </span><a href="#h-17194"><span class="HTitleText2">Remedial Actions</span></a>
</li></ul>
</li><li><span class='sectionRange'>507 - </span><a href="#h-17204"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Foreign Banks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>507 - </span><a href="#h-17205"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>510 - </span><a href="#h-17385"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">General Prohibitions and Exceptions</span></a>
</li>
<li><span class='sectionRange'>522.04 - </span><a href="#h-17629"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">No Financial Establishment in Canada</span></a>
</li>
<li><span class='sectionRange'>522.07 - </span><a href="#h-17658"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Financial Establishment in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>522.07 - </span><a href="#h-17659"><span class="HTitleText3">Investments</span></a>
</li>
<li><span class='sectionRange'>522.16 - </span><a href="#h-17785"><span class="HTitleText3">Branches</span></a>
</li></ul>
</li><li><span class='sectionRange'>522.2 - </span><a href="#h-17818"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Approvals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>522.2 - </span><a href="#h-17819"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>522.21 - </span><a href="#h-17824"><span class="HTitleText3">Approval to Have a Financial Establishment in Canada</span></a>
</li>
<li><span class='sectionRange'>522.22 - </span><a href="#h-17851"><span class="HTitleText3">Approvals in Respect of Investments and Activities</span></a>
</li></ul>
</li><li><span class='sectionRange'>522.23 - </span><a href="#h-17880"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>522.28 - </span><a href="#h-17916"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">[Repealed, 2007, c. 6, s. 72]</span></a>
</li>
<li><span class='sectionRange'>522.29 - </span><a href="#h-17918"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>522.34 - </span><a href="#h-17989"><span class="HLabel1">PART XII.01</span> - <span class="HTitleText1">Non-Application of the Investment Canada Act</span></a>
</li>
<li><span class='sectionRange'>523 - </span><a href="#h-18008"><span class="HLabel1">PART XII.1</span> - <span class="HTitleText1">Authorized Foreign Banks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>523 - </span><a href="#h-18009"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>524 - </span><a href="#h-18017"><span class="HTitleText2">Formalities of Authorization</span></a>
</li>
<li><span class='sectionRange'>534 - </span><a href="#h-18163"><span class="HTitleText2">Commencement and Carrying on of Business in Canada</span></a>
</li>
<li><span class='sectionRange'>535 - </span><a href="#h-18195"><span class="HTitleText2">Principal Office and Principal Officer</span></a>
</li>
<li><span class='sectionRange'>537 - </span><a href="#h-18214"><span class="HTitleText2">Transfer of Liabilities</span></a>
</li>
<li><span class='sectionRange'>538 - </span><a href="#h-18227"><span class="HTitleText2">Business and Powers</span></a>
</li>
<li><span class='sectionRange'>556 - </span><a href="#h-18484"><span class="HTitleText2">Deposit Acceptance</span></a>
</li>
<li><span class='sectionRange'>557 - </span><a href="#h-18501"><span class="HTitleText2">Unclaimed Balances</span></a>
</li>
<li><span class='sectionRange'>559 - </span><a href="#h-18551"><span class="HTitleText2">Accounts</span></a>
</li>
<li><span class='sectionRange'>566.1 - </span><a href="#h-18610"><span class="HTitleText2">Registered Products</span></a>
</li>
<li><span class='sectionRange'>567 - </span><a href="#h-18624"><span class="HTitleText2">Borrowing Costs</span></a>
</li>
<li><span class='sectionRange'>573 - </span><a href="#h-18708"><span class="HTitleText2">Complaints</span></a>
</li>
<li><span class='sectionRange'>574.1 - </span><a href="#h-18739"><span class="HTitleText2">Miscellaneous</span></a>
</li>
<li><span class='sectionRange'>582 - </span><a href="#h-18891"><span class="HTitleText2">Deposit Requirements</span></a>
</li>
<li><span class='sectionRange'>583 - </span><a href="#h-18903"><span class="HTitleText2">Financial Year</span></a>
</li>
<li><span class='sectionRange'>584 - </span><a href="#h-18911"><span class="HTitleText2">Auditors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>584 - </span><a href="#h-18912"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>585 - </span><a href="#h-18917"><span class="HTitleText3">Appointment</span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-18994"><span class="HTitleText3">Examinations and Reports</span></a>
</li></ul>
</li><li><span class='sectionRange'>597 - </span><a href="#h-19045"><span class="HTitleText2">Records</span></a>
</li>
<li><span class='sectionRange'>599 - </span><a href="#h-19076"><span class="HTitleText2">Termination of Business in Canada</span></a>
</li>
<li><span class='sectionRange'>600 - </span><a href="#h-19092"><span class="HTitleText2">Supervision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>600 - </span><a href="#h-19093"><span class="HTitleText3">Returns</span></a>
</li>
<li><span class='sectionRange'>613 - </span><a href="#h-19189"><span class="HTitleText3">Inspection of Authorized Foreign Banks</span></a>
</li></ul>
</li><li><span class='sectionRange'>614.1 - </span><a href="#h-19203"><span class="HTitleText2">Remedial Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>614.1 - </span><a href="#h-19204"><span class="HTitleText3">Prudential Agreements</span></a>
</li>
<li><span class='sectionRange'>615 - </span><a href="#h-19209"><span class="HTitleText3">Directions of Compliance</span></a>
</li>
<li><span class='sectionRange'>617 - </span><a href="#h-19234"><span class="HTitleText3">Asset Maintenance</span></a>
</li>
<li><span class='sectionRange'>617.1 - </span><a href="#h-19241"><span class="HTitleText3">Disqualification and Removal of Principal Officers</span></a>
</li>
<li><span class='sectionRange'>618 - </span><a href="#h-19291"><span class="HTitleText3">Supervisory Intervention</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>628 - </span><a href="#h-19372"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Regulation of Banks — Superintendent</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>628 - </span><a href="#h-19373"><span class="HTitleText2">Supervision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>628 - </span><a href="#h-19374"><span class="HTitleText3">Returns</span></a>
</li>
<li><span class='sectionRange'>643 - </span><a href="#h-19506"><span class="HTitleText3">Inspection of Banks</span></a>
</li></ul>
</li><li><span class='sectionRange'>644.1 - </span><a href="#h-19520"><span class="HTitleText2">Remedial Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>644.1 - </span><a href="#h-19521"><span class="HTitleText3">Prudential Agreements</span></a>
</li>
<li><span class='sectionRange'>645 - </span><a href="#h-19526"><span class="HTitleText3">Directions of Compliance</span></a>
</li>
<li><span class='sectionRange'>646.1 - </span><a href="#h-19551"><span class="HTitleText3">Disqualification and Removal of Directors or Senior Officers</span></a>
</li>
<li><span class='sectionRange'>648 - </span><a href="#h-19615"><span class="HTitleText3">Supervisory Intervention</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>657 - </span><a href="#h-19692"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Regulation of Banks and External Complaints Bodies — Commissioner</span></a>
</li>
<li><span class='sectionRange'>662 - </span><a href="#h-19725"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">Bank Holding Companies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>662 - </span><a href="#h-19726"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>663 - </span><a href="#h-19731"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>664 - </span><a href="#h-19746"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Status and Powers</span></a>
</li>
<li><span class='sectionRange'>671 - </span><a href="#h-19797"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Incorporation and Continuance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>671 - </span><a href="#h-19798"><span class="HTitleText3">Formalities of Incorporation</span></a>
</li>
<li><span class='sectionRange'>682 - </span><a href="#h-19883"><span class="HTitleText3">Continuance</span></a>
</li>
<li><span class='sectionRange'>689 - </span><a href="#h-19952"><span class="HTitleText3">Discontinuance</span></a>
</li>
<li><span class='sectionRange'>693 - </span><a href="#h-19977"><span class="HTitleText3">Corporate Name</span></a>
</li>
<li><span class='sectionRange'>699 - </span><a href="#h-20029"><span class="HTitleText3">Publication of Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>700 - </span><a href="#h-20036"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Organization and Commencement</span></a>
</li>
<li><span class='sectionRange'>703 - </span><a href="#h-20065"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Capital Structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>703 - </span><a href="#h-20066"><span class="HTitleText3">Share Capital</span></a>
</li>
<li><span class='sectionRange'>723 - </span><a href="#h-20293"><span class="HTitleText3">Subordinated Indebtedness</span></a>
</li>
<li><span class='sectionRange'>724 - </span><a href="#h-20303"><span class="HTitleText3">Security Certificates and Transfers</span></a>
</li></ul>
</li><li><span class='sectionRange'>725 - </span><a href="#h-20314"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Corporate Governance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>725 - </span><a href="#h-20315"><span class="HTitleText3">Shareholders</span></a>
</li>
<li><span class='sectionRange'>746 - </span><a href="#h-20566"><span class="HTitleText3">Proxies and Voting Restrictions</span></a>
</li>
<li><span class='sectionRange'>747 - </span><a href="#h-20576"><span class="HTitleText3">Directors and Officers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>747 - </span><a href="#h-20577"><span class="HTitleText4">Duties</span></a>
</li>
<li><span class='sectionRange'>749 - </span><a href="#h-20604"><span class="HTitleText4">Qualification and Number — Directors</span></a>
</li>
<li><span class='sectionRange'>753 - </span><a href="#h-20634"><span class="HTitleText4">Election and Tenure — Directors</span></a>
</li>
<li><span class='sectionRange'>758 - </span><a href="#h-20705"><span class="HTitleText4">Incomplete Elections and Director Vacancies</span></a>
</li>
<li><span class='sectionRange'>769 - </span><a href="#h-20800"><span class="HTitleText4">Meetings of the Board</span></a>
</li>
<li><span class='sectionRange'>778 - </span><a href="#h-20889"><span class="HTitleText4">By-laws</span></a>
</li>
<li><span class='sectionRange'>781 - </span><a href="#h-20912"><span class="HTitleText4">Committees of the Board</span></a>
</li>
<li><span class='sectionRange'>783 - </span><a href="#h-20937"><span class="HTitleText4">Directors and Officers — Authority</span></a>
</li>
<li><span class='sectionRange'>789 - </span><a href="#h-20982"><span class="HTitleText4">Conflicts of Interest</span></a>
</li>
<li><span class='sectionRange'>794 - </span><a href="#h-21043"><span class="HTitleText4">Liability, Exculpation and Indemnification</span></a>
</li></ul>
</li><li><span class='sectionRange'>802 - </span><a href="#h-21134"><span class="HTitleText3">Fundamental Changes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>802 - </span><a href="#h-21135"><span class="HTitleText4">Amendments</span></a>
</li>
<li><span class='sectionRange'>803 - </span><a href="#h-21144"><span class="HTitleText4">Amalgamation</span></a>
</li>
<li><span class='sectionRange'>813 - </span><a href="#h-21289"><span class="HTitleText4">Transfer of Business</span></a>
</li></ul>
</li><li><span class='sectionRange'>814 - </span><a href="#h-21307"><span class="HTitleText3">Corporate Records</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>814 - </span><a href="#h-21308"><span class="HTitleText4">Head Office and Corporate Records</span></a>
</li>
<li><span class='sectionRange'>825 - </span><a href="#h-21423"><span class="HTitleText4">Securities Registers</span></a>
</li>
<li><span class='sectionRange'>832 - </span><a href="#h-21479"><span class="HTitleText4">Corporate Name and Seal</span></a>
</li>
<li><span class='sectionRange'>834 - </span><a href="#h-21491"><span class="HTitleText4">Insiders</span></a>
</li>
<li><span class='sectionRange'>835 - </span><a href="#h-21496"><span class="HTitleText4">Prospectus</span></a>
</li>
<li><span class='sectionRange'>835.1 - </span><a href="#h-21501"><span class="HTitleText4">Going-private Transactions and Squeeze-out Transactions</span></a>
</li>
<li><span class='sectionRange'>836 - </span><a href="#h-21509"><span class="HTitleText4">Compulsory Acquisitions</span></a>
</li>
<li><span class='sectionRange'>838 - </span><a href="#h-21521"><span class="HTitleText4">Trust Indentures</span></a>
</li></ul>
</li><li><span class='sectionRange'>839 - </span><a href="#h-21529"><span class="HTitleText3">Financial Statements and Auditor</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>839 - </span><a href="#h-21530"><span class="HTitleText4">Annual Financial Statement</span></a>
</li>
<li><span class='sectionRange'>845 - </span><a href="#h-21599"><span class="HTitleText4">Auditors</span></a>
</li>
<li><span class='sectionRange'>865 - </span><a href="#h-21801"><span class="HTitleText4">Remedial Actions</span></a>
</li>
<li><span class='sectionRange'>866 - </span><a href="#h-21808"><span class="HTitleText4">Liquidation and Dissolution</span></a>
</li>
<li><span class='sectionRange'>869 - </span><a href="#h-21826"><span class="HTitleText4">Simple Liquidation</span></a>
</li>
<li><span class='sectionRange'>870 - </span><a href="#h-21833"><span class="HTitleText4">Court-supervised Liquidation</span></a>
</li>
<li><span class='sectionRange'>871 - </span><a href="#h-21841"><span class="HTitleText4">General</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>873 - </span><a href="#h-21860"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Ownership</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>873 - </span><a href="#h-21861"><span class="HTitleText3">Constraints on Ownership</span></a>
</li>
<li><span class='sectionRange'>905 - </span><a href="#h-22143"><span class="HTitleText3">Approval Process</span></a>
</li></ul>
</li><li><span class='sectionRange'>922 - </span><a href="#h-22306"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Business and Powers</span></a>
</li>
<li><span class='sectionRange'>925 - </span><a href="#h-22335"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Investments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>925 - </span><a href="#h-22336"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>926 - </span><a href="#h-22352"><span class="HTitleText3">Investments</span></a>
</li>
<li><span class='sectionRange'>927 - </span><a href="#h-22357"><span class="HTitleText3">General Constraints on Investments</span></a>
</li>
<li><span class='sectionRange'>930 - </span><a href="#h-22418"><span class="HTitleText3">Subsidiaries and Equity Investments</span></a>
</li>
<li><span class='sectionRange'>933 - </span><a href="#h-22563"><span class="HTitleText3">Exceptions and Exclusions</span></a>
</li>
<li><span class='sectionRange'>937 - </span><a href="#h-22614"><span class="HTitleText3">Portfolio Limits</span></a>
</li>
<li><span class='sectionRange'>938 - </span><a href="#h-22628"><span class="HTitleText3">Real Property</span></a>
</li>
<li><span class='sectionRange'>939 - </span><a href="#h-22633"><span class="HTitleText3">Equities</span></a>
</li>
<li><span class='sectionRange'>940 - </span><a href="#h-22644"><span class="HTitleText3">Aggregate Limit</span></a>
</li>
<li><span class='sectionRange'>941 - </span><a href="#h-22658"><span class="HTitleText3">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>949 - </span><a href="#h-22787"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">Adequacy of Capital and Liquidity</span></a>
</li>
<li><span class='sectionRange'>950 - </span><a href="#h-22804"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2">Regulation of Bank Holding Companies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>950 - </span><a href="#h-22805"><span class="HTitleText3">Supervision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>950 - </span><a href="#h-22806"><span class="HTitleText4">Returns</span></a>
</li></ul>
</li><li><span class='sectionRange'>957 - </span><a href="#h-22903"><span class="HTitleText3">Inspection of Bank Holding Companies</span></a>
</li>
<li><span class='sectionRange'>959 - </span><a href="#h-22917"><span class="HTitleText3">Remedial Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>959 - </span><a href="#h-22918"><span class="HTitleText4">Prudential Agreements</span></a>
</li>
<li><span class='sectionRange'>960 - </span><a href="#h-22923"><span class="HTitleText4">Directions of Compliance</span></a>
</li>
<li><span class='sectionRange'>962 - </span><a href="#h-22946"><span class="HTitleText4">Disqualification and Removal of Directors or Senior Officers</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>964.1 - </span><a href="#h-23007"><span class="HLabel1">PART XVI</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>964.1 - </span><a href="#h-23008"><span class="HTitleText2">Notices and Other Documents</span></a>
</li>
<li><span class='sectionRange'>973 - </span><a href="#h-23071"><span class="HTitleText2">Approvals</span></a>
</li>
<li><span class='sectionRange'>973.07 - </span><a href="#h-23132"><span class="HTitleText2">Exceptions to Generally Accepted Accounting Principles</span></a>
</li>
<li><span class='sectionRange'>973.1 - </span><a href="#h-23142"><span class="HTitleText2">Short-term Exemption Order</span></a>
</li>
<li><span class='sectionRange'>973.2 - </span><a href="#h-23150"><span class="HTitleText2">Orders to Exempt or Adapt</span></a>
</li>
<li><span class='sectionRange'>974 - </span><a href="#h-23196"><span class="HTitleText2">Orders and Directives</span></a>
</li>
<li><span class='sectionRange'>976 - </span><a href="#h-23205"><span class="HTitleText2">Applications to Superintendent</span></a>
</li>
<li><span class='sectionRange'>976.1 - </span><a href="#h-23225"><span class="HTitleText2">Applications for Certain Approvals</span></a>
</li>
<li><span class='sectionRange'>977 - </span><a href="#h-23248"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>978 - </span><a href="#h-23261"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>979 - </span><a href="#h-23283"><span class="HTitleText2">Delegation</span></a>
</li></ul>
</li><li><span class='sectionRange'>980 - </span><a href="#h-23288"><span class="HLabel1">PART XVII</span> - <span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>992 - </span><a href="#h-23525"><span class="HLabel1">PART XVIII</span> - <span class="HTitleText1">Documents in Electronic or Other Form</span></a>
</li>
<li><a href="#h-1115190"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-1115199"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="#h-1115208"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
