<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Energy Costs Assistance Measures Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-218969"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-218972"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Energy Cost Benefit</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-218989"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-218990"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-218993"><span class="HTitleText3">Old Age Security Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="page-1.html#h-218995"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Reduction of Housing Energy Consumption</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-219005"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Public Transit</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-219015"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Coordinating Amendments</span></a>
</li></ul>
</li></ul>

</nav>

