<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Defence Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Department of National Defence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Minister</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Deputy Minister</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Judge Advocate General</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText2">Materiel</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HLabel1">PART II</span> - <span class="HTitleText1">The Canadian Forces</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText2">Units and Other Elements</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText2">Chief of the Defence Staff</span></a>
</li>
<li><span class='sectionRange'>18.3 - </span><a href="#h-14"><span class="HTitleText2">Canadian Forces Provost Marshal</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-15"><span class="HTitleText2">Powers of Command</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-16"><span class="HTitleText2">Enrolment</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText2">Attachment and Secondment</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText2">Promotion</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-19"><span class="HTitleText2">Grievances</span></a>
</li>
<li><span class='sectionRange'>29.16 - </span><a href="#h-20"><span class="HTitleText2">Military Grievances External Review Committee</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-21"><span class="HTitleText2">Release</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-22"><span class="HTitleText2">Active Service</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-23"><span class="HTitleText2">Service</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-24"><span class="HTitleText2">Limitation on Deployment</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-25"><span class="HTitleText2">Pay and Allowances</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-26"><span class="HTitleText2">Supply and Issue of Materiel</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-27"><span class="HTitleText2">Public Property</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-28"><span class="HTitleText2">Non-public Property</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-29"><span class="HTitleText2">Service Estates</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-30"><span class="HTitleText2">Presumption of Death</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-31"><span class="HTitleText2">Personal Effects of Absentees</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-32"><span class="HTitleText2">Boards of Inquiry</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-33"><span class="HTitleText2">Cadet Organizations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-34"><span class="HTitleText2">Educational Institutions</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-35"><span class="HTitleText2">Service Associations</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-36"><span class="HTitleText2">Exercise of Authority</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-37"><span class="HTitleText2">Notification of Orders</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-38"><span class="HTitleText2">Validity of Documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 to 59 - </span><a href="#h-39"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Code of Service Discipline</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 to 59 - </span><a href="#h-40"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Disciplinary Jurisdiction of the Canadian Forces</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 to 59 - </span><a href="#h-41"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-42"><span class="HTitleText3">Plea in Bar of Trial</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-43"><span class="HTitleText3">Place of Commission of Offence</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-44"><span class="HTitleText3">Place of Trial</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-45"><span class="HTitleText3">Period of Liability</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-46"><span class="HTitleText3">Limitations with respect to Certain Offences</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-47"><span class="HTitleText3">Jurisdiction of Civil Courts</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="#h-48"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Service Offences and Punishments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-49"><span class="HTitleText3">Responsibility for Offences</span></a>
</li>
<li><span class='sectionRange'>72.1 - </span><a href="#h-50"><span class="HTitleText3">Civil Defences</span></a>
</li>
<li><span class='sectionRange'>72.2 - </span><a href="#h-51"><span class="HTitleText3">Ignorance of the Law</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-52"><span class="HTitleText3">Misconduct of Commanders in Presence of Enemy</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-53"><span class="HTitleText3">Misconduct of any Person in Presence of Enemy</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-54"><span class="HTitleText3">Security</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-55"><span class="HTitleText3">Prisoners of War</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-56"><span class="HTitleText3">Miscellaneous Operational Offences</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-57"><span class="HTitleText3">Spies for the Enemy</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-58"><span class="HTitleText3">Mutiny</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-59"><span class="HTitleText3">Seditious Offences</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-60"><span class="HTitleText3">Insubordination</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-61"><span class="HTitleText3">Desertion</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-62"><span class="HTitleText3">Absence without Leave</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-63"><span class="HTitleText3">Disgraceful Conduct</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-64"><span class="HTitleText3">Offences in relation to Service Arrest and Custody</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-65"><span class="HTitleText3">Offences in relation to Vessels</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-66"><span class="HTitleText3">Offences in relation to Aircraft</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-67"><span class="HTitleText3">Offences in relation to Vehicles</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-68"><span class="HTitleText3">Offences in relation to Property</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-69"><span class="HTitleText3">Offences in relation to Tribunals</span></a>
</li>
<li><span class='sectionRange'>119.1 - </span><a href="#h-70"><span class="HTitleText3">Offence in Relation to the <cite class="XRefExternalAct">Sex Offender Information Registration Act</cite></span></a>
</li>
<li><span class='sectionRange'>119.2 - </span><a href="#h-71"><span class="HTitleText3">Offence in Relation to DNA Identification</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-72"><span class="HTitleText3">Offences in relation to Billeting</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-73"><span class="HTitleText3">Offences in relation to Enrolment</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-74"><span class="HTitleText3">Miscellaneous Offences</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-75"><span class="HTitleText3">Conduct to the Prejudice of Good Order and Discipline</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-76"><span class="HTitleText3">Offences Punishable by Ordinary Law</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-77"><span class="HTitleText3">Conviction of Cognate Offence</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-78"><span class="HTitleText3">Punishments</span></a>
</li>
<li><span class='sectionRange'>147.1 - </span><a href="#h-79"><span class="HTitleText3">Prohibition Orders</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-80"><span class="HTitleText3">Sentences</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-81"><span class="HTitleText3">Incarceration under more than one Sentence</span></a>
</li>
<li><span class='sectionRange'>149.2 - </span><a href="#h-82"><span class="HTitleText3">Punishment for Certain Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-83"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Arrest and Pre-Trial Custody</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-84"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-85"><span class="HTitleText3">Authority to Arrest</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-86"><span class="HTitleText3">Action following Arrest</span></a>
</li>
<li><span class='sectionRange'>158.2 - </span><a href="#h-87"><span class="HTitleText3">Initial Review</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-88"><span class="HTitleText3">Review by Military Judge</span></a>
</li>
<li><span class='sectionRange'>159.8 - </span><a href="#h-89"><span class="HTitleText3">Duty of Director of Military Prosecutions</span></a>
</li>
<li><span class='sectionRange'>159.9 - </span><a href="#h-90"><span class="HTitleText3">Review by Court Martial Appeal Court</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="#h-91"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Commencement of Proceedings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>160 - </span><a href="#h-92"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-93"><span class="HTitleText3">Laying of Charge</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-94"><span class="HTitleText3">Duty to Act Expeditiously</span></a>
</li>
<li><span class='sectionRange'>162.1 - </span><a href="#h-95"><span class="HTitleText3">Right to Trial by Court Martial</span></a>
</li></ul>
</li><li><span class='sectionRange'>162.3 - </span><a href="#h-96"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Summary Trials</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>162.3 - </span><a href="#h-97"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-98"><span class="HTitleText3">Summary Trials by Commanding Officers</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-99"><span class="HTitleText3">Summary Trial by Superior Commanders</span></a>
</li>
<li><span class='sectionRange'>164.2 - </span><a href="#h-100"><span class="HTitleText3">Referral to Director of Military Prosecutions</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-101"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Trial by Court Martial</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-102"><span class="HTitleText3">Charge must be Preferred</span></a>
</li>
<li><span class='sectionRange'>165.1 - </span><a href="#h-103"><span class="HTitleText3">Director of Military Prosecutions</span></a>
</li>
<li><span class='sectionRange'>165.18 - </span><a href="#h-104"><span class="HTitleText3">Court Martial Administrator</span></a>
</li>
<li><span class='sectionRange'>165.21 - </span><a href="#h-105"><span class="HTitleText3">Military Judges</span></a>
</li>
<li><span class='sectionRange'>165.22 - </span><a href="#h-106"><span class="HTitleText3">Reserve Force Military Judges</span></a>
</li>
<li><span class='sectionRange'>165.23 - </span><a href="#h-107"><span class="HTitleText3">Duties and Immunity of Military Judges</span></a>
</li>
<li><span class='sectionRange'>165.24 - </span><a href="#h-108"><span class="HTitleText3">Chief Military Judge</span></a>
</li>
<li><span class='sectionRange'>165.31 - </span><a href="#h-109"><span class="HTitleText3">Military Judges Inquiry Committee</span></a>
</li>
<li><span class='sectionRange'>165.33 - </span><a href="#h-110"><span class="HTitleText3">Military Judges Compensation Committee</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-111"><span class="HTitleText3">General Courts Martial</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-112"><span class="HTitleText3">Standing Courts Martial</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-113"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-114"><span class="HTitleText3">Admission to Courts Martial</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-115"><span class="HTitleText3">Rules of Evidence</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-116"><span class="HTitleText3">Witnesses at Courts Martial</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-117"><span class="HTitleText3">Evidence on Commission</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-118"><span class="HTitleText3">Objections</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-119"><span class="HTitleText3">Preliminary Proceedings</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-120"><span class="HTitleText3">Amendment of Charges</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-121"><span class="HTitleText3">Adjournments</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-122"><span class="HTitleText3">Views</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-123"><span class="HTitleText3">Decisions of General Court Martial</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-124"><span class="HTitleText3">Similar Offences</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-125"><span class="HTitleText3">Pronouncement of Findings and Sentence</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-126"><span class="HTitleText3">Death or Incapacity</span></a>
</li></ul>
</li><li><span class='sectionRange'>196.11 - </span><a href="#h-127"><span class="HLabel2">DIVISION 6.1</span> - <span class="HTitleText2">Forensic DNA Analysis</span></a>
</li>
<li><span class='sectionRange'>196.26 - </span><a href="#h-128"><span class="HLabel2">DIVISION 6.2</span> - <span class="HTitleText2">Identification of Accused Persons and Offenders</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-129"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Mental Disorder</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-130"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-131"><span class="HTitleText3">Fitness to Stand Trial</span></a>
</li>
<li><span class='sectionRange'>202.13 - </span><a href="#h-132"><span class="HTitleText3">Mental Disorder When Offence Committed</span></a>
</li>
<li><span class='sectionRange'>202.17 - </span><a href="#h-133"><span class="HTitleText3">General Provisions Respecting Assessment Orders, Dispositions and Assessment Reports</span></a>
</li>
<li><span class='sectionRange'>202.24 - </span><a href="#h-134"><span class="HTitleText3">Protected Statements</span></a>
</li>
<li><span class='sectionRange'>202.25 - </span><a href="#h-135"><span class="HTitleText3">Provisions of Criminal Code Applicable</span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-136"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Provisions Applicable to Imprisonment and Detention</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="#h-137"><span class="HTitleText3">Computation of Term</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-138"><span class="HTitleText3">Service Prisons and Detention Barracks</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-139"><span class="HTitleText3">Suspension of Imprisonment or Detention</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-140"><span class="HTitleText3">Committal to Imprisonment or Detention</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-141"><span class="HTitleText3">Temporary Removal from Incarceration</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-142"><span class="HTitleText3">Rules Applicable to Service Convicts and Service Prisoners</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-143"><span class="HTitleText3">Validity of Documents</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-144"><span class="HTitleText3">Mental Disorder during Imprisonment or Detention</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-145"><span class="HTitleText3">Transfer of Offenders</span></a>
</li>
<li><span class='sectionRange'>226.1 - </span><a href="#h-146"><span class="HTitleText3">Parole Eligibility</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-147"><span class="HLabel2">DIVISION 8.1</span> - <span class="HTitleText2">Sex Offender Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>227 - </span><a href="#h-148"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>227.01 - </span><a href="#h-149"><span class="HTitleText3">Order to Comply with the <cite class="XRefExternalAct">Sex Offender Information Registration Act</cite></span></a>
</li>
<li><span class='sectionRange'>227.06 - </span><a href="#h-150"><span class="HTitleText3">Notice and Obligation to Comply with the <cite class="XRefExternalAct">Sex Offender Information Registration Act</cite> — Convictions Before September 12, 2008</span></a>
</li>
<li><span class='sectionRange'>227.15 - </span><a href="#h-151"><span class="HTitleText3">Suspension of Time Limits, Proceedings and Obligations</span></a>
</li>
<li><span class='sectionRange'>227.18 - </span><a href="#h-152"><span class="HTitleText3">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>227.2 - </span><a href="#h-153"><span class="HTitleText3">Authorizations, Designations and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>228 - </span><a href="#h-154"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Appeals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="#h-155"><span class="HTitleText3">General Provisions</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-156"><span class="HTitleText3">Right to Appeal</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-157"><span class="HTitleText3">Entry of Appeals</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-158"><span class="HTitleText3">Appeals from Dispositions</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-159"><span class="HTitleText3">Court Martial Appeal Court of Canada</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-160"><span class="HTitleText3">Disposition of Appeals by Court Martial Appeal Court of Canada</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-161"><span class="HTitleText3">Rules of Appeal Procedure</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-162"><span class="HTitleText3">Appeal to Supreme Court of Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>248.1 - </span><a href="#h-163"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">Release Pending Appeal</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-164"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2">Review</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>249 - </span><a href="#h-165"><span class="HTitleText3">Review Authorities</span></a>
</li>
<li><span class='sectionRange'>249.11 - </span><a href="#h-166"><span class="HTitleText3">Quashing of Findings</span></a>
</li>
<li><span class='sectionRange'>249.12 - </span><a href="#h-167"><span class="HTitleText3">Substitution of Findings</span></a>
</li>
<li><span class='sectionRange'>249.13 - </span><a href="#h-168"><span class="HTitleText3">Substitution of Punishments</span></a>
</li>
<li><span class='sectionRange'>249.14 - </span><a href="#h-169"><span class="HTitleText3">Mitigation, Commutation and Remission of Punishments</span></a>
</li>
<li><span class='sectionRange'>249.15 - </span><a href="#h-170"><span class="HTitleText3">Conditions Applicable to New Punishments</span></a>
</li>
<li><span class='sectionRange'>249.16 - </span><a href="#h-171"><span class="HTitleText3">Petition for New Trial</span></a>
</li></ul>
</li><li><span class='sectionRange'>249.17 - </span><a href="#h-172"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Miscellaneous Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>249.17 - </span><a href="#h-173"><span class="HTitleText3">Right to be Represented</span></a>
</li>
<li><span class='sectionRange'>249.18 - </span><a href="#h-174"><span class="HTitleText3">Defence Counsel Services</span></a>
</li>
<li><span class='sectionRange'>249.22 - </span><a href="#h-175"><span class="HTitleText3">Witnesses at Courts Martial and before Commissioners</span></a>
</li>
<li><span class='sectionRange'>249.23 - </span><a href="#h-176"><span class="HTitleText3">Warrant for Arrest on Non-Appearance of Accused</span></a>
</li>
<li><span class='sectionRange'>249.24 - </span><a href="#h-177"><span class="HTitleText3">Effect of New Punishment</span></a>
</li>
<li><span class='sectionRange'>249.25 - </span><a href="#h-178"><span class="HTitleText3">Restitution of Property</span></a>
</li>
<li><span class='sectionRange'>249.26 - </span><a href="#h-179"><span class="HTitleText3">Reference to Ranks</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>250 - </span><a href="#h-180"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Complaints About or by Military Police</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250 - </span><a href="#h-181"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>250.1 - </span><a href="#h-182"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Military Police Complaints Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.1 - </span><a href="#h-183"><span class="HTitleText3">Establishment and Organization</span></a>
</li>
<li><span class='sectionRange'>250.11 - </span><a href="#h-184"><span class="HTitleText3">Chairperson</span></a>
</li>
<li><span class='sectionRange'>250.12 - </span><a href="#h-185"><span class="HTitleText3">Head Office</span></a>
</li>
<li><span class='sectionRange'>250.13 - </span><a href="#h-186"><span class="HTitleText3">Staff</span></a>
</li>
<li><span class='sectionRange'>250.14 - </span><a href="#h-187"><span class="HTitleText3">Duty to Act Expeditiously</span></a>
</li>
<li><span class='sectionRange'>250.15 - </span><a href="#h-188"><span class="HTitleText3">Rules</span></a>
</li>
<li><span class='sectionRange'>250.16 - </span><a href="#h-189"><span class="HTitleText3">Immunity</span></a>
</li>
<li><span class='sectionRange'>250.17 - </span><a href="#h-190"><span class="HTitleText3">Annual Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.18 - </span><a href="#h-191"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Complaints</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.18 - </span><a href="#h-192"><span class="HLabel3">SUBDIVISION 1</span> - <span class="HTitleText3">Right to Complain</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.18 - </span><a href="#h-193"><span class="HTitleText4">Conduct Complaints</span></a>
</li>
<li><span class='sectionRange'>250.19 - </span><a href="#h-194"><span class="HTitleText4">Interference Complaints</span></a>
</li>
<li><span class='sectionRange'>250.2 - </span><a href="#h-195"><span class="HTitleText4">Time Limit</span></a>
</li>
<li><span class='sectionRange'>250.21 - </span><a href="#h-196"><span class="HTitleText4">To Whom Complaint May be Made</span></a>
</li>
<li><span class='sectionRange'>250.24 - </span><a href="#h-197"><span class="HTitleText4">Withdrawal of Complaint</span></a>
</li>
<li><span class='sectionRange'>250.25 - </span><a href="#h-198"><span class="HTitleText4">Record of Complaints</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.26 - </span><a href="#h-199"><span class="HTitleText3">Subdivision 2</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>250.26 - </span><a href="#h-200"><span class="HTitleText4">Disposal of Conduct Complaints</span></a>
</li>
<li><span class='sectionRange'>250.31 - </span><a href="#h-201"><span class="HTitleText4">Review by Complaints Commission</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.34 - </span><a href="#h-202"><span class="HLabel3">SUBDIVISION 3</span> - <span class="HTitleText3">Disposal of Interference Complaints</span></a>
</li></ul>
</li><li><span class='sectionRange'>250.38 - </span><a href="#h-203"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Investigations and Hearings by Complaints Commission</span></a>
</li>
<li><span class='sectionRange'>250.49 - </span><a href="#h-204"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Review and Final Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>251 - </span><a href="#h-205"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Miscellaneous Provisions Having General Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>251 - </span><a href="#h-206"><span class="HTitleText2">Oaths</span></a>
</li>
<li><span class='sectionRange'>251.2 - </span><a href="#h-207"><span class="HTitleText2">Witness Fees and Allowances</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-208"><span class="HTitleText2">Disposal by Civil Authorities of Deserters and Absentees without Leave</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-209"><span class="HTitleText2">Certificate of Civil Courts</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-210"><span class="HTitleText2">Duties respecting Incarceration</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-211"><span class="HTitleText2">Manoeuvres</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-212"><span class="HTitleText2">Exemption from Tolls</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-213"><span class="HTitleText2">Ships in Convoy</span></a>
</li>
<li><span class='sectionRange'>263 - </span><a href="#h-214"><span class="HTitleText2">Salvage</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="#h-215"><span class="HTitleText2">Limitation or Prescription Periods, Liability and Exemptions</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-216"><span class="HTitleText2">Compensation</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-217"><span class="HTitleText2">Dependants</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-218"><span class="HTitleText2">Jurisdiction of Civil Courts</span></a>
</li>
<li><span class='sectionRange'>273.1 - </span><a href="#h-219"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>273.2 - </span><a href="#h-220"><span class="HTitleText2">Searches</span></a>
</li>
<li><span class='sectionRange'>273.6 - </span><a href="#h-221"><span class="HTitleText2">Public Service</span></a>
</li>
<li><span class='sectionRange'>273.601 - </span><a href="#h-222"><span class="HTitleText2">Independent Review</span></a>
</li></ul>
</li><li><span class='sectionRange'>273.61 - </span><a href="#h-223"><span class="HLabel1">PART V.1</span> - <span class="HTitleText1">Communications Security Establishment</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-224"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Aid of the Civil Power</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-225"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Offences Triable by Civil Courts</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>286 - </span><a href="#h-226"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-227"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><a href="#h-379774"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
