<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Comprehensive Nuclear Test-Ban Treaty Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-90722"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-90725"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-90737"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-90740"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-90743"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-90746"><span class="HTitleText1">Delegation by Minister</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-90749"><span class="HTitleText1">Nuclear Explosions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-90765"><span class="HTitleText1">Chemical Explosions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-90781"><span class="HTitleText1">National Authority and Monitoring Activities</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-90815"><span class="HTitleText1">Request for Information</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-90829"><span class="HTitleText1">On-site Inspections</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-90850"><span class="HTitleText1">Warrant for Inspection and Search</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-90862"><span class="HTitleText1">Privileges and Immunities Concerning On-site Inspections</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-90893"><span class="HTitleText1">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-90903"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-90912"><span class="HTitleText1">Amendments to the Treaty</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-90915"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-90927"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-90933"><span class="HTitleText1">Conditional Amendment</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-90935"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-90939"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Comprehensive Nuclear Test-Ban Treaty</span></a>
</li>
<li><a href="#h-91355"><span class="scheduleLabel">ANNEX 1 TO THE TREATY</span> - <span class="scheduleTitleText"> - List of States Pursuant to Article II, Paragraph 28</span></a>
</li>
<li><a href="#h-91563"><span class="scheduleLabel">ANNEX 2 TO THE TREATY</span> - <span class="scheduleTitleText"> - List of States Pursuant to Article XIV</span></a>
</li>
<li><a href="#h-91920"><span class="scheduleLabel">ANNEX 1 TO THE PROTOCOL</span></a>
</li>
<li><a href="#h-91965"><span class="scheduleLabel">ANNEX 2 TO THE PROTOCOL</span> - <span class="scheduleTitleText"> - List of Characterization Parameters for International Data Centre Standard Event Screening</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
