<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Journée nationale de la sensibilisation à la drépanocytose</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-355149"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-355152"><span class="HTitleText1">Journée nationale de la sensibilisation à la drépanocytose</span></a>
</li></ul>
</li></ul>

</nav>

