<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Security Intelligence Service Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-76156"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-76161"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-76188"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Canadian Security Intelligence Service</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-76189"><span class="HTitleText2">Establishment of Service</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-76199"><span class="HTitleText2">Director</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-76220"><span class="HTitleText2">Management of Service</span></a>
</li>
<li><span class='sectionRange'>11.01 - </span><a href="#h-76283"><span class="HTitleText2">Duties and Functions of Service</span></a>
</li>
<li><span class='sectionRange'>20.2 - </span><a href="#h-1193870"><span class="HTitleText2">Report to Parliament</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-76429"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Judicial Control</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-76568"><span class="HLabel1">PART III</span> - <span class="HTitleText1">[Repealed, 2019, c. 13, s. 22]</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-76754"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">[Repealed, 2019, c. 13, s. 22]</span></a>
</li>
<li><a href="#h-76763"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

