<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Banque de l’infrastructure du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-143075"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-143078"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-143092"><span class="HTitleText1">Désignation et ministre de tutelle</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-143097"><span class="HTitleText1">Constitution et organisation de la Banque</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-143098"><span class="HTitleText2">Qualité de la Banque</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-143112"><span class="HTitleText2">Mission et fonctions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-143128"><span class="HTitleText2">Conseil et premier dirigeant</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-143186"><span class="HTitleText1">Gestion et contrôle financier</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-143194"><span class="HTitleText1">Certains pouvoirs de la Banque</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-143220"><span class="HTitleText1">Pouvoirs du ministre des Finances</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-143230"><span class="HTitleText1">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-143264"><span class="HTitleText1">Dispositions transitoires</span></a>
</li></ul>
</li></ul>

</nav>

