<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Cree-Naskapi (of Quebec) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Inconsistency with Federal or Provincial Law</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Application of Indian Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Band By-laws and Resolutions</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="#h-6"><span class="HTitleText1">Cree Regional Authority By-laws and Resolutions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">Incorporation by Reference of Provincial Laws</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Local Government</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Incorporation of Bands</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText2">Membership of Bands</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-12"><span class="HTitleText2">Objects and Powers of Bands</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-13"><span class="HTitleText2">Head Office of Band</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Band Council</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Council Meetings</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-16"><span class="HTitleText2">Committees of a Council</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText2">Band Bodies, Officers, Employees and Agents</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">By-laws Respecting Local Government</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-19"><span class="HTitleText2">Procedure for Making By-Laws and Resolutions</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-20"><span class="HTitleText2">Challenges to By-Laws or Resolutions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-21"><span class="HTitleText2">Transitional</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-22"><span class="HTitleText3">Cree Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-23"><span class="HTitleText3">Naskapi Transitional Provisions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>62.01 - </span><a href="#h-24"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Cree Regional Authority</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-25"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Band Elections</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-26"><span class="HTitleText2">Election By-laws</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-27"><span class="HTitleText2">Eligibility to be Elected and to Serve as Council Member</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-28"><span class="HTitleText2">Returning Officers</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-29"><span class="HTitleText2">Calling of Elections</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-30"><span class="HTitleText2">Contestation of election results</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-31"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Meetings and Referenda of the Band</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-32"><span class="HTitleText2">Ordinary Band Meetings</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-33"><span class="HTitleText2">Special Band Meetings and Referenda</span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="#h-34"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Financial Administration of Bands</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>93 - </span><a href="#h-35"><span class="HTitleText2">Audit</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-36"><span class="HTitleText2">Borrowing Powers of Band</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-37"><span class="HTitleText2">Contracts</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-38"><span class="HTitleText2">Appointment of Administrator</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-39"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Residence and Access Rights on Category IA and IA-N Land</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="#h-40"><span class="HTitleText2">Residence Rights</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-41"><span class="HTitleText2">Access Rights</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-42"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-43"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Rights of Bands, Quebec and Others in Relation to Category IA and IA-N Land</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="#h-44"><span class="HTitleText2">Soapstone Deposits</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-45"><span class="HTitleText2">Forest Resources</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-46"><span class="HTitleText2">Gravel</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-47"><span class="HTitleText2">Mineral, Subsurface and Mining Rights</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-48"><span class="HTitleText2">Pre-Existing Rights and Interests on Category IA and IA-N Land</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-49"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Expropriation of Category IA or IA-N Land by Quebec</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-50"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Dispositions of Rights and Interests in Category IA and IA-N Land and Buildings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-51"><span class="HTitleText2">Superficie</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-52"><span class="HTitleText2">Subsequent Transfers of Rights or Interests</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-53"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="#h-54"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Cessions by Bands</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-55"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Land Registry System</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-56"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Expropriation by Bands</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-57"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Cree-Naskapi Commission</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-58"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Successions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>181 - </span><a href="#h-59"><span class="HTitleText2">Disposition of Traditional Property on an Intestacy</span></a>
</li></ul>
</li><li><span class='sectionRange'>187 - </span><a href="#h-60"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Tax Exemptions</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-61"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">Seizure Exemptions</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-62"><span class="HLabel1">PART XVI</span> - <span class="HTitleText1">Policing</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-63"><span class="HLabel1">PART XVII</span> - <span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-64"><span class="HLabel1">PART XVIII</span> - <span class="HTitleText1">Administration of Justice</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-65"><span class="HLabel1">PART XIX</span> - <span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>204 to 217 - </span><a href="#h-66"><span class="HLabel1">PART XX</span> - <span class="HTitleText1">Consequential Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="#h-67"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
