<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la commercialisation du poisson d’eau douce</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Office de commercialisation du poisson d’eau douce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Constitution et mise en place</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText2">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText2">Fonctionnement et personnel</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText2">Dispositions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Réglementation du commerce interprovincial et de l’exportation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Commerce interprovincial et exportation</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Responsabilités et pouvoirs de l’Office</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2">Accords de participation</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-16"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-17"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Rapport annuel</span></a>
</li>
<li><a href="#h-225370"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
