<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’indemnisation des agents de l’État</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-245608"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-245613"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-245633"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-245641"><span class="HTitleText1">Indemnités</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-245700"><span class="HTitleText1">Recours contre les tiers responsables</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-245738"><span class="HTitleText1">Immunité de la Couronne</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-245747"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

