<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le parc de Kingsmere</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-330000"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><a href="page-2.html#h-330025"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Extrait du testament de M. King :</span></a>
</li></ul>
</li></ul>

</nav>

