<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada-Argentina Income Tax Convention Act, 1994</a><ul class="TocIndent"><li><span class='sectionRange'>19 - </span><a href="page-1.html#h-41582"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Canada-Argentina Income Tax Convention</span></a>
</li>
<li><a href="page-2.html#h-41599"><span class="scheduleLabel">SCHEDULE V</span> <span class="scheduleTitleText"> - Convention Between Canada and the Argentine Republic for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-3.html#h-41879"><span class="scheduleLabel">SCHEDULE VI</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>

