<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi instituant des jours de fête légale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-250593"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-250598"><span class="HTitleText1">Fête du Canada</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-250606"><span class="HTitleText1">Jour du Souvenir</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-250611"><span class="HTitleText1">Fête de Victoria</span></a>
</li></ul>
</li></ul>

</nav>

