<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Charities Registration (Security Information) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-79939"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-79942"><span class="HTitleText1">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-79950"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-79960"><span class="HTitleText1">Certificate Based on Intelligence</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-79971"><span class="HTitleText1">Judicial Consideration of Certificate</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-80022"><span class="HTitleText1">Review of Certificate</span></a>
</li></ul>
</li></ul>

</nav>

