<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada-Costa Rica Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-49444"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-49447"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-49462"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-49474"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-49477"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-49487"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of Agreement Generally</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-49488"><span class="HTitleText2">Approval of Agreement</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-49491"><span class="HTitleText2">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-49494"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-49501"><span class="HTitleText2">Panels, Committees, Subcommittees and Working Groups</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-49511"><span class="HTitleText2">Orders and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 to 59 - </span><a href="#h-49532"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Related and Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-49534"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-49541"><span class="scheduleLabel">SCHEDULES 1 TO 3</span></a>
</li></ul>
</li></ul>

</nav>

