<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada-Belgium Income Tax Convention Act, 1976</a><ul class="TocIndent"><li><span class='sectionRange'>4 - </span><a href="#h-42512"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Canada-Belgium Income Tax Convention</span></a>
</li>
<li><a href="#h-42525"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Kingdom of Belgium for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li></ul>
</li></ul>

</nav>

