<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le Nunavut</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-360832"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-360835"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-360843"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Constitution et gouvernement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-360844"><span class="HTitleText2">Constitution du Nunavut</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-360851"><span class="HTitleText2">Capitale</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-360854"><span class="HTitleText2">Pouvoir exécutif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-360855"><span class="HTitleText3">Commissaire du Nunavut</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-360876"><span class="HTitleText3">Conseil exécutif du Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-1.html#h-360879"><span class="HTitleText2">Pouvoir législatif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-1.html#h-360880"><span class="HTitleText3">Législature du Nunavut</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-360883"><span class="HTitleText3">Assemblée législative du Nunavut</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-360910"><span class="HTitleText3">Compétence législative</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-1.html#h-360977"><span class="HTitleText3">Droit applicable au Nunavut</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="page-2.html#h-361000"><span class="HTitleText2">Pouvoir judiciaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-2.html#h-361001"><span class="HTitleText3">Organisation judiciaire</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-361013"><span class="HTitleText3">Cour de justice du Nunavut</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-2.html#h-361045"><span class="HTitleText3">Cour d’appel du Nunavut</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-361050"><span class="HTitleText3">Cessation d’effet</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-2.html#h-361053"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Dispositions diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="page-2.html#h-361054"><span class="HTitleText2">Langues officielles</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-2.html#h-361059"><span class="HTitleText2">Trésor du Nunavut</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-2.html#h-361069"><span class="HTitleText2">Comptes du Nunavut</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-2.html#h-361104"><span class="HTitleText2">Biens-fonds</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-3.html#h-361136"><span class="HTitleText2">Biens culturels</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="page-3.html#h-361147"><span class="HLabel1">*PARTIE III</span> - <span class="HTitleText1">*[Note : La partie III a cessé d’avoir effet le 1er juillet 1999.]</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="page-3.html#h-361148"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="page-3.html#h-361149"><span class="HTitleText2">Dépenses</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-3.html#h-361152"><span class="HTitleText2">Commissaire provisoire du Nunavut</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-3.html#h-361239"><span class="HTitleText2">Conseil des Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>76.01 - </span><a href="page-3.html#h-361245"><span class="HTitleText2">Premières élections</span></a>
</li>
<li><span class='sectionRange'>76.06 - </span><a href="page-4.html#h-361278"><span class="HTitleText2">Charges et organismes publics</span></a>
</li>
<li><span class='sectionRange'>76.09 - </span><a href="page-4.html#h-361312"><span class="HTitleText2">Affaires en cours</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 à 77.3 - </span><a href="page-4.html#h-361360"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Modifications corrélatives et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 à 77.3 - </span><a href="page-4.html#h-361361"><span class="HTitleText2">Loi sur les Territoires du Nord-Ouest</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-4.html#h-361363"><span class="HTitleText2">Autres modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-4.html#h-361365"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-5.html#h-361372"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Limite ouest du territoire du Nunavut</span></a>
</li>
<li><a href="page-6.html#h-361393"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Collectivités</span></a>
</li>
<li><a href="page-7.html#h-361436"><span class="scheduleLabel">ANNEXE III</span> </a>
</li></ul>
</li></ul>

</nav>

