<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Déclaration canadienne des droits</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-60172"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Déclaration des droits</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-60202"><span class="HTitleText1">Partie II</span></a>
</li></ul>
</li></ul>

</nav>

