<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée nationale des Gardiens de la paix (Casques bleus)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-354561"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-354564"><span class="HTitleText1">Journée nationale des gardiens de la paix (casques bleus)</span></a>
</li></ul>
</li></ul>

</nav>

