<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tarif des douanes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Définitions et dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Modification de l’annexe</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Droits de douane</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-7"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Origine des marchandises</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText3">Règles d’origine</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText3">Expédition directe et transbordement</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText3">Marquage des marchandises</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-11"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Imposition des droits de douane</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-13"><span class="HTitleText3">Classement spécial</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-14"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Traitements tarifaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-16"><span class="HTitleText3">Tarif général</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-17"><span class="HTitleText3">Tarif de la nation la plus favorisée</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-18"><span class="HTitleText3">Tarif de préférence général</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-19"><span class="HTitleText3">Tarif des pays les moins développés</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-20"><span class="HTitleText3">Tarif des pays antillais du Commonwealth</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-21"><span class="HTitleText3">Tarifs de l’Australie et de la Nouvelle-Zélande</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-22"><span class="HTitleText3">Tarif des États-Unis, tarif du Mexique et tarif Mexique — États-Unis</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-23"><span class="HTitleText3">Tarif du Chili</span></a>
</li>
<li><span class='sectionRange'>49.01 - </span><a href="#h-24"><span class="HTitleText3">Tarif de la Colombie</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="#h-25"><span class="HTitleText3">Tarif du Costa Rica</span></a>
</li>
<li><span class='sectionRange'>49.41 - </span><a href="#h-26"><span class="HTitleText3">Tarif du Panama</span></a>
</li>
<li><span class='sectionRange'>49.5 - </span><a href="#h-27"><span class="HTitleText3">Tarif du Pérou</span></a>
</li>
<li><span class='sectionRange'>49.6 - </span><a href="#h-28"><span class="HTitleText3">Tarif du Honduras</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-29"><span class="HTitleText3">Tarif de l’Accord Canada — Israël</span></a>
</li>
<li><span class='sectionRange'>52.1 - </span><a href="#h-30"><span class="HTitleText3">Tarif de l’Islande</span></a>
</li>
<li><span class='sectionRange'>52.2 - </span><a href="#h-31"><span class="HTitleText3">Tarif de la Norvège</span></a>
</li>
<li><span class='sectionRange'>52.3 - </span><a href="#h-32"><span class="HTitleText3">Tarif de Suisse-Liechtenstein</span></a>
</li>
<li><span class='sectionRange'>52.4 - </span><a href="#h-33"><span class="HTitleText3">Tarif de la Jordanie</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-34"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Mesures spéciales, mesures d’urgence et mesures de sauvegarde</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-35"><span class="HTitleText3">Mesures spéciales</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-36"><span class="HTitleText3">Mesures d’urgence globales</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-37"><span class="HTitleText3">Mesures de sauvegarde visant les produits agricoles</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-38"><span class="HTitleText3">Mesures d’urgence bilatérales visant les marchandises des États-Unis</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-39"><span class="HTitleText3">Mesures d’urgence bilatérales visant les marchandises du Mexique et TMÉU</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-40"><span class="HTitleText3">Mesures d’urgence bilatérales : Chili</span></a>
</li>
<li><span class='sectionRange'>71.01 - </span><a href="#h-41"><span class="HTitleText3">Mesures d’urgence bilatérales : Colombie</span></a>
</li>
<li><span class='sectionRange'>71.1 - </span><a href="#h-42"><span class="HTitleText3">Mesures d’urgence bilatérales : Costa Rica</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="#h-43"><span class="HTitleText3">Mesures d’urgence bilatérales : Islande</span></a>
</li>
<li><span class='sectionRange'>71.3 - </span><a href="#h-44"><span class="HTitleText3">Mesures d’urgence bilatérales : Norvège</span></a>
</li>
<li><span class='sectionRange'>71.4 - </span><a href="#h-45"><span class="HTitleText3">Mesures d’urgence bilatérales : Suisse-Liechtenstein</span></a>
</li>
<li><span class='sectionRange'>71.41 - </span><a href="#h-46"><span class="HTitleText3">Mesures d’urgence bilatérales : Panama</span></a>
</li>
<li><span class='sectionRange'>71.5 - </span><a href="#h-47"><span class="HTitleText3">Mesures d’urgence bilatérales : Pérou</span></a>
</li>
<li><span class='sectionRange'>71.6 - </span><a href="#h-48"><span class="HTitleText3">Mesures d’urgence bilatérales : Jordanie</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-49"><span class="HTitleText3">Mesures d’urgence bilatérales : Honduras</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-50"><span class="HTitleText3">Mesures d’urgence bilatérales visant les produits textiles et vêtements importés du Honduras</span></a>
</li>
<li><span class='sectionRange'>77.1 - </span><a href="#h-51"><span class="HTitleText3">Mesures de sauvegarde visant la Chine</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-52"><span class="HTitleText3">Surtaxes</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-53"><span class="HTitleText3">Marchandises en transit</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-54"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Exonération de droits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="#h-55"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-56"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Réduction des taux</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-57"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Importation sans le paiement intégral des droits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="#h-58"><span class="HTitleText3">Réduction de la valeur en douane</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-59"><span class="HTitleText3">Groupes ethnoculturels</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-60"><span class="HTitleText3">Report des droits</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-61"><span class="HTitleText3">Marchandises canadiennes à l’étranger</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-62"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-63"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Marchandises surannées ou excédentaires</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-64"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Autres formes d’exonération</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-65"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>129 - </span><a href="#h-66"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Règlements et arrêtés</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-67"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Interdiction d’importer</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-68"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>147 à 191 - </span><a href="#h-69"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>192 à 212 - </span><a href="#h-70"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-71"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Abrogation et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>213 - </span><a href="#h-72"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-73"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-142544"><span class="scheduleLabel"><span class="wb-invisible">Note de bas de page </span><sup>*</sup>ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
