<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon Environmental and Socio-economic Assessment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-472875"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-472878"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-472985"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-473008"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Yukon Environmental and Socio-economic Assessment Board and Designated Offices</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-473009"><span class="HTitleText2">Yukon Environmental and Socio-economic Assessment Board</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-473087"><span class="HTitleText2">Assessment Districts and Designated Offices</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-473119"><span class="HTitleText2">Budgets and Reporting</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-473140"><span class="HTitleText2">Rules and By-Laws</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-473227"><span class="HTitleText2">General Requirement</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-473230"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Assessment Process and Decision Documents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-473231"><span class="HTitleText2">Assessments — General</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="#h-473291"><span class="HTitleText2">Time Limits</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-473296"><span class="HTitleText2">Proposed Activities Subject to Assessment</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-473336"><span class="HTitleText2">Proposals for Projects</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-473363"><span class="HTitleText2">Evaluation of Projects by Designated Offices</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-473393"><span class="HTitleText2">Screening of Projects by Executive Committee</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-473425"><span class="HTitleText2">Request for Review</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-473442"><span class="HTitleText2">Powers of Minister of Environment</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-473464"><span class="HTitleText2">Panels of the Board</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-473512"><span class="HTitleText2">Agreements for Joint Panels</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-473543"><span class="HTitleText2">Reviews of Projects by Panels</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-473586"><span class="HTitleText2">Consideration of Recommendations and Issuance of Decision Documents</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-473649"><span class="HTitleText2">Implementation of Decision Documents</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-473704"><span class="HTitleText2">Projects on Yukon North Slope</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-473724"><span class="HTitleText2">Collaboration and External Activities</span></a>
</li>
<li><span class='sectionRange'>93.1 - </span><a href="#h-473739"><span class="HTitleText2">Cost Recovery</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-473752"><span class="HTitleText2">Existing Projects</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-473835"><span class="HTitleText2">Plans</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-473912"><span class="HTitleText2">Audits and Effects Monitoring</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-473927"><span class="HTitleText2">Studies and Research</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-473948"><span class="HTitleText2">Violation of Decision Document</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-473956"><span class="HTitleText2">Court Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-473965"><span class="HTitleText2">Maintenance of Records and Public Access</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-473996"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-474019"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Transitional Provisions, Consequential and Coordinating Amendments and Commencement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-474020"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-474038"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-474039"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-474042"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-474044"><span class="HTitleText3">Yukon First Nations Self-Government Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-474046"><span class="HTitleText3">Yukon Surface Rights Board Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-474048"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-474051"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><a href="#h-474055"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

