<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère des Relations Couronne-Autochtones et des Affaires du Nord</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1155695"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1155698"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1155706"><span class="HTitleText1">Ministère des Relations Couronne-Autochtones et des Affaires du Nord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-1155707"><span class="HTitleText2">Mise en place</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1155717"><span class="HTitleText2">Attributions ministérielles</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-1155731"><span class="HTitleText1">Ministre des Affaires du Nord</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-1155766"><span class="HTitleText1">Dispositions communes</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
