<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Gender Budgeting Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-69671"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-69674"><span class="HTitleText1">Gender Budgeting Policy</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-69681"><span class="HTitleText1">Implementation of Policy</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
