<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi sur le règlement des revendications particulières <span class='Repealed'>[Abrogée, 2008, ch. 22, art. 52]</span></a></li></ul>
</nav>
</div></section>
