<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Energy Efficiency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-219031"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-219034"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-219053"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-219056"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Energy-using Products</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-219057"><span class="HTitleText2">Trade in Energy-Using Products</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-219078"><span class="HTitleText2">Test Products</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-219094"><span class="HTitleText2">Documents and Records</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-219103"><span class="HTitleText2">Inspection and Seizure</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-219145"><span class="HTitleText2">Detention</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-219156"><span class="HTitleText2">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-219169"><span class="HTitleText2">Illegal Import</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-219177"><span class="HTitleText2">Third Parties</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-219180"><span class="HTitleText2">Warranty</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-219183"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-219224"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Promotion of Energy Efficiency and Alternative Energy Sources</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-219225"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-219233"><span class="HTitleText2">Statistics</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-219262"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-219263"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-219270"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-219319"><span class="HTitleText2">Report to Parliament</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-219331"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

