<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’autonomie gouvernementale des premières nations du Yukon</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-462977"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-462980"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-463001"><span class="HTitleText1">Portée de la présente loi</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-463016"><span class="HTitleText1">Constitution de la première nation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-463037"><span class="HTitleText1">Textes législatifs de la première nation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-463087"><span class="HTitleText1">Administration de la justice</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-463103"><span class="HTitleText1">Lois d’application générale</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-463145"><span class="HTitleText1">Réserves</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-463181"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-463201"><span class="HTitleText1">Régime transitoire</span></a>
</li>
<li><span class='sectionRange'>33 à 39 - </span><a href="#h-463215"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-463217"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-463221"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-463231"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Premières nations visées par un accord en vigueur</span></a>
</li>
<li><a href="#h-463246"><span class="scheduleLabel">ANNEXE III</span> <span class="scheduleTitleText"> - Pouvoirs législatifs</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
