<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Weather Modification Information Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-467627"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-467632"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-467639"><span class="HTitleText1">Information</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-467652"><span class="HTitleText1">Records and Reports</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-467669"><span class="HTitleText1">Disclosure</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-467674"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-467679"><span class="HTitleText1">Offence and Punishment</span></a>
</li></ul>
</li></ul>

</nav>

