<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Telesat Canada Reorganization and Divestiture Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-461266"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-461269"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-461287"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-461290"><span class="HTitleText1">Transfer of Shares to Minister</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-461302"><span class="HTitleText1">Disposal of Shares by Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-461312"><span class="HTitleText1">Continuance</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-461333"><span class="HTitleText1">Corporate Affairs and Status</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-461347"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-461355"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-461389"><span class="HTitleText1">Amendment</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-461391"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

