<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’emballage et l’étiquetage des produits de consommation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-93666"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-93671"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-93689"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-93697"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-93740"><span class="HTitleText1">Étiquetage</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-93750"><span class="HTitleText1">Normalisation des contenants</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-93758"><span class="HTitleText1">Recherches</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-93766"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-93846"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-93868"><span class="HTitleText1">Publication des projets de règlement</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-93873"><span class="HTitleText1">Infractions et peines</span></a>
</li></ul>
</li></ul>

</nav>

