<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Marine Liability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Personal Injuries and Fatalities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Liability to Dependants</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Apportionment of Liability</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText2">Limitation of Time</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Limitation of Liability for Maritime Claims</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-12"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-13"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Liability of Owners of Docks, Canals and Ports</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-15"><span class="HTitleText2">Amendment of Maximum Liability</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>34.1 - </span><a href="#h-17"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-18"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Liability for Carriage of Passengers by Water</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-19"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-20"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-21"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-22"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Liability for Carriage of Goods by Water</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-23"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-24"><span class="HTitleText2">Hague-Visby Rules</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-25"><span class="HTitleText2">Hamburg Rules</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-26"><span class="HTitleText2">Institution of Proceedings in Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-27"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Liability and Compensation for Pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-28"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">International Conventions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-29"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-30"><span class="HTitleText3">Civil Liability Convention</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-31"><span class="HTitleText3">Fund Convention</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-32"><span class="HTitleText3">Supplementary Fund Protocol</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-33"><span class="HTitleText3">Bunkers Convention</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-34"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Liability Not Covered by Division 1</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-35"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-36"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-37"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="#h-38"><span class="HTitleText3">Admiralty Court</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-39"><span class="HTitleText3">Registration of Foreign Judgments</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-40"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-41"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Ship-source Oil Pollution Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-42"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-43"><span class="HTitleText2">Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-44"><span class="HTitleText2">Administrator and Deputy Administrator</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-45"><span class="HTitleText2">Liability of Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-46"><span class="HTitleText2">Claims for Loss of Income</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-47"><span class="HTitleText2">Proceedings Against the Owner of a Ship</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-48"><span class="HTitleText2">Limit of Liability of Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-49"><span class="HTitleText2">Levies To Be Paid to the Ship-source Oil Pollution Fund, the International Fund and the Supplementary Fund</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-50"><span class="HTitleText2">Governance of the Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-51"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-52"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-53"><span class="HTitleText2">Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-54"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-55"><span class="HTitleText2">Sale of Ships</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-56"><span class="HTitleText2">Maritime Lien</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-57"><span class="HTitleText2">Limitation Period</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-58"><span class="HTitleText2">Inconsistency</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-59"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><a href="#h-60"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-351466"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-351621"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Hague-Visby Rules</span></a>
</li>
<li><a href="#h-351730"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - Hamburg Rules</span></a>
</li>
<li><a href="#h-352009"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - Text of Articles I to XI, XII bis and 15 of the International Convention on Civil Liability for Oil Pollution Damage, 1992, as Amended by the Resolution of 2000</span></a>
</li>
<li><a href="#h-352165"><span class="scheduleLabel">SCHEDULE 6</span> <span class="scheduleTitleText"> - Text of Articles 1 to 4, 6 to 10, 12 to 15, 36 ter, 29, 33 and 37 of the International Convention on the Establishment of an International Fund for Compensation for Oil Pollution Damage, 1992, as Amended by the Resolution of 2000</span></a>
</li>
<li><a href="#h-352316"><span class="scheduleLabel">SCHEDULE 7</span> <span class="scheduleTitleText"> - Text of Articles 1 to 15, 18, 20, 24, 25 and 29 of the Protocol of 2003 to the International Convention on the Establishment of an International Fund for Compensation for Oil Pollution Damage, 1992</span></a>
</li>
<li><a href="#h-352457"><span class="scheduleLabel">SCHEDULE 8</span> <span class="scheduleTitleText"> - Text of Articles 1 to 10 of the International Convention on Civil Liability for Bunker Oil Pollution Damage, 2001</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
