<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les musées</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-345326"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-345329"><span class="HTitleText1">Définitions et déclaration</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-345342"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Constitution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-345343"><span class="HTitleText2">Constitution du Musée des beaux-arts du Canada</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-345349"><span class="HTitleText2">Mission, capacité et pouvoirs du Musée des beaux-arts du Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-345373"><span class="HTitleText2">Constitution du Musée canadien de l’histoire</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-345381"><span class="HTitleText2">Mission, capacité et pouvoirs du Musée canadien de l’histoire</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-345413"><span class="HTitleText2">Constitution du Musée canadien de la nature</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-345419"><span class="HTitleText2">Mission, capacité et pouvoirs du Musée canadien de la nature</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-345450"><span class="HTitleText2">Constitution du Musée national des sciences et de la technologie</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-345456"><span class="HTitleText2">Mission, capacité et pouvoirs du Musée national des sciences et de la technologie</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-345481"><span class="HTitleText2">Constitution du Musée canadien des droits de la personne</span></a>
</li>
<li><span class='sectionRange'>15.2 - </span><a href="#h-345489"><span class="HTitleText2">Mission, capacité et pouvoirs du Musée canadien des droits de la personne</span></a>
</li>
<li><span class='sectionRange'>15.4 - </span><a href="#h-345517"><span class="HTitleText2">Constitution du Musée canadien de l’immigration du Quai 21</span></a>
</li>
<li><span class='sectionRange'>15.5 - </span><a href="#h-345525"><span class="HTitleText2">Mission, capacité et pouvoirs du Musée canadien de l’immigration du Quai 21</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-345553"><span class="HTitleText2">Capacité au Canada et à l’étranger</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-345559"><span class="HTitleText2">Validité des actes</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-345562"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Organisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-345606"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-345643"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-345675"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Modifications corrélatives, abrogation, dispositions transitoires et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-345676"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-345678"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-345692"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-345696"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
