<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tax Conventions Implementation Act, 2013</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-447775"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-447778"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada–Namibia Tax Convention</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-447780"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Canada–Serbia Tax Convention</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-447782"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Canada–Poland Tax Convention</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-447784"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Canada–Hong Kong Tax Agreement</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-447786"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Canada–Luxembourg Tax Convention</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-447787"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Conventions Implementation Act, 1999</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-447791"><span class="HTitleText2">Canada–Luxembourg 2012 Protocol and Agreement</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-447798"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Canada–Switzerland Tax Convention</span></a>
</li>
<li><a href="#h-447808"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-447810"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-447812"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-447814"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="#h-447816"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li>
<li><a href="#h-447819"><span class="scheduleLabel">SCHEDULE 6</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
