<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2006 sur les droits d’exportation de produits de bois d’oeuvre</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-421409"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-421412"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-421466"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-421469"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-421475"><span class="HTitleText1">Droits d’exportation de produits de bois d’oeuvre</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-421476"><span class="HTitleText2">Droits d’exportation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-421595"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-421612"><span class="HTitleText1">Droits sur les remboursements de dépôts douaniers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-421643"><span class="HTitleText1">Dispositions générales concernant les droits et les autres sommes à payer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-421644"><span class="HTitleText2">Personnel assurant l’exécution et le contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-421654"><span class="HTitleText2">Inscription et agrément</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-421688"><span class="HTitleText2">Déclarations et paiement des droits</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-421735"><span class="HTitleText2">Intérêts</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-421754"><span class="HTitleText2">Frais administratifs prévus par la <cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-421757"><span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-421814"><span class="HTitleText2">Faillites et réorganisations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-421866"><span class="HTitleText2">Sociétés de personnes</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-421883"><span class="HTitleText2">Registres et renseignements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-421920"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-421965"><span class="HTitleText2">Opposition aux cotisations</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-422012"><span class="HTitleText2">Appel</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-422107"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-422108"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-422121"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-422179"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-422248"><span class="HTitleText2">Enquête</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-422271"><span class="HTitleText2">Renseignements confidentiels</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-422339"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-422551"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-422594"><span class="HTitleText1">Paiements aux provinces</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-422626"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-422642"><span class="HTitleText1">Cessation d’effet</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-422645"><span class="HTitleText1">Affectation de versements</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-422648"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-422673"><span class="HTitleText1">Modifications à la Loi sur les licences d’exportation et d’importation</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-422683"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="#h-422684"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-422687"><span class="HTitleText2">Loi sur l’Agence du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-422689"><span class="HTitleText2">Loi sur la Cour canadienne de l’impôt</span></a>
</li></ul>
</li><li><span class='sectionRange'>125 - </span><a href="#h-422694"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-422696"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-422705"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Personnes exemptées</span></a>
</li></ul>
</li></ul>

</nav>

