<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Evidence Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-137446"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-137451"><span class="HTitleText1">Part I</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-137452"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-137457"><span class="HTitleText2">Witnesses</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-137531"><span class="HTitleText2">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-137586"><span class="HTitleText2">Judicial Notice</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-137595"><span class="HTitleText2">Documentary Evidence</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-137838"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-137843"><span class="HTitleText2">Specified Public Interest</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-137899"><span class="HTitleText2">International Relations and National Defence and National Security</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-138147"><span class="HTitleText2">Confidences of the Queen’s Privy Council for Canada</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-138169"><span class="HTitleText2">Journalistic Sources</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-138209"><span class="HTitleText2">Provincial Laws of Evidence</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-138214"><span class="HTitleText2">Statutory Declarations</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-138221"><span class="HTitleText2">Insurance Proofs</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-138226"><span class="HTitleText1">Part II</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-138227"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-138232"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-138245"><span class="HTitleText2">Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-138283"><span class="HTitleText1">Part III</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-138284"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-138295"><span class="HTitleText2">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-138300"><span class="HTitleText2">Documentary Evidence</span></a>
</li></ul>
</li><li><a href="#h-138309"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Designated Entities</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
