<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nuclear Liability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Liability for Nuclear Incidents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Duty of Operator</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Absolute Liability of Operator</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Exceptions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Limitations</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Insurance and Financial Responsibility</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Special Measures for Compensation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Proclamations</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-12"><span class="HTitleText2">Establishment of Commission</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-13"><span class="HTitleText2">Compensation Orders</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Interim Financial Assistance</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-15"><span class="HTitleText2">Limit of Payments</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
