<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les espèces sauvages du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-458224"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-458229"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-458249"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-458254"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-458291"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-458313"><span class="HTitleText1">Espèces menacées d’extinction</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-458318"><span class="HTitleText1">Acquisition de terres</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-458330"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-458548"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-458788"><span class="HTitleText1">Contraventions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
