<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la manutention des grains en Colombie-Britannique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-32680"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-32683"><span class="HTitleText1">Terminologie</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-32686"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Manutention des grains à Vancouver</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-32687"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-32696"><span class="HTitleText2">Manutention des grains</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-32721"><span class="HTitleText2">Médiateur-arbitre</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-32738"><span class="HTitleText2">Modification de la convention collective</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-32741"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-32753"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Manutention des grains à Prince Rupert</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-32754"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-32762"><span class="HTitleText2">Manutention des grains</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-32787"><span class="HTitleText2">Médiateur-arbitre</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-32804"><span class="HTitleText2">Modification de la convention collective</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-32807"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-32819"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-32826"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

