<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les systèmes de télédétection spatiale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-416858"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-416861"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-416883"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-416886"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-416897"><span class="HTitleText1">Exploitation des systèmes de télédétection spatiale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-416898"><span class="HTitleText2">Obligation d’être titulaire d’une licence</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-416907"><span class="HTitleText2">Délivrance des licences et questions connexes</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-416965"><span class="HTitleText2">Modification, suspension et révocation des licences</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-416993"><span class="HTitleText2">Interruption des services</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-417005"><span class="HTitleText2">Accès prioritaire</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-417026"><span class="HTitleText2">Transfert de satellites de télédétection</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-417034"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-417064"><span class="HTitleText1">Demande de renseignements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-417074"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-417108"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-417126"><span class="HTitleText1">Immunité</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-417132"><span class="HTitleText1">Violations et pénalités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-417133"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-417136"><span class="HTitleText2">Agents verbalisateurs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-417144"><span class="HTitleText2">Procès-verbaux</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-417162"><span class="HTitleText2">Responsabilité et pénalité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-417163"><span class="HTitleText3">Paiement de la pénalité</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-417166"><span class="HTitleText3">Présentation des observations</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-417181"><span class="HTitleText3">Aveu de responsabilité</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-417184"><span class="HTitleText2">Appel au ministre</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-417190"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-417206"><span class="HTitleText2">Recouvrement des pénalités et des sommes</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-417219"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="#h-417251"><span class="HTitleText1">Examen et rapport</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-417257"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-417259"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

