<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la poursuite des activités de la Banque de la Colombie-Britannique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-23061"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-23064"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-23076"><span class="HTitleText1">Incompatibilité</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-23079"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-23082"><span class="HTitleText1">Vente d’éléments d’actif</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-23138"><span class="HTitleText1">Dissolution</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-23146"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
