<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
First Nations Elections Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-224423"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-224426"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-224445"><span class="HTitleText1">Adding to the Schedule</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-224460"><span class="HTitleText1">Election Dates</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-224469"><span class="HTitleText1">Council</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-224477"><span class="HTitleText1">Candidates</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-224507"><span class="HTitleText1">Ballots</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-224515"><span class="HTitleText1">Voting</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-224539"><span class="HTitleText1">Polling Stations</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-224553"><span class="HTitleText1">Awarding of Positions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-224558"><span class="HTitleText1">By-Elections</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-224561"><span class="HTitleText1">Obstruction of Elections</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-224566"><span class="HTitleText1">Term of Office</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-224579"><span class="HTitleText1">Contested Elections</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-224597"><span class="HTitleText1">Petition for Removal from Office</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-224602"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-224621"><span class="HTitleText1">Penalties</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-224631"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-224648"><span class="HTitleText1">Removal from Schedule</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-224664"><span class="HTitleText1">Consequential Amendment to the Indian Act</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-224666"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Participating First Nations</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
