<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada-Nova Scotia Offshore Petroleum Resources Accord Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">Prescribing Limits of Offshore Area</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-4"><span class="HTitleText1">Condition Precedent for Certain Regulations</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Amendment of Accord</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Joint Management</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText2">Establishment of Board</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HTitleText2">Functions of Board</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-10"><span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-11"><span class="HTitleText2">Decisions in Relation to Offshore Management</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-12"><span class="HTitleText2">Regional Security of Supply</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-13"><span class="HTitleText2">Nova Scotia Trunkline</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-14"><span class="HTitleText2">Ministerial Directives</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-15"><span class="HTitleText2">Public Notice</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-16"><span class="HTitleText2">Strategic Plan for Interests, Exploration and Development</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-17"><span class="HTitleText2">Public Review</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-18"><span class="HTitleText2">Canada-Nova Scotia Benefits Plan</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-19"><span class="HTitleText2">Coordination of Government Departments and Agencies</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-20"><span class="HTitleText2">Constitution of Panel</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-21"><span class="HTitleText2">Settlement Procedure for Disputes</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-22"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Petroleum Resources</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-23"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-24"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-25"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>52 - </span><a href="#h-26"><span class="HTitleText3">Manner of Giving Notices</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-27"><span class="HTitleText3"> Her Majesty</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-28"><span class="HTitleText3">Designations and Appointments</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-29"><span class="HTitleText3">General Rules Respecting Interests</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-30"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">General Rules Relating to Issuance of Interests</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-31"><span class="HTitleText3">Authority to Issue Interests</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-32"><span class="HTitleText3">Issuance of Interests in Relation to Crown Reserve Areas</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-33"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Exploration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-34"><span class="HTitleText3">Exploration Licences</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-35"><span class="HTitleText3">Significant Discoveries</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-36"><span class="HTitleText3">Significant Discovery Licences</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-37"><span class="HTitleText3">Drilling Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="#h-38"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>81 - </span><a href="#h-39"><span class="HTitleText3">Commercial Discoveries</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-40"><span class="HTitleText3">Development Orders</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-41"><span class="HTitleText3">Issuance of Production Licences</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-42"><span class="HTitleText3">Subsurface Storage Licences</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-43"><span class="HTitleText3">Qualification for Production Licence</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-44"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">[Repealed, 1993, c. 47, s. 15]</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-45"><span class="HLabel2">DIVISION VI</span> - <span class="HTitleText2">Royalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-46"><span class="HTitleText3">Reservation of Royalties</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-47"><span class="HTitleText3">Liability and Collection of Royalties</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-48"><span class="HLabel2">DIVISION VII</span> - <span class="HTitleText2">Environmental Studies Research Fund</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-49"><span class="HLabel2">DIVISION VIII</span> - <span class="HTitleText2">Transfers, Assignments and Registration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>105 - </span><a href="#h-50"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-51"><span class="HTitleText3">Transfer and Assignment</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-52"><span class="HTitleText3">Registration</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="#h-53"><span class="HLabel2">DIVISION IX</span> - <span class="HTitleText2">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-54"><span class="HTitleText3">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-55"><span class="HTitleText3">Arbitration</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-56"><span class="HTitleText3">Cancellation of Rights</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-57"><span class="HTitleText3">Hearings and Judicial Review</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-58"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-59"><span class="HLabel2">DIVISION X</span> - <span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>138 - </span><a href="#h-60"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Petroleum Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-61"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>138.1 - </span><a href="#h-62"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-63"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>139.1 - </span><a href="#h-64"><span class="HTitleText2">Oil and Gas Administration Advisory Council</span></a>
</li>
<li><span class='sectionRange'>139.2 - </span><a href="#h-65"><span class="HTitleText2">Offshore Oil and Gas Training Standards Advisory Board</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-66"><span class="HTitleText2">Prohibition</span></a>
</li>
<li><span class='sectionRange'>141.1 - </span><a href="#h-67"><span class="HTitleText2">Delegation</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-68"><span class="HTitleText2">Licences and Authorizations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>142 - </span><a href="#h-69"><span class="HTitleText3">Operating Licences and Authorization for Work</span></a>
</li>
<li><span class='sectionRange'>142.2 - </span><a href="#h-70"><span class="HTitleText3">Safety of Works and Activities</span></a>
</li>
<li><span class='sectionRange'>142.3 - </span><a href="#h-71"><span class="HTitleText3">Financial Responsibility</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-72"><span class="HTitleText3">Development Plan Approval</span></a>
</li>
<li><span class='sectionRange'>143.1 - </span><a href="#h-73"><span class="HTitleText3">Declarations</span></a>
</li>
<li><span class='sectionRange'>143.2 - </span><a href="#h-74"><span class="HTitleText3">Certificates</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-75"><span class="HTitleText2">Chief Safety Officer and Chief Conservation Officer</span></a>
</li>
<li><span class='sectionRange'>144.1 - </span><a href="#h-76"><span class="HTitleText2">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>144.2 - </span><a href="#h-77"><span class="HTitleText2">Extended Formation Flow Tests</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-78"><span class="HTitleText2">Oil and Gas Committee</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="#h-79"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-80"><span class="HTitleText3">Jurisdiction and Powers</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-81"><span class="HTitleText3">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-82"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Regulation of Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-83"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-84"><span class="HTitleText3">Waste</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-85"><span class="HTitleText3">Spills and Debris</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-86"><span class="HTitleText3">Inquiries</span></a>
</li></ul>
</li><li><span class='sectionRange'>171 - </span><a href="#h-87"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Production Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172 - </span><a href="#h-88"><span class="HTitleText3">Pooling</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-89"><span class="HTitleText3">Unitization</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-90"><span class="HTitleText3">Compulsory Unitization</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-91"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>189 - </span><a href="#h-92"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Appeals and Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>189 - </span><a href="#h-93"><span class="HTitleText3">Appeals</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-94"><span class="HTitleText3">Safety and Conservation Officers</span></a>
</li>
<li><span class='sectionRange'>198.2 - </span><a href="#h-95"><span class="HTitleText3">Installation Manager</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-96"><span class="HTitleText3">Offences and Penalties</span></a>
</li></ul>
</li><li><span class='sectionRange'>208 - </span><a href="#h-97"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-98"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-99"><span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>211 - </span><a href="#h-100"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Revenue Sharing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>211 - </span><a href="#h-101"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-102"><span class="HTitleText2">Imposition of Consumption Taxes</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-103"><span class="HTitleText2">Imposition of Insurance Premiums Tax</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-104"><span class="HTitleText2">Tax Administration Agreement</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-105"><span class="HTitleText2">Imposition of Corporate Income Taxes</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="#h-106"><span class="HTitleText2">Liability and Collection of Tax</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-107"><span class="HTitleText2">Revenue Account</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-108"><span class="HTitleText2">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-109"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-110"><span class="HTitleText2">Appropriation</span></a>
</li></ul>
</li><li><span class='sectionRange'>223 - </span><a href="#h-111"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Fiscal Equalization Offset Payments and Determination of Per Capita Fiscal Capacity</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>223 - </span><a href="#h-112"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-113"><span class="HTitleText2">Fiscal Equalization Offset Payments</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-114"><span class="HTitleText2">Determination of Per Capita Fiscal Capacity</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-115"><span class="HTitleText2">Determinations</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-116"><span class="HTitleText2">Advance Payments</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-117"><span class="HTitleText2">Appropriation</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-118"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-119"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>233 - </span><a href="#h-120"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Canada-nova Scotia Development Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>233 - </span><a href="#h-121"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-122"><span class="HTitleText2">Development Fund</span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-123"><span class="HTitleText2">Appropriation</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-124"><span class="HTitleText2">Report to Parliament</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="#h-125"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Drilling Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-126"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-127"><span class="HTitleText2">Drilling Assistance</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-128"><span class="HTitleText2">Appropriation</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="#h-129"><span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-130"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>246 - </span><a href="#h-131"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Crown Share Adjustment Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>246 - </span><a href="#h-132"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-133"><span class="HTitleText2">Adjustment Payments</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-134"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-135"><span class="HTitleText2">Appropriation</span></a>
</li></ul>
</li><li><span class='sectionRange'>250 to 252 - </span><a href="#h-136"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Corporate Income Tax</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-137"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Transitional, Consequential, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>253 - </span><a href="#h-138"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>254 to 265 - </span><a href="#h-139"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="#h-140"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="#h-141"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-142"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Limits of the Offshore Area</span> - <span class="scheduleTitleText"> - (All latitudes and longitudes referred to in this Schedule are determined according to N.A.D. 27 datum.)</span></a>
</li>
<li><a href="#h-164540"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Limits of the Bay of Fundy</span> - <span class="scheduleTitleText"> - (All latitudes and longitudes referred to in this Schedule are determined according to N.A.D. 27 datum.)</span></a>
</li>
<li><a href="#h-164545"><span class="scheduleLabel">SCHEDULE III</span> <span class="scheduleTitleText"> - Limits of Sable Island</span> - <span class="scheduleTitleText"> - (All latitudes and longitudes referred to in this Schedule are determined according to N.A.D. 27 datum.)</span></a>
</li>
<li><a href="#h-145"><span class="scheduleLabel">SCHEDULE IV</span> <span class="scheduleTitleText"> - Limits of the Portion of the Offshore Area Referred to in Sections 104 and 141</span> - <span class="scheduleTitleText"> - (All latitudes and longitudes referred to in this schedule are determined according to the NAD 27 datum. All parallels of latitude referred to in this schedule are to be determined in such a manner that they are parallel with boundaries of grid areas as defined by the Canada Oil and Gas Land Regulations.)</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
