<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
International Rapids Power Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-273720"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-273725"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-273741"><span class="HTitleText1">Commencement</span></a>
</li>
<li><a href="#h-273747"><span class="scheduleLabel">SCHEDULE</span> - <span class="scheduleTitleText"> - </span></a>
</li></ul>
</li></ul>

</nav>

