<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Petro-Canada Public Participation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-391598"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-391601"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-391616"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-391619"><span class="HTitleText1">Changes of Names</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-391629"><span class="HTitleText1">Transfer of Shares to Minister</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-391639"><span class="HTitleText1">Sale of Shares by Petro-Canada</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-391642"><span class="HTitleText1">Reorganization of Petro-Canada</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-391722"><span class="HTitleText1">Financial Arrangements</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-391729"><span class="HTitleText1">Petro-Canada International Assistance Corporation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-391743"><span class="HTitleText1">Dissolution of Petro-Canada Limited</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-391752"><span class="HTitleText1">Transitional, Consequential and Coming into Force Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-391753"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-391785"><span class="HTitleText2">Consequential</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-391792"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-391801"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>

