<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Immigration and Refugee Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-274068"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-274071"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-274085"><span class="HTitleText1">Objectives and Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-274120"><span class="HTitleText1">Enabling Authority</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-274166"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>10.01 - </span><a href="#h-274192"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Immigration to Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10.01 - </span><a href="#h-274193"><span class="HLabel2">DIVISION 0.01</span> - <span class="HTitleText2">Biometric Information</span></a>
</li>
<li><span class='sectionRange'>10.1 - </span><a href="#h-274208"><span class="HLabel2">DIVISION 0.1</span> - <span class="HTitleText2">Invitation to Make an Application</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-274277"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Requirements and Selection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-274278"><span class="HTitleText3">Requirements</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-274314"><span class="HTitleText3">Selection of Permanent Residents</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-274322"><span class="HTitleText3">Sponsorship of Foreign Nationals</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-274331"><span class="HTitleText3">Undertakings</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-274343"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>14.1 - </span><a href="#h-274361"><span class="HTitleText3">Minister’s Instructions</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-274389"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Examination</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-274418"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Entering and Remaining in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-274419"><span class="HTitleText3">Entering and Remaining</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-274473"><span class="HTitleText3">Status and Authorization to Enter</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-274598"><span class="HTitleText3">Rights and Obligations of Permanent and Temporary Residents</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-274660"><span class="HTitleText3">Status Document</span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="#h-274673"><span class="HTitleText3">Refugee Travel Document</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-274678"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-274694"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Inadmissibility</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-274820"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Loss of Status and Removal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-274821"><span class="HTitleText3">Report on Inadmissibility</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-274840"><span class="HTitleText3">Admissibility Hearing by the Immigration Division</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-274847"><span class="HTitleText3">Loss of Status</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-274871"><span class="HTitleText3">Enforcement of Removal Orders</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-274908"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-274921"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Detention and Release</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-275022"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Right of Appeal</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-275091"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Judicial Review</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-275121"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Certificates and Protection of Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-275122"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-275129"><span class="HTitleText3">Certificate</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-275170"><span class="HTitleText3">Detention and Release</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-275234"><span class="HTitleText3">Protection of Information</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-275266"><span class="HTitleText3">Special Advocate</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-275326"><span class="HTitleText3">Other Proceedings</span></a>
</li>
<li><span class='sectionRange'>87.2 - </span><a href="#h-275353"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>87.3 - </span><a href="#h-275365"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87.3 - </span><a href="#h-275366"><span class="HTitleText3">Instructions on Processing Applications and Requests</span></a>
</li>
<li><span class='sectionRange'>87.31 - </span><a href="#h-1174017"><span class="HTitleText3">Applications for Temporary Resident Visas, Work Permits and Study Permits</span></a>
</li>
<li><span class='sectionRange'>87.4 - </span><a href="#h-275393"><span class="HTitleText3">Federal Skilled Workers</span></a>
</li>
<li><span class='sectionRange'>87.5 - </span><a href="#h-275407"><span class="HTitleText3">Federal Investor and Entrepreneur Classes</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-275427"><span class="HTitleText3">Loans</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-275433"><span class="HTitleText3">Fees</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-275480"><span class="HTitleText3">Social Insurance Numbers</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-275485"><span class="HTitleText3">Representation or Advice</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-275522"><span class="HTitleText3">Material Incorporated in Regulations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-275542"><span class="HTitleText3">Report to Parliament</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-275558"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Refugee Protection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-275559"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Refugee Protection, Convention Refugees and Persons in Need of Protection</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-275598"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Convention Refugees and Persons in Need of Protection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-275599"><span class="HTitleText3">Claim for Refugee Protection</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-275613"><span class="HTitleText3">Examination of Eligibility to Refer Claim</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-275662"><span class="HTitleText3">Suspension or Termination of Consideration of Claim</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-275683"><span class="HTitleText3">Extradition Procedure</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-275695"><span class="HTitleText3">Claimant Without Identification</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-275698"><span class="HTitleText3">Decision on Claim for Refugee Protection</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-275708"><span class="HTitleText3">Cessation of Refugee Protection</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-275723"><span class="HTitleText3">Applications to Vacate</span></a>
</li>
<li><span class='sectionRange'>109.1 - </span><a href="#h-275731"><span class="HTitleText3">Designated Countries of Origin</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-275750"><span class="HTitleText3">Appeal to Refugee Appeal Division</span></a>
</li>
<li><span class='sectionRange'>111.1 - </span><a href="#h-275797"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-275810"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Pre-removal Risk Assessment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-275811"><span class="HTitleText3">Protection</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-275863"><span class="HTitleText3">Principle of Non-refoulement</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-275875"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-275876"><span class="HTitleText2">Human Smuggling and Trafficking</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-275932"><span class="HTitleText2">Offences Related to Documents</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-275952"><span class="HTitleText2">General Offences</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-275997"><span class="HTitleText2">Prosecution of Offences</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-276019"><span class="HTitleText2">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-276025"><span class="HTitleText2">Officers Authorized to Enforce Act</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-276047"><span class="HTitleText2">Peace Officers</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-276054"><span class="HTitleText2">Ticketable Offences</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-276078"><span class="HTitleText2">Debt Due to Her Majesty</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-276094"><span class="HTitleText2">Collection of Debts Due to Her Majesty</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-276119"><span class="HTitleText2">Transportation Companies</span></a>
</li>
<li><span class='sectionRange'>150.1 - </span><a href="#h-276147"><span class="HTitleText2">Sharing of Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-276160"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Immigration and Refugee Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-276161"><span class="HTitleText2">Composition of Board</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-276198"><span class="HTitleText2">Head Office and Staff</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-276208"><span class="HTitleText2">Duties of Chairperson</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-276231"><span class="HTitleText2">Functioning of Board</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-276247"><span class="HTitleText2">Provisions that Apply to All Divisions</span></a>
</li>
<li><span class='sectionRange'>169.1 - </span><a href="#h-276295"><span class="HTitleText2">Refugee Protection Division</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-276321"><span class="HTitleText2">Refugee Appeal Division</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-276338"><span class="HTitleText2">Immigration Division</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-276352"><span class="HTitleText2">Immigration Appeal Division</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-276366"><span class="HTitleText2">Remedial and Disciplinary Measures</span></a>
</li></ul>
</li><li><span class='sectionRange'>186.1 - </span><a href="#h-276412"><span class="HLabel1">PART 4.1</span> - <span class="HTitleText1">Electronic Administration</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-276454"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Transitional Provisions, Consequential and Related Amendments, Coordinating Amendments, Repeals and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>187 - </span><a href="#h-276455"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-276499"><span class="HTitleText2">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>202 - </span><a href="#h-276500"><span class="HTitleText3">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-276502"><span class="HTitleText3">Agricultural Marketing Programs Act</span></a>
</li>
<li><span class='sectionRange'>204 and 205 - </span><a href="#h-276504"><span class="HTitleText3">Animal Pedigree Act</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-276506"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-276508"><span class="HTitleText3">Budget Implementation Act, 1998</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-276510"><span class="HTitleText3">Business Development Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-276512"><span class="HTitleText3">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-276514"><span class="HTitleText3">Canada Customs and Revenue Agency Act</span></a>
</li>
<li><span class='sectionRange'>211 to 214 - </span><a href="#h-276516"><span class="HTitleText3">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-276518"><span class="HTitleText3">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>216 to 218 - </span><a href="#h-276520"><span class="HTitleText3">Canada Shipping Act</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-276522"><span class="HTitleText3">Canada Student Financial Assistance Act</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-276524"><span class="HTitleText3">Canada Student Loans Act</span></a>
</li>
<li><span class='sectionRange'>221 and 222 - </span><a href="#h-276526"><span class="HTitleText3">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>223 to 226 - </span><a href="#h-276528"><span class="HTitleText3">Canadian Security Intelligence Service Act</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-276530"><span class="HTitleText3">Chemical Weapons Convention Implementation Act</span></a>
</li>
<li><span class='sectionRange'>227.1 to 232 - </span><a href="#h-276532"><span class="HTitleText3">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-276534"><span class="HTitleText3">Comprehensive Nuclear Test-Ban Treaty Implementation Act</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-276536"><span class="HTitleText3">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>235 to 241 - </span><a href="#h-276538"><span class="HTitleText3">Copyright Act</span></a>
</li>
<li><span class='sectionRange'>242 and 243 - </span><a href="#h-276540"><span class="HTitleText3">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-276542"><span class="HTitleText3">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>248 and 249 - </span><a href="#h-276546"><span class="HTitleText3">Emergencies Act</span></a>
</li>
<li><span class='sectionRange'>250 to 252 - </span><a href="#h-276548"><span class="HTitleText3">Extradition Act</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-276550"><span class="HTitleText3">Foreign Publishers Advertising Services Act</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-276552"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-276554"><span class="HTitleText3">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>256 to 258 - </span><a href="#h-276556"><span class="HTitleText3">International Centre for Human Rights and Democratic Development Act</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-276558"><span class="HTitleText3">Investment Canada Act</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-276560"><span class="HTitleText3">Labour Adjustment Benefits Act</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-276562"><span class="HTitleText3">Mutual Legal Assistance in Criminal Matters Act</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-276564"><span class="HTitleText3">National Energy Board Act</span></a>
</li>
<li><span class='sectionRange'>263 to 267 - </span><a href="#h-276566"><span class="HTitleText3">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-276568"><span class="HTitleText3">Pilotage Act</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-276570"><span class="HTitleText3">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-276572"><span class="HTitleText3">Proceeds of Crime (Money Laundering) Act</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-276574"><span class="HTitleText3">Trade-marks Act</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-276576"><span class="HTitleText3">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-276578"><span class="HTitleText3">Terminology</span></a>
</li></ul>
</li><li><span class='sectionRange'>273.1 - </span><a href="#h-276585"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-276587"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-276589"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><a href="#h-276595"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

