<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le pipe-line du Nord</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Objets</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Administration du pipe-line du Nord</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Constitution de l’Administration</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HTitleText2">Bureaux</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2">Vérification et rapport annuel</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Transfert de pouvoirs</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Conseil consultatif fédéral-provincial</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Conseils consultatifs</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">L’Office national de l’énergie</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText2">Certificat</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2">Questions judiciaires</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-16"><span class="HTitleText2">Droits des autochtones</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-17"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-18"><span class="HTitleText2">Recouvrement des frais</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-19"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Mouvement, droits et tarifs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-20"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-21"><span class="HTitleText2">Consultation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-22"><span class="HTitleText2">Droits et tarifs</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-23"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-24"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Biens immeubles</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-25"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-26"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-27"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-28"><span class="HTitleText2">Abrogation de la partie I</span></a>
</li></ul>
</li><li><a href="#h-357738"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Accord entre le Canada et les États-Unis d’Amérique sur les principes applicables à un pipe-line pour le transport du gaz naturel du nord</span></a>
</li>
<li><a href="#h-357935"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Compagnies</span></a>
</li>
<li><a href="#h-31"><span class="scheduleLabel">ANNEXE III</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
