<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Research Council Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-363419"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-363424"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-363434"><span class="HTitleText1">Establishment of Council</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-363442"><span class="HTitleText1">Duties and Powers</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-363476"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-363532"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-363537"><span class="HTitleText1">Annual Report</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
