<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Small Business Financing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-53864"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-53867"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-53885"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-53897"><span class="HTitleText1">Eligibility</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-53915"><span class="HTitleText1">Liability of Minister</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-53955"><span class="HTitleText1">Fees and Charges</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-53965"><span class="HTitleText1">Pilot Projects</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-53979"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-54010"><span class="HTitleText1">Audit or Examination</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-54022"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-54035"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-54044"><span class="HTitleText1">Consequential Amendment</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-54046"><span class="HTitleText1">Repeal</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
