<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Foreign Extraterritorial Measures Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-236139"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-236144"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-236162"><span class="HTitleText1">Amendments to Schedule</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-236169"><span class="HTitleText1">Disclosure of Records to Foreign Tribunals</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-236170"><span class="HTitleText2">Orders of the Attorney General</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-236188"><span class="HTitleText2">Seizure of Records</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-236193"><span class="HTitleText1">Measures of a Foreign State or Foreign Tribunal</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-236205"><span class="HTitleText1">Service</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-236217"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>7.1 - </span><a href="#h-236235"><span class="HTitleText1">Recognition and Enforcement of Foreign Judgments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7.1 - </span><a href="#h-236236"><span class="HTitleText2">Orders of the Attorney General</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-236264"><span class="HTitleText2">Recovery of Damages</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-236283"><span class="HTitleText1">Tabling of Orders</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-236288"><span class="HTitleText1">Commencement</span></a>
</li>
<li><a href="#h-236294"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

