<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’aménagement de l’énergie des rapides internationaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-267045"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-267050"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-267066"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-267072"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - [Traduction]</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
