<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Safe Food for Canadians Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-429385"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-429388"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-429420"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-429423"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-429485"><span class="HTitleText1">Registrations and Licences</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-429518"><span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-429519"><span class="HTitleText2">Certificate</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-429522"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-429566"><span class="HTitleText2">Dealing with Seized Things</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-429583"><span class="HTitleText2">Other Measures</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-429614"><span class="HTitleText2">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-429646"><span class="HTitleText2">Analysis</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-429651"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-429684"><span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-429685"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-429702"><span class="HTitleText2">Export Certificates</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-429705"><span class="HTitleText2">Samples</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-429708"><span class="HTitleText2">Intellectual Property</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-429711"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-429764"><span class="HTitleText2">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-429773"><span class="HTitleText2">Interim Orders</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-429793"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-429796"><span class="HTitleText2">Limitation on Liability</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-429811"><span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-429817"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-429846"><span class="HTitleText1">Repeals</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-429850"><span class="HTitleText1">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="#h-429851"><span class="HTitleText2"><cite class="XRefExternalAct">Competition Act</cite></span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-429853"><span class="HTitleText2"><cite class="XRefExternalAct">Consumer Packaging and Labelling Act</cite></span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-429860"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Courts Act</cite></span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-429862"><span class="HTitleText2"><cite class="XRefExternalAct">Feeds Act</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-429864"><span class="HTitleText2"><cite class="XRefExternalAct">Fertilizers Act</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-429866"><span class="HTitleText2"><cite class="XRefExternalAct">Seeds Act</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-429870"><span class="HTitleText2"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-429872"><span class="HTitleText2"><cite class="XRefExternalAct">Health of Animals Act</cite></span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-429875"><span class="HTitleText2"><cite class="XRefExternalAct">Plant Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-429877"><span class="HTitleText2"><cite class="XRefExternalAct">Contraventions Act</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-429879"><span class="HTitleText2"><cite class="XRefExternalAct">Agriculture and Agri-Food Administrative Monetary Penalties Act</cite></span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-429886"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Food Inspection Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-429890"><span class="HTitleText2"><cite class="XRefExternalAct">Pest Control Products Act</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-429892"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Border Services Agency Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-429895"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-429898"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
