<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Bureau de la traduction</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-441186"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-441191"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-441196"><span class="HTitleText1">Constitution</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-441201"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-441209"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-441215"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>

