<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Assisted Human Reproduction Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-5999"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-6002"><span class="HTitleText1">Principles</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-6012"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6052"><span class="HTitleText1">Prohibited Activities</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-6124"><span class="HTitleText1">Responsibility of Minister</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-6150"><span class="HTitleText1">Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-6276"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-6299"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-6366"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 - </span><a href="#h-6367"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-6370"><span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-6372"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-6375"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-6377"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
