<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Cour suprême</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-432685"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-432690"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-432707"><span class="HTitleText1">La Cour</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-432712"><span class="HTitleText1">Les juges</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-432759"><span class="HTitleText1">Greffe et personnel de la Cour</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-432806"><span class="HTitleText1">Avocats et procureurs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-432819"><span class="HTitleText1">Sessions et quorum</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-432898"><span class="HTitleText1">Juridiction d’appel</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-432971"><span class="HTitleText1">Jugements</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-432988"><span class="HTitleText1">Frais</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-432993"><span class="HTitleText1">Amendements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-433005"><span class="HTitleText1">Intérêt</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-433010"><span class="HTitleText1">Certificat de jugement</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-433015"><span class="HTitleText1">Caractère souverain</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-433020"><span class="HTitleText1">Juridiction spéciale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-433021"><span class="HTitleText2">Renvois par le gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-433043"><span class="HTitleText2">Questions déférées par le Sénat ou les Communes</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-433048"><span class="HTitleText2">Certiorari</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-433053"><span class="HTitleText1">Procédure d’appel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-433054"><span class="HTitleText2">L’appel</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-433117"><span class="HTitleText2">Sursis d’exécution</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-433159"><span class="HTitleText2">Désistement</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-433167"><span class="HTitleText2">Cassation du jugement</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-433172"><span class="HTitleText2">Rejet de l’appel pour retard</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-433180"><span class="HTitleText2">Décès des parties</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-433212"><span class="HTitleText1">Mise au rôle</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-433217"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-433299"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

