<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère des Transports</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-441394"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-441399"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-441407"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-441439"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-441460"><span class="HTitleText1">Audition de témoins sous serment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-441471"><span class="HTitleText1">Contrats, soumissions et sûretés</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-441495"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-441500"><span class="HTitleText1">Péages sur les canaux</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-441518"><span class="HTitleText1">Règlements pour l’usage des canaux</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-441538"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-441547"><span class="HTitleText1">Rapport annuel</span></a>
</li></ul>
</li></ul>

</nav>

