<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les pensions</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-404646"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-404651"><span class="HTitleText1">Règle d’interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-404656"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="page-1.html#h-404729"><span class="HTitleText1">Loi sur le bien-être des vétérans</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-2.html#h-404743"><span class="HTitleText1">Égalité de statut</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-404748"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-404773"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Pensions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-4.html#h-404988"><span class="HTitleText2">Enfants</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-405029"><span class="HTitleText2">Pensions pour invalidité</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-405130"><span class="HTitleText2">Pensions pour décès</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-7.html#h-405301"><span class="HTitleText2">Pensions supplémentaires en ce qui concerne les membres des forces alliées et des marines marchandes alliées</span></a>
</li></ul>
</li><li><span class='sectionRange'>71.1 - </span><a href="page-7.html#h-405374"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Prisonniers de guerre</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>71.1 - </span><a href="page-7.html#h-405375"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="page-8.html#h-405404"><span class="HTitleText2">Indemnités</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="page-8.html#h-405442"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Allocation d’incapacité exceptionnelle</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-8.html#h-405469"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Ajustement annuel des pensions et allocations</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-8.html#h-405508"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Procédure</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-9.html#h-405577"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="page-11.html#h-405679"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Échelle des pensions d’invalidité</span></a>
</li>
<li><a href="page-12.html#h-405690"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Pensions pour décès</span></a>
</li>
<li><a href="page-13.html#h-405699"><span class="scheduleLabel">ANNEXE III</span> <span class="scheduleTitleText"> - Allocations</span></a>
</li></ul>
</li></ul>

</nav>

