<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Pilotage Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-394338"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-394343"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-394353"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Pilotage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-394354"><span class="HTitleText2">Interpretation</span></a>
</li></ul>
</li><li><span class='sectionRange'>3 - </span><a href="#h-394365"><span class="HTitleText1">Pilotage Authorities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-394366"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-394397"><span class="HTitleText2">Organization</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-394480"><span class="HTitleText1">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-394533"><span class="HTitleText1">Licences and Certificates</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-394638"><span class="HTitleText1">Tariffs</span></a>
</li>
<li><span class='sectionRange'>36.01 - </span><a href="#h-394683"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-394700"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-394734"><span class="HTitleText1">St. Lambert Lock</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-394745"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-394777"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-394788"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-394796"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Lower St. Lawrence Pilots’ Pensions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-394797"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-394822"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-394827"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-394868"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><a href="#h-22"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
