<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi fédérale sur la responsabilité</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-232179"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-232182"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Conflits d’intérêts, financement électoral, lobbying et personnel ministériel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-232183"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les conflits d’intérêts</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-232184"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-232186"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-232211"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-232212"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-232214"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-232217"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-232219"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion financière et statistique des premières nations</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-232221"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-232231"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite></span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-232233"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-232235"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-232242"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-232246"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-232251"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-232253"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-232255"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-232260"><span class="HTitleText2"><cite class="XRefExternalAct">Loi électorale du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-232261"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-232283"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-232287"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-232288"><span class="HTitleText4"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-232291"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’enregistrement des lobbyistes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-232292"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-232310"><span class="HTitleText3">Terminologie</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-232312"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-232322"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-232323"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-232327"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-232332"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-232334"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-232337"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-232339"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>100 - </span><a href="#h-232340"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-232348"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-232350"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="#h-232366"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Appui au Parlement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="#h-232367"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-232369"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le vérificateur général</cite></span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-232371"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-232373"><span class="HTitleText2">Loi sur le Parlement du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-232374"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-232380"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-232384"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-232386"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-232388"><span class="HTitleText2">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="#h-232390"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Directeur des poursuites pénales, transparence administrative et divulgation des actes répréhensibles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-232391"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le directeur des poursuites pénales</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-232392"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-232394"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-232402"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>129 - </span><a href="#h-232403"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-232405"><span class="HTitleText4"><cite class="XRefExternalAct">Loi électorale du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-232413"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le ministère de la Justice</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-232415"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-232418"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="#h-232420"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-232421"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>172.1 - </span><a href="#h-232455"><span class="HTitleText3">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>172.1 - </span><a href="#h-232456"><span class="HTitleText4">Loi sur la Commission canadienne du blé</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-232458"><span class="HTitleText2">Loi électorale du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-232459"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-232465"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>179 - </span><a href="#h-232467"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
</li>
<li><span class='sectionRange'>179.1 - </span><a href="#h-232469"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Bibliothèque et les Archives du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-232472"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-232486"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des fonctionnaires divulgateurs d’actes répréhensibles</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="#h-232487"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-232520"><span class="HTitleText3">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-232522"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les traitements</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-232524"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>229 - </span><a href="#h-232530"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Supervision administrative et responsabilisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>229 - </span><a href="#h-232531"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Banque de développement du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-232533"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil des Arts du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-232535"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société canadienne d’hypothèques et de logement</cite></span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-232539"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-232543"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Agence du revenu du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-232545"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Corporation commerciale canadienne</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-232547"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Commission canadienne du lait</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-232548"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-232552"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>243 - </span><a href="#h-232554"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Fondation canadienne des relations raciales</cite></span></a>
</li>
<li><span class='sectionRange'>244.1 - </span><a href="#h-232557"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Commission canadienne du tourisme</cite></span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-232560"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société de développement du Cap-Breton</cite></span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="#h-232562"><span class="HTitleText2"><cite class="XRefExternalAct">Code criminel</cite></span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-232564"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Société d’expansion du Cap-Breton</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="#h-232565"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-232572"><span class="HTitleText3">Disposition transitoire</span></a>
</li></ul>
</li><li><span class='sectionRange'>254 - </span><a href="#h-232574"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-232576"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur Financement agricole Canada</cite></span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-232579"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>257 - </span><a href="#h-232580"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-232595"><span class="HTitleText3">Dispositions de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>276 - </span><a href="#h-232601"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la commercialisation du poisson d’eau douce</cite></span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-232605"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les musées</cite></span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="#h-232607"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Centre national des Arts</cite></span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="#h-232611"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la capitale nationale</cite></span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-232619"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le pilotage</cite></span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="#h-232625"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office d’investissement des régimes de pensions du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-232629"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la Monnaie royale canadienne</cite></span></a>
</li>
<li><span class='sectionRange'>299 - </span><a href="#h-232631"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Conseil canadien des normes</cite></span></a>
</li>
<li><span class='sectionRange'>300 - </span><a href="#h-232633"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>301 - </span><a href="#h-232639"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Contrats et approvisionnement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>301 - </span><a href="#h-232640"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le vérificateur général</cite></span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-232646"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère des Travaux publics et des Services gouvernementaux</cite></span></a>
</li>
<li><span class='sectionRange'>308 - </span><a href="#h-232649"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>308 - </span><a href="#h-232650"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-232656"><span class="HTitleText3">Disposition de coordination</span></a>
</li></ul>
</li><li><span class='sectionRange'>314 - </span><a href="#h-232658"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-232665"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
