<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Pest Control Products Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Mandate</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Advisory Council</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">Registration of Pest Control Products</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Applications for Registration or Amendment</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Maximum Residue Limits</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Additional Information and Mandatory Reporting</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Re-evaluation and Special Review</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-12"><span class="HTitleText2">Other Grounds for Cancellation or Amendment</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText2">Public Consultation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText1">Export Controls</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">Reconsideration of Decisions</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText1">Authorization to Use Unregistered Product</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText1">Access to Information</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-19"><span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-20"><span class="HTitleText2">Inspectors and Analysts</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-21"><span class="HTitleText2">Voluntary Reports</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-22"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-23"><span class="HTitleText2">Searches</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-24"><span class="HTitleText2">Seizures</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-25"><span class="HTitleText2">Disposition of Things Seized</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-26"><span class="HTitleText2">Enforcement Measures</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-27"><span class="HTitleText2">Disposal and Risk-control Measures</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-28"><span class="HTitleText2">Review of Inspectors’ Requirements</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-29"><span class="HTitleText2">Court Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-30"><span class="HTitleText1">Delivery of Documents</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-31"><span class="HTitleText1">Fees, Charges and Costs</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-32"><span class="HTitleText1">Limitation on Liability</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-33"><span class="HTitleText1">Compensation for Use of Information</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-34"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-35"><span class="HTitleText1">Offences and Punishment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>68 - </span><a href="#h-36"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-37"><span class="HTitleText2">Related Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-38"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-39"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>82 to 88 - </span><a href="#h-40"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-41"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-42"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
