<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Gender Equality Week Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-247289"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-247292"><span class="HTitleText1">Gender Equality Week</span></a>
</li></ul>
</li></ul>

</nav>

