<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada and Taiwan Territories Tax Arrangement Act, 2016</a><ul class="TocIndent"><li><a href="#h-41294"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Arrangement Between the Canadian Trade Office in Taipei and the Taipei Economic and Cultural Office in Canada for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income</span></a>
</li>
<li><a href="#h-41561"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Protocol of Understanding</span></a>
</li></ul>
</li></ul>

</nav>

