<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
College of Patent Agents and Trademark Agents Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-86615"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-86618"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-86635"><span class="HTitleText1">Establishment and Organization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-86636"><span class="HTitleText2">College</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-86656"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-86725"><span class="HTitleText2">Committees, Registrar and Chief Executive Officer</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-86741"><span class="HTitleText2">Powers of Minister and Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="page-2.html#h-86754"><span class="HTitleText1">Licensees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="page-2.html#h-86755"><span class="HTitleText2">Patent Agents</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-86780"><span class="HTitleText2">Trademark Agents</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-86805"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-2.html#h-86820"><span class="HTitleText2">Suspension, Revocation and Surrender of Licences</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="page-2.html#h-86839"><span class="HTitleText1">Investigations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-2.html#h-86840"><span class="HTitleText2">Duty to Investigate</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-2.html#h-86845"><span class="HTitleText2">Complaints</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-2.html#h-86855"><span class="HTitleText2">Conduct of Investigation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-86948"><span class="HTitleText2">Conclusion of Investigation</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-3.html#h-86960"><span class="HTitleText1">Disciplinary Proceedings</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-4.html#h-87033"><span class="HTitleText1">Confidentiality</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-4.html#h-87065"><span class="HTitleText1">Prohibitions and Offences</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-4.html#h-87104"><span class="HTitleText1">By-laws and Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="page-4.html#h-87151"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

