<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-472417"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-472420"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-472441"><span class="HTitleText1">Government</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-472442"><span class="HTitleText2">Executive Power</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-472466"><span class="HTitleText2">Legislative Power</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-472467"><span class="HTitleText3">Legislative Assembly</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-472488"><span class="HTitleText3">Legislature</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-472491"><span class="HTitleText3">Legislative Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-472600"><span class="HTitleText2">Yukon Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-472610"><span class="HTitleText2">Yukon Public Accounts</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-472650"><span class="HTitleText1">Administration of Justice</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-472651"><span class="HTitleText2">Judicature</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-472656"><span class="HTitleText2">Supreme Court of Yukon</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-472677"><span class="HTitleText2">Court of Appeal of Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-472680"><span class="HTitleText1">Real Property, Water, Oil and Gas</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-472681"><span class="HTitleText2">Administration and Control</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-472705"><span class="HTitleText2">Restrictions</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-472746"><span class="HTitleText1">Exercise of Federal Powers</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-472760"><span class="HTitleText1">Legislative Amendment</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-472766"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>68 to 76 - </span><a href="#h-472834"><span class="HTitleText1">Amendments to this Act</span></a>
</li>
<li><span class='sectionRange'>77 to 271 - </span><a href="#h-472836"><span class="HTitleText1">Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>272 to 278 - </span><a href="#h-472838"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>279 to 284 - </span><a href="#h-472840"><span class="HTitleText1">Repeals</span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="#h-472842"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-472851"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Description of Yukon</span></a>
</li>
<li><a href="#h-472854"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Northern Limit of Adjoining Area</span></a>
</li></ul>
</li></ul>

</nav>

