<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Antarctic Environmental Protection Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-6"><span class="HTitleText1">Permits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Issuance</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText2">Environmental Impact Assessments</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText2">Waste Management Plans and Emergency Plans</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText2">Security</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-12"><span class="HTitleText1">Enforcement in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-13"><span class="HTitleText2">Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-14"><span class="HTitleText2">Inspections in Canada</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-15"><span class="HTitleText2">Search and Seizure in Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText2">Detention in Canada</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-17"><span class="HTitleText2">Detention of Canadian Vessels</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-18"><span class="HTitleText2">Assistance to Enforcement Officers and Analysts</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-19"><span class="HTitleText2">Forfeiture in Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-20"><span class="HTitleText1">Inspections in the Antarctic</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-21"><span class="HTitleText1">Obstruction and False Information</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-23"><span class="HTitleText1">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-24"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
