<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les marques de commerce</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-3"><span class="HTitleText1">Concurrence déloyale et marques interdites</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-4"><span class="HTitleText1">Marques de commerce enregistrables</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-5"><span class="HTitleText1">Personnes admises à l’enregistrement des marques de commerce</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-6"><span class="HTitleText1">Validité et effet de l’enregistrement</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-7"><span class="HTitleText1">Marques de certification</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-8"><span class="HTitleText1">Registre des marques de commerce</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-9"><span class="HTitleText1">Demandes d’enregistrement de marques de commerce</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-10"><span class="HTitleText1">Enregistrement des marques de commerce</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-11"><span class="HTitleText1">Modification du registre</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-12"><span class="HTitleText1">Renouvellement des enregistrements</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-13"><span class="HTitleText1">Prolongation de délai</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-14"><span class="HTitleText1">Transfert</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-15"><span class="HTitleText1">Changement apporté aux fins de l’emploi d’une marque</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-16"><span class="HTitleText1">Licences</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-17"><span class="HTitleText1">Procédures judiciaires</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-18"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-19"><span class="HTitleText1">Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-20"><span class="HTitleText1">Disposition transitoire</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
