<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le libre choix des producteurs de grains en matière de commercialisation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-344499"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-344502"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Activités de la Commission canadienne du blé en période préliminaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-344503"><span class="HTitleText2">Modification de la Loi sur la Commission canadienne du blé</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-344515"><span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-344518"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Mise en commun volontaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-344519"><span class="HTitleText2">Édiction de la Loi sur la Commission canadienne du blé (activités en période intérimaire)</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-344522"><span class="HTitleText2">Modifications corrélatives et connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-344523"><span class="HTitleText3">Loi sur le paiement anticipé des récoltes</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-344525"><span class="HTitleText3">Loi sur les programmes de commercialisation agricole</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-344532"><span class="HTitleText3">Loi sur la vente coopérative des produits agricoles</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-344534"><span class="HTitleText3">Loi modifiant la Loi sur les grains du Canada et la Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire et abrogeant la Loi sur les marchés de grain à terme</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-344536"><span class="HTitleText3">Loi sur les grains du Canada</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-344548"><span class="HTitleText3">Loi sur les offices des produits agricoles</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-344550"><span class="HTitleText3">Loi sur l’aide à l’alimentation des animaux de ferme</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-344552"><span class="HTitleText3">Loi sur les paiements anticipés pour le grain des Prairies</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-344554"><span class="HTitleText3">Loi sur les semences</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-344556"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-344558"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-344561"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Commercialisation de la Commission canadienne du blé</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-344562"><span class="HTitleText2">Prorogation</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-344585"><span class="HTitleText2">Entrée en vigueur</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-344588"><span class="HTitleText2">Cessation d’effet</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-344591"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Liquidation de la Commission canadienne du blé</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-344592"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-344595"><span class="HTitleText2">Ultime période de mise en commun</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-344603"><span class="HTitleText2">Distribution de l’actif</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-344621"><span class="HTitleText2">Nomination d’un liquidateur</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-344630"><span class="HTitleText2">Date de dissolution</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-344633"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Abrogation de la Loi sur la Commission canadienne du blé (activités en période intérimaire)</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-344634"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-344637"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-344640"><span class="HTitleText2">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-344641"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-344643"><span class="HTitleText3">Loi sur les grains du Canada</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-344645"><span class="HTitleText3">Loi sur les transports au Canada</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-344647"><span class="HTitleText3">Loi sur les arrangements fiscaux entre le gouvernement fédéral et les provinces</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-344649"><span class="HTitleText3">Loi sur les paiements versés en remplacement d’impôts</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-344651"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-344653"><span class="HTitleText2">Abrogation</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
