<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Courts Administration Service Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-112392"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-112395"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-112401"><span class="HTitleText1">Courts Administration Service</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-112411"><span class="HTitleText1">Chief Administrator</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-112432"><span class="HTitleText1">Powers, Duties and Functions of Chief Administrator</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-112442"><span class="HTitleText1">Chief Justices</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-112463"><span class="HTitleText1">Staff of the Service</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-112466"><span class="HTitleText1">Contracting for Services</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-112469"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>13 to 58 - </span><a href="#h-112475"><span class="HTitleText1">Amendments to the Federal Court Act</span></a>
</li>
<li><span class='sectionRange'>59 to 81 - </span><a href="#h-112477"><span class="HTitleText1">Amendments to the Tax Court of Canada Act</span></a>
</li>
<li><span class='sectionRange'>82 to 111 - </span><a href="#h-112479"><span class="HTitleText1">Amendments to the Judges Act</span></a>
</li>
<li><span class='sectionRange'>112 and 113 - </span><a href="#h-112481"><span class="HTitleText1">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 and 113 - </span><a href="#h-112482"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-112484"><span class="HTitleText2">Anti-Personnel Mines Convention Implementation Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-112486"><span class="HTitleText2">Army Benevolent Fund Act</span></a>
</li>
<li><span class='sectionRange'>116 and 117 - </span><a href="#h-112488"><span class="HTitleText2">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-112490"><span class="HTitleText2">Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-112493"><span class="HTitleText2">Canada Labour Code</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-112495"><span class="HTitleText2">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-112497"><span class="HTitleText2">Canada Transportation Act</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-112499"><span class="HTitleText2">Canadian Ownership and Control Determination Act</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-112501"><span class="HTitleText2">Civil International Space Station Agreement Implementation Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-112503"><span class="HTitleText2">Commercial Arbitration Act</span></a>
</li>
<li><span class='sectionRange'>126 to 129 - </span><a href="#h-112505"><span class="HTitleText2">Competition Act</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-112507"><span class="HTitleText2">Competition Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-112509"><span class="HTitleText2">Copyright Act</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-112511"><span class="HTitleText2">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-112513"><span class="HTitleText2">Cree-Naskapi (of Quebec) Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-112515"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-112517"><span class="HTitleText2">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-112519"><span class="HTitleText2">Energy Supplies Emergency Act</span></a>
</li>
<li><span class='sectionRange'>137 to 140 - </span><a href="#h-112521"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-112523"><span class="HTitleText2">Extradition Act</span></a>
</li>
<li><span class='sectionRange'>142 and 143 - </span><a href="#h-112525"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>144 to 147 - </span><a href="#h-112527"><span class="HTitleText2">Immigration Act</span></a>
</li>
<li><span class='sectionRange'>148 and 149 - </span><a href="#h-112529"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-112531"><span class="HTitleText2">International Sale of Goods Contracts Convention Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-112533"><span class="HTitleText2">Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-112535"><span class="HTitleText2">Investment Canada Act</span></a>
</li>
<li><span class='sectionRange'>153 and 154 - </span><a href="#h-112537"><span class="HTitleText2">National Defence Act</span></a>
</li>
<li><span class='sectionRange'>155 to 157 - </span><a href="#h-112539"><span class="HTitleText2">Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-112541"><span class="HTitleText2">Plant Breeders’ Rights Act</span></a>
</li>
<li><span class='sectionRange'>159 and 160 - </span><a href="#h-112543"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-112545"><span class="HTitleText2">Proceeds of Crime (Money Laundering) Act</span></a>
</li>
<li><span class='sectionRange'>162 and 163 - </span><a href="#h-112547"><span class="HTitleText2">Public Sector Compensation Act</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-112549"><span class="HTitleText2">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>165 to 167 - </span><a href="#h-112551"><span class="HTitleText2">Public Service Staff Relations Act</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-112553"><span class="HTitleText2">Railway Safety Act</span></a>
</li>
<li><span class='sectionRange'>169 to 173 - </span><a href="#h-112555"><span class="HTitleText2">Special Import Measures Act</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-112557"><span class="HTitleText2">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>175 and 176 - </span><a href="#h-112559"><span class="HTitleText2">Supreme Court Act</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-112561"><span class="HTitleText2">Trade-marks Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-112563"><span class="HTitleText2">United Nations Foreign Arbitral Awards Convention Act</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-112565"><span class="HTitleText2">Veterans Review and Appeal Board Act</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-112567"><span class="HTitleText2">Yukon First Nations Self-Government Act</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-112569"><span class="HTitleText2">Yukon Surface Rights Board Act</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-112571"><span class="HTitleText2">References</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-112589"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>193 to 198 - </span><a href="#h-112636"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-112638"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-112642"><span class="scheduleLabel">SCHEDULE</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
