<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Industrial Design Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-333790"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-333795"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-333813"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Industrial Designs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-333814"><span class="HTitleText2">Registration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-333925"><span class="HTitleText2">Exclusive Right</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-333954"><span class="HTitleText2">Proprietorship</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-333962"><span class="HTitleText2">Transfers</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-333979"><span class="HTitleText2">Action for Infringement</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-334013"><span class="HLabel1">PART II</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-334016"><span class="HTitleText2">Extension of Time</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-334024"><span class="HTitleText2">Procedure as to Rectification and Alteration</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-334047"><span class="HTitleText2">Electronic Form and Means</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-334057"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-334092"><span class="HTitleText1">Transitional Provisions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
