<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2013 pour la mise en oeuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-437245"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-437248"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Convention Fiscale Canada-Namibie</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-437250"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Convention Fiscale Canada-Serbie</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-437252"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Convention Fiscale Canada-Pologne</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-437254"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Accord Fiscal Canada-Hong Kong</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-437256"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Convention Fiscale Canada-Luxembourg</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-437257"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de 1999 pour la mise en oeuvre de conventions fiscales</cite></span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-437261"><span class="HTitleText2">Avenant et Accord Canada-Luxembourg, 2012</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-437268"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Convention Fiscale Canada-Suisse</span></a>
</li>
<li><a href="#h-437278"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-437280"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-437282"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="#h-437284"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-437286"><span class="scheduleLabel">ANNEXE 5</span> </a>
</li>
<li><a href="#h-437289"><span class="scheduleLabel">ANNEXE 6</span> </a>
</li></ul>
</li></ul>

</nav>

