<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Energy Monitoring Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-220160"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-220165"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-220188"><span class="HTitleText1">Energy Enterprise Monitoring</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-220242"><span class="HTitleText1">Oil and Gas Dealer Monitoring</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-220266"><span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-220267"><span class="HTitleText2">Reports Regarding Energy Commodities and Energy Enterprises</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-220275"><span class="HTitleText2">Documents, Records and Books of Account</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-220290"><span class="HTitleText2">Disclosure of Statistics and Information</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-220312"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-220342"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
