<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Freezing Assets of Corrupt Foreign Officials Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-237470"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-237473"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-237500"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-237503"><span class="HTitleText1">Orders and Regulations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-237530"><span class="HTitleText1">Duty To Determine</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-237544"><span class="HTitleText1">Disclosure</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-237552"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-237571"><span class="HTitleText1">Rights of Persons Who Are Subject to an Order or Regulation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-237579"><span class="HTitleText1">Application for a Certificate</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-237590"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-237599"><span class="HTitleText1">Review and Report</span></a>
</li></ul>
</li></ul>

</nav>

