<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la modernisation de certains régimes d’avantages et d’obligations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-349669"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-349673"><span class="HTitleText1">Loi sur les programmes de commercialisation agricole</span></a>
</li>
<li><span class='sectionRange'>3 à 7 - </span><a href="page-1.html#h-349675"><span class="HTitleText1">Loi sur les banques</span></a>
</li>
<li><span class='sectionRange'>8 à 21 - </span><a href="page-1.html#h-349677"><span class="HTitleText1">Loi sur la faillite et l’insolvabilité</span></a>
</li>
<li><span class='sectionRange'>22 à 24 - </span><a href="page-1.html#h-349679"><span class="HTitleText1">Loi sur les lettres de change</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-349681"><span class="HTitleText1">Loi sur les ponts</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-349683"><span class="HTitleText1">Loi sur la Banque de développement du Canada</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-1.html#h-349685"><span class="HTitleText1">Loi canadienne sur les sociétés par actions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-1.html#h-349687"><span class="HTitleText1">Loi canadienne sur les coopératives</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-1.html#h-349689"><span class="HTitleText1">Loi sur les corporations canadiennes</span></a>
</li>
<li><span class='sectionRange'>30 à 40 - </span><a href="page-1.html#h-349691"><span class="HTitleText1">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-1.html#h-349693"><span class="HTitleText1">Loi sur la Société canadienne d’hypothèques et de logement</span></a>
</li>
<li><span class='sectionRange'>42 à 65 - </span><a href="page-1.html#h-349695"><span class="HTitleText1">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-1.html#h-349697"><span class="HTitleText1">Loi sur la pension de retraite des forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="page-1.html#h-349701"><span class="HTitleText1">Loi sur la médaille canadienne du maintien de la paix</span></a>
</li>
<li><span class='sectionRange'>70 à 72 - </span><a href="page-1.html#h-349703"><span class="HTitleText1">Loi sur la Commission canadienne du blé</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-1.html#h-349705"><span class="HTitleText1">Loi sur le transport aérien</span></a>
</li>
<li><span class='sectionRange'>74 à 77 - </span><a href="page-1.html#h-349707"><span class="HTitleText1">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>78 et 79 - </span><a href="page-1.html#h-349709"><span class="HTitleText1">Loi sur l’assurance du service civil</span></a>
</li>
<li><span class='sectionRange'>80 à 83 - </span><a href="page-1.html#h-349711"><span class="HTitleText1">Loi sur les prestations de guerre pour les civils</span></a>
</li>
<li><span class='sectionRange'>84 à 86 - </span><a href="page-1.html#h-349713"><span class="HTitleText1">Loi sur les associations coopératives de crédit</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-1.html#h-349715"><span class="HTitleText1">Loi sur les déclarations des personnes morales</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-1.html#h-349717"><span class="HTitleText1">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>89 et 90 - </span><a href="page-1.html#h-349719"><span class="HTitleText1">Loi sur les Cris et les Naskapis du Québec</span></a>
</li>
<li><span class='sectionRange'>91 à 95 - </span><a href="page-1.html#h-349721"><span class="HTitleText1">Code criminel</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-1.html#h-349723"><span class="HTitleText1">Loi sur les douanes</span></a>
</li>
<li><span class='sectionRange'>97 et 98 - </span><a href="page-1.html#h-349725"><span class="HTitleText1">Loi sur la continuation de la pension des services de défense</span></a>
</li>
<li><span class='sectionRange'>99 à 105 - </span><a href="page-1.html#h-349727"><span class="HTitleText1">Loi sur la pension spéciale du service diplomatique</span></a>
</li>
<li><span class='sectionRange'>106 à 109 - </span><a href="page-1.html#h-349729"><span class="HTitleText1">Loi sur l’assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="page-1.html#h-349731"><span class="HTitleText1">Loi sur les biens en déshérence</span></a>
</li>
<li><span class='sectionRange'>111 à 114 - </span><a href="page-1.html#h-349733"><span class="HTitleText1">Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-1.html#h-349735"><span class="HTitleText1">Loi d’aide à l’exécution des ordonnances et des ententes familiales</span></a>
</li>
<li><span class='sectionRange'>116 à 118 - </span><a href="page-1.html#h-349737"><span class="HTitleText1">Loi sur les armes à feu</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="page-1.html#h-349739"><span class="HTitleText1">Loi sur les missions étrangères et les organisations internationales</span></a>
</li>
<li><span class='sectionRange'>120 et 121 - </span><a href="page-1.html#h-349741"><span class="HTitleText1">Loi sur la saisie-arrêt et la distraction de pensions</span></a>
</li>
<li><span class='sectionRange'>122 et 123 - </span><a href="page-1.html#h-349743"><span class="HTitleText1">Loi relative aux rentes sur l’État</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="page-1.html#h-349745"><span class="HTitleText1">Loi sur le fonctionnement des sociétés du secteur public</span></a>
</li>
<li><span class='sectionRange'>125 et 126 - </span><a href="page-1.html#h-349747"><span class="HTitleText1">Loi sur l’indemnisation des agents de l’État</span></a>
</li>
<li><span class='sectionRange'>127 à 129 - </span><a href="page-1.html#h-349749"><span class="HTitleText1">Loi sur le gouverneur général</span></a>
</li>
<li><span class='sectionRange'>130 à 146 - </span><a href="page-1.html#h-349751"><span class="HTitleText1">Loi de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-1.html#h-349753"><span class="HTitleText1">Règles concernant l’application de l’impôt sur le revenu</span></a>
</li>
<li><span class='sectionRange'>148 à 152 - </span><a href="page-1.html#h-349755"><span class="HTitleText1">Loi sur les indiens</span></a>
</li>
<li><span class='sectionRange'>153 à 158 - </span><a href="page-1.html#h-349757"><span class="HTitleText1">Loi sur les sociétés d’assurances</span></a>
</li>
<li><span class='sectionRange'>159 à 169 - </span><a href="page-1.html#h-349759"><span class="HTitleText1">Loi sur les juges</span></a>
</li>
<li><span class='sectionRange'>170 à 175 - </span><a href="page-1.html#h-349761"><span class="HTitleText1">Loi sur la pension de retraite des lieutenants-gouverneurs</span></a>
</li>
<li><span class='sectionRange'>176 à 186 - </span><a href="page-1.html#h-349763"><span class="HTitleText1">Loi sur les allocations de retraite des parlementaires</span></a>
</li>
<li><span class='sectionRange'>187 à 191 - </span><a href="page-1.html#h-349765"><span class="HTitleText1">Loi sur l’indemnisation des marins marchands</span></a>
</li>
<li><span class='sectionRange'>192 à 209 - </span><a href="page-1.html#h-349767"><span class="HTitleText1">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="page-1.html#h-349769"><span class="HTitleText1">Loi sur le Parlement du Canada</span></a>
</li>
<li><span class='sectionRange'>211 à 221 - </span><a href="page-1.html#h-349771"><span class="HTitleText1">Loi sur les pensions</span></a>
</li>
<li><span class='sectionRange'>243 à 253 - </span><a href="page-1.html#h-349775"><span class="HTitleText1">Loi sur le partage des prestations de retraite</span></a>
</li>
<li><span class='sectionRange'>254 à 264 - </span><a href="page-1.html#h-349777"><span class="HTitleText1">Loi de 1985 sur les normes de prestation de pension</span></a>
</li>
<li><span class='sectionRange'>265 à 270 - </span><a href="page-1.html#h-349779"><span class="HTitleText1">Loi sur les sociétés de caisse de retraite</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-1.html#h-349781"><span class="HTitleText1">Loi sur les rapports relatifs aux pensions publiques</span></a>
</li>
<li><span class='sectionRange'>272 à 274 - </span><a href="page-1.html#h-349783"><span class="HTitleText1">Loi sur l’emploi dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>275 à 277 - </span><a href="page-1.html#h-349785"><span class="HTitleText1">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>278 à 284 - </span><a href="page-1.html#h-349787"><span class="HTitleText1">Loi de l’assurance des soldats de retour</span></a>
</li>
<li><span class='sectionRange'>285 à 287 - </span><a href="page-1.html#h-349789"><span class="HTitleText1">Loi sur la continuation des pensions de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>288 à 290 - </span><a href="page-1.html#h-349791"><span class="HTitleText1">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="page-1.html#h-349793"><span class="HTitleText1">Loi sur les mesures spéciales d’importation</span></a>
</li>
<li><span class='sectionRange'>292 à 294 - </span><a href="page-1.html#h-349795"><span class="HTitleText1">Loi sur les régimes de retraite particuliers</span></a>
</li>
<li><span class='sectionRange'>295 et 296 - </span><a href="page-1.html#h-349797"><span class="HTitleText1">Loi sur les prestations de retraite supplémentaires</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-1.html#h-349799"><span class="HTitleText1">Loi sur les syndicats ouvriers</span></a>
</li>
<li><span class='sectionRange'>298 à 302 - </span><a href="page-1.html#h-349801"><span class="HTitleText1">Loi sur les sociétés de fiducie et de prêt</span></a>
</li>
<li><span class='sectionRange'>303 à 310 - </span><a href="page-1.html#h-349803"><span class="HTitleText1">Loi sur l’assurance des anciens combattants</span></a>
</li>
<li><span class='sectionRange'>311 à 314 - </span><a href="page-1.html#h-349805"><span class="HTitleText1">Loi sur les terres destinées aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="page-1.html#h-349807"><span class="HTitleText1">Loi sur le tribunal des anciens combattants (révision et appel)</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="page-1.html#h-349809"><span class="HTitleText1">Loi sur les forces étrangères présentes au Canada</span></a>
</li>
<li><span class='sectionRange'>317 à 339 - </span><a href="page-1.html#h-349811"><span class="HTitleText1">Loi sur les allocations aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="page-1.html#h-349813"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-2.html#h-349820"><span class="scheduleLabel">ANNEXES 1 ET 2</span></a>
</li></ul>
</li></ul>

</nav>

