<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la concurrence</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Objet et définitions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1.1 - </span><a href="#h-3"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText2">Définitions</span></a>
</li></ul>
</li><li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-6"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Entraide juridique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-7"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>30.01 - </span><a href="#h-8"><span class="HTitleText2">Rôle du ministre de la Justice</span></a>
</li>
<li><span class='sectionRange'>30.02 - </span><a href="#h-9"><span class="HTitleText2">Publication des accords</span></a>
</li>
<li><span class='sectionRange'>30.03 - </span><a href="#h-10"><span class="HTitleText2">Demandes présentées par un État étranger</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30.03 - </span><a href="#h-11"><span class="HTitleText3">Demandes</span></a>
</li>
<li><span class='sectionRange'>30.04 - </span><a href="#h-12"><span class="HTitleText3">Perquisitions et saisies</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-13"><span class="HTitleText3">Éléments de preuve destinés à l’étranger</span></a>
</li>
<li><span class='sectionRange'>30.19 - </span><a href="#h-14"><span class="HTitleText3">Prêt de pièces</span></a>
</li>
<li><span class='sectionRange'>30.24 - </span><a href="#h-15"><span class="HTitleText3">Appel</span></a>
</li></ul>
</li><li><span class='sectionRange'>30.25 - </span><a href="#h-16"><span class="HTitleText2">Demandes présentées par le Canada</span></a>
</li>
<li><span class='sectionRange'>30.29 - </span><a href="#h-17"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-18"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Recours spéciaux</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-19"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">[Abrogée, L.R. (1985), ch. 19 (2e suppl.), art. 29]</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-20"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Infractions relatives à la concurrence</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-21"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Autres infractions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-22"><span class="HTitleText2">Infractions</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-23"><span class="HTitleText2">Procédure</span></a>
</li></ul>
</li><li><span class='sectionRange'>74.01 - </span><a href="#h-24"><span class="HLabel1">PARTIE VII.1</span> - <span class="HTitleText1">Pratiques commerciales trompeuses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>74.01 - </span><a href="#h-25"><span class="HTitleText2">Comportement susceptible d’examen</span></a>
</li>
<li><span class='sectionRange'>74.09 - </span><a href="#h-26"><span class="HTitleText2">Recours administratifs</span></a>
</li>
<li><span class='sectionRange'>74.17 - </span><a href="#h-27"><span class="HTitleText2">Règles de procédure</span></a>
</li>
<li><span class='sectionRange'>74.18 - </span><a href="#h-28"><span class="HTitleText2">Appels</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-29"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Affaires que le Tribunal peut examiner</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-30"><span class="HTitleText2">Pratiques restrictives du commerce</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-31"><span class="HTitleText3">Refus de vendre</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-32"><span class="HTitleText3">Maintien des prix</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-33"><span class="HTitleText3">Exclusivité, ventes liées et limitation du marché</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-34"><span class="HTitleText3">Abus de position dominante</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-35"><span class="HTitleText3">Prix à la livraison</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-36"><span class="HTitleText3">Jugements et droit étrangers</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-37"><span class="HTitleText3">Fournisseurs étrangers</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-38"><span class="HTitleText2">Accords de spécialisation</span></a>
</li>
<li><span class='sectionRange'>90.1 - </span><a href="#h-39"><span class="HTitleText2">Accords ou arrangements empêchant ou diminuant sensiblement la concurrence</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-40"><span class="HTitleText2">Fusionnements</span></a>
</li>
<li><span class='sectionRange'>103.1 - </span><a href="#h-41"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>108 - </span><a href="#h-42"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Transactions devant faire l’objet d’un avis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-43"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-44"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-45"><span class="HTitleText2">Exceptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-46"><span class="HTitleText3">Acquisition d’actions comportant droit de vote, d’éléments d’actif ou de titres de participation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-47"><span class="HTitleText3">Association d’intérêts</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-48"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>114 - </span><a href="#h-49"><span class="HTitleText2">Avis et renseignements</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-50"><span class="HTitleText2">Parachèvement des transactions proposées</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-51"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>124.1 - </span><a href="#h-52"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124.1 - </span><a href="#h-53"><span class="HTitleText2">Avis du commissaire</span></a>
</li>
<li><span class='sectionRange'>124.2 - </span><a href="#h-54"><span class="HTitleText2">Renvois</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-55"><span class="HTitleText2">Observations aux offices fédéraux, commissions et autres tribunaux</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-56"><span class="HTitleText2">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-57"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
