<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la stratégie nationale sur le logement</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1155356"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1155359"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1155362"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1155365"><span class="HTitleText1">Politique en matière de logement</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1155372"><span class="HTitleText1">Stratégie nationale sur le logement</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1155382"><span class="HTitleText1">Conseil national du logement</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-1155434"><span class="HTitleText1">Défenseur fédéral du logement</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-1155487"><span class="HTitleText1">Commissions d’examen</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1155506"><span class="HTitleText1">Obligation de rendre compte</span></a>
</li></ul>
</li></ul>

</nav>

