<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi d’exécution du budget de 1997</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-34264"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-34267"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Fondation canadienne pour l’innovation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-34268"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-34296"><span class="HTitleText2">Constitution de la fondation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-34342"><span class="HTitleText2">Administrateurs</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-34394"><span class="HTitleText2">Membres</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-34443"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-34455"><span class="HTitleText2">Opérations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-34502"><span class="HTitleText2">Considérations financières et vérification</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-2.html#h-34546"><span class="HTitleText2">Rapports et examen des rapports</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-34562"><span class="HTitleText2">Liquidation</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-3.html#h-34570"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="page-3.html#h-34579"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Taxe sur le tabac des tribus Cowichan</span></a>
</li>
<li><span class='sectionRange'>59 à 79 - </span><a href="page-3.html#h-34679"><span class="HLabel1">PARTIES III ET IV</span> - <span class="HTitleText1">[Abrogées, 2000, ch. 14, art. 30]</span></a>
</li>
<li><span class='sectionRange'>59 à 79 - </span><a href="page-3.html#h-34680"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Produits du tabac</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-3.html#h-34682"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Prestation fiscale pour enfants</span></a>
</li>
<li><span class='sectionRange'>81 à 86 - </span><a href="page-3.html#h-34684"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Remise de la taxe sur le carburant aviation</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-3.html#h-34686"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Mesure du volume de combustible</span></a>
</li>
<li><span class='sectionRange'>88 à 91 - </span><a href="page-3.html#h-34688"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Assurance-emploi</span></a>
</li>
<li><span class='sectionRange'>92 et 93 - </span><a href="page-3.html#h-34690"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Modifications apportées à d’autres lois</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-3.html#h-34692"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Paiement à la Fondation canadienne pour l’innovation</span></a>
</li></ul>
</li></ul>

</nav>

