<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canadian Bill of Rights</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-61447"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Bill of Rights</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-61477"><span class="HTitleText1">Part II</span></a>
</li></ul>
</li></ul>

</nav>

