<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le Centre canadien de lutte contre les toxicomanies</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-60219"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-60222"><span class="HTitleText1">Constitution</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-60225"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-60233"><span class="HTitleText1">Capacité et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-60247"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-60273"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-60296"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-60305"><span class="HTitleText1">Rémunération et indemnités</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-60317"><span class="HTitleText1">Comités</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-60320"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-60328"><span class="HTitleText1">Statut du centre</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-1.html#h-60339"><span class="HTitleText1">Exercice et vérification</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-1.html#h-60344"><span class="HTitleText1">Rapport</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-1.html#h-60354"><span class="HTitleText1">Examen</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-60359"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

