<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Prince Rupert Grain Handling Operations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-396781"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-396784"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-396795"><span class="HTitleText1">Grain Handling Operations</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-396824"><span class="HTitleText1">Arbitration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-396836"><span class="HTitleText1">Amendment of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-396839"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-396849"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
