<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Sports of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-363929"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-363932"><span class="HTitleText1">National Sports of Canada</span></a>
</li></ul>
</li></ul>

</nav>

