<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Banque de développement du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-39268"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-39271"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-39294"><span class="HTitleText1">Constitution et organisation de la banque</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-39295"><span class="HTitleText2">Qualité de la Banque</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-39305"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-39311"><span class="HTitleText2">Conseil</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-39352"><span class="HTitleText2">Dirigeants et personnel</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-39374"><span class="HTitleText2">Rémunération et avantages</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-39388"><span class="HTitleText1">Pouvoirs spécifiques de la banque</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-39389"><span class="HTitleText2">Services financiers</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-39456"><span class="HTitleText2">Services de gestion</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-39469"><span class="HTitleText2">Opérations de trésorerie</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-39489"><span class="HTitleText2">Accords et programmes</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-39496"><span class="HTitleText2">Pouvoirs subsidiaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-39507"><span class="HTitleText1">Capital de la banque</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-39564"><span class="HTitleText1">Rapport dettes-capitaux propres</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-39578"><span class="HTitleText1">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-39605"><span class="HTitleText1">Matières diverses</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-39640"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-39642"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>44 à 55 - </span><a href="#h-39661"><span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><a href="#h-39664"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
