<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Geneva Conventions Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Conventions Approved</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Grave Breaches</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Legal Proceedings in Respect of Protected Persons</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-248082"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-248422"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="#h-248739"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li>
<li><a href="#h-249552"><span class="scheduleLabel">SCHEDULE IV</span> </a>
</li>
<li><a href="#h-250365"><span class="scheduleLabel">SCHEDULE V</span> <span class="scheduleTitleText"> - Protocol I</span> - <span class="scheduleTitleText"> - Protocol Additional to the Geneva Conventions of 12 August 1949, and Relating to the Protection of Victims of International Armed Conflicts (Protocol I)</span></a>
</li>
<li><a href="#h-251299"><span class="scheduleLabel">SCHEDULE VI</span> <span class="scheduleTitleText"> - Protocol II</span> - <span class="scheduleTitleText"> - Protocol Additional to the Geneva Conventions of 12 August 1949, and Relating to the Protection of Victims of Non-International Armed Conflicts (Protocol II)</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
