<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada-Newfoundland Atlantic Accord Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">Prescribing Limits of Offshore Area and Settlement Procedure for Disputes</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">Condition Precedent for Certain Regulations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Joint Management</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Establishment of Board</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText2">Functions of Board</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-10"><span class="HTitleText2">Decisions in Relation to Offshore Management</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-11"><span class="HTitleText2">Regional Security of Supply</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-12"><span class="HTitleText2">Ministerial Directives</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-13"><span class="HTitleText2">Plan for interests</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-14"><span class="HTitleText2">Public Review</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-15"><span class="HTitleText2">Canada-Newfoundland Benefits Plan</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-16"><span class="HTitleText2">Coordination of Government Departments and Agencies</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-17"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Petroleum Resources</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-18"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-19"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-20"><span class="HTitleText3">Manner of Giving Notices</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-21"><span class="HTitleText3">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-22"><span class="HTitleText3">Designations and Appointments</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-23"><span class="HTitleText3">General Rules Respecting Interests</span></a>
</li></ul>
</li><li><span class='sectionRange'>57 - </span><a href="#h-24"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">General Rules Relating to Issuance of Interests</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>57 - </span><a href="#h-25"><span class="HTitleText3">Authority to Issue Interests</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-26"><span class="HTitleText3">Issuance of Interests in Relation to Crown Reserve Areas</span></a>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-27"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Exploration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-28"><span class="HTitleText3">Exploration Licences</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-29"><span class="HTitleText3">Significant Discoveries</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-30"><span class="HTitleText3">Significant Discovery Licences</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-31"><span class="HTitleText3">Drilling Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-32"><span class="HLabel2">DIVISION IV</span> - <span class="HTitleText2">Production</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-33"><span class="HTitleText3">Commercial Discoveries</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-34"><span class="HTitleText3">Development Orders</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-35"><span class="HTitleText3">Issuance of Production Licences</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-36"><span class="HTitleText3">Subsurface Storage Licences</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-37"><span class="HTitleText3">Qualification for Production Licence</span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="#h-38"><span class="HLabel2">DIVISION V</span> - <span class="HTitleText2">[Repealed, 1993, c. 47, s. 8]</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-39"><span class="HLabel2">DIVISION VI</span> - <span class="HTitleText2">Royalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>97 - </span><a href="#h-40"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-41"><span class="HTitleText3">Liability and Collection of Royalties</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-42"><span class="HLabel2">DIVISION VII</span> - <span class="HTitleText2">Environmental Studies Revolving Funds</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-43"><span class="HLabel2">DIVISION VIII</span> - <span class="HTitleText2">Transfers, Assignments and Registration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-44"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-45"><span class="HTitleText3">Transfer and Assignment</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-46"><span class="HTitleText3">Registration</span></a>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="#h-47"><span class="HLabel2">DIVISION IX</span> - <span class="HTitleText2">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>119 - </span><a href="#h-48"><span class="HTitleText3">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-49"><span class="HTitleText3">Arbitration</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-50"><span class="HTitleText3">Cancellation of Rights</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-51"><span class="HTitleText3">Hearings and Judicial Review</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-52"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-53"><span class="HLabel2">DIVISION X</span> - <span class="HTitleText2">Transitional, Consequential and Commencement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-54"><span class="HTitleText3">Transitional</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>135 - </span><a href="#h-55"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Petroleum Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-56"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-57"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-58"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>136.1 - </span><a href="#h-59"><span class="HTitleText2">Oil and Gas Administration Advisory Council</span></a>
</li>
<li><span class='sectionRange'>136.2 - </span><a href="#h-60"><span class="HTitleText2">Offshore Oil and Gas Training Standards Advisory Board</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-61"><span class="HTitleText2">Prohibition</span></a>
</li>
<li><span class='sectionRange'>137.1 - </span><a href="#h-62"><span class="HTitleText2">Delegation</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-63"><span class="HTitleText2">Licences and Authorizations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-64"><span class="HTitleText3">Operating Licences and Authorization for Work</span></a>
</li>
<li><span class='sectionRange'>138.2 - </span><a href="#h-65"><span class="HTitleText3">Safety of Works and Activities</span></a>
</li>
<li><span class='sectionRange'>138.3 - </span><a href="#h-66"><span class="HTitleText3">Financial Responsibility</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-67"><span class="HTitleText3">Development Plan Approval</span></a>
</li>
<li><span class='sectionRange'>139.1 - </span><a href="#h-68"><span class="HTitleText3">Declarations</span></a>
</li>
<li><span class='sectionRange'>139.2 - </span><a href="#h-69"><span class="HTitleText3">Certificates</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-70"><span class="HTitleText2">Chief Safety Officer and Chief Conservation Officer</span></a>
</li>
<li><span class='sectionRange'>140.1 - </span><a href="#h-71"><span class="HTitleText2">Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>140.2 - </span><a href="#h-72"><span class="HTitleText2">Extended Formation Flow Tests</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-73"><span class="HTitleText2">Oil and Gas Committee</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-74"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-75"><span class="HTitleText3">Jurisdiction and Powers</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-76"><span class="HTitleText3">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>149 - </span><a href="#h-77"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Regulation of Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="#h-78"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-79"><span class="HTitleText3">Production Orders</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-80"><span class="HTitleText3">Waste</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-81"><span class="HTitleText3">Spills and Debris</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-82"><span class="HTitleText3">Inquiries</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-83"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">Production Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="#h-84"><span class="HTitleText3">Pooling</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-85"><span class="HTitleText3">Unitization</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-86"><span class="HTitleText3">Compulsory Unitization</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-87"><span class="HTitleText3">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>184 - </span><a href="#h-88"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Appeals and Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>184 - </span><a href="#h-89"><span class="HTitleText3">Appeals</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-90"><span class="HTitleText3">Safety and Conservation Officers</span></a>
</li>
<li><span class='sectionRange'>193.2 - </span><a href="#h-91"><span class="HTitleText3">Installation Manager</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-92"><span class="HTitleText3">Offences and Penalties</span></a>
</li></ul>
</li><li><span class='sectionRange'>203 - </span><a href="#h-93"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-94"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-95"><span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-96"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Revenue Sharing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-97"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-98"><span class="HTitleText2">Imposition of Consumption Taxes</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-99"><span class="HTitleText2">Imposition of Insurance Companies Tax</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-100"><span class="HTitleText2">Tax Administration Agreement</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-101"><span class="HTitleText2">Imposition of Corporate Income Taxes</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-102"><span class="HTitleText2">Liability and Collection of Tax</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-103"><span class="HTitleText2">Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-104"><span class="HTitleText2">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-105"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-106"><span class="HTitleText2">Appropriation</span></a>
</li></ul>
</li><li><span class='sectionRange'>218 - </span><a href="#h-107"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Fiscal Equalization Offset Payments and Determination of Per Capita Fiscal Capacity</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>218 - </span><a href="#h-108"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-109"><span class="HTitleText2">Fiscal Equalization Offset Payments</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-110"><span class="HTitleText2">Determination of Per Capita Fiscal Capacity</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-111"><span class="HTitleText2">Determinations</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-112"><span class="HTitleText2">Advance Payments</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-113"><span class="HTitleText2">Appropriation</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-114"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-115"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>228 - </span><a href="#h-116"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Offshore Development Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="#h-117"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-118"><span class="HTitleText2">Development Fund</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-119"><span class="HTitleText2">Agreement with Provincial Government</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-120"><span class="HTitleText2">Payments</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-121"><span class="HTitleText2">Development Fund Committee</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-122"><span class="HTitleText2">Appropriation</span></a>
</li></ul>
</li><li><span class='sectionRange'>234 and 235 - </span><a href="#h-123"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Corporate Income Tax</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-124"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Transitional, Consequential and Commencement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>236 - </span><a href="#h-125"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>237 and 238 - </span><a href="#h-126"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-127"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
