<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les sanctions administratives pécuniaires en matière d’agriculture et d’agroalimentaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-9551"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-9554"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-9567"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-9570"><span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-9602"><span class="HTitleText1">Ouverture de la poursuite</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9612"><span class="HTitleText1">Avertissements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9618"><span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-9629"><span class="HTitleText1">Transactions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9652"><span class="HTitleText1">Contestation devant le ministre</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9663"><span class="HTitleText1">Révision par la Commission</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9669"><span class="HTitleText1">Exécution des sanctions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9690"><span class="HTitleText1">Règles spécifiques aux violations</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-9709"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-9723"><span class="HTitleText1">Commission de révision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-1098844"><span class="HTitleText2">Composition</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-1098888"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-1098897"><span class="HTitleText2">Indemnités et frais</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-1098916"><span class="HTitleText2">Siège</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-1098925"><span class="HTitleText2">Compétence</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-1098949"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-1098961"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-1098970"><span class="HTitleText2">Généralités</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

