<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Anthem Act</a><ul class="TocIndent"><li><a href="page-2.html#h-364102"><span class="scheduleLabel">SCHEDULE / <span class="otherLang" lang="fr">ANNEXE</span></span> )</span> - <span class="scheduleTitleText"> - National Anthem — <span class="otherLang" lang="fr">Hymne national</span></span> - <span class="scheduleTitleText"> - O Canada</span></a>
</li></ul>
</li></ul>

</nav>

