<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant un décret pris au titre de la Loi d’aide au développement international (institutions financières)</a></li></ul>

</nav>
</div></section>
