<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Service Labour Relations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Labour Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Employee Freedoms</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Management Rights</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Consultation Committees and Co-Development</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Public Service Labour Relations and Employment Board</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-9"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Bargaining Rights</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-10"><span class="HTitleText3">Certification of Bargaining Agents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-11"><span class="HTitleText4">Application for Certification</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-12"><span class="HTitleText4">Determination of Appropriate Bargaining Units</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-13"><span class="HTitleText4">Managerial or Confidential Positions</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-14"><span class="HTitleText4">Certification</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-15"><span class="HTitleText4">Where Certification Prohibited</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-16"><span class="HTitleText4">Effect of Certification</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-17"><span class="HTitleText3">Changes to Certification</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="#h-18"><span class="HTitleText4">Review of Bargaining Units</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-19"><span class="HTitleText4">Managerial or Confidential Positions</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-20"><span class="HTitleText3">Successor Rights and Obligations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-21"><span class="HTitleText3">Revocation of Certification</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-22"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2">Process for Dispute Resolution</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-23"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2">Collective Bargaining and Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>105 - </span><a href="#h-24"><span class="HTitleText3">Negotiation of Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>105 - </span><a href="#h-25"><span class="HTitleText4">Notice to Bargain Collectively</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-26"><span class="HTitleText4">Effect of Notice</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-27"><span class="HTitleText4">Mediation</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-28"><span class="HTitleText4">Collective Bargaining for Two or More Units</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-29"><span class="HTitleText4">Two-tier Bargaining</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-30"><span class="HTitleText3">Collective Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-31"><span class="HTitleText4">Authority to Enter into Agreement</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-32"><span class="HTitleText4">Restriction on Content of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-33"><span class="HTitleText4">Duration and Effect</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-34"><span class="HTitleText4">Amendments</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>119 - </span><a href="#h-35"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Essential Services</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-36"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Arbitration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>135 - </span><a href="#h-37"><span class="HTitleText3">Application of Division</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-38"><span class="HTitleText3">Request for Arbitration</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-39"><span class="HTitleText3">Establishment of Arbitration Board</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-40"><span class="HTitleText3">Referral to Arbitration</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-41"><span class="HTitleText3">Duty and Powers</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-42"><span class="HTitleText3">Making of Arbitral Award</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-43"><span class="HTitleText3">Duration and Operation of Arbitral Award</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-44"><span class="HTitleText3">Implementation</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-45"><span class="HTitleText3">Matters Not Dealt With</span></a>
</li>
<li><span class='sectionRange'>158.1 - </span><a href="#h-46"><span class="HTitleText3">Review</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-47"><span class="HTitleText3">Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>160 - </span><a href="#h-48"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2">Conciliation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>160 - </span><a href="#h-49"><span class="HTitleText3">Application of Division</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-50"><span class="HTitleText3">Request for Conciliation</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-51"><span class="HTitleText3">Establishment of Public Interest Commission</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-52"><span class="HTitleText3">Powers and Functions</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-53"><span class="HTitleText3">Report</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-54"><span class="HTitleText3">Alternate Dispute Resolution Process</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-55"><span class="HTitleText3">Vote on Employer’s Offer</span></a>
</li></ul>
</li><li><span class='sectionRange'>184 - </span><a href="#h-56"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2">Strike Votes</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-57"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2">Unfair Labour Practices</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-58"><span class="HLabel2">DIVISION 13</span> - <span class="HTitleText2">Complaints</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-59"><span class="HLabel2">DIVISION 14</span> - <span class="HTitleText2">Prohibitions and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>193 - </span><a href="#h-60"><span class="HTitleText3">Acts of Officers and Representatives of Employee Organizations</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-61"><span class="HTitleText3">Prohibitions Relating to Strikes</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-62"><span class="HTitleText3">Declarations and Orders Relating to Strikes</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-63"><span class="HTitleText3">Prohibition Relating to Essential Services</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-64"><span class="HTitleText3">Offences and Punishment</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-65"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-66"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-67"><span class="HTitleText2">Conflict Management</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-68"><span class="HTitleText2">Individual Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>208 - </span><a href="#h-69"><span class="HTitleText3">Presentation</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-70"><span class="HTitleText3">Reference to Adjudication</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-71"><span class="HTitleText3">Representation</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-72"><span class="HTitleText3">Binding Effect</span></a>
</li></ul>
</li><li><span class='sectionRange'>215 - </span><a href="#h-73"><span class="HTitleText2">Group Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>215 - </span><a href="#h-74"><span class="HTitleText3">Presentation</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-75"><span class="HTitleText3">Reference to Adjudication</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="#h-76"><span class="HTitleText3">Withdrawal from Group Grievance</span></a>
</li></ul>
</li><li><span class='sectionRange'>220 - </span><a href="#h-77"><span class="HTitleText2">Policy Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-78"><span class="HTitleText3">Presentation</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-79"><span class="HTitleText3">Reference to Adjudication</span></a>
</li></ul>
</li><li><span class='sectionRange'>223 - </span><a href="#h-80"><span class="HTitleText2">Adjudication</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>223 - </span><a href="#h-81"><span class="HTitleText3">Notice to Board</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-82"><span class="HTitleText3">Board of Adjudication</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-83"><span class="HTitleText3">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-84"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-85"><span class="HTitleText3">Decision</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-86"><span class="HTitleText3">Expenses of Adjudication</span></a>
</li></ul>
</li><li><span class='sectionRange'>236 - </span><a href="#h-87"><span class="HTitleText2">No Right of Action</span></a>
</li>
<li><span class='sectionRange'>237 - </span><a href="#h-88"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>239 - </span><a href="#h-89"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Occupational Health and Safety</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>239 - </span><a href="#h-90"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-91"><span class="HTitleText2">Part II of Canada Labour Code</span></a>
</li></ul>
</li><li><span class='sectionRange'>241 - </span><a href="#h-92"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>241 - </span><a href="#h-93"><span class="HTitleText2">Defects in Proceedings</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-94"><span class="HTitleText2">Restriction on Admissibility of Evidence</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="#h-95"><span class="HTitleText2">Protection</span></a>
</li>
<li><span class='sectionRange'>246 - </span><a href="#h-96"><span class="HTitleText2">Oaths and Solemn Affirmations</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-97"><span class="HTitleText2">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-98"><span class="HTitleText2">Witness Fees</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-99"><span class="HTitleText2">Provision of Facilities and Human Resources</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="#h-100"><span class="HTitleText2">Application of Safety or Security Provisions</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-101"><span class="HTitleText2">Five-year Review</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
