<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Protecting Air Service Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-400416"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-400419"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-400427"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Technical, Maintenance and Operational Support Employees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-400428"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-400435"><span class="HTitleText2">Air Service Operations</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-400453"><span class="HTitleText2">Extension of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-400464"><span class="HTitleText2">Final Offer Selection</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-400498"><span class="HTitleText2">New Collective Agreement</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="page-1.html#h-400506"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Pilots</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-1.html#h-400507"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-400514"><span class="HTitleText2">Air Service Operations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-400532"><span class="HTitleText2">Extension of Collective Agreement</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-400543"><span class="HTitleText2">Final Offer Selection</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-400577"><span class="HTitleText2">New Collective Agreement</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="page-2.html#h-400585"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="page-2.html#h-400586"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-400589"><span class="HTitleText2">Enforcement</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="page-2.html#h-400603"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

