<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Court Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">The Court</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">The Judges</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText1">Barristers, Advocates, Attorneys and Solicitors</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText1">Prothonotaries</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText1">Sheriffs and Marshals</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText1">Administration of Court</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText1">Organization of Work</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText1">Jurisdiction of Trial Division</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-11"><span class="HTitleText1">Jurisdiction of Federal Court of Appeal</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-12"><span class="HTitleText1">Substantive Provisions</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-13"><span class="HTitleText1">Procedure</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-14"><span class="HTitleText1">Judgments of Court of Appeal</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-15"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-16"><span class="HTitleText1">Process</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-17"><span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-18"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
