<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Wage Earner Protection Program Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-464276"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-464279"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-464307"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-464310"><span class="HTitleText1">Program Established</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-464313"><span class="HTitleText1">Eligibility for Payments</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-464333"><span class="HTitleText1">Amounts Covered by Program</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-464341"><span class="HTitleText1">Application for Payment</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-464357"><span class="HTitleText1">Review by Minister</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-464374"><span class="HTitleText1">Appeal to Adjudicator</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-464401"><span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-464402"><span class="HTitleText2">Duties of Trustees and Receivers</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-464429"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-464494"><span class="HTitleText2">Overpayments</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-464564"><span class="HTitleText2">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-464593"><span class="HTitleText2">Offences and Penalties</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-464621"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-464638"><span class="HTitleText1">Review of Act</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
