<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des renseignements personnels</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-4"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText1">Collecte, conservation et retrait des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText1">Fichiers de renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText1">Répertoire de renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText1">Accès aux renseignements personnels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Droit d’accès</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-11"><span class="HTitleText2">Demandes de communication</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText2">Exercice de l’accès</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText1">Exceptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-14"><span class="HTitleText2">Fichiers inconsultables</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-15"><span class="HTitleText2">Responsabilités de l’État</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText2">Secret professionnel des avocats</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText2">Dossiers médicaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-19"><span class="HTitleText1">Plaintes</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-20"><span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-21"><span class="HTitleText1">Examen des fichiers inconsultables</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-22"><span class="HTitleText1">Contrôle d’application des articles 4 à 8</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-23"><span class="HTitleText1">Rapports au Parlement</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-24"><span class="HTitleText1">Révision par la Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-25"><span class="HTitleText1">Commissariat à la protection de la vie privée</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-26"><span class="HTitleText2">Commissaire à la protection de la vie privée</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-27"><span class="HTitleText2">Commissaires adjoints à la protection de la vie privée</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-28"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-29"><span class="HTitleText2">Délégation</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-30"><span class="HTitleText2">Études spéciales</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-31"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>68 - </span><a href="#h-32"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-33"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-34"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Institutions fédérales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
