<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Prairie Grain Advance Payments Act <span class='Repealed'>[Repealed, 2011, c. 25, s. 37]</span></a></li></ul>
</nav>
</div></section>
