<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les banques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Définitions et application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-4"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Constitution et prorogation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText2">Formalités constitutives</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-9"><span class="HTitleText2">Prorogation</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-10"><span class="HTitleText2">Cessation</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-11"><span class="HTitleText2">Dénomination sociale</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-12"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Organisation et fonctionnement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-13"><span class="HTitleText2">Réunions</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-14"><span class="HTitleText2">Fonctionnement initial</span></a>
</li></ul>
</li><li><span class='sectionRange'>59 - </span><a href="#h-15"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Structure du capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-16"><span class="HTitleText2">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-17"><span class="HTitleText2">Titres secondaires</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-18"><span class="HTitleText2">Certificats de valeurs mobilières et transferts</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-19"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Administration de la banque</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-20"><span class="HTitleText2">Actionnaires</span></a>
</li>
<li><span class='sectionRange'>156.01 - </span><a href="#h-21"><span class="HTitleText2">Procurations</span></a>
</li>
<li><span class='sectionRange'>156.09 - </span><a href="#h-22"><span class="HTitleText2">Restriction du droit de vote</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-23"><span class="HTitleText2">Administrateurs et dirigeants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>157 - </span><a href="#h-24"><span class="HTitleText3">Obligations</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-25"><span class="HTitleText3">Administrateurs — Nombre et qualités requises</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-26"><span class="HTitleText3">Administrateurs — Élections et fonctions</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-27"><span class="HTitleText3">Élections incomplètes et vacances d’administrateurs</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-28"><span class="HTitleText3">Réunions du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-29"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-30"><span class="HTitleText3">Comités du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-31"><span class="HTitleText3">Mandat des administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-32"><span class="HTitleText3">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-33"><span class="HTitleText3">Responsabilité, exonération et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>215 - </span><a href="#h-34"><span class="HTitleText2">Modifications de structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>215 - </span><a href="#h-35"><span class="HTitleText3">Modifications</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-36"><span class="HTitleText3">Fusion</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-37"><span class="HTitleText3">Ventes d’éléments d’actif</span></a>
</li></ul>
</li><li><span class='sectionRange'>237 - </span><a href="#h-38"><span class="HTitleText2">Livres et registres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>237 - </span><a href="#h-39"><span class="HTitleText3">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-40"><span class="HTitleText3">Registres des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-41"><span class="HTitleText3">Dénomination sociale et sceau</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-42"><span class="HTitleText3">Initiés</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="#h-43"><span class="HTitleText3">Rapport d’initié</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-44"><span class="HTitleText3">Opérations d’initiés</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-45"><span class="HTitleText3">Recours</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="#h-46"><span class="HTitleText3">Prospectus</span></a>
</li>
<li><span class='sectionRange'>275 - </span><a href="#h-47"><span class="HTitleText3">Transactions de fermeture et transactions d’éviction</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="#h-48"><span class="HTitleText3">Offres publiques d’achat</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-49"><span class="HTitleText3">Acte de fiducie</span></a>
</li></ul>
</li><li><span class='sectionRange'>307 - </span><a href="#h-50"><span class="HTitleText2">États financiers et vérificateurs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>307 - </span><a href="#h-51"><span class="HTitleText3">Rapport financier annuel</span></a>
</li>
<li><span class='sectionRange'>313 - </span><a href="#h-52"><span class="HTitleText3">Vérificateurs</span></a>
</li>
<li><span class='sectionRange'>334 - </span><a href="#h-53"><span class="HTitleText3">Recours judiciaires</span></a>
</li>
<li><span class='sectionRange'>339 - </span><a href="#h-54"><span class="HTitleText3">Liquidation et dissolution</span></a>
</li>
<li><span class='sectionRange'>342 - </span><a href="#h-55"><span class="HTitleText3">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>347 - </span><a href="#h-56"><span class="HTitleText3">Surveillance judiciaire</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-57"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>370 - </span><a href="#h-58"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>370 - </span><a href="#h-59"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="#h-60"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Propriété des banques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>372 - </span><a href="#h-61"><span class="HTitleText3">Restrictions à la propriété</span></a>
</li>
<li><span class='sectionRange'>395 - </span><a href="#h-62"><span class="HTitleText3">Procédure d’agrément</span></a>
</li></ul>
</li><li><span class='sectionRange'>402 - </span><a href="#h-63"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Arrêtés et ordonnances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>404 - </span><a href="#h-64"><span class="HTitleText3">Dispositions d’ordre général</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>409 - </span><a href="#h-65"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Activité et pouvoirs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>409 - </span><a href="#h-66"><span class="HTitleText2">Activités générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>425 - </span><a href="#h-67"><span class="HTitleText3">Sûreté particulière</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="#h-68"><span class="HTitleText3">Dépôts</span></a>
</li>
<li><span class='sectionRange'>438 - </span><a href="#h-69"><span class="HTitleText3">Soldes non réclamés</span></a>
</li>
<li><span class='sectionRange'>439.1 - </span><a href="#h-70"><span class="HTitleText3">Comptes</span></a>
</li>
<li><span class='sectionRange'>448.3 - </span><a href="#h-71"><span class="HTitleText3">Produits enregistrés</span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-72"><span class="HTitleText3">Coût d’emprunt</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="#h-73"><span class="HTitleText3">Réclamations</span></a>
</li></ul>
</li><li><span class='sectionRange'>457 - </span><a href="#h-74"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>464 - </span><a href="#h-75"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>464 - </span><a href="#h-76"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>465 - </span><a href="#h-77"><span class="HTitleText2">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-78"><span class="HTitleText2">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>471 - </span><a href="#h-79"><span class="HTitleText2">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>475 - </span><a href="#h-80"><span class="HTitleText2">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>476 - </span><a href="#h-81"><span class="HTitleText2">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>477 - </span><a href="#h-82"><span class="HTitleText2">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>478 - </span><a href="#h-83"><span class="HTitleText2">Limite globale</span></a>
</li>
<li><span class='sectionRange'>479 - </span><a href="#h-84"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>485 - </span><a href="#h-85"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Capital et liquidités</span></a>
</li>
<li><span class='sectionRange'>485.1 - </span><a href="#h-86"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Opérations avec apparentés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>485.1 - </span><a href="#h-87"><span class="HTitleText2">Interprétation et application</span></a>
</li>
<li><span class='sectionRange'>489 - </span><a href="#h-88"><span class="HTitleText2">Opérations interdites</span></a>
</li>
<li><span class='sectionRange'>490 - </span><a href="#h-89"><span class="HTitleText2">Opérations permises</span></a>
</li>
<li><span class='sectionRange'>501 - </span><a href="#h-90"><span class="HTitleText2">Restrictions applicables aux opérations permises</span></a>
</li>
<li><span class='sectionRange'>504 - </span><a href="#h-91"><span class="HTitleText2">Obligation d’information</span></a>
</li>
<li><span class='sectionRange'>506 - </span><a href="#h-92"><span class="HTitleText2">Recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>507 - </span><a href="#h-93"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Banques étrangères</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>507 - </span><a href="#h-94"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>510 - </span><a href="#h-95"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Interdictions générales et exceptions</span></a>
</li>
<li><span class='sectionRange'>522.04 - </span><a href="#h-96"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Absence d’établissement financier au Canada</span></a>
</li>
<li><span class='sectionRange'>522.07 - </span><a href="#h-97"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Établissement financier au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>522.07 - </span><a href="#h-98"><span class="HTitleText3">Placements</span></a>
</li>
<li><span class='sectionRange'>522.16 - </span><a href="#h-99"><span class="HTitleText3">Succursales</span></a>
</li></ul>
</li><li><span class='sectionRange'>522.2 - </span><a href="#h-100"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Agréments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>522.2 - </span><a href="#h-101"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>522.21 - </span><a href="#h-102"><span class="HTitleText3">Agrément relatif aux établissements financiers au Canada</span></a>
</li>
<li><span class='sectionRange'>522.22 - </span><a href="#h-103"><span class="HTitleText3">Agréments relatifs aux placements et aux activités</span></a>
</li></ul>
</li><li><span class='sectionRange'>522.23 - </span><a href="#h-104"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>522.28 - </span><a href="#h-105"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">[Abrogée, 2007, ch. 6, art. 72]</span></a>
</li>
<li><span class='sectionRange'>522.29 - </span><a href="#h-106"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>522.34 - </span><a href="#h-107"><span class="HLabel1">PARTIE XII.01</span> - <span class="HTitleText1">Non-application de la Loi sur investissement Canada</span></a>
</li>
<li><span class='sectionRange'>523 - </span><a href="#h-108"><span class="HLabel1">PARTIE XII.1</span> - <span class="HTitleText1">Banques étrangères autorisées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>523 - </span><a href="#h-109"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>524 - </span><a href="#h-110"><span class="HTitleText2">Formalités de l’autorisation</span></a>
</li>
<li><span class='sectionRange'>534 - </span><a href="#h-111"><span class="HTitleText2">Ordonnance d’agrément</span></a>
</li>
<li><span class='sectionRange'>535 - </span><a href="#h-112"><span class="HTitleText2">Bureau principal et dirigeant principal</span></a>
</li>
<li><span class='sectionRange'>537 - </span><a href="#h-113"><span class="HTitleText2">Transfert des dettes</span></a>
</li>
<li><span class='sectionRange'>538 - </span><a href="#h-114"><span class="HTitleText2">Activités et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>556 - </span><a href="#h-115"><span class="HTitleText2">Dépôts</span></a>
</li>
<li><span class='sectionRange'>557 - </span><a href="#h-116"><span class="HTitleText2">Soldes non réclamés</span></a>
</li>
<li><span class='sectionRange'>559 - </span><a href="#h-117"><span class="HTitleText2">Comptes</span></a>
</li>
<li><span class='sectionRange'>566.1 - </span><a href="#h-118"><span class="HTitleText2">Produits enregistrés</span></a>
</li>
<li><span class='sectionRange'>567 - </span><a href="#h-119"><span class="HTitleText2">Coût d’emprunt</span></a>
</li>
<li><span class='sectionRange'>573 - </span><a href="#h-120"><span class="HTitleText2">Réclamations</span></a>
</li>
<li><span class='sectionRange'>574.1 - </span><a href="#h-121"><span class="HTitleText2">Divers</span></a>
</li>
<li><span class='sectionRange'>582 - </span><a href="#h-122"><span class="HTitleText2">Dépôt obligatoire à titre de cautionnement</span></a>
</li>
<li><span class='sectionRange'>583 - </span><a href="#h-123"><span class="HTitleText2">Exercice</span></a>
</li>
<li><span class='sectionRange'>584 - </span><a href="#h-124"><span class="HTitleText2">Vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>584 - </span><a href="#h-125"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>585 - </span><a href="#h-126"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-127"><span class="HTitleText3">Examens et rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>597 - </span><a href="#h-128"><span class="HTitleText2">Documents</span></a>
</li>
<li><span class='sectionRange'>599 - </span><a href="#h-129"><span class="HTitleText2">Cessation des activités au Canada</span></a>
</li>
<li><span class='sectionRange'>600 - </span><a href="#h-130"><span class="HTitleText2">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>600 - </span><a href="#h-131"><span class="HTitleText3">Relevés</span></a>
</li>
<li><span class='sectionRange'>613 - </span><a href="#h-132"><span class="HTitleText3">Enquête sur les banques étrangères autorisées</span></a>
</li></ul>
</li><li><span class='sectionRange'>614.1 - </span><a href="#h-133"><span class="HTitleText2">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>614.1 - </span><a href="#h-134"><span class="HTitleText3">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>615 - </span><a href="#h-135"><span class="HTitleText3">Décisions</span></a>
</li>
<li><span class='sectionRange'>617 - </span><a href="#h-136"><span class="HTitleText3">Maintien de l’actif</span></a>
</li>
<li><span class='sectionRange'>617.1 - </span><a href="#h-137"><span class="HTitleText3">Rejet des candidatures et destitution</span></a>
</li>
<li><span class='sectionRange'>618 - </span><a href="#h-138"><span class="HTitleText3">Surveillance et intervention</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>628 - </span><a href="#h-139"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Réglementation des banques : surintendant</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>628 - </span><a href="#h-140"><span class="HTitleText2">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>628 - </span><a href="#h-141"><span class="HTitleText3">Relevés</span></a>
</li>
<li><span class='sectionRange'>643 - </span><a href="#h-142"><span class="HTitleText3">Enquête sur les banques</span></a>
</li></ul>
</li><li><span class='sectionRange'>644.1 - </span><a href="#h-143"><span class="HTitleText2">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>644.1 - </span><a href="#h-144"><span class="HTitleText3">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>645 - </span><a href="#h-145"><span class="HTitleText3">Décisions</span></a>
</li>
<li><span class='sectionRange'>646.1 - </span><a href="#h-146"><span class="HTitleText3">Rejet des candidatures et destitution</span></a>
</li>
<li><span class='sectionRange'>648 - </span><a href="#h-147"><span class="HTitleText3">Surveillance et intervention</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>657 - </span><a href="#h-148"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Réglementation des banques : commissaire</span></a>
</li>
<li><span class='sectionRange'>662 - </span><a href="#h-149"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Sociétés de portefeuille bancaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>662 - </span><a href="#h-150"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>663 - </span><a href="#h-151"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>664 - </span><a href="#h-152"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>671 - </span><a href="#h-153"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Constitution et prorogation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>671 - </span><a href="#h-154"><span class="HTitleText3">Formalités constitutives</span></a>
</li>
<li><span class='sectionRange'>682 - </span><a href="#h-155"><span class="HTitleText3">Prorogation</span></a>
</li>
<li><span class='sectionRange'>689 - </span><a href="#h-156"><span class="HTitleText3">Cessation</span></a>
</li>
<li><span class='sectionRange'>693 - </span><a href="#h-157"><span class="HTitleText3">Dénomination sociale</span></a>
</li>
<li><span class='sectionRange'>699 - </span><a href="#h-158"><span class="HTitleText3">Publication de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>700 - </span><a href="#h-159"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Organisation et fonctionnement</span></a>
</li>
<li><span class='sectionRange'>703 - </span><a href="#h-160"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Structure du capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>703 - </span><a href="#h-161"><span class="HTitleText3">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>723 - </span><a href="#h-162"><span class="HTitleText3">Titres secondaires</span></a>
</li>
<li><span class='sectionRange'>724 - </span><a href="#h-163"><span class="HTitleText3">Certificats de valeurs mobilières et transferts</span></a>
</li></ul>
</li><li><span class='sectionRange'>725 - </span><a href="#h-164"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Administration de la société de portefeuille bancaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>725 - </span><a href="#h-165"><span class="HTitleText3">Actionnaires</span></a>
</li>
<li><span class='sectionRange'>746 - </span><a href="#h-166"><span class="HTitleText3">Procurations et restrictions sur le droit de vote</span></a>
</li>
<li><span class='sectionRange'>747 - </span><a href="#h-167"><span class="HTitleText3">Administrateurs et dirigeants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>747 - </span><a href="#h-168"><span class="HTitleText4">Obligations</span></a>
</li>
<li><span class='sectionRange'>749 - </span><a href="#h-169"><span class="HTitleText4">Administrateurs — nombre et qualités requises</span></a>
</li>
<li><span class='sectionRange'>753 - </span><a href="#h-170"><span class="HTitleText4">Administrateurs — élection et fonctions</span></a>
</li>
<li><span class='sectionRange'>758 - </span><a href="#h-171"><span class="HTitleText4">Élections incomplètes et vacances d’administrateurs</span></a>
</li>
<li><span class='sectionRange'>769 - </span><a href="#h-172"><span class="HTitleText4">Réunions du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>778 - </span><a href="#h-173"><span class="HTitleText4">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>781 - </span><a href="#h-174"><span class="HTitleText4">Comités du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>783 - </span><a href="#h-175"><span class="HTitleText4">Mandat des administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>789 - </span><a href="#h-176"><span class="HTitleText4">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>794 - </span><a href="#h-177"><span class="HTitleText4">Responsabilité, exonération et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>802 - </span><a href="#h-178"><span class="HTitleText3">Modifications de structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>802 - </span><a href="#h-179"><span class="HTitleText4">Modifications</span></a>
</li>
<li><span class='sectionRange'>803 - </span><a href="#h-180"><span class="HTitleText4">Fusion</span></a>
</li>
<li><span class='sectionRange'>813 - </span><a href="#h-181"><span class="HTitleText4">Ventes d’éléments d’actif</span></a>
</li></ul>
</li><li><span class='sectionRange'>814 - </span><a href="#h-182"><span class="HTitleText3">Livres et registres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>814 - </span><a href="#h-183"><span class="HTitleText4">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>825 - </span><a href="#h-184"><span class="HTitleText4">Registres des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>832 - </span><a href="#h-185"><span class="HTitleText4">Dénomination sociale et sceau</span></a>
</li>
<li><span class='sectionRange'>834 - </span><a href="#h-186"><span class="HTitleText4">Initiés</span></a>
</li>
<li><span class='sectionRange'>835 - </span><a href="#h-187"><span class="HTitleText4">Prospectus</span></a>
</li>
<li><span class='sectionRange'>835.1 - </span><a href="#h-188"><span class="HTitleText4">Transactions de fermeture et transactions d’éviction</span></a>
</li>
<li><span class='sectionRange'>836 - </span><a href="#h-189"><span class="HTitleText4">Offres publiques d’achat</span></a>
</li>
<li><span class='sectionRange'>838 - </span><a href="#h-190"><span class="HTitleText4">Acte de fiducie</span></a>
</li></ul>
</li><li><span class='sectionRange'>839 - </span><a href="#h-191"><span class="HTitleText3">États financiers et vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>839 - </span><a href="#h-192"><span class="HTitleText4">Rapport financier annuel</span></a>
</li>
<li><span class='sectionRange'>845 - </span><a href="#h-193"><span class="HTitleText4">Vérificateurs</span></a>
</li>
<li><span class='sectionRange'>865 - </span><a href="#h-194"><span class="HTitleText4">Recours judiciaires</span></a>
</li>
<li><span class='sectionRange'>866 - </span><a href="#h-195"><span class="HTitleText4">Liquidation et dissolution</span></a>
</li>
<li><span class='sectionRange'>869 - </span><a href="#h-196"><span class="HTitleText4">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>870 - </span><a href="#h-197"><span class="HTitleText4">Surveillance judiciaire</span></a>
</li>
<li><span class='sectionRange'>871 - </span><a href="#h-198"><span class="HTitleText4">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>873 - </span><a href="#h-199"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>873 - </span><a href="#h-200"><span class="HTitleText3">Restrictions à la propriété</span></a>
</li>
<li><span class='sectionRange'>905 - </span><a href="#h-201"><span class="HTitleText3">Procédure d’agrément</span></a>
</li></ul>
</li><li><span class='sectionRange'>922 - </span><a href="#h-202"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Activité commerciale et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>925 - </span><a href="#h-203"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>925 - </span><a href="#h-204"><span class="HTitleText3">Interprétation</span></a>
</li>
<li><span class='sectionRange'>926 - </span><a href="#h-205"><span class="HTitleText3">Placements</span></a>
</li>
<li><span class='sectionRange'>927 - </span><a href="#h-206"><span class="HTitleText3">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>930 - </span><a href="#h-207"><span class="HTitleText3">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>933 - </span><a href="#h-208"><span class="HTitleText3">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>937 - </span><a href="#h-209"><span class="HTitleText3">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>938 - </span><a href="#h-210"><span class="HTitleText3">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>939 - </span><a href="#h-211"><span class="HTitleText3">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>940 - </span><a href="#h-212"><span class="HTitleText3">Limite globale</span></a>
</li>
<li><span class='sectionRange'>941 - </span><a href="#h-213"><span class="HTitleText3">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>949 - </span><a href="#h-214"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Capital et liquidités</span></a>
</li>
<li><span class='sectionRange'>950 - </span><a href="#h-215"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2">Réglementation des sociétés de portefeuille bancaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>950 - </span><a href="#h-216"><span class="HTitleText3">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>950 - </span><a href="#h-217"><span class="HTitleText4">Relevés</span></a>
</li></ul>
</li><li><span class='sectionRange'>957 - </span><a href="#h-218"><span class="HTitleText3">Enquête sur les sociétés de portefeuille bancaires</span></a>
</li>
<li><span class='sectionRange'>959 - </span><a href="#h-219"><span class="HTitleText3">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>959 - </span><a href="#h-220"><span class="HTitleText4">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>960 - </span><a href="#h-221"><span class="HTitleText4">Décisions</span></a>
</li>
<li><span class='sectionRange'>962 - </span><a href="#h-222"><span class="HTitleText4">Rejet des candidatures et destitution</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>964.1 - </span><a href="#h-223"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>964.1 - </span><a href="#h-224"><span class="HTitleText2">Avis et autres documents</span></a>
</li>
<li><span class='sectionRange'>973 - </span><a href="#h-225"><span class="HTitleText2">Agréments</span></a>
</li>
<li><span class='sectionRange'>973.1 - </span><a href="#h-226"><span class="HTitleText2">Arrêtés d’exemption temporaires</span></a>
</li>
<li><span class='sectionRange'>973.2 - </span><a href="#h-227"><span class="HTitleText2">Exemption ou adaptation par décret</span></a>
</li>
<li><span class='sectionRange'>974 - </span><a href="#h-228"><span class="HTitleText2">Arrêts, ordonnances et décisions</span></a>
</li>
<li><span class='sectionRange'>976 - </span><a href="#h-229"><span class="HTitleText2">Demandes au surintendant</span></a>
</li>
<li><span class='sectionRange'>976.1 - </span><a href="#h-230"><span class="HTitleText2">Demandes relatives à certains agréments</span></a>
</li>
<li><span class='sectionRange'>977 - </span><a href="#h-231"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>978 - </span><a href="#h-232"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>979 - </span><a href="#h-233"><span class="HTitleText2">Délégation</span></a>
</li></ul>
</li><li><span class='sectionRange'>980 - </span><a href="#h-234"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Peines</span></a>
</li>
<li><span class='sectionRange'>992 - </span><a href="#h-235"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Documents sous forme électronique ou autre</span></a>
</li>
<li><a href="#h-236"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-237"><span class="scheduleLabel">ANNEXE II</span> </a>
</li>
<li><a href="#h-238"><span class="scheduleLabel">ANNEXE III</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
