<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Prize Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-49552"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-49557"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-49562"><span class="HTitleText1">Prize Court</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-49572"><span class="HTitleText1">Prize Law of Canada</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-49587"><span class="HTitleText1">Procedure and Orders or Regulations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-49597"><span class="HTitleText1">Reciprocal Arrangements with Other Governments</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-49622"><span class="HTitleText1">Continuation of Procedure</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
