<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les ponts et tunnels internationaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-264152"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-264155"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-264178"><span class="HTitleText1">Construction et modification</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-264239"><span class="HTitleText1">Entretien et réparation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-264248"><span class="HTitleText1">Exploitation et usage</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-264260"><span class="HTitleText1">Sûreté</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-264290"><span class="HTitleText1">Changement concernant la propriété, l’exploitation ou le contrôle</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-264339"><span class="HTitleText1">Constitution de personnes morales par lettres patentes</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-264406"><span class="HTitleText1">Actions d’une personne morale</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-264409"><span class="HTitleText1">Mesures de contrainte</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-264462"><span class="HTitleText1">Pénalités</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-264521"><span class="HTitleText1">Examen</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-264527"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-264532"><span class="HTitleText1">Modification corrélative</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-264533"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal d’appel des transports du Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-264535"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-264539"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Lois relatives à certains ponts et tunnels</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
