<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada — Moldova Tax Convention Act, 2002</a><ul class="TocIndent"><li><a href="#h-150816"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Republic of Moldova for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income</span></a>
</li>
<li><a href="#h-151074"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
