<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’inspection du poisson</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-224954"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-224959"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-224972"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Poisson et contenants</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-225041"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Plantes marines</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-225063"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
