<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Security of Canada Information Sharing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-444921"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-444924"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-444944"><span class="HTitleText1">Purpose and Principles</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-444954"><span class="HTitleText1">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-444968"><span class="HTitleText1">Protection from Civil Proceedings</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-444971"><span class="HTitleText1">Powers of Governor in Council</span></a>
</li>
<li><a href="#h-444983"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Excluded Institutions</span></a>
</li>
<li><a href="#h-444985"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Additional Institutions</span></a>
</li>
<li><a href="#h-444989"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
