<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’accord définitif concernant la Première Nation de Yale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-458835"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-458838"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-458848"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-458861"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-458864"><span class="HTitleText1">Terres</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-458867"><span class="HTitleText1">Fiscalité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-458872"><span class="HTitleText1">Pêches</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-458877"><span class="HTitleText1">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-458882"><span class="HTitleText1">Application de lois de la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-458885"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-458911"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-458912"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-458914"><span class="HTitleText2">Loi sur les pêches</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-458916"><span class="HTitleText2">Loi sur les paiements versés en remplacement d’impôts</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-458918"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-458920"><span class="HTitleText2">Loi sur le Tribunal des revendications particulières</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-458922"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

