<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Radiocommunication Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-423762"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-423767"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-423806"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-423829"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-423843"><span class="HTitleText1">Minister’s Powers</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-423903"><span class="HTitleText1">Powers of Governor in Council and Others</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-424026"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-424141"><span class="HTitleText1">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-424278"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-424295"><span class="HTitleText1">Civil Action</span></a>
</li></ul>
</li></ul>

</nav>

