<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’autonomie gouvernementale de la bande indienne sechelte</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-433923"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-433926"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-433940"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-433943"><span class="HTitleText1">Bande indienne sechelte</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-433949"><span class="HTitleText1">Attributions de la bande</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-433960"><span class="HTitleText1">Conseil de la bande indienne sechelte</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-433965"><span class="HTitleText1">Constitution de la bande</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-433984"><span class="HTitleText1">Modification de la constitution</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-433987"><span class="HTitleText1">Publication de la constitution et des modifications</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-433990"><span class="HTitleText1">Attributions législatives du conseil</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-434025"><span class="HTitleText1">District de l’administration indienne sechelte</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-434060"><span class="HTitleText1">Transfert de terres</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-434077"><span class="HTitleText1">Aliénation des terres secheltes</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-434080"><span class="HTitleText1">Registre des terres secheltes</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-434106"><span class="HTitleText1">Terres secheltes</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-434109"><span class="HTitleText1">Sommes d’argent</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-434115"><span class="HTitleText1">Financement</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-2.html#h-434120"><span class="HTitleText1">Application de la Loi sur les indiens</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-434130"><span class="HTitleText1">Application des lois fédérales</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-2.html#h-434133"><span class="HTitleText1">Application des lois de la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-2.html#h-434136"><span class="HTitleText1">Application des lois sur les ressources naturelles</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-2.html#h-434143"><span class="HTitleText1">Application des règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-2.html#h-434146"><span class="HTitleText1">Gouverneur en conseil et ministre</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-2.html#h-434149"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>47 à 60 - </span><a href="page-2.html#h-434164"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-2.html#h-434166"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

