<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi autorisant l’aliénation de Nordion et de Theratronics</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-356748"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-356751"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-356766"><span class="HTitleText1">Autorisation d’aliénation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-356774"><span class="HTitleText1">Nordion</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-356843"><span class="HTitleText1">Theratronics</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-356848"><span class="HTitleText1">Dispositions transitoires et modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-356874"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

