<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Transportation Appeal Tribunal of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-451802"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-451805"><span class="HTitleText1">Transportation Appeal Tribunal of Canada</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-451916"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>33 to 70 - </span><a href="#h-451947"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>71 and 72 - </span><a href="#h-451949"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-451951"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

