<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Natural Sciences and Engineering Research Council Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-364274"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-364279"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-364288"><span class="HTitleText1">Constitution of the Council</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-364293"><span class="HTitleText1">Functions and Powers</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-364305"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-364385"><span class="HTitleText1">Donations</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-364391"><span class="HTitleText1">Report to Parliament</span></a>
</li></ul>
</li></ul>

</nav>

