<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi fédérale sur l’aide financière aux étudiants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-431226"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-431229"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-431249"><span class="HTitleText1">Autorité compétente</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-431264"><span class="HTitleText1">Accords avec les prêteurs</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="#h-431293"><span class="HTitleText1">Financement des prêts d’études par le gouvernement</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-431327"><span class="HTitleText1">Période sans intérêt ni remboursement</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="#h-431354"><span class="HTitleText1">Médecin de famille, infirmier ou infirmier praticien dans une collectivité rurale ou éloignée mal desservie</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="#h-1228788"><span class="HTitleText1">Période allant du 30 mars 2020 au 30 septembre 2020</span></a>
</li>
<li><span class='sectionRange'>9.4 - </span><a href="#h-1281633"><span class="HTitleText1">Période allant du 1<sup>er</sup> avril 2021 au 31 mars 2022</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-431364"><span class="HTitleText1">Décès ou invalidité de l’emprunteur</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-431387"><span class="HTitleText1">Certificats d’admissibilité</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-431413"><span class="HTitleText1">Maximum admissible des prêts d’études impayés</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-431418"><span class="HTitleText1">Montants compensatoires</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-431477"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-431514"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-1191110"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>21 à 27 - </span><a href="#h-431648"><span class="HTitleText1">Modification de la loi fédérale sur les prêts aux étudiants</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-431650"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-431652"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
