<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Postal Services Continuation Act, 1997 <span class='Repealed'>[Repealed, 2017, c. 26, s. 70]</span></a></li></ul>
</nav>
</div></section>
