<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Business Development Bank of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Establishment and Organization of the Bank</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Status of the Bank</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Officers and Employees</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">Remuneration and Benefits</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText1">Specific Powers of the Bank</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText2">Financial Services</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText2">Management Services</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText2">Treasury Activities</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Other Services and Programs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Ancillary Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-15"><span class="HTitleText1">Capital of the Bank</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-16"><span class="HTitleText1">Debt-to-equity Ratio</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText1">Conflict of Interest</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-18"><span class="HTitleText1">Miscellaneous Provisions</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-19"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-20"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>44 to 55 - </span><a href="#h-21"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><a href="#h-40641"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
