<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la taxe d’accise</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Primes d’assurance autres que l’assurance maritime</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Taxe de transport aérien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-6"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Taxe imposée</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-9"><span class="HTitleText2">Perception de la taxe</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-10"><span class="HTitleText2">Pénalité pour défaut de production du rapport</span></a>
</li>
<li><span class='sectionRange'>20.2 - </span><a href="#h-11"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>21.1 - </span><a href="#h-12"><span class="HLabel1">PARTIE II.1</span> - <span class="HTitleText1">Taxe sur les services de programmation fournis par voie de télécommunication</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21.1 - </span><a href="#h-13"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>21.11 - </span><a href="#h-14"><span class="HTitleText2">Application à la Couronne</span></a>
</li>
<li><span class='sectionRange'>21.12 - </span><a href="#h-15"><span class="HTitleText2">Imposition et paiement de la taxe</span></a>
</li>
<li><span class='sectionRange'>21.14 - </span><a href="#h-16"><span class="HTitleText2">Cas spécial de détermination du montant exigé</span></a>
</li>
<li><span class='sectionRange'>21.15 - </span><a href="#h-17"><span class="HTitleText2">Garantie</span></a>
</li>
<li><span class='sectionRange'>21.16 - </span><a href="#h-18"><span class="HTitleText2">Détournements</span></a>
</li>
<li><span class='sectionRange'>21.17 - </span><a href="#h-19"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="#h-20"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>21.21 - </span><a href="#h-21"><span class="HTitleText2">Augmentation du montant exigé par le titulaire d’une licence</span></a>
</li></ul>
</li><li><span class='sectionRange'>21.22 - </span><a href="#h-22"><span class="HLabel1">PARTIE II.2</span> - <span class="HTitleText1">Taxe sur les services de télécommunication</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21.22 - </span><a href="#h-23"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>21.23 - </span><a href="#h-24"><span class="HTitleText2">Application à la Couronne</span></a>
</li>
<li><span class='sectionRange'>21.24 - </span><a href="#h-25"><span class="HTitleText2">Imposition de la taxe</span></a>
</li>
<li><span class='sectionRange'>21.25 - </span><a href="#h-26"><span class="HTitleText2">Cas spécial de détermination du montant exigé</span></a>
</li>
<li><span class='sectionRange'>21.26 - </span><a href="#h-27"><span class="HTitleText2">Exonération de la taxe</span></a>
</li>
<li><span class='sectionRange'>21.29 - </span><a href="#h-28"><span class="HTitleText2">Détournements</span></a>
</li>
<li><span class='sectionRange'>21.3 - </span><a href="#h-29"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>21.31 - </span><a href="#h-30"><span class="HTitleText2">Perception de la taxe</span></a>
</li>
<li><span class='sectionRange'>21.32 - </span><a href="#h-31"><span class="HTitleText2">Déclaration et remise de la taxe</span></a>
</li>
<li><span class='sectionRange'>21.34 - </span><a href="#h-32"><span class="HTitleText2">Pouvoir réglementaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-33"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Taxes d’accise sur les cosmétiques, bijoux, postes de réception de t.s.f., etc.</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-34"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">[Abrogée, 2002, ch. 22, art. 370]</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-35"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">[Abrogée, 2002, ch. 22, art. 370]</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-36"><span class="HLabel1">PARTIE V.1</span> - <span class="HTitleText1">[Abrogée, 2000, ch. 30, art. 10]</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-37"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Taxe de consommation ou de vente</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-38"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-39"><span class="HTitleText2">Taxe imposée</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-40"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-41"><span class="HTitleText2">Dissimulation de la matière imposable</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="#h-42"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58.1 - </span><a href="#h-43"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-44"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-45"><span class="HTitleText2">Timbres</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-46"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-47"><span class="HTitleText2">Marchandises exportées</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-48"><span class="HTitleText2">Application des taxes à la Couronne</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-49"><span class="HTitleText2">Déductions, remises et drawbacks</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-50"><span class="HTitleText2">Déclarations et paiement de la taxe</span></a>
</li>
<li><span class='sectionRange'>80.1 - </span><a href="#h-51"><span class="HTitleText2">Garantie</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-52"><span class="HTitleText2">Obligations des syndics</span></a>
</li>
<li><span class='sectionRange'>81.1 - </span><a href="#h-53"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>81.15 - </span><a href="#h-54"><span class="HTitleText2">Oppositions</span></a>
</li>
<li><span class='sectionRange'>81.19 - </span><a href="#h-55"><span class="HTitleText2">Droits d’appel</span></a>
</li>
<li><span class='sectionRange'>81.25 - </span><a href="#h-56"><span class="HTitleText2">Appels au Tribunal</span></a>
</li>
<li><span class='sectionRange'>81.28 - </span><a href="#h-57"><span class="HTitleText2">Appels à la Cour</span></a>
</li>
<li><span class='sectionRange'>81.32 - </span><a href="#h-58"><span class="HTitleText2">Prolongation du délai pour opposition ou appel</span></a>
</li>
<li><span class='sectionRange'>81.33 - </span><a href="#h-59"><span class="HTitleText2">Oppositions et appels d’acheteurs</span></a>
</li>
<li><span class='sectionRange'>81.34 - </span><a href="#h-60"><span class="HTitleText2">Interventions</span></a>
</li>
<li><span class='sectionRange'>81.36 - </span><a href="#h-61"><span class="HTitleText2">Renvois</span></a>
</li>
<li><span class='sectionRange'>81.38 - </span><a href="#h-62"><span class="HTitleText2">Paiements par le ministre à la suite d’appels</span></a>
</li>
<li><span class='sectionRange'>81.39 - </span><a href="#h-63"><span class="HTitleText2">Paiements en trop par le ministre</span></a>
</li>
<li><span class='sectionRange'>81.4 - </span><a href="#h-64"><span class="HTitleText2">Frais administratifs prévus par la <cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-65"><span class="HTitleText2">Perception</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-66"><span class="HTitleText2">Signification</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-67"><span class="HTitleText2">Preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-68"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-69"><span class="HTitleText2">Remboursement de la taxe de vente à l’inventaire</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-70"><span class="HTitleText2">Remboursement pour habitations neuves</span></a>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="#h-71"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Taxe sur les produits et services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-72"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Définitions et interprétation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-73"><span class="HTitleText3">Personnes liées, personnes associées, personnes distinctes et résidence</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-74"><span class="HTitleText3">Fournitures et activités commerciales</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-75"><span class="HTitleText3">Petits fournisseurs</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-76"><span class="HTitleText3">Institutions financières</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-77"><span class="HTitleText3">Contrepartie</span></a>
</li></ul>
</li><li><span class='sectionRange'>165 - </span><a href="#h-78"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Taxe sur les produits et services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-79"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Assujettissement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-80"><span class="HTitleText4">Taxe payable</span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="#h-81"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Crédit de taxe sur les intrants</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-82"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Cas spéciaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>171 - </span><a href="#h-83"><span class="HTitleText4">Début et cessation de l’inscription</span></a>
</li>
<li><span class='sectionRange'>171.1 - </span><a href="#h-84"><span class="HTitleText4">Entreprises de taxis</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-85"><span class="HTitleText4">Utilisation de biens et de services</span></a>
</li>
<li><span class='sectionRange'>172.1 - </span><a href="#h-86"><span class="HTitleText4">Régimes de pension</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-87"><span class="HTitleText4">Avantages taxables</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-88"><span class="HTitleText4">Indemnités et remboursements</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-89"><span class="HTitleText4">Contenants consignés d’occasion</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-90"><span class="HTitleText4">Mandataires</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-91"><span class="HTitleText4">Vendeurs de réseau</span></a>
</li>
<li><span class='sectionRange'>178.1 - </span><a href="#h-92"><span class="HTitleText4">Démarcheurs</span></a>
</li>
<li><span class='sectionRange'>178.6 - </span><a href="#h-93"><span class="HTitleText4">Groupes d’acheteurs</span></a>
</li>
<li><span class='sectionRange'>178.7 - </span><a href="#h-94"><span class="HTitleText4">Organismes de bienfaisance désignés</span></a>
</li>
<li><span class='sectionRange'>178.8 - </span><a href="#h-95"><span class="HTitleText4">Ententes d’importation</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-96"><span class="HTitleText4">Personne non résidante</span></a>
</li>
<li><span class='sectionRange'>180.1 - </span><a href="#h-97"><span class="HTitleText4">Vols et voyages internationaux</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-98"><span class="HTitleText4">Bons et remises</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-99"><span class="HTitleText4">Biens acquis par les assureurs sur règlement de sinistre</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-100"><span class="HTitleText4">Biens et services pour services financiers</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-101"><span class="HTitleText4">Paris et jeux de hasard</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-102"><span class="HTitleText4">Prix</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-103"><span class="HTitleText4">Cotisations</span></a>
</li>
<li><span class='sectionRange'>189.1 - </span><a href="#h-104"><span class="HTitleText4">Frais</span></a>
</li>
<li><span class='sectionRange'>189.2 - </span><a href="#h-105"><span class="HTitleText4">Congrès étrangers</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-106"><span class="HTitleText4">Immeubles</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-107"><span class="HTitleText4">Crédits pour immeubles</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-108"><span class="HTitleText4">Déclaration concernant l’utilisation d’un immeuble</span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="#h-109"><span class="HLabel3">SOUS-SECTION d</span> - <span class="HTitleText3">Immobilisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>199 - </span><a href="#h-110"><span class="HTitleText4">Immobilisations (biens meubles)</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-111"><span class="HTitleText4">Immobilisations (immeubles)</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>212 - </span><a href="#h-112"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Taxe sur l’importation de produits</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-113"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Taxe sur les fournitures taxables importées</span></a>
</li>
<li><span class='sectionRange'>220.01 - </span><a href="#h-114"><span class="HLabel2">SECTION IV.1</span> - <span class="HTitleText2">Taxe sur les produits et services transférés dans une province participante</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220.05 - </span><a href="#h-115"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Taxe sur les biens meubles corporels</span></a>
</li>
<li><span class='sectionRange'>220.08 - </span><a href="#h-116"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Taxe sur les biens incorporels et les services</span></a>
</li>
<li><span class='sectionRange'>220.09 - </span><a href="#h-117"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Déclarations et paiement de la taxe</span></a>
</li></ul>
</li><li><span class='sectionRange'>221 - </span><a href="#h-118"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Perception et versement de la taxe prévue à la section II</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>221 - </span><a href="#h-119"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Perception</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-120"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Versement de la taxe</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-121"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Déclarations</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-122"><span class="HLabel3">SOUS-SECTION d</span> - <span class="HTitleText3">Inscription</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="#h-123"><span class="HLabel3">SOUS-SECTION e</span> - <span class="HTitleText3">Exercices et périodes de déclaration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>243 - </span><a href="#h-124"><span class="HTitleText4">Exercices</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-125"><span class="HTitleText4">Périodes de déclaration</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>252 - </span><a href="#h-126"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-127"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Divers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>265 - </span><a href="#h-128"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Syndics, séquestres et représentants personnels</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-129"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Fusion et liquidation</span></a>
</li>
<li><span class='sectionRange'>272.1 - </span><a href="#h-130"><span class="HLabel3">SOUS-SECTION b.1</span> - <span class="HTitleText3">Sociétés de personnes et coentreprises</span></a>
</li>
<li><span class='sectionRange'>273.1 - </span><a href="#h-131"><span class="HLabel3">SOUS-SECTION b.2</span> - <span class="HTitleText3">Centres de distribution des exportations</span></a>
</li>
<li><span class='sectionRange'>273.2 - </span><a href="#h-132"><span class="HLabel3">SOUS-SECTION b.3</span> - <span class="HTitleText3">Déclaration de renseignements des institutions financières</span></a>
</li>
<li><span class='sectionRange'>274 - </span><a href="#h-133"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Évitement</span></a>
</li></ul>
</li><li><span class='sectionRange'>275 - </span><a href="#h-134"><span class="HLabel2">SECTION VIII</span> - <span class="HTitleText2">Application et exécution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>275 - </span><a href="#h-135"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-136"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Déclarations, pénalités et intérêts</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="#h-137"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Généralités</span></a>
</li>
<li><span class='sectionRange'>296 - </span><a href="#h-138"><span class="HLabel3">SOUS-SECTION d</span> - <span class="HTitleText3">Cotisations, oppositions et appels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>296 - </span><a href="#h-139"><span class="HTitleText4">Cotisation</span></a>
</li>
<li><span class='sectionRange'>301 - </span><a href="#h-140"><span class="HTitleText4">Opposition et appels</span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="#h-141"><span class="HLabel3">SOUS-SECTION e</span> - <span class="HTitleText3">Perception</span></a>
</li>
<li><span class='sectionRange'>326 - </span><a href="#h-142"><span class="HLabel3">SOUS-SECTION f</span> - <span class="HTitleText3">Infractions</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="#h-143"><span class="HLabel3">SOUS-SECTION g</span> - <span class="HTitleText3">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>336 - </span><a href="#h-144"><span class="HLabel2">SECTION IX</span> - <span class="HTitleText2">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="#h-145"><span class="HTitleText3">Immeubles</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-146"><span class="HTitleText3">Biens et services</span></a>
</li></ul>
</li><li><span class='sectionRange'>348 - </span><a href="#h-147"><span class="HLabel2">SECTION X</span> - <span class="HTitleText2">Dispositions transitoires applicables aux provinces participantes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>348 - </span><a href="#h-148"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>349 - </span><a href="#h-149"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>350 - </span><a href="#h-150"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Transition</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>352 - </span><a href="#h-151"><span class="HTitleText4">Biens et services</span></a>
</li></ul>
</li><li><span class='sectionRange'>362 - </span><a href="#h-152"><span class="HLabel3">SOUS-SECTION d</span> - <span class="HTitleText3">Cas particuliers</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-195218"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-195271"><span class="scheduleLabel">ANNEXE II</span></a>
</li>
<li><a href="#h-195276"><span class="scheduleLabel">ANNEXE II.1</span> <span class="scheduleTitleText"> - Taux spécifiés pour produits pétroliers</span></a>
</li>
<li><a href="#h-195285"><span class="scheduleLabel">ANNEXE III</span> </a>
</li>
<li><a href="#h-195613"><span class="scheduleLabel">ANNEXE III.1</span> - <span class="scheduleTitleText"> - Marchandises vendues par des fabricants ou producteurs présumés</span></a>
</li>
<li><a href="#h-195626"><span class="scheduleLabel">ANNEXE IV</span> </a>
</li>
<li><a href="#h-159"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Fournitures exonérées</span></a>
</li>
<li><a href="#h-160"><span class="scheduleLabel">ANNEXE VI</span> <span class="scheduleTitleText"> - Fournitures détaxées</span></a>
</li>
<li><a href="#h-161"><span class="scheduleLabel">ANNEXE VII</span> <span class="scheduleTitleText"> - Importations non taxables</span></a>
</li>
<li><a href="#h-196621"><span class="scheduleLabel">ANNEXE VIII</span> </a>
</li>
<li><a href="#h-196631"><span class="scheduleLabel">ANNEXE IX</span> <span class="scheduleTitleText"> - Fourniture dans une province</span></a>
</li>
<li><a href="#h-164"><span class="scheduleLabel">ANNEXE X</span> - <span class="scheduleTitleText"> - Biens et services non taxables pour l’application de la section IV.1 de la partie IX</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
