<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Supplementary Retirement Benefits Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-442871"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-442876"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-442919"><span class="HTitleText1">Supplementary Retirement Benefits</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-442965"><span class="HTitleText1">Return of Contributions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-442986"><span class="HTitleText1">Recoveries</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-442991"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-443007"><span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-443024"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-443045"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
