<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Tax Court of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-458932"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-458937"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-458969"><span class="HTitleText1">The Court</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-458974"><span class="HTitleText1">The Judges</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-459047"><span class="HTitleText1">Jurisdiction and Powers of the Court</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-459065"><span class="HTitleText1">Proceedings Before the Court</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-459102"><span class="HTitleText2">General Procedure</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-459161"><span class="HTitleText2">Informal Procedure</span></a>
</li>
<li><span class='sectionRange'>18.31 - </span><a href="#h-459482"><span class="HTitleText2">References</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-459512"><span class="HTitleText1">Oaths and Affidavits</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="#h-459520"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-459547"><span class="HTitleText1">Rules</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-459595"><span class="HTitleText1">Administration of Court</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-459611"><span class="HTitleText1">Transitional</span></a>
</li></ul>
</li></ul>

</nav>

