<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de mise en oeuvre de l’Accord Canada–Yukon sur le pétrole et le gaz</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-59219"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-59222"><span class="HTitleText1">Modification de la Loi sur le Yukon</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-59232"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-59233"><span class="HTitleText2">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-59236"><span class="HTitleText2">Loi fédérale sur les hydrocarbures</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-59239"><span class="HTitleText2">Loi sur l’Office des droits de surface du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-59244"><span class="HTitleText1">Dispositions transitoires et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-59245"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-59257"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-59311"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

