<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur Téléfilm Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-67773"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-67778"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-67790"><span class="HTitleText1">Établissement de la Société Téléfilm Canada</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-67826"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-67857"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-67896"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-67928"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-67933"><span class="HTitleText1">Rapport au Parlement</span></a>
</li></ul>
</li></ul>

</nav>

