<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Forces Superannuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Equality of Status</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-4"><span class="HTitleText1">Application to Certain Reserve Force Members</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Superannuation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText2">Eligibility for Benefits</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText2">Pensionable Service</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-9"><span class="HTitleText2">Elective Pensionable Service: Amount Required to be Paid</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-10"><span class="HTitleText2">Elections</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText2">Benefits: Definitions, etc.</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText2">Annuities: How Computed</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-13"><span class="HTitleText2">Benefits Payable to Contributors</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Benefits Payable to Survivors, Children and Other Beneficiaries</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-15"><span class="HTitleText2">Minimum Benefits</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-16"><span class="HTitleText2">Special Cases</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-17"><span class="HTitleText3">Former Members of the Regular Force</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-18"><span class="HTitleText3">Members of the Regular Force, Enrolled for a Fixed Period of Service</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-19"><span class="HTitleText3">Former Public Service Employees and Members of the Royal Canadian Mounted Police</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-20"><span class="HTitleText2">Service Pension Board</span></a>
</li>
<li><span class='sectionRange'>49.1 - </span><a href="#h-21"><span class="HTitleText2">Advisory Committee</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-22"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-23"><span class="HTitleText2">Payments out of Account</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-24"><span class="HTitleText2">Amounts</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-25"><span class="HTitleText2">Canadian Forces Superannuation Investment Fund</span></a>
</li>
<li><span class='sectionRange'>55.2 - </span><a href="#h-26"><span class="HTitleText2">Canadian Forces Pension Fund</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-27"><span class="HTitleText2">Actuarial Report</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-28"><span class="HTitleText2">Annual Report</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-29"><span class="HTitleText2">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-30"><span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>59.1 - </span><a href="#h-31"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Reserve Force Pension Plan</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-32"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Supplementary Death Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-33"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-34"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-35"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-36"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-37"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Supplementary Benefits</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-38"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-71241"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
