<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Government Organization Act, Atlantic Canada, 1987</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-251634"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 to 24 - </span><a href="#h-251637"><span class="HLabel1">PART I</span></a>
</li>
<li><span class='sectionRange'>25 to 44 - </span><a href="#h-251639"><span class="HLabel1">PART II</span></a>
</li>
<li><span class='sectionRange'>45 to 56 - </span><a href="#h-251641"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Consequential and Related Amendments</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-251643"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

