<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
State Immunity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-440032"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-440037"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-440054"><span class="HTitleText1">State Immunity</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-440136"><span class="HTitleText1">Procedure and Relief</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-440218"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

