<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Government Corporations Operation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-251555"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-251560"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-251565"><span class="HTitleText1">Status, Powers and Personnel of Corporations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-251596"><span class="HTitleText1">Application</span></a>
</li></ul>
</li></ul>

</nav>

