<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Peru Free Trade Agreement Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-166097"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-166100"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-166116"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-166119"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-166130"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-166136"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement and the Related Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-166137"><span class="HTitleText2">Approval</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-166140"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-166145"><span class="HTitleText2">Panels, Committees, Subcommittees and Working Groups</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-166157"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-166167"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-166168"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-166176"><span class="HTitleText2">Commercial Arbitration Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-166178"><span class="HTitleText2">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-166186"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-166192"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-166207"><span class="HTitleText2">Department of Human Resources and Skills Development Act</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-166210"><span class="HTitleText2">Export and Import Permits Act</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-166214"><span class="HTitleText2">Financial Administration Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-166216"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-166217"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-166219"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-166226"><span class="scheduleLabel">SCHEDULE 1</span></a>
</li>
<li><a href="#h-166229"><span class="scheduleLabel">SCHEDULE 2</span></a>
</li>
<li><a href="#h-166232"><span class="scheduleLabel">SCHEDULE 3</span></a>
</li>
<li><a href="#h-166235"><span class="scheduleLabel">SCHEDULE 4</span></a>
</li>
<li><a href="#h-166238"><span class="scheduleLabel">SCHEDULE 5</span></a>
</li>
<li><a href="#h-166241"><span class="scheduleLabel">SCHEDULE 6</span></a>
</li>
<li><a href="#h-166244"><span class="scheduleLabel">SCHEDULE 7</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
