<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Cour canadienne de l’impôt</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-448101"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-448106"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-448136"><span class="HTitleText1">La Cour</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-448141"><span class="HTitleText1">Les juges</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-448209"><span class="HTitleText1">Compétence et pouvoirs de la cour</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-448227"><span class="HTitleText1">Procédure devant la cour</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="page-2.html#h-448264"><span class="HTitleText2">Procédure générale</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-448323"><span class="HTitleText2">Procédure informelle</span></a>
</li>
<li><span class='sectionRange'>18.31 - </span><a href="page-5.html#h-448636"><span class="HTitleText2">Renvois</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="page-5.html#h-448666"><span class="HTitleText1">Déclarations sous serment ou autres</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="page-5.html#h-448674"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-5.html#h-448701"><span class="HTitleText1">Règles</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-5.html#h-448749"><span class="HTitleText1">Administration de la cour</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-6.html#h-448765"><span class="HTitleText1">Dispositions transitoires</span></a>
</li></ul>
</li></ul>

</nav>

