<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
International Sale of Goods Contracts Convention Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-276621"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-276624"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-276630"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-276633"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-276641"><span class="HTitleText1">Inconsistent Laws</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-276644"><span class="HTitleText1">Courts</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-276649"><span class="HTitleText1">Publication</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-276652"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-276655"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-2.html#h-276659"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - United Nations Convention on Contracts for the International Sale of Goods</span></a>
</li></ul>
</li></ul>

</nav>

