<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée nationale des produits du phoque</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-354867"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-354870"><span class="HTitleText1">Journée nationale des produits du phoque</span></a>
</li></ul>
</li></ul>

</nav>

