<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Plant Breeders’ Rights Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Plant Breeder’s Rights</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Applications for Plant Breeder’s Rights</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">Denominations of New Varieties</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-8"><span class="HTitleText1">Summary Disposition of Applications</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">Protective Directions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-10"><span class="HTitleText1">Consideration and Disposition of Applications</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-11"><span class="HTitleText1">Grant, Refusal and Disposal of Plant Breeder’s Rights</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-12"><span class="HTitleText1">Maintenance of Propagating Material</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-13"><span class="HTitleText1">Assignment of Plant Breeder’s Rights</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-14"><span class="HTitleText1">Compulsory Licences</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-15"><span class="HTitleText1">Annulment and Revocation of Grants</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HTitleText1">Surrender of Plant Breeder’s Rights</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText1">Agents</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-18"><span class="HTitleText1">Civil Remedies</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-19"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-20"><span class="HTitleText1">Plant Breeders’ Rights Office</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-21"><span class="HTitleText1">Records</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-22"><span class="HTitleText1">Publication</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-23"><span class="HTitleText1">Advisory Committee</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-24"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-25"><span class="HTitleText1">Seeds Act</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-26"><span class="HTitleText1">Review of Act</span></a>
</li>
<li><span class='sectionRange'>79. to 81 - </span><a href="#h-27"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-28"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
