<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Multiculturalism Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-73115"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-73118"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-73130"><span class="HTitleText1">Multiculturalism Policy of Canada</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-73152"><span class="HTitleText1">Implementation of the Multiculturalism Policy of Canada</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-73183"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
