<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget and Economic Statement Implementation Act, 2007</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-34850"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-34853"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments in Respect of the Goods and Services Tax/Harmonized Sales Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-34854"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-34861"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendment Relating to Excise Tax on Renewable Fuels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-34862"><span class="HTitleText2">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-34864"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-34865"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-34926"><span class="HTitleText2">Income Tax Application Rules</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-34928"><span class="HTitleText2">Income Tax Conventions Interpretation Act</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-34930"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-34950"><span class="HTitleText2">Canada Pension Plan Regulations</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-34952"><span class="HTitleText2">Insurable Earnings and Collection of Premiums Regulations</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-34954"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="#h-34964"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Disability Savings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-34965"><span class="HTitleText2">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-34966"><span class="HTitleText3">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-34991"><span class="HTitleText3">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-34995"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="#h-34996"><span class="HTitleText4">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-34998"><span class="HTitleText4">Old Age Security Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-35000"><span class="HTitleText3">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-35006"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-35008"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Disability Savings Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-35009"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-35012"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Children’s Special Allowances Act</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-35014"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>139 - </span><a href="#h-35017"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Incentive for Provinces to Eliminate Taxes on Capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>139 - </span><a href="#h-35018"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-35020"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Bank for International Settlements (Immunity) Act</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-35023"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Phased Retirement — Amendments Other than Those Concerning Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-35024"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-35027"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-35030"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Advance Market Commitment</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-35040"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Oil and Gas Operations in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>145 - </span><a href="#h-35041"><span class="HTitleText2">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-35048"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-35049"><span class="HTitleText3">Canada Petroleum Resources Act</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-35051"><span class="HTitleText3">National Energy Board Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>154 - </span><a href="#h-35054"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Amendments to the Farm Income Protection Act</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-35062"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Federal-Provincial Fiscal Arrangements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="#h-35063"><span class="HTitleText2">Amendments to the Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-35072"><span class="HTitleText2">Amendments to the Budget Implementation Act, 2007</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-35076"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Canada-Newfoundland Atlantic Accord Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-35078"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-35082"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>176 - </span><a href="#h-35088"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Amendments to the Canada Education Savings Act</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-35091"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Private-Public Partnerships</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-35094"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Tax Amendments to Implement the 2007 Economic Statement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-35095"><span class="HTitleText2">Amendments Relating to Income Tax</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>179 - </span><a href="#h-35096"><span class="HTitleText3">Income Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="#h-35101"><span class="HTitleText2">Amendments to Implement the GST/HST Rate Reduction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-35102"><span class="HTitleText3">Excise Tax Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>196 - </span><a href="#h-35116"><span class="HTitleText2">Related Amendments as a Result of the GST/HST Rate Reduction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>196 - </span><a href="#h-35117"><span class="HTitleText3">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-35119"><span class="HTitleText3">Excise Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-35120"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-35133"><span class="HTitleText4">Application</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
