<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Commercial Corporation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-61899"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-61904"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-61914"><span class="HTitleText1">Establishment and Organization of the Corporation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-61973"><span class="HTitleText1">Purposes and Powers of the Corporation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-61998"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-62027"><span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
