<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la réduction de la paperasse</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-415858"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-415861"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-415867"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-415870"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-415873"><span class="HTitleText1">Règle</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-415888"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-415894"><span class="HTitleText1">Rapport annuel</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-415899"><span class="HTitleText1">Examen</span></a>
</li></ul>
</li></ul>

</nav>

