<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2006 sur les droits d’exportation de produits de bois d’oeuvre</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">Droits d’exportation de produits de bois d’oeuvre</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText2">Droits d’exportation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText2">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-8"><span class="HTitleText1">Droits sur les remboursements de dépôts douaniers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">Dispositions générales concernant les droits et les autres sommes à payer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText2">Personnel assurant l’exécution et le contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-11"><span class="HTitleText2">Inscription et agrément</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText2">Déclarations et paiement des droits</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-13"><span class="HTitleText2">Intérêts</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-14"><span class="HTitleText2">Frais administratifs prévus par la <cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText2">Remboursements</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-16"><span class="HTitleText2">Faillites et réorganisations</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-17"><span class="HTitleText2">Sociétés de personnes</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-18"><span class="HTitleText2">Registres et renseignements</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-19"><span class="HTitleText2">Cotisations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-20"><span class="HTitleText2">Opposition aux cotisations</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-21"><span class="HTitleText2">Appel</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-22"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-23"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-24"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-25"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-26"><span class="HTitleText2">Enquête</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-27"><span class="HTitleText2">Renseignements confidentiels</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-28"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-29"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>99 - </span><a href="#h-30"><span class="HTitleText1">Paiements aux provinces</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-31"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-32"><span class="HTitleText1">Cessation d’effet</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-33"><span class="HTitleText1">Affectation de versements</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-34"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-35"><span class="HTitleText1">Modifications à la Loi sur les licences d’exportation et d’importation</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-36"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="#h-37"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-38"><span class="HTitleText2">Loi sur l’Agence du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-39"><span class="HTitleText2">Loi sur la Cour canadienne de l’impôt</span></a>
</li></ul>
</li><li><span class='sectionRange'>125 - </span><a href="#h-40"><span class="HTitleText1">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-41"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-422705"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Personnes exemptées</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
