<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les poids et mesures</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-456984"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-456989"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-457009"><span class="HTitleText1">Approbation ministérielle des instruments</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-457017"><span class="HTitleText1">Unités de mesure</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-457047"><span class="HTitleText1">Emploi des unités de mesure</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-457054"><span class="HTitleText1">Utilisation des instruments</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-457061"><span class="HTitleText1">Marquage des marchandises</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-457072"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-457106"><span class="HTitleText1">Étalons de référence et étalons locaux</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-457134"><span class="HTitleText1">Examen des instruments</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-457150"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16.1 - </span><a href="#h-457151"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-457163"><span class="HTitleText2">Pouvoirs</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-457223"><span class="HTitleText1">Droits et frais d’examen</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-457240"><span class="HTitleText1">Pénalités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-457241"><span class="HTitleText2">Pouvoirs du gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>22.1 - </span><a href="#h-457252"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>22.11 - </span><a href="#h-457262"><span class="HTitleText2">Ouverture de la procédure</span></a>
</li>
<li><span class='sectionRange'>22.12 - </span><a href="#h-457279"><span class="HTitleText2">Pénalités</span></a>
</li>
<li><span class='sectionRange'>22.13 - </span><a href="#h-457291"><span class="HTitleText2">Transactions</span></a>
</li>
<li><span class='sectionRange'>22.15 - </span><a href="#h-457316"><span class="HTitleText2">Contestation devant le ministre</span></a>
</li>
<li><span class='sectionRange'>22.16 - </span><a href="#h-457330"><span class="HTitleText2">Recouvrement de créances</span></a>
</li>
<li><span class='sectionRange'>22.18 - </span><a href="#h-457352"><span class="HTitleText2">Règles propres aux violations</span></a>
</li>
<li><span class='sectionRange'>22.24 - </span><a href="#h-457380"><span class="HTitleText2">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-457403"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-457533"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-457556"><span class="HTitleText1">Saisie et rétention</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-457588"><span class="HTitleText1">Confiscation et restitution</span></a>
</li>
<li><a href="#h-457599"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Unités basées sur le Système international d’unités</span></a>
</li>
<li><a href="#h-457632"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Unités canadiennes de mesure</span></a>
</li>
<li><a href="#h-457672"><span class="scheduleLabel">ANNEXE III</span> </a>
</li>
<li><a href="#h-457682"><span class="scheduleLabel">ANNEXE IV</span> <span class="scheduleTitleText"> - Étalons de référence</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
