<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la pension de retraite des lieutenants-gouverneurs</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-337035"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-337040"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-337059"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Pension de retraite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-337060"><span class="HTitleText2">Prestations</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-337083"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-337093"><span class="HTitleText2">Choix de ne pas contribuer</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-337105"><span class="HTitleText2">Distraction de versements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-337113"><span class="HTitleText2">Conjoints survivants</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-337136"><span class="HTitleText2">Prestation consécutive au décès</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-337141"><span class="HTitleText2">Paiements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-337152"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-337168"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Contributions relatives aux prestations de retraite supplémentaires</span></a>
</li></ul>
</li></ul>

</nav>

