<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
An Act to establish the Corporation for the Mitigation of Mackenzie Gas Project Impacts <span class='Repealed'>[Repealed, 2013, c. 40, s. 287]</span></a></li></ul>
</nav>
</div></section>
