<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Textile Labelling Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-448588"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-448593"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-448619"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-448642"><span class="HTitleText1">Labels</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-448653"><span class="HTitleText1">Analysts</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-448658"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-448700"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-448726"><span class="HTitleText1">Offence and Punishment</span></a>
</li></ul>
</li></ul>

</nav>

