<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Status of the Artist Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-440259"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-440262"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General Principles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-440263"><span class="HTitleText2">Proclamation and Policy concerning the Status of the Artist</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="#h-440279"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Professional Relations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-440280"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-440298"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-440311"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-440314"><span class="HTitleText2">Freedom of Association</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-440317"><span class="HTitleText2">Exclusions and Presumptions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-440331"><span class="HTitleText2">Canada Industrial Relations Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-440338"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-440383"><span class="HTitleText3">Criteria for Application</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-440393"><span class="HTitleText3">Proceedings</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-440421"><span class="HTitleText3">Review and Enforcement of Determinations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-440438"><span class="HTitleText2">Certification of Artists’ Associations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-440439"><span class="HTitleText3">Prerequisites for Certification</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-440448"><span class="HTitleText3">Associations of Producers</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-440458"><span class="HTitleText3">Certification Procedure</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-440473"><span class="HTitleText3">Determination of Sector and Representativeness of an Association</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-440493"><span class="HTitleText3">Certification</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-440510"><span class="HTitleText3">Revocation of Certification</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-440526"><span class="HTitleText3">Successor Rights and Obligations</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-440534"><span class="HTitleText2">Bargaining and Scale Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-440535"><span class="HTitleText3">Notice to Bargain</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-440553"><span class="HTitleText3">Duration and Effect of Scale Agreements</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-440576"><span class="HTitleText3">Content and Interpretation of Scale Agreements</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-440638"><span class="HTitleText3">Compulsory Check-off</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-440641"><span class="HTitleText3">Settlement of Labour Disputes</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-440644"><span class="HTitleText2">Prohibitions and Remedies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-440645"><span class="HTitleText3">Pressure Tactics</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-440650"><span class="HTitleText3">Declarations respecting Pressure Tactics</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-440674"><span class="HTitleText3">Unfair Practices</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-440743"><span class="HTitleText3">Co-production Agreements</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-440749"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-440754"><span class="HTitleText3">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-440785"><span class="HTitleText3">Evidence</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-440794"><span class="HTitleText3">Miscellaneous</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>68 to 70 - </span><a href="#h-440814"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-440816"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
