<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi n<Sup>o</Sup> 1 sur le plan d’action économique de 2015</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-171691"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-171694"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Modification de la Loi de l’impôt sur le revenu et de textes connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-171695"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-171714"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-171722"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur le Régime de pensions du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-171724"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement sur la rémunération assurable et la perception des cotisations</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-171726"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Soutien aux familles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-171727"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-171734"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la prestation universelle pour la garde d’enfants</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-171735"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-171739"><span class="HTitleText3">Modifications connexes à la <cite class="XRefExternalAct">Loi sur les allocations spéciales pour enfants</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-171742"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-171745"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Diverses mesures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-171746"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi fédérale sur l’équilibre budgétaire</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-171747"><span class="HTitleText3">Édiction de la loi</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-171750"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la prévention des voyages de terroristes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-171751"><span class="HTitleText3">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-171754"><span class="HTitleText3">Modification connexe à la <cite class="XRefExternalAct">Loi sur la preuve au Canada</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="#h-171756"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Propriété intellectuelle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-171757"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les dessins industriels</cite></span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-171764"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les brevets</cite></span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-171781"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les marques de commerce</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-171788"><span class="HTitleText3">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-171791"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-171805"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Congé et prestations de soignant</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-171806"><span class="HTitleText3"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-171808"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-171814"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-171816"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>81 - </span><a href="#h-171819"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le droit d’auteur</cite></span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-171822"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le développement des exportations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="#h-171823"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-171827"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-171830"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Code canadien du travail</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>87 - </span><a href="#h-171831"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-171838"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="#h-171841"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les allocations de retraite des parlementaires</cite></span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-171845"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’Office national de l’énergie</cite></span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-171847"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Parlement du Canada</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="#h-171848"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-171850"><span class="HTitleText3">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-171875"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-171876"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la Société canadienne des postes</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-171878"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les Cours fédérales</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-171880"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-171882"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la saisie-arrêt et la distraction de pensions</cite></span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-171893"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’indemnisation des agents de l’État</cite></span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-171895"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la pension de la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-171897"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la radiocommunication</cite></span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-171899"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les relations de travail au Parlement</cite></span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-171904"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la santé des non-fumeurs</cite></span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-171906"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur les langues officielles</cite></span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-171913"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la rémunération du secteur public</cite></span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-171915"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur l’emploi dans la fonction publique</cite></span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-171917"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur le contrôle des dépenses</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-171919"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’assurance-emploi</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>153 - </span><a href="#h-171920"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-171926"><span class="HTitleText3">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-171928"><span class="HTitleText3">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-171929"><span class="HTitleText4"><cite class="XRefExternalAct">Loi sur la modernisation de certains régimes d’avantages et d’obligations</cite></span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-171931"><span class="HTitleText4"><cite class="XRefExternalAct">Loi d’exécution du budget de 2000</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="#h-171933"><span class="HLabel2">SECTION 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le financement des petites entreprises du Canada</cite></span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-171937"><span class="HLabel2">SECTION 13</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels et les documents électroniques</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-171941"><span class="HLabel2">SECTION 14</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-171943"><span class="HLabel2">SECTION 15</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’immigration et la protection des réfugiés</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>168 - </span><a href="#h-171944"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-171953"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>177 - </span><a href="#h-171959"><span class="HLabel2">SECTION 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion financière des premières nations</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="#h-171960"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-171989"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-171992"><span class="HLabel2">SECTION 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des Forces canadiennes</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-171993"><span class="HTitleText3">Modification de la loi</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-172014"><span class="HTitleText3">Modifications corrélatives à la <cite class="XRefExternalAct">Loi sur le Tribunal des anciens combattants (révision et appel)</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-172017"><span class="HTitleText3">Disposition de coordination</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-172019"><span class="HTitleText3">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>230 - </span><a href="#h-172022"><span class="HLabel2">SECTION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’abolition du registre des armes d’épaule</cite></span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="#h-172025"><span class="HLabel2">SECTION 19</span> - <span class="HTitleText2">Protection de renseignements relatifs à la supervision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>232 - </span><a href="#h-172026"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés de fiducie et de prêt</cite></span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-172028"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les banques</cite></span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-172032"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les sociétés d’assurances</cite></span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-172035"><span class="HTitleText3"><cite class="XRefExternalAct">Loi sur les associations coopératives de crédit</cite></span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-172037"><span class="HTitleText3">Dispositions transitoires</span></a>
</li></ul>
</li></ul>
</li><li><a href="#h-172074"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-172076"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

