<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Shipping Conferences Exemption Act, 1987</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-430992"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-430995"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-431020"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-431025"><span class="HTitleText1">Non-application of Competition Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-431061"><span class="HTitleText1">Filing of Documents</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-431086"><span class="HTitleText1">Giving of Notices</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-431098"><span class="HTitleText1">Disclosure of Service Contracts</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-431111"><span class="HTitleText1">Investigation of Complaints</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-431142"><span class="HTitleText1">Investigation of Conference</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-431152"><span class="HTitleText1">Inspection and Destruction of Documents</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-431160"><span class="HTitleText1">Offices</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-431165"><span class="HTitleText1">Inspection of Documents</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-431182"><span class="HTitleText1">Meetings</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-431185"><span class="HTitleText1">Designated Shipper Groups</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-431190"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-431204"><span class="HTitleText1">Security</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-431214"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-431224"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>26 and 27 - </span><a href="#h-431229"><span class="HTitleText1">Consequential and Related Amendments</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-431231"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-431233"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
