<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Public Works and Government Services Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Activities of the Department</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HTitleText1">Queen’s Printer</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-7"><span class="HTitleText1">Contracts</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText1">Beds of Navigable Waters</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-10"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-11"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>29 to 59 - </span><a href="#h-12"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-13"><span class="HTitleText1">References</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-14"><span class="HTitleText1">Conditional Amendment</span></a>
</li>
<li><span class='sectionRange'>63 to 66 - </span><a href="#h-15"><span class="HTitleText1">Repeals</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-16"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
