<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi modernisant le régime de l’emploi et des relations de travail dans la fonction publique, modifiant la Loi sur la gestion des finances publiques et la Loi sur le Centre canadien de gestion et apportant des modifications corrélatives à d’autres lois</a><ul class="TocIndent"><li><span class='sectionRange'>2 - </span><a href="page-1.html#h-397486"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-397488"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications à la Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-397498"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Loi sur l’emploi dans la fonction publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-1.html#h-397499"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Édiction de la loi</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-397503"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Modifications à la Loi sur l’emploi dans la fonction publique</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="page-1.html#h-397511"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Modifications à la Loi sur le Centre canadien de gestion</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-1.html#h-397527"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="page-1.html#h-397528"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Dispositions transitoires découlant de l’édiction de la Loi sur les relations de travail dans la fonction publique à la partie 1</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="page-1.html#h-397529"><span class="HTitleText3">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-1.html#h-397531"><span class="HTitleText3">Commission des relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-1.html#h-397543"><span class="HTitleText3">Agents négociateurs et unités de négociation</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-1.html#h-397546"><span class="HTitleText3">Poste de direction ou de confiance</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-1.html#h-397548"><span class="HTitleText3">Choix du mode de règlement des différends</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-1.html#h-397550"><span class="HTitleText3">Conventions collectives et décisions arbitrales</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-1.html#h-397553"><span class="HTitleText3">Conciliateurs et enquêteurs</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-1.html#h-397556"><span class="HTitleText3">Mode substitutif de règlement</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-1.html#h-397558"><span class="HTitleText3">Arbitrage</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-1.html#h-397560"><span class="HTitleText3">Désignations, conciliation et interdictions</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="page-1.html#h-397562"><span class="HTitleText3">Plaintes</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-1.html#h-397565"><span class="HTitleText3">Griefs</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="page-1.html#h-397572"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Disposition transitoire découlant des modifications à la Loi sur la gestion des finances publiques à la partie 2</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-1.html#h-397574"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Dispositions transitoires découlant de la partie 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="page-1.html#h-397576"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Dispositions transitoires découlant de l’édiction de la Loi sur l’emploi dans la fonction publique à la section 1 de la partie 3</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="page-1.html#h-397585"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Dispositions transitoires découlant des modifications de la Loi sur l’emploi dans la fonction publique à la section 2 de la partie 3</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="page-1.html#h-397594"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Dispositions transitoires découlant des modifications de la Loi sur le centre canadien de gestion à la partie 4</span></a>
</li></ul>
</li><li><span class='sectionRange'>88 - </span><a href="page-1.html#h-397598"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="page-1.html#h-397599"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Modifications corrélatives découlant de l’édiction de la Loi sur les relations de travail dans la fonction publique à la partie 1 et des modifications à la Loi sur la gestion des finances publiques à la partie 2</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="page-1.html#h-397600"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-1.html#h-397602"><span class="HTitleText3">Loi sur l’aéronautique</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-1.html#h-397604"><span class="HTitleText3">Loi sur le vérificateur général</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-1.html#h-397608"><span class="HTitleText3">Loi sur la Banque du Canada</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-1.html#h-397611"><span class="HTitleText3">Loi sur l’Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-1.html#h-397617"><span class="HTitleText3">Loi électorale du Canada</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="page-1.html#h-397622"><span class="HTitleText3">Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-1.html#h-397625"><span class="HTitleText3">Loi sur les grains du Canada</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="page-1.html#h-397627"><span class="HTitleText3">Code canadien du travail</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-1.html#h-397634"><span class="HTitleText3">Loi maritime du Canada</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-1.html#h-397637"><span class="HTitleText3">Loi sur la Société canadienne d’hypothèques et de logement</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-1.html#h-397640"><span class="HTitleText3">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="page-1.html#h-397646"><span class="HTitleText3">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="page-1.html#h-397652"><span class="HTitleText3">Loi sur les opérations pétrolières au Canada</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="page-1.html#h-397655"><span class="HTitleText3">Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="page-1.html#h-397658"><span class="HTitleText3">Loi fédérale sur les hydrocarbures</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="page-1.html#h-397660"><span class="HTitleText3">Loi sur l’École de la fonction publique du Canada</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="page-1.html#h-397664"><span class="HTitleText3">Loi sur la Corporation commerciale canadienne</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="page-1.html#h-397666"><span class="HTitleText3">Loi sur l’Agence canadienne d’inspection des aliments</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="page-1.html#h-397668"><span class="HTitleText3">Loi sur la pension de retraite des Forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-1.html#h-397670"><span class="HTitleText3">Loi canadienne sur les droits de la personne</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-1.html#h-397672"><span class="HTitleText3">Loi sur les Instituts de recherche en santé du Canada</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="page-1.html#h-397677"><span class="HTitleText3">Loi canadienne sur les paiements</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="page-1.html#h-397679"><span class="HTitleText3">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="page-1.html#h-397684"><span class="HTitleText3">Loi sur l’Agence spatiale canadienne</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="page-1.html#h-397686"><span class="HTitleText3">Loi sur les allocations spéciales pour enfants</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="page-1.html#h-397688"><span class="HTitleText3">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-1.html#h-397690"><span class="HTitleText3">Loi sur la commercialisation des services de navigation aérienne civile</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="page-1.html#h-397693"><span class="HTitleText3">Loi sur les coopératives de l’énergie</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="page-1.html#h-397696"><span class="HTitleText3">Loi sur le droit d’auteur</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="page-1.html#h-397698"><span class="HTitleText3">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="page-1.html#h-397700"><span class="HTitleText3">Loi sur le Service administratif des tribunaux judiciaires</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="page-1.html#h-397703"><span class="HTitleText3">Loi sur la production de défense</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="page-1.html#h-397706"><span class="HTitleText3">Loi sur le ministère du Développement des ressources humaines</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="page-1.html#h-397708"><span class="HTitleText3">Loi sur le ministère des Anciens Combattants</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="page-1.html#h-397710"><span class="HTitleText3">Loi sur la pension spéciale du service diplomatique</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="page-1.html#h-397712"><span class="HTitleText3">Loi sur l’équité en matière d’emploi</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="page-2.html#h-397716"><span class="HTitleText3">Loi sur les offices des produits agricoles</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-2.html#h-397718"><span class="HTitleText3">Loi sur la Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="page-2.html#h-397720"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-2.html#h-397722"><span class="HTitleText3">Loi sur l’Agence de la consommation en matière financière du Canada</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="page-2.html#h-397725"><span class="HTitleText3">Loi sur le contrôle des renseignements relatifs aux matières dangereuses</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-2.html#h-397727"><span class="HTitleText3">Loi sur l’immigration et la protection des réfugiés</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="page-2.html#h-397730"><span class="HTitleText3">Loi sur les enquêtes</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="page-2.html#h-397732"><span class="HTitleText3">Loi sur le cinéma</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="page-2.html#h-397734"><span class="HTitleText3">Loi sur la santé des non-fumeurs</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-2.html#h-397736"><span class="HTitleText3">Loi sur le Bureau du surintendant des institutions financières</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="page-2.html#h-397738"><span class="HTitleText3">Loi sur la sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="page-2.html#h-397741"><span class="HTitleText3">Loi sur l’Agence Parcs Canada</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="page-2.html#h-397744"><span class="HTitleText3">Loi sur les relations de travail au Parlement</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-2.html#h-397751"><span class="HTitleText3">Loi sur les pensions</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-2.html#h-397753"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="page-2.html#h-397755"><span class="HTitleText3">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-2.html#h-397758"><span class="HTitleText3">Loi sur l’emploi dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="page-2.html#h-397774"><span class="HTitleText3">Loi sur les restructurations et les transferts d’attributions dans l’administration publique</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="page-2.html#h-397777"><span class="HTitleText3">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="page-2.html#h-397784"><span class="HTitleText3">Loi sur la publication des lois</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="page-2.html#h-397786"><span class="HTitleText3">Loi sur la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="page-2.html#h-397789"><span class="HTitleText3">Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="page-2.html#h-397791"><span class="HTitleText3">Loi sur le parc marin du Saguenay — Saint-Laurent</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="page-2.html#h-397793"><span class="HTitleText3">Loi sur le statut de l’artiste</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="page-2.html#h-397796"><span class="HTitleText3">Loi sur les allocations aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="page-2.html#h-397798"><span class="HTitleText3">Modifications terminologiques</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="page-2.html#h-397803"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Modifications corrélatives découlant de la partie 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>227 - </span><a href="page-2.html#h-397804"><span class="HLabel3">SOUS-SECTION A</span> - <span class="HTitleText3">Modifications corrélatives découlant de l’édiction de la Loi sur l’emploi dans la fonction publique à la section 1 de la partie 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>227 - </span><a href="page-2.html#h-397805"><span class="HTitleText4">Loi sur le vérificateur général</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-2.html#h-397808"><span class="HTitleText4">Loi sur l’Agence des douanes et du revenu du Canada</span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="page-2.html#h-397811"><span class="HTitleText4">Loi de mise en oeuvre de l’Accord atlantique Canada — Terre-Neuve</span></a>
</li>
<li><span class='sectionRange'>232 - </span><a href="page-2.html#h-397813"><span class="HTitleText4">Loi de mise en oeuvre de l’Accord Canada — Nouvelle-Écosse sur les hydrocarbures extracôtiers</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="page-2.html#h-397815"><span class="HTitleText4">Loi sur les Instituts de recherche en santé du Canada</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="page-2.html#h-397817"><span class="HTitleText4">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="page-2.html#h-397819"><span class="HTitleText4">Loi sur l’Agence spatiale canadienne</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="page-2.html#h-397821"><span class="HTitleText4">Loi sur l’équité en matière d’emploi</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="page-2.html#h-397825"><span class="HTitleText4">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="page-2.html#h-397827"><span class="HTitleText4">Loi sur le cinéma</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="page-2.html#h-397829"><span class="HTitleText4">Loi sur l’Agence Parcs Canada</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="page-2.html#h-397831"><span class="HTitleText4">Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="page-2.html#h-397833"><span class="HTitleText4">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="page-2.html#h-397835"><span class="HTitleText4">Loi référendaire</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="page-2.html#h-397837"><span class="HTitleText4">Loi sur les avantages destinés aux anciens combattants</span></a>
</li></ul>
</li><li><span class='sectionRange'>246 - </span><a href="page-2.html#h-397839"><span class="HLabel3">SOUS-SECTION B</span> - <span class="HTitleText3">Modifications corrélatives découlant des modifications de la Loi sur l’emploi dans la fonction publique à la section 2 de la partie 3</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>246 - </span><a href="page-2.html#h-397840"><span class="HTitleText4">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="page-2.html#h-397842"><span class="HTitleText4">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="page-2.html#h-397844"><span class="HTitleText4">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="page-2.html#h-397846"><span class="HTitleText4">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-2.html#h-397848"><span class="HTitleText4">Loi sur la pension de la fonction publique</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>251 - </span><a href="page-2.html#h-397850"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Modifications corrélatives découlant des modifications à la Loi sur le centre canadien de gestion à la partie 4</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>251 - </span><a href="page-2.html#h-397851"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="page-2.html#h-397854"><span class="HTitleText3">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="page-2.html#h-397857"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="page-2.html#h-397860"><span class="HTitleText3">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="page-2.html#h-397863"><span class="HTitleText3">Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="page-2.html#h-397866"><span class="HTitleText3">Loi sur les fonds renouvelables</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>262 - </span><a href="page-2.html#h-397868"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Dispositions de coordination</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>262 - </span><a href="page-2.html#h-397869"><span class="HTitleText2">Loi sur la modernisation de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="page-2.html#h-397872"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="page-2.html#h-397878"><span class="HTitleText2">Loi sur l’emploi dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="page-2.html#h-397881"><span class="HTitleText2">Loi sur l’emploi dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>273 - </span><a href="page-2.html#h-397884"><span class="HTitleText2">Loi sur les relations de travail dans la fonction publique</span></a>
</li>
<li><span class='sectionRange'>276 - </span><a href="page-2.html#h-397888"><span class="HTitleText2">Loi sur le Yukon</span></a>
</li>
<li><span class='sectionRange'>277 - </span><a href="page-2.html#h-397890"><span class="HTitleText2">Projet de loi C-2</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-2.html#h-397892"><span class="HTitleText2">Projet de loi C-6</span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="page-2.html#h-397894"><span class="HTitleText2">Projet de loi C-12</span></a>
</li>
<li><span class='sectionRange'>280 - </span><a href="page-2.html#h-397896"><span class="HTitleText2">Projet de loi C-13</span></a>
</li>
<li><span class='sectionRange'>281 - </span><a href="page-2.html#h-397898"><span class="HTitleText2">Projet de loi C-17</span></a>
</li>
<li><span class='sectionRange'>282 - </span><a href="page-2.html#h-397900"><span class="HTitleText2">Projet de loi C-18</span></a>
</li>
<li><span class='sectionRange'>283 - </span><a href="page-2.html#h-397902"><span class="HTitleText2">Projet de loi C-19</span></a>
</li></ul>
</li><li><span class='sectionRange'>284 - </span><a href="page-2.html#h-397904"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>286 - </span><a href="page-2.html#h-397907"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="page-3.html#h-397914"><span class="scheduleLabel">ANNEXE 1</span></a>
</li>
<li><a href="page-4.html#h-397917"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

