<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act respecting first nations goods and services tax</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">First Nations Goods and Services Tax Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Application of other Acts of Parliament</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">First Nation Goods and Services Tax Law</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText2">First Nation Law Enacted Under Separate Power</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText2">Administration Agreement and Part IX of Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">First Nations Sales Tax — Quebec</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText2">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-13"><span class="HTitleText2">Administration Agreement</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText2">Delegation</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><a href="#h-16"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-17"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
