<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la maison Laurier (Laurier House)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-336143"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><a href="page-2.html#h-336179"><span class="scheduleLabel">PREMIÈRE ANNEXE</span> - <span class="scheduleTitleText"> - (Traduction)</span> - <span class="scheduleTitleText"> - Description de la propriété « Laurier House » :</span></a>
</li>
<li><a href="page-3.html#h-336184"><span class="scheduleLabel">SECONDE ANNEXE</span> - <span class="scheduleTitleText"> - (Traduction)</span> - <span class="scheduleTitleText"> - Extrait du testament de M. King :</span></a>
</li></ul>
</li></ul>

</nav>

