<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le cheval national du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-350433"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-350436"><span class="HTitleText1">Le cheval national</span></a>
</li></ul>
</li></ul>

</nav>

