<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Controlled Drugs and Substances Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-94341"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-94344"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-94405"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Offences and Punishment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="page-1.html#h-94406"><span class="HTitleText2">Particular Offences</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-94549"><span class="HTitleText2">Notice</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-94554"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-94562"><span class="HTitleText2">Sentencing</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-94585"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-3.html#h-94632"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Disposition</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-3.html#h-94645"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Non-chemical Offence-related Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-3.html#h-94646"><span class="HTitleText3">Restraint Orders</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="page-3.html#h-94683"><span class="HTitleText3">Management Orders</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-3.html#h-94719"><span class="HTitleText3">Forfeiture</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="page-4.html#h-94822"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Controlled Substances, Precursors and Chemical Offence-related Property</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-5.html#h-94883"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Administration and Compliance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="page-5.html#h-94884"><span class="HTitleText2">Inspectors</span></a>
</li></ul>
</li><li><span class='sectionRange'>33 - </span><a href="page-5.html#h-94953"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Administrative Orders for Contraventions of Designated Regulations</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-6.html#h-95021"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-6.html#h-95022"><span class="HTitleText2">Analysis</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="page-6.html#h-95032"><span class="HTitleText2">Ministerial Orders</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-6.html#h-95078"><span class="HTitleText2">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="page-6.html#h-95085"><span class="HTitleText2">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-6.html#h-95117"><span class="HTitleText2">Evidence and Procedure</span></a>
</li>
<li><span class='sectionRange'>54.1 - </span><a href="page-7.html#h-95166"><span class="HTitleText2">Technical Assistance</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-7.html#h-95171"><span class="HTitleText2">Regulations and Exemptions</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-8.html#h-95268"><span class="HTitleText2">Miscellaneous</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-8.html#h-95276"><span class="HTitleText2">Amendments to Schedules</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-8.html#h-95292"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Transitional Provisions, Consequential and Conditional Amendments, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>61 - </span><a href="page-8.html#h-95293"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>64 to 93.1 - </span><a href="page-8.html#h-95305"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>93.2 and 93.3 - </span><a href="page-8.html#h-95307"><span class="HTitleText2">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-8.html#h-95309"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-8.html#h-95311"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-9.html#h-95315"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="page-10.html#h-95541"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li>
<li><a href="page-11.html#h-95603"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li>
<li><a href="page-12.html#h-95661"><span class="scheduleLabel">SCHEDULE IV</span> </a>
</li>
<li><a href="page-13.html#h-95820"><span class="scheduleLabel">SCHEDULE V</span> </a>
</li>
<li><a href="page-14.html#h-95824"><span class="scheduleLabel">SCHEDULE VI</span> </a>
</li>
<li><a href="page-15.html#h-95881"><span class="scheduleLabel">SCHEDULE VII</span></a>
</li>
<li><a href="page-16.html#h-95884"><span class="scheduleLabel">SCHEDULE VIII</span></a>
</li>
<li><a href="page-17.html#h-95887"><span class="scheduleLabel">SCHEDULE IX</span> </a>
</li></ul>
</li></ul>

</nav>

