<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canadian Radio-television and Telecommunications Commission Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-74763"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-74768"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-74785"><span class="HTitleText1">Establishment and Constitution of Commission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-74810"><span class="HTitleText1">Chairperson and Vice-chairpersons</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-74822"><span class="HTitleText1">Remuneration</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-74830"><span class="HTitleText1">Staff</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-74835"><span class="HTitleText1">Superannuation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-74843"><span class="HTitleText1">Offices, Meetings and Residence</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-74864"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-74875"><span class="HTitleText1">Objects, Powers, Duties and Functions</span></a>
</li></ul>
</li></ul>

</nav>

