<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Criminal Code</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-115006"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-115011"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-115244"><span class="HTitleText1">Part I</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3.1 - </span><a href="#h-115245"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-115570"><span class="HTitleText2">Parties to Offences</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-115622"><span class="HTitleText2">Protection of Persons Administering and Enforcing the Law</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-115792"><span class="HTitleText2">Suppression of Riots</span></a>
</li>
<li><span class='sectionRange'>33.1 - </span><a href="#h-115821"><span class="HTitleText2">Self-induced Intoxication</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-115831"><span class="HTitleText2">Defence of Person</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-115853"><span class="HTitleText2">Defence of Property</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-115879"><span class="HTitleText2">Protection of Persons in Authority</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-115891"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Offences Against Public Order</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-115892"><span class="HTitleText2">Treason and other Offences against the Queen’s Authority and Person</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-115937"><span class="HTitleText2">Prohibited Acts</span></a>
</li>
<li><span class='sectionRange'>56.1 - </span><a href="#h-115997"><span class="HTitleText2">Official Documents</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-116054"><span class="HTitleText2">Sedition</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-116101"><span class="HTitleText2">Unlawful Assemblies and Riots</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-116152"><span class="HTitleText2">Unlawful Drilling</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-116167"><span class="HTitleText2">Duels</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-116169"><span class="HTitleText2">Forcible Entry and Detainer</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-116187"><span class="HTitleText2">Piracy</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-116204"><span class="HTitleText2">Offences against Air or Maritime Safety</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-116256"><span class="HTitleText2">Dangerous Materials and Devices</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-116323"><span class="HTitleText2">Prize Fights</span></a>
</li></ul>
</li><li><span class='sectionRange'>83.01 - </span><a href="#h-116339"><span class="HLabel1">PART II.1</span> - <span class="HTitleText1">Terrorism</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83.01 - </span><a href="#h-116340"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>83.02 - </span><a href="#h-116382"><span class="HTitleText2">Financing of Terrorism</span></a>
</li>
<li><span class='sectionRange'>83.05 - </span><a href="#h-116404"><span class="HTitleText2">List of Entities</span></a>
</li>
<li><span class='sectionRange'>83.08 - </span><a href="#h-116461"><span class="HTitleText2">Freezing of Property</span></a>
</li>
<li><span class='sectionRange'>83.13 - </span><a href="#h-116524"><span class="HTitleText2">Seizure and Restraint of Property</span></a>
</li>
<li><span class='sectionRange'>83.14 - </span><a href="#h-116570"><span class="HTitleText2">Forfeiture of Property</span></a>
</li>
<li><span class='sectionRange'>83.18 - </span><a href="#h-116622"><span class="HTitleText2">Participating, Facilitating, Instructing and Harbouring</span></a>
</li>
<li><span class='sectionRange'>83.231 - </span><a href="#h-116779"><span class="HTitleText2">Hoax Regarding Terrorist Activity</span></a>
</li>
<li><span class='sectionRange'>83.24 - </span><a href="#h-116797"><span class="HTitleText2">Proceedings and Aggravated Punishment</span></a>
</li>
<li><span class='sectionRange'>83.3 - </span><a href="#h-116877"><span class="HTitleText2">Recognizance with Conditions</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-117002"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Firearms and Other Weapons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-117003"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-117102"><span class="HTitleText2">Use Offences</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-117146"><span class="HTitleText2">Possession Offences</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-117305"><span class="HTitleText2">Trafficking Offences</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-117343"><span class="HTitleText2">Assembling Offence</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-117353"><span class="HTitleText2">Export and Import Offences</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-117384"><span class="HTitleText2">Offences relating to Lost, Destroyed or Defaced Weapons, etc.</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-117434"><span class="HTitleText2">Prohibition Orders</span></a>
</li>
<li><span class='sectionRange'>117.011 - </span><a href="#h-117580"><span class="HTitleText2">Limitations on Access</span></a>
</li>
<li><span class='sectionRange'>117.02 - </span><a href="#h-117608"><span class="HTitleText2">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>117.07 - </span><a href="#h-117679"><span class="HTitleText2">Exempted Persons</span></a>
</li>
<li><span class='sectionRange'>117.11 - </span><a href="#h-117741"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="#h-117787"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Offences Against the Administration of Law and Justice</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>118 - </span><a href="#h-117788"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-117813"><span class="HTitleText2">Corruption and Disobedience</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-117964"><span class="HTitleText2">Misleading Justice</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-118061"><span class="HTitleText2">Escapes and Rescues</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-118141"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Sexual Offences, Public Morals and Disorderly Conduct</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-118142"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>150.1 - </span><a href="#h-118150"><span class="HTitleText2">Sexual Offences</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-118363"><span class="HTitleText2">Offences Tending to Corrupt Morals</span></a>
</li>
<li><span class='sectionRange'>172.2 - </span><a href="#h-118604"><span class="HTitleText2">Disorderly Conduct</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-118691"><span class="HTitleText2">Nuisances</span></a>
</li></ul>
</li><li><span class='sectionRange'>183 - </span><a href="#h-118715"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Invasion of Privacy</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>183 - </span><a href="#h-118716"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-118925"><span class="HTitleText2">Interception of Communications</span></a>
</li></ul>
</li><li><span class='sectionRange'>197 - </span><a href="#h-119349"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Disorderly Houses, Gaming and Betting</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-119350"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-119394"><span class="HTitleText2">Presumptions</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-119396"><span class="HTitleText2">Search</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-119416"><span class="HTitleText2">Obstruction</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-119418"><span class="HTitleText2">Gaming and Betting</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-119650"><span class="HTitleText2">Offences in Relation to Offering, Providing or Obtaining Sexual Services for Consideration</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-119663"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Offences Against the Person and Reputation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-119664"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-119680"><span class="HTitleText2">Duties Tending to Preservation of Life</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-119725"><span class="HTitleText2">Criminal Negligence</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-119746"><span class="HTitleText2">Homicide</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-119808"><span class="HTitleText2">Murder, Manslaughter and Infanticide</span></a>
</li>
<li><span class='sectionRange'>241 - </span><a href="#h-119931"><span class="HTitleText2">Suicide</span></a>
</li>
<li><span class='sectionRange'>241.1 - </span><a href="#h-119953"><span class="HTitleText2">Medical Assistance in Dying</span></a>
</li>
<li><span class='sectionRange'>242 - </span><a href="#h-120062"><span class="HTitleText2">Neglect in Child-birth and Concealing Dead Body</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-120071"><span class="HTitleText2">Bodily Harm and Acts and Omissions Causing Danger to the Person</span></a>
</li>
<li><span class='sectionRange'>264.1 - </span><a href="#h-120223"><span class="HTitleText2">Assaults</span></a>
</li>
<li><span class='sectionRange'>279 - </span><a href="#h-120700"><span class="HTitleText2">Kidnapping, Trafficking in Persons, Hostage Taking and Abduction</span></a>
</li>
<li><span class='sectionRange'>286.1 - </span><a href="#h-120840"><span class="HTitleText2">Commodification of Sexual Activity</span></a>
</li>
<li><span class='sectionRange'>287 - </span><a href="#h-120918"><span class="HTitleText2">Abortion</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="#h-120958"><span class="HTitleText2">Venereal Diseases</span></a>
</li>
<li><span class='sectionRange'>290 - </span><a href="#h-120960"><span class="HTitleText2">Offences Against Conjugal Rights</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-121018"><span class="HTitleText2">Unlawful Solemnization of Marriage</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-121030"><span class="HTitleText2">Defamatory Libel</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="#h-121171"><span class="HTitleText2">Verdicts</span></a>
</li>
<li><span class='sectionRange'>318 - </span><a href="#h-121176"><span class="HTitleText2">Hate Propaganda</span></a>
</li>
<li><span class='sectionRange'>320.101 - </span><a href="#h-1336410"><span class="HTitleText2">Conversion Therapy</span></a>
</li></ul>
</li><li><span class='sectionRange'>320.11 - </span><a href="#h-121277"><span class="HLabel1">PART VIII.1</span> - <span class="HTitleText1">Offences Relating to Conveyances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>320.11 - </span><a href="#h-121278"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>320.12 - </span><a href="#h-121299"><span class="HTitleText2">Recognition and Declaration</span></a>
</li>
<li><span class='sectionRange'>320.13 - </span><a href="#h-121308"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>320.27 - </span><a href="#h-121487"><span class="HTitleText2">Investigative Matters</span></a>
</li>
<li><span class='sectionRange'>320.31 - </span><a href="#h-121560"><span class="HTitleText2">Evidentiary Matters</span></a>
</li>
<li><span class='sectionRange'>320.36 - </span><a href="#h-121635"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>321 - </span><a href="#h-121681"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Offences Against Rights of Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>321 - </span><a href="#h-121682"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="#h-121703"><span class="HTitleText2">Theft</span></a>
</li>
<li><span class='sectionRange'>335 - </span><a href="#h-121811"><span class="HTitleText2">Offences Resembling Theft</span></a>
</li>
<li><span class='sectionRange'>343 - </span><a href="#h-121951"><span class="HTitleText2">Robbery and Extortion</span></a>
</li>
<li><span class='sectionRange'>347 - </span><a href="#h-122004"><span class="HTitleText2">Criminal Interest Rate</span></a>
</li>
<li><span class='sectionRange'>348 - </span><a href="#h-122049"><span class="HTitleText2">Breaking and Entering</span></a>
</li>
<li><span class='sectionRange'>354 - </span><a href="#h-122146"><span class="HTitleText2">Possession and Trafficking</span></a>
</li>
<li><span class='sectionRange'>361 - </span><a href="#h-122229"><span class="HTitleText2">False Pretences</span></a>
</li>
<li><span class='sectionRange'>366 - </span><a href="#h-122291"><span class="HTitleText2">Forgery and Offences Resembling Forgery</span></a>
</li></ul>
</li><li><span class='sectionRange'>379 - </span><a href="#h-122418"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Fraudulent Transactions Relating to Contracts and Trade</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>379 - </span><a href="#h-122419"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="#h-122424"><span class="HTitleText2">Fraud</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="#h-122658"><span class="HTitleText2">Falsification of Books and Documents</span></a>
</li>
<li><span class='sectionRange'>402.1 - </span><a href="#h-122702"><span class="HTitleText2">Identity Theft and Identity Fraud</span></a>
</li>
<li><span class='sectionRange'>406 - </span><a href="#h-122752"><span class="HTitleText2">Forgery of Trademarks and Trade Descriptions</span></a>
</li>
<li><span class='sectionRange'>415 - </span><a href="#h-122804"><span class="HTitleText2">Wreck</span></a>
</li>
<li><span class='sectionRange'>416 - </span><a href="#h-122817"><span class="HTitleText2">Public Stores</span></a>
</li>
<li><span class='sectionRange'>422 - </span><a href="#h-122869"><span class="HTitleText2">Breach of Contract, Intimidation and Discrimination Against Trade Unionists</span></a>
</li>
<li><span class='sectionRange'>426 - </span><a href="#h-122942"><span class="HTitleText2">Secret Commissions</span></a>
</li></ul>
</li><li><span class='sectionRange'>428 - </span><a href="#h-122960"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Wilful and Forbidden Acts in Respect of Certain Property</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>428 - </span><a href="#h-122961"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="#h-122977"><span class="HTitleText2">Mischief</span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="#h-123081"><span class="HTitleText2">Arson and Other Fires</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="#h-123114"><span class="HTitleText2">Other Interference with Property</span></a>
</li>
<li><span class='sectionRange'>444 - </span><a href="#h-123162"><span class="HTitleText2">Animals</span></a>
</li>
<li><span class='sectionRange'>445.1 - </span><a href="#h-123192"><span class="HTitleText2">Cruelty to Animals</span></a>
</li></ul>
</li><li><span class='sectionRange'>448 - </span><a href="#h-123246"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Offences Relating to Currency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>448 - </span><a href="#h-123247"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>449 - </span><a href="#h-123262"><span class="HTitleText2">Making</span></a>
</li>
<li><span class='sectionRange'>450 - </span><a href="#h-123267"><span class="HTitleText2">Possession</span></a>
</li>
<li><span class='sectionRange'>452 - </span><a href="#h-123282"><span class="HTitleText2">Uttering</span></a>
</li>
<li><span class='sectionRange'>455 - </span><a href="#h-123300"><span class="HTitleText2">Defacing or Impairing</span></a>
</li>
<li><span class='sectionRange'>458 - </span><a href="#h-123333"><span class="HTitleText2">Instruments or Materials</span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="#h-123345"><span class="HTitleText2">Advertising and Trafficking in Counterfeit Money or Counterfeit Tokens of Value</span></a>
</li>
<li><span class='sectionRange'>461 - </span><a href="#h-123356"><span class="HTitleText2">Special Provisions as to Proof</span></a>
</li>
<li><span class='sectionRange'>462 - </span><a href="#h-123368"><span class="HTitleText2">Forfeiture</span></a>
</li></ul>
</li><li><span class='sectionRange'>462.1 - </span><a href="#h-123380"><span class="HLabel1">PART XII.1</span> - <span class="HTitleText1">[Repealed, 2018, c. 16, s. 211]</span></a>
</li>
<li><span class='sectionRange'>462.3 - </span><a href="#h-123383"><span class="HLabel1">PART XII.2</span> - <span class="HTitleText1">Proceeds of Crime</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>462.3 - </span><a href="#h-123384"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>462.31 - </span><a href="#h-123410"><span class="HTitleText2">Offence</span></a>
</li>
<li><span class='sectionRange'>462.32 - </span><a href="#h-123424"><span class="HTitleText2">Search, Seizure and Detention of Proceeds of Crime</span></a>
</li>
<li><span class='sectionRange'>462.37 - </span><a href="#h-123592"><span class="HTitleText2">Forfeiture of Proceeds of Crime</span></a>
</li>
<li><span class='sectionRange'>462.47 - </span><a href="#h-123765"><span class="HTitleText2">Disclosure Provisions</span></a>
</li>
<li><span class='sectionRange'>462.49 - </span><a href="#h-123834"><span class="HTitleText2">Specific Rules of Forfeiture</span></a>
</li>
<li><span class='sectionRange'>462.5 - </span><a href="#h-123842"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>463 - </span><a href="#h-123847"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Attempts — Conspiracies — Accessories</span></a>
</li>
<li><span class='sectionRange'>468 - </span><a href="#h-123975"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Jurisdiction</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>468 - </span><a href="#h-123976"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>476 - </span><a href="#h-124048"><span class="HTitleText2">Special Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>482 - </span><a href="#h-124166"><span class="HTitleText2">Rules of Court</span></a>
</li></ul>
</li><li><span class='sectionRange'>483 - </span><a href="#h-124222"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">Special Procedure and Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>483 - </span><a href="#h-124223"><span class="HTitleText2">General Powers of Certain Officials</span></a>
</li>
<li><span class='sectionRange'>487.04 - </span><a href="#h-124748"><span class="HTitleText2">Forensic DNA Analysis</span></a>
</li>
<li><span class='sectionRange'>487.1 - </span><a href="#h-125193"><span class="HTitleText2">Other Provisions Respecting Search Warrants, Preservation Orders and Production Orders</span></a>
</li>
<li><span class='sectionRange'>490.011 - </span><a href="#h-125497"><span class="HTitleText2">Sex Offender Information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>490.011 - </span><a href="#h-125498"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>490.012 - </span><a href="#h-125591"><span class="HTitleText3">Order to Comply with the <cite class="XRefExternalAct">Sex Offender Information Registration Act</cite></span></a>
</li>
<li><span class='sectionRange'>490.019 - </span><a href="#h-125690"><span class="HTitleText3">Notice and Obligation to Comply with the <cite class="XRefExternalAct">Sex Offender Information Registration Act</cite> — Convictions Before December 15, 2004</span></a>
</li>
<li><span class='sectionRange'>490.02901 - </span><a href="#h-125811"><span class="HTitleText3">Notice and Obligation to Comply with the <cite class="XRefExternalAct">Sex Offender Information Registration Act</cite> — Convictions Outside Canada</span></a>
</li>
<li><span class='sectionRange'>490.02912 - </span><a href="#h-125921"><span class="HTitleText3"><cite class="XRefExternalAct">International Transfer of Offenders Act</cite></span></a>
</li>
<li><span class='sectionRange'>490.03 - </span><a href="#h-125961"><span class="HTitleText3">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>490.031 - </span><a href="#h-125974"><span class="HTitleText3">Offences</span></a>
</li>
<li><span class='sectionRange'>490.032 - </span><a href="#h-126000"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>490.1 - </span><a href="#h-126007"><span class="HTitleText2">Forfeiture of Offence-related Property</span></a>
</li></ul>
</li><li><span class='sectionRange'>493 - </span><a href="#h-126302"><span class="HLabel1">PART XVI</span> - <span class="HTitleText1">Compelling Appearance of Accused Before a Justice and Interim Release</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>493 - </span><a href="#h-126303"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>493.1 - </span><a href="#h-1212559"><span class="HTitleText2">Principle and Considerations</span></a>
</li>
<li><span class='sectionRange'>494 - </span><a href="#h-126325"><span class="HTitleText2">Arrest without Warrant and Release from Custody</span></a>
</li>
<li><span class='sectionRange'>502.1 - </span><a href="#h-126468"><span class="HTitleText2">Appearance of Accused before Justice</span></a>
</li>
<li><span class='sectionRange'>504 - </span><a href="#h-126519"><span class="HTitleText2">Information, Summons and Warrant</span></a>
</li>
<li><span class='sectionRange'>515 - </span><a href="#h-126679"><span class="HTitleText2">Judicial Interim Release</span></a>
</li>
<li><span class='sectionRange'>523.1 - </span><a href="#h-126931"><span class="HTitleText2">Proceedings Respecting Failure to Comply with Release Conditions</span></a>
</li>
<li><span class='sectionRange'>525 - </span><a href="#h-126975"><span class="HTitleText2">Review of Detention where Trial Delayed</span></a>
</li>
<li><span class='sectionRange'>527 - </span><a href="#h-127018"><span class="HTitleText2">Procedure to Procure Attendance of a Prisoner</span></a>
</li>
<li><span class='sectionRange'>528 - </span><a href="#h-127046"><span class="HTitleText2">Endorsement of Warrant</span></a>
</li>
<li><span class='sectionRange'>529 - </span><a href="#h-127056"><span class="HTitleText2">Powers to Enter Dwelling-houses to Carry out Arrests</span></a>
</li></ul>
</li><li><span class='sectionRange'>530 - </span><a href="#h-127103"><span class="HLabel1">PART XVII</span> - <span class="HTitleText1">Language of Accused</span></a>
</li>
<li><span class='sectionRange'>535 - </span><a href="#h-127180"><span class="HLabel1">PART XVIII</span> - <span class="HTitleText1">Procedure on Preliminary Inquiry</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>535 - </span><a href="#h-127181"><span class="HTitleText2">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>536.3 - </span><a href="#h-127238"><span class="HTitleText2">Procedures before Preliminary Inquiry</span></a>
</li>
<li><span class='sectionRange'>537 - </span><a href="#h-127259"><span class="HTitleText2">Powers of Justice</span></a>
</li>
<li><span class='sectionRange'>539 - </span><a href="#h-127288"><span class="HTitleText2">Taking Evidence of Witnesses</span></a>
</li>
<li><span class='sectionRange'>543 - </span><a href="#h-127360"><span class="HTitleText2">Remand Where Offence Committed in Another Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>544 - </span><a href="#h-127373"><span class="HTitleText2">Absconding Accused</span></a>
</li>
<li><span class='sectionRange'>545 - </span><a href="#h-127392"><span class="HTitleText2">Procedure where Witness Refuses to Testify</span></a>
</li>
<li><span class='sectionRange'>546 - </span><a href="#h-127407"><span class="HTitleText2">Remedial Provisions</span></a>
</li>
<li><span class='sectionRange'>548 - </span><a href="#h-127425"><span class="HTitleText2">Adjudication and Recognizances</span></a>
</li>
<li><span class='sectionRange'>551 - </span><a href="#h-127463"><span class="HTitleText2">Transmission of Record</span></a>
</li></ul>
</li><li><span class='sectionRange'>551.1 - </span><a href="#h-127468"><span class="HLabel1">PART XVIII.1</span> - <span class="HTitleText1">Case Management Judge</span></a>
</li>
<li><span class='sectionRange'>552 - </span><a href="#h-127562"><span class="HLabel1">PART XIX</span> - <span class="HTitleText1">Indictable Offences — Trial Without Jury</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>552 - </span><a href="#h-127563"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>553 - </span><a href="#h-127581"><span class="HTitleText2">Jurisdiction of Provincial Court Judges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>553 - </span><a href="#h-127582"><span class="HTitleText3">Absolute Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>554 - </span><a href="#h-127612"><span class="HTitleText3">Provincial Court Judge’s Jurisdiction with Consent</span></a>
</li></ul>
</li><li><span class='sectionRange'>558 - </span><a href="#h-127661"><span class="HTitleText2">Jurisdiction of Judges</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>558 - </span><a href="#h-127662"><span class="HTitleText3">Judge’s Jurisdiction with Consent</span></a>
</li>
<li><span class='sectionRange'>560 - </span><a href="#h-127674"><span class="HTitleText3">Election</span></a>
</li>
<li><span class='sectionRange'>566 - </span><a href="#h-127793"><span class="HTitleText3">Trial</span></a>
</li></ul>
</li><li><span class='sectionRange'>567 - </span><a href="#h-127814"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>573 - </span><a href="#h-127860"><span class="HLabel1">PART XIX.1</span> - <span class="HTitleText1">Nunavut Court of Justice</span></a>
</li>
<li><span class='sectionRange'>574 - </span><a href="#h-127935"><span class="HLabel1">PART XX</span> - <span class="HTitleText1">Procedure in Jury Trials and General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>574 - </span><a href="#h-127936"><span class="HTitleText2">Preferring Indictment</span></a>
</li>
<li><span class='sectionRange'>581 - </span><a href="#h-128004"><span class="HTitleText2">General Provisions respecting Counts</span></a>
</li>
<li><span class='sectionRange'>584 - </span><a href="#h-128039"><span class="HTitleText2">Special Provisions respecting Counts</span></a>
</li>
<li><span class='sectionRange'>587 - </span><a href="#h-128062"><span class="HTitleText2">Particulars</span></a>
</li>
<li><span class='sectionRange'>588 - </span><a href="#h-128082"><span class="HTitleText2">Ownership of Property</span></a>
</li>
<li><span class='sectionRange'>589 - </span><a href="#h-128087"><span class="HTitleText2">Joinder or Severance of Counts</span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-128131"><span class="HTitleText2">Joinder of Accused in Certain Cases</span></a>
</li>
<li><span class='sectionRange'>597 - </span><a href="#h-128148"><span class="HTitleText2">Proceedings when Person Indicted is at Large</span></a>
</li>
<li><span class='sectionRange'>599 - </span><a href="#h-128177"><span class="HTitleText2">Change of Venue</span></a>
</li>
<li><span class='sectionRange'>601 - </span><a href="#h-128196"><span class="HTitleText2">Amendment</span></a>
</li>
<li><span class='sectionRange'>603 - </span><a href="#h-128243"><span class="HTitleText2">Inspection and Copies of Documents</span></a>
</li>
<li><span class='sectionRange'>606 - </span><a href="#h-128262"><span class="HTitleText2">Pleas</span></a>
</li>
<li><span class='sectionRange'>620 - </span><a href="#h-128369"><span class="HTitleText2">Organizations</span></a>
</li>
<li><span class='sectionRange'>624 - </span><a href="#h-128389"><span class="HTitleText2">Record of Proceedings</span></a>
</li>
<li><span class='sectionRange'>625.1 - </span><a href="#h-128401"><span class="HTitleText2">Pre-hearing Conference</span></a>
</li>
<li><span class='sectionRange'>626 - </span><a href="#h-128409"><span class="HTitleText2">Juries</span></a>
</li>
<li><span class='sectionRange'>628 - </span><a href="#h-128425"><span class="HTitleText2">Challenging the Array</span></a>
</li>
<li><span class='sectionRange'>631 - </span><a href="#h-128440"><span class="HTitleText2">Empanelling Jury</span></a>
</li>
<li><span class='sectionRange'>645 - </span><a href="#h-128589"><span class="HTitleText2">Trial</span></a>
</li>
<li><span class='sectionRange'>655 - </span><a href="#h-128722"><span class="HTitleText2">Evidence on Trial</span></a>
</li>
<li><span class='sectionRange'>658 - </span><a href="#h-128791"><span class="HTitleText2">Children and Young Persons</span></a>
</li>
<li><span class='sectionRange'>659 - </span><a href="#h-128807"><span class="HTitleText2">Corroboration</span></a>
</li>
<li><span class='sectionRange'>660 - </span><a href="#h-128812"><span class="HTitleText2">Verdicts</span></a>
</li>
<li><span class='sectionRange'>664 - </span><a href="#h-128848"><span class="HTitleText2">Previous Convictions</span></a>
</li>
<li><span class='sectionRange'>669.1 - </span><a href="#h-128881"><span class="HTitleText2">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>670 - </span><a href="#h-128910"><span class="HTitleText2">Formal Defects in Jury Process</span></a>
</li></ul>
</li><li><span class='sectionRange'>672.1 - </span><a href="#h-128925"><span class="HLabel1">PART XX.1</span> - <span class="HTitleText1">Mental Disorder</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>672.1 - </span><a href="#h-128926"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>672.11 - </span><a href="#h-128953"><span class="HTitleText2">Assessment Orders</span></a>
</li>
<li><span class='sectionRange'>672.2 - </span><a href="#h-129048"><span class="HTitleText2">Assessment Reports</span></a>
</li>
<li><span class='sectionRange'>672.21 - </span><a href="#h-129060"><span class="HTitleText2">Protected Statements</span></a>
</li>
<li><span class='sectionRange'>672.22 - </span><a href="#h-129077"><span class="HTitleText2">Fitness to Stand Trial</span></a>
</li>
<li><span class='sectionRange'>672.34 - </span><a href="#h-129161"><span class="HTitleText2">Verdict of Not Criminally Responsible on Account of Mental Disorder</span></a>
</li>
<li><span class='sectionRange'>672.38 - </span><a href="#h-129190"><span class="HTitleText2">Review Boards</span></a>
</li>
<li><span class='sectionRange'>672.45 - </span><a href="#h-129235"><span class="HTitleText2">Disposition Hearings</span></a>
</li>
<li><span class='sectionRange'>672.54 - </span><a href="#h-129433"><span class="HTitleText2">Dispositions by a Court or Review Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>672.54 - </span><a href="#h-129434"><span class="HTitleText3">Terms of Dispositions</span></a>
</li>
<li><span class='sectionRange'>672.64 - </span><a href="#h-129524"><span class="HTitleText3">High-Risk Accused</span></a>
</li>
<li><span class='sectionRange'>672.67 - </span><a href="#h-129548"><span class="HTitleText3">Dual Status Offenders</span></a>
</li></ul>
</li><li><span class='sectionRange'>672.72 - </span><a href="#h-129599"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>672.81 - </span><a href="#h-129674"><span class="HTitleText2">Review of Dispositions</span></a>
</li>
<li><span class='sectionRange'>672.85 - </span><a href="#h-129737"><span class="HTitleText2">Power to Compel Appearance</span></a>
</li>
<li><span class='sectionRange'>672.851 - </span><a href="#h-129744"><span class="HTitleText2">Stay of Proceedings</span></a>
</li>
<li><span class='sectionRange'>672.86 - </span><a href="#h-129786"><span class="HTitleText2">Interprovincial Transfers</span></a>
</li>
<li><span class='sectionRange'>672.9 - </span><a href="#h-129824"><span class="HTitleText2">Enforcement of Orders and Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>673 - </span><a href="#h-129874"><span class="HLabel1">PART XXI</span> - <span class="HTitleText1">Appeals — Indictable Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>673 - </span><a href="#h-129875"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>674 - </span><a href="#h-129890"><span class="HTitleText2">Right of Appeal</span></a>
</li>
<li><span class='sectionRange'>678 - </span><a href="#h-129954"><span class="HTitleText2">Procedure on Appeals</span></a>
</li>
<li><span class='sectionRange'>686 - </span><a href="#h-130097"><span class="HTitleText2">Powers of the Court of Appeal</span></a>
</li>
<li><span class='sectionRange'>691 - </span><a href="#h-130192"><span class="HTitleText2">Appeals to the Supreme Court of Canada</span></a>
</li>
<li><span class='sectionRange'>696 - </span><a href="#h-130261"><span class="HTitleText2">Appeals by Attorney General of Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>696.1 - </span><a href="#h-130266"><span class="HLabel1">PART XXI.1</span> - <span class="HTitleText1">Applications for Ministerial Review — Miscarriages of Justice</span></a>
</li>
<li><span class='sectionRange'>697 - </span><a href="#h-130316"><span class="HLabel1">PART XXII</span> - <span class="HTitleText1">Procuring Attendance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>697 - </span><a href="#h-130317"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>698 - </span><a href="#h-130322"><span class="HTitleText2">Process</span></a>
</li>
<li><span class='sectionRange'>701 - </span><a href="#h-130370"><span class="HTitleText2">Execution or Service of Process</span></a>
</li>
<li><span class='sectionRange'>704 - </span><a href="#h-130407"><span class="HTitleText2">Defaulting or Absconding Witness</span></a>
</li>
<li><span class='sectionRange'>708.1 - </span><a href="#h-130454"><span class="HTitleText2">Electronically Transmitted Copies</span></a>
</li>
<li><span class='sectionRange'>709 - </span><a href="#h-130459"><span class="HTitleText2">Evidence on Commission</span></a>
</li>
<li><span class='sectionRange'>714.1 - </span><a href="#h-130516"><span class="HTitleText2">Video and Audio Evidence</span></a>
</li>
<li><span class='sectionRange'>715 - </span><a href="#h-130564"><span class="HTitleText2">Evidence Previously Taken</span></a>
</li>
<li><span class='sectionRange'>715.1 - </span><a href="#h-130583"><span class="HTitleText2">Video-recorded Evidence</span></a>
</li></ul>
</li><li><span class='sectionRange'>715.21 - </span><a href="#h-1202926"><span class="HLabel1">PART XXII.01</span> - <span class="HTitleText1">Remote Attendance by Certain Persons</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>715.21 - </span><a href="#h-1202927"><span class="HTitleText2">Principles</span></a>
</li>
<li><span class='sectionRange'>715.23 - </span><a href="#h-1202936"><span class="HTitleText2">Accused</span></a>
</li>
<li><span class='sectionRange'>715.25 - </span><a href="#h-1202955"><span class="HTitleText2">Participants</span></a>
</li>
<li><span class='sectionRange'>715.26 - </span><a href="#h-1202975"><span class="HTitleText2">Judge or Justice</span></a>
</li></ul>
</li><li><span class='sectionRange'>715.3 - </span><a href="#h-130598"><span class="HLabel1">PART XXII.1</span> - <span class="HTitleText1">Remediation Agreements</span></a>
</li>
<li><span class='sectionRange'>716 - </span><a href="#h-130799"><span class="HLabel1">PART XXIII</span> - <span class="HTitleText1">Sentencing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>716 - </span><a href="#h-130800"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>717 - </span><a href="#h-130813"><span class="HTitleText2">Alternative Measures</span></a>
</li>
<li><span class='sectionRange'>718 - </span><a href="#h-130884"><span class="HTitleText2">Purpose and Principles of Sentencing</span></a>
</li>
<li><span class='sectionRange'>718.21 - </span><a href="#h-130929"><span class="HTitleText2">Organizations</span></a>
</li>
<li><span class='sectionRange'>718.3 - </span><a href="#h-130944"><span class="HTitleText2">Punishment Generally</span></a>
</li>
<li><span class='sectionRange'>720 - </span><a href="#h-130995"><span class="HTitleText2">Procedure and Evidence</span></a>
</li>
<li><span class='sectionRange'>730 - </span><a href="#h-131176"><span class="HTitleText2">Absolute and Conditional Discharges</span></a>
</li>
<li><span class='sectionRange'>731 - </span><a href="#h-131191"><span class="HTitleText2">Probation</span></a>
</li>
<li><span class='sectionRange'>734 - </span><a href="#h-131365"><span class="HTitleText2">Fines and Forfeiture</span></a>
</li>
<li><span class='sectionRange'>737.1 - </span><a href="#h-131542"><span class="HTitleText2">Restitution</span></a>
</li>
<li><span class='sectionRange'>742 - </span><a href="#h-131616"><span class="HTitleText2">Conditional Sentence of Imprisonment</span></a>
</li>
<li><span class='sectionRange'>743 - </span><a href="#h-131837"><span class="HTitleText2">Imprisonment</span></a>
</li>
<li><span class='sectionRange'>743.6 - </span><a href="#h-131892"><span class="HTitleText2">Eligibility for Parole</span></a>
</li>
<li><span class='sectionRange'>744 - </span><a href="#h-131904"><span class="HTitleText2">Delivery of Offender to Keeper of Prison</span></a>
</li>
<li><span class='sectionRange'>745 - </span><a href="#h-131909"><span class="HTitleText2">Imprisonment for Life</span></a>
</li>
<li><span class='sectionRange'>748 - </span><a href="#h-132091"><span class="HTitleText2">Pardons and Remissions</span></a>
</li>
<li><span class='sectionRange'>750 - </span><a href="#h-132114"><span class="HTitleText2">Disabilities</span></a>
</li>
<li><span class='sectionRange'>751 - </span><a href="#h-132134"><span class="HTitleText2">Miscellaneous Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>752 - </span><a href="#h-132143"><span class="HLabel1">PART XXIV</span> - <span class="HTitleText1">Dangerous Offenders and Long-term Offenders</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>752 - </span><a href="#h-132144"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>752.01 - </span><a href="#h-132237"><span class="HTitleText2">Dangerous Offenders and Long-Term Offenders</span></a>
</li></ul>
</li><li><span class='sectionRange'>762 - </span><a href="#h-132426"><span class="HLabel1">PART XXV</span> - <span class="HTitleText1">Effect and Enforcement of Undertakings, Release Orders and Recognizances</span></a>
</li>
<li><span class='sectionRange'>774 - </span><a href="#h-132537"><span class="HLabel1">PART XXVI</span> - <span class="HTitleText1">Extraordinary Remedies</span></a>
</li>
<li><span class='sectionRange'>785 - </span><a href="#h-132629"><span class="HLabel1">PART XXVII</span> - <span class="HTitleText1">Summary Convictions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>785 - </span><a href="#h-132630"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>787 - </span><a href="#h-132663"><span class="HTitleText2">Punishment</span></a>
</li>
<li><span class='sectionRange'>788 - </span><a href="#h-132672"><span class="HTitleText2">Information</span></a>
</li>
<li><span class='sectionRange'>793 - </span><a href="#h-132702"><span class="HTitleText2">Defects and Objections</span></a>
</li>
<li><span class='sectionRange'>795 - </span><a href="#h-132710"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>798 - </span><a href="#h-132716"><span class="HTitleText2">Trial</span></a>
</li>
<li><span class='sectionRange'>804 - </span><a href="#h-132775"><span class="HTitleText2">Adjudication</span></a>
</li>
<li><span class='sectionRange'>810 - </span><a href="#h-132816"><span class="HTitleText2">Sureties to Keep the Peace</span></a>
</li>
<li><span class='sectionRange'>812 - </span><a href="#h-133094"><span class="HTitleText2">Appeal</span></a>
</li>
<li><span class='sectionRange'>816 - </span><a href="#h-133142"><span class="HTitleText2">Interim Release of Appellant</span></a>
</li>
<li><span class='sectionRange'>821 - </span><a href="#h-133192"><span class="HTitleText2">Procedure on Appeal</span></a>
</li>
<li><span class='sectionRange'>829 - </span><a href="#h-133269"><span class="HTitleText2">Summary Appeal on Transcript or Agreed Statement of Facts</span></a>
</li>
<li><span class='sectionRange'>839 - </span><a href="#h-133335"><span class="HTitleText2">Appeals to Court of Appeal</span></a>
</li>
<li><span class='sectionRange'>840 - </span><a href="#h-133353"><span class="HTitleText2">Fees and Allowances</span></a>
</li></ul>
</li><li><span class='sectionRange'>841 - </span><a href="#h-133361"><span class="HLabel1">PART XXVIII</span> - <span class="HTitleText1">Miscellaneous</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>841 - </span><a href="#h-133362"><span class="HTitleText2">Electronic Documents</span></a>
</li>
<li><span class='sectionRange'>848 - </span><a href="#h-133399"><span class="HTitleText2">Remote Appearance by Incarcerated Accused</span></a>
</li>
<li><span class='sectionRange'>849 - </span><a href="#h-133404"><span class="HTitleText2">Forms</span></a>
</li></ul>
</li><li><a href="#h-133415"><span class="scheduleLabel">SCHEDULE TO PART XX.1</span></a>
</li>
<li><a href="#h-133418"><span class="scheduleLabel">SCHEDULE TO PART XXII.1</span> <span class="scheduleTitleText"> - Offences in respect of which a remediation agreement may be entered into</span></a>
</li>
<li><a href="#h-133458"><span class="scheduleLabel">SCHEDULE [to Part XXV]</span> </a>
</li>
<li><a href="#h-133467"><span class="scheduleLabel">SCHEDULE [to Part XXVII]</span> </a>
</li>
<li><a href="#h-133514"><span class="scheduleLabel">FORM 1</span> <span class="scheduleTitleText"> - Information To Obtain a Search Warrant</span></a>
</li>
<li><a href="#h-133530"><span class="scheduleLabel">FORM 2</span> <span class="scheduleTitleText"> - Information</span></a>
</li>
<li><a href="#h-133546"><span class="scheduleLabel">FORM 3</span></a>
</li>
<li><a href="#h-133550"><span class="scheduleLabel">FORM 4</span> <span class="scheduleTitleText"> - Heading of Indictment</span></a>
</li>
<li><a href="#h-133568"><span class="scheduleLabel">FORM 5</span> <span class="scheduleTitleText"> - Warrant To Search</span></a>
</li>
<li><a href="#h-133581"><span class="scheduleLabel">FORM 5.001</span> <span class="scheduleTitleText"> - Preservation Demand</span></a>
</li>
<li><a href="#h-133599"><span class="scheduleLabel">FORM 5.002</span> <span class="scheduleTitleText"> - Information To Obtain a Preservation Order</span></a>
</li>
<li><a href="#h-133615"><span class="scheduleLabel">FORM 5.003</span> <span class="scheduleTitleText"> - Preservation Order</span></a>
</li>
<li><a href="#h-133633"><span class="scheduleLabel">FORM 5.004</span> <span class="scheduleTitleText"> - Information To Obtain a Production Order</span></a>
</li>
<li><a href="#h-133667"><span class="scheduleLabel">FORM 5.005</span> <span class="scheduleTitleText"> - Production Order for Documents</span></a>
</li>
<li><a href="#h-133687"><span class="scheduleLabel">FORM 5.006</span> <span class="scheduleTitleText"> - Production Order To Trace a Communication</span></a>
</li>
<li><a href="#h-133706"><span class="scheduleLabel">FORM 5.007</span> <span class="scheduleTitleText"> - Production Order for Transmission Data or Tracking Data</span></a>
</li>
<li><a href="#h-133723"><span class="scheduleLabel">FORM 5.008</span> <span class="scheduleTitleText"> - Production Order for Financial Data</span></a>
</li>
<li><a href="#h-133740"><span class="scheduleLabel">FORM 5.0081</span> <span class="scheduleTitleText"> - Information To Revoke or Vary an Order Made Under Any of Sections 487.013 to 487.018 of the Criminal Code</span></a>
</li>
<li><a href="#h-133755"><span class="scheduleLabel">FORM 5.009</span> <span class="scheduleTitleText"> - Information To Obtain a Non-Disclosure Order</span></a>
</li>
<li><a href="#h-133771"><span class="scheduleLabel">FORM 5.0091</span> <span class="scheduleTitleText"> - Non-Disclosure Order</span></a>
</li>
<li><a href="#h-133787"><span class="scheduleLabel">FORM 5.01</span> <span class="scheduleTitleText"> - Information To Obtain a Warrant To Take Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133810"><span class="scheduleLabel">FORM 5.02</span> <span class="scheduleTitleText"> - Warrant Authorizing the Taking of Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133832"><span class="scheduleLabel">FORM 5.03</span> <span class="scheduleTitleText"> - Order Authorizing the Taking of Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133846"><span class="scheduleLabel">FORM 5.04</span> <span class="scheduleTitleText"> - Order Authorizing the Taking of Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133871"><span class="scheduleLabel">FORM 5.041</span> <span class="scheduleTitleText"> - Order to a Person To Have Bodily Substances Taken for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133891"><span class="scheduleLabel">FORM 5.05</span> <span class="scheduleTitleText"> - Application for an Authorization To Take Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133910"><span class="scheduleLabel">FORM 5.06</span> <span class="scheduleTitleText"> - Authorization To Take Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133932"><span class="scheduleLabel">FORM 5.061</span> <span class="scheduleTitleText"> - Summons to a Person To Have Bodily Substances Taken for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-133952"><span class="scheduleLabel">FORM 5.062</span> <span class="scheduleTitleText"> - Warrant for Arrest</span></a>
</li>
<li><a href="#h-133966"><span class="scheduleLabel">FORM 5.07</span> <span class="scheduleTitleText"> - Report to a Provincial Court Judge or the Court</span></a>
</li>
<li><a href="#h-133986"><span class="scheduleLabel">FORM 5.08</span> <span class="scheduleTitleText"> - Application for an Authorization To Take Additional Samples of Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-134002"><span class="scheduleLabel">FORM 5.09</span> <span class="scheduleTitleText"> - Authorization To Take Additional Samples of Bodily Substances for Forensic DNA Analysis</span></a>
</li>
<li><a href="#h-134020"><span class="scheduleLabel">FORM 5.1</span> <span class="scheduleTitleText"> - Warrant To Search</span></a>
</li>
<li><a href="#h-134039"><span class="scheduleLabel">FORM 5.2</span> <span class="scheduleTitleText"> - Report to a Justice</span></a>
</li>
<li><a href="#h-134058"><span class="scheduleLabel">FORM 5.3</span> <span class="scheduleTitleText"> - Report to a Judge of Property Seized</span></a>
</li>
<li><a href="#h-1213198"><span class="scheduleLabel">FORM 6</span> <span class="scheduleTitleText"> - Summons to a Person Charged with an Offence</span></a>
</li>
<li><a href="#h-1213217"><span class="scheduleLabel">FORM 7</span> <span class="scheduleTitleText"> - Warrant for Arrest</span></a>
</li>
<li><a href="#h-134126"><span class="scheduleLabel">FORM 7.1</span> <span class="scheduleTitleText"> - Warrant To Enter Dwelling-house</span></a>
</li>
<li><a href="#h-1213245"><span class="scheduleLabel">FORM 8</span> <span class="scheduleTitleText"> - Warrant for Committal</span></a>
</li>
<li><a href="#h-1213268"><span class="scheduleLabel">FORM 9</span> <span class="scheduleTitleText"> - Appearance Notice</span></a>
</li>
<li><a href="#h-1213310"><span class="scheduleLabel">FORM 10</span> <span class="scheduleTitleText"> - Undertaking</span></a>
</li>
<li><a href="#h-1213372"><span class="scheduleLabel">FORM 11</span> <span class="scheduleTitleText"> - Release Order</span></a>
</li>
<li><a href="#h-1213434"><span class="scheduleLabel">FORM 11.1</span></a>
</li>
<li><a href="#h-1213437"><span class="scheduleLabel">FORM 12</span> <span class="scheduleTitleText"> - Surety Declaration</span></a>
</li>
<li><a href="#h-1213486"><span class="scheduleLabel">FORM 13</span></a>
</li>
<li><a href="#h-1213489"><span class="scheduleLabel">FORM 14</span></a>
</li>
<li><a href="#h-134315"><span class="scheduleLabel">FORM 15</span> <span class="scheduleTitleText"> - Warrant To Convey Accused Before Justice of Another Territorial Division</span></a>
</li>
<li><a href="#h-134328"><span class="scheduleLabel">FORM 16</span> <span class="scheduleTitleText"> - Subpoena to a Witness</span></a>
</li>
<li><a href="#h-134343"><span class="scheduleLabel">FORM 16.1</span> <span class="scheduleTitleText"> - Subpoena to a Witness in the Case of Proceedings in Respect of an Offence Referred to in Subsection 278.2(1) of the Criminal Code</span></a>
</li>
<li><a href="#h-134363"><span class="scheduleLabel">FORM 17</span> <span class="scheduleTitleText"> - Warrant for Witness</span></a>
</li>
<li><a href="#h-134382"><span class="scheduleLabel">FORM 18</span> <span class="scheduleTitleText"> - Warrant To Arrest an Absconding Witness</span></a>
</li>
<li><a href="#h-134396"><span class="scheduleLabel">FORM 19</span> <span class="scheduleTitleText"> - Warrant Remanding a Prisoner</span></a>
</li>
<li><a href="#h-1203117"><span class="scheduleLabel">FORM 20</span> <span class="scheduleTitleText"> - Warrant of Committal of Witness for Refusing to Be Sworn or to Give Evidence</span></a>
</li>
<li><a href="#h-134425"><span class="scheduleLabel">FORM 21</span> <span class="scheduleTitleText"> - Warrant of Committal on Conviction</span></a>
</li>
<li><a href="#h-134443"><span class="scheduleLabel">FORM 22</span> <span class="scheduleTitleText"> - Warrant of Committal on an Order for the Payment of Money</span></a>
</li>
<li><a href="#h-134457"><span class="scheduleLabel">FORM 23</span> <span class="scheduleTitleText"> - Warrant of Committal for Failure To Furnish Recognizance To Keep the Peace</span></a>
</li>
<li><a href="#h-1203137"><span class="scheduleLabel">FORM 24</span> <span class="scheduleTitleText"> - Warrant of Committal of Witness for Failure to Enter into Recognizance</span></a>
</li>
<li><a href="#h-1203153"><span class="scheduleLabel">FORM 25</span> <span class="scheduleTitleText"> - Warrant of Committal for Contempt</span></a>
</li>
<li><a href="#h-134507"><span class="scheduleLabel">FORM 26</span> <span class="scheduleTitleText"> - Warrant of Committal in Default of Payment of Costs of an Appeal</span></a>
</li>
<li><a href="#h-1213492"><span class="scheduleLabel">FORM 27</span> <span class="scheduleTitleText"> - Warrant of Committal on Forfeiture of Amounts</span></a>
</li>
<li><a href="#h-1203177"><span class="scheduleLabel">FORM 28</span> <span class="scheduleTitleText"> - Endorsement of Warrant</span></a>
</li>
<li><a href="#h-134545"><span class="scheduleLabel">FORM 28.1</span></a>
</li>
<li><a href="#h-134549"><span class="scheduleLabel">FORM 29</span> <span class="scheduleTitleText"> - Endorsement of Warrant</span></a>
</li>
<li><a href="#h-1203186"><span class="scheduleLabel">FORM 30</span> <span class="scheduleTitleText"> - Order for Accused to Be Brought Before Justice Prior to Expiration of Period of Remand</span></a>
</li>
<li><a href="#h-134571"><span class="scheduleLabel">FORM 31</span> <span class="scheduleTitleText"> - Deposition of a Witness</span></a>
</li>
<li><a href="#h-1213508"><span class="scheduleLabel">FORM 32</span> <span class="scheduleTitleText"> - Recognizance</span></a>
</li>
<li><a href="#h-1213575"><span class="scheduleLabel">FORM 33</span> <span class="scheduleTitleText"> - Certificate of Default to Be Endorsed</span></a>
</li>
<li><a href="#h-134642"><span class="scheduleLabel">FORM 34</span> <span class="scheduleTitleText"> - Writ of Fieri Facias</span></a>
</li>
<li><a href="#h-134653"><span class="scheduleLabel">FORM 34.1</span> <span class="scheduleTitleText"> - Statement on Restitution</span></a>
</li>
<li><a href="#h-134675"><span class="scheduleLabel">FORM 34.2</span> <span class="scheduleTitleText"> - Victim Impact Statement</span></a>
</li>
<li><a href="#h-134743"><span class="scheduleLabel">FORM 34.3</span> <span class="scheduleTitleText"> - Community Impact Statement</span></a>
</li>
<li><a href="#h-134807"><span class="scheduleLabel">FORM 35</span> <span class="scheduleTitleText"> - Conviction</span></a>
</li>
<li><a href="#h-134822"><span class="scheduleLabel">FORM 36</span> <span class="scheduleTitleText"> - Order Against an Offender</span></a>
</li>
<li><a href="#h-134833"><span class="scheduleLabel">FORM 37</span> <span class="scheduleTitleText"> - Order Acquitting Accused</span></a>
</li>
<li><a href="#h-1203218"><span class="scheduleLabel">FORM 38</span> <span class="scheduleTitleText"> - Conviction for Contempt</span></a>
</li>
<li><a href="#h-1203232"><span class="scheduleLabel">FORM 39</span> <span class="scheduleTitleText"> - Order for Discharge of a Person in Custody</span></a>
</li>
<li><a href="#h-134866"><span class="scheduleLabel">FORM 40</span> <span class="scheduleTitleText"> - Challenge To Array</span></a>
</li>
<li><a href="#h-134878"><span class="scheduleLabel">FORM 41</span> <span class="scheduleTitleText"> - Challenge for Cause</span></a>
</li>
<li><a href="#h-134889"><span class="scheduleLabel">FORM 42</span> <span class="scheduleTitleText"> - Certificate of Non-payment of Costs of Appeal</span></a>
</li>
<li><a href="#h-134898"><span class="scheduleLabel">FORM 43</span> <span class="scheduleTitleText"> - Jailer’s Receipt to Peace Officer for Prisoner</span></a>
</li>
<li><a href="#h-134906"><span class="scheduleLabel">FORM 44</span> </a>
</li>
<li><a href="#h-134915"><span class="scheduleLabel">FORM 45</span> </a>
</li>
<li><a href="#h-134923"><span class="scheduleLabel">FORM 46</span> <span class="scheduleTitleText"> - Probation Order</span></a>
</li>
<li><a href="#h-134944"><span class="scheduleLabel">FORM 47</span> <span class="scheduleTitleText"> - Order To Disclose Income Tax Information</span></a>
</li>
<li><a href="#h-134958"><span class="scheduleLabel">FORM 48</span> <span class="scheduleTitleText"> - Assessment Order of the Court</span></a>
</li>
<li><a href="#h-134979"><span class="scheduleLabel">FORM 48.1</span> <span class="scheduleTitleText"> - Assessment Order of the Review Board</span></a>
</li>
<li><a href="#h-134997"><span class="scheduleLabel">FORM 48.2</span> <span class="scheduleTitleText"> - Victim Impact Statement  —  Not Criminally Responsible</span></a>
</li>
<li><a href="#h-135060"><span class="scheduleLabel">FORM 49</span> <span class="scheduleTitleText"> - Warrant of Committal</span></a>
</li>
<li><a href="#h-135081"><span class="scheduleLabel">FORM 50</span> <span class="scheduleTitleText"> - Warrant of Committal</span></a>
</li>
<li><a href="#h-135103"><span class="scheduleLabel">FORM 51</span> <span class="scheduleTitleText"> - Notice of Obligation To Provide Samples of Bodily Substance</span></a>
</li>
<li><a href="#h-135118"><span class="scheduleLabel">FORM 52</span> <span class="scheduleTitleText"> - Order To Comply with Sex Offender Information Registration Act</span></a>
</li>
<li><a href="#h-135139"><span class="scheduleLabel">FORM 53</span> <span class="scheduleTitleText"> - Notice of Obligation To Comply with Sex Offender Information Registration Act</span></a>
</li>
<li><a href="#h-135159"><span class="scheduleLabel">FORM 54</span> <span class="scheduleTitleText"> - Obligation To Comply with Sex Offender Information Registration Act</span></a>
</li></ul>
</li></ul>

</nav>

