<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Housing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-359205"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-359210"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-359276"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-359281"><span class="HTitleText1">Rights and Obligations of the Corporation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-359287"><span class="HTitleText1">Approved Lenders</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-359316"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Housing Loan Insurance, Guarantee and Protection</span></a>
</li>
<li><span class='sectionRange'>21.5 - </span><a href="page-3.html#h-359518"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Covered Bonds</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21.5 - </span><a href="page-3.html#h-359519"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>21.51 - </span><a href="page-3.html#h-359532"><span class="HTitleText2">Establishment of Legal Framework</span></a>
</li>
<li><span class='sectionRange'>21.63 - </span><a href="page-4.html#h-359641"><span class="HTitleText2">Bankruptcy and Insolvency Protection</span></a>
</li>
<li><span class='sectionRange'>21.66 - </span><a href="page-4.html#h-359664"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="page-4.html#h-359677"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Housing for Rental Purposes</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-5.html#h-359767"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Land Assembly</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-5.html#h-359821"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Land Acquisition and Leasing</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-5.html#h-359832"><span class="HLabel1">PART V</span> - <span class="HTitleText1">[Repealed, R.S., 1985, c. 25 (4th Supp.), s. 23]</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-5.html#h-359833"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Repair, Rehabilitation, Improvement and Conversion of Buildings</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-5.html#h-359847"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Facilitation of Home Ownership and Occupancy</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-5.html#h-359873"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Housing Research, Community Planning and International Support</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-6.html#h-359928"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Public Housing</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-6.html#h-359951"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">New Communities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="page-6.html#h-359952"><span class="HTitleText2">Federal-Provincial Agreements</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="page-6.html#h-359970"><span class="HTitleText2">Loans</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="page-6.html#h-359994"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Loans for Student Housing Projects</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-6.html#h-360011"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Community Services</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-7.html#h-360021"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Housing Development</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-7.html#h-360074"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="page-7.html#h-360150"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

