<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la commercialisation du CN</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-39685"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-39688"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-39705"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-39708"><span class="HTitleText1">Opérations préliminaires</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-39716"><span class="HTitleText1">Prorogation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-39767"><span class="HTitleText1">Opérations sur les actions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-39775"><span class="HTitleText1">Accords financiers</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-39783"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-39793"><span class="HTitleText1">Dispositions transitoires, modifications corrélatives, abrogations et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-39794"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-39802"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-39804"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-39810"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-39814"><span class="scheduleLabel">ANNEXES I ET II</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
