<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2004 pour la mise en œuvre de conventions fiscales</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-437199"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-437202"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Convention fiscale Canada–Gabon</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-437206"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Convention fiscale Canada–Irlande</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-437210"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Convention fiscale Canada–Arménie</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-437214"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Accord fiscal Canada–Oman</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-437218"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Convention fiscale Canada–Azerbaïdjan</span></a>
</li>
<li><a href="#h-437223"><span class="scheduleLabel"><strong>ANNEXE 1</strong></span> </a>
</li>
<li><a href="#h-437225"><span class="scheduleLabel"><strong>ANNEXE 2</strong></span> </a>
</li>
<li><a href="#h-437227"><span class="scheduleLabel"><strong>ANNEXE 3</strong></span> </a>
</li>
<li><a href="#h-437229"><span class="scheduleLabel"><strong>ANNEXE 4</strong></span> </a>
</li>
<li><a href="#h-437231"><span class="scheduleLabel"><strong>ANNEXE 5</strong></span> </a>
</li></ul>
</li></ul>

</nav>

