<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Integrated Cross-border Law Enforcement Operations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-270566"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-270569"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-270577"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-270580"><span class="HTitleText1">Principles</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-270589"><span class="HTitleText1">Central Authority for Canada</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-270621"><span class="HTitleText1">Powers of Designated Officers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-270626"><span class="HTitleText1">Detention of Persons</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-270632"><span class="HTitleText1">Seizure</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
