<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canadian Commercial Bank Financial Assistance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-61652"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-61655"><span class="HTitleText1">Financial Assistance</span></a>
</li></ul>
</li></ul>

</nav>

