<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Pension Benefits Division Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-414146"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-414149"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-414180"><span class="HTitleText1">Application for Division</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-414227"><span class="HTitleText1">Division</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-414274"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-414299"><span class="HTitleText1">Offence</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-414302"><span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

