<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Food Inspection Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-67970"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-67973"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-67978"><span class="HTitleText1">Establishment of the Agency</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-67986"><span class="HTitleText1">Organization and Head Office</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-68000"><span class="HTitleText1">Advisory Board</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-68016"><span class="HTitleText1">Responsibilities of the Agency</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-68032"><span class="HTitleText1">Human Resources</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-68044"><span class="HTitleText1">Powers of the Agency</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-68060"><span class="HTitleText1">Recall Orders</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-68068"><span class="HTitleText1">Establishment of Federal-Provincial Corporations</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-68075"><span class="HTitleText1">Corporate Business Plan and Annual Report</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-68097"><span class="HTitleText1">Fees and Expenditures</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-68127"><span class="HTitleText1">Accounting</span></a>
</li>
<li><span class='sectionRange'>32.1 - </span><a href="#h-68131"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>37 to 89 - </span><a href="#h-68148"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>90 and 91 - </span><a href="#h-68150"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-68152"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-68154"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
