<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Crown Liability and Proceedings Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-138340"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-138345"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-138361"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Liability</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-138362"><span class="HTitleText2">Liability and Civil Salvage</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-138395"><span class="HTitleText2">Special Provisions respecting Liability</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-138409"><span class="HTitleText2">Property</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-138419"><span class="HTitleText2">Proceedings in rem</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-138428"><span class="HTitleText2">Invasion of Privacy</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-138478"><span class="HTitleText2">Environmental and Labour Cooperation Treaties</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-138528"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Proceedings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-138529"><span class="HTitleText2">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-138544"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-138570"><span class="HTitleText2">Costs</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-138579"><span class="HTitleText2">Execution of Judgment</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-138591"><span class="HTitleText2">Interest</span></a>
</li>
<li><span class='sectionRange'>31.2 - </span><a href="#h-138624"><span class="HTitleText2">Tenders</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-138632"><span class="HTitleText2">Prescription and Limitation</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-138637"><span class="HTitleText2">Application of Statutes to the Crown</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-138642"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-138652"><span class="HTitleText2">Agencies and Servants of the Crown</span></a>
</li></ul>
</li><li><a href="#h-21"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
