<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la transparence financière des Premières Nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-219032"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-219035"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-219046"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-219051"><span class="HTitleText1">États financiers et annexe des rémunérations et des dépenses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-219052"><span class="HTitleText2">Préparation et vérification indépendante</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-219065"><span class="HTitleText2">Divulgation</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="#h-219086"><span class="HTitleText1">Recours judiciaires et mesures administratives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-219087"><span class="HTitleText2">Ordonnances</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-219094"><span class="HTitleText2">Mesures administratives</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

