<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Film Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-382681"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-382686"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-382697"><span class="HTitleText1">Responsibility of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-382702"><span class="HTitleText1">National Film Board</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-382738"><span class="HTitleText1">Purposes of the Board</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-382748"><span class="HTitleText1">Powers of Board</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-382790"><span class="HTitleText1">Government Film Commissioner</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-382809"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-382821"><span class="HTitleText1">Reports</span></a>
</li>
<li><a href="page-2.html#h-382834"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Oath of Office and Secrecy</span></a>
</li></ul>
</li></ul>

</nav>

