<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’évaluation environnementale et socioéconomique au Yukon</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-461678"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-461681"><span class="HTitleText1">Définitions et dispositions d’interprétation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-461772"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-461795"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Office d’évaluation environnementale et socioéconomique du Yukon et bureaux désignés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-461796"><span class="HTitleText2">Office d’évaluation environnementale et socioéconomique du Yukon</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-461871"><span class="HTitleText2">Circonscriptions et bureaux désignés</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-461903"><span class="HTitleText2">Budgets et rapports</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-461924"><span class="HTitleText2">Règles et règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-462011"><span class="HTitleText2">Obligation générale</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-462014"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Processus d’évaluation et décisions écrites</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-462015"><span class="HTitleText2">Dispositions générales sur le processus</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="#h-462075"><span class="HTitleText2">Délais</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-462080"><span class="HTitleText2">Activités visées</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-462118"><span class="HTitleText2">Saisine</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-462143"><span class="HTitleText2">Examen par le bureau désigné</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-462173"><span class="HTitleText2">Avis et préétude par le comité de direction</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-462205"><span class="HTitleText2">Demande d’étude</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-462222"><span class="HTitleText2">Pouvoirs du ministre de l’Environnement</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-462242"><span class="HTitleText2">Comité restreint</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-462288"><span class="HTitleText2">Comité mixte</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-462315"><span class="HTitleText2">Étude du projet de développement</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-462354"><span class="HTitleText2">Examen des recommandations et prise des décisions écrites</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-462413"><span class="HTitleText2">Mise en oeuvre des décisions écrites</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-462455"><span class="HTitleText2">Versant nord du Yukon</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-462475"><span class="HTitleText2">Coopération</span></a>
</li>
<li><span class='sectionRange'>93.1 - </span><a href="#h-462490"><span class="HTitleText2">Recouvrement des coûts</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-462503"><span class="HTitleText2">Ouvrages</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-462580"><span class="HTitleText2">Plans</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-462655"><span class="HTitleText2">Mesures de contrôle et de vérification</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-462670"><span class="HTitleText2">Études et recherches</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-462691"><span class="HTitleText2">Violation des prescriptions des décisions écrites</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-462699"><span class="HTitleText2">Compétence judiciaire</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-462708"><span class="HTitleText2">Dossiers et accès à l’information</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-462737"><span class="HTitleText2">Règlements et décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="#h-462760"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions transitoires, modifications connexes, dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>124 - </span><a href="#h-462761"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-462779"><span class="HTitleText2">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-462780"><span class="HTitleText3">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-462783"><span class="HTitleText3">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-462785"><span class="HTitleText3">Loi sur l’autonomie gouvernementale des premières nations du Yukon</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-462787"><span class="HTitleText3">Loi sur l’Office des droits de surface du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>132 - </span><a href="#h-462789"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-462792"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-462796"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

