<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2006 sur la convention fiscale Canada–Finlande</a><ul class="TocIndent"><li><a href="page-2.html#h-132258"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Convention entre le Canada et la Finlande en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li></ul>
</li></ul>

</nav>

