<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la manutention des grains à Prince Rupert</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-387291"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-387294"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-387305"><span class="HTitleText1">Manutention des grains</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-387334"><span class="HTitleText1">Arbitrage</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-387346"><span class="HTitleText1">Modification de la convention collective</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-387349"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-387359"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
