<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la compétence extracôtière du Canada pour les douanes et l’accise</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-139049"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-139054"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-139081"><span class="HTitleText1">Compétence douanière</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-139091"><span class="HTitleText1">Renseignements et documents</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-139099"><span class="HTitleText1">Droits acquis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-139100"><span class="HTitleText2">Biens rendus sur place</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-139117"><span class="HTitleText2">Biens commandés</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-139135"><span class="HTitleText2">Règles spéciales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-139149"><span class="HTitleText2">Navires</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
