<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’accord définitif concernant les premières nations maanulthes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-340006"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-340009"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-340019"><span class="HTitleText1">Accord</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-340032"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-340035"><span class="HTitleText1">Terres</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-340038"><span class="HTitleText1">Fiscalité</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-340043"><span class="HTitleText1">Pêches</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-340048"><span class="HTitleText1">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-340053"><span class="HTitleText1">Application de lois de la Colombie-Britannique</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-340056"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-340082"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="page-1.html#h-340083"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’accès à l’information</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-340085"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les pêches</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-340087"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les paiements versés en remplacement d’impôts</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-340089"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la protection des renseignements personnels</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-340091"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal des revendications particulières</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-1.html#h-340093"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

