<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’Office d’investissement des régimes de pensions du secteur public</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-392868"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-392871"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-392882"><span class="HTitleText1">Constitution de l’office</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="page-1.html#h-392900"><span class="HTitleText1">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-392910"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-392931"><span class="HTitleText1">Gestion</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-1.html#h-392932"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-392974"><span class="HTitleText2">Administrateurs</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-393019"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-393035"><span class="HTitleText2">Dirigeants</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-393043"><span class="HTitleText2">Diligence</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-393065"><span class="HTitleText2">Décisions</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-393068"><span class="HTitleText2">Conflit d’intérêts</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-393100"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-2.html#h-393109"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-393128"><span class="HTitleText1">Comités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="page-2.html#h-393129"><span class="HTitleText2">Constitution</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-393139"><span class="HTitleText2">Comité de vérification</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-393158"><span class="HTitleText2">Comité de placement</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="page-3.html#h-393168"><span class="HTitleText1">Placements</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-3.html#h-393173"><span class="HTitleText1">Gestion financière</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="page-3.html#h-393174"><span class="HTitleText2">Exercice</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-3.html#h-393177"><span class="HTitleText2">États financiers</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-3.html#h-393215"><span class="HTitleText1">Rapports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="page-3.html#h-393216"><span class="HTitleText2">États financiers trimestriels</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-3.html#h-393221"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="page-3.html#h-393243"><span class="HTitleText1">Réunions</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-3.html#h-393246"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-3.html#h-393256"><span class="HTitleText1">Infraction</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-393264"><span class="HTitleText1">Liquidation</span></a>
</li>
<li><span class='sectionRange'>53 à 114 - </span><a href="page-3.html#h-393267"><span class="HTitleText1">Modification de la Loi sur la pension de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>115 à 117 - </span><a href="page-3.html#h-393269"><span class="HTitleText1">Modification de la Loi sur la pension de retraite des forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>169 à 171 - </span><a href="page-4.html#h-393281"><span class="HTitleText1">Modification de la Loi sur la pension de retraite de la Gendarmerie royale du Canada</span></a>
</li>
<li><span class='sectionRange'>207 à 227 - </span><a href="page-4.html#h-393288"><span class="HTitleText1">Modification d’autres lois</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="page-4.html#h-393290"><span class="HTitleText1">Modification corrélative</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="page-4.html#h-393292"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="page-4.html#h-393300"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

