<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Marine Liability Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-349462"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-349465"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-349470"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-349473"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Personal Injuries and Fatalities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-349474"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-349484"><span class="HTitleText2">Liability to Dependants</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-349524"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Apportionment of Liability</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-349525"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-349537"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-349563"><span class="HTitleText2">Limitation of Time</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-349573"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Limitation of Liability for Maritime Claims</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-349574"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-349599"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-349643"><span class="HTitleText2">Liability of Owners of Docks, Canals and Ports</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-349661"><span class="HTitleText2">Amendment of Maximum Liability</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-349669"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>34.1 - </span><a href="#h-349696"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-349703"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Liability for Carriage of Passengers by Water</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-349704"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-349720"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-349748"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-349762"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Liability for Carriage of Goods by Water</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-349763"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-349772"><span class="HTitleText2">Hague-Visby Rules</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-349782"><span class="HTitleText2">Hamburg Rules</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-349796"><span class="HTitleText2">Institution of Proceedings in Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-349805"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Liability and Compensation for Pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-349806"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">International Conventions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-349807"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-349837"><span class="HTitleText3">Civil Liability Convention</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-349920"><span class="HTitleText3">Fund Convention</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-349950"><span class="HTitleText3">Supplementary Fund Protocol</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-349980"><span class="HTitleText3">Bunkers Convention</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-350069"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Liability Not Covered by Division 1</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>75 - </span><a href="#h-350070"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-350086"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="#h-350128"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="#h-350129"><span class="HTitleText3">Admiralty Court</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-350142"><span class="HTitleText3">Registration of Foreign Judgments</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-350222"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-350235"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Ship-source Oil Pollution Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-350236"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-350258"><span class="HTitleText2">Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-350290"><span class="HTitleText2">Administrator and Deputy Administrator</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-350340"><span class="HTitleText2">Liability of Ship-source Oil Pollution Fund</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>101 - </span><a href="#h-350341"><span class="HTitleText3">Process for Claims</span></a>
</li>
<li><span class='sectionRange'>106.1 - </span><a href="#h-350431"><span class="HTitleText3">Expedited Process for Small Claims</span></a>
</li></ul>
</li><li><span class='sectionRange'>107 - </span><a href="#h-350532"><span class="HTitleText2">Claims for Loss of Income</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-350584"><span class="HTitleText2">Proceedings Against the Owner of a Ship</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-350594"><span class="HTitleText2">Emergency Funds</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-350641"><span class="HTitleText2">Levies To Be Paid to the Ship-source Oil Pollution Fund, the International Fund and the Supplementary Fund</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-350821"><span class="HTitleText2">Governance of the Ship-source Oil Pollution Fund</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-350881"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-350892"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-350893"><span class="HTitleText2">Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>130.01 - </span><a href="#h-350952"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130.01 - </span><a href="#h-350953"><span class="HTitleText3">Assurances of Compliance and Notices of Violation</span></a>
</li>
<li><span class='sectionRange'>130.11 - </span><a href="#h-351084"><span class="HTitleText3">Recovery of Debts</span></a>
</li>
<li><span class='sectionRange'>130.13 - </span><a href="#h-351105"><span class="HTitleText3">General</span></a>
</li>
<li><span class='sectionRange'>130.17 - </span><a href="#h-351122"><span class="HTitleText3">Public Record</span></a>
</li>
<li><span class='sectionRange'>130.19 - </span><a href="#h-351150"><span class="HTitleText3">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>131 - </span><a href="#h-351158"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-351207"><span class="HTitleText2">Sale of Ships</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-351251"><span class="HTitleText2">Maritime Lien</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-351269"><span class="HTitleText2">Limitation Period</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-351274"><span class="HTitleText2">Inconsistency</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-351279"><span class="HTitleText2">Coming Into Force</span></a>
</li></ul>
</li><li><a href="#h-351285"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-351466"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-351621"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Hague-Visby Rules</span></a>
</li>
<li><a href="#h-351730"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - Hamburg Rules</span></a>
</li>
<li><a href="#h-352009"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - Text of Articles I to XI, XII bis and 15 of the International Convention on Civil Liability for Oil Pollution Damage, 1992, as Amended by the Resolution of 2000</span></a>
</li>
<li><a href="#h-352165"><span class="scheduleLabel">SCHEDULE 6</span> <span class="scheduleTitleText"> - Text of Articles 1 to 4, 6 to 10, 12 to 15, 36 ter, 29, 33 and 37 of the International Convention on the Establishment of an International Fund for Compensation for Oil Pollution Damage, 1992, as Amended by the Resolution of 2000</span></a>
</li>
<li><a href="#h-352316"><span class="scheduleLabel">SCHEDULE 7</span> <span class="scheduleTitleText"> - Text of Articles 1 to 15, 18, 20, 24, 25 and 29 of the Protocol of 2003 to the International Convention on the Establishment of an International Fund for Compensation for Oil Pollution Damage, 1992</span></a>
</li>
<li><a href="#h-352457"><span class="scheduleLabel">SCHEDULE 8</span> <span class="scheduleTitleText"> - Text of Articles 1 to 10 of the International Convention on Civil Liability for Bunker Oil Pollution Damage, 2001</span></a>
</li></ul>
</li></ul>

</nav>

