<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Code canadien du travail</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>Préambule - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Relations du travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText2">Grands travaux</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Libertés fondamentales</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Conseil canadien des relations industrielles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText3">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText3">Pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-11"><span class="HTitleText3">Révision et exécution des ordonnances</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-12"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Acquisition et extinction des droits de négociation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>24 - </span><a href="#h-13"><span class="HTitleText3">Demande d’accréditation</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-14"><span class="HTitleText3">Détermination des unités de négociation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-15"><span class="HTitleText3">Accréditation des agents négociateurs et questions connexes</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HTitleText3">Révocation de l’accréditation et questions connexes</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-17"><span class="HTitleText3">Droits et obligations du successeur</span></a>
</li>
<li><span class='sectionRange'>47.3 - </span><a href="#h-18"><span class="HTitleText3">Contrats successifs de fourniture de services</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-19"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Négociations collectives et conventions collectives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-20"><span class="HTitleText3">Obligation de négocier collectivement</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-21"><span class="HTitleText3">Changement technologique</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-22"><span class="HTitleText3">Contenu et interprétation des conventions collectives</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-23"><span class="HTitleText3">Précompte obligatoire des cotisations</span></a>
</li></ul>
</li><li><span class='sectionRange'>70.1 - </span><a href="#h-24"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Conciliation et première convention</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70.1 - </span><a href="#h-25"><span class="HTitleText3">Service fédéral de médiation et de conciliation</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-26"><span class="HTitleText3">Procédures de conciliation</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-27"><span class="HTitleText3">Première convention collective</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-28"><span class="HTitleText3">Constitution des commissions de conciliation</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-29"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>87.1 - </span><a href="#h-30"><span class="HLabel2">SECTION V.1</span> - <span class="HTitleText2">Obligations en matière de grèves et de lock-out</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-31"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Interdictions et recours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-32"><span class="HTitleText3">Grèves et lock-out</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-33"><span class="HTitleText3">Déclarations relatives aux grèves et lock-out</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-34"><span class="HTitleText3">Pratiques déloyales</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-35"><span class="HTitleText3">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>104.1 - </span><a href="#h-36"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104.1 - </span><a href="#h-37"><span class="HTitleText3">Règlement pacifique des conflits de travail</span></a>
</li>
<li><span class='sectionRange'>108.1 - </span><a href="#h-38"><span class="HTitleText3">Scrutin sur les offres de l’employeur</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-39"><span class="HTitleText3">Accès aux employés</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-40"><span class="HTitleText3">Communication des états financiers</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-41"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-42"><span class="HTitleText3">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-43"><span class="HTitleText3">Accords avec les provinces</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-44"><span class="HTitleText3">Rapports annuels</span></a>
</li>
<li><span class='sectionRange'>121.1 - </span><a href="#h-45"><span class="HTitleText3">Application de lois provinciales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>122 - </span><a href="#h-46"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Santé et sécurité au travail</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-47"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>122.1 - </span><a href="#h-48"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>122.3 - </span><a href="#h-49"><span class="HTitleText2">Modes de communication</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-50"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-51"><span class="HTitleText2">Obligations des employeurs</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-52"><span class="HTitleText2">Obligations des employés</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-53"><span class="HTitleText2">Sécurité au travail</span></a>
</li>
<li><span class='sectionRange'>127.1 - </span><a href="#h-54"><span class="HTitleText2">Processus de règlement interne des plaintes</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-55"><span class="HTitleText2">Employées enceintes ou allaitantes</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-56"><span class="HTitleText2">Plaintes découlant de mesures disciplinaires</span></a>
</li>
<li><span class='sectionRange'>134.1 - </span><a href="#h-57"><span class="HTitleText2">Comités d’orientation en matière de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-58"><span class="HTitleText2">Comités locaux de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-59"><span class="HTitleText2">Règles communes aux comités d’orientation et aux comités locaux</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-60"><span class="HTitleText2">Représentants en matière de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>137.1 - </span><a href="#h-61"><span class="HTitleText2">Commission de la sécurité dans les mines de charbon</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-62"><span class="HTitleText2">Exécution</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-63"><span class="HTitleText2">Agents de santé et de sécurité</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-64"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-65"><span class="HTitleText2">Mesures spéciales de sécurité</span></a>
</li>
<li><span class='sectionRange'>145.1 - </span><a href="#h-66"><span class="HTitleText2">Appel des décisions et instructions</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-67"><span class="HTitleText2">Mesures disciplinaires</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-68"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-69"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-70"><span class="HTitleText2">Pouvoirs du Conseil canadien des relations industrielles</span></a>
</li>
<li><span class='sectionRange'>156.1 - </span><a href="#h-71"><span class="HTitleText2">Facturation</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-72"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-73"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Durée normale du travail, salaire, congés et jours fériés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>166 - </span><a href="#h-74"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-75"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-76"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Durée du travail</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-77"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Salaire minimum</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-78"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Égalité des salaires</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-79"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Congés annuels</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-80"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Jours fériés</span></a>
</li>
<li><span class='sectionRange'>203 - </span><a href="#h-81"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Employeurs multiples</span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-82"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2">Réaffectation, congé de maternité, congé parental, congé de soignant et congé en cas de décès ou de disparition</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>204 - </span><a href="#h-83"><span class="HTitleText3">Réaffectation et congé liés à la maternité</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-84"><span class="HTitleText3">Congé de maternité</span></a>
</li>
<li><span class='sectionRange'>206.1 - </span><a href="#h-85"><span class="HTitleText3">Congé parental</span></a>
</li>
<li><span class='sectionRange'>206.3 - </span><a href="#h-86"><span class="HTitleText3">Congé de soignant</span></a>
</li>
<li><span class='sectionRange'>206.5 - </span><a href="#h-87"><span class="HTitleText3">Congé en cas de décès ou de disparition</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-88"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>210 - </span><a href="#h-89"><span class="HLabel2">SECTION VIII</span> - <span class="HTitleText2">Congés de décès</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-90"><span class="HLabel2">SECTION IX</span> - <span class="HTitleText2">Licenciements collectifs</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-91"><span class="HLabel2">SECTION X</span> - <span class="HTitleText2">Licenciements individuels</span></a>
</li>
<li><span class='sectionRange'>235 - </span><a href="#h-92"><span class="HLabel2">SECTION XI</span> - <span class="HTitleText2">Indemnité de départ</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-93"><span class="HLabel2">SECTION XII</span> - <span class="HTitleText2">Saisie-arrêt</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-94"><span class="HLabel2">SECTION XIII</span> - <span class="HTitleText2">Congés de maladie</span></a>
</li>
<li><span class='sectionRange'>239.1 - </span><a href="#h-95"><span class="HLabel2">SECTION XIII.1</span> - <span class="HTitleText2">Accidents et maladies professionnels</span></a>
</li>
<li><span class='sectionRange'>240 - </span><a href="#h-96"><span class="HLabel2">SECTION XIV</span> - <span class="HTitleText2">Congédiement injuste</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-97"><span class="HLabel2">SECTION XV</span> - <span class="HTitleText2">Paiement du salaire</span></a>
</li>
<li><span class='sectionRange'>247.1 - </span><a href="#h-98"><span class="HLabel2">SECTION XV.1</span> - <span class="HTitleText2">Harcèlement sexuel</span></a>
</li>
<li><span class='sectionRange'>247.5 - </span><a href="#h-99"><span class="HLabel2">SECTION XV.2</span> - <span class="HTitleText2">Congé pour les membres de la force de réserve</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-100"><span class="HLabel2">SECTION XVI</span> - <span class="HTitleText2">Application et dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>248 - </span><a href="#h-101"><span class="HTitleText3">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>249 - </span><a href="#h-102"><span class="HTitleText3">Inspections</span></a>
</li>
<li><span class='sectionRange'>251.1 - </span><a href="#h-103"><span class="HTitleText3">Recouvrement du salaire</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-104"><span class="HTitleText3">Renseignements et déclarations</span></a>
</li>
<li><span class='sectionRange'>254.1 - </span><a href="#h-105"><span class="HTitleText3">Retenues</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-106"><span class="HTitleText3">Fusion d’entreprises fédérales</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-107"><span class="HTitleText3">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-108"><span class="HTitleText3">Arrêtés ministériels</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-109"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="#h-110"><span class="HTitleText3">Application de lois provinciales</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
