<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Day of Remembrance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-374207"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-374210"><span class="HTitleText1">National Day of Remembrance</span></a>
</li></ul>
</li></ul>

</nav>

