<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Security of Information Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-384836"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-384841"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-384913"><span class="HTitleText1">Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-384914"><span class="HTitleText2">Miscellaneous Offences</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-384952"><span class="HTitleText2">Special Operational Information and Persons Permanently Bound to Secrecy</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-385062"><span class="HTitleText2">Communications with Foreign Entities or Terrorist Groups</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-385090"><span class="HTitleText2">Economic Espionage</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-385110"><span class="HTitleText2">Foreign-influenced or Terrorist-influenced Threats or Violence</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-385122"><span class="HTitleText2">Harbouring or Concealing</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-385132"><span class="HTitleText2">Preparatory Acts</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-385145"><span class="HTitleText2">Conspiracy, Attempts, Etc.</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="#h-385150"><span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-385182"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
