<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’entraide juridique en matière criminelle</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Annexe</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Publication des accords</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Ententes administratives</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Rôle du ministre</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Procédures ou enquêtes étrangères en matière criminelle</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText2">Mise en oeuvre</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-9"><span class="HTitleText2">Amendes</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="#h-10"><span class="HTitleText2">Cour pénale internationale</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="#h-11"><span class="HTitleText2">Ordonnances de blocage, de saisie et de confiscation de biens situés au Canada</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-12"><span class="HTitleText2">Perquisitions, fouilles et saisies</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-13"><span class="HTitleText2">Éléments de preuve destinés à l’étranger</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-14"><span class="HTitleText2">Transfèrement de personnes détenues</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Prêt de pièces à conviction</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText2">Appel</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-17"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Admissibilité au Canada d’éléments de preuve obtenus à l’étranger en vertu d’un accord</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-18"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Mise en oeuvre des accords au Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-19"><span class="HTitleText2">Autorisations spéciales d’entrer au Canada</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-20"><span class="HTitleText2">Détention au Canada</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-21"><span class="HTitleText2">Détermination de la validité des refus</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-22"><span class="HTitleText2">Protection des documents étrangers</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-23"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Modifications corrélatives et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-24"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-25"><span class="HTitleText2">Loi sur la responsabilité de l’État</span></a>
</li>
<li><span class='sectionRange'>47 et 48 - </span><a href="#h-26"><span class="HTitleText2">Loi sur l’immigration</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-27"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-28"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - États et entités désignés</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
