<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal Framework for Suicide Prevention Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-238675"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-238678"><span class="HTitleText1">Federal Framework for Suicide Prevention</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-238689"><span class="HTitleText1">Consultations</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-238692"><span class="HTitleText1">Report</span></a>
</li></ul>
</li></ul>

</nav>

