<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’identification des criminels</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-251430"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="page-1.html#h-251435"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-251440"><span class="HTitleText1">Identification des criminels</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-251465"><span class="HTitleText1">Destruction des empreintes digitales et des photographies</span></a>
</li></ul>
</li></ul>

</nav>

