<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la cession du droit au remboursement en matière d’impôt</a><ul class="TocIndent"><li><a href="#h-450159"><span class="scheduleLabel">ANNEXES I ET II</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
