<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de l’impôt sur le revenu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Impôt sur le revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HLabel2">SECTION A</span> - <span class="HTitleText2">Assujettissement à l’impôt</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HLabel2">SECTION B</span> - <span class="HTitleText2">Calcul du revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText3">Règles fondamentales</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Revenu ou perte provenant d’une charge ou d’un emploi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText4">Règles fondamentales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText4">Éléments à inclure</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText4">Déductions</span></a>
</li></ul>
</li><li><span class='sectionRange'>9 - </span><a href="#h-10"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Revenu ou perte provenant d’une entreprise ou d’un bien</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-11"><span class="HTitleText4">Règles fondamentales</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-12"><span class="HTitleText4">Éléments à inclure</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText4">Déductions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText4">Cessation de l’exploitation d’une entreprise</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-15"><span class="HTitleText4">Cas spéciaux</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Gains en capital imposables et pertes en capital déductibles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47.1 - </span><a href="#h-17"><span class="HTitleText4">Régimes de placements en titres indexés</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-18"><span class="HLabel3">SOUS-SECTION d</span> - <span class="HTitleText3">Autres sources de revenu</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-19"><span class="HLabel3">SOUS-SECTION e</span> - <span class="HTitleText3">Déductions dans le calcul du revenu</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-20"><span class="HLabel3">SOUS-SECTION f</span> - <span class="HTitleText3">Règles relatives au calcul du revenu</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-21"><span class="HLabel3">SOUS-SECTION g</span> - <span class="HTitleText3">Sommes exclues du calcul du revenu</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-22"><span class="HLabel3">SOUS-SECTION h</span> - <span class="HTitleText3">Les sociétés résidant au Canada et leurs actionnaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>86.1 - </span><a href="#h-23"><span class="HTitleText4">Distributions d’actions de l’étranger</span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-24"><span class="HLabel3">SOUS-SECTION i</span> - <span class="HTitleText3">Actionnaires de sociétés ne résidant pas au Canada</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-25"><span class="HLabel3">SOUS-SECTION j</span> - <span class="HTitleText3">Les sociétés de personnes et leurs associés</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-26"><span class="HLabel3">SOUS-SECTION k</span> - <span class="HTitleText3">Les fiducies et leurs bénéficiaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-27"><span class="HLabel2">SECTION C</span> - <span class="HTitleText2">Calcul du revenu imposable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110.2 - </span><a href="#h-28"><span class="HTitleText3">Paiements forfaitaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>115 - </span><a href="#h-29"><span class="HLabel2">SECTION D</span> - <span class="HTitleText2">Revenu imposable gagné au Canada par des non-résidents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>115.2 - </span><a href="#h-30"><span class="HTitleText3">Non-résidents et fournisseurs de services de placement canadiens</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-31"><span class="HLabel2">SECTION E</span> - <span class="HTitleText2">Calcul de l’impôt</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-32"><span class="HLabel3">SOUS-SECTION a</span> - <span class="HTitleText3">Règles applicables aux particuliers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117.1 - </span><a href="#h-33"><span class="HTitleText4">Rajustement annuel des déductions et autres sommes</span></a>
</li>
<li><span class='sectionRange'>120.31 - </span><a href="#h-34"><span class="HTitleText4">Paiements forfaitaires</span></a>
</li>
<li><span class='sectionRange'>120.4 - </span><a href="#h-35"><span class="HTitleText4">Impôt sur le revenu fractionné</span></a>
</li></ul>
</li><li><span class='sectionRange'>122.6 - </span><a href="#h-36"><span class="HLabel3">SOUS-SECTION a.1</span> - <span class="HTitleText3">Prestation fiscale canadienne pour enfants</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-37"><span class="HLabel3">SOUS-SECTION b</span> - <span class="HTitleText3">Règles applicable aux sociétés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123.4 - </span><a href="#h-38"><span class="HTitleText4">Réductions de l’impôt des sociétés</span></a>
</li>
<li><span class='sectionRange'>125.4 - </span><a href="#h-39"><span class="HTitleText4">Crédit d’impôt pour production cinématographique ou magnétoscopique canadienne</span></a>
</li>
<li><span class='sectionRange'>125.5 - </span><a href="#h-40"><span class="HTitleText4">Crédit d’impôt pour services de production cinématographique ou magnétoscopique</span></a>
</li></ul>
</li><li><span class='sectionRange'>126 - </span><a href="#h-41"><span class="HLabel3">SOUS-SECTION c</span> - <span class="HTitleText3">Règles applicables à tous les contribuables</span></a>
</li></ul>
</li><li><span class='sectionRange'>127.5 - </span><a href="#h-42"><span class="HLabel2">SECTION E.1</span> - <span class="HTitleText2">Impôt minimum</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-43"><span class="HLabel2">SECTION F</span> - <span class="HTitleText2">Règles spéciale applicables en certains cas</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>128 - </span><a href="#h-44"><span class="HTitleText3"> Faillites</span></a>
</li>
<li><span class='sectionRange'>128.1 - </span><a href="#h-45"><span class="HTitleText3">Changement de résidence</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-46"><span class="HTitleText3">Sociétés privées</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-47"><span class="HTitleText3">Sociétés de placement</span></a>
</li>
<li><span class='sectionRange'>130.1 - </span><a href="#h-48"><span class="HTitleText3">Sociétés de placement hypothécaire</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-49"><span class="HTitleText3">Sociétés de placement à capital variable</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-50"><span class="HTitleText3">Fiducies de fonds commun de placement</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-51"><span class="HTitleText3">Sociétés de placement appartenant à des non-résidents</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-52"><span class="HTitleText3">Ristournes</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-53"><span class="HTitleText3">Coopératives agricoles — ristournes à imposition différée</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-54"><span class="HTitleText3">Sociétés coopératives</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-55"><span class="HTitleText3">Caisses de crédit, caisses d’épargne et de crédit et compagnies d’assurance-dépôts</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-56"><span class="HTitleText3">Compagnies d’assurance</span></a>
</li>
<li><span class='sectionRange'>139.1 - </span><a href="#h-57"><span class="HTitleText3">Démutualisation des compagnies d’assurance</span></a>
</li>
<li><span class='sectionRange'>142.2 - </span><a href="#h-58"><span class="HTitleText3">Institutions Financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>142.2 - </span><a href="#h-59"><span class="HTitleText4">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>142.3 - </span><a href="#h-60"><span class="HTitleText4">Revenu provenant de titres de créance déterminés</span></a>
</li>
<li><span class='sectionRange'>142.4 - </span><a href="#h-61"><span class="HTitleText4">Disposition de titres de créance déterminés</span></a>
</li>
<li><span class='sectionRange'>142.5 - </span><a href="#h-62"><span class="HTitleText4">Biens évalués à la valeur du marché</span></a>
</li>
<li><span class='sectionRange'>142.6 - </span><a href="#h-63"><span class="HTitleText4">Autres règles</span></a>
</li>
<li><span class='sectionRange'>142.7 - </span><a href="#h-64"><span class="HTitleText4">Transformation d’une filiale de banque étrangère en succursale</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-65"><span class="HTitleText4">Organismes communautaires</span></a>
</li>
<li><span class='sectionRange'>143.2 - </span><a href="#h-66"><span class="HTitleText4">Coût des abris fiscaux déterminés</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>144 - </span><a href="#h-67"><span class="HLabel2">SECTION G</span> - <span class="HTitleText2">Régimes de participation différée et autres arrangements spéciaux relatifs aux revenus</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>144 - </span><a href="#h-68"><span class="HTitleText3">Régimes de participation des employés aux bénéfices</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-69"><span class="HTitleText3">Régimes enregistrés de prestations supplémentaires de chômage</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-70"><span class="HTitleText3">Régimes enregistrés d’épargne-retraite</span></a>
</li>
<li><span class='sectionRange'>146.01 - </span><a href="#h-71"><span class="HTitleText3">Régime d’accession à la propriété</span></a>
</li>
<li><span class='sectionRange'>146.02 - </span><a href="#h-72"><span class="HTitleText3">Régime d’éducation permanente</span></a>
</li>
<li><span class='sectionRange'>146.1 - </span><a href="#h-73"><span class="HTitleText3">Régimes enregistrés d’épargne-études</span></a>
</li>
<li><span class='sectionRange'>146.2 - </span><a href="#h-74"><span class="HTitleText3">Régimes enregistrés d’épargne-logement</span></a>
</li>
<li><span class='sectionRange'>146.3 - </span><a href="#h-75"><span class="HTitleText3">Fonds enregistrés de revenu de retraite</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-76"><span class="HTitleText3">Régimes de participation différée aux bénéfices</span></a>
</li>
<li><span class='sectionRange'>147.1 - </span><a href="#h-77"><span class="HTitleText3">Régimes de pension agréés</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-78"><span class="HTitleText3">Polices d’assurance-vie</span></a>
</li>
<li><span class='sectionRange'>148.1 - </span><a href="#h-79"><span class="HTitleText3">Arrangements de services funéraires</span></a>
</li></ul>
</li><li><span class='sectionRange'>149 - </span><a href="#h-80"><span class="HLabel2">SECTION H</span> - <span class="HTitleText2">Exemptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="#h-81"><span class="HTitleText3">Exemptions diverses</span></a>
</li>
<li><span class='sectionRange'>149.1 - </span><a href="#h-82"><span class="HTitleText3">Organismes de bienfaisance</span></a>
</li></ul>
</li><li><span class='sectionRange'>150 - </span><a href="#h-83"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Déclarations, cotisations, paiement et appels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>150 - </span><a href="#h-84"><span class="HTitleText3">Déclarations</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-85"><span class="HTitleText3">Estimation de l’impôt</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-86"><span class="HTitleText3">Cotisation</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-87"><span class="HTitleText3">Paiement de l’impôt</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-88"><span class="HTitleText3">Intérêts</span></a>
</li>
<li><span class='sectionRange'>161.1 - </span><a href="#h-89"><span class="HTitleText3">Compensation des intérêts créditeurs et des intérêts débiteurs</span></a>
</li>
<li><span class='sectionRange'>161.3 - </span><a href="#h-90"><span class="HTitleText3">Sommes minimes</span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-91"><span class="HTitleText3">Pénalités</span></a>
</li>
<li><span class='sectionRange'>163.2 - </span><a href="#h-92"><span class="HTitleText3">Information trompeuse en matière fiscale fournie par des tiers</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-93"><span class="HTitleText3">Remboursements</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-94"><span class="HTitleText3">Opposition à la cotisation</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-95"><span class="HTitleText3">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-96"><span class="HTitleText3">Révocation de l’enregistrement de certaines oeuvres et associations</span></a>
</li></ul>
</li><li><span class='sectionRange'>169 - </span><a href="#h-97"><span class="HLabel2">SECTION J</span> - <span class="HTitleText2">Appels auprès de la Cour canadienne de l’impôt et de la Cour d’appel fédérale</span></a>
</li></ul>
</li><li><span class='sectionRange'>180.1 - </span><a href="#h-98"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Impôt supplémentaire (revenus des particuliers)</span></a>
</li>
<li><span class='sectionRange'>180.2 - </span><a href="#h-99"><span class="HLabel1">PARTIE I.2</span> - <span class="HTitleText1">Impôt sur les prestations de sécurité de la vieillesse</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-100"><span class="HLabel1">PARTIE I.3</span> - <span class="HTitleText1">Impôt des grandes sociétés</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-101"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Surtaxe des fabricants de tabac</span></a>
</li>
<li><span class='sectionRange'>183.1 - </span><a href="#h-102"><span class="HLabel1">PARTIE II.1</span> - <span class="HTitleText1">Impôt sur certaines distributions de surplus</span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-103"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Impôt supplémentaire sur les excédents résultant d’un choix</span></a>
</li>
<li><span class='sectionRange'>185.1 - </span><a href="#h-104"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Impôt supplémentaire sur les désignations excessives de dividendes déterminés</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-105"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Impôt sur les dividendes imposables reçus par les sociétés privées</span></a>
</li>
<li><span class='sectionRange'>187.1 - </span><a href="#h-106"><span class="HLabel1">PARTIE IV.1</span> - <span class="HTitleText1">Imposition des dividendes reçus par des sociétés sur certaines actions privilégiées</span></a>
</li>
<li><span class='sectionRange'>187.7 - </span><a href="#h-107"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Impôt et pénalités relatifs aux organismes de bienfaisance enregistrés</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-108"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Impôt des institutions financières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>190.1 - </span><a href="#h-109"><span class="HTitleText2">Calcul de l’impôt</span></a>
</li>
<li><span class='sectionRange'>190.16 - </span><a href="#h-110"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>190.2 - </span><a href="#h-111"><span class="HTitleText2">Dispositions d’ordre administratif</span></a>
</li></ul>
</li><li><span class='sectionRange'>191 - </span><a href="#h-112"><span class="HLabel1">PARTIE VI.1</span> - <span class="HTitleText1">Imposition des sociétés versant des dividendes sur des actions privilégiées imposables</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-113"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Impôt remboursable aux sociétés émettant des actions admissibles</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-114"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Impôt sur les sociétés remboursable au titre du crédit d’impôt pour des activités de recherche scientifique et de développement expérimental</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-115"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Impôt sur la déduction visée à l’article 66.5</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-116"><span class="HLabel1">PARTIE IX.1</span> - <span class="HTitleText1">Impôt des sociétés de personnes intermédiaires de placement déterminées</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-117"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Impôts sur les régimes de participation différée aux bénéfices et sur les régimes dont l’agrément est retiré</span></a>
</li>
<li><span class='sectionRange'>204.1 - </span><a href="#h-118"><span class="HLabel1">PARTIE X.1</span> - <span class="HTitleText1">Impôt frappant les excédents de contribution aux régimes de revenu différé</span></a>
</li>
<li><span class='sectionRange'>204.4 - </span><a href="#h-119"><span class="HLabel1">PARTIE X.2</span> - <span class="HTitleText1">Impôt sur les placements enregistrés</span></a>
</li>
<li><span class='sectionRange'>204.8 - </span><a href="#h-120"><span class="HLabel1">PARTIE X.3</span> - <span class="HTitleText1">Sociétés à capital de risque de travailleurs</span></a>
</li>
<li><span class='sectionRange'>204.9 - </span><a href="#h-121"><span class="HLabel1">PARTIE X.4</span> - <span class="HTitleText1">Impôt sur les versements excédentaires aux régimes enregistrés d’épargne-études</span></a>
</li>
<li><span class='sectionRange'>204.94 - </span><a href="#h-122"><span class="HLabel1">PARTIE X.5</span> - <span class="HTitleText1">Paiements dans le cadre de régimes enregistrés d’épargne-études</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-123"><span class="HLabel1">PARTIE XI</span>[Abrogée, 2005, ch. 30, art. 14] </a>
</li>
<li><span class='sectionRange'>207.1 - </span><a href="#h-124"><span class="HLabel1">PARTIE XI.1</span> - <span class="HTitleText1">Impôt relatif aux régimes de revenu différé et à d’autres personnes exonérées d’impôt</span></a>
</li>
<li><span class='sectionRange'>207.3 - </span><a href="#h-125"><span class="HLabel1">PARTIE XI.2</span> - <span class="HTitleText1">Impôt sur la disposition de certains biens</span></a>
</li>
<li><span class='sectionRange'>207.5 - </span><a href="#h-126"><span class="HLabel1">PARTIE XI.3</span> - <span class="HTitleText1">Impôt sur les conventions de retraite</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-127"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Impôt relatif à certains impôts, loyers, à certaines redevances, etc. versés à un gouvernement par une personne exonérée d’impôt</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-128"><span class="HLabel1">PARTIE XII.1</span> - <span class="HTitleText1">Impôt sur les revenus miniers et pétroliers tirés de biens restreints</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-129"><span class="HLabel1">PARTIE XII.2</span> - <span class="HTitleText1">Impôt sur le revenu distribué de certaines fiducies</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-130"><span class="HLabel1">PARTIE XII.3</span> - <span class="HTitleText1">Impôt sur le revenu de placement des assureurs sur la vie</span></a>
</li>
<li><span class='sectionRange'>211.6 - </span><a href="#h-131"><span class="HLabel1">PARTIE XII.4</span> - <span class="HTitleText1">Impôt des fiducies pour l’environnement admissible</span></a>
</li>
<li><span class='sectionRange'>211.7 - </span><a href="#h-132"><span class="HLabel1">PARTIE XII.5</span> - <span class="HTitleText1">Recouvrement du crédit d’impôt relatif à un fonds de travailleurs</span></a>
</li>
<li><span class='sectionRange'>211.91 - </span><a href="#h-133"><span class="HLabel1">PARTIE XII.6</span> - <span class="HTitleText1">Impôt sur les actions accréditives</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-134"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Impôt sur le revenu de personnes non-résidentes provenant du Canada</span></a>
</li>
<li><span class='sectionRange'>218.2 - </span><a href="#h-135"><span class="HLabel1">PARTIE XIII.1</span> - <span class="HTitleText1">Impôt supplémentaire des banques étrangères autorisées</span></a>
</li>
<li><span class='sectionRange'>218.3 - </span><a href="#h-136"><span class="HLabel1">PARTIE XIII.2</span> - <span class="HTitleText1">Placements de non-résidents dans les fonds communs de placement canadiens</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-137"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Impôt supplémentaire des sociétés non-résidentes</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-138"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Application et exécution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-139"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-140"><span class="HTitleText2">Recouvrement</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-141"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-142"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>244 - </span><a href="#h-143"><span class="HTitleText2">Procédure et preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>245 - </span><a href="#h-144"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Évitement fiscal</span></a>
</li>
<li><span class='sectionRange'>247 - </span><a href="#h-145"><span class="HLabel1">PARTIE XVI.1</span> - <span class="HTitleText1">Prix de transfert</span></a>
</li>
<li><span class='sectionRange'>248 - </span><a href="#h-146"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Interprétation</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
