<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’École de la fonction publique du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-49168"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-49173"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-49186"><span class="HTitleText1">Prorogation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-49200"><span class="HTitleText1">Mission et attributions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-49236"><span class="HTitleText1">Président et personnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="page-1.html#h-49237"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-49253"><span class="HTitleText2">Personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-49265"><span class="HTitleText1">Services en matière de formation et de recherche</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-1.html#h-49271"><span class="HTitleText1">Redevances</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-49281"><span class="HTitleText1">Examen et rapport</span></a>
</li>
<li><span class='sectionRange'>21 à 25 - </span><a href="page-1.html#h-49294"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-49296"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

