<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les Indiens (Établissement de soldats)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1033596"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-1033602"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Établissement de soldats</span></a>
</li></ul>
</li></ul>

</nav>

