<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Royal Canadian Mounted Police Pension Continuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-420299"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-420304"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-420326"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-420363"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Officers’ Pensions</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-420545"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Constables’ Pensions</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-3.html#h-420654"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Widows’ and Orphans’ Pensions</span></a>
</li>
<li><a href="page-5.html#h-420795"><span class="scheduleLabel">SCHEDULE TO PART IV</span> - <span class="scheduleTitleText"> - Contributions Required To Purchase Benefits Described in Section 48</span></a>
</li></ul>
</li></ul>

</nav>

