<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère des Travaux publics et des Services gouvernementaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-400468"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-400471"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-400482"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-400495"><span class="HTitleText1">Mission du ministère</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-400498"><span class="HTitleText1">Pouvoirs et fonctions du ministre</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-400603"><span class="HTitleText1">Imprimerie nationale</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-400609"><span class="HTitleText1">Marchés</span></a>
</li>
<li><span class='sectionRange'>22.1 - </span><a href="#h-400621"><span class="HTitleText1">Ombudsman de l’approvisionnement</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-400655"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-400680"><span class="HTitleText1">Lits des cours d’eau navigables</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-400683"><span class="HTitleText1">Preuve</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-400686"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>29 à 59 - </span><a href="#h-400700"><span class="HTitleText1">Modifications connexes</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-400702"><span class="HTitleText1">Nouvelle terminologie</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-400711"><span class="HTitleText1">Modification conditionnelle</span></a>
</li>
<li><span class='sectionRange'>63 à 66 - </span><a href="#h-400713"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-400715"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

