<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Unemployment Assistance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-461853"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-461858"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-461867"><span class="HTitleText1">Agreements with Provinces</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-461905"><span class="HTitleText1">Payments</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-461910"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-461915"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><a href="#h-461921"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

