<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur les lieux et monuments historiques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-248635"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-248640"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-248648"><span class="HTitleText1">Lieux historiques</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-248658"><span class="HTitleText1">Commission des lieux et monuments historiques du Canada</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-248709"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

