<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Space Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-75016"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-75019"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-75029"><span class="HTitleText1">Establishment of Agency</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-75032"><span class="HTitleText1">Objects and Functions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-75061"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-75093"><span class="HTitleText1">Organization of Agency</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-75134"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>24 to 27 - </span><a href="#h-75137"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-75139"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-75145"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

