<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les télécommunications</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-448925"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-448928"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-448929"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-448960"><span class="HTitleText2">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-448963"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-448972"><span class="HTitleText2">Politique canadienne de télécommunication</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-448984"><span class="HTitleText2">Pouvoirs du gouverneur en conseil, du Conseil et du ministre</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-449052"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Admissibilité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-449053"><span class="HTitleText2">Propriété et contrôle canadiens</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-449090"><span class="HTitleText2">Licences de services de télécommunication internationale</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-449126"><span class="HTitleText2">Licences de câble sous-marin international</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-449149"><span class="HTitleText2">Preuve documentaire</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-449152"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-449181"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Tarifs, installations et services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="#h-449182"><span class="HTitleText2">Fourniture de services</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-449226"><span class="HTitleText2">Itinérance</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-449262"><span class="HTitleText2">Abstention</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-449274"><span class="HTitleText2">Ordre de fourniture de services</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-449282"><span class="HTitleText2">Contenu des messages</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-449285"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-449326"><span class="HTitleText2">Interconnexion d’installations</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-449332"><span class="HTitleText2">Télécommunications non sollicitées</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-449430"><span class="HTitleText2">Construction et expropriation</span></a>
</li>
<li><span class='sectionRange'>46.1 - </span><a href="#h-449468"><span class="HTitleText2">Ressources en matière de numérotage et autres questions</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="#h-449510"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>47 - </span><a href="#h-449511"><span class="HTitleText2">Exercice des pouvoirs et fonctions par le Conseil</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-449545"><span class="HTitleText2">Directives et avis du Conseil</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-449553"><span class="HTitleText2">Décisions du Conseil</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-449574"><span class="HTitleText2">Appel</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-449590"><span class="HTitleText2">Preuve</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-449604"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>69.1 - </span><a href="#h-449630"><span class="HLabel1">PARTIE IV.1</span> - <span class="HTitleText1">Appareils de télécommunication</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69.1 - </span><a href="#h-449631"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>69.2 - </span><a href="#h-449636"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>69.3 - </span><a href="#h-449644"><span class="HTitleText2">Pouvoirs ministériels</span></a>
</li>
<li><span class='sectionRange'>69.4 - </span><a href="#h-449673"><span class="HTitleText2">Pouvoirs du gouverneur en conseil et autres</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-449692"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Enquêtes et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>70 - </span><a href="#h-449693"><span class="HTitleText2">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-449705"><span class="HTitleText2">Inspecteurs</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-449738"><span class="HTitleText2">Responsabilité civile</span></a>
</li>
<li><span class='sectionRange'>72.001 - </span><a href="#h-449748"><span class="HTitleText2">Sanctions administratives pécuniaires — régime général</span></a>
</li>
<li><span class='sectionRange'>72.01 - </span><a href="#h-449859"><span class="HTitleText2">Sanctions administratives pécuniaires — télécommunications non sollicitées</span></a>
</li>
<li><span class='sectionRange'>72.14 - </span><a href="#h-449929"><span class="HTitleText2">Dispositions communes aux régimes de sanctions administratives pécuniaires</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-449961"><span class="HTitleText2">Infractions</span></a>
</li>
<li><span class='sectionRange'>74.1 - </span><a href="#h-449994"><span class="HTitleText2">Confiscation</span></a>
</li></ul>
</li><li><span class='sectionRange'>75 - </span><a href="#h-450015"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>77 à 129 - </span><a href="#h-450030"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Modifications corrélatives, abrogations, application de certaines dispositions et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 à 129 - </span><a href="#h-450031"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>130 et 131 - </span><a href="#h-450033"><span class="HTitleText2">Abrogations</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-450035"><span class="HTitleText2">Application de certaines dispositions</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-450040"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

