<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée nationale du violon traditionnel</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-370752"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-370755"><span class="HTitleText1">Journée nationale du violon traditionnel</span></a>
</li></ul>
</li></ul>

</nav>

