<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Emission Reduction Incentives Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-3"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText1">Designations</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText1">Establishment of Agency</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Object</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">Organization and Head Office</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText1">Advisory Board</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText1">Employees</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText1">Duties and Powers of the Agency</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-11"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-12"><span class="HTitleText1">Corporate Business Plan</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-13"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText1">Annual Report</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
