<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal-Provincial Fiscal Arrangements Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-238871"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-238876"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-238886"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Equalization, Stabilization and Succession Duty Payments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-238911"><span class="HTitleText2">Provincial Revenue Equalization Payments</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-238983"><span class="HTitleText2">Provincial Revenue Stabilization Payments</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-239001"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Post-Secondary Education Adjustment Payments</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-239135"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20 - </span><a href="#h-239136"><span class="HTitleText2">Tax Collection Agreements</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-239154"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

