<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les sociétés d'assurances</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Définitions et application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Constitution, prorogation et cessation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText2">Formalités constitutives</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-9"><span class="HTitleText2">Prorogation</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-10"><span class="HTitleText2">Cessation</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-11"><span class="HTitleText2">Dénomination sociale</span></a>
</li></ul>
</li><li><span class='sectionRange'>49 - </span><a href="#h-12"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Organisation et fonctionnement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49 - </span><a href="#h-13"><span class="HTitleText2">Réunions</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-14"><span class="HTitleText2">Fonctionnement initial</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="#h-15"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Structure du capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>63 - </span><a href="#h-16"><span class="HTitleText2">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>83.01 - </span><a href="#h-17"><span class="HTitleText2">Restrictions particulières aux actions de sociétés mutuelles</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-18"><span class="HTitleText2">Titres secondaires</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-19"><span class="HTitleText2">Certificats de valeurs mobilières et transferts</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-20"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Administration de la société</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-21"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Actionnaires et souscripteurs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-22"><span class="HTitleText3">Lieu des assemblées</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-23"><span class="HTitleText3">Convocation des assemblées</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-24"><span class="HTitleText3">Dates de référence</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-25"><span class="HTitleText3">Avis des assemblées</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-26"><span class="HTitleText3">Propositions des actionnaires et des souscripteurs</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-27"><span class="HTitleText3">Listes des actionnaires et des souscripteurs</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-28"><span class="HTitleText3">Quorum</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-29"><span class="HTitleText3">Vote</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-30"><span class="HTitleText3">Résolution tenant lieu d’assemblée</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-31"><span class="HTitleText3">Demande de convocation</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-32"><span class="HTitleText3">Pouvoirs du tribunal</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-33"><span class="HTitleText3">Conventions de vote</span></a>
</li></ul>
</li><li><span class='sectionRange'>164 - </span><a href="#h-34"><span class="HLabel2">SECTION I.1</span> - <span class="HTitleText2">Procurations</span></a>
</li>
<li><span class='sectionRange'>164.08 - </span><a href="#h-35"><span class="HLabel2">SECTION I.2</span> - <span class="HTitleText2">Restriction du droit de vote</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-36"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Administrateurs et dirigeants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-37"><span class="HTitleText3">Obligations</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-38"><span class="HTitleText3">Administrateurs — Nombre et qualités</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-39"><span class="HTitleText3">Administrateurs — Élection et fonctions</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-40"><span class="HTitleText3">Élections incomplètes et vacances d’administrateurs</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-41"><span class="HTitleText3">Réunions du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-42"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-43"><span class="HTitleText3">Comités du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-44"><span class="HTitleText3">Mandat des administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-45"><span class="HTitleText3">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-46"><span class="HTitleText3">Responsabilité, exonération et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>224 - </span><a href="#h-47"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Modifications de structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>224 - </span><a href="#h-48"><span class="HTitleText3">Modifications — Lettres patentes</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-49"><span class="HTitleText3">Mutualisation</span></a>
</li>
<li><span class='sectionRange'>236.1 - </span><a href="#h-50"><span class="HTitleText3">Transformation en société avec actions ordinaires</span></a>
</li>
<li><span class='sectionRange'>238 - </span><a href="#h-51"><span class="HTitleText3">Modifications — Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-52"><span class="HTitleText3">Fusion</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-53"><span class="HTitleText3">Ventes d’éléments d’actif et réassurance</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="#h-54"><span class="HLabel2">SECTION IV</span> - <span class="HTitleText2">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-55"><span class="HLabel2">SECTION V</span> - <span class="HTitleText2">Registres des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-56"><span class="HLabel2">SECTION VI</span> - <span class="HTitleText2">Dénomination sociale et sceau</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-57"><span class="HLabel2">SECTION VII</span> - <span class="HTitleText2"></span>[Abrogée, 1997, ch. 15, art. 230] </a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-58"><span class="HLabel2">SECTION VIII</span> - <span class="HTitleText2">Initiés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>288 - </span><a href="#h-59"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>289 - </span><a href="#h-60"><span class="HTitleText3">Rapport d’initié</span></a>
</li>
<li><span class='sectionRange'>293 - </span><a href="#h-61"><span class="HTitleText3">Opérations d’initiés</span></a>
</li>
<li><span class='sectionRange'>294 - </span><a href="#h-62"><span class="HTitleText3">Recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>296 - </span><a href="#h-63"><span class="HLabel2">SECTION IX</span> - <span class="HTitleText2">Prospectus</span></a>
</li>
<li><span class='sectionRange'>307 - </span><a href="#h-64"><span class="HLabel2">SECTION X</span> - <span class="HTitleText2">Offres publiques d’achat</span></a>
</li>
<li><span class='sectionRange'>317 - </span><a href="#h-65"><span class="HLabel2">SECTION XI</span> - <span class="HTitleText2">Acte de fiducie</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="#h-66"><span class="HLabel2">SECTION XII</span> - <span class="HTitleText2">Rapports financiers</span></a>
</li>
<li><span class='sectionRange'>336 - </span><a href="#h-67"><span class="HLabel2">SECTION XIII</span> - <span class="HTitleText2">Vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>336 - </span><a href="#h-68"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>337 - </span><a href="#h-69"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>338 - </span><a href="#h-70"><span class="HTitleText3">Conditions</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-71"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>346 - </span><a href="#h-72"><span class="HTitleText3">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>356 - </span><a href="#h-73"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>357 - </span><a href="#h-74"><span class="HLabel2">SECTION XIV</span> - <span class="HTitleText2">Actuaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>357 - </span><a href="#h-75"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>360 - </span><a href="#h-76"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>365 - </span><a href="#h-77"><span class="HTitleText3">Évaluations et rapports</span></a>
</li>
<li><span class='sectionRange'>370 - </span><a href="#h-78"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>371 - </span><a href="#h-79"><span class="HLabel2">SECTION XV</span> - <span class="HTitleText2">Recours judiciaires</span></a>
</li>
<li><span class='sectionRange'>376 - </span><a href="#h-80"><span class="HLabel2">SECTION XVI</span> - <span class="HTitleText2">Liquidation et dissolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>376 - </span><a href="#h-81"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>377 - </span><a href="#h-82"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>380 - </span><a href="#h-83"><span class="HTitleText3">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>385 - </span><a href="#h-84"><span class="HTitleText3">Surveillance judiciaire</span></a>
</li>
<li><span class='sectionRange'>399 - </span><a href="#h-85"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>406.1 - </span><a href="#h-86"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>406.1 - </span><a href="#h-87"><span class="HLabel2">SECTION I</span> - <span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>407 - </span><a href="#h-88"><span class="HLabel2">SECTION II</span> - <span class="HTitleText2">Restrictions à la propriété</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>419 - </span><a href="#h-89"><span class="HTitleText3">Procédure d’agrément</span></a>
</li></ul>
</li><li><span class='sectionRange'>432 - </span><a href="#h-90"><span class="HLabel2">SECTION III</span> - <span class="HTitleText2">Arrêtés et ordonnances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>434 - </span><a href="#h-91"><span class="HTitleText3">Dispositions d’ordre général</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>440 - </span><a href="#h-92"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Activité et pouvoirs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>440 - </span><a href="#h-93"><span class="HTitleText2">Activités générales</span></a>
</li>
<li><span class='sectionRange'>443 - </span><a href="#h-94"><span class="HTitleText2">Branches d’assurance</span></a>
</li>
<li><span class='sectionRange'>450 - </span><a href="#h-95"><span class="HTitleText2">Caisses séparées</span></a>
</li>
<li><span class='sectionRange'>456 - </span><a href="#h-96"><span class="HTitleText2">Polices à participation</span></a>
</li>
<li><span class='sectionRange'>465 - </span><a href="#h-97"><span class="HTitleText2">Réassurance</span></a>
</li>
<li><span class='sectionRange'>466 - </span><a href="#h-98"><span class="HTitleText2">Restrictions</span></a>
</li>
<li><span class='sectionRange'>473 - </span><a href="#h-99"><span class="HTitleText2">Restrictions particulières aux sociétés d’assurance-vie</span></a>
</li>
<li><span class='sectionRange'>476 - </span><a href="#h-100"><span class="HTitleText2">Restrictions particulières aux sociétés d’assurances multirisques</span></a>
</li>
<li><span class='sectionRange'>479 - </span><a href="#h-101"><span class="HTitleText2">Coût d’emprunt</span></a>
</li>
<li><span class='sectionRange'>486 - </span><a href="#h-102"><span class="HTitleText2">Réclamations</span></a>
</li>
<li><span class='sectionRange'>488 - </span><a href="#h-103"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>490 - </span><a href="#h-104"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>490 - </span><a href="#h-105"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>492 - </span><a href="#h-106"><span class="HTitleText2">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>495 - </span><a href="#h-107"><span class="HTitleText2">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>498 - </span><a href="#h-108"><span class="HTitleText2">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>502 - </span><a href="#h-109"><span class="HTitleText2">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>503 - </span><a href="#h-110"><span class="HTitleText2">Prêts commerciaux : sociétés d’assurance-vie</span></a>
</li>
<li><span class='sectionRange'>505 - </span><a href="#h-111"><span class="HTitleText2">Prêts commerciaux et à la consommation : sociétés d’assurances multirisques</span></a>
</li>
<li><span class='sectionRange'>506 - </span><a href="#h-112"><span class="HTitleText2">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>507 - </span><a href="#h-113"><span class="HTitleText2">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>508 - </span><a href="#h-114"><span class="HTitleText2">Limite globale</span></a>
</li>
<li><span class='sectionRange'>509 - </span><a href="#h-115"><span class="HTitleText2">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>515 - </span><a href="#h-116"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Capital et liquidités</span></a>
</li>
<li><span class='sectionRange'>517.1 - </span><a href="#h-117"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Opérations avec apparentés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>517.1 - </span><a href="#h-118"><span class="HTitleText2">Interprétation et application</span></a>
</li>
<li><span class='sectionRange'>521 - </span><a href="#h-119"><span class="HTitleText2">Opérations interdites</span></a>
</li>
<li><span class='sectionRange'>522 - </span><a href="#h-120"><span class="HTitleText2">Opérations permises</span></a>
</li>
<li><span class='sectionRange'>534 - </span><a href="#h-121"><span class="HTitleText2">Restrictions applicables aux opérations permises</span></a>
</li>
<li><span class='sectionRange'>537 - </span><a href="#h-122"><span class="HTitleText2">Obligation d’information</span></a>
</li>
<li><span class='sectionRange'>539 - </span><a href="#h-123"><span class="HTitleText2">Recours</span></a>
</li></ul>
</li><li><span class='sectionRange'>540 - </span><a href="#h-124"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Sociétés de secours mutuels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>540 - </span><a href="#h-125"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>541 - </span><a href="#h-126"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>543 - </span><a href="#h-127"><span class="HTitleText2">Administration</span></a>
</li>
<li><span class='sectionRange'>550 - </span><a href="#h-128"><span class="HTitleText2">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>550 - </span><a href="#h-129"><span class="HTitleText3">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>551 - </span><a href="#h-130"><span class="HTitleText3">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>554 - </span><a href="#h-131"><span class="HTitleText3">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>557 - </span><a href="#h-132"><span class="HTitleText3">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>561 - </span><a href="#h-133"><span class="HTitleText3">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>562 - </span><a href="#h-134"><span class="HTitleText3">Prêts commerciaux et à la consommation</span></a>
</li>
<li><span class='sectionRange'>563 - </span><a href="#h-135"><span class="HTitleText3">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>565 - </span><a href="#h-136"><span class="HTitleText3">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>566 - </span><a href="#h-137"><span class="HTitleText3">Limite globale</span></a>
</li>
<li><span class='sectionRange'>567 - </span><a href="#h-138"><span class="HTitleText3">Divers</span></a>
</li>
<li><span class='sectionRange'>570 - </span><a href="#h-139"><span class="HTitleText3">Non-interdiction</span></a>
</li></ul>
</li><li><span class='sectionRange'>570.01 - </span><a href="#h-140"><span class="HTitleText2">Liquidation et dissolution d’une société de secours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>570.01 - </span><a href="#h-141"><span class="HTitleText3">Définition</span></a>
</li>
<li><span class='sectionRange'>570.02 - </span><a href="#h-142"><span class="HTitleText3">Application</span></a>
</li>
<li><span class='sectionRange'>570.03 - </span><a href="#h-143"><span class="HTitleText3">Obligation de fournir des renseignements</span></a>
</li>
<li><span class='sectionRange'>570.04 - </span><a href="#h-144"><span class="HTitleText3">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>570.09 - </span><a href="#h-145"><span class="HTitleText3">Surveillance judiciaire</span></a>
</li>
<li><span class='sectionRange'>570.23 - </span><a href="#h-146"><span class="HTitleText3">Dispositions générales</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>571 - </span><a href="#h-147"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Sociétés d’assurances étrangères</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>571 - </span><a href="#h-148"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>572 - </span><a href="#h-149"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>573 - </span><a href="#h-150"><span class="HTitleText2">Garantie de risques au Canada</span></a>
</li>
<li><span class='sectionRange'>588 - </span><a href="#h-151"><span class="HTitleText2">Branches d’assurance</span></a>
</li>
<li><span class='sectionRange'>592 - </span><a href="#h-152"><span class="HTitleText2">Caisses séparées</span></a>
</li>
<li><span class='sectionRange'>596 - </span><a href="#h-153"><span class="HTitleText2">Réassurance</span></a>
</li>
<li><span class='sectionRange'>598 - </span><a href="#h-154"><span class="HTitleText2">Coût d’emprunt</span></a>
</li>
<li><span class='sectionRange'>604 - </span><a href="#h-155"><span class="HTitleText2">Réclamations</span></a>
</li>
<li><span class='sectionRange'>606 - </span><a href="#h-156"><span class="HTitleText2">Divers</span></a>
</li>
<li><span class='sectionRange'>608 - </span><a href="#h-157"><span class="HTitleText2">Capital ou actif suffisant</span></a>
</li>
<li><span class='sectionRange'>610 - </span><a href="#h-158"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>611 - </span><a href="#h-159"><span class="HTitleText2">Actif au Canada</span></a>
</li>
<li><span class='sectionRange'>613 - </span><a href="#h-160"><span class="HTitleText2">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>613 - </span><a href="#h-161"><span class="HTitleText3">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>615 - </span><a href="#h-162"><span class="HTitleText3">Restrictions générales</span></a>
</li>
<li><span class='sectionRange'>616 - </span><a href="#h-163"><span class="HTitleText3">Prêts commerciaux par les sociétés d’assurance-vie étrangères</span></a>
</li>
<li><span class='sectionRange'>617 - </span><a href="#h-164"><span class="HTitleText3">Prêts commerciaux et à la consommation par les sociétés d’assurances multirisques étrangères</span></a>
</li>
<li><span class='sectionRange'>618 - </span><a href="#h-165"><span class="HTitleText3">Biens immeubles</span></a>
</li>
<li><span class='sectionRange'>619 - </span><a href="#h-166"><span class="HTitleText3">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>620 - </span><a href="#h-167"><span class="HTitleText3">Limite globale</span></a>
</li></ul>
</li><li><span class='sectionRange'>621 - </span><a href="#h-168"><span class="HTitleText2">Opérations avec apparentés</span></a>
</li>
<li><span class='sectionRange'>623 - </span><a href="#h-169"><span class="HTitleText2">Actuaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>623 - </span><a href="#h-170"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>625 - </span><a href="#h-171"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>628 - </span><a href="#h-172"><span class="HTitleText3">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>632 - </span><a href="#h-173"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>633 - </span><a href="#h-174"><span class="HTitleText2">Vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>633 - </span><a href="#h-175"><span class="HTitleText3">Nomination</span></a>
</li>
<li><span class='sectionRange'>634 - </span><a href="#h-176"><span class="HTitleText3">Conditions</span></a>
</li>
<li><span class='sectionRange'>636 - </span><a href="#h-177"><span class="HTitleText3">Vacances</span></a>
</li>
<li><span class='sectionRange'>641 - </span><a href="#h-178"><span class="HTitleText3">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>646 - </span><a href="#h-179"><span class="HTitleText3">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>647 - </span><a href="#h-180"><span class="HTitleText2">Livres</span></a>
</li>
<li><span class='sectionRange'>650 - </span><a href="#h-181"><span class="HTitleText2">Cessation des opérations d’assurance au Canada</span></a>
</li></ul>
</li><li><span class='sectionRange'>656 - </span><a href="#h-182"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Sociétés provinciales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>656 - </span><a href="#h-183"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>657 - </span><a href="#h-184"><span class="HTitleText2">Autorisation de fonctionnement</span></a>
</li>
<li><span class='sectionRange'>660 - </span><a href="#h-185"><span class="HTitleText2">Obligations des administrateurs</span></a>
</li>
<li><span class='sectionRange'>661 - </span><a href="#h-186"><span class="HTitleText2">Livres et registres</span></a>
</li></ul>
</li><li><span class='sectionRange'>663 - </span><a href="#h-187"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Réglementation des sociétés, sociétés de secours, sociétés étrangères et sociétés provinciales : surintendant</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>663 - </span><a href="#h-188"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>664 - </span><a href="#h-189"><span class="HTitleText2">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>664 - </span><a href="#h-190"><span class="HTitleText3">États</span></a>
</li>
<li><span class='sectionRange'>674 - </span><a href="#h-191"><span class="HTitleText3">Enquête sur les sociétés</span></a>
</li></ul>
</li><li><span class='sectionRange'>675.1 - </span><a href="#h-192"><span class="HTitleText2">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>675.1 - </span><a href="#h-193"><span class="HTitleText3">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>676 - </span><a href="#h-194"><span class="HTitleText3">Décisions</span></a>
</li>
<li><span class='sectionRange'>678.01 - </span><a href="#h-195"><span class="HTitleText3">Rejet des candidatures et destitution</span></a>
</li>
<li><span class='sectionRange'>678.5 - </span><a href="#h-196"><span class="HTitleText3">Surveillance et intervention</span></a>
</li>
<li><span class='sectionRange'>686 - </span><a href="#h-197"><span class="HTitleText3">Cotisations particulières des sociétés</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>693 - </span><a href="#h-198"><span class="HLabel1">PARTIE XVI</span> - <span class="HTitleText1">Réglementation des sociétés et sociétés étrangères : commissaire</span></a>
</li>
<li><span class='sectionRange'>699 - </span><a href="#h-199"><span class="HLabel1">PARTIE XVII</span> - <span class="HTitleText1">Sociétés de portefeuille d’assurances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>699 - </span><a href="#h-200"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>700 - </span><a href="#h-201"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>701 - </span><a href="#h-202"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>708 - </span><a href="#h-203"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Constitution, prorogation et cessation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>708 - </span><a href="#h-204"><span class="HTitleText3">Formalités constitutives</span></a>
</li>
<li><span class='sectionRange'>719 - </span><a href="#h-205"><span class="HTitleText3">Prorogation</span></a>
</li>
<li><span class='sectionRange'>726 - </span><a href="#h-206"><span class="HTitleText3">Cessation</span></a>
</li>
<li><span class='sectionRange'>730 - </span><a href="#h-207"><span class="HTitleText3">Dénomination sociale</span></a>
</li>
<li><span class='sectionRange'>738 - </span><a href="#h-208"><span class="HTitleText3">Publication de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>739 - </span><a href="#h-209"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Organisation et fonctionnement</span></a>
</li>
<li><span class='sectionRange'>742 - </span><a href="#h-210"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Structure du capital</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>742 - </span><a href="#h-211"><span class="HTitleText3">Capital-actions</span></a>
</li>
<li><span class='sectionRange'>762 - </span><a href="#h-212"><span class="HTitleText3">Titres secondaires</span></a>
</li>
<li><span class='sectionRange'>763 - </span><a href="#h-213"><span class="HTitleText3">Certificats de valeurs mobilières et transferts</span></a>
</li></ul>
</li><li><span class='sectionRange'>764 - </span><a href="#h-214"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Administration de la société de portefeuille d’assurances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>764 - </span><a href="#h-215"><span class="HLabel3">SOUS-SECTION 1</span> - <span class="HTitleText3">Actionnaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>764 - </span><a href="#h-216"><span class="HTitleText4">Lieu des assemblées</span></a>
</li>
<li><span class='sectionRange'>765 - </span><a href="#h-217"><span class="HTitleText4">Convocation des assemblées</span></a>
</li>
<li><span class='sectionRange'>766 - </span><a href="#h-218"><span class="HTitleText4">Dates de référence</span></a>
</li>
<li><span class='sectionRange'>767 - </span><a href="#h-219"><span class="HTitleText4">Avis des assemblées</span></a>
</li>
<li><span class='sectionRange'>770 - </span><a href="#h-220"><span class="HTitleText4">Propositions des actionnaires</span></a>
</li>
<li><span class='sectionRange'>772 - </span><a href="#h-221"><span class="HTitleText4">Liste des actionnaires</span></a>
</li>
<li><span class='sectionRange'>773 - </span><a href="#h-222"><span class="HTitleText4">Quorum</span></a>
</li>
<li><span class='sectionRange'>775 - </span><a href="#h-223"><span class="HTitleText4">Vote</span></a>
</li>
<li><span class='sectionRange'>779 - </span><a href="#h-224"><span class="HTitleText4">Résolution tenant lieu d’assemblée</span></a>
</li>
<li><span class='sectionRange'>780 - </span><a href="#h-225"><span class="HTitleText4">Demande de convocation</span></a>
</li>
<li><span class='sectionRange'>781 - </span><a href="#h-226"><span class="HTitleText4">Pouvoirs du tribunal</span></a>
</li>
<li><span class='sectionRange'>784 - </span><a href="#h-227"><span class="HTitleText4">Conventions de vote</span></a>
</li></ul>
</li><li><span class='sectionRange'>785 - </span><a href="#h-228"><span class="HLabel3">SOUS-SECTION 2</span> - <span class="HTitleText3">Procurations et restriction du droit de vote</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>785 - </span><a href="#h-229"><span class="HTitleText4">Procurations</span></a>
</li>
<li><span class='sectionRange'>793 - </span><a href="#h-230"><span class="HTitleText4">Restriction du droit de vote</span></a>
</li></ul>
</li><li><span class='sectionRange'>794 - </span><a href="#h-231"><span class="HLabel3">SOUS-SECTION 3</span> - <span class="HTitleText3">Administrateurs et dirigeants</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>794 - </span><a href="#h-232"><span class="HTitleText4">Obligations</span></a>
</li>
<li><span class='sectionRange'>796 - </span><a href="#h-233"><span class="HTitleText4">Administrateurs — nombre et qualités</span></a>
</li>
<li><span class='sectionRange'>800 - </span><a href="#h-234"><span class="HTitleText4">Administrateurs — élection et fonctions</span></a>
</li>
<li><span class='sectionRange'>805 - </span><a href="#h-235"><span class="HTitleText4">Élections incomplètes et vacances d’administrateurs</span></a>
</li>
<li><span class='sectionRange'>816 - </span><a href="#h-236"><span class="HTitleText4">Réunions du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>825 - </span><a href="#h-237"><span class="HTitleText4">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>828 - </span><a href="#h-238"><span class="HTitleText4">Comités du conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>830 - </span><a href="#h-239"><span class="HTitleText4">Mandat des administrateurs et dirigeants</span></a>
</li>
<li><span class='sectionRange'>836 - </span><a href="#h-240"><span class="HTitleText4">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>841 - </span><a href="#h-241"><span class="HTitleText4">Responsabilité, exonération et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>849 - </span><a href="#h-242"><span class="HLabel3">SOUS-SECTION 4</span> - <span class="HTitleText3">Modifications de structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>849 - </span><a href="#h-243"><span class="HTitleText4">Modifications — lettres patentes</span></a>
</li>
<li><span class='sectionRange'>851 - </span><a href="#h-244"><span class="HTitleText4">Modifications — règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>857 - </span><a href="#h-245"><span class="HTitleText4">Fusion</span></a>
</li>
<li><span class='sectionRange'>867 - </span><a href="#h-246"><span class="HTitleText4">Ventes d’éléments d’actif</span></a>
</li></ul>
</li><li><span class='sectionRange'>868 - </span><a href="#h-247"><span class="HLabel3">SOUS-SECTION 5</span> - <span class="HTitleText3">Siège et livres</span></a>
</li>
<li><span class='sectionRange'>879 - </span><a href="#h-248"><span class="HLabel3">SOUS-SECTION 6</span> - <span class="HTitleText3">Registres des valeurs mobilières</span></a>
</li>
<li><span class='sectionRange'>880 - </span><a href="#h-249"><span class="HLabel3">SOUS-SECTION 7</span> - <span class="HTitleText3">Dénomination sociale et sceau</span></a>
</li>
<li><span class='sectionRange'>882 - </span><a href="#h-250"><span class="HLabel3">SOUS-SECTION 8</span> - <span class="HTitleText3">Initiés</span></a>
</li>
<li><span class='sectionRange'>883 - </span><a href="#h-251"><span class="HLabel3">SOUS-SECTION 9</span> - <span class="HTitleText3">Prospectus</span></a>
</li>
<li><span class='sectionRange'>884 - </span><a href="#h-252"><span class="HLabel3">SOUS-SECTION 10</span> - <span class="HTitleText3">Offres publiques d’achat</span></a>
</li>
<li><span class='sectionRange'>885 - </span><a href="#h-253"><span class="HLabel3">SOUS-SECTION 11</span> - <span class="HTitleText3">Acte de fiducie</span></a>
</li>
<li><span class='sectionRange'>886 - </span><a href="#h-254"><span class="HLabel3">SOUS-SECTION 12</span> - <span class="HTitleText3">Rapports financiers</span></a>
</li>
<li><span class='sectionRange'>892 - </span><a href="#h-255"><span class="HLabel3">SOUS-SECTION 13</span> - <span class="HTitleText3">Vérificateur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>892 - </span><a href="#h-256"><span class="HTitleText4">Définitions</span></a>
</li>
<li><span class='sectionRange'>893 - </span><a href="#h-257"><span class="HTitleText4">Nomination</span></a>
</li>
<li><span class='sectionRange'>894 - </span><a href="#h-258"><span class="HTitleText4">Conditions</span></a>
</li>
<li><span class='sectionRange'>896 - </span><a href="#h-259"><span class="HTitleText4">Vacances</span></a>
</li>
<li><span class='sectionRange'>902 - </span><a href="#h-260"><span class="HTitleText4">Examens et rapports</span></a>
</li>
<li><span class='sectionRange'>911 - </span><a href="#h-261"><span class="HTitleText4">Immunité</span></a>
</li></ul>
</li><li><span class='sectionRange'>912 - </span><a href="#h-262"><span class="HLabel3">SOUS-SECTION 14</span> - <span class="HTitleText3">Recours judiciaires</span></a>
</li>
<li><span class='sectionRange'>917 - </span><a href="#h-263"><span class="HLabel3">SOUS-SECTION 15</span> - <span class="HTitleText3">Liquidation et dissolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>917 - </span><a href="#h-264"><span class="HTitleText4">Définition</span></a>
</li>
<li><span class='sectionRange'>918 - </span><a href="#h-265"><span class="HTitleText4">Application</span></a>
</li>
<li><span class='sectionRange'>920 - </span><a href="#h-266"><span class="HTitleText4">Liquidation simple</span></a>
</li>
<li><span class='sectionRange'>925 - </span><a href="#h-267"><span class="HTitleText4">Surveillance judiciaire</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>926 - </span><a href="#h-268"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Propriété</span></a>
</li>
<li><span class='sectionRange'>963 - </span><a href="#h-269"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Activité commerciale et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>966 - </span><a href="#h-270"><span class="HLabel2">SECTION 9</span> - <span class="HTitleText2">Placements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>966 - </span><a href="#h-271"><span class="HTitleText3">Interprétation</span></a>
</li>
<li><span class='sectionRange'>967 - </span><a href="#h-272"><span class="HTitleText3">Placements</span></a>
</li>
<li><span class='sectionRange'>968 - </span><a href="#h-273"><span class="HTitleText3">Restrictions générales relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>971 - </span><a href="#h-274"><span class="HTitleText3">Filiales et placements</span></a>
</li>
<li><span class='sectionRange'>974 - </span><a href="#h-275"><span class="HTitleText3">Exceptions et exclusions</span></a>
</li>
<li><span class='sectionRange'>978 - </span><a href="#h-276"><span class="HTitleText3">Limites relatives aux placements</span></a>
</li>
<li><span class='sectionRange'>979 - </span><a href="#h-277"><span class="HTitleText3">Prêts commerciaux</span></a>
</li>
<li><span class='sectionRange'>981 - </span><a href="#h-278"><span class="HTitleText3">Placements immobiliers</span></a>
</li>
<li><span class='sectionRange'>982 - </span><a href="#h-279"><span class="HTitleText3">Capitaux propres</span></a>
</li>
<li><span class='sectionRange'>983 - </span><a href="#h-280"><span class="HTitleText3">Limite globale</span></a>
</li>
<li><span class='sectionRange'>984 - </span><a href="#h-281"><span class="HTitleText3">Divers</span></a>
</li></ul>
</li><li><span class='sectionRange'>992 - </span><a href="#h-282"><span class="HLabel2">SECTION 10</span> - <span class="HTitleText2">Capital et liquidités</span></a>
</li>
<li><span class='sectionRange'>993 - </span><a href="#h-283"><span class="HLabel2">SECTION 11</span> - <span class="HTitleText2">Réglementation des sociétés de portefeuille d’assurances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>993 - </span><a href="#h-284"><span class="HTitleText3">Surveillance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>993 - </span><a href="#h-285"><span class="HTitleText4">États</span></a>
</li>
<li><span class='sectionRange'>1000 - </span><a href="#h-286"><span class="HTitleText4">Enquête sur les sociétés de portefeuille d’assurances</span></a>
</li></ul>
</li><li><span class='sectionRange'>1002 - </span><a href="#h-287"><span class="HTitleText3">Réparation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1002 - </span><a href="#h-288"><span class="HTitleText4">Accords prudentiels</span></a>
</li>
<li><span class='sectionRange'>1003 - </span><a href="#h-289"><span class="HTitleText4">Décisions</span></a>
</li>
<li><span class='sectionRange'>1005 - </span><a href="#h-290"><span class="HTitleText4">Rejet des candidatures et destitution</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1008 - </span><a href="#h-291"><span class="HLabel1">PARTIE XVIII</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1008 - </span><a href="#h-292"><span class="HTitleText2">Avis et autres documents</span></a>
</li>
<li><span class='sectionRange'>1016 - </span><a href="#h-293"><span class="HTitleText2">Agréments : conditions et engagements</span></a>
</li>
<li><span class='sectionRange'>1017 - </span><a href="#h-294"><span class="HTitleText2">Arrêts, ordonnances et décisions</span></a>
</li>
<li><span class='sectionRange'>1019 - </span><a href="#h-295"><span class="HTitleText2">Demandes au surintendant</span></a>
</li>
<li><span class='sectionRange'>1020 - </span><a href="#h-296"><span class="HTitleText2">Appels</span></a>
</li>
<li><span class='sectionRange'>1021 - </span><a href="#h-297"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>1022 - </span><a href="#h-298"><span class="HTitleText2">Délégation</span></a>
</li></ul>
</li><li><span class='sectionRange'>1023 - </span><a href="#h-299"><span class="HLabel1">PARTIE XIX</span> - <span class="HTitleText1">Peines</span></a>
</li>
<li><a href="#h-300"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Branches d’assurance</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
