<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Mutual Legal Assistance in Criminal Matters Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-354373"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-354376"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-354411"><span class="HTitleText1">Schedule</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-354419"><span class="HTitleText1">Publication of Agreements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-354429"><span class="HTitleText1">Administrative Arrangements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-354445"><span class="HTitleText1">Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-354455"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Foreign Investigations or Other Proceedings in Respect of Offences</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="page-1.html#h-354456"><span class="HTitleText2">Implementation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-354464"><span class="HTitleText2">Fines</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="page-1.html#h-354474"><span class="HTitleText2">International Criminal Court</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="page-2.html#h-354511"><span class="HTitleText2">Foreign Orders for Restraint, Seizure and Forfeiture of Property in Canada</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-354570"><span class="HTitleText2">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-354653"><span class="HTitleText2">Production Orders</span></a>
</li>
<li><span class='sectionRange'>22.1 - </span><a href="page-4.html#h-354782"><span class="HTitleText2">Video Link</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-4.html#h-354819"><span class="HTitleText2">Arrest Warrant</span></a>
</li>
<li><span class='sectionRange'>23.1 - </span><a href="page-4.html#h-354834"><span class="HTitleText2">Examination of Place or Site</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-4.html#h-354844"><span class="HTitleText2">Transfer of Detained Persons</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-5.html#h-354888"><span class="HTitleText2">Lending Exhibits</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-5.html#h-354925"><span class="HTitleText2">Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="page-5.html#h-354930"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Admissibility in Canada of Evidence Obtained Abroad Pursuant to an Agreement</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-5.html#h-354951"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Implementation of Agreements in Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="page-5.html#h-354952"><span class="HTitleText2">Special Authorization to Come Into Canada</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-5.html#h-354972"><span class="HTitleText2">Detention in Canada</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-354982"><span class="HTitleText2">Determination of the Validity of Refusals</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-5.html#h-354987"><span class="HTitleText2">Privilege for Foreign Records</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="page-5.html#h-354995"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Consequential Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="page-5.html#h-354996"><span class="HTitleText2">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-354998"><span class="HTitleText2">Crown Liability Act</span></a>
</li>
<li><span class='sectionRange'>47 and 48 - </span><a href="page-5.html#h-355000"><span class="HTitleText2">Immigration Act</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-355002"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-6.html#h-355006"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Designated States or Entities</span></a>
</li></ul>
</li></ul>

</nav>

