<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Seized Property Management Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-445102"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-445105"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-445129"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-445143"><span class="HTitleText1">Management of Property</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-445168"><span class="HTitleText1">Management Order</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-445210"><span class="HTitleText1">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-445226"><span class="HTitleText1">Sharing of Proceeds</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-445248"><span class="HTitleText1">Financial</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-445294"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-445301"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-445315"><span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>21 to 30 - </span><a href="page-3.html#h-445321"><span class="HTitleText1">Consequential and Related Amendments</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-445323"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-3.html#h-445326"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

