<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le bien-être des vétérans</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-66593"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-66598"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-1.html#h-66657"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-66662"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Services de réorientation professionnelle</span></a>
</li>
<li><span class='sectionRange'>5.11 - </span><a href="page-2.html#h-66707"><span class="HLabel1">PARTIE 1.1</span> - <span class="HTitleText1">Allocation pour études et formation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-2.html#h-66799"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Services de réadaptation, assistance professionnelle et avantages financiers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="page-2.html#h-66800"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-66811"><span class="HTitleText2">Services de réadaptation et assistance professionnelle</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-3.html#h-66884"><span class="HTitleText2">Prestation de remplacement du revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="page-3.html#h-1110462"><span class="HTitleText3">Vétérans</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-4.html#h-1109516"><span class="HTitleText3">Survivants et orphelins</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-4.html#h-66968"><span class="HTitleText2">Allocation de soutien du revenu</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-5.html#h-67173"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="page-5.html#h-67185"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Blessure grave, douleur et souffrance, décès et captivité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-5.html#h-67186"><span class="HTitleText2">Généralités</span></a>
</li>
<li><span class='sectionRange'>44.1 - </span><a href="page-5.html#h-67198"><span class="HTitleText2">Indemnité pour blessure grave</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-5.html#h-67216"><span class="HTitleText2">Indemnité pour douleur et souffrance</span></a>
</li>
<li><span class='sectionRange'>56.6 - </span><a href="page-6.html#h-1109779"><span class="HTitleText2">Indemnité supplémentaire pour douleur et souffrance</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-7.html#h-67338"><span class="HTitleText2">Indemnité de décès</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-7.html#h-67356"><span class="HTitleText2">Allocation vestimentaire</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-7.html#h-67374"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="page-7.html#h-67379"><span class="HTitleText2">Indemnité de captivité</span></a>
</li></ul>
</li><li><span class='sectionRange'>65.1 - </span><a href="page-7.html#h-67398"><span class="HLabel1">PARTIE 3.1</span> - <span class="HTitleText1">Allocation de reconnaissance pour aidant</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="page-7.html#h-67459"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Généralités</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="page-7.html#h-67460"><span class="HTitleText2">Soins de santé</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="page-8.html#h-67470"><span class="HTitleText2">Désignation</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-8.html#h-67507"><span class="HTitleText2">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>75.1 - </span><a href="page-8.html#h-67517"><span class="HTitleText2">Transition à la vie civile</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-8.html#h-67526"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>78.1 - </span><a href="page-8.html#h-67547"><span class="HTitleText2">Dispense</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-8.html#h-67570"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="page-8.html#h-67581"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-9.html#h-67597"><span class="HTitleText2">Révision</span></a>
</li>
<li><span class='sectionRange'>87.1 - </span><a href="page-9.html#h-67610"><span class="HTitleText2">Versements</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-9.html#h-67622"><span class="HTitleText2">Trop-perçu</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-9.html#h-67640"><span class="HTitleText2">Divers</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-9.html#h-67664"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="page-9.html#h-67694"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="page-9.html#h-67695"><span class="HTitleText2">Limites</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-9.html#h-1109862"><span class="HTitleText2">Zones de service spécial et opérations de service spécial</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="page-9.html#h-1110258"><span class="HTitleText2">Dispositions transitoires relatives à l’allocation de remplacement du revenu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-9.html#h-1110306"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-10.html#h-67703"><span class="HTitleText3">Allocation pour perte de revenus</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="page-10.html#h-67704"><span class="HTitleText4">Militaires et vétérans</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="page-10.html#h-1109906"><span class="HTitleText4">Survivants et orphelins</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="page-11.html#h-67719"><span class="HTitleText3">Allocation pour incidence sur la carrière</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="page-11.html#h-67727"><span class="HTitleText3">Allocation de sécurité du revenu de retraite</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>115 - </span><a href="page-11.html#h-1110464"><span class="HTitleText4">Vétérans</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="page-12.html#h-1110076"><span class="HTitleText4">Survivants</span></a>
</li></ul>
</li><li><span class='sectionRange'>124 - </span><a href="page-12.html#h-1110141"><span class="HTitleText3">Prestation de retraite supplémentaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="page-13.html#h-1110389"><span class="HTitleText2">Dispositions transitoires relatives à l’indemnité pour douleur et souffrance</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="page-13.html#h-1110439"><span class="HTitleText2">Dispositions transitoires relatives à l’indemnité supplémentaire pour douleur et souffrance</span></a>
</li></ul>
</li><li><a href="page-14.html#h-67735"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-15.html#h-67745"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="page-16.html#h-1110325"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li>
<li><a href="page-17.html#h-1110467"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li></ul>
</li></ul>

</nav>

