<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la compensation et le règlement des paiements</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-402125"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-402128"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-402145"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Encadrement des systèmes de compensation et de règlement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-402146"><span class="HTitleText2">Systèmes visés</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-402160"><span class="HTitleText2">Renseignements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-402165"><span class="HTitleText2">Directives</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-402200"><span class="HTitleText2">Pouvoirs de la banque</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-402203"><span class="HTitleText2">Dispositions concernant le règlement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-402224"><span class="HTitleText2">Avis et approbation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-402239"><span class="HTitleText2">Vérification et inspection</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="page-2.html#h-1173966"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Résolution des systèmes de compensation et de règlement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="page-2.html#h-1173967"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>11.01 - </span><a href="page-2.html#h-1173973"><span class="HTitleText2">Autorité responsable de la résolution</span></a>
</li>
<li><span class='sectionRange'>11.04 - </span><a href="page-2.html#h-1173996"><span class="HTitleText2">Comité</span></a>
</li>
<li><span class='sectionRange'>11.05 - </span><a href="page-2.html#h-1174016"><span class="HTitleText2">Plan de résolution</span></a>
</li>
<li><span class='sectionRange'>11.06 - </span><a href="page-2.html#h-1174024"><span class="HTitleText2">Début de la résolution</span></a>
</li>
<li><span class='sectionRange'>11.09 - </span><a href="page-2.html#h-1174087"><span class="HTitleText2">Dévolution et mise sous séquestre</span></a>
</li>
<li><span class='sectionRange'>11.12 - </span><a href="page-3.html#h-1174192"><span class="HTitleText2">Chambres de compensation-relais</span></a>
</li>
<li><span class='sectionRange'>11.15 - </span><a href="page-3.html#h-1174220"><span class="HTitleText2">Non-application de certaines dispositions législatives</span></a>
</li>
<li><span class='sectionRange'>11.18 - </span><a href="page-3.html#h-1174243"><span class="HTitleText2">Financement</span></a>
</li>
<li><span class='sectionRange'>11.2 - </span><a href="page-3.html#h-1174257"><span class="HTitleText2">Fin de la résolution</span></a>
</li>
<li><span class='sectionRange'>11.25 - </span><a href="page-4.html#h-1174312"><span class="HTitleText2">Indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="page-4.html#h-402246"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-4.html#h-402247"><span class="HTitleText2">Pouvoirs de la banque</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-4.html#h-402262"><span class="HTitleText2">Accords de compensation</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="page-4.html#h-402291"><span class="HTitleText2">Chambre spécialisée</span></a>
</li>
<li><span class='sectionRange'>13.2 - </span><a href="page-5.html#h-402312"><span class="HTitleText2">Accords</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-5.html#h-402328"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-5.html#h-402343"><span class="HTitleText2">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-5.html#h-402358"><span class="HTitleText2">Lignes directrices</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-5.html#h-402361"><span class="HTitleText2">Confidentialité des renseignements</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-5.html#h-402377"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les textes réglementaires</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-5.html#h-402380"><span class="HTitleText2">Absence de responsabilité</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-5.html#h-402385"><span class="HTitleText2">Contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-5.html#h-402390"><span class="HTitleText2">Établissements participants</span></a>
</li></ul>
</li><li><span class='sectionRange'>24 - </span><a href="page-5.html#h-402415"><span class="HTitleText1">Règlements</span></a>
</li></ul>
</li></ul>

</nav>

