<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Saskatchewan Treaty Land Entitlement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-444120"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-444123"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-444140"><span class="HTitleText1">General</span></a>
</li>
<li><a href="page-2.html#h-444204"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - An Agreement To Vary the Natural Resources Transfer Agreement</span></a>
</li>
<li><a href="page-3.html#h-444260"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Provisions of the Framework Agreement</span></a>
</li>
<li><a href="page-4.html#h-444327"><span class="scheduleLabel">SCHEDULE III</span> <span class="scheduleTitleText"> - Provisions of the Nekaneet Agreement</span></a>
</li></ul>
</li></ul>

</nav>

