<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Specific Claims Tribunal Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-436589"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-436592"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-436608"><span class="HTitleText1">Purpose and Application of Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-436615"><span class="HTitleText1">Specific Claims Tribunal</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-436616"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-436651"><span class="HTitleText2">Functions, Powers and Duties</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-436692"><span class="HTitleText2">Specific Claims</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-436744"><span class="HTitleText2">Hearings and Decisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>39 - </span><a href="#h-436857"><span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="#h-436858"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-436861"><span class="HTitleText2">Annual Report</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-436869"><span class="HTitleText2">Review and Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-436877"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-436894"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="#h-436895"><span class="HTitleText2">Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-436898"><span class="HTitleText2">Federal Courts Act</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-436900"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-436904"><span class="HTitleText2">Privacy Act</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-436906"><span class="HTitleText2">Public Service Superannuation Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 - </span><a href="#h-436908"><span class="HTitleText1">Repeal</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-436910"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-22"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
