<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi canadienne sur l’évaluation environnementale (2012) <span class='Repealed'>[Abrogée, 2019, ch. 28, art. 9]</span></a></li></ul>
</nav>
</div></section>
