<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Environmental Assessment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Purposes</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Environmental Assessment of Projects</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Projects to be Assessed</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText2">Excluded Projects</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText2">Responsible Authority</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2">Action of Federal Authorities Suspended</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText1">Environmental Assessment Process</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText2">Screening</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Comprehensive Study</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Discretionary Powers</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText2">Mediation and Panel Reviews</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-16"><span class="HTitleText2">Decision of Responsible Authority</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-17"><span class="HTitleText2">Follow-up Program</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-18"><span class="HTitleText2">Certificate</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-19"><span class="HTitleText2">Joint Review Panels</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-20"><span class="HTitleText2">Public Hearing by a Federal Authority</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-21"><span class="HTitleText1">Transboundary and Related Environmental Effects</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-22"><span class="HTitleText1">Agreements and Arrangements</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-23"><span class="HTitleText1">Access to Information</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-24"><span class="HTitleText1">Statistical Summary</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-25"><span class="HTitleText1">Judicial Review</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-26"><span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>58 - </span><a href="#h-27"><span class="HTitleText2">Minister’s Powers</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-28"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="#h-29"><span class="HTitleText1">Canadian Environmental Assessment Agency</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-30"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-31"><span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-32"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>75 to 81 - </span><a href="#h-33"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-34"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
