<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Personal Information Protection and Electronic Documents Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Protection of Personal Information in the Private Sector</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Protection of Personal Information</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Remedies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText3">Filing of Complaints</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText3">Investigations of Complaints</span></a>
</li>
<li><span class='sectionRange'>12.2 - </span><a href="#h-10"><span class="HTitleText3">Discontinuance of Investigation</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-11"><span class="HTitleText3">Commissioner’s Report</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText3">Hearing by Court</span></a>
</li>
<li><span class='sectionRange'>17.1 - </span><a href="#h-13"><span class="HTitleText3">Compliance Agreements</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-14"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">Audits</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-16"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Electronic Documents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-18"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-19"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-20"><span class="HTitleText2">Electronic Alternatives</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-21"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 to 57 - </span><a href="#h-22"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments to the Canada Evidence Act</span></a>
</li>
<li><span class='sectionRange'>58 and 59 - </span><a href="#h-23"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Amendments to the Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>60 to 71 - </span><a href="#h-24"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Amendments to the Statute Revision Act</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-25"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-417659"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Principles Set Out in the National Standard of Canada Entitled Model Code for the Protection of Personal Information, CAN/CSA-Q830-96</span></a>
</li>
<li><a href="#h-417792"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="#h-417802"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="#h-417812"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
