<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
CN Commercialization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-40662"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-40665"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-40682"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-40685"><span class="HTitleText1">Preliminary Transactions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-40693"><span class="HTitleText1">Continuance</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-40749"><span class="HTitleText1">Share Transactions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-40757"><span class="HTitleText1">Financial Arrangements</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-40765"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-40775"><span class="HTitleText1">Transitional, Consequential, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-40776"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-40784"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-40786"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-40792"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-40796"><span class="scheduleLabel">SCHEDULES I AND II</span></a>
</li></ul>
</li></ul>

</nav>

