<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le ministère de la Sécurité publique et de la Protection civile</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-391996"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-391999"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-392007"><span class="HTitleText1">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-392032"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-392047"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-392048"><span class="HTitleText2">Loi sur l’accès à l’information</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-392051"><span class="HTitleText2">Loi sur le Centre canadien de lutte contre les toxicomanies</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-392053"><span class="HTitleText2">Loi sur la médaille canadienne du maintien de la paix</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-392055"><span class="HTitleText2">Loi sur le Service canadien du renseignement de sécurité</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-392057"><span class="HTitleText2">Loi sur la citoyenneté</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-392059"><span class="HTitleText2">Loi réglementant certaines drogues et autres substances</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-392062"><span class="HTitleText2">Loi sur le système correctionnel et la mise en liberté sous condition</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-392064"><span class="HTitleText2">Code criminel</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-392073"><span class="HTitleText2">Loi sur l’identification par les empreintes génétiques</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-392075"><span class="HTitleText2">Loi sur la gestion des finances publiques</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-392078"><span class="HTitleText2">Loi sur les armes à feu</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-392080"><span class="HTitleText2">Loi sur la protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-392083"><span class="HTitleText2">Loi sur la rémunération du secteur public</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-392086"><span class="HTitleText2">Nouvelle terminologie</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-392088"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-392091"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-392093"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

