<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Wheat Board (Interim Operations) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">The Canadian Wheat Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Continuation of the Corporation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Status, Object and Powers</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText2">President</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText2">Directors and Officers</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText2">Contingency fund</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-11"><span class="HTitleText2">Pricing, Profits and Losses</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-12"><span class="HTitleText2">Investment of Moneys</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Accounts and Reports</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText2">Pension Fund and Group Insurance</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText2">Directions by Governor in Council</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Plans, Borrowings and Guarantees</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Interprovincial and Export Marketing of Grain by the Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>27 - </span><a href="#h-18"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText2">Purchase of Grain and Initial Payment</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-20"><span class="HTitleText2">Payment of Balance and Interim Payments</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-21"><span class="HTitleText2">Quality Characteristics Within Grades</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-22"><span class="HTitleText2">Separate Accounts</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-23"><span class="HTitleText2">Regulations and Authorizations Respecting Certificates and Accounts</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-24"><span class="HTitleText2">Other Purchases of Grain</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-25"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-26"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-27"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-28"><span class="HTitleText2">Implementation of the North American Free Trade Agreement</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-29"><span class="HTitleText2">Borrowing by Agents or Mandataries</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-30"><span class="HTitleText2">Declaration</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-31"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
