<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’Agence du revenu du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-48511"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-48516"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-48529"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-48532"><span class="HTitleText1">Prorogation et mission de l’agence</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-48553"><span class="HTitleText1">Ministre</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-48597"><span class="HTitleText1">Structure organisationnelle de l’agence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-48598"><span class="HTitleText2">Conseil de direction</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-48635"><span class="HTitleText2">Président du conseil</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-48642"><span class="HTitleText2">Commissaire et commissaire délégué</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="page-2.html#h-48671"><span class="HTitleText1">Compétence générale de l’agence</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-48684"><span class="HTitleText1">Direction et gestion de l’agence</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="page-2.html#h-48685"><span class="HTitleText2">Attributions du conseil</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-2.html#h-48710"><span class="HTitleText2">Attributions du commissaire</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-2.html#h-48746"><span class="HTitleText2">Obligations des administrateurs et indemnisation</span></a>
</li></ul>
</li><li><span class='sectionRange'>47 - </span><a href="page-2.html#h-48791"><span class="HTitleText1">Plan d’entreprise</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-3.html#h-48815"><span class="HTitleText1">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="page-3.html#h-48875"><span class="HTitleText1">Utilisation des crédits et recettes</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-3.html#h-48892"><span class="HTitleText1">Contrats, ententes, accords et actions en justice</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-4.html#h-48932"><span class="HTitleText1">Propriété intellectuelle</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="page-4.html#h-48937"><span class="HTitleText1">Immeubles et biens réels</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-4.html#h-49035"><span class="HTitleText1">Rapports au Parlement</span></a>
</li>
<li><span class='sectionRange'>89.1 - </span><a href="page-4.html#h-49059"><span class="HTitleText1">Application de la Loi sur les langues officielles</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-5.html#h-49062"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>106 à 185.1 - </span><a href="page-5.html#h-49147"><span class="HTitleText1">Modifications corrélatives et conditionnelles</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="page-5.html#h-49150"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="page-5.html#h-49152"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

