<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Weights and Measures Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-468058"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-468063"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-468084"><span class="HTitleText1">Approval of Devices by the Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-468092"><span class="HTitleText1">Units of Measurement</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-468122"><span class="HTitleText1">Use of Units of Measurement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-468129"><span class="HTitleText1">Use of Devices</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-468136"><span class="HTitleText1">Marking of Commodities</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-468147"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-468181"><span class="HTitleText1">Reference and Local Standards</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-468209"><span class="HTitleText1">Examination of Devices</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-468225"><span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16.1 - </span><a href="#h-468226"><span class="HTitleText2">Designation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-468238"><span class="HTitleText2">Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-468298"><span class="HTitleText1">Examination Fees and Charges</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-468315"><span class="HTitleText1">Administrative Monetary Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>22 - </span><a href="#h-468316"><span class="HTitleText2">Powers of the Governor in Council</span></a>
</li>
<li><span class='sectionRange'>22.1 - </span><a href="#h-468327"><span class="HTitleText2">Violations</span></a>
</li>
<li><span class='sectionRange'>22.11 - </span><a href="#h-468337"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>22.12 - </span><a href="#h-468354"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>22.13 - </span><a href="#h-468369"><span class="HTitleText2">Compliance Agreements</span></a>
</li>
<li><span class='sectionRange'>22.15 - </span><a href="#h-468403"><span class="HTitleText2">Review by the Minister</span></a>
</li>
<li><span class='sectionRange'>22.16 - </span><a href="#h-468419"><span class="HTitleText2">Recovery of Debts</span></a>
</li>
<li><span class='sectionRange'>22.18 - </span><a href="#h-468441"><span class="HTitleText2">Rules of Law About Violations</span></a>
</li>
<li><span class='sectionRange'>22.24 - </span><a href="#h-468469"><span class="HTitleText2">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>23 - </span><a href="#h-468492"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-468622"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-468645"><span class="HTitleText1">Seizure and Detention</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-468677"><span class="HTitleText1">Forfeiture and Return</span></a>
</li>
<li><a href="#h-468688"><span class="scheduleLabel">SCHEDULE I</span> <span class="scheduleTitleText"> - Units Based on the International System of Units</span></a>
</li>
<li><a href="#h-468721"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - Canadian Units of Measurement</span></a>
</li>
<li><a href="#h-468761"><span class="scheduleLabel">SCHEDULE III</span> </a>
</li>
<li><a href="#h-468771"><span class="scheduleLabel">SCHEDULE IV</span> <span class="scheduleTitleText"> - Reference Standards</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
