<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Royal Canadian Mounted Police Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-420830"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-420835"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-420861"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Constitution and Organization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="page-1.html#h-420862"><span class="HTitleText2">Composition of Force</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-420871"><span class="HTitleText2">Commissioner</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-420879"><span class="HTitleText2">Officers and Members</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="page-1.html#h-420929"><span class="HTitleText2">Qualifications</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="page-1.html#h-420937"><span class="HTitleText2">Revocation</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="page-1.html#h-420942"><span class="HTitleText2">Probation</span></a>
</li>
<li><span class='sectionRange'>9.5 - </span><a href="page-1.html#h-420957"><span class="HTitleText2">Resignation</span></a>
</li>
<li><span class='sectionRange'>9.6 - </span><a href="page-1.html#h-420962"><span class="HTitleText2">Supernumerary Special Constables</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-420972"><span class="HTitleText2">Civilian Staff</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-420977"><span class="HTitleText2">Reserve</span></a>
</li>
<li><span class='sectionRange'>11.1 - </span><a href="page-2.html#h-420987"><span class="HTitleText2">Peace Officers</span></a>
</li>
<li><span class='sectionRange'>11.2 - </span><a href="page-2.html#h-420997"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-421007"><span class="HTitleText2">Suspension</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-421013"><span class="HTitleText2">Headquarters</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-421018"><span class="HTitleText2">Oaths</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-421026"><span class="HTitleText2">Absence of Commissioner</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-421036"><span class="HTitleText2">Duties</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="page-2.html#h-421059"><span class="HTitleText2">Human Resource Management</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-421089"><span class="HTitleText2">Regulations and Rules</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-421117"><span class="HTitleText2">Pay and Allowances</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-421135"><span class="HTitleText2">Benefit Trust Fund</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-421154"><span class="HTitleText2">Disposition of Property</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="page-3.html#h-421162"><span class="HTitleText2">Boards of Inquiry</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="page-3.html#h-421200"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Royal Canadian Mounted Police External Review Committee</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="page-3.html#h-421201"><span class="HTitleText2">Establishment and Organization of Committee</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-3.html#h-421243"><span class="HTitleText2">Duties</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-421255"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-3.html#h-421264"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>30.1 - </span><a href="page-3.html#h-421272"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Grievances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30.1 - </span><a href="page-3.html#h-421273"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>30.2 - </span><a href="page-3.html#h-421278"><span class="HTitleText2">Conflict Management</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-421283"><span class="HTitleText2">Presentation of Grievances</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-4.html#h-421330"><span class="HTitleText2">Reference to Committee</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-421394"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="page-4.html#h-421401"><span class="HTitleText2">Recommendation for Deputy Commissioner’s Discharge</span></a>
</li></ul>
</li><li><span class='sectionRange'>36.2 - </span><a href="page-4.html#h-421406"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Conduct</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36.2 - </span><a href="page-4.html#h-421407"><span class="HTitleText2">Purposes of Part</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-4.html#h-421417"><span class="HTitleText2">Responsibilities</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-4.html#h-421430"><span class="HTitleText2">Code of Conduct</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="page-4.html#h-421444"><span class="HTitleText2">Investigation</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-5.html#h-421566"><span class="HTitleText2">Conduct Boards</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="page-6.html#h-421611"><span class="HTitleText2">Hearing</span></a>
</li>
<li><span class='sectionRange'>45.11 - </span><a href="page-6.html#h-421639"><span class="HTitleText2">Appeal</span></a>
</li>
<li><span class='sectionRange'>45.171 - </span><a href="page-6.html#h-421711"><span class="HTitleText2">Notice</span></a>
</li></ul>
</li><li><span class='sectionRange'>45.18 - </span><a href="page-6.html#h-421724"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Management Advisory Board</span></a>
</li>
<li><span class='sectionRange'>45.29 - </span><a href="page-7.html#h-421736"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Civilian Review and Complaints Commission For the Royal Canadian Mounted Police</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45.29 - </span><a href="page-7.html#h-421737"><span class="HTitleText2">Establishment and Organization</span></a>
</li>
<li><span class='sectionRange'>45.33 - </span><a href="page-7.html#h-421788"><span class="HTitleText2">Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>45.39 - </span><a href="page-8.html#h-421834"><span class="HTitleText2">Information Provisions</span></a>
</li>
<li><span class='sectionRange'>45.49 - </span><a href="page-9.html#h-421981"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>45.5 - </span><a href="page-9.html#h-421996"><span class="HTitleText2">Immunity</span></a>
</li>
<li><span class='sectionRange'>45.51 - </span><a href="page-9.html#h-422004"><span class="HTitleText2">Reporting</span></a>
</li></ul>
</li><li><span class='sectionRange'>45.53 - </span><a href="page-9.html#h-422021"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Investigation, Review and Hearing of Complaints</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45.53 - </span><a href="page-9.html#h-422022"><span class="HTitleText2">Complaints</span></a>
</li>
<li><span class='sectionRange'>45.55 - </span><a href="page-9.html#h-422065"><span class="HTitleText2">Withdrawal of Complaints</span></a>
</li>
<li><span class='sectionRange'>45.56 - </span><a href="page-9.html#h-422083"><span class="HTitleText2">Informal Resolution</span></a>
</li>
<li><span class='sectionRange'>45.57 - </span><a href="page-10.html#h-422099"><span class="HTitleText2">Representations</span></a>
</li>
<li><span class='sectionRange'>45.59 - </span><a href="page-10.html#h-422119"><span class="HTitleText2">Chairperson-initiated Complaints</span></a>
</li>
<li><span class='sectionRange'>45.6 - </span><a href="page-10.html#h-422131"><span class="HTitleText2">Investigation of Complaints by the Force</span></a>
</li>
<li><span class='sectionRange'>45.65 - </span><a href="page-10.html#h-422168"><span class="HTitleText2">Powers of the Commission in Relation to Complaints</span></a>
</li>
<li><span class='sectionRange'>45.66 - </span><a href="page-10.html#h-422193"><span class="HTitleText2">Investigation by the Commission</span></a>
</li>
<li><span class='sectionRange'>45.7 - </span><a href="page-10.html#h-422222"><span class="HTitleText2">Referral of Complaints to Commission</span></a>
</li>
<li><span class='sectionRange'>45.73 - </span><a href="page-11.html#h-422253"><span class="HTitleText2">Hearings</span></a>
</li>
<li><span class='sectionRange'>45.74 - </span><a href="page-11.html#h-422284"><span class="HTitleText2">Suspension and Joint Proceedings</span></a>
</li>
<li><span class='sectionRange'>45.76 - </span><a href="page-11.html#h-422301"><span class="HTitleText2">Reports Following Investigation or Hearing</span></a>
</li></ul>
</li><li><span class='sectionRange'>45.79 - </span><a href="page-11.html#h-422319"><span class="HLabel1">PART VII.1</span> - <span class="HTitleText1">Serious Incidents</span></a>
</li>
<li><span class='sectionRange'>45.88 - </span><a href="page-12.html#h-422410"><span class="HLabel1">PART VII.2</span> - <span class="HTitleText1">Review of Integrated Cross-Border Law Enforcement Operations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45.88 - </span><a href="page-12.html#h-422411"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>45.89 - </span><a href="page-12.html#h-422433"><span class="HTitleText2">Purpose</span></a>
</li>
<li><span class='sectionRange'>45.9 - </span><a href="page-12.html#h-422440"><span class="HTitleText2">Application of Sections 45.34 to 45.51</span></a>
</li>
<li><span class='sectionRange'>45.91 - </span><a href="page-12.html#h-422458"><span class="HTitleText2">Reporting</span></a>
</li>
<li><span class='sectionRange'>45.94 - </span><a href="page-12.html#h-422481"><span class="HTitleText2">Investigation, Review and Hearing of Complaints</span></a>
</li>
<li><span class='sectionRange'>45.98 - </span><a href="page-13.html#h-422515"><span class="HTitleText2">Serious Incidents</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="page-13.html#h-422536"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="page-13.html#h-422537"><span class="HTitleText2">Miscellaneous Provisions having General Application</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-13.html#h-422598"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><a href="page-15.html#h-422682"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

