<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Parks Canada Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Establishment of Agency</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-4"><span class="HTitleText1">Organization of Agency</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">Human Resources</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-8"><span class="HTitleText1">Fees</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-9"><span class="HTitleText1">Reports and Plans</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-10"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-11"><span class="HTitleText1">Application of the Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-12"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>46 to 61.01 - </span><a href="#h-13"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>61.1 - </span><a href="#h-14"><span class="HTitleText1">Conditional Amendment</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-15"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-16"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
