<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Veterans Insurance Act</a><ul class="TocIndent"><li><a href="#h-462697"><span class="scheduleLabel">SCHEDULE A — <span class="otherLang" lang="fr">ANNEXE A</span></span> - <span class="scheduleTitleText"> - Monthly Premiums for $1,000 Insurance Payable at Death</span> - <span class="scheduleTitleText"> - <span class="otherLang" lang="fr">Primes mensuelles par $1,000 d’assurance payable au décès</span></span></a>
</li>
<li><a href="#h-462708"><span class="scheduleLabel">SCHEDULE B</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
