<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur les prises</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-48423"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-48428"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-48433"><span class="HTitleText1">Cour des prises</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-48443"><span class="HTitleText1">Loi canadienne sur les prises</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-48458"><span class="HTitleText1">Procédure et décrets ou règlements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-48468"><span class="HTitleText1">Arrangements réciproques avec d’autres gouvernements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-48493"><span class="HTitleText1">Maintien de la procédure</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
