<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les accords de Bretton Woods et des accords connexes</a><ul class="TocIndent"><li><a href="#h-1"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-31128"><span class="scheduleLabel">ANNEXE II</span> </a>
</li>
<li><a href="#h-31488"><span class="scheduleLabel">ANNEXE III</span> <span class="scheduleTitleText"> - (<em>Traduction</em>)</span></a>
</li>
<li><a href="#h-31764"><span class="scheduleLabel">ANNEXE IV</span> </a>
</li>
<li><a href="#h-32004"><span class="scheduleLabel">ANNEXE V</span> <span class="scheduleTitleText"> - Convention portant création de l’Agence multilatérale de garantie des investissements</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
