<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Financial Institutions and Deposit Insurance System Amendment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-222909"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 to 46 - </span><a href="#h-222912"><span class="HLabel1">PART I</span></a>
</li>
<li><span class='sectionRange'>47 to 73 - </span><a href="#h-222914"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Canada Deposit Insurance Corporation Act</span></a>
</li>
<li><span class='sectionRange'>74 to 84 - </span><a href="#h-222916"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Bank Act</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-222918"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>86 to 101 - </span><a href="#h-222920"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>102 to 123 - </span><a href="#h-222922"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Canadian and British Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>124 to 136 - </span><a href="#h-222924"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Foreign Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>137 to 142 - </span><a href="#h-222926"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Investment Companies Act</span></a>
</li>
<li><span class='sectionRange'>143 to 158 - </span><a href="#h-222928"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>159 to 173 - </span><a href="#h-222930"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Trust Companies Act</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-222932"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

