<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Citizenship and Immigration Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-80783"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-80786"><span class="HTitleText1">Establishment</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-80794"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-80819"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>9 to 22 - </span><a href="#h-80832"><span class="HTitleText1">Consequential Amendments</span></a>
</li></ul>
</li></ul>

</nav>

