<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Excise Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-178738"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-178741"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-178973"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Application and Administrative Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-178974"><span class="HTitleText2">Application to Her Majesty</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-178977"><span class="HTitleText2">Administration and Officers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-179002"><span class="HTitleText2">Inquiries</span></a>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-179016"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Licences and Registrations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-179017"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-179040"><span class="HTitleText2">Registrations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-179058"><span class="HTitleText2">Excise Warehouses</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-179069"><span class="HTitleText2">Special Excise Warehouses</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-179088"><span class="HTitleText2">Duty Free Shops</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-179091"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-179117"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Tobacco</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-179118"><span class="HTitleText2">Regulation of Tobacco</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-179353"><span class="HTitleText2">Duty on Tobacco</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-179415"><span class="HTitleText2">Excise Warehouses</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-179475"><span class="HTitleText2">Special Duties on Tobacco Products</span></a>
</li></ul>
</li><li><span class='sectionRange'>58.1 - </span><a href="#h-179525"><span class="HLabel1">PART 3.1</span> - <span class="HTitleText1">Cigarette Inventory Tax</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-179599"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Alcohol</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>59 - </span><a href="#h-179600"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-179669"><span class="HTitleText2">Bulk Alcohol</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-179724"><span class="HTitleText2">Special Containers of Spirits</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-179740"><span class="HTitleText2">Special Containers of Wine</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-179756"><span class="HTitleText2">Packaged Alcohol</span></a>
</li>
<li><span class='sectionRange'>93.1 - </span><a href="#h-179835"><span class="HTitleText2">Restricted Formulations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-179844"><span class="HTitleText2">Denatured Alcohol and Specially Denatured Alcohol</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-179900"><span class="HTitleText2">Responsibility for Bulk Spirits</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-179940"><span class="HTitleText2">Responsibility for Bulk Wine</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-179983"><span class="HTitleText2">Imposition and Payment of Duty on Alcohol</span></a>
</li>
<li><span class='sectionRange'>140 - </span><a href="#h-180173"><span class="HTitleText2">Liability of Excise Warehouse Licensees and Licensed Users</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-180191"><span class="HTitleText2">Non-dutiable Uses and Removals of Alcohol</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-180240"><span class="HTitleText2">Determining Volume of Alcohol</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-180252"><span class="HTitleText2">Excise Warehouses</span></a>
</li></ul>
</li><li><span class='sectionRange'>158.01 - </span><a href="#h-180318"><span class="HLabel1">PART 4.1</span> - <span class="HTitleText1">Cannabis</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>158.01 - </span><a href="#h-180319"><span class="HTitleText2">Exclusions</span></a>
</li>
<li><span class='sectionRange'>158.02 - </span><a href="#h-180327"><span class="HTitleText2">Cannabis Production and Stamping</span></a>
</li>
<li><span class='sectionRange'>158.17 - </span><a href="#h-180495"><span class="HTitleText2">Responsibility for Cannabis</span></a>
</li>
<li><span class='sectionRange'>158.19 - </span><a href="#h-180518"><span class="HTitleText2">Imposition and Payment of Duty on Cannabis</span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-180659"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">General Provisions Concerning Duty and Other Amounts Payable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 - </span><a href="#h-180660"><span class="HTitleText2">Fiscal Periods</span></a>
</li>
<li><span class='sectionRange'>159.1 - </span><a href="#h-180677"><span class="HTitleText2">Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-180723"><span class="HTitleText2">Returns and Payment of Duty and Other Amounts</span></a>
</li>
<li><span class='sectionRange'>170 - </span><a href="#h-180791"><span class="HTitleText2">Interest</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-180814"><span class="HTitleText2">Refunds</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-180926"><span class="HTitleText2">Assessments</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-181095"><span class="HTitleText2">Objections to Assessment</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-181146"><span class="HTitleText2">Appeal</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-181257"><span class="HTitleText2">Records and Information</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-181508"><span class="HTitleText2">Bankruptcies and Corporate Reorganizations</span></a>
</li></ul>
</li><li><span class='sectionRange'>214 - </span><a href="#h-181562"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>214 - </span><a href="#h-181563"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-181746"><span class="HTitleText2">Proceeds of Crime</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-181780"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-181948"><span class="HTitleText2">Penalty Imposition</span></a>
</li>
<li><span class='sectionRange'>258 - </span><a href="#h-181966"><span class="HTitleText2">Search Warrants</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-181998"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>264 - </span><a href="#h-182042"><span class="HTitleText2">Return or Disposal of Things Seized</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="#h-182069"><span class="HTitleText2">Forfeitures</span></a>
</li>
<li><span class='sectionRange'>270 - </span><a href="#h-182076"><span class="HTitleText2">Review of Imposed Penalty or Seizure</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="#h-182162"><span class="HTitleText2">Third Party Claims</span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="#h-182224"><span class="HTitleText2">Collection</span></a>
</li>
<li><span class='sectionRange'>298 - </span><a href="#h-182514"><span class="HTitleText2">Evidence and Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>304 - </span><a href="#h-182584"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>305 - </span><a href="#h-182661"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Transitional Provisions and Consequential, Related and Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>305 - </span><a href="#h-182662"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>321 to 325 - </span><a href="#h-182808"><span class="HTitleText2">Consequential and Related Amendments</span></a>
</li>
<li><span class='sectionRange'>408 to 411 - </span><a href="#h-182814"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>412 to 421 - </span><a href="#h-182816"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Amendments Related to Excise Tax on Tobacco Products</span></a>
</li>
<li><span class='sectionRange'>422 to 432 - </span><a href="#h-182818"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Amendments Related to Ships’ Stores</span></a>
</li>
<li><span class='sectionRange'>433 - </span><a href="#h-182820"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-182824"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Rates of Duty on Tobacco Products</span></a>
</li>
<li><a href="#h-182841"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Additional Duty on Cigars</span></a>
</li>
<li><a href="#h-182850"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Rates of Special Duties on Certain Manufactured Tobacco</span></a>
</li>
<li><a href="#h-182882"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - Rates of Duty on Spirits</span></a>
</li>
<li><a href="#h-182892"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - Rate of Special Duty on Spirits</span></a>
</li>
<li><a href="#h-182896"><span class="scheduleLabel">SCHEDULE 6</span> <span class="scheduleTitleText"> - Rates of Duty on Wine</span></a>
</li>
<li><a href="#h-182910"><span class="scheduleLabel">SCHEDULE 7</span> <span class="scheduleTitleText"> - Duty on Cannabis Products</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
