<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi du traité des eaux limitrophes internationales</a><ul class="TocIndent"><li><span class='sectionRange'>10 - </span><a href="#h-1"><span class="HTitleText1">Licences et prohibitions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-2"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-4"><span class="HTitleText2">Prohibition</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-6"><span class="HTitleText2">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-8"><span class="HTitleText2">Droits ancestraux et issus de traités</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-10"><span class="HTitleText2">Injonction</span></a>
</li></ul>
</li><li><a href="#h-11"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
