<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
An Act to assist families by supporting their child care choices through direct financial support and to make consequential and related amendments to certain Acts</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-462243"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-462246"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-462255"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-462262"><span class="HTitleText1">Benefit</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
