<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
International Development (Financial Institutions) Assistance Act</a><ul class="TocIndent"><li><a href="#h-272090"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - International Financial Institutions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
