<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le règlement des revendications territoriales des premières nations du Yukon</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-462830"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-462833"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-462841"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-462844"><span class="HTitleText1">Accords visés par la présente loi</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-462852"><span class="HTitleText1">Portée des accords</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-462862"><span class="HTitleText1">Organismes</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-462886"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-462902"><span class="HTitleText1">Affectation de fonds</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-462905"><span class="HTitleText1">Publicité</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-462914"><span class="HTitleText1">Consultation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-462917"><span class="HTitleText1">Pouvoirs du gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>18 et 19 - </span><a href="#h-462920"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-462926"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-462934"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
