<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les Nations Unies</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-451260"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-451265"><span class="HTitleText1">Décrets et règlements du gouverneur en conseil</span></a>
</li>
<li><a href="#h-451287"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
