<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Foundation for Sustainable Development Technology Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-136007"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-136010"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-136031"><span class="HTitleText1">Continuation of the Corporation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-136093"><span class="HTitleText1">Directors</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-136158"><span class="HTitleText1">Members</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-136222"><span class="HTitleText1">Staff</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-136234"><span class="HTitleText1">Operations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-136283"><span class="HTitleText1">Financial Matters and Audit</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-136325"><span class="HTitleText1">Annual Meeting</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-136334"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-136352"><span class="HTitleText1">Winding-up</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-136360"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-136370"><span class="HTitleText1">Designation and Amendments Consequential on It</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-136379"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
