<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Latin American Heritage Month Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-344563"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-344566"><span class="HTitleText1">Latin American Heritage Month</span></a>
</li></ul>
</li></ul>

</nav>

