<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Statistics Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-440828"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-440833"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-440843"><span class="HTitleText1">Statistics Canada</span></a>
</li>
<li><span class='sectionRange'>8.1 - </span><a href="#h-440930"><span class="HTitleText1">Canadian Statistics Advisory Council</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-440948"><span class="HTitleText1">Statistics</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-441013"><span class="HTitleText1">Secrecy</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-441062"><span class="HTitleText1">Population Census and Agriculture Census</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-441085"><span class="HTitleText1">General Statistics</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-441136"><span class="HTitleText1">Criminal Statistics</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-441153"><span class="HTitleText1">Offences and Punishment</span></a>
</li></ul>
</li></ul>

</nav>

