<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Loi sur l’inspection du poisson <span class='Repealed'>[Abrogée, 2012, ch. 24, art. 76]</span></a></li></ul>
</nav>
</div></section>
