<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada-Brazil Income Tax Convention Act, 1984</a><ul class="TocIndent"><li><span class='sectionRange'>19 - </span><a href="#h-43240"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Canada-Brazil Income Tax Convention</span></a>
</li>
<li><a href="#h-43254"><span class="scheduleLabel">SCHEDULE V</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Federative Republic of Brazil for the Avoidance of Double Taxation with Respect to Taxes on Income</span></a>
</li>
<li><a href="#h-43477"><span class="scheduleLabel">SCHEDULE VI</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
