<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Special Import Measures Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Special Import Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">LIABILITY FOR ANTI-DUMPING, COUNTERVAILING AND PROVISIONAL DUTIES</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText3">Anti-dumping and Countervailing Duty</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText3">Provisional Duty</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText3">Payment of Duty During Court Proceedings and Proceedings under Part I.1 or II</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText3">General Rules Relating to Payment of Duty</span></a>
</li>
<li><span class='sectionRange'>13.2 - </span><a href="#h-9"><span class="HTitleText3">Expedited Review of Normal Value, Export Price or Amount of Subsidy</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText3">Exemption from Application of Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-11"><span class="HTitleText2">NORMAL VALUE, EXPORT PRICE, MARGIN OF DUMPING AND AMOUNT OF SUBSIDY</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText3">Normal Value</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-13"><span class="HTitleText3">Export Price</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText3">Normal Value and Export Price</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-15"><span class="HTitleText3">Margin of Dumping</span></a>
</li>
<li><span class='sectionRange'>30.4 - </span><a href="#h-16"><span class="HTitleText3">Amount of Subsidy</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText2">PROCEDURE IN DUMPING AND SUBSIDY INVESTIGATIONS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-18"><span class="HTitleText3">Commencement of Investigation</span></a>
</li>
<li><span class='sectionRange'>37.1 - </span><a href="#h-19"><span class="HTitleText3">Preliminary Determination of Injury or of Dumping or Subsidizing</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-20"><span class="HTitleText3">Final Determination</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-21"><span class="HTitleText2">INQUIRIES BY TRIBUNAL</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-22"><span class="HTitleText2">UNDERTAKINGS</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-23"><span class="HTitleText2">DETERMINATIONS BY DESIGNATED OFFICER</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-24"><span class="HTitleText2">RE-DETERMINATIONS AND APPEALS</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-25"><span class="HTitleText3">Re-determination by Designated Officer or Commissioner</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-26"><span class="HTitleText3">Appeal to Canadian International Trade Tribunal</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-27"><span class="HTitleText3">Appeal to Federal Court</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-28"><span class="HTitleText3">Review of Orders and Findings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-29"><span class="HTitleText4">Judicial Review</span></a>
</li>
<li><span class='sectionRange'>76.01 - </span><a href="#h-30"><span class="HTitleText4">Review of Orders and Findings by Tribunal</span></a>
</li>
<li><span class='sectionRange'>76.02 - </span><a href="#h-31"><span class="HTitleText4">Review on Referral Back</span></a>
</li>
<li><span class='sectionRange'>76.03 - </span><a href="#h-32"><span class="HTitleText4">Expiry Review</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-33"><span class="HTitleText3">Rescission of Orders and Findings</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>77.01 - </span><a href="#h-34"><span class="HLabel1">PART I.1</span> - <span class="HTitleText1">Dispute Settlement Respecting Goods of a NAFTA Country</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77.01 - </span><a href="#h-35"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>77.011 - </span><a href="#h-36"><span class="HTitleText2">Request for Review</span></a>
</li>
<li><span class='sectionRange'>77.013 - </span><a href="#h-37"><span class="HTitleText2">Establishment of Panels</span></a>
</li>
<li><span class='sectionRange'>77.015 - </span><a href="#h-38"><span class="HTitleText2">Review by Panel</span></a>
</li>
<li><span class='sectionRange'>77.016 - </span><a href="#h-39"><span class="HTitleText2">Action on Decision of Panel</span></a>
</li>
<li><span class='sectionRange'>77.017 - </span><a href="#h-40"><span class="HTitleText2">Extraordinary Challenge Proceeding</span></a>
</li>
<li><span class='sectionRange'>77.021 - </span><a href="#h-41"><span class="HTitleText2">Members</span></a>
</li>
<li><span class='sectionRange'>77.023 - </span><a href="#h-42"><span class="HTitleText2">Review by Special Committee</span></a>
</li>
<li><span class='sectionRange'>77.034 - </span><a href="#h-43"><span class="HTitleText2">Offence</span></a>
</li>
<li><span class='sectionRange'>77.035 - </span><a href="#h-44"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>77.037 - </span><a href="#h-45"><span class="HTitleText2">Application of Acts</span></a>
</li></ul>
</li><li><span class='sectionRange'>77.1 - </span><a href="#h-46"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Dispute Settlement Respecting Goods of the United States</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77.1 - </span><a href="#h-47"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>77.11 - </span><a href="#h-48"><span class="HTitleText2">Request for Review</span></a>
</li>
<li><span class='sectionRange'>77.13 - </span><a href="#h-49"><span class="HTitleText2">Establishment of Panels</span></a>
</li>
<li><span class='sectionRange'>77.15 - </span><a href="#h-50"><span class="HTitleText2">Review by Panel</span></a>
</li>
<li><span class='sectionRange'>77.16 - </span><a href="#h-51"><span class="HTitleText2">Action on Decision of Panel</span></a>
</li>
<li><span class='sectionRange'>77.17 - </span><a href="#h-52"><span class="HTitleText2">Extraordinary Challenge Proceeding</span></a>
</li>
<li><span class='sectionRange'>77.21 - </span><a href="#h-53"><span class="HTitleText2">Members</span></a>
</li>
<li><span class='sectionRange'>77.23 - </span><a href="#h-54"><span class="HTitleText2">Secretariat</span></a>
</li>
<li><span class='sectionRange'>77.26 - </span><a href="#h-55"><span class="HTitleText2">Offence</span></a>
</li>
<li><span class='sectionRange'>77.27 - </span><a href="#h-56"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>77.29 - </span><a href="#h-57"><span class="HTitleText2">Application of Acts</span></a>
</li></ul>
</li><li><span class='sectionRange'>78 - </span><a href="#h-58"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>78 - </span><a href="#h-59"><span class="HTitleText2">Provision of Evidence to Commissioner</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-60"><span class="HTitleText2">Collection of Duty</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-61"><span class="HTitleText2">Disclosure of Information</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-62"><span class="HTitleText2">Ruling on Who is Importer</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-63"><span class="HTitleText2">Gathering of Information</span></a>
</li>
<li><span class='sectionRange'>96.1 - </span><a href="#h-64"><span class="HTitleText2">Application for Review</span></a>
</li>
<li><span class='sectionRange'>96.4 - </span><a href="#h-65"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>97 - </span><a href="#h-66"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-67"><span class="HTitleText1">Orders</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
