<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
International Boundary Waters Treaty Act</a><ul class="TocIndent"><li><span class='sectionRange'>10 - </span><a href="page-1.html#h-271358"><span class="HTitleText1">Licences and Prohibitions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-271359"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-271375"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-271390"><span class="HTitleText2">Prohibition</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-271409"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-271418"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="page-1.html#h-271451"><span class="HTitleText2">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>20.1 - </span><a href="page-1.html#h-271452"><span class="HTitleText3">Designation</span></a>
</li>
<li><span class='sectionRange'>20.2 - </span><a href="page-1.html#h-271457"><span class="HTitleText3">Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="page-2.html#h-271536"><span class="HTitleText2">Regulations and Orders</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="page-2.html#h-271564"><span class="HTitleText2">Aboriginal and Treaty Rights</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-271569"><span class="HTitleText2">Obstruction and False Information</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-271585"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-271768"><span class="HTitleText2">Injunctions</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-3.html#h-271778"><span class="HTitleText2">Report</span></a>
</li></ul>
</li><li><a href="page-4.html#h-271787"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-5.html#h-271883"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Water Basins</span></a>
</li>
<li><a href="page-6.html#h-271893"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Transboundary Waters</span></a>
</li></ul>
</li></ul>

</nav>

