<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les produits dangereux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-248102"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-248107"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-248134"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">[Abrogée, 2010, ch. 21, art. 73]</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-248144"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Produits dangereux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-248146"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-248158"><span class="HTitleText2">Interdictions</span></a>
</li>
<li><span class='sectionRange'>14.3 - </span><a href="#h-248193"><span class="HTitleText2">Tenue de documents</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-248210"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-248258"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-248283"><span class="HTitleText2">Modification des annexes 1 et 2</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-248290"><span class="HTitleText2">Consultation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-248295"><span class="HTitleText2">Essais, études et compilation de renseignements</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-248313"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Exécution et contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-248314"><span class="HTitleText2">Inspecteurs et analystes</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-248324"><span class="HTitleText2">Inspection et analyse</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-248383"><span class="HTitleText2">Mesures relatives aux choses saisies</span></a>
</li>
<li><span class='sectionRange'>26.01 - </span><a href="#h-248424"><span class="HTitleText2">Retrait ou confiscation d’importations illégales</span></a>
</li>
<li><span class='sectionRange'>26.1 - </span><a href="#h-248440"><span class="HTitleText2">Ordre de prise de mesures</span></a>
</li>
<li><span class='sectionRange'>26.2 - </span><a href="#h-248452"><span class="HTitleText2">Révision de l’ordre de prise de mesures</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-248486"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-248499"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-248521"><span class="HTitleText2">Infractions, peines et procédure</span></a>
</li></ul>
</li><li><a href="#h-248572"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Non-application de la partie II</span></a>
</li>
<li><a href="#h-248582"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Classes de danger</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
