<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Indian Oil and Gas Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-333209"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-333214"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-1195557"><span class="HTitleText1">Royalties</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="page-1.html#h-1195567"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-2.html#h-1195644"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-1195681"><span class="HTitleText1">Inspection, Audit and Examination</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-1195749"><span class="HTitleText1">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-1195759"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-1195774"><span class="HTitleText1">Unauthorized Exploration and Exploitation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-1195783"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-3.html#h-1195861"><span class="HTitleText1">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>28.1 - </span><a href="page-3.html#h-1195933"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-1195941"><span class="HTitleText1">Transitional</span></a>
</li></ul>
</li></ul>

</nav>

