<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Ministries and Ministers of State Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-358560"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-358565"><span class="HTitleText1">Ministries of State for Specified Purposes</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-358592"><span class="HTitleText1">Ministers of State for Ministries of State</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-358612"><span class="HTitleText1">Other Ministers of State</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
