<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Parlement du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Sénat et Chambre des communes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Continuité du Parlement</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Privilèges, immunités et pouvoirs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText3">Nature</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText3">Publication de documents</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText3">Interrogatoire des témoins</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Sénat</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText2">Conflits d’intérêts</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Suppléance du président</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="#h-11"><span class="HTitleText2">Régie interne</span></a>
</li>
<li><span class='sectionRange'>19.5 - </span><a href="#h-12"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>19.6 - </span><a href="#h-13"><span class="HTitleText2">Avis</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText2">Administration financière</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-15"><span class="HTitleText2">Conseiller sénatorial en éthique</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-16"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Chambre des communes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-17"><span class="HLabel2">SECTION A</span> - <span class="HTitleText2">ÉLIGIBILITÉ, DÉMISSION ET VACANCE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-18"><span class="HTitleText3">Candidatures multiples</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-19"><span class="HTitleText3">Membres d’une législature provinciale</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-20"><span class="HTitleText3">Démission d’un député</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-21"><span class="HTitleText3">Vacance</span></a>
</li></ul>
</li><li><span class='sectionRange'>32 - </span><a href="#h-22"><span class="HLabel2">SECTION B</span> - <span class="HTitleText2">CONFLITS D’INTÉRÊTS</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-23"><span class="HLabel2">SECTION C</span> - <span class="HTitleText2">PRÉSIDENT, SECRÉTAIRES PARLEMENTAIRES, GREFFIER ET AUTRES MEMBRES DU PERSONNEL</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-24"><span class="HTitleText3">Suppléance du président</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-25"><span class="HTitleText3">Secrétaires parlementaires</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-26"><span class="HTitleText3">Greffier et autres membres du personnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>50 - </span><a href="#h-27"><span class="HLabel2">SECTION D</span> - <span class="HTitleText2">BUREAU DE RÉGIE INTERNE</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="#h-28"><span class="HTitleText3">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>52.2 - </span><a href="#h-29"><span class="HTitleText3">Mission</span></a>
</li>
<li><span class='sectionRange'>52.5 - </span><a href="#h-30"><span class="HTitleText3">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>52.6 - </span><a href="#h-31"><span class="HTitleText3">Avis</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>54.1 - </span><a href="#h-32"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Rémunération des parlementaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54.1 - </span><a href="#h-33"><span class="HTitleText2">Montant de base de la rémunération</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-34"><span class="HTitleText2">Indemnités de session : avant le 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-35"><span class="HTitleText2">Indemnités de session : à compter du 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-36"><span class="HTitleText2">Dispositions générales relatives aux indemnités de session</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-37"><span class="HTitleText2">Traitements et autres indemnités de certains membres : avant le 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>62.1 - </span><a href="#h-38"><span class="HTitleText2">Traitements et autres indemnités de certains membres : à compter du 1<sup>er</sup> avril 2004</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-39"><span class="HTitleText2">Frais</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-40"><span class="HTitleText2">Rajustement des traitements et indemnités</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-41"><span class="HTitleText2">Indemnités en cas de dissolution de la Chambre des communes</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-42"><span class="HTitleText2">Indemnité de départ</span></a>
</li>
<li><span class='sectionRange'>71.1 - </span><a href="#h-43"><span class="HTitleText2">Allocation d’invalidité</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="#h-44"><span class="HTitleText2">Régimes collectifs d'assurance</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-45"><span class="HTitleText2">Dispositions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>72.01 - </span><a href="#h-46"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72.01 - </span><a href="#h-47"><span class="HTitleText2">Commissaire à l’éthique</span></a>
</li>
<li><span class='sectionRange'>72.05 - </span><a href="#h-48"><span class="HTitleText2">Fonctions à l’égard des députés</span></a>
</li>
<li><span class='sectionRange'>72.06 - </span><a href="#h-49"><span class="HTitleText2">Fonctions à l’égard des titulaires de charge publique</span></a>
</li>
<li><span class='sectionRange'>72.12 - </span><a href="#h-50"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-51"><span class="HTitleText2">Bibliothèque du Parlement</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-52"><span class="HTitleText2">Infraction et peine</span></a>
</li></ul>
</li><li><a href="#h-53"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
