<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Payments Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-74004"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-74009"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="#h-74072"><span class="HTitleText1">Act Binding on Her Majesty</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-74080"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canadian Payments Association</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-74081"><span class="HTitleText2">Establishment and Membership</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-74135"><span class="HTitleText2">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-74157"><span class="HTitleText2">Head Office</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-74162"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-74218"><span class="HTitleText2">Chairperson</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-74230"><span class="HTitleText2">President</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-74240"><span class="HTitleText2">Duty of Care</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-74247"><span class="HTitleText2">Duties and Powers of Board</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-74287"><span class="HTitleText2">Rules, Statements of Principle and Standards</span></a>
</li>
<li><span class='sectionRange'>19.2 - </span><a href="#h-74308"><span class="HTitleText2">Disallowance</span></a>
</li>
<li><span class='sectionRange'>19.3 - </span><a href="#h-74318"><span class="HTitleText2">Directives</span></a>
</li>
<li><span class='sectionRange'>19.4 - </span><a href="#h-74334"><span class="HTitleText2">Information Requirements</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-74343"><span class="HTitleText2">Committees of the Board</span></a>
</li>
<li><span class='sectionRange'>21.2 - </span><a href="#h-74361"><span class="HTitleText2">Stakeholder Advisory Council</span></a>
</li>
<li><span class='sectionRange'>21.4 - </span><a href="#h-74383"><span class="HTitleText2">Member Advisory Council</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-74393"><span class="HTitleText2">Budgets</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-74401"><span class="HTitleText2">Corporate Plan and Annual Report</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-74426"><span class="HTitleText2">Annual Meeting</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-74434"><span class="HTitleText2">Auditor</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-74443"><span class="HTitleText2">Fiscal Year</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-74448"><span class="HTitleText2">Electronic Meetings</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-74457"><span class="HTitleText2">Rights and Duties of Members</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-74463"><span class="HTitleText2">Insolvency</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-74490"><span class="HTitleText2">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-74498"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-74511"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Designated Payment Systems</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-74512"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-74521"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-74526"><span class="HTitleText2">Designation</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-74545"><span class="HTitleText2">Rules</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-74561"><span class="HTitleText2">Guidelines and Directives</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-74591"><span class="HTitleText2">Information Requirements</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-74601"><span class="HTitleText2">Participants</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-74614"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
