<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’économie de pétrole et le remplacement du mazout</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-377759"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-377764"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-377769"><span class="HTitleText1">Paiements de reconversion et d’amélioration du rendement énergétique</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-377785"><span class="HTitleText1">Assistance à la commercialisation et au développement</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-377795"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

