<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la participation publique au capital de Petro-Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-382211"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-382214"><span class="HTitleText1">Définitions et application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-382229"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-382232"><span class="HTitleText1">Changements de dénomination sociale</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-382242"><span class="HTitleText1">Transfert d’actions au ministre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-382250"><span class="HTitleText1">Vente d’actions par Petro-Canada</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-382253"><span class="HTitleText1">Réorganisation de Petro-Canada</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-382324"><span class="HTitleText1">Accords financiers</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-382329"><span class="HTitleText1">La corporation Petro-Canada pour l’assistance internationale</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-382341"><span class="HTitleText1">Dissolution de Petro-Canada limitée</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-382350"><span class="HTitleText1">Dispositions diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-382351"><span class="HTitleText2">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-382383"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-382390"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-382399"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>

