<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Conseil des Arts du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-71550"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-71555"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-71562"><span class="HTitleText1">Mise en place</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-71567"><span class="HTitleText1">Membres du conseil</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-71577"><span class="HTitleText1">Directeur</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-71585"><span class="HTitleText1">Rémunération et indemnités</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-71593"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-71598"><span class="HTitleText1">Mission et attributions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-71629"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-71667"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-71672"><span class="HTitleText1">Rapport au Parlement</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
