<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des pêches côtières</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-85115"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-85120"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-85159"><span class="HTitleText1">Bateaux de pêche étrangers</span></a>
</li>
<li><span class='sectionRange'>5.6 - </span><a href="#h-1132036"><span class="HTitleText1">Importation interdite</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-85205"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-85236"><span class="HTitleText1">Inspection, arrestation, saisie et confiscation</span></a>
</li>
<li><span class='sectionRange'>16.4 - </span><a href="#h-1132235"><span class="HTitleText1">Renseignements</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-85324"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-85374"><span class="HTitleText1">Application du droit criminel</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-85406"><span class="HTitleText1">Compétence des tribunaux</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
