<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le Mois du patrimoine juif canadien</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-71377"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-71380"><span class="HTitleText1">Mois du patrimoine juif canadien</span></a>
</li></ul>
</li></ul>

</nav>

