<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Tla’amin Final Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-448803"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-448806"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-448816"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-448829"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-448832"><span class="HTitleText1">Lands</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-448835"><span class="HTitleText1">Taxation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-448840"><span class="HTitleText1">Application of Other Acts</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-448854"><span class="HTitleText1">Application of Laws of British Columbia</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-1.html#h-448857"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-448888"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="page-1.html#h-448889"><span class="HTitleText2"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-448891"><span class="HTitleText2"><cite class="XRefExternalAct">Fisheries Act</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-448893"><span class="HTitleText2"><cite class="XRefExternalAct">Payments in Lieu of Taxes Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-448895"><span class="HTitleText2"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-448897"><span class="HTitleText2"><cite class="XRefExternalAct">First Nations Land Management Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-448899"><span class="HTitleText2"><cite class="XRefExternalAct">Specific Claims Tribunal Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="page-1.html#h-448901"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

