<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection des renseignements personnels et les documents électroniques</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Protection des renseignements personnels dans le secteur privé</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Protection des renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-7"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Recours</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-8"><span class="HTitleText3">Dépôt des plaintes</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText3">Examen des plaintes</span></a>
</li>
<li><span class='sectionRange'>12.2 - </span><a href="#h-10"><span class="HTitleText3">Fin de l’examen</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-11"><span class="HTitleText3">Rapport du commissaire</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-12"><span class="HTitleText3">Audience de la Cour</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Vérifications</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Dispositions transitoires</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-16"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Documents électroniques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-19"><span class="HTitleText2">Moyens électroniques</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-20"><span class="HTitleText2">Règlements et décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>52 à 57 - </span><a href="#h-21"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Modification de la Loi sur la preuve au Canada</span></a>
</li>
<li><span class='sectionRange'>58 et 59 - </span><a href="#h-22"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Modification de la Loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>60 à 71 - </span><a href="#h-23"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Modification de la Loi sur la révision des lois</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-24"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-407817"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Principes énoncés dans la norme nationale du Canada intitulée Code type sur la protection des renseignements personnels, CAN/CSA-Q830-96</span></a>
</li>
<li><a href="#h-407950"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-407960"><span class="scheduleLabel">ANNEXE 3</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
