<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi nationale sur l’habitation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-350477"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-350482"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-350547"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-350552"><span class="HTitleText1">Droits et obligations de la société</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-350558"><span class="HTitleText1">Prêteurs agréés</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-350587"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Assurance de prêts à l’habitation, garantie et protection</span></a>
</li>
<li><span class='sectionRange'>21.5 - </span><a href="#h-350786"><span class="HLabel1">PARTIE I.1</span> - <span class="HTitleText1">Obligations sécurisées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21.5 - </span><a href="#h-350787"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>21.51 - </span><a href="#h-350800"><span class="HTitleText2">Mise en place du cadre juridique</span></a>
</li>
<li><span class='sectionRange'>21.63 - </span><a href="#h-350907"><span class="HTitleText2">Protection en cas d’insolvabilité et de faillite</span></a>
</li>
<li><span class='sectionRange'>21.66 - </span><a href="#h-350930"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-350943"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Logements locatifs</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-351032"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Lotissement</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-351085"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Acquisition des terrains et location-financement</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-351096"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">[Abrogée, L.R. (1985), ch. 25 (4e suppl.), art. 23]</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-351097"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Réparation, remise en état, amélioration et transformation des immeubles</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-351111"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Aide destinée à faciliter l’accession à la propriété et l’occupation des habitations</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-351137"><span class="HLabel1">PARTIE IX</span> - <span class="HTitleText1">Recherche en matière d’habitation, urbanisme et activité internationale</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-351192"><span class="HLabel1">PARTIE X</span> - <span class="HTitleText1">Logement public</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-351215"><span class="HLabel1">PARTIE XI</span> - <span class="HTitleText1">Collectivités nouvelles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-351216"><span class="HTitleText2">Accords fédéro-provinciaux</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-351234"><span class="HTitleText2">Prêts</span></a>
</li></ul>
</li><li><span class='sectionRange'>87 - </span><a href="#h-351257"><span class="HLabel1">PARTIE XII</span> - <span class="HTitleText1">Prêts pour des ensembles d’habitation destinés aux étudiants</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-351274"><span class="HLabel1">PARTIE XIII</span> - <span class="HTitleText1">Services communautaires</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-351284"><span class="HLabel1">PARTIE XIV</span> - <span class="HTitleText1">Développement du secteur de l’habitation</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-351337"><span class="HLabel1">PARTIE XV</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>102 - </span><a href="#h-351401"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
