<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi canadienne sur la protection de l’environnement (1999)</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-61956"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-61959"><span class="HTitleText1">Application administrative</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-61987"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-62064"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-62067"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Exécution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-62068"><span class="HTitleText2">Comités consultatifs</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-62109"><span class="HTitleText2">Accords relatifs à l’exécution de la présente loi</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-62129"><span class="HTitleText2">Accords relatifs aux dispositions équivalentes</span></a>
</li></ul>
</li><li><span class='sectionRange'>11 - </span><a href="#h-62153"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Participation du public</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-62154"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-62157"><span class="HTitleText2">Registre de la protection de l’environnement</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-62173"><span class="HTitleText2">Droits prévus aux autres parties</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-62176"><span class="HTitleText2">Rapports volontaires</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-62189"><span class="HTitleText2">Enquêtes sur les infractions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-62212"><span class="HTitleText2">Action en protection de l’environnement</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-62313"><span class="HTitleText2">Injonction et action en dommages-intérêts</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-62318"><span class="HTitleText2">Dispositions diverses</span></a>
</li></ul>
</li><li><span class='sectionRange'>43 - </span><a href="#h-62335"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Collecte de l’information et établissement d’objectifs, de directives et de codes de pratique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>43 - </span><a href="#h-62336"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-62341"><span class="HTitleText2">Données et recherches sur l’environnement</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-62364"><span class="HTitleText2">Collecte de l’information</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-62433"><span class="HTitleText2">Objectifs, directives et codes de pratique</span></a>
</li></ul>
</li><li><span class='sectionRange'>56 - </span><a href="#h-62456"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Prévention de la pollution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>56 - </span><a href="#h-62457"><span class="HTitleText2">Plans de prévention de la pollution</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-62496"><span class="HTitleText2">Modèles de plan et directives</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-62506"><span class="HTitleText2">Autres initiatives</span></a>
</li></ul>
</li><li><span class='sectionRange'>64 - </span><a href="#h-62514"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Substances toxiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="#h-62515"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-62532"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-62587"><span class="HTitleText2">Collecte de renseignements</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-62611"><span class="HTitleText2">Substances d’intérêt prioritaire et autres substances</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-62702"><span class="HTitleText2">Substances et activités nouvelles au Canada</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-62844"><span class="HTitleText2">Réglementation des substances toxiques</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-62939"><span class="HTitleText2">Rejet de substances toxiques</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-63007"><span class="HTitleText2">Exportation des substances</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-63034"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Substances biotechnologiques animées</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-63185"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Contrôle de la pollution et gestion des déchets</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-63186"><span class="HLabel2">SECTION 1</span> - <span class="HTitleText2">Substances nutritives</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-63230"><span class="HLabel2">SECTION 2</span> - <span class="HTitleText2">Protection du milieu marin contre la pollution de source tellurique</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-63245"><span class="HLabel2">SECTION 3</span> - <span class="HTitleText2">Immersion en mer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>122 - </span><a href="#h-63246"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>122.1 - </span><a href="#h-63288"><span class="HTitleText3">Objet</span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-63293"><span class="HTitleText3">Interdictions</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-63360"><span class="HTitleText3">Permis</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-63411"><span class="HTitleText3">Cas d’urgence</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-63428"><span class="HTitleText3">Surveillance des sites</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-63431"><span class="HTitleText3">Publication</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-63441"><span class="HTitleText3">Avis d’opposition</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-63454"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-63481"><span class="HTitleText3">Dépenses de l’État</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-63486"><span class="HTitleText3">Signification des documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>138 - </span><a href="#h-63493"><span class="HLabel2">SECTION 4</span> - <span class="HTitleText2">Combustibles</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>138 - </span><a href="#h-63494"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-63499"><span class="HTitleText3">Réglementation des combustibles</span></a>
</li>
<li><span class='sectionRange'>141 - </span><a href="#h-63547"><span class="HTitleText3">Marques nationales</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-63583"><span class="HTitleText3">Dérogations</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-63586"><span class="HTitleText3">Mesures correctives</span></a>
</li></ul>
</li><li><span class='sectionRange'>149 - </span><a href="#h-63601"><span class="HLabel2">SECTION 5</span> - <span class="HTitleText2">Émissions des véhicules, moteurs et équipements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>149 - </span><a href="#h-63602"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-63624"><span class="HTitleText3">Marques nationales</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-63638"><span class="HTitleText3">Normes pour les véhicules, moteurs et équipements</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-63676"><span class="HTitleText3">Dispense pour les véhicules et les moteurs</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-63693"><span class="HTitleText3">Avis de défaut</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-63714"><span class="HTitleText3">Recherches et tests</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-63731"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>164 - </span><a href="#h-63785"><span class="HTitleText3">Preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>166 - </span><a href="#h-63790"><span class="HLabel2">SECTION 6</span> - <span class="HTitleText2">Pollution atmosphérique internationale</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-63887"><span class="HLabel2">SECTION 7</span> - <span class="HTitleText2">Pollution internationale des eaux</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-63991"><span class="HLabel2">SECTION 8</span> - <span class="HTitleText2">Contrôle des mouvements de déchets dangereux ou de matières recyclables dangereuses et de déchets non dangereux régis devant être éliminés définitivement</span></a>
</li></ul>
</li><li><span class='sectionRange'>193 - </span><a href="#h-64049"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Questions d’ordre environnemental en matière d’urgences</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="#h-64226"><span class="HLabel1">PARTIE 9</span> - <span class="HTitleText1">Opérations gouvernementales, territoire domanial et terres autochtones</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>206 - </span><a href="#h-64227"><span class="HTitleText2">Définition</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-64230"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-64240"><span class="HTitleText2">Objectifs, directives et codes de pratique</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-64248"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-64296"><span class="HTitleText2">Renseignements sur les projets d’entreprises et d’activités</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-64302"><span class="HTitleText2">Rejet de substances</span></a>
</li></ul>
</li><li><span class='sectionRange'>216 - </span><a href="#h-64353"><span class="HLabel1">PARTIE 10</span> - <span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>216 - </span><a href="#h-64354"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-64375"><span class="HTitleText2">Agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="#h-64397"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>220 - </span><a href="#h-64471"><span class="HTitleText2">Perquisition</span></a>
</li>
<li><span class='sectionRange'>222.1 - </span><a href="#h-64518"><span class="HTitleText2">Arrestation sans mandat</span></a>
</li>
<li><span class='sectionRange'>223 - </span><a href="#h-64523"><span class="HTitleText2">Rétention</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-64555"><span class="HTitleText2">Arrêt de navires</span></a>
</li>
<li><span class='sectionRange'>225.1 - </span><a href="#h-64579"><span class="HTitleText2">Ordre aux navires</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-64591"><span class="HTitleText2">Aide à donner aux agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>228.1 - </span><a href="#h-64604"><span class="HTitleText2">Responsabilité pour frais</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-64609"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-64648"><span class="HTitleText2">Ordres d’exécution en matière de protection de l’environnement</span></a>
</li>
<li><span class='sectionRange'>243 - </span><a href="#h-64775"><span class="HTitleText2">Réviseurs</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-64815"><span class="HTitleText2">Révisions</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-64871"><span class="HTitleText2">Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>271.1 - </span><a href="#h-64878"><span class="HTitleText2">Actes commis hors du Canada</span></a>
</li>
<li><span class='sectionRange'>272 - </span><a href="#h-64888"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>287 - </span><a href="#h-65174"><span class="HTitleText2">Détermination de la peine</span></a>
</li>
<li><span class='sectionRange'>288 - </span><a href="#h-65210"><span class="HTitleText2">Absolution</span></a>
</li>
<li><span class='sectionRange'>295 - </span><a href="#h-65311"><span class="HTitleText2">Mesures de rechange en matière de protection de l’environnement</span></a>
</li>
<li><span class='sectionRange'>310 - </span><a href="#h-65449"><span class="HTitleText2">Contraventions</span></a>
</li>
<li><span class='sectionRange'>311 - </span><a href="#h-65459"><span class="HTitleText2">Autres moyens de droit</span></a>
</li>
<li><span class='sectionRange'>312 - </span><a href="#h-65467"><span class="HTitleText2">Moyen de défense</span></a>
</li></ul>
</li><li><span class='sectionRange'>313 - </span><a href="#h-65470"><span class="HLabel1">PARTIE 11</span> - <span class="HTitleText1">Dispositions diverses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>313 - </span><a href="#h-65471"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>322 - </span><a href="#h-65524"><span class="HTitleText2">Mesures économiques</span></a>
</li>
<li><span class='sectionRange'>328 - </span><a href="#h-65562"><span class="HTitleText2">Règlements en matière de droits et tarifs</span></a>
</li>
<li><span class='sectionRange'>330 - </span><a href="#h-65578"><span class="HTitleText2">Pouvoirs réglementaires généraux et dérogations</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="#h-65609"><span class="HTitleText2">Obligation de prépublication</span></a>
</li>
<li><span class='sectionRange'>333 - </span><a href="#h-65619"><span class="HTitleText2">Cas de constitution d’une commission de révision</span></a>
</li>
<li><span class='sectionRange'>342 - </span><a href="#h-65663"><span class="HTitleText2">Rapport au Parlement</span></a>
</li></ul>
</li><li><span class='sectionRange'>344 à 354 - </span><a href="#h-65676"><span class="HLabel1">PARTIE 12</span> - <span class="HTitleText1">Modifications corrélatives, abrogation, disposition transitoire et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>344 à 354 - </span><a href="#h-65677"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>355 - </span><a href="#h-65679"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>355.1 - </span><a href="#h-65681"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>356 - </span><a href="#h-65687"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-65691"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Liste des substances toxiques</span></a>
</li>
<li><a href="#h-65957"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li>
<li><a href="#h-65967"><span class="scheduleLabel">ANNEXE 3</span> <span class="scheduleTitleText"> - Liste des substances d’exportation contrôlée</span></a>
</li>
<li><a href="#h-66081"><span class="scheduleLabel">ANNEXE 4</span> </a>
</li>
<li><a href="#h-66091"><span class="scheduleLabel">ANNEXE 5</span> <span class="scheduleTitleText"> - Déchets ou autres matières</span></a>
</li>
<li><a href="#h-66099"><span class="scheduleLabel">ANNEXE 6</span> <span class="scheduleTitleText"> - Gestion des déchets ou autres matières</span></a>
</li></ul>
</li></ul>

</nav>

