<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Office des droits de surface du Yukon</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interprétation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Terres gwich’in tetlit du Yukon</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Incompatibilité de textes</span></a>
</li></ul>
</li><li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Office des droits de surface du Yukon</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Mise en place de l’Office</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText2">Siège et réunions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText2">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-13"><span class="HTitleText2">Statut</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText2">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2">Rapports</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Saisine de l’Office</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-18"><span class="HTitleText2">Dossiers</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-19"><span class="HTitleText2">Règles</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-20"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Terres désignées</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-21"><span class="HTitleText2">Accès sur consentement ou ordonnance</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-22"><span class="HTitleText2">Conditions supplémentaires relatives à l’accès de plein droit</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-23"><span class="HTitleText2">Différends concernant l’accès de plein droit</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-24"><span class="HTitleText2">Différends concernant les matières spécifiées</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-25"><span class="HTitleText2">Différends concernant les carrières</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-26"><span class="HTitleText2">Expropriation</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-27"><span class="HTitleText2">Réserves</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-28"><span class="HTitleText2">Caractérisation des terres désignées</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-29"><span class="HTitleText2">Attributions supplémentaires de l’Office</span></a>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-30"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Différends concernant les droits miniers sur les terres non désignées</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-31"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-32"><span class="HTitleText2">Décisions de l’Office</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-33"><span class="HTitleText2">Révision des ordonnances</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-34"><span class="HTitleText2">Règlements et décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 à 102 - </span><a href="#h-35"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Modifications corrélatives et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 à 102 - </span><a href="#h-36"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-37"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-464235"><span class="scheduleLabel">ANNEXE I</span> </a>
</li>
<li><a href="#h-464266"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Droits d’accès</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
