<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Expropriation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Expropriation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Acquisition and Abandonment of Land</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-5"><span class="HTitleText2">Compensation</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-6"><span class="HTitleText2">Payment of Compensation</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-7"><span class="HTitleText2">Interest</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-8"><span class="HTitleText2">Entry and Possession</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-9"><span class="HTitleText2">Costs</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-10"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Use of Lands</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-11"><span class="HLabel1">PART III</span> - <span class="HTitleText1">General</span></a>
</li>
<li><a href="#h-12"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
