<footer id="wb-info" class="visible-sm visible-md visible-lg wb-navcurr">
<div class="container">
<nav role="navigation">
<h2>À propos de ce site</h2>
<ul id="gc-tctr" class="list-inline">
<li ><a href="https://www.justice.gc.ca/fra/avis-terms/index.html" >Avis</a></li>
<li ><a href="https://www.justice.gc.ca/fra/trans/index.html">Transparence</a></li></ul>
<div class="row">
<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/fra/contact/index.html">Contactez-nous</a></h3>
<ul class="list-unstyled">
                           <li><a href="https://www.justice.gc.ca/fra/contact/comm4.html">Politique en mati&egrave;re d'aide juridique</a></li>
                           <li><a href="https://www.justice.gc.ca/fra/contact/comm3.html">Signification &agrave; la Couronne</a></li>
                           <li><a href="https://www.justice.gc.ca/fra/contact/comm2.html">Guide canadien d'information juridique</a></li>
                           <li><a href="https://www.justice.gc.ca/fra/contact/aide-help.html">Aide</a></li>
                           <li><a href="https://www.justice.gc.ca/fra/contact/lien-link.html">Liens utiles</a></li></ul>
</section>


<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/fra/apd-abt/index.html">&Agrave; propos de nous</a></h3>
<ul class="list-unstyled">
                            <li><a href="https://www.justice.gc.ca/fra/apd-abt/min.html">Le ministre et procureur g&eacute;n&eacute;ral</a></li>
                            <li><a href="https://www.justice.gc.ca/fra/apd-abt/org.html">Organisation</a></li>
                            <li><a href="https://www.justice.gc.ca/fra/trans/lr-ar/index.html">Lois et r&egrave;glements</a></li>
                            <li><a href="https://www.justice.gc.ca/fra/apd-abt/recru/index.html">Carri&egrave;re et programmes de stages</a></li>
                            <li><a href="https://www.justice.gc.ca/fra/pr-rp/index.html">Rapports et publications</a></li>
                            <li><a href="https://www.justice.gc.ca/fra/apd-abt/dd-sd/index.html">D&eacute;veloppement durable</a></li>
                            <li><a href="https://www.justice.gc.ca/fra/trans/ouvert-open.html">Gouvernement ouvert au ministère de la Justice Canada</a></li>

</ul>
</section>
<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/fra/nouv-news/index.html">Nouvelles</a></h3>
<ul class="list-unstyled">
	<li><a href="https://www.justice.gc.ca/fra/nouv-news/cp-nr.html">Communiqu&eacute;s de presse</a></li>
	<li><a href="https://www.justice.gc.ca/fra/nouv-news/doc-bck.html">Document d'information</a></li>		
	<li><a href="https://www.justice.gc.ca/fra/nouv-news/nj-ja.asp?tid=4" title="Nominations &agrave; la magistrature">Nominations &agrave; la magistrature</a></li>
	<li><a href="https://www.justice.gc.ca/fra/nouv-news/dec-sta.html">D&eacute;clarations</a></li>			
	<li><a href="https://www.justice.gc.ca/fra/nouv-news/di-sp.html">Discours</a></li>
	<li><a href="https://www.justice.gc.ca/fra/nouv-news/am-ma.html">Avis aux m&eacute;dias</a></li> 
	<li><a href="https://www.justice.gc.ca/fra/sjc-csj/pl/charte-charter/index.html">&Eacute;nonc&eacute; concernant la Charte</a></li>             			                       
	<li><a href="https://www.justice.gc.ca/fra/nouv-news/photo/index.html">Galerie de vid&eacute;os et photos</a></li></ul>
</section>


<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/fra/branches-connect.html">Restez branch&eacute;s</a></h3>
<ul class="list-unstyled">
	<li><a href="https://www.facebook.com/JusticeCanadaFr">Facebook</a></li>
	<li><a href="http://www.justice.gc.ca/fra/nouv-news/rss.html">RSS</a></li>
	<li><a href="https://twitter.com/JusticeCanadaFr">Twitter</a></li>
	<li><a href="http://www.youtube.com/user/JusticeCanadaFr">YouTube</a></li>
	<li><a href="https://www.linkedin.com/company/justice-canada/">LinkedIn</a></li>
	<li><a href="https://www.justice.gc.ca/fra/cons/index.html">Consultations publiques</a></li></ul>
</section>
</div>
</nav>
</div>
<div id="gc-info">
<div class="container">
<nav role="navigation">
<h2>Pied de page du gouvernement du Canada</h2>
<ul class="list-inline">
<li><a href="https://www.canada.ca/fr/services/sante.html"><span>Santé</span></a></li>
<li><a href="https://voyage.gc.ca/"><span>Voyage</span></a></li>
<li><a href="https://www.canada.ca/fr/emploi-developpement-social/ministere/portefeuille/service-canada.html"><span>Service Canada</span></a></li>
<li><a href="https://www.guichetemplois.gc.ca/accueil"><span>Emplois</span></a></li>
<li><a href="https://www.budget.gc.ca"><span>Économie</span></a></li>
<li id="canada-ca"><a href="https://www.canada.ca/fr.html">Canada.ca</a></li>
</ul>
</nav>
</div>
</div>
</footer>

<!-- insert Adobe Analytics code here -->
<!-- Do not remove - this Adobe Analytics tag - STARTS --> 
<script type="text/javascript">_satellite.pageBottom();</script> 
<!-- Do not remove - this Adobe Analytics tag - STARTS -->

