<footer id="wb-info" class="visible-sm visible-md visible-lg wb-navcurr">
<div class="container">
<nav role="navigation">
<h2>About this site</h2>
<ul id="gc-tctr" class="list-inline">
<li><a rel="license" href="https://www.justice.gc.ca/eng/terms-avis/index.html">Terms and conditions</a></li>
<li><a href="https://www.justice.gc.ca/eng/trans/index.html">Transparency</a></li>
</ul>
<div class="row">
<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/eng/contact/index.html">Contact us</a></h3>
<ul class="list-unstyled">
<li><a href="https://www.justice.gc.ca/eng/contact/Comm4.html">Policy on Legal Assistance</a></li>
<li><a href="https://www.justice.gc.ca/eng/contact/Comm3.html">Service on the Crown </a></li>
<li><a href="https://www.justice.gc.ca/eng/contact/Comm2.html">Guide to Canadian Legal Information</a></li>
<li><a href="https://www.justice.gc.ca/eng/contact/help-aide.html">Help</a></li>
<li><a href="https://www.justice.gc.ca/eng/contact/link-lien.html" title="Helpful links">Helpful Links</a></li>
</ul>
</section>
<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/eng/abt-apd/index.html">About us</a></h3>
<ul class="list-unstyled">
<li><a href="https://www.justice.gc.ca/eng/abt-apd/min.html">The Minister and Attorney General</a></li>
<li><a href="https://www.justice.gc.ca/eng/abt-apd/org.html">Organization</a></li>
<li><a href="https://www.justice.gc.ca/eng/trans/ar-lr/index.html">Acts and Regulations</a></li>
<li><a href="https://www.justice.gc.ca/eng/abt-apd/recru/index.html">Careers and Articling </a></li>
<li><a href="https://www.justice.gc.ca/eng/rp-pr/index.html">Reports and Publications</a></li>
<li><a href="https://www.justice.gc.ca/eng/abt-apd/sd-dd/index.html">Sustainable Development</a></li>
<li><a href="https://www.justice.gc.ca/eng/trans/open-ouvert.html">Open Government at Justice</a></li>
</ul>
</section>
<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/eng/news-nouv/index.html">News</a></h3>
<ul class="list-unstyled">
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/nr-cp.html">News Releases</a></li>			
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/bck-doc.html">Backgrounders</a></li>		
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/ja-nj.asp?tid=4">Judicial Appointments</a></li>
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/sta-dec.html">Statements</a></li>		
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/sp-di.html">Speeches</a></li>           
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/ma-am.html">Media Advisories</a></li>
			<li><a href="https://www.justice.gc.ca/eng/csj-sjc/pl/charter-charte/index.html">Charter Statements</a></li>
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/photo/index.html">Photo Gallery</a></li>
</ul>
</section>
<section class="col-sm-3">
<h3><a href="https://www.justice.gc.ca/eng/connect-branches.html">Stay connected</a></h3>
<ul class="list-unstyled">
			<li><a href="https://www.facebook.com/JusticeCanadaEn">Facebook</a></li>
			<li><a href="https://www.justice.gc.ca/eng/news-nouv/rss.html">RSS</a></li>
			<li><a href="https://twitter.com/JusticeCanadaEn">Twitter</a></li>
			<li><a href="http://www.youtube.com/user/JusticeCanadaEn">YouTube</a></li>
			<li><a href="https://www.linkedin.com/company/justice-canada/">LinkedIn</a></li>
			<li><a href="https://www.justice.gc.ca/eng/cons/index.html">Public Consultations</a></li>
</ul>
</section>
</div>
</nav>
</div>
<div id="gc-info">
<div class="container">
<nav role="navigation">
<h2>Government of Canada footer</h2>
<ul class="list-inline">
<li><a href="https://healthycanadians.gc.ca"><span>Health</span></a></li>
<li><a href="https://travel.gc.ca"><span>Travel</span></a></li>
<li><a href="https://www.servicecanada.gc.ca/eng/home.shtml"><span>Service Canada</span></a></li>
<li><a href="https://www.jobbank.gc.ca"><span>Jobs</span></a></li>
<li><a href="https://www.budget.gc.ca/"><span>Economy</span></a></li>
<li id="canada-ca"><a href="https://www.canada.ca/en/index.html">Canada.ca</a></li>
</ul>
</nav>
</div>
</div>
</footer>

<!-- insert Adobe Analytics code here -->
<!-- Do not remove - this Adobe Analytics tag - STARTS --> 
<script type="text/javascript">_satellite.pageBottom();</script> 
<!-- Do not remove - this Adobe Analytics tag - STARTS -->
