<nav id="wb-sec" typeof="SiteNavigationElement" class="col-md-3 col-md-pull-9 visible-md visible-lg">
<h2>Menu secondaire</h2>
<ul class="list-group menu list-unstyled"><li>
<h3 class="wb-navcurr">Textes constitutionnels</h3>
<ul class="list-group menu list-unstyled">
<li><a class="list-group-item" href="/fra/Const/page-12.html">Charte canadienne des droits et libertés</a></li>
<li><a class="list-group-item" href="/fra/Const/Const_index.html">Codification des Lois constitutionnelles de 1867 &agrave; 1982</a></li>
<li><a class="list-group-item" href="/fra/ConstRpt/Const_index.html">Codification des Lois constitutionnelles de 1867 &agrave; 1982 (fondée sur le rapport<br> de 1990)</a></li>
<li><a class="list-group-item" href="https://www.justice.gc.ca/fra/pr-rp/sjc-csj/constitution/loireg-lawreg/index.html">Comit&eacute; de r&eacute;daction constitutionnelle fran&ccedil;aise (1990)</a></li>
</ul>
</li>
<li>
<h3 class="wb-navcurr">Lois</h3>
<ul class="list-group menu list-unstyled">
<li><a class="list-group-item" href="/fra/lois/" title="Lois par titre">Lois  codifi&eacute;es</a></li>
<li><a class="list-group-item" href="/fra/reglements/" title="R&egrave;glements par titre">R&egrave;glements codifi&eacute;s</a></li>
<li><a class="list-group-item" href="/fra/LoisAnnuelles/">Lois annuelles</a></li> 
<li><a class="list-group-item" href="/fra/Rapports/">Loi sur l'abrogation des lois - rapports, reports et abrogations</a></li>
<li><a class="list-group-item" href="/fra/MSLA/">Programme de correction des lois</a></li>
<li><a class="list-group-item" href="/fra/Corrections/">Corrections typographiques et grammaticales</a></li>
</ul>
</li>
<li>
<h3 class="wb-navcurr">Nouvelle pr&eacute;sentation</h3>
<ul class="list-group menu list-unstyled">
<li><a class="list-group-item" href="/fra/PDF/">Nouvelle mise en page des textes l&eacute;gislatifs</a></li>
<li><a class="list-group-item" href="/fra/survey.html">Boutons d'accessibilit&eacute;</a></li>
</ul>
</li>
<li>
<h3 class="wb-navcurr">Recherche</h3>
<ul class="list-group menu list-unstyled">
<li><a class="list-group-item" href="/Recherche/Recherche.aspx" title="Recherche de base - site Web de la l&eacute;gislation">Recherche de base</a></li> 
<li><a class="list-group-item" href="/Recherche/Avancee.aspx" title="Recherche avanc&eacute;e - site Web de la l&eacute;gislation">Recherche avanc&eacute;e</a></li> 
</ul>
</li>
<li>
<h3 class="wb-navcurr">Ressources</h3>
<ul class="list-group menu list-unstyled">
<li><a class="list-group-item" href="/fra/TableauLoisPublic/index.html">Tableau des lois d'int&eacute;r&ecirc;t public et des ministres responsables</a></li> 
<li><a class="list-group-item" href="/fra/TableauLoisPrive/index.html">Tableau des lois d'int&eacute;r&ecirc;t priv&eacute;</a></li> 
<li><a class="list-group-item" href="/fra/IndexTextesReglementaires">Index codifi&eacute; des textes r&eacute;glementaires</a></li> 
<li><a class="list-group-item" href="/fra/IndexationFrais/index.html">Indexation des frais</a></li>
<li><a class="list-group-item" href="/fra/RessourcesConnexes">Ressources connexes</a></li>
</ul>
</li>
<li>
<h3 class="wb-navcurr">Aide</h3>
<ul class="list-group menu list-unstyled">
<li><a class="list-group-item" href="/fra/Accessibilite">Accessibilit&eacute;</a></li>
<li><a class="list-group-item" href="/fra/FAQ" title="Foire aux questions">FAQ</a></li>
<li><a class="list-group-item" href="/fra/AideGenerale">Aide g&eacute;n&eacute;rale</a></li>
<li><a class="list-group-item" href="/fra/AideRecherche">Aide &agrave; la recherche</a></li> 
<li><a class="list-group-item" href="/fra/AidePDF">Aide PDF</a></li> 
<li><a class="list-group-item" href="/fra/GuideLiens">Comment cr&eacute;er des liens stables</a></li> 
<li><a class="list-group-item" href="/fra/Impression">Impression</a></li> 
<li><a class="list-group-item" href="/fra/Glossaire">Glossaire</a></li> 
<li><a class="list-group-item" href="/fra/NoteImportante">Note importante</a></li> 
</ul>
</li>
</ul>
</nav>