<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
DNA Identification Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-173570"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-173573"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-173592"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-173599"><span class="HTitleText1">Principles</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-173610"><span class="HTitleText1">National DNA Data Bank</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-173611"><span class="HTitleText2">Establishment and Contents</span></a>
</li>
<li><span class='sectionRange'>5.5 - </span><a href="#h-173689"><span class="HTitleText2">Comparison of Profiles and Communication and Use of Information</span></a>
</li>
<li><span class='sectionRange'>8.1 - </span><a href="#h-173774"><span class="HTitleText2">Removal of Access to Information</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-173817"><span class="HTitleText2">Storage and Destruction of Bodily Substances</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-173848"><span class="HTitleText2">Offence</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-173855"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-173866"><span class="HTitleText1">Review of Act</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-173871"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>14 to 25 - </span><a href="#h-173879"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-173881"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
