<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le développement commercial et industriel des premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-218578"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-218581"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-218594"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-218668"><span class="HTitleText1">Autres lois</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-218682"><span class="HTitleText1">Limites de responsabilité, moyens de défense et immunités</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-218695"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

