<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Special Areas Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-434190"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-434195"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-434200"><span class="HTitleText1">Special Areas</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-434214"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-434248"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-434258"><span class="HTitleText1">Annual Report</span></a>
</li></ul>
</li></ul>

</nav>

