<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi constituant en corporation la Banque Continentale du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-91412"><span class="HTitleText1">Constitution en corporation et organisation</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-91451"><span class="HTitleText1">Rapport entre la banque et IAC Limitée</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-91498"><span class="HTitleText1">Application de la Loi sur les banques à IAC Limitée</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-91523"><span class="HTitleText1">Activités commerciales de IAC Limitée jusqu’à la fusion</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-2.html#h-91555"><span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-91562"><span class="HTitleText1">Autres matières</span></a>
</li></ul>
</li></ul>

</nav>

