<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Station canadienne de recherche dans l’Extrême-Arctique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Constitution</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Mission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText1">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-8"><span class="HTitleText1">Président du Conseil</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText1">Président de la SCREA</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-10"><span class="HTitleText1">Ressources humaines</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText1">Bureaux et réunions</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-12"><span class="HTitleText1">Règlements administratifs</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-13"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
