<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les océans</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-373822"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-373825"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-373843"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-373846"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Zones maritimes du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-373847"><span class="HTitleText2">Mer territoriale et zone contiguë</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-373892"><span class="HTitleText2">Zone économique exclusive</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-373912"><span class="HTitleText2">Plateau continental</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-373954"><span class="HTitleText2">Compétence juridictionnelle</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-373968"><span class="HTitleText2">Dispositions diverses</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-373984"><span class="HTitleText2">Règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-374022"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Stratégie de gestion des océans</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-374195"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Attributions du ministre</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-374196"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-374202"><span class="HTitleText2">Garde côtière</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-374219"><span class="HTitleText2">Sciences de la mer</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-374242"><span class="HTitleText2">Facturation</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-374274"><span class="HTitleText1">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>54 et 55 - </span><a href="#h-374276"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>56 à 108 - </span><a href="#h-374278"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-374280"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
