<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Journée du Parcours vers la liberté</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-328225"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-328228"><span class="HTitleText1">Journée du Parcours vers la liberté</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
