<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant la taxe sur les produits et services des premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Application d’autres lois fédérales</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Texte législatif concernant la taxe sur les produits et services d’une première nation</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-5"><span class="HTitleText1">Texte législatif autochtone édicté en vertu d’un pouvoir distinct</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">Accord d’application et partie IX de la Loi sur la taxe d’accise</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-7"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-9"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
