<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Office de surveillance des activités en matière de sécurité nationale et de renseignement</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1156051"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1156054"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1156074"><span class="HTitleText1">Constitution et composition de l’Office de surveillance</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-1156110"><span class="HTitleText1">Mandat</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-1156133"><span class="HTitleText1">Accès à l’information</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-1156156"><span class="HTitleText1">Organisme de surveillance</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="#h-1156169"><span class="HTitleText1">Coordination</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-1156175"><span class="HTitleText1">Plaintes</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-1156209"><span class="HTitleText1">Règlement à l’amiable des plaintes</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-1156215"><span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-1156246"><span class="HTitleText1">Études ministérielles</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-1156252"><span class="HTitleText1">Rapports aux ministres</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-1156285"><span class="HTitleText1">Rapports publics</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-1156301"><span class="HTitleText1">Secrétariat</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-1156344"><span class="HTitleText1">Sécurité et confidentialité</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-1156365"><span class="HTitleText1">Généralités</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-1156368"><span class="HTitleText1">Pouvoirs du gouverneur en conseil</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
