<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Yukon</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-461232"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-461235"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-461251"><span class="HTitleText1">Gouvernement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-461252"><span class="HTitleText2">Pouvoir exécutif</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-461276"><span class="HTitleText2">Pouvoir législatif</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-461277"><span class="HTitleText3">Assemblée législative</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-461298"><span class="HTitleText3">Législature</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-461301"><span class="HTitleText3">Compétence législative</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-461410"><span class="HTitleText2">Trésor du Yukon</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-461420"><span class="HTitleText2">Comptes du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>38 - </span><a href="#h-461460"><span class="HTitleText1">Administration de la justice</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-461461"><span class="HTitleText2">Organisation judiciaire</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-461466"><span class="HTitleText2">Cour suprême du Yukon</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-461487"><span class="HTitleText2">Cour d’appel du Yukon</span></a>
</li></ul>
</li><li><span class='sectionRange'>45 - </span><a href="#h-461490"><span class="HTitleText1">Biens réels, eaux et ressources pétrolières et gazières</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-461491"><span class="HTitleText2">Gestion et maîtrise</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-461515"><span class="HTitleText2">Restrictions</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-461549"><span class="HTitleText1">Exercice de pouvoirs fédéraux</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-461563"><span class="HTitleText1">Modification législative</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-461569"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>68 à 76 - </span><a href="#h-461637"><span class="HTitleText1">Modifications apportées à la présente loi</span></a>
</li>
<li><span class='sectionRange'>77 à 271 - </span><a href="#h-461639"><span class="HTitleText1">Modifications apportées à d’autres lois</span></a>
</li>
<li><span class='sectionRange'>272 à 278 - </span><a href="#h-461641"><span class="HTitleText1">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>279 à 284 - </span><a href="#h-461643"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>285 - </span><a href="#h-461645"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-461654"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Délimitation du territoire</span></a>
</li>
<li><a href="#h-461657"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Limite septentrionale de la zone adjacente</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
