<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Jobs and Economic Growth Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-334221"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-334224"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the Income Tax Act and Related Acts and Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-334225"><span class="HTitleText2">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-334247"><span class="HTitleText2">Income Tax Regulations</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-334251"><span class="HTitleText2">Canada Disability Savings Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-1.html#h-334255"><span class="HTitleText2">Canada Disability Savings Regulations</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-1.html#h-334257"><span class="HTitleText2">Canada Education Savings Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-1.html#h-334260"><span class="HTitleText2">Canada Education Savings Regulations</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-1.html#h-334263"><span class="HTitleText2">Canada Pension Plan Regulations</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-1.html#h-334265"><span class="HTitleText2">Insurable Earnings and Collection of Premiums Regulations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-1.html#h-334267"><span class="HTitleText2">Regulations Excluding Certain Indictable Offences from the Definition of “Designated Offence”</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="page-1.html#h-334269"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Amendments in Respect of Excise Duties and Sales and Excise Taxes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>37 - </span><a href="page-1.html#h-334270"><span class="HTitleText2">Excise Act</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-1.html#h-334272"><span class="HTitleText2">Amendments in Respect of the Excise Act, 2001</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="page-1.html#h-334273"><span class="HTitleText3">Excise Act, 2001</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-1.html#h-334284"><span class="HTitleText3">Customs Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-1.html#h-334291"><span class="HTitleText3">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>55 - </span><a href="page-1.html#h-334293"><span class="HTitleText2">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-1.html#h-334329"><span class="HTitleText2">Health Care Services (GST/HST) Regulations</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="page-1.html#h-334331"><span class="HTitleText2">Input Tax Credit Allocation Methods (GST/HST) Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="page-1.html#h-334332"><span class="HTitleText3">Making of Regulations</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="page-1.html#h-334336"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>93 - </span><a href="page-1.html#h-334339"><span class="HTitleText2">Interest Rates (Excise Act, 2001) Regulations</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="page-1.html#h-334341"><span class="HTitleText2">Interest Rates (Excise Tax Act) Regulations</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-1.html#h-334343"><span class="HTitleText2">Coordinating Amendment</span></a>
</li></ul>
</li><li><span class='sectionRange'>96 - </span><a href="page-1.html#h-334345"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Amendments in Respect of the Air Travellers Security Charge</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>96 - </span><a href="page-1.html#h-334346"><span class="HTitleText2">Air Travellers Security Charge Act</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="page-1.html#h-334348"><span class="HTitleText2">Interest Rates (Air Travellers Security Charge Act) Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="page-1.html#h-334350"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Softwood Lumber Products Export Charge Act, 2006</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>98 - </span><a href="page-1.html#h-334351"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="page-1.html#h-334357"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 to 1644 - </span><a href="page-1.html#h-334363"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Customs Tariff</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 to 1644 - </span><a href="page-1.html#h-334364"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1645 - </span><a href="page-1.html#h-334366"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1646 - </span><a href="page-1.html#h-334369"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Federal-Provincial Fiscal Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>1649 - </span><a href="page-1.html#h-334373"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Expenditure Restraint Act</span></a>
</li>
<li><span class='sectionRange'>1650 - </span><a href="page-1.html#h-334375"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Amendments Relating to Certain Governmental Bodies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="page-1.html#h-334376"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2">Amendments Relating to Certain Governor in Council Appointments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="page-1.html#h-334377"><span class="HTitleText3">Alberta-British Columbia Boundary Act, 1974</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1650 - </span><a href="page-1.html#h-334378"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1653 - </span><a href="page-1.html#h-334382"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1654 - </span><a href="page-1.html#h-334385"><span class="HTitleText3">Asia-Pacific Foundation of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1654 - </span><a href="page-1.html#h-334386"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1655 - </span><a href="page-1.html#h-334388"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1656 - </span><a href="page-1.html#h-334391"><span class="HTitleText3">Assisted Human Reproduction Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1656 - </span><a href="page-1.html#h-334392"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1657 - </span><a href="page-1.html#h-334394"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1658 - </span><a href="page-1.html#h-334397"><span class="HTitleText3">Budget Implementation Act, 1997</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1658 - </span><a href="page-1.html#h-334398"><span class="HTitleText4">Amendment to the Act (Canada Foundation for Innovation)</span></a>
</li>
<li><span class='sectionRange'>1659 - </span><a href="page-1.html#h-334400"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1660 - </span><a href="page-2.html#h-334403"><span class="HTitleText3">Business Development Bank of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1660 - </span><a href="page-2.html#h-334404"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1661 - </span><a href="page-2.html#h-334406"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1662 - </span><a href="page-2.html#h-334409"><span class="HTitleText3">Canada Grain Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1662 - </span><a href="page-2.html#h-334410"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1664 - </span><a href="page-2.html#h-334413"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1665 - </span><a href="page-2.html#h-334416"><span class="HTitleText3">Canada Mortgage and Housing Corporation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1665 - </span><a href="page-2.html#h-334417"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1667 - </span><a href="page-2.html#h-334420"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1668 - </span><a href="page-2.html#h-334423"><span class="HTitleText3">Canada Pension Plan</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1668 - </span><a href="page-2.html#h-334424"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1670 - </span><a href="page-2.html#h-334427"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1671 - </span><a href="page-2.html#h-334430"><span class="HTitleText3">Canada School of Public Service Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1671 - </span><a href="page-2.html#h-334431"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1674 - </span><a href="page-2.html#h-334435"><span class="HTitleText4">Related Amendment to the Access to Information Act</span></a>
</li>
<li><span class='sectionRange'>1675 - </span><a href="page-2.html#h-334437"><span class="HTitleText4">Related Amendments to the Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>1676 - </span><a href="page-2.html#h-334439"><span class="HTitleText4">Related Amendment to the Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>1677 - </span><a href="page-2.html#h-334441"><span class="HTitleText4">Related Amendment to the Privacy Act</span></a>
</li>
<li><span class='sectionRange'>1678 - </span><a href="page-2.html#h-334443"><span class="HTitleText4">Related Amendments to the Public Servants Disclosure Protection Act</span></a>
</li>
<li><span class='sectionRange'>1683 - </span><a href="page-2.html#h-334449"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1684 - </span><a href="page-2.html#h-334452"><span class="HTitleText3">Canadian Centre for Occupational Health and Safety Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1684 - </span><a href="page-2.html#h-334453"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1686 - </span><a href="page-2.html#h-334456"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1687 - </span><a href="page-2.html#h-334459"><span class="HTitleText3">Canadian Centre on Substance Abuse Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1687 - </span><a href="page-2.html#h-334460"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1692 - </span><a href="page-2.html#h-334466"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1693 - </span><a href="page-2.html#h-334469"><span class="HTitleText3">Canadian Institutes of Health Research Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1693 - </span><a href="page-2.html#h-334470"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1694 - </span><a href="page-2.html#h-334472"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1695 - </span><a href="page-2.html#h-334475"><span class="HTitleText3">Canadian International Trade Tribunal Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1695 - </span><a href="page-2.html#h-334476"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1696 - </span><a href="page-2.html#h-334478"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1697 - </span><a href="page-2.html#h-334481"><span class="HTitleText3">Canadian Race Relations Foundation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1697 - </span><a href="page-2.html#h-334482"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1699 - </span><a href="page-2.html#h-334485"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1700 - </span><a href="page-2.html#h-334488"><span class="HTitleText3">Canadian Radio-television and Telecommunications Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1700 - </span><a href="page-2.html#h-334489"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1710 - </span><a href="page-2.html#h-334500"><span class="HTitleText4">Consequential Amendment to the Broadcasting Act</span></a>
</li>
<li><span class='sectionRange'>1711 - </span><a href="page-2.html#h-334502"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1712 - </span><a href="page-2.html#h-334505"><span class="HTitleText3">Canadian Space Agency Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1712 - </span><a href="page-2.html#h-334506"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1716 - </span><a href="page-2.html#h-334511"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1717 - </span><a href="page-2.html#h-334514"><span class="HTitleText3">Canadian Tourism Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1717 - </span><a href="page-2.html#h-334515"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1722 - </span><a href="page-2.html#h-334521"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1723 - </span><a href="page-2.html#h-334524"><span class="HTitleText3">Department of Human Resources and Skills Development Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1723 - </span><a href="page-2.html#h-334525"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1724 - </span><a href="page-2.html#h-334527"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1725 - </span><a href="page-2.html#h-334530"><span class="HTitleText3">Energy Supplies Emergency Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1725 - </span><a href="page-2.html#h-334531"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1728 - </span><a href="page-2.html#h-334535"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1729 - </span><a href="page-2.html#h-334538"><span class="HTitleText3">Export Development Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1729 - </span><a href="page-2.html#h-334539"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1730 - </span><a href="page-2.html#h-334541"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1731 - </span><a href="page-2.html#h-334544"><span class="HTitleText3">Farm Products Agencies Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1731 - </span><a href="page-2.html#h-334545"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1732 - </span><a href="page-2.html#h-334547"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1733 - </span><a href="page-2.html#h-334550"><span class="HTitleText3">First Nations Fiscal and Statistical Management Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1733 - </span><a href="page-2.html#h-334551"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1737 - </span><a href="page-2.html#h-334556"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1738 - </span><a href="page-2.html#h-334559"><span class="HTitleText3">Freshwater Fish Marketing Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1738 - </span><a href="page-2.html#h-334560"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1739 - </span><a href="page-2.html#h-334562"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1740 - </span><a href="page-2.html#h-334565"><span class="HTitleText3">Historic Sites and Monuments Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1740 - </span><a href="page-2.html#h-334566"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1742 - </span><a href="page-2.html#h-334569"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1743 - </span><a href="page-2.html#h-334572"><span class="HTitleText3">International Boundary Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1743 - </span><a href="page-2.html#h-334573"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1745 - </span><a href="page-2.html#h-334576"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1746 - </span><a href="page-2.html#h-334579"><span class="HTitleText3">International Development Research Centre Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1746 - </span><a href="page-2.html#h-334580"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1754 - </span><a href="page-3.html#h-334589"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1755 - </span><a href="page-3.html#h-334592"><span class="HTitleText3">National Defence Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1755 - </span><a href="page-3.html#h-334593"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1756 - </span><a href="page-3.html#h-334595"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1757 - </span><a href="page-3.html#h-334598"><span class="HTitleText3">National Research Council Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1757 - </span><a href="page-3.html#h-334599"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1758 - </span><a href="page-3.html#h-334601"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1759 - </span><a href="page-3.html#h-334604"><span class="HTitleText3">National Round Table on the Environment and the Economy Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1759 - </span><a href="page-3.html#h-334605"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1760 - </span><a href="page-3.html#h-334607"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1761 - </span><a href="page-3.html#h-334610"><span class="HTitleText3">Natural Sciences and Engineering Research Council Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1761 - </span><a href="page-3.html#h-334611"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1762 - </span><a href="page-3.html#h-334613"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1763 - </span><a href="page-3.html#h-334616"><span class="HTitleText3">Public Sector Pension Investment Board Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1763 - </span><a href="page-3.html#h-334617"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1764 - </span><a href="page-3.html#h-334619"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1765 - </span><a href="page-3.html#h-334622"><span class="HTitleText3">Roosevelt Campobello International Park Commission Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1765 - </span><a href="page-3.html#h-334623"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1766 - </span><a href="page-3.html#h-334625"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1767 - </span><a href="page-3.html#h-334628"><span class="HTitleText3">Social Sciences and Humanities Research Council Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1767 - </span><a href="page-3.html#h-334629"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1768 - </span><a href="page-3.html#h-334631"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1769 - </span><a href="page-3.html#h-334634"><span class="HTitleText3">Standards Council of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1769 - </span><a href="page-3.html#h-334635"><span class="HTitleText4">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1773 - </span><a href="page-3.html#h-334640"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1774 - </span><a href="page-3.html#h-334643"><span class="HTitleText3">Status of the Artist Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1774 - </span><a href="page-3.html#h-334644"><span class="HTitleText4">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>1775 - </span><a href="page-3.html#h-334646"><span class="HTitleText4">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1776 - </span><a href="page-3.html#h-334649"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">North American Free Trade Agreement Implementation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1776 - </span><a href="page-3.html#h-334650"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1778 - </span><a href="page-3.html#h-334653"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>1779 - </span><a href="page-3.html#h-334655"><span class="HTitleText3">Consequential Amendments to the Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>1782 - </span><a href="page-3.html#h-334659"><span class="HTitleText3">Consequential Amendment to the Special Import Measures Act</span></a>
</li>
<li><span class='sectionRange'>1783 - </span><a href="page-3.html#h-334661"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1784 - </span><a href="page-3.html#h-334664"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2">The Intercolonial and Prince Edward Island Railways Employees’ Provident Fund Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1784 - </span><a href="page-3.html#h-334665"><span class="HTitleText3">Repeal of the Act</span></a>
</li>
<li><span class='sectionRange'>1785 - </span><a href="page-3.html#h-334667"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1786 - </span><a href="page-3.html#h-334670"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Pension Benefits Standards Act, 1985</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1786 - </span><a href="page-3.html#h-334671"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1826 - </span><a href="page-3.html#h-334712"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>1827 - </span><a href="page-3.html#h-334714"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1828 - </span><a href="page-3.html#h-334717"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Agreement on Social Security Between Canada and the Republic of Poland — Retroactive Coming into Force</span></a>
</li>
<li><span class='sectionRange'>1831 - </span><a href="page-3.html#h-334724"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Export Development Act</span></a>
</li>
<li><span class='sectionRange'>1834 - </span><a href="page-3.html#h-334728"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Payment Card Networks</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1834 - </span><a href="page-3.html#h-334729"><span class="HTitleText2">Enactment of Payment Card Networks Act</span></a>
</li>
<li><span class='sectionRange'>1835 - </span><a href="page-3.html#h-334732"><span class="HTitleText2">Related Amendments to the Financial Consumer Agency of Canada Act</span></a>
</li>
<li><span class='sectionRange'>1850 - </span><a href="page-4.html#h-334748"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1851 - </span><a href="page-4.html#h-334751"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Financial Consumer Agency of Canada Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1851 - </span><a href="page-4.html#h-334752"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1858 - </span><a href="page-4.html#h-334760"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1858 - </span><a href="page-4.html#h-334761"><span class="HTitleText3">Bank Act</span></a>
</li>
<li><span class='sectionRange'>1859 - </span><a href="page-4.html#h-334763"><span class="HTitleText3">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>1860 - </span><a href="page-4.html#h-334765"><span class="HTitleText3">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>1861 - </span><a href="page-4.html#h-334767"><span class="HTitleText3">Trust and Loan Companies Act</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>1862 - </span><a href="page-4.html#h-334769"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1862 - </span><a href="page-4.html#h-334770"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1883 - </span><a href="page-4.html#h-334792"><span class="HTitleText2">Consequential Amendment to the Office of the Superintendent of Financial Institutions act</span></a>
</li>
<li><span class='sectionRange'>1884 - </span><a href="page-4.html#h-334794"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1885 - </span><a href="page-4.html#h-334799"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Canada Post Corporation Act</span></a>
</li>
<li><span class='sectionRange'>1886 - </span><a href="page-4.html#h-334801"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">Canada Deposit Insurance Corporation Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1886 - </span><a href="page-4.html#h-334802"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>1893 - </span><a href="page-4.html#h-334810"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>1894 - </span><a href="page-4.html#h-334813"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">Federal Credit Unions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>1894 - </span><a href="page-4.html#h-334814"><span class="HTitleText2">Bank Act</span></a>
</li>
<li><span class='sectionRange'>2094 - </span><a href="page-5.html#h-335015"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Deposit Insurance Corporation Act</cite></span></a>
</li>
<li><span class='sectionRange'>2108 - </span><a href="page-5.html#h-335030"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>2110 - </span><a href="page-5.html#h-335033"><span class="HTitleText2">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2110 - </span><a href="page-5.html#h-335034"><span class="HTitleText3"><cite class="XRefExternalAct">Bank of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>2113 - </span><a href="page-5.html#h-335038"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Cooperatives Act</cite></span></a>
</li>
<li><span class='sectionRange'>2114 - </span><a href="page-5.html#h-335040"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li>
<li><span class='sectionRange'>2116 - </span><a href="page-5.html#h-335043"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Consumer Agency of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>2117 - </span><a href="page-5.html#h-335045"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>2122 - </span><a href="page-5.html#h-335051"><span class="HTitleText3"><cite class="XRefExternalAct">Office of the Superintendent of Financial Institutions Act</cite></span></a>
</li>
<li><span class='sectionRange'>2123 - </span><a href="page-5.html#h-335053"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>2126 - </span><a href="page-5.html#h-335057"><span class="HTitleText3"><cite class="XRefExternalAct">Winding-up and Restructuring Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>2135 - </span><a href="page-5.html#h-335067"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>2136 - </span><a href="page-5.html#h-335069"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>2137 - </span><a href="page-5.html#h-335072"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">Atomic Energy of Canada Limited</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2137 - </span><a href="page-5.html#h-335073"><span class="HTitleText2">Reorganization and Divestiture</span></a>
</li>
<li><span class='sectionRange'>2147 - </span><a href="page-6.html#h-335156"><span class="HTitleText2">Canadian Nuclear Laboratories Ltd.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2148.1 - </span><a href="page-6.html#h-335176"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>2149 - </span><a href="page-6.html#h-335178"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">Participant Funding Programs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2149 - </span><a href="page-6.html#h-335179"><span class="HTitleText2">National Energy Board Act</span></a>
</li>
<li><span class='sectionRange'>2150 - </span><a href="page-6.html#h-335181"><span class="HTitleText2">Nuclear Safety and Control Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>2152 - </span><a href="page-6.html#h-335184"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">Environmental Assessment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2152 - </span><a href="page-6.html#h-335185"><span class="HTitleText2">Canadian Environmental Assessment Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2152 - </span><a href="page-6.html#h-335186"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>2162 - </span><a href="page-6.html#h-335197"><span class="HTitleText3">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>2164 - </span><a href="page-6.html#h-335200"><span class="HTitleText2">Exclusion List Regulations, 2007</span></a>
</li>
<li><span class='sectionRange'>2167 - </span><a href="page-6.html#h-335204"><span class="HTitleText2">Regulations Amending the Exclusion List Regulations, 2007</span></a>
</li>
<li><span class='sectionRange'>2171 - </span><a href="page-6.html#h-335209"><span class="HTitleText2">Infrastructure Projects Environmental Assessment Adaptation Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>2172 - </span><a href="page-6.html#h-335211"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">Canada Labour Code</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2172 - </span><a href="page-6.html#h-335212"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>2178 - </span><a href="page-6.html#h-335219"><span class="HTitleText2">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>2179 - </span><a href="page-6.html#h-335221"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>2180 - </span><a href="page-6.html#h-335224"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">Payments to Certain Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2180 - </span><a href="page-6.html#h-335225"><span class="HTitleText2">Canadian Youth Business Foundation</span></a>
</li>
<li><span class='sectionRange'>2181 - </span><a href="page-6.html#h-335228"><span class="HTitleText2">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>2182 - </span><a href="page-6.html#h-335231"><span class="HTitleText2">Pathways to Education Canada</span></a>
</li>
<li><span class='sectionRange'>2183 - </span><a href="page-6.html#h-335234"><span class="HTitleText2">Rick Hansen Foundation</span></a>
</li></ul>
</li><li><span class='sectionRange'>2184 - </span><a href="page-6.html#h-335237"><span class="HLabel1">PART 23</span> - <span class="HTitleText1">Telecommunications Act</span></a>
</li>
<li><span class='sectionRange'>2185 - </span><a href="page-6.html#h-335239"><span class="HLabel1">PART 24</span> - <span class="HTitleText1">Employment Insurance Financing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2185 - </span><a href="page-6.html#h-335240"><span class="HTitleText2">Employment Insurance Act</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2185 - </span><a href="page-6.html#h-335241"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>2195 - </span><a href="page-7.html#h-335252"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>2201 - </span><a href="page-7.html#h-335259"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2201 - </span><a href="page-7.html#h-335260"><span class="HTitleText4"><cite class="XRefExternalAct">Department of Human Resources and Skills Development Act</cite></span></a>
</li>
<li><span class='sectionRange'>2202 - </span><a href="page-7.html#h-335262"><span class="HTitleText4"><cite class="XRefExternalRegulation">Employment Insurance Regulations</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>2204 - </span><a href="page-7.html#h-335265"><span class="HTitleText2">Budget Implementation Act, 2008</span></a>
</li>
<li><span class='sectionRange'>2207 - </span><a href="page-7.html#h-335269"><span class="HTitleText2">Canada Employment Insurance Financing Board Act</span></a>
</li>
<li><span class='sectionRange'>2208 - </span><a href="page-7.html#h-335271"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-8.html#h-335279"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-9.html#h-335282"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-10.html#h-335285"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li></ul>
</li></ul>

</nav>

