<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Cooperatives Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-44933"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-44936"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Interpretation and Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-44937"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-45018"><span class="HTitleText2">Purpose and Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-45063"><span class="HTitleText2">Share Ownership</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-45068"><span class="HTitleText2">Cooperative Basis</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-45093"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Incorporation, Structure and Organization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-45094"><span class="HTitleText2">Incorporators</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-45105"><span class="HTitleText2">Capital Structure</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-45108"><span class="HTitleText2">Application for Incorporation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-45118"><span class="HTitleText2">Articles of Incorporation</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-45145"><span class="HTitleText2">Incorporation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-45159"><span class="HTitleText2">By-laws</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-45203"><span class="HTitleText2">Cooperative Basis</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-45211"><span class="HTitleText2">Pre-incorporation Contracts</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-45227"><span class="HTitleText2">Name</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-45265"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Capacity and Powers</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-45300"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Registered Office and Records</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30 - </span><a href="#h-45301"><span class="HTitleText2">Registered Office</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-45313"><span class="HTitleText2">Records</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-45357"><span class="HTitleText2">Lists</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-45377"><span class="HTitleText2">Corporate Seal</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-45385"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Membership</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-45386"><span class="HTitleText2">Conditions for Membership</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-45409"><span class="HTitleText2">Withdrawal from Membership</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-45423"><span class="HTitleText2">Termination of Membership</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-45445"><span class="HTitleText2">Limitation</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-45448"><span class="HTitleText2">Termination of Membership by Members</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-45451"><span class="HTitleText2">Other Terminations</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-45469"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Corporate Governance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>48 - </span><a href="#h-45470"><span class="HTitleText2">Meetings</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-45563"><span class="HTitleText2">Proposals</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-45610"><span class="HTitleText2">Lists</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-45633"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-45675"><span class="HTitleText2">Requisitions</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-45696"><span class="HTitleText2">Other Methods of Calling Meetings</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-45719"><span class="HTitleText2">By-laws</span></a>
</li></ul>
</li><li><span class='sectionRange'>76 - </span><a href="#h-45740"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Directors and Officers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-45741"><span class="HTitleText2">General Provisions</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-45939"><span class="HTitleText2">Liability</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-45990"><span class="HTitleText2">Conflict of Interests</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-46050"><span class="HTitleText2">Officers</span></a>
</li></ul>
</li><li><span class='sectionRange'>116 - </span><a href="#h-46146"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Capital Structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>116 - </span><a href="#h-46147"><span class="HTitleText2">Membership Capital</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-46167"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-46206"><span class="HTitleText2">Investment Shares</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-46269"><span class="HTitleText2">Constraints</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-46372"><span class="HTitleText2">Corporate Finance</span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-46566"><span class="HTitleText2">Marketing</span></a>
</li></ul>
</li><li><span class='sectionRange'>163 - </span><a href="#h-46585"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Proxies</span></a>
</li>
<li><span class='sectionRange'>171 - </span><a href="#h-46702"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Insider Trading</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-46785"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Compulsory Acquisition</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-46877"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Security Certificates, Registers and Transfers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>177 - </span><a href="#h-46878"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-46923"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>179 - </span><a href="#h-46926"><span class="HTitleText2">Security Certificates</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-47000"><span class="HTitleText2">Registers</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-47065"><span class="HTitleText2">Proceedings</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-47072"><span class="HTitleText2">Delivery</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-47083"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>247 - </span><a href="#h-47356"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Financial Disclosure</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="#h-47530"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Trust Indentures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>266 - </span><a href="#h-47531"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>267 - </span><a href="#h-47541"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-47549"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>278 - </span><a href="#h-47616"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Receivers, Receiver-managers and Sequestrators</span></a>
</li>
<li><span class='sectionRange'>284 - </span><a href="#h-47661"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">Fundamental Changes</span></a>
</li>
<li><span class='sectionRange'>306 - </span><a href="#h-48067"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">Liquidation and Dissolution</span></a>
</li>
<li><span class='sectionRange'>329 - </span><a href="#h-48374"><span class="HLabel1">PART 18</span> - <span class="HTitleText1">Investigations</span></a>
</li>
<li><span class='sectionRange'>337.1 - </span><a href="#h-48457"><span class="HLabel1">PART 18.1</span> - <span class="HTitleText1">Apportioning Award of Damages</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>337.1 - </span><a href="#h-48458"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>337.3 - </span><a href="#h-48487"><span class="HTitleText2">Apportionment of Damages</span></a>
</li>
<li><span class='sectionRange'>337.5 - </span><a href="#h-48506"><span class="HTitleText2">Joint and Several, or Solidary, Liability</span></a>
</li></ul>
</li><li><span class='sectionRange'>338 - </span><a href="#h-48556"><span class="HLabel1">PART 19</span> - <span class="HTitleText1">Remedies, Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>352 - </span><a href="#h-48696"><span class="HLabel1">PART 20</span> - <span class="HTitleText1">Additional Provisions Respecting Non-profit Housing Cooperatives</span></a>
</li>
<li><span class='sectionRange'>359 - </span><a href="#h-48765"><span class="HLabel1">PART 21</span> - <span class="HTitleText1">Additional Provisions Respecting Worker Cooperatives</span></a>
</li>
<li><span class='sectionRange'>361.1 - </span><a href="#h-48808"><span class="HLabel1">PART 21.1</span> - <span class="HTitleText1">Documents in Electronic or Other Form</span></a>
</li>
<li><span class='sectionRange'>362 - </span><a href="#h-48870"><span class="HLabel1">PART 22</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>362 - </span><a href="#h-48871"><span class="HTitleText2">Notices</span></a>
</li>
<li><span class='sectionRange'>365 - </span><a href="#h-48895"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>367 - </span><a href="#h-48913"><span class="HTitleText2">Notices and Documents</span></a>
</li>
<li><span class='sectionRange'>371 - </span><a href="#h-48941"><span class="HTitleText2">Appointment of Director</span></a>
</li>
<li><span class='sectionRange'>372 - </span><a href="#h-48944"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>373 - </span><a href="#h-48969"><span class="HTitleText2">Statements</span></a>
</li>
<li><span class='sectionRange'>378 - </span><a href="#h-49056"><span class="HTitleText2">Records</span></a>
</li></ul>
</li><li><span class='sectionRange'>379 - </span><a href="#h-49070"><span class="HLabel1">PART 23</span> - <span class="HTitleText1">Continuance</span></a>
</li>
<li><span class='sectionRange'>380 to 384 - </span><a href="#h-49083"><span class="HLabel1">PART 24</span> - <span class="HTitleText1">Consequential Amendments, Repeal and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>380 to 384 - </span><a href="#h-49084"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>385 - </span><a href="#h-49086"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>386 - </span><a href="#h-49088"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
