<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Indigenous Services Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1169251"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1169254"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1169262"><span class="HTitleText1">Establishment of Department</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1169269"><span class="HTitleText1">Powers, Duties and Functions of Minister</span></a>
</li></ul>
</li></ul>

</nav>

