<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le fonctionnement des sociétés du secteur public</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-245508"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-245513"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-245518"><span class="HTitleText1">Pouvoirs de la société et personnel</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-245549"><span class="HTitleText1">Champ d’application</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
