<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les prestations canadiennes de relance économique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1248554"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1248557"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1248566"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Prestation canadienne de relance économique</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-1248646"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Prestation canadienne de maladie pour la relance économique</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1248693"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Prestation canadienne de relance économique pour les proches aidants</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-1248757"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-1248885"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-1248886"><span class="HTitleText2"><cite class="XRefExternalAct">Loi de l’impôt sur le revenu</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-1248897"><span class="HTitleText2"><cite class="XRefExternalRegulation">Règlement de l’impôt sur le revenu</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
