<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Naskapi and the Cree-Naskapi Commission Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-112662"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-112667"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-112719"><span class="HTitleText1">Inconsistency with Federal or Provincial Law</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-112727"><span class="HTitleText1">Application of Indian Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-112732"><span class="HTitleText1">Band By-laws and Resolutions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-112754"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-112759"><span class="HTitleText1">Incorporation by Reference of Provincial Laws</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-112771"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Local Government</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="page-1.html#h-112772"><span class="HTitleText2">Band Name</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-112795"><span class="HTitleText2">Membership of Band</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-2.html#h-112810"><span class="HTitleText2">Objects and Powers of Band</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-112847"><span class="HTitleText2">Head Office of Band</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-2.html#h-112852"><span class="HTitleText2">Band Council</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-2.html#h-112876"><span class="HTitleText2">Council Meetings</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="page-2.html#h-112947"><span class="HTitleText2">Committees of a Council</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-112959"><span class="HTitleText2">Band Bodies, Officers, Employees and Agents</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-3.html#h-112992"><span class="HTitleText2">By-laws Respecting Local Government</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-113094"><span class="HTitleText2">Procedure for Making By-Laws and Resolutions</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-4.html#h-113139"><span class="HTitleText2">Challenges to By-Laws or Resolutions</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-4.html#h-113154"><span class="HTitleText2">Transitional</span></a>
</li></ul>
</li><li><span class='sectionRange'>63 - </span><a href="page-4.html#h-113180"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Band Elections</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64 - </span><a href="page-4.html#h-113188"><span class="HTitleText2">Election By-laws</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="page-4.html#h-113226"><span class="HTitleText2">Eligibility to be Elected and to Serve as Council Member</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-4.html#h-113257"><span class="HTitleText2">Returning Officers</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="page-5.html#h-113281"><span class="HTitleText2">Calling of Elections</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-5.html#h-113326"><span class="HTitleText2">Contestation of election results</span></a>
</li></ul>
</li><li><span class='sectionRange'>79 - </span><a href="page-5.html#h-113351"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Meetings and Referenda of the Band</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="page-5.html#h-113362"><span class="HTitleText2">Ordinary Band Meetings</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-5.html#h-113370"><span class="HTitleText2">Special Band Meetings and Referenda</span></a>
</li></ul>
</li><li><span class='sectionRange'>89 - </span><a href="page-5.html#h-113411"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Financial Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>93 - </span><a href="page-6.html#h-113474"><span class="HTitleText2">Audit</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="page-6.html#h-113510"><span class="HTitleText2">Borrowing Powers of Band</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="page-6.html#h-113540"><span class="HTitleText2">Contracts</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="page-6.html#h-113545"><span class="HTitleText2">Appointment of Administrator</span></a>
</li></ul>
</li><li><span class='sectionRange'>101 - </span><a href="page-6.html#h-113563"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Residence and Access Rights on Category IA-N Land</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="page-6.html#h-113575"><span class="HTitleText2">Residence Rights</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="page-7.html#h-113596"><span class="HTitleText2">Access Rights</span></a>
</li></ul>
</li><li><span class='sectionRange'>109 - </span><a href="page-7.html#h-113632"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Rights of Band, Quebec and Others in Relation to Category IA-N Land</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>110 - </span><a href="page-7.html#h-113640"><span class="HTitleText2">Soapstone Deposits</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="page-7.html#h-113645"><span class="HTitleText2">Forest Resources</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="page-7.html#h-113655"><span class="HTitleText2">Gravel</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="page-7.html#h-113660"><span class="HTitleText2">Mineral, Subsurface and Mining Rights</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="page-7.html#h-113695"><span class="HTitleText2">Pre-Existing Rights and Interests on Category IA-N Land</span></a>
</li></ul>
</li><li><span class='sectionRange'>118 - </span><a href="page-7.html#h-113718"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Expropriation of Category IA-N Land by Quebec</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="page-8.html#h-113837"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Dispositions of Rights and Interests in Category IA-N Land and Buildings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="page-9.html#h-113899"><span class="HTitleText2">Superficie</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="page-9.html#h-113923"><span class="HTitleText2">Subsequent Transfers of Rights or Interests</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="page-9.html#h-113933"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="page-9.html#h-113950"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Cessions by Band</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="page-10.html#h-114018"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Land Registry System</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="page-10.html#h-114059"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Expropriation by Band</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="page-10.html#h-114085"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Cree-Naskapi Commission</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="page-11.html#h-114194"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Successions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>181 - </span><a href="page-11.html#h-114250"><span class="HTitleText2">Disposition of Traditional Property on an Intestacy</span></a>
</li></ul>
</li><li><span class='sectionRange'>187 - </span><a href="page-11.html#h-114291"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Tax Exemptions</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="page-11.html#h-114316"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">Seizure Exemptions</span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="page-12.html#h-114363"><span class="HLabel1">PART XVI</span> - <span class="HTitleText1">Policing</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="page-12.html#h-114384"><span class="HLabel1">PART XVII</span> - <span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="page-12.html#h-114407"><span class="HLabel1">PART XVIII</span> - <span class="HTitleText1">Administration of Justice</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-12.html#h-114419"><span class="HLabel1">PART XIX</span> - <span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>204 to 217 - </span><a href="page-12.html#h-114440"><span class="HLabel1">PART XX</span> - <span class="HTitleText1">Consequential Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>218 - </span><a href="page-12.html#h-114442"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

