<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi relative aux répercussions du projet gazier Mackenzie</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Constitution de la société</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HTitleText1">Administrateurs</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-5"><span class="HTitleText1">Personnel</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HTitleText1">Opérations</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-7"><span class="HTitleText1">Liquidation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-8"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-9"><span class="HTitleText1">Modification de l’annexe</span></a>
</li>
<li><a href="#h-10"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Organisations régionales</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
