<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le divorce</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-168588"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-168591"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-168638"><span class="HTitleText1">Compétence</span></a>
</li>
<li><span class='sectionRange'>7.1 - </span><a href="#h-1274323"><span class="HTitleText1">Obligations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7.1 - </span><a href="#h-1274324"><span class="HTitleText2">Parties à une instance</span></a>
</li>
<li><span class='sectionRange'>7.7 - </span><a href="#h-1274349"><span class="HTitleText2">Conseiller juridique</span></a>
</li>
<li><span class='sectionRange'>7.8 - </span><a href="#h-1274364"><span class="HTitleText2">Tribunal</span></a>
</li></ul>
</li><li><span class='sectionRange'>8 - </span><a href="#h-168681"><span class="HTitleText1">Divorce</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-168758"><span class="HTitleText1">Mesures accessoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15.1 - </span><a href="#h-168764"><span class="HTitleText2">Ordonnances alimentaires au profit d’un enfant</span></a>
</li>
<li><span class='sectionRange'>15.2 - </span><a href="#h-168786"><span class="HTitleText2">Ordonnances alimentaires au profit d’un époux</span></a>
</li>
<li><span class='sectionRange'>15.3 - </span><a href="#h-168809"><span class="HTitleText2">Priorité</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-168819"><span class="HTitleText2">Intérêt de l’enfant</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-1274430"><span class="HTitleText2">Ordonnances parentales</span></a>
</li>
<li><span class='sectionRange'>16.5 - </span><a href="#h-1274473"><span class="HTitleText2">Ordonnances de contact</span></a>
</li>
<li><span class='sectionRange'>16.6 - </span><a href="#h-1274497"><span class="HTitleText2">Plan parental</span></a>
</li>
<li><span class='sectionRange'>16.7 - </span><a href="#h-1274505"><span class="HTitleText2">Changement du lieu de résidence</span></a>
</li>
<li><span class='sectionRange'>16.9 - </span><a href="#h-1274523"><span class="HTitleText2">Déménagement important</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-168841"><span class="HTitleText2">Modification, annulation ou suspension des ordonnances</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-168894"><span class="HTitleText2">Actions interprovinciales et internationales en obtention, modification, annulation ou suspension d’ordonnances alimentaires ou en reconnaissance de décisions d’États désignés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-1274628"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-1274636"><span class="HTitleText3">Actions interprovinciales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18.1 - </span><a href="#h-1274637"><span class="HTitleText4">Réception et transmission de demandes</span></a>
</li>
<li><span class='sectionRange'>18.2 - </span><a href="#h-1274677"><span class="HTitleText4">Conversion de demandes</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-1274700"><span class="HTitleText3">Actions internationales – États désignés</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-1274701"><span class="HTitleText4">Réception et transmission des demandes d’États désignés</span></a>
</li>
<li><span class='sectionRange'>19.1 - </span><a href="#h-1274737"><span class="HTitleText4">Reconnaissance de décisions d’un État désigné</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>20 - </span><a href="#h-1274748"><span class="HTitleText2">Validité, exécution et respect des ordonnances et cession de créances</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-168984"><span class="HTitleText1">Appels</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-169002"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-169118"><span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>33 - </span><a href="#h-169121"><span class="HTitleText2">Loi sur le divorce, S.R. 1970, ch. D-8</span></a>
</li>
<li><span class='sectionRange'>35.1 - </span><a href="#h-169139"><span class="HTitleText2">Loi sur le divorce, L.R. ch. 3 (2<sup>e</sup> suppl.)</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-169149"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
