<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Gendarmerie royale du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-410936"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-410941"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-410965"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Constitution et organisation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>3 - </span><a href="#h-410966"><span class="HTitleText2">Composition de la Gendarmerie</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-410975"><span class="HTitleText2">Commissaire</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-410983"><span class="HTitleText2">Officiers et membres</span></a>
</li>
<li><span class='sectionRange'>9.1 - </span><a href="#h-411032"><span class="HTitleText2">Qualités requises</span></a>
</li>
<li><span class='sectionRange'>9.2 - </span><a href="#h-411040"><span class="HTitleText2">Révocation</span></a>
</li>
<li><span class='sectionRange'>9.3 - </span><a href="#h-411045"><span class="HTitleText2">Stagiaires</span></a>
</li>
<li><span class='sectionRange'>9.5 - </span><a href="#h-411060"><span class="HTitleText2">Démission</span></a>
</li>
<li><span class='sectionRange'>9.6 - </span><a href="#h-411065"><span class="HTitleText2">Gendarmes spéciaux</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-411075"><span class="HTitleText2">Personnel civil</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-411080"><span class="HTitleText2">Réserve</span></a>
</li>
<li><span class='sectionRange'>11.1 - </span><a href="#h-411090"><span class="HTitleText2">Agents de la paix</span></a>
</li>
<li><span class='sectionRange'>11.2 - </span><a href="#h-411100"><span class="HTitleText2">Certificats</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-411110"><span class="HTitleText2">Suspension</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-411116"><span class="HTitleText2">Quartier général</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-411121"><span class="HTitleText2">Serments</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-411129"><span class="HTitleText2">Intérim du commissaire</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-411139"><span class="HTitleText2">Fonctions</span></a>
</li>
<li><span class='sectionRange'>20.1 - </span><a href="#h-411162"><span class="HTitleText2">Gestion des ressources humaines</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-411192"><span class="HTitleText2">Règlements et règles</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-411220"><span class="HTitleText2">Solde et indemnités</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-411238"><span class="HTitleText2">Caisse fiduciaire de bienfaisance</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-411254"><span class="HTitleText2">Destination des biens recueillis</span></a>
</li>
<li><span class='sectionRange'>24.1 - </span><a href="#h-411262"><span class="HTitleText2">Commissions d’enquête</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-411300"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Comité externe d’examen de la Gendarmerie royale du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-411301"><span class="HTitleText2">Constitution et organisation du Comité</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-411343"><span class="HTitleText2">Fonctions</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-411355"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-411364"><span class="HTitleText2">Rapport annuel</span></a>
</li></ul>
</li><li><span class='sectionRange'>30.1 - </span><a href="#h-411372"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Griefs</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>30.1 - </span><a href="#h-411373"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>30.2 - </span><a href="#h-411378"><span class="HTitleText2">Gestion des conflits</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-411383"><span class="HTitleText2">Présentation des griefs</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-411430"><span class="HTitleText2">Renvoi devant le Comité</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-411494"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>36.1 - </span><a href="#h-411501"><span class="HTitleText2">Recommandation de licencier un sous-commissaire</span></a>
</li></ul>
</li><li><span class='sectionRange'>36.2 - </span><a href="#h-411506"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Déontologie</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36.2 - </span><a href="#h-411507"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-411517"><span class="HTitleText2">Responsabilités</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-411530"><span class="HTitleText2">Code de déontologie</span></a>
</li>
<li><span class='sectionRange'>39.1 - </span><a href="#h-411544"><span class="HTitleText2">Enquête</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-411666"><span class="HTitleText2">Comités de déontologie</span></a>
</li>
<li><span class='sectionRange'>45.1 - </span><a href="#h-411711"><span class="HTitleText2">Audience</span></a>
</li>
<li><span class='sectionRange'>45.11 - </span><a href="#h-411739"><span class="HTitleText2">Appel</span></a>
</li>
<li><span class='sectionRange'>45.171 - </span><a href="#h-411811"><span class="HTitleText2">Avis</span></a>
</li></ul>
</li><li><span class='sectionRange'>45.18 - </span><a href="#h-411824"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">[Abrogée, 2013, ch. 18, art. 33]</span></a>
</li>
<li><span class='sectionRange'>45.29 - </span><a href="#h-411836"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Commission civile d’examen et de traitement des plaintes relatives à la Gendarmerie royale du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45.29 - </span><a href="#h-411837"><span class="HTitleText2">Constitution et organisation</span></a>
</li>
<li><span class='sectionRange'>45.33 - </span><a href="#h-411888"><span class="HTitleText2">Pouvoirs et fonctions</span></a>
</li>
<li><span class='sectionRange'>45.39 - </span><a href="#h-411934"><span class="HTitleText2">Dispositions relatives aux renseignements</span></a>
</li>
<li><span class='sectionRange'>45.49 - </span><a href="#h-412081"><span class="HTitleText2">Règles</span></a>
</li>
<li><span class='sectionRange'>45.5 - </span><a href="#h-412096"><span class="HTitleText2">Immunité</span></a>
</li>
<li><span class='sectionRange'>45.51 - </span><a href="#h-412104"><span class="HTitleText2">Rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>45.53 - </span><a href="#h-412121"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Enquêtes, révisions et audiences relatives aux plaintes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45.53 - </span><a href="#h-412122"><span class="HTitleText2">Plaintes</span></a>
</li>
<li><span class='sectionRange'>45.55 - </span><a href="#h-412165"><span class="HTitleText2">Retrait de la plainte</span></a>
</li>
<li><span class='sectionRange'>45.56 - </span><a href="#h-412183"><span class="HTitleText2">Règlement à l’amiable des plaintes</span></a>
</li>
<li><span class='sectionRange'>45.57 - </span><a href="#h-412199"><span class="HTitleText2">Observations</span></a>
</li>
<li><span class='sectionRange'>45.59 - </span><a href="#h-412219"><span class="HTitleText2">Plaintes déposées par le président de la Commission</span></a>
</li>
<li><span class='sectionRange'>45.6 - </span><a href="#h-412231"><span class="HTitleText2">Enquête sur les plaintes par la Gendarmerie</span></a>
</li>
<li><span class='sectionRange'>45.65 - </span><a href="#h-412268"><span class="HTitleText2">Pouvoirs de la Commission relativement aux plaintes</span></a>
</li>
<li><span class='sectionRange'>45.66 - </span><a href="#h-412293"><span class="HTitleText2">Enquête par la Commission</span></a>
</li>
<li><span class='sectionRange'>45.7 - </span><a href="#h-412322"><span class="HTitleText2">Plaintes renvoyées à la Commission</span></a>
</li>
<li><span class='sectionRange'>45.73 - </span><a href="#h-412353"><span class="HTitleText2">Audience</span></a>
</li>
<li><span class='sectionRange'>45.74 - </span><a href="#h-412384"><span class="HTitleText2">Suspension et procédures conjointes</span></a>
</li>
<li><span class='sectionRange'>45.76 - </span><a href="#h-412401"><span class="HTitleText2">Rapports d’enquête et d’audience</span></a>
</li></ul>
</li><li><span class='sectionRange'>45.79 - </span><a href="#h-412419"><span class="HLabel1">PARTIE VII.1</span> - <span class="HTitleText1">Incidents graves</span></a>
</li>
<li><span class='sectionRange'>45.88 - </span><a href="#h-412505"><span class="HLabel1">PARTIE VII.2</span> - <span class="HTitleText1">Examen des opérations transfrontalières intégrées de contrôle d’application de la loi</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45.88 - </span><a href="#h-412506"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>45.89 - </span><a href="#h-412525"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>45.9 - </span><a href="#h-412532"><span class="HTitleText2">Application des articles 45.34 à 45.51</span></a>
</li>
<li><span class='sectionRange'>45.91 - </span><a href="#h-412550"><span class="HTitleText2">Rapport</span></a>
</li>
<li><span class='sectionRange'>45.94 - </span><a href="#h-412573"><span class="HTitleText2">Enquêtes, révisions et audiences relatives aux plaintes</span></a>
</li>
<li><span class='sectionRange'>45.98 - </span><a href="#h-412607"><span class="HTitleText2">Incident grave</span></a>
</li></ul>
</li><li><span class='sectionRange'>46 - </span><a href="#h-412628"><span class="HLabel1">PARTIE VIII</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-412629"><span class="HTitleText2">Dispositions diverses d’application générale</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-412690"><span class="HTitleText2">Infractions</span></a>
</li></ul>
</li><li><a href="#h-412772"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
