<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Serbia Tax Convention Act, 2013</a><ul class="TocIndent"><li><a href="#h-50465"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention Between Canada and the Republic of Serbia for the Avoidance of Double Taxation with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="#h-50724"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Protocol</span></a>
</li></ul>
</li></ul>

</nav>

