<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Government Services Resumption Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-252079"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-252082"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-252095"><span class="HTitleText1">Government Services</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-252112"><span class="HTitleText1">Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-252126"><span class="HTitleText1">Conciliation Boards</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-252166"><span class="HTitleText1">Amendment of Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-252169"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-252179"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-252183"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

