<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Cooperative Credit Associations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-96535"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-96538"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Interpretation and Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-96539"><span class="HTitleText2">Definitions</span></a>
</li>
<li><span class='sectionRange'>2.1 - </span><a href="page-2.html#h-96670"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-3.html#h-96803"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-3.html#h-96810"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Status and Powers</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-3.html#h-96851"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Incorporation, Continuance and Discontinuance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>23 - </span><a href="page-3.html#h-96852"><span class="HTitleText2">Formalities of Incorporation</span></a>
</li>
<li><span class='sectionRange'>31.1 - </span><a href="page-3.html#h-96914"><span class="HTitleText2">Continuance</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-97004"><span class="HTitleText2">Discontinuance</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-97029"><span class="HTitleText2">Corporate Name</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="page-5.html#h-97080"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Membership</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="page-5.html#h-97081"><span class="HTitleText2">Admittance</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-5.html#h-97111"><span class="HTitleText2">Withdrawal and Expulsion</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-5.html#h-97125"><span class="HTitleText2">Members Register</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-97136"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="page-5.html#h-97159"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Organization and Commencement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="page-5.html#h-97160"><span class="HTitleText2">Organization Meetings</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-5.html#h-97182"><span class="HTitleText2">Commencement and Carrying on of Business</span></a>
</li></ul>
</li><li><span class='sectionRange'>66 - </span><a href="page-6.html#h-97252"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Capital Structure</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="page-6.html#h-97253"><span class="HTitleText2">Share Capital</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="page-7.html#h-97481"><span class="HTitleText2">Subordinated Indebtedness</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="page-7.html#h-97491"><span class="HTitleText2">Security Certificates and Transfers</span></a>
</li></ul>
</li><li><span class='sectionRange'>143 - </span><a href="page-11.html#h-97890"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Corporate Governance</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>143 - </span><a href="page-11.html#h-97891"><span class="HTitleText2">Members and Shareholders</span></a>
</li>
<li><span class='sectionRange'>166.01 - </span><a href="page-12.html#h-98128"><span class="HTitleText2">Proxies</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="page-13.html#h-98246"><span class="HTitleText2">Directors and Officers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>167 - </span><a href="page-13.html#h-98247"><span class="HTitleText3">Duties</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="page-13.html#h-98271"><span class="HTitleText3">Qualification and Number — Directors</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="page-13.html#h-98292"><span class="HTitleText3">Election and Tenure — Directors</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="page-14.html#h-98330"><span class="HTitleText3">Director Vacancies</span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="page-14.html#h-98406"><span class="HTitleText3">Meetings of the Board</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="page-15.html#h-98478"><span class="HTitleText3">By-laws</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="page-15.html#h-98513"><span class="HTitleText3">Committees of the Board</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="page-15.html#h-98558"><span class="HTitleText3">Directors and Officers — Authority</span></a>
</li>
<li><span class='sectionRange'>206 - </span><a href="page-15.html#h-98595"><span class="HTitleText3">Conflicts of Interest</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="page-16.html#h-98656"><span class="HTitleText3">Liability, Exculpation and Indemnification</span></a>
</li></ul>
</li><li><span class='sectionRange'>219 - </span><a href="page-17.html#h-98744"><span class="HTitleText2">Fundamental Changes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>219 - </span><a href="page-17.html#h-98745"><span class="HTitleText3">Amendments</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="page-17.html#h-98808"><span class="HTitleText3">Amalgamation</span></a>
</li>
<li><span class='sectionRange'>233.1 - </span><a href="page-18.html#h-98937"><span class="HTitleText3">Transfer of Business</span></a>
</li></ul>
</li><li><span class='sectionRange'>234 - </span><a href="page-18.html#h-98981"><span class="HTitleText2">Corporate Records</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>234 - </span><a href="page-18.html#h-98982"><span class="HTitleText3">Head Office and Corporate Records</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="page-19.html#h-99088"><span class="HTitleText3">Securities Registers</span></a>
</li>
<li><span class='sectionRange'>250 - </span><a href="page-19.html#h-99122"><span class="HTitleText3">Corporate Name and Seal</span></a>
</li></ul>
</li><li><span class='sectionRange'>260 - </span><a href="page-19.html#h-99133"><span class="HTitleText2">Insiders</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>260 - </span><a href="page-19.html#h-99134"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="page-19.html#h-99155"><span class="HTitleText3">Insider Reporting</span></a>
</li>
<li><span class='sectionRange'>265 - </span><a href="page-20.html#h-99173"><span class="HTitleText3">Insider Trading</span></a>
</li>
<li><span class='sectionRange'>266 - </span><a href="page-20.html#h-99191"><span class="HTitleText3">Civil remedies</span></a>
</li></ul>
</li><li><span class='sectionRange'>268 - </span><a href="page-20.html#h-99253"><span class="HTitleText2">Prospectus</span></a>
</li>
<li><span class='sectionRange'>278 - </span><a href="page-20.html#h-99279"><span class="HTitleText2">Trust Indentures</span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="page-21.html#h-99361"><span class="HTitleText2">Financial Statements and Auditors</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>291 - </span><a href="page-21.html#h-99362"><span class="HTitleText3">Annual Financial Statement</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="page-22.html#h-99427"><span class="HTitleText3">Auditor</span></a>
</li></ul>
</li><li><span class='sectionRange'>318 - </span><a href="page-23.html#h-99613"><span class="HTitleText2">Remedial Actions</span></a>
</li>
<li><span class='sectionRange'>323 - </span><a href="page-23.html#h-99658"><span class="HTitleText2">Liquidation and Dissolution</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>323 - </span><a href="page-23.html#h-99659"><span class="HTitleText3">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>326 - </span><a href="page-23.html#h-99671"><span class="HTitleText3">Simple Liquidation</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="page-24.html#h-99706"><span class="HTitleText3">Court-supervised Liquidation</span></a>
</li>
<li><span class='sectionRange'>345 - </span><a href="page-25.html#h-99833"><span class="HTitleText3">General</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>354 - </span><a href="page-25.html#h-99892"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Ownership</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>354 - </span><a href="page-25.html#h-99893"><span class="HLabel2">DIVISION I</span> - <span class="HTitleText2">Constraints on Ownership</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-26.html#h-100033"><span class="HLabel2">DIVISION II</span> - <span class="HTitleText2">[Repealed, 1994, c. 47, s. 54]</span></a>
</li>
<li><span class='sectionRange'>368 - </span><a href="page-26.html#h-100034"><span class="HLabel2">DIVISION III</span> - <span class="HTitleText2">Directions</span></a>
</li></ul>
</li><li><span class='sectionRange'>375 - </span><a href="page-26.html#h-100080"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Business and Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>375 - </span><a href="page-26.html#h-100081"><span class="HTitleText2">General Business</span></a>
</li>
<li><span class='sectionRange'>385.01 - </span><a href="page-28.html#h-100338"><span class="HTitleText2">Deposit Acceptance</span></a>
</li>
<li><span class='sectionRange'>385.03 - </span><a href="page-28.html#h-100358"><span class="HTitleText2">Unclaimed Balances</span></a>
</li>
<li><span class='sectionRange'>385.05 - </span><a href="page-29.html#h-100407"><span class="HTitleText2">Accounts</span></a>
</li>
<li><span class='sectionRange'>385.131 - </span><a href="page-29.html#h-100474"><span class="HTitleText2">Registered Products</span></a>
</li>
<li><span class='sectionRange'>385.14 - </span><a href="page-29.html#h-100488"><span class="HTitleText2">Borrowing Costs</span></a>
</li>
<li><span class='sectionRange'>385.22 - </span><a href="page-30.html#h-100572"><span class="HTitleText2">Complaints</span></a>
</li>
<li><span class='sectionRange'>385.241 - </span><a href="page-30.html#h-100603"><span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>386 - </span><a href="page-31.html#h-100742"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Investments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>386 - </span><a href="page-31.html#h-100743"><span class="HTitleText2">Definitions and Application</span></a>
</li>
<li><span class='sectionRange'>387 - </span><a href="page-32.html#h-100828"><span class="HTitleText2">General Constraints on Investments</span></a>
</li>
<li><span class='sectionRange'>390 - </span><a href="page-32.html#h-100869"><span class="HTitleText2">Subsidiaries and Equity Investments</span></a>
</li>
<li><span class='sectionRange'>393 - </span><a href="page-33.html#h-100983"><span class="HTitleText2">Exceptions and Exclusions</span></a>
</li>
<li><span class='sectionRange'>397 - </span><a href="page-33.html#h-101046"><span class="HTitleText2">Portfolio Limits</span></a>
</li>
<li><span class='sectionRange'>398 - </span><a href="page-33.html#h-101060"><span class="HTitleText2">Commercial Loans</span></a>
</li>
<li><span class='sectionRange'>401 - </span><a href="page-34.html#h-101079"><span class="HTitleText2">Real Property</span></a>
</li>
<li><span class='sectionRange'>402 - </span><a href="page-34.html#h-101084"><span class="HTitleText2">Equities</span></a>
</li>
<li><span class='sectionRange'>403 - </span><a href="page-34.html#h-101095"><span class="HTitleText2">Miscellaneous</span></a>
</li></ul>
</li><li><span class='sectionRange'>409 - </span><a href="page-34.html#h-101173"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Adequacy of Capital and Liquidity</span></a>
</li>
<li><span class='sectionRange'>409.1 - </span><a href="page-34.html#h-101192"><span class="HLabel1">PART XII</span> - <span class="HTitleText1">Self-dealing</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>409.1 - </span><a href="page-34.html#h-101193"><span class="HTitleText2">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>413 - </span><a href="page-35.html#h-101277"><span class="HTitleText2">Prohibited Related Party Transactions</span></a>
</li>
<li><span class='sectionRange'>414 - </span><a href="page-35.html#h-101287"><span class="HTitleText2">Permitted Related Party Transactions</span></a>
</li>
<li><span class='sectionRange'>425 - </span><a href="page-36.html#h-101407"><span class="HTitleText2">Restrictions on Permitted Transactions</span></a>
</li>
<li><span class='sectionRange'>428 - </span><a href="page-36.html#h-101420"><span class="HTitleText2">Disclosure</span></a>
</li>
<li><span class='sectionRange'>430 - </span><a href="page-36.html#h-101430"><span class="HTitleText2">Remedial Actions</span></a>
</li></ul>
</li><li><span class='sectionRange'>431 - </span><a href="page-36.html#h-101440"><span class="HLabel1">PART XIII</span> - <span class="HTitleText1">Regulation of Associations — Superintendent</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>431 - </span><a href="page-36.html#h-101441"><span class="HTitleText2">Supervision</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>431 - </span><a href="page-36.html#h-101442"><span class="HTitleText3">Returns</span></a>
</li>
<li><span class='sectionRange'>437 - </span><a href="page-37.html#h-101540"><span class="HTitleText3">Inspection of Associations</span></a>
</li></ul>
</li><li><span class='sectionRange'>438.1 - </span><a href="page-37.html#h-101552"><span class="HTitleText2">Remedial Powers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>438.1 - </span><a href="page-37.html#h-101553"><span class="HTitleText3">Prudential Agreements</span></a>
</li>
<li><span class='sectionRange'>439 - </span><a href="page-37.html#h-101558"><span class="HTitleText3">Directions of Compliance</span></a>
</li>
<li><span class='sectionRange'>441.01 - </span><a href="page-37.html#h-101582"><span class="HTitleText3">Disqualification and Removal of Directors or Senior Officers</span></a>
</li>
<li><span class='sectionRange'>442 - </span><a href="page-37.html#h-101639"><span class="HTitleText3">Supervisory Intervention</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>452.1 - </span><a href="page-38.html#h-101715"><span class="HLabel1">PART XIII.1</span> - <span class="HTitleText1">Regulation of Retail Associations — Commissioner</span></a>
</li>
<li><span class='sectionRange'>452.6 - </span><a href="page-38.html#h-101748"><span class="HLabel1">PART XIV</span> - <span class="HTitleText1">Administration</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>452.6 - </span><a href="page-38.html#h-101749"><span class="HTitleText2">Notices and Other Documents</span></a>
</li>
<li><span class='sectionRange'>459.2 - </span><a href="page-39.html#h-101803"><span class="HTitleText2">Approvals</span></a>
</li>
<li><span class='sectionRange'>459.81 - </span><a href="page-39.html#h-101862"><span class="HTitleText2">Exceptions to Generally Accepted Accounting Principles</span></a>
</li>
<li><span class='sectionRange'>459.9 - </span><a href="page-39.html#h-101872"><span class="HTitleText2">Orders to Exempt or Adapt</span></a>
</li>
<li><span class='sectionRange'>460 - </span><a href="page-39.html#h-101914"><span class="HTitleText2">Orders and Directives</span></a>
</li>
<li><span class='sectionRange'>461.1 - </span><a href="page-39.html#h-101919"><span class="HTitleText2">Applications to Superintendent</span></a>
</li>
<li><span class='sectionRange'>461.2 - </span><a href="page-40.html#h-101939"><span class="HTitleText2">Applications for Certain Approvals</span></a>
</li>
<li><span class='sectionRange'>462 - </span><a href="page-40.html#h-101957"><span class="HTitleText2">Appeals</span></a>
</li>
<li><span class='sectionRange'>463 - </span><a href="page-40.html#h-101970"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>464 - </span><a href="page-40.html#h-101994"><span class="HTitleText2">Delegation</span></a>
</li></ul>
</li><li><span class='sectionRange'>465 - </span><a href="page-40.html#h-101997"><span class="HLabel1">PART XV</span> - <span class="HTitleText1">Sanctions</span></a>
</li>
<li><span class='sectionRange'>472 - </span><a href="page-40.html#h-102055"><span class="HLabel1">PART XVI</span> - <span class="HTitleText1">[Repealed, 2014, c. 39, s. 291]</span></a>
</li>
<li><span class='sectionRange'>481 - </span><a href="page-40.html#h-102065"><span class="HLabel1">PART XVII</span> - <span class="HTitleText1">Loans to Associations and Deposit Protection Agencies</span></a>
</li>
<li><span class='sectionRange'>487.01 - </span><a href="page-41.html#h-102106"><span class="HLabel1">PART XVII.1</span> - <span class="HTitleText1">Documents in Electronic or Other Form</span></a>
</li>
<li><span class='sectionRange'>488 to 499 - </span><a href="page-41.html#h-102193"><span class="HLabel1">PART XVIII</span> - <span class="HTitleText1">General Provisions</span></a>
</li>
<li><span class='sectionRange'>500 - </span><a href="page-41.html#h-102195"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

