<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les foyers familiaux situés dans les réserves et les droits ou intérêts matrimoniaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-215347"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-215350"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-215388"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-215391"><span class="HTitleText1">Objet et application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-215398"><span class="HTitleText1">Adoption de textes législatifs par les premières nations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-215399"><span class="HTitleText2">Pouvoir des premières nations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-215411"><span class="HTitleText2">Consultation populaire</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-215430"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-215444"><span class="HTitleText1">Règles fédérales provisoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-215445"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-215465"><span class="HTitleText2">Foyer familial</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-215466"><span class="HTitleText3">Droit d’occupation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-215484"><span class="HTitleText3">Ordonnance de protection d’urgence</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-215565"><span class="HTitleText3">Ordonnance d’occupation exclusive</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-215627"><span class="HTitleText3">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-215642"><span class="HTitleText2">Partage de la valeur des droits ou intérêts matrimoniaux</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-215643"><span class="HTitleText3">Échec de la relation conjugale</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-215724"><span class="HTitleText3">Décès de l’époux ou conjoint de fait</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-215807"><span class="HTitleText2">Avis au conseil et observations du conseil</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-215815"><span class="HTitleText2">Compétence</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-215841"><span class="HTitleText2">Règles de pratique et de procédure</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-215860"><span class="HTitleText2">Autres dispositions</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-215882"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-215888"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-215902"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
