<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 2006 sur la convention fiscale Canada–Mexique</a><ul class="TocIndent"><li><a href="page-2.html#h-146773"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Convention entre le gouvernement du Canada et le gouvernement des États-Unis du Mexique en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu</span></a>
</li>
<li><a href="page-3.html#h-147070"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole</span></a>
</li></ul>
</li></ul>

</nav>

