<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Human Pathogens and Toxins Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-254961"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-254964"><span class="HTitleText1">Purpose of the Act</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-254967"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-255005"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-255008"><span class="HTitleText1">Obligation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-255011"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-255029"><span class="HTitleText1">Schedules 1 to 4</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-255046"><span class="HTitleText1">Schedule 5</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-255063"><span class="HTitleText1">Consequences of Adding to Schedules</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-255074"><span class="HTitleText1">Obligation to Inform Minister</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-255104"><span class="HTitleText1">Licences</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-255207"><span class="HTitleText1">Access to Facility to Which Licence Applies</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-255212"><span class="HTitleText1">Security Clearances</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-255236"><span class="HTitleText1">Biological Safety Officers</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-255250"><span class="HTitleText1">Exemptions</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-255257"><span class="HTitleText1">Information</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-255279"><span class="HTitleText1">Administration and Enforcement</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-255394"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-255445"><span class="HTitleText1">Debts</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-255451"><span class="HTitleText1">Regulatory Powers</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-255554"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-255575"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-255579"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Toxins</span></a>
</li>
<li><a href="#h-255610"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Risk Group 2 Human Pathogens</span></a>
</li>
<li><a href="#h-255737"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Risk Group 3 Human Pathogens</span></a>
</li>
<li><a href="#h-255804"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - Risk Group 4 Human Pathogens</span></a>
</li>
<li><a href="#h-255828"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - Prohibited Human Pathogens and Toxins</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
