<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Broadcasting Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-34116"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-34119"><span class="HLabel1">PART I</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="page-1.html#h-34120"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-34144"><span class="HTitleText2">Broadcasting Policy for Canada</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-34198"><span class="HTitleText2">Application</span></a>
</li></ul>
</li><li><span class='sectionRange'>5 - </span><a href="page-1.html#h-34218"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Objects and Powers of the Commission in Relation to Broadcasting</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-34219"><span class="HTitleText2">Objects</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-2.html#h-34268"><span class="HTitleText2">General Powers</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="page-2.html#h-34361"><span class="HTitleText2">Hearings and Procedure</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-3.html#h-34398"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-3.html#h-34439"><span class="HTitleText2">General Powers of the Governor in Council</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-34485"><span class="HTitleText2">Decisions and Orders</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-4.html#h-34495"><span class="HTitleText2">Offences</span></a>
</li></ul>
</li><li><span class='sectionRange'>34.1 - </span><a href="page-4.html#h-34509"><span class="HLabel1">PART II.1</span> - <span class="HTitleText1">Offence  — Paper Bill</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-4.html#h-34524"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Canadian Broadcasting Corporation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="page-4.html#h-34525"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-4.html#h-34537"><span class="HTitleText2">Continuation of Corporation</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-4.html#h-34566"><span class="HTitleText2">Chairperson</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-34574"><span class="HTitleText2">President</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-4.html#h-34582"><span class="HTitleText2">Remuneration</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-34590"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-4.html#h-34598"><span class="HTitleText2">Standing Committees</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-4.html#h-34608"><span class="HTitleText2">Objects and Powers</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-5.html#h-34649"><span class="HTitleText2">Agent of Her Majesty</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="page-5.html#h-34675"><span class="HTitleText2">Head Office and Meetings</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="page-5.html#h-34683"><span class="HTitleText2">By-laws</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-5.html#h-34695"><span class="HTitleText2">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="page-6.html#h-34787"><span class="HTitleText2">Report to Parliament</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 to 88 - </span><a href="page-6.html#h-34803"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Related and Consequential Amendments, Repeal, Transitional and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>72 to 88 - </span><a href="page-6.html#h-34804"><span class="HTitleText2">Related and Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="page-6.html#h-34806"><span class="HTitleText2">Repeal</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-6.html#h-34808"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="page-6.html#h-34829"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-7.html#h-34833"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

