<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les ouvrages destinés à l’amélioration des cours d’eau internationaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-270892"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-270897"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-270910"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-270921"><span class="HTitleText1">Permis</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-270935"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-270954"><span class="HTitleText1">Contrôle d’application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-270955"><span class="HTitleText2">Agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-270975"><span class="HTitleText2">Inspection</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-271028"><span class="HTitleText2">Perquisition et saisie</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-271033"><span class="HTitleText2">Aide à donner aux agents de l’autorité et analystes</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-271040"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-271067"><span class="HTitleText2">Ordres d’exécution</span></a>
</li></ul>
</li><li><span class='sectionRange'>31 - </span><a href="#h-271185"><span class="HTitleText1">Entrave et renseignements faux ou trompeurs</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-271201"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-271402"><span class="HTitleText1">Rapports</span></a>
</li></ul>
</li></ul>

</nav>

