<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les fonds renouvelables</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-418665"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-418670"><span class="HTitleText1">Ministre de l’Agriculture et de l’Agroalimentaire</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-418683"><span class="HTitleText1">Ministre du Patrimoine canadien (Agence Parcs Canada)</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-418686"><span class="HTitleText1">Ministre de la Citoyenneté et de l’Immigration</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-418696"><span class="HTitleText1">Ministre des Travaux publics et des Services gouvernementaux</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-418724"><span class="HTitleText1">Secrétaire d’État (Office national du film)</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-418734"><span class="HTitleText1">Secrétaire d’État (Commission de la fonction publique)</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-418736"><span class="HTitleText1">Ministre des Approvisionnements et Services</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-418739"><span class="HTitleText1">Ministre des Transports (aéroports)</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-418741"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

