<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Statistics Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Statistics Canada</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-4"><span class="HTitleText1">Statistics</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-5"><span class="HTitleText1">Secrecy</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-6"><span class="HTitleText1">Population Census and Agriculture Census</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-7"><span class="HTitleText1">General Statistics</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-8"><span class="HTitleText1">Criminal Statistics</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-9"><span class="HTitleText1">Offences and Punishment</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
