<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Great Lakes Fisheries Convention Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-232308"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-232313"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-232320"><span class="HTitleText1">Convention and Regulations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-232333"><span class="HTitleText1">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-232338"><span class="HTitleText1">Duration</span></a>
</li>
<li><a href="#h-232344"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

