<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Representation Act, 1974</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-427405"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-427408"><span class="HLabel1">PART I</span> - <span class="HTitleText1">British North America Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-427413"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Electoral Boundaries Readjustment</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
