<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’emploi dans la fonction publique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Commission de la fonction publique, administrateurs généraux et employeur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Commission</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText2">Mission et attributions de la Commission</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HTitleText2">Délégation de pouvoirs aux administrateurs généraux</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText2">Vérifications de la Commission</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-8"><span class="HTitleText2">Exemptions</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2">Règlements de la Commission</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText2">Rapports de la Commission</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText2">Administrateurs généraux</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText2">Règlements et lignes directrices de l’employeur</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-13"><span class="HTitleText2">Rapport annuel du Conseil du Trésor</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-14"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Nominations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText2">Pouvoir de nomination</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-16"><span class="HTitleText2">Modalités de nomination</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText2">Préférences, priorités et autres droits</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-18"><span class="HTitleText2">Discussions informelles et nomination</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-19"><span class="HTitleText2">Emploi occasionnel</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-20"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Mutations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-21"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Emploi</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-22"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Enquêtes et plaintes relatives aux nominations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="#h-23"><span class="HTitleText2">Enquêtes de la Commission sur les nominations</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-24"><span class="HTitleText2">Plaintes relatives aux révocations devant le Tribunal</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-25"><span class="HTitleText2">Plaintes relatives aux nominations internes devant le Tribunal</span></a>
</li></ul>
</li><li><span class='sectionRange'>88 - </span><a href="#h-26"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Tribunal de la dotation de la fonction publique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-27"><span class="HTitleText2">Composition et mission</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-28"><span class="HTitleText2">Procédure relative aux plaintes</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-29"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-30"><span class="HTitleText2">Règlements et rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-31"><span class="HLabel1">PARTIE 7</span> - <span class="HTitleText1">Activités politiques</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-32"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-33"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-34"><span class="HTitleText2">Fonctionnaires</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-35"><span class="HTitleText2">Administrateurs généraux</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-36"><span class="HTitleText2">Allégations</span></a>
</li></ul>
</li><li><span class='sectionRange'>123 - </span><a href="#h-37"><span class="HLabel1">PARTIE 8</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-38"><span class="HTitleText2">Application de la présente loi</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-39"><span class="HTitleText2">Chef de la fonction publique</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-40"><span class="HTitleText2">Personnel des cabinets de ministres</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-41"><span class="HTitleText2">Hauts responsables</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-42"><span class="HTitleText2">Personnel diplomatique</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-43"><span class="HTitleText2">Transferts en bloc</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-44"><span class="HTitleText2">Infraction</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-45"><span class="HTitleText2">Serments</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-46"><span class="HTitleText2">Accès aux installations et renseignements</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-47"><span class="HTitleText2">Examen quinquennal</span></a>
</li></ul>
</li><li><a href="#h-48"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Définitions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
