<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi liquidant Sport Sélect et Loto Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-426992"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-426995"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-427003"><span class="HTitleText1">Société canadienne des paris sportifs</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-427013"><span class="HTitleText1">Loto Canada Inc.</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-427019"><span class="HTitleText1">Procédures judiciaires</span></a>
</li></ul>
</li></ul>

</nav>

