<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
First Nations Financial Transparency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-224746"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-224749"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-224760"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-224765"><span class="HTitleText1">Financial Statements and Schedule of Remuneration and Expenses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="page-1.html#h-224766"><span class="HTitleText2">Preparation and Independent Audit</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-224779"><span class="HTitleText2">Disclosure</span></a>
</li></ul>
</li><li><span class='sectionRange'>10 - </span><a href="page-1.html#h-224800"><span class="HTitleText1">Court Remedies and Administrative Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="page-1.html#h-224801"><span class="HTitleText2">Orders</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-224808"><span class="HTitleText2">Administrative Measures</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

