<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Agricultural Products Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-40834"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-40837"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-40876"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-40879"><span class="HTitleText1">Board of Arbitration and Review Tribunal</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-40973"><span class="HTitleText1">Complaint to Board of Arbitration</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-40982"><span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-40992"><span class="HTitleText1">Enforcement of Decisions and Orders</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-41025"><span class="HTitleText1">Registered Establishments and Accredited Laboratories</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-41030"><span class="HTitleText1">National Trade-marks</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-41037"><span class="HTitleText1">Trade in Agricultural Products</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-41047"><span class="HTitleText1">Administrative Officers</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-41064"><span class="HTitleText1">Inspection</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-41095"><span class="HTitleText1">Search</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-41110"><span class="HTitleText1">Disposition of Things Seized</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-41151"><span class="HTitleText1">Illegal Import</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-41159"><span class="HTitleText1">Financial Responsibility</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-41164"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-41200"><span class="HTitleText1">Offence and Punishment</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-41238"><span class="HTitleText1">Evidence</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-41255"><span class="HTitleText1">Repeal</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
