<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Bank of Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Constitution of the Bank</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-4"><span class="HTitleText1">Management</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText1">Executive Committee</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">Government Directive</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText1">Bank Staff</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-8"><span class="HTitleText1">Secrecy</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-9"><span class="HTitleText1">Capital and Shares</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-10"><span class="HTitleText1">Business and Powers of the Bank</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText1">Note Issue</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText1">Redemption of Notes Other than Those of the Bank</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-13"><span class="HTitleText1">Rest Fund</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-14"><span class="HTitleText1">Audit</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-15"><span class="HTitleText1">Returns</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-16"><span class="HTitleText1">Liability</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-17"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-18"><span class="HTitleText1">Liquidation or Winding-up</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-19"><span class="HTitleText1">By-laws</span></a>
</li>
<li><a href="#h-24243"><span class="scheduleLabel">SCHEDULE</span> </a>
</li>
<li><a href="#h-24254"><span class="scheduleLabel">SCHEDULES II AND III</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
