<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Yukon Oil and Gas Accord Implementation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Amendments to Yukon Act</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-3"><span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 - </span><a href="#h-4"><span class="HTitleText2">Canada Oil and Gas Operations Act</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-5"><span class="HTitleText2">Canada Petroleum Resources Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HTitleText2">Yukon Surface Rights Board Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>19 - </span><a href="#h-7"><span class="HTitleText1">Transitional and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>19 - </span><a href="#h-8"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-9"><span class="HTitleText2">Transitional</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-10"><span class="HTitleText2">Coming into force</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
