<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Family Homes on Reserves and Matrimonial Interests or Rights Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-220943"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-220946"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-220984"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-220987"><span class="HTitleText1">Purpose and Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-220997"><span class="HTitleText1">Enactment of First Nation Laws</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="#h-220998"><span class="HTitleText2">Power of First Nations</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-221010"><span class="HTitleText2">Community Approval</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-221029"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-221043"><span class="HTitleText1">Provisional Federal Rules</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-221044"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-221064"><span class="HTitleText2">Family Home</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-221065"><span class="HTitleText3">Occupation</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-221083"><span class="HTitleText3">Emergency Protection Order</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-221164"><span class="HTitleText3">Exclusive Occupation Order</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-221226"><span class="HTitleText3">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-221241"><span class="HTitleText2">Division of the Value of Matrimonial Interests or Rights</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-221242"><span class="HTitleText3">Breakdown of a Conjugal Relationship</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-221324"><span class="HTitleText3">Death of a Spouse or Common-Law Partner</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-221407"><span class="HTitleText2">Notice to Council and Views of Council</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-221415"><span class="HTitleText2">Jurisdiction of Courts</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-221441"><span class="HTitleText2">Rules of Practice and Procedure</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-221460"><span class="HTitleText2">Other Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-221482"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-221488"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-221502"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
