<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les armes à feu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Possession</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Admissibilité</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText3">Règles générales</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText3">Cas particuliers : personnes</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-9"><span class="HTitleText3">Cas particuliers : armes à feu, armes, dispositifs et munitions prohibés</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText2">Certificats d’enregistrement</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText1">Transport d’armes à feu</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-12"><span class="HTitleText1">Cession et prêt</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-13"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText2">Cession</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-15"><span class="HTitleText2">Prêt</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-16"><span class="HTitleText1">Exportation et importation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-17"><span class="HTitleText2">Particuliers</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-18"><span class="HTitleText2">Entreprises</span></a>
</li></ul>
</li><li><span class='sectionRange'>54 - </span><a href="#h-19"><span class="HTitleText1">Permis, autorisations et certificats d’enregistrement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-20"><span class="HTitleText2">Demandes</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-21"><span class="HTitleText2">Délivrance</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-22"><span class="HTitleText2">Durée de validité</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-23"><span class="HTitleText2">Non-délivrance et révocation</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-24"><span class="HTitleText2">Transporteurs internationaux et interprovinciaux</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-25"><span class="HTitleText2">Renvoi à un juge de la cour provinciale</span></a>
</li>
<li><span class='sectionRange'>76.1 - </span><a href="#h-26"><span class="HTitleText2">Appels à la cour supérieure et à la cour d’appel</span></a>
</li>
<li><span class='sectionRange'>81.1 - </span><a href="#h-27"><span class="HTitleText2">COMMISSAIRE AUX ARMES À FEU</span></a>
</li></ul>
</li><li><span class='sectionRange'>82 - </span><a href="#h-28"><span class="HTitleText1">Système canadien d’enregistrement des armes à feu</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>82 - </span><a href="#h-29"><span class="HTitleText2">Directeur</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-30"><span class="HTitleText2">Registre</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-31"><span class="HTitleText2">Registre des contrôleurs des armes à feu</span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-32"><span class="HTitleText2">Notification des ordonnances d’interdiction</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-33"><span class="HTitleText2">Accès au registre</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-34"><span class="HTitleText2">Transmission électronique</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-35"><span class="HTitleText2">Rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>95 - </span><a href="#h-36"><span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>95 - </span><a href="#h-37"><span class="HTitleText2">Accords avec les provinces</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-38"><span class="HTitleText2">Autres questions</span></a>
</li></ul>
</li><li><span class='sectionRange'>98 - </span><a href="#h-39"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-40"><span class="HTitleText1">Visite</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-41"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-42"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-43"><span class="HTitleText1">Dispositions transitoires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>120 - </span><a href="#h-44"><span class="HTitleText2">Permis</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-45"><span class="HTitleText2">Certificats d’enregistrement</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-46"><span class="HTitleText2">Transport d’armes à feu</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 et 137 - </span><a href="#h-47"><span class="HTitleText1">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>138 et 139 - </span><a href="#h-48"><span class="HTitleText1">Modifications du Code criminel</span></a>
</li>
<li><span class='sectionRange'>140 à 157 - </span><a href="#h-49"><span class="HTitleText1">Modifications corrélatives : Code criminel</span></a>
</li>
<li><span class='sectionRange'>158 à 187 - </span><a href="#h-50"><span class="HTitleText1">Modifications corrélatives : autres lois</span></a>
</li>
<li><span class='sectionRange'>188 à 192 - </span><a href="#h-51"><span class="HTitleText1">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-52"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
