<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Air Travellers Security Charge Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1540"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1543"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1645"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-1656"><span class="HTitleText1">Administration and Officers</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-1666"><span class="HTitleText1">Charge Payable</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-1720"><span class="HTitleText1">Collection of Charge</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-1750"><span class="HTitleText1">General Provisions Concerning Charges and Other Amounts Payable</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="#h-1751"><span class="HTitleText2">Fiscal Periods</span></a>
</li>
<li><span class='sectionRange'>16.1 - </span><a href="#h-1764"><span class="HTitleText2">Reporting Periods</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1787"><span class="HTitleText2">Returns and Payments of Charges and Other Amounts</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-1857"><span class="HTitleText2">Interest</span></a>
</li>
<li><span class='sectionRange'>30.1 - </span><a href="#h-1878"><span class="HTitleText2">Administrative Charge under the <cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-1883"><span class="HTitleText2">Refunds</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-1936"><span class="HTitleText2">Records and Information</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-1985"><span class="HTitleText2">Assessments</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-2034"><span class="HTitleText2">Objections to Assessment</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-2085"><span class="HTitleText2">Appeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>53 - </span><a href="#h-2194"><span class="HTitleText1">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-2195"><span class="HTitleText2">Penalties</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-2226"><span class="HTitleText2">Penalty Imposition</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-2231"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-2284"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-2309"><span class="HTitleText2">Collection</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-2480"><span class="HTitleText2">Evidence and Procedure</span></a>
</li></ul>
</li><li><span class='sectionRange'>84 - </span><a href="#h-2527"><span class="HTitleText1">Regulations</span></a>
</li>
<li><a href="#h-2542"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Listed Airports</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
