<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Sechelt Indian Band Self-Government Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-444409"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-444412"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-444428"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-444431"><span class="HTitleText1">Sechelt Indian Band</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-444437"><span class="HTitleText1">Capacity and Powers of Band</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-444448"><span class="HTitleText1">Sechelt Indian Band Council</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-444453"><span class="HTitleText1">Band Constitution</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-444475"><span class="HTitleText1">Amendment to Band Constitution</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-444478"><span class="HTitleText1">Publication of Constitution and Amendments</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-444481"><span class="HTitleText1">Legislative Powers of Council</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-444516"><span class="HTitleText1">Sechelt Indian Government District</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-444551"><span class="HTitleText1">Transfer of Lands</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-2.html#h-444568"><span class="HTitleText1">Disposition of Sechelt Lands</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-444571"><span class="HTitleText1">Registration of Sechelt Lands</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-444603"><span class="HTitleText1">Sechelt Lands</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-444606"><span class="HTitleText1">Moneys</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-444612"><span class="HTitleText1">Funding</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="page-2.html#h-444617"><span class="HTitleText1">Application of Indian Act</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-444630"><span class="HTitleText1">Application of Laws of Canada</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-2.html#h-444633"><span class="HTitleText1">Application of Laws of British Columbia</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-2.html#h-444636"><span class="HTitleText1">Application of Laws Relating to Natural Resources</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-2.html#h-444643"><span class="HTitleText1">Application of By-laws</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="page-2.html#h-444646"><span class="HTitleText1">Governor in Council and Ministers</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-2.html#h-444649"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>47 to 60 - </span><a href="page-2.html#h-444664"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="page-2.html#h-444666"><span class="HTitleText1">Commencement</span></a>
</li></ul>
</li></ul>

</nav>

