<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur Téléfilm Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-67773"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-67778"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-67790"><span class="HTitleText1">Établissement de la Société Téléfilm Canada</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-67826"><span class="HTitleText1">Mission et pouvoirs</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-67857"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-67896"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-67928"><span class="HTitleText1">Vérification</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-67933"><span class="HTitleText1">Rapport au Parlement</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
