<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la responsabilité et l’indemnisation en matière nucléaire</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Désignation du ministre</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-7"><span class="HTitleText1">Désignation d’établissements nucléaires et d’exploitants</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-8"><span class="HTitleText1">Responsabilité à l’égard des accidents nucléaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Responsabilité de l’exploitant</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-10"><span class="HTitleText2">Dommages indemnisables</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText2">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-12"><span class="HTitleText2">Droits et obligations préservés</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-13"><span class="HTitleText2">Instances judiciaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>36 - </span><a href="#h-14"><span class="HTitleText1">Tribunal d’indemnisation en matière nucléaire</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>36 - </span><a href="#h-15"><span class="HTitleText2">Déclaration du gouverneur en conseil</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-16"><span class="HTitleText2">Rapport au Parlement</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-17"><span class="HTitleText2">Aide financière provisoire</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-18"><span class="HTitleText2">Constitution d’un tribunal d’indemnisation en matière nucléaire</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-19"><span class="HTitleText2">Attributions du Tribunal</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-20"><span class="HTitleText2">Demandes d’indemnisation</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-21"><span class="HTitleText2">Réexamen et appel</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-22"><span class="HTitleText2">Dispositions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-23"><span class="HTitleText1">Accords de réciprocité</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-24"><span class="HTitleText1">Autres obligations internationales</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-25"><span class="HTitleText1">Infraction et peine</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-26"><span class="HTitleText1">Règlements</span></a>
</li>
<li><a href="#h-27"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Convention sur la réparation complémentaire des dommages nucléaires</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
