<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Shipping Act, 2001</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-50746"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-50749"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-50792"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-50793"><span class="HTitleText2">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-50796"><span class="HTitleText2">Objectives</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-50808"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-50824"><span class="HTitleText2">Ministerial Responsibility</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-50827"><span class="HTitleText2">Powers of Ministers</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-50869"><span class="HTitleText2">Inspections by Marine Safety Inspectors and Others</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-50902"><span class="HTitleText2">Authorized Representative</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-50918"><span class="HTitleText2">Canadian Maritime Documents</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-51045"><span class="HTitleText2">Other Documents</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-51050"><span class="HTitleText2">General Prohibitions</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-51058"><span class="HTitleText2">Tonnage Measurers</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-51063"><span class="HTitleText2">Marine Technical Review Board</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-51117"><span class="HTitleText2">International Conventions, Protocols and Resolutions</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-51132"><span class="HTitleText2">Incorporation by Reference</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-51164"><span class="HTitleText2">Orders and Directions</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-51172"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-51232"><span class="HTitleText2">Fees</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-51273"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>41 - </span><a href="#h-51308"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Registration, Listing and Recording</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>41 - </span><a href="#h-51309"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-51312"><span class="HTitleText2">Canadian Register of Vessels and Registrars</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-51329"><span class="HTitleText2">Registration, Listing and Recording</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-51359"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-51365"><span class="HTitleText2">Names of Vessels</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-51379"><span class="HTitleText2">Ownership of Vessels</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-51399"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-51426"><span class="HTitleText2">Marking</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-51436"><span class="HTitleText2">Notifying Chief Registrar</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-51456"><span class="HTitleText2">Maintenance of Register</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-51459"><span class="HTitleText2">Suspension, Cancellation and Reinstatement of Registration</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-51482"><span class="HTitleText2">Custody of Certificates of Registry and Provisional Certificates</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-51492"><span class="HTitleText2">Rights and Obligations</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-51502"><span class="HTitleText2">Mortgages</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-51536"><span class="HTitleText2">Transfers of Vessels or Shares in Vessels</span></a>
</li>
<li><span class='sectionRange'>75.01 - </span><a href="#h-51545"><span class="HTitleText2">Fleets</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-51670"><span class="HTitleText2">Entries</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-51675"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-51692"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>80 - </span><a href="#h-51727"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Personnel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>80 - </span><a href="#h-51728"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-51731"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="#h-51734"><span class="HTitleText2">Masters</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-51749"><span class="HTitleText2">Stowaways and Other Persons</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-51752"><span class="HTitleText2">Contract of Employment</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-51760"><span class="HTitleText2">Liens and Claims</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-51779"><span class="HTitleText2">Certificates</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-51798"><span class="HTitleText2">Medical or Optometric Information</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-51812"><span class="HTitleText2">Articles of Agreement, Discharge and Record of Sea Service</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-51827"><span class="HTitleText2">Return of Crew Members</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-51837"><span class="HTitleText2">Births and Deaths</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-51851"><span class="HTitleText2">Obligation of Persons Who Provide Crew Members</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-51859"><span class="HTitleText2">Resolution of Disputes</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-51862"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-51880"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-51918"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Safety</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-51919"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-51922"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-51925"><span class="HTitleText2">Authorized Representatives</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-51936"><span class="HTitleText2">Masters</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-51960"><span class="HTitleText2">Crew</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-51969"><span class="HTitleText2">Passengers</span></a>
</li>
<li><span class='sectionRange'>116 - </span><a href="#h-51975"><span class="HTitleText2">Authorized Representatives, Masters, Crew Members and Other Persons</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-51986"><span class="HTitleText2">Construction of Vessels</span></a>
</li>
<li><span class='sectionRange'>120 - </span><a href="#h-51989"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-52023"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>125 - </span><a href="#h-52062"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Navigation Services</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>125 - </span><a href="#h-52063"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-52069"><span class="HTitleText2">Vessel Traffic Services</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-52106"><span class="HTitleText2">Aids to Navigation</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-52114"><span class="HTitleText2">Search and Rescue</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-52144"><span class="HTitleText2">Enforcement</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-52150"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-52169"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-52202"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Incidents, Accidents and Casualties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-52203"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-52251"><span class="HTitleText2">Obligations in Case of Collisions</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-52256"><span class="HTitleText2">Inquiry into Causes of Death</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-52272"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-52284"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-52299"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">[Repealed, 2019, c. 1, s. 146]</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-52393"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Pollution Prevention and Response — Department of Transport and Department of Fisheries and Oceans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>165 - </span><a href="#h-52394"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-52409"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-52417"><span class="HTitleText2">Discharges of Oil</span></a>
</li>
<li><span class='sectionRange'>167.1 - </span><a href="#h-1185908"><span class="HTitleText2">Oil Handling Facilities</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-52465"><span class="HTitleText2">Response Organizations</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-52508"><span class="HTitleText2">Advisory Councils</span></a>
</li>
<li><span class='sectionRange'>173 - </span><a href="#h-52524"><span class="HTitleText2">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-52527"><span class="HTitleText2">Pollution Response Officers</span></a>
</li>
<li><span class='sectionRange'>177 - </span><a href="#h-52594"><span class="HTitleText2">Detention of Vessels</span></a>
</li>
<li><span class='sectionRange'>180 - </span><a href="#h-52635"><span class="HTitleText2">Response Measures</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-52694"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-52702"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>185 - </span><a href="#h-52748"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Pollution Prevention — Department of Transport</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>185 - </span><a href="#h-52749"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-52761"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>187 - </span><a href="#h-52769"><span class="HTitleText2">Pollution Incidents</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-52774"><span class="HTitleText2">Directions to Vessels</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-52786"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-52807"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>194 - </span><a href="#h-52842"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Pleasure Craft</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>194 - </span><a href="#h-52843"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>195 - </span><a href="#h-52856"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-52908"><span class="HTitleText2">Investigations</span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-52911"><span class="HTitleText2">Safe Operation of Pleasure Craft</span></a>
</li>
<li><span class='sectionRange'>202 - </span><a href="#h-52914"><span class="HTitleText2">Pleasure Craft Licences</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-52931"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>208 - </span><a href="#h-52957"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>210 - </span><a href="#h-52979"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Enforcement — Department of Transport</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>210 - </span><a href="#h-52980"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-52989"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>213 - </span><a href="#h-53032"><span class="HTitleText2">Clearance</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-53037"><span class="HTitleText2">Voyage with a Person on Board without Their Consent</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-53040"><span class="HTitleText2">Reporting of Alleged Contraventions</span></a>
</li>
<li><span class='sectionRange'>219 - </span><a href="#h-53062"><span class="HTitleText2">Investigations</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-53079"><span class="HTitleText2">Analysis and Examination</span></a>
</li>
<li><span class='sectionRange'>222 - </span><a href="#h-53091"><span class="HTitleText2">Detention of Vessels</span></a>
</li>
<li><span class='sectionRange'>225 - </span><a href="#h-53133"><span class="HTitleText2">Sale of Vessels</span></a>
</li>
<li><span class='sectionRange'>227 - </span><a href="#h-53153"><span class="HTitleText2">Foreign Vessels in Contravention of International Conventions</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-53164"><span class="HTitleText2">Administrative Penalties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="#h-53165"><span class="HTitleText3">Interpretation</span></a>
</li>
<li><span class='sectionRange'>229 - </span><a href="#h-53170"><span class="HTitleText3">Assurances of Compliance and Notices of Violation</span></a>
</li>
<li><span class='sectionRange'>233 - </span><a href="#h-53264"><span class="HTitleText3">Choice of Proceedings</span></a>
</li>
<li><span class='sectionRange'>234 - </span><a href="#h-53267"><span class="HTitleText3">Recovery of Debts</span></a>
</li>
<li><span class='sectionRange'>236 - </span><a href="#h-53283"><span class="HTitleText3">Rules of Law about Violations</span></a>
</li>
<li><span class='sectionRange'>239 - </span><a href="#h-53293"><span class="HTitleText3">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>244 - </span><a href="#h-53331"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>245 - </span><a href="#h-53347"><span class="HTitleText2">Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>247 - </span><a href="#h-53371"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Miscellaneous</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>247 - </span><a href="#h-53372"><span class="HTitleText2">Goods</span></a>
</li>
<li><span class='sectionRange'>251 - </span><a href="#h-53395"><span class="HTitleText2">Stevedoring</span></a>
</li>
<li><span class='sectionRange'>252 - </span><a href="#h-53407"><span class="HTitleText2">Proof of Offences by Vessels</span></a>
</li>
<li><span class='sectionRange'>253 - </span><a href="#h-53415"><span class="HTitleText2">Offences</span></a>
</li>
<li><span class='sectionRange'>254 - </span><a href="#h-53423"><span class="HTitleText2">Due Diligence</span></a>
</li>
<li><span class='sectionRange'>255 - </span><a href="#h-53429"><span class="HTitleText2">Prohibitions on Conviction</span></a>
</li>
<li><span class='sectionRange'>256 - </span><a href="#h-53434"><span class="HTitleText2">Summary Conviction Proceedings</span></a>
</li>
<li><span class='sectionRange'>257 - </span><a href="#h-53442"><span class="HTitleText2">Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>259 - </span><a href="#h-53453"><span class="HTitleText2">Damage Occasioned by Foreign Vessels</span></a>
</li>
<li><span class='sectionRange'>260 - </span><a href="#h-53458"><span class="HTitleText2">Defence</span></a>
</li>
<li><span class='sectionRange'>261 - </span><a href="#h-53463"><span class="HTitleText2">Depositions in Legal Proceedings</span></a>
</li>
<li><span class='sectionRange'>262 - </span><a href="#h-53474"><span class="HTitleText2">Procedure</span></a>
</li>
<li><span class='sectionRange'>268 - </span><a href="#h-53495"><span class="HTitleText2">Application of Fines</span></a>
</li>
<li><span class='sectionRange'>268.1 - </span><a href="#h-53504"><span class="HTitleText2">Crown Liability</span></a>
</li>
<li><span class='sectionRange'>269 - </span><a href="#h-53509"><span class="HTitleText2">State of War or Armed Conflict</span></a>
</li></ul>
</li><li><span class='sectionRange'>270 - </span><a href="#h-53536"><span class="HLabel1">PART 13</span> - <span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>275 to 324 - </span><a href="#h-53566"><span class="HLabel1">PART 14</span> - <span class="HTitleText1">Consequential and Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>325 to 330 - </span><a href="#h-53568"><span class="HLabel1">PART 15</span> - <span class="HTitleText1">Amendments to the Shipping Conferences Exemption Act, 1987</span></a>
</li>
<li><span class='sectionRange'>331 - </span><a href="#h-53570"><span class="HLabel1">PART 16</span> - <span class="HTitleText1">Amendments to the Canadian Environmental Protection Act, 1999</span></a>
</li>
<li><span class='sectionRange'>332 - </span><a href="#h-53572"><span class="HLabel1">PART 17</span> - <span class="HTitleText1">Repeals and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>332 - </span><a href="#h-53573"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>334 - </span><a href="#h-53576"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-53583"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - International Conventions and Protocols — Minister of Transport</span></a>
</li>
<li><a href="#h-53621"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - International Conventions and Protocols — Minister of Fisheries and Oceans</span></a>
</li>
<li><a href="#h-1196301"><span class="scheduleLabel">SCHEDULE 3</span></a>
</li></ul>
</li></ul>

</nav>

