<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi concernant des paiements à une fiducie établie en vue de fournir du financement à des provinces et à des territoires pour le développement des collectivités</a></li></ul>

</nav>
</div></section>
