<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’immunité des États</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-429642"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-429647"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-429664"><span class="HTitleText1">Immunité de juridiction</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-429744"><span class="HTitleText1">Procédure et réparation</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-429823"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

