<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le gouvernement du territoire provisoire de Kanesatake</a><ul class="TocIndent"><li><span class='sectionRange'>24 - </span><a href="page-2.html#h-329952"><span class="HTitleText1">Modification de la Loi sur l’arpentage des terres du Canada</span></a>
</li>
<li><a href="page-3.html#h-329955"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Territoire provisoire de Kanesatake</span></a>
</li></ul>
</li></ul>

</nav>

