<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 2010 sur la convention fiscale Canada-Turquie</a><ul class="TocIndent"><li><a href="#h-56269"><span class="scheduleLabel">ANNEXE 1</span> <span class="scheduleTitleText"> - Accord entre le Canada et la République de Turquie en vue d’éviter les doubles impositions et de prévenir l’évasion fiscale en matière d’impôts sur le revenu et sur la fortune</span></a>
</li>
<li><a href="#h-56542"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Protocole</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
