<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Rouge National Urban Park Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-428278"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-428281"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-428294"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-428297"><span class="HTitleText1">Park Established</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-428300"><span class="HTitleText1">Management of the Park</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-428333"><span class="HTitleText1">Park Lands</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-428363"><span class="HTitleText1">Pollution Clean-up</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-428371"><span class="HTitleText1">Prohibited Activities</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-428397"><span class="HTitleText1">Agricultural Activities</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-428400"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-428462"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-428507"><span class="HTitleText1">Offences and Penalties</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-428704"><span class="HTitleText1">Non-Application of Statutory Instruments Act</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-428707"><span class="HTitleText1">Claim in Respect of Aboriginal Rights</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-428710"><span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-428711"><span class="HTitleText2">Canada Lands Surveys Act</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-428713"><span class="HTitleText2">Parks Canada Agency Act</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-428718"><span class="HTitleText2">Species at Risk Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-428720"><span class="HTitleText2">Environmental Violations Administrative Monetary Penalties Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-428722"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-428726"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Rouge National Urban Park</span></a>
</li></ul>
</li></ul>

</nav>

