<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur le cadre fédéral de prévention du suicide</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-232734"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-232737"><span class="HTitleText1">Cadre fédéral de prévention du suicide</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-232748"><span class="HTitleText1">Consultations</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-232751"><span class="HTitleText1">Rapport</span></a>
</li></ul>
</li></ul>

</nav>

