<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Northern Canada Power Commission Yukon Assets Disposal Authorization Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-365940"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-365943"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-365953"><span class="HTitleText1">Disposal of Assets</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-365974"><span class="HTitleText1">Financial Provisions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-365990"><span class="HTitleText1">Pension Rights</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-366009"><span class="HTitleText1">Agency Status</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-366012"><span class="HTitleText1">Consequential and Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-366013"><span class="HTitleText2">Northern Canada Power Commission Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>17 - </span><a href="#h-366019"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

