<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Postal Services Resumption and Continuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-395694"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-395697"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-395711"><span class="HTitleText1">Postal Services</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-395724"><span class="HTitleText1">Extension of Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-395747"><span class="HTitleText1">Mediator-Arbitrator</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-395787"><span class="HTitleText1">New Collective Agreements</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-395800"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-395812"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
