<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Coasting Trade Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-86288"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-86291"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-86338"><span class="HTitleText1">Regulation of Foreign Ships and Non-duty Paid Ships</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-2.html#h-86441"><span class="HTitleText1">Function and Powers of Agency</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-86451"><span class="HTitleText1">Unfair Practices</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-2.html#h-86459"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-2.html#h-86465"><span class="HTitleText1">Offences</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-86476"><span class="HTitleText1">Searches</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-86486"><span class="HTitleText1">Detention of Ship</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-3.html#h-86572"><span class="HTitleText1">Other Offences</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-3.html#h-86582"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>22 to 28 - </span><a href="page-3.html#h-86590"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="page-3.html#h-86592"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-3.html#h-86595"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

