<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Accessible Canada Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1153392"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1153395"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1153408"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1153411"><span class="HTitleText1">Designation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1153414"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-1153434"><span class="HTitleText1">Principles</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-1153444"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-1153464"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Minister’s Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-1153482"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Canadian Accessibility Standards Development Organization</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>17 - </span><a href="#h-1153483"><span class="HTitleText2">Establishment</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-1153491"><span class="HTitleText2">Mandate</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-1153499"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-1153512"><span class="HTitleText2">Minister</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-1153518"><span class="HTitleText2">Board of Directors</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-1153552"><span class="HTitleText2">Chair</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-1153560"><span class="HTitleText2">Chief Executive Officer</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-1153582"><span class="HTitleText2">Human Resources</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-1153585"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-1153590"><span class="HTitleText2">Annual Report</span></a>
</li></ul>
</li><li><span class='sectionRange'>37 - </span><a href="#h-1153596"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Accessibility Commissioner</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-1153632"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Duties of Regulated Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-1153633"><span class="HTitleText2">Regulated Entities That Carry On Broadcasting Undertakings</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-1153634"><span class="HTitleText3">Accessibility Plans — Requirements Under the <cite class="XRefExternalAct">Broadcasting Act</cite></span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-1153658"><span class="HTitleText3">Feedback</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-1153668"><span class="HTitleText3">Progress Reports</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-1153684"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-1153698"><span class="HTitleText3">Exemptions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-1153704"><span class="HTitleText3">Accessibility Plans — Regulations Under This Act</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-1153726"><span class="HTitleText3">Feedback</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-1153736"><span class="HTitleText3">Progress Reports</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-1153752"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-1153760"><span class="HTitleText2">Regulated Entities That Are Canadian Carriers or Telecommunications Service Providers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="#h-1153761"><span class="HTitleText3">Accessibility Plans — Requirements Under the <cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-1153784"><span class="HTitleText3">Feedback</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-1153794"><span class="HTitleText3">Progress Reports</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-1153810"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-1153824"><span class="HTitleText3">Exemptions</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-1153830"><span class="HTitleText3">Accessibility Plans — Regulations Under This Act</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-1153852"><span class="HTitleText3">Feedback</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-1153862"><span class="HTitleText3">Progress Reports</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-1153878"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-1153886"><span class="HTitleText2">Regulated Entities in the Transportation Network</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-1153887"><span class="HTitleText3">Accessibility Plans — Regulations Under the <cite class="XRefExternalAct">Canada Transportation Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-1153912"><span class="HTitleText3">Feedback</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-1153922"><span class="HTitleText3">Progress Reports</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-1153938"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-1153952"><span class="HTitleText3">Exemptions</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-1153958"><span class="HTitleText3">Accessibility Plans — Regulations Under This Act</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-1153983"><span class="HTitleText3">Feedback</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-1153993"><span class="HTitleText3">Progress Reports</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-1154009"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li><li><span class='sectionRange'>69 - </span><a href="#h-1154017"><span class="HTitleText2">Other Regulated Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>69 - </span><a href="#h-1154018"><span class="HTitleText3">Accessibility Plans — Regulations Under This Act</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-1154040"><span class="HTitleText3">Feedback</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-1154050"><span class="HTitleText3">Progress Reports</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-1154066"><span class="HTitleText3">Exemptions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-1154074"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-1154075"><span class="HTitleText2">Inspections</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-1154105"><span class="HTitleText2">Production Order</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-1154113"><span class="HTitleText2">Compliance Order</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-1154130"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="#h-1154257"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Remedies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>94 - </span><a href="#h-1154258"><span class="HTitleText2">Filing of Complaint</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-1154270"><span class="HTitleText2">Investigation</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-1154376"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-1154381"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Chief Accessibility Officer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-1154382"><span class="HTitleText2">Appointment</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-1154392"><span class="HTitleText2">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-1154398"><span class="HTitleText2">Duties and Functions</span></a>
</li></ul>
</li><li><span class='sectionRange'>117 - </span><a href="#h-1154415"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>117 - </span><a href="#h-1154416"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-1154484"><span class="HTitleText2">Miscellaneous</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-1154535"><span class="HTitleText2">National AccessAbility Week</span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-1154538"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Parliamentary Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="#h-1154539"><span class="HTitleText2">Definition and Application</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-1154553"><span class="HTitleText2">Parliamentary Powers, Privileges and Immunities</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-1154556"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-1154626"><span class="HTitleText2">Notification of Speakers</span></a>
</li></ul>
</li><li><span class='sectionRange'>147 - </span><a href="#h-1154658"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>147 - </span><a href="#h-1154659"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Radio-television and Telecommunications Commission Act</cite></span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-1154664"><span class="HTitleText2"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-1154679"><span class="HTitleText2"><cite class="XRefExternalAct">Parliamentary Employment and Staff Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-1154698"><span class="HTitleText2"><cite class="XRefExternalAct">Broadcasting Act</cite></span></a>
</li>
<li><span class='sectionRange'>162 - </span><a href="#h-1154708"><span class="HTitleText2"><cite class="XRefExternalAct">Telecommunications Act</cite></span></a>
</li>
<li><span class='sectionRange'>166 - </span><a href="#h-1154732"><span class="HTitleText2"><cite class="XRefExternalAct">Canada Transportation Act</cite></span></a>
</li>
<li><span class='sectionRange'>184 - </span><a href="#h-1154794"><span class="HTitleText2"><cite class="XRefExternalAct">Federal Public Sector Labour Relations Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-1154824"><span class="HTitleText2"><cite class="XRefExternalAct">Public Service Employment Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="#h-1154839"><span class="HLabel1">PART 11</span> - <span class="HTitleText1">Consequential and Coordinating Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="#h-1154840"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="#h-1154841"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>201 - </span><a href="#h-1154846"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>204 - </span><a href="#h-1154856"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>205 - </span><a href="#h-1154861"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>206 - </span><a href="#h-1154869"><span class="HLabel1">PART 12</span> - <span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

