<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la gestion des terres des premières nations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-5"><span class="HTitleText1">Mise en place du régime de gestion des terres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-6"><span class="HTitleText2">Code foncier et accord spécifique</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Vérification</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Consultation populaire et certification</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-9"><span class="HTitleText2">Entrée en vigueur du code foncier</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText2">Règles particulières : échec du mariage</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText1">Régime de gestion des terres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText2">Pouvoirs généraux de la première nation</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Textes législatifs</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-14"><span class="HTitleText2">Registre des terres des premières nations</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-15"><span class="HTitleText2">Restrictions en matière d’aliénation</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="#h-16"><span class="HTitleText1">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-17"><span class="HTitleText1">Immunité et contrôle judiciaire</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-18"><span class="HTitleText1">Cadre législatif</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-19"><span class="HTitleText1">Modification de l’annexe</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-20"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-21"><span class="HTitleText1">Modification conditionnelle</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-22"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-23"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Premières nations</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
