<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li class="liGold"><a title="Page 1" href="#">
Vocational Rehabilitation of Disabled Persons Act <span class='Repealed'>[Repealed,  2005, c. 35, s. 69]</span></a></li></ul>
</nav>
</div></section>
