<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi fédérale sur le paiement rapide des travaux de construction</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1155801"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1155804"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1155830"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1155833"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1155836"><span class="HTitleText1">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-1155860"><span class="HTitleText1">Paiements entre parties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="#h-1155861"><span class="HTitleText2">Sa Majesté ou fournisseur de services et entrepreneur</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-1155873"><span class="HTitleText2">Entrepreneur et sous-traitant</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-1155883"><span class="HTitleText2">Sous-traitant et autres sous-traitants</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-1155897"><span class="HTitleText2">Retenue</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-1155905"><span class="HTitleText2">Non-paiement</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-1155920"><span class="HTitleText2">Règlement des différends</span></a>
</li></ul>
</li><li><span class='sectionRange'>22 - </span><a href="#h-1155973"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-1155991"><span class="HTitleText1">Disposition transitoire</span></a>
</li></ul>
</li></ul>

</nav>

