<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la mise au point des pensions du service public</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-397927"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-397932"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-397950"><span class="HTitleText1">Calcul pour la mise au point des pensions</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-397998"><span class="HTitleText1">Généralités</span></a>
</li>
<li><a href="#h-398033"><span class="scheduleLabel">ANNEXE I</span></a>
</li>
<li><a href="#h-398047"><span class="scheduleLabel">SCHEDULE II — ANNEXE II</span></a>
</li>
<li><a href="#h-398056"><span class="scheduleLabel">ANNEXE III</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
