<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
The Manitoba Natural Resources Act</a><ul class="TocIndent"><li><a href="#h-448087"><span class="scheduleLabel">SCHEDULE</span> - <span class="scheduleTitleText"> - Memorandum of Agreement</span></a>
</li>
<li><a href="#h-448175"><span class="scheduleLabel">SCHEDULE</span> - <span class="scheduleTitleText"> - Agreement Between Canada, Ontario and Manitoba</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
