<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Railway Relocation and Crossing Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-426804"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-426809"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-426822"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Joint Urban Development and Transportation Plans</span></a>
</li>
<li><a href="#h-426918"><span class="HLabel1">PARTS II AND III</span> - <span class="HTitleText1">[Repealed, R.S., 1985, c. 32 (4th Supp.), s. 118]</span></a>
</li>
<li><a href="#h-426920"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Determining Net Costs of Railway Relocation</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
