<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’accès à l’information</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3.2 - </span><a href="#h-4"><span class="HTitleText1">Désignation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText1">Accès aux documents de l’administration fédérale</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-6"><span class="HTitleText2">Droit d’accès</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7"><span class="HTitleText2">Répertoire des institutions fédérales</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-8"><span class="HTitleText2">Demandes de communication</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">Exercice de l’accès</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText1">Exceptions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-11"><span class="HTitleText2">Responsabilités de l’État</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText2">Renseignements personnels</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText2">Renseignements de tiers</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText2">Activités du gouvernement</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-15"><span class="HTitleText2">Interdictions fondées sur d’autres lois</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText2">Refus de communication</span></a>
</li></ul>
</li><li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText1">Intervention de tiers</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-18"><span class="HTitleText1">Plaintes</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-19"><span class="HTitleText1">Enquêtes</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-20"><span class="HTitleText1">Rapports au Parlement</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-21"><span class="HTitleText1">Révision par la Cour fédérale</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-22"><span class="HTitleText1">Commissariat à l’information</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>54 - </span><a href="#h-23"><span class="HTitleText2">Commissaire à l’information</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-24"><span class="HTitleText2">Commissaires adjoints à l’information</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-25"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-26"><span class="HTitleText2">Délégation</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-27"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>67 - </span><a href="#h-28"><span class="HTitleText1">Infractions</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-29"><span class="HTitleText1">Exclusions</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-30"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-31"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Institutions fédérales</span></a>
</li>
<li><a href="#h-1217"><span class="scheduleLabel">ANNEXE II</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
