<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Worker Lockdown Benefit Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1334522"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1334525"><span class="HTitleText1">Definitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-1334548"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada Worker Lockdown Benefit</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-1334619"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">General</span></a>
</li></ul>
</li></ul>

</nav>

