<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Modernization of Benefits and Obligations Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-358398"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-358402"><span class="HTitleText1">Agricultural Marketing Programs Act</span></a>
</li>
<li><span class='sectionRange'>3 to 7 - </span><a href="#h-358404"><span class="HTitleText1">Bank Act</span></a>
</li>
<li><span class='sectionRange'>8 to 21 - </span><a href="#h-358406"><span class="HTitleText1">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>22 to 24 - </span><a href="#h-358408"><span class="HTitleText1">Bills of Exchange Act</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-358410"><span class="HTitleText1">Bridges Act</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-358412"><span class="HTitleText1">Business Development Bank of Canada Act</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-358414"><span class="HTitleText1">Canada Business Corporations Act</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-358416"><span class="HTitleText1">Canada Cooperatives Act</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-358418"><span class="HTitleText1">Canada Corporations Act</span></a>
</li>
<li><span class='sectionRange'>30 to 40 - </span><a href="#h-358420"><span class="HTitleText1">Canada Elections Act</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-358422"><span class="HTitleText1">Canada Mortgage and Housing Corporation Act</span></a>
</li>
<li><span class='sectionRange'>42 to 65 - </span><a href="#h-358424"><span class="HTitleText1">Canada Pension Plan</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-358426"><span class="HTitleText1">Canadian Forces Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-358430"><span class="HTitleText1">Canadian Peacekeeping Service Medal Act</span></a>
</li>
<li><span class='sectionRange'>70 to 72 - </span><a href="#h-358432"><span class="HTitleText1">Canadian Wheat Board Act</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-358434"><span class="HTitleText1">Carriage by Air Act</span></a>
</li>
<li><span class='sectionRange'>74 to 77 - </span><a href="#h-358436"><span class="HTitleText1">Citizenship Act</span></a>
</li>
<li><span class='sectionRange'>78 and 79 - </span><a href="#h-358438"><span class="HTitleText1">Civil Service Insurance Act</span></a>
</li>
<li><span class='sectionRange'>80 to 83 - </span><a href="#h-358440"><span class="HTitleText1">Civilian War-related Benefits Act</span></a>
</li>
<li><span class='sectionRange'>84 to 86 - </span><a href="#h-358442"><span class="HTitleText1">Cooperative Credit Associations Act</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-358444"><span class="HTitleText1">Corporations Returns Act</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-358446"><span class="HTitleText1">Corrections and Conditional Release Act</span></a>
</li>
<li><span class='sectionRange'>89 and 90 - </span><a href="#h-358448"><span class="HTitleText1">Cree-Naskapi (of Quebec) Act</span></a>
</li>
<li><span class='sectionRange'>91 to 95 - </span><a href="#h-358450"><span class="HTitleText1">Criminal Code</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-358452"><span class="HTitleText1">Customs Act</span></a>
</li>
<li><span class='sectionRange'>97 and 98 - </span><a href="#h-358454"><span class="HTitleText1">Defence Services Pension Continuation Act</span></a>
</li>
<li><span class='sectionRange'>99 to 105 - </span><a href="#h-358456"><span class="HTitleText1">Diplomatic Service (Special) Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>106 to 109 - </span><a href="#h-358458"><span class="HTitleText1">Employment Insurance Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-358460"><span class="HTitleText1">Escheats Act</span></a>
</li>
<li><span class='sectionRange'>111 to 114 - </span><a href="#h-358462"><span class="HTitleText1">Excise Tax Act</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-358464"><span class="HTitleText1">Family Orders and Agreements Enforcement Assistance Act</span></a>
</li>
<li><span class='sectionRange'>116 to 118 - </span><a href="#h-358466"><span class="HTitleText1">Firearms Act</span></a>
</li>
<li><span class='sectionRange'>119 - </span><a href="#h-358468"><span class="HTitleText1">Foreign Missions and International Organizations Act</span></a>
</li>
<li><span class='sectionRange'>120 and 121 - </span><a href="#h-358470"><span class="HTitleText1">Garnishment, Attachment and Pension Diversion Act</span></a>
</li>
<li><span class='sectionRange'>122 and 123 - </span><a href="#h-358472"><span class="HTitleText1">Government Annuities Act</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-358474"><span class="HTitleText1">Government Corporations Operation Act</span></a>
</li>
<li><span class='sectionRange'>125 and 126 - </span><a href="#h-358476"><span class="HTitleText1">Government Employees Compensation Act</span></a>
</li>
<li><span class='sectionRange'>127 to 129 - </span><a href="#h-358478"><span class="HTitleText1">Governor General’s Act</span></a>
</li>
<li><span class='sectionRange'>130 to 146 - </span><a href="#h-358480"><span class="HTitleText1">Income Tax Act</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-358482"><span class="HTitleText1">Income Tax Application Rules</span></a>
</li>
<li><span class='sectionRange'>148 to 152 - </span><a href="#h-358484"><span class="HTitleText1">Indian Act</span></a>
</li>
<li><span class='sectionRange'>153 to 158 - </span><a href="#h-358486"><span class="HTitleText1">Insurance Companies Act</span></a>
</li>
<li><span class='sectionRange'>159 to 169 - </span><a href="#h-358488"><span class="HTitleText1">Judges Act</span></a>
</li>
<li><span class='sectionRange'>170 to 175 - </span><a href="#h-358490"><span class="HTitleText1">Lieutenant Governors Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>176 to 186 - </span><a href="#h-358492"><span class="HTitleText1">Members of Parliament Retiring Allowances Act</span></a>
</li>
<li><span class='sectionRange'>187 to 191 - </span><a href="#h-358494"><span class="HTitleText1">Merchant Seamen Compensation Act</span></a>
</li>
<li><span class='sectionRange'>192 to 209 - </span><a href="#h-358496"><span class="HTitleText1">Old Age Security Act</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-358498"><span class="HTitleText1">Parliament of Canada Act</span></a>
</li>
<li><span class='sectionRange'>211 to 221 - </span><a href="#h-358500"><span class="HTitleText1">Pension Act</span></a>
</li>
<li><span class='sectionRange'>243 to 253 - </span><a href="#h-358504"><span class="HTitleText1">Pension Benefits Division Act</span></a>
</li>
<li><span class='sectionRange'>254 to 264 - </span><a href="#h-358506"><span class="HTitleText1">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>265 to 270 - </span><a href="#h-358508"><span class="HTitleText1">Pension Fund Societies Act</span></a>
</li>
<li><span class='sectionRange'>271 - </span><a href="#h-358510"><span class="HTitleText1">Public Pensions Reporting Act</span></a>
</li>
<li><span class='sectionRange'>272 to 274 - </span><a href="#h-358512"><span class="HTitleText1">Public Service Employment Act</span></a>
</li>
<li><span class='sectionRange'>275 to 277 - </span><a href="#h-358514"><span class="HTitleText1">Public Service Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>278 to 284 - </span><a href="#h-358516"><span class="HTitleText1">The Returned Soldiers’ Insurance Act</span></a>
</li>
<li><span class='sectionRange'>285 to 287 - </span><a href="#h-358518"><span class="HTitleText1">Royal Canadian Mounted Police Pension Continuation Act</span></a>
</li>
<li><span class='sectionRange'>288 to 290 - </span><a href="#h-358520"><span class="HTitleText1">Royal Canadian Mounted Police Superannuation Act</span></a>
</li>
<li><span class='sectionRange'>291 - </span><a href="#h-358522"><span class="HTitleText1">Special Import Measures Act</span></a>
</li>
<li><span class='sectionRange'>292 to 294 - </span><a href="#h-358524"><span class="HTitleText1">Special Retirement Arrangements Act</span></a>
</li>
<li><span class='sectionRange'>295 and 296 - </span><a href="#h-358526"><span class="HTitleText1">Supplementary Retirement Benefits Act</span></a>
</li>
<li><span class='sectionRange'>297 - </span><a href="#h-358528"><span class="HTitleText1">Trade Unions Act</span></a>
</li>
<li><span class='sectionRange'>298 to 302 - </span><a href="#h-358530"><span class="HTitleText1">Trust and Loan Companies Act</span></a>
</li>
<li><span class='sectionRange'>303 to 310 - </span><a href="#h-358532"><span class="HTitleText1">Veterans Insurance Act</span></a>
</li>
<li><span class='sectionRange'>311 to 314 - </span><a href="#h-358534"><span class="HTitleText1">Veterans’ Land Act</span></a>
</li>
<li><span class='sectionRange'>315 - </span><a href="#h-358536"><span class="HTitleText1">Veterans Review and Appeal Board Act</span></a>
</li>
<li><span class='sectionRange'>316 - </span><a href="#h-358538"><span class="HTitleText1">Visiting Forces Act</span></a>
</li>
<li><span class='sectionRange'>317 to 339 - </span><a href="#h-358540"><span class="HTitleText1">War Veterans Allowance Act</span></a>
</li>
<li><span class='sectionRange'>340 - </span><a href="#h-358542"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-358549"><span class="scheduleLabel">SCHEDULES 1 AND 2</span></a>
</li></ul>
</li></ul>

</nav>

