<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Régime de pensions du Canada</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-163383"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-163388"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-163466"><span class="HTitleText1">Application et effet de la loi</span></a>
</li>
<li><span class='sectionRange'>4.1 - </span><a href="#h-163500"><span class="HTitleText1">Moyens électroniques</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-163505"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Cotisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-163513"><span class="HLabel2">SECTION A</span> - <span class="HTitleText2">Cotisations payables</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>6 - </span><a href="#h-163514"><span class="HTitleText3">Emplois ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-163561"><span class="HTitleText3">Cotisations payées par les employés et les employeurs à l’égard de l’emploi ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-163653"><span class="HTitleText3">Cotisations versées par des personnes à l’égard des gains provenant du travail qu’elles exécutent pour leur propre compte</span></a>
</li></ul>
</li><li><span class='sectionRange'>11.1 - </span><a href="#h-163707"><span class="HLabel2">SECTION B</span> - <span class="HTitleText2">Calcul des cotisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11.1 - </span><a href="#h-163708"><span class="HTitleText3">Taux de cotisation</span></a>
</li>
<li><span class='sectionRange'>11.2 - </span><a href="#h-163719"><span class="HTitleText3">Premier taux de cotisation supplémentaire et deuxième taux de cotisation supplémentaire</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-163724"><span class="HTitleText3">Traitement et salaire cotisables</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-163751"><span class="HTitleText3">Gains cotisables provenant du travail qu’une personne exécute pour son propre compte</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-163839"><span class="HTitleText3">Traitement et salaire sur lesquels la cotisation est versée</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-163888"><span class="HTitleText3">Maximum des gains cotisables</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-163893"><span class="HTitleText3">Maximum des gains ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>17.1 - </span><a href="#h-163908"><span class="HTitleText3">Maximum supplémentaire des gains ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-163923"><span class="HTitleText3">Maximum des gains annuels ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-163956"><span class="HTitleText3">Maximum supplémentaire des gains annuels ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-163966"><span class="HTitleText3">Exemption de base</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-163992"><span class="HTitleText3">Exemption de base de l’année</span></a>
</li></ul>
</li><li><span class='sectionRange'>21 - </span><a href="#h-164000"><span class="HLabel2">SECTION C</span> - <span class="HTitleText2">Perception des cotisations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>21 - </span><a href="#h-164001"><span class="HTitleText3">Employés et employeurs</span></a>
</li>
<li><span class='sectionRange'>26.1 - </span><a href="#h-164146"><span class="HTitleText3">Décisions et appels</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-164207"><span class="HLabel2">SECTION D</span> - <span class="HTitleText2">Perception des cotisations à l’égard des gains provenant du travail qu’une personne exécute pour son propre compte</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-164283"><span class="HLabel2">SECTION E</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>38 - </span><a href="#h-164284"><span class="HTitleText3">Remboursement des versements excédentaires</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-164319"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-164342"><span class="HTitleText3">Infractions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-164368"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Pensions et prestations supplémentaires</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-164369"><span class="HTitleText2">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-164403"><span class="HTitleText2">Indice de pension</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-164413"><span class="HLabel2">SECTION A</span> - <span class="HTitleText2">Prestations payables</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-164501"><span class="HLabel2">SECTION B</span> - <span class="HTitleText2">Calcul des prestations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>45 - </span><a href="#h-164502"><span class="HTitleText3">Montant de base et ajustement annuel</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-164513"><span class="HTitleText3">Pension de retraite</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-164947"><span class="HTitleText3">Partage des gains non ajustés ouvrant droit à pension dans les cas de divorces et d’annulations de mariage ayant lieu avant l’entrée en vigueur de l’article 55.1</span></a>
</li>
<li><span class='sectionRange'>55.1 - </span><a href="#h-164976"><span class="HTitleText3">Partage des gains non ajustés ouvrant droit à pension</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-165080"><span class="HTitleText3">Pension d’invalidité</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="#h-165145"><span class="HTitleText3">Prestation de décès</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="#h-165177"><span class="HTitleText3">Pension de survivant</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-165351"><span class="HTitleText3">Prestation d’enfant de cotisant invalide et prestation d’orphelin</span></a>
</li>
<li><span class='sectionRange'>59.1 - </span><a href="#h-165362"><span class="HTitleText3">Prestation après-retraite</span></a>
</li>
<li><span class='sectionRange'>59.2 - </span><a href="#h-165434"><span class="HTitleText3">Prestation d’invalidité après-retraite</span></a>
</li></ul>
</li><li><span class='sectionRange'>60 - </span><a href="#h-165447"><span class="HLabel2">SECTION C</span> - <span class="HTitleText2">Paiement des prestations : dispositions générales</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-165690"><span class="HLabel2">SECTION D</span> - <span class="HTitleText2">Paiement des prestations : règles spéciales applicables</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>67 - </span><a href="#h-165691"><span class="HTitleText3">Pension de retraite</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-165731"><span class="HTitleText3">Pension d’invalidité et prestation d’invalidité après-retraite</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-165790"><span class="HTitleText3">Prestation de décès</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-165803"><span class="HTitleText3">Pension de survivant</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-165823"><span class="HTitleText3">Prestation d’enfant de cotisant invalide et prestation d’orphelin</span></a>
</li>
<li><span class='sectionRange'>76.1 - </span><a href="#h-165864"><span class="HTitleText3">Prestation après-retraite</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-165873"><span class="HLabel2">SECTION E</span> - <span class="HTitleText2">Paiement de prestations : montant payable selon le régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-165952"><span class="HLabel2">SECTION F</span> - <span class="HTitleText2">Révisions et appels</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-165985"><span class="HLabel2">SECTION G</span> - <span class="HTitleText2">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>89 - </span><a href="#h-166003"><span class="HTitleText3">Règlements</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-166032"><span class="HTitleText3">Infractions</span></a>
</li>
<li><span class='sectionRange'>90.1 - </span><a href="#h-166045"><span class="HTitleText3">Pénalités</span></a>
</li>
<li><span class='sectionRange'>90.2 - </span><a href="#h-166068"><span class="HTitleText3">Application et exécution</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>91 - </span><a href="#h-166110"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>91 - </span><a href="#h-166111"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-166120"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-166139"><span class="HTitleText2">Registres et renseignements</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-166233"><span class="HTitleText2">Accessibilité aux renseignements</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-166264"><span class="HTitleText2">Accords avec les provinces</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-166271"><span class="HTitleText2">Serments, affidavits, déclarations et affirmations</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-166284"><span class="HTitleText2">Accords réciproques avec d’autres pays</span></a>
</li>
<li><span class='sectionRange'>107.1 - </span><a href="#h-166299"><span class="HTitleText2">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>113.1 - </span><a href="#h-166428"><span class="HTitleText2">Révision financière du Régime de pensions du Canada</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-166561"><span class="HTitleText2">Modifications à la présente loi</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-166584"><span class="HTitleText2">Rapport de l’actuaire en chef</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-166623"><span class="HTitleText2">Rapport au Parlement et aux provinces</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-166638"><span class="HTitleText2">Employés de l’État</span></a>
</li></ul>
</li><li><a href="#h-166656"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-166666"><span class="scheduleLabel">ANNEXE 2</span> <span class="scheduleTitleText"> - Premiers et deuxièmes taux de cotisation supplémentaires</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
