<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Department of Natural Resources Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-364120"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-364123"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-364131"><span class="HTitleText1">Establishment of the Department</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-364139"><span class="HTitleText1">Powers, Duties and Functions of the Minister</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-364156"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-364162"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>11 to 36 - </span><a href="#h-364172"><span class="HTitleText1">Related Amendments</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-364174"><span class="HTitleText1">References</span></a>
</li>
<li><span class='sectionRange'>39 to 41 - </span><a href="#h-364183"><span class="HTitleText1">Repeals</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-364185"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
