<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada–Jordan Economic Growth and Prosperity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-147706"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-147709"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-147725"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-147728"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-147737"><span class="HTitleText1">Causes of Action</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-147743"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Implementation of the Agreement and the Related Agreements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-147744"><span class="HTitleText2">Approval</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-147747"><span class="HTitleText2">Administrative and Institutional Provisions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-147752"><span class="HTitleText2">Panels, Committees, Subcommittees, Working Groups and Expert Groups</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-147775"><span class="HTitleText2">Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-147785"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-147786"><span class="HTitleText2">Canadian International Trade Tribunal Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-1.html#h-147793"><span class="HTitleText2">Crown Liability and Proceedings Act</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-1.html#h-147796"><span class="HTitleText2">Customs Act</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-1.html#h-147805"><span class="HTitleText2">Customs Tariff</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-1.html#h-147815"><span class="HTitleText2">Department of Human Resources and Skills Development Act</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-1.html#h-147817"><span class="HTitleText2">Financial Administration Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>44 - </span><a href="page-1.html#h-147820"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Coordinating Amendments and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>44 - </span><a href="page-1.html#h-147821"><span class="HTitleText2">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-1.html#h-147824"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="page-2.html#h-147828"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="page-3.html#h-147831"><span class="scheduleLabel">SCHEDULE 2</span> </a>
</li>
<li><a href="page-4.html#h-147834"><span class="scheduleLabel">SCHEDULE 3</span> </a>
</li>
<li><a href="page-5.html#h-147837"><span class="scheduleLabel">SCHEDULE 4</span> </a>
</li>
<li><a href="page-6.html#h-147840"><span class="scheduleLabel">SCHEDULE 5</span> </a>
</li></ul>
</li></ul>

</nav>

