<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le Conseil de recherches en sciences humaines</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-423622"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-423627"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-423636"><span class="HTitleText1">Constitution du conseil</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-423641"><span class="HTitleText1">Mission et pouvoirs du conseil</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-423653"><span class="HTitleText1">Organisation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-423742"><span class="HTitleText1">Dispositions financières</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-423752"><span class="HTitleText1">Rapport au Parlement</span></a>
</li></ul>
</li></ul>

</nav>

