<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Centre for Management Development Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Establishment of the Centre</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Objects and Powers of the Centre</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-5"><span class="HTitleText1">Organization</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-6"><span class="HTitleText1">Officers and Employees</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-7"><span class="HTitleText2">Principal</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-8"><span class="HTitleText2">Other Officers and Employees</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-9"><span class="HTitleText1">Teaching and Research Services</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-10"><span class="HTitleText1">By-laws</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-11"><span class="HTitleText1">Fees</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-12"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-13"><span class="HTitleText1">Transitional</span></a>
</li>
<li><span class='sectionRange'>21 to 25 - </span><a href="#h-14"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-15"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
