<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les immeubles fédéraux et les biens réels fédéraux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-234405"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-234410"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-234440"><span class="HTitleText1">Délégation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-234445"><span class="HTitleText1">Disposition, location et permis</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-234450"><span class="HTitleText1">Concessions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-234512"><span class="HTitleText1">Application d’autres lois</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-234521"><span class="HTitleText1">Ministre de la Justice</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-234534"><span class="HTitleText1">Dispositions, acquisitions et transferts d’attributions administratives</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-234603"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>23 à 49 - </span><a href="#h-234632"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-234634"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-234636"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
