<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Federal Framework on Lyme Disease Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-238718"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-238721"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-238728"><span class="HTitleText1">Federal Framework on Lyme Disease</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-238738"><span class="HTitleText1">Review and Report</span></a>
</li></ul>
</li></ul>

</nav>

