<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Public Service Employment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Public Service Commission, Deputy Heads and Employer</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText2">Commission</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-5"><span class="HTitleText2">Mandate and Functions of Commission</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-6"><span class="HTitleText2">Delegation by Commission to Deputy Heads</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-7"><span class="HTitleText2">Commission Audits</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-8"><span class="HTitleText2">Exclusions from this Act</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-9"><span class="HTitleText2">Regulations of Commission</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-10"><span class="HTitleText2">Reports — Commission</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-11"><span class="HTitleText2">Deputy Heads</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-12"><span class="HTitleText2">Regulations and Policies of Employer</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-13"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Appointments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-14"><span class="HTitleText2">Authority to Appoint</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText2">Basis of Appointment</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-16"><span class="HTitleText2">Preferences, Priorities and Entitlements</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-17"><span class="HTitleText2">Informal Discussion and Appointment</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-18"><span class="HTitleText2">Casual Employment</span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="#h-19"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Deployments</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-20"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Employment</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-21"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Investigations and Complaints Relating to Appointments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>66 - </span><a href="#h-22"><span class="HTitleText2">Investigation of Appointments by Commission</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-23"><span class="HTitleText2">Complaints to Board — Revocation of Appointment</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-24"><span class="HTitleText2">Complaints to Board — Internal Appointments</span></a>
</li></ul>
</li><li><span class='sectionRange'>88 - </span><a href="#h-25"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Public Service Labour Relations and Employment Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>88 - </span><a href="#h-26"><span class="HTitleText2">Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-27"><span class="HTitleText2">Mediation Services</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-28"><span class="HTitleText2">Complaint Procedure</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-29"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-30"><span class="HTitleText2">Regulations</span></a>
</li></ul>
</li><li><span class='sectionRange'>111 - </span><a href="#h-31"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Political Activities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>111 - </span><a href="#h-32"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>112 - </span><a href="#h-33"><span class="HTitleText2">Purpose of Part</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-34"><span class="HTitleText2">Employees</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-35"><span class="HTitleText2">Deputy Heads</span></a>
</li>
<li><span class='sectionRange'>118 - </span><a href="#h-36"><span class="HTitleText2">Allegations</span></a>
</li></ul>
</li><li><span class='sectionRange'>123 - </span><a href="#h-37"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>123 - </span><a href="#h-38"><span class="HTitleText2">Application of Act</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-39"><span class="HTitleText2">Head of Public Service</span></a>
</li>
<li><span class='sectionRange'>127.1 - </span><a href="#h-40"><span class="HTitleText2">Deputy Ministers and Other Senior Officials</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-41"><span class="HTitleText2">Ministerial Staff</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-42"><span class="HTitleText2">Public Officials</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-43"><span class="HTitleText2">Diplomatic Personnel</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-44"><span class="HTitleText2">Block Transfers</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-45"><span class="HTitleText2">Offence</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-46"><span class="HTitleText2">Oaths and Affirmations</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-47"><span class="HTitleText2">Access to Facilities and Information</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-48"><span class="HTitleText2">Five-year Review</span></a>
</li></ul>
</li><li><a href="#h-404848"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Definitions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
