<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon First Nations Self-Government Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-3"><span class="HTitleText1">Purpose and Effect of this Act</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-4"><span class="HTitleText1">First Nation Constitutions</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-5"><span class="HTitleText1">First Nation Laws</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-6"><span class="HTitleText1">Administration of Justice</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">Laws of General Application</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText1">Disposition of Reserve Lands</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-9"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-10"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>33 to 39 - </span><a href="#h-11"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-12"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-474493"><span class="scheduleLabel">SCHEDULE I</span> </a>
</li>
<li><a href="#h-474503"><span class="scheduleLabel">SCHEDULE II</span> <span class="scheduleTitleText"> - First Nations Having Self-Government Agreements in Effect</span></a>
</li>
<li><a href="#h-474518"><span class="scheduleLabel">SCHEDULE III</span> <span class="scheduleTitleText"> - Legislative Powers</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
