<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Export and Import of Rough Diamonds Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-202530"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-202533"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-202546"><span class="HTitleText1">Ministerial Powers</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-202562"><span class="HTitleText1">Exporting Rough Diamonds</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-202593"><span class="HTitleText1">Importing Rough Diamonds</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-202616"><span class="HTitleText1">In-transit Rough Diamonds</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-1.html#h-202626"><span class="HTitleText1">Inspections</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-202648"><span class="HTitleText1">Investigations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="page-1.html#h-202653"><span class="HTitleText1">Disposition of Things Seized</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="page-2.html#h-202673"><span class="HTitleText1">Forfeiture</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="page-2.html#h-202687"><span class="HTitleText1">Liability for Costs</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="page-2.html#h-202693"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="page-2.html#h-202710"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="page-2.html#h-202761"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="page-3.html#h-202765"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Participants</span></a>
</li></ul>
</li></ul>

</nav>

