<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Addition of Lands to Reserves and Reserve Creation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-14"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-17"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-30"><span class="HTitleText1">Setting Apart of Lands</span></a>
</li></ul>
</li></ul>

</nav>

