<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Addition of Lands to Reserves and Reserve Creation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-14"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-17"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-27"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-30"><span class="HTitleText1">Setting Apart of Lands</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
