<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi de 1985 sur la représentation électorale</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-417317"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-417320"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Loi constitutionnelle de 1867</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-417324"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Révision des limites des circonscriptions électorales pour le recensement de 1981</span></a>
</li>
<li><span class='sectionRange'>5 à 11 - </span><a href="page-1.html#h-417330"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Loi sur la revision des limites des circonscriptions électorales</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-417334"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

