<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nunavut Planning and Project Assessment Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-3"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-4"><span class="HTitleText1">Consultation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-5"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Commission and Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-7"><span class="HTitleText2">Nunavut Planning Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-9"><span class="HTitleText3">Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HTitleText3">Meetings</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-11"><span class="HTitleText3">By-laws and Rules</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-12"><span class="HTitleText2">Nunavut Impact Review Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText3">Constitution</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-14"><span class="HTitleText3">Powers, Duties and Functions</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-15"><span class="HTitleText3">Meetings</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-16"><span class="HTitleText3">By-laws and Rules</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-17"><span class="HTitleText3">Panels</span></a>
</li></ul>
</li><li><span class='sectionRange'>28 - </span><a href="#h-18"><span class="HTitleText2">General Provisions — Commission and Board</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>28 - </span><a href="#h-19"><span class="HTitleText3">Members</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-20"><span class="HTitleText3">Staff</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-21"><span class="HTitleText3">Conflict of Interest</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-22"><span class="HTitleText3">Status and General Powers</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-23"><span class="HTitleText3">Head Office</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-24"><span class="HTitleText3">Languages</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-25"><span class="HTitleText3">By-laws and Rules</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-26"><span class="HTitleText3">Financial Provisions</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-27"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Land Use Planning</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-28"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-29"><span class="HTitleText2">Policies, Priorities and Objectives</span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-30"><span class="HTitleText2">Land Use Plans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>46 - </span><a href="#h-31"><span class="HTitleText3">General Provisions</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-32"><span class="HTitleText3">Development</span></a>
</li>
<li><span class='sectionRange'>59 - </span><a href="#h-33"><span class="HTitleText3">Amendment</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-34"><span class="HTitleText3">Periodic Review</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-35"><span class="HTitleText3">Implementation</span></a>
</li></ul>
</li><li><span class='sectionRange'>70 - </span><a href="#h-36"><span class="HTitleText2">Parks and Conservation Areas</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-37"><span class="HTitleText2">Municipalities</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-38"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Assessment of Projects to Be Carried Out in the Designated Area</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>73 - </span><a href="#h-39"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-40"><span class="HTitleText2">Compliance</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-41"><span class="HTitleText2">Review by Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-42"><span class="HTitleText3">Project Proposal</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-43"><span class="HTitleText3">Land Use Plan in Effect</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-44"><span class="HTitleText4">Determination</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-45"><span class="HTitleText4">Project in Conformity with Land Use Plan</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-46"><span class="HTitleText4">Project Not in Conformity with Land Use Plan</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-47"><span class="HTitleText4">Time Limit</span></a>
</li></ul>
</li><li><span class='sectionRange'>85 - </span><a href="#h-48"><span class="HTitleText3">No Land Use Plan</span></a>
</li></ul>
</li><li><span class='sectionRange'>86 - </span><a href="#h-49"><span class="HTitleText2">Screening by Board</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-50"><span class="HTitleText2">Review</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>99 - </span><a href="#h-51"><span class="HTitleText3">Board</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-52"><span class="HTitleText3">Federal Environmental Assessment Panel</span></a>
</li></ul>
</li><li><span class='sectionRange'>134 - </span><a href="#h-53"><span class="HTitleText2">Project Terms and Conditions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>134 - </span><a href="#h-54"><span class="HTitleText3">Compatibility</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-55"><span class="HTitleText3">Monitoring Programs</span></a>
</li>
<li><span class='sectionRange'>136 - </span><a href="#h-56"><span class="HTitleText3">Implementation</span></a>
</li></ul>
</li><li><span class='sectionRange'>141 - </span><a href="#h-57"><span class="HTitleText2">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>141 - </span><a href="#h-58"><span class="HTitleText3">Modifications to Project During Assessment</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-59"><span class="HTitleText3">Requests During Assessment</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-60"><span class="HTitleText3">Modifications to Project After Assessment</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-61"><span class="HTitleText3">Projects Not Carried Out</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-62"><span class="HTitleText3">Consultations</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-63"><span class="HTitleText3">Multiple Responsible Ministers</span></a>
</li>
<li><span class='sectionRange'>150 - </span><a href="#h-64"><span class="HTitleText3">Reasons for Decisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>151 - </span><a href="#h-65"><span class="HTitleText2">Special Cases</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>151 - </span><a href="#h-66"><span class="HTitleText3">National Security</span></a>
</li>
<li><span class='sectionRange'>152 - </span><a href="#h-67"><span class="HTitleText3">Emergency Situations</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-68"><span class="HTitleText3">Community Resupply and Ship Movements</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-69"><span class="HTitleText3">Exploration, Developmental or Development Activities</span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-70"><span class="HTitleText3">Transboundary Projects</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-71"><span class="HTitleText4">Review by Commission</span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-72"><span class="HTitleText4">Screening by Board</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-73"><span class="HTitleText4">Review</span></a>
</li></ul>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>158 - </span><a href="#h-74"><span class="HTitleText5">Board</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-75"><span class="HTitleText5">Federal Environmental Assessment Panel or Joint Panel</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-76"><span class="HTitleText3">Parks and Conservation Areas</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>163 - </span><a href="#h-77"><span class="HTitleText4">Projects</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>173 - </span><a href="#h-78"><span class="HTitleText4">Establishment, Abolition and Alteration of Area</span></a>
</li></ul>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-79"><span class="HTitleText5">Interpretation</span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-80"><span class="HTitleText5">Proposal</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-81"><span class="HTitleText5">Land Use Plan in Effect</span></a>
</li>
<li><span class='sectionRange'>181 - </span><a href="#h-82"><span class="HTitleText5">No Land Use Plan</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-83"><span class="HTitleText5">Applicable Regime</span></a>
</li>
<li><span class='sectionRange'>183 - </span><a href="#h-84"><span class="HTitleText5">Previous Work</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>184 - </span><a href="#h-85"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Review of Projects to Be Carried Out Outside the Designated Area</span></a>
</li>
<li><span class='sectionRange'>189 - </span><a href="#h-86"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">General Provisions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>189 - </span><a href="#h-87"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>190 - </span><a href="#h-88"><span class="HTitleText2">Standing During Assessment</span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-89"><span class="HTitleText2">Coordination of Activities</span></a>
</li>
<li><span class='sectionRange'>197 - </span><a href="#h-90"><span class="HTitleText2">Information and Documents</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>197 - </span><a href="#h-91"><span class="HTitleText3">Obtaining Information</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-92"><span class="HTitleText3">Use of Information</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-93"><span class="HTitleText3">Communication of Information and Documents</span></a>
</li></ul>
</li><li><span class='sectionRange'>207 - </span><a href="#h-94"><span class="HTitleText2">Rights Preserved</span></a>
</li>
<li><span class='sectionRange'>209 - </span><a href="#h-95"><span class="HTitleText2">Administration and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>209 - </span><a href="#h-96"><span class="HTitleText3">Designation</span></a>
</li>
<li><span class='sectionRange'>210 - </span><a href="#h-97"><span class="HTitleText3">Powers</span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-98"><span class="HTitleText3">Orders</span></a>
</li>
<li><span class='sectionRange'>215 - </span><a href="#h-99"><span class="HTitleText3">Coordination</span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-100"><span class="HTitleText3">Injunction</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-101"><span class="HTitleText3">Prohibitions, Offences and Punishment</span></a>
</li></ul>
</li><li><span class='sectionRange'>220 - </span><a href="#h-102"><span class="HTitleText2">Judicial Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>220 - </span><a href="#h-103"><span class="HTitleText3">Court Jurisdiction</span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-104"><span class="HTitleText3">Immunity</span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-105"><span class="HTitleText3">Time Limits</span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-106"><span class="HTitleText2">General Monitoring</span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-107"><span class="HTitleText2">Regulations and Orders</span></a>
</li></ul>
</li><li><span class='sectionRange'>231 - </span><a href="#h-108"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><a href="#h-109"><span class="scheduleLabel">SCHEDULE 1</span> </a>
</li>
<li><a href="#h-110"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Designated Regulatory Agencies</span></a>
</li>
<li><a href="#h-111"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Classes of Works and Activities Exempt from Screening</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
