<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les avantages destinés aux anciens combattants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-451445"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-451450"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-451465"><span class="HTitleText1">Loi sur les indemnités de service de guerre</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-451511"><span class="HTitleText1">Loi sur les terres destinées aux anciens combattants</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-451526"><span class="HTitleText1">Loi sur l’assurance des anciens combattants</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-451552"><span class="HTitleText1">Loi sur l’emploi dans la fonction publique</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
