<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la croissance économique et la prospérité — Canada-Honduras</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-142595"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-142598"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-142614"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-142617"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-142628"><span class="HTitleText1">Droit de poursuite</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-142634"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Mise en oeuvre de l’accord et des accords connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>9 - </span><a href="page-1.html#h-142635"><span class="HTitleText2">Approbation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-142638"><span class="HTitleText2">Dispositions institutionnelles et administratives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-142643"><span class="HTitleText2">Groupes spéciaux, comités, sous-comités, groupes de travail et groupes d’experts</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-1.html#h-142666"><span class="HTitleText2">Décrets</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="page-1.html#h-142676"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Modifications connexes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>16 - </span><a href="page-1.html#h-142677"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la responsabilité civile de l’État et le contentieux administratif</cite></span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-1.html#h-142679"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les licences d’exportation et d’importation</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-142683"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur la gestion des finances publiques</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="page-1.html#h-142685"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’importation des boissons enivrantes</cite></span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-1.html#h-142688"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur les douanes</cite></span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="page-1.html#h-142696"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur l’arbitrage commercial</cite></span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-1.html#h-142698"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le Tribunal canadien du commerce extérieur</cite></span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-1.html#h-142707"><span class="HTitleText2"><cite class="XRefExternalAct">Tarif des douanes</cite></span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-1.html#h-142718"><span class="HTitleText2"><cite class="XRefExternalAct">Loi sur le ministère de l’Emploi et du Développement social</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>51 - </span><a href="page-1.html#h-142721"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Dispositions de coordination et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>51 - </span><a href="page-1.html#h-142722"><span class="HTitleText2">Dispositions de coordination</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-1.html#h-142725"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="page-2.html#h-142729"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="page-3.html#h-142732"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>

