<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l'extraction du quartz dans le Yukon</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>1.1 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-3"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Cession des droits miniers de la Couronne</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-4"><span class="HTitleText2">DÉFINITIONS</span></a>
</li></ul>
</li><li><span class='sectionRange'>3 - </span><a href="#h-5"><span class="HTitleText1">Fonctions du registraire minier</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-6"><span class="HTitleText1">Droit d’acquérir des claims miniers</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-7"><span class="HTitleText1">Dimensions des claims miniers et nombre qui peut être acquis</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-8"><span class="HTitleText1">Manière de jalonner un claim minier</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-9"><span class="HTitleText1">Enlèvement ou détérioration des bornes</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-10"><span class="HTitleText1">Enregistrement</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-11"><span class="HTitleText1">Abandon</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-12"><span class="HTitleText1">Groupement</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-13"><span class="HTitleText1">Travaux</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-14"><span class="HTitleText1">Différends</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-15"><span class="HTitleText1">Titre</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-16"><span class="HTitleText1">Droit adverse</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="#h-17"><span class="HTitleText1">Adresse pour signification</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-18"><span class="HTitleText1">Ce que comporte l’inscription ou bail</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-19"><span class="HTitleText1">Arpentages</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-20"><span class="HTitleText1">Transfert d’un claim minier</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-21"><span class="HTitleText1">Redevance</span></a>
</li>
<li><span class='sectionRange'>101 - </span><a href="#h-22"><span class="HTitleText1">Durée du bail et loyer</span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-23"><span class="HTitleText1">Autorisation de l’accès</span></a>
</li>
<li><span class='sectionRange'>113 - </span><a href="#h-24"><span class="HTitleText1">Administration des biens de mineurs décédés ou déments</span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-25"><span class="HTitleText1">Emplacements d’usines</span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-26"><span class="HTitleText1">Égouts et canaux souterrains</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-27"><span class="HTitleText1">Droits de prise d’eau</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-28"><span class="HTitleText1">Divers</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-29"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Utilisation et remise en état des terres</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="#h-30"><span class="HTitleText2">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-31"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-32"><span class="HTitleText2">Programmes d’exploration</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-33"><span class="HTitleText2">Développement et production</span></a>
</li>
<li><span class='sectionRange'>142 - </span><a href="#h-34"><span class="HTitleText2">Demandes</span></a>
</li>
<li><span class='sectionRange'>143 - </span><a href="#h-35"><span class="HTitleText2">Garantie</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-36"><span class="HTitleText2">Modification par l’inspecteur des programmes d’exploration de type II</span></a>
</li>
<li><span class='sectionRange'>145 - </span><a href="#h-37"><span class="HTitleText2">Modification et renouvellement des plans d’exploitation et des permis</span></a>
</li>
<li><span class='sectionRange'>147 - </span><a href="#h-38"><span class="HTitleText2">Cession</span></a>
</li>
<li><span class='sectionRange'>148 - </span><a href="#h-39"><span class="HTitleText2">Inspection et contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>153 - </span><a href="#h-40"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-41"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><a href="#h-42"><span class="scheduleLabel">ANNEXE I</span></a>
</li>
<li><a href="#h-43"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Droits</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
