<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Motor Vehicle Fuel Consumption Standards Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-358633"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-358638"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-358657"><span class="HTitleText1">Fuel Consumption Standards</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-358678"><span class="HTitleText1">Prohibitions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-358692"><span class="HTitleText1">Registration of Fuel Consumption Numbers</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-358724"><span class="HTitleText1">Calculation of Company Average Fuel Consumption</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-358741"><span class="HTitleText1">Enforcement of Fuel Consumption Standards</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-358802"><span class="HTitleText1">Exemption from Fuel Consumption Standard</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-358832"><span class="HTitleText1">National Fuel Consumption Marks</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-358859"><span class="HTitleText1">Records</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-358875"><span class="HTitleText1">Test Vehicles</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-358890"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-358922"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-358955"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-358990"><span class="HTitleText1">Correction of Defects</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-359015"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-359022"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-359027"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
