<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Security and Intelligence Review Agency Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1169766"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1169769"><span class="HTitleText1">Definitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-1169789"><span class="HTitleText1">Review Agency and Members</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-1169825"><span class="HTitleText1">Mandate</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-1169848"><span class="HTitleText1">Access to Information</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="page-1.html#h-1169871"><span class="HTitleText1">Review Body</span></a>
</li>
<li><span class='sectionRange'>15.1 - </span><a href="page-2.html#h-1169884"><span class="HTitleText1">Coordination</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="page-2.html#h-1169890"><span class="HTitleText1">Complaints</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-1169924"><span class="HTitleText1">Informal Resolution</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-2.html#h-1169930"><span class="HTitleText1">Investigations</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="page-2.html#h-1169961"><span class="HTitleText1">Departmental Study</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="page-2.html#h-1169967"><span class="HTitleText1">Reports to Ministers</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="page-3.html#h-1170000"><span class="HTitleText1">Public Reports</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="page-3.html#h-1170016"><span class="HTitleText1">Secretariat</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="page-3.html#h-1170059"><span class="HTitleText1">Security and Confidentiality</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-3.html#h-1170080"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="page-3.html#h-1170083"><span class="HTitleText1">Governor in Council Powers</span></a>
</li></ul>
</li></ul>

</nav>

