<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
National Security Act, 2017</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1158652"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1158655"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">National Security and Intelligence Review Agency</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-1158656"><span class="HTitleText2"><cite class="XRefExternalAct">National Security and Intelligence Review Agency Act</cite></span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1158660"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-1158714"><span class="HTitleText2">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>18 - </span><a href="#h-1158715"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-1158722"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-1158727"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-1158742"><span class="HTitleText3"><cite class="XRefExternalAct">Citizenship Act</cite></span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-1158756"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-1158777"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Human Rights Act</cite></span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-1158789"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>37.1 - </span><a href="#h-1158803"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-1158815"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-1158820"><span class="HTitleText3"><cite class="XRefExternalAct">Royal Canadian Mounted Police Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-1158829"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>46 - </span><a href="#h-1158837"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-1158844"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>49.1 - </span><a href="#h-1158891"><span class="HLabel1">PART 1.1</span> - <span class="HTitleText1">Avoiding Complicity in Mistreatment by Foreign Entities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>49.1 - </span><a href="#h-1158892"><span class="HTitleText2"><cite class="XRefExternalAct">Avoiding Complicity in Mistreatment by Foreign Entities Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>49.2 - </span><a href="#h-1158896"><span class="HTitleText1">Coordinating Amendments</span></a>
</li>
<li><span class='sectionRange'>50 - </span><a href="#h-1158907"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Intelligence Commissioner</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>50 - </span><a href="#h-1158908"><span class="HTitleText2"><cite class="XRefExternalAct">Intelligence Commissioner Act</cite></span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-1158912"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-1158942"><span class="HTitleText2">Related and Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>60 - </span><a href="#h-1158943"><span class="HTitleText3"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-1158948"><span class="HTitleText3"><cite class="XRefExternalAct">Canada Evidence Act</cite></span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-1158952"><span class="HTitleText3"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="#h-1158957"><span class="HTitleText3"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-1158974"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-1158979"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-1158984"><span class="HTitleText3"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-1158989"><span class="HTitleText3"><cite class="XRefExternalAct">Public Service Superannuation Act</cite></span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-1158994"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Canada Information Disclosure Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>74 - </span><a href="#h-1158999"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>76 - </span><a href="#h-1159015"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Communications Security Establishment</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>76 - </span><a href="#h-1159016"><span class="HTitleText2"><cite class="XRefExternalAct">Communications Security Establishment Act</cite></span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-1159020"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-1159056"><span class="HTitleText2"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-1159064"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>84 - </span><a href="#h-1159065"><span class="HTitleText3"><cite class="XRefExternalAct">National Defence Act</cite></span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-1159069"><span class="HTitleText3"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-1159078"><span class="HTitleText3"><cite class="XRefExternalAct">Proceeds of Crime (Money Laundering) and Terrorist Financing Act</cite></span></a>
</li>
<li><span class='sectionRange'>89 - </span><a href="#h-1159083"><span class="HTitleText3"><cite class="XRefExternalAct">Security of Canada Information Disclosure Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>90 - </span><a href="#h-1159088"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>92 - </span><a href="#h-1159101"><span class="HLabel1">PART 4</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Canadian Security Intelligence Service Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>92 - </span><a href="#h-1159104"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>110 - </span><a href="#h-1159158"><span class="HTitleText2">Transitional Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>112 - </span><a href="#h-1159166"><span class="HLabel1">PART 5</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Security of Canada Information Sharing Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>112 - </span><a href="#h-1159169"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>121 - </span><a href="#h-1159210"><span class="HTitleText2">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>121 - </span><a href="#h-1159211"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>122 - </span><a href="#h-1159216"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Fisheries and Oceans Act</cite></span></a>
</li>
<li><span class='sectionRange'>123 - </span><a href="#h-1159221"><span class="HTitleText3"><cite class="XRefExternalAct">Customs Act</cite></span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-1159226"><span class="HTitleText3"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>125 - </span><a href="#h-1159231"><span class="HTitleText3"><cite class="XRefExternalAct">Chemical Weapons Convention Implementation Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-1159236"><span class="HTitleText3"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>127 - </span><a href="#h-1159241"><span class="HLabel1">PART 6</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Secure Air Travel Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>127 - </span><a href="#h-1159244"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>139 - </span><a href="#h-1159285"><span class="HTitleText2">Transitional Provision</span></a>
</li></ul>
</li><li><span class='sectionRange'>140 - </span><a href="#h-1159288"><span class="HLabel1">PART 7</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Criminal Code</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>140 - </span><a href="#h-1159291"><span class="HTitleText2">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>155 - </span><a href="#h-1159334"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>157.1 - </span><a href="#h-1159341"><span class="HTitleText2">Section 83.3 of the <cite class="XRefExternalAct">Criminal Code</cite></span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-1159344"><span class="HTitleText2">Consequential Amendment to the <cite class="XRefExternalAct">Corrections and Conditional Release Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>159 - </span><a href="#h-1159349"><span class="HLabel1">PART 8</span></span> - <span class="HTitleText1"><cite class="XRefExternalAct">Youth Criminal Justice Act</cite></span></a>
</li>
<li><span class='sectionRange'>168 - </span><a href="#h-1159379"><span class="HLabel1">PART 9</span> - <span class="HTitleText1">Review</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-1159397"><span class="HLabel1">PART 10</span> - <span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-1159419"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

