<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Yukon First Nations Land Claims Settlement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-474088"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-474091"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-474099"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-474102"><span class="HTitleText1">Land Claims Agreements</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-474114"><span class="HTitleText1">Effect of Agreements</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-474124"><span class="HTitleText1">Boards, Commissions and Councils</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-474148"><span class="HTitleText1">Application of Laws and Agreements</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-474164"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-474167"><span class="HTitleText1">Deposit</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-474176"><span class="HTitleText1">Consultation</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-474179"><span class="HTitleText1">Powers of Governor in Council</span></a>
</li>
<li><span class='sectionRange'>18 and 19 - </span><a href="#h-474182"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-474188"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-474196"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>

