<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nunavik Inuit Land Claims Agreement Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-369616"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-369619"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-369626"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-369629"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-369647"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-369650"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-369688"><span class="HTitleText1">Consequential Amendments to the Canada National Parks Act</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-369691"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

