<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
United Nations Declaration on the Rights of Indigenous Peoples Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1301574"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-1301577"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-1301588"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-1301591"><span class="HTitleText1">Purposes of Act</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-1301596"><span class="HTitleText1">Measures for Consistency of Laws and Achieving the Objectives of the Declaration</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-1301616"><span class="HTitleText1">Report to Parliament</span></a>
</li>
<li><a href="#h-1301627"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - United Nations Declaration on the Rights of Indigenous Peoples</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
