<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Aviation Industry Indemnity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-7336"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-7339"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-7357"><span class="HTitleText1">Undertaking</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7386"><span class="HTitleText1">Claim for Indemnification</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-7412"><span class="HTitleText1">Assessment and Report</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7422"><span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

