<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le recyclage des produits de la criminalité et le financement des activités terroristes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Tenue de documents et déclaration des opérations douteuses</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Tenue et conservation de documents</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Déclaration</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Déclaration des espèces et effets</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>12 - </span><a href="#h-10"><span class="HTitleText2">Déclaration</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Rétention</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText2">Fouilles et perquisitions</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText2">Saisie</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-14"><span class="HTitleText2">Courrier destiné à l’exportation</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-15"><span class="HTitleText2">Remise</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-16"><span class="HTitleText2">Confiscation</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-17"><span class="HTitleText2">Révision et appel</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-18"><span class="HTitleText2">Revendication des tiers</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-19"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-20"><span class="HTitleText2">Accords de réciprocité</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-21"><span class="HTitleText2">Délégation</span></a>
</li></ul>
</li><li><span class='sectionRange'>40 - </span><a href="#h-22"><span class="HLabel1">PARTIE 3</span> - <span class="HTitleText1">Centre d’analyse des opérations et déclarations financières du Canada</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>40 - </span><a href="#h-23"><span class="HTitleText2">Objet</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-24"><span class="HTitleText2">Constitution du Centre</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-25"><span class="HTitleText2">Organisation et siège</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-26"><span class="HTitleText2">Gestion des ressources humaines</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-27"><span class="HTitleText2">Accord de service</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-28"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-29"><span class="HTitleText2">Rapports et renseignements</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-30"><span class="HTitleText2">Communication et utilisation des renseignements</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-31"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-32"><span class="HTitleText2">Contrats et autres accords</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-33"><span class="HTitleText2">Procédures judiciaires</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-34"><span class="HTitleText2">Vérification</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-35"><span class="HTitleText2">Rapports</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-36"><span class="HLabel1">PARTIE 4</span> - <span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-37"><span class="HLabel1">PARTIE 5</span> - <span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-38"><span class="HLabel1">PARTIE 6</span> - <span class="HTitleText1">Disposition transitoire, modifications corrélatives et conditionnelles, abrogation et entrée en vigueur</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>83 - </span><a href="#h-39"><span class="HTitleText2">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>84 à 96 - </span><a href="#h-40"><span class="HTitleText2">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>97 - </span><a href="#h-41"><span class="HTitleText2">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-42"><span class="HTitleText2">Abrogation</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-43"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
