<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le parc urbain national de la Rouge</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-418150"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-418153"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-418166"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-418169"><span class="HTitleText1">Création du parc</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-418172"><span class="HTitleText1">Gestion du parc</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-418205"><span class="HTitleText1">Terrains</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-418235"><span class="HTitleText1">Dépollution</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-418243"><span class="HTitleText1">Activités interdites</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-418269"><span class="HTitleText1">Activités agricoles</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-418272"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-418334"><span class="HTitleText1">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-418375"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-418572"><span class="HTitleText1">Non-application de la Loi sur les textes réglementaires</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-418575"><span class="HTitleText1">Revendications en matière de droits ancestraux</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-418578"><span class="HTitleText1">Modifications corrélatives</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>55 - </span><a href="#h-418579"><span class="HTitleText2">Loi sur l’arpentage des terres du Canada</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-418581"><span class="HTitleText2">Loi sur l’Agence Parcs Canada</span></a>
</li>
<li><span class='sectionRange'>60 - </span><a href="#h-418586"><span class="HTitleText2">Loi sur les espèces en péril</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-418588"><span class="HTitleText2">Loi sur les pénalités administratives en matière d’environnement</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-418590"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-21"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Parc urbain national de la Rouge</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
