<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les dispositifs émettant des radiations</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-410151"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-410156"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-410176"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-410183"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-410202"><span class="HTitleText1">Notification</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-410217"><span class="HTitleText1">Exécution et contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-410267"><span class="HTitleText1">Disposition des dispositifs avec le consentement du propriétaire</span></a>
</li>
<li><span class='sectionRange'>12.1 - </span><a href="#h-410278"><span class="HTitleText1">Confiscation</span></a>
</li>
<li><span class='sectionRange'>12.2 - </span><a href="#h-410290"><span class="HTitleText1">Retrait ou confiscation d’importations illégales</span></a>
</li>
<li><span class='sectionRange'>12.3 - </span><a href="#h-410306"><span class="HTitleText1">Frais</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-410321"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-410346"><span class="HTitleText1">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-410368"><span class="HTitleText1">Infractions et peines</span></a>
</li></ul>
</li></ul>

</nav>

