<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les licences d'exportation et d'importation</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Établissement de listes de contrôle</span></a>
</li>
<li><span class='sectionRange'>6.1 - </span><a href="#h-4"><span class="HTitleText1">Mesures d’urgence bilatérales : produits textiles et vêtements</span></a>
</li>
<li><span class='sectionRange'>6.2 - </span><a href="#h-5"><span class="HTitleText1">Régime d’accès</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-6"><span class="HTitleText1">Licences et certificats</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText1">Interdictions</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-9"><span class="HTitleText1">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-10"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-11"><span class="HTitleText1">Rapport au Parlement</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
