<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canadian Bill of Rights</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-61447"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Bill of Rights</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-61477"><span class="HTitleText1">Part II</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
