<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Income Tax Conventions Implementation Act, 1997</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-324174"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-324177"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada — Sweden Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-324193"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Canada — Lithuania Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-324209"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Canada — Kazakhstan Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="page-1.html#h-324225"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Canada — Iceland Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="page-1.html#h-324241"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Canada — Denmark Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>32 and 33 - </span><a href="page-1.html#h-324257"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Canada — Netherlands Income Tax Convention</span></a>
</li>
<li><span class='sectionRange'>34 and 35 - </span><a href="page-1.html#h-324259"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Canada — United States Tax Convention</span></a>
</li>
<li><a href="page-2.html#h-324262"><span class="scheduleLabel">SCHEDULE 1</span> <span class="scheduleTitleText"> - Convention Between Canada and Sweden for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income</span></a>
</li>
<li><a href="page-3.html#h-324566"><span class="scheduleLabel">SCHEDULE 2</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Republic of Lithuania for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-4.html#h-324879"><span class="scheduleLabel">SCHEDULE 3</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Republic of Kazakhstan for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-5.html#h-325163"><span class="scheduleLabel">SCHEDULE 4</span> <span class="scheduleTitleText"> - Convention Between Canada and the Republic of Iceland for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-6.html#h-325457"><span class="scheduleLabel">SCHEDULE 5</span> <span class="scheduleTitleText"> - Convention Between Canada and the Kingdom of Denmark for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li>
<li><a href="page-7.html#h-325788"><span class="scheduleLabel">SCHEDULES 6 AND 7</span></a>
</li></ul>
</li></ul>

</nav>

