<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les pensions</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Règle d’interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3.1 - </span><a href="#h-4"><span class="HTitleText1">Loi sur les mesures de réinsertion et d’indemnisation des militaires et vétérans des forces canadiennes</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText1">Égalité de statut</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText1">Pouvoirs du ministre</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Pensions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>34 - </span><a href="#h-8"><span class="HTitleText2">Enfants</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-9"><span class="HTitleText2">Pensions pour invalidité</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-10"><span class="HTitleText2">Pensions pour décès</span></a>
</li>
<li><span class='sectionRange'>64 - </span><a href="#h-11"><span class="HTitleText2">Pensions supplémentaires en ce qui concerne les membres des forces alliées et des marines marchandes alliées</span></a>
</li></ul>
</li><li><span class='sectionRange'>71.1 - </span><a href="#h-12"><span class="HLabel1">PARTIE III.1</span> - <span class="HTitleText1">Prisonniers de guerre</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>71.1 - </span><a href="#h-13"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>71.2 - </span><a href="#h-14"><span class="HTitleText2">Indemnités</span></a>
</li></ul>
</li><li><span class='sectionRange'>72 - </span><a href="#h-15"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Allocation d’incapacité exceptionnelle</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-16"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Ajustement annuel des pensions et allocations</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-17"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Procédure</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-18"><span class="HLabel1">PARTIE VII</span> - <span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><a href="#h-405679"><span class="scheduleLabel">ANNEXE I</span> <span class="scheduleTitleText"> - Échelle des pensions d’invalidité</span></a>
</li>
<li><a href="#h-405690"><span class="scheduleLabel">ANNEXE II</span> <span class="scheduleTitleText"> - Pensions pour décès</span></a>
</li>
<li><a href="#h-405699"><span class="scheduleLabel">ANNEXE III</span> <span class="scheduleTitleText"> - Allocations</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
