<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le gouvernement du territoire provisoire de Kanesatake</a><ul class="TocIndent"><li><span class='sectionRange'>24 - </span><a href="#h-329952"><span class="HTitleText1">Modification de la Loi sur l’arpentage des terres du Canada</span></a>
</li>
<li><a href="#h-329955"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Territoire provisoire de Kanesatake</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
