<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Economic Action Plan 2013 Act, No. 1</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-174167"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-174170"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Amendments to the Income Tax Act, the Tax Court of Canada Act and the Income Tax Regulations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-174171"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-174192"><span class="HTitleText2"><cite class="XRefExternalAct">Tax Court of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-174203"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-174213"><span class="HTitleText2">Coordinating Amendments</span></a>
</li></ul>
</li><li><span class='sectionRange'>42 - </span><a href="#h-174215"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Measures Relating to Sales and Excise Taxes and Excise Duties</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="#h-174216"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-174228"><span class="HTitleText2"><cite class="XRefExternalAct">Excise Act, 2001</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>53 - </span><a href="#h-174229"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-174238"><span class="HTitleText3">Application</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-174240"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Various Measures</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-174241"><span class="HLabel2">DIVISION 1</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Customs Tariff</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>62 - </span><a href="#h-174242"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>103 - </span><a href="#h-174284"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>104 - </span><a href="#h-174287"><span class="HLabel2">DIVISION 2</span> - <span class="HTitleText2">Financial Institutions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>104 - </span><a href="#h-174288"><span class="HTitleText3"><cite class="XRefExternalAct">Trust and Loan Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>105 - </span><a href="#h-174290"><span class="HTitleText3"><cite class="XRefExternalAct">Bank Act</cite></span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-174293"><span class="HTitleText3"><cite class="XRefExternalAct">Insurance Companies Act</cite></span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-174296"><span class="HTitleText3"><cite class="XRefExternalAct">Cooperative Credit Associations Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>110 - </span><a href="#h-174298"><span class="HLabel2">DIVISION 3</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Federal-Provincial Fiscal Arrangements Act</cite></span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-174315"><span class="HLabel2">DIVISION 4</span> - <span class="HTitleText2">Payments to Certain Entities or for Certain Purposes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>126 - </span><a href="#h-174316"><span class="HTitleText3">Canadian Youth Business Foundation</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-174319"><span class="HTitleText3">Genome Canada</span></a>
</li>
<li><span class='sectionRange'>128 - </span><a href="#h-174322"><span class="HTitleText3">Nature Conservancy of Canada</span></a>
</li>
<li><span class='sectionRange'>129 - </span><a href="#h-174325"><span class="HTitleText3">Nunavut Housing</span></a>
</li>
<li><span class='sectionRange'>130 - </span><a href="#h-174328"><span class="HTitleText3">Indspire</span></a>
</li>
<li><span class='sectionRange'>131 - </span><a href="#h-174331"><span class="HTitleText3">Pallium Foundation of Canada</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-174334"><span class="HTitleText3">Canadian National Institute for the Blind</span></a>
</li></ul>
</li><li><span class='sectionRange'>133 - </span><a href="#h-174337"><span class="HLabel2">DIVISION 5</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canadian Securities Regulation Regime Transition Office Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>133 - </span><a href="#h-174338"><span class="HTitleText3">Amendment to the Act</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-174340"><span class="HTitleText3">Repeal</span></a>
</li>
<li><span class='sectionRange'>135 - </span><a href="#h-174342"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>136 - </span><a href="#h-174345"><span class="HLabel2">DIVISION 6</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Investment Canada Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>136 - </span><a href="#h-174346"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>146 - </span><a href="#h-174359"><span class="HTitleText3">Related Amendments to the <cite class="XRefExternalAct">Budget Implementation Act, 2009</cite></span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-174363"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>154 - </span><a href="#h-174369"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>155 - </span><a href="#h-174372"><span class="HLabel2">DIVISION 7</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Canada Pension Plan</cite></span></a>
</li>
<li><span class='sectionRange'>156 - </span><a href="#h-174374"><span class="HLabel2">DIVISION 8</span> - <span class="HTitleText2">Improving Veterans’ Benefits</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>156 - </span><a href="#h-174375"><span class="HTitleText3"><cite class="XRefExternalAct">Pension Act</cite></span></a>
</li>
<li><span class='sectionRange'>157 - </span><a href="#h-174377"><span class="HTitleText3"><cite class="XRefExternalAct">War Veterans Allowance Act</cite></span></a>
</li>
<li><span class='sectionRange'>159 - </span><a href="#h-174380"><span class="HTitleText3">Transitional Provision</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-174382"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>161 - </span><a href="#h-174385"><span class="HLabel2">DIVISION 9</span> - <span class="HTitleText2">Immigration and Refugee Protection</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>161 - </span><a href="#h-174386"><span class="HTitleText3"><cite class="XRefExternalAct">Immigration and Refugee Protection Act</cite></span></a>
</li>
<li><span class='sectionRange'>167 - </span><a href="#h-174393"><span class="HTitleText3">No Appeal to the Refugee Appeal Division</span></a>
</li>
<li><span class='sectionRange'>169 - </span><a href="#h-174396"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>170 - </span><a href="#h-174399"><span class="HLabel2">DIVISION 10</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Citizenship Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>170 - </span><a href="#h-174400"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-174403"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>173 - </span><a href="#h-174406"><span class="HLabel2">DIVISION 11</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Nuclear Safety and Control Act</cite></span></a>
</li>
<li><span class='sectionRange'>174 - </span><a href="#h-174408"><span class="HLabel2">DIVISION 12</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Department of Foreign Affairs, Trade and Development Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>174 - </span><a href="#h-174409"><span class="HTitleText3">Enactment of Act</span></a>
</li>
<li><span class='sectionRange'>175 - </span><a href="#h-174412"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>175 - </span><a href="#h-174413"><span class="HTitleText4"><cite class="XRefExternalAct">Access to Information Act</cite></span></a>
</li>
<li><span class='sectionRange'>178 - </span><a href="#h-174417"><span class="HTitleText4"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
</li>
<li><span class='sectionRange'>185 - </span><a href="#h-174425"><span class="HTitleText4"><cite class="XRefExternalAct">Privacy Act</cite></span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-174429"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Compensation Act</cite></span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-174433"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Real Property and Federal Immovables Act</cite></span></a>
</li>
<li><span class='sectionRange'>192 - </span><a href="#h-174435"><span class="HTitleText4"><cite class="XRefExternalAct">Conflict of Interest Act</cite></span></a>
</li>
<li><span class='sectionRange'>193 - </span><a href="#h-174437"><span class="HTitleText4"><cite class="XRefExternalAct">Official Development Assistance Accountability Act</cite></span></a>
</li>
<li><span class='sectionRange'>194 - </span><a href="#h-174439"><span class="HTitleText4"><cite class="XRefExternalAct">Federal Sustainable Development Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>195 - </span><a href="#h-174441"><span class="HTitleText3">Terminology</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-174453"><span class="HTitleText3">Repeal</span></a>
</li></ul>
</li><li><span class='sectionRange'>200 - </span><a href="#h-174455"><span class="HLabel2">DIVISION 13</span> - <span class="HTitleText2">Ridley Terminals Inc.</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>200 - </span><a href="#h-174456"><span class="HTitleText3">Reorganization and Divestiture</span></a>
</li>
<li><span class='sectionRange'>211 - </span><a href="#h-174537"><span class="HTitleText3">Consequential Amendment to the <cite class="XRefExternalAct">Canada Marine Act</cite></span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-174539"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>213 - </span><a href="#h-174542"><span class="HLabel2">DIVISION 14</span> - <span class="HTitleText2">Transfer of Powers, Duties and Functions to the Minister of Canadian Heritage</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>213 - </span><a href="#h-174543"><span class="HTitleText3"><cite class="XRefExternalAct">National Capital Act</cite></span></a>
</li>
<li><span class='sectionRange'>214 - </span><a href="#h-174545"><span class="HTitleText3"><cite class="XRefExternalAct">Department of Canadian Heritage Act</cite></span></a>
</li>
<li><span class='sectionRange'>216 - </span><a href="#h-174548"><span class="HTitleText3">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>221 - </span><a href="#h-174554"><span class="HTitleText3">Consequential Amendments to the <cite class="XRefExternalAct">National Holocaust Monument Act</cite></span></a>
</li>
<li><span class='sectionRange'>224 - </span><a href="#h-174558"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>225 - </span><a href="#h-174561"><span class="HLabel2">DIVISION 15</span> - <span class="HTitleText2">Parliamentary Secretaries and Ministers</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>225 - </span><a href="#h-174562"><span class="HTitleText3"><cite class="XRefExternalAct">Parliament of Canada Act</cite></span></a>
</li>
<li><span class='sectionRange'>226 - </span><a href="#h-174564"><span class="HTitleText3"><cite class="XRefExternalAct">Salaries Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>227 - </span><a href="#h-174566"><span class="HLabel2">DIVISION 16</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Department of Public Works and Government Services Act</cite></span></a>
</li>
<li><span class='sectionRange'>228 - </span><a href="#h-174568"><span class="HLabel2">DIVISION 17</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Financial Administration Act</cite></span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>228 - </span><a href="#h-174569"><span class="HTitleText3">Amendments to the Act</span></a>
</li>
<li><span class='sectionRange'>230 - </span><a href="#h-174572"><span class="HTitleText3">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>230 - </span><a href="#h-174573"><span class="HTitleText4"><cite class="XRefExternalAct">Canadian Race Relations Foundation Act</cite></span></a>
</li>
<li><span class='sectionRange'>231 - </span><a href="#h-174575"><span class="HTitleText4"><cite class="XRefExternalAct">Public Sector Pension Investment Board Act</cite></span></a>
</li></ul>
</li><li><span class='sectionRange'>232 - </span><a href="#h-174577"><span class="HTitleText3">Coming into Force</span></a>
</li></ul>
</li><li><span class='sectionRange'>233 - </span><a href="#h-174580"><span class="HLabel2">DIVISION 18</span> - <span class="HTitleText2"><cite class="XRefExternalAct">Keeping Canada’s Economy and Jobs Growing Act</cite></span></a>
</li></ul>
</li><li><a href="#h-174583"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
