<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Preclearance Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-396011"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-396014"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-396023"><span class="HTitleText1">Designation of Minister</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-396026"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-396031"><span class="HTitleText1">Administration of Preclearance Laws</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-396039"><span class="HTitleText1">Preclearance and Intransit Areas</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-396059"><span class="HTitleText1">Powers of Preclearance Officers</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-396094"><span class="HTitleText1">Search of Persons</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-396122"><span class="HTitleText1">Examination of Goods</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-396142"><span class="HTitleText1">Passenger Information</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-396164"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-396178"><span class="HTitleText1">Civil Liability and Immunity</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-396190"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-396202"><span class="HTitleText1">Five-year Review</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-396205"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-396209"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
