<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Donkin Coal Block Development Opportunity Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-173897"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-173900"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-173914"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-173917"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-173920"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-173925"><span class="HTitleText1">Delegation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-173928"><span class="HTitleText1">Royalties</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-173942"><span class="HTitleText1">Agreement</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-173945"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-173973"><span class="HTitleText1">Consequential Amendment to the Canada-nova Scotia Offshore Petroleum Resources Accord Implementation Act</span></a>
</li>
<li><a href="#h-173976"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Area of the Donkin Coal Block</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
