<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’assistance-chômage</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-450914"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-450919"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-450928"><span class="HTitleText1">Accords avec les provinces</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-450966"><span class="HTitleText1">Paiements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-450971"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-450976"><span class="HTitleText1">Rapport au Parlement</span></a>
</li>
<li><a href="page-2.html#h-450982"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>

