<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi autorisant l’acquisition de Marine Atlantique S.C.C.</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-340179"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-340182"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-340187"><span class="HTitleText1">Changement de nom</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-340193"><span class="HTitleText1">Transfert d’actions</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-340211"><span class="HTitleText1">Transfert de biens</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-340221"><span class="HTitleText1">Modification des statuts</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-340224"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-340227"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
