<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Pooled Registered Pension Plans Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-394894"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-394897"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-394924"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-394927"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-394932"><span class="HTitleText1">Agreements</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-394971"><span class="HTitleText1">Powers of Superintendent</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="page-1.html#h-394987"><span class="HTitleText1">Registration</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-1.html#h-395010"><span class="HTitleText1">Administration of Pooled Registered Pension Plans</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>14 - </span><a href="page-1.html#h-395011"><span class="HTitleText2">Administrator</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="page-2.html#h-395066"><span class="HTitleText2">Employer</span></a>
</li></ul>
</li><li><span class='sectionRange'>34 - </span><a href="page-2.html#h-395088"><span class="HTitleText1">Directions of Compliance</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="page-2.html#h-395106"><span class="HTitleText1">Objections and Appeals</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="page-2.html#h-395129"><span class="HTitleText1">General Requirements</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>39 - </span><a href="page-2.html#h-395130"><span class="HTitleText2">Membership</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="page-3.html#h-395175"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="page-3.html#h-395183"><span class="HTitleText2">Locking-in</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="page-3.html#h-395195"><span class="HTitleText2">Variable Payments</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="page-3.html#h-395217"><span class="HTitleText2">Death of Member</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="page-3.html#h-395225"><span class="HTitleText2">Divorce, Annulment, Separation or Breakdown of Common-law Partnership</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="page-3.html#h-395247"><span class="HTitleText2">Transfer of Funds and Purchase of Life Annuities</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="page-3.html#h-395264"><span class="HTitleText2">Sex Discrimination Prohibited</span></a>
</li>
<li><span class='sectionRange'>57 - </span><a href="page-3.html#h-395267"><span class="HTitleText2">Rights to Information</span></a>
</li>
<li><span class='sectionRange'>58 - </span><a href="page-4.html#h-395282"><span class="HTitleText2">Duty to Provide Information</span></a>
</li></ul>
</li><li><span class='sectionRange'>61 - </span><a href="page-4.html#h-395298"><span class="HTitleText1">Termination and Winding-Up</span></a>
</li>
<li><span class='sectionRange'>63 - </span><a href="page-4.html#h-395328"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>75 - </span><a href="page-4.html#h-395395"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="page-5.html#h-395424"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="page-5.html#h-395471"><span class="HTitleText1">Annual Report</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="page-5.html#h-395474"><span class="HTitleText1">Related Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>79 - </span><a href="page-5.html#h-395475"><span class="HTitleText2">Bankruptcy and Insolvency Act</span></a>
</li>
<li><span class='sectionRange'>82 - </span><a href="page-5.html#h-395479"><span class="HTitleText2">Companies’ Creditors Arrangement Act</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="page-5.html#h-395481"><span class="HTitleText2">Canadian Human Rights Act</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="page-5.html#h-395483"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="page-5.html#h-395490"><span class="HTitleText2">Office of the Superintendent of Financial Institutions Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>94 - </span><a href="page-5.html#h-395495"><span class="HTitleText1">Coordinating Amendment</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="page-5.html#h-395497"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>

