<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de 1999 sur les services gouvernementaux</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-245832"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-245835"><span class="HLabel1">PARTIE 1</span> - <span class="HTitleText1">Groupes des services de l’exploitation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-245836"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-245848"><span class="HTitleText2">Services gouvernementaux</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-245853"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-245865"><span class="HTitleText2">Conventions collectives</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-245889"><span class="HTitleText2">Modification de la convention collective</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-245892"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-245911"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><span class='sectionRange'>15 - </span><a href="#h-245914"><span class="HLabel1">PARTIE 2</span> - <span class="HTitleText1">Groupes des services correctionnels</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>15 - </span><a href="#h-245915"><span class="HTitleText2">Définitions</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-245927"><span class="HTitleText2">Services gouvernementaux</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-245932"><span class="HTitleText2">Obligations</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-245944"><span class="HTitleText2">Conventions collectives</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-245968"><span class="HTitleText2">Modification des conventions collectives</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-245971"><span class="HTitleText2">Contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-245990"><span class="HTitleText2">Entrée en vigueur</span></a>
</li></ul>
</li><li><a href="#h-245994"><span class="scheduleLabel">ANNEXE 1</span> </a>
</li>
<li><a href="#h-246012"><span class="scheduleLabel">ANNEXE 2</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
