<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Canada Recovery Benefits Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1260494"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1260497"><span class="HTitleText1">Definitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-1260506"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada Recovery Benefit</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-1260590"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Canada Recovery Sickness Benefit</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-1260637"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Canada Recovery Caregiving Benefit</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="page-3.html#h-1260701"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="page-4.html#h-1260831"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Consequential Amendments</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>42 - </span><a href="page-4.html#h-1260832"><span class="HTitleText2"><cite class="XRefExternalAct">Income Tax Act</cite></span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="page-4.html#h-1260843"><span class="HTitleText2"><cite class="XRefExternalRegulation">Income Tax Regulations</cite></span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

