<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Precious Metals Marking Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-396861"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-396866"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-396891"><span class="HTitleText1">Marking</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-396915"><span class="HTitleText1">National Marks</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-396923"><span class="HTitleText1">Enforcement</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-396955"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-396969"><span class="HTitleText1">Offences and Punishment</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
