<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Western Grain Transition Payments Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-468820"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-468823"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-468832"><span class="HTitleText1">Applications</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-468840"><span class="HTitleText1">Payments</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-468861"><span class="HTitleText1">Appropriation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-468864"><span class="HTitleText1">Regulations</span></a>
</li></ul>
</li></ul>

</nav>

