<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Veterans Insurance Act</a><ul class="TocIndent"><li><a href="page-3.html#h-462697"><span class="scheduleLabel">SCHEDULE A — <span class="otherLang" lang="fr">ANNEXE A</span></span> - <span class="scheduleTitleText"> - Monthly Premiums for $1,000 Insurance Payable at Death</span> - <span class="scheduleTitleText"> - <span class="otherLang" lang="fr">Primes mensuelles par $1,000 d’assurance payable au décès</span></span></a>
</li>
<li><a href="page-4.html#h-462708"><span class="scheduleLabel">SCHEDULE B</span></a>
</li></ul>
</li></ul>

</nav>

