<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’Agence canadienne d’inspection des aliments</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-66393"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-66396"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-66401"><span class="HTitleText1">Constitution de l’Agence</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-66409"><span class="HTitleText1">Organisation et siège</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-66423"><span class="HTitleText1">Comité consultatif</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-66439"><span class="HTitleText1">Mission de l’Agence</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-66455"><span class="HTitleText1">Gestion des ressources humaines</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-66467"><span class="HTitleText1">Pouvoirs de l’Agence</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-66483"><span class="HTitleText1">Rappel</span></a>
</li>
<li><span class='sectionRange'>19.2 - </span><a href="#h-1099110"><span class="HTitleText1">Révision de certaines mesures</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-66491"><span class="HTitleText1">Création de sociétés fédéro-provinciales</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-66498"><span class="HTitleText1">Plan d’entreprise et rapport d’activités</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-66520"><span class="HTitleText1">Fixation des prix et recettes d’exploitation</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-66550"><span class="HTitleText1">Documents comptables</span></a>
</li>
<li><span class='sectionRange'>32.1 - </span><a href="#h-66554"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>37 à 89 - </span><a href="#h-66571"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>90 et 91 - </span><a href="#h-66573"><span class="HTitleText1">Modifications conditionnelles</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-66575"><span class="HTitleText1">Abrogation</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-66577"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
