<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Federal-Provincial Fiscal Arrangements Act, 1972</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-239941"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-239944"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-239953"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Provincial Revenue Equalization Payments</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-240039"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Provincial Revenue Stabilization Payments</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-240060"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Tax Collection Agreements</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-240079"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Provincial Tax Revenue Guarantee Payments</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-240154"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Transfer Payments with Respect to Tax on 1971 Undistributed Income on Hand</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-240170"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Post-Secondary Education Adjustment Payments</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-240315"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">General</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>32 - </span><a href="#h-240316"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>33 - </span><a href="#h-240333"><span class="HTitleText2">Payment out of Consolidated Revenue Fund</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-240336"><span class="HTitleText2">Established Programs (Interim Arrangements) Act</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>

