<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la Société canadienne des postes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions et interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Société canadienne des postes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Constitution de la Société</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Mission</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Conseil d’administration</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Président du conseil</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Président</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-10"><span class="HTitleText2">Siège social</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-11"><span class="HTitleText2">Gestion de la Société</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-12"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-13"><span class="HTitleText2">Privilège exclusif de la Société</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-14"><span class="HTitleText2">Pouvoirs</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-15"><span class="HTitleText2">Règlements</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-16"><span class="HTitleText2">Instructions</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-17"><span class="HTitleText2">Statut de la Société</span></a>
</li>
<li><span class='sectionRange'>27.1 - </span><a href="#h-18"><span class="HTitleText2">Dispositions financières</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-19"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Dispositions générales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>35 - </span><a href="#h-20"><span class="HTitleText2">Pouvoirs publics</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-21"><span class="HTitleText2">Conventions</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-22"><span class="HTitleText2">Transmission des envois</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-23"><span class="HTitleText2">Services financiers</span></a>
</li>
<li><span class='sectionRange'>40 - </span><a href="#h-24"><span class="HTitleText2">Responsabilité</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-25"><span class="HTitleText2">Ouverture des envois</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-26"><span class="HTitleText2">Douanes</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-27"><span class="HTitleText2">Arrêté d’interdiction</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-28"><span class="HTitleText2">Infractions et peines</span></a>
</li></ul>
</li><li><span class='sectionRange'>62 - </span><a href="#h-29"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
