<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la protection du revenu agricole</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Protection du revenu agricole</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Accords fédéro-provinciaux</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-6"><span class="HTitleText2">Communication de renseignements</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-7"><span class="HTitleText2">Mesures spéciales</span></a>
</li></ul>
</li><li><span class='sectionRange'>13 - </span><a href="#h-8"><span class="HTitleText1">Caisses et compte</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>13 - </span><a href="#h-9"><span class="HTitleText2">Caisse de réassurance-récolte</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-10"><span class="HTitleText2">Compte de stabilisation du revenu net</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-11"><span class="HTitleText2">Caisse d’assurance-revenu</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText2">Avances</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-14"><span class="HTitleText1">Paiements sur le trésor</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-15"><span class="HTitleText1">Rapports au Parlement</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-16"><span class="HTitleText1">Dispositions transitoires</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-17"><span class="HTitleText1">Modification corrélative</span></a>
</li>
<li><span class='sectionRange'>27 à 29 - </span><a href="#h-18"><span class="HTitleText1">Abrogations</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-19"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
