<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Hazardous Materials Information Review Act</a><ul class="TocIndent"><li><span class='sectionRange'>9 - </span><a href="#h-252440"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-252445"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-252480"><span class="HTitleText1">Filing of Claim for Exemption</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-1238745"><span class="HTitleText1">Review of Claim for Exemption</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-1238789"><span class="HTitleText1">Review of Safety Data Sheet or Label</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-252607"><span class="HTitleText1">Exemption Periods</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-1238801"><span class="HTitleText1">Suspension or Cancellation of Exemption</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-1238824"><span class="HTitleText1">Reinstatement of Suspended or Cancelled Exemption</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-1238833"><span class="HTitleText1">Disclosure of Confidential Business Information</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-1238872"><span class="HTitleText1">Remission of Fees</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-1238886"><span class="HTitleText1">Additional Powers, Duties and Functions of Minister</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-252800"><span class="HTitleText1">Regulations</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-252816"><span class="HTitleText1">Offence and Punishment</span></a>
</li></ul>
</li></ul>

</nav>

