<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Nuclear Safety and Control Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Purpose of Act</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Application</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-5"><span class="HTitleText1">Canadian Nuclear Safety Commission</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>8 - </span><a href="#h-6"><span class="HTitleText2">Establishment of Commission</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-7"><span class="HTitleText2">Objects</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-8"><span class="HTitleText2">Members</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-9"><span class="HTitleText2">President</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-10"><span class="HTitleText2">Remuneration and Expenses</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-11"><span class="HTitleText2">Meetings</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-12"><span class="HTitleText2">By-laws</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-13"><span class="HTitleText2">Officers, Employees and Contractors</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-14"><span class="HTitleText2">Civil Liability</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-15"><span class="HTitleText2">Directives</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-16"><span class="HTitleText2">Powers</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="#h-17"><span class="HTitleText2">Panels</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-18"><span class="HTitleText2">Decision-Making</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-19"><span class="HTitleText2">Licences</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-20"><span class="HTitleText2">Records and Reports</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-21"><span class="HTitleText2">Analysts and Inspectors</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-22"><span class="HTitleText2">Designated Officers</span></a>
</li>
<li><span class='sectionRange'>38 - </span><a href="#h-23"><span class="HTitleText2">Procedures for Decisions and Orders</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-24"><span class="HTitleText2">Redetermination and Appeal of Decisions and Orders</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-25"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-26"><span class="HTitleText2">Exceptional Powers</span></a>
</li></ul>
</li><li><span class='sectionRange'>48 - </span><a href="#h-27"><span class="HTitleText1">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-28"><span class="HTitleText1">General</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-29"><span class="HTitleText1">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>83 to 105 - </span><a href="#h-30"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>124 - </span><a href="#h-31"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><span class='sectionRange'>127 - </span><a href="#h-32"><span class="HTitleText1">Coming into Force</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
