<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur le vérificateur général</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-6946"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-6951"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-6981"><span class="HTitleText1">Le vérificateur général du Canada</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-7001"><span class="HTitleText1">Attributions</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-7069"><span class="HTitleText1">Accès à l’information</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7090"><span class="HTitleText1">Personnel du bureau du vérificateur général</span></a>
</li>
<li><span class='sectionRange'>18.1 - </span><a href="#h-7134"><span class="HTitleText1">Immunité</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="#h-7148"><span class="HTitleText1">Budget des dépenses</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-7160"><span class="HTitleText1">Vérification du bureau du vérificateur général</span></a>
</li>
<li><span class='sectionRange'>21.1 - </span><a href="#h-7168"><span class="HTitleText1">Développement durable</span></a>
</li>
<li><a href="#h-11"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
