<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’accord de 1986 concernant les terres indiennes</a><ul class="TocIndent"><li><a href="#h-324705"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Accord de 1986 sur les terres indiennes</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
