<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les réseaux de cartes de paiement</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-402051"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-402054"><span class="HTitleText1">Objet</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-402057"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-402067"><span class="HTitleText1">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-402070"><span class="HTitleText1">Agence de la consommation en matière financière du Canada</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-402090"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-402100"><span class="HTitleText1">Dispositions générales</span></a>
</li></ul>
</li></ul>

</nav>

