<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les Jeux olympiques de 1976</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-377839"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-377842"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-377849"><span class="HTitleText1">Pièces olympiques</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-377890"><span class="HTitleText1">Timbres et produits postaux connexes des Jeux olympiques</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-377915"><span class="HTitleText1">Loteries</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-377923"><span class="HTitleText1">Compte des Jeux olympiques</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-377946"><span class="HTitleText1">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-377949"><span class="HTitleText1">Marques de commerce et symboles</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-378010"><span class="HTitleText1">Rapports au Parlement</span></a>
</li>
<li><a href="#h-378031"><span class="scheduleLabel"><span class="otherLang" lang="en">SCHEDULE I</span> / ANNEXE I</span></a>
</li>
<li><a href="#h-378036"><span class="scheduleLabel"><span class="otherLang" lang="en">SCHEDULE II</span> / ANNEXE II</span></a>
</li></ul>
</li></ul>

</nav>

