<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Crimes Against Humanity and War Crimes Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-114623"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-114626"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-114638"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-114641"><span class="HTitleText1">Offences Within Canada</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-114689"><span class="HTitleText1">Offences Outside Canada</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-114754"><span class="HTitleText1">Procedure and Defences</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-114789"><span class="HTitleText1">Parole Eligibility</span></a>
</li>
<li><span class='sectionRange'>16 - </span><a href="#h-114810"><span class="HTitleText1">Offences Against the Administration of Justice</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-114874"><span class="HTitleText1">Crimes Against Humanity Fund</span></a>
</li>
<li><span class='sectionRange'>33 to 75 - </span><a href="#h-114895"><span class="HTitleText1">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>76 and 76.1 - </span><a href="#h-114897"><span class="HTitleText1">Conditional Amendment</span></a>
</li>
<li><span class='sectionRange'>77 - </span><a href="#h-114899"><span class="HTitleText1">Coming into Force</span></a>
</li>
<li><a href="#h-114903"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Provisions of Rome Statute</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
