<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada–Gabon Tax Convention Act, 2004</a><ul class="TocIndent"><li><a href="#h-136436"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Convention Between the Government of Canada and the Government of the Gabonese Republic for the Avoidance of Double Taxation and the Prevention of Fiscal Evasion with Respect to Taxes on Income and on Capital</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
