name: Deploy LawsWeb to Azure Web App - jusclawsweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

#Job creates a runner
jobs:
  build:
    runs-on: windows-latest
    
  LawsWeb-Deploy-Job:
    name: Running job to deploy to Azure resource
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

  deploy:
    runs-on: windows-latest
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jusclawsweb'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EA720D262B97414297F5FDB7FF1E7CCC }}
          package: .
