name: Deployment

"on":
  - push
  
jobs:
  deploy_ghpages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: echo $GITHUB_SHA >> public/index.html
      - uses: sgorn/LawsWeb@main
        env:
          BUILD_DIR: public/
          GH_PAT: ${{ secrets.GH_PAT }}
