<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Airport Transfer (Miscellaneous Matters) Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-1427"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-1430"><span class="HTitleText1">Interpretation and Application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-1446"><span class="HTitleText1">Her Majesty</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="page-1.html#h-1449"><span class="HTitleText1">Official Languages</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="page-1.html#h-1463"><span class="HTitleText1">Pension Benefits</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-1482"><span class="HTitleText1">Income Tax</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-1500"><span class="HTitleText1">Seizure and Detention of Aircraft</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-1521"><span class="HTitleText1">Qualified Investment</span></a>
</li></ul>
</li></ul>

</nav>

