<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Governor General’s Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-252196"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-252201"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Office of Governor General</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="page-1.html#h-252237"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Governor General’s Retiring Annuity</span></a>
</li></ul>
</li></ul>

</nav>

