<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Kingsmere Park Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-338349"><span class="HTitleText1">Short Title</span></a>
</li>
<li><a href="page-2.html#h-338376"><span class="scheduleLabel">SCHEDULE</span> - <span class="scheduleTitleText"> - Portions of Mr. King’s Will</span></a>
</li></ul>
</li></ul>

</nav>

