<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Diplomatic Service (Special) Superannuation Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Equality of Status</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Retirement and Superannuation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Superannuation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Benefits</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Contributions</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-8"><span class="HTitleText2">Alternate Benefits</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-9"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>16 - </span><a href="#h-10"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Supplementary Retirement Benefit Contributions</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
