<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi de l’impôt sur les revenus pétroliers</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-382410"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-382415"><span class="HTitleText1">Définitions et champ d’application</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-382512"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-382517"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Impôt sur le revenu et les recettes</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-382518"><span class="HTitleText2">Impôt et calcul</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-382802"><span class="HTitleText2">Déclarations</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-382848"><span class="HTitleText2">Paiement de l’impôt</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-382886"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>26 - </span><a href="#h-383046"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Impôt sur les redevances</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>26 - </span><a href="#h-383047"><span class="HTitleText2">Impôt et calcul</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-383068"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-383111"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Application</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>29 - </span><a href="#h-383112"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-383165"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-383192"><span class="HTitleText2">Dispositions spéciales</span></a>
</li></ul>
</li></ul>
</li></ul>

</nav>
</div></section>
