<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi autorisant l’aliénation de La Société des transports du nord Limitée</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-357246"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-357249"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-357254"><span class="HTitleText1">Autorisation d’aliénation</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-357274"><span class="HTitleText1">Remise de dette</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-357284"><span class="HTitleText1">Redressement des comptes</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-357287"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="#h-357297"><span class="HTitleText1">Entrée en vigueur</span></a>
</li>
<li><a href="#h-357301"><span class="scheduleLabel">ANNEXE</span></a>
</li></ul>
</li></ul>

</nav>

