<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 1995</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-35148"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 to 6 - </span><a href="#h-35151"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Compensation</span></a>
</li>
<li><span class='sectionRange'>7 to 10 - </span><a href="#h-35153"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Management of Labour</span></a>
</li>
<li><span class='sectionRange'>11 to 22 - </span><a href="#h-35155"><span class="HLabel1">PART III</span> - <span class="HTitleText1">Transportation Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>11 to 22 - </span><a href="#h-35156"><span class="HTitleText2">National Transportation Act, 1987</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-35158"><span class="HTitleText2">Coming into Force</span></a>
</li>
<li><span class='sectionRange'>24 to 26 - </span><a href="#h-35161"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>27 - </span><a href="#h-35163"><span class="HTitleText2">Transitional Provisions</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-35175"><span class="HTitleText2">Enactment</span></a>
</li></ul>
</li><li><span class='sectionRange'>30 - </span><a href="#h-35178"><span class="HLabel1">PART IV</span> - <span class="HTitleText1">Fiscal Arrangements and Other Matters</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>31 and 32 - </span><a href="#h-35180"><span class="HTitleText2">Canada Assistance Plan</span></a>
</li>
<li><span class='sectionRange'>33 to 41 - </span><a href="#h-35182"><span class="HTitleText2">Canada Health Act</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-35184"><span class="HTitleText2">Children of Deceased Veterans Education Assistance Act</span></a>
</li>
<li><span class='sectionRange'>43 - </span><a href="#h-35186"><span class="HTitleText2">Department of Foreign Affairs and International Trade Act</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-35188"><span class="HTitleText2">Federal-Provincial Fiscal Arrangements and Federal Post-Secondary Education and Health Contributions Act</span></a>
</li>
<li><span class='sectionRange'>57 to 60 - </span><a href="#h-35194"><span class="HTitleText2">Financial Administration Act</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-35196"><span class="HTitleText2">Pension Benefits Standards Act, 1985</span></a>
</li>
<li><span class='sectionRange'>62 to 64 - </span><a href="#h-35198"><span class="HTitleText2">Public Utilities Income Tax Transfer Act</span></a>
</li>
<li><span class='sectionRange'>66 - </span><a href="#h-35202"><span class="HTitleText2">Tax Rebate Discounting Act</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-35204"><span class="HTitleText2">Vocational Rehabilitation of Disabled Persons Act</span></a>
</li>
<li><span class='sectionRange'>68 to 72 - </span><a href="#h-35206"><span class="HTitleText2">War Veterans Allowance Act</span></a>
</li></ul>
</li><li><span class='sectionRange'>73 - </span><a href="#h-35208"><span class="HTitleText1">Conditional Amendments</span></a>
</li>
<li><a href="#h-35211"><span class="scheduleLabel">SCHEDULE I</span></a>
</li>
<li><a href="#h-35214"><span class="scheduleLabel">SCHEDULE II</span> </a>
</li></ul>
</li></ul>

</nav>

