<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur la prestation universelle pour la garde d’enfants</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-451304"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-451307"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-451316"><span class="HTitleText1">Objet de la loi</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-451323"><span class="HTitleText1">Prestation</span></a>
</li></ul>
</li></ul>

</nav>

