<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
National Capital Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-374222"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-374227"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-374252"><span class="HTitleText1">Commission Continued</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="page-1.html#h-374300"><span class="HTitleText1">Officers and Employees</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="page-1.html#h-374312"><span class="HTitleText1">Committees</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-1.html#h-374324"><span class="HTitleText1">Objects, Purposes and Powers</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-1.html#h-374342"><span class="HTitleText1">Development</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="page-2.html#h-374393"><span class="HTitleText1">Expropriation</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="page-2.html#h-374401"><span class="HTitleText1">Property</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="page-2.html#h-374422"><span class="HTitleText1">Financial</span></a>
</li>
<li><span class='sectionRange'>19 - </span><a href="page-2.html#h-374431"><span class="HTitleText1">By-laws and Regulations</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-374456"><span class="HTitleText1">General</span></a>
</li>
<li><a href="page-3.html#h-374470"><span class="scheduleLabel">SCHEDULE</span> <span class="scheduleTitleText"> - Description of National Capital Region</span></a>
</li></ul>
</li></ul>

</nav>

