<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur la Convention Canada-Royaume-Uni relative aux jugements en matière civile et commerciale</a><ul class="TocIndent"><li><a href="page-2.html#h-82956"><span class="scheduleLabel">ANNEXE</span> <span class="scheduleTitleText"> - Convention entre le Canada et le Royaume-Uni de Grande-Bretagne et d’Irlande du Nord pour assurer la reconnaissance et l’exécution réciproques des jugements en matière civile et commerciale</span></a>
</li></ul>
</li></ul>

</nav>

