<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Budget Implementation Act, 1997</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-35228"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-35231"><span class="HLabel1">PART I</span> - <span class="HTitleText1">Canada Foundation for Innovation</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-35232"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-35260"><span class="HTitleText2">Establishment of Foundation</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-35306"><span class="HTitleText2">Directors</span></a>
</li>
<li><span class='sectionRange'>13 - </span><a href="#h-35358"><span class="HTitleText2">Members</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-35407"><span class="HTitleText2">Staff</span></a>
</li>
<li><span class='sectionRange'>18 - </span><a href="#h-35419"><span class="HTitleText2">Operations</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-35466"><span class="HTitleText2">Financial Matters and Audits</span></a>
</li>
<li><span class='sectionRange'>29 - </span><a href="#h-35510"><span class="HTitleText2">Reports and Consideration of Reports</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-35526"><span class="HTitleText2">Winding Up</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-35534"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>35 - </span><a href="#h-35543"><span class="HLabel1">PART II</span> - <span class="HTitleText1">Cowichan Tribes Tobacco Tax</span></a>
</li>
<li><span class='sectionRange'>59 to 79 - </span><a href="#h-35643"><span class="HLabel1">PARTS III AND IV</span> - <span class="HTitleText1">[Repealed, 2000, c. 14, s. 30]</span></a>
</li>
<li><span class='sectionRange'>59 to 79 - </span><a href="#h-35644"><span class="HLabel1">PART V</span> - <span class="HTitleText1">Tobacco Products</span></a>
</li>
<li><span class='sectionRange'>80 - </span><a href="#h-35646"><span class="HLabel1">PART VI</span> - <span class="HTitleText1">Child Tax Benefit</span></a>
</li>
<li><span class='sectionRange'>81 to 86 - </span><a href="#h-35648"><span class="HLabel1">PART VII</span> - <span class="HTitleText1">Aviation Fuel Tax Rebate</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-35650"><span class="HLabel1">PART VIII</span> - <span class="HTitleText1">Fuel Measurement</span></a>
</li>
<li><span class='sectionRange'>88 to 91 - </span><a href="#h-35652"><span class="HLabel1">PART IX</span> - <span class="HTitleText1">Employment Insurance</span></a>
</li>
<li><span class='sectionRange'>92 and 93 - </span><a href="#h-35654"><span class="HLabel1">PART X</span> - <span class="HTitleText1">Amendments to Other Acts</span></a>
</li>
<li><span class='sectionRange'>94 - </span><a href="#h-35656"><span class="HLabel1">PART XI</span> - <span class="HTitleText1">Payment to the Canada Foundation for Innovation</span></a>
</li></ul>
</li></ul>

</nav>

