<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Canada Marine Act</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Short Title</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Interpretation</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Aboriginal Rights</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Purpose</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HLabel1">PART 1</span> - <span class="HTitleText1">Canada Port Authorities</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="#h-7"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="#h-8"><span class="HTitleText2">Agent of Her Majesty</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-9"><span class="HTitleText2">Incorporation</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="#h-10"><span class="HTitleText2">Continuance of Harbour Commissions</span></a>
</li>
<li><span class='sectionRange'>12 - </span><a href="#h-11"><span class="HTitleText2">Initial Port Authorities</span></a>
</li>
<li><span class='sectionRange'>13.1 - </span><a href="#h-12"><span class="HTitleText2">Amalgamation of Port Authorities</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-13"><span class="HTitleText2">Directors</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="#h-14"><span class="HTitleText2">Legal Regime Applicable to Port Authorities</span></a>
</li>
<li><span class='sectionRange'>28 - </span><a href="#h-15"><span class="HTitleText2">Capacity and Powers</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-16"><span class="HTitleText2">Annual Meeting</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-17"><span class="HTitleText2">Financial Management</span></a>
</li>
<li><span class='sectionRange'>41 - </span><a href="#h-18"><span class="HTitleText2">Special Examinations</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-19"><span class="HTitleText2">Property</span></a>
</li>
<li><span class='sectionRange'>49 - </span><a href="#h-20"><span class="HTitleText2">Fees</span></a>
</li>
<li><span class='sectionRange'>54 - </span><a href="#h-21"><span class="HTitleText2">Official Languages</span></a>
</li>
<li><span class='sectionRange'>55 - </span><a href="#h-22"><span class="HTitleText2">Liquidation and Dissolution</span></a>
</li>
<li><span class='sectionRange'>56 - </span><a href="#h-23"><span class="HTitleText2">Port Traffic Control</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-24"><span class="HTitleText2">Order and Safety</span></a>
</li>
<li><span class='sectionRange'>62 - </span><a href="#h-25"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>64.1 - </span><a href="#h-26"><span class="HTitleText2">Undertakings Situated in a Port</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>64.1 - </span><a href="#h-27"><span class="HTitleText3">Regulations</span></a>
</li>
<li><span class='sectionRange'>64.6 - </span><a href="#h-28"><span class="HTitleText3">Agreements</span></a>
</li>
<li><span class='sectionRange'>64.7 - </span><a href="#h-29"><span class="HTitleText3">Other Acts</span></a>
</li>
<li><span class='sectionRange'>64.92 - </span><a href="#h-30"><span class="HTitleText3">Limits on Liability, Defences and Immunities</span></a>
</li></ul>
</li></ul>
</li><li><span class='sectionRange'>65 - </span><a href="#h-31"><span class="HLabel1">PART 2</span> - <span class="HTitleText1">Public Ports</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>65 - </span><a href="#h-32"><span class="HTitleText2">Designation by Governor in Council</span></a>
</li>
<li><span class='sectionRange'>67 - </span><a href="#h-33"><span class="HTitleText2">Fees</span></a>
</li>
<li><span class='sectionRange'>69 - </span><a href="#h-34"><span class="HTitleText2">Harbour Masters and Wharfingers</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-35"><span class="HTitleText2">Agreements</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-36"><span class="HTitleText2">Federal Real Property and Federal Immovables</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-37"><span class="HTitleText2">General</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-38"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>76 - </span><a href="#h-39"><span class="HTitleText2">Traffic Control</span></a>
</li></ul>
</li><li><span class='sectionRange'>77 - </span><a href="#h-40"><span class="HLabel1">PART 3</span> - <span class="HTitleText1">Seaway</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>77 - </span><a href="#h-41"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>78 - </span><a href="#h-42"><span class="HTitleText2">Objectives</span></a>
</li>
<li><span class='sectionRange'>79 - </span><a href="#h-43"><span class="HTitleText2">Powers of Minister</span></a>
</li>
<li><span class='sectionRange'>83 - </span><a href="#h-44"><span class="HTitleText2">Annual Meeting</span></a>
</li>
<li><span class='sectionRange'>84 - </span><a href="#h-45"><span class="HTitleText2">Financial Management</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-46"><span class="HTitleText2">Special Examinations</span></a>
</li>
<li><span class='sectionRange'>90 - </span><a href="#h-47"><span class="HTitleText2">Property</span></a>
</li>
<li><span class='sectionRange'>92 - </span><a href="#h-48"><span class="HTitleText2">Fees</span></a>
</li>
<li><span class='sectionRange'>95 - </span><a href="#h-49"><span class="HTitleText2">Official Languages Act</span></a>
</li>
<li><span class='sectionRange'>96 - </span><a href="#h-50"><span class="HTitleText2">Dissolution</span></a>
</li>
<li><span class='sectionRange'>98 - </span><a href="#h-51"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>99 - </span><a href="#h-52"><span class="HTitleText2">Traffic Control</span></a>
</li>
<li><span class='sectionRange'>100 - </span><a href="#h-53"><span class="HTitleText2">General</span></a>
</li></ul>
</li><li><span class='sectionRange'>103 - </span><a href="#h-54"><span class="HLabel1">PART 4</span> - <span class="HTitleText1">Regulations and Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>103 - </span><a href="#h-55"><span class="HTitleText2">Interpretation</span></a>
</li>
<li><span class='sectionRange'>104 - </span><a href="#h-56"><span class="HTitleText2">Regulations</span></a>
</li>
<li><span class='sectionRange'>106 - </span><a href="#h-57"><span class="HTitleText2">Traffic Control</span></a>
</li>
<li><span class='sectionRange'>107 - </span><a href="#h-58"><span class="HTitleText2">Liability for Fees</span></a>
</li>
<li><span class='sectionRange'>108 - </span><a href="#h-59"><span class="HTitleText2">Enforcement</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>108 - </span><a href="#h-60"><span class="HTitleText3">Designation</span></a>
</li>
<li><span class='sectionRange'>109 - </span><a href="#h-61"><span class="HTitleText3">Inspection</span></a>
</li>
<li><span class='sectionRange'>111 - </span><a href="#h-62"><span class="HTitleText3">Search and Seizure</span></a>
</li>
<li><span class='sectionRange'>115 - </span><a href="#h-63"><span class="HTitleText3">Detention of Ships</span></a>
</li></ul>
</li><li><span class='sectionRange'>121 - </span><a href="#h-64"><span class="HTitleText2">Other Powers</span></a>
</li>
<li><span class='sectionRange'>126 - </span><a href="#h-65"><span class="HTitleText2">Offences and Punishment</span></a>
</li>
<li><span class='sectionRange'>129.01 - </span><a href="#h-66"><span class="HTitleText2">Administrative Monetary Penalties</span></a>
</li>
<li><span class='sectionRange'>129.18 - </span><a href="#h-67"><span class="HTitleText2">General Provisions</span></a>
</li></ul>
</li><li><span class='sectionRange'>130 - </span><a href="#h-68"><span class="HLabel1">PART 5</span> - <span class="HTitleText1">Human Resources</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>130 - </span><a href="#h-69"><span class="HTitleText2">Seaway</span></a>
</li>
<li><span class='sectionRange'>132 - </span><a href="#h-70"><span class="HTitleText2">Local Port Corporations</span></a>
</li>
<li><span class='sectionRange'>133 - </span><a href="#h-71"><span class="HTitleText2">Harbour Commissions</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-72"><span class="HTitleText2">Non-corporate Ports of Canada Ports Corporation</span></a>
</li>
<li><span class='sectionRange'>138.1 - </span><a href="#h-73"><span class="HTitleText2">Comparable Employee Benefits</span></a>
</li></ul>
</li><li><span class='sectionRange'>139 - </span><a href="#h-74"><span class="HLabel1">PART 6</span> - <span class="HTitleText1">Miscellaneous</span></a>
</li>
<li><span class='sectionRange'>145 to 158 - </span><a href="#h-75"><span class="HLabel1">PART 7</span> - <span class="HTitleText1">Amendments to the Pilotage Act</span></a>
</li>
<li><span class='sectionRange'>159 to 196 - </span><a href="#h-76"><span class="HLabel1">PART 8</span> - <span class="HTitleText1">Consequential Amendments, Repeals and Coming into Force</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>159 to 196 - </span><a href="#h-77"><span class="HTitleText2">Consequential Amendments</span></a>
</li>
<li><span class='sectionRange'>197 to 204.1 - </span><a href="#h-78"><span class="HTitleText2">Repeals</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-79"><span class="HTitleText2">Coming into Force</span></a>
</li></ul>
</li><li><a href="#h-80"><span class="scheduleLabel">SCHEDULE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
