<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les Indiens</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Administration</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HTitleText1">Application de la loi</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-5"><span class="HTitleText1">Définition et enregistrement des indiens</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Registre des Indiens</span></a>
</li>
<li><span class='sectionRange'>8 - </span><a href="#h-7"><span class="HTitleText2">Listes de bande</span></a>
</li>
<li><span class='sectionRange'>14 - </span><a href="#h-8"><span class="HTitleText2">Affichage des listes de bande</span></a>
</li>
<li><span class='sectionRange'>14.1 - </span><a href="#h-9"><span class="HTitleText2">Demandes</span></a>
</li>
<li><span class='sectionRange'>14.2 - </span><a href="#h-10"><span class="HTitleText2">Protestations</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-11"><span class="HTitleText2">Paiements aux personnes qui cessent d’être membres d’une bande</span></a>
</li>
<li><span class='sectionRange'>17 - </span><a href="#h-12"><span class="HTitleText2">Nouvelles bandes</span></a>
</li></ul>
</li><li><span class='sectionRange'>18 - </span><a href="#h-13"><span class="HTitleText1">Réserves</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-14"><span class="HTitleText1">Possession de terres dans des réserves</span></a>
</li>
<li><span class='sectionRange'>30 - </span><a href="#h-15"><span class="HTitleText1">Violation du droit de propriété dans les réserves</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-16"><span class="HTitleText1">Vente ou troc de produits</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-17"><span class="HTitleText1">Routes et ponts</span></a>
</li>
<li><span class='sectionRange'>35 - </span><a href="#h-18"><span class="HTitleText1">Terres prises pour cause d’utilité publique</span></a>
</li>
<li><span class='sectionRange'>36 - </span><a href="#h-19"><span class="HTitleText1">Réserves spéciales</span></a>
</li>
<li><span class='sectionRange'>37 - </span><a href="#h-20"><span class="HTitleText1">Cession et désignation</span></a>
</li>
<li><span class='sectionRange'>42 - </span><a href="#h-21"><span class="HTitleText1">Transmission de biens par droit de succession</span></a>
</li>
<li><span class='sectionRange'>45 - </span><a href="#h-22"><span class="HTitleText1">Testaments</span></a>
</li>
<li><span class='sectionRange'>47 - </span><a href="#h-23"><span class="HTitleText1">Appels</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-24"><span class="HTitleText1">Distribution des biens ab intestat</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-25"><span class="HTitleText1">Indiens mentalement incapables</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-26"><span class="HTitleText1">Tutelle</span></a>
</li>
<li><span class='sectionRange'>52.1 - </span><a href="#h-27"><span class="HTitleText1">Fonds des mineurs</span></a>
</li>
<li><span class='sectionRange'>53 - </span><a href="#h-28"><span class="HTitleText1">Administration des réserves et des terres cédées ou désignées</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-29"><span class="HTitleText1">Administration de l’argent des indiens</span></a>
</li>
<li><span class='sectionRange'>70 - </span><a href="#h-30"><span class="HTitleText1">Prêts aux indiens</span></a>
</li>
<li><span class='sectionRange'>71 - </span><a href="#h-31"><span class="HTitleText1">Fermes</span></a>
</li>
<li><span class='sectionRange'>72 - </span><a href="#h-32"><span class="HTitleText1">Sommes payables en vertu d’un traité</span></a>
</li>
<li><span class='sectionRange'>73 - </span><a href="#h-33"><span class="HTitleText1">Règlements</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-34"><span class="HTitleText1">Élection des chefs et des conseils de bande</span></a>
</li>
<li><span class='sectionRange'>81 - </span><a href="#h-35"><span class="HTitleText1">Pouvoirs du conseil</span></a>
</li>
<li><span class='sectionRange'>87 - </span><a href="#h-36"><span class="HTitleText1">Taxation</span></a>
</li>
<li><span class='sectionRange'>88 - </span><a href="#h-37"><span class="HTitleText1">Droits légaux</span></a>
</li>
<li><span class='sectionRange'>91 - </span><a href="#h-38"><span class="HTitleText1">Commerce avec les indiens</span></a>
</li>
<li><span class='sectionRange'>93 - </span><a href="#h-39"><span class="HTitleText1">Enlèvement d’objets sur les réserves</span></a>
</li>
<li><span class='sectionRange'>94 à 100 - </span><a href="#h-40"><span class="HTitleText1">Infractions, peines et contrôle d’application</span></a>
</li>
<li><span class='sectionRange'>109 à 113 - </span><a href="#h-41"><span class="HTitleText1">Émancipation</span></a>
</li>
<li><span class='sectionRange'>114 - </span><a href="#h-42"><span class="HTitleText1">Écoles</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
