<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’interprétation des conventions en matière d’impôts sur le revenu</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-323258"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-323263"><span class="HTitleText1">Définition</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-323268"><span class="HTitleText1">Interprétation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-323366"><span class="HTitleText1">Application</span></a>
</li></ul>
</li></ul>

</nav>

