<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur l’aéronautique</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HTitleText1">Sa Majesté</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-3"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-4"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Aéronautique</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Champ d’application</span></a>
</li>
<li><span class='sectionRange'>4.2 - </span><a href="#h-6"><span class="HTitleText2">Attributions du ministre</span></a>
</li>
<li><span class='sectionRange'>4.4 - </span><a href="#h-7"><span class="HTitleText2">Redevances</span></a>
</li>
<li><span class='sectionRange'>4.7 - </span><a href="#h-8"><span class="HTitleText2">Sûreté aérienne</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>4.7 - </span><a href="#h-9"><span class="HTitleText3">Définitions</span></a>
</li>
<li><span class='sectionRange'>4.71 - </span><a href="#h-10"><span class="HTitleText3">Règlements sur la sûreté aérienne</span></a>
</li>
<li><span class='sectionRange'>4.72 - </span><a href="#h-11"><span class="HTitleText3">Mesures de sûreté</span></a>
</li>
<li><span class='sectionRange'>4.75 - </span><a href="#h-12"><span class="HTitleText3">Exigences relatives aux aéronefs étrangers</span></a>
</li>
<li><span class='sectionRange'>4.76 - </span><a href="#h-13"><span class="HTitleText3">Directives d’urgence</span></a>
</li>
<li><span class='sectionRange'>4.79 - </span><a href="#h-14"><span class="HTitleText3">Communications illicites</span></a>
</li>
<li><span class='sectionRange'>4.8 - </span><a href="#h-15"><span class="HTitleText3">Habilitations de sécurité</span></a>
</li>
<li><span class='sectionRange'>4.81 - </span><a href="#h-16"><span class="HTitleText3">Fourniture de renseignements</span></a>
</li>
<li><span class='sectionRange'>4.84 - </span><a href="#h-17"><span class="HTitleText3">Contrôles</span></a>
</li>
<li><span class='sectionRange'>4.86 - </span><a href="#h-18"><span class="HTitleText3">Contrôle des transporteurs aériens et aérodromes</span></a>
</li>
<li><span class='sectionRange'>4.87 - </span><a href="#h-19"><span class="HTitleText3">Contrôle d’observation et d’efficacité</span></a>
</li></ul>
</li><li><span class='sectionRange'>4.9 - </span><a href="#h-20"><span class="HTitleText2">Dispositions réglementaires générales</span></a>
</li>
<li><span class='sectionRange'>5.4 - </span><a href="#h-21"><span class="HTitleText2">Zonage des aéroports</span></a>
</li>
<li><span class='sectionRange'>5.9 - </span><a href="#h-22"><span class="HTitleText2">Dispositions générales concernant les règlements, arrêtés, etc.</span></a>
</li>
<li><span class='sectionRange'>6.3 - </span><a href="#h-23"><span class="HTitleText2">Commissions d’enquête</span></a>
</li>
<li><span class='sectionRange'>6.41 - </span><a href="#h-24"><span class="HTitleText2">Arrêtés d’urgence</span></a>
</li>
<li><span class='sectionRange'>6.5 - </span><a href="#h-25"><span class="HTitleText2">Renseignements médicaux et optométriques</span></a>
</li>
<li><span class='sectionRange'>6.6 - </span><a href="#h-26"><span class="HTitleText2">Mesures relatives aux documents d’aviation canadiens</span></a>
</li>
<li><span class='sectionRange'>7.3 - </span><a href="#h-27"><span class="HTitleText2">Interdictions, infractions et peines</span></a>
</li>
<li><span class='sectionRange'>7.6 - </span><a href="#h-28"><span class="HTitleText2">Procédure relative à certaines  contraventions</span></a>
</li>
<li><span class='sectionRange'>8.4 - </span><a href="#h-29"><span class="HTitleText2">Mesures de contrainte</span></a>
</li>
<li><span class='sectionRange'>9 - </span><a href="#h-30"><span class="HTitleText2">Dispositions générales</span></a>
</li></ul>
</li><li><span class='sectionRange'>25 - </span><a href="#h-31"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">[Abrogée, L.R. (1985), ch. 28 (3e suppl.), art. 276]</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-32"><span class="HLabel1">PARTIE III</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>25 - </span><a href="#h-33"><span class="HTitleText2">Personnel</span></a>
</li>
<li><span class='sectionRange'>26 - </span><a href="#h-34"><span class="HTitleText2">Poursuites</span></a>
</li></ul>
</li><li><span class='sectionRange'>29 - </span><a href="#h-35"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">[Abrogée, 2001, ch. 29, art. 44]</span></a>
</li>
<li><a href="#h-8800"><span class="scheduleLabel">ANNEXE</span> </a>
</li></ul>
</li></ul>

</nav>
</div></section>
