<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table of Contents</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Indian Reserves of Nova Scotia Act</a><ul class="TocIndent"><li><a href="#h-333158"><span class="scheduleLabel">SCHEDULE</span> - <span class="scheduleTitleText"> - </span> - <span class="scheduleTitleText"> - Memorandum of Agreement made this 14th Day of April, 1959</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
