<nav>
<ul class="TocIndent">
<li><a title="Page 1" href="page-1.html">
Loi sur l’exploitation du champ Hibernia</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="page-1.html#h-247861"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="page-1.html#h-247864"><span class="HTitleText1">Définitions</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="page-1.html#h-247888"><span class="HTitleText1">Accords</span></a>
</li>
<li><span class='sectionRange'>6 - </span><a href="page-1.html#h-247924"><span class="HTitleText1">Homologation</span></a>
</li>
<li><span class='sectionRange'>7 - </span><a href="page-1.html#h-247932"><span class="HTitleText1">Application des lois fédérales et provinciales</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>7 - </span><a href="page-1.html#h-247933"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>10 - </span><a href="page-2.html#h-247956"><span class="HTitleText2">Compétence des tribunaux</span></a>
</li>
<li><span class='sectionRange'>11 - </span><a href="page-2.html#h-247966"><span class="HTitleText2">Dispositions générales</span></a>
</li>
<li><span class='sectionRange'>11.1 - </span><a href="page-2.html#h-247969"><span class="HTitleText2">Incompatibilité</span></a>
</li></ul>
</li><li><span class='sectionRange'>12 à 21 - </span><a href="page-2.html#h-247974"><span class="HTitleText1">Modifications corrélatives</span></a>
</li>
<li><span class='sectionRange'>22 - </span><a href="page-2.html#h-247976"><span class="HTitleText1">Disposition transitoire</span></a>
</li>
<li><span class='sectionRange'>23 - </span><a href="page-2.html#h-247978"><span class="HTitleText1">Entrée en vigueur</span></a>
</li></ul>
</li></ul>

</nav>

