<section id="right-panel" class="wb-overlay modal-content overlay-def wb-panel-l"><header class="modal-header">
<h2 class="modal-title">Table des matières</h2></header><div class="modal-body"><nav>
<ul class="TocIndent">
<li><a title="Page 1" href="#">
Loi sur les corporations canadiennes</a><ul class="TocIndent"><li><span class='sectionRange'>1 - </span><a href="#h-1"><span class="HTitleText1">Titre abrégé</span></a>
</li>
<li><span class='sectionRange'>2 - </span><a href="#h-2"><span class="HLabel1">PARTIE I</span> - <span class="HTitleText1">Compagnies par actions</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>2 - </span><a href="#h-3"><span class="HTitleText2">Application de la présente Partie</span></a>
</li>
<li><span class='sectionRange'>3 - </span><a href="#h-4"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>4 - </span><a href="#h-5"><span class="HTitleText2">Préliminaires</span></a>
</li>
<li><span class='sectionRange'>5 - </span><a href="#h-6"><span class="HTitleText2">Formation de nouvelles compagnies</span></a>
</li>
<li><span class='sectionRange'>15 - </span><a href="#h-7"><span class="HTitleText2">Pouvoirs et devoirs généraux des compagnies</span></a>
</li>
<li><span class='sectionRange'>20 - </span><a href="#h-8"><span class="HTitleText2">Changement des dispositions des lettres patentes</span></a>
</li>
<li><span class='sectionRange'>21 - </span><a href="#h-9"><span class="HTitleText2">Contrats, etc.</span></a>
</li>
<li><span class='sectionRange'>24 - </span><a href="#h-10"><span class="HTitleText2">Siège</span></a>
</li>
<li><span class='sectionRange'>25 - </span><a href="#h-11"><span class="HTitleText2">Nom de la compagnie</span></a>
</li>
<li><span class='sectionRange'>31 - </span><a href="#h-12"><span class="HTitleText2">Déchéance de la charte</span></a>
</li>
<li><span class='sectionRange'>32 - </span><a href="#h-13"><span class="HTitleText2">Abandon de la charte</span></a>
</li>
<li><span class='sectionRange'>34 - </span><a href="#h-14"><span class="HTitleText2">Actions</span></a>
</li>
<li><span class='sectionRange'>39 - </span><a href="#h-15"><span class="HTitleText2">Transfert d’actions</span></a>
</li>
<li><span class='sectionRange'>44 - </span><a href="#h-16"><span class="HTitleText2">Appels de versements</span></a>
</li>
<li><span class='sectionRange'>48 - </span><a href="#h-17"><span class="HTitleText2">Responsabilité des actionnaires</span></a>
</li>
<li><span class='sectionRange'>51 - </span><a href="#h-18"><span class="HTitleText2">Modification du capital-actions</span></a>
</li>
<li><span class='sectionRange'>52 - </span><a href="#h-19"><span class="HTitleText2">Réduction du capital</span></a>
</li>
<li><span class='sectionRange'>61 - </span><a href="#h-20"><span class="HTitleText2">Actions privilégiées et actions portant des droits spéciaux</span></a>
</li>
<li><span class='sectionRange'>65 - </span><a href="#h-21"><span class="HTitleText2">Pouvoirs d’emprunter</span></a>
</li>
<li><span class='sectionRange'>68 - </span><a href="#h-22"><span class="HTitleText2">Renseignements sur les hypothèques et charges</span></a>
</li>
<li><span class='sectionRange'>74 - </span><a href="#h-23"><span class="HTitleText2">Prospectus et offres au public</span></a>
</li>
<li><span class='sectionRange'>85 - </span><a href="#h-24"><span class="HTitleText2">Dividendes</span></a>
</li>
<li><span class='sectionRange'>86 - </span><a href="#h-25"><span class="HTitleText2">Administrateurs</span></a>
</li>
<li><span class='sectionRange'>102 - </span><a href="#h-26"><span class="HTitleText2">Assemblées des actionnaires</span></a>
</li></ul>
</li><li><span class='sectionRange'>108.1 - </span><a href="#h-27"><span class="HTitleText1">Procurations et sollicitations de procurations</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>109 - </span><a href="#h-28"><span class="HTitleText2">Registre</span></a>
</li>
<li><span class='sectionRange'>117 - </span><a href="#h-29"><span class="HTitleText2">Comptes et vérifications</span></a>
</li>
<li><span class='sectionRange'>134 - </span><a href="#h-30"><span class="HTitleText2">Arrangements et compromis</span></a>
</li>
<li><span class='sectionRange'>135.1 - </span><a href="#h-31"><span class="HTitleText2">Offres visant à la prise de contrôle</span></a>
</li>
<li><span class='sectionRange'>137 - </span><a href="#h-32"><span class="HTitleText2">Fusion</span></a>
</li>
<li><span class='sectionRange'>138 - </span><a href="#h-33"><span class="HTitleText2">Preuve</span></a>
</li>
<li><span class='sectionRange'>144 - </span><a href="#h-34"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>149 - </span><a href="#h-35"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>151 - </span><a href="#h-36"><span class="HTitleText2">Droits et règlements</span></a>
</li></ul>
</li><li><span class='sectionRange'>153 - </span><a href="#h-37"><span class="HLabel1">PARTIE II</span> - <span class="HTitleText1">Corporations sans capital-actions</span></a>
</li>
<li><span class='sectionRange'>158 - </span><a href="#h-38"><span class="HLabel1">PARTIE III</span> - <span class="HTitleText1">Compagnies constituées en corporations par Loi spéciale</span></a>
</li>
<li><span class='sectionRange'>160 - </span><a href="#h-39"><span class="HLabel1">PARTIE IV</span> - <span class="HTitleText1">Clauses des compagnies</span></a>
<ul class="TocIndent"><li>
<span class='sectionRange'>160 - </span><a href="#h-40"><span class="HTitleText2">Interprétation</span></a>
</li>
<li><span class='sectionRange'>161 - </span><a href="#h-41"><span class="HTitleText2">Application</span></a>
</li>
<li><span class='sectionRange'>163 - </span><a href="#h-42"><span class="HTitleText2">Pouvoirs généraux</span></a>
</li>
<li><span class='sectionRange'>165 - </span><a href="#h-43"><span class="HTitleText2">Administrateurs — leurs fonctions et attributions</span></a>
</li>
<li><span class='sectionRange'>172 - </span><a href="#h-44"><span class="HTitleText2">Statuts</span></a>
</li>
<li><span class='sectionRange'>176 - </span><a href="#h-45"><span class="HTitleText2">Capital social et appels de versements</span></a>
</li>
<li><span class='sectionRange'>182 - </span><a href="#h-46"><span class="HTitleText2">Registres de la compagnie</span></a>
</li>
<li><span class='sectionRange'>186 - </span><a href="#h-47"><span class="HTitleText2">Infractions et peines</span></a>
</li>
<li><span class='sectionRange'>188 - </span><a href="#h-48"><span class="HTitleText2">Responsabilité des actionnaires</span></a>
</li>
<li><span class='sectionRange'>191 - </span><a href="#h-49"><span class="HTitleText2">Assemblées et vote</span></a>
</li>
<li><span class='sectionRange'>196 - </span><a href="#h-50"><span class="HTitleText2">Actions privilégiées</span></a>
</li>
<li><span class='sectionRange'>198 - </span><a href="#h-51"><span class="HTitleText2">Contrats</span></a>
</li>
<li><span class='sectionRange'>199 - </span><a href="#h-52"><span class="HTitleText2">Fiducies</span></a>
</li>
<li><span class='sectionRange'>200 - </span><a href="#h-53"><span class="HTitleText2">Responsabilité des administrateurs</span></a>
</li>
<li><span class='sectionRange'>205 - </span><a href="#h-54"><span class="HTitleText2">Emploi des fonds</span></a>
</li>
<li><span class='sectionRange'>207 - </span><a href="#h-55"><span class="HTitleText2">Procédure</span></a>
</li>
<li><span class='sectionRange'>212 - </span><a href="#h-56"><span class="HTitleText2">Preuve</span></a>
</li></ul>
</li><li><span class='sectionRange'>215 - </span><a href="#h-57"><span class="HLabel1">PARTIE V</span> - <span class="HTitleText1">Pouvoirs afférents aux corps constitués, créés autrement que par lettres patentes</span></a>
</li>
<li><span class='sectionRange'>217 - </span><a href="#h-58"><span class="HLabel1">PARTIE VI</span> - <span class="HTitleText1">Dispositions d’application générale</span></a>
</li>
<li><a href="#h-59"><span class="scheduleLabel">ANNEXE</span> - <span class="scheduleTitleText"> - Dispositions spéciales applicables aux compagnies par actions à participation restreinte</span></a>
</li></ul>
</li></ul>

</nav>
</div></section>
